### ISSUE TITLE
Generate list of contributions for org membership

### ISSUE THREAD

**Issue by nikhita** [kubernetes/org#10]
We ask for a list of contributions in the org membership template. The list includes PRs reviewed, authored or issues created (but not limited to it). It would be nice to automate and generate this list.

There was a discussion related to this before: https://github.com/kubernetes/community/issues/874. Creating an issue here instead because having the script in this repo would be make more sense IMO.

PS: I had written something quick for this a long time back - https://github.com/nikhita/github-contrib.

/cc @cblecker @fejta @spiffxp @justaugustus 
/kind feature

**Comment by idvoretskyi** [comment]
cc

**Comment by fejta** [comment]
Adapting Nikhitas repo into a prow plugin that listens for issue created events seems like a good approach for this. 

See https://github.com/kubernetes/test-infra/blob/master/prow/plugins/requiresig/requiresig.go for something similar

**Comment by cblecker** [comment]
I'm wondering if this is necessary though. Issues that are highlighted should be representative of a contributors work, rather than just a list of all PRs. Trivial fixes aren't considered representative.

**Comment by yue9944882** [comment]
> Issues that are highlighted should be representative of a contributors work, rather than just a list of all PRs. 

can't agree more. involving issues, providing support, help digging into problems are all important for estimating a contributor's involvement in the community, not only counting pulls ( this might also help reducing trival pulls 🙃).

**Comment by nikhita** [comment]
> can't agree more. involving issues, providing support, help digging into problems are all important for estimating a contributor's involvement in the community, not only counting pulls

Sgtm, closing this.

We can get to this if we find that we really do need this in the future.

/close
