### ISSUE TITLE
REQUEST: New membership for JamieRachel

### ISSUE THREAD

**Issue by JamieRachel** [kubernetes/org#1002]
### GitHub Username
(at)JamieRachel

### Organization you are requesting membership in
(at)kubernetes & (at) kubernetes/community

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- (at)ParisPittman
- (at)MrBobbytables

### List of contributions to the Kubernetes project: 
Contributor Summit - I will need to set issues and triage as a project manager
Current issues that I have set include: 
3867
3865
3866

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by mrbobbytables** [comment]
+1 from me :) Jamie will be helping with the contributor summits.

**Comment by parispittman** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @JamieRachel, thank you for all your contributions so far :)

I've created PR #1007 to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
