### ISSUE TITLE
REQUEST: New membership for sbueringer

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/org#1004]
### GitHub Username
@sbueringer

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @chrigl 
- @jichenjc

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/383
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/388
  - https://github.com/kubernetes-sigs/controller-runtime/pull/489

- SIG projects I am involved with:
  - Cluster API Provider OpenStack

**Comment by jichenjc** [comment]
+1 to me ~

**Comment by chrigl** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @sbueringer, thank you for all your contributions so far :)

I've created PR #1007 to add you to the kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
