### ISSUE TITLE
REQUEST: New membership for openstacker

### ISSUE THREAD

**Issue by openstacker** [kubernetes/org#1008]
### GitHub Username
openstacker

### Organization you are requesting membership in
@kubernetes @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lingxiankong
- @dims 
- @jichenjc 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/cloud-provider-openstack/pull/167
  https://github.com/kubernetes/cloud-provider-openstack/pull/168
  https://github.com/kubernetes/cloud-provider-openstack/pull/171

- Issues responded to
  https://github.com/kubernetes/autoscaler/issues/1716
  https://github.com/kubernetes/kubernetes/issues/72949
  https://github.com/kubernetes/autoscaler/pull/1873
  https://github.com/kubernetes/cloud-provider-openstack/issues/195

- SIG projects I am involved with
  SIG-OpenStack

**Comment by jichenjc** [comment]
+1 to me

**Comment by lingxiankong** [comment]
+1 from me, welcome!

**Comment by dims** [comment]
+1 from me!

**Comment by nzoueidi** [comment]
Hey there @openstacker, thank you for all your contributions so far :)

I've created PR #1011 to add you to the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
