### ISSUE TITLE
REQUEST: New membership for thandayuthapani

### ISSUE THREAD

**Issue by thandayuthapani** [kubernetes/org#1010]
### GitHub Username
@thandayuthapani
### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @k82cn 
- @hex108 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
https://github.com/kubernetes-sigs/kube-batch

**Comment by hex108** [comment]
+1

Thanks for the contribution!

**Comment by k82cn** [comment]
*1

**Comment by nzoueidi** [comment]
Hey there @thandayuthapani, thank you for all your contributions so far :)

I've created PR #1008 to add you to the kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by thandayuthapani** [comment]
Thanks all!!
