### ISSUE TITLE
REQUEST: New membership for runyontr

### ISSUE THREAD

**Issue by runyontr** [kubernetes/org#1014]
### GitHub Username
@runyontr

### Organization you are requesting membership in
@kubernetes-sigs
@wg-multitenancy 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rjbez17 
- @srampal
- @tashimi

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pull/74452
* Issues responded to
   https://github.com/kubernetes-sigs/kubebuilder/issues/675#issuecomment-490875729
   https://github.com/kubernetes/kubernetes/issues/64333
* SIG projects I am involved with
   SIG-Apps
   SIG-Auth (WG-Multitenancy)

**Comment by tashimi** [comment]
/approve 

![tenor-231525071](https://user-images.githubusercontent.com/719646/61400207-a3470200-a884-11e9-9e09-1a0ae34405c3.gif)

**Comment by dims** [comment]
+1 from me

**Comment by nzoueidi** [comment]
Hey there @runyontr, thank you for all your contributions so far :)

I've created PR #1017  to add you to the kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by nzoueidi** [comment]
Hey @runyontr can you please find another non-VMware sponsor? Sponsors for org membership should be from different companies.
https://github.com/kubernetes/community/blob/master/community-membership.md#requirements
Thanks.

**Comment by runyontr** [comment]
@nzoueidi I'll ask some contacts and get back to you.

**Comment by rjbez17** [comment]
+1

**Comment by mrbobbytables** [comment]
@runyontr unfortunately @rjbez17 cannot sponsor you for org membership. a Sponsor must be an approver or reviewer in an owners file within @kubernetes or the org you're applying membership to. For more information, please see the [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

**Comment by tashimi** [comment]
@rjbez17 is now on the owners page for the multi-tenancy repo, which he should have been previously as he's a highly engaged contributor

**Comment by srampal** [comment]
+1
