### ISSUE TITLE
Retire `kubernetes-sigs/kubeadm-dind-cluster`

### ISSUE THREAD

**Issue by timothysc** [kubernetes/org#1016]
### Repository to retire
Please move https://github.com/kubernetes-sigs/kubeadm-dind-cluster to the retired org.  

### Repository and/or sig subproject owners that are approving this archival
e.g. sig-cluster-lifecycle

### When should this be done
e.g. Anytime.

### Additional context for request
We are deprecating this solution in favor of KIND. 
Many thanks to the folks who blazed the trail, and to those who built a new one! 

/cc @ivan4th @luxas @BenTheElder @justinsb

**Comment by cblecker** [comment]
To whoever picks this up: Please ensure the full procedure in https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#removing-repositories is followed

**Comment by mrbobbytables** [comment]
I'll take care of it :)

/assign

**Comment by timothysc** [comment]
Please hold on final ok from @ivan4th gives the thumbs up.

**Comment by nikhita** [comment]
/assign @ivan4th 
for final confirmation

**Comment by ivan4th** [comment]
Outstanding PRs merged to ease the transition (to kind) for those who are still using the project, deprecation notice adding to README.md. Please move kubeadm-dind-cluster to its final resting place. Thanks!

**Comment by mrbobbytables** [comment]
Thanks for ack'ing @ivan4th :) I'll go ahead and take care of it.

**Comment by mrbobbytables** [comment]
All owners removed, open issues/PRs closed and repo migrated to: 
https://github.com/kubernetes-retired/kubeadm-dind-cluster

Project removed from sigs.yaml:
https://github.com/kubernetes/community/pull/3932

Notice sent to k-dev:
https://groups.google.com/forum/#!topic/kubernetes-dev/8Do25FgTYTs

With that, should be safe to close :) 
If there is anything else, just let me know!

/close
