### ISSUE TITLE
REQUEST: New membership for klueska

### ISSUE THREAD

**Issue by klueska** [kubernetes/org#1018]
### GitHub Username
@klueska

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ConnorDoyle 
- @derekwaynecarr 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

Authored:
https://github.com/kubernetes/kubernetes/pull/78516
https://github.com/kubernetes/kubernetes/pull/78515
https://github.com/kubernetes/kubernetes/pull/77162
https://github.com/kubernetes/kubernetes/pull/80301
https://github.com/kubernetes/kubernetes/pull/80294
https://github.com/kubernetes/kubernetes/pull/78762
https://github.com/kubernetes/enhancements/pull/1120
https://github.com/kubernetes/enhancements/pull/1121
https://github.com/kubernetes/enhancements/pull/1131

Co-Authored:
https://github.com/kubernetes/kubernetes/pull/73580

Reviewed:
https://github.com/kubernetes/kubernetes/pull/78587
https://github.com/kubernetes/kubernetes/pull/72885
https://github.com/kubernetes/kubernetes/pull/73589
https://github.com/kubernetes/kubernetes/pull/72913
https://github.com/kubernetes/kubernetes/pull/73920
https://github.com/kubernetes/kubernetes/pull/74345
https://github.com/kubernetes/kubernetes/pull/74357
https://github.com/kubernetes/kubernetes/pull/74423
https://github.com/kubernetes/kubernetes/pull/74411

- Issues responded to
https://github.com/kubernetes/enhancements/issues/693

- SIG projects I am involved with
`sig-node`

**Comment by ConnorDoyle** [comment]
Wholehearted +1 👍

**Comment by derekwaynecarr** [comment]
about time!

+1

**Comment by nzoueidi** [comment]
Hey there @klueska, thank you for all your contributions so far :)

I've created PR #1019 to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
