### ISSUE TITLE
REQUEST: New membership for vincepri

### ISSUE THREAD

**Issue by vincepri** [kubernetes/org#102]
### GitHub Username
@vincepri

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timothysc 
- @dims  

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/90
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/86
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/82
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/77
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/76
  * https://github.com/kubernetes/website/pull/10186
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/68
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/25
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/74
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/81
- Issues responded to
  * https://github.com/kubernetes/kubeadm/issues/1086
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/89
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/88
- SIG projects I am involved with
  * cluster-lifecycle

**Comment by timothysc** [comment]
+1 from me.

**Comment by cblecker** [comment]
@vincepri Both of your sponsors are from the same company. Unfortunately, this does not meet the [sponsorship requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) for becoming a community member. 

As @timothysc has already +1'd, would you be able to solicit a second sponsor other than from Heptio? Thank you!

**Comment by vincepri** [comment]
@cblecker Thank you for the note! I've spoken to @dims and he agreed to be a sponsor. I've updated the issue.

**Comment by dims** [comment]
+1 from me

**Comment by vincepri** [comment]
Woo, thanks!
