### ISSUE TITLE
REQUEST: New membership for divyenpatel

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/org#1023]
### GitHub Username
@divyenpatel
### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andrewsykim 
- @frapposelli 
- @codenrhoden 
- @dvonthenen

### List of contributions to the Kubernetes project
- PRs reviewed / authored

   **PRs authored** - https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Adivyenpatel+is%3Aclosed

   **PRs reviewed** - https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+assignee%3Adivyenpatel+is%3Aclosed

- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=mentions%3Adivyenpatel+is%3Aclosed

- SIG projects I am involved with
   - https://github.com/kubernetes-sigs/vsphere-csi-driver
   - https://github.com/kubernetes/cloud-provider-vsphere

**Comment by codenrhoden** [comment]
@divyenpatel you are already a member of the `kubernetes` org. No sponsorship is needed. You just open up a PR as documented in [this section](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem)

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #1031 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
