### ISSUE TITLE
REQUEST: New membership for hantaowang

### ISSUE THREAD

**Issue by hantaowang** [kubernetes/org#1024]
### GitHub Username
@hantaowang

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@davidz627
@jingxu97

### List of contributions to the Kubernetes project
Kubernetes PRs: https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ahantaowang+
perf-test PRs: https://github.com/kubernetes/perf-tests/pulls?utf8=✓&q=is%3Apr+author%3Ahantaowang+

**Comment by davidz627** [comment]
+1
Will has made important contributions to k8s storage through new functionality, and soon some scalability testing.

**Comment by jingxu97** [comment]
+1

**Comment by nzoueidi** [comment]
Hey @hantaowang sponsors should be from different companies. Can you find another eligible sponsor to sponsor your membership?

**Comment by hantaowang** [comment]
@gnufied

**Comment by mrbobbytables** [comment]
gentle ping reminder for @gnufied :)

**Comment by gnufied** [comment]
+1

**Comment by mrbobbytables** [comment]
@hantaowang , thank you for all your contributions to the project so far :)

I've created PR #1105  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
