### ISSUE TITLE
REQUEST: New membership for clarketm

### ISSUE THREAD

**Issue by clarketm** [kubernetes/org#1026]
### GitHub Username
@clarketm

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp
- @cblecker 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - kubernetes/test-infra#13300
    - kubernetes/test-infra#13383
    - kubernetes/test-infra#13385
    - kubernetes/test-infra#13417
    - kubernetes/test-infra#13368 (rev: kubernetes/test-infra#13540)
- Issues responded to
    - kubernetes/test-infra#13536
    - kubernetes/test-infra#13414
    - kubernetes/test-infra#13162
    - kubernetes/test-infra#9079 (WIP)
    - kubernetes/test-infra#13164 (WIP)

- SIG projects I am involved with
None

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by cblecker** [comment]
+1 from me. Thanks for your work making our python better!

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #1031 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
