### ISSUE TITLE
REQUEST: New membership for alisondy

### ISSUE THREAD

**Issue by alisondy** [kubernetes/org#1027]
### GitHub Username
@alisondy

### Organization you are requesting membership in
kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman
- @munnerz 
- @BenTheElder

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   https://github.com/kubernetes-sigs/kind/pull/618
   https://github.com/kubernetes/enhancements/pull/1007

- Issues responded to / authored
   https://github.com/kubernetes/minikube/issues/4470

- SIG projects I am involved with
  Contributor Summit San Diego
  APAC Coordinator Contribex Subproject

**Comment by mrbobbytables** [comment]
+1 here :)

**Comment by parispittman** [comment]
+1

**Comment by cblecker** [comment]
+💯

**Comment by BenTheElder** [comment]
+1000

**Comment by justaugustus** [comment]
Enthusiastic +1!
/pony party

**Comment by justaugustus** [comment]
I've created #1031 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.
Looking forward to your contributions!!

Welcome! :)
/assign
