### ISSUE TITLE
REQUEST: New membership for sethmccombs

### ISSUE THREAD

**Issue by sethmccombs** [kubernetes/org#1028]
### GitHub Username
@sethmccombs

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @lachie83  

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/sig-release/issues/665 
  - https://github.com/kubernetes/website/pull/14482
  - various other Docs PRs
- Issues responded to
- SIG projects I am involved with
  - 1.16 Release Team (Docs Shadow)

**Comment by lachie83** [comment]
+1

**Comment by mrbobbytables** [comment]
+1 \o/

**Comment by alisondy** [comment]
+1 ✨🎉

**Comment by justaugustus** [comment]
Enthusiastic +1!
/pony party

**Comment by justaugustus** [comment]
I've created #1031 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.
Looking forward to your contributions!!

Welcome! :)
/assign
