### ISSUE TITLE
REQUEST: New membership for <karenhchu>

### ISSUE THREAD

**Issue by karenhchu** [kubernetes/org#1029]
### GitHub Username
@karenhchu

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lachie83
- @onlydole

### List of contributions to the Kubernetes project
- Release Team - Comms Shadow

**Comment by onlydole** [comment]
+1 to @karenhchu! She has been a strong OSS and Kubernetes advocate for some time, and she should be added to the Kubernetes organization.

**Comment by alisondy** [comment]
+1 ✨🎉

**Comment by justaugustus** [comment]
Enthusiastic +1!
/pony party

**Comment by justaugustus** [comment]
I've created #1031 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.
Looking forward to your contributions!!

Welcome! :)
/assign
