### ISSUE TITLE
REQUEST: New membership for madhanrm

### ISSUE THREAD

**Issue by madhanrm** [kubernetes/org#103]
### GitHub Username
@madhanrm

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @brendandburns 
- @michmike 
- @PatrickLang 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
Own https://github.com/kubernetes/kubernetes/tree/master/pkg/proxy/winkernel
Authored CNI support for Windows
- Issues responded to
- SIG projects I am involved with 
sig-windows, sig-network

**Comment by michmike** [comment]
i approve the sponsorship

**Comment by michmike** [comment]
+1

**Comment by PatrickLang** [comment]
I approve too.

Sent from a tiny keyboard

On Sep 20, 2018, at 5:07 PM, Madhan Raj Mookkandy <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @michmike<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichmike&data=02%7C01%7C%7Cab05c7f15e194d4c65dd08d61f563b06%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636730852542576064&sdata=fR%2BLnpgzmsWkXbyxmPg5L1CVEc%2BNHVvwxwscTZ1MnuA%3D&reserved=0>

Am already part of https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/winkernel/OWNERS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkubernetes%2Fkubernetes%2Fblob%2Fmaster%2Fpkg%2Fproxy%2Fwinkernel%2FOWNERS&data=02%7C01%7C%7Cab05c7f15e194d4c65dd08d61f563b06%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636730852542576064&sdata=Om%2BaL%2FOZp%2F9K4vzM4XHonNJU3f5lKFnAjn%2BQujgDoCk%3D&reserved=0>
