### ISSUE TITLE
REQUEST: New membership for @shaileshsharan98

### ISSUE THREAD

**Issue by shaileshsharan98** [kubernetes/org#1035]
### GitHub Username

@shaileshsharan98

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @kittenking

### List of contributions to the Kubernetes project
https://github.com/kubernetes/website/pull/15485

**Comment by zacharysarah** [comment]
+1, @shaileshsharan98 is initiating a new Tamil localization of the docs along with @kittenking (#1034).

**Comment by nikhita** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @shaileshsharan98, thank you for all your contributions so far :)

I've created PR #1041 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
