### ISSUE TITLE
REQUEST: New membership for markyjackson-taulia

### ISSUE THREAD

**Issue by markyjackson-taulia** [kubernetes/org#1037]
### GitHub Username
@markyjackson-taulia 

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mrbobbytables 
- @jberkus

### List of contributions to the Kubernetes project

PRs reviewed / authored
https://github.com/kubernetes/website/pull/9675
https://github.com/kubernetes/community/pull/3920
- Issues responded to
https://github.com/kubernetes/community/issues/3921
https://github.com/kubernetes/community/issues/3894
https://github.com/kubernetes/community/issues/3717
- SIG projects I am involved with
sig-contribex 
summit-staff

**Comment by mrbobbytables** [comment]
+1 from sponsor :)

/pony party

**Comment by nzoueidi** [comment]
Hey there @markyjackson-taulia, thank you for all your contributions so far :)

I've created PR #1041 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
