### ISSUE TITLE
REQUEST: New membership for ipochi

### ISSUE THREAD

**Issue by ipochi** [kubernetes/org#1039]
### GitHub Username
@ipochi

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @onlydole
- @jberkus

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by onlydole** [comment]
+1 to Imran - currently, he is serving as a communications shadow for the 1.16 release of Kubernetes.

**Comment by nzoueidi** [comment]
Hey there @ipochi, thank you for all your contributions so far :)

I've created PR #1044 to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
