### ISSUE TITLE
REQUEST: New membership for dineshgovindasamy

### ISSUE THREAD

**Issue by dineshgovindasamy** [kubernetes/org#104]
### GitHub Username
@dineshgovindasamy

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@michmike 
@PatrickLang 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/winkernel/OWNERS
https://github.com/kubernetes/kubernetes/pull/64862
https://github.com/kubernetes/kubernetes/pull/64862
https://github.com/kubernetes/community/pull/1276
- Issues responded to
- SIG projects I am involved with
SIG-WINDOWS
SIG-NETWORK

**Comment by michmike** [comment]
+1
