### ISSUE TITLE
REQUEST: New membership for alculquicondor

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/org#1042]
### GitHub Username
@alculquicondor

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Huang-Wei 
- @ahg-g 

### List of contributions to the Kubernetes project

- PRs merged:
  - https://github.com/kubernetes/kubernetes/pull/80220
  - https://github.com/kubernetes/kubernetes/pull/78400
  - https://github.com/kubernetes/kubernetes/pull/77419
  - https://github.com/kubernetes/kubernetes/pull/77418
  - https://github.com/kubernetes/kubernetes/pull/73966
  - https://github.com/kubernetes/kubernetes/pull/73926
- WIP PRs:
  - https://github.com/kubernetes/enhancements/pull/1127
  - https://github.com/kubernetes/kubernetes/pull/80533
  - https://github.com/kubernetes/kubernetes/pull/80233
- PRs reviewed:
  - https://github.com/kubernetes/kubernetes/pull/77327 [Merged]
  - https://github.com/kubernetes/kubernetes/pull/77760 [Merged]
  - https://github.com/kubernetes/kubernetes/pull/77828
  - https://github.com/kubernetes/kubernetes/pull/79062
  - https://github.com/kubernetes/kubernetes/pull/79063
  - https://github.com/kubernetes/kubernetes/pull/80395
- Issues responded to:
  - https://github.com/kubernetes/kubernetes/issues/80216
  - https://github.com/kubernetes/kubernetes/issues/80322
  - https://github.com/kubernetes/kubernetes/issues/80372
- SIG projects I am involved with:
  - scheduling: scheduler
  - node: cri-api

**Comment by Huang-Wei** [comment]
+1

Welcome, @alculquicondor! Looking forward to seeing more contributions in the future.

**Comment by ahg-g** [comment]
+1, thanks @alculquicondor for your contributions so far, and looking forward to seeing more in the future.

**Comment by nzoueidi** [comment]
Hey there @alculquicondor, thank you for all your contributions so far :)

I've created PR #1044 to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
