### ISSUE TITLE
REQUEST: New membership for daihao

### ISSUE THREAD

**Issue by DaiHao** [kubernetes/org#1043]
### GitHub Username
@DaiHao

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xiang90
- @resouer
- @janetkuo 
- @k82cn 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3ADaiHao
- Issues responded to
https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=assignee%3ADaiHao+
- SIG projects I am involved with
apps

**Comment by DaiHao** [comment]
@resouer @xiang90 @janetkuo please +1 if you feel comfortable. thx

**Comment by resouer** [comment]
+1

/lgtm

**Comment by xiang90** [comment]
+1

/lgtm

**Comment by nzoueidi** [comment]
Hey @DaiHao, I think @resouer and @xiang90 are both from Alibaba, could you please correct me if I am mistaken. 
If no, you may want to find another eligible sponsor to sponsor your org membership. 
Sponsors should be from different multiple companies. More info are here: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by DaiHao** [comment]
ping @janetkuo

**Comment by k82cn** [comment]
+1, thanks for your contribution :)

**Comment by DaiHao** [comment]
@nzoueidi ptal, I think it meets the requirements now

**Comment by nzoueidi** [comment]
Hey there @DaiHao, thank you for all your contributions so far :)

I've created PR #1067 to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
