### ISSUE TITLE
Creation of sig-usability in kubernetes-sigs 

### ISSUE THREAD

**Issue by tashimi** [kubernetes/org#1047]
### New Repo, Staging Repo, or migrate existing
new repo 

### Requested name for new repository
sig-usability

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@tashimi
@vllry
@Rajakavitha1
@hpandeycodeit

### If not a staging repo, who should have write access
@tashimi
@vllry
@Rajakavitha1
@hpandeycodeit

### If not a staging repo, who should be listed as approvers in OWNERS
@tashimi
@vllry
@Rajakavitha1
@hpandeycodeit

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@tashimi
@vllry
@Rajakavitha1
@hpandeycodeit

### What should the repo description be
SIG-Usability related docs and code 

### What SIG and subproject does this fall under in sigs.yaml
This is a new project, sig-usability

### Approvals
[Sig Approval](https://github.com/kubernetes/community/pull/3801) 

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

### Additional context for request
[SIG-Usability Charter](https://github.com/kubernetes/community/blob/master/sig-usability/charter.md)

**Comment by nikhita** [comment]
Repo has been created: https://github.com/kubernetes-sigs/sig-usability :tada: 

Also created:
- https://github.com/kubernetes/org/pull/1050 - to add GitHub teams to grant permissions
- https://github.com/kubernetes/community/pull/3940 - to add the repo to k/community

Once both PRs merge, we can close this issue.

**Comment by tashimi** [comment]
Thank you!!!

**Comment by nikhita** [comment]
All PRs have merged and teams have been granted access.

/close
