### ISSUE TITLE
REQUEST: New membership for @VineethReddy02

### ISSUE THREAD

**Issue by VineethReddy02** [kubernetes/org#1048]
### GitHub Username
e.g. @VineethReddy02

### Organization you are requesting membership in
e.g. @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @simplytunde 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
 https://github.com/kubernetes/website/pull/12577
 https://github.com/kubernetes/website/pull/12580

- Issues responded to
  https://github.com/kubernetes/enhancements/issues/600
  https://github.com/kubernetes/enhancements/issues/598
  https://github.com/kubernetes/enhancements/issues/589
  https://github.com/kubernetes/enhancements/issues/596
   
- SIG projects I am involved with 
  - sig-release as docs shadow, virtual-kubelet, sig-docs-security, sig-docs.

**Comment by justaugustus** [comment]
+1! Vineeth is helping out on the Release Team for 1.16. :)

**Comment by simplytunde** [comment]
+1 for me

**Comment by nzoueidi** [comment]
Hey there @VineethReddy02, thank you for all your contributions so far :)

I've created PR #1057 to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
