### ISSUE TITLE
Migrate kepval into kubernetes/enhancements

### ISSUE THREAD

**Issue by chuckha** [kubernetes/org#1049]
### New Repo, Staging Repo, or migrate existing
Migrate https://github.com/chuckha/kepval into https://github.com/kubernetes/enhancements

I'm not entirely sure if I need this issue, but I will  be opening it just in case I do need it. Please feel free to close if this PR is sufficient: https://github.com/kubernetes/enhancements/pull/1185/files

### Approvals
@justaugustus 

### Additional context for request
This was the first step to getting the metadata validated across KEPs. The kep/release teams have plans to use the metadata this app keeps validated to build a UI around keps in the future.

**Comment by nikhita** [comment]
> I'm not entirely sure if I need this issue, but I will be opening it just in case I do need it. Please feel free to close if this PR is sufficient: https://github.com/kubernetes/enhancements/pull/1185/files

That PR seems fine :)

@chuckha Thanks for creating the issue to surface it though!
