### ISSUE TITLE
REQUEST: New membership for randomvariable

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/org#105]
### GitHub Username
@randomvariable

### Organization you are requesting membership in
* @kubernetes
* @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @detiber
- @dims

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - Authored
    - [Cluster API Provider AWS](https://github.com/kubernetes-sigs/cluster-api-provider-aws/)
      - [NAT Gateway reconciliation](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/81)
      - [Allowing use of AWS Elastic Container Registry](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/92)
    - [Cluster API](https://github.com/kubernetes-sigs/cluster-api/)
      - [RFC 3531 network CIDR allocation](https://github.com/kubernetes-sigs/cluster-api/pull/503)
    - [Community](https://github.com/kubernetes/community)
      - [KEP for AWS IAM support](https://github.com/kubernetes/community/pull/2329) (co-authored with @pingles)
  - Reviewed
    - [Kubernetes](https://github.com/kubernetes/kubernetes/)
        - [kubeadm: kubelet config persistence](https://github.com/kubernetes/kubernetes/pull/63887)
        - [Handling of AWS EBS volume creation](https://github.com/kubernetes/kubernetes/pull/65223)
    - [Website](https://github.com/kubernetes/website)
        - [Minikube MacOS instructions update](https://github.com/kubernetes/website/pull/9384)
        - [Minikube KVM instructions update](https://github.com/kubernetes/website/pull/9223)
    - [Cluster API Provider AWS](https://github.com/kubernetes-sigs/cluster-api-provider-aws/)
      - [Documenting idempotent resource handling](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/66)
- Issues responded to
  - [Kubernetes](https://github.com/kubernetes/kubernetes)
    - [Handling of AWS EBS volume creation](https://github.com/kubernetes/kubernetes/issues/62171)
  - [Kubeadm](https://github.com/kubernetes/kubeadm)
    - [SELinux support](https://github.com/kubernetes/kubeadm/issues/279)
  - [Website](https://github.com/kubernetes/website)
    - [Missing pages after Hugo migration](https://github.com/kubernetes/website/issues/8261)

- SIG projects I am involved with
  - SIG Cluster Lifecycle
  - SIG AWS

**Comment by dims** [comment]
+1 from me!

**Comment by detiber** [comment]
+1
