### ISSUE TITLE
Cleanup teams for cloud provider specific SIGs

### ISSUE THREAD

**Issue by nikhita** [kubernetes/org#1051]
All cloud providers SIGs are folded into SIG Cloud Provider. We should cleanup the teams related to these SIGs as well.

Related: syncing the OWNERS_ALIASES file with the one in k/community removes the cloud provider specific SIG aliases. New aliases were added manually for now so that they don't contradict with the cleanup (https://github.com/kubernetes/org/pull/1050).

fyi @andrewsykim @d-nishi @justaugustus @frapposelli

**Comment by justaugustus** [comment]
Hey @nikhita, you linked #1050, but I don't see anything related. 
Did you mean to reference another PR?

**Comment by nikhita** [comment]
Sorry, I should have been clearer! Mainly meant this part in the PR body of #1050: 

> Adds sig-usability-leads to OWNERS_ALIASES. Ideally we should just do a sync of the OWNERS_ALIASES file in k/community but that removes aliases for cloud providers sigs (sig-azure, etc). I'd prefer to clean those up in a follow-up (#1051)

**Comment by justaugustus** [comment]
Addressed in #1051.

**Comment by justaugustus** [comment]
Actually, we'll still need a follow-up once #1051 merges to nest the consolidated SIG directories under SIG Cloud Provider.
@mrbobbytables mentioned there might be some weirdness with the levels of directories peribolos traverses when generating its' config, so I didn't attempt to do it there.

**Comment by nikhita** [comment]
> there might be some weirdness with the levels of directories peribolos traverses when generating its' config, so I didn't attempt to do it there.

Yeah, I was going to suggest nesting as well but I think we do some bazel magic to stitch all teams.yaml files together so I thought it'd be better to do that as a follow up as well.

**Comment by mrbobbytables** [comment]
It looks like the relevant block is in [cmd/merge/main.go](https://github.com/kubernetes/org/blob/master/cmd/merge/main.go)

https://github.com/kubernetes/org/blob/4a4f8cfc705b31e66d3d345f066fc1ee729b207f/cmd/merge/main.go#L128-L130

 @fejta -- Do you think it'd be a problem to update it to walk deeper?

**Comment by nikhita** [comment]
Just realized one thing around the nesting here -- I think it's sort of clear who the owners for the nested subproject would be in case of cloud providers (maybe sig leads of the now deprecated SIGs?) -- but if we make this a "thing" or "feature" to allow to have separate `teams.yaml` file per subprojects, we probably need some way around defining who these subproject owners would be...which we don't currently.

Related: https://github.com/kubernetes/community/issues/1673

**Comment by justaugustus** [comment]
Any updates on this one?

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/milestone v1.19
I think we should consider this as part of https://github.com/kubernetes/community/issues/2323

I notice we now have a kubernetes/provider-azure

We can either:
- follow that example for the other provider- subprojects
- modify our config merging code to support nesting subprojects under sig dirs
