### ISSUE TITLE
REQUEST: New membership for rawkode

### ISSUE THREAD

**Issue by rawkode** [kubernetes/org#1054]
### GitHub Username
@rawkode

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @castrojo
- @lachie83 

### List of contributions to the Kubernetes project
- SIG projects I am involved with
  - SIG-Release 1.15 and 1.16

**Comment by castrojo** [comment]
Strong +1 from me!

**Comment by lachie83** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @rawkode, thank you for all your contributions so far :)

I've created PR #1057 to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
