### ISSUE TITLE
Request to create a new repository kubernetes-csi/csi-proxy

### ISSUE THREAD

**Issue by ddebroy** [kubernetes/org#1060]
### New Repo, Staging Repo, or migrate existing
New Repository

### Requested name for new repository
csi-proxy

### Which Organization should it reside
kubernetes-csi

### If not a staging repo, who should have admin access
@ddebroy, @PatrickLang, @msau42 

### If not a staging repo, who should have write access
@ddebroy, @PatrickLang, @msau42

### If not a staging repo, who should be listed as approvers in OWNERS
@ddebroy, @PatrickLang, @msau42 @yujuhong @jingxu97 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@ddebroy, @PatrickLang, @msau42 @yujuhong 

### What should the repo description be
CSI Proxy utility to enable CSI Plugins on Windows

### What SIG and subproject does this fall under in sigs.yaml
This is part of the CSI project under sig-storage

### Approvals
1. KEP Approved with the above repository https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190714-windows-csi-support.md#infrastructure-needed
2. Discussed and agreed upon as part of CSI meeting on July 31st under Misc Topics: https://docs.google.com/document/d/1_hvq3nleqQEYatH9V_Gfep39jMzaFJRSN2ioA0PFq-Q/edit#

**Comment by msau42** [comment]
Please also add @jingxu97 as an approver

**Comment by nikhita** [comment]
/assign 

Oddly, I'm not able to access the google doc even though I've joined the sig storage google group. Treating this as approved because of the KEP though..

**Comment by nikhita** [comment]
Repo has been created https://github.com/kubernetes-csi/csi-proxy :tada: 

Also created:

- https://github.com/kubernetes/org/pull/1061 - to add GitHub teams for granting access
- https://github.com/kubernetes/community/pull/3950 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by ddebroy** [comment]
Thanks @nikhita !

**Comment by nikhita** [comment]
All PRs have merged and teams have been granted access.

/close
