### ISSUE TITLE
REQUEST: New membership for cji

### ISSUE THREAD

**Issue by cji** [kubernetes/org#1062]
### GitHub Username
@cji

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mattmoyer (VMWare)
- @tallclair (Google)

### List of contributions to the Kubernetes project
- WG I am involved with: https://github.com/kubernetes/community/tree/master/wg-security-audit
- Based my on WG lead role, I was asked to apply for membership as a requirement here: https://github.com/kubernetes/community/issues/3945
- https://github.com/kubernetes/test-infra/pull/11979
- https://github.com/kubernetes/security/pull/43

**Comment by mattmoyer** [comment]
I'm happy to vouch for @cji.

**Comment by spiffxp** [comment]
@tallclair vouched here https://github.com/kubernetes/community/issues/3945#issuecomment-517421709

**Comment by joelsmith** [comment]
:+1: +1 from me too if you need another sponsor. Been a pleasure to work with @cji on wg-security-audit.

**Comment by nzoueidi** [comment]
Hey there @cji, thank you for all your contributions so far :)

I've created PR #1067 to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
