### ISSUE TITLE
REQUEST: New membership for johscheuer

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/org#1064]
### GitHub Username
@johscheuer

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @castrojo
- @saad-ali 

### List of contributions to the Kubernetes project
- Here is a list of my PR's (`kubernetes/kubernetes`) https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ajohscheuer
- And I'm part of an Owners file: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/quobyte/OWNERS
- Currently SIG-Network before Sig-Storage (implemented the Quobyte drive)

**Comment by nikhita** [comment]
/assign @castrojo @saad-ali 
can you comment here?

**Comment by saad-ali** [comment]
I +1 this. @johscheuer implemented the Quobyte volume plugin, and it would be good to get him in to the OWNERS file for that plugin. To do that, he first needs membership.

**Comment by castrojo** [comment]
+1 from me, sorry for my delayed response.

**Comment by mrbobbytables** [comment]
Hey there @johscheuer, thank you for all your contributions so far :)

I've created PR #1092  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by johscheuer** [comment]
Thanks ! :)
