### ISSUE TITLE
REQUEST: New membership for @aasmall

### ISSUE THREAD

**Issue by aasmall** [kubernetes/org#1065]
### GitHub Username
@aasmall

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @destijl 
- @joelsmith 

### List of contributions to the Kubernetes project
- WG I am involved with: https://github.com/kubernetes/community/tree/master/wg-security-audit
- Based my on WG lead role, I was asked to apply for membership as a requirement here: kubernetes/community#3945
- Most of the collaboration with the WG has been in private meetings and under embargo due to the sensitive nature of the content. It will be shared with the community shortly.
  - https://github.com/kubernetes/community/commit/4da4a630216fb393ed74d560b7243fe1d66e6034#diff-93d9219d03a630486013bea4d2fe5436

**Comment by destijl** [comment]
Vouching for Aaron. Aaron has put in a lot of work coordinating, guiding, and leading a large security audit for K8s that will benefit all of our users.

**Comment by joelsmith** [comment]
:+1: +1 on making @aasmall a member of the Kubernetes project. He has worked hard in his role in wg-security-audit and used his expertise to drive a favorable outcome for the CNCF and Kubernetes.

**Comment by nzoueidi** [comment]
Hey there @aasmall, unfortunately @destijl cannot sponsor you for membership in the @kubernetes org. Sponsors must be reviewers or approvers in at least 1 OWNERS file either in any repo in the Kubernetes org.

More information can be found in the requirements section: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

If you have any questions don't be afraid to ask.

Thanks!

**Comment by mikedanese** [comment]
I'll vouch for @aasmall. His work on coordinating the security audit has been very beneficial to the project.

**Comment by aasmall** [comment]
@nzoueidi @destijl  - My apologies, I just assumed Greg was on an owners file. 
@mikedanese - Thank you :)

**Comment by nikhita** [comment]
@aasmall I've created #1071 to add you to @kubernetes. Once that merges, you should receive an invite from our automation framework.
Welcome! :)

/assign
