### ISSUE TITLE
REQUEST: New membership for phenixblue

### ISSUE THREAD

**Issue by phenixblue** [kubernetes/org#1066]
### GitHub Username
@phenixblue

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mauilion
- @BenTheElder 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/73253
  - https://github.com/kubernetes/website/pull/12162
  - https://github.com/kubernetes-sigs/cluster-api/pull/694
  - https://github.com/kubernetes-sigs/kind/pull/448
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/76680
  - https://github.com/kubernetes-sigs/kind/issues/447
- SIG projects I am involved with
  - sig-testing (kind)
  - sig-cluster-lifecycle (cluster-api)
  - sig-docs

**Comment by BenTheElder** [comment]
+1 🙂

**Comment by mauilion** [comment]
+1 from me Joe has been speaking at meetups and helping folks in slack as well as contributing to projects like sigs.k8s.io/kind.

**Comment by nzoueidi** [comment]
Hey there @phenixblue, thank you for all your contributions so far :)

I've created PR #1067 to add you to the kubernetes and kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
