### ISSUE TITLE
REQUEST: New membership for @Fei-Guo

### ISSUE THREAD

**Issue by Fei-Guo** [kubernetes/org#1069]
### GitHub Username
Fei-Guo

### Organization you are requesting membership in
Kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @resouer 
- @Huang-Wei 

### List of contributions to the Kubernetes project
- PRs reviewed / authored https://github.com/kubernetes-sigs/multi-tenancy/pull/32
- SIG projects I am involved with wg-multitenancy
- Design docs
https://docs.google.com/document/d/1EELeVaduYZ65j4AXg9bp3Kyn38GKDU5fAJ5LFcxt2ZU/edit
https://docs.google.com/document/d/1RseBCBhb5u_g6iwpVABP--XHhKi6I9-i_UTB8QJrT9k/edit

- CNCF blog
https://www.cncf.io/blog/2019/06/20/virtual-cluster-extending-namespace-based-multi-tenancy-with-a-cluster-view/

**Comment by resouer** [comment]
+1

**Comment by adohe** [comment]
+1

**Comment by resouer** [comment]
kindly ping @nikhita for approve :-)

**Comment by nikhita** [comment]
IIUC @resouer @adohe both of you are from Alibaba?

@Fei-Guo Sponsors need to be from different companies so if you could find an additional sponsor not from Alibaba, that would be great! :)

**Comment by resouer** [comment]
@nikhita Aha, @adohe is not from Alibaba Group, he's from Ant Financial, the profile is not up-to-date.

Anyway we just changed the supporter :-)

**Comment by Huang-Wei** [comment]
+1

Looking forward to seeing more innovative ideas/contributions in multi-tenancy side.

**Comment by nikhita** [comment]
@Fei-Guo I've created #1074 to add you to @kubernetes-sigs. Once that merges, you should receive an invite from our automation framework.
Welcome!! :)

/assign

**Comment by resouer** [comment]
Welcome aboard! @Fei-Guo
