### ISSUE TITLE
REQUEST: New membership for lilic

### ISSUE THREAD

**Issue by LiliC** [kubernetes/org#1070]
### GitHub Username
@LiliC 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @brancz 
- @tariq1890 

### List of contributions to the Kubernetes project
- PRs reviewed / authored -> https://github.com/search?q=org%3Akubernetes+is%3Apr+author%3ALiliC
- Issues responded to https://github.com/kubernetes/kube-state-metrics/issues?utf8=%E2%9C%93&q=is%3Aissue+lilic
- SIG projects I am involved with -> I am about to be added as a maintainer to kube-state-metrics, but need to be in kubernetes org to do that :) https://github.com/kubernetes/kube-state-metrics/pull/861

**Comment by brancz** [comment]
:100: +1 from me! :slightly_smiling_face:

**Comment by tariq1890** [comment]
Huge +1 from me. Thank you for all contributions to Kube-state-metrics and several other K8s projects. Well deserved, no doubt!

**Comment by nikhita** [comment]
+10000 :)

/woof

**Comment by andyxning** [comment]
+1

**Comment by nikhita** [comment]
@LiliC  I've created #1071 to add you to @kubernetes. Once that merges, you should receive an invite from our automation framework.
Welcome! So happy to see this!! :)

/assign
