### ISSUE TITLE
REQUEST: New membership for devlware

### ISSUE THREAD

**Issue by devlware** [kubernetes/org#1073]
### GitHub Username
@devlware

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @femrtnz 
- @jcjesus

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    https://github.com/kubernetes/website/pull/14705
- Issues responded to
- SIG projects I am involved with

**Comment by mrbobbytables** [comment]
@devlware I think you're requesting membership to @kubernetes where the the [website repo](https://github.com/kubernetes/website) is managed. You don't have to request access to specific sigs :)

**Comment by devlware** [comment]
@mrbobbytables You are correct. I was not sure about it, I'll edit and update it.

**Comment by femrtnz** [comment]
+1 @devlware is helping us with the Portuguese translations :)

**Comment by jcjesus** [comment]
+1 @devlware

**Comment by zacharysarah** [comment]
+1

**Comment by mrbobbytables** [comment]
@devlware  thank you for helping with the Portuguese localization efforts :)

I've created PR #1078   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
