### ISSUE TITLE
REQUEST: New membership for yoonian

### ISSUE THREAD

**Issue by yoonian** [kubernetes/org#1075]
### GitHub Username
@yoonian

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gochist
- @seokho-son

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=org%3Akubernetes+is%3Apr+author%3Ayoonian

- Issues responded to
https://github.com/kubernetes/website/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Ayoonian

- SIG projects I am involved with
 kubernetes/sig-docs

**Comment by seokho-son** [comment]
+1, @yoonian is an active contributor for Korean localization.  I'm happy to work with @yoonian !

**Comment by gochist** [comment]
+1

**Comment by mrbobbytables** [comment]
@yoonian, thank you for all your help with the Korean localization efforts <3

I've created PR #1078  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
