### ISSUE TITLE
REQUEST: New membership for @jaybeale

### ISSUE THREAD

**Issue by JayBeale** [kubernetes/org#1077]
### GitHub Username
@jaybeale

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ X] I have subscribed to the kubernetes-dev e-mail list  
(https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ X] I am actively contributing to 1 or more Kubernetes subprojects
- [X ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @joelsmith 
- @tallclair 

### List of contributions to the Kubernetes project
- Co-leadership on the Security Audit working group
- Edits on the Kubernetes website: security documentation
- Work on the multi-tenancy working group

**Comment by joelsmith** [comment]
:+1: +1 from me. @JayBeale has been a great help on wg-security-audit!

**Comment by nikhita** [comment]
@JayBeale thank you for all your help with the security audit :)

I've created PR #1081 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by JayBeale** [comment]
Thank you all.  I promise that I'll keep contributing.
