### ISSUE TITLE
REQUEST: New membership for @danninov

### ISSUE THREAD

**Issue by danninov** [kubernetes/org#1080]
### GitHub Username
@danninov

### Organization you are requesting membership in
@kubernetes

### Requirements

- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @irvifa 
- @girikuncoro 

### List of contributions to the Kubernetes project
[kubernetes/website#14165](https://github.com/kubernetes/website/pull/14165)
[kubernetes/website#14156](https://github.com/kubernetes/website/pull/14156)
[kubernetes/website#14015](https://github.com/kubernetes/website/pull/14015)
[kubernetes/website#14229](https://github.com/kubernetes/website/pull/14229)

**Comment by girikuncoro** [comment]
+1 from me, @danninov has been great in helping out the docs localization effort for Indonesian language: kubernetes.io/id

**Comment by irvifa** [comment]
👍 from me, he's helping us a lot in the id localization.

**Comment by nikhita** [comment]
@danninov thank you for all your help with the Indonesian localization efforts :)

I've created PR #1081 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
