### ISSUE TITLE
REQUEST: New membership for moriadry

### ISSUE THREAD

**Issue by Moriadry** [kubernetes/org#1082]
### GitHub Username
moriadry

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims
- @xiangpengzhao 
- @kad 

### List of contributions to the Kubernetes project

- Contributed PR https://github.com/kubernetes/kubernetes/pull/80953 (Fix error collides with imported package name)

- Contributed PR https://github.com/kubernetes/kubernetes/pull/80321 (vender upgrade codedellemc/goscaleio to release v0.1.0)

- Contributed PR https://github.com/kubernetes/autoscaler/pull/2187 (improve code coverage and add test case for controller_fetcher and cluster_feeder)

- Opened issue https://github.com/kubernetes/autoscaler/issues/2194 (vertical-pod-autoscaler: fails on recommender init)

- Reviewed PR https://github.com/kubernetes/kubernetes/pull/80471 (Create CustomEncoder interface)

- WIP PR https://github.com/kubernetes/kubernetes/pull/80290 (upgrade vishvananda/netlink)

- WIP PR https://github.com/kubernetes/kubernetes/pull/80950 (clean up: use framework.ExpectEqual instead of should)

- Responded to issue https://github.com/kubernetes/kubernetes/issues/80178(Reuse FIFO code in DeltaFIFO)

I am involved with the autoscaling SIG.

**Comment by xiangpengzhao** [comment]
+1 :+1:

**Comment by dims** [comment]
+1 @Moriadry

**Comment by kad** [comment]
+1

**Comment by mrbobbytables** [comment]
@Moriadry, thank you for all your help with the project :D

I've created PR #1092  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
