### ISSUE TITLE
REQUEST: New membership for obitech

### ISSUE THREAD

**Issue by obitech** [kubernetes/org#1083]
### GitHub Username
@obitech

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @stealthybox
- @mattjmcnaughton

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pull/75202
- https://github.com/kubernetes/kubernetes/pull/75303
- https://github.com/kubernetes/kubernetes/pull/77023
- https://github.com/kubernetes/kubernetes/pull/78345
- https://github.com/kubernetes/kubernetes/pull/78347
- https://github.com/kubernetes/kubernetes/pull/80943
- https://github.com/kubernetes/kubernetes/issues/80941
- Onboarding with [wg-component-standard](https://github.com/kubernetes/community/blob/master/wg-component-standard/README.md)

**Comment by mattjmcnaughton** [comment]
/lgtm

@obitech has done a great job on the golint diffs I've worked with him on :)

**Comment by stealthybox** [comment]
+1
/lgtm

**Comment by mrbobbytables** [comment]
@obitech , thank you for helping with the component-standard working group :)

I've created PR #1092   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
