### ISSUE TITLE
GitHub Actions on kubernetes-sigs appear to have stopped working

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/org#1086]
### Organization or repository

kubernetes-sigs

(specifically, kubernetes-sigs/controller-runtime and friends)

### Name of integration

GitHub actions

### Link to integration website

https://github.com/features/actions

### Describe what is attempting to be accomplished

We were using GH actions in the KubeBuilder repos to perform some linting on the PRs themselves (namely, checking PR title formatting).  All was working well until yesterday or todayish, when things seem to have stopped working.

This makes me suspect that we've either been migrated to the new GitHub actions syntax, or have been kicked from the beta somehow.  The latter seems to be the case, unless I'm doing something wrong, since the new syntax (YAML-based) doesn't seem to be working (see below).

Can someone with org permissions double check on https://github.com/features/actions or whatnot to see what's happened?

### Sample PRs

An old PR with evidence of the old actions: https://github.com/kubernetes-sigs/controller-runtime/pull/542/checks

A newer PR that doesn't have any action runs: https://github.com/kubernetes-sigs/controller-runtime/pull/554

A PR against a branch with the new syntax: https://github.com/kubernetes-sigs/controller-runtime/pull/556

**Comment by cblecker** [comment]
/assign

I've verified k-sigs is still in the beta. Looks like the last run was 17 hours ago: https://github.com/kubernetes-sigs/controller-runtime/actions

**Comment by cblecker** [comment]
Sent e-mail to GitHub Support

**Comment by DirectXMan12** [comment]
Thanks!

**Comment by DirectXMan12** [comment]
Feel free to put me in touch with them directly, if they need more info :-)

**Comment by DirectXMan12** [comment]
looks like they're running on merges, but not on any other PR actions?  Strange.

**Comment by mrbobbytables** [comment]
Gentle ping @DirectXMan12 are things working okay for you now?

**Comment by mrbobbytables** [comment]
I think this is all good? Going to go ahead and close for now. @DirectXMan12 if there continues to be a problem, please reopen or a poke in slack.

Thanks!

/close
