### ISSUE TITLE
REQUEST: New membership for @CindyXing

### ISSUE THREAD

**Issue by CindyXing** [kubernetes/org#1087]
### GitHub Username
@CindyXing

### Organization you are requesting membership in
 @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @idvoretskyi
- @cantbewong

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
  a. Federation (multi-cluster)
  b. KubeEdge
  c. Windows container

**Comment by cantbewong** [comment]
+1 @CindyXing has been a frequent contributor to the IoT and Edge Working group for the past year

**Comment by mrbobbytables** [comment]
@CindyXing , thank you for helping with wg-iot-edge! :) 

I've created PR #1092   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
