### ISSUE TITLE
REQUEST: New membership for dejanb

### ISSUE THREAD

**Issue by dejanb** [kubernetes/org#1088]
### GitHub Username
dejanb

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @idvoretskyi
- @cantbewong

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/community/pull/2219
  - https://github.com/kubernetes/community/pull/3929
- Issues responded to
- SIG projects I am involved with
  - IoT Edge Working Group

**Comment by idvoretskyi** [comment]
+1

**Comment by cantbewong** [comment]
+1

**Comment by nikhita** [comment]
@dejanb  thank you for your contributions thus far :)

I've created PR #1097  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
