### ISSUE TITLE
REQUEST: New membership for mattiaperi

### ISSUE THREAD

**Issue by mattiaperi** [kubernetes/org#1089]
### GitHub Username
mattiaperi

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rlenferink
- @micheleberardi 

### List of contributions to the Kubernetes project
-  Working with sig-docs on the Italian localization of the docs

**Comment by rlenferink** [comment]
+1, @mattiaperi is helping with the Italian localization of our docs 🎉

**Comment by micheleberardi** [comment]
+1, lets get Mattia invited :) Grazie Mattia !!!

**Comment by micheleberardi** [comment]
+1, lets get @mattiaperi invited :) Grazie Mattia !!!

**Comment by mrbobbytables** [comment]
Hey there @mattiaperi, thank you for helping with the Italian localization efforts :)

I've created PR #1092  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
