### ISSUE TITLE
REQUEST: New membership for @phanama

### ISSUE THREAD

**Issue by phanama** [kubernetes/org#1091]
### GitHub Username
@phanama

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @girikuncoro 
- @irvifa 

### List of contributions to the Kubernetes project
- [https://github.com/kubernetes/website/pull/14395](kubernetes/website/#14395)
- [https://github.com/kubernetes/website/pull/14927](kubernetes/website/#14927)
- [https://github.com/kubernetes/website/pull/15335](kubernetes/website/#15335)
- [https://groups.google.com/forum/#!forum/kubernetes-sig-docs-id](#sig-docs-id)

**Comment by irvifa** [comment]
He already helped us a lot in the localization project so I give my :+1:

**Comment by girikuncoro** [comment]
+1 from me, @phanama has been helping out a lot with Indonesian localization and driving the community in Indonesia for this effort

**Comment by mrbobbytables** [comment]
@phanama thank you for your help with the Indonesian localization efforts :D

I've created PR #1105  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
