### ISSUE TITLE
REQUEST: New membership for yue9944882 @kubernetes-sigs

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/org#1093]
### GitHub Username

yue9944882

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of contributions to the Kubernetes project

(~200) reviews: https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=reviewed-by%3Ayue9944882+

(~140) PRs: https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=+is%3Apr+author%3Ayue9944882+

**Comment by nikhita** [comment]
Since you are already a member of @kubernetes, you don't need to file a membership request for @kubernetes-sigs. Feel free to create a PR! :smile:
