### ISSUE TITLE
Migrating apiserver-builder-alpha to @kubernetes-sigs

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/org#1094]
### New Repo, Staging Repo, or migrate existing

migrate existing

### Requested name for new repository

apiserver-builder-alpha

### Which Organization should it reside

@kubernetes-sigs

### If not a staging repo, who should have admin access

@yue9944882 @pwittrock @DirectXMan12 

### If not a staging repo, who should have write access

@yue9944882 @pwittrock @DirectXMan12 

### If not a staging repo, who should be listed as approvers in OWNERS

@yue9944882 @pwittrock @DirectXMan12 

### If not a staging repo, who should be listed in SECURITY_CONTACTS

yue9944882 <yue944882@gmail.com>

### What should the repo description be

```
apiserver-builder-alpha implements libraries and tools to quickly and easily build Kubernetes apiservers to support custom resource types based on APIServer Aggregation
```

### What SIG and subproject does this fall under in sigs.yaml

this belong to sig-apimachinery under server-sdk portion

### Approvals

@pwittrock has approval access, according to https://github.com/kubernetes/community/pull/3279

### Additional context for request

we're migrating from @kubernetes-incubator b/c that org is being officially archived..

**Comment by nikhita** [comment]
/assign @pwittrock 
for approval

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/community/issues/1922

**Comment by yue9944882** [comment]
+@adohe

**Comment by spiffxp** [comment]
Setting up teams https://github.com/kubernetes/org/pull/1112

**Comment by spiffxp** [comment]
Moving repo in sigs.yaml https://github.com/kubernetes/community/pull/4009

**Comment by yue9944882** [comment]
thank you for helping! can we close the issue now?

**Comment by yue9944882** [comment]
UPDATES: seems that these teams aren't granted corresponding permissions yet? i can't merge pulls or tagging labels currently. am i missing anything?

>  apiserver-builder-alpha-admins:
  apiserver-builder-alpha-maintainers:

**Comment by nikhita** [comment]
> EDIT: as the next stop, we need to archive the old repo, right?

The repo was migrated over to k-sigs, so https://github.com/kubernetes-incubator/apiserver-builder-alpha will automatically redirect to https://github.com/kubernetes-sigs/apiserver-builder-alpha.

>  seems that these teams aren't granted corresponding permissions yet?

The teams were had `Read` access. Fixed to grant them appropriate permissions. 

> can we close the issue now?

Yes, looks like everything is done! :tada: 
/close
