### ISSUE TITLE
REQUEST: New membership for CecileRobertMichon

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes/org#1096]
### GitHub Username
@CecileRobertMichon

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @juan-lee 

### List of contributions to the Kubernetes project
I contributed to kubernetes/autoscaler, kubernetes-sigs/cluster-api-provider-azure, kubernetes/test-infra:

https://github.com/kubernetes/autoscaler/pull/2152
https://github.com/kubernetes/autoscaler/pull/2052
https://github.com/kubernetes/autoscaler/pull/2094
https://github.com/kubernetes/autoscaler/issues/2044
https://github.com/kubernetes/test-infra/pull/12767
https://github.com/kubernetes/test-infra/pull/13807
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/225
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/226
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/227
https://github.com/kubernetes/kubernetes/pull/69012

I am a reviewer for cluster-api-provider-azure:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/251

And I'm active in the sig-cloud-provider/provider-azure community (k8s Slack, sig meetings, etc.)

Currently trying to become more involved with kubernetes-sigs/cluster-api.

**Comment by justaugustus** [comment]
Enthusiastic +1 for @CecileRobertMichon's membership!

**Comment by ritazh** [comment]
+1

**Comment by PatrickLang** [comment]
+1

**Comment by lachie83** [comment]
+1

**Comment by saiyan86** [comment]
Not a org member, but +1 XD

**Comment by kkmsft** [comment]
Not an org member but  +1 for @CecileRobertMichon membership.

**Comment by allantargino** [comment]
Not an org member but +1 for @CecileRobertMichon membership.²

**Comment by justaugustus** [comment]
Thanks for all the +1s. We have enough to add Cecile to the org.
(In future, please only +1 org requests if you are listed in an OWNERS file for the kubernetes org the contributor is requesting membership to.)

**Comment by justaugustus** [comment]
Also, for anyone on the thread that has been contributing to the project, but is not yet an org member, please consider filing an [org membership request](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+<your-GH-handle>) like Cecile did. 

We're always looking for new org members! :)

**Comment by feiskyer** [comment]
+1

**Comment by nikhita** [comment]
@CecileRobertMichon  thank you for your contributions thus far :)

I've created PR #1097  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
