### ISSUE TITLE
REQUEST: New membership for nikhita to kubernetes-sigs

### ISSUE THREAD

**Issue by nikhita** [kubernetes/org#110]
### GitHub Username
@nikhita

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements

I am already a member of @kubernetes.

(asking because of the recent conversation on slack for https://github.com/kubernetes-sigs/kind/pull/31)

**Comment by BenTheElder** [comment]
+1
@cblecker are there any plans to sync the members from kubernetes to kubernetes-sigs or should everyone in kubernetes interested in kubernetes-sigs be filing requests like this long-term?

**Comment by cblecker** [comment]
@BenTheElder eventually, but we need to set up pruning inactive members first.
