### ISSUE TITLE
REQUEST: New membership for tehcyx

### ISSUE THREAD

**Issue by tehcyx** [kubernetes/org#1100]
### GitHub Username
tehcyx

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@spiffxp 
@stevekuznetsov

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/test-infra/pull/13801
- https://github.com/kubernetes/test-infra/pull/13182
- https://github.com/kubernetes/test-infra/pull/13450
- https://github.com/kubernetes/test-infra/pull/13580
- https://github.com/kubernetes/test-infra/pull/13650
- https://github.com/kubernetes/test-infra/issues/13651
- https://github.com/kubernetes/test-infra/issues/13776
- https://github.com/kubernetes/test-infra/issues/13789

SIG projects I am involved with: [test-infra](https://github.com/kubernetes/test-infra) @[sig-testing](https://github.com/kubernetes/community/blob/master/sig-testing/README.md)

**Comment by stevekuznetsov** [comment]
+1 from this guy

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by nikhita** [comment]
@tehcyx thank you for your contributions to test-infra :)

I've created PR #1114 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
