### ISSUE TITLE
REQUEST: New membership for oz123

### ISSUE THREAD

**Issue by oz123** [kubernetes/org#1103]
### GitHub Username
oz123

### Organization you are requesting membership in

@kubernetes-clients

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @micw523 
- @roycaihw

### List of contributions to the Kubernetes project
- PRs reviewed / authored
1. https://github.com/kubernetes/kubernetes/pull/33564
1. https://github.com/kubernetes/kubernetes/pull/73101
1. https://github.com/kubernetes/examples/pull/275
1. https://github.com/kubernetes-client/python/pull/795
1. https://github.com/kubernetes-client/python/pull/807
1. https://github.com/kubernetes-client/python/pull/856
1. https://github.com/kubernetes-client/python/pull/893
1. https://github.com/kubernetes-client/python/pull/894
1. https://github.com/kubernetes-client/python/pull/922
1. https://github.com/kubernetes/website/pull/15830

- SIG projects I am involved with
1. python-client

**Comment by micw523** [comment]
+1

**Comment by roycaihw** [comment]
+1

Welcome, @oz123!

**Comment by mrbobbytables** [comment]
Hey there @oz123, thank you for helping with the python client library :)

I've created PR #1105  to add you to the Kubernetes-client Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-client! 🎉

/assign
