### ISSUE TITLE
REQUEST: New membership for jingxu97

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/org#1104]
### GitHub Username
jingxu97

### Organization you are requesting membership in
kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
-@msau42
-@xing-yang
- @saad-ali 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3Ajingxu97
https://github.com/pulls?q=is%3Aopen+is%3Apr+review-requested%3Ajingxu97
- Issues responded to
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+author%3Ajingxu97
- SIG projects I am involved with
Kubernetes VolumeSnapshot, Kubernetes-CSI

**Comment by msau42** [comment]
+1 Jing is heavily involved in snapshots and windows kubernetes-csi projects.

**Comment by xing-yang** [comment]
+1 Jing is already an approver of the kubernetes-csi/external-snapshotter repo.  She should be a member of kubernetes-csi.

**Comment by nikhita** [comment]
@jingxu97 thank you for your contributions thus far :)

I've created PR #1114 to add you to the kubernetes-csi org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-csi! 🎉

/assign
