### ISSUE TITLE
new repository: system-validators under Kubernetes

### ISSUE THREAD

**Issue by yastij** [kubernetes/org#1110]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
system-validators

### Which Organization should it reside
Kubernetes

### If not a staging repo, who should have admin access
@neolit123 @timothysc 
### If not a staging repo, who should have write access
@neolit123 @timothysc 

### If not a staging repo, who should be listed as approvers in OWNERS
the kubeadm [approvers](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/OWNERS#L3)

### If not a staging repo, who should be listed in SECURITY_CONTACTS
the [PST](https://github.com/kubernetes/kubernetes/blob/master/SECURITY_CONTACTS#L13)

### What should the repo description be

a set of system-oriented validators for kubeadm preflight checks

### What SIG and subproject does this fall under in sigs.yaml

This falls under the kubeadm subproject of sig-cluster-lifecycle

### Approvals
https://github.com/kubernetes/kubeadm/issues/1638#issuecomment-519079841
https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/QKeNaEnB-PI

### Additional context for request

part of the larger effort of extracting kubeadm out-of-tree, see https://github.com/kubernetes/kubeadm/issues/1600

**Comment by yastij** [comment]
cc @timothysc @dims

**Comment by dims** [comment]
Please send an email to arch ML as well @yastij

**Comment by yastij** [comment]
@dims - email thread already linked (under approvals)

**Comment by cblecker** [comment]
Is this a staging repo?

Also, I see an e-mail to sig-arch, but it doesn't have a consensus deadline.

**Comment by yastij** [comment]
@cblecker - this is a new repo under the kubernetes org, I'm adding a deadline to the thread

**Comment by nikhita** [comment]
/assign

Moving ahead on this since lazy consensus period is over, and has explicit lgtm from sig-cluster-lifecycle and sig-architecture leads.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/system-validators :tada: 

Also created:

- https://github.com/kubernetes/org/pull/1120 - to add GitHub teams to grant access.
- https://github.com/kubernetes/community/pull/4012 - to add the repo to sigs.yaml

Once both PRs have merged, we can close this issue.

**Comment by nikhita** [comment]
All PRs have merged and the teams have been granted appropriate access.

/close
