### ISSUE TITLE
REQUEST: New membership for xueweiz

### ISSUE THREAD

**Issue by xueweiz** [kubernetes/org#1111]
### GitHub Username
@xueweiz

### Organization you are requesting membership in
@kubernetes

### Requirements
- [ x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x ] I am actively contributing to 1 or more Kubernetes subprojects
- [ x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @wangzhen127 
- @Random-Liu 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/node-problem-detector/commit/360a23165d72383ebce7570e6efde57fe3285cf4
https://github.com/kubernetes/node-problem-detector/commit/63f0e35e56432848e0d0531ffc64855da972a25c
https://github.com/kubernetes/node-problem-detector/commit/7ad5dec712d741d2346bd24c6aab8d261b396e6f
https://github.com/kubernetes/node-problem-detector/commit/fbebcf311b341a2f057ee72c3ed0fe05e220ecce

- Issues responded to
https://github.com/kubernetes/node-problem-detector/issues/259
https://github.com/kubernetes/node-problem-detector/issues/284
https://github.com/kubernetes/node-problem-detector/issues/296
https://github.com/kubernetes/node-problem-detector/issues/304
https://github.com/kubernetes/node-problem-detector/issues/298

- SIG projects I am involved with
[SIGNode](https://github.com/kubernetes/community/blob/master/sig-node/README.md)

**Comment by wangzhen127** [comment]
+1

**Comment by nikhita** [comment]
@xueweiz :wave: according to [membership requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements), sponsors must be from different companies. Since both @wangzhen127 and @Random-Liu are from Google, you'll need to find a non-Googler sponsor.

**Comment by nzoueidi** [comment]
Hey @xueweiz did you had a chance to reach out to another sponsor from a different company? 
If no, I could help out with this. 

Thanks.

**Comment by andyxning** [comment]
+1

/cc @xueweiz @nikhita

**Comment by andyxning** [comment]
I come from https://bytedance.com/en. :)

**Comment by nzoueidi** [comment]
Hey there @xueweiz, thank you for all your contributions so far :)

I've created PR #1148  to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
