### ISSUE TITLE
REQUEST: New membership for nilo19

### ISSUE THREAD

**Issue by nilo19** [kubernetes/org#1116]
### GitHub Username
@nilo19

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @feiskyer 
- @justaugustus 

#### PRs reviewed / authored
- https://github.com/kubernetes/test-infra/pull/13289
- https://github.com/kubernetes/test-infra/pull/13457
- https://github.com/kubernetes/test-infra/pull/13483
- https://github.com/kubernetes/test-infra/pull/13501
- https://github.com/kubernetes/test-infra/pull/13503
- https://github.com/kubernetes/test-infra/pull/13535
- https://github.com/kubernetes/test-infra/pull/13574
- https://github.com/kubernetes/test-infra/pull/13595
- https://github.com/kubernetes/test-infra/pull/13596
- https://github.com/kubernetes/test-infra/pull/13598
- https://github.com/kubernetes/test-infra/pull/13620
- https://github.com/kubernetes/test-infra/pull/13653
- https://github.com/kubernetes/test-infra/pull/13680
- https://github.com/kubernetes/test-infra/pull/13705
- https://github.com/kubernetes/test-infra/pull/13961
- https://github.com/kubernetes/test-infra/pull/13962
- https://github.com/kubernetes/cloud-provider-azure/pull/171
- https://github.com/kubernetes/cloud-provider-azure/pull/172
- https://github.com/kubernetes/cloud-provider-azure/pull/174
- https://github.com/kubernetes/cloud-provider-azure/pull/189
- https://github.com/kubernetes/cloud-provider-azure/pull/191
- https://github.com/kubernetes/cloud-provider-azure/pull/192
- https://github.com/kubernetes/cloud-provider-azure/pull/195
- https://github.com/kubernetes/cloud-provider-azure/pull/196
- https://github.com/kubernetes/cloud-provider-azure/pull/197
- https://github.com/kubernetes/cloud-provider-azure/pull/198
- https://github.com/kubernetes/cloud-provider-azure/pull/199
- https://github.com/kubernetes/cloud-provider-azure/pull/200
- https://github.com/kubernetes/cloud-provider-azure/pull/205
- https://github.com/kubernetes/cloud-provider-azure/pull/207
- https://github.com/kubernetes/cloud-provider-azure/pull/210
- https://github.com/kubernetes/cloud-provider-azure/pull/212
- https://github.com/kubernetes/cloud-provider-azure/pull/213
- https://github.com/kubernetes/cloud-provider-azure/pull/214
- https://github.com/kubernetes/cloud-provider-azure/pull/215
- https://github.com/kubernetes/cloud-provider-azure/pull/217
- https://github.com/kubernetes/kubernetes/pull/79095
- https://github.com/kubernetes/kubernetes/pull/79462
- https://github.com/kubernetes/kubernetes/pull/81054
- https://github.com/kubernetes/kubernetes/pull/81213
- https://github.com/kubernetes/kubernetes/pull/81411
- https://github.com/kubernetes/autoscaler/pull/2171

#### SIG projects I am involved with

- @[sig-cloud-provider](https://github.com/kubernetes/community/tree/master/sig-cloud-provider), [cloud-provider-azure](https://github.com/kubernetes/cloud-provider-azure)
- @[sig-autoscaling](https://github.com/kubernetes/community/tree/master/sig-autoscaling), [autoscaler](https://github.com/kubernetes/autoscaler)
- @[sig-testing](https://github.com/kubernetes/community/tree/master/sig-testing), [test-infra](https://github.com/kubernetes/test-infra)

**Comment by justaugustus** [comment]
+1! @nilo19 has been helping out a bunch with Azure improvements.

**Comment by feiskyer** [comment]
+1 @nilo19 has worked a lot on cloud-provider-azure, cluster-autoscaler and e2e tests.

**Comment by nikhita** [comment]
@nilo19 thank you for your contributions thus far :)

I've created PR #1121 to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
