### ISSUE TITLE
REQUEST: New membership for vivekbagade

### ISSUE THREAD

**Issue by vivekbagade** [kubernetes/org#1117]
### GitHub Username
e.g. (at)vivekbagade

### Organization you are requesting membership in
e.g. (at)kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- (at)MaciekPytel
- (at)feiskyer

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * https://github.com/kubernetes/autoscaler/pull/2233
  * https://github.com/kubernetes/autoscaler/pull/2146
  * https://github.com/kubernetes/autoscaler/pull/2133
  * https://github.com/kubernetes/autoscaler/pull/2128
  * https://github.com/kubernetes/autoscaler/pull/2127
  * https://github.com/kubernetes/kubernetes/pull/75092
  * https://github.com/kubernetes/autoscaler/pull/1735
  * https://github.com/kubernetes/autoscaler/pull/1596
- Issues responded to
- SIG projects I am involved with

**Comment by feiskyer** [comment]
+1 @vivekbagade has worked a lot on autoscaler

**Comment by MaciekPytel** [comment]
+1 for @vivekbagade's many contributions to autoscaling

**Comment by nikhita** [comment]
@vivekbagade thank you for your contributions thus far :)

I've created PR #1121 to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
