### ISSUE TITLE
REQUEST: New membership for https://github.com/ps882

### ISSUE THREAD

**Issue by ps882** [kubernetes/org#1119]
### GitHub Username
e.g. (at)example_user
@ps882

### Organization you are requesting membership in
e.g. (at)kubernetes
@kubernetes-sigs

### Requirements
- [ Y] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ Y] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [Y ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [Y ] I am actively contributing to 1 or more Kubernetes subprojects
- [ Y] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ Y] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @listx
- @spiffxp

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/101
    - https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/102 
- Issues responded to
- SIG projects I am involved with
    - k8s-container-image-promoter

**Comment by listx** [comment]
/lgtm

ps882 (`premdeep sharma` on slack) is my fellow teammate interested in contributing to the community via volunteering for the deb/rpm release process and making improvements in that space.

**Comment by nikhita** [comment]
@ps882 :wave: according to [membership requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements), sponsors must be from different companies. Since both @listx and @spiffxp are from Google, you'll need to find a non-Googler sponsor.

**Comment by justaugustus** [comment]
I'll sponsor!

**Comment by justaugustus** [comment]
(Can we ensure membership is for both the `kubernetes` and `kubernetes-sigs` orgs?)

**Comment by nikhita** [comment]
Thanks @justaugustus! And considering this as a membership request for both kubernetes and kubernetes-sigs. :+1: 

@ps882 I've created PR #1121 to add you to @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get membership invite notifications for both orgs.

Welcome!! :tada: 

/assign

**Comment by ps882** [comment]
Thanks a lot ! @nikhita  @justaugustus :confetti_ball:
