### ISSUE TITLE
Rename  kubernetes-incubator/kube-arbitrator to kubernetes-incubator/kube-batch

### ISSUE THREAD

**Issue by k82cn** [kubernetes/org#112]
### Organization or repository
kubernetes-incubator

### Describe the issue
Rename kubernetes-incubator/kube-arbitrator to kubernetes-incubator/kube-batch

Approval:

https://groups.google.com/d/msgid/kubernetes-sig-scheduling/23662eac-4884-4a05-84aa-7178a98e5284%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by bsalamat** [comment]
It is fine with me.

**Comment by spiffxp** [comment]
@k82cn I can do this, but while I have your attention, two other questions:
- how would you feel about moving to the same branch requirements / code review mechanisms as all of the repos in kubernetes-sigs?  we don't currently support `require_signed_commits`, and the requirement for code reviews isn't really necessary if you use /lgtm + /approve (ref https://github.com/kubernetes/test-infra/pull/9467)
- how would you feel about moving this repo to kubernetes-sigs?

**Comment by k82cn** [comment]
wow, that'll be great if we can use /lgtm + /appove in kubernetes-sigs; it have to merge code manually righ now :(. So I'd like to see that, is there any additional requirements to do that?

/cc @bsalamat

**Comment by spiffxp** [comment]
@k82cn no additional requirements, I'll just have to make a few changes to the repo and want to make sure this is ok:
- move the repo from kubernetes-incubator/kube-arbitrator to kubernetes-sigs/kube-batch
- adjust the repo's branch protection settings so that github reviews aren't required, and signed commits aren't required (this will make it match all other repo settings in kubernetes-sigs)
- adjust kubernetes/community/sigs.yaml

**Comment by spiffxp** [comment]
/assign
Sounds good, I'll get on this shortly

**Comment by spiffxp** [comment]
@jinzhejz is not currently a member of kubernetes, just kubernetes-incubator, can you have them file a kubernetes/org issue for membership to kubernetes-sigs with sponsors?

**Comment by spiffxp** [comment]
I moved the repo to https://github.com/kubernetes-sigs/kube-batch and updated branch settings manually

I added @k82cn as an admin collaborator for now, until membership invite is accepted

**Comment by spiffxp** [comment]
/close
Left this open in case there were any hiccups, there have been none, so closing
