### ISSUE TITLE
REQUEST: New membership for liu-cong

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/org#1127]
### GitHub Username
@liu-cong

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ahg-g 
- @Huang-Wei 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   * Authored
     * https://github.com/kubernetes/kubernetes/pull/80930
     * https://github.com/kubernetes/kubernetes/pull/81614
     * https://github.com/kubernetes/kubernetes/pull/80383
     * https://github.com/kubernetes/kubernetes/pull/80811
     * https://github.com/kubernetes/kubernetes/pull/80588
  * Reviewed
     * https://github.com/kubernetes/kubernetes/pull/80144
     * https://github.com/kubernetes/kubernetes/pull/80011
     * https://github.com/kubernetes/kubernetes/pull/81148
     * https://github.com/kubernetes/kubernetes/pull/81015
     * https://github.com/kubernetes/enhancements/pull/1178
     * https://github.com/kubernetes/kubernetes/pull/80697
     * https://github.com/kubernetes/kubernetes/pull/80453
     * https://github.com/kubernetes/kubernetes/pull/80448
     * https://github.com/kubernetes/kubernetes/pull/79474
     * https://github.com/kubernetes/kubernetes/pull/79465
     * https://github.com/kubernetes/kubernetes/pull/80430

- Issues responded to
  * https://github.com/kubernetes/kubernetes/issues/81433
  * https://github.com/kubernetes/kubernetes/issues/80921
  * https://github.com/kubernetes/kubernetes/issues/80908
  * https://github.com/kubernetes/kubernetes/issues/80812
  * https://github.com/kubernetes/kubernetes/issues/80272
  * https://github.com/kubernetes/kubernetes/issues/80808
  * https://github.com/kubernetes/kubernetes/issues/80528
  * https://github.com/kubernetes/kubernetes/issues/79901
  * https://github.com/kubernetes/kubernetes/issues/81438

- SIG projects I am involved with
sig-scheduling

**Comment by Huang-Wei** [comment]
+1
for @liu-cong 's continuous contributions. Looking forward to seeing more in the future!

**Comment by ahg-g** [comment]
+1 thanks Cong

**Comment by nzoueidi** [comment]
Hey there @liu-cong, thank you for all your contributions so far :)

I've created PR #1133 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
