### ISSUE TITLE
REQUEST: New membership for nikopen

### ISSUE THREAD

**Issue by nikopen** [kubernetes/org#113]
### GitHub Username

@nikopen

### Organization you are requesting membership in

@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@guineveresaenger 
@AishSundar 
@tpepper 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   * [Fix VMWare VM freezing bug by reverting #51066](https://github.com/kubernetes/kubernetes/pull/67825)
  * cherry-picked to [1.9](https://github.com/kubernetes/kubernetes/pull/68056), [1.10](https://github.com/kubernetes/kubernetes/pull/68057), [1.11](https://github.com/kubernetes/kubernetes/pull/68058)

- SIG projects I am involved with
   * sig-release: Bug Triage Lead for 1.13 after shadowing for 1.12

**Comment by tpepper** [comment]
I support this membership and look forward to Niko's growing contributions via his 1.13 bug triage role.

**Comment by AishSundar** [comment]
+1 on Niko's org membership request. He has been a valuable member of the 1.12 release team and will be leading the bug triage role for 1.13.

**Comment by guineveresaenger** [comment]
+1 - as the 1.12 bug triage lead, Niko made valuable contributions and I look forward to him filling the role as Lead for 1.13. His contributions to the community are worthy of membership. ❤️

**Comment by spiffxp** [comment]
/unassign @calebamiles 
on this now
