### ISSUE TITLE
Audit repo permissions for release-managers team

### ISSUE THREAD

**Issue by nikhita** [kubernetes/org#1132]
### Organization or repository
kubernetes/client-go and kubernetes/website

### Users affected
@kubernetes/release-managers 

### Describe the issue
Currently, the `release-managers` team has the following permissions (ref: https://github.com/orgs/kubernetes/teams/release-managers/repositories):

- Admin access to k/k (needed for release management operations)
- Write access to k/release and k/sig-release (useful for editing PR/issue bodies, etc)
- Write access to k/client-go and k/website (not sure why this is needed)

Opening this issue so we can make sure if write access to k/client-go or k/website is needed.

IMO client-go shouldn't be needed because publishing-bot is responsible for publishing code in the repo and for the PRs that need to be merged in the k/client-go repo directly (README), we use Tide for merging.

/cc @justaugustus @idealhack @tpepper 
/sig release

**Comment by idealhack** [comment]
Maybe it's because previous release managers are doing things related but not now, this can be a cleanup task.

Copying my comments from Slack:

> k/website might be related to docs. IIRC branch managers didn't participate in that since 1.12 though.

**Comment by tpepper** [comment]
I can't think of any reason k/client-go and k/website were granted to the whole team.

**Comment by justaugustus** [comment]
+1 to removing those

**Comment by nikhita** [comment]
Removed write access to k/client-go and k/website.

/close
