### ISSUE TITLE
REQUEST: New membership for nolancon

### ISSUE THREAD

**Issue by nolancon** [kubernetes/org#1138]
### GitHub Username
nolancon

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@ConnorDoyle 
@derekwaynecarr 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/79343
https://github.com/kubernetes/kubernetes/pull/78938
https://github.com/kubernetes/kubernetes/pull/74411
https://github.com/kubernetes/kubernetes/pull/73920
https://github.com/kubernetes/kubernetes/pull/72913
https://github.com/kubernetes/kubernetes/pull/73589
https://github.com/kubernetes/website/pull/15716
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/72828
- SIG projects
SIG-Node

**Comment by nzoueidi** [comment]
Hey there @nolancon, thank you for all your contributions so far :)

I've created PR #1148  to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
