### ISSUE TITLE
REQUEST: New membership for <MJ-CJM>

### ISSUE THREAD

**Issue by MJ-CJM** [kubernetes/org#1141]
### GitHub Username
@MJ-CJM

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markthink 
- @zhangxiaoyu-zidif 
- @chenrui333 
- @Mr-Linus 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/11303
https://github.com/kubernetes/website/pull/11602
https://github.com/kubernetes/website/pull/11611
https://github.com/kubernetes/website/pull/11992
https://github.com/kubernetes/website/pull/12275
https://github.com/kubernetes/website/pull/12432
https://github.com/kubernetes/website/pull/12879
https://github.com/kubernetes/website/pull/14658
https://github.com/kubernetes/website/pull/14795
https://github.com/kubernetes/website/pull/15350
https://github.com/kubernetes/website/pull/15400
https://github.com/kubernetes/website/pull/15645
https://github.com/kubernetes/website/pull/15687
https://github.com/kubernetes/website/pull/15839
https://github.com/kubernetes/website/pull/15840
https://github.com/kubernetes/website/pull/15842
https://github.com/kubernetes/website/pull/15885
https://github.com/kubernetes/website/pull/15959

- SIG projects I am involved with

**Comment by Mr-Linus** [comment]
+1  👍

**Comment by markthink** [comment]
+1  keep it up 👍

**Comment by nzoueidi** [comment]
Hey there @MJ-CJM, thank you for all your contributions so far :)

I've created PR #1148  to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
