### ISSUE TITLE
REQUEST: New membership for scottilee

### ISSUE THREAD

**Issue by scottilee** [kubernetes/org#1142]
### GitHub Username
@scottilee

### Organization you are requesting membership in
@kubernetes-client

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yliaog
- @roycaihw
- @oz123

### List of contributions to the Kubernetes project
python-client:
- https://github.com/kubernetes-client/python/pull/786
- https://github.com/kubernetes-client/python/pull/820
- https://github.com/kubernetes-client/python/pull/846
- https://github.com/kubernetes-client/python/pull/883
- https://github.com/kubernetes-client/python/pull/938
- https://github.com/kubernetes-client/python/pull/915
- https://github.com/kubernetes-client/python/pull/916

**Comment by scottilee** [comment]
Adding @oz123 because Yu and Roy are both from Google.

**Comment by roycaihw** [comment]
+1

Welcome!

**Comment by oz123** [comment]
+1

Welcome!

**Comment by nzoueidi** [comment]
Hey @scottilee, unfortunately @oz123 can't sponsor your org membership request. Sponsors should be approvers in at least 1 owners file in any repo in the @kubernetes org. 

More information can be found here: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

Let me know if you have any questions.

**Comment by scottilee** [comment]
@micw523 I pinged you on Slack but would you be okay with sponsoring me?

**Comment by scottilee** [comment]
I'm going to close this for now, I didn't read the community-membership correctly. I will re-apply when I work with more people in the Python Client OWNERS file.
