### ISSUE TITLE
REQUEST: New membership for joonas

### ISSUE THREAD

**Issue by joonas** [kubernetes/org#1149]
### GitHub Username
@joonas

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ashish-amarnath
- @detiber 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - kubernetes-sigs/cluster-api
    - https://github.com/kubernetes-sigs/cluster-api/pull/1280
    - https://github.com/kubernetes-sigs/cluster-api/pull/1301
    - https://github.com/kubernetes-sigs/cluster-api/pull/1305
    - https://github.com/kubernetes-sigs/cluster-api/pull/1330
    - https://github.com/kubernetes-sigs/cluster-api/pull/1344
  - kubernetes-sigs/cluster-api-provider-aws
    - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1024
    - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1025
    - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1038
    - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1039
    - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1040
    - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1043
    - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1086
  - kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm
    - https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/103
    - https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/162
    - https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/163
    - https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/164
    - https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/172
    - https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/189
    - https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/195
    - https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/165
    - https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/166
  - kubernetes-sigs/cluster-api-provider-docker
    - https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/214
    - https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/225
    - https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/226
    - https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/229
    - https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/231
    - https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/237
- Issues responded to
  - kubernetes-sigs/cluster-api
    - https://github.com/kubernetes-sigs/cluster-api/issues/1266
  - kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm
    - https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/160
  - kubernetes-sigs/cluster-api-provider-docker
    - https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/230
- SIG projects I am involved with
  - [kubernetes-sigs/cluster-api](https://github.com/kubernetes-sigs/cluster-api)
  - [kubernetes-sigs/cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws)
  - [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm](https://github.com/kubernetes-sigs/bootstrap-provider-kubeadm)
  - [kubernetes-sigs/cluster-api-provider-docker](https://github.com/kubernetes-sigs/cluster-api-provider-docker)

**Comment by detiber** [comment]
+1 from me

**Comment by ashish-amarnath** [comment]
+1 from me too

**Comment by nikhita** [comment]
@joonas  thank you for your contributions to cluster-api :)

I've created #1152 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by nikhita** [comment]
https://github.com/kubernetes/org/pull/1152 has merged.
/close
