### ISSUE TITLE
REQUEST: New membership for ameukam

### ISSUE THREAD

**Issue by ameukam** [kubernetes/org#115]
### GitHub Username
@ameukam

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman
- @AishSundar 
- @guineveresaenger

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
   - https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Aameukam+archived%3Afalse+org%3Akubernetes
- Issues responded to:
  - https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Aameukam+archived%3Afalse+org%3Akubernetes
- SIG projects I am involved with
  - k/kubernetes Bug Triage Shadow 1.12, Features/Enhancements Shadow 1.13
  - Working on https://github.com/kubernetes/community/issues/2466

**Comment by AishSundar** [comment]
I would like to +1 Arnaud's membership request. He has been an active Bug triage shadow in 1.12 release and is continuing his contributions in 1.13 release cycle as well.

**Comment by guineveresaenger** [comment]
+1 from me! He was a big help finding issues that needed attention for 1.12 bug triage. 🙂

**Comment by parispittman** [comment]
+1 Arnauds help with contributor experience has been wonderful and looking forward to working with him more on our communication platform Discovery and artifacts that will come from that.
