### ISSUE TITLE
REQUEST: New membership for xianlubird

### ISSUE THREAD

**Issue by xianlubird** [kubernetes/org#1150]
### GitHub Username
@xianlubird 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andrewsykim
- @nikhita 

### List of contributions to the Kubernetes project
I have already been a kubernetes org membership.  We want to contribute our repo https://github.com/AliyunContainerService/csi-plugin to kubernetes-sigs org.  So OWNERS file need a kubernetes-sigs membership. According the rule which has no requirements if you're already a kubernetes org member, I raise a issue to apply for join kubernetes-sigs org.

The linked issue at here #1146 .

Thank you very much.

**Comment by nikhita** [comment]
@xianlubird  since you already a kubernetes org member, you don't need sponsorship for kubernetes-sigs. :)

I've created #1152 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by nikhita** [comment]
https://github.com/kubernetes/org/pull/1152 has merged.
/close
