### ISSUE TITLE
REQUEST: New membership for fredkan

### ISSUE THREAD

**Issue by fredkan** [kubernetes/org#1151]
### GitHub Username
@fredkan

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@andrewsykim
@nikhita

### List of contributions to the Kubernetes project
I am the owner of [Alibaba Cloud CSI-Plugin](https://github.com/AliyunContainerService/csi-plugin) repo, and we want to contribute the repo to kubernetes-sigs org. OWNERS file need a kubernetes-sigs membership. I raise the issue to apply for join kubernetes-sigs org.

The linked issue at here #1146 .

### PRs authored:

* [kubernetes/kubernetes#81456](https://github.com/kubernetes/kubernetes/pull/81456)
* [kubernetes/kubernetes#80904](https://github.com/kubernetes/kubernetes/pull/80904)
* [kubernetes/kubernetes-csi#114](https://github.com/kubernetes-csi/docs/pull/114)
* [kubernetes/kubernetes#69865](https://github.com/kubernetes/kubernetes/pull/69865)
* [kubernetes/kubernetes#80686](https://github.com/kubernetes/kubernetes/pull/80686)
* [kubernetes/kubernetes-sigs#50](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/50)

Thank you very much.

**Comment by resouer** [comment]
+1

**Comment by zhangxiaoyu-zidif** [comment]
+1

**Comment by nzoueidi** [comment]
Hey @fredkan I am waiting for another non-Alibaba sponsor so I can proceed with your membership request.

**Comment by huangyuqi** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by edisonxiang** [comment]
+1

**Comment by shashidharatd** [comment]
+1

**Comment by xlgao-zju** [comment]
+1

**Comment by nikhita** [comment]
@fredkan I've created #1152 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification. :)

Welcome to @kubernetes-sigs! 🎉

/assign
