### ISSUE TITLE
REQUEST: New membership for gjtempleton

### ISSUE THREAD

**Issue by gjtempleton** [kubernetes/org#1153]
### GitHub Username

@gjtempleton

### Organization you are requesting membership in

@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @maciekpytel
- @mikesplain 

### List of contributions to the Kubernetes project

- PRs reviewed / authored

https://github.com/kubernetes/kops/pull/7404
https://github.com/kubernetes/kops/pull/7400
https://github.com/kubernetes/kops/pull/7164
https://github.com/kubernetes/kops/pull/7376
https://github.com/kubernetes/kubernetes/pull/78503
https://github.com/kubernetes/kubernetes/pull/76058
https://github.com/kubernetes/kubernetes/pull/80075
https://github.com/kubernetes/autoscaler/pull/2008
https://github.com/kubernetes/website/pull/14865
https://github.com/kubernetes/website/pull/14728
https://github.com/kubernetes/website/pull/14041
https://github.com/kubernetes/autoscaler/pull/2291
https://github.com/kubernetes/autoscaler/pull/2290
https://github.com/kubernetes/autoscaler/pull/2289

- Issues responded to

https://github.com/kubernetes/client-go/issues/358

- SIG projects I am involved with

SIG-Autoscaling
SIG-ClusterLifecycle

**Comment by mikesplain** [comment]
+1! @gjtempleton has been an asset for the Kops team and across the board on Kubernetes.  We look forward to his continued contributions!

/lgtm

**Comment by MaciekPytel** [comment]
+1 @gjtempleton is an active memeber of sig-autoscaling and a contributor to Cluster Autoscaler project in particular.

**Comment by justaugustus** [comment]
@gjtempleton -- Thanks so much for your contributions thus far!
I've created #1155 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign

**Comment by Jeffwan** [comment]
+1 @gjtempleton
