### ISSUE TITLE
REQUEST: New membership for eloyekunle

### ISSUE THREAD

**Issue by eloyekunle** [kubernetes/org#1157]
### GitHub Username
@eloyekunle

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @maciaszczykm 
- @sttts

### PRs reviewed / authored

The following list is automatically generated using https://github.com/nikhita/github-contrib.

**Repository: kubernetes**

Pull Requests: 4
1. [kubernetes/kubernetes#81507](https://github.com/kubernetes/kubernetes/pull/81507) - update scale client to support non-namespaced resources
2. [kubernetes/kubernetes#81356](https://github.com/kubernetes/kubernetes/pull/81356) - use subtest for table units (pkg/scheduler/*)
3. [kubernetes/kubernetes#75826](https://github.com/kubernetes/kubernetes/pull/75826) - Nit: Fix in deviceplugin api description
4. [kubernetes/kubernetes#73369](https://github.com/kubernetes/kubernetes/pull/73369) - Fixes Golint Errors: staging/src/k8s.io/kube-aggregator

Total Issues Opened: 2
1. [kubernetes/kubernetes#81380](https://github.com/kubernetes/kubernetes/issues/81380) - scale client: support non-namespaced resources
2. [kubernetes/kubernetes#78824](https://github.com/kubernetes/kubernetes/issues/78824) - Field Selector not applied in fake clients List

**Repository: dashboard**

Total Pull Requests Created: 27
1. [kubernetes/dashboard#4195](https://github.com/kubernetes/dashboard/pull/4195) - Support 'Scale' subresource for CRDs
2. [kubernetes/dashboard#4189](https://github.com/kubernetes/dashboard/pull/4189) - Improve Namespace-awareness for CRDs
3. [kubernetes/dashboard#4161](https://github.com/kubernetes/dashboard/pull/4161) - CRD - e2e Tests
4. [kubernetes/dashboard#4159](https://github.com/kubernetes/dashboard/pull/4159) - Implement Resource Menu Pinning
5. [kubernetes/dashboard#4156](https://github.com/kubernetes/dashboard/pull/4156) - Show time tooltips for events FirstSeen and LastSeen
6. [kubernetes/dashboard#4155](https://github.com/kubernetes/dashboard/pull/4155) - Implement CRD Objects Events Section
7. [kubernetes/dashboard#4151](https://github.com/kubernetes/dashboard/pull/4151) - Use binary search in getLineIndex method
8. [kubernetes/dashboard#4130](https://github.com/kubernetes/dashboard/pull/4130) - Add context menus in list views for cluster resources
9. [kubernetes/dashboard#4103](https://github.com/kubernetes/dashboard/pull/4103) - Make Resource information card title consistent
10. [kubernetes/dashboard#4030](https://github.com/kubernetes/dashboard/pull/4030) - CRD Support - Frontend
11. [kubernetes/dashboard#4002](https://github.com/kubernetes/dashboard/pull/4002) - Migrate e2e tests to Cypress
12. [kubernetes/dashboard#3995](https://github.com/kubernetes/dashboard/pull/3995) - Add go modules verification and update scripts
13. [kubernetes/dashboard#3994](https://github.com/kubernetes/dashboard/pull/3994) - Nit: Update comment in Github PR template
14. [kubernetes/dashboard#3938](https://github.com/kubernetes/dashboard/pull/3938) - Download golangci-lint via curl
15. [kubernetes/dashboard#3886](https://github.com/kubernetes/dashboard/pull/3886) - Update to client-go kubernetes-1.14.0
16. [kubernetes/dashboard#3885](https://github.com/kubernetes/dashboard/pull/3885) - Update go-restful to the latest version
17. [kubernetes/dashboard#3878](https://github.com/kubernetes/dashboard/pull/3878) - Migrate from dep to go mod
18. [kubernetes/dashboard#3877](https://github.com/kubernetes/dashboard/pull/3877) - Remove redundant namespace filters
19. [kubernetes/dashboard#3843](https://github.com/kubernetes/dashboard/pull/3843) - CRD Support - Backend
20. [kubernetes/dashboard#3810](https://github.com/kubernetes/dashboard/pull/3810) - Update style format message to correct npm script
21. [kubernetes/dashboard#3630](https://github.com/kubernetes/dashboard/pull/3630) - Replace history when the log page appends container param
22. [kubernetes/dashboard#3590](https://github.com/kubernetes/dashboard/pull/3590) - Switch chart engine from nvd3 to c3
23. [kubernetes/dashboard#3586](https://github.com/kubernetes/dashboard/pull/3586) - Fix bug in CPU allocation chart
24. [kubernetes/dashboard#3562](https://github.com/kubernetes/dashboard/pull/3562) - Display query in search bar after namespace change and page reload
25. [kubernetes/dashboard#3561](https://github.com/kubernetes/dashboard/pull/3561) - Logs Auto Scroll
26. [kubernetes/dashboard#3559](https://github.com/kubernetes/dashboard/pull/3559) - Added tooltip for Timestamp icon on Logs page
27. [kubernetes/dashboard#3558](https://github.com/kubernetes/dashboard/pull/3558) - Show light-colored scrollbar in dark logs mode

Total Issues Opened: 10
1. [kubernetes/dashboard#4167](https://github.com/kubernetes/dashboard/issues/4167) - Support 'Scale' subresource for CRDs
2. [kubernetes/dashboard#4153](https://github.com/kubernetes/dashboard/issues/4153) - [Parent Issue]: Add e2e Tests
3. [kubernetes/dashboard#4123](https://github.com/kubernetes/dashboard/issues/4123) - Implement CRD Object Detail Page
4. [kubernetes/dashboard#4027](https://github.com/kubernetes/dashboard/issues/4027) - Enable Angular Ivy
5. [kubernetes/dashboard#3993](https://github.com/kubernetes/dashboard/issues/3993) - Verify vendored modules in pull requests
6. [kubernetes/dashboard#3884](https://github.com/kubernetes/dashboard/issues/3884) - Upgrade go-restful to latest version
7. [kubernetes/dashboard#3631](https://github.com/kubernetes/dashboard/issues/3631) - Show tooltip timestamp on time hover across pages
8. [kubernetes/dashboard#3585](https://github.com/kubernetes/dashboard/issues/3585) - Misplaced labels on the Nodes CPU allocation chart
9. [kubernetes/dashboard#3567](https://github.com/kubernetes/dashboard/issues/3567) - Prevent page exit on the create page when there are unsaved changes
10. [kubernetes/dashboard#3557](https://github.com/kubernetes/dashboard/issues/3557) - Logs scrollbar not showing in dark mode

Total Pull Requests Reviewed: 1
1. [kubernetes/dashboard#3767](https://github.com/kubernetes/dashboard/pull/3767) - Show tooltip timestamp on time hover across pages

**Repository: minikube**

Total Pull Requests Created: 1
1. [kubernetes/minikube#3715](https://github.com/kubernetes/minikube/pull/3715) - Fix code block highlight in README

**Repository: community**

Total Pull Requests Created: 1
1. [kubernetes/community#3797](https://github.com/kubernetes/community/pull/3797) - Update meeting time for SIG-UI Bi-Weekly

### Issues responded to

1. https://github.com/kubernetes/kubernetes/issues/49964 - Hardware topology awareness at node level (including NUMA)
2. https://github.com/kubernetes/kubernetes/issues/52757 - Is sharing GPU to multiple containers feasible?
3. https://github.com/kubernetes/kubernetes/issues/66749 - ADDRESS column is empty in "kubectl get ingress"
4. https://github.com/kubernetes/kubernetes/issues/78707 - Some CRDs that duplicate built-in group/version/kinds reap built-in etcd data on deletion
5. https://github.com/kubernetes/gengo/pull/116 - import-boss: add inverse import rules
6. https://github.com/kubernetes/dashboard/issues/3936 - Investigate to use `go mod` in Travis CI
7. https://github.com/kubernetes/dashboard/pull/3935 - Disable `go mod` once in travis
8. https://github.com/kubernetes/dashboard/issues/3921 - Migrate e2e tests to Cypress
9. https://github.com/kubernetes/dashboard/issues/3900 - Use binary search in getLineIndex method
10. https://github.com/kubernetes/dashboard/issues/3870 - Update to the new client-go
11. https://github.com/kubernetes/dashboard/pull/3795 - Fix ts errors
12. https://github.com/kubernetes/dashboard/pull/3643 - added tooltips to event timestamps
13. https://github.com/kubernetes/dashboard/issues/3609 - Navigating back from logs does not work properly.
14. https://github.com/kubernetes/dashboard/issues/3602 - Unable to switch containers in the terminal
15. https://github.com/kubernetes/dashboard/issues/3571 - Use c3 instead of nvd3
16. https://github.com/kubernetes/dashboard/issues/3509 - Support following logs
17. https://github.com/kubernetes/dashboard/issues/3502 - Do not remove query after namespace change and page reload
18. https://github.com/kubernetes/dashboard/issues/3440 - Complete Angular migration
19. https://github.com/kubernetes/dashboard/issues/2493 - Support Custom Resource Definitions

### SIG projects I am involved with
1. SIG-UI
2. SIG-API Machinery

**Comment by maciaszczykm** [comment]
+1 from my side

**Comment by nikhita** [comment]
+1

**Comment by sttts** [comment]
+1

**Comment by nikhita** [comment]
@eloyekunle Thank your contributions with the kubernetes dashboard :)

I've created #1163 to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification. :)

Welcome to @kubernetes! 🎉

/assign
