### ISSUE TITLE
migrate kubernetes-incubator/reference-docs

### ISSUE THREAD

**Issue by jimangel** [kubernetes/org#1158]
### New Repo, Staging Repo, or migrate existing
migrate existing (https://github.com/kubernetes-incubator/reference-docs)

### Requested name for new repository
reference-docs

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
- bradamant3
- jimangel
- zacharysarah

### If not a staging repo, who should have write access
- tengqm
- kbhawkey

### If not a staging repo, who should be listed as approvers in OWNERS
- bradamant3
- bradtopol
- kbarnard10
- steveperry-53
- tengqm
- zacharysarah
- zparnold
- kbhawkey

### If not a staging repo, who should be listed in SECURITY_CONTACTS
- bradamant3
- jimangel
- zacharysarah
- tengqm

### What should the repo description be
Tools to build reference documentation for Kubernetes APIs and CLIs.

### What SIG and subproject does this fall under in sigs.yaml
This is a subproject of sig-docs

### Approvals
This subproject, reference-docs, is outlined as being [in-scope](https://github.com/kubernetes/community/blob/master/sig-docs/charter.md#in-scope) as part of the sig-docs charter. An issue https://github.com/kubernetes/website/issues/13904 was opened after the 1.14 release about this repo moving locations as well as discussed in the 9/3 sig-docs community meeting.

### Additional context for request
Since this repo is used for each release and iterated on, I would like to `/hold` the migration until 1.16 is out the door.

Addt'l items:
- We'll need to PR fixes to these references
  - https://github.com/kubernetes/website/search?q=kubernetes-incubator%2Freference-docs&type=Code
  - https://github.com/kubernetes/community/tree/master/sig-docs#reference-docs
- We'll need to merge or hold: https://github.com/kubernetes-incubator/reference-docs/pull/82
- Related k/website issue for tracking: https://github.com/kubernetes/website/issues/13904

Note: I took a guess at which users should be included as well as permissions. It could use a second set of :eyes: 

/cc @zacharysarah @bradamant3 @kbarnard10 @simplytunde @tengqm @kbhawkey

**Comment by mrbobbytables** [comment]
I've created the PR #1231 to add the additional members to k-sigs and migrate the teams. Once it merges, should be able to move the repo 👍

**Comment by mrbobbytables** [comment]
The Repo has been migrated and is now at: https://github.com/kubernetes-sigs/reference-docs

OWNERS update is here: https://github.com/kubernetes-sigs/reference-docs/pull/92

**Comment by mrbobbytables** [comment]
The repo relocation update to sigs.yaml is here: https://github.com/kubernetes/community/pull/4123

Once all PRs have merged, the migration should be complete and the issue can be closed 👍

**Comment by mrbobbytables** [comment]
All PRs merged, things should be good to go!

Ping me if you have any problems 👍 

/close

**Comment by zacharysarah** [comment]
Thanks, @mrbobbytables! 
/pony
