### ISSUE TITLE
REQUEST: New membership for <haoshuwei>

### ISSUE THREAD

**Issue by haoshuwei** [kubernetes/org#1162]
### GitHub Username
@haoshuwei

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@fredkan
@nikhita

### List of contributions to the Kubernetes project
I am the member of the AlibabaCloud Container Service Team and I am focus on developing and improving the [kubernetes-sigs/alibaba-cloud-csi-driver](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver) project, some PRs contributed listed below:

#### PRs authored:
- [kubernetes/kubernetes-sigs#55](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/55)
- [kubernetes/kubernetes-sigs#76](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/76)
- [kubernetes/kubernetes-sigs#78](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/78)
- [kubernetes/kubernetes-sigs#82](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/82)
- [kubernetes/kubernetes-sigs#84](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/84)
- [kubernetes/kubernetes-sigs#85](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/85)

Thank you very much.

**Comment by fredkan** [comment]
+1

**Comment by nikhita** [comment]
+1

**Comment by nikhita** [comment]
@haoshuwei I've created #1163 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification. :)

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by haoshuwei** [comment]
> @haoshuwei I've created #1163 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification. :)
> 
> Welcome to @kubernetes-sigs! 🎉
> 
> /assign

**Comment by haoshuwei** [comment]
@nikhita Thanks very much!
