### ISSUE TITLE
REQUEST: New membership for brysonshepherd

### ISSUE THREAD

**Issue by brysonshepherd** [kubernetes/org#1165]
### GitHub Username
@brysonshepherd

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @feiskyer
- @cantbewong

### List of contributions to the Kubernetes project
- SIG projects I am involved with
1. sig-vmware (now provider-vsphere under SIG Cloud Provider)
2. sig-azure (now provider-azure under SIG Cloud Provider)
3. sig-cluster-lifecycle

- Issues responded to

1. https://github.com/kubernetes/kubeadm/issues/1054
2. https://github.com/kubernetes/kubernetes/issues/82408

**Comment by justaugustus** [comment]
+1 (on behalf of the subproject formerly known as SIG Azure)!

**Comment by cantbewong** [comment]
+1 Bryson has been a valuable contributor in SIG VMware and on Slack on matters related to Kubernetes running on vSphere

**Comment by feiskyer** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @brysonshepherd , thank you for all your contributions so far :)

I've created PR #1181   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
