### ISSUE TITLE
REQUEST: New membership for hannibalhuang

### ISSUE THREAD

**Issue by hannibalhuang** [kubernetes/org#1167]
### GitHub Username
@hannibalhuang

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @k82cn 
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
co-lead for [wg-policy](https://github.com/kubernetes/community/tree/master/wg-policy)

**Comment by dims** [comment]
welcome @hannibalhuang ! +1 from me.

**Comment by hannibalhuang** [comment]
in reference to https://github.com/kubernetes/community/issues/3945

**Comment by mrbobbytables** [comment]
+1 here too :)

**Comment by k82cn** [comment]
+1

**Comment by mrbobbytables** [comment]
@hannibalhuang , thank you for all your help organizing wg-policy! :D

I've created PR #1172  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by hannibalhuang** [comment]
> @hannibalhuang , thank you for all your help organizing wg-policy! :D
> 
> I've created PR #1172 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉
> 
> /assign

Thanks Bob :)
