### ISSUE TITLE
REQUEST: New membership for sbueringer

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/org#1169]
### GitHub Username
@sbueringer

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jichenjc 
- @adisky 
- @detiber 
- @chrigl 

### List of contributions to the Kubernetes project
* I'm already member in the @kubernetes-sigs org for a while and have been actively contribution to ClusterAPI OpenStack: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/graphs/contributors
* I'm not sure what the current status on this issue is: https://github.com/kubernetes/org/issues/966 :)

**Comment by jichenjc** [comment]
+1 to me , thanks

**Comment by chrigl** [comment]
I'm not in the owners file of a k-repo. But I would like to see @sbueringer becoming a member.
@adisky Could you support him?

**Comment by adisky** [comment]
+1 from me!! :)

**Comment by detiber** [comment]
+1 from me as well :)

**Comment by mrbobbytables** [comment]
@sbueringer , thank you for all your help with the CAPI OpenStack provider :D

I've created PR #1181   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by sbueringer** [comment]
@mrbobbytales Thx 😀
