### ISSUE TITLE
REQUEST: New membership for jaypipes

### ISSUE THREAD

**Issue by jaypipes** [kubernetes/org#1170]
### GitHub Username
@jaypipes 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @castrojo
- @zacharysarah 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
[k8s.io PRs](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ajaypipes+archived%3Afalse+kubernetes)
[sigs.k8s.io PRs](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ajaypipes+archived%3Afalse+kubernetes-sigs)
- Issues responded to
[k8s.io issues](https://github.com/issues?utf8=%E2%9C%93&q=author%3Ajaypipes+archived%3Afalse+kubernetes)
[sigs.k8s.io issues](https://github.com/issues?utf8=%E2%9C%93&q=author%3Ajaypipes+archived%3Afalse+kubernetes-sigs)
- SIG projects I am involved with
sig-docs, sig-node, sig-autoscaling
Less so on: sig-cloud-provider, sig-auth, sig-architecture

**Comment by castrojo** [comment]
+1 from me!

**Comment by zacharysarah** [comment]
+1 from me, @jaypipes contributes valuable reviews to docs.

**Comment by nikhita** [comment]
+1 from me too :)

**Comment by mrbobbytables** [comment]
its not needed, but +1 here too :P 

/pony yay

**Comment by mrbobbytables** [comment]
@jaypipes  thank you for all your contributions so far :D

I've created PR #1172  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by jaypipes** [comment]
Thanks, y'all :)
