### ISSUE TITLE
REQUEST: New membership for dhellmann

### ISSUE THREAD

**Issue by dhellmann** [kubernetes/org#1171]
### GitHub Username
@dhellmann

### Organization you are requesting membership in
@kubernetes-sig

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @detiber 
- @hogepodge 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api/pull/1001
- Issues responded to
  - https://github.com/kubernetes-sigs/cluster-api/pull/882
  - https://github.com/kubernetes-sigs/cluster-api/pull/967
  - https://github.com/kubernetes-sigs/cluster-api/pull/997
  - https://github.com/kubernetes-sigs/cluster-api/pull/1081
- SIG projects I am involved with
  - discussions about the cluster-api v1alpha2 and later designs

**Comment by detiber** [comment]
+1 from me

**Comment by hogepodge** [comment]
+1 /lgtm

Doug is an excellent technical contributor, and has already made significant contributions through the Metal3 project to enable open source bare-metal provisioning through Cluster API.

**Comment by mrbobbytables** [comment]
@dhellmann , thank you for all your contributions to the cluster-api 👍 

I've created PR #1172  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
