### ISSUE TITLE
REQUEST: New membership for everpeace

### ISSUE THREAD

**Issue by everpeace** [kubernetes/org#1173]
### GitHub Username
@everpeace

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @k82cn 
- @draveness 
- @hex108 

### List of contributions to the Kubernetes project
- PRs reviewed / authored: kubernetes/kubernetes#82483 , kubernetes/kubernetes#81698, kubernetes/kubernetes#81263, kubernetes/kubernetes#72619
- Issues responded to kubernetes/kubernetes#72278, kubernetes/kubernetes#49964
- SIG projects I am involved with sig-scheduling

**Comment by draveness** [comment]
+1 Thanks for your contribution

Regards,
Draven

**Comment by hex108** [comment]
+1 Thanks for your contribution

**Comment by k82cn** [comment]
+1, thanks for your contribution :)

**Comment by everpeace** [comment]
@k82cn Thanks for guiding me on how to handle the issue in my PR https://github.com/kubernetes/org/pull/1174#issuecomment-529796144.

>  IMO, that should be ok to only contain reviewers/approvers of sigs of those team :)

I will be waiting for the response from [GitHub Administration Team](https://github.com/kubernetes/community/blob/master/github-management/README.md#github-administration-team) as described the [doc](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

> If we want to add/update reviewers/approver, please open PR in k/k against OWNERS_ALIAS.

And I will happily open k/k repo issue too!

**Comment by everpeace** [comment]
> And let me try to open k/k repo issue too!

I realized I'm not qualified yet. I will try to review PRs to qualify to become a reviewer.

https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer
> member for at least 3 months

**Comment by k82cn** [comment]
> I realized I'm not qualified yet. I will try to review PRs to qualify to become a reviewer.

That's great! Looking forward your contribution :)

**Comment by mrbobbytables** [comment]
@everpeace thanks for your contributions and help with sig-scheduling :)

I've created PR #1181   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by everpeace** [comment]
@mrbobbytables Thank you very much!!
