### ISSUE TITLE
Migrate descheduler to kubernetes-sigs

### ISSUE THREAD

**Issue by k82cn** [kubernetes/org#1176]
### New Repo, Staging Repo, or migrate existing

migrate existing (https://github.com/kubernetes-incubator/descheduler/)

### Requested name for new repository

descheduler

### Which Organization should it reside

kubernetes-sigs

### If not a staging repo, who should have admin access

@ravisantoshgudimetla , @aveshagarwal , @k82cn

### If not a staging repo, who should have write access

@ravisantoshgudimetla , @aveshagarwal , @k82cn

### If not a staging repo, who should be listed as approvers in OWNERS

@ravisantoshgudimetla , @aveshagarwal , @k82cn

### If not a staging repo, who should be listed in SECURITY_CONTACTS

@ravisantoshgudimetla  , @aveshagarwal , @k82cn

### What should the repo description be

 Descheduler, based on its policy, finds pods that can be moved and evicts them. Used to be rescheduler.

### What SIG and subproject does this fall under in sigs.yaml

sig-scheduling

### Approvals

https://groups.google.com/forum/#!topic/kubernetes-sig-scheduling/Zpj7t3v-6aY

### Additional context for request

None

**Comment by aveshagarwal** [comment]
Please make sure that during this migration, history remains intact (regarding commits, stars etc.) and https://github.com/kubernetes-incubator/descheduler redirects to the new repo location.

**Comment by mrbobbytables** [comment]
@aveshagarwal The full history will be left intact :) 

A redirect is automatically put in place by GitHub (we don't have control over it). 

If you want to take a look at a repo that has previously been moved, a recent example is the service-catalog:
- Request to move: https://github.com/kubernetes/org/issues/882
- kubernetes-sigs repo: https://github.com/kubernetes-sigs/service-catalog
- incubator repo (redirects): https://github.com/kubernetes-incubator/service-catalog

**Comment by aveshagarwal** [comment]
@mrbobbytables Just wanted to make sure. Thanks for your help.

**Comment by mrbobbytables** [comment]
Added @ravisantoshgudimetla and @aveshagarwal to kubernetes-sigs in #1179 
Added teams for descheduler in #1180 

once those 2 merge, I can move the repo over :)

**Comment by mrbobbytables** [comment]
One slight hiccup -- it looks like the repo has some integrations with the openshift ci system that were setup early last year:
- https://github.com/openshift/release/blob/master/ci-operator/jobs/kubernetes-incubator/descheduler/kubernetes-incubator-descheduler-master-presubmits.yaml
- https://github.com/openshift/release/pull/683

@ingvagabund Do you know if this integration is still needed?

**Comment by mrbobbytables** [comment]
All outstanding items have been completed. I'm going to go ahead and close the issue. 

If you have any problems, feel free to reopen or ping me on slack 👍 

/close
