### ISSUE TITLE
REQUEST: New membership for dtaniwaki

### ISSUE THREAD

**Issue by dtaniwaki** [kubernetes/org#1178]
### GitHub Username
dtaniwaki

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @liggitt 
- @janetkuo 
- @soltysh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/80802 
https://github.com/kubernetes/kubernetes/pull/71447
https://github.com/kubernetes/kubernetes/pull/70470
https://github.com/kubernetes/kubernetes/pull/70127
https://github.com/kubernetes/kubernetes/pull/69279
https://github.com/kubernetes/kubernetes/pull/65582
https://github.com/kubernetes/kubernetes/pull/65351

**Comment by liggitt** [comment]
+1

**Comment by janetkuo** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @dtaniwaki -- I hate to be a stickler, but do you happen to know a non-googler that might be able to sponsor you? Sponsors must be from different member organizations per the [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#member).

**Comment by nikhita** [comment]
@dtaniwaki thank you for your contributions thus far :)

I've created PR #1188 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by dtaniwaki** [comment]
@liggitt @janetkuo @soltysh
Thank you for giving me +1!

@mrbobbytables @nikhita
Thank you for adding me to the org!

See you guys in the contributor summit of KubeCon 2019 NA.
