### ISSUE TITLE
k8s-infra-team github team in k8s org

### ISSUE THREAD

**Issue by dims** [kubernetes/org#118]
### Organization or repository
kubernetes

### Users effected
folks on k8s-infra-team on slack

### Describe the issue
We need a (single) github team for general awareness, notification, and assignment of issues and pr's relating to the k8s infra team working on transfer of infrastructure from google to CNCF effort.

**Comment by dims** [comment]
cc @cblecker @thockin @idvoretskyi @ixdy @BenTheElder @roberthbailey @timothysc @stevekuznetsov @brendandburns

**Comment by idvoretskyi** [comment]
+1

**Comment by cblecker** [comment]
@kubernetes/k8s-infra-team already exists.. or are you asking for something else? :)

**Comment by dims** [comment]
Duh! thanks @cblecker
