### ISSUE TITLE
REQUEST: New membership for resouer

### ISSUE THREAD

**Issue by resouer** [kubernetes/org#1183]
### GitHub Username
@resouer 

### Organization you are requesting membership in
@kubernetes-sigs 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Huang-Wei 
- @k82cn 

### List of contributions to the Kubernetes project
- PRs reviewed / authored: https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+author%3Aresouer
- SIG projects I am involved with: SIG node, SIG scheduling, SIG multi-tenancy

**Comment by Huang-Wei** [comment]
+1

**Comment by k82cn** [comment]
+1

**Comment by resouer** [comment]
kindly ping @nikhita , PTAL

**Comment by mrbobbytables** [comment]
Just as an FYI -- as a member of the Kubernetes org, you implicitly have permission to join any of the other kubernetes organizations without seeking further sponsorship. 😄 

 It's just the inverse -- e.g. if you're only a member of kubernetes-sigs and requesting to join kubernetes-csi you would need to find additional sponsors where its the case.

**Comment by nikhita** [comment]
@resouer I've created PR #1188 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification. :)

Welcome to @kubernetes-sigs! 🎉

/assign
