### ISSUE TITLE
REQUEST: New membership for fredkan

### ISSUE THREAD

**Issue by fredkan** [kubernetes/org#1184]
## GitHub Username
@fredkan

## Organization you are requesting membership in
@kubernetes

## Requirements
* [x]  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
* [x]  I have enabled 2FA on my GitHub account (https://github.com/settings/security)
* [x]  I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
* [x]  I am actively contributing to 1 or more Kubernetes subprojects
* [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
* [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

## Sponsors
- @cheyang
- @shashidharatd

## List of contributions to the Kubernetes project
I am a kubernetes-sigs org membership and the owner of [kubernetes-sigs/alibaba-cloud-csi-driver](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver), and have great interest to review and submit PRs to Kubernetes community. 

I am the member of the AlibabaCloud Container Service Team and developing and improving the [kubernetes/cloud-provider-alibaba-cloud](https://github.com/kubernetes/cloud-provider-alibaba-cloud).

## PRs authored:
kubernetes/kubernetes#81456
kubernetes/kubernetes#80904
kubernetes/kubernetes#69865
kubernetes/kubernetes#80686
https://github.com/kubernetes-csi/docs/pull/114

https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/50
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/81
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/71
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/70
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/52
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/47
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/64

Thank you very much.

**Comment by fredkan** [comment]
> Hey there @fredkan, unfortunately @xianlubird cannot sponsor you for membership in the @kubernetes org, but CAN sponsor you for membership in @kubernetes-sigs.
> 
> An approver/reviewer in @kubernetes, may sponsor someone for the @kubernetes org or any of the related organizations (@kubernetes-sigs, @kubernetes-csi etc); as long as it's a project they're involved with.
> 
> However, this does not work the other way around. A sponsor that is only an approver/reviewer in @kubernetes-csi cannot sponsor someone for membership in @kubernetes. They are scoped just to the org they're associated with.
> 
> @fredkan If you'd like to amend your request to just @kubernetes-sigs, we can proceed with getting your membership processed. Otherwise, if you could, please find another sponsor from the @kubernetes org.
> 
> If you have any questions don't be afraid to ask.
> 
> Thanks!

Thank you very much for your clarification, Sponsors is updated. Thanks.

**Comment by cheyang** [comment]
+1

**Comment by mrbobbytables** [comment]
@fredkan, thank you for all your contributions so far :)

I've created PR #1193  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by fredkan** [comment]
> @fredkan, thank you for all your contributions so far :)
> 
> I've created PR #1193 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉
> 
> /assign

Thank you very much! @mrbobbytables
