### ISSUE TITLE
REQUEST: New membership for sallyom

### ISSUE THREAD

**Issue by sallyom** [kubernetes/org#1186]
### GitHub Username
@sallyom

### Organization you are requesting membership in
@kubernetes @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @soltysh
- @seans3

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/82660
https://github.com/kubernetes/kubernetes/pull/82423
https://github.com/kubernetes/kubernetes/pull/82442
https://github.com/kubernetes/kubernetes/pull/79207
https://github.com/kubernetes/kubernetes/pull/79205
https://github.com/kubernetes/kubernetes/pull/79202
https://github.com/kubernetes/kubernetes/pull/78991
- SIG projects I am involved with
cli, multitenacy

**Comment by nikhita** [comment]
+100 :)

**Comment by nikhita** [comment]
@sallyom thank you for your contributions thus far :)

I've created PR #1188 to add you to the kubernetes and kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.

Welcome!! 🎉

/assign

**Comment by soltysh** [comment]
:+1:
