### ISSUE TITLE
REQUEST: New membership for robscott

### ISSUE THREAD

**Issue by robscott** [kubernetes/org#1187]
### GitHub Username
@robscott

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @freehan 
- @khenidak

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/kubernetes/pull/80766
- https://github.com/kubernetes/kubernetes/pull/81048
- https://github.com/kubernetes/kubernetes/pull/81430
- https://github.com/kubernetes/kubernetes/pull/81795
- https://github.com/kubernetes/kubernetes/pull/81815
- https://github.com/kubernetes/kubernetes/pull/82139
- https://github.com/kubernetes/kubernetes/pull/82153
- https://github.com/kubernetes/kubernetes/pull/82289
- https://github.com/kubernetes/kubernetes/pull/82380
- https://github.com/kubernetes/kubernetes/pull/82393
- https://github.com/kubernetes/kubernetes/pull/82397
- https://github.com/kubernetes/website/pull/3494
- https://github.com/kubernetes/website/pull/16018
- https://github.com/kubernetes/website/pull/16267

**Comment by nikhita** [comment]
@robscott thank you for your contributions thus far :)

I've created PR #1188 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
