### ISSUE TITLE
REQUEST: New membership for holgpar

### ISSUE THREAD

**Issue by holgpar** [kubernetes/org#1189]
### GitHub Username
holgpar

### Organization you are requesting membership in
sig Multi-tenancy

### Requirements
- [ x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ ] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- (at)sponsor-1
- (at)sponsor-2

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by mrbobbytables** [comment]
Hey there @holgpar, have you looked for sponsors? If you haven't discussed it with folks yet, it might be worth to close the issue and reopen it when you've found two that meet the [sponsorship requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

Also as an FYI -- you don't need to specify a  sig you're looking to join, but one of the [kubernetes github orgs](https://github.com/kubernetes/community/tree/master/github-management#actively-used-github-organizations). You may want to check out the [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md) for more info.

**Comment by mrbobbytables** [comment]
@holgpar I'm going to go ahead and close this issue for now. Please feel free to reopen when you're ready to apply 👍 

/close
