### ISSUE TITLE
REQUEST: New membership for ysyukr

### ISSUE THREAD

**Issue by ysyukr** [kubernetes/org#1190]
### GitHub Username
@ysyukr

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gochist
- @seokho-son

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/search?q=org%3Akubernetes+is%3Apr+is%3Amerged+author%3Aysyukr
- Issues responded to
  https://github.com/kubernetes/website/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Aysyukr
- SIG projects I am involved with
  kubernetes/sig-docs

**Comment by gochist** [comment]
+1 @ysyukr is one of the most passionate members for Korean localization.

**Comment by seokho-son** [comment]
+1, I am happy to sponsor @ysyukr  :)

**Comment by ianychoi** [comment]
+1 agreed as another Korean localization reviewer

**Comment by ysyukr** [comment]
@gochist , @seokho-son , @ianychoi 
Thanks to the members of the Korea l10n team for reviewing and helping with my translation. :)

**Comment by mrbobbytables** [comment]
Hey there @ysyukr , thank you for all your localization efforts \o/

I've created PR #1193  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
