### ISSUE TITLE
REQUEST: New membership for DahuK

### ISSUE THREAD

**Issue by DahuK** [kubernetes/org#1194]
### GitHub Username
@DahuK

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xianlubird 
- @bluebreezecf 
- @k82cn 

### List of contributions to the Kubernetes project

I am the member of the AlibabaCloud Container Service Team and I am focus on developing and improving the [kubernetes-sigs/alibaba-cloud-csi-driver](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver) project, some PRs contributed listed below:

#### PRs authored:
- [kubernetes/alibaba-cloud-csi-driver#74](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/74)
- [kubernetes/alibaba-cloud-csi-driver#86](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/86)
- [kubernetes/alibaba-cloud-csi-driver#87](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/87)
- [kubernetes/alibaba-cloud-csi-driver#88](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/88)
- [kubernetes/alibaba-cloud-csi-driver#89](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/89)

Thank you very much.

**Comment by fredkan** [comment]
+1

**Comment by xianlubird** [comment]
+1

**Comment by haoshuwei** [comment]
+1

**Comment by k82cn** [comment]
+1, thanks for your contribution :)

**Comment by mrbobbytables** [comment]
Hey there @DahuK , thank you for all your contributions so far :)

I've created PR #1200  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by DahuK** [comment]
@mrbobbytables @k82cn @xianlubird @fredkan Thanks so much!!
