### ISSUE TITLE
REQUEST: New membership for Ahmad Diaa

### ISSUE THREAD

**Issue by ahmad-diaa** [kubernetes/org#1195]
### GitHub Username
@ahmad-diaa

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Huang-Wei 
- @alculquicondor 

### List of contributions to the Kubernetes project
- PRs Contributed To
  - kubernetes/kubernetes#66948
  - kubernetes/kubernetes#67788 
  - kubernetes/kubernetes#81207
  - kubernetes/kubernetes#82040
  - kubernetes/kubernetes#82283
  - kubernetes/kubernetes#82732
- WIP PRs
  - kubernetes/kubernetes#81374
  - kubernetes/kubernetes#81911
  - kubernetes/kubernetes#82735
- Issues responded to
  - kubernetes/kubernetes#71859
  - kubernetes/kubernetes#72547
  - kubernetes/kubernetes#82306
- SIG projects I am involved with
  - sig-scheduling

**Comment by Huang-Wei** [comment]
+1

@ahmad-diaa did a fantastic job on improving the performance of PodAffinity. Looking forward to seeing more contributions!

**Comment by alculquicondor** [comment]
+1

@ahmad-diaa is being a major contributor in the scheduler configuration cleanup. I fully support this request.

**Comment by mrbobbytables** [comment]
@ahmad-diaa thank you for your help with all the scheduler work :D

I've created PR #1200   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
