### ISSUE TITLE
REQUEST: New membership for <haoshuwei>

### ISSUE THREAD

**Issue by haoshuwei** [kubernetes/org#1196]
### GitHub Username
@haoshuwei

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@cheyang
@dims

### List of contributions to the Kubernetes project
I am the member of the AlibabaCloud Container Service Team and I am focus on developing and improving the [kubernetes-sigs/alibaba-cloud-csi-driver](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver) project, and have great interest to review and submit PRs to Kubernetes community. Some PRs authored listed below:

#### PRs authored:
- [kubernetes/kubernetes#82447](https://github.com/kubernetes/kubernetes/pull/82477)
- [kubernetes/kubernetes#82486](https://github.com/kubernetes/kubernetes/pull/82486)
- [kubernetes/kubernetes#82571](https://github.com/kubernetes/kubernetes/pull/82571)
<br>

- [kubernetes-sigs/alibaba-cloud-csi-driver#55](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/55)
- [kubernetes-sigs/alibaba-cloud-csi-driver#76](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/76)
- [kubernetes-sigs/alibaba-cloud-csi-driver#78](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/78)
- [kubernetes-sigs/alibaba-cloud-csi-driver#82](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/82)
- [kubernetes-sigs/alibaba-cloud-csi-driver#84](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/84)
- [kubernetes-sigs/alibaba-cloud-csi-driver#85](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/85)

Thank you very much.

**Comment by fredkan** [comment]
+1

**Comment by cheyang** [comment]
+1

**Comment by dims** [comment]
+1 from me!

**Comment by mrbobbytables** [comment]
@haoshuwei thanks for your help with the alibaba csi driver :)

I've created PR #1200  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
