### ISSUE TITLE
REQUEST: New membership for Potapy4

### ISSUE THREAD

**Issue by Potapy4** [kubernetes/org#1199]
### GitHub Username
@Potapy4

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @remyleone
- @rekcah78

### List of contributions to the Kubernetes project
- PRs authored:

Small:
kubernetes/website/pull/15268
kubernetes/website/pull/15479
kubernetes/website/pull/15559

Init Russian localization:
kubernetes/website/pull/16404

---

~~P.S. - at the moment I have only **one** sponsor, who can approve this application 👀~~

Thanks @remyleone!

**Comment by remyleone** [comment]
👍

**Comment by remyleone** [comment]
@rekcah78 could you approve also?

**Comment by rekcah78** [comment]
+1

**Comment by mrbobbytables** [comment]
@Potapy4, thank you for kick starting the Russian localization efforts :)

I've created PR #1200  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
