### ISSUE TITLE
REQUEST: New membership for leakingtapan

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes/org#120]
### GitHub Username
@leakingtapan

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gnufied  
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/d-nishi/aws-ebs-csi-driver/pull/8
   - https://github.com/d-nishi/aws-ebs-csi-driver/pull/12
   - https://github.com/kubernetes-csi/docs/pull/51
   - https://github.com/kubernetes-csi/csi-test/pull/117
   - https://github.com/kubernetes/kubernetes/pull/68255

- SIG projects I am involved with
   - sig-storage
   - sig-aws

**Comment by gnufied** [comment]
+1 from me.

**Comment by d-nishi** [comment]
+1

**Comment by cblecker** [comment]
@leakingtapan You may need an additional sponsor. @gnufied has already +1'd, but unfortunately @d-nishi isn't eligible to sponsor per the community membership guidelines (https://git.k8s.io/community/community-membership.md). @jsafrane also wouldn't be able to sponsor, as both @jsafrane and @gnufied work for Red Hat.

**Comment by dims** [comment]
Happy to sponsor you @leakingtapan

**Comment by cblecker** [comment]
Invite will be sent out as soon as #130 merges. Welcome to @kubernetes! 🚀
