### ISSUE TITLE
REQUEST: New membership for nicoaragon

### ISSUE THREAD

**Issue by nicoaragon** [kubernetes/org#1202]
### GitHub Username
nicoaragon

### Organization you are requesting membership in
Kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @fejta 
- @stevekuznetsov

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/test-infra/pull/14161
- https://github.com/kubernetes/test-infra/pull/13884
- https://github.com/kubernetes/test-infra/issues/13276

**Comment by fejta** [comment]
+1

**Comment by stevekuznetsov** [comment]
+1

**Comment by nikhita** [comment]
@nicoaragon thank you for your contributions to test-infra :)

I've created PR #1210 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
