### ISSUE TITLE
REQUEST: New membership for @celanthe

### ISSUE THREAD

**Issue by celanthe** [kubernetes/org#1204]
### GitHub Username
@celanthe

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman
- @mrbobbytables 

### List of contributions to the Kubernetes project

PRs reviewed / authored

* https://github.com/kubernetes-sigs/contributor-site/pull/75 
* https://github.com/celanthe/website/pull/1 (https://kubernetes.io/blog/2019/05/02/kubecon-diversity-lunch-and-hack/)
* https://github.com/kubernetes/community/pull/3773
* https://github.com/kubernetes/community/pull/3817 

SIG projects I am involved with:

contribex 
community

**Comment by mrbobbytables** [comment]
+1 from me :)

**Comment by nikhita** [comment]
+1 from me too! :tada:

**Comment by nikhita** [comment]
@celanthe thank you for your contributions thus far :)

I've created PR #1210 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! So happy to have you here!! 🎉

/assign
