### ISSUE TITLE
why is it python repo?

### ISSUE THREAD

**Issue by yasongxu** [kubernetes/org#1206]
### Organization or repository
e.g. kubernetes/org

### Users affected
no affect, just confused

### Describe the issue

find this repo by language python ,but no python file, confused -_-

![image](https://user-images.githubusercontent.com/12278081/65407190-53e8f900-de14-11e9-8f24-40c522b1358e.png)

**Comment by nikhita** [comment]
Bazel files are also treated as "python": https://github.com/kubernetes/org/search?l=python :)

/close
