### ISSUE TITLE
REQUEST: New membership for @dianaabv

### ISSUE THREAD

**Issue by dianaabv** [kubernetes/org#1207]
### GitHub Username
e.g. @dianaabv

### Organization you are requesting membership in
e.g. @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @remyleone
- @rekcah78

### List of contributions to the Kubernetes project
- PRs reviewed / authored
Init Russian localization:
kubernetes/website/pull/16404

**Comment by Potapy4** [comment]
+1
@dianaabv will be part of the RU localization team

**Comment by remyleone** [comment]
+1

Em seg, 23 de set de 2019 09:39, Nikita Potapenko <notifications@github.com>
escreveu:

**Comment by nikhita** [comment]
Hi @dianaabv! Unfortunately @Potapy4 can't sponsor since sponsors need to be reviewers or approvers in the @kubernetes org.

In case you want help with finding additional sponsors -- I'd suggest asking a SIG Docs lead for sponsorship since this involves initializing RU localization. :)

**Comment by remyleone** [comment]
@rekcah78 @zacharysarah @rbenzair

**Comment by rekcah78** [comment]
+1

**Comment by dianaabv** [comment]
> +1
Thank you!

**Comment by zacharysarah** [comment]
+1

**Comment by rbenzair** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @dianaabv, thank you for all you help with the Russian localization efforts \o/

I've created PR #1236  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
