### ISSUE TITLE
REQUEST: New membership for M00nF1sh

### ISSUE THREAD

**Issue by M00nF1sh** [kubernetes/org#121]
### GitHub Username
@M00nF1sh

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@bigkraig
@leakingtapan

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/614
  - https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/589
  - https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/627
  - https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/637
  - https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/648
  - https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/636
- SIG projects I am involved with
  - sig-aws

**Comment by bigkraig** [comment]
+1 for @M00nF1sh

**Comment by andrewtandoc** [comment]
+1

**Comment by cblecker** [comment]
@M00nF1sh Hi there! Unfortunately it doesn't appear that your sponsors meet the requirements for being sponsors (they aren't themselves members). Please review the guidelines here: https://git.k8s.io/community/community-membership.md

**Comment by leakingtapan** [comment]
+1

**Comment by M00nF1sh** [comment]
@cblecker 
Hi, i changed to be @leakingtapan , and kraig also just become a member :D i guess it's fine now 😄

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #143 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome (in advance)! :)
/assign
