### ISSUE TITLE
REQUEST: New membership for @mars1024

### ISSUE THREAD

**Issue by mars1024** [kubernetes/org#1215]
### GitHub Username
@mars1024

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dcbw 
- @yue9944882 

### List of contributions to the Kubernetes project

[PRs authored](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amars1024+) and [issues related](https://github.com/kubernetes/kubernetes/issues?utf8=✓&q=mentions%3Amars1024+).

**Comment by yue9944882** [comment]
definitely +1. bruce has been actively working in our squad of maintaining upstream features in k/k for a period of time.

**Comment by nikhita** [comment]
@mars1024 thank you for your contributions thus far :)

I've created PR #1217 to add you to the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get membership invite notifications.

Welcome!! 🎉

/assign
