### ISSUE TITLE
REQUEST: New membership for @savitharaghunathan

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/org#1216]
### GitHub Username
@savitharaghunathan 

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jimangel 
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

  https://github.com/kubernetes/website/pull/16540
  https://github.com/kubernetes/website/pull/15972
  https://github.com/kubernetes/website/pull/16190
  https://github.com/kubernetes/website/pull/15604
  https://github.com/kubernetes/website/pull/15588
  https://github.com/kubernetes/website/pull/15827
  https://github.com/kubernetes/website/pull/16237

- Issues responded to
  https://github.com/kubernetes/website/issues/16211
  https://github.com/kubernetes/website/issues/16530
  https://github.com/kubernetes/website/issues/16482
  https://github.com/kubernetes/website/issues/16542
  https://github.com/kubernetes/website/issues/16476
  https://github.com/kubernetes/website/issues/16478
  https://github.com/kubernetes/website/issues/16456
  https://github.com/kubernetes/website/issues/16441
  https://github.com/kubernetes/website/issues/16348
  
- SIG projects I am involved with
  sig-docs
  sig-contribex-triage

**Comment by jimangel** [comment]
+1 @savitharaghunathan is eager to help improve sig-docs and look forward to future contributions!

**Comment by dims** [comment]
+1 from me. welcome @savitharaghunathan

**Comment by nikhita** [comment]
@savitharaghunathan thank you for your contributions thus far :)

I've created PR #1217 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
