### ISSUE TITLE
REQUEST: New membership for @yiqigao217

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes/org#1219]
### GitHub Username
@yiqigao217

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rjbez17 
- @tashimi

### List of contributions to the Kubernetes project
- PRs reviewed / authored - https://github.com/kubernetes-sigs/multi-tenancy/pull/65
- Issues responded to - None
- SIG projects I am involved with - https://github.com/kubernetes-sigs/multi-tenancy

**Comment by adrianludwin** [comment]
NB - this request came up because I was unable to assign https://github.com/kubernetes-sigs/multi-tenancy/issues/76 to @yiqigao217 .

**Comment by tashimi** [comment]
![tenor-163143992](https://user-images.githubusercontent.com/719646/65703580-df8f9f00-e039-11e9-9d67-1575e6dbf794.gif)

/approve

**Comment by rjbez17** [comment]
+1

**Comment by yiqigao217** [comment]
Thank all!

**Comment by nikhita** [comment]
Reopening since you'll still need to be PR'd in to be part of the @kubernetes-sigs org

**Comment by nikhita** [comment]
@yiqigao217 thank you for your contributions with the multi-tenancy working group :)

I've created PR #1226 to add you to the kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
