### ISSUE TITLE
REQUEST: New membership for dstrebel

### ISSUE THREAD

**Issue by dstrebel** [kubernetes/org#122]
### GitHub Username
@dstrebel

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @brendandburns 
- @AishSundar 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
  - Sig-Azure
  - Sig-Release

**Comment by justaugustus** [comment]
+1 from me. Thanks for helping out in #sig-azure and for your work on the 1.12 and 1.13 Release Teams! :)

**Comment by AishSundar** [comment]
+1 from my end as well. Dave is a great addition to the release team !

**Comment by justaugustus** [comment]
Awesome. Thanks Aish! I'll whip up the PR :)
