### ISSUE TITLE
REQUEST: New membership for @lafh

### ISSUE THREAD

**Issue by lafh** [kubernetes/org#1220]
### GitHub Username
@lafh

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rjbez17
- @tashimi

### List of contributions to the Kubernetes project
- SIG projects I am involved with [MTWG](https://github.com/kubernetes-sigs/multi-tenancy)

The purpose of joining is so that you can be assigned issues in the [MTWG](https://github.com/kubernetes-sigs/multi-tenancy)

**Comment by tashimi** [comment]
![tenor-81883876](https://user-images.githubusercontent.com/719646/65703899-693f6c80-e03a-11e9-8b94-acbcc6c4aa30.gif)

+1!

**Comment by rjbez17** [comment]
+1

**Comment by nikhita** [comment]
@lafh thank you for your contributions with the multi-tenancy working group :)

I've created PR #1226 to add you to the kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
