### ISSUE TITLE
REQUEST: New membership for tao12345666333

### ISSUE THREAD

**Issue by tao12345666333** [kubernetes/org#1222]
### GitHub Username
@tao12345666333

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @idealhack 
- @nikhita

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kind/pulls?q=is%3Aclosed+is%3Apr+author%3Atao12345666333

  https://github.com/search?q=org%3Akubernetes+org%3Akubernetes-sigs+author%3Atao12345666333&type=Issues

- SIG projects I am involved with
`kubernetes-sigs/kind` and sig-contribex

**Comment by nikhita** [comment]
+1

**Comment by tao12345666333** [comment]
Thanks @nikhita

**Comment by k82cn** [comment]
+1

**Comment by idealhack** [comment]
+1 of course

**Comment by tao12345666333** [comment]
Thank you  :heart:  @k82cn @idealhack

**Comment by nikhita** [comment]
@tao12345666333 This should have been done wayyyy earlier. :)

I've created PR #1226 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
