### ISSUE TITLE
REQUEST: New membership for saiyam1814

### ISSUE THREAD

**Issue by saiyam1814** [kubernetes/org#1223]
### GitHub Username
@saiyam1814

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @idealhack 
- @nikhita 

### List of contributions to the Kubernetes project
- PRs reviewed/authored
   https://github.com/kubernetes/autoscaler/pull/2339
   https://github.com/kubernetes/website/pull/15102
   https://github.com/kubernetes/autoscaler/pull/2059

- Issues responded to
  https://github.com/kubernetes/community/issues/4044
  https://github.com/kubernetes/community/issues/4086

- SIG projects I am involved with
  sig-autoscaling
  sig-contribex

**Comment by nikhita** [comment]
+1

**Comment by idealhack** [comment]
+1

**Comment by nikhita** [comment]
@Pensu thank you for your contributions, and especially for helping out sig contribex in APAC! :)

I've created PR #1226 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by saiyam1814** [comment]
Thank you @nikhita 🎉
