### ISSUE TITLE
REQUEST: New membership for pensu

### ISSUE THREAD

**Issue by Pensu** [kubernetes/org#1224]
### GitHub Username
@pensu

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @idealhack 
- @nikhita 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/examples/pull/101
  https://github.com/kubernetes/minikube/pull/2171
  https://github.com/kubernetes/minikube/pull/3368
  https://github.com/kubernetes/kubernetes/pull/71455
  https://github.com/kubernetes/test-infra/pull/3477
- Issues responded to
  https://github.com/kubernetes/minikube/issues/3890
  https://github.com/kubernetes/kubernetes/issues/78845
  https://github.com/kubernetes/kubernetes/issues/44750
- SIG projects I am involved with
   sig-contribex

**Comment by idealhack** [comment]
+1

**Comment by nikhita** [comment]
+1

**Comment by nikhita** [comment]
@Pensu thank you for your contributions, and especially for helping out sig contribex in APAC! :)

I've created PR #1226 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
