### ISSUE TITLE
REQUEST: New membership for @serathius

### ISSUE THREAD

**Issue by serathius** [kubernetes/org#1225]
### GitHub Username
@serathius

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @x13n 
- @brancz 

### List of contributions to the Kubernetes project
- [46 PRs in k/k authored](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=+is%3Apr+author%3Aserathius+)
- [3 PRs in metrics-server](https://github.com/kubernetes-incubator/metrics-server/pulls?q=is%3Apr+author%3Aserathius+is%3Aclosed)
- [9 PRs in heapster](https://github.com/kubernetes-retired/heapster/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aserathius+)
- Authored and Implemented [Metrics validation and verification KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190605-metrics-validation-and-verification.md)
- Issues responded to 
    * https://github.com/kubernetes-incubator/metrics-server/issues/190
- Was responsible for moving examples directory from k/k to separate repo https://github.com/kubernetes/kubernetes/issues/60887

**Comment by brancz** [comment]
Thanks for all the work you've done, and looking forward to everything that's still to come. :+1: from me

**Comment by x13n** [comment]
+1, LGTM!

**Comment by nikhita** [comment]
@serathius thank you for your contributions thus far :)

I've created PR #1226 to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
