### ISSUE TITLE
Repository for discuss.k8s.io theme/css 

### ISSUE THREAD

**Issue by castrojo** [kubernetes/org#1233]
### New Repo, Staging Repo, or migrate existing
New Repo

### Requested name for new repository
discuss-theme

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@mrbobbytables @castrojo

### If not a staging repo, who should have write access
@mrbobbytables @castrojo

### If not a staging repo, who should be listed as approvers in OWNERS
@mrbobbytables @castrojo

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@mrbobbytables @castrojo

### What should the repo description be
Theme and CSS files for discuss.kubernetes.io 

### What SIG and subproject does this fall under in sigs.yaml
community-management under SIG Contributor Experience

### Approvals
https://groups.google.com/forum/#!topic/kubernetes-sig-contribex/tx1qR9S6OOs

### Additional context for request
CNCF has acked that we're ok to add an Apache 2.0 license to the files.

**Comment by cblecker** [comment]
explicit approval from contribex tech lead :)

**Comment by mrbobbytables** [comment]
/assign

Should be able to do this tonight :)

**Comment by mrbobbytables** [comment]
Repo has been created: https://github.com/kubernetes-sigs/discuss-theme
OWNERS have been updated: https://github.com/kubernetes-sigs/discuss-theme/blob/master/OWNERS
PR in flight to add repo groups: https://github.com/kubernetes/org/pull/1242
PR in flight to add OWNERS reference under community management subproject: https://github.com/kubernetes/community/pull/4134

**Comment by mrbobbytables** [comment]
All PRs have merged and groups added. Repo should be good to go!
/close
