### ISSUE TITLE
REQUEST: New membership for @pjbgf

### ISSUE THREAD

**Issue by pjbgf** [kubernetes/org#1234]
### GitHub Username
@pjbgf

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tallclair 
- @jeefy 

### List of contributions to the Kubernetes project
- PRs reviewed / authored: 
https://github.com/kubernetes/kubernetes/pull/82347
https://github.com/kubernetes/kubernetes/pull/82648
https://github.com/kubernetes/dashboard/pull/4292
https://github.com/kubernetes/dashboard/pull/4288
https://github.com/kubernetes/enhancements/pull/1257

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/82885
https://github.com/kubernetes/kubernetes/issues/82647
https://github.com/kubernetes/kubernetes/issues/82623
https://github.com/kubernetes/dashboard/issues/4287
https://github.com/kubernetes/test-infra/issues/14260

- SIG projects I am involved with 
sig-node
sig-auth

**Comment by jeefy** [comment]
+1!

**Comment by tallclair** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @pjbgf , thank you for all your help with the dashboard \o/

I've created PR #1241  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by pjbgf** [comment]
That's awesome! Thank you, @mrbobbytables!
