### ISSUE TITLE
REQUEST: New membership for @annajung

### ISSUE THREAD

**Issue by annajung** [kubernetes/org#1235]
### GitHub Username
@annajung

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mrbobbytables 
- @guineveresaenger

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
    - release

**Comment by guineveresaenger** [comment]
+1 from me! Welcome, and see you on the team!

**Comment by mrbobbytables** [comment]
+1 from me too :)
/pony yay

**Comment by mrbobbytables** [comment]
bah, not the best random pony.

Anyway, @annajung, thanks for helping with the 1.17 release team :)

I've created PR #1236  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
