### ISSUE TITLE
REQUEST: New membership for BobyMCbobs

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/org#1238]
### GitHub Username
BobyMCbobs

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hh 
- @??

### List of contributions to the Kubernetes project
- PRs reviewed / authored: [Merged PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=author%3ABobyMCbobs+is%3Amerged), [All PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=author%3ABobyMCbobs)
- SIGs
  - sig/architecture
  - sig/testing

**Comment by BobyMCbobs** [comment]
I'm working on a lot of tests, it would be great to be able to initiate the testing of the tests by myself :smile:

**Comment by hh** [comment]
+1
/area conformance 
/assign @timothysc
/assign @johnbelamaric
/assign @spiffxp

**Comment by alejandrox1** [comment]
Huge +1!
Thank you for all your work @BobyMCbobs

**Comment by alejandrox1** [comment]
/assign @mrbobbytables 
ptal :smile:

**Comment by mrbobbytables** [comment]
Does this mean we have to have a highlander moment?

_grizzled voice_ **There can be only one Bob**

![](https://media.giphy.com/media/9Jmb2idg10qJSygvTQ/giphy.gif)

**Comment by johnbelamaric** [comment]
LGTM, +1

**Comment by BobyMCbobs** [comment]
> Huge +1!
> Thank you for all your work @BobyMCbobs

My pleasure :D

**Comment by BobyMCbobs** [comment]
> Does this mean we have to have a highlander moment?
> 
> _grizzled voice_ **There can be only one Bob**
> 
> ![](https://camo.githubusercontent.com/52afcf856fb1df157fa9f6a16e8d9b866cc5182b/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f394a6d62326964673130714a5379677654512f67697068792e676966)

Let's squeeze onneee more in ;)

**Comment by mrbobbytables** [comment]
@BobyMCbobs - I guess we can make some room ;) The community could use more Bobs.

I've created PR #1241   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by BobyMCbobs** [comment]
Thank you so much! :smiley: 
I look forward to continuing collaborating with you all :smile:
