### ISSUE TITLE
Rename k/features to k/enhancements

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#124]
### New Repo, or migrate existing
`k/features`

### Requested name for new repository
`k/enhancements`

### Which Organization should it reside
`kubernetes`

### Who should be provided access to this repository
At the offset, access will remain the same

### Approvals
Please detail out the approval process for the new repo
Requirements are listed here: https://git.k8s.io/community/github-management/kubernetes-repositories.md
If this is a core repository, then sig-architecture must approve
If this is a SIG repository, then the SIG Technical Leads must approve
Please include links to the approvals (meeting minutes, e-mail thread, etc)

### Additional context for request
Any additional information or context to describe the request.

Work item for https://github.com/kubernetes/features/issues/617

/kind feature
/sig pm
/milestone v1.13
/assign

**Comment by spiffxp** [comment]
/area github-repo
/assign

Should there be any notice given on this? Github will redirect from k/features to k/enhancements but I think I'm looking for some sign of approval here.

**Comment by justaugustus** [comment]
@spiffxp Yep, the redirect should be enough. Let's lazy consensus this for EOD PT, Friday, October 19th.
I'll make an announcement on k-pm and k-dev on Monday to allow some time for feedback.

cc: @calebamiles @idvoretskyi @jdumars

**Comment by justaugustus** [comment]
@idvoretskyi @spiffxp -- lazy consensus period is up on this, so we can go ahead and rename the repo!

**Comment by justaugustus** [comment]
Caleb to handle later today.
/assign @calebamiles

**Comment by calebamiles** [comment]
[done](https://github.com/kubernetes/enhancements)
