### ISSUE TITLE
REQUEST: New membership for chewong

### ISSUE THREAD

**Issue by chewong** [kubernetes/org#1240]
### GitHub Username
@chewong

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andyzhangx
- @justaugustus
- @ritazh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Achewong+
  - https://github.com/kubernetes/test-infra/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Achewong
  - https://github.com/kubernetes-sigs/azuredisk-csi-driver/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Achewong
  - https://github.com/kubernetes-sigs/azurefile-csi-driver/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Achewong
  - https://github.com/kubernetes/cloud-provider-azure/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Achewong
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/80571
  - [WIP] https://github.com/kubernetes/cloud-provider-azure/issues/224
  - [WIP] https://github.com/kubernetes/cloud-provider-azure/issues/227
  - https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/62
  - https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/167
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/azurefile-csi-driver
  - https://github.com/kubernetes-sigs/azuredisk-csi-driver
  - https://github.com/kubernetes/cloud-provider-azure

**Comment by chewong** [comment]
Closing this issue for now while searching for a second sponsor.

**Comment by andyzhangx** [comment]
+1

**Comment by nzoueidi** [comment]
Hey @chewong, did you find any other eligible sponsor for your org membership?

**Comment by chewong** [comment]
@nzoueidi not yet. I will re-open this issue once I found one.

**Comment by justaugustus** [comment]
+1. Ernest has been helping out in a bunch in various Azure subprojects :)
/reopen

**Comment by chewong** [comment]
Thanks @andyzhangx @justaugustus! @nzoueidi could you review this issue again?

**Comment by ritazh** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @chewong, thank you for all your contributions so far :)

I've created PR #1321 to add you to the Kubernetes and Kuberentes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
