### ISSUE TITLE
REQUEST: New membership for raelga

### ISSUE THREAD

**Issue by raelga** [kubernetes/org#1243]
### GitHub Username
@raelga 

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tashimi 
- @vllry 

### List of contributions to the Kubernetes project

Membership request discussed during the tri-weekly sig-usability meeting.
 
- https://github.com/kubernetes/community/issues/4069
- https://github.com/kubernetes-sigs/sig-usability/issues/3
- https://github.com/kubernetes/website/issues/13948
- https://github.com/kubernetes/community/pull/4129

**Comment by nikhita** [comment]
Since you are already a member of @kubernetes, you don't need sponsorship for k-sigs. Feel free to create a PR to add yourself. :smile:

**Comment by raelga** [comment]
> Since you are already a member of @kubernetes, you don't need sponsorship for k-sigs. Feel free to create a PR to add yourself. 😄

Thank you @nikhita, done in #1250. 🎉
