### ISSUE TITLE
REQUEST: New membership for @mylesagray

### ISSUE THREAD

**Issue by mylesagray** [kubernetes/org#1244]
### GitHub Username
@mylesagray

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cantbewong
- @jdumars

### List of contributions to the Kubernetes project
Work on upstream docs, bug logging and reviewing PRs logged for CAPV, vSphere Cloud Provider, vSphere CPI and vSphere CSI drivers. Example"
https://github.com/kubernetes/cloud-provider-vsphere/pull/254
https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/69

kubernetes/cloud-provider-vsphere#181 (work done through Andrew’s fork and squashed into his commit).
kubernetes/cloud-provider-vsphere#236 (worked offline with Cormac and pushed commits through his fork)

https://github.com/kubernetes/cloud-provider-vsphere/issues?utf8=✓&q=mylesagray
https://github.com/vmware/vsphere-storage-for-kubernetes/pulls?utf8=✓&q=mylesagray
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues?utf8=✓&q=author%3Amylesagray+
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pulls?utf8=✓&q=mylesagray

Contributions to external-dns incubator project: kubernetes-incubator/external-dns#1116

Contributions (indirectly) to Velero (kubernetes backup) project, refactored and build Velero images for multi-architectures, amd64, arm32v7 and arm64v8 (https://github.com/mylesagray/velero-multiarch) which became the basis of IBM’s multi-arch PR for Velero: vmware-tanzu/velero#1768

Active member on K8s Slack help troubleshooting VMware users installing and running K8s.

Active member on SIG-VMware community meetings

Co-authored RedHat reference architecture for 3.11 running on VMware: https://access.redhat.com/documentation/en-us/reference_architectures/2019/html-single/deploying_and_managing_openshift_3.11_on_a_vmware_software-defined_data_center/index

Extensive blogs on using K8s on vSphere via upstream plugins: http://blah.cloud/course/k8s-on-vmw/

**Comment by cantbewong** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @mylesagray, thank you for all your contributions so far :)

I've created PR #1254  to add you to both the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome aboard! 🎉

/assign
