### ISSUE TITLE
Migrate deislabs/secrets-store-csi-driver to kubernetes-sigs

### ISSUE THREAD

**Issue by ritazh** [kubernetes/org#1245]
### New Repo, Staging Repo, or migrate existing
migrate repository

### Requested name for new repository
secrets-store-csi-driver

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@ritazh 
@aramase
@anubhavmishra
@malnick

### If not a staging repo, who should have write access
@ritazh 
@aramase
@anubhavmishra
@malnick

### If not a staging repo, who should be listed as approvers in OWNERS
@ritazh 
@aramase
@anubhavmishra
@malnick

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@ritazh 
@aramase
@anubhavmishra
@malnick

### What should the repo description be
The Secrets Store CSI driver allows Kubernetes to mount secret content stored in enterprise-grade external secrets stores into the container's file system.

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject for sig-auth called secret-store-csi-driver

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)
1. Group reached consensus to migrate the rep on [Dec 19, 2019]. SIG-AUTH google group discussion approval: https://groups.google.com/d/msg/kubernetes-sig-auth/HeNMNFbwQig/DR9bXqlkAgAJ
2. Kubernetes code of conduct is adopted: https://github.com/deislabs/secrets-store-csi-driver/blob/master/code-of-conduct.md
3. The repo uses Apache License v2: https://github.com/deislabs/secrets-store-csi-driver/blob/master/LICENSE

The following individuals have expressed interests in this project being in a neutral home per this [discussion](https://groups.google.com/d/msg/kubernetes-sig-auth/HeNMNFbwQig/DR9bXqlkAgAJ):
@mikedanese (Google)
@jaypipes (Amazon)
@mayakacz (Google)
@tashimi (VMware)

TODO:
- Make sure all contributors have signed the CNCF individual or corporate CLA
Not sure about (https://github.com/mskjeret)
- CNCF CLA bot needs to be [enabled](https://github.com/kubernetes/community/blob/master/github-management/setting-up-cla-check.md). Can this be done after the repo is moved under kubernetes-sigs?
- Update [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) file after repo transfer is complete.

**Comment by mikedanese** [comment]
@enj @tallclair

**Comment by saad-ali** [comment]
CC @msau42 for CSI review

**Comment by mrbobbytables** [comment]
Checking back in on this issue -- it looks like the initial code review was completed? Is this still looking to be migrated in?

**Comment by aramase** [comment]
@mrbobbytables Yes, we are planning to migrate it to `kubernetes-sigs`. The code review has been complete and all the issues identified in code reviews have been addressed. @ritazh has sent a note to the mailing group (https://groups.google.com/d/msg/kubernetes-sig-auth/HeNMNFbwQig/oO0VpvU7BgAJ) to check if there are any concerns or issues. If not, then I think we are ready for the next step to make the move.

@mikedanese @msau42 

cc @ritazh @craiglpeters

**Comment by mikedanese** [comment]
I'm happy to give the LGTM from the sig-auth side.

**Comment by msau42** [comment]
I reviewed the CSI driver and lgtm from sig-storage

**Comment by cblecker** [comment]
/assign @liggitt @deads2k @mikedanese 
Reading the e-mail thread, I don't see a clear consensus from the technical leads. Could we get explicit sign off that this repo should be brought into @kubernetes-sigs ?

**Comment by liggitt** [comment]
LGTM per https://groups.google.com/g/kubernetes-sig-auth/c/HeNMNFbwQig/m/o8IPe1hJAwAJ

**Comment by ritazh** [comment]
@cblecker I have added you as an admin to the repo.

**Comment by cblecker** [comment]
Still to be done:
- CLA check run on all contribs
- Groups created
- SECURITY_CONTACTS file required (@ritazh can you please take care of this one? you can use https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/SECURITY_CONTACTS as a template)

**Comment by ritazh** [comment]
Thanks @cblecker Just added SECURITY_CONTACTS

**Comment by enj** [comment]
@cblecker any updates on this?  I think everything is good from SIG Auth's side.

**Comment by cblecker** [comment]
Verified SECURITY_CONTACTS.

Ran CLA check. Looks like there are two contributors who are missing CLAs:
- @malnick (1 PR: https://github.com/deislabs/secrets-store-csi-driver/pull/121)
- @ryysud (1 PR: https://github.com/deislabs/secrets-store-csi-driver/pull/48)

@ritazh @enj @craiglpeters: Can we follow up with these users and ask them to sign the CNCF CLA (https://git.k8s.io/community/CLA.md)?

**Comment by cblecker** [comment]
Created PR for teams: https://github.com/kubernetes/org/pull/1647

I've dropped @anubhavmishra and @malnick from the access list for this repo, as they are not org members (going through the community membership process is a requirement).

**Comment by cblecker** [comment]
Remaining steps:
- Resolve the above CLA issue: https://github.com/kubernetes/org/issues/1245#issuecomment-588580996
- Merge #1647
- Pick a time to migrate repo
- After migration, update sigs.yaml

**Comment by ritazh** [comment]
Thank you @malnick @ryysud for signing the CLA 🎉  

@cblecker Pls let me know how I can help next!

**Comment by cblecker** [comment]
I think we're good @ritazh . What day next week would you like to do this? I can't do Monday, but any other day works for me.

**Comment by ritazh** [comment]
Tuesday works for me!

**Comment by cblecker** [comment]
Sounds good. I'll take care of this tomorrow then.

**Comment by cblecker** [comment]
Repo has been migrated: https://github.com/kubernetes-sigs/secrets-store-csi-driver

Last step is to update sigs.yaml and the sig-auth section to refer to this repo. Would you mind opening that PR, @ritazh ?

**Comment by ritazh** [comment]
Thanks everyone for your feedback and support for this migration. Thank you @enj and @cblecker for moving this forward. 👏
