### ISSUE TITLE
REQUEST: New membership for blueelvis

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/org#1246]
### GitHub Username
@blueelvis

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sharifelgamal
- @afbjorklund

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - https://github.com/kubernetes/minikube/pull/5119
    - https://github.com/kubernetes/minikube/pull/5025
    - https://github.com/kubernetes/minikube/pull/5004
    - https://github.com/kubernetes/minikube/pull/4980
    - https://github.com/kubernetes/minikube/pull/4840
    - https://github.com/kubernetes/minikube/pull/4758
    - https://github.com/kubernetes/minikube/pull/4745
    - https://github.com/kubernetes/minikube/pull/4647
    - https://github.com/kubernetes/minikube/pull/4595
    - https://github.com/kubernetes/minikube/pull/4579
    - https://github.com/kubernetes/minikube/pull/4463
    - https://github.com/kubernetes/minikube/pull/4362

- Issues responded to
    - https://github.com/kubernetes/minikube/issues/4275
    - https://github.com/kubernetes/minikube/issues/4458
    - https://github.com/kubernetes/minikube/issues/4459
    - https://github.com/kubernetes/minikube/issues/4661
    - https://github.com/kubernetes/minikube/issues/4727
    - https://github.com/kubernetes/minikube/issues/4841
    - https://github.com/kubernetes/minikube/issues/4846
    - https://github.com/kubernetes/minikube/issues/4847
    - https://github.com/kubernetes/minikube/issues/4848
    - https://github.com/kubernetes/minikube/issues/4864
    - https://github.com/kubernetes/minikube/issues/4865
    - https://github.com/kubernetes/minikube/issues/4920
    - https://github.com/kubernetes/minikube/issues/4978
    - https://github.com/kubernetes/minikube/issues/4979
    - https://github.com/kubernetes/minikube/issues/5013
    - https://github.com/kubernetes/minikube/issues/5117
    - https://github.com/kubernetes/minikube/issues/5118
    - https://github.com/kubernetes/minikube/issues/5358
    - https://github.com/kubernetes/minikube/issues/5450
    - https://github.com/kubernetes/minikube/issues/5029
    - https://github.com/kubernetes/minikube/issues/5002
    - https://github.com/kubernetes/minikube/issues/4996
    - https://github.com/kubernetes/minikube/issues/4511
    - https://github.com/kubernetes/minikube/issues/3372

- SIG projects I am involved with
    - sig-cluster-lifecycle/minikube

/cc: @tstromberg

**Comment by sharifelgamal** [comment]
I'll sponsor @blueelvis

**Comment by nzoueidi** [comment]
Hey @afbjorklund, do you have a moment to sponsor @blueelvis's org membership? 

Thank you.

**Comment by afbjorklund** [comment]
I sponsor @blueelvis for kubernetes/minikube, we need someone to look after Windows for us

**Comment by nzoueidi** [comment]
Hey there @blueelvis, thank you for all your contributions so far :)

I've created PR #1268 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by blueelvis** [comment]
@nzoueidi - Thanks for the warm welcome!
