### ISSUE TITLE
Migrate cloud-provider-azure from k to k-sigs

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#1247]
### New Repo, Staging Repo, or migrate existing
https://github.com/kubernetes/cloud-provider-azure

### Requested name for new repository
cloud-provider

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
https://github.com/kubernetes/org/blob/41d2401bac1b9fedb43c1de18537eaa565102600/config/kubernetes/sig-azure/teams.yaml#L19-L24

### If not a staging repo, who should have write access
https://github.com/kubernetes/org/blob/41d2401bac1b9fedb43c1de18537eaa565102600/config/kubernetes/sig-azure/teams.yaml#L25-L32

### If not a staging repo, who should be listed as approvers in OWNERS
Already configured.

### If not a staging repo, who should be listed in SECURITY_CONTACTS
Already configured.

### What should the repo description be
Already configured.

### What SIG and subproject does this fall under in sigs.yaml
SIG: Cloud Provider
subproject: provider azure

### Approvals
Self-approve as a subproject owner for provider-azure
/assign @feiskyer @khenidak @craiglpeters @andrewsykim 
cc: @ritazh @lachie83 

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
This is a kubernetes project to project migration; not sure if this is a special case, but let me know what you need. In aid of the SIG Cloud Provider consolidation.

**Comment by cblecker** [comment]
Time frame that you'd like this done in?

**Comment by justaugustus** [comment]
@cblecker -- Soon-ish :tm: 

I'm going to drop a note on the list and call for consensus period of 5 business days, but I wanted to get the issue rolling and see if there were things we needed in place before sending that.

It's currently low-ish usage and both GH and go shouldn't have an issue with the redirect (if that was a concern).

**Comment by cblecker** [comment]
Because it's currently all in-org, there really aren't extra steps other than:
- Move teams.yaml definitions from k -> k-sigs in a PR
- Move repo
- Hook permissions back up
- PR to update sigs.yaml
- Crack open a cold one

**Comment by justaugustus** [comment]
Awesome, I'll get the communications going on this! :beers:

**Comment by nikhita** [comment]
@justaugustus :wave: just wanted to check if there have been any updates here :)

**Comment by justaugustus** [comment]
Sent note to ML: https://groups.google.com/d/topic/kubernetes-provider-azure/z27pjVi4dVw/discussion
Setting lazy consensus for Friday, November 1, EOD US PT, so we can proceed on Monday.

**Comment by justaugustus** [comment]
I'm preparing the migration PRs now!

**Comment by mrbobbytables** [comment]
repo has been migrated: https://github.com/kubernetes-sigs/cloud-provider-azure

**Comment by craiglpeters** [comment]
Seems like we're good to go @justaugustus ?

**Comment by feiskyer** [comment]
already done, this could be closed now.
/close
