### ISSUE TITLE
REQUEST: New membership for bertinatto

### ISSUE THREAD

**Issue by bertinatto** [kubernetes/org#125]
### GitHub Username
bertinatto

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jsafrane 
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
    * Metrics:
        * A/D Controller: https://github.com/kubernetes/kubernetes/pull/66666
        * Volume Manager: https://github.com/kubernetes/kubernetes/pull/66446
        * PV Controller: https://github.com/kubernetes/kubernetes/pull/66389
    * Block Volume support in Cinder plugin: https://github.com/kubernetes/kubernetes/pull/64879
    * Fix flake in CSI plugin: https://github.com/kubernetes/kubernetes/pull/69215
- SIG projects I am involved with:
    * Amazon Elastic Block Store CSI driver: https://github.com/d-nishi/aws-ebs-csi-driver

**Comment by jsafrane** [comment]
+1 from me

**Comment by d-nishi** [comment]
@bertinatto please add @dims as I am yet to become a member myself. 

@dims @cblecker -- Fabio is working with AWS (@leakingtapan) on the ebs csi driver alpha. Please help with the membership.

**Comment by dims** [comment]
+1 from me.

**Comment by spiffxp** [comment]
I'm going to pre-emptively add you to kubernetes-sigs as well, since that's where the subproject you're involved with is hosted

**Comment by spiffxp** [comment]
When #131 merges, you should be invited, and this will close, welcome!

**Comment by d-nishi** [comment]
ThannQ @dims @spiffxp
