### ISSUE TITLE
REQUEST: New membership for bridgetkromhout

### ISSUE THREAD

**Issue by bridgetkromhout** [kubernetes/org#1253]
### GitHub Username
@bridgetkromhout

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cartyc
- @guineveresaenger

### List of contributions to the Kubernetes project
- Release Team - 1.17 release shadow: https://github.com/kubernetes/sig-release/pull/817
- k8s ecosystem projects I am involved with: new PM on Helm

**Comment by guineveresaenger** [comment]
+1 from me!

**Comment by cartyc** [comment]
+1  yay!

**Comment by justaugustus** [comment]
+1!!

**Comment by mrbobbytables** [comment]
@bridgetkromhout  thank you for joining the release team \o/

I've created PR #1254   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
/pony party

**Comment by lachie83** [comment]
Massive +1. Yay!
