### ISSUE TITLE
REQUEST: New membership for @hasheddan

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/org#1255]
### GitHub Username
@hasheddan

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @guineveresaenger
- @alenkacz 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/82496
https://github.com/kubernetes/test-infra/pull/14572
https://github.com/kubernetes-sigs/kubebuilder/pull/918
https://github.com/kubernetes-sigs/kubebuilder/pull/926
https://github.com/kubernetes-sigs/kubebuilder/pull/948
https://github.com/kubernetes-sigs/controller-runtime/pull/527
https://github.com/kubernetes/sig-release/pull/813
https://github.com/kubernetes/sig-release/pull/818

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/82460
https://github.com/kubernetes/test-infra/issues/14531
https://github.com/kubernetes-sigs/kubebuilder/issues/914

- SIG projects I am involved with
https://github.com/kubernetes/community/tree/master/sig-cloud-provider
https://github.com/kubernetes/community/tree/master/sig-api-machinery
https://github.com/kubernetes/community/tree/master/sig-release

**Comment by alenkacz** [comment]
💯 👍

**Comment by guineveresaenger** [comment]
+1 yayyyy! 🎈 🎉

**Comment by justaugustus** [comment]
+1!

**Comment by nzoueidi** [comment]
Hey there @hasheddan, thank you for all your contributions so far :)

I've created PR #1258  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
