### ISSUE TITLE
REQUEST: New membership for d-nishi

### ISSUE THREAD

**Issue by d-nishi** [kubernetes/org#126]
### GitHub Username
@d-nishi

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @gnufied 
- @cblecker 
- @timothysc 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
https://github.com/kubernetes/community/pull/2257
https://github.com/kubernetes/community/pull/2544
https://github.com/kubernetes/community/pull/2549
https://github.com/kubernetes/community/pull/2733
https://github.com/kubernetes/community/pull/2442
https://github.com/kubernetes-sigs/alb-ingress-controller/pull/387
https://github.com/kubernetes-sigs/alb-ingress-controller/pull/394

- Issues responded to
https://github.com/kubernetes/org/issues/123

- SIG projects I am involved with
SIG AWS Lead

**Comment by timothysc** [comment]
+1 from me.

**Comment by gnufied** [comment]
+1 from me.

**Comment by dims** [comment]
+1 from me

**Comment by d-nishi** [comment]
ThanQ @dims @timothysc @gnufied

**Comment by cblecker** [comment]
Invite will be sent out as soon as #130 merges. Welcome to @kubernetes! 🚀

**Comment by d-nishi** [comment]
ThanQ @cblecker
