### ISSUE TITLE
REQUEST: New membership for @danielSbastos

### ISSUE THREAD

**Issue by danielSbastos** [kubernetes/org#1260]
### GitHub Username
@danielSbastos

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @adrianludwin
- @tashimi

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
  - multi-tenancy

**Comment by tashimi** [comment]
+1 

![tenor-117176035](https://user-images.githubusercontent.com/719646/66172273-1f3d2480-e600-11e9-8cc7-bcf4c7a3039f.gif)

**Comment by adrianludwin** [comment]
👍 because I'm not as cool as Tasha

**Comment by adrianludwin** [comment]
![image](https://media.giphy.com/media/8Fxlp25ov2RCGwye9I/giphy.gif)

**Comment by tashimi** [comment]
![tenor-178235416](https://user-images.githubusercontent.com/719646/66172675-85767700-e601-11e9-978a-87ee4e711f21.gif)

**Comment by rjbez17** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @danielSbastos, thank you for all your contributions so far :)

I've created PR #1264 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
