### ISSUE TITLE
REQUEST: New membership for entro-pi

### ISSUE THREAD

**Issue by entro-pi** [kubernetes/org#1261]
### GitHub Username
@entro-pi

### Organization you are requesting membership in
@kubernetes 
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mrbobbytables 
- @tashimi

### List of contributions to the Kubernetes project
- Issues responded to
I have responded to the following issues in both the kubernetes-sigs and kubernetes repositories.
https://github.com/kubernetes-sigs/multi-tenancy/issues/88
https://github.com/kubernetes/kubernetes/issues/68026
- SIG projects I am involved with
I plan on applying to the multi-tenancy kubernetes-SIG for the Outreachy Internship.

**Comment by tashimi** [comment]
+1!

![tenor-26924363](https://user-images.githubusercontent.com/719646/66173741-ae4d3b00-e606-11e9-8fc1-a4392e54799d.gif)

**Comment by mrbobbytables** [comment]
+1
/pony party

**Comment by rjbez17** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @entro-pi, thank you for all your contributions so far :)

I've created PR #1264 to add you to the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and to @kubernetes-sigs! 🎉

/assign

**Comment by entro-pi** [comment]
Hooray! Thank you so much! I look forward to contributing even more!
