### ISSUE TITLE
REQUEST: New membership for kikisdeliveryservice

### ISSUE THREAD

**Issue by kikisdeliveryservice** [kubernetes/org#1265]
### GitHub Username
@kikisdeliveryservice

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @josiahbjorgaard
- @guineveresaenger

### List of contributions to the Kubernetes project
https://github.com/issues?utf8=%E2%9C%93&q=author%3Akikisdeliveryservice+user%3Akubernetes+user%3Akubernetes-sigs

- SIG projects I am involved with
sig-release (I'm a bug triage shadow for 1.17 see https://github.com/kubernetes/sig-release/pull/815)

**Comment by justaugustus** [comment]
Yayyyyy! +1
/meow

**Comment by josiahbjorgaard** [comment]
+1 :)

**Comment by guineveresaenger** [comment]
+1! Yayyyyyyy so excited!

**Comment by nzoueidi** [comment]
Hey there @kikisdeliveryservice, thank you for all your contributions so far :)

I've created PR #1267 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
