### ISSUE TITLE
REQUEST: New membership for gman0

### ISSUE THREAD

**Issue by gman0** [kubernetes/org#1269]
### GitHub Username
@gman0

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tombarron
- @lingxiankong 
- @ramineni

### List of contributions to the Kubernetes project
- author/maintainer of Manila external provisioner in [kubernetes/cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-manila-provisioner.md)
- author/maintainer of Manila CSI plugin in [kubernetes/cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-manila-csi-plugin.md)

**Comment by nikhita** [comment]
+1 :)

**Comment by lingxiankong** [comment]
+1, welcome!

**Comment by tombarron** [comment]
+1

**Comment by ramineni** [comment]
Thanks. +1

**Comment by nzoueidi** [comment]
Hey there @gman0, thank you for all your contributions so far :)

I've created PR #1280 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
