### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for xmudrii

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/org#127]
### GitHub Username
@xmudrii 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I am member of Kubernetes main organization

### SIG projects I am involved with
* cluster-api and cluster-api-providers

**Comment by cblecker** [comment]
Invite will be sent out as soon as #130 merges. Welcome to @kubernetes! 🚀
