### ISSUE TITLE
REQUEST: New membership for @akshaymankar

### ISSUE THREAD

**Issue by akshaymankar** [kubernetes/org#1270]
### GitHub Username
@akshaymankar

### Organization you are requesting membership in
@kubernetes-client

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @guoshimin
- @jonschoning

### List of contributions to the Kubernetes project
- PRs authored
  - https://github.com/kubernetes-client/haskell/pull/46
  - https://github.com/kubernetes-client/haskell/pull/48
  - https://github.com/kubernetes-client/haskell/pull/49
  - https://github.com/kubernetes-client/haskell/pull/50
  - https://github.com/kubernetes-client/haskell/pull/51
- Issues responded to
  - A few on kubernetes-client/haskell
- SIG projects I am involved with
   I plan to work on kubernetes-client/haskell, which is part of sig-api-machinery

**Comment by jonschoning** [comment]
+1

**Comment by guoshimin** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @akshaymankar, thank you for all your contributions so far :)

I've created PR #1280 to add you to the Kubernetes-client Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-client! 🎉

/assign
