### ISSUE TITLE
REQUEST: New membership for chendave

### ISSUE THREAD

**Issue by chendave** [kubernetes/org#1273]
### GitHub Username
@chendave

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @draveness
- @kevin-wangzefeng 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * [PRs merged](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Amerged+is%3Apr+author%3Achendave+)
  * [All PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Achendave+)
- Issues responded to
   * [All issues filed or addressed by myself](https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Achendave+)
- SIG projects I am involved with
   * sig/testing
   * sig/scheduling

**Comment by chendave** [comment]
@draveness @kevin-wangzefeng , PTAL :)

**Comment by draveness** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1 for @chendave

**Comment by chendave** [comment]
thanks to you guys! @draveness  @kevin-wangzefeng

**Comment by nzoueidi** [comment]
Hey there @chendave, thank you for all your contributions so far :)

I've created PR #1280 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
