### ISSUE TITLE
REQUEST: New membership for @gerred

### ISSUE THREAD

**Issue by gerred** [kubernetes/org#1274]
### GitHub Username
@gerred

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jdumars 
- @alenkacz 
- @castrojo

### List of contributions to the Kubernetes project
- Involvement in SIG Architecture and subprojects, now working to get more involved in production readiness reviews, KEP reviews, and issue triage
- Involvement in the kubebuilder sub-project of SIG API Machinery. Very involved in assisting people with controller-runtime and kubebuilder, and am working on contributing more directly to those projects while working on KUDO. Recently worked to solve test generation issues and working with the KUDO org and SIG API Machinery to update controller-runtime to Kubernetes 1.16.
- Issue for Kubernetes repo: https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3Agerred+is%3Aclosed
- Issues under controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Agerred
- Active assistance with users of kubebuilder and controller-runtime in Slack
- Creator and developer on the Kubernetes Universal Declarative Operator ([KUDO](https://github.com/kudobuilder/kudo)), which has the #kudo channel in the Kubernetes Slack and active participant in operator development in the Kubernetes Slack and relevant channels. Also working on it becoming a CNCF sandbox project.
- Assist users in Slack with KIND usage

**Comment by alenkacz** [comment]
whaat? This guy is still not in the org? We need to fix it! 💯 👍

**Comment by jdumars** [comment]
Very glad to +1 Gerred into the org.

**Comment by nzoueidi** [comment]
Hey there @gerred, thank you for all your contributions so far :)

I've created PR #1280 to add you to the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and to @kubernetes-sigs! 🎉

/assign
