### ISSUE TITLE
REQUEST: New membership for fabianvf

### ISSUE THREAD

**Issue by fabianvf** [kubernetes/org#1276]
### GitHub Username
@fabianvf

### Organization you are requesting membership in
@kubernetes 
@kubernetes-client

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @roycaihw 
- @chris-short

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-client/python-base/pull/56
  - https://github.com/kubernetes-client/python-base/pull/145
  - https://github.com/kubernetes-client/python-base/pull/164
- Issues responded to
  - https://github.com/kubernetes-client/python/issues/899
  - https://github.com/kubernetes-client/python/issues/464
- SIG projects I am involved with
  - kubernetes-client/python
  - kubernetes-client/python-base

**Comment by chris-short** [comment]
+1

My name is Chris Short and I approved this message.

**Comment by roycaihw** [comment]
+1

Welcome!

**Comment by nzoueidi** [comment]
Hey there @fabianvf, thank you for all your contributions so far :)

I've created PR #1280 to add you to the Kubernetes and Kubernetes-client Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and to @kubernetes-client! 🎉

/assign

**Comment by justaugustus** [comment]
Chris. :laughing:
