### ISSUE TITLE
REQUEST: New membership for shivi28

### ISSUE THREAD

**Issue by shivi28** [kubernetes/org#1277]
### GitHub Username
@shivi28

### Organization you are requesting membership in
 @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@adrianludwin
@tashimi

### List of contributions to the Kubernetes project
I want to contribute to the Hierarchy Namespace Controller (HNC) in wg-multitenancy

**Comment by adrianludwin** [comment]
Approved

**Comment by tashimi** [comment]
+1!

![tenor-60865393](https://user-images.githubusercontent.com/719646/66429914-e91bee00-e9cd-11e9-914e-b82a1823fb18.gif)

**Comment by nzoueidi** [comment]
Hey there @shivi28, thank you for all your contributions so far :)

I've created PR #1280 to add you to the  Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by shivi28** [comment]
thanks @nzoueidi @tashimi @adrianludwin  :)
