### ISSUE TITLE
Need repo permissions on k/dns

### ISSUE THREAD

**Issue by prameshj** [kubernetes/org#1283]
### Organization or repository

kubernetes/dns

### Users affected

prameshj

### Describe the issue

I am in the [OWNERS](https://github.com/kubernetes/dns/blob/master/OWNERS) file but I need owner permission on the repository itself in order to conduct releases.

**Comment by cblecker** [comment]
@prameshj You can PR yourself into the maintainers team to get access: https://github.com/kubernetes/org/blob/a3dcfe125492b2e85c8fc6afc6d3c6954d56893d/config/kubernetes/org.yaml#L1276-L1282
