### ISSUE TITLE
REQUEST: New membership for @vjdhama

### ISSUE THREAD

**Issue by vjdhama** [kubernetes/org#1289]
### GitHub Username
@vjdhama

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @adrianludwin
- @tashimi

### List of contributions to the Kubernetes project
- PRs authored
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/499
- SIG projects I am involved with
  - I am looking for active contribution in multi-tenancy WG and sig-cluster-lifecycle.

**Comment by adrianludwin** [comment]
+1

**Comment by tashimi** [comment]
+1

![tenor-248348967](https://user-images.githubusercontent.com/719646/66600199-dd5d3280-eb59-11e9-9caf-a476c2c410d1.gif)

**Comment by nzoueidi** [comment]
Hey there @vjdhama, thank you for all your contributions so far :)

I've created PR #1294 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
