### ISSUE TITLE
REQUEST: New membership for liyinan926

### ISSUE THREAD

**Issue by liyinan926** [kubernetes/org#129]
### GitHub Username
@liyinan926

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @kow3ns 
- @janetkuo 
- @foxish 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aliyinan926+archived%3Afalse+is%3Aclosed+org%3Akubernetes+
https://github.com/helm/charts/pull/6239
https://github.com/kubernetes-sigs/application/pull/55
- Issues responded to
https://github.com/kubernetes-sigs/application/issues/57
https://github.com/kubernetes/kubernetes/issues/66620
- SIG projects I am involved with
https://github.com/kubernetes-sigs/application
Spark on Kubernetes from sig-big-data: https://github.com/apache/spark/tree/master/resource-managers/kubernetes

**Comment by spiffxp** [comment]
@liyinan926 Hi there! Unfortunately it doesn't appear that your sponsors meet the requirements for being sponsors (one must be from a different company than the other). Please review the guidelines here: https://git.k8s.io/community/community-membership.md

**Comment by liyinan926** [comment]
@spiffxp Thanks for pointing that out. Added one more person to the list.

**Comment by janetkuo** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @liyinan926, thank you so much for all the contributors you've done so far! :)
I've created PR #146 to add you to the main Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
