### ISSUE TITLE
REQUEST: New membership for rikatz

### ISSUE THREAD

**Issue by rikatz** [kubernetes/org#1291]
### GitHub Username
e.g. @rikatz

### Organization you are requesting membership in
kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yagonobre 
- @aledbf 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls/rikatz
https://github.com/kubernetes/ingress-nginx/pulls/rikatz

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/assigned/rikatz

- SIG projects I am involved with
sig-network

**Comment by aledbf** [comment]
+1

**Comment by yagonobre** [comment]
+1 from me
Also, Katz is doing a great job on São Paulo Kubernetes community

**Comment by nzoueidi** [comment]
Hey there @rikatz, thank you for all your contributions so far :)

I've created PR #1294 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by rikatz** [comment]
Thank you all!!! Really happy to be part of the org and keep contributing :)
