### ISSUE TITLE
New repo kubernetes-sigs/service-apis

### ISSUE THREAD

**Issue by bowei** [kubernetes/org#1292]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
load-balancing-api
EDIT (mrbobbytables): repo name is service-apis

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
bowei, thockin

### If not a staging repo, who should have write access
bowei, thockin

### If not a staging repo, who should be listed as approvers in OWNERS
bowei, thockin

### If not a staging repo, who should be listed in SECURITY_CONTACTS
bowei, thockin

### What should the repo description be
Repository for the next iteration of composite service (e.g. Ingress) and load balancing APIs.

### What SIG and subproject does this fall under in sigs.yaml
sig-network

### Approvals
thockin, caseydavenport, dcbw

### Additional context for request

As part of the V2 (aka that thing that will replace Ingress) API work, it seems like the best home for artifacts (such as a description of the spec) and common code for the project will be in a new Github repository on github.com/kubernetes-sigs, rather than putting it into the core repo (kubernetes/kubernetes).

Putting the project outside of the core repo will align with the desire to break up the monolith into independent pieces and allow us potentially faster iterations while the V2 design is being put together.

**Comment by bowei** [comment]
From e-mail to the sig-network mailing list:

As part of the V2 (aka that thing that will replace Ingress) API work, it seems like the best home for artifacts (such as a description of the spec) and common code for the project will be in a new Github repository on github.com/kubernetes-sigs, rather than putting it into the core repo (kubernetes/kubernetes).

Putting the project outside of the core repo will align with the desire to break up the monolith into independent pieces and allow us potentially faster iterations while the V2 design is being put together. 

Note that this has some analogs to the work that has been done for storage (CSI: https://github.com/kubernetes-sigs?q=csi).

Any thoughts on this? If not, we can get started with creating the repo (will need sig lead ack on the https://github.com/kubernetes/org issue).

Also, we need to think of a good name for the repo :-)

/assign @thockin 
/assign @caseydavenport 
/assign @dcbw

**Comment by nikhita** [comment]
For reference: https://groups.google.com/forum/#!topic/kubernetes-sig-network/Ev2FX74bACA

**Comment by mrbobbytables** [comment]
/assign
I may not be able to get to it till after Enhancements freeze, but I should be able to take care of it by EoD Wednesday.

**Comment by nikhita** [comment]
> Also, we need to think of a good name for the repo :-)

@bowei Just wanted to double check... is the name of the repo still under discussion?

**Comment by bowei** [comment]
Let's give it until the Thursday sig-network meeting...

**Comment by rikatz** [comment]
Can we use this issue to suggest better naming (if there's one)? Is there any naming convention We need to follow here?

**Comment by mrbobbytables** [comment]
Just checking back in...did you wind up deciding on a name?

**Comment by bowei** [comment]
Sorry about the delay, we are still discussing, will try to get this resolved by next week.

**Comment by mrbobbytables** [comment]
No worries! Just figured I'd check :)

**Comment by bowei** [comment]
Hi @mrbobbytables, can we create "service-apis" repository.
We will probably rename it later.

**Comment by mrbobbytables** [comment]
Great. I should be able to get this provisioned tomorrow :)

**Comment by bowei** [comment]
:+1: thanks!

**Comment by mrbobbytables** [comment]
The repo has been created: [kubernetes-sigs/service-apis](https://github.com/kubernetes-sigs/service-apis)
PR is out to add the teams: https://github.com/kubernetes/org/pull/1374

@bowei As far as updating the list of projects in k/community do you want it added as a [new subproject](https://github.com/kubernetes/community/tree/master/sig-network#subprojects)? or included under the [services subproject](https://github.com/kubernetes/community/tree/master/sig-network#services)?

**Comment by bowei** [comment]
I think it fits under the service subproject.

**Comment by mrbobbytables** [comment]
The teams have been added to the repo and https://github.com/kubernetes/community/pull/4211 has merged adding it to the services subproject 👍 

That should be everything. Going to go ahead and close this issue. If you have any issues, please don't hesitate to give me a poke or reopen.

Thanks!

/close
