### ISSUE TITLE
REQUEST: New membership for AevaOnline

### ISSUE THREAD

**Issue by AevaOnline** [kubernetes/org#1295]
### GitHub Username
@AevaOnline

### Organization you are requesting membership in
@Kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jdumars 
- @carolynvs

### List of contributions to the Kubernetes project
- elected to CoC Committee in 2019
- was part of SIG-OpenStack early on, but inactive for a while now
- behind the scenes helped with Baremetal (@spiffxp will remember) and Security (@jaybeale) work
- finally getting around to actually joining the org! :-D

**Comment by carolynvs** [comment]
+1

**Comment by JayBeale** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @AevaOnline, thank you for all your contributions so far :)

I've created PR #1298 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
