### ISSUE TITLE
REQUEST: New membership for camilamacedo86

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes/org#1297]
### GitHub Username
camilamacedo86 - https://github.com/camilamacedo86

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@marun (RedHat)
@mengqiy (Google) 

I spoke with them since they have been helping already and they are maintainers of this org. 

### List of contributions to the Kubernetes project
- Issues created by me: https://github.com/kubernetes-sigs/kubebuilder/issues/created_by/camilamacedo86
- Issues assigned to me: https://github.com/kubernetes-sigs/kubebuilder/issues/assigned/camilamacedo86
- SIG projects I am involved with: kubebuilder
- PRs which was done by myself: https://github.com/kubernetes-sigs/kubebuilder/pulls/camilamacedo86

**Comment by mengqiy** [comment]
+1 from @mengqiy

**Comment by marun** [comment]
+1 from @marun

**Comment by nzoueidi** [comment]
Hey there @camilamacedo86, thank you for all your contributions so far :)

I've created PR #1311 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
