### ISSUE TITLE
REQUEST: New membership for grayluck

### ISSUE THREAD

**Issue by grayluck** [kubernetes/org#1300]
### GitHub Username
@grayluck

### Organization you are requesting membership in
@kubernetes @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @foxish 
- @freehan 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Agrayluck+
https://github.com/kubernetes-sigs/ip-masq-agent/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Agrayluck+
https://github.com/kubernetes/ingress-gce/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Agrayluck+

- Issues responded to
https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+grayluck+
https://github.com/kubernetes-sigs/ip-masq-agent/issues?utf8=%E2%9C%93&q=is%3Aissue+grayluck+
https://github.com/kubernetes/ingress-gce/issues?utf8=%E2%9C%93&q=is%3Aissue+grayluck+

- SIG projects I am involved with
https://github.com/kubernetes/kubernetes
https://github.com/kubernetes-sigs/ip-masq-agent
https://github.com/kubernetes/ingress-gce

**Comment by foxish** [comment]
+1 from my end!

**Comment by grayluck** [comment]
> +1 from my end!

Thank you, Anirudh!

**Comment by freehan** [comment]
+1! Thank you for your contributions!

**Comment by grayluck** [comment]
> +1! Thank you for your contributions!

Thank you, Minhan!

**Comment by nzoueidi** [comment]
Hey there @grayluck, thank you for all your contributions so far :)

I've created PR #1311 to add you to the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
