### ISSUE TITLE
REQUEST: New membership for <fedebongio>

### ISSUE THREAD

**Issue by fedebongio** [kubernetes/org#1301]
### GitHub Username
@fedebongio

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lavalamp 
- @mrbobbytables 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/fedebongio?tab=overview&from=2018-12-01&to=2018-12-31 / mostly helped to fix the way we test using sample-apiserver and how do we generate a new one on each new version of K8s so the test is current all the time. 
- Issues responded to
As I usually run the bug-triage meeting, I try to find the best fit of people to address issues as they are raised. 
- SIG projects I am involved with
I'm involved mostly in SIG-API Machinery. For the last 1.5 year, I help run the bi-weekly public API Machinery Bug triage meeting. I help coordinate the bi-monthly sig meetings, gather topics, moderate, record and upload recordings into the official channels.

**Comment by fedebongio** [comment]
@lavalamp @mrbobbytables

**Comment by mrbobbytables** [comment]
+1 from sponsor
Thanks!

/pony happy

**Comment by lavalamp** [comment]
+1!

**Comment by fedebongio** [comment]
Thank you both! 👍

**Comment by nzoueidi** [comment]
Hey there @fedebongio, thank you for all your contributions so far :)

I've created PR #1311 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
