### ISSUE TITLE
REQUEST: New membership for ksubrmnn

### ISSUE THREAD

**Issue by ksubrmnn** [kubernetes/org#1302]
### GitHub Username
@ksubrmnn 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123 
- @PatrickLang 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
In the Kubernetes repo:
https://github.com/kubernetes/kubernetes/pull/70896
https://github.com/kubernetes/kubernetes/pull/68897
https://github.com/kubernetes/kubernetes/pull/74436

In the CoreOS repo, I have:
https://github.com/coreos/flannel/pull/1061 
https://github.com/coreos/flannel/pull/1078
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/74435

- SIG projects I am involved with
Kubeadm for Windows

**Comment by mrbobbytables** [comment]
@ksubrmnn Just a heads up, as a member of the kubernetes org you don't need to seek sponsorship to be added to any of the 'child' orgs (kubernetes-sigs, kubernetes-csi etc). You're implicitly granted permission to join them 😄 

 If you'd like, please feel free to PR yourself into the kubernetes-sigs org. If not, it'll get batched into the next org update. 👍
