### ISSUE TITLE
Migrate bootkube to kubernetes-sigs

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes/org#1305]
### New Repo, Staging Repo, or migrate existing
migrate existing

### Requested name for new repository

https://github.com/kubernetes-sigs/bootkube

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@aaronlevy 

### If not a staging repo, who should have write access
@aaronlevy 

### If not a staging repo, who should be listed as approvers in OWNERS
@aaronlevy 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@aaronlevy 

### What should the repo description be
Launch a self-hosted Kubernetes cluster

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject for sig-cluster-lifecycle called bootkube

### Approvals
I believe this is already technically part of sig-cluster-lifecycle (https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle#bootkube), but the repo was never moved.

/cc @kubernetes/sig-cluster-lifecycle 

### Additional context for request
Moving from deprecated kubernetes-incubator org.

Intention is to add community (and active SIG members) to OWNERS once this is moved. /cc @andrewrynhard @rmenn

**Comment by nikhita** [comment]
@aaronlevy Thanks for creating an issue to get this moving!

Regarding approval, we'll still need at least one lgtm from a SIG lead since this involves moving repos (albeit, in the kubernetes orgs).

/assign @timothysc @justinsb 
for approval

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/community/issues/1922

**Comment by timothysc** [comment]
@aaronlevy - How active is the project now-a-days?  I was looking through the commit logs and if the most prevalent users are openshift, is there any other major consumers?

**Comment by rajugupta15** [comment]
Yes, In Razorpay, We are using bootkube.

**Comment by aaronlevy** [comment]
Also the Talos Systems folks have been maintaining a fork, but would like to contribute back to the upstream project. That's part of the reason for this move (can't add new people to incubator projects).

**Comment by timothysc** [comment]
part of any project that would be submitted would be to evaluate the owners files and aliases to determine the health of the proposed sub-project.   Could you please update  https://github.com/kubernetes-incubator/bootkube/blob/master/OWNERS to reflect who the new owners are?  If projects are not actively maintained then move them out of community resources.  Also SIG chairs will need rights in order to manage the repo should it fall into disarray.   Please update your OWNERS and OWNERS_ALIAS to reflect who are the maintainers (e.g. - https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES)

**Comment by aaronlevy** [comment]
Opened https://github.com/kubernetes-incubator/bootkube/pull/1051 and https://github.com/kubernetes-incubator/bootkube/pull/1052 to address this.

Bit of a chicken-egg problem on https://github.com/kubernetes-incubator/bootkube/pull/1051 - @rmenn isn't part of the org, but people aren't being added to incubator org anymore...

I could start by just adding @andrewrynhard for the sake of the project move - but will wait to hear your thoughts.

**Comment by timothysc** [comment]
@rmenn @andrewrynhard - if you can confirm that would be useful.

**Comment by andrewrynhard** [comment]
@timothysc Yes please. We have a lot of updates to bootkube we would love to get in before the 1.17 k8s release. The sooner we can start, the better.

**Comment by rmenn** [comment]
@timothysc nope i am not a member of kubernetes-incubator, please feel free to add @andrewrynhard

**Comment by timothysc** [comment]
@rmenn you will need todo a korg issue/request for access to the kubernetes-sigs org.

**Comment by rmenn** [comment]
will do, i did open this up, which is when this (https://github.com/kubernetes/org/issues/1282)  pebble started rolling down the hill, will open once once everything is migrated

**Comment by rmenn** [comment]
opened https://github.com/kubernetes/org/issues/1343 TBD after migration

**Comment by rata** [comment]
> @aaronlevy - How active is the project now-a-days? I was looking through the commit logs and if the most prevalent users are openshift, is there any other major consumers?

We are using it in https://github.com/kinvolk/lokomotive-kubernetes too. We've just opened some PRs :-)

**Comment by timothysc** [comment]
Poke me when the OWNER file is finalized and folks have access to the org.

**Comment by aaronlevy** [comment]
@timothysc The OWNERS and OWNERS_ALIASES have been updated.

**Comment by mrbobbytables** [comment]
/assign

I'll move things over once theres ack from @timothysc 👍

**Comment by timothysc** [comment]
@rmenn & @andrewrynhard - can you please apply for membership of kubernetes-sigs org once that is done then it we're good. 

/lgtm 
/approve 
/hold 
^ until they are added to the sigs org.

**Comment by andrewrynhard** [comment]
https://github.com/kubernetes/org/issues/1357

**Comment by rmenn** [comment]
@timothysc both of us are a part of the org, `/hold` can be removed

**Comment by timothysc** [comment]
/hold cancel 
@mrbobbytables  - go for it.

**Comment by mrbobbytables** [comment]
* Teams have been added: #1401
* Repo has been migrated and teams added: https://github.com/kubernetes-sigs/bootkube
* OWNERS was updated pre-migration.
* SECURITY_CONTACTS updated: https://github.com/kubernetes-sigs/bootkube/pull/1055
* sigs.yaml updated with new location: https://github.com/kubernetes/community/pull/4223

Once all remaining PRs are merged, the repo migration will be complete.

**Comment by mrbobbytables** [comment]
All PRs have been merged. The repo has been migrated. I'm going to go ahead and close the issue. If you have any problems or questions, please feel free to reopen or ping me on slack :)

/close
