### ISSUE TITLE
REQUEST: New membership for @kendallnelson

### ISSUE THREAD

**Issue by kendallnelson** [kubernetes/org#1307]
### GitHub Username
@kendallnelson

### Organization you are requesting membership in
@kubernetes @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @adisky 

### List of contributions to the Kubernetes project
- SIG projects I am involved with- recently, sig-cloud-provider and provider-openstack, and sig-contribex. I have worked on OpenStack for years now and am getting more involved in the integration of k8s with OpenStack in sig-cloud-provider and provider-openstack. In Seattle last year, I attended KubeCon + Cloud Native Con and attended the new contributor training and later gave feedback to the organizers to make it more effective for new contributors in the future. I am in the related slack channels and keep up on the goings on there.

**Comment by adisky** [comment]
+1 from me!

**Comment by dims** [comment]
+1 from me. thanks for taking over for @hogepodge

**Comment by hogepodge** [comment]
+1

**Comment by mrbobbytables** [comment]
@kendallnelson Thanks for stepping in to help with OpenStack here in the Kubernetes project :)

I've created PR #1329  to add you to both the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them

Welcome to @kubernetes! 🎉

/assign
