### ISSUE TITLE
REQUEST: New membership for yuxiaobo96

### ISSUE THREAD

**Issue by yuxiaobo96** [kubernetes/org#1309]
### GitHub Username
@yuxiaobo96

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markthink 
- @hwdef 

### List of contributions to the Kubernetes project
Repository: kubernetes/website

Total Pull Requests Created: 4

1.[kubernetes/website#16735](https://github.com/kubernetes/website/pull/16735)-zh-translation:assign-cpu-resource.md
2.[kubernetes/website#16275](https://github.com/kubernetes/website/pull/16275)-zh-translation:reconfigure-kubelet.md
3.[kubernetes/website#16398](https://github.com/kubernetes/website/pull/16398)-Delete document:content/en/docs/user-journeys/users/cluster-operator/…
4.[kubernetes/website#16260](https://github.com/kubernetes/website/pull/16260)-zh-translation:2015-07-00-Announcing-First-Kubernetes-Enterprise.md

Total Pull Requests issues: 1

1.[kubernetes/website#16326](https://github.com/kubernetes/website/issues/16326)-Issue with content/en/docs/user-journeys/users/cluster-operator/_advanced.md

Repository: kubernetes

Total Pull Requests Created: 2

1.[kubernetes/kubernetes#82363](https://github.com/kubernetes/kubernetes/pull/82363)-update spelling mistakes
2.[kubernetes/kubernetes#82164](https://github.com/kubernetes/kubernetes/pull/82164)-delete extra comma

Repository: kubernetes-sigs/kind

Total Pull Requests Created: 2

1.[kubernetes-sigs/kind#938](https://github.com/kubernetes-sigs/kind/pull/938)-A little mistake:staticcheck and fix-up typo
2.[kubernetes-sigs/kind#883](https://github.com/kubernetes-sigs/kind/pull/883)-Perfect documentations again

Repository: kubernetes/minikube

Total Pull Requests Created: 3

1.[kubernetes/minikube#5455](https://github.com/kubernetes/minikube/pull/5455)-Improve the grammar and annotations
2.[kubernetes/minikube#5443](https://github.com/kubernetes/minikube/pull/5443)-registry / go9p: Correct grammar and spelling in comments
3.[kubernetes/minikube#5468](https://github.com/kubernetes/minikube/pull/5468)-fix-up typo

Repository: kubernetes/kops

Total Pull Requests Created: 1
1.[kubernetes/kops#7705](https://github.com/kubernetes/kops/pull/7705)-Correct word misspelling

Repository: kubernetes/kubeadm

Total Pull Requests Created: 1
1.[kubernetes/kubeadm#1811](https://github.com/kubernetes/kubeadm/pull/1811)-Correct word misspelling

**Comment by markthink** [comment]
+1

**Comment by hwdef** [comment]
+1
Thanks for your contribution!

**Comment by nzoueidi** [comment]
Hey there @yuxiaobo96, thank you for all your contributions so far :)

I've created PR #1311 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
