### ISSUE TITLE
REQUEST: New membership for @pgburt

### ISSUE THREAD

**Issue by pgburt** [kubernetes/org#1312]
### GitHub Username
e.g. @pgburt

### Organization you are requesting membership in
e.g. @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @daminisatya
- @justaugustus 

### List of contributions to the Kubernetes project
I am a sig-docs shadow for the 1.17 release

**Comment by justaugustus** [comment]
+1! Paul is a thoughtful and thorough Kubernetes evangelist and I'm happy to welcome him to the org!
/honk

**Comment by daminisatya** [comment]
+1 Paul is part of 1.17 docs release team! Thank you for your help and I'm super happy to have you on team :-)

**Comment by mrbobbytables** [comment]
Hey there @pgburt , thank you for helping with the 1.17 release!

I've created PR #1329  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
