### ISSUE TITLE
REQUEST: New membership for truongnh1992

### ISSUE THREAD

**Issue by truongnh1992** [kubernetes/org#1315]
### GitHub Username
@truongnh1992

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @jimangel 
- @ngtuna 
- @remyleone

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - kubernetes/kubernetes#74107
    - kubernetes/kubernetes#74116
    - kubernetes/kubernetes#74121
    - kubernetes/kubernetes#74124
    - kubernetes/kubernetes#74174
- Issues responded to
    - kubernetes/kubernetes#77628
- SIG projects I am involved with
    - [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder)

**Comment by ngtuna** [comment]
+1. @truongnh1992 will be leading team to translate k8s docs to vietnamese. Membership is required to do that. https://github.com/kubernetes/org/pull/1314

**Comment by remyleone** [comment]
:+1: I've contacted the Vietnamese CNCF meetup group to get it started. I sponsor the membership of @truongnh1992

**Comment by truongnh1992** [comment]
> 
> 
> 👍 I've contacted the Vietnamese meetup group to get it started. I sponsor the membership of @truongnh1992 https://www.meetup.com/cloudnativevietnamonline/?a=pswmg2

We also running a community called [VietKubers](https://github.com/vietkubers)
Our meetup: https://www.meetup.com/Vietkubers-Vietnam-Kubernetes-Community/

**Comment by remyleone** [comment]
:+1:

Em qui, 17 de out de 2019 08:45, Zach Corleissen <notifications@github.com>
escreveu:

**Comment by jimangel** [comment]
+1! Welcome!

**Comment by nzoueidi** [comment]
Hey there @truongnh1992, thank you for all your contributions so far :)

I've created PR #1321 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
