### ISSUE TITLE
REQUEST: New membership for notpad

### ISSUE THREAD

**Issue by notpad** [kubernetes/org#1316]
### GitHub Username

@notpad

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @draveness 
- @liu-cong
- @wojtek-t 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
kubernetes/kubernetes#82947
kubernetes/kubernetes#83365
kubernetes/kubernetes#83731
kubernetes/kubernetes#83843
kubernetes/kubernetes#83894
kubernetes/kubernetes#84008
kubernetes/kubernetes#85508
kubernetes/kubernetes#84728
kubernetes/kubernetes#84190

- Issues responded to
kubernetes/kubernetes#83039
kubernetes/kubernetes#83125

- SIG projects I am involved with
sig-scheduling
sig-scalability
sig-testing

**Comment by nikhita** [comment]
@notpad according to membership requirements, you'll need 2 sponsors for your application. We can add you to the org once the sponsors +1 on this issue. :)

**Comment by notpad** [comment]
Thanks, close this for now. I'll reopen it once my sponsors agrees with this.

**Comment by liu-cong** [comment]
+1
Looking forward to your future involvement @notpad !

**Comment by draveness** [comment]
+1 Thanks for the contribution.

**Comment by wojtek-t** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @notpad, thank you for all your contributions so far :)

I've created PR #1444 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
