### ISSUE TITLE
REQUEST: New membership for anthonydahanne

### ISSUE THREAD

**Issue by anthonydahanne** [kubernetes/org#1320]
### GitHub Username
@anthonydahanne

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @remyleone
- @rbenzair 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/14863
https://github.com/kubernetes/website/pull/14793
https://github.com/kubernetes/website/pull/14785
https://github.com/kubernetes/website/pull/13425
https://github.com/kubernetes/website/pull/14960
https://github.com/kubernetes/website/pull/16052

- SIG projects I am involved with
sig-docs

**Comment by remyleone** [comment]
:+1:

**Comment by rbenzair** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @anthonydahanne, thank you for all your contributions so far :)

I've created PR #1321 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by anthonydahanne** [comment]
hey there ! thanks a lot @nzoueidi !
