### ISSUE TITLE
REQUEST: New membership for ggriffiths

### ISSUE THREAD

**Issue by ggriffiths** [kubernetes/org#1322]
### GitHub Username
e.g. @ggriffiths

### Organization you are requesting membership in
e.g. @kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xing-yang
- @msau42 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-csi/external-provisioner/pull/274
https://github.com/kubernetes-csi/docs/pull/167
https://github.com/kubernetes-csi/docs/pull/168
https://github.com/kubernetes-csi/docs/pull/171
https://github.com/kubernetes-csi/external-provisioner/pull/301
https://github.com/kubernetes-csi/external-snapshotter/pull/138
https://github.com/kubernetes-csi/external-snapshotter/pull/171
https://github.com/kubernetes-csi/external-resizer/pull/55
https://github.com/kubernetes/kubernetes/pull/83338
https://github.com/kubernetes/website/pull/16682
https://github.com/kubernetes-csi/external-snapshotter/pull/153 (pending)

- Issues responded to
https://github.com/kubernetes-csi/external-snapshotter/issues/159
https://github.com/kubernetes-csi/external-snapshotter/issues/168
https://github.com/kubernetes-csi/external-provisioner/issues/278
https://github.com/kubernetes-csi/external-snapshotter/issues/134
https://github.com/kubernetes-csi/docs/issues/150
https://github.com/kubernetes-csi/external-snapshotter/issues/132
https://github.com/kubernetes/website/issues/16680
various questions in #sig-storage

- SIG projects I am involved with
kubernetes-csi
sig-storage

**Comment by xing-yang** [comment]
+1 for @ggriffiths !

**Comment by msau42** [comment]
+1 @ggriffiths has been doing lots of work on snapshots

**Comment by mrbobbytables** [comment]
Hey there @ggriffiths , thank you for all your contributions so far :)

I've created PR #1329  to add you to the Kubernetes-csi Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-csi! 🎉

/assign
