### ISSUE TITLE
REQUEST: New membership for @ttousai

### ISSUE THREAD

**Issue by ttousai** [kubernetes/org#1324]
### GitHub Username
e.g. (at)ttousai

### Organization you are requesting membership in
e.g. (at)kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jb
- @ markyjackson-taulia

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
   release project

**Comment by markyjackson-taulia** [comment]
+1 from me

**Comment by justaugustus** [comment]
+1 from me too! @ttousai has been active across several release cycles. :)

**Comment by josiahbjorgaard** [comment]
+1!

**Comment by mrbobbytables** [comment]
@ttousai, thank you for helping with the release team!

I've created PR #1329  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
