### ISSUE TITLE
REQUEST: New membership for tanjunchen

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/org#1326]
### GitHub Username
@tanjunchen

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xichengliudui  
- @chenrui333 
- @hwdef 

### List of contributions to the Kubernetes project
Repository: kubernetes
        Total Pull Or Issues Requests Created: [6](https://github.com/kubernetes/kubernetes/pulls/tanjunchen)<br/>
        such as:<br/>
        [[1]](https://github.com/kubernetes/kubernetes/pull/83833) -- Refactor test/integration/master/ with metric<br/>
        [[2]](https://github.com/kubernetes/kubernetes/pull/83714) -- fix staticcheck failures in test/e2e/windows<br/>
        [[3]](https://github.com/kubernetes/kubernetes/pull/83711) -- fix staticcheck failures in test/e2e/common directory<br/>
        [[4]](https://github.com/kubernetes/kubernetes/pull/81998) -- refactor test/e2e/common/e2elog<br/>
    Repository: website
        Total Pull Or Issues Requests Created: [43](https://github.com/kubernetes/website/pulls/tanjunchen)<br/>
        such as:<br/>
        [[1]](https://github.com/kubernetes/website/pull/16904) -- add zh translation /docs/reference/setup-tools/kubeadm/generated/kube…<br/>
        [[2]](https://github.com/kubernetes/website/pull/16902) -- add zh translation content/zh/docs/reference/setup-tools/kubeadm/gene…<br/>
        [[3]](https://github.com/kubernetes/website/pull/16901) -- add zh translation content/zh/docs/reference/setup-tools/kubeadm/gene…<br/>
        [[4]](https://github.com/kubernetes/website/pull/16898) -- update zh translation content/zh/docs/reference/glossary/device-plugi…<br/>
        [[5]](https://github.com/kubernetes/website/pull/16896) -- update zh translation content/zh/docs/reference/glossary/flexvolume.md<br/>
        [[6]](https://github.com/kubernetes/website/pull/16895) -- add zh translation content/zh/docs/reference/glossary/cri-o.md<br/>
        [[7]](https://github.com/kubernetes/website/pull/16690) -- add ZH translation /docs/reference/setup-tools/kubeadm/generated/kube…<br/>
        [[8]](https://github.com/kubernetes/website/pull/16539) -- zh content/zh/docs/tasks/configure-pod-container/configure-pod-config…<br/>
        [[9]](https://github.com/kubernetes/website/pull/16498) -- add zh content/zh/docs/tasks/run-application/run-replicated-stateful-…<br/>
        [[10]](https://github.com/kubernetes/website/pull/16365) -- translate-/docs/tutorials/clusters/apparmor.md<br/>
    Repository: kubeadm
        Total Pull Or Issues Requests Created: [4](https://github.com/kubernetes/kubeadm/pulls/tanjunchen)<br/>
        such as:<br/>
            [[1]](https://github.com/kubernetes/kubeadm/pull/1812) -- improve code in  tests/e2e/manifests/verify_manifest_lists.go<br/>
            [[2]](https://github.com/kubernetes/kubeadm/pull/1813) -- delete go.mod file in the root directory<br/>
            [[3]](https://github.com/kubernetes/kubeadm/pull/1808) -- fix the wrong word<br/>
            [[4]](https://github.com/kubernetes/kubeadm/pull/1771) -- remove the-repeat-word<br/>
    Repository: kops
        Total Pull Or Issues Requests Created: [17](https://github.com/kubernetes/kops/pulls/tanjunchen)<br/>
        such as:<br/>
            [[1]](https://github.com/kubernetes/kops/pull/7760) -- remove the unnecessary newline and unused vars<br/>
            [[2]](https://github.com/kubernetes/kops/pull/7755) -- fix-up staticcheck error<br/>
            [[3]](https://github.com/kubernetes/kops/pull/7754) -- gosimple check error<br/>
            [[4]](https://github.com/kubernetes/kops/pull/7745) -- simplfy code<br/>
            [[5]](https://github.com/kubernetes/kops/pull/7792) -- remove unused functions and simplify return str<br/>
            [[6]](https://github.com/kubernetes/kops/pull/7519) -- modify-doc-small-mistake<br/>
    Repository: minikube
        Total Pull Or Issues Requests Created: [5](https://github.com/kubernetes/minikube/pulls/tanjunchen)<br/>
        such as:
            [[1]](https://github.com/kubernetes/minikube/pull/5386) -- typo fixes: capitalize "CPU", remove duplicate "the"<br/>

**Comment by hwdef** [comment]
+1
Thanks for your contribution!

**Comment by xichengliudui** [comment]
+1
from the Chinese approver

**Comment by chenrui333** [comment]
+1 Thanks for your contributions!!

**Comment by mrbobbytables** [comment]
@tanjunchen  thank you for helping with the chinese localization efforts!

I've created PR #1329  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by chenrui333** [comment]
Thanks @mrbobbytables!!
