### ISSUE TITLE
REQUEST: New membership for bigkraig

### ISSUE THREAD

**Issue by bigkraig** [kubernetes/org#133]
### GitHub Username
@bigkraig

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @d-nishi
- @philips 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - Authored and own https://github.com/kubernetes-sigs/aws-alb-ingress-controller
- Issues responded to
- SIG projects I am involved with
  - sig-aws

**Comment by philips** [comment]
+1

**Comment by d-nishi** [comment]
+1
