### ISSUE TITLE
REQUEST: New membership for hprateek43

### ISSUE THREAD

**Issue by hprateek43** [kubernetes/org#1330]
### GitHub Username
@hprateek43
### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @alculquicondor 
- @draveness 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/83558
https://github.com/kubernetes/kubernetes/pull/83233
https://github.com/kubernetes/kubernetes/pull/82465
https://github.com/kubernetes/kubernetes/pull/76427
https://github.com/kubernetes/kubernetes/pull/76422
https://github.com/kubernetes/kubernetes/pull/82465
https://github.com/kubernetes/kubernetes/pull/83835

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/83873
https://github.com/kubernetes/kubernetes/issues/83873
https://github.com/kubernetes/kubernetes/issues/76598
https://github.com/kubernetes/kubernetes/issues/71134

- SIG projects I am involved with
sig/scheduler

**Comment by draveness** [comment]
+1.  Thanks for the contribution

**Comment by alculquicondor** [comment]
+1
Thanks for your contributions so far and I'm looking forward for more contributions :)

**Comment by hprateek43** [comment]
@draveness Thanks!

**Comment by hprateek43** [comment]
@alculquicondor Thanks. Will try to keep up the pace!

**Comment by nikhita** [comment]
@hprateek43 thank you for your contributions with SIG Scheduling! :)

I've created PR #1334 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
