### ISSUE TITLE
REQUEST: New membership for @miteshskj

### ISSUE THREAD

**Issue by miteshskj** [kubernetes/org#1332]
### GitHub Username
@miteshskj

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@daminisatya 
@zparnold 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - Authored
      - https://github.com/kubernetes/website/pull/16808
      - https://github.com/kubernetes/website/pull/17008
      - https://github.com/kubernetes/website/pull/17011
      - https://github.com/kubernetes/website/pull/17045
      - https://github.com/kubernetes/website/pull/17082
      - https://github.com/kubernetes/website/pull/17027
      - https://github.com/kubernetes/website/pull/17028
      - https://github.com/kubernetes/website/pull/17051
   - Reviewed
      - https://github.com/kubernetes/website/pull/17109
      - https://github.com/kubernetes/website/pull/17019
   - Issues responded to
      - https://github.com/kubernetes/website/issues/17116
      - https://github.com/kubernetes/website/issues/17025
      - https://github.com/kubernetes/website/issues/17113
      - https://github.com/kubernetes/website/issues/17108
- SIG projects I am involved with
   - Docs kubernetes/website

**Comment by daminisatya** [comment]
@miteshskj +1000 

So good to see your contributions and your expertise will definitely help improve K8s docs!! Thank you so much!! 

/party

**Comment by zparnold** [comment]
+1 @miteshskj has done great work!

**Comment by zacharysarah** [comment]
+1 Thanks for your contributions!

**Comment by nikhita** [comment]
@miteshskj thank you for your contributions with kubernetes docs! :)

I've created PR #1334 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
