### ISSUE TITLE
REQUEST: New membership for devigned

### ISSUE THREAD

**Issue by devigned** [kubernetes/org#1335]
### GitHub Username
@devigned

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus
- @CecileRobertMichon 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/278
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure
  - https://github.com/kubernetes-sigs/cluster-api

**Comment by justaugustus** [comment]
+1! Excited to have David working on capz with us :)
/honk

**Comment by CecileRobertMichon** [comment]
+1 !!

**Comment by nikhita** [comment]
@devigned thank you for your contributions with capz! :)

I've created PR #1341 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
