### ISSUE TITLE
REQUEST: New membership for misterikkit

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/org#1337]
### GitHub Username
@misterikkit

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
I am already a member in @kubernetes and @kubernetes-csi. 
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] (NA) I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- 

### List of contributions to the Kubernetes project
(copied from https://github.com/kubernetes/org/issues/1249#issuecomment-537772192)
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/83255
  - https://github.com/kubernetes-csi/csi-test/pull/220
  - https://github.com/kubernetes/kubernetes/pull/82955
  - https://github.com/kubernetes/kubernetes/pull/78009
  - https://github.com/kubernetes/kubernetes/pull/82683
  - https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/316
  - https://github.com/kubernetes/kubernetes/pull/78280
  - https://github.com/kubernetes/kubernetes/pull/79945
  - https://github.com/kubernetes/kubernetes/pull/79417
  - ...
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/68951
  - https://github.com/kubernetes/kubernetes/issues/67589
  - https://github.com/kubernetes/kubernetes/issues/37232
  - https://github.com/kubernetes/kubernetes/issues/75617
  - ...
- SIG projects I am involved with
  - storage
  - scheduling (former member)

**Comment by cblecker** [comment]
As you are already a @kubernetes org member, feel free to PR yourself into the org :)

**Comment by nikhita** [comment]
@misterikkit I've created PR #1341 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by misterikkit** [comment]
Much obliged!

>
