### ISSUE TITLE
REQUEST: New membership for @wfernandes

### ISSUE THREAD

**Issue by wfernandes** [kubernetes/org#1339]
### GitHub Username
@wfernandes

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @detiber 
- @juan-lee 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

  Authored
  - https://github.com/kubernetes-sigs/cluster-api/pull/1645
  - https://github.com/kubernetes-sigs/cluster-api/pull/1531
  - https://github.com/kubernetes-sigs/cluster-api/pull/1511
  - https://github.com/kubernetes-sigs/cluster-api/pull/1493
  - https://github.com/kubernetes-sigs/cluster-api/pull/1479
  - https://github.com/kubernetes-sigs/cluster-api/pull/1462
  - https://github.com/kubernetes-sigs/cluster-api/pull/1439

  Reviewed
  - https://github.com/kubernetes-sigs/cluster-api/pull/1456
  - https://github.com/kubernetes-sigs/cluster-api/pull/1520

- Issues responded to

  Created
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1233
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1211
  - https://github.com/kubernetes-sigs/cluster-api/issues/1561
  - https://github.com/kubernetes-sigs/cluster-api/issues/1480
  - https://github.com/kubernetes-sigs/cluster-api/issues/1478
  - https://github.com/kubernetes-sigs/cluster-api/issues/1470
  - https://github.com/kubernetes-sigs/cluster-api/issues/1469
  - https://github.com/kubernetes-sigs/cluster-api/issues/1461

  Mentioned
  - https://github.com/kubernetes-sigs/cluster-api/issues/1477
  - https://github.com/kubernetes-sigs/cluster-api/issues/1578

- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws
  - https://github.com/kubernetes-sigs/cluster-api-provider-gcp
  - https://github.com/kubernetes-sigs/cluster-api

**Comment by detiber** [comment]
+1

**Comment by juan-lee** [comment]
+1

**Comment by nikhita** [comment]
@wfernandes thank you for your contributions with Cluster API! :)

I've created PR #1341 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
