### ISSUE TITLE
quinton-hoole is now quinton-hoole-2

### ISSUE THREAD

**Issue by quinton-hoole-2** [kubernetes/org#134]
### Organization or repository
kubernetes/*

### Users effected
@quinton-hoole, @quinton-hoole-2

### Describe the issue
Due to a 2FA snarfu I've temporarily (for 6 months) lost access to my quinton-hoole github account.  So I'm now quinton-hoole-2.  @spiffxp could I ask you to please grant quinton-hoole-2 the same github permissions as quinton-hoole has, across all repos in the kubernetes/* orgs?  

Best leave quinton-hoole as is, because I'll hopefully switch back to that account in 6 months, once the github grace period has expired.  Weird, I know, but that's how it works.  

Many thanks in advance...

Quinton

**Comment by spiffxp** [comment]
on this, thanks

**Comment by spiffxp** [comment]
Once the invite is sent/accepted, we'll need to add quinton-hoole-2 to the following teams:
- https://github.com/orgs/kubernetes/teams?query=%40quinton-hoole
- https://github.com/orgs/kubernetes-sigs/teams?query=%40quinton-hoole

**Comment by spiffxp** [comment]
Added to all teams
