### ISSUE TITLE
REQUEST: New membership for bells17

### ISSUE THREAD

**Issue by bells17** [kubernetes/org#1340]
### GitHub Username
@bells17

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nasa9084
- @inductor

### List of contributions to the Kubernetes project
- PRs reviewed / authored
Translation PRs of Kubernetes document into Japanese
https://github.com/kubernetes/website/pull/16554
https://github.com/kubernetes/website/pull/16351
https://github.com/kubernetes/website/pull/16284
https://github.com/kubernetes/website/pull/16129
https://github.com/kubernetes/website/pull/11579
https://github.com/kubernetes/website/pull/11579
https://github.com/kubernetes/website/pull/11577
https://github.com/kubernetes/website/pull/11576
https://github.com/kubernetes/website/pull/11574
https://github.com/kubernetes/website/pull/11572
https://github.com/kubernetes/website/pull/11569

PRs of Kubernetes-csi document modification
https://github.com/kubernetes-csi/docs/pull/202
https://github.com/kubernetes-csi/docs/pull/201
https://github.com/kubernetes-csi/docs/pull/200
https://github.com/kubernetes-csi/docs/pull/199
https://github.com/kubernetes-csi/docs/pull/198

PRs of controller-tools command example modification
https://github.com/kubernetes-sigs/controller-tools/pull/219

PRs of kustomize example modification
https://github.com/kubernetes-sigs/kustomize/pull/948

- Issues responded to
- SIG projects I am involved with
kubernetes/sig-docs

**Comment by nasa9084** [comment]
+1
Thank you for your contribution~

**Comment by nikhita** [comment]
+1

from our interactions on slack :)

**Comment by inductor** [comment]
+1
Welcome to the party :D

**Comment by nikhita** [comment]
@bells17 thank you for your contributions with japanese localization! :)

I've created PR #1341 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by bells17** [comment]
@nikhita Thank you!
