### ISSUE TITLE
Request Netlify site for kubernetes/kops

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/org#1342]
### Repository
kubernetes/kops (https://github.com/kubernetes/kops)

Kops site, currently using existing unreleased mkdocs.  We will probably eventually migrate it to hugo.

### Project domain
kops.sigs.k8s.io (will request after site is verified)
NOTE: Must match domain request.
See subproject site request docs for more information:
http://git.k8s.io/community/github-management/subproject-site-requests.md#subproject-domain-request

### Additional context for request
Kops issue: https://github.com/kubernetes/kops/issues/7636

Thanks so much!  If there's anything missing just let me know!

**Comment by mrbobbytables** [comment]
@mikesplain I've enabled netlify for the repo and set it up with the temporary domain for verification: https://kubernetes-kops.netlify.com

If that looks good for you, please go ahead with the kops.sigs.k8s.io address request.

**Comment by mikesplain** [comment]
Requested, thanks for the help!

**Comment by mikesplain** [comment]
DNS entry is in place now but getting a `Not Found` at http://kops.sigs.k8s.io, any idea if we need to make any other changes @mrbobbytables?  Thanks so much!

**Comment by mrbobbytables** [comment]
Everything is good to go :) 
https://kops.sigs.k8s.io works with a lets encrypt cert provisioned.

If you have any problems, please feel free to reopen or give me a poke on slack.

/close
