### ISSUE TITLE
REQUEST: New membership for @jfbai

### ISSUE THREAD

**Issue by jfbai** [kubernetes/org#1346]
### GitHub Username
@jfbai

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123 
- @fabriziopandini 
- @draveness 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
authored
  - https://github.com/kubernetes/kubernetes/pull/83661
  - https://github.com/kubernetes/kubernetes/pull/83237
  - https://github.com/kubernetes/kubernetes/pull/83106
  - https://github.com/kubernetes/kubernetes/pull/83018
  - https://github.com/kubernetes/kubernetes/pull/82941
  - https://github.com/kubernetes/kubernetes/pull/82243
  - https://github.com/kubernetes/kubernetes/pull/81903
  - https://github.com/kubernetes/kubernetes/pull/81663
  - https://github.com/kubernetes/kubernetes/pull/81647
  - https://github.com/kubernetes/kubernetes/pull/81594
  - https://github.com/kubernetes/kubernetes/pull/81347
  - https://github.com/kubernetes/kubernetes/pull/81265
  - https://github.com/kubernetes/kubernetes/pull/81264
  - https://github.com/kubernetes/kubernetes/pull/80961
  - https://github.com/kubernetes/kubernetes/pull/80559

and there are several [working PRs](https://github.com/kubernetes/kubernetes/pulls/jfbai): 
- Issues responded to
- SIG projects I am involved with
  - https://github.com/kubernetes/kubernetes

/area github-membership

**Comment by fabriziopandini** [comment]
+1
Happy to see @jfbai joining the community
Looking forward to more contributions!

**Comment by neolit123** [comment]
/lgtm
+1 thanks @jfbai

**Comment by mrbobbytables** [comment]
@jfbai I hate to be a stickler, but do you happen to else that could sponsor you? Both @neolit123 and @fabriziopandini work for vmware and our [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require sponsorship from folk from different organizations.

**Comment by jfbai** [comment]
> @jfbai I hate to be a stickler, but do you happen to else that could sponsor you? Both @neolit123 and @fabriziopandini work for vmware and our [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require sponsorship from folk from different organizations.

@mrbobbytables  Oops, my mistake, I missed to read the last sponsor requirement. I will try to ask for help from one sponsor. Thanks a lot.

**Comment by draveness** [comment]
+1, thanks for the contribution

**Comment by mrbobbytables** [comment]
@jfbai, thank you for all your contributions so far :)

I've created PR #1349  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
