### ISSUE TITLE
REQUEST: New membership for @devaips

### ISSUE THREAD

**Issue by devaips** [kubernetes/org#1347]
### GitHub Username
@devaips

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hh 
- @timothysc 

### List of contributions to the Kubernetes project
- PRs reviewed / authored: 
  - [PRs and Issues I've been involved with in k8s/k8s](https://github.com/kubernetes/kubernetes/search?q=devaips&type=Issues)
  - [PRs in k8s/community](https://github.com/kubernetes/community/pulls?q=is%3Apr+author%3Adevaips+is%3Aclosed)
- SIG projects I am involved with:
   - sig/testing
   - sig/architecture

**Comment by hh** [comment]
Good going @devaips 
Thanks for your test writing work.
/approve

**Comment by timothysc** [comment]
I can sponsor you 
/lgtm 
/approve

**Comment by devaips** [comment]
Thank you @timothysc!

**Comment by mrbobbytables** [comment]
@devaips, thank you for all your contributions \o/

I've created PR #1349  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
