### ISSUE TITLE
REQUEST: New membership for jiatongw

### ISSUE THREAD

**Issue by jiatongw** [kubernetes/org#1348]
### GitHub Username
@jiatongw 

### Organization you are requesting membership in
kubernetes-sigs/image-builder

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @figo 
- @codenrhoden 

### List of contributions to the Kubernetes project
https://github.com/kubernetes-sigs/image-builder/pull/61
https://github.com/kubernetes-sigs/image-builder/pull/41

**Comment by mrbobbytables** [comment]
@jiatongw do you happen to else that could sponsor you? Both @figo and @codenrhoden work for vmware and our [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require sponsors to be from different organizations.

**Comment by jiatongw** [comment]
You mean open a PR in `config/kubernetes-sigs/org.yaml` ?
