### ISSUE TITLE
REQUEST: New membership for ZeroMagic

### ISSUE THREAD

**Issue by ZeroMagic** [kubernetes/org#1350]
### GitHub Username
@ZeroMagic

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @resouer 
- @andyzhangx 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/frakti/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AZeroMagic+
  - https://github.com/kubernetes-sigs/azuredisk-csi-driver/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AZeroMagic+
  - https://github.com/kubernetes-sigs/azurefile-csi-driver/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AZeroMagic+
  - [WIP]https://github.com/kubernetes-csi/csi-test/pull/225
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/76258
  - https://github.com/kubernetes/frakti/issues/320
  - https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues?utf8=%E2%9C%93&q=is%3Aissue+assignee%3AZeroMagic+
  - https://github.com/kubernetes-sigs/azurefile-csi-driver/issues?utf8=%E2%9C%93&q=is%3Aissue+assignee%3AZeroMagic+

- SIG projects I am involved with
https://github.com/kubernetes/frakti
https://github.com/kubernetes-sigs/azurefile-csi-driver
https://github.com/kubernetes-sigs/azuredisk-csi-driver

**Comment by andyzhangx** [comment]
+1
@ZeroMagic has made great progress on CSI driver work under k8s-sig

**Comment by mrbobbytables** [comment]
+1 Thank you for all your help!

**Comment by mrbobbytables** [comment]
@ZeroMagic, thank you for all your contributions so far :)

I've created PR #1362  to add you to both the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign

**Comment by resouer** [comment]
+1
