### ISSUE TITLE
REQUEST: New membership for tg123

### ISSUE THREAD

**Issue by tg123** [kubernetes/org#1351]
### GitHub Username
@tg123

### Organization you are requesting membership in
@kubernetes-client

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @brendanburns
- @krabhishek8260

### List of contributions to the Kubernetes project
- PRs reviewed / authored
<https://github.com/kubernetes-client/csharp/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Atg123>
- Issues responded to
<https://github.com/kubernetes-client/csharp/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Atg123+>
- SIG projects I am involved with

**Comment by brendanburns** [comment]
+1 from me!

**Comment by nikhita** [comment]
@tg123 According to our membership rules, sponsors must be from different companies. Since @krabhishek8260 and @brendandburns are both from Microsoft, can you find another non-Microsoft sponsor? Thanks!

**Comment by tg123** [comment]
@nikhita is there anyway to request an exception? owners of csharp client project are all from Microsoft

**Comment by mrbobbytables** [comment]
+1 Thanks for being so quick to act on the outside collaborator clean up 👍

**Comment by mrbobbytables** [comment]
@tg123 thanks for all your efforts on the csharp client library, 

I've created PR #1362  to add you to the Kubernetes-client Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-client! 🎉

/assign
