### ISSUE TITLE
REQUEST: New membership for njuettner

### ISSUE THREAD

**Issue by njuettner** [kubernetes/org#1356]
### GitHub Username
@njuettner

### Organization you are requesting membership in
@kubernetes-sigs 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nikhita 
- @mrbobbytables 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/external-dns/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Anjuettner
- Issues responded to
https://github.com/kubernetes-sigs/external-dns/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Anjuettner
- SIG projects I am involved with
https://github.com/kubernetes-sigs/external-dns

**Comment by mrbobbytables** [comment]
+1

**Comment by nikhita** [comment]
+1

@njuettner is a major contributor to external-dns and is a root-approver for the repo.

**Comment by njuettner** [comment]
thanks @nikhita @mrbobbytables ❤️

**Comment by nikhita** [comment]
@njuettner I've created PR #1368 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! :tada:

/assign
