### ISSUE TITLE
REQUEST: New membership for @JimBugwadia

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes/org#1360]
### GitHub Username

@JimBugwadia

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements
- [ x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @srampal
- @tashimi

### List of contributions to the Kubernetes project
- wg-multitenancy
- wg-policy

**Comment by srampal** [comment]
+1

**Comment by tashimi** [comment]
Typo: should be @kubernetes-sigs

> ### Organization you are requesting membership in
> 
> @kubbernetes-sigs

+1, @JimBugwadia is doing great work around benchmarking 
![tenor-190564943](https://user-images.githubusercontent.com/719646/67905908-2dfbf600-fb30-11e9-84c1-58eb9dab3286.gif)

**Comment by mrbobbytables** [comment]
Hey there @JimBugwadia thank you for helping with wg-multitenancy and wg-policy!

I've created PR #1362  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by JimBugwadia** [comment]
Thanks @mrbobbytables @tashimi @srampal!
