### ISSUE TITLE
REQUEST: New membership for dtoledo67

### ISSUE THREAD

**Issue by dtoledo67** [kubernetes/org#1361]
### GitHub Username
@dtoledo67

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @srampal
- @tashimi

### List of contributions to the Kubernetes project
https://github.com/kubernetes-sigs/multi-tenancy

**Comment by srampal** [comment]
+1

**Comment by tashimi** [comment]
+1!

![tenor-254557094](https://user-images.githubusercontent.com/719646/67906322-68b25e00-fb31-11e9-992b-62e7e5f9413a.gif)

**Comment by mrbobbytables** [comment]
@dtoledo67 thank you for helping with wg-multitenancy :D

I've created PR #1362  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
