### ISSUE TITLE
REQUEST: New membership for jonschoning

### ISSUE THREAD

**Issue by jonschoning** [kubernetes/org#1363]
### GitHub Username
@jonschoning

### Organization you are requesting membership in
@kubernetes-client

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @guoshimin
- @akshaymankar

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-client/haskell/pull/60
  - https://github.com/kubernetes-client/haskell/pull/41
  - https://github.com/kubernetes-client/gen/pull/129
  - https://github.com/kubernetes-client/gen/pull/112
  - https://github.com/kubernetes-client/gen/pull/108
- Issues responded to
  - A few on kubernetes-client/haskell
- SIG projects I am involved with
  - I plan to work on kubernetes-client/haskell, which is part of sig-api-machinery

**Comment by akshaymankar** [comment]
+1

**Comment by mrbobbytables** [comment]
+1 here too. Thank you for being quick to follow up on the collaborator clean up :)

**Comment by mrbobbytables** [comment]
@jonschoning -- I've created PR #1371  to add you to the Kubernetes-client Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-client! 🎉

/assign
