### ISSUE TITLE
REQUEST: New membership for Raffo

### ISSUE THREAD

**Issue by Raffo** [kubernetes/org#1367]
This request is part of the efforts to move External DNS to the kubernetes-sigs org (#1286)

### GitHub Username
@Raffo

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @linki
- @nikhita

### List of contributions to the Kubernetes project
- PRs authored: https://github.com/kubernetes-sigs/external-dns/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3ARaffo
- SIG projects I am involved with: External DNS

**Comment by nikhita** [comment]
+1

**Comment by linki** [comment]
+1
