### ISSUE TITLE
REQUEST: New membership for guoshimin

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/org#1372]
### GitHub Username
@guoshimin

### Organization you are requesting membership in
@kubernetes-client

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jonschoning
- @akshaymankar

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-client/haskell/pulls?q=is%3Apr+author%3Aguoshimin+is%3Aclosed
- I did the initial legwork to bootstrap kubernetes-client/haskell

**Comment by akshaymankar** [comment]
+1

**Comment by mrbobbytables** [comment]
+1 from me, @guoshimin is already an approver for the haskell repo (as an outside collaborator)
https://raw.githubusercontent.com/kubernetes-client/haskell/master/OWNERS

**Comment by jonschoning** [comment]
+1

**Comment by mrbobbytables** [comment]
@guoshimin thanks for being quick to follow up on org member 👍 

I've created PR #1385  to add you to the Kubernetes-client Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-client! 🎉

/assign
