### ISSUE TITLE
REQUEST: New membership for bertinatto

### ISSUE THREAD

**Issue by bertinatto** [kubernetes/org#1381]
### GitHub Username
bertinatto

### Organization you are requesting membership in
kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jsafrane 
- @msau42 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pull/77595
- https://github.com/kubernetes/kubernetes/pull/80084
- https://github.com/kubernetes/kubernetes/pull/80091
- https://github.com/kubernetes/kubernetes/pull/80360
- https://github.com/kubernetes/kubernetes/pull/81467

**Comment by msau42** [comment]
+1

Fabio has been doing a lot of great work with volume resizing, attach limits, and topology features

**Comment by jsafrane** [comment]
+1

**Comment by mrbobbytables** [comment]
@bertinatto I've created PR #1385 to add you to the @kubernetes-csi org. 👍 Once it merges you should get a membership invite notification.

Just an FYI for the future, as a member of @kubernetes you're implicitly allowed to join the other orgs (PR yourself in) and do not have to seek sponsorship.

/assign
