### ISSUE TITLE
Migrate metrics-server to kubernetes-sigs

### ISSUE THREAD

**Issue by serathius** [kubernetes/org#1382]
### New Repo, Staging Repo, or migrate existing
Migrate existing repository from [kubernetes-incubator/metrics-server](https://github.com/kubernetes-incubator/metrics-server)

### Requested name for new repository
metrics-server

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
piosz
brancz

### If not a staging repo, who should have write access
s-urbaniak
serathius

### If not a staging repo, who should be listed as approvers in OWNERS
kawych
s-urbaniak
piosz
brancz
serathius

### If not a staging repo, who should be listed in SECURITY_CONTACTS
s-urbaniak
piosz
brancz
serathius

### What should the repo description be
by default we will set it to "created due to (link to this issue)"

### What SIG and subproject does this fall under in sigs.yaml
this is part of Metrics API subproject for sig-instrumentation

### Approvals
/cc @brancz @s-urbaniak @kawych

**Comment by brancz** [comment]
Not sure where I need to approve, but this has my approval.

**Comment by mrbobbytables** [comment]
That's good enough for sign off 👍

**Comment by mrbobbytables** [comment]
The new teams and org memberships have been added in #1386 
The update to sigs.yaml is here: https://github.com/kubernetes/community/pull/4216

Once the teams have been merged, I will proceed with the migration of the repo 👍

**Comment by mrbobbytables** [comment]
The repo has been migrated and teams have been added: https://github.com/kubernetes-sigs/metrics-server
PR is out to update OWNERS: https://github.com/kubernetes-sigs/metrics-server/pull/346

Once that PR has merged, the migration should be complete 👍

**Comment by serathius** [comment]
Updated list of approvers to include all admins and writers. 
Sorry for confusion.

**Comment by mrbobbytables** [comment]
All outstanding tasks have been completed. 
With that, I'm going to go ahead and close the issue 👍 
If there are any problems, please feel free to reopen or ping me on slack.

Thanks!

/close

**Comment by serathius** [comment]
Thanks for your help!!

**Comment by serathius** [comment]
@lilic
