### ISSUE TITLE
REQUEST: New membership for @chaosaffe

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes/org#139]
### GitHub Username
@chaosaffe

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @roberthbailey 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/helm/helm/pull/3505
https://github.com/kubernetes/website/pull/1685
https://github.com/kubernetes/dashboard/pull/372
https://github.com/kubernetes/kube-deploy/pull/298
https://github.com/kubernetes-sigs/cluster-api/pull/494
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/19
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/20
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/21
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/22
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/24
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/25
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/26

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/59478
https://github.com/kubernetes-sigs/cluster-api/issues/505
https://github.com/kubernetes-sigs/cluster-api/issues/160
https://github.com/kubernetes-sigs/cluster-api/issues/409
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/23

- SIG projects I am involved with
  - **sig-cluster-lifecycle**
    - cluster-api
    - cluster-api-provider-openstack

**Comment by dims** [comment]
+1 from me @chaosaffe

**Comment by roberthbailey** [comment]
+1 from me

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #142 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome (in advance)! :)
/assign
