### ISSUE TITLE
REQUEST: New membership for joelanford

### ISSUE THREAD

**Issue by joelanford** [kubernetes/org#1390]
### GitHub Username
@joelanford

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @DirectXMan12
- @LiliC

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/search?q=org%3Akubernetes-sigs+joelanford+is%3Apr
- Issues responded to
  - https://github.com/search?q=org%3Akubernetes-sigs+joelanford+is%3Aissue

- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/controller-runtime
  - https://github.com/kubernetes-sigs/controller-tools
  - https://github.com/kubernetes-sigs/kubebuilder

**Comment by LiliC** [comment]
Happy to confirm that I am sponsoring @joelanford! 🎉

**Comment by DirectXMan12** [comment]
100% a :+1: from me as well :tada:

**Comment by joelanford** [comment]
Thanks @LiliC and @DirectXMan12!

**Comment by mrbobbytables** [comment]
Hey there @joelanford, thank you for all your contributions so far \o/

I've created PR #1402  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
