### ISSUE TITLE
Request edit access to SIG Apps sub-project kubernetes-sigs/application

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/org#1391]
### Organization or repository
e.g. kubernetes-sigs/application

### Users affected
janetkuo

### Describe the issue
The repo is a sub-project of SIG Apps. I'm one of the SIG Apps chairs. Would like to have edit access to the repo.

**Comment by nikhita** [comment]
PRs welcome :stuck_out_tongue: 

https://github.com/kubernetes/org/blob/master/config/kubernetes-sigs/org.yaml#L358
