### ISSUE TITLE
Install OpenLab Github app for kubernetes-sigs/cluster-api-provider-openstack

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/org#1400]
### Organization or repository
kubernetes-sigs/cluster-api-provider-openstack

### Name of integration
OpenLab Zuul

### Link to integration website
https://github.com/apps/theopenlab-ci

### Describe what is attempting to be accomplished
It will be used to integrate OpenLab Zuul to test ClusterAPI OpenStack. (see also issue: kubernetes-sigs/cluster-api-provider-openstack#484).

**Comment by mrbobbytables** [comment]
@sbueringer Sorry for the delay, things have been kinda crazy with the pre-kubecon rush. It has now been enabled. 👍 

With that, I'm going to go ahead and close the issue. If you have any problems feel free to reopen or ping me on slack.

Thanks!

/close
