### ISSUE TITLE
REQUEST: New membership for @clarklee92

### ISSUE THREAD

**Issue by clarklee92** [kubernetes/org#1403]
### GitHub Username
@clarklee92

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @liggitt
- @oomichi
- @alejandrox1

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aclarklee92

- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Aclarklee92+
- SIG projects I am involved with
  - sigs/testing
  - sigs/node
  - sigs/storage

**Comment by clarklee92** [comment]
I have spoken to my sponsors.
Due to the time difference, I am waiting for their reply. 😁

**Comment by alejandrox1** [comment]
Huge +1!!!
Thank you for all the work you’ve done @clarklee92

**Comment by liggitt** [comment]
+1

**Comment by oomichi** [comment]
+1, thanks for your contribution @clarklee92

**Comment by mrbobbytables** [comment]
Hey there @clarklee92 , thank you for all your contributions so far :)

Sorry for the delay in getting to this, things have been pretty busy with kubecon around the corner. 😬 With that though -- I've created PR #1414  to add you to both the Kubernetes, and kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign
