### ISSUE TITLE
Add GitHub Actions Integration to kubernetes-client organization

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/org#1405]
### Organization or repository
kubernetes-client/

### Name of integration
GitHub Actions

### Link to integration website
https://github.com/features/actions

### Describe what is attempting to be accomplished
GitHub Actions to simplify CI/CD for client library projects and depend on a single vendor (GitHub)

**Comment by cblecker** [comment]
@brendandburns Done! Can you test and let me know if this works for you?

**Comment by brendandburns** [comment]
many thanks! will try this evening.

**Comment by cblecker** [comment]
This is done, closing.
/remove-lifecycle frozen
/close
