### ISSUE TITLE
REQUEST: New membership for rifelpet

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/org#1406]
### GitHub Username
e.g. @rifelpet

### Organization you are requesting membership in
e.g. @kubernetes-sigs

### Requirements
I'm already a member of the `kubernetes` org:

https://github.com/kubernetes/org/blob/8490b37e610eda52524e7fd2a512d46184339ceb/config/kubernetes/org.yaml#L818

**Comment by mrbobbytables** [comment]
@rifelpet I've create PR #1414 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification :) 

Also -- just an FYI for the future: if you need to join one of the other kubernetes orgs, please feel free to open a PR doing so. You don't have to wait for one of us to add you. As long as everything looks good, one of us will approve. 👍 

/assign
