### ISSUE TITLE
REQUEST: New membership for sambdavidson

### ISSUE THREAD

**Issue by sambdavidson** [kubernetes/org#1407]
### GitHub Username
@sambdavidson

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mikedanese 
- @awly 
- @mattjmcnaughton
- @nikhita

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - [kubernetes/cloud-provider-gcp](https://github.com/kubernetes/cloud-provider-gcp)
        - [Disabled dynamic linking of gke-exec-auth-plugin binary. #97](https://github.com/kubernetes/cloud-provider-gcp/pull/97)
        - [Moved lockfile from os's tmp to cache dir. #91](https://github.com/kubernetes/cloud-provider-gcp/pull/91)
        - [Filesystem lock for gke-exec-auth-plugin #90](https://github.com/kubernetes/cloud-provider-gcp/pull/90)
        - [Updated dependencies and fix README #89](https://github.com/kubernetes/cloud-provider-gcp/pull/89) 
        - [Outbound QPS metrics in gcp-controller-manager #86](https://github.com/kubernetes/cloud-provider-gcp/pull/86) 
        - [Moved pantheon metrics to their own file and fixed various go-lint errors #84](https://github.com/kubernetes/cloud-provider-gcp/pull/84) 
        - [Many unofficial reviews](https://github.com/kubernetes/cloud-provider-gcp/issues?utf8=%E2%9C%93&q=sambdavidson) 
    - [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes)
        - [Add a kubelet serving cert age metric #84534](https://github.com/kubernetes/kubernetes/pull/84534)
        - [Added rest client metrics for client TTL and rot. #84382](https://github.com/kubernetes/kubernetes/pull/84382)
        - [Bump debian-* base images for security fixes #75562](https://github.com/kubernetes/kubernetes/pull/75562)
        - [Revert "limit forbidden error to details of what was forbidden" #70314](https://github.com/kubernetes/kubernetes/pull/70314)
- Issues responded to
    - kubernetes
        - [GKE IAM authorizer can authorize verb="*" checks, but not specific verbs #79958](https://github.com/kubernetes/kubernetes/issues/79958)
        - [rotate-server-certificates keep applying for certificates #77489](https://github.com/kubernetes/kubernetes/issues/77489)

- SIG projects I am involved with
    - sig/auth
    - sig/gcp
    - sig/api-machinery

**Comment by awly** [comment]
+1

**Comment by nikhita** [comment]
+1 for Sam

**Comment by mattjmcnaughton** [comment]
+1

**Comment by mikedanese** [comment]
+1

**Comment by mrbobbytables** [comment]
@sambdavidson, thank you for all your contributions so far \o/

I've created PR #1414  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
