### ISSUE TITLE
REQUEST: New membership for jkaniuk

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/org#1408]
### GitHub Username
@jkaniuk

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mm4tt
- @shyamjvs

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/pulls?q=is%3Apr+author%3Ajkaniuk+is%3Aclosed
- Issues responded to
  - https://github.com/issues?q=is%3Aissue+jkaniuk+is%3Aclosed
- SIG projects I am involved with
  - sig-scalability
  - sig-autoscaling

**Comment by mm4tt** [comment]
+1!

**Comment by shyamjvs** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @jkaniuk, thank you for all your contributions so far :)

I've created PR #1430 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
