### ISSUE TITLE
REQUEST: New membership for @jackkleeman

### ISSUE THREAD

**Issue by jackkleeman** [kubernetes/org#1409]
### GitHub Username
@jackkleeman

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @deads2k
- @liggitt 

### List of contributions to the Kubernetes project
PRs created:
- https://github.com/kubernetes/kubernetes/pull/84303
- https://github.com/kubernetes/kubernetes/pull/84200
- https://github.com/kubernetes/kubernetes/pull/83627
- https://github.com/kubernetes/kubernetes/pull/83580
- https://github.com/kubernetes/autoscaler/pull/2186

PRs reviewed:
- https://github.com/kubernetes/kubernetes/pull/85145
- https://github.com/kubernetes/kubernetes/pull/85144
- https://github.com/kubernetes/kubernetes/pull/83579

Sigs:
- Auth

**Comment by liggitt** [comment]
+1

**Comment by deads2k** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @jackkleeman, thank you for all your contributions so far :)

I've created PR #1414  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
