### ISSUE TITLE
Requesting owner permissions for https://github.com/kubernetes-csi/* repos

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/org#141]
### Organization or repository
https://github.com/kubernetes-csi/driver-registrar
https://github.com/kubernetes-csi/external-attacher
https://github.com/kubernetes-csi/external-snapshotter
https://github.com/kubernetes-csi/external-provisioner
https://github.com/kubernetes-csi/docs
https://github.com/kubernetes-csi/csi-test
https://github.com/kubernetes-csi/drivers
https://github.com/kubernetes-csi/livenessprobe

### Users effected
saad-ali

### Describe the issue
Need to be owner of these CSI repo in order to cut releases, etc.
Already have ownership of newly created repos, just not the old ones listed above.

**Comment by spiffxp** [comment]
can you get @xing-yang and @jingxu97 to file issues to become members of kubernetes-csi, and to be added to the external-snapshotter-admins team?

**Comment by spiffxp** [comment]
/close
Created all of the requisite -admins and -maintainers teams, and added @saad-ali and @childsb as team maintainers, as with the other teams.  For repos that had collaborators with admin/write access, I moved them to those teams where possible.

**Comment by saad-ali** [comment]
Thanks @spiffxp!
