### ISSUE TITLE
REQUEST: New membership for barney-s

### ISSUE THREAD

**Issue by barney-s** [kubernetes/org#1410]
### GitHub Username
@barney-s

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @kow3ns 
- @janetkuo 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/85084
  - https://github.com/kubernetes/enhancements/pull/1246
  - https://github.com/kubernetes/kubernetes/issues/78796
  - https://github.com/kubernetes/kubernetes/pull/59768
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/cli-utils/commits?author=barney-s
  - https://github.com/kubernetes-sigs/cli-experimental/commits?author=barney-s
  - https://github.com/kubernetes-sigs/application/commits?author=barney-s

**Comment by janetkuo** [comment]
+1

**Comment by kow3ns** [comment]
+1

**Comment by mrbobbytables** [comment]
@barney-s , thank you for helping with sig-apps and sig-cli 👍 

I've created PR #1414   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
