### ISSUE TITLE
REQUEST: New membership for kkmsft

### ISSUE THREAD

**Issue by kkmsft** [kubernetes/org#1412]
### GitHub Username
e.g. (at)example_user

@kkmsft

### Organization you are requesting membership in
e.g. (at)kubernetes

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- (at)sponsor-1
- (at)sponsor-2

@ddebroy 
@andyzhangx 

### List of contributions to the Kubernetes project
- PRs & Issues

https://github.com/kubernetes/kubernetes/issues?q=mentions%3Akkmsft+is%3Aopen
https://github.com/kubernetes/kubernetes/issues?q=mentions%3Akkmsft+is%3Aclosed

https://github.com/kubernetes-sigs/azuredisk-csi-driver/pulls?q=is%3Apr+author%3Akkmsft+is%3Aclosed

https://github.com/kubernetes/autoscaler/issues?q=mentions%3Akkmsft+is%3Aclosed

- SIG projects I am involved with

Involved in csi-proxy, azuredisk-csi-driver & azurefile-csi-driver  which lie on the boundaries of sig-windows. Have started participating in sig-node in relation to runtime handler patches. Also participating in the in-tree storage drivers for Azure and will get more involved in the sig-storage in the coming days.

**Comment by andyzhangx** [comment]
+1
@kkmsft has done lots of work under csi drivers, made great progress on that.

**Comment by ddebroy** [comment]
+1
@kkmsft has been actively engaged with CSI driver support for Windows

**Comment by mrbobbytables** [comment]
@kkmsft , thank you for all your help with the different windows related projects 👍 

I've created PR #1414   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
