### ISSUE TITLE
REQUEST: New membership for benmoss

### ISSUE THREAD

**Issue by benmoss** [kubernetes/org#1413]
### GitHub Username
benmoss

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @PatrickLang 
- @michmike 

### List of contributions to the Kubernetes project
I'm a technical lead with SIG-Windows, just looking for access on https://github.com/kubernetes-sigs/sig-windows-tools to be able to help deal with issues there.

**Comment by benmoss** [comment]
@neolit123

**Comment by neolit123** [comment]
+1 thanks for the contributions @benmoss !

**Comment by michmike** [comment]
+1 thank you Ben!

**Comment by mrbobbytables** [comment]
@benmoss I've created PR #1414 to add you to the kubernetes-sigs org. 

Just an FYI for the future, as a member of Kubernetes you're implicitly allowed to join the other orgs without requiring other sponsorship :) You can PR yourself in there and one of the slack admins will sign off on it 👍 

/assign
