### ISSUE TITLE
REQUEST: New membership for cadmuxe

### ISSUE THREAD

**Issue by cadmuxe** [kubernetes/org#1416]
### GitHub Username
@cadmuxe

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @freehan
- @caseydavenport

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/ingress-gce/pull/935
  - https://github.com/kubernetes/ingress-gce/pull/827
  - https://github.com/kubernetes/kubernetes/pull/79188
  - https://github.com/kubernetes/kubernetes/pull/67262
- Issues responded to
- SIG projects I am involved with
  - sig-network

**Comment by cadmuxe** [comment]
/cc @freehan @caseydavenport
Hi Minhan and Casey, 
Please review the request, thanks.

**Comment by freehan** [comment]
+1 

Thank you for all the contributions.

**Comment by caseydavenport** [comment]
+1 from me!

**Comment by nzoueidi** [comment]
Hey there @cadmuxe, thank you for all your contributions so far :)

I've created PR #1422 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by cadmuxe** [comment]
nzoueidi, thank you for creating the PR.
