### ISSUE TITLE
REQUEST: New membership for @jefftree

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/org#1417]
### GitHub Username
@jefftree

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @johnbelamaric
- @hh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored [Link](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ajefftree+user%3Akubernetes+)

Projects:

Am actively involved in two projects with sig architecture and sig api-machinery.

- **[Behavior Driven Conformance](https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/20190412-conformance-behaviors.md)** 
- **[apiserver network proxy](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md)**

**Comment by nzoueidi** [comment]
Hey there @Jefftree, thank you for all your contributions so far :)

I've created PR #1422 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
