### ISSUE TITLE
REQUEST: New membership for wozniakjan

### ISSUE THREAD

**Issue by wozniakjan** [kubernetes/org#1426]
### GitHub Username
@wozniakjan

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bskiba 
- @tariq1890 

### List of contributions to the Kubernetes project
- PRs reviewed / authored - [link](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Awozniakjan+user%3Akubernetes+)
https://github.com/kubernetes/autoscaler/pull/2531
https://github.com/kubernetes/kube-state-metrics/pull/949
https://github.com/kubernetes/kubernetes/pull/73405
https://github.com/kubernetes/kops/pull/6380
https://github.com/kubernetes/kubernetes/pull/71313

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/70916

- SIG projects I am involved with
sig-autoscaling
sig-api-machinery

**Comment by bskiba** [comment]
+1

**Comment by tariq1890** [comment]
+1 :)

**Comment by nzoueidi** [comment]
Hey there @wozniakjan, thank you for all your contributions so far :)

I've created PR #1430 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
