### ISSUE TITLE
REQUEST: New membership for huynguyennovem

### ISSUE THREAD

**Issue by huynguyennovem** [kubernetes/org#1427]
### GitHub Username
@huynguyennovem

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x ] I am actively contributing to 1 or more Kubernetes subprojects
- [x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @truongnh1992
- @ngtuna
- @remyleone

### List of contributions to the Kubernetes project

- PRs reviewed / authored
     - https://github.com/kubernetes/kubernetes/pull/72014
     - https://github.com/kubernetes/kubernetes/pull/74050
     - https://github.com/kubernetes/kubernetes/pull/74288
     - https://github.com/kubernetes/kubernetes/pull/74063
- Issues responded to
    - https://github.com/kubernetes/kubernetes/issues/73169
- SIG projects I am involved with
    - https://github.com/kubernetes-sigs/kubebuilder

**Comment by remyleone** [comment]
:+1:

**Comment by truongnh1992** [comment]
+1 @huynguyennovem will be a reviewer / approver for Vietnamese localization.
@ngtuna please vote for Huy, please.

**Comment by nzoueidi** [comment]
Hey there @huynguyennovem, thank you for all your contributions so far :)

I've created PR #1430 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by huynguyennovem** [comment]
> Hey there @huynguyennovem, thank you for all your contributions so far :)
> 
> I've created PR #1430 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 
> 
> /assign

Thank you @nzoueidi :)
