### ISSUE TITLE
REQUEST: New membership for smileisak

### ISSUE THREAD

**Issue by smileisak** [kubernetes/org#1432]
### GitHub Username
smileisak

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- (at)sponsor-1
- (at)sponsor-2

### List of contributions to the Kubernetes project
- PRs reviewed / authored: 
[kubernetes/charts](https://github.com/helm/charts/pulls?q=is%3Apr+author%3Asmileisak+is%3Aclosed)
- Issues responded to: 
[kubernetes/charts](https://github.com/helm/charts/issues?q=is%3Aissue+smileisak+is%3Aclosed)
- SIG projects I am involved with:
wg-multitenancy (request in progress)

**Comment by nzoueidi** [comment]
Hey @smileisak according to membership requirements, you will need to contribute to 1 or more subprojects and you will need also to have 2 sponsors for your application. 
https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by smileisak** [comment]
@nzoueidi thank you for your response, i've contributed to helm/chart project is it enough or it needs more :p...

**Comment by mrbobbytables** [comment]
@smileisak Helm is it's own project with their own membership guidelines. For Kubernetes it must be contributions to one or more things associated with one of the Kubernetes owned subprojects. Sponsors are still a requirement as well. 👍

**Comment by smileisak** [comment]
Thanks @mrbobbytables, i'll close this issue. ;)
