### ISSUE TITLE
website-maintainers team doesn't have write permission

### ISSUE THREAD

**Issue by cstoku** [kubernetes/org#1436]
### Organization or repository
[Kubernetes/website-maintainers](https://github.com/orgs/kubernetes/teams/website-maintainers)
[kubernetes/website](https://github.com/kubernetes/website)

### Users affected
Users who belong to the website-maintainers team

### Describe the issue
This team doesn't have k/website write permission.
This makes it impossible to create a branch.

**Comment by gochist** [comment]
This blocks finishing Korean l10n team milestone `dev-1.16-ko.5` and starting `dev-1.16-ko.6`.

**Comment by justaugustus** [comment]
(Just a heads up that a bunch of the @kubernetes/owners team is at KubeCon, so this may take a little bit.)

**Comment by nikhita** [comment]
Granted website-maintainers write access to the repo.

@zacharysarah I noticed that `sig-docs-maintainers` also had write access. Two questions:

1. Should write access be revoked from this team?

2. Do we still need this team now that we have `website-maintainers`, `website-admins` and language specific teams?

**Comment by zacharysarah** [comment]
@nikhita 👋 Thanks for your patience.

> I noticed that sig-docs-maintainers also had write access. Two questions:
> - Should write access be revoked from this team?

Yes. 

> - Do we still need this team now that we have website-maintainers, website-admins and language specific teams?

No. 

I'll open a separate PR to remove the team. Thanks, @nikhita, for surfacing the concern! 🙇

**Comment by zacharysarah** [comment]
@gochist To be clear, you should have write access now. Do you have what you need?

**Comment by zacharysarah** [comment]
fixed by #1375 

/close
