### ISSUE TITLE
REQUEST: New membership for zhuangqh

### ISSUE THREAD

**Issue by zhuangqh** [kubernetes/org#1438]
### GitHub Username

@zhuangqh

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Fei-Guo
- @adohe
- @rjbez17

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/multi-tenancy/pulls?q=is%3Apr+author%3Azhuangqh+is%3Aclosed
  - https://github.com/kubernetes-sigs/multi-tenancy/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Azhuangqh+
- Issues responded to
  - https://github.com/kubernetes-sigs/multi-tenancy/issues?utf8=%E2%9C%93&q=+is%3Aissue+author%3Azhuangqh+
- SIG projects I am involved with

https://github.com/kubernetes-sigs/multi-tenancy

**Comment by Fei-Guo** [comment]
+1 Jerry has done excellent development work in sig-multitenancy, welcome!

**Comment by rjbez17** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @zhuangqh, thank you for all your contributions so far :)

I've created PR #1439 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
