### ISSUE TITLE
REQUEST: New membership for njuettner

### ISSUE THREAD

**Issue by njuettner** [kubernetes/org#1445]
### GitHub Username
njuettner

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @thockin 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/external-dns/pulls?utf8=%E2%9C%93&q=is%3Apr+njuettner+reviewed-by%3Anjuettner+
- Maintainer of https://github.com/kubernetes-sigs/external-dns

### Additional information
Follow-up https://github.com/kubernetes/k8s.io/pull/479

**Comment by szuecs** [comment]
+1 welcome!

**Comment by linki** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @njuettner, unfortunately @szuecs and @linki cannot sponsor you for membership in the @kubernetes org, as they are not an approvers nor reviewers in the @kubernetes org.

If you have any questions don't be afraid to ask.

Thanks!

**Comment by thockin** [comment]
+1

**Comment by dims** [comment]
+1 from me!

**Comment by njuettner** [comment]
@nzoueidi I got now more approvals, would this be ok now?

**Comment by nzoueidi** [comment]
Hey there @njuettner, thank you for all your contributions so far :)

I've created PR #1453   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
