### ISSUE TITLE
REQUEST: New membership for smileisak

### ISSUE THREAD

**Issue by smileisak** [kubernetes/org#1448]
### GitHub Username
smileisak

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nzoueidi 
- @oussemos 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/multi-tenancy/pull/276

- Issues responded to
https://github.com/kubernetes-sigs/multi-tenancy/issues/275

- SIG projects I am involved with:
`multi-tenancy`

**Comment by oussemos** [comment]
+1

**Comment by nzoueidi** [comment]
@smileisak as discussed in Slack, it would be cool to see more PRs on any of the sub-projects in the k organization.

**Comment by cblecker** [comment]
As I don't see any further activity on this since Dec 1, I'm going to go ahead and close this request. If in the future, you wish to get more involved and reapply, please feel free to do so @smileisak.
