### ISSUE TITLE
REQUEST: New membership for haiyanmeng

### ISSUE THREAD

**Issue by haiyanmeng** [kubernetes/org#1450]
### GitHub Username
@haiyanmeng

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pwittrock
- @monopole
- @mrbobbytables

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes-sigs/kustomize/pull/1845
  https://github.com/kubernetes-sigs/kustomize/pull/1820
  https://github.com/kubernetes-sigs/kustomize/pull/1814
  https://github.com/kubernetes-sigs/kustomize/pull/1800
  https://github.com/kubernetes-sigs/kustomize/pull/1793
  https://github.com/kubernetes-sigs/controller-tools/pull/267
  https://github.com/kubernetes-sigs/controller-tools/pull/265
  https://github.com/kubernetes-sigs/controller-tools/pull/260
  https://github.com/kubernetes-sigs/controller-tools/pull/253
  https://github.com/kubernetes-sigs/controller-tools/pull/252
  https://github.com/kubernetes-sigs/controller-tools/pull/241
  https://github.com/kubernetes-sigs/controller-tools/pull/235
  https://github.com/kubernetes-sigs/controller-tools/pull/234
- Issues responded to
  https://github.com/kubernetes-sigs/kustomize/issues/1747
  https://github.com/kubernetes-sigs/controller-tools/issues/251
  https://github.com/kubernetes-sigs/controller-tools/issues/239
  https://github.com/kubernetes-sigs/controller-tools/issues/236
  https://github.com/kubernetes-sigs/controller-tools/issues/225
- SIG projects I am involved with
  https://github.com/kubernetes-sigs/kustomize
  https://github.com/kubernetes-sigs/controller-tools

**Comment by pwittrock** [comment]
+1

**Comment by mrbobbytables** [comment]
+1
Thanks for helping with kustomize!

**Comment by monopole** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @haiyanmeng, thank you for all your contributions so far :)

I've created PR #1453   to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
