### ISSUE TITLE
REQUEST: New membership for marosset

### ISSUE THREAD

**Issue by marosset** [kubernetes/org#1451]
### GitHub Username
@marosset

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @PatrickLang
- @michmike

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/84882
  - https://github.com/kubernetes/test-infra/pull/15173
  - https://github.com/kubernetes-sigs/windows-testing/pull/113
- Issues responded to
- SIG projects I am involved with
  - Maintaining test configs/jobs for SIG Windows
  - Maintaining test configs/jobs for cluster-provider-azure
  - Misc SIG Windows work
  - Cluster API provider for Azure work

**Comment by michmike** [comment]
thank you Mark for your contributions to Windows on K8s. I support this.
+1

**Comment by PatrickLang** [comment]
+1 :)

**Comment by nzoueidi** [comment]
Hey there @marosset, thank you for all your contributions so far :)

I've created PR #1453   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by marosset** [comment]
Thanks All!
