### ISSUE TITLE
REQUEST: New membership for @joncwong

### ISSUE THREAD

**Issue by joncwong** [kubernetes/org#1452]
### GitHub Username
@joncwong

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pwittrock
- @mrbobbytables

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - [kubernetes-sigs/kustomize#1822](https://github.com/kubernetes-sigs/kustomize/pull/1822)
- Issues responded to
    - [kubernetes-sigs/kustomize#1851](https://github.com/kubernetes-sigs/kustomize/issues/1851)
- SIG projects I am involved with
    - kubectl
    - kustomize

**Comment by pwittrock** [comment]
+1

**Comment by mrbobbytables** [comment]
+1 from me as well :)

**Comment by nzoueidi** [comment]
Hey there @joncwong, thank you for all your contributions so far :)

I've created PR #1453   to add you to the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by joncwong** [comment]
Thanks a ton @pwittrock, @mrbobbytables, and @nzoueidi!
