### ISSUE TITLE
netlify: image-builder.sigs.k8s.io

### ISSUE THREAD

**Issue by moshloop** [kubernetes/org#1456]
### Repository
kubernetes-sigs/image-builder

### Project domain
image-builder.sigs.k8s.io

### Additional context for request

This site will host the docs for image-builder project

**Comment by mrbobbytables** [comment]
I've enabled netlify for the repo and set it up with the domain:
https://kubernetes-sigs-image-builder.netlify.com/

Till the dns record is ready -- in the meantime, can you add a [netlify config](https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file) to the root of the repo? The site will remain blank until that's found there 😬 

Additional Context:
ref: https://github.com/kubernetes-sigs/image-builder/issues/93
ref: https://github.com/kubernetes-sigs/image-builder/pull/99
ref: https://github.com/kubernetes/k8s.io/pull/484

/assign

**Comment by moshloop** [comment]
It looks like the DNS is all up and the redirects are working but it still returns a Not Found

**Comment by mrbobbytables** [comment]
@moshloop now that it has a netlify.toml file in there I can finish up the configuration on the netlify side 👍

**Comment by mrbobbytables** [comment]
Finished configuration. The site is available here: http://image-builder.sigs.k8s.io
It'll take a little time before the ssl cert is provisioned, but it should be complete no matter what by EoD.

**Comment by mrbobbytables** [comment]
Things look good, site is live with the correct cert 👍 
Going to go ahead and close this issue, if you have any problems feel free to reopen or ping me on slack.

Thanks!
/close
