### ISSUE TITLE
REQUEST: New membership for blakebarnett

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/org#1457]
### GitHub Username
blakebarnett

### Organization you are requesting membership in
(at)kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mikesplain 
- @justinsb 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kops/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Ablakebarnett+is%3Aclosed
- Issues responded to
I'm not sure how to find all the ones I've been involved on, probably a lot more than these 2 lists.
https://github.com/kubernetes/kops/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+author%3Ablakebarnett
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+sort%3Aupdated-desc+author%3Ablakebarnett+is%3Aclosed
- SIG projects I am involved with
None currently

**Comment by mikesplain** [comment]
Thanks @blakebarnett!

/lgtm

**Comment by mrbobbytables** [comment]
+1 :)

**Comment by justinsb** [comment]
+1 from me.. surprised to learn this wasn't already the case!

**Comment by mrbobbytables** [comment]
Hey there @blakebarnett , thank you for all your help with the kops subproject \o/

I've created PR #1485  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
