### ISSUE TITLE
REQUEST: New membership for zhucan

### ISSUE THREAD

**Issue by zhucan** [kubernetes/org#1460]
### GitHub Username
@zhucan 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@davidz627 
@msau42 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/426
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/222
- Issues responded to
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/346
- SIG projects I am involved with
 gcp-compute-persistent-disk-csi-driver

**Comment by msau42** [comment]
+1 Louis has helped fix issues in the gce PD CSI driver

**Comment by davidz627** [comment]
+1

**Comment by mrbobbytables** [comment]
@zhucan do you happen to know a non-googler that could +1 you? =/ Our [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#member) require sponsors to be from different organizations.

**Comment by zhucan** [comment]
@mrbobbytables Maybe @xing-yang or @gnufied could +1 for me?

**Comment by xing-yang** [comment]
+1
@zhucan has been helping with volume snapshot work.

**Comment by mrbobbytables** [comment]
@zhucan  thank you for all your contributions so far :)

I've created PR #1485  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
