### ISSUE TITLE
REQUEST: New membership for @nader-ziada

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes/org#1463]
### GitHub Username
@nader-ziada

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @vincepri 
- @CecileRobertMichon 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/kubernetes-sigs/cluster-api/pull/1520
   - https://github.com/kubernetes-sigs/cluster-api/pull/1669
   - https://github.com/kubernetes-sigs/cluster-api/pull/1720 
   - https://github.com/kubernetes-sigs/cluster-api/pull/1742
   - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/260
   - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/259
   - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/247
   - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/245
   - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/244
   - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/236
   - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/335
   - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/315

- Issues responded to
   - https://github.com/kubernetes-sigs/cluster-api/issues/1803
   - https://github.com/kubernetes-sigs/cluster-api/issues/1731
   - https://github.com/kubernetes-sigs/cluster-api/issues/1702 
   - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/255
   - https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/301

- SIG projects I am involved with
   - [cluster-api](https://github.com/kubernetes-sigs/cluster-api)
   - [cluster-api-provider-gcp](https://github.com/kubernetes-sigs/cluster-api-provider-gcp)
   - [cluster-api-provider-azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure)

**Comment by vincepri** [comment]
+1

**Comment by CecileRobertMichon** [comment]
Thanks @nader-ziada!

+1

**Comment by nader-ziada** [comment]
Thanks @vincepri and @CecileRobertMichon

**Comment by nzoueidi** [comment]
Hey there @nader-ziada, thank you for all your contributions so far :)

I've created PR #1471 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
