### ISSUE TITLE
REQUEST: New membership for @estroz

### ISSUE THREAD

**Issue by estroz** [kubernetes/org#1466]
### GitHub Username
@estroz

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @DirectXMan12
- @joelanford

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/controller-runtime/pull/578
  - https://github.com/kubernetes-sigs/controller-runtime/pull/554
  - https://github.com/kubernetes-sigs/controller-runtime/pull/215
  - https://github.com/kubernetes-sigs/controller-tools/pull/311
  - https://github.com/kubernetes-sigs/controller-tools/pull/182
  - https://github.com/kubernetes-sigs/controller-tools/pull/181
  - https://github.com/kubernetes-sigs/controller-tools/pull/177
- Issues responded to
  - https://github.com/kubernetes-sigs/controller-runtime/issues/297
  - https://github.com/kubernetes-sigs/controller-runtime/issues/576
  - https://github.com/kubernetes-sigs/controller-tools/issues/127
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/controller-runtime
  - https://github.com/kubernetes-sigs/controller-tools
  https://github.com/kubernetes-sigs/kubebuilder

**Comment by joelanford** [comment]
Big 👍 from me! 🎉

**Comment by DirectXMan12** [comment]
👍 from me

**Comment by mrbobbytables** [comment]
@estroz  thank you for all your help with controller-runtime and kubebuilder \o/

I've created PR #1485  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
