### ISSUE TITLE
REQUEST: New membership for carlosedp

### ISSUE THREAD

**Issue by carlosedp** [kubernetes/org#1469]
### GitHub Username

@carlosedp

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@BenTheElder 
@yagonobre 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

https://github.com/kubernetes/kubernetes/pulls/carlosedp

- SIG projects I am involved with

sig-apimachinery
sig-cli

**Comment by BenTheElder** [comment]
Thanks for your contributions, excited to see kubernetes on riscv :-)

**Comment by yagonobre** [comment]
Happy to see you here, thanks for your contributions.
+1

**Comment by nzoueidi** [comment]
Hey there @carlosedp, thank you for all your contributions so far :)

I've created PR #1471 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
