### ISSUE TITLE
Please create repo kubernetes/cloud-provider

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/org#147]
### New Repo, or migrate existing
new repository

### Requested name for new repository
cloud-provider

### Which Organization should it reside
kubernetes

### Who should be provided access to this repository
(based on previous approvers in OWNERS file)
@andrewsykim 
@cheftako 
@dims 

### Approvals
This should get approval from SIG Cloud Provider leads and SIG Arch as the cloud provider interface consumed by other providers is "core"

### Additional context for request
PR to move cloud-provider to staging: https://github.com/kubernetes/kubernetes/pull/68310

**Comment by dims** [comment]
request to sig-arch is [here](https://groups.google.com/d/msg/kubernetes-sig-architecture/wUY-pCWJ1Qo/YlSkGidXBgAJ)

**Comment by smarterclayton** [comment]
LGTM

**Comment by dims** [comment]
Can you please setup permissions as documented here as well? https://github.com/kubernetes/org/issues/56#issue-356711512

**Comment by spiffxp** [comment]
- Created: https://github.com/kubernetes/cloud-provider
- Branch protection: https://github.com/kubernetes/test-infra/pull/9739
- Subproject update: https://github.com/kubernetes/community/pull/2769

Since this is a staging repo I did not create cloud-provider-admins nor cloud-provider-maintainers teams

I will close this issue once the linked PR's merge

**Comment by spiffxp** [comment]
One other request: what would you like as the description of the repo?

**Comment by nikhita** [comment]
PR to add the repo to the publishing bot: https://github.com/kubernetes/publishing-bot/pull/121

**Comment by andrewsykim** [comment]
@spiffxp for description, as per Walter's suggestion on slack:
```
Cloud-provider defines the shared interfaces which Kubernetes cloud providers implement. These interfaces allow various controllers to integrate with any cloud provider in a pluggable fashion.
```

**Comment by cblecker** [comment]
Updated description.
/close
