### ISSUE TITLE
REQUEST: New membership for MorrisLaw

### ISSUE THREAD

**Issue by MorrisLaw** [kubernetes/org#1470]
### GitHub Username
@MorrisLaw

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andrewsykim 
- @alejandrox1

### List of contributions to the Kubernetes project
- PRs authored
  - [PR #84613(k/k): Move KubectlCmd and related functions into it's own package.](https://github.com/kubernetes/kubernetes/pull/84613)
  - [PR #66589(k/k): Get load balancer name per provider.](https://github.com/kubernetes/kubernetes/pull/66589)
  - [PR #6886(k/test-infra): Migrate lgtm_after_commit munger to prow lgtm plugin.](https://github.com/kubernetes/test-infra/pull/6886)
  - [PR #67405(k/k): Updated comment for DefaultLoadBalancerName to provide further context.](https://github.com/kubernetes/kubernetes/pull/67405)
  - [PR #65677(k/k): Improved logging message for checking if node is shutdown.](https://github.com/kubernetes/kubernetes/pull/65677)
  - [PR #57583(k/k): Bugfix/logf newline.](https://github.com/kubernetes/kubernetes/pull/57583)
  - [PR #127(k/csi): Refactor external-attacher to use csi-lib-utils/rpc.](https://github.com/kubernetes-csi/external-attacher/pull/127)
  - [PR #39(k/csi): Refactor livenessprobe to use csi-lib-utils/rpc.](https://github.com/kubernetes-csi/livenessprobe/pull/39)
  - [PR #1553(k/community): Fix typo.](https://github.com/kubernetes/community/pull/1553)
- PRs reviewed
  - [PR #85200(k/k): e2e: move LogFailedContainers out of e2e test framework util.go
](https://github.com/kubernetes/kubernetes/pull/85200)
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/39090#issuecomment-560040629
  - https://github.com/kubernetes/kubernetes/issues/84615#issuecomment-549249867
  - https://github.com/kubernetes/kubernetes/issues/81804
  - https://github.com/kubernetes/kubernetes/issues/50564#event-2544060281
  - https://github.com/kubernetes/kubernetes/issues/77095#issuecomment-546041219
  - https://github.com/kubernetes/kubernetes/pull/85564#issuecomment-561514459
- SIG projects I am involved with
  - sig/testing
  - sig/cloud-provider

**Comment by andrewsykim** [comment]
+1 from me, thank you @MorrisLaw

**Comment by alejandrox1** [comment]
+111!!! Thank you for all your hard work @MorrisLaw 

/assign @nzoueidi 
ptal :smile:

**Comment by nzoueidi** [comment]
Hey there @MorrisLaw, thank you for all your contributions so far :)

I've created PR #1471 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
