### ISSUE TITLE
REQUEST: New membership for gab-satchi

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes/org#1475]
### GitHub Username
@gab-satchi

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @michmike
- @PatrickLang

### List of contributions to the Kubernetes project
- PRs
  - [PR 84472 Windows build information as a label](https://github.com/kubernetes/kubernetes/pull/84472)
  - [PR 80911 Vsphere volume mount/attach on Windows](https://github.com/kubernetes/kubernetes/pull/80911)

- SIG projects I am involved with
  - sig-windows

**Comment by michmike** [comment]
thank you for your contributions @gab-satchi !!!
+1

**Comment by PatrickLang** [comment]
+1 Thanks @gab-satchi !

**Comment by nzoueidi** [comment]
Hey there @gab-satchi, thank you for all your contributions so far :)

I've created PR #1496 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes 🎉
