### ISSUE TITLE
REQUEST: New membership for gongguan

### ISSUE THREAD

**Issue by gongguan** [kubernetes/org#1476]
### GitHub Username
@gongguan

### Organization you are requesting membership in
@kubernetes

### Requirements
* [x]  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
* [x]  I have enabled 2FA on my GitHub account (https://github.com/settings/security)
* [x]  I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
* [x]  I am actively contributing to 1 or more Kubernetes subprojects
* [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
* [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
* @wojtek-t 
* @neolit123 
* @robscott 

### List of contributions to the Kubernetes project
* PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Agongguan
* Issues responded to
  https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+gongguan
* SIG projects I am involved with
  * sig-network
  * sig-scalability

**Comment by robscott** [comment]
:+1:

**Comment by gongguan** [comment]
I'm sorry that I haven't realized sponsors should belong to different company. I'll find another sponsor later.

**Comment by gongguan** [comment]
gentle ping @neolit123

**Comment by neolit123** [comment]
+1 thank you for the PRs thus far!

**Comment by wojtek-t** [comment]
+1 - I support this request

**Comment by mrbobbytables** [comment]
Hey there @gongguan , thank you for all your contributions so far :)

I've created PR #1485  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
