### ISSUE TITLE
REQUEST: New membership for xrmzju

### ISSUE THREAD

**Issue by xrmzju** [kubernetes/org#1477]
### GitHub Username
xrmzju

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @detiber 
- @DirectXMan12

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/controller-runtime/pull/647
https://github.com/kubernetes-sigs/controller-runtime/pull/569
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1020
- Issues responded to
https://github.com/kubernetes-sigs/controller-runtime/issues/648
https://github.com/kubernetes-sigs/controller-runtime/issues/568
https://github.com/kubernetes-sigs/cluster-api/issues/1398
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1019
https://github.com/kubernetes-sigs/cluster-api/issues/1622
https://github.com/kubernetes/kubernetes/issues/74231
- SIG projects I am involved with
Sig Cluster Lifecycle

**Comment by detiber** [comment]
+1 from me, @xrmzju has been a valuable contributor to cluster-api and cluster-api-provider-aws :)

**Comment by DirectXMan12** [comment]
:+1: they've been contributing nicely to controller-runtime as well.

**Comment by mrbobbytables** [comment]
@xrmzju , thank you for all your help with controller-runtime and cluster-api :)

I've created PR #1485  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
