### ISSUE TITLE
REQUEST: New membership for @aaroniscode

### ISSUE THREAD

**Issue by aaroniscode** [kubernetes/org#1478]
### GitHub Username
@aaroniscode

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @detiber
- @moshloop

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api/pull/1641
  - https://github.com/kubernetes-sigs/cluster-api/pull/1616
  - https://github.com/kubernetes-sigs/cluster-api/pull/1590
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/979
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/985
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1023
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1029
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1033
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1232
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1263
  - https://github.com/kubernetes-sigs/image-builder/pull/69
  - https://github.com/kubernetes-sigs/image-builder/pull/65
  - https://github.com/kubernetes-sigs/image-builder/pull/68
- Issues responded to
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1167
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1062
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/cluster-api
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws
  - https://github.com/kubernetes-sigs/image-builder

**Comment by detiber** [comment]
+1 @aaroniscode has been an incredible asset to the cluster-api, cluster-api-provider-aws, and image-builder projects.

**Comment by moshloop** [comment]
+1

**Comment by mrbobbytables** [comment]
@aaroniscode, thank you for all your help with the cluster-api and image-builder :)

I've created PR #1485  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
