### ISSUE TITLE
REQUEST: New membership for chrisohaver

### ISSUE THREAD

**Issue by chrisohaver** [kubernetes/org#148]
### GitHub Username
@chrisohaver

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123 (VMware)
- @wojtek-t (Google)

### List of contributions to the Kubernetes project
- [PRs authored](https://github.com/pulls?utf8=✓&q=is%3Apr+author%3Achrisohaver+is%3Amerged+repo%3Akubernetes%2Fkubernetes+repo%3Akubernetes%2Fwebsite+repo%3Akubernetes%2Fdns+repo%3Akubernetes%2Ftest-infra+repo%3Akubernetes%2Fperf-tests)
- Issues responded to: Being a maintainer of CoreDNS, I watch for mentions of "DNS" in the kubernetes repos, and across kubernetes slack channels, and try to help out where I can.
- sig-networking, sig-scalability

**Comment by johnbelamaric** [comment]
+1

**Comment by wojtek-t** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @chrisohaver ! Unfortunately it doesn't appear that your sponsors meet the requirements for being sponsors ([they must be from different member companies](https://git.k8s.io/community/community-membership.md#requirements)). Would you mind soliciting another sponsor from an organization other than Google? Thanks!

**Comment by chrisohaver** [comment]
i'll re-open If I can find an owner not working at Google.

**Comment by neolit123** [comment]
i sponsor @chrisohaver with a +1.

**Comment by mrbobbytables** [comment]
Awesome, thanks for jumping in @neolit123! 

@chrisohaver thanks for all the work you've done so far! :)

I've created PR #152  to add you to the main Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
