### ISSUE TITLE
REQUEST: New membership for ggriffiths

### ISSUE THREAD

**Issue by ggriffiths** [kubernetes/org#1480]
### GitHub Username
e.g. @ggriffiths

### Organization you are requesting membership in
e.g. @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @msau42 
- @jsafrane 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/test-infra/pull/15556
https://github.com/kubernetes/test-infra/pull/15290
https://github.com/kubernetes/kubernetes/pull/83338
https://github.com/kubernetes/website/pull/16682
https://github.com/kubernetes-csi/csi-driver-host-path/pull/126
https://github.com/kubernetes-csi/csi-driver-host-path/pull/124
https://github.com/kubernetes-csi/csi-driver-host-path/pull/98
https://github.com/kubernetes-csi/csi-release-tools/pull/45
https://github.com/kubernetes-csi/external-snapshotter/pull/153 (pending)
https://github.com/kubernetes-csi/external-provisioner/pull/274
https://github.com/kubernetes-csi/docs/pull/167
https://github.com/kubernetes-csi/docs/pull/168
https://github.com/kubernetes-csi/docs/pull/171
https://github.com/kubernetes-csi/external-provisioner/pull/301
https://github.com/kubernetes-csi/external-snapshotter/pull/138
https://github.com/kubernetes-csi/external-snapshotter/pull/171
https://github.com/kubernetes-csi/external-resizer/pull/55

- Issues responded to
https://github.com/kubernetes/website/issues/16680
https://github.com/kubernetes-csi/external-snapshotter/issues/159
https://github.com/kubernetes-csi/external-snapshotter/issues/168
https://github.com/kubernetes-csi/external-provisioner/issues/278
https://github.com/kubernetes-csi/external-snapshotter/issues/134
https://github.com/kubernetes-csi/docs/issues/150
https://github.com/kubernetes-csi/external-snapshotter/issues/132

- SIG projects I am involved with
kubernetes-csi
sig-storage

**Comment by msau42** [comment]
+1 Grant has been doing a lot of great working with the snapshots feature!

**Comment by jsafrane** [comment]
+1 for his snapshot work.

**Comment by mrbobbytables** [comment]
Hey there @ggriffiths , thank you for all your help with csi :)

I've created PR #1485  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by ggriffiths** [comment]
Thank you all!
