### ISSUE TITLE
Administrative access to kubernetes-sigs/cri-tools for saschagrunert

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/org#1484]
### Organization or repository

[kubernetes-sigs/cri-tools](https://github.com/kubernetes-sigs/cri-tools)

### Users affected

@saschagrunert 

### Describe the issue

I need admin access to draft releases and edit tags, so I'm kindly asking to grant me those. :)

Referring to: https://github.com/kubernetes-sigs/cri-tools/issues/558

**Comment by justaugustus** [comment]
cc: @kubernetes/owners

@feiskyer @Random-Liu for approval

**Comment by feiskyer** [comment]
+1

**Comment by nikhita** [comment]
https://github.com/kubernetes/org/blob/a8c57014da22fa0ae73fa8a94b4262336a31c47f/config/kubernetes-sigs/org.yaml#L424-L431

Please create a PR against this when ready. :)

**Comment by saschagrunert** [comment]
> Please create a PR against this when ready. :)

Okay, did it in #1495

**Comment by cblecker** [comment]
Fixed in #1495 
/close
