### ISSUE TITLE
REQUEST: New membership for pjh

### ISSUE THREAD

**Issue by pjh** [kubernetes/org#1489]
### GitHub Username
@pjh

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @PatrickLang 
- @michmike 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=author%3Apjh
https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=assignee%3Apjh+

- Issues responded to
https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=assignee%3Apjh+is%3Aclosed

- SIG projects I am involved with
sig/windows

**Comment by mrbobbytables** [comment]
@pjh Just an FYI -- as a member of the Kubernetes org, you do not need sponsorship to join the other kubernetes orgs :) 
If you want, please feel free to PR yourself into k-sigs (commit msg should be `Add pjh to kubernetes-sigs org.`), or you can wait till we add the next batch of folk 👍

**Comment by pjh** [comment]
Ah, ok! I did not see that in https://github.com/kubernetes/community/blob/master/community-membership.md#member but maybe I just did not read carefully enough.

I will send a PR.
