### ISSUE TITLE
REQUEST: Membership to kubernetes-sigs for @jefftree

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/org#1491]
### GitHub Username
@Jefftree 

### Organization you are requesting membership in

kubernetes-sigs

Am already a kubernetes member.

Ref: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/46#issuecomment-565662483

**Comment by nikhita** [comment]
/close
Fixed by https://github.com/kubernetes/org/pull/1492

@Jefftree you should get an invite to join @kubernetes-sigs from the bot soon. :)
