### ISSUE TITLE
REQUEST: New membership for <zehuaiWANG>

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/org#1494]
### GitHub Username
@zehuaiWANG

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @shu-mutou  
- @hwdef 
- @tanjunchen  

### List of contributions to the Kubernetes project
- PRs reviewed / authored

1. [kubernetes/dashboard pr#4496](https://github.com/kubernetes/dashboard/pull/4496) -add list/detail for roleBinding and clusterRoleBinding resource 
2. [kubernetes/dashboard pr#4480](https://github.com/kubernetes/dashboard/pull/4480) -add list/details for Role resource
3. [kubernetes/dashboard pr#4615](https://github.com/kubernetes/dashboard/pull/4615) -Add hpa handler for deployment
4. [kubernetes/dashborad pr#4597](https://github.com/kubernetes/dashboard/pull/4597) -Support filtering according to the type of service 
5. [kubernetes/dashboard pr#4475](https://github.com/kubernetes/dashboard/pull/4475) -remove some useless code in handler/apihandler.api
6. [kubernetes/dashboard pr#4468](https://github.com/kubernetes/dashboard/pull/4468) -remove some useless codes 
7. [kubernetes/dashboard pr#4437](https://github.com/kubernetes/dashboard/pull/4437) -use golint and fix typo
8. [kubernetes/dashboard pr#4432](https://github.com/kubernetes/dashboard/pull/4432) -Use golint
9. [kubernetes/dashboard pr#4424](https://github.com/kubernetes/dashboard/pull/4424) -Reduce code duplication and fix typo
10. [kubernetes/dashboard pr#4340](https://github.com/kubernetes/dashboard/pull/4340) -modify the comment in pod/common.go
11. [kubernetes/kops pr#8127](https://github.com/kubernetes/kops/pull/8127) - a little change
- Issues responded to
1. [kubernetes/dashboard issue#4596](https://github.com/kubernetes/dashboard/issues/4596) -Support filtering according to the type of service 
2. [kubernetes/kubernetes issue#86181](https://github.com/kubernetes/kubernetes/issues/86181) -[Flaky Test] [sig-storage] PersistentVolumes GCEPD should test that deleting the Namespace of a PVC and Pod causes the successful detach of Persistent Disk
3. [kubernetes/dashboard issue#4317](https://github.com/kubernetes/dashboard/issues/4317) -Modify the pod/common.go code to make it more concise and high performance
4. [kubernetes/dashboard issue#4461](https://github.com/kubernetes/dashboard/issues/4461) -Create documentation about building the Dashboard
5. [kubernetes/dashboard issue#4405](https://github.com/kubernetes/dashboard/issues/4405) -Why does dashborad not support multi-cluster management?
6. [kubernetes/dashboard issue#4473](https://github.com/kubernetes/dashboard/issues/4473) -some feature about taints、tolerations and labels managerment
7. [kubernetes/dashboard issue#4416](https://github.com/kubernetes/dashboard/issues/4416) -modified the IsLabelSelectorMatching function to reduce code duplications and fix typo in src/app/backend/api/types.go

**Comment by shu-mutou** [comment]
Big +1!
@zehuaiWANG has been contributing in SIG-UI and has been active in the community.

**Comment by hwdef** [comment]
+1 
Thanks for your contirbutions.

**Comment by tanjunchen** [comment]
+1
Thanks for your contirbutions.

**Comment by nzoueidi** [comment]
Hey there @zehuaiWANG, thank you for all your contributions so far :)

I've created PR #1496 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes 🎉
