### ISSUE TITLE
REQUEST: New membership for <zhouya0>

### ISSUE THREAD

**Issue by zhouya0** [kubernetes/org#1498]
### GitHub Username
@zhouya0

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @seans3
- @neolit123
- @soltysh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/83825 -fix kubectl delete semantic error
https://github.com/kubernetes/kubernetes/pull/85174 -add table convertor to componentstatus
https://github.com/kubernetes/kubernetes/pull/85406 -kubectl change podSecurityPolicy group
https://github.com/kubernetes/kubernetes/pull/85595 -add test coverage with kubectl get components
https://github.com/kubernetes/kubernetes/pull/85597 (which i think is going to be merged) -fix wrong cached klog message
https://github.com/kubernetes/website/pull/17810 -fix secret not working
https://github.com/kubernetes/website/pull/17923 -fix path not consistent

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/83721
https://github.com/kubernetes/kubectl/issues/754
https://github.com/kubernetes/kubectl/issues/762
https://github.com/kubernetes/kubernetes/issues/85314
https://github.com/kubernetes/kubernetes/issues/85277
https://github.com/kubernetes/kubernetes/issues/85648
https://github.com/kubernetes/kubernetes/pull/86402
https://github.com/kubernetes/kubectl/issues/775
https://github.com/kubernetes/kubectl/issues/787
https://github.com/kubernetes/kubectl/issues/772
https://github.com/kubernetes/website/issues/17597

**Comment by seans3** [comment]
+1

**Comment by neolit123** [comment]
+1

**Comment by soltysh** [comment]
:+1:

**Comment by nzoueidi** [comment]
Hey there @zhouya0, thank you for all your contributions so far :)

I've created PR #1502  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
