### ISSUE TITLE
REQUEST: New membership for truongnh1992

### ISSUE THREAD

**Issue by truongnh1992** [kubernetes/org#1501]
### GitHub Username
@truongnh1992

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ngtuna 
- @remyleone
- @huynguyennovem 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - kubernetes/kubernetes#74107
    - kubernetes/kubernetes#74116
    - kubernetes/kubernetes#74121
    - kubernetes/kubernetes#74124
    - kubernetes/kubernetes#74174
    - kubernetes/website#17868
    - kubernetes/website#17861
    - kubernetes/website#17854
    - kubernetes/website#17823
    - kubernetes/website#17785
    - kubernetes/website#17715
    - kubernetes/website#17647
    - kubernetes/website#17655
    - kubernetes/website#17822
    - kubernetes/website#17684
    - kubernetes/website#17653
    - kubernetes/website#17629
    - kubernetes/website#18181
    - kubernetes/website#18105
    - kubernetes/website#18101
    - kubernetes/website#18013
    - kubernetes/website#17825
    - kubernetes/org#1431
    - kubernetes/org#1323
    - kubernetes/community#4190
    - kubernetes/test-infra#14817
- Issues responded to
    - kubernetes/kubernetes#77628
- SIG projects I am involved with
    - [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder)
    - [kind](https://github.com/kubernetes-sigs/kind)

**Comment by huynguyennovem** [comment]
+1

**Comment by remyleone** [comment]
👍

**Comment by truongnh1992** [comment]
Thank you @huynguyennovem and @remyleone

**Comment by ngtuna** [comment]
👍

**Comment by nzoueidi** [comment]
Hey @truongnh1992 once this PR gets merged, you should get a membership invite notification for kubernetes-sigs org.

Thank you.
