### ISSUE TITLE
REQUEST: New membership for vishakhanihore

### ISSUE THREAD

**Issue by vishakhanihore** [kubernetes/org#1503]
### GitHub Username

vishakhanihore

### Organization you are requesting membership in

kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman
- @mrbobbytables 

### List of contributions to the Kubernetes project
- PRs reviewed / authored -: 
https://github.com/kubernetes/community/pull/4334
https://github.com/kubernetes/community/pull/4343
https://github.com/kubernetes/community/pull/4338
https://github.com/kubernetes/community/pull/4345
https://github.com/kubernetes/community/pull/4344
https://github.com/kubernetes/community/pull/4335
https://github.com/kubernetes/community/pull/4332
https://github.com/kubernetes/community/pull/4326
https://github.com/kubernetes/community/pull/4327
https://github.com/kubernetes/community/pull/4342
https://github.com/kubernetes/community/pull/4346

- Issues responded to -:
https://github.com/kubernetes/community/issues/4333
https://github.com/kubernetes/community/issues/4111
https://github.com/kubernetes/community/issues/4086
https://github.com/kubernetes/community/issues/3064
https://github.com/kubernetes/community/issues/4324
https://github.com/kubernetes/community/issues/923
https://github.com/kubernetes/community/issues/4077
https://github.com/kubernetes/community/issues/2759
https://github.com/kubernetes/community/issues/1645
https://github.com/kubernetes/community/issues/1514
https://github.com/kubernetes/community/issues/1644

- SIG projects I am involved with- 
`Contributor Guide`, `Developer GUide`

**Comment by mrbobbytables** [comment]
+1 from sponsor :)

**Comment by parispittman** [comment]
+1 from sponsor 

welcome, @vishakhanihore!

**Comment by mrbobbytables** [comment]
@vishakhanihore  thank you for all your contributions so far \o/

I've created PR #1504   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
/honk
/pony party
