### ISSUE TITLE
REQUEST: New membership for du2016

### ISSUE THREAD

**Issue by du2016** [kubernetes/org#1505]
### GitHub Username
@du2016

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Mr-Linus 
- @MJ-CJM 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/dashboard/pull/1413
https://github.com/kubernetes/website/pull/2047
https://github.com/kubernetes/website/pull/2055
https://github.com/kubernetes/kubernetes/pull/38945/files
https://github.com/kubernetes/kubernetes/pull/40906/files
https://github.com/kubernetes/kubernetes/pull/38808/files

- issue
https://github.com/kubernetes/minikube/issues/2061

**Comment by cblecker** [comment]
It seems you have deleted the sponsorship section, but you’ve indicated that you have spoken to your sponsors. Can you please clarify?

**Comment by du2016** [comment]
@cblecker done,thanks

**Comment by Mr-Linus** [comment]
+1 👍

**Comment by MJ-CJM** [comment]
+1 👍

**Comment by nzoueidi** [comment]
Hey @du2016 looks like @Mr-Linus and @MJ-CJM are not an approvers nor reviewers in the kubernetes org. Could you please look for sponsors that are already approvers or reviewers in the org. 
More information about the github org membership are here:  https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by du2016** [comment]
ok thanks
