### ISSUE TITLE
REQUEST: New membership for mfilocha

### ISSUE THREAD

**Issue by mfilocha** [kubernetes/org#1506]
### GitHub Username
@mfilocha

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @remyleone
- @rbenzair

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/website/pull/18254
- https://github.com/kubernetes/test-infra/pull/15684
- https://github.com/kubernetes/community/pull/4348

**Comment by rbenzair** [comment]
+1 👍

**Comment by rbenzair** [comment]
Thank for your contribution to the kubernetes translation. You are welcome

**Comment by remyleone** [comment]
:+1:

Em qui, 26 de dez de 2019 13:33, Reda Benzair <notifications@github.com>
escreveu:

**Comment by nzoueidi** [comment]
Hey there @mfilocha, thank you for all your contributions so far :)

I've created PR #1507 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
