### ISSUE TITLE
REQUEST: New membership for warmchang

### ISSUE THREAD

**Issue by warmchang** [kubernetes/org#151]
### GitHub Username
@warmchang

### Organization you are requesting membership in
[@kubernetes](https://github.com/kubernetes)
[@kubernetes-incubator](https://github.com/kubernetes-incubator)

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@zhangxiaoyu-zidif 
@xiangpengzhao 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - [PRs authored](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Awarmchang+repo%3Akubernetes%2Fkubernetes+repo%3Akubernetes%2Fwebsite+repo%3Akubernetes%2Fcommunity+repo%3Akubernetes%2Fcloud-provider-openstack+repo%3Akubernetes%2Fperf-tests+repo%3Akubernetes%2Fminikube+repo%3Akubernetes%2Fingress-nginx+repo%3Akubernetes%2Fcontrib+repo%3Akubernetes-incubator%2Fexternal-storage+repo%3Akubernetes-incubator%2Fkubespray+)
    - [PRs reviewed](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Awarmchang+repo%3Akubernetes%2Fkubernetes+repo%3Akubernetes%2Fwebsite+repo%3Akubernetes%2Fcommunity+repo%3Akubernetes%2Fcloud-provider-openstack+repo%3Akubernetes%2Fperf-tests+repo%3Akubernetes%2Fminikube+repo%3Akubernetes%2Fingress-nginx+repo%3Akubernetes%2Fcontrib+repo%3Akubernetes-incubator%2Fexternal-storage+repo%3Akubernetes-incubator%2Fkubespray+)
    - [PRs mentions](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+mentions%3Awarmchang+repo%3Akubernetes%2Fkubernetes+repo%3Akubernetes%2Fwebsite+repo%3Akubernetes%2Fcommunity+repo%3Akubernetes%2Fcloud-provider-openstack+repo%3Akubernetes%2Fperf-tests+repo%3Akubernetes%2Fminikube+repo%3Akubernetes%2Fingress-nginx+repo%3Akubernetes%2Fcontrib+repo%3Akubernetes-incubator%2Fexternal-storage+repo%3Akubernetes-incubator%2Fkubespray+)

- Issues responded to
    - [Issues authored](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Awarmchang+repo%3Akubernetes%2Fkubernetes+repo%3Akubernetes%2Fwebsite+repo%3Akubernetes%2Fcommunity+repo%3Akubernetes%2Fcloud-provider-openstack+repo%3Akubernetes%2Fperf-tests+repo%3Akubernetes%2Fminikube+repo%3Akubernetes%2Fingress-nginx+repo%3Akubernetes%2Fcontrib+repo%3Akubernetes-incubator%2Fexternal-storage+repo%3Akubernetes-incubator%2Fkubespray+repo%3Akubernetes%2Fautoscaler+repo%3Akubernetes%2Fdashboard+repo%3Akubernetes-sigs%2Fkubeadm-dind-cluster+repo%3Akubernetes%2Fkubeadm)
    - [Issues mentions](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+mentions%3Awarmchang+repo%3Akubernetes%2Fkubernetes+repo%3Akubernetes%2Fwebsite+repo%3Akubernetes%2Fcommunity+repo%3Akubernetes%2Fcloud-provider-openstack+repo%3Akubernetes%2Fperf-tests+repo%3Akubernetes%2Fminikube+repo%3Akubernetes%2Fingress-nginx+repo%3Akubernetes%2Fcontrib+repo%3Akubernetes-incubator%2Fexternal-storage+repo%3Akubernetes-incubator%2Fkubespray+repo%3Akubernetes%2Fautoscaler+repo%3Akubernetes%2Fdashboard+repo%3Akubernetes-sigs%2Fkubeadm-dind-cluster+repo%3Akubernetes%2Fkubeadm)

- SIG projects I am involved with
    - sig-docs
    - sig-storage
    - sig-node

**Comment by mrbobbytables** [comment]
Hey there @warmchang , thank you for all your contributions so far :)

I've created PR #156  to add you to both the Kubernetes and Kubernetes-Incubator Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
