### ISSUE TITLE
REQUEST: New membership for hakman

### ISSUE THREAD

**Issue by hakman** [kubernetes/org#1514]
### GitHub Username
@hakman

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justinsb 
- @rifelpet 

### List of contributions to the Kubernetes project
https://github.com/kubernetes/kops/pulls?utf8=✓&q=is%3Apr+author%3Ahakman+
* PRs reviewed / authored:
https://github.com/kubernetes/kops/pull/7986
https://github.com/kubernetes/kops/pull/8020
https://github.com/kubernetes/kops/pull/8164
https://github.com/kubernetes/kops/pull/8104
https://github.com/kubernetes/kops/pull/8076
https://github.com/kubernetes/test-infra/pull/15669
https://github.com/kubernetes/website/pull/17405

**Comment by rifelpet** [comment]
+1 👍 
Thank you for the great work so far! I'm looking forward to your future contributions and involvement

**Comment by justinsb** [comment]
Big +1 from me also!

**Comment by hakman** [comment]
Thank you @rifelpet @justinsb ! :)

**Comment by nzoueidi** [comment]
Hey there @hakman, thank you for all your contributions so far :)

I've created PR #1521 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
