### ISSUE TITLE
REQUEST: New membership for marwanad

### ISSUE THREAD

**Issue by marwanad** [kubernetes/org#1518]
### GitHub Username
@marwanad

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @feiskyer 
- @juan-lee 
- @tariq1890 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/autoscaler/pull/2714
https://github.com/kubernetes/autoscaler/pull/2699
https://github.com/kubernetes/autoscaler/pull/2674
https://github.com/kubernetes/autoscaler/pull/2671
https://github.com/kubernetes/autoscaler/pull/2661
- Issues responded to
- SIG projects I am involved with
formely cluster-api-provider-azure

**Comment by feiskyer** [comment]
+1 for @marwanad contribution to autoscaler.

**Comment by tariq1890** [comment]
+1 :)

**Comment by juan-lee** [comment]
+1 based on @marwanad's contribution to cluster autoscaler and cluster-api-provider-azure

**Comment by justaugustus** [comment]
+1!

**Comment by nzoueidi** [comment]
Hey there @marwanad, thank you for all your contributions so far :)

I've created PR #1521 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
