### ISSUE TITLE
Archive kubernetes-sigs/testing_frameworks

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/org#1519]
### Repository to archive
[kubernetes-sigs/testing_frameworks]

### Repository and/or sig subproject owners that are approving this archival
@hoegaarden
@DirectXMan12 

### When should this be done
Anytime

### Additional context for request
The repo only holds one lib / framework. This framework is only been used by [kubernetes-sigs/controller-runtime], we don't know of any and couldn't find any other users. There is not much use in separating them.
There is an [issue] discussing the move from [kubernetes-sigs/testing_frameworks] to [kubernetes-sigs/controller-runtime] and a [PR] doing the move.
Let me know if and which things I should handle from the list of Todos I found [here][todos].

[kubernetes-sigs/testing_frameworks]: https://github.com/kubernetes-sigs/testing_frameworks
[kubernetes-sigs/controller-runtime]: https://github.com/kubernetes-sigs/controller-runtime
[issue]: https://github.com/kubernetes-sigs/controller-runtime/issues/676
[PR]: https://github.com/kubernetes-sigs/controller-runtime/pull/749
[todos]: https://github.com/kubernetes/community/blob/2c7a172d0f59c8807c242f2bdce87d6d174bb66c/github-management/org-owners-guide.md#removing-repositories

**Comment by mrbobbytables** [comment]
/assign @spiffxp @stevekuznetsov @fejta 
For sign off from the [sub-project owning sig (testing)](https://github.com/kubernetes/community/blob/master/sig-testing/README.md#testing-commons)

**Comment by spiffxp** [comment]
LGTM as sig testing chair

**Comment by nikhita** [comment]
Repo has been archived: https://github.com/kubernetes-retired/testing_frameworks

Created:
- https://github.com/kubernetes/org/pull/1572 - to remove GitHub teams
- https://github.com/kubernetes/community/pull/4421 - to remove the repo from sigs.yaml

Sent notice to k-dev ML: https://groups.google.com/forum/#!topic/kubernetes-dev/cZhGkUIrsLg

**Comment by nikhita** [comment]
Both PRs have merged.

/close
