### ISSUE TITLE
REQUEST: New membership for robscott

### ISSUE THREAD

**Issue by robscott** [kubernetes/org#1522]
### GitHub Username
@robscott 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @aojea
- @bowei

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pulls/robscott
- https://github.com/kubernetes/enhancements/pulls/robscott
- https://github.com/kubernetes/website/pulls/robscott

**Comment by aojea** [comment]
+1 @robscott

**Comment by mrbobbytables** [comment]
As a member of Kubernetes, you're implicitly allowed to join the other organizations. You don't need sponsorship :)
If you need immediate access, please feel free to open a PR adding yourself to the kubernetes-sigs org. 
If not, it'll get handled when the next batch of membership requests are processed 👍 

If you have questions, please feel free to poke me here or on slack.

Thanks!

**Comment by bowei** [comment]
+1
