### ISSUE TITLE
REQUEST: New membership for johngmyers

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/org#1527]
### GitHub Username
@johngmyers

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rifelpet 
- @mikesplain 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - Reviewed: kubernetes/kops#8088 kubernetes/kops#8139
  - Authored: kubernetes/kops#8021 kubernetes/kops#7904
- Issues responded to
  kubernetes/kops#8243 kubernetes/kops#7902 kubernetes/kops#7258
- SIG projects I am involved with
  kubernetes/kops (sig-cluster-lifecycle)

**Comment by rifelpet** [comment]
+1 from me, thanks for your contributions!

**Comment by mikesplain** [comment]
+1 thanks for the hard work!

**Comment by mrbobbytables** [comment]
Hey there @johngmyers , thank you for all your contributions to the kops project \o/

I've created PR #1544  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
