### ISSUE TITLE
Migrate cluster-capacity to kubernetes-sigs

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/org#1529]
### New Repo, Staging Repo, or migrate existing
migrate existing (https://github.com/kubernetes-incubator/cluster-capacity)

### Requested name for new repository
cluster-capacity

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@ingvagabund

### If not a staging repo, who should have write access
@ingvagabund

### If not a staging repo, who should be listed as approvers in OWNERS
@ingvagabund

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@ingvagabund

### What should the repo description be
Cluster capacity analysis

### What SIG and subproject does this fall under in sigs.yaml
sig-scheduling

### Approvals
https://github.com/kubernetes/kubernetes/issues/85399#issuecomment-561631786

### Additional context for request
None

**Comment by ahg-g** [comment]
/sig scheduling

Sounds good to me.

**Comment by mrbobbytables** [comment]
The repo has been migrated: http://github.com/kubernetes-sigs/cluster-capacity
Teams were updated in: #1561 
Update to sig project list is here: https://github.com/kubernetes/community/pull/4408

Once the update is merged, the migration should be complete 👍

**Comment by mrbobbytables** [comment]
That was quick, the sig project list has been updated and the repo migration should be complete.
If you have any questions feel free to ask here or ping in slack.
Thanks!

/close
