### ISSUE TITLE
Create https://github.com/kubernetes-csi/kubernetes-csi-migration-library

### ISSUE THREAD

**Issue by davidz627** [kubernetes/org#153]
### New Repo, or migrate existing
Please create a new repo

### Requested name for new repository
https://github.com/kubernetes-csi/kubernetes-csi-migration-library

### Which Organization should it reside
kubernetes-csi

### Who should be provided access to this repository
Please make:
https://github.com/davidz627
https://github.com/saad-ali
owners

### Approvals
https://groups.google.com/forum/#!topic/kubernetes-sig-storage-wg-csi/YHHGqTkLets
Approved by sig-lead Saad Ali

### Additional context for request

I am proposing to create a new repository in the "kubernetes-csi" github organization to house the translation library for in-tree to CSI Migration for Kubernetes.
The background and design for this can be found here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md
This library will house the logic for converting between CSI Source and each In-tree Source and vice-versa.

**Comment by davidz627** [comment]
PTAL @cblecker @spiffxp

**Comment by spiffxp** [comment]
Created
- https://github.com/kubernetes-csi/kubernetes-csi-migration-library
- https://github.com/orgs/kubernetes-csi/teams/kubernetes-csi-migration-library-admins
- https://github.com/orgs/kubernetes-csi/teams/kubernetes-csi-migration-library-maintainers

Updated OWNERS and SECURITY_CONTACTS to match the requested owners

**Comment by spiffxp** [comment]
/close
Please ping here or reopen if something appears to be off, otherwise I think you're all set!
