### ISSUE TITLE
REQUEST: New membership for phumberdroz

### ISSUE THREAD

**Issue by phumberdroz** [kubernetes/org#1530]
### GitHub Username
@phumberdroz

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @castrojo

### List of contributions to the Kubernetes project
https://github.com/kubernetes/community/issues/4350
Slack by helping others

**Comment by castrojo** [comment]
+1 from me, I will be mentoring Pierre through the slack moderation process.

**Comment by mrbobbytables** [comment]
+1 from me as well.

**Comment by jeefy** [comment]
+1

**Comment by phumberdroz** [comment]
Will reopen in a couple of weeks since per channel moderation seems to work without being a kubernetes member

**Comment by castrojo** [comment]
Ok Pierre has been sticking around and enough time has passed that I'm comfortable reopening this application:

- Office Hours panelist, this includes answering questions on stream and prep work, like helping prep the show notes, collection questions.
- Being active helping answer user questions in slack and triaging them to the right SIGs. 
- Actively attending and participating in our contribex meetings and taking on community work.

**Comment by phumberdroz** [comment]
Thanks @castrojo !

**Comment by nzoueidi** [comment]
Hey there @phumberdroz , thank you for all your contributions so far :)

I've created PR #1850 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
