### ISSUE TITLE
REQUEST: New membership for elisiano

### ISSUE THREAD

**Issue by elisiano** [kubernetes/org#1531]
### GitHub Username
@elisiano

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ ] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @castrojo

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/community/issues/4350
- https://github.com/kubernetes/kubernetes/pull/77781
- https://github.com/kubernetes/kops/issues/4276
- https://github.com/kubernetes/kops/pull/6871

**Comment by castrojo** [comment]
+1 from me, I will be mentoring Elisiano through the slack moderation process.

**Comment by mrbobbytables** [comment]
+1 from other slack admin.

**Comment by jeefy** [comment]
+1

**Comment by elisiano** [comment]
As discussed over slack this is not needed for now, closing it.
