### ISSUE TITLE
REQUEST: New membership for helayoty

### ISSUE THREAD

**Issue by helayoty** [kubernetes/org#1532]
### GitHub Username
@helayoty

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jeremyrickard
- @mrbobbytables

### List of contributions to the Kubernetes project
* PRs reviewed / authored
* Issues responded to
* SIG projects I am involved with
   * release

**Comment by jeremyrickard** [comment]
+1 from me! Thank you for volunteering to help with the 1.18 release team @helayoty!

**Comment by mrbobbytables** [comment]
+1 thanks for helping with the 1.18 release :)

**Comment by justaugustus** [comment]
+1! :)

**Comment by mrbobbytables** [comment]
@helayoty thank you for helping with enhancements for the 1.18 release :)

I've created PR #1544  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
