### ISSUE TITLE
REQUEST: New membership for nvtkaszpir

### ISSUE THREAD

**Issue by nvtkaszpir** [kubernetes/org#1533]
### GitHub Username
@nvtkaszpir

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @remyleone
- @rlenferink

### List of contributions to the Kubernetes project
SIG projects I am involved with:
- https://github.com/kubernetes/website Polish translation

**Comment by rlenferink** [comment]
+1 @nvtkaszpir is helping with the Polish translation of our docs 🎉

**Comment by remyleone** [comment]
:+1:

**Comment by mrbobbytables** [comment]
@nvtkaszpir  , thank you for your help with the polish localization efforts :)

I've created PR #1544  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
