### ISSUE TITLE
REQUEST: New membership for YangLu1031

### ISSUE THREAD

**Issue by YangLu1031** [kubernetes/org#1534]
### GitHub Username
@YangLu1031

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @patricklang
- @justaugustus

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/test-infra/pull/15741
https://github.com/kubernetes/kubernetes/pull/85836
https://github.com/kubernetes-sigs/windows-testing/pull/121
https://github.com/kubernetes/perf-tests/pull/930
...
- Issues responded to
https://github.com/kubernetes/test-infra/issues/15267
https://github.com/kubernetes/test-infra/issues/15738
- SIG projects I am involved with
https://github.com/kubernetes/kubernetes
https://github.com/kubernetes/test-infra
https://github.com/kubernetes-sigs/windows-testing
https://github.com/kubernetes/perf-tests

**Comment by justaugustus** [comment]
+1 for Yang's work on Windows test-infra! :)

**Comment by PatrickLang** [comment]
+1 thanks for your contributions!

**Comment by mrbobbytables** [comment]
Hey there @YangLu1031, thank you for all your help with sig-windows!

I've created PR #1544  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
