### ISSUE TITLE
REQUEST: New membership for timyinshi

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/org#1536]
GitHub Username
@timyinshi

Organization you are requesting membership in
@kubernetes-sigs

Requirements
I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
I have enabled 2FA on my GitHub account (https://github.com/settings/security)
I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
I am actively contributing to 1 or more Kubernetes subprojects
I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors
@dankohn
@msau42
@tanjunchen

List of contributions to the Kubernetes project
PRs reviewed / authored
https://github.com/kubernetes-csi/docs/pull/250
       https://github.com/kubernetes/enhancements/pull/1385
https://github.com/kubernetes/kubernetes/pull/85170
https://github.com/kubernetes/kubernetes/pull/85129
https://github.com/kubernetes/kubernetes/pull/85626
https://github.com/kubernetes/enhancements/pull/1374
https://github.com/kubernetes/enhancements/pull/1378
https://github.com/kubernetes/enhancements/pull/1386
https://github.com/kubernetes/enhancements/pull/1414
https://github.com/kubernetes/enhancements/pull/1427
https://github.com/kubernetes/enhancements/pull/1428

Issues responded to
https://github.com/kubernetes/kubernetes/issues/78576
https://github.com/kubernetes/kubernetes/issues/78847
https://github.com/kubernetes/kubernetes/issues/78897
https://github.com/kubernetes/kubernetes/issues/78930
https://github.com/kubernetes/kubernetes/issues/79271
https://github.com/kubernetes/kubernetes/issues/77728
https://github.com/kubernetes/kubernetes/issues/79691
https://github.com/kubernetes/kubernetes/issues/79788
https://github.com/kubernetes/kubernetes/issues/85261

**Comment by tanjunchen** [comment]
+1 
Thanks your job for kk

**Comment by dankohn** [comment]
+1. @timyinshi has been an enthusiastic supporter and contributor from China

**Comment by msau42** [comment]
+1
@timyinshi has been very helpful fixing docs

**Comment by nzoueidi** [comment]
Hey there @timyinshi, thank you for all your contributions so far :)

I've created PR #1559 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
