### ISSUE TITLE
Archive localization repositories and teams

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/org#154]
### Repository to archive

The following localization repositories:

https://github.com/kubernetes/kubernetes-docs-ja
https://github.com/kubernetes/kubernetes-docs-ko
https://github.com/kubernetes/kubernetes-docs-zh

And their associated teams:

```
 @kubernetes/kubernetes-docs-ja-admins
 @kubernetes/kubernetes-docs-ja-maintainers
 @kubernetes/kubernetes-docs-ko-admins
 @kubernetes/kubernetes-docs-ko-maintainers
 @kubernetes/kubernetes-docs-zh-admins
 @kubernetes/kubernetes-docs-zh-maintainers
 @kubernetes/kubernetes-docs-zh-reviewers
```

These are replaced with localization-specific workflows and teams in `k/website`.

See https://github.com/kubernetes/website/pull/10485 for context.

### Repository and/or sig subproject owners that are approving this archival

@zacharysarah, Chair of [SIG Docs](https://github.com/kubernetes/community/tree/master/sig-docs)

### When should this be done

After https://github.com/kubernetes/website/pull/10485 merges (scheduled Friday, October 11)

### Additional context for request

From the description of https://github.com/kubernetes/website/pull/10485:

> The combination of native multilingual support and automated language labeling allows SIG Docs to consolidate l10n workflows in a single repository: `k/website`. This strategy scales appropriately with increasing numbers of localizations.

/sig docs
/assign @cblecker 

/cc @cstoku # kubernetes-docs-ja 
/cc @gochist # kubernetes-docs-ko
/cc @hanjiayao # kubernetes-docs-zh
/cc @kubernetes/sig-docs-maintainers

**Comment by zacharysarah** [comment]
@spiffxp @cblecker 👋 https://github.com/kubernetes/website/pull/10485 has merged.

**Comment by cblecker** [comment]
@zacharysarah Can those repos be archived at any time? Or would you like to keep them around a bit before taking this action?

**Comment by zacharysarah** [comment]
@cblecker They can be archived whenever you’re ready. 

All of the teams have signaled that they’ve suspended work, but if you’d like to practice an abundance of caution and keep them open at least over the weekend, that seems reasonable.

**Comment by cblecker** [comment]
@zacharysarah sounds good. I'll take of this next week then :)

**Comment by zacharysarah** [comment]
@cblecker 👋 All quiet over the weekend, feel free to merge this whenever.

**Comment by cblecker** [comment]
This is now done.
