### ISSUE TITLE
REQUEST: New membership for @wahyuoi

### ISSUE THREAD

**Issue by wahyuoi** [kubernetes/org#1540]
### GitHub Username
@wahyuoi

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @girikuncoro 
- @irvifa 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/website/pull/16165
- https://github.com/kubernetes/website/pull/16979
- https://github.com/kubernetes/website/pull/17035
- https://github.com/kubernetes/website/pull/17990
- https://github.com/kubernetes/website/pull/18159

**Comment by girikuncoro** [comment]
+1 , @wahyuoi has been helping out a lot in driving SIG Docs ID and localizing/reviewing a bunch of pages already, happy to collaborate more with him in Kubernetes community

**Comment by irvifa** [comment]
+1 from me, he’s been helping a lot.

**Comment by mrbobbytables** [comment]
@wahyuoi  thanks for all your help with the ID localization efforts \o/ 

I've created PR #1544  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
