### ISSUE TITLE
REQUEST: New membership for hrishin

### ISSUE THREAD

**Issue by hrishin** [kubernetes/org#1542]
### GitHub Username
@hrishin

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ ] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @droslean
- @alejandrox1 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
  https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Ahrishin+
  https://github.com/kubernetes/kompose/issues?q=is%3Aissue+author%3Ahrishin+is%3Aclosed
- SIG projects I am involved with

**Comment by droslean** [comment]
I sponsor. @hrishin is one of the ci-signal shadows for the 1.18 release cycle.

@justaugustus FYI

**Comment by mrbobbytables** [comment]
+1 thank you for helping with the 1.18 release :)

**Comment by mrbobbytables** [comment]
@hrishin I've created PR #1544   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by hrishin** [comment]
Thank you @droslean @justaugustus @mrbobbytables :bowing_man:
