### ISSUE TITLE
REQUEST: New membership for jpreese

### ISSUE THREAD

**Issue by jpreese** [kubernetes/org#1543]
### GitHub Username
@jpreese

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @droslean 
- @alejandrox1 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/15968 #didathing

- Issues responded to

- SIG projects I am involved with
To be active in ci-signal for 1.18

**Comment by droslean** [comment]
I sponsor. @jpreese is one of the ci-signal shadows for the 1.18 release cycle. 

@justaugustus FYI

**Comment by alejandrox1** [comment]
+1 

/cc @mrbobbytables @nzoueidi

**Comment by mrbobbytables** [comment]
Hey there @jpreese, thank you for help with the 1.18 release \o/

I've created PR #1544   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
