### ISSUE TITLE
REQUEST: New membership for dberkov

### ISSUE THREAD

**Issue by dberkov** [kubernetes/org#1547]
### GitHub Username
@dberkov

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [V] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [V] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [V] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [V] I am actively contributing to 1 or more Kubernetes subprojects
- [V] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [V] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @caesarxuchao 
- @cheftako 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/45
   - https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/46
- Issues responded to
- SIG projects I am involved with:
   - kubernetes-sigs/apiserver-network-proxy

**Comment by caesarxuchao** [comment]
+1

**Comment by andrewsykim** [comment]
+1 for contributions

Though should this be a kubernetes-sig membership request since contributions have only been to kubernetes-sig so far?

**Comment by andrewsykim** [comment]
I see the update now, thanks! +1

**Comment by cheftako** [comment]
+1, Though I think Andrew above should actually be the second sponsor.

**Comment by nzoueidi** [comment]
Hey there @dberkov, thank you for all your contributions so far :)

I've created PR #1559 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
