### ISSUE TITLE
REQUEST: New membership for mkhaas

### ISSUE THREAD

**Issue by mkhaas** [kubernetes/org#1550]
### GitHub Username
e.g. (at)mkaas
@mkhaas

### Organization you are requesting membership in
e.g. (at)kubernetes
(at)kubernetes

### Requirements
- [Y ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ Y] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [Y ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ ] I am actively contributing to 1 or more Kubernetes subprojects
- [ Y] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [Y ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- (at)karenhchu
@karenhchu
- (at)lachie83
@lachie83 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
https://github.com/kubernetes/website/pull/14434
https://github.com/kubernetes/community/pull/2114 

-SIG projects I am involved with

**Comment by karenhchu** [comment]
+1  
glad to have you on release team as a shadow!

**Comment by mkhaas** [comment]
thanks @karenhchu

**Comment by alejandrox1** [comment]
+1
welcome to the team
/assign @nzoueidi 
ptal

**Comment by nzoueidi** [comment]
Hey @mkhaas unfortunately, @karenhchu can't sponsor your org membership as they are not approvers and/or reviewers in the kubernetes org.

**Comment by karenhchu** [comment]
Hi there. I am the Communications leads for the K8s 1.18 Release Tam and @mkhaas is my shadow. My other shadow listed me as a sponsor and there were no issues there. Please advise on how to proceed. CC: @lachie83 / @alejandrox1

**Comment by nzoueidi** [comment]
That's true, looks like there is an issue with cs.k8s.io. Please ignore my previous comment for now.

**Comment by justaugustus** [comment]
+1 from me.

@nzoueidi -- Release Team shadows are an exception to this rule. 
They still require sponsors, but the sponsors will likely be Release Team role leads, which should be listed in OWNERS files for SIG Release.

Karen is listed here: https://raw.githubusercontent.com/kubernetes/sig-release/a48579c32c164276ef0014738be828dc1bf03ae0/releases/release-1.18/OWNERS

**Comment by nzoueidi** [comment]
Yep my bad, will proceed with this request in a few minutes.

**Comment by justaugustus** [comment]
Thanks!

**Comment by nzoueidi** [comment]
Hey there @mkhaas, thank you for all your contributions so far :)

I've created PR #1570 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
