### ISSUE TITLE
REQUEST: New membership for gianarb

### ISSUE THREAD

**Issue by gianarb** [kubernetes/org#1551]
### GitHub Username
@gianarb 
### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @smourapina 
- @alejandrox1

### List of contributions to the Kubernetes project
- SIG-Release 1.18 shadow for Bug Triage

**Comment by smourapina** [comment]
+1
Welcome to the team! 🎉

**Comment by alejandrox1** [comment]
+1 
welcome to the team @gianarb 

/assign @mrbobbytables

**Comment by nzoueidi** [comment]
Hey there @gianarb, thank you for all your contributions so far :)

I've created PR #1559 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by gianarb** [comment]
Thanks a lot!
