### ISSUE TITLE
REQUEST: New membership for cnadolny

### ISSUE THREAD

**Issue by cnadolny** [kubernetes/org#1552]
### GitHub Username
@cnadolny

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @karenhchu
- @lachie83 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
  - Shadow for the Communications Release Team for 1.18!!

**Comment by lachie83** [comment]
+1

**Comment by alejandrox1** [comment]
+1

**Comment by karenhchu** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @cnadolny, thank you for all your contributions so far :)

I've created PR #1559 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
