### ISSUE TITLE
REQUEST: New membership for jtslear

### ISSUE THREAD

**Issue by jtslear** [kubernetes/org#1553]
### GitHub Username
@jtslear

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @alejandrox1 
- @smourapina 

### List of contributions to the Kubernetes project
- Shadow for Bug Triage team for 1.18 release

**Comment by alejandrox1** [comment]
+1

**Comment by smourapina** [comment]
+1

**Comment by smourapina** [comment]
Great to have you on the team for 1.18! 🎉

**Comment by nzoueidi** [comment]
Hey there @jtslear, thank you for all your contributions so far :)

I've created PR #1559 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
