### ISSUE TITLE
REQUEST: New membership for @jluk

### ISSUE THREAD

**Issue by jluk** [kubernetes/org#1554]
### GitHub Username
@jluk

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lachie83 
- @evillgenius75 

### List of contributions to the Kubernetes project
- Release Team Shadow

**Comment by alejandrox1** [comment]
+1
welcome tothe team @jluk

**Comment by mrbobbytables** [comment]
+1 thanks for helping with release :)

**Comment by lachie83** [comment]
+1 welcome!

**Comment by nikhita** [comment]
@jluk thank you for all your contributions so far :)

I've created PR #1590  to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
