### ISSUE TITLE
REQUEST: New membership for reylejano-rxm

### ISSUE THREAD

**Issue by reylejano-rxm** [kubernetes/org#1555]
### GitHub Username
@reylejano-rxm

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @evillgenius75 
- @alejandrox1
- @lachie83 

### List of contributions to the Kubernetes project
- 1.18 Release Notes Shadow

**Comment by alejandrox1** [comment]
+1
Welcome to the team :)

**Comment by evillgenius75** [comment]
+1
Let's have some fun!

**Comment by alejandrox1** [comment]
/assign @nzoueidi 
ptal

**Comment by reylejano-rxm** [comment]
Updated request to add @lachie83 as a sponsor.

**Comment by nzoueidi** [comment]
My bad @reylejano-rxm, @evillgenius75 is already in OWNER file of sig release.

**Comment by nzoueidi** [comment]
Hey there @reylejano-rxm, thank you for all your contributions so far :)

I've created PR #1570 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
