### ISSUE TITLE
REQUEST: New membership for puerco

### ISSUE THREAD

**Issue by puerco** [kubernetes/org#1556]
### GitHub Username
@puerco

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @alejandrox1 
- @evillgenius75 

### List of contributions to the Kubernetes project
- Release shadow for 1.18 
- wg-k8s-infra contributor 
- PRs k8s.io/495 & k8s.io/469

**Comment by evillgenius75** [comment]
+1
Let's have some fun!

**Comment by puerco** [comment]
Thank you. let's do this :D

**Comment by alejandrox1** [comment]
/assign @nzoueidi 
ptal :smile:

**Comment by nzoueidi** [comment]
Hey @puerco, @evillgenius75 can't sponsor your org membership as they are not approver or/and reviewer in the kubernetes org.

**Comment by justaugustus** [comment]
+1 from me!

**Comment by nzoueidi** [comment]
Hey there @puerco, thank you for all your contributions so far :)

I've created PR #1570 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by puerco** [comment]
Thanks @justaugustus & @nzoueidi  !
