### ISSUE TITLE
REQUEST: New membership for rbitia

### ISSUE THREAD

**Issue by rbitia** [kubernetes/org#1557]
### GitHub Username
@rbitia 

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x ] I am actively contributing to 1 or more Kubernetes subprojects
- [x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@justaugustus 
@CecileRobertMichon 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/357
- SIG projects I am involved with 
Cluster API, CAPZ

**Comment by justaugustus** [comment]
Enthusiastic +1 from me!
Ria has been great contributing to work in both Cluster API Azure and SIG Release! :)

/honk

**Comment by CecileRobertMichon** [comment]
+1 !! 

🎉

**Comment by nzoueidi** [comment]
Hey there @rbitia, thank you for all your contributions so far :)

I've created PR #1559 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
