### ISSUE TITLE
REQUEST: New membership for Sh4d1

### ISSUE THREAD

**Issue by Sh4d1** [kubernetes/org#1558]
### GitHub Username
@Sh4d1

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cheftako 
- @andrewsykim 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/k8s.io/pull/421
   - https://github.com/kubernetes/website/pull/15244
  - https://github.com/kubernetes/node-problem-detector/pull/336
  - https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/35
  - https://github.com/kubernetes/kubernetes/pull/84381
  - https://github.com/kubernetes/k8s.io/pull/428
  - https://github.com/kubernetes/test-infra/pull/15011
  - https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/37
  - https://github.com/kubernetes/test-infra/pull/15090
  - https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/38
  - https://github.com/kubernetes/test-infra/pull/15137
  - https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/39
  - https://github.com/kubernetes/kubernetes/pull/85168
  - https://github.com/kubernetes/kubernetes/pull/85656
  - https://github.com/kubernetes/website/pull/12763
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/85250
  - https://github.com/kubernetes/kubernetes/issues/79783
  - https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/19
  - https://github.com/kubernetes/test-infra/issues/14091
  - https://github.com/kubernetes-sigs/kubespray/issues/4315
  - https://github.com/kubernetes-sigs/kubespray/issues/3985
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/apiserver-network-proxy

**Comment by andrewsykim** [comment]
+1

**Comment by remyleone** [comment]
:+1:

**Comment by cheftako** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @Sh4d1, thank you for all your contributions so far :)

I've created PR #1570 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
