### ISSUE TITLE
REQUEST: New membership for yujunz

### ISSUE THREAD

**Issue by yujunz** [kubernetes/org#1560]
### GitHub Username
yujunz

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Miouge1 
- @Liujingfang1 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/kubespray/pulls?q=is%3Apr+author%3Ayujunz+is%3Aclosed
  - https://github.com/kubernetes-sigs/kustomize/pulls?q=is%3Apr+author%3Ayujunz+is%3Aclosed
- Issues responded to
  - https://github.com/kubernetes-sigs/kubespray/issues?q=author%3Ayujunz
  - https://github.com/kubernetes-sigs/kustomize/issues?q=author%3Ayujunz
- SIG projects I am involved with
  - kubespray
  - kustomize

**Comment by Miouge1** [comment]
+1

**Comment by Liujingfang1** [comment]
+1

@yujunz has contributed to Kustomize for improving performance, fixing issues and writing documents.

**Comment by nzoueidi** [comment]
Hey @yujunz, unfortunately @Miouge1 and @Liujingfang1 are not approvers or/and reviewers in the kubernetes/kubernetes-sigs orgs.
You can find more info here: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by nzoueidi** [comment]
Hey there @yujunz, thank you for all your contributions so far :)

I've created PR #1570 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
