### ISSUE TITLE
REQUEST: New membership for kensipe

### ISSUE THREAD

**Issue by kensipe** [kubernetes/org#1562]
### GitHub Username
kensipe

### Organization you are requesting membership in
@kubernetes 
@kubernetes-sigs 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gerred 
- @alenkacz 

### List of contributions to the Kubernetes project
- PRs  [authored](https://github.com/search?q=org%3Akubernetes+kensipe&type=Issues)
- Working on [SIG-Arch](https://github.com/kubernetes/community/tree/master/sig-architecture) with @dims and @gerred 
- Working with https://github.com/kubernetes-sigs/kubebuilder 
- Participate on issues on https://github.com/kubernetes-sigs/controller-runtime and https://github.com/kubernetes-sigs/kubebuilder 
- Working in Slack in #kudo and #kubebuilder to help others build kubernetes operators
- One of the [top committers on Kudobuilder](https://github.com/kudobuilder/kudo/graphs/contributors)

**Comment by gerred** [comment]
+1

@kensipe has contributed to a lot of work in the controllers and operators space!

**Comment by dims** [comment]
+1 from me!

**Comment by alenkacz** [comment]
+1!

**Comment by nzoueidi** [comment]
Hey there @kensipe, thank you for all your contributions so far :)

I've created PR #1570 to add you to the Kubernetes & Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by kensipe** [comment]
thank you @nzoueidi !
