### ISSUE TITLE
Deprecate kubernetes-incubator/external-storage/

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/org#1563]
### Organization or repository
https://github.com/kubernetes-incubator/external-storage/

### Users affected
SIG Storage

### Describe the issue
This is a tracking bug. There is an effort to deprecate the https://github.com/kubernetes-incubator/ org

SIG Storage has an old repo https://github.com/kubernetes-incubator/external-storage/ which has a number of projects in it. Many of them have been deprecated, but we want to make sure all of them are moved or are ok to delete before we archive or delete the repo.

/assign @wongma7 

Related: https://groups.google.com/d/msg/kubernetes-sig-storage/W6OWDocLxfA/Jjf-tPZzAwAJ

**Comment by cblecker** [comment]
@saad-ali Any update on this? Have you been making progress in moving the active projects out?

**Comment by saad-ali** [comment]
New repos have been created for NFS:
* https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner
* https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner

Next steps:
* Move the NFS provisioner code to new repos - @kmova is working on this.
* SIG Storage has also identified the gluster provisioner as needing to be moved, so we'll have to create a repo and move the code for that. @humblec is working on this.

SIG storage is tracking this work and deprecation in our [Q2 planning](https://docs.google.com/spreadsheets/d/1t4z5DYKjX2ZDlkTpCnp18icRAQqOE85C1T1r2gqJVck/edit#gid=1092163339)

**Comment by mrbobbytables** [comment]
Checking back in -- with the gluster repos created and the WIP PRs open, is this in a good enough state to move forward with archival?

**Comment by kmova** [comment]
@mrbobbytables - I need to raise one more WIP PR for the NFS client code. I will ping back here as soon as I get that done.

**Comment by mrbobbytables** [comment]
Great, thanks for the update!

**Comment by mrbobbytables** [comment]
Checking back in again, how are things looking? Are we good to archive at this point?

**Comment by mrbobbytables** [comment]
@kmova @saad-ali do you think its ready to be archived?

**Comment by kmova** [comment]
@mrbobbytables Looks good from the NFS provisioners side. Went ahead and tagged all the Open PRs with a note to migrate to new repo. 

Btw, it is possible to move some of the open issues under that repo to the corresponding migrated repos prior to archiving it.

**Comment by mrbobbytables** [comment]
@kmova we can't transfer issues across orgs unfortunately :(

Maybe create new and just point to the closed issue as a reference?

**Comment by kmova** [comment]
sounds good. Will do that.

**Comment by nikhita** [comment]
/assign

Based on https://github.com/kubernetes/org/issues/1563#issuecomment-665906972, I am going to go ahead and archive the repo. Archiving the repo doesn't delete the repo, just makes it read-only. Code can still be moved. :+1:

**Comment by nikhita** [comment]
Repo has been archived - https://github.com/kubernetes-retired/external-storage

Created https://github.com/kubernetes/community/pull/5016 to remove from sigs.yaml

GitHub teams in the kubernetes-incubator org will be removed once we sunset the org (see https://github.com/kubernetes/org/pull/2094 for more details).

**Comment by nikhita** [comment]
Sent a notice to k-dev and sig storage mailing lists - https://groups.google.com/g/kubernetes-dev/c/rtvM7VS0FLY

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/5016 has merged. Closing :tada:

**Comment by Nuru** [comment]
@nikhita Where has support for EFS Provisioner moved to, or has it been abandoned?

**Comment by mrbobbytables** [comment]
@Nuru The EFS driver in external storage was deprecated. For future work, please see the efs csi driver:
https://github.com/kubernetes-sigs/aws-efs-csi-driver

**Comment by lowang-bh** [comment]
hi, where does the cephfs has moved to?
