### ISSUE TITLE
New repo kubernetes-sigs/scheduler-plugins

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/org#1564]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
scheduler-plugins

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
ahg-g, Huang-Wei

### If not a staging repo, who should have write access
ahg-g, Huang-Wei

### If not a staging repo, who should be listed as approvers in OWNERS
ahg-g, Huang-Wei

### If not a staging repo, who should be listed in SECURITY_CONTACTS
ahg-g, Huang-Wei

### What should the repo description be
Repository for out-of-tree scheduler plugins based on scheduler framework.

### What SIG and subproject does this fall under in sigs.yaml
sig-scheduling

### Approvals
ahg-g
- This idea has been discussed this is the sig meeting and got a consensus. The item is tracked here: https://docs.google.com/spreadsheets/d/1Dx44Ck7p28Y4XvXJMyKP_b7dwfEbcpZsX7QF6UQ5ZAE/edit#gid=705920834.
- k/k issue: https://github.com/kubernetes/kubernetes/issues/85826

### Additional context for request
The Scheduler Framework is designed to engage end-users to easily build custom scheduling plugins to fit their particular requirements. We do have some basic examples and documents guiding users on how to use the new framework, however, for some complex and common requirements (e.g. batch), we'd like to create this SIG subrepo to store qualified plugins code, so that the plugins can be developed iteratively in an open-source way, and hence benefit more users.

The eventual goal is to enable Scheduler Framework to fit more kinds of workloads, so that Kubernetes itself can be more widely adopted as well.

/cc @ahg-g

**Comment by nikhita** [comment]
/assign @ahg-g 
for approval

**Comment by nikhita** [comment]
Thanks @ahg-g!

/assign

**Comment by nikhita** [comment]
Repo has been created: https://github.com/kubernetes-sigs/scheduler-plugins :tada: 

Also created:

- https://github.com/kubernetes/org/pull/1566 - to add GitHub teams to grant access to the repo
- https://github.com/kubernetes/community/pull/4417 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by nikhita** [comment]
Both PRs have merged and teams have been granted access.

/close

**Comment by Huang-Wei** [comment]
Thanks @nikhita  @ahg-g !!
