### ISSUE TITLE
REQUEST: New membership for iheanyi1

### ISSUE THREAD

**Issue by iheanyi1** [kubernetes/org#1565]
### GitHub Username
@iheanyi1

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
-  @lachie83

### List of contributions to the Kubernetes project
I am one of the docs shadows for 1.18 release.
The membership request is to help me with the 1.18 docs release work.

**Comment by nikhita** [comment]
/assign @justaugustus @lachie83 
for approval

**Comment by VineethReddy02** [comment]
Hi @lachie83 @justaugustus 
Waiting for your approval on this.

Thanks in advance!

**Comment by justaugustus** [comment]
Sorry for missing this!
+1 and welcome to the Release Team, @iheanyi1! :)

**Comment by mrbobbytables** [comment]
+1 thanks for being a part of the release team :)

**Comment by mrbobbytables** [comment]
@iheanyi1  welcome to the release team \o/

I've created PR #1613  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
