### ISSUE TITLE
REQUEST: New membership for bzub

### ISSUE THREAD

**Issue by bzub** [kubernetes/org#1567]
### GitHub Username
@bzub

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pwittrock 
- @andrewsykim 

### List of contributions to the Kubernetes project
- [kustomize PRs authored](https://github.com/kubernetes-sigs/kustomize/pulls?q=is%3Apr+is%3Aclosed+author%3Abzub)
- kustomize PRs review examples:
  - https://github.com/kubernetes-sigs/kustomize/pull/2100#discussion_r366564302
  - https://github.com/kubernetes-sigs/kustomize/pull/2107#issuecomment-574832645
- [kustomize Issues authored](https://github.com/kubernetes-sigs/kustomize/issues?q=is%3Aissue+author%3Abzub+is%3Aclosed)

I look forward to many more contributions! Thanks.

**Comment by pwittrock** [comment]
+1

**Comment by andrewsykim** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @bzub, thank you for all your contributions so far :)

I've created PR #1570 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
