### ISSUE TITLE
REQUEST: New membership for barney-s

### ISSUE THREAD

**Issue by barney-s** [kubernetes/org#1568]
### GitHub Username
@barney-s 

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
Approved in K8s org already: https://github.com/kubernetes/org/issues/1410

**Comment by nikhita** [comment]
I've created PR #1590  to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification. :)

Welcome to @kubernetes-sigs! 🎉

/assign
