### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for tizhou86

### ISSUE THREAD

**Issue by tizhou86** [kubernetes/org#157]
### GitHub Username
@tizhou86 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I am member of Kubernetes main organization

### SIG projects I am involved with
- kube-batch & cluster-api & cluster-api-provider

/area github-membership

**Comment by justaugustus** [comment]
(approving this as you're already part of the kubernetes org)

Thanks so much for your contributions thus far!
I've created #166 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome (in advance)! :)
