### ISSUE TITLE
REQUEST: New membership for <wawa0210>

### ISSUE THREAD

**Issue by wawa0210** [kubernetes/org#1574]
### GitHub Username
@wawa0210

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @benmoss 
- @feiskyer

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/84156
https://github.com/kubernetes/kubernetes/pull/82959
https://github.com/kubernetes/kubernetes/pull/82975
https://github.com/kubernetes/kubernetes/pull/83358
https://github.com/kubernetes/kubernetes/pull/83362
https://github.com/kubernetes/kubernetes/pull/83363
https://github.com/kubernetes/kubernetes/pull/83364
https://github.com/kubernetes/kubernetes/pull/85739
https://github.com/kubernetes/website/pull/18273
https://github.com/kubernetes/ingress-nginx/pull/4645
- Cherry-pick authored
https://github.com/kubernetes/kubernetes/pull/87022
https://github.com/kubernetes/kubernetes/pull/87020
https://github.com/kubernetes/kubernetes/pull/83198
https://github.com/kubernetes/kubernetes/pull/83199
https://github.com/kubernetes/kubernetes/pull/84317
https://github.com/kubernetes/kubernetes/pull/84318
https://github.com/kubernetes/kubernetes/pull/84319
- Issues authored
https://github.com/kubernetes/kubernetes/issues/79515
https://github.com/kubernetes/kubernetes/issues/85379
https://github.com/kubernetes/kubernetes/issues/87112
https://github.com/kubernetes/kubernetes/issues/82522

- SIG projects I am involved with

/sig windows

**Comment by dims** [comment]
+1 from me. welcome @wawa0210 !

**Comment by benmoss** [comment]
Unfortunately me and @dims now work at the same company, so we'll need to find another sponsor!

**Comment by feiskyer** [comment]
+1 for @wawa0210's contribution to SIG Windows
