### ISSUE TITLE
REQUEST: New membership for @samudralavamshi54

### ISSUE THREAD

**Issue by samudralavamshi54** [kubernetes/org#1575]
### GitHub Username

@samudralavamshi54

### Organization you are requesting membership in
e.g. (at)kubernetes
@kubernetes 
@k8s-ci-robot 
@kubernetes-sig

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markyjackson-taulia
- @castrojo

### List of contributions to the Kubernetes project
- PRs reviewed / authored 
2 Issues opened and 1 closed and 1 in progress

https://github.com/kubernetes/website/issues/18197
https://github.com/kubernetes/kubernetes/issues/86390

- Issues responded to
- SIG projects I am involved with 
sig-contribex ( hosting community meetings and shadow for biweekly-meetings)
contribex subproject - mentoring 
sig-release
release-ci-signal
wg-Data protection

**Comment by markyjackson-taulia** [comment]
+1 from me!

**Comment by castrojo** [comment]
+1 from me as well!

**Comment by nzoueidi** [comment]
Hey @samudralavamshi54, unfortunately, @markyjackson-taulia can only sponsor your org membership for @kubernetes-sigs and not for @kubernetes. Do you want to go with that and add you only to @kubernetes-sigs org or you can add another eligible sponsor.
More information about the requirements for the community membership: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by markyjackson-taulia** [comment]
@parispittman might be able to help me and/or @samudralavamshi54

**Comment by parispittman** [comment]
It would be cool to see a PR or two :)

**Comment by samudralavamshi54** [comment]
@nzoueidi  please add to Kubernetes-sig will
Open another request form later for Kubernetes

**Comment by nikhita** [comment]
@samudralavamshi54 thank you for all your contributions so far :)

I've created PR #1590  to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
