### ISSUE TITLE
REQUEST: New membership for JamesLaverack

### ISSUE THREAD

**Issue by JamesLaverack** [kubernetes/org#1576]
### GitHub Username
@JamesLaverack

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @evillgenius75 
- @lachie83 

### List of contributions to the Kubernetes project
- [1.18 Release Team - Release Notes Shadow](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.18/release_team.md)

**Comment by evillgenius75** [comment]
+1 from me

**Comment by lachie83** [comment]
+1

**Comment by nikhita** [comment]
@JamesLaverack thank you for all your contributions so far :)

I've created PR #1590  to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
