### ISSUE TITLE
REQUEST: New membership for timyinshi

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/org#1579]
GitHub Username
@timyinshi

Organization you are requesting membership in
@kubernetes

Requirements
I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
I have enabled 2FA on my GitHub account (https://github.com/settings/security)
I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
I am actively contributing to 1 or more Kubernetes subprojects
I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors
@dankohn
@tanjunchen
@chenrui333

List of contributions to the Kubernetes project
PRs reviewed / authored
kubernetes-csi/docs#250
kubernetes/enhancements#1385
kubernetes/kubernetes#85170
kubernetes/kubernetes#85129
kubernetes/kubernetes#85626
kubernetes/enhancements#1374
kubernetes/enhancements#1378
kubernetes/enhancements#1386
kubernetes/enhancements#1414
kubernetes/enhancements#1427
kubernetes/enhancements#1428

Issues responded to
kubernetes/kubernetes#78576
kubernetes/kubernetes#78847
kubernetes/kubernetes#78897
kubernetes/kubernetes#78930
kubernetes/kubernetes#79271
kubernetes/kubernetes#77728
kubernetes/kubernetes#79691
kubernetes/kubernetes#79788
kubernetes/kubernetes#85261

**Comment by dankohn** [comment]
I'm happy to endorse @timyinshi's membership

**Comment by tanjunchen** [comment]
+1 thanks for your job in kk

**Comment by nikhita** [comment]
@timyinshi Unfortunately, @dankohn can't act as a sponsor because sponsors need to be in an OWNERS file in the @kubernetes org. If you could add another sponsor who is either a reviewer or approver for any repo in the @kubernetes org, that would be great!

**Comment by dankohn** [comment]
Thanks, sorry for my oversight

**Comment by chenrui333** [comment]
I am happy to sponsor @timyinshi! Hope to see more contributions from you!

**Comment by idealhack** [comment]
@timyinshi thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/1608 to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
