### ISSUE TITLE
REQUEST: New membership for @alvaroaleman

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/org#158]
### GitHub Username
@alvaroaleman

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nikhita
- @roberthbailey

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/64
  * https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/65
  * https://github.com/kubernetes-sigs/controller-runtime/pull/169
  * https://github.com/kubernetes-sigs/cluster-api/pull/499
  * https://github.com/kubernetes-sigs/cluster-api/pull/504
  * https://github.com/kubernetes-sigs/cluster-api/pull/523
  * https://github.com/kubernetes-sigs/cluster-api/pull/524
  * https://github.com/kubernetes/ingress-nginx/pull/2203
  * https://github.com/kubernetes/ingress-nginx/pull/2243
  * https://github.com/kubernetes/ingress-nginx/pull/2283
  * https://github.com/kubernetes/community/pull/2653
  * https://github.com/kubernetes/website/pull/7808
  * https://github.com/kubernetes/kubernetes/pull/65152

- Issues created/responded to
  * https://github.com/kubernetes/kubernetes/issues/69497
  * https://github.com/kubernetes/kubernetes/issues/69489
  * https://github.com/kubernetes/kubernetes/issues/69346
  * https://github.com/kubernetes/kubernetes/issues/65471
  * https://github.com/kubernetes/kubernetes/issues/65145
  * https://github.com/kubernetes/kubernetes/issues/64668
  * https://github.com/kubernetes/kubernetes/issues/64291
  * https://github.com/kubernetes/kubernetes/issues/62295
  * https://github.com/kubernetes/kubernetes/issues/62223
  * https://github.com/kubernetes/kubernetes/issues/61239
  * https://github.com/kubernetes/kubernetes/issues/55337
  * https://github.com/kubernetes/kubeadm/issues/1038
  * https://github.com/kubernetes-sigs/cluster-api/issues/501

- SIG projects I am involved with
  * sig-cluster-lifecycle
    * cluster-api

/area github-membership

**Comment by nikhita** [comment]
+100

@alvaroaleman is not only active on the cluster-api github repo, but also on slack and in meetings!

**Comment by roberthbailey** [comment]
+1

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #161 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome (in advance)! :)
/assign

**Comment by alvaroaleman** [comment]
thank you @justaugustus !
