### ISSUE TITLE
REQUEST: New membership for gaorong

### ISSUE THREAD

**Issue by gaorong** [kubernetes/org#1580]
### GitHub Username
@gaorong

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @k82cn 
- @feiskyer 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=+is%3Apr+author%3Agaorong+

- Issues responded to
https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=+is%3Aissue+author%3Agaorong+

- SIG projects I am involved with
sig-node
sig-scheduling

**Comment by k82cn** [comment]
+1 to me according to [merged PR](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=+is%3Apr+is%3Amerged+author%3Agaorong+), and thanks very much for your contribution :)

**Comment by nikhita** [comment]
@gaorong thank you for all your contributions so far :)

I've created PR #1590  to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
