### ISSUE TITLE
REQUEST: New membership for haosdent

### ISSUE THREAD

**Issue by haosdent** [kubernetes/org#1581]
### GitHub Username

@haosdent

### Organization you are requesting membership in

@kubernetes

### Requirements

- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Huang-Wei 
- @ahg-g 

### List of contributions to the Kubernetes project

- PRs authored
	* https://github.com/kubernetes/kubernetes/pull/78820
	* https://github.com/kubernetes/kubernetes/pull/86040
	* https://github.com/kubernetes/kubernetes/pull/86059
	* https://github.com/kubernetes/kubernetes/pull/86061
	* https://github.com/kubernetes/kubernetes/pull/86062
	* https://github.com/kubernetes/kubernetes/pull/86109
	* https://github.com/kubernetes/kubernetes/pull/86110
	* https://github.com/kubernetes/kubernetes/pull/86113
	* https://github.com/kubernetes/kubernetes/pull/86119
	* https://github.com/kubernetes/kubernetes/pull/86283
	* https://github.com/kubernetes/kubernetes/pull/86742
	* https://github.com/kubernetes/kubernetes/pull/86764
	* https://github.com/kubernetes/kubernetes/pull/86836
	* https://github.com/kubernetes/kubernetes/pull/86847
	* https://github.com/kubernetes/kubernetes/pull/86848
	* https://github.com/kubernetes/kubernetes/pull/86849
	* https://github.com/kubernetes/kubernetes/pull/86850
	* https://github.com/kubernetes/kubernetes/pull/86852
	* https://github.com/kubernetes/kubernetes/pull/87406
	* https://github.com/kubernetes/kubernetes/pull/87407

- PRs reviewed
	* https://github.com/kubernetes/kubernetes/pull/84416
	* https://github.com/kubernetes/kubernetes/pull/84951
	* https://github.com/kubernetes/kubernetes/pull/86634
	* https://github.com/kubernetes/kubernetes/pull/86905
	* https://github.com/kubernetes/kubernetes/pull/87073
	* https://github.com/kubernetes/kubernetes/pull/87091
	* https://github.com/kubernetes/kubernetes/pull/87101
	* https://github.com/kubernetes/kubernetes/pull/87102
	* https://github.com/kubernetes/kubernetes/pull/87103
	* https://github.com/kubernetes/kubernetes/pull/87342
	* https://github.com/kubernetes/kubernetes/pull/87401

- Issues responded to
	* https://github.com/kubernetes/kubernetes/issues/2377
	* https://github.com/kubernetes/kubernetes/issues/44328
	* https://github.com/kubernetes/kubernetes/issues/69553
	* https://github.com/kubernetes/kubernetes/issues/83044
	* https://github.com/kubernetes/kubernetes/issues/85992
	* https://github.com/kubernetes/kubernetes/issues/86106
	* https://github.com/kubernetes/kubernetes/issues/86174
	* https://github.com/kubernetes/kubernetes/issues/86194

- SIG projects I am involved with
	* sig/scheduling
	* sig/testing

**Comment by ahg-g** [comment]
I support this membership request. Thanks @haosdent for your contributions so far.

**Comment by Huang-Wei** [comment]
+1

Looking forward to seeing more contributions!

**Comment by nikhita** [comment]
@haosdent thank you for all your contributions so far :)

I've created PR #1590  to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
