### ISSUE TITLE
Rename k-sigs/addon-operators to k-sigs/cluster-addons

### ISSUE THREAD

**Issue by dholbach** [kubernetes/org#1583]
### New Repo, Staging Repo, or migrate existing
Rename k-sigs/addon-operators to k-sigs/cluster-addons

### Requested name for new repository
k-sigs/cluster-addons

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
No changes.

### If not a staging repo, who should have write access
No changes.

### If not a staging repo, who should be listed as approvers in OWNERS
No changes.

### If not a staging repo, who should be listed in SECURITY_CONTACTS
No changes.

### What should the repo description be
No changes.

### What SIG and subproject does this fall under in sigs.yaml
No changes.

### Approvals
This was discussed in our subproject meeting earlier today: https://docs.google.com/document/d/10_tl_SXcFGb-2109QpcFVrdrfnVEuQ05MBrXtasB0vk/edit#heading=h.rsxbgpek84py

The rationale for renaming this repository is:
- consistency with sub-project name, Slack channel, etc.
- broader scope than just addon operators (addon installer, addon discovery, etc.)

ccing @justinsb 

### Next steps

If there's no objections and no major other changes required, I'd make sure to inform the next SIG Cluster Lifecycle meeting about this and clean up all relevant docs, etc.

**Comment by nikhita** [comment]
> If there's no objections and no major other changes required, I'd make sure to inform the next SIG Cluster Lifecycle meeting about this and clean up all relevant docs, etc.

@dholbach IIUC this is yet to be discussed in the SCL meeting? Could you ping back here once it has been approved there? We can move ahead with the rename after that. :)

**Comment by dholbach** [comment]
OK. I wasn't sure what the process was. In Cluster Addons we already decided this, but sure I can get a :+1: from SCL on Jan 28th too. Thanks @nikhita .

**Comment by nikhita** [comment]
@dholbach either that or if the leads could comment here approving this issue. :)

**Comment by dholbach** [comment]
Following the discussion with @neolit123 [on Slack](https://kubernetes.slack.com/archives/C13J86Z63/p1579854048003200), can you please :+1: the request here, @justinsb?

/assign @justinsb

**Comment by dholbach** [comment]
I'll update links where necessary afterwards and inform the mailing list too.

**Comment by timothysc** [comment]
+1 from 
/lgtm 
/hold 
^ for timeout.

**Comment by timothysc** [comment]
/hold cancel  
derp this is an issue..

**Comment by nikhita** [comment]
Repo has been renamed: https://github.com/kubernetes-sigs/cluster-addons :+1: 

Also created:
- https://github.com/kubernetes/org/pull/1603 - to update GitHub team names
- https://github.com/kubernetes/community/pull/4460 - to update sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by dholbach** [comment]
Thanks a lot @nikhita ! :-D

**Comment by nikhita** [comment]
Both PRs have merged

/close
