### ISSUE TITLE
Add @apelisse as admin of kubernetes/kube-openapi

### ISSUE THREAD

**Issue by apelisse** [kubernetes/org#1584]
### Organization or repository
kubernetes/kube-openapi

### Users affected
@apelisse

### Describe the issue
I want to be an admin on this repo so that I can push new branches.

**Comment by jennybuckley** [comment]
+1

**Comment by lavalamp** [comment]
Or myself or @deads2k or all three. Is there a place to list e.g. api-machinery "maintainers" so we don't have to worry about this for every single thing we own?

**Comment by spiffxp** [comment]
Manually added kubernetes/kube-openapi-admins and kubernetes/kube-openapi-maintainers to the repo once #1585 merged. I added @apelisse to the team since they opened the issue, please PR yourselves in if you'd like to be added.
