### ISSUE TITLE
REQUEST: New membership for noamran

### ISSUE THREAD

**Issue by noamran** [kubernetes/org#1587]
### GitHub Username
@noamran

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @vincepri 
- @CecileRobertMichon 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api/pull/2114
https://github.com/kubernetes-sigs/cluster-api/pull/2084
https://github.com/kubernetes-sigs/cluster-api/pull/2035
https://github.com/kubernetes-sigs/cluster-api/pull/1822
https://github.com/kubernetes-sigs/cluster-api/pull/1800
https://github.com/kubernetes-sigs/cluster-api/pull/1786
https://github.com/kubernetes-sigs/cluster-api/pull/1776
https://github.com/kubernetes-sigs/cluster-api/pull/1683
https://github.com/kubernetes-sigs/cluster-api/pull/1633
https://github.com/kubernetes-sigs/cluster-api/pull/1615
https://github.com/kubernetes-sigs/cluster-api/pull/1593
https://github.com/kubernetes-sigs/cluster-api/pull/1523
https://github.com/kubernetes-sigs/cluster-api/pull/1492
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/366
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/365
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/297
https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/289
https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/280
https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/273
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/262
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/211
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1367
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1352
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1329
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1294
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1178
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/612
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/254

- Issues responded to
https://github.com/kubernetes-sigs/cluster-api/issues/1561
https://github.com/kubernetes-sigs/cluster-api/issues/1960
https://github.com/kubernetes-sigs/cluster-api/issues/1823
https://github.com/kubernetes-sigs/cluster-api/issues/1783
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/256
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1350
https://github.com/kubernetes-sigs/cluster-api/issues/1681
https://github.com/kubernetes-sigs/cluster-api/issues/1670
https://github.com/kubernetes-sigs/cluster-api/issues/1606
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1204

- SIG projects I am involved with
https://github.com/kubernetes-sigs/cluster-api
https://github.com/kubernetes-sigs/cluster-api-provider-aws
https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm

**Comment by vincepri** [comment]
+💯 Noa has been doing awesome things in the community!

**Comment by CecileRobertMichon** [comment]
🎉 Thank you for all your contributions so far @noamran! +1

**Comment by ncdc** [comment]
Big +1 here!

**Comment by nikhita** [comment]
@noamran thank you for all your contributions so far :)

I've created PR #1590  to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
