### ISSUE TITLE
REQUEST: New membership for qvicksilver

### ISSUE THREAD

**Issue by qvicksilver** [kubernetes/org#1595]
### GitHub Username
qvicksilver

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@Miouge1 
@holmsten

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pulls?q=is%3Apr+author%3Aqvicksilver+is%3Aclosed
- Issues responded to
https://github.com/kubernetes-sigs/kubespray/issues?q=author%3Aqvicksilver
- SIG projects I am involved with
kubespray

**Comment by Miouge1** [comment]
+1 @qvicksilver has been driving the control plane recovery work in Kubespray

**Comment by holmsten** [comment]
+1
Thanks for your contributions. :)

**Comment by idealhack** [comment]
@qvicksilver thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/1608 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
