### ISSUE TITLE
REQUEST: New membership for johnharris85

### ISSUE THREAD

**Issue by johnharris85** [kubernetes/org#1596]
### GitHub Username
@johnharris85

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ncdc 
- @rudoi

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3Ajohnharris85
https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+author%3Ajohnharris85
- Issues responded to
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues?q=author%3Ajohnharris85
https://github.com/kubernetes-sigs/cluster-api/issues?q=author%3Ajohnharris85
- SIG projects I am involved with
cluster-api
cluster-api-provider-aws

/area github-membership

**Comment by ncdc** [comment]
👍 🎉

**Comment by rudoi** [comment]
:+1: :100:

Welcome!

**Comment by idealhack** [comment]
@johnharris85 thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/1608 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
