### ISSUE TITLE
REQUEST: New membership for seanmalloy

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes/org#1604]
### GitHub Username
@seanmalloy

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @damemi
- @ravisantoshgudimetla

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/descheduler/pull/217
https://github.com/kubernetes-sigs/descheduler/pull/210
https://github.com/kubernetes-sigs/descheduler/pull/209
https://github.com/kubernetes-sigs/descheduler/pull/208
https://github.com/kubernetes-sigs/descheduler/pull/183
https://github.com/kubernetes-sigs/descheduler/pull/173
https://github.com/kubernetes-sigs/descheduler/pull/165
https://github.com/kubernetes-sigs/descheduler/pull/160

- Issues responded to
https://github.com/kubernetes-sigs/descheduler/issues/144
https://github.com/kubernetes-sigs/descheduler/pull/158

- SIG projects I am involved with
descheduler

**Comment by damemi** [comment]
+1

**Comment by Huang-Wei** [comment]
+1

**Comment by idealhack** [comment]
@seanmalloy thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/1608 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
