### ISSUE TITLE
REQUEST: New membership for gkarthiks

### ISSUE THREAD

**Issue by gkarthiks** [kubernetes/org#1606]
### GitHub Username
@gkarthiks

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mrbobbytables 
- @parispittman

#### PRs reviewed / authored
- https://github.com/kubernetes/test-infra/pull/16009
- https://github.com/kubernetes/kubernetes/pull/85562
https://github.com/kubernetes/kubernetes/pull/85440
#### Issues responded to
- https://github.com/kubernetes/kubernetes/pull/63707#issuecomment-496054173
- https://github.com/kubernetes/community/issues/4430
- https://github.com/kubernetes/kubectl/issues/809
- https://github.com/kubernetes/kubectl/issues/505
- https://github.com/kubernetes-sigs/metrics-server/issues/36
- https://github.com/kubernetes-sigs/metrics-server/issues/34
#### SIG projects I am involved with
- sig-contributor-experience (https://github.com/kubernetes/community)
   - [marketing team with sig-contributor-experience]

**Comment by mrbobbytables** [comment]
+1 from sponsor :)
Thanks!

**Comment by cblecker** [comment]
@gkarthiks Hello! I appreciate your enthusiasm for Kubernetes, but would you mind changing your GitHub profile picture to not be the Kubernetes logo? This may cause confusion as we use the logo as the profile picture for our orgs itself.

**Comment by gkarthiks** [comment]
hi @cblecker , sure. I changed it now.

**Comment by parispittman** [comment]
+1 from me :) thanks for all of your help so far @gkarthiks  and looking forward to working together more.

**Comment by idealhack** [comment]
@gkarthiks thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/1608 to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
