### ISSUE TITLE
REQUEST: New membership for sophieliu15

### ISSUE THREAD

**Issue by sophieliu15** [kubernetes/org#1609]
### GitHub Username
- @sophieliu15

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @adrianludwin
- @tashimi

### List of contributions to the Kubernetes project
I am part of GKE team in Google Waterloo office and I am working on HNC with @adrianludwin. I will actively contribute to the HNC project.

**Comment by adrianludwin** [comment]
Approved!

**Comment by cblecker** [comment]
Hello! Our [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md) require already having made contributions -- unfortunately working for a specific employer does not qualify someone for membership. We'd love to have you join our community, but only after some contributions have already been made.

If you have any questions or concerns after reviewing our community membership guidelines, please reach out (Slack is a great way to do this).

Thank you!
