### ISSUE TITLE
REQUEST: New membership for LuckySB

### ISSUE THREAD

**Issue by LuckySB** [kubernetes/org#1610]
### GitHub Username
@LuckySB

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Miouge1
- @mattymo
- @woopstar

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pull/5569
https://github.com/kubernetes-sigs/kubespray/pull/5257
https://github.com/kubernetes-sigs/kubespray/pull/5094
https://github.com/kubernetes-sigs/kubespray/pull/4188
https://github.com/kubernetes-sigs/kubespray/pull/4116
https://github.com/kubernetes-sigs/kubespray/pull/4179

- Issues responded to
https://github.com/kubernetes-sigs/kubespray/issues/5052
https://github.com/kubernetes-sigs/kubespray/issues/5576
https://github.com/kubernetes-sigs/kubespray/issues/5562

**Comment by woopstar** [comment]
Happy to be sponsor.

/lgtm

**Comment by Miouge1** [comment]
+1

@LuckySB has been a regular contributor to Kubespray, therefore happy to sponsor.

**Comment by mrbobbytables** [comment]
@LuckySB thanks for all your efforts with the kubespray project 👍 

I've created PR #1613  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
