### ISSUE TITLE
REQUEST: New membership for @julianvmodesto

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/org#1611]
### GitHub Username
@julianvmodesto

### Organization you are requesting membership in
@kubernetes

### Requirements 
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @apelisse 
- @soltysh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/enhancements/pull/1460
  - https://github.com/kubernetes/website/pull/18235
- Issues responded to: 
  - https://github.com/kubernetes/kubernetes/issues/68526
  - https://github.com/kubernetes/kubernetes/issues/68514
  - https://github.com/kubernetes/kubernetes/issues/86525
  - https://github.com/kubernetes/kubernetes/issues/85652
  - https://github.com/kubernetes/kubernetes/issues/86526
- SIG projects I am involved with:
  - wg-apply
  - sig-cli
  - sig-api-machinery

**Comment by apelisse** [comment]
I confirm. Julian is taking care of everything in the promotion of Dry-run and `kubectl diff` to GA and is doing a wonderful job!

**Comment by soltysh** [comment]
I confirm as well, :+1:

**Comment by mrbobbytables** [comment]
Hey there @julianvmodesto, thank you for all your contributions so far :)

I've created PR #1613  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
