### ISSUE TITLE
REQUEST: New membership for boluisa

### ISSUE THREAD

**Issue by boluisa** [kubernetes/org#1612]
### GitHub Username
@boluisa

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @castrojo  
- @parispittman

### List of contributions to the Kubernetes project
- PRs reviewed / authored
[kubernetes/kubernetes#85412](https://github.com/kubernetes/kubernetes/pull/85412)
[kubernetes/community#4459](https://github.com/kubernetes/community/pull/4459)
[kubernetes/website#17332](https://github.com/kubernetes/website/pull/17332)
[kubernetes/website#17922](https://github.com/kubernetes/website/pull/17922)
- Issues responded to
[kubernetes/kubernetes#81370](https://github.com/kubernetes/kubernetes/issues/81370)
[kubernetes/kubeadm#1723](https://github.com/kubernetes/kubeadm/issues/1723)
[kubernetes/kubeadm#2013](https://github.com/kubernetes/kubeadm/issues/2013)
[kubernetes/community#4044](https://github.com/kubernetes/community/issues/4044)
[kubernetes/sig-release#280](https://github.com/kubernetes/sig-release/issues/280)
[kubernetes/kubeadm#1916](https://github.com/kubernetes/kubeadm/issues/1916)
- SIG projects I am involved with
SIG- contributor-experience
SIG- cluster-lifecycle

**Comment by castrojo** [comment]
+1

**Comment by parispittman** [comment]
yay +1!!

**Comment by mrbobbytables** [comment]
Hey there @boluisa , thank you for helping with the marketing team \o/

I've created PR #1613  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
