### ISSUE TITLE
REQUEST: New membership for enxebre

### ISSUE THREAD

**Issue by enxebre** [kubernetes/org#1614]
### GitHub Username
@enxebre

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sttts
- @hardikdr
- @ncdc
- @apelisse
- @DirectXMan12

### List of contributions to the Kubernetes project
- PRs reviewed / authored

https://github.com/kubernetes/kubernetes/pull/54504
https://github.com/kubernetes/kubernetes/pull/81336
https://github.com/kubernetes/gengo/pull/154
https://github.com/kubernetes/kops/pull/3582
https://github.com/kubernetes/kubernetes/pull/46620
https://github.com/kubernetes/kubernetes/pull/83743
https://github.com/kubernetes/enhancements/pull/1341
https://github.com/kubernetes/kubernetes/pull/84113

https://github.com/kubernetes-sigs/cluster-api/pull/2165
https://github.com/kubernetes-sigs/cluster-api/pull/2101
https://github.com/kubernetes-sigs/cluster-api/pull/1684
https://github.com/kubernetes-sigs/cluster-api/pull/809
https://github.com/kubernetes-sigs/cluster-api/pull/824
https://github.com/kubernetes-sigs/cluster-api/pull/728
https://github.com/kubernetes-sigs/cluster-api/pull/683
https://github.com/kubernetes-sigs/cluster-api/pull/658
https://github.com/kubernetes-sigs/cluster-api/pull/657
https://github.com/kubernetes-sigs/cluster-api/pull/651
https://github.com/kubernetes-sigs/cluster-api/pull/650
https://github.com/kubernetes-sigs/cluster-api/pull/646
https://github.com/kubernetes-sigs/cluster-api/pull/645
https://github.com/kubernetes-sigs/cluster-api/pull/643
https://github.com/kubernetes-sigs/cluster-api/pull/606
https://github.com/kubernetes-sigs/cluster-api/pull/596
https://github.com/kubernetes-sigs/cluster-api/pull/565
https://github.com/kubernetes-sigs/cluster-api/pull/546
https://github.com/kubernetes-sigs/cluster-api/pull/488
https://github.com/kubernetes-sigs/cluster-api/pull/457

https://github.com/kubernetes-sigs/controller-runtime/pull/622
https://github.com/kubernetes-sigs/controller-runtime/pull/618
https://github.com/kubernetes-sigs/controller-runtime/pull/588

- Issues responded to

https://github.com/kubernetes/autoscaler/issues/2495
https://github.com/kubernetes/kubernetes/issues/81333

https://github.com/kubernetes-sigs/cluster-api/issues/853
https://github.com/kubernetes-sigs/cluster-api/issues/1524
https://github.com/kubernetes-sigs/cluster-api/issues/721
https://github.com/kubernetes-sigs/cluster-api/issues/490
https://github.com/kubernetes-sigs/cluster-api/issues/59
https://github.com/kubernetes-sigs/cluster-api/issues/11

https://github.com/kubernetes-sigs/controller-runtime/issues/703
https://github.com/kubernetes-sigs/controller-runtime/issues/617
https://github.com/kubernetes-sigs/controller-tools/issues/339

- SIG projects I am involved with
sig-cluster-lifecycle
sig-autoscaling
sig-api-machinery

**Comment by sttts** [comment]
+1

**Comment by hardikdr** [comment]
+1

**Comment by ncdc** [comment]
+1

**Comment by apelisse** [comment]
+1

**Comment by DirectXMan12** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @enxebre , thank you for all your contributions across the project \o/

I've created PR #1628  to add you to both the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them

Welcome to @kubernetes / @kubernetes-sigs  🎉

/assign
