### ISSUE TITLE
REQUEST: New membership for nader-ziada

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes/org#1616]
### GitHub Username
@nader-ziada

### Organization you are requesting membership in
kubernetes

### Requirements
- [ x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @CecileRobertMichon 
- @justaugustus 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/335
- Issus responded to
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/301
- SIG projects I am involved with
   - currently a reviewer in the `https://github.com/kubernetes-sigs/cluster-api-provider-azure` sub project and need to be added to the `kubernetes` org to resolve this issue here: https://github.com/kubernetes/k8s.io/pull/547#issuecomment-578316166

**Comment by justaugustus** [comment]
+1! Nader is a reviewer on capz and will need membership to help manage image promotion for that project in k/k8s.io

**Comment by CecileRobertMichon** [comment]
+1

**Comment by mrbobbytables** [comment]
@nader-ziada , thank you for all your help with capi-azure :)

I've created PR #1628  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
