### ISSUE TITLE
REQUEST: New membership for rficcaglia

### ISSUE THREAD

**Issue by rficcaglia** [kubernetes/org#1618]
### GitHub Username
rficcaglia

### Organization you are requesting membership in
kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hannibalhuang
- @ericavonb

### List of contributions to the Kubernetes project
- Issues: https://github.com/kubernetes/kubernetes/issues/75554 
- SIG projects I am involved with: https://github.com/cncf/sig-security/

**Comment by ericavonb** [comment]
I approve of @rficcaglia's request!

**Comment by hannibalhuang** [comment]
+1 !

**Comment by mrbobbytables** [comment]
@rficcaglia , thank you helping with wg-policy.

I've created PR #1628  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
