### ISSUE TITLE
REQUEST: New membership for @chentao1596

### ISSUE THREAD

**Issue by chentao1596** [kubernetes/org#162]
### GitHub Username
@chentao1596

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xiangpengzhao 
- @zhangxiaoyu-zidif 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/36626
https://github.com/kubernetes/kubernetes/pull/38161
https://github.com/kubernetes/kubernetes/pull/42467
https://github.com/kubernetes/kubernetes/pull/55218
https://github.com/kubernetes/kubernetes/pull/54983
https://github.com/kubernetes/kubernetes/pull/54913
https://github.com/kubernetes/kubernetes/pull/53042
https://github.com/kubernetes/kubernetes/pull/52841
https://github.com/kubernetes/kubernetes/pull/62441
https://github.com/kubernetes/kubernetes/pull/58378
https://github.com/kubernetes/kubernetes-docs-zh/pull/339
https://github.com/kubernetes/kubernetes-docs-zh/pull/338
https://github.com/kubernetes/kubernetes-docs-zh/pull/337
https://github.com/kubernetes/kubernetes-docs-zh/pull/335
https://github.com/kubernetes/kubernetes-docs-zh/pull/336
https://github.com/kubernetes/kubernetes-docs-zh/pull/279
https://github.com/kubernetes/kubernetes-docs-zh/pull/331
https://github.com/kubernetes/kubernetes-docs-zh/pull/332
https://github.com/kubernetes/kubernetes-docs-zh/pull/333
https://github.com/kubernetes/kubernetes-docs-zh/pull/334
https://github.com/kubernetes/ingress-nginx/pull/630
https://github.com/kubernetes/ingress-nginx/pull/1006
https://github.com/kubernetes/ingress-nginx/pull/536
https://github.com/kubernetes/ingress-nginx/pull/320
https://github.com/kubernetes/ingress-nginx/pull/307
https://github.com/kubernetes/ingress-nginx/pull/158
https://github.com/kubernetes/website/pull/6030
https://github.com/kubernetes/community/pull/1890
https://github.com/kubernetes/website/pull/5247
https://github.com/kubernetes/website/pull/5246
https://github.com/kubernetes/dns/pull/16
https://github.com/kubernetes/website/pull/2001
https://github.com/kubernetes/dns/pull/5
https://github.com/kubernetes/website/pull/1962
https://github.com/kubernetes/website/pull/2126
https://github.com/kubernetes/website/pull/2001
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/58868
https://github.com/kubernetes/kubernetes/issues/55216
https://github.com/kubernetes/kubernetes/issues/38946
- SIG projects I am involved with
k/kubernetes-docs-zh
k/kubernetes
k/website
k/ingress

/area github-membership

**Comment by xiangpengzhao** [comment]
+1

**Comment by zhangxiaoyu-zidif** [comment]
+1 from me

**Comment by mrbobbytables** [comment]
Hey there @chentao1596 , thank you so much for all the work you've done so far! :)

I've created PR #167  to add you to the main Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉 

/assign
