### ISSUE TITLE
REQUEST: New membership for kakts

### ISSUE THREAD

**Issue by kakts** [kubernetes/org#1624]
### GitHub Username
@kakts

### Organization you are requesting membership in
@kubernetes
### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nasa9084
- @inductor 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Akakts
https://github.com/kubernetes/website/pull/18234
https://github.com/kubernetes/website/pull/17796
https://github.com/kubernetes/website/pull/17794
https://github.com/kubernetes/website/pull/17586
https://github.com/kubernetes/website/pull/16319
https://github.com/kubernetes/website/pull/14916
https://github.com/kubernetes/website/pull/14849
https://github.com/kubernetes/website/pull/14805
https://github.com/kubernetes/website/pull/14767
https://github.com/kubernetes/website/pull/14735
https://github.com/kubernetes/website/pull/14720
https://github.com/kubernetes/website/pull/14696
https://github.com/kubernetes/website/pull/14673
https://github.com/kubernetes/website/pull/14641
https://github.com/kubernetes/website/pull/14581
https://github.com/kubernetes/website/pull/14576
https://github.com/kubernetes/website/pull/14535
https://github.com/kubernetes/website/pull/14494
https://github.com/kubernetes/website/pull/14403
https://github.com/kubernetes/website/pull/14396
https://github.com/kubernetes/website/pull/14319
https://github.com/kubernetes/website/pull/14161
- Issues responded to
https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Akakts+is%3Aclosed
- SIG projects I am involved with
kubernetes/sig-docs

**Comment by nasa9084** [comment]
+1
Thank you for your contribution for Ja docs~

**Comment by inductor** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @kakts , thank you for all your help with the japanese localization efforts \o/

I've created PR #1652  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by kakts** [comment]
Thank you so much!
