### ISSUE TITLE
Remove stale invites

### ISSUE THREAD

**Issue by cblecker** [kubernetes/org#1627]
There are a number of stale invites on all of our orgs.

These are folks that have either:
- left the org manually, and then we reinvited them
- never accepted their original invite to the org

Either way, we can safely remove these folks as these invites have been outstanding for awhile.

I opened https://github.com/kubernetes/org/pull/1626 to deal with these in @kubernetes, but we should also do the other orgs too.

Basic task:
- Look at the pending invites for an org (e.g. https://github.com/orgs/kubernetes-sigs/people)
- git blame the associated file (`git blame config/kubernetes-sigs/org.yaml | grep username`)
- If the date when they were added to the file is more than 30 days, remove them from the file
- Open 1 PR per org, just to keep things manageable for review

Complete:
- [x] kubernetes
- [ ] kubernetes-sigs
- [ ] kubernetes-incubator
- [ ] kubernetes-client
- [ ] kubernetes-csi

@justaugustus @nzoueidi @idealhack: Any of you three interested in splitting up the above orgs and taking a crack? Shouldn't take more than 20 minutes per org.

**Comment by nzoueidi** [comment]
I will tackle this tonight. 

/assign

**Comment by justaugustus** [comment]
@nzoueidi -- Did you have a chance to look into this?

**Comment by justaugustus** [comment]
@cblecker -- p.s. I don't/can't see pending invitations.
- There might not be any
- NMCs may not have permissions to view them

**Comment by mrbobbytables** [comment]
hm...it might require org admin privs -_- Some of these folk should probably just be pinged to accept the invite. They'll also likely need to be removed from groups in those orgs.

**kubernetes-sigs:**
- @kris-nova
- @bryk
- @hh
- @openstacker
- @oomichi
- @vllry
- @zparnold
- @bradtopol
- @grayluck
- @alisondy
- @lachie83
- @brendandburns
- @dtoledo67

**kubernetes-incubator:**
- **NOTE:** With this being decom'ed soon, I'd just go ahead and remove even if folks are active.
- chenopis
- kbarnard10
- dnardo
- ryanmcginnis

**kubernetes-client:**
- @guoshimin

**kubernetes-csi:**
- @kfox1111
- @PatrickLang

**Comment by kfox1111** [comment]
I hadn't realized I missed clicking on the invite. I think I have fixed that.

**Comment by mrbobbytables** [comment]
Yup, that took care of it 👍

**Comment by nzoueidi** [comment]
Missed that. I will do this tonight - sorry for the delay.

**Comment by hh** [comment]
Done, thanks for the invite/ping.

**Comment by oomichi** [comment]
@mrbobbytables Thanks for your help, I succeeded to join the organization.

**Comment by nzoueidi** [comment]
I see that people started accepting the invites, should we wait a little bit maybe there are other could be notified by the comment of Bob, wdyt?

**Comment by oomichi** [comment]
@nzoueidi Did you see some alert related to the invitation on the page https://github.com/kubernetes-sigs ?
That is what @mrbobbytables gave me advice.

**Comment by alisondy** [comment]
Joined! Thanks for the ping, The invite email eluded me before. 👀

**Comment by lachie83** [comment]
Joined! Thanks for the ping

**Comment by bradtopol** [comment]
I have accepted my invite. Sorry for the delay!

**Comment by cblecker** [comment]
Update on current pending invites:

```shell
$ for org in kubernetes{,-sigs,-client,-csi}; do echo $org; echo '---'; hub api /orgs/${org}/invitations | jq -r '.[] | "@\(.login) - Created: \(.created_at)"'; echo; done
```
kubernetes
---
@rficcaglia - Created: 2020-02-10T21:20:41.000-08:00

kubernetes-sigs
---
@bryk - Created: 2019-01-22T22:31:00.000-08:00
@grayluck - Created: 2019-10-15T23:02:05.000-07:00
@dtoledo67 - Created: 2020-01-11T14:20:44.000-08:00
@brendandburns - Created: 2019-12-05T23:04:40.000-08:00
@openstacker - Created: 2019-07-16T14:10:06.000-07:00
@kris-nova - Created: 2019-01-04T14:41:51.000-08:00

kubernetes-client
---
@guoshimin - Created: 2019-11-04T21:10:36.000-08:00

kubernetes-csi
---
@PatrickLang - Created: 2019-07-31T20:40:14.000-07:00

**Comment by kris-nova** [comment]
Looks like you can just go [here](https://github.com/orgs/kubernetes-sigs/invitation) if you have an open invite and click the join button.

No YAML or `git blame`ing required. 

Maybe I am missing something?

**Comment by PatrickLang** [comment]
I think I accepted the pending invite - I see this on my profile:
```
Joined the Kubernetes CSI organization
on Feb 25
```

If one is missing let me know. I can't find others - they could have got lost in email

**Comment by cblecker** [comment]
@PatrickLang @kris-nova We're good with both of you now :) Thanks!
