### ISSUE TITLE
REQUEST: New membership for @gyuho

### ISSUE THREAD

**Issue by gyuho** [kubernetes/org#163]
### GitHub Username

@gyuho

### Organization you are requesting membership in

@kubernetes
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @d-nishi 
- @jpbetz 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/69322
https://github.com/kubernetes/kubernetes/pull/69263
https://github.com/kubernetes/kubernetes/pull/57480
https://github.com/kubernetes/kubernetes/pull/47470
https://github.com/kubernetes/kubernetes/pull/26502
https://github.com/kubernetes/kubernetes/pull/26019
https://github.com/kubernetes/kubernetes/pull/26018
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/231
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/237
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/641
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/583
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/581
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/566
https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/149

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/67732
https://github.com/kubernetes/kubernetes/issues/63243

- SIG projects I am involved with
https://github.com/kubernetes-sigs/aws-alb-ingress-controller
https://github.com/kubernetes-sigs/cluster-api-provider-aws
https://github.com/kubernetes-sigs/aws-iam-authenticator

/area github-membership

**Comment by d-nishi** [comment]
+1

**Comment by jpbetz** [comment]
+1

**Comment by justaugustus** [comment]
+1 as well!
/assign

**Comment by justaugustus** [comment]
Hey @gyuho! Thanks so much for your contributions! :)
I've created #166 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome (in advance)! :)

**Comment by gyuho** [comment]
Thanks @justaugustus !
