### ISSUE TITLE
REQUEST: New membership for headcr4sh

### ISSUE THREAD

**Issue by headcr4sh** [kubernetes/org#1633]
### GitHub Username
@headcr4sh

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jeefy
- @maciaszczykm

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/dashboard/pull/4905
  - https://github.com/kubernetes/ingress-nginx/pull/5000
  - https://github.com/kubernetes/ingress-nginx/issues/4953
- Issues responded to
  - none, yet
- SIG projects I am involved with
  - kubernetes-dashboard (German translation)

**Comment by jeefy** [comment]
+1

**Comment by maciaszczykm** [comment]
+1

**Comment by justaugustus** [comment]
@headcr4sh -- Thanks so much for your contributions thus far!
I've created https://github.com/kubernetes/org/pull/1639 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
