### ISSUE TITLE
REQUEST: New membership for alijahnas

### ISSUE THREAD

**Issue by alijahnas** [kubernetes/org#1635]
### GitHub Username
@alijahnas

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Miouge1 
- @holmsten

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pull/5184
https://github.com/kubernetes-sigs/kubespray/pull/5491
https://github.com/kubernetes-sigs/kubespray/pull/5492
https://github.com/kubernetes-sigs/kubespray/pull/5078
- Issues responded to
- SIG projects I am involved with
https://github.com/kubernetes-sigs/kubespray

**Comment by holmsten** [comment]
+1

Happy to sponsor.

**Comment by Miouge1** [comment]
+1

@alijahnas has been driving the efforts to integrate the [kubernetes/cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack) in Kubespray, providing a path forward from the legacy/in-tree openstack provider.

**Comment by justaugustus** [comment]
@alijahnas -- Thanks so much for your contributions thus far!
I've created https://github.com/kubernetes/org/pull/1639 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
