### ISSUE TITLE
REQUEST: New membership for jimmidyson

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/org#1637]
### GitHub Username
@jimmidyson 

### Organization you are requesting membership in
kubernetes-sigs (already a member of Kubernetes github org)

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pmorie
- @gerred 

### List of contributions to the Kubernetes project
- Recent PR https://github.com/kubernetes-sigs/kubefed/pull/1184 (this request is to be able to become an owner of kubefed so this is the first of many to come)
- Lots of old-ish PRs to Kubernetes and various ecosystem projects

**Comment by pmorie** [comment]
+1

Is a sponsor necessary if someone is already a member of the main kubernetes org?

**Comment by gerred** [comment]
+1

I think I've even seen this get auto-accepted, so I don't think so, but I'll cast one in anyway. ;)

**Comment by jimmidyson** [comment]
@kubernetes/owners I'd really appreciate it if you could action this request so I can start taking more responsibility for kubernetes-sigs/kubefed. Thank you!

**Comment by mrbobbytables** [comment]
@jimmidyson I've created #1652 to go ahead and add you to the kubernetes-sigs org.
Just an FYI for the future -- As a member of kubernetes, you do not need sponsorship to join the other "child orgs". Please feel free to PR yourself in if its urgent 👍We generally batch memberships changes every 2-3 days.

/assign

**Comment by jimmidyson** [comment]
@mrbobbytables Thank you! I didn't know the process for this at all so thank you for your help!
