### ISSUE TITLE
Enable FOSSA license scanning across all Kubernetes orgs

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#164]
### Organization or repository
All k8s orgs

### Name of integration
FOSSA

### Link to integration website
- https://fossa.io/
- https://github.com/fossas/fossa-docs/blob/master/src/md/getting-started/repository-permissions.md

### Describe what is attempting to be accomplished
As a project, we'd like to be able to scan software licenses with some framework and it seems the general consensus has been to use FOSSA.
There are multiple tracking issues and threads to catch up on, so I'll point there instead:
- Open `k/steering` issue: https://github.com/kubernetes/steering/issues/57
- Umbrella `k/sig-release` tracking: https://github.com/kubernetes/sig-release/issues/223
- Older `k/steering` issue: https://github.com/kubernetes/steering/issues/21

### Additional context for request
N/A

/area github-integration
/assign
/cc @kubernetes/owners @nikhita @dims @swinslow

**Comment by dims** [comment]
@justaugustus can you please point us to the page that describes the permissions needed by this app?

**Comment by justaugustus** [comment]
@dims -- here you go: https://github.com/fossas/fossa-docs/blob/master/src/md/getting-started/repository-permissions.md

added to the issue description as well.

**Comment by spiffxp** [comment]
I see this already happens to be enabled for google and GoogleCloudPlatform, so I figure if it's good enough for them...

But seriously, discussed in private with the rest of @kubernetes/owners, it's been enabled for kubernetes-sigs for a bit and nothing has caught on fire, so we're ok with this

**Comment by fejta** [comment]
This is fine as a first step. +1

At what kind of cadence does this provide results? Ideally we find a solution that allows us to prevent merges of bad licenses, in addition to flagging problems after the fact.

**Comment by spiffxp** [comment]
I clicked the 'grant' button for the kubernetes orgs I manage.  Explicitly not touching kubernetes-security.

![screen shot 2018-10-12 at 3 00 14 pm](https://user-images.githubusercontent.com/49258/46895961-985fcc80-ce2f-11e8-9c76-8aa73741e656.png)

**Comment by idvoretskyi** [comment]
@justaugustus +1. Thanks for doing this!

**Comment by cblecker** [comment]
+1 in support of this.

**Comment by spiffxp** [comment]
/close
I leave it to @justaugustus to continue setting this up, please ping here / reopen if permissions still aren't correct for you to do what you need

**Comment by justaugustus** [comment]
Yayyyyy! I'll be kicking off documentation around the Licensing / Compliance subproject next week. It was mentioned [here](https://groups.google.com/d/msg/kubernetes-sig-release/6oljCwkD6HQ/sH8W-uwwAAAJ) originally, but I've actually got bandwidth to do stuff now.

Thanks @spiffxp! :)
