### ISSUE TITLE
REQUEST: New membership for gujing

### ISSUE THREAD

**Issue by gujingit** [kubernetes/org#1642]
### GitHub Username
@[gujingit](https://github.com/gujingit)

### Organization you are requesting membership in
@[kubernetes](https://github.com/kubernetes)

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andrewsykim 
- @[aoxn](https://github.com/aoxn)
- @xlgao-zju 

### List of contributions to the Kubernetes project
- PRs authored
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/fb2750455ee7988b0dcd033a89d8d0e689c6194a
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/13fb1303c5ed607c17f16b5866d7f73a7a7add2d
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/2a36ca1f1195de3f542a4a45b462ec7b054ddb85
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/6cddde442377bf05483ed699bd2dcaa87fb3d794
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/c1c2e554c7c5d48e45b6d9703d97ca8d851c7936
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/6bd487eb147e7c8c154c01d5407b0a93dc63d071
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/dbf8e83119f8bff538897ea31101cb23452f9004
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/bf0e5fe60c5e213f8993b8840571d51bda435861
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/63dc05949e55b0dba75738d1abdc3010d3137f8a
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/2df82097cfb6df5d0a71ff880a36fce1c38f9f6c
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/1fb871168aa1ea73c7adc23d107680564553a861
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/fb47fac650c628027e850f72115fc1ae81ad7379
https://github.com/kubernetes/cloud-provider-alibaba-cloud/commit/c2cee553d33ef9082fde9418a37e2473784d1f18

**Comment by andrewsykim** [comment]
+1

**Comment by aoxn** [comment]
+1

**Comment by cheyang** [comment]
+1

**Comment by cheyang** [comment]
+1

**Comment by xlgao-zju** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @gujingit, thank you for all your contributions so far :)

I've created PR #1652  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
