### ISSUE TITLE
Migrate k8smeetup/website-tasks to kubernetes-sigs

### ISSUE THREAD

**Issue by idealhack** [kubernetes/org#1643]
### New Repo, Staging Repo, or migrate existing

https://github.com/k8smeetup/website-tasks

### Requested name for new repository

website-zh-tasks

### Which Organization should it reside

kubernetes-sigs

### If not a staging repo, who should have admin access

[`sig-docs-zh-owners` in kubernetes/website](https://github.com/kubernetes/website/blob/470f932dd8649592152b0388c653d114e81ee74d/OWNERS_ALIASES#L166-L179)

### If not a staging repo, who should have write access

[`sig-docs-zh-reviews` in kubernetes/website](https://github.com/kubernetes/website/blob/470f932dd8649592152b0388c653d114e81ee74d/OWNERS_ALIASES#L180-L189)

### If not a staging repo, who should be listed as approvers in OWNERS

[`sig-docs-zh-owners` in kubernetes/website](https://github.com/kubernetes/website/blob/470f932dd8649592152b0388c653d114e81ee74d/OWNERS_ALIASES#L166-L179)

### If not a staging repo, who should be listed in SECURITY_CONTACTS

https://github.com/kubernetes/website/blob/master/SECURITY_CONTACTS

### What should the repo description be

translation tasks for k8s docs Chinese localization

### What SIG and subproject does this fall under in sigs.yaml

this is part of the website subproject for sig-docs

### Approvals

this was approved by some owners in the Chinese localization team, but not by SIG docs chairs yet. we'll ask for approval as this issue opened.

### Additional context for request

mostly we are using the repo issues for task management: https://github.com/k8smeetup/website-tasks/issues

this repo was created in k-sigs but not used, and then got removed last year: https://github.com/kubernetes/org/issues/753 after that, we had the conversation to move the repo to an official org: https://twitter.com/idealhack/status/1122241859319762949

later on, we felt it's better to finish this migration so we can better organize the community effort.

/cc @chenrui333 @markthink @fleeto @zacharysarah 
/cc @kubernetes/sig-docs-zh-owners

**Comment by zacharysarah** [comment]
@idealhack 👋 

To surface our [Slack conversation](https://kubernetes.slack.com/archives/CE3LNFYJ1/p1582115611002500) for visibility: why is a repo required? Can the same goal be accomplished with a project in k/website?

**Comment by idealhack** [comment]
@zacharysarah Thank you! I think there were a few reasons behind a separated repo:

- the tool might open and close a large number of issues
- the current repo has another set of labels
- the tool will require additional permissions to manage the issues

But if it's OK to create the issues in k/website, then it's fine to change the tool a bit to adapt that.

**Comment by idealhack** [comment]
So we are going to try to use the k/website for task management, closing this for now :)

**Comment by justaugustus** [comment]
FWIW, if the repo was to be migrated, it would contributors who had write access to both to migrate issues into k/website.

There are a lot of issues there and it might be worthwhile.

**Comment by justaugustus** [comment]
(all existing labels would get dropped in the process though)
