### ISSUE TITLE
REQUEST: New membership for nan-yu

### ISSUE THREAD

**Issue by nan-yu** [kubernetes/org#1646]
### GitHub Username
@nan-yu

### Organization you are requesting membership in
@kubernetes @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mortent 
- @kow3ns 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/86097
https://github.com/kubernetes/kubernetes/pull/85863
https://github.com/kubernetes/kubernetes/pull/85819
https://github.com/kubernetes-sigs/application/pull/134
https://github.com/kubernetes-sigs/application/pull/135
https://github.com/kubernetes-sigs/application/pull/138
https://github.com/kubernetes-sigs/application/pull/139
https://github.com/kubernetes-sigs/application/pull/142
https://github.com/kubernetes-sigs/application/pull/144
https://github.com/kubernetes-sigs/application/pull/145
https://github.com/kubernetes-sigs/application/pull/149
https://github.com/kubernetes-sigs/application/pull/151
https://github.com/kubernetes-sigs/application/pull/153
https://github.com/kubernetes-sigs/application/pull/155
https://github.com/kubernetes-sigs/application/pull/156
https://github.com/kubernetes-sigs/application/pull/168

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/85974
https://github.com/kubernetes-sigs/application/issues/148
https://github.com/kubernetes-sigs/application/issues/147
https://github.com/kubernetes-sigs/application/issues/141

- SIG projects I am involved with
https://github.com/kubernetes-sigs/application

**Comment by mortent** [comment]
+1

**Comment by kow3ns** [comment]
+1

**Comment by ant31** [comment]
+1

**Comment by mrbobbytables** [comment]
@nan-yu  , thank you for all your help with the app crd :)

I've created PR #1652  to add you to both the Kubernetes and Kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
