### ISSUE TITLE
REQUEST: New membership for @eddycharly

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/org#1649]
### GitHub Username
@eddycharly

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @alvaroaleman 
- @cjwagner 

### List of contributions to the Kubernetes project
https://github.com/kubernetes/test-infra/pull/16323
https://github.com/kubernetes/test-infra/pull/16320
https://github.com/kubernetes/test-infra/pull/16185
https://github.com/kubernetes/test-infra/pull/16099
https://github.com/kubernetes/test-infra/pull/16068
https://github.com/kubernetes/test-infra/pull/15667
https://github.com/kubernetes/test-infra/pull/15565
https://github.com/kubernetes/test-infra/pull/15295
https://github.com/kubernetes/test-infra/pull/15283
https://github.com/kubernetes/test-infra/pull/15072
https://github.com/kubernetes/test-infra/pull/15022

**Comment by alvaroaleman** [comment]
+1

**Comment by cjwagner** [comment]
+1

**Comment by mrbobbytables** [comment]
@eddycharly  thank you for all your help with test-infra \o/

I've created PR #1652  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
