### ISSUE TITLE
REQUEST: New membership for ChiefAlexander

### ISSUE THREAD

**Issue by ChiefAlexander** [kubernetes/org#1654]
### GitHub Username
@ChiefAlexander

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @aledbf 
- @scottrigby 

### List of contributions to the Kubernetes project
My contributions are to the nginx-ingress helm chart which I have been an owner of since May 2019. The helm chart is moving into the ingress-nginx repo which I would like to continue to own.
- https://github.com/helm/charts/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AChiefAlexander+is%3Aclosed+nginx-ingress

**Comment by aledbf** [comment]
+1

**Comment by scottrigby** [comment]
+1

**Comment by nzoueidi** [comment]
@scottrigby I don't think that you could sponsor this org membership while you are not an approver/reviewer in the kubernetes org. Helm is a separate organization. 

More information here: https://github.com/kubernetes/community/blob/master/community-membership.md#member

@ChiefAlexander I would rather think for applying for membership in the Helm org as it make more sense while most of your contributions are there.

**Comment by aledbf** [comment]
@nzoueidi on May 13th, 2020, in less than three months, the stable and incubator repositories will be de-listed from the Helm Hub. @ChiefAlexander is already a member of the helm org and current maintainer and reviewer of the `nginx-ingress` chart.
His membership in the k8s org is required to continue the contribution in the  https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx repository.

**Comment by mrbobbytables** [comment]
@aledbf We still need another sponsor per the[ membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

Would another owner from the [ingress-nginx](https://github.com/kubernetes/ingress-nginx) subproject be able to sponsor?

**Comment by aledbf** [comment]
@mrbobbytables not sure. None of the [OWNERS_ALIASES](https://github.com/kubernetes/ingress-nginx/blob/master/OWNERS_ALIASES) are involved in the project.

ping @bowei

**Comment by bowei** [comment]
+1

**Comment by nzoueidi** [comment]
Thank you @ChiefAlexander for all your contributions so far :)

I've created PR #1682 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉
