### ISSUE TITLE
REQUEST: New membership for hectorj2f

### ISSUE THREAD

**Issue by hectorj2f** [kubernetes/org#1656]
### GitHub Username
@hectorj2f

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @caseydavenport 
- @pmorie 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
 I have collaborated since the beginning of the project, and so I made PRs in the past. However, I have been recently helping on different projects of the ecosystem with recent PRs to repositories such as:
https://github.com/kubernetes-retired/contrib/pull/1952
https://github.com/kubernetes-sigs/kubefed/pull/1171
https://github.com/kubernetes-sigs/kubefed/pull/1193
https://github.com/virtual-kubelet/virtual-kubelet/pull/671/commits
https://github.com/kubernetes/autoscaler/pull/2448
https://github.com/virtual-kubelet/virtual-kubelet/pull/614
https://github.com/kubernetes-sigs/kubefed/pull/1196
https://github.com/kubernetes-sigs/kubefed/pull/1146
https://github.com/kubernetes-sigs/kubefed/pull/1184
https://github.com/kubernetes-sigs/kubefed/pull/1157
https://github.com/kubernetes/kubernetes/pull/79379
https://github.com/kubernetes-sigs/kubefed/pull/1191
https://github.com/kubernetes/kubernetes/pull/79379

Likewise I am an official maintainer of diverse helm/charts at https://github.com/helm/charts

- Issues responded to: 
I believe it would be a bit hard to track my participations in terms of issues, replies as well as my participation on the Kubernetes slack channels.

https://github.com/kubernetes/kubernetes/issues/35183  https://github.com/kubernetes/autoscaler/issues/2628  https://github.com/kubernetes/kubeadm/issues/1637  https://github.com/kubernetes/kubernetes/issues/44328  https://github.com/kubernetes/kubernetes/issues/37554  https://github.com/kubernetes/kubernetes/issues/37278  https://github.com/kubernetes/kubernetes/issues/22770  
https://github.com/kubernetes-sigs/kubefed/issues/1176
https://github.com/kubernetes-sigs/kubefed/issues/1194  
https://github.com/kubernetes-sigs/kubefed/issues/1178 

- SIG projects I am involved with:`sig-multicluster`. I'd like to become a code owner of `kubernetes-sigs/kubefed` and help maintaining that project as well as drive their future releases. In addition, I am also involved on sig-cluster-lifecycle

**Comment by caseydavenport** [comment]
+1 from me

**Comment by pmorie** [comment]
+1 from me.

**Comment by nzoueidi** [comment]
Hey there @hectorj2f, thank you for all your contributions so far :)

I've created PR #1673 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by hectorj2f** [comment]
Thanks @nzouedi
