### ISSUE TITLE
REQUEST: New membership for gavinfish

### ISSUE THREAD

**Issue by gavinfish** [kubernetes/org#1657]
### GitHub Username
@gavinfish

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah
- @sftim

### List of contributions to the Kubernetes project
- PRs authored
kubernetes/website(20): [list](https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=author%3Agavinfish)
kubernetes/kubernetes(16): [list](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=author%3Agavinfish)

**Comment by zacharysarah** [comment]
+1!

**Comment by sftim** [comment]
+1!

**Comment by nzoueidi** [comment]
Hey there @gavinfish, thank you for all your contributions so far :)

I've created PR #1673 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
