### ISSUE TITLE
REQUEST: New membership for Adirio

### ISSUE THREAD

**Issue by Adirio** [kubernetes/org#1659]
### GitHub Username
@Adirio

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @DirectxMan12
- @camilamacedo86

### List of contributions to the Kubernetes project
- PRs authored in [`kubebuilder`](https://github.com/kubernetes-sigs/kubebuilder) (51 at application time): [link](https://github.com/kubernetes-sigs/kubebuilder/pulls?utf8=%E2%9C%93&q=author%3AAdirio)
- PRs reviewed in [`kubebuilder`](https://github.com/kubernetes-sigs/kubebuilder) (42 at application time): [link](https://github.com/kubernetes-sigs/kubebuilder/issues?utf8=%E2%9C%93&q=reviewed-by%3AAdirio+-author%3AAdirio)
- Issues responded to in [`kubebuilder`](https://github.com/kubernetes-sigs/kubebuilder) (38 at application time): [link](https://github.com/kubernetes-sigs/kubebuilder/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3AAdirio+-author%3AAdirio)
- SIG projects I am involved with: [`kubebuilder`](https://github.com/kubernetes-sigs/kubebuilder) ([contributors](https://github.com/kubernetes-sigs/kubebuilder/graphs/contributors)) and related tools, belonging to `sigs-api-machinery`

**Comment by camilamacedo86** [comment]
Yes, +1.  👍

**Comment by DirectXMan12** [comment]
:+1: from me as well.  @Adirio has been doing a lot of awesome work in KB.

**Comment by nzoueidi** [comment]
Hey there @Adirio, thank you for all your contributions so far :)

I've created PR #1673 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by Adirio** [comment]
Hi @nzoueidi,

First of all, thank you very much.

#1673 already got merged, but I still didn't get any membership invite notification. How long does it usually take? I'm asking because I recently signed in the new Beta GitHub notifications, hope that it is not an issue.
