### ISSUE TITLE
REQUEST: New membership for kgroschoff

### ISSUE THREAD

**Issue by kgroschoff** [kubernetes/org#1663]
### GitHub Username
@kgroschoff

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @maciaszczykm
- @jeefy

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - reviewed https://github.com/kubernetes/dashboard/pull/4905
- Issues responded to
  - none yet
- SIG projects I am involved with
  - helping out with german translations in the kubernetes-dashboard

**Comment by maciaszczykm** [comment]
+1

**Comment by nzoueidi** [comment]
Hey @jeefy, do you have a moment to sponsor @kgroschoff's org membership

**Comment by jeefy** [comment]
Sorry things have been crazy. :) 

+1

**Comment by nzoueidi** [comment]
Thank you @jeefy, hope everything goes well!

And thank you @kgroschoff for all your contributions so far :)

I've created PR #1682 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉
