### ISSUE TITLE
krew.sigs.k8s.io: Netlify site request

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/org#1668]
### Repository

kubernetes-sigs/krew

### Project domain

krew.sigs.k8s.io

Thanks. 🙌

**Comment by mrbobbytables** [comment]
Netlify domain is setup https://kubernetes-sigs-krew.netlify.com/
once the k8s domain is setup can configure the domain on the netlify side 👍

**Comment by mrbobbytables** [comment]
site is live, things should be good 👍 
Going to go ahead and close this out. If you have any problems please reach out in slack or reopen.

Thanks!

/close
