### ISSUE TITLE
New repository for wg-policy proposals and prototypes under kubernetes-sigs

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes/org#1669]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
wg-policy-prototypes

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@ericavonb
@hannibalhuang

### If not a staging repo, who should have write access
@JimBugwadia

### If not a staging repo, who should be listed as approvers in OWNERS
@ericavonb
@hannibalhuang
@JimBugwadia

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@ericavonb
@hannibalhuang
@JimBugwadia

### What should the repo description be
A place for policy work group related proposals and prototypes.

### What SIG and subproject does this fall under in sigs.yaml
this is a subproject / wg for sig-auth called policy

### Approvals
Requested at:
sig-auth ML: https://groups.google.com/forum/#!topic/kubernetes-sig-auth/ufi-8zv_90w
wg-policy ML: https://groups.google.com/forum/#!topic/kubernetes-wg-policy/PKn4LpaT-To

**Comment by cblecker** [comment]
Hi @JimBugwadia,
Working groups, by their definition, cannot own code or documentation. All the work from a WG must funnel up to one of their sponsoring sigs. As such, we cannot process this as-is.

Please reach out your sponsoring sigs (https://git.k8s.io/community/wg-policy) and get them to review the request and sponsor this work (or suggest another place to do it). This is what @nikhita was speaking about here: https://github.com/cncf/soc/pull/145/files#r383708223

**Comment by JimBugwadia** [comment]
@cblecker - thanks! Makes sense. Just contacted @tallclair for his recommendation on how to proceed.

**Comment by hannibalhuang** [comment]
+1 we have been discussing this for a long time, it would be great to have the sig repo for our ongoing k8s centric projects :)

**Comment by tallclair** [comment]
From our discussions at last sig-auth, I think we're OK with this, as long as it's clear that this is for prototypes & proposals, and not supported code. Along those lines:

- Repo name should be `wg-policy-prototypes`. I'm open to suggestions, but I'd like it to be clear from the URL that this isn't production code.
- Readme should clearly document the expectations for the repo.

**Comment by JimBugwadia** [comment]
Sounds good! I've updated the repo name and description in the request, based on your suggestion.

**Comment by nikhita** [comment]
Repo has been created: https://github.com/kubernetes-sigs/wg-policy-prototypes :+1: 

Also created:

- https://github.com/kubernetes/org/pull/1767 - to create GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4675 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by nikhita** [comment]
Closing as teams have been setup and repo has been added to sigs.yaml
