### ISSUE TITLE
REQUEST: New membership for <immuzz>

### ISSUE THREAD

**Issue by immuzz** [kubernetes/org#1676]
### GitHub Username
immuzz

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @PatrickLang
- @michmike

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pull/74684
- https://github.com/kubernetes/test-infra/pull/11301
- Issues responded to
- SIG projects I am involved with
SIG- Windows

**Comment by PatrickLang** [comment]
+1 - glad to have you helping :)

**Comment by michmike** [comment]
+1. thank you for helping Muzz

**Comment by nzoueidi** [comment]
Hey there @immuzz, thank you for all your contributions so far :)

I've created PR #1682 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉
