### ISSUE TITLE
REQUEST: New membership for elmiko

### ISSUE THREAD

**Issue by elmiko** [kubernetes/org#1677]
### GitHub Username
@elmiko 

### Organization you are requesting membership in
@kubernetes 
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timothysc 
- @ncdc 
- @enxebre 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/cluster-api/pull/2351
- https://github.com/kubernetes-sigs/cluster-api/pull/2271
- https://github.com/kubernetes/autoscaler/pull/1866
- https://github.com/kubernetes/enhancements/issues/609

**Comment by ncdc** [comment]
+1

**Comment by enxebre** [comment]
+1

**Comment by timothysc** [comment]
+1 from me

**Comment by nzoueidi** [comment]
Hey @elmiko, both @timothysc and @ncdc are from VMware - sponsors should be from different companies. 

Also, @enxebre is not in in any OWNERS file(s) for kubernetes and kubernetes-sigs orgs. Could you please pick/add another sponsor.

**Comment by nzoueidi** [comment]
Hey there @elmiko, thank you for all your contributions so far :)

I've created PR #1682 to add you to the Kubernetes & Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉

**Comment by elmiko** [comment]
thanks!
