### ISSUE TITLE
REQUEST: New membership for frobware

### ISSUE THREAD

**Issue by frobware** [kubernetes/org#1678]
### GitHub Username
@frobware

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ncdc
- @maciekpytel
- @hardikdr 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/autoscaler/pull/1866
- https://github.com/kubernetes/kubernetes/pull/51085
- https://github.com/kubernetes/kubernetes/pull/63859
- https://github.com/kubernetes/kubernetes/issues/50011
- https://github.com/kubernetes/kubernetes/pull/50690
- https://github.com/kubernetes/kubernetes/issues/49489
- https://github.com/kubernetes/kubernetes/pull/51715
- https://github.com/kubernetes/autoscaler/pull/1356
- https://github.com/kubernetes/autoscaler/pull/1456
- https://github.com/kubernetes/autoscaler/pull/1482
- https://github.com/kubernetes/autoscaler/pull/1516
- https://github.com/kubernetes/autoscaler/pull/1771
- https://github.com/kubernetes/autoscaler/pull/1863
- https://github.com/kubernetes/autoscaler/pull/2096
- https://github.com/kubernetes/autoscaler/pull/2308
- https://github.com/kubernetes/autoscaler/pull/2313

**Comment by ncdc** [comment]
+1

**Comment by MaciekPytel** [comment]
+1 for many contributions to autoscaling

**Comment by hardikdr** [comment]
+100

**Comment by nzoueidi** [comment]
Hey there @frobware, thank you for all your contributions so far :)

I've created PR #1682 to add you to the Kubernetes & Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉
