### ISSUE TITLE
REQUEST: New membership for sophieliu15

### ISSUE THREAD

**Issue by sophieliu15** [kubernetes/org#1679]
### GitHub Username
@sophieliu15

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @adrianludwin
- @tashimi

### List of contributions to the Kubernetes project
- PRs reviewed / authored
 kubernetes-sigs/multi-tenancy#371
 kubernetes-sigs/multi-tenancy#377
kubernetes-sigs/multi-tenancy#412
kubernetes-sigs/multi-tenancy#424
kubernetes-sigs/multi-tenancy#438
kubernetes-sigs/multi-tenancy#442
kubernetes-sigs/multi-tenancy#447
kubernetes-sigs/multi-tenancy#462
kubernetes-sigs/multi-tenancy#471
kubernetes-sigs/multi-tenancy#476
- Issues responded to
kubernetes-sigs/multi-tenancy#369
kubernetes-sigs/multi-tenancy#441
kubernetes-sigs/multi-tenancy#411
- SIG projects I am involved with
 kubernetes-sigs/multi-tenancy: I actively contribute to the [HNC](https://github.com/kubernetes-sigs/multi-tenancy/tree/master/incubator/hnc) project under multi-tenancy.

**Comment by adrianludwin** [comment]
Approved, Sophie's already making good contributions to HNC.

**Comment by tashimi** [comment]
![tenor-240687646](https://user-images.githubusercontent.com/719646/75712979-c8567c80-5c7d-11ea-9a2e-43620cae3aa3.gif)

+1!

**Comment by nzoueidi** [comment]
Hey there @sophieliu15, thank you for all your contributions so far :)

I've created PR #1682 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉
