### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for jinzhejz

### ISSUE THREAD

**Issue by jinzhejz** [kubernetes/org#168]
### GitHub Username
@jinzhejz

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@k82cn
@wanghaoran1988 

### List of contributions to the Kubernetes project
* kube-batch, here are all my [commits](https://github.com/kubernetes-sigs/kube-batch/commits?author=jinzhejz)

/area github-membership

**Comment by k82cn** [comment]
+1 to me

**Comment by wanghaoran1988** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @jinzhejz, thank you so much for all the work you've done with kube-batch! As a HPC/Research person definitely keeping an eye on the project. :)

I've created PR #171  to add you to both the Kubernetes and Kubernetes-Sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉 

/assign
