### ISSUE TITLE
REQUEST: New membership of kubernetes-csi 

### ISSUE THREAD

**Issue by kkmsft** [kubernetes/org#1680]
### GitHub Username

@kkmsft 

### Organization you are requesting membership in

kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
Already member kubernetes org. 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/kubernetes-csi/csi-proxy/pulls?utf8=✓&q=+is%3Apr+author%3A%40me+
   - https://github.com/kubernetes-csi/node-driver-registrar/pulls?utf8=✓&q=+is%3Apr+author%3A%40me+

- Issues responded to

- SIG projects I am involved with
CSI-Windows.

**Comment by nzoueidi** [comment]
This should be done by #1682
