### ISSUE TITLE
sig-network iptables-wrappers subproject

### ISSUE THREAD

**Issue by danwinship** [kubernetes/org#1688]
### New Repo, Staging Repo, or migrate existing
migrate existing, https://github.com/danwinship/iptables-wrappers

### Requested name for new repository
iptables-wrappers

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
danwinship, caseydavenport, dcbw, thockin

### If not a staging repo, who should have write access
danwinship, caseydavenport, dcbw, thockin

### If not a staging repo, who should be listed as approvers in OWNERS
danwinship

### If not a staging repo, who should be listed in SECURITY_CONTACTS
danwinship

### What should the repo description be
Wrapper scripts for using iptables in containers

### What SIG and subproject does this fall under in sigs.yaml
new subproject for sig-network called iptables-wrappers

### Approvals
Originally discussed in January 23, 2020 [SIG meeting](https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit#). Raised [on mailing list](https://groups.google.com/d/msg/kubernetes-sig-network/PE9PJdbeGIY/NYCN0JvNCQAJ) to no objections. In particular, [+1'ed by Tim](https://groups.google.com/d/msg/kubernetes-sig-network/PE9PJdbeGIY/1B99LwdyAgAJ).

**Comment by nikhita** [comment]
@danwinship sorry for the delay on this!

Can you update the copyright headers from the Red Hat boilerplate to Kubernetes one? You can find the k8s one here - https://github.com/kubernetes/kubernetes/tree/master/hack/boilerplate.

Looks good to go after that! I have invited you to the https://github.com/kubernetes-purgatory org. Once the boilerplates have been updated, can you move the repo to this dummy org? I can then migrate it to kubernetes-sigs from there.

GitHub doesn't allow adding admins to repos tied to personal accounts (i.e. non-org accounts). This requires us to move the repo to a (dummy) org first.

**Comment by danwinship** [comment]
Fixed the boilerplate and also updated the OWNERS file to add the sig-network team leads as approvers. It is now moved to kubernetes-purgatory.

**Comment by nikhita** [comment]
Repo has been migrated: https://github.com/kubernetes-sigs/iptables-wrappers :+1: 

Also created:

- https://github.com/kubernetes/org/pull/1706 - to create GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4597 - to update sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by nikhita** [comment]
All PRs have merged and teams have been granted access.

/close
