### ISSUE TITLE
REQUEST: New membership for alexgervais

### ISSUE THREAD

**Issue by alexgervais** [kubernetes/org#1689]
### GitHub Username
@alexgervais

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bowei 
- @youngnick

### List of contributions to the Kubernetes project
- Donated kubernetes-sigs/ingress-controller-conformance and authored PRs as well as issues thereafter
   - https://github.com/kubernetes-sigs/ingress-controller-conformance/issues?q=is%3Aissue+%40alexgervais+
   - https://github.com/kubernetes-sigs/ingress-controller-conformance/pulls?q=is%3Apr+%40alexgervais
- SIG-network Ingress V1 and sig-network-service-apis

**Comment by mrbobbytables** [comment]
gentle ping @bowei @youngnick for ack 👍

**Comment by cblecker** [comment]
/lifecycle stale

Is this still active? If so, please `/remove-lifecycle stale`
@alexgervais: you may wish to ping your sponsors (@bowei and @youngnick) on Slack and refer them to this.

**Comment by youngnick** [comment]
Oh, sorry! That is a solid ack from me.

**Comment by robscott** [comment]
:+1: from me, thanks for all your work @alexgervais!

**Comment by nikhita** [comment]
@alexgervais thank you for all your contributions :)

I've created PR #1789 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by alexgervais** [comment]
Thanks all! @nikhita  @mrbobbytables  @youngnick @robscott @bowei 
Looking forward to more contributions!
