### ISSUE TITLE
REQUEST: New membership for gab-satchi

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes/org#1690]
### GitHub Username
@gab-satchi 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects

### Sponsors
According to the cluster-api [contributor guidelines](https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md#issue-and-pull-request-management), an existing member of the k8s org doesn't need sponsors. Let me know if that's not the case. 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - [PR88287](https://github.com/kubernetes/kubernetes/pull/88287)
  - [PR84472](https://github.com/kubernetes/kubernetes/pull/84472)
  - [PR80911](https://github.com/kubernetes/kubernetes/pull/80911)
- sig-windows

**Comment by mrbobbytables** [comment]
Hey there @gab-satchi I've gone ahead and created PR #1704 to add you to @kubernetes-sigs. Once that merges, you should get a membership invite notification 👍 

/assign
