### ISSUE TITLE
sig-cloud-provider: add cloud-provider-huaweicloud repo

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes/org#1691]
### New Repo, Staging Repo, or migrate existing
Migrate existing: https://github.com/huawei-cloudnative/cloud-provider-huaweicloud

### Requested name for new repository
cloud-provider-huaweicloud

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@kevin-wangzefeng, @RainbowMango 

### If not a staging repo, who should have write access
@kevin-wangzefeng, @RainbowMango 

### If not a staging repo, who should be listed as approvers in OWNERS
@kevin-wangzefeng, @RainbowMango 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@kevin-wangzefeng, @RainbowMango 

### What should the repo description be
HUAWEI CLOUD Controller Manager is an external cloud controller manager for running kubernetes in a HUAWEI CLOUD cluster.

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject for sig-cloud-provider called cloud-provider-huaweicloud

### Approvals
See this [request cloud provider](https://github.com/kubernetes/enhancements/pull/1565)

**Comment by RainbowMango** [comment]
/cc @andrewsykim @cheftako @nikhita
Thanks.

**Comment by RainbowMango** [comment]
Thanks!
@nikhita Are you a member of the GitHub admin team?

**Comment by nikhita** [comment]
I have verified the CLAs and licenses. Everything looks good!

@RainbowMango can you add the `SECURITY_CONTACTS` file to the repo and add me as an admin to the repo? I can proceed with the migration after that. :+1:

**Comment by RainbowMango** [comment]
Sure thing, thanks.
Here: https://github.com/huawei-cloudnative/cloud-provider-huaweicloud/pull/62

> add me as an admin to the repo?
Done.

**Comment by nikhita** [comment]
Repo has been migrated - https://github.com/kubernetes-sigs/cloud-provider-huaweicloud. :tada: 

Also created:

- https://github.com/kubernetes/org/pull/1705 - to create GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4596 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue. :+1:

**Comment by nikhita** [comment]
Both PRs have merged and teams have been granted access.

/close
