### ISSUE TITLE
REQUEST: New membership for joshvanl

### ISSUE THREAD

**Issue by JoshVanL** [kubernetes/org#1693]
### GitHub Username
e.g. @joshvanl

### Organization you are requesting membership in
e.g. @kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @munnerz 
- (at)sponsor-2

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/88879
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/80574
https://github.com/kubernetes/kubernetes/issues/88878
- SIG projects I am involved with

**Comment by munnerz** [comment]
+1 - Josh has been working on cert-manager extensively and it'd be helpful to have him named as an approver & able to lgtm PRs like this: https://github.com/kubernetes/test-infra/pull/16685

He's also been contributing to & using various parts of `k8s.io/apiserver` via https://github.com/jetstack/kube-oidc-proxy/

**Comment by mrbobbytables** [comment]
@JoshVanL do you have a 2nd sponsor? it's been 2 weeks and usually folks hold off on opening these until they have 2 😬

**Comment by cblecker** [comment]
/lifecycle stale

Is this still active? If so, please `/remove-lifecycle stale`
Two sponsors are required for Kubernetes membership. They must have close interaction, and be familiar with your work. More details are available here: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by mrbobbytables** [comment]
It's been a month without an update. I'm going to go ahead and close this out. @JoshVanL if you find a second sponsor, please either reopen or create a new org membership request issue. 👍 
Thanks!

/close
