### ISSUE TITLE
REQUEST: New membership for jhonmike

### ISSUE THREAD

**Issue by jhonmike** [kubernetes/org#1694]
### GitHub Username
@jhonmike

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @femrtnz
- @jcjesus
- @devlware

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/19434
https://github.com/kubernetes/website/pull/19573
- Issues responded to
https://github.com/kubernetes/website/issues/13939

**Comment by femrtnz** [comment]
Approved. @jhonmike is helping us the Portuguese translations :)

FYI @zacharysarah @mrbobbytables

**Comment by devlware** [comment]
I also agree that @jhonmike will help us in the Portuguese team.

**Comment by jcjesus** [comment]
Approved for me too! @jhonmike is helping us.

**Comment by mrbobbytables** [comment]
Hey there @jhonmike , thank you for all your help with the localization efforts :)

I've created PR #1704  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
