### ISSUE TITLE
REQUEST: New membership for jayunit100

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/org#1695]
### GitHub Username
jayunit100

### Organization you are requesting membership in

kubernetes-sigs

### Requirements
- [x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dlipovetsky 
- @ravisantoshgudimetla
- @ncdc

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/500ab7a6407e123a52b120d4a672615773c2aa3b
- https://github.com/kubernetes-sigs/cluster-api/graphs/contributors

**Comment by ncdc** [comment]
👍

**Comment by ravisantoshgudimetla** [comment]
:+1:

**Comment by dlipovetsky** [comment]
:+1:

**Comment by justaugustus** [comment]
@jayunit100 -- As a Kubernetes org member, you're implicitly eligible for membership to kubernetes-sigs.

If you want, you can PR yourself in ([example](https://github.com/kubernetes/org/pull/1685)), assign me to the PR and I'll approve. :)

**Comment by jayunit100** [comment]
oh hey ! ok cool

**Comment by mrbobbytables** [comment]
@jayunit100 I opened up PR #1704 to add you to @kubernetes-sigs. Once that gets merged, you should get the membership invite notification 👍 

/assign
