### ISSUE TITLE
REQUEST: New membership for @djzager

### ISSUE THREAD

**Issue by djzager** [kubernetes/org#1698]
### GitHub Username
@djzager

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @shawn-hurley
- @alvaroaleman 
- @directxman12

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/controller-runtime/pull/663
  - https://github.com/kubernetes-sigs/controller-runtime/pull/811
  - https://github.com/kubernetes-sigs/controller-tools/pull/413
- Issues responded to
  - https://github.com/kubernetes-sigs/controller-runtime/issues/822
  - https://github.com/kubernetes-sigs/controller-tools/issues/206
  - https://github.com/kubernetes-sigs/controller-tools/issues/227
  - https://github.com/kubernetes-sigs/kubebuilder/issues/1071
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/controller-runtime
  - https://github.com/kubernetes-sigs/controller-tools
  - https://github.com/kubernetes-sigs/kubebuilder

**Comment by alvaroaleman** [comment]
+1

**Comment by DirectXMan12** [comment]
:+1:

**Comment by shawn-hurley** [comment]
👍

**Comment by mrbobbytables** [comment]
@djzager thanks for all your help with controller-runtime and kubebuilder :)

I've created PR #1704  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
