### ISSUE TITLE
REQUEST: New membership for chendotjs

### ISSUE THREAD

**Issue by chendotjs** [kubernetes/org#1699]
### GitHub Username
@chendotjs

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @aojea 
- @liggitt 
- @mattjmcnaughton

### List of contributions to the Kubernetes project
- PRs reviewed / authored

https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Achendotjs+is%3Aclosed

- Issues responded to

https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+commenter%3Achendotjs

**Comment by aojea** [comment]
+1

**Comment by liggitt** [comment]
+1

**Comment by mrbobbytables** [comment]
@chendotjs  thank you for all your contributions so far :)

I've created PR #1704  to add you to both the Kubernetes and Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification from both of them

Welcome to @kubernetes! 🎉

/assign
