### ISSUE TITLE
REQUEST: New membership for woopstar

### ISSUE THREAD

**Issue by woopstar** [kubernetes/org#17]
### GitHub Username
woopstar

### Organization you are requesting membership in
kubernetes-incubator

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-incubator/kubespray/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Awoopstar
- https://github.com/kubernetes-incubator/kubespray

**Comment by cblecker** [comment]
This request cannot be actioned without sponsors.

**Comment by cblecker** [comment]
Closing this issue. Sponsors are required for this. Please open a new issue when you have secured sponsorship.
