### ISSUE TITLE
REQUEST: New membership for m1kola

### ISSUE THREAD

**Issue by m1kola** [kubernetes/org#170]
### GitHub Username
@m1kola

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @soltysh 
- @seans3 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/67573
  - https://github.com/kubernetes/kubernetes/pull/69500
  - https://github.com/kubernetes/kubernetes/pull/69477
  - https://github.com/kubernetes/kubernetes/pull/67860
  - https://github.com/kubernetes/kubernetes/pull/67316
  - https://github.com/kubernetes/kubernetes/pull/66692
  - https://github.com/kubernetes/kubernetes/pull/66463
- Issues responded to
  - https://github.com/kubernetes/kubectl/issues/542
  - https://github.com/kubernetes/kubectl/issues/535
- SIG projects I am involved with
  - sig-cli

/area github-membership

**Comment by seans3** [comment]
+1

**Comment by soltysh** [comment]
+1

**Comment by cblecker** [comment]
Invite will be sent out as soon as #176 merges. Welcome to @kubernetes! 🚀
