### ISSUE TITLE
Request to create new repository “kubernetes-client/c”

### ISSUE THREAD

**Issue by ityuhui** [kubernetes/org#1700]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
c

### Which Organization should it reside
kubernetes-client

### If not a staging repo, who should have admin access
@brendandburns @ityuhui

### If not a staging repo, who should have write access
@brendandburns @ityuhui

### If not a staging repo, who should be listed as approvers in OWNERS
@brendandburns @ityuhui

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@brendandburns @ityuhui

### What should the repo description be
c client library for kubernetes

### What SIG and subproject does this fall under in sigs.yaml
sig-api-machinery kubernetes-client

### Approvals

This new client is discussed and sponsored by @brendandburns
 
https://github.com/kubernetes-client/gen/issues/132
https://github.com/kubernetes-client/gen/pull/148

### Additional context for request

/cc @brendandburns

**Comment by mrbobbytables** [comment]
/assign @brendandburns @fedebongio @deads2k @lavalamp 
@ityuhui In addition to Brendan's signs off you will need approval from the [sig-api-machinery leads](https://github.com/kubernetes/community/tree/master/sig-api-machinery#leadership) as the owners of the [kubernetes-client libraries](https://github.com/kubernetes/community/tree/master/sig-api-machinery#kubernetes-clients).

You will also need to apply for org membership to @kubernetes-client. For information on this, please see the [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

**Comment by lavalamp** [comment]
As long as two people are signed up to maintain it, it's fine with me.

/approve

**Comment by brendandburns** [comment]
/approve

I will sign up to maintain this in addition to @ityuhui 

There's a little bit of a catch 22 here in that @ityuhui needs to be a member of the kubernetes org, but the main contribution is what would be checked into the repo that we're trying to create :)

But I'm willing to sponsor @ityuhui into the Kubernetes org on the basis of this as a future contribution. Let me know if that works.

**Comment by nikhita** [comment]
@brendandburns That works, especially since they have already had a few contributions in other repos already (https://github.com/kubernetes-client/gen/pull/148). :)

**Comment by brendandburns** [comment]
Cool, do we need to do anything else to get this repo created?

Thanks!

**Comment by mrbobbytables** [comment]
@ityuhui if you could, please create an issue here using the [Org Membership Request Issue Template](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E). You will want to request membership to the kubernetes-client org and reference this issue with @brendandburns and myself as a sponsor. 👍 

I understand its kind of an odd situation and I'll add my +1.

Once that's done we can create the repo with the correct owners without having to do a follow up PR :)

**Comment by ityuhui** [comment]
@mrbobbytables  
OK. I will do it.

**Comment by ityuhui** [comment]
Hello @mrbobbytables @brendandburns 

I have submitted the membership request to the kubernetes-client @ https://github.com/kubernetes/org/issues/1713

Thank you for sponsoring me !

**Comment by mrbobbytables** [comment]
/assign

I'll create the repo once #1718 is merged and the membership invite accepted :)

**Comment by ityuhui** [comment]
Thank you @mrbobbytables

**Comment by mrbobbytables** [comment]
The repo has been created: https://github.com/kubernetes-client/c
The teams have been added: #1723
Once https://github.com/kubernetes/community/pull/4629 is merged, this should be able to be closed :)

**Comment by mrbobbytables** [comment]
https://github.com/kubernetes/community/pull/4629 has merged, and with that everything should be good. Going to go ahead and close this out.

If you have any questions, please feel free to reach out either in this issue or give me a poke in slack. 

Thanks!

/close

**Comment by ityuhui** [comment]
Thank you @mrbobbytables
