### ISSUE TITLE
REQUEST: New membership for @wfernandes

### ISSUE THREAD

**Issue by wfernandes** [kubernetes/org#1703]
### GitHub Username
@wfernandes

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @vincepri 
- @fabriziopandini 
- @CecileRobertMichon 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1393
  - https://github.com/kubernetes/k8s.io/pull/652
- Issues responded to
  - https://github.com/kubernetes-sigs/kubebuilder/issues/1392
- SIG projects I am involved with
  - SIG Cluster Lifecycle

**Comment by vincepri** [comment]
+:100:

**Comment by mrbobbytables** [comment]
@wfernandes do you happen to know someone else who can sponsor you? Sponsors must be from different companies 😬

**Comment by wfernandes** [comment]
@mrbobbytables Let me ask around 🙂

**Comment by CecileRobertMichon** [comment]
+1

**Comment by fabriziopandini** [comment]
+1
@wfernandes thanks for your great work!

**Comment by mrbobbytables** [comment]
@wfernandes thank you for all your contributions so far :)

I've created PR #1718  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
