### ISSUE TITLE
REQUEST: New membership for @sedefsavas

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes/org#1707]
### GitHub Username
@sedefsavas
### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @vincepri 
- @CecileRobertMichon 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api/pull/2559
https://github.com/kubernetes-sigs/cluster-api/pull/2463

- Issues responded to
https://github.com/kubernetes-sigs/cluster-api/issues/2395
https://github.com/kubernetes-sigs/cluster-api/issues/2518

- SIG projects I am involved with
cluster-api

**Comment by vincepri** [comment]
+:100:

**Comment by CecileRobertMichon** [comment]
+1!

**Comment by mrbobbytables** [comment]
Hey there @sedefsavas, thank you for all your help with the cluster-api :)

I've created PR #1718  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
