### ISSUE TITLE
REQUEST: New membership for @brianpursley

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/org#1709]
### GitHub Username
@brianpursley

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @soltysh 
- @seans3

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/87527
https://github.com/kubernetes/kubernetes/pull/87633
https://github.com/kubernetes/kubernetes/pull/87776
https://github.com/kubernetes/kubernetes/pull/88765
https://github.com/kubernetes/website/pull/19450
https://github.com/kubernetes/website/pull/19467
https://github.com/kubernetes/website/pull/19468
https://github.com/kubernetes/website/pull/19469
https://github.com/kubernetes/website/pull/19470
https://github.com/kubernetes-sigs/krew/pull/547
https://github.com/kind-ci/examples/pull/20

- Issues responded to
https://github.com/kubernetes/kubectl/issues/792
https://github.com/kubernetes/kubectl/issues/796
https://github.com/kubernetes/kubectl/issues/813
https://github.com/kubernetes/kubectl/issues/816
https://github.com/kubernetes/website/issues/19340
https://github.com/kubernetes-sigs/krew/issues/521

- SIG projects I am involved with
SIG-CLI
SIG-Docs

**Comment by seans3** [comment]
+1

**Comment by soltysh** [comment]
:+1:

**Comment by mrbobbytables** [comment]
@brianpursley , thank you for all your contributions to kubectl \o/

I've created PR #1718  to add you to both the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign
