### ISSUE TITLE
REQUEST: New membership for bozzo

### ISSUE THREAD

**Issue by bozzo** [kubernetes/org#1711]
### GitHub Username
@bozzo

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Miouge1 
- @LuckySB

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pulls?q=is%3Apr+author%3Abozzo

- Issues responded to
- SIG projects I am involved with
https://github.com/kubernetes-sigs/kubespray

**Comment by LuckySB** [comment]
Happy to be sponsor.

/lgtm

**Comment by Miouge1** [comment]
+1

Great to get some help with kube-router support in Kubespray, thank you @bozzo

**Comment by mrbobbytables** [comment]
@bozzo, thank you for all your help with kubespray

I've created PR #1718  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
