### ISSUE TITLE
REQUEST: New membership for nilo19

### ISSUE THREAD

**Issue by nilo19** [kubernetes/org#1712]
### GitHub Username
@nilo19

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @feiskyer 
- @justaugustus 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/306
- Issues responded to
- SIG projects I am involved with
https://github.com/kubernetes-sigs/cloud-provider-azure

**Comment by feiskyer** [comment]
+1 for @nilo19's contributions to cloud-provider-azure

**Comment by justaugustus** [comment]
+1. Thanks for your work in cloud-provider-azure, @nilo19!!

**Comment by mrbobbytables** [comment]
Hey there @nilo19 , thank you for all your contributions to the azure cloud provider :)

I've created PR #1718  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
