### ISSUE TITLE
REQUEST: New membership for ityuhui

### ISSUE THREAD

**Issue by ityuhui** [kubernetes/org#1713]
### GitHub Username
@ityuhui

### Organization you are requesting membership in
@kubernetes-client

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @brendandburns 
- @mrbobbytables

### List of contributions to the Kubernetes project
- Submited the PR  kubernetes-client/gen#148
- Will submit the c client library code to  kubernetes-client/c

**Comment by mrbobbytables** [comment]
+1 from sponsor, thanks for getting the c client going :)

**Comment by brendandburns** [comment]
+1 to sponsor

--brendan

________________________________

**Comment by mrbobbytables** [comment]
@ityuhui , thank you for kick start the C client.

I've created PR #1718  to add you to the Kubernetes-client Org. Once that gets merged, you should get a membership invite notification and I can move forward with creating the repo \o/

Welcome to @kubernetes-client! 🎉

/assign

**Comment by ityuhui** [comment]
Thank you @mrbobbytables @brendandburns
