### ISSUE TITLE
REQUEST: New membership for olivierlemasle

### ISSUE THREAD

**Issue by olivierlemasle** [kubernetes/org#1714]
### GitHub Username
@olivierlemasle

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @brancz 
- @tariq1890 

### List of contributions to the Kubernetes project
- PRs authored: https://github.com/search?q=org%3Akubernetes+author%3Aolivierlemasle+is%3Apr&type=Issues
- PRs reviewed: https://github.com/search?q=commenter%3Aolivierlemasle+is%3Apr+-author%3Aolivierlemasle+org%3Akubernetes&type=Issues
- Issues responded to: https://github.com/search?q=commenter%3Aolivierlemasle+is%3Aissue+-author%3Aolivierlemasle+org%3Akubernetes&type=Issues
- SIG projects I am involved with: kube-state-metrics (SIG instrumentation)

**Comment by brancz** [comment]
Thanks for all your contributions! Looking forward to working with you even more! :) lgtm :tada:

**Comment by tariq1890** [comment]
+1 from me too!

I couldn't be happier to recommend @olivierlemasle for his invaluable contributions to kube-state-metrics. Welcome aboard!

**Comment by olivierlemasle** [comment]
Ping @kubernetes/owners

**Comment by olivierlemasle** [comment]
Ping @mrbobbytables

**Comment by mrbobbytables** [comment]
Hey there @olivierlemasle, thank you for all your contributions so far :)

I've created PR #1741  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
