### ISSUE TITLE
sig-cloud-provider: Add cloud-provider-baiducloud repository

### ISSUE THREAD

**Issue by tizhou86** [kubernetes/org#1716]
### New Repo, Staging Repo, or migrate existing
Migrate existing repository: https://github.com/baidu/cloud-provider-baiducloud

### Requested name for new repository
cloud-provider-baiducloud

### Which Organization should it reside
kubernetes or kubernetes-sigs

### If not a staging repo, who should have admin access
@tizhou86, @ZP-AlwaysWin, @hello2mao

### If not a staging repo, who should have write access
@tizhou86, @ZP-AlwaysWin, @hello2mao

### If not a staging repo, who should be listed as approvers in OWNERS
@tizhou86, @ZP-AlwaysWin, @hello2mao

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@tizhou86, @ZP-AlwaysWin, @hello2mao

### What should the repo description be
Baidu Cloud Controller Manager is an external cloud controller manager for running Kubernetes in Baidu Cloud cluster.

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject for sig-cloud-provider called cloud-provider-baiducloud

### Approvals
Related approval at [this link](https://github.com/kubernetes/enhancements/pull/1563).

### Additional context for request
N/A

**Comment by andrewsykim** [comment]
+1

**Comment by mrbobbytables** [comment]
@tizhou86
Can you add `SECURITY_CONTACTS` and  `OWNERS` files to the repo? We try to have those staged before import.

I'll give it a FOSSA scan and get back to you if other things are needed before import :)

/assign

**Comment by tizhou86** [comment]
> @tizhou86
> Can you add `SECURITY_CONTACTS` and `OWNERS` files to the repo? We try to have those staged before import.
> 
> I'll give it a FOSSA scan and get back to you if other things are needed before import :)
> 
> /assign

Done, please take a look, thanks!

**Comment by tizhou86** [comment]
Ping @mrbobbytables , thanks!

**Comment by mrbobbytables** [comment]
Sorry for the delay @tizhou86, I've been busy with $dayjob -- Things looked okay on the dependency side, but the commit history for the repo is kind of messy 😬 

Gives the list of authors:
```
$ git --no-pager log --author=.* --pretty=format:"%an - %ae" | sort | uniq
CodeLingo Bot - bot@codelingo.io
Hongbin Mao - hello2mao@gmail.com
Meng Yang - yangm3ng@gmail.com
Ti Zhou - tizhou1986@gmail.com
Tianyuan Sun - suntianyuan0611@gmail.com
Tianyuan Sun - suntianyuan@baidu.com
guohaowang - wangguohao.2009@gmail.com
hello2mao - hello2mao@gmail.com
maohongbin01 - maohongbin01@baidu.com
mengyang02 - mengyang02@baidu.com
suntianyuan - suntianyuan@baidu.com
tizhou86 - tizhou1986@gmail.com
wangchengcheng - wangchengcheng@appledeMacBook-Pro.local
wcc - 751484782@qq.com
wcc - wangchengcheng01@baidu.com
wccsama - wangchengcheng01@baidu.com
xuri - xuri.me@gmail.com
```

Commits signed by:
```
wangchengcheng - wangchengcheng@appledeMacBook-Pro.local
wcc - 751484782@qq.com
wccsama - wangchengcheng01@baidu.com
```
Do not have a signed CLA for that email address. There may be a few other issues, but thats what we've found so far.

These ideally should be re-signed as the correct author, or while not ideal -- removed and added back in by an author with a valid CLA.

cc @caniszczyk

**Comment by tizhou86** [comment]
Hi @mrbobbytables , we've just re-signed the commits to the correct author today, please take a look, and if there are any other issues, please let me know, thanks!

```
wccsama - wangchengcheng01@baidu.com
```
By the way, we confirmed that this one has a signed CLA.

**Comment by mrbobbytables** [comment]
Awesome, it looks like the CLA issues have been resolved 👍 
If you could, please add me as an admin to the repo and I should be able to do the migration :)

**Comment by tizhou86** [comment]
@mrbobbytables Invitation sent, thanks Bob!

**Comment by mrbobbytables** [comment]
Hm, under the admin tab does it give you the option of transferring the repo? I see this when I take a look at it:
```
Transfer ownership
Organization members cannot transfer repositories
```

**Comment by tizhou86** [comment]
@mrbobbytables Sorry for that, it should be working now, please try it again, thanks!

**Comment by mrbobbytables** [comment]
The repo has been transferred. \o/
PR to add teams is here: https://github.com/kubernetes/org/pull/1745
PR to add it as a subproject: https://github.com/kubernetes/community/pull/4650

Once those have merged and teams granted access the migration should be complete.

**Comment by mrbobbytables** [comment]
Now that https://github.com/kubernetes/community/pull/4650 has merged -- all steps for repo migration have been complete 🎉 
With that I'm going to go ahead and close this out.
If you have questions, feel free to reopen or give me a poke in slack.

Thanks!

/close
