### ISSUE TITLE
Migrate kubernetes-incubator/node-feature-discovery to kubernetes-sigs/

### ISSUE THREAD

**Issue by marquiz** [kubernetes/org#172]
### New Repo, or migrate existing
Migrate existing

### Requested name for new repository
node-feature-discovery

### Which Organization should it reside
kubernetes-sigs

### Who should be provided access to this repository
@marquiz
@balajismaniam

### Approvals
Please detail out the approval process for the new repo
Requirements are listed here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

Migration was discussed and agreed on in [SIG-node meeting](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.tckc5u7ktdbz) on 2018/10/09. Approved by @derekwaynecarr.

### Additional context for request
Any additional information or context to describe the request.

/cc @derekwaynecarr 

/area github-repo

**Comment by cblecker** [comment]
/assign

Sorry for the delay on this! Are you ready for this migration? When would you like me to take care of it?

**Comment by marquiz** [comment]
No problem, as we've been iterating over one issue (kubernetes-incubator/node-feature-discovery#176) which I wanted to resolve before the migration. But, I think we would be ready, now.

So, please migrate whenever you have time.

**Comment by marquiz** [comment]
ping @cblecker, when do you think you would be able to do the migration?

**Comment by cblecker** [comment]
@marquiz taking a look at this now :)

**Comment by cblecker** [comment]
Okay, this should be mostly done.

Can you please open a PR to update sigs.yaml with the new repo location?

**Comment by marquiz** [comment]
> Okay, this should be mostly done.

Cool, thanks!
 
> Can you please open a PR to update sigs.yaml with the new repo location?

kubernetes/community#2985

**Comment by cblecker** [comment]
All done!
/close
