### ISSUE TITLE
REQUEST: New membership for prksu

### ISSUE THREAD

**Issue by prksu** [kubernetes/org#1725]
### GitHub Username
@prksu 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xmudrii 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/140
  - https://github.com/kubernetes-sigs/cluster-api/pull/2435
- Issues responded to
  - https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/issues/139
- SIG projects I am involved with
  - sig-cluster-lifecycle
  - cluster-api
  - cluster-api-provider-digitalocean

**Comment by xmudrii** [comment]
+1

Additional sponsor is not needed since @prksu is already the Kubernetes org member.

**Comment by cpanato** [comment]
+1

**Comment by cpanato** [comment]
I think you can open a PR similar to this one: https://github.com/kubernetes/org/pull/1685

Add similar commit message and put your GitHub in the alphabetical order in the list 😄 

cc @prksu @xmudrii

**Comment by prksu** [comment]
@cpanato is it ok to do that? :sweat_smile:

**Comment by cpanato** [comment]
@prksu yes, why not? :)
the worst thing that can happen is to close the PR, which i bet not going to happen :)

**Comment by xmudrii** [comment]
@prksu +1 to what @cpanato said, it should be totally okay. :slightly_smiling_face:
