### ISSUE TITLE
REQUEST: New membership for @mohamedsgap

### ISSUE THREAD

**Issue by mohamedsgap** [kubernetes/org#1726]
### GitHub Username
@mohamedsgap

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @remyleone 
- @rbenzair

### List of contributions to the Kubernetes project
- [PR](https://github.com/kubernetes/website/pull/19758)
- SIG-Docs localization in Arabic (https://github.com/kubernetes/website)

**Comment by remyleone** [comment]
👍

**Comment by mohamedsgap** [comment]
@sftim any update??

**Comment by sftim** [comment]
Hi @mohamedsgap it sounds like you'd like help or advice. I'm not sure I'm the right person to help you with that - did you mean to ask someone else?

**Comment by rlenferink** [comment]
+1 @mohamedsgap is helping out to start an Arabic localization of our docs 🎉

**Comment by mrbobbytables** [comment]
@mohamedsgap, thank you for kickstarting the arabic localization

I've created PR #1741  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
