### ISSUE TITLE
REQUEST: New membership for jingyih

### ISSUE THREAD

**Issue by jingyih** [kubernetes/org#1729]
### GitHub Username
@jingyih

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims
- @jpbetz

### List of contributions to the Kubernetes project
- PRs authored
https://github.com/search?q=org%3Akubernetes+author%3Ajingyih+is%3Apr&type=Issues
- PRs reviewed
https://github.com/search?q=org%3Akubernetes+commenter%3Ajingyih+-author%3Ajingyih+is%3Apr&type=Issues
- Issues responded to
https://github.com/search?q=commenter%3Ajingyih+is%3Aissue+-author%3Ajingyih+org%3Akubernetes&type=Issues
- SIG projects I am involved with
sig api-machinery

**Comment by jpbetz** [comment]
/lgtm
Thanks for all your hard work @jingyih !

**Comment by dims** [comment]
/lgtm

Big thanks from as well @jingyih

**Comment by mrbobbytables** [comment]
@jingyih, thank you for all your help with the project thus far \o/

I've created PR #1741 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
