### ISSUE TITLE
Migrate github.com/liggitt/clientgofix repo to kubernetes-sigs/clientgofix

### ISSUE THREAD

**Issue by liggitt** [kubernetes/org#1731]
### New Repo, Staging Repo, or migrate existing
Migrate https://github.com/liggitt/clientgofix

### Requested name for new repository
clientgofix

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@liggitt, @mikedanese

### If not a staging repo, who should have write access
@liggitt, @mikedanese

### If not a staging repo, who should be listed as approvers in OWNERS
@liggitt, @mikedanese

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@liggitt, @mikedanese

### What should the repo description be
> clientgofix rewrites calls to old k8s.io/client-go methods to use newer invocations

### What SIG and subproject does this fall under in sigs.yaml
This is part of the kubernetes-clients subproject of sig-api-machinery (https://github.com/kubernetes/community/tree/master/sig-api-machinery#kubernetes-clients)

### Approvals
Discussed with sig-api-machinery leads already, they can ack here
/assign @deads2k @lavalamp

### Additional context for request
Much more context about this tool can be found at https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20200123-client-go-ctx.md

**Comment by deads2k** [comment]
This is great to ease the migration.

/lgtm
/approve

**Comment by nikhita** [comment]
Repo has been migrated: https://github.com/kubernetes-sigs/clientgofix

Also created:
- https://github.com/kubernetes/org/pull/1733 - to create GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4640 - to add repo to sigs.yaml

Once https://github.com/kubernetes/community/pull/4640 is merged, we can close this issue.

**Comment by liggitt** [comment]
thanks, repo transferred, teams set up, sigs.yaml updated

**Comment by lavalamp** [comment]
belated +1
