### ISSUE TITLE
REQUEST: New membership for olemarkus

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/org#1732]
### GitHub Username
olemarkus

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zetaab 
- @rifelpet 

### List of contributions to the Kubernetes project
- PRs https://github.com/search?q=org%3Akubernetes+author%3Aolemarkus+is%3Apr&type=Issues
- Issues https://github.com/search?q=commenter%3Aolemarkus+is%3Aissue+-author%3Aolivierlemasle+org%3Akubernetes&type=Issues

**Comment by zetaab** [comment]
+1

**Comment by rifelpet** [comment]
+1 thanks for your contributions so far!

**Comment by mrbobbytables** [comment]
@olemarkus , thank you for all your help with the kops subproject :)

I've created PR #1741  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
