### ISSUE TITLE
REQUEST: New membership for marosset - kubernetes-sigs

### ISSUE THREAD

**Issue by marosset** [kubernetes/org#1736]
### GitHub Username
e.g. @marosset 

### Organization you are requesting membership in
e.g. @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @chewong 
- @michmike 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/windows-testing/pull/143
  - https://github.com/kubernetes-sigs/windows-testing/pull/128
  - https://github.com/kubernetes-sigs/sig-windows-tools/pull/34
- Issues responded to
- SIG projects I am involved with
  - SIG-windows co-chair - https://github.com/kubernetes/community/pull/4575

**Comment by chewong** [comment]
+1

**Comment by justaugustus** [comment]
+1

**Comment by michmike** [comment]
+1

**Comment by justaugustus** [comment]
@marosset -- As a member of the `kubernetes` org, you're implicitly eligible for membership to the other orgs, like `kubernetes-sigs`, so you can just PR yourself in :)

Here's an example of how to do that: https://github.com/kubernetes/org/pull/1685
Keeping two things in mind:
- Usernames must be alpha-sorted
- PR title and commit message must clearly listed who you are and what you're being added to, so:
  ```
  Add marosset to kubernetes-sigs org
  ```

**Comment by marosset** [comment]
Did not know that...
I'll close this issue and do follow up with a PR :)
