### ISSUE TITLE
REQUEST: New membership for Benwa-98

### ISSUE THREAD

**Issue by Benwa-98** [kubernetes/org#1739]
### GitHub Username
@Benwa-98

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@remyleone
@rbenzair

### List of contributions to the Kubernetes project

(PR) [https://github.com/kubernetes/website/pull/19758]
SIG-Docs localization in Arabic (https://github.com/kubernetes/website)

**Comment by mohamedsgap** [comment]
+1 :+1:

**Comment by mohamedsgap** [comment]
@remyleone

**Comment by remyleone** [comment]
+1

Em seg, 23 de mar de 2020 23:58, Mohamed Abdel Nasser <
notifications@github.com> escreveu:

**Comment by rlenferink** [comment]
+1

**Comment by mrbobbytables** [comment]
I know this is to help with starting a new localization effort, but one of the [membership requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#member) is to be actively contributing to the project. In the associated PR it doesn't look like there has been 😬. 

Once the Arabic localization effort is started and there are a few contributions, I'd move to reopen this 👍 

/cc @zacharysarah

**Comment by zacharysarah** [comment]
Agreed with @mrbobbytables. I’d like to see some open PRs before approving a localization membership.

**Comment by cblecker** [comment]
/lifecycle stale

Is this still active? If so, please `/remove-lifecycle stale`
As noted, active contributions to the project are required prior to submitting for membership. Please note that membership is not required to contribute.

**Comment by mrbobbytables** [comment]
As there hasn't been any activity in about a month, I'm going to go ahead and close this out for now. @Benwa-98 if things should change, please reopen the issue or create a new org membership request 👍 

Thanks!

/close
