### ISSUE TITLE
REQUEST: kubernetes-sigs membership for marquiz 

### ISSUE THREAD

**Issue by marquiz** [kubernetes/org#174]
### GitHub Username
@marquiz

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@spiffxp 
@vikaschoudhary16 

This PR is related to #172.

### List of contributions to the Kubernetes project
- [node-feature-discovery](https://github.com/kubernetes-incubator/node-feature-discovery/pulls?utf8=%E2%9C%93&q=author%3Amarquiz)

/area github-membership

**Comment by cblecker** [comment]
@marquiz Right now our policies are set up that membership in @kubernetes automatically qualifies you for membership in other k8s orgs as required.. this doesn't necessarily apply in the other direction however (membership in @kubernetes-incubator doesn't automatically get you @kubernetes-sigs membership).

As such, 2 sponsors that meet the guidelines are still required. Are you able to solicit those? Thanks!

**Comment by marquiz** [comment]
> As such, 2 sponsors that meet the guidelines are still required.

OK, added two sponsorts

**Comment by spiffxp** [comment]
+1
