### ISSUE TITLE
REQUEST: New membership for zhlhahaha

### ISSUE THREAD

**Issue by zhlhahaha** [kubernetes/org#1742]
### GitHub Username
@zhlhahaha

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @BenTheElder 
- @lubinsz
- @mkumatag 
### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/82308
https://github.com/kubernetes/kubernetes/pull/82413
https://github.com/kubernetes/kubernetes/pull/85601
https://github.com/kubernetes/kubernetes/pull/86573
https://github.com/kubernetes/kubernetes/pull/86598
https://github.com/kubernetes-sigs/kind/pull/1346

**Comment by dims** [comment]
+1 from me!

**Comment by lubinsz** [comment]
+1 :)

**Comment by nikhita** [comment]
@zhlhahaha Unfortunately, @lubinsz cannot act as a sponsor as sponsors [need to be reviewers/approvers](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) for any repo in the @kubernetes org. :(

@BenTheElder should still be able to sponsor though.

**Comment by mkumatag** [comment]
+1
Thanks for all your patched so far, looking forward to see more contributions from you.

**Comment by mrbobbytables** [comment]
@zhlhahaha , thank you for all your contributions so far :)

I've created PR #1769  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by BenTheElder** [comment]
sorry, I've just been overwhelmed again, my inbox has overflowed.
