### ISSUE TITLE
REQUEST: New membership for danehans

### ISSUE THREAD

**Issue by danehans** [kubernetes/org#175]
### GitHub Username
@danehans

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pmorie  
- @marun 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+author%3Adanehans

/area github-membership

**Comment by cblecker** [comment]
Invite will be sent out as soon as #176 merges. Welcome to @kubernetes-sigs! 🚀
