### ISSUE TITLE
REQUEST: New membership for ricolin

### ISSUE THREAD

**Issue by ricolin** [kubernetes/org#1751]
### GitHub Username
@ricolin

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev  e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ramineni
- @lxkong

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/cloud-provider-openstack/pull/910
  https://github.com/kubernetes/cloud-provider-openstack/pull/967
- SIG projects I am involved with:
  sig-cloud-provider

**Comment by lingxiankong** [comment]
/lgtm

Thanks for adding the multi-arch support to cloud-provider-openstack.

**Comment by nikhita** [comment]
@ricolin thank you for all your help with cloud-provider-openstack :)

I've created PR #1762  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
