### ISSUE TITLE
REQUEST: New membership for  tanjunchen

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/org#1752]
### GitHub Username

@tanjunchen 

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

I am the member of kubernetes now. 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

Kubernetes/kubernetes

https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Atanjunchen+is%3Aclosed+

Kubernetes/website

https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Atanjunchen+is%3Aclosed

- Issues responded to
- SIG projects I am involved with

**Comment by nikhita** [comment]
@tanjunchen I've created PR #1762  to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
