### ISSUE TITLE
REQUEST: New membership for kmova

### ISSUE THREAD

**Issue by kmova** [kubernetes/org#1755]
### GitHub Username
@kmova

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @msau42
- @xing-yang

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * https://github.com/kubernetes/community/pull/4301
  * https://github.com/kubernetes/minikube/pull/2500
  * https://github.com/kubernetes/community/pull/1857
  * https://github.com/kubernetes/dashboard/pull/2544
  * https://github.com/kubernetes/community/pull/1638
  * https://github.com/kubernetes/dashboard/pull/2249
  * https://github.com/kubernetes-incubator/external-storage/issues
  * https://github.com/kubernetes-csi/csi-lib-iscsi/issues
  * https://github.com/kubernetes-csi/drivers/pull/157

- Issues responded to
  * https://github.com/kubernetes/kubernetes/issues/58569
  * https://github.com/kubernetes/minikube/issues/2506
  * https://github.com/kubernetes/kubernetes/issues/69168
  * https://github.com/kubernetes-incubator/external-storage/issues/736
 
- SIG projects I am involved with
   * sig-storage

**Comment by xing-yang** [comment]
+1

**Comment by msau42** [comment]
+1

**Comment by nikhita** [comment]
@kmova thank you for all your help with sig storage :)

I've created PR #1762 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
