### ISSUE TITLE
REQUEST: New membership for chriskim06

### ISSUE THREAD

**Issue by chriskim06** [kubernetes/org#1757]
### GitHub Username
@chriskim06

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ahmetb 
- @corneliusweig 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/krew/pull/408
https://github.com/kubernetes-sigs/krew/pull/432
https://github.com/kubernetes-sigs/krew/pull/444
https://github.com/kubernetes-sigs/krew/pull/465
https://github.com/kubernetes-sigs/krew/pull/466
https://github.com/kubernetes-sigs/krew/pull/510
https://github.com/kubernetes-sigs/krew/pull/512
https://github.com/kubernetes-sigs/krew/pull/526
https://github.com/kubernetes-sigs/krew/pull/537
https://github.com/kubernetes-sigs/krew/pull/545
https://github.com/kubernetes-sigs/krew/pull/555
https://github.com/kubernetes-sigs/krew/pull/558
- Issues responded to
https://github.com/kubernetes-sigs/krew/issues/328
https://github.com/kubernetes-sigs/krew/issues/383
https://github.com/kubernetes-sigs/krew/issues/402
https://github.com/kubernetes-sigs/krew/issues/410
https://github.com/kubernetes-sigs/krew/issues/419
https://github.com/kubernetes-sigs/krew/issues/421
https://github.com/kubernetes-sigs/krew/issues/431
https://github.com/kubernetes-sigs/krew/issues/483
https://github.com/kubernetes-sigs/krew/issues/507
- SIG projects I am involved with
SIG-CLI

**Comment by corneliusweig** [comment]
👍 from me. Chris has shown his dedication to krew and is driving the project forward with his work on multi-indexes.

**Comment by ahmetb** [comment]
> 👍 from me. Chris has shown his dedication to krew and is driving the project forward with his work on multi-indexes.

Agreed. Seconding.

**Comment by nikhita** [comment]
@chriskim06 thank you for all your help with krew :)

I've created PR #1762  to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
