### ISSUE TITLE
REQUEST: New membership for @butuzov

### ISSUE THREAD

**Issue by butuzov** [kubernetes/org#1763]
### GitHub Username
@butuzov

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @MaxymVlasov
- @idvoretskyi  

### List of contributions to the Kubernetes project
- PRs reviewed / authored : https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Abutuzov
- Issues responded to : https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Abutuzov+is%3Aclosed
- SIG projects I am involved with: `sig-docs-uk-owners`, `sig-docs-uk-reviews`

**Comment by idvoretskyi** [comment]
+1

**Comment by MaxymVlasov** [comment]
+1

**Comment by mrbobbytables** [comment]
@butuzov - unfortunately @MaxymVlasov cannot sponsor you for membership. =/ Sponsors must be a reviewer or approver according to our [Membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements). Is there someone else that might be able to sponsor you?

**Comment by butuzov** [comment]
That's a pity.
I can request help about sponsorship from the next people:
- @sftim
- @remyleone  

Guys, if you read this I am really sorry I have tagged you without consent.
I hope you remember who am I, and what I did (even if my PR's wasn't something extraordinary). . I want to be a part of the Kubernetes organization in order to help with Ukrainian localization of the website. I can't guarantee I can be online and ready to help 7/24, but I will do my best.

**Comment by remyleone** [comment]
👍

**Comment by remyleone** [comment]
@rekcah78 @rbenzair Can you approve this membership request?

**Comment by sftim** [comment]
Hi @butuzov 

Please check the list of requirements in the issue description - I'm happy to be your sponsor, but also a little concerned that you submitted this request before you're able to tick that list.

**Comment by butuzov** [comment]
Hi @sftim 

Thank you and @remyleone for answering on my call. Can you point what am I missing ( if it's about MaxymVlasov who isn't an owner/reviewer - it's totally my fault as I thought Max and Anastasia already in owners/reviewers list for the Ukrainian language, my fault I didn't confirm it before making PR), as far as I can tell about you - is that you have hawk eye for details I wish I had.
Can you point on what items I missed (except messing with sponsorship)?

Once again thank you!

**Comment by sftim** [comment]
![Requirements](https://user-images.githubusercontent.com/22591623/78178132-13b7a280-7457-11ea-9a80-24dd3e78417f.png)

Reviewers looking at this PR would expect to see each of those items checked, @butuzov. Which ones can you already check off?

**Comment by butuzov** [comment]
1) I have reviewed the community membership guidelines.
2) I have enabled 2FA on my GitHub account (I did it a month ago)
3) I have subscribed to the kubernetes-dev e-mail list ( I am subscribed to it since 27/11/2019)
4) I am actively contributing to 1 or more Kubernetes subprojects. (Am I wrong here?)
5-6) I have spoken to @idvoretskyi and @MaxymVlasov before submitting PR. I have asked @remyleone  and you about support after the discovery of my own fault publicly in the comment. You are two other guys of Kubernetes community I do Respect and Admire. I have spoken to Remy and explained the current situation before asking in chat if he can be my sponsor. I wish i start chat with you and Remy in private before making comment and asking about support. But - mistakes were made =(. 

Anyway, I can say - I can for sure satisfy all requirements. I wish you say "OK" for my application too.

Cheers.

**Comment by mrbobbytables** [comment]
>  it's totally my fault as I thought Max and Anastasia already in owners/reviewers list for the Ukrainian language, my fault I didn't confirm it before making PR)

These things happen fairly often^^:;;; Please don't beat yourself up. It's why we have the [Membership Coordinator role](https://github.com/kubernetes/community/tree/master/github-management#new-membership-coordinator) to help vet and guide folks through the membership process. 👍

**Comment by sftim** [comment]
Let me reiterate that I'm happy to sponsor here.

**Comment by butuzov** [comment]
Thank you Tim!

**Comment by mrbobbytables** [comment]
@butuzov sorry if things got off to the wrong start^^;;;

I've created PR #1769  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
