### ISSUE TITLE
REQUEST: New membership for jianzzha

### ISSUE THREAD

**Issue by jianzzha** [kubernetes/org#1774]
### GitHub Username
@jianzzha

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @klueska
- @derekwaynecarr 

### List of contributions to the Kubernetes project
- PRs authored
https://github.com/kubernetes/kubernetes/pull/89907
https://github.com/kubernetes/kubernetes/pull/83592
https://github.com/kubernetes/website/pull/17648

- PRs reviewed
https://github.com/kubernetes/kubernetes/pull/87532
https://github.com/kubernetes/enhancements/pull/1319
https://github.com/kubernetes/kubernetes/pull/87452

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/85764

- SIG projects I am involved with
SIG-Node

**Comment by mrbobbytables** [comment]
As there has been no traction with this in a month I'm going to flag it as rotten.

/lifecycle rotten

Please remember that you must speak to your sponsors first and get their approval before applying for org membership.

If this is still active, please go ahead and  `/remove-lifecycle rotten`
