### ISSUE TITLE
REQUEST: New membership for @hbagdi

### ISSUE THREAD

**Issue by hbagdi** [kubernetes/org#1778]
### GitHub Username

@hbagdi

### Organization you are requesting membership in

kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @robscott 
- @kbarnard10 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/service-apis/pulls?q=is%3Apr+hbagdi. Actively involved in design discussions.
- Issues responded to
https://github.com/kubernetes-sigs/service-apis/issues?q=is%3Aissue+author%3Ahbagdi+
- SIG projects I am involved with
  - service-apis under SIG Network

**Comment by robscott** [comment]
👍Thanks for all the help with Service APIs + Ingress!

**Comment by kbarnard10** [comment]
Big #1 from me. Excited to officially welcome you to the team!

**Comment by mrbobbytables** [comment]
@hbagdi , thank you for all your contributions so far :)

I've created PR #1782  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by hbagdi** [comment]
Thank you, @mrbobbytables!
