### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for suleisl2000

### ISSUE THREAD

**Issue by suleisl2000** [kubernetes/org#178]
### GitHub Username
@suleisl2000

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@k82cn
@jinzhejz

### List of contributions to the Kubernetes project
   - kube-batch (https://github.com/kubernetes-sigs/kube-batch/commits?author=suleisl2000)

/area github-membership

**Comment by jinzhejz** [comment]
+1

**Comment by k82cn** [comment]
+1

**Comment by k82cn** [comment]
looking forward for your more contribution！

**Comment by justaugustus** [comment]
Hey @suleisl2000, before we can approve your request for membership, you need to be sponsored by at least 2 members of kubernetes orgs. 

@k82cn counts as one, but @jinzhejz is neither in the `kubernetes`, nor the `kubernetes-sigs` org.
Would you be able to find another sponsor?

**Comment by mrbobbytables** [comment]
@justaugustus  I don't believe @jinzhejz has accepted the membership invites yet to the `kubernetes` and `kubernetes-sigs` orgs, but is listed under `kubernetes`, `kubernetes-incubator` and `kubernetes-sigs` in the org configs. @suleisl2000's membership request is related to establishing the new [OWNERS](https://github.com/kubernetes-sigs/kube-batch/blob/master/OWNERS) for the kube-batch (formerly kube-arbitrator) project.

**Comment by jinzhejz** [comment]
accepted done.

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #187 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome (in advance)! :)
/assign
