### ISSUE TITLE
REQUEST: New membership for pjhwa

### ISSUE THREAD

**Issue by pjhwa** [kubernetes/org#1780]
### GitHub Username
@pjhwa

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gochist 
- @seokho-son 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   https://github.com/search?q=org%3Akubernetes+is%3Apr+is%3Amerged+author%3Apjhwa
- Issues responded to
   https://github.com/kubernetes/website/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Apjhwa
- SIG projects I am involved with
   kubernetes/sig-docs

**Comment by gochist** [comment]
+1 Thank you for your contribution in document Korean localization!!!

**Comment by seokho-son** [comment]
+1 Thank you for your contribution.

**Comment by pjhwa** [comment]
@gochist , @seokho-son 
Thank you for your sponsorship! :-)

**Comment by ysyukr** [comment]
+1 welcome to l10n korean team! :smile:

**Comment by pjhwa** [comment]
> +1 welcome to l10n korean team! :smile: 

Thank you very much! @ysyukr

**Comment by nikhita** [comment]
@pjhwa thank you for all your help with Korean localization :)

I've created PR #1789 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by pjhwa** [comment]
Thank you so much, @nikhita !
