### ISSUE TITLE
Repo creation request: kubernetes-sigs/boskos

### ISSUE THREAD

**Issue by ixdy** [kubernetes/org#1783]
### New Repo, Staging Repo, or migrate existing
new repository (will move https://github.com/kubernetes/test-infra/tree/master/boskos into this repository)

### Requested name for new repository
`boskos`

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@ixdy 
@alvaroaleman
@stevekuznetsov

### If not a staging repo, who should have write access
@ixdy 
@alvaroaleman
@stevekuznetsov

### If not a staging repo, who should be listed as approvers in OWNERS
@ixdy 
@alvaroaleman
@stevekuznetsov

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@ixdy 
@alvaroaleman
@stevekuznetsov

### What should the repo description be
Boskos is a resource management service that provides reservation and lifecycle management of a variety of different kinds of resources.

### What SIG and subproject does this fall under in sigs.yaml
This is a spin-off of a sig-testing project from `kubernetes/test-infra`.

### Approvals
I am one of the current approvers of Boskos (per https://raw.githubusercontent.com/kubernetes/test-infra/master/boskos/OWNERS). @krzyzacy and @sebastienvas, the other approvers, have mostly moved on to other projects.

This was discussed at a sig-testing biweekly meeting ([video recording](https://www.youtube.com/watch?v=t8U68wIHjSQ&t=22m25s), [notes](https://docs.google.com/document/d/1z8MQpr_jTwhmjLMUaqQyBk1EYG_Y_3D4y4YdMJ7V1Kk/edit#heading=h.s0n7b8dpnomy)) where I also shared a [doc](https://docs.google.com/document/d/1gjn9BPVt-hR8Yc7SHNLlnTXwcLMhD7FXpmOb23uwcfg/edit#) suggesting this repository move, among other items.

I [emailed](https://groups.google.com/g/kubernetes-sig-testing/c/KfjlilCF9cA/m/PQ4U0Ti3CQAJ) out the proposal at large to sig-testing with a link to the doc and recording.

In general, it seems like everyone has been in favor of moving Boskos into its own repository; this was particularly evident in the sig-testing meeting.

cc'ing sig-testing chairs here to be explicit, though. @fejta @spiffxp @stevekuznetsov 

### Additional context for request
n/a

**Comment by spiffxp** [comment]
/assign @stevekuznetsov @fejta 
To get your thoughts

I'm in favor this

**Comment by fejta** [comment]
No concerns

**Comment by stevekuznetsov** [comment]
+1 from me!

**Comment by spiffxp** [comment]
/close
- created repo following instructions at https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#creating-repositories
- made the teams via https://github.com/kubernetes/org/pull/1788
- updated sigs.yaml via https://github.com/kubernetes/community/pull/4714

@ixdy you should have access to https://github.com/kubernetes-sigs/boskos/settings if you need to do any further configuration
