### ISSUE TITLE
REQUEST: New membership for knverey

### ISSUE THREAD

**Issue by KnVerey** [kubernetes/org#1784]
### GitHub Username
knverey

### Organization you are requesting membership in
kubernetes,kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @soltysh 
- @mortent 

### List of contributions to the Kubernetes project

PRs reviewed/authored:
https://github.com/kubernetes-sigs/kustomize/pull/2009
https://github.com/kubernetes-sigs/kustomize/pull/2048
https://github.com/kubernetes-sigs/kustomize/pull/2002
https://github.com/kubernetes-sigs/cli-utils/pull/19
https://github.com/kubernetes/kubernetes/pull/71117

Issues responded to
https://github.com/kubernetes/kubernetes/issues/82435
https://github.com/kubernetes/kubernetes/issues/60162
https://github.com/kubernetes-sigs/cli-utils/pull/92#discussion_r394654865
https://github.com/kubernetes-sigs/cli-utils/pull/109#pullrequestreview-390438430

SIG projects I am involved with
sig-cli
- kustomize, cli-utils, kubectl

**Comment by mortent** [comment]
+1

**Comment by soltysh** [comment]
:+1:

**Comment by nikhita** [comment]
@KnVerey thank you for all your contributions with sig cli :)

I've created PR #1789 to add you to the Kubernetes and Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! 🎉

/assign
