### ISSUE TITLE
REQUEST: New membership for lex111

### ISSUE THREAD

**Issue by lex111** [kubernetes/org#1787]
### GitHub Username
@lex111

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Potapy4 
- @sftim

### List of contributions to the Kubernetes project
- PRs authored: https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=author%3Alex111

**Comment by sftim** [comment]
I'm happy to sponsor this.

BTW @lex111 [I think] you can tick the boxes in the PR description that you are already meeting.

**Comment by sftim** [comment]
Ah, the checkboxes thing looks like a GitHub bug. If I try a different browser they show as checked.

**Comment by Potapy4** [comment]
+1, I'm good 👍

**Comment by nikhita** [comment]
@lex111 thank you for all your contributions :)

I've created PR #1789 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
