### ISSUE TITLE
Request for owner/admin access to cri-o under kubernetes-sig

### ISSUE THREAD

**Issue by rhatdan** [kubernetes/org#179]
GitHub Username
@rhatdan
@giuseppe

Organization you are requesting membership in
kubernetes-sigs

Requirements
  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
  I have enabled 2FA on my GitHub account (https://github.com/settings/security)
  I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
  I am actively contributing to 1 or more Kubernetes subprojects
  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
Sponsors
@runcom 
@mrunalp 

SIG projects I am involved with
CRI-O

**Comment by mrunalp** [comment]
@spiffxp ptal. @rhatdan and @giuseppe are CRI-O maintainers. Thanks!

**Comment by justaugustus** [comment]
+1 as a sponsor! Thanks for your work on CRI-O! :)

I've opened #185 to add Dan and Giuseppe to `kubernetes-sigs`. 
Once that merges, we can get them the appropriate permissions on https://github.com/kubernetes-sigs/cri-o

**Comment by justaugustus** [comment]
@rhatdan @giuseppe -- I'd also like to see a non Red Hat sponsor, for the sake of company diversity. Can you track one down?

**Comment by vrothberg** [comment]
Consider me (SUSE employee) as a sponsor of @giuseppe and @rhatdan.

**Comment by justaugustus** [comment]
@vrothberg thanks for volunteering! Unfortunately, the additional sponsor would have to be an existing member of a Kubernetes org.

**Comment by sameo** [comment]
@justaugustus Please add me as a sponsor there. I'm part of the kubernetes-incubator org.

**Comment by justaugustus** [comment]
LGTM! Thanks @sameo :)

**Comment by cblecker** [comment]
Noting that this is related to the migration of cri-o: https://github.com/kubernetes/org/issues/60

(Dug into the history of this one)

**Comment by rhatdan** [comment]
Well all of us were members of the kubernetes-incubator and need to move over to kubernetes-sigs.

**Comment by cblecker** [comment]
Closing this as invites have been sent out :)

/close

**Comment by cblecker** [comment]
oh, and I should point out that now that they're members of the org, @mrunalp can add them to https://github.com/orgs/kubernetes-sigs/teams/cri-o-maintainers/members if they need write access :)

**Comment by rhatdan** [comment]
@cblecker I was never added as a member of kubernetes-sigs?

**Comment by cblecker** [comment]
You were invited, but you need to accept the invitation. You can either check your e-mail, or go to https://github.com/kubernetes-sigs to accept it.

**Comment by rhatdan** [comment]
Thanks I must have missed the email, in the flood of emails.  I have now accepted the invite and am in.
