### ISSUE TITLE
REQUEST: New membership for gaurav1086

### ISSUE THREAD

**Issue by gaurav1086** [kubernetes/org#1790]
### GitHub Username
gaurav1086

### Organization you are requesting membership in
kubernetes

### Requirements
- [ y] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [y ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ y] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [y ] I am actively contributing to 1 or more Kubernetes subprojects
- [ y] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [n ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bowei 
- @aojea 
- @tanjunchen 
- @smarterclayton
- @ash2k 
- @neolit123 

### List of contributions to the Kubernetes project
- PRs authored
https://github.com/kubernetes/kubernetes/pull/89870 [Merged]
https://github.com/kubernetes/kubernetes/pull/89979 [Merged]
https://github.com/kubernetes/kubernetes/pull/89979 [open]
https://github.com/kubernetes/kubernetes/pull/89981 [open]
https://github.com/kubernetes/kubernetes/pull/90081 [open]

- Issues responded to
- SIG projects I am involved with

**Comment by neolit123** [comment]
@gaurav1086 we normally request more PRs / activity from contributors before adding them as a member, or at least that is what i've seen.

**Comment by mrbobbytables** [comment]
As there has been no traction with this in a month I'm going to flag it as rotten.

/lifecycle rotten

Please remember that you must speak to your sponsors first and get their approval before applying for org membership.

If this is still active, please go ahead and /remove-lifecycle rotten
