### ISSUE TITLE
Migrate Metacontroller Into A Kubernetes Org

### ISSUE THREAD

**Issue by alaimo** [kubernetes/org#1791]
### New Repo, Staging Repo, or migrate existing
Migrate existing

### Requested name for new repository
metacontroller

### Which Organization should it reside
sig-api-machinery

### If not a staging repo, who should have admin access
@luisdavim, @alaimo, @AmitKumarDas

### If not a staging repo, who should have write access
@luisdavim, @alaimo, @AmitKumarDas

### If not a staging repo, who should be listed as approvers in OWNERS
@luisdavim, @alaimo, @AmitKumarDas

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@luisdavim, @alaimo, @AmitKumarDas

### What should the repo description be
by default we will set it to "created due to (link to this issue)"

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject for sig-api-machinery called metacontroller

### Approvals
Confirmation of approval from @DirectXMan12
https://kubernetes.slack.com/archives/CA0SUPUDP/p1586819887053000

### Additional context for request
Migrate the metacontroller repository at https://github.com/GoogleCloudPlatform/metacontroller to a Kubernetes Org.  Relates to https://github.com/kubernetes/enhancements/pull/1684.

**Comment by mrbobbytables** [comment]
@alaimo It requires sign off from the [SIG api-machinery leads](https://github.com/kubernetes/community/tree/master/sig-api-machinery#leadership) as they would then be responsible for the project. 

/assign @deads2k @fedebongio @lavalamp

**Comment by nikhita** [comment]
@alaimo :wave: Have there been any updates on this?

**Comment by lavalamp** [comment]
Yes, David, Fede, & I met with @alaimo & @AmitKumarDas. I think we're waiting on some AIs before writing that up here.

**Comment by DirectXMan12** [comment]
I think we can close this now

/close

**Comment by DirectXMan12** [comment]
(it was decided to transfer to a standalone org instead)
