### ISSUE TITLE
REQUEST: New membership for LappleApple

### ISSUE THREAD

**Issue by LappleApple** [kubernetes/org#1795]
### GitHub Username
e.g. (at)example_user

### Organization you are requesting membership in
e.g. (at)kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mrbobbytables 
- @onlydole  

### List of contributions to the Kubernetes project
- Issues responded to 
[#4149](https://github.com/kubernetes/community/issues/4149)
[#915](https://github.com/kubernetes/sig-release/issues/915)

- SIG projects I am involved with
Process/Contributor Experience: [#4149](https://github.com/kubernetes/community/issues/4149), [#4289](https://github.com/kubernetes/community/issues/4289), [#3456](https://github.com/kubernetes/community/issues/3456)

**Comment by onlydole** [comment]
A huge +1 from me! Thank you for all your amazing work in the community, @LappleApple 🎉

**Comment by mrbobbytables** [comment]
Oh woops, thought I +1'ed this already 🤦 
ANYWAY - +1 from me :P

**Comment by nzoueidi** [comment]
Hey there @LappleApple, thank you for all your contributions so far :)

I've created PR #1807  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by LappleApple** [comment]
Thanks!
