### ISSUE TITLE
REQUEST: New membership for Zimmertr

### ISSUE THREAD

**Issue by zimmertr** [kubernetes/org#1797]
### GitHub Username
@zimmertr

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @kmova
- @wongma7

### List of contributions to the Kubernetes project
- **Pull Request 1:** https://github.com/kubernetes-incubator/external-storage/pull/1230
- **Pull Request 2:** https://github.com/kubernetes-incubator/external-storage/pull/1215
- **Pull Request 3:** https://github.com/kubernetes/cloud-provider-aws/pull/97
- **Project 1:** https://github.com/zimmertr/TKS
- **Project 2:** https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU
- **Project 3:** https://github.com/zimmertr/Kubernetes-Manifests
- **Project 4:** https://github.com/zimmertr/Bootstrap-Kubernetes-with-LXC
- **Project 5:** https://github.com/zimmertr/Bare_Metal_Kubeadm
- **StackOverflow Answers:** https://stackoverflow.com/users/3066788/tj-zimmerman?tab=answers
- **Related Issue:** https://github.com/ansible/ansible/issues/48402
- **Attended:** KubeCon 2018 & 2019
- **Active:** Member of `kubernetes.slack.com`
- **Professional:** Kubernetes/Cloud Native Infrastructure SME

**Comment by zimmertr** [comment]
Original request made [here](https://github.com/kubernetes/org/issues/1744#issuecomment-604192447) by @kmova. 

Ask to become a community member first made [here](https://github.com/kubernetes/org/issues/1744#issuecomment-604192447).

**Comment by kmova** [comment]
+1

**Comment by nzoueidi** [comment]
Hey @wongma7 do you have a moment to sponsor @zimmertr's org membership?

**Comment by mrbobbytables** [comment]
@zimmertr do you have someone else that might be able to sponsor you?

**Comment by zimmertr** [comment]
Unfortunately no. I had confirmation from @wongma7 via the Kubernetes Slack server that he would sponsor me but it looks like he may have changed his mind. @kmova is the only other developer I'm acquainted with in the Kubernetes community.

I am *very* interested in participating and becoming a developer in SIG Storage. But I do not believe I will be able to acquire another sponsor in a timely fashion.

**Comment by mrbobbytables** [comment]
After chatting in slack, and seeing the image zimmertr posted -- everything should be good sponsorship wise 👍

**Comment by mrbobbytables** [comment]
@zimmertr thanks for being patient with all this, but with everything out of the way :) I've created PR #1894  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by zimmertr** [comment]
Thank you!

**Comment by wongma7** [comment]
Sorry I didn't respond here on GitHub. This is me responding on GitHub just to doubly confirm for what that's worth!
