### ISSUE TITLE
REQUEST: sig-architecture-* teams cleanup

### ISSUE THREAD

**Issue by johnbelamaric** [kubernetes/org#1798]
### Organization or repository
k/k

### Users affected
Various

### Describe the issue
The [sig arch teams](https://github.com/orgs/kubernetes/teams?query=sig-arch) are out-of-date and not managed by Peribolos. I'd like to clean these up. Probably we should move them to managed by Peribolos then we can use a PR to clean them up.

**Comment by justaugustus** [comment]
I can help out here!
/assign

**Comment by justaugustus** [comment]
@johnbelamaric -- to clarify a little:

> Probably we should move them to managed by Peribolos

All lists are actually already managed by Peribolos. You can see the SIG Arch ones here: https://github.com/kubernetes/org/tree/master/config/kubernetes/sig-architecture

[This PR](https://github.com/kubernetes/org/pull/1799) consolidates the groups and does some minor membership updates (just to ensure the SIG Chairs are present everywhere).

/sig architecture
/area github-management

**Comment by johnbelamaric** [comment]
thanks, I was looking in the wrong place
