### ISSUE TITLE
New repo for kubernetes-incubator/external-storage/tree/master/gluster/file

### ISSUE THREAD

**Issue by humblec** [kubernetes/org#1801]
### New Repo, Staging Repo, or migrate existing
 new repository

### Requested name for new repository
 gluster-file-external-provisioner

### Which Organization should it reside
 kubernetes-sigs

### If not a staging repo, who should have admin access

@jsafrane
@msau42
@saad-ali
@xing-yang
### If not a staging repo, who should be listed as approvers in OWNERS
@humblec 
@yuanying
@jsafrane 
@msau42
@saad-ali
@xing-yang

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@jsafrane 
@msau42
@saad-ali
@xing-yang

### What should the repo description be

Gluster File Dynamic Volume Provisioner

### What SIG and subproject does this fall under in sigs.yaml
sig-storage

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

Need sig-storage approval from: @jsafrane, @saad-ali and @xing-yang

See "Create K8s sig projects for Gluster provisioners" in https://docs.google.com/document/d/11zx8i5CfpJUKW4RiHAIBznmuaVkkItS_Mo3NDIFEK4M/edit?usp=sharing
Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

### Additional context for request

kubernetes-incubator/external-storage was marked as deprecated and there is an active proposal to deprecate the https://github.com/kubernetes-incubator/ org. Most of the actively maintained projects in the external-storage repository have been moved out either into kubernetes-sigs org or to specific CSI driver projects.

Creating a kubernetes sig project for the Gluster File Provisioner will provide the users, contributors and maintainers a best neutral home governed by the Kubernetes community guidelines and governance.

/area github-repo
/sig storage

**Comment by humblec** [comment]
@saad-ali @jsafrane @msau42 @xing-yang as discussed here is the proposal for new repo . PTAL .. thanks!

**Comment by xing-yang** [comment]
+1

**Comment by nikhita** [comment]
Created https://github.com/kubernetes-sigs/gluster-file-external-provisioner :+1: 

Also created:

- https://github.com/kubernetes/org/pull/1802 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4725 - to add the repo to sigs.yaml

Once both PRs get merged, we can close this issue.

**Comment by humblec** [comment]
Thanks @nikhita for quick action and help here!

**Comment by nikhita** [comment]
Teams have been set up/granted access and sigs.yaml has been updated.

/close
