### ISSUE TITLE
REQUEST: New membership for yuanying

### ISSUE THREAD

**Issue by yuanying** [kubernetes/org#1804]
### GitHub Username
e.g. @yuanying

### Organization you are requesting membership in
e.g. @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @humblec 
- @nikhita 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/gluster-block-external-provisioner
  - https://github.com/kubernetes-sigs/gluster-file-external-provisioner
- Issues responded to
  - https://github.com/kubernetes-sigs/gluster-block-external-provisioner
  - https://github.com/kubernetes-sigs/gluster-file-external-provisioner
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/gluster-block-external-provisioner
  - https://github.com/kubernetes-sigs/gluster-file-external-provisioner

**Comment by nikhita** [comment]
+1

**Comment by nzoueidi** [comment]
Hey there @yuanying, thank you for all your contributions so far :)

I've created PR #1807  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
