### ISSUE TITLE
Request Netlify site for kubernetes-sigs/vsphere-csi-driver

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/org#1808]
### Repository
https://github.com/kubernetes-sigs/vsphere-csi-driver

### Project domain
vsphere-csi-driver.sigs.k8s.io

NOTE: Must match domain request.
See subproject site request docs for more information:
http://git.k8s.io/community/github-management/subproject-site-requests.md#subproject-domain-request

### Additional context for request
Any additional information or links to discussions regarding the request.

https://github.com/kubernetes/k8s.io/pull/759

**Comment by divyenpatel** [comment]
cc: @mrbobbytables

**Comment by bartsmykla** [comment]
Closing as kubernetes/k8s.io#759 was merged and dns reconciliation done.

/close

**Comment by mrbobbytables** [comment]
/reopen
@bartsmykla this still needs to be resolved on the netlify side

**Comment by bartsmykla** [comment]
Yes, apologies

**Comment by mrbobbytables** [comment]
@divyenpatel please stop spamming requesting the netlify integration through the GH UI. It's something we have to handle.

**Comment by nikhita** [comment]
https://vsphere-csi-driver.sigs.k8s.io/ is live now :)

It might take a while to get HTTPS enabled. Please reopen if you face any issues!
