### ISSUE TITLE
REQUEST: New membership for EppO

### ISSUE THREAD

**Issue by EppO** [kubernetes/org#1811]
### GitHub Username
@EppO

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Miouge1 
- @LuckySB

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pulls?q=author%3AEppO+is%3Apr+is%3Amerged
- Issues responded to
https://github.com/kubernetes-sigs/kubespray/issues/5432
https://github.com/kubernetes-sigs/kubespray/issues/5973#issuecomment-616893417
https://github.com/kubernetes-sigs/kubespray/issues/5940#issuecomment-612479421
https://github.com/kubernetes-sigs/kubespray/issues/5134#issuecomment-545585827
https://github.com/kubernetes-sigs/kubespray/issues/5694#issuecomment-595826706
https://github.com/kubernetes-sigs/kubespray/pull/5150#discussion_r322751806
- SIG projects I am involved with
https://github.com/kubernetes-sigs/kubespray

**Comment by LuckySB** [comment]
Happy to be sponsor

**Comment by Miouge1** [comment]
+1

**Comment by mrbobbytables** [comment]
@EppO, thank you for all your help with kubespray :)

I've created PR #1836  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
