### ISSUE TITLE
archive kubernetes/kubernetes-anywhere

### ISSUE THREAD

**Issue by neolit123** [kubernetes/org#1812]
### Repository to archive
https://github.com/kubernetes/kubernetes-anywhere

### Repository and/or sig subproject owners that are approving this archival
/sig cluster-lifecycle
@neolit123 
(i'm an admin for that repository)

### When should this be done
Anytime.

### Additional context for request
- the project has been deprecated [since Dec 2018](https://github.com/kubernetes/kubernetes-anywhere/commit/494d171d0b674)
- it is no longer referenced in e2e-test jobs, although there is still [some residue](https://github.com/kubernetes/test-infra/pull/17313) which is going to be cleaned out of sync.

**Comment by nikhita** [comment]
@neolit123 IIUC the repo needs to be archived after https://github.com/kubernetes/test-infra/pull/17313 gets merged, right?

**Comment by neolit123** [comment]
nope, not required. the code that mentions "kubernetes-anywhere" is not used.

**Comment by nikhita** [comment]
@neolit123 ah right!

/assign

**Comment by nikhita** [comment]
The repo has been archived - https://github.com/kubernetes-retired/kubernetes-anywhere

Once https://github.com/kubernetes/org/pull/1813 and https://github.com/kubernetes/community/pull/4735, we can close this issue.

**Comment by nikhita** [comment]
Also announced on the k-dev mailing list - https://groups.google.com/forum/#!topic/kubernetes-dev/no7pQ3YxmKA

**Comment by neolit123** [comment]
thanks @nikhita

**Comment by nikhita** [comment]
#1813 and kubernetes/community#4735 have merged

/close
