### ISSUE TITLE
REQUEST: New membership for joao-luna-98

### ISSUE THREAD

**Issue by joao-luna-98** [kubernetes/org#1818]
### GitHub Username
@joao-luna-98

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @femrtnz
- @devlware

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - kubernetes/website#20235
  - kubernetes/website#19805
  - kubernetes/website#20083
- Issues responded to
  - kubernetes/website#13939

Involved in the localization effort.

**Comment by devlware** [comment]
+1 @joao-luna-98 is helping us with the Portuguese translations :)

**Comment by femrtnz** [comment]
Approved!  @joao-luna-98 is helping us with the Portuguese translations

cc @mrbobbytables

**Comment by nzoueidi** [comment]
Hey there @joao-luna-98, thank you for all your contributions so far :)

I've created PR #1842  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
