### ISSUE TITLE
REQUEST: New membership for divya-mohan0209

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/org#1821]
### GitHub Username
@divya-mohan0209

### Organization you are requesting membership in
@kubernetes

### Requirements
- [&#x2611;] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [&#x2611;] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [&#x2611;] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [&#x2611;] I am actively contributing to 1 or more Kubernetes subprojects
- [&#x2611;] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [&#x2611;] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @savitharaghunathan 
- @onlydole 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
1. Signposting added in /docs/home to redirect users to /training #19592
2. Updated service.md #19539
3. removed 'big data' from sig list on gov doc #4579
4. Update content in intermediate.md #19524
5. Added date metadata to blog articles #19503 #19523
- Issues responded to
- SIG projects I am involved with
1. SIG Release

**Comment by savitharaghunathan** [comment]
+1 for @divya-mohan0209 :) She has been working actively on improving website documentation and also a member of 1.19 release team.

**Comment by onlydole** [comment]
+1 for @divya-mohan0209 too!!! Welcome to the 1.19 Release Team!

**Comment by mrbobbytables** [comment]
@divya-mohan0209 thanks for helping with the 1.19 release \o/

I've created PR #1836  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
