### ISSUE TITLE
Migrate kubernetes-incubator/cluster-proportional*-autoscaler to kubernetes-sigs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/org#1823]
### New Repo, Staging Repo, or migrate existing
Migrate existing

### From
- https://github.com/kubernetes-incubator/cluster-proportional-autoscaler
- https://github.com/kubernetes-incubator/cluster-proportional-vertical-autoscaler

### To
- https://github.com/kubernetes-sigs/cluster-proportional-autoscaler
- https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler

### If not a staging repo, who should have admin access
@bowei 
@dnardo 
@MrHohn 
@thockin 

### If not a staging repo, who should have write access
same as above

### If not a staging repo, who should be listed as approvers in OWNERS
use existing

### If not a staging repo, who should be listed in SECURITY_CONTACTS
use existing

### What should the repo description be
use existing

### What SIG and subproject does this fall under in sigs.yaml
sig-network/cluster-proportional*-autoscaler

### Approvals
/cc @thockin 

### Additional context for request
This is part of https://github.com/kubernetes/community/issues/1922#issuecomment-516974448

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by spiffxp** [comment]
Creating teams prior to move: https://github.com/kubernetes/org/pull/1824
Update sigs.yaml after move: https://github.com/kubernetes/community/pull/4738

**Comment by spiffxp** [comment]
Transferred https://github.com/kubernetes-sigs/cluster-proportional-autoscaler
Removed collaborators
Added teams

**Comment by spiffxp** [comment]
Transferred https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler
Removed collaborators
Added teams
Added k8s-sig-network topic

**Comment by spiffxp** [comment]
/close
This has been finished
