### ISSUE TITLE
REQUEST: New membership for @wilsonehusin

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/org#1825]
### GitHub Username
@wilsonehusin

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @puerco 
- @onlydole 

### List of contributions to the Kubernetes project
- SIG Release 1.19 shadow program

**Comment by onlydole** [comment]
+1 to this request! Welcome to the 1.19 Release Team, @wilsonehusin 👏

**Comment by puerco** [comment]
+1 welcome to the release notes team @wilsonehusin  :)

**Comment by mrbobbytables** [comment]
@wilsonehusin thanks for helping with the 1.19 release \o/

I've created PR #1836  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
