### ISSUE TITLE
REQUEST: New membership for @zestrells

### ISSUE THREAD

**Issue by zestrells** [kubernetes/org#1826]
### GitHub Username
@zestrells

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @savitharaghunathan
- @onlydole

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/community/pull/4609
https://github.com/kubernetes/community/issues/4109
https://github.com/kubernetes/website/pull/19622

- SIG projects I am involved with
Sig Release 1.19 Shadow Team

**Comment by onlydole** [comment]
+1 to @zestrells and welcome to the 1.19 release team!

**Comment by savitharaghunathan** [comment]
+1 to @zestrells 🎉

**Comment by mrbobbytables** [comment]
@zestrells  thanks for helping with the 1.19 release \o/

I've created PR #1836  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
