### ISSUE TITLE
REQUEST: New membership for desaintmartin

### ISSUE THREAD

**Issue by desaintmartin** [kubernetes/org#1829]
### GitHub Username
@desaintmartin

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @maciaszczykm
- @floreks

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/68012
  - https://github.com/kubernetes/kubernetes/pull/70376
  - https://github.com/kubernetes/kubernetes/pull/63369
  - https://github.com/kubernetes/kubernetes/pull/73629
  - https://github.com/kubernetes/kubernetes/pull/71252
  - https://github.com/kubernetes/website/pull/12660
  - https://github.com/kubernetes/website/pull/12658
  - https://github.com/kubernetes/dashboard/pull/4502
  - https://github.com/kubernetes/kubernetes/pull/89415
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/52444
  - https://github.com/kubernetes/kubernetes/issues/73887
- SIG projects I am involved with
  - SIG-ui
- Other subprojects:
  - kubespray
  - sig-docs (french translation)

**Comment by floreks** [comment]
+1 from me

**Comment by maciaszczykm** [comment]
+1

**Comment by nzoueidi** [comment]
@desaintmartin both sponsors @floreks and @maciaszczykm are from loodse and while the requirements are to have two sponsors from different companies. Take a look here and let me know if you need any help: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by jeefy** [comment]
+1 from me

**Comment by desaintmartin** [comment]
@nzoueidi Indeed, it makes sense. Could you consider @jeefy for the second sponsor?

**Comment by nzoueidi** [comment]
Hey there @desaintmartin, sure thing.

Tank you for all your contributions so far :)

I've created PR #1850 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
