### ISSUE TITLE
REQUEST: New membership for @RobertKielty

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/org#1830]
### GitHub Username
@RobertKielty

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hasheddan 
- @onlydole 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/88364
https://github.com/kubernetes/kubernetes/pull/78171
https://github.com/kubernetes/kubernetes/issues/78168

- SIG projects I am involved with
ContribEx
https://github.com/kubernetes/community/pull/4563
https://github.com/kubernetes/community/issues/4446

**Comment by onlydole** [comment]
+1 to @RobertKielty and I’m excited to have you on the 1.19 release team!

**Comment by hasheddan** [comment]
+1 from me! :tada: 

@RobertKielty could you update the issue title to your GH username? :)

**Comment by mrbobbytables** [comment]
@RobertKielty I thought you were a member already :P 
ANYWAY, that's getting taken care of now with #1836 :)
When that gets merged you'll get a membership invite notification.

Welcome to Kubernetes 🎉 

/assign
/honk
/pony yay
