### ISSUE TITLE
REQUEST: New membership for AGMETEOR

### ISSUE THREAD

**Issue by AGMETEOR** [kubernetes/org#1832]
### GitHub Username
AGMETEOR

### Organization you are requesting membership in
Kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- Taylor Dolezal (@onlydole )
- Adolfo Garcia (@puerco)

### List of contributions to the Kubernetes project
- [PRs authored](https://github.com/pulls?q=is%3Apr+author%3AAGMETEOR+archived%3Afalse+is%3Aclosed+kubernetes)
- Kubernetes 1.19 Shadow Program (Release Notes)

**Comment by puerco** [comment]
+1 Welcome to the release notes team @AGMETEOR  !

**Comment by onlydole** [comment]
+1 to @AGMETEOR and I’m stoked to have you working with us on 1.19 🙌🏼

**Comment by mrbobbytables** [comment]
@AGMETEOR happy to see you on the release team :)

I've created PR #1836  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
