### ISSUE TITLE
REQUEST: New membership for phanimarupaka

### ISSUE THREAD

**Issue by phanimarupaka** [kubernetes/org#1833]
### GitHub Username
phanimarupaka

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @monopole
- @brianpursley
- @mortent
### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kustomize/pull/2354
https://github.com/kubernetes/kubernetes/pull/88737
https://github.com/kubernetes-sigs/kustomize/pull/2343
https://github.com/kubernetes-sigs/kustomize/pull/2320
https://github.com/kubernetes-sigs/cli-utils/pull/16
https://github.com/kubernetes-sigs/cli-utils/pull/28
https://github.com/kubernetes-sigs/cli-utils/pull/41
https://github.com/kubernetes-sigs/kustomize/pull/2265
https://github.com/kubernetes-sigs/kustomize/pull/2287
https://github.com/kubernetes-sigs/kustomize/pull/2199

- Issues responded to
https://github.com/kubernetes-sigs/kustomize/issues/2351
https://github.com/kubernetes-sigs/cli-utils/issues/75
https://github.com/kubernetes-sigs/cli-utils/issues/76

- SIG projects I am involved with
https://github.com/kubernetes-sigs/kustomize/
https://github.com/kubernetes-sigs/cli-utils/

**Comment by mortent** [comment]
+1

**Comment by brianpursley** [comment]
+1

**Comment by mrbobbytables** [comment]
@phanimarupaka, thank you for all your help with sig-cli :)

I've created PR #1836  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
