### ISSUE TITLE
REQUEST: New membership for hkamel

### ISSUE THREAD

**Issue by hkamel** [kubernetes/org#1834]
### GitHub Username
@hkamel

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @onlydole 
- @hasheddan 

### List of contributions to the Kubernetes project
- SIG projects I am involved with: 
   - [sig-release](https://github.com/kubernetes/sig-release) for kubernetes 1.19 (CI Signal Team for [https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/release_team.md](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/release_team.md) )

**Comment by hasheddan** [comment]
+1 welcome @hkamel! :tada:

**Comment by onlydole** [comment]
+1 for @hkamel and welcome to the 1.19 release team!

**Comment by mrbobbytables** [comment]
@hkamel thanks for helping with the 1.19 release \o/

I've created PR #1836 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
