### ISSUE TITLE
REQUEST: New membership for @mikejoh

### ISSUE THREAD

**Issue by mikejoh** [kubernetes/org#1835]
### GitHub Username
@mikejoh

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @savitharaghunathan 
- @onlydole 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
https://github.com/kubernetes/website/pull/20178
https://github.com/kubernetes/cloud-provider-openstack/pull/1008
https://github.com/kubernetes/cloud-provider-openstack/pull/950

- Issues responded to:
https://github.com/kubernetes/cloud-provider-openstack/issues/754

- SIG projects I am involved with:
SIG Release 1.19 Shadow Team (Docs)

**Comment by onlydole** [comment]
+1 to @mikejoh - I’m looking forward to working with you on 1.19 :smile:

**Comment by mrbobbytables** [comment]
+1 thanks for helping with 1.19 :)

**Comment by mrbobbytables** [comment]
@mikejoh thanks for helping with the 1.19 release \o/

I've created PR #1836 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by mikejoh** [comment]
@mrbobbytables Awesome, thanks!

**Comment by savitharaghunathan** [comment]
+1 to @mikejoh 🎉  Thank you @onlydole & @mrbobbytables for the sponsorship :)
