### ISSUE TITLE
REQUEST: New membership for bai

### ISSUE THREAD

**Issue by bai** [kubernetes/org#1838]
### GitHub Username
@bai

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gianarb 
- @onlydole 

### List of contributions to the Kubernetes project
- sig-release for kubernetes 1.19 (Bug Triage Team for https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/release_team.md)

**Comment by onlydole** [comment]
+1 to @bai and welcome to the 1.19 release team!

**Comment by mrbobbytables** [comment]
+1 thanks for helping with the 1.19 release :)

**Comment by mrbobbytables** [comment]
@bai thanks for joining the 1.19 release team \o/

I've created PR #1866   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by bai** [comment]
Thanks for having me, pleasure to be here 💯
