### ISSUE TITLE
REQUEST: New membership for msedzins

### ISSUE THREAD

**Issue by msedzins** [kubernetes/org#1840]
### GitHub Username
@msedzins

### Organization you are requesting membership in
Kubernetes Org

### Requirements
- [ X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ X] I am actively contributing to 1 or more Kubernetes subprojects
- [ X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @palnabarun 
- @onlydole 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
SIG-release.
I'm part of the Release Team as an enhancements shadow:
 https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/release_team.md

**Comment by palnabarun** [comment]
+1 from the 1.19 Enhancements Lead.

Welcome @msedzins to the team and the community. :fireworks:

**Comment by onlydole** [comment]
+1 to @msedzins and welcome to the 1.19 release team!

**Comment by nzoueidi** [comment]
Hey there @msedzins, thank you for all your contributions so far :)

I've created PR #1842  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
