### ISSUE TITLE
REQUEST: New membership for @tlereste

### ISSUE THREAD

**Issue by tlereste** [kubernetes/org#1841]
### GitHub Username
@tlereste

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lilic 
- @tariq1890 

### List of contributions to the Kubernetes project
- PRs authored
https://github.com/kubernetes/kubernetes/pull/82332
https://github.com/kubernetes-sigs/krew/pull/539
https://github.com/kubernetes-sigs/krew-index/pull/529
https://github.com/kubernetes/kube-state-metrics/pull/1045
https://github.com/kubernetes/kube-state-metrics/pull/1003
https://github.com/kubernetes/kube-state-metrics/pull/1049
https://github.com/kubernetes/kube-state-metrics/pull/1016
https://github.com/kubernetes/kube-state-metrics/pull/1128
https://github.com/kubernetes/kube-state-metrics/pull/1129

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/88808
https://github.com/kubernetes/kubernetes/issues/90055
https://github.com/kubernetes/kube-state-metrics/issues/1127
https://github.com/kubernetes/kube-state-metrics/issues/1007

- SIG projects I am involved with
kube-state-metrics (SIG instrumentation)

**Comment by tariq1890** [comment]
+1 :)

**Comment by lilic** [comment]
👍 +1 from me as well! :)

**Comment by nzoueidi** [comment]
Hey there @tlereste, thank you for all your contributions so far :)

I've created PR #1850 to add you to the Kubernetes & Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
