### ISSUE TITLE
REQUEST: New membership for @Joseph-Irving

### ISSUE THREAD

**Issue by Joseph-Irving** [kubernetes/org#1843]
### GitHub Username
@Joseph-Irving
### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mrbobbytables 
- @alejandrox1 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  VPA fix https://github.com/kubernetes/autoscaler/pull/2275 - co-authored
  A number of KEP related [PRs](https://github.com/kubernetes/enhancements/pulls?q=+is%3Apr+author%3AJoseph-Irving+)
   Sidecar PR https://github.com/kubernetes/kubernetes/pull/80744
- Issues responded to
   Sidecars KEP https://github.com/kubernetes/enhancements/issues/753
   
- SIG projects I am involved with
  Sig-node/apps  [Sidecar Containers](https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md)

**Comment by mrbobbytables** [comment]
+1 from sponsor 👍

**Comment by alejandrox1** [comment]
Huge +1 !
Thank you for all the work you have done @Joseph-Irving !

**Comment by nzoueidi** [comment]
Hey there @Joseph-Irving, thank you for all your contributions so far :)

I've created PR #1850 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
