### ISSUE TITLE
REQUEST: New membership for kbruner

### ISSUE THREAD

**Issue by kbruner** [kubernetes/org#1844]
### GitHub Username
@kbruner

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gianarb
- @onlydole

### List of contributions to the Kubernetes project
- Shadow to bug triage group for 1.19
- Author of multiple blog posts and talks about the Kubernetes ecosystem. List at https://nightmarebeforedevops.wordpress.com/external-posts-and-other-content/

**Comment by onlydole** [comment]
+1 to @kbruner and welcome to the 1.19 Release Team!

**Comment by mrbobbytables** [comment]
+1 thanks for helping with the 1.19 release :)

**Comment by mrbobbytables** [comment]
thanks for joining the 1.19 release team \o/

I've created PR #1866   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by kbruner** [comment]
Thanks, all!
