### ISSUE TITLE
REQUEST: New membership for jrsapi

### ISSUE THREAD

**Issue by jrsapi** [kubernetes/org#1847]
### GitHub Username
@jrsapi

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mkorbi
- @onlydole 

### List of contributions to the Kubernetes project
- Privileged to be a comms-shadow for the Kubernetes 1.19 release team.

**Comment by mkorbi** [comment]
Great to have you in the tram!
/lgtm

**Comment by mrbobbytables** [comment]
+1 thanks for helping with the 1.19 release :)

**Comment by onlydole** [comment]
+1 to @jrsapi and welcome to the 1.19 team!

**Comment by mrbobbytables** [comment]
@jrsapi  thanks for joining the 1.19 release team \o/

I've created PR #1866   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
