### ISSUE TITLE
REQUEST: New membership for MoShitrit

### ISSUE THREAD

**Issue by MoShitrit** [kubernetes/org#1849]
### GitHub Username
@MoShitrit

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rifelpet 
- @mikesplain 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kops/pull/9021
https://github.com/kubernetes/kops/pull/8987
https://github.com/kubernetes/kops/pull/8974

- Issues responded to
https://github.com/kubernetes/kops/issues/9031
https://github.com/kubernetes/kops/issues/8995

- SIG projects I am involved with
sig-cluster-lifecycle/kops

**Comment by mikesplain** [comment]
+1 Thanks for your contributions! Looking forward to working with you!

**Comment by rifelpet** [comment]
+1 Thank you and welcome!

**Comment by nzoueidi** [comment]
Hey there @MoShitrit, thank you for all your contributions so far :)

I've created PR #1850 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by MoShitrit** [comment]
Thank you all so much!! @rifelpet @mikesplain @nzoueidi
