### ISSUE TITLE
REQUEST: New membership for ariscahyadi

### ISSUE THREAD

**Issue by ariscahyadi** [kubernetes/org#1851]
### GitHub Username
@ariscahyadi

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @girikuncoro 
- @irvifa 

### List of contributions to the Kubernetes project
- Joined SIG-DOCS-ID activity to translate the Kubernetes documentation to Bahasa Indonesia
- I have 12 PRs in Kubernetes website repository (9 are closed, 3 are still opened) - PR [#19799](https://github.com/kubernetes/website/pull/19799), [#19815](https://github.com/kubernetes/website/pull/19815), [#19875](https://github.com/kubernetes/website/pull/19875), [#19909](https://github.com/kubernetes/website/pull/19909), [#20106](https://github.com/kubernetes/website/pull/20106), [#20195](https://github.com/kubernetes/website/pull/20195), [#20229](https://github.com/kubernetes/website/pull/20229), [#20240](https://github.com/kubernetes/website/pull/20240), [#20261](https://github.com/kubernetes/website/pull/20261), [#20266](https://github.com/kubernetes/website/pull/20266), [#20500](https://github.com/kubernetes/website/pull/20500), [#20588](https://github.com/kubernetes/website/pull/20588)
- I have one talk in Kubernetes Indonesia Meetup https://www.youtube.com/watch?v=8BUc6E6aM_E

**Comment by girikuncoro** [comment]
+1
@ariscahyadi has been instrumental in the successful of current kubernetes.io/id localization milestone, he helped SIG Docs localizing 12 pages into Bahasa Indonesia (which now have 7,000 views per month) 

Welcome to kubernetes org!

**Comment by wahyuoi** [comment]
+1

@ariscahyadi helps us a lot, translate dozen of pages within a month.

Welcome @ariscahyadi 🎉

**Comment by mrbobbytables** [comment]
@ariscahyadi unfortunately @wahyuoi cannot sponsor you for org membership. :( A sponsor must be an approver or reviewer per the [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md). Is there someone else that might be able to sponsor you?

**Comment by wahyuoi** [comment]
Hi @mrbobbytables, based on https://github.com/kubernetes/org/pull/1754, I already put my name as sig-docs-id reviewer.

**Comment by mrbobbytables** [comment]
@wahyuoi team membership is different from being an approver or reviewer -- Here are the current id localization reviewer/approvers.

https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L122-L127

**Comment by wahyuoi** [comment]
i see, thank you @mrbobbytables to point this out. :bow: 
@irvifa please help to sponsor @ariscahyadi :pray:

**Comment by irvifa** [comment]
+1 from me as well 🙂

**Comment by idealhack** [comment]
@ariscahyadi thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/1876 to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
