### ISSUE TITLE
ask to create sig-windows-samples repo in kubernetes-sigs

### ISSUE THREAD

**Issue by michmike** [kubernetes/org#1853]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
sig-windows-samples

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
michmike, marosset

### If not a staging repo, who should have write access
michmike, marosset

### If not a staging repo, who should be listed as approvers in OWNERS
michmike, marosset

### If not a staging repo, who should be listed in SECURITY_CONTACTS
michmike, marosset

### What should the repo description be
Repository for samples and examples related to the sig-windows charter in Kubernetes. 

### What SIG and subproject does this fall under in sigs.yaml
This is a new repo for SIG-Windows.

### Approvals
Mark and I are the sig co-chairs

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
Any additional information or context to describe the request.

**Comment by nikhita** [comment]
@michmike Sorry for the delayed response! From the [SIG Windows meeting notes (5/5/2020)](https://docs.google.com/document/d/1Tjxzjjuy4SQsFSUVXZbvqVb64hjNAG5CQX8bK7Yda9w/edit#), it mentions that this repo will contain code migrated from https://github.com/PatrickLang/fabrikamfiber.

We have different requirements for repo migration vs starting a new repo from scratch - https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories. Can you clarify if this repo will contain migrated code? Thanks!

**Comment by michmike** [comment]
@nikhita , this repo would contain both new samples as well as existing samples that sig-windows is creating (or has created). Patrick was the sig-windows lead in the past and created that work as part of sig-windows. since there was no repo to put them, he used his own account.

**Comment by PatrickLang** [comment]
Hi @nikhita - that repo has many samples in it that I don't want to migrate because they're out of date or superceded by other docs. Our goal here is to bring in just the portions that are still relevant rather than the full repo.

**Comment by nikhita** [comment]
@michmike @PatrickLang thanks for the context! I have created the repo - https://github.com/kubernetes-sigs/sig-windows-samples :)

Also created:
- https://github.com/kubernetes/org/pull/1870 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4769 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by michmike** [comment]
thank you!

**Comment by nikhita** [comment]
Teams have been granted access and sigs.yaml has been updated

/close
