### ISSUE TITLE
REQUEST: New membership for cloudmelon

### ISSUE THREAD

**Issue by cloudmelon** [kubernetes/org#1854]
### GitHub Username
cloudmelon

https://github.com/cloudmelon

### Organization you are requesting membership in
kubernetes-sigs/multi-tenancy

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- (at)sponsor-1
- (at)sponsor-2

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with : multi-tenancy

**Comment by mrbobbytables** [comment]
@cloudmelon do you have anyone that could sponsor you? Usually org requests are created once all the requirements have been met 😬

**Comment by cloudmelon** [comment]
Hi Rob,

Could you bring more clarity about how we define the sponsor ? I work for Microsoft. Happy to represent my company to be part of the community. 

Best wishes from the UK
Melony

**Comment by mrbobbytables** [comment]
@cloudmelon sponsors must be a reviewer or approver in an owners file within the org you're seeking membership. They should be people you've worked closely with in the project so far, e.g. reviewed a few PRs you've contributed to the project. 

For a bit more information, please see our [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#member)

**Comment by cloudmelon** [comment]
Hi Rob,  Thanks for pointing me in the right direction, let me know if I
understood correctly :  Sponsors must be one of the people in OWNERs file:
https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md
,
however I can see only 13 people have contributed on this repo ?  Do you
know where can I find a list of people so I could know if have any peers at
MS could sponsor me. I am very keen to be part of contributors. Thanks ☺

**Comment by mrbobbytables** [comment]
> I am very keen to be part of contributors.

You don't have to be a member to contribute -- Getting some PRs in is usually the first step of climbing the contributor ladder :) (becoming a member) I'd suggest starting with reading our [contributor guide](https://github.com/kubernetes/community/blob/master/contributors/guide/README.md).

> Do you know where can I find a list of people so I could know if have any peers at MS could sponsor me. 
 
The sponsors are the people you worth with in the project, they aren't really tied to your employer. Most of the time they're the owners that have reviewed/approved some of your initial PRs.

**Comment by mrbobbytables** [comment]
Im going to go ahead and close this out. When you're ready, please reopen or create a new issue. 👍 

/close
