### ISSUE TITLE
REQUEST: New membership for kendallroden

### ISSUE THREAD

**Issue by kendallroden** [kubernetes/org#1855]
### GitHub Username
@kendallroden

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mkorbi 
- @onlydole 

### List of contributions to the Kubernetes project
- Communications team shadow for K8s 1.19 Release
- Member of Azure SIG

**Comment by mkorbi** [comment]
Yeah! Welcome it team :) 
/lgtm

**Comment by mrbobbytables** [comment]
+1 thanks for helping with the 1.19 release :)

**Comment by mrbobbytables** [comment]
@kendallroden  thanks for joining the 1.19 release team \o/

I've created PR #1866   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by kendallroden** [comment]
@mrbobbytables so strange but I must have missed the email that this went through. I just tried to join and it expired. Think you can assist? Sorry again :(

**Comment by mrbobbytables** [comment]
You should get an invite the next time peribolos runs its sync (every 24hrs or next merge). 👍
