### ISSUE TITLE
Netlify site request for kubernetes/cloud-provider-aws

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/org#1856]
### Repository
kubernetes/cloud-provider-aws

### Project domain
cloud-provider-aws.sigs.k8s.io

### Additional context for request
Docs site is currently WIP but we added the initial gitbooks configuration setup in https://github.com/kubernetes/cloud-provider-aws/pull/94. We would like the site up and running so we can check it as we iterate on the docs. 

ref: https://github.com/kubernetes/cloud-provider-aws/pull/94 https://github.com/kubernetes/cloud-provider-aws/issues/42

**Comment by andrewsykim** [comment]
DNS request: https://github.com/kubernetes/k8s.io/pull/837

**Comment by mrbobbytables** [comment]
It's been configured for `kubernetes-sigs-cloud-provider-aws.netlify.app` With the current netlify config defined in the repo it forces the redirect to the cloud-provider.aws.sigs.k8s.io dns name and can't be previewed. Once the DNS request is merged I can finish configuration 👍

**Comment by andrewsykim** [comment]
@mrbobbytables looks like the DNS request went through, is there anything else that needs to happen?

**Comment by mrbobbytables** [comment]
Ive configured the dns side in netlify 👍 a lets encrypt cert should be provisioned for it soon.

**Comment by mrbobbytables** [comment]
I finished configuring it in netlify :) everything should be good to go 👍 

https://cloud-provider-aws.sigs.k8s.io/

With that, Im going to go ahead and close this out for now. If you need anything else, please feel free to ping me directly. 

/close

**Comment by andrewsykim** [comment]
Thank you @mrbobbytables
