### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for Markthink

### ISSUE THREAD

**Issue by markthink** [kubernetes/org#186]
### GitHub Username
@markthink

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @idealhack 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amarkthink+archived%3Afalse+is%3Aclosed+
- Issues responded to
https://github.com/kubernetes/website/pull/10683
- SIG projects I am involved with
kubernetes-sigs/application

/area github-membership

**Comment by idealhack** [comment]
+1

**Comment by markthink** [comment]
+1

**Comment by idealhack** [comment]
@markthink apparently you can't sponsor yourself 😅 let's see if @zacharysarah can respond here.

**Comment by idealhack** [comment]
@markthink I thought you want to require membership for `kubernetes` instead of `kubernetes-sigs`? And you should finish the requirements checklist.

**Comment by zacharysarah** [comment]
@markthink 👋 Please make the following changes:

### 1. Organization you are requesting membership in

Please specify `kubernetes` instead of `kubernetes-sigs`.

### 2. Requirements

Please check the boxes once you've verified that you meet the requirements. You can check boxes for completed requirements by updating the Markdown in the original description. For example, this markdown:

```markdown
- [x] I am actively contributing to 1 or more Kubernetes subprojects
```

produces this output:

> - [x] I am actively contributing to 1 or more Kubernetes subprojects

### 3. Sponsors

Please update this section to list myself (@zacharysarah) and @idealhack as your sponsors.

**Comment by markthink** [comment]
@zacharysarah thank you very much for your reply. Is this compliant?

**Comment by zacharysarah** [comment]
@markthink Yes, thanks for the updates.

+1

**Comment by mrbobbytables** [comment]
Hey there @markthink, thank you for all your contributions so far :)

I've created PR #192  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by brucehex** [comment]
@mrbobbytables thanks 🎉

**Comment by markthink** [comment]
@mrbobbytables thanks 🎉
