### ISSUE TITLE
REQUEST: New membership for <Riaankl>

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/org#1861]
### GitHub Username
@Riaankl

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hh 
- @johnbelamaric
### List of contributions to the Kubernetes project
- Issue and PR tracking for ii.coop
- Follow-up topics on the conformance-definition dashboard
- SIG Architecture, sub project Conformance Definition

**Comment by hh** [comment]
@Riaankl is helping to manage @ii conformance tickets and PRs:

https://github.com/orgs/kubernetes/projects/9?card_filter_query=author%3Ariaankl

/approve
/assign
/assign @johnbelamaric

**Comment by mrbobbytables** [comment]
@Riaankl , thank you for all your contributions so far :)

I've created PR # 1866 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
