### ISSUE TITLE
REQUEST: New membership for @ytsarev

### ISSUE THREAD

**Issue by Raffo** [kubernetes/org#1863]
### GitHub Username
@ytsarev

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Raffo 
- @njuettner 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/external-dns/pulls?q=is%3Apr+ytsarev+is%3Aclosed

**Comment by Raffo** [comment]
I checked the checklist on behalf of @ytsarev who confirmed me that reviewed all the items above. I took care of creating this issue a part of https://github.com/kubernetes-sigs/external-dns/issues/1558

**Comment by njuettner** [comment]
Welcome 🙂

**Comment by idealhack** [comment]
@ytsarev thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/1876 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
