### ISSUE TITLE
REQUEST: New membership for @ sheerun

### ISSUE THREAD

**Issue by Raffo** [kubernetes/org#1864]
### GitHub Username
@ sheerun

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Raffo 
- @njuettner 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/external-dns/pulls?q=is%3Apr+sheerun+is%3Aclosed+

**Comment by mrbobbytables** [comment]
/assign @sheerun
If you can please ack the items on the list 👍

**Comment by sheerun** [comment]
I confirm everything. I currently contribute to external-dns's cloudflare provider. I haven't confirmed directly with @njuettner that he agrees to be my sponsor, but I assume that @Raffo had.

**Comment by Raffo** [comment]
Checked the items on the checklist. @njuettner is up to speed with the plan 👍

**Comment by njuettner** [comment]
Welcome 🙂

**Comment by sheerun** [comment]
thank you :)

**Comment by idealhack** [comment]
@sheerun thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/1876 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
