### ISSUE TITLE
Create repository for csi-driver-smb as a kubernetes-csi subproject

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/org#1867]
### New Repo, Staging Repo, or migrate existing
Migrate https://github.com/csi-driver/csi-driver-smb to https://github.com/kubernetes-csi/csi-driver-smb

### Requested name for new repository
csi-driver-smb

### Which Organization should it reside
https://github.com/kubernetes-csi

### If not a staging repo, who should have admin access
andyzhangx, saad-ali , msau42 , jsafrane , xing-yang

### If not a staging repo, who should have write access
@andyzhangx
@msau42 
@jingxu97 

### If not a staging repo, who should be listed as approvers in OWNERS
@andyzhangx
@msau42 
@jingxu97 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
saad-ali , msau42 , jsafrane , xing-yang

### What should the repo description be
This driver allows Kubernetes to use SMB CSI volume, the driver works on both Linux and Windows nodes

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject for sig-storage called csi-driver-smb

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
Any additional information or context to describe the request.
details could be found here: https://github.com/kubernetes/kubernetes/issues/56005

cc @kubernetes/steering-committee

**Comment by nikhita** [comment]
Needs approval from sig-storage leads:

/assign @xing-yang @saad-ali @msau42 @jsafrane

**Comment by xing-yang** [comment]
I think sig-storage-leads should have admin access and be listed as SECURITY_CONTACTS.  Other than that, this looks good to me.

**Comment by andyzhangx** [comment]
> I think sig-storage-leads should have admin access and be listed as SECURITY_CONTACTS. Other than that, this looks good to me.

added as following:
### If not a staging repo, who should be listed in SECURITY_CONTACTS
@andyzhangx
@msau42 
@jingxu97 
@xing-yang 
@saad-ali

**Comment by xing-yang** [comment]
See this issue here as an example: 
https://github.com/kubernetes/org/issues/1648

**Comment by andyzhangx** [comment]
> See this issue here as an example:
> #1648

thanks, updated.

**Comment by xing-yang** [comment]
Can you update the "admin access" section too?

**Comment by andyzhangx** [comment]
> Can you update the "admin access" section too?

done

**Comment by andyzhangx** [comment]
@nikhita  I have added you as admin of repo: https://github.com/csi-driver/csi-driver-smb, are you going to migrate this repo? thanks.

**Comment by nikhita** [comment]
Verified that licenses are proper and all contributors have signed the CNCF CLA. @andyzhangx Thanks for taking care of all prerequisites for repo transfer in advance! :smile: 

Repo has been migrated - https://github.com/kubernetes-csi/csi-driver-smb

Also created:
- https://github.com/kubernetes/org/pull/1871 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4770 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by andyzhangx** [comment]
@nikhita thanks. Could you also add me as owner of this new project: https://github.com/kubernetes-csi/csi-driver-smb? Thanks.

**Comment by nikhita** [comment]
Granted access to you via the https://github.com/orgs/kubernetes-csi/teams/csi-driver-smb-admins team :)

**Comment by nikhita** [comment]
Teams have been granted access and sigs.yaml has been updated.

/close
