### ISSUE TITLE
REQUEST: New membership for @MoShitrit

### ISSUE THREAD

**Issue by MoShitrit** [kubernetes/org#1868]
### GitHub Username
@MoShitrit 

### Organization you are requesting membership in
@kubernetes-client

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @roycaihw 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-client/python/pull/1155
  - https://github.com/kubernetes-client/python/pull/1160
  - https://github.com/kubernetes-client/python/pull/1164

- Issues responded to
  - https://github.com/kubernetes-client/python/issues/1163
  - https://github.com/kubernetes-client/python/issues/1145
  - https://github.com/kubernetes-client/python/issues/1147

- SIG projects I am involved with
  I'm also active on various slack channels and already a member of @kubernetes org, in case it's relevant. Thanks!

**Comment by roycaihw** [comment]
+1

Welcome!

**Comment by idealhack** [comment]
@MoShitrit thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/1876 to add you to the kubernetes-client org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-client! 🎉

**Comment by MoShitrit** [comment]
Thank you both! 😄 
@idealhack @roycaihw
