### ISSUE TITLE
REQUEST: New membership for jiahuif

### ISSUE THREAD

**Issue by jiahuif** [kubernetes/org#1869]
### GitHub Username
@jiahuif

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cheftako 
- @andrewsykim 
### List of contributions to the Kubernetes project
- PRs reviewed / authored

| PR  Authored                      | Milestone |
|-----------------------------|-----------|
| kubernetes/kubernetes#90742 | 1.19      |
| kubernetes/kubernetes#90737 | 1.19      |
| kubernetes/kubernetes#89238 | 1.18      |
| kubernetes/kubernetes#88987 | 1.19      |
| kubernetes/kubernetes#88354 | 1.18      |
| kubernetes/kubernetes#88100 | 1.18      |
| kubernetes/kubernetes#88089 | None      |
| kubernetes/kubernetes#86458 | 1.18      |
| kubernetes/community#4225   | N/A       |
| kubernetes/community#4226   | N/A       |

| PR  Reviewed                      | Milestone |
|-----------------------------|-----------|
| kubernetes/kubernetes#90738 | None     |
| kubernetes/kubernetes#88099 | 1.18      |

- Issues responded to

kubernetes/kubernetes#90185

- SIG projects I am involved with
sig-cloud-provider
sig-node

**Comment by andrewsykim** [comment]
+1

**Comment by cheftako** [comment]
+1

**Comment by idealhack** [comment]
@jiahuif thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/1876 to add you to the kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
