### ISSUE TITLE
REQUEST: New membership for tosi3k

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/org#1878]
### GitHub Username
@tosi3k

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mm4tt 
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
Merged 19 PRs to kubernetes/* repos so far: https://github.com/pulls?q=is%3Apr+author%3Atosi3k+archived%3Afalse+user%3Akubernetes+label%3Aapproved+is%3Aclosed
Conducted scalability A/B testing in the following PRs to confirm no new scalability regressions were introduced:
  - [kubernetes/kubernetes/pull/90183](https://github.com/kubernetes/kubernetes/pull/90183) (relevant [issue](https://github.com/kubernetes/kubernetes/issues/89961))
  - [kubernetes/kubernetes/pull/90674](https://github.com/kubernetes/kubernetes/pull/90674)

- Issues responded to
Issues created by myself:
  - [kubernetes/kubernetes/issues/90833](https://github.com/kubernetes/kubernetes/issues/90833)
  - [kubernetes/test-infra/issues/17412](https://github.com/kubernetes/test-infra/issues/17412)

- SIG projects I am involved with
[SIG Scalability](https://github.com/kubernetes/community/tree/master/sig-scalability)

**Comment by mm4tt** [comment]
+1

Thanks @tosi3k for all your contributions so far!

**Comment by dims** [comment]
+1 from me as well. thanks!

**Comment by mrbobbytables** [comment]
@tosi3k , thank you for all your contributions so far :)

I've created PR #1886  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
