### ISSUE TITLE
REQUEST: New membership for chaodaiG

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/org#1879]
### GitHub Username
chaodaiG

### Organization you are requesting membership in
kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @fejta 
- @alvaroaleman 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
So far had 12 PRs merged, examples:
https://github.com/kubernetes/test-infra/pull/16992
https://github.com/kubernetes/test-infra/pull/16318

- Issues responded to
https://github.com/kubernetes/test-infra/issues/17509
https://github.com/kubernetes/test-infra/issues/17266

- SIG projects I am involved with
sig-testing

**Comment by alvaroaleman** [comment]
+1

**Comment by fejta** [comment]
+1

**Comment by mrbobbytables** [comment]
@chaodaiG , thank you for all your help with test-infra :)

I've created PR #1886  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
