### ISSUE TITLE
REQUEST: New membership for marquiz

### ISSUE THREAD

**Issue by marquiz** [kubernetes/org#1880]
### GitHub Username
@marquiz

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @derekwaynecarr 
- @dims 

### List of contributions to the Kubernetes project
- PRs authored
  - https://github.com/kubernetes/kubernetes/pull/88122
  - https://github.com/kubernetes/kubernetes/pull/88231
  - https://github.com/kubernetes/k8s.io/pull/524
- PRs reviewed
  - https://github.com/kubernetes/kubernetes/pull/87522
  - https://github.com/kubernetes/kubernetes/pull/87348
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/65850
  - https://github.com/kubernetes/kubernetes/issues/66525
  - https://github.com/kubernetes/kubernetes/issues/87150
  - https://github.com/kubernetes/kubernetes/issues/87198
  - https://github.com/kubernetes/kubernetes/issues/87862
  - https://github.com/kubernetes/kubernetes/issues/88142
  - https://github.com/kubernetes/kubernetes/issues/88271
  - https://github.com/kubernetes/kubernetes/issues/88325
  - https://github.com/kubernetes/kubernetes/issues/88330
  - https://github.com/kubernetes/kubernetes/issues/90129
  - https://github.com/kubernetes/kubernetes/issues/90238
- SIG projects I am involved with (SIG-Node)
  - https://github.com/kubernetes-sigs/node-feature-discovery
  - https://github.com/kubernetes-sigs/node-feature-discovery-operator

**Comment by dims** [comment]
+1 from me. Welcome!

**Comment by derekwaynecarr** [comment]
+1

**Comment by mrbobbytables** [comment]
@marquiz  , thank you for all your contributions so far :)

I've created PR #1886  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
