### ISSUE TITLE
REQUEST: New membership for @bobbypage

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/org#1884]
### GitHub Username
e.g. @bobbypage

### Organization you are requesting membership in
e.g. (at)kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @karan
- @yguo0905
- @jdumars

### List of contributions to the Kubernetes project
- PRs reviewed / authored:

* https://github.com/kubernetes/kubernetes/pull/50396
* https://github.com/kubernetes/kubernetes/pull/51152
* https://github.com/kubernetes/kubernetes/pull/52588

- Issues responded to
- SIG projects I am involved with: Sig-Node, GCP Cloud Provider

**Comment by karan** [comment]
+1

**Comment by mrbobbytables** [comment]
@bobbypage unfortunately @karan cannot sponsor you for org membership. A sponsor must be an approver or reviewer within the kubernetes org. They must also be from different member organizations. Please see our [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#member) for more information.

**Comment by jdumars** [comment]
+1 from me as a sponsor. David has been involved with the community for a long time, and will be a great addition to our org.

**Comment by yguo0905** [comment]
+1

**Comment by mrbobbytables** [comment]
Thanks for your +1s :)

@bobbypage I've created PR #1886  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
