### ISSUE TITLE
Migrate a repository for hosting 'mount' library under staging.

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/org#1887]
### New Repo, Staging Repo, or migrate existing

Staging Repo

### Requested name for new repository
mount-utils

### Which Organization should it reside

kubernetes

### What should the repo description be
Package mount defines an interface to mounting filesystems

### What SIG and subproject does this fall under in sigs.yaml
sig-storage

### Approvals
Approved KEP : https://github.com/kubernetes/enhancements/pull/1760

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

**Comment by msau42** [comment]
/assign @saad-ali 
what do you think of the name?

**Comment by saad-ali** [comment]
SGTM

**Comment by nikhita** [comment]
Repos under the kubernetes org require approval from sig-arch too.

**Comment by nikhita** [comment]
@brahmaroutu I know that the issue mentions migration, but in this case we'd be starting with a bare repo. The code move from https://github.com/kubernetes/utils/tree/master/mount can be done as a follow up, especially because it involves some other things like go mod updates, import path updates, etc. Can you confirm that this works for you?

cc @dims

**Comment by brahmaroutu** [comment]
@nikhita thanks for the review, I do understand that we have address some build issues and we are ready to do necessary fixes once the repo is moved. Also I know that we need to create a bare repo first. I will send out a request to sig-arch forum to create the repo I guess. Please confirm.

**Comment by nikhita** [comment]
> @nikhita thanks for the review, I do understand that we have address some build issues and we are ready to do necessary fixes once the repo is moved. Also I know that we need to create a bare repo first. I will send out a request to sig-arch forum to create the repo I guess. Please confirm.

Sounds good! :)

**Comment by dims** [comment]
+1 please go ahead

**Comment by nikhita** [comment]
@brahmaroutu can you please update the issue body with details about who should be in approvers, reviewers, have admin access, etc?

**Comment by nikhita** [comment]
@brahmaroutu oops never mind, it's a staging repo :)

**Comment by nikhita** [comment]
Repo has been created with no initial commits (necessary for publishing-bot) - https://github.com/kubernetes/mount-utils

Also created:
1. https://github.com/kubernetes/test-infra/pull/17744 - to enable branch protection for the repo
2. https://github.com/kubernetes/community/pull/4818 - to add the repo to sigs.yaml
3. https://github.com/kubernetes/publishing-bot/pull/224 - to add the repo to the testing script in the publishing-bot repo

We can close this issue once 1 and 2 have merged (3 can be tracked separately).

**Comment by brahmaroutu** [comment]
Thanks @dims and @nikhita

**Comment by brahmaroutu** [comment]
thanks @nikhita @dims

**Comment by brahmaroutu** [comment]
@msau42 We need to move the repo with history. I have steps to do so but may not have necessary permissions and also I do not know the process.  Should we wait until the repo is hooked to test-infra CI?

**Comment by nikhita** [comment]
> Should we wait until the repo is hooked to test-infra CI?

Since this is a staging repo, the repo will need to be created as a directory here - https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io. The publishing-bot will sync this directory with https://github.com/kubernetes/mount-utils.

You will not be able to add code or merge PRs directly in the mount-utils repo, everything in that repo would be a copy of the staging directory.

**Comment by nikhita** [comment]
I'll close this issue since the repo is setup (https://github.com/kubernetes/test-infra/pull/17744 and https://github.com/kubernetes/community/pull/4818).

If you have any questions about the staging directory, please feel free to reach out to me on slack.

/close
