### ISSUE TITLE
archive the kubernetes/kube-deploy repository

### ISSUE THREAD

**Issue by neolit123** [kubernetes/org#1888]
### Repository to archive
https://github.com/kubernetes/kube-deploy

### Repository and/or sig subproject owners that are approving this archival
/cc @justinsb @timothysc 

### When should this be done
Anytime.

### Additional context for request
after a discussion in the SIG Cluster Lifecycle meeting of [20.05.2020](https://youtu.be/fTWQs53HAlM?list=PL69nYSiGNLP29D0nYgAGWt1ZFqS9Z7lw4&t=325) about [kube-deploy](https://github.com/kubernetes/community/blob/7a77ccc011ce9901993cb4cfb4a965351f68eb48/sig-cluster-lifecycle/README.md#kube-deploy).
it was decided that it was time to archive this project/repository. it currently contains only a single tool, an image builder, that is already exposed [elsewhere](https://github.com/kubernetes-sigs/image-builder).

the repository is not used in k8s CI and other than k/community, the only reference seems to be found in prow configuration (which AFAIK acts on invocation from the same repository). 

k/community cleanup:
https://github.com/kubernetes/community/pull/4796

k/test-infra cleanup:
https://github.com/kubernetes/test-infra/pull/17661

**Comment by timothysc** [comment]
+1 from me, we talked about this during the last SCL meeting.

**Comment by nikhita** [comment]
Repository has been archived - https://github.com/kubernetes-retired/kube-deploy

Also announced on the k-dev mailing list - https://groups.google.com/forum/#!topic/kubernetes-dev/j-Nk1qcPQLM

Once https://github.com/kubernetes/community/pull/4796 (removal from sigs.yaml) and https://github.com/kubernetes/org/pull/1892 (GitHub teams removal) merge, we can close this issue.

**Comment by neolit123** [comment]
thanks @nikhita !

**Comment by cblecker** [comment]
All PRs merged!
