### ISSUE TITLE
REQUEST: New membership for vpickard

### ISSUE THREAD

**Issue by vpickard** [kubernetes/org#1889]
### GitHub Username
@vpickard

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@spiffxp
@klueska

### List of contributions to the Kubernetes project
- PRs authored
https://github.com/kubernetes/kubernetes/pull/86184
https://github.com/kubernetes/kubernetes/pull/88773
https://github.com/kubernetes/test-infra/pull/15599
https://github.com/kubernetes/test-infra/pull/16062
https://github.com/kubernetes/test-infra/pull/16547
https://github.com/kubernetes/test-infra/pull/16646
https://github.com/kubernetes/test-infra/pull/17317
https://github.com/kubernetes/enhancements/pull/1527
https://github.com/intel/network-resources-injector/pull/7
https://github.com/intel/network-resources-injector/pull/15
https://github.com/intel/sriov-cni/pull/92
https://github.com/intel/sriov-cni/pull/107
https://github.com/intel/sriov-cni/pull/108
https://github.com/kubernetes/community/pull/4749
https://github.com/kubernetes/kubernetes/pull/88275

- PRs reviewed
https://github.com/kubernetes/kubernetes/pull/87255
https://github.com/kubernetes/kubernetes/pull/87645
https://github.com/kubernetes/kubernetes/pull/87799
https://github.com/kubernetes/kubernetes/pull/87921
https://github.com/kubernetes/kubernetes/pull/88721

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/86925
https://github.com/kubernetes/kubernetes/issues/91292

- SIG projects I am involved with
sig-node
test-infra

**Comment by spiffxp** [comment]
+1 from sponsor, @vpickard has been super helpful

**Comment by klueska** [comment]
+1 Welcome @vpickard!

**Comment by mrbobbytables** [comment]
@vpickard , thank you for all your contributions so far :)

I've created PR #1894  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
