### ISSUE TITLE
REQUEST: New membership for @iamemilio

### ISSUE THREAD

**Issue by iamemilio** [kubernetes/org#189]
### GitHub Username
@iamemilio

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @chaosaffe
- @Lion-Wei

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-openstack
https://github.com/kubernetes-sigs/cluster-api-provider-openstack
- Issues responded to
- SIG projects I am involved with
    sig-cluster-lifecycle
        cluster-api
        cluster-api-provider-openstack

/area github-membership

**Comment by chaosaffe** [comment]
+1 from me

**Comment by mrbobbytables** [comment]
Hey there @iamemilio, thanks for all the work you've done so far :)

I've created PR #192  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
