### ISSUE TITLE
REQUEST: New membership for prachirp

### ISSUE THREAD

**Issue by prachirp** [kubernetes/org#1890]
### GitHub Username
@prachirp

### Organization you are requesting membership in
kubernetes, kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @monopole (Google)
- @mortent (Google)
- @pwittrock (Apple)

### List of contributions to the Kubernetes project
- SIG projects I am involved with: kustomize
- PRs reviewed / authored: https://github.com/kubernetes-sigs/kustomize/commits?author=prachirp

**Comment by nikhita** [comment]
@prachirp can you please follow up with the sponsors to +1 here? Thanks :)

**Comment by mortent** [comment]
+1

**Comment by monopole** [comment]
+1

**Comment by nikhita** [comment]
/assign @pwittrock 
can you comment with a +1 here?

We'll need a non-google sponsor to +1 to close the loop on this :)

**Comment by pwittrock** [comment]
+1

FYI: I don't start at Apple until June 15.

**Comment by prachirp** [comment]
/assign @nikhita 
can you approve membership now?

**Comment by nikhita** [comment]
@prachirp thank you for all your contributors with kustomize so far :)

I've created PR #1917 to add you to the Kubernetes and the Kubernetes SIGs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! 🎉

/assign
