### ISSUE TITLE
REQUEST: New membership for @devigned

### ISSUE THREAD

**Issue by devigned** [kubernetes/org#1891]
### GitHub Username
@devigned

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @CecileRobertMichon

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/483
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/619
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/546
- Issues responded to
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/586
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/472
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/416
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure

https://github.com/kubernetes/test-infra/pull/17684#issuecomment-632398731

**Comment by justaugustus** [comment]
Definitely approved from me!

**Comment by justaugustus** [comment]
For passerby context: David is now a capz reviewer, which means we need to get him added to a variety of OWNERS in k org

**Comment by CecileRobertMichon** [comment]
+1 ! 🎉

**Comment by cpanato** [comment]
+1

**Comment by mrbobbytables** [comment]
@devigned  , thank you for all your contributions so far :)

I've created PR #1894  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
