### ISSUE TITLE
REQUEST: New membership for viniciusbds

### ISSUE THREAD

**Issue by viniciusbds** [kubernetes/org#1893]
### GitHub Username
@viniciusbds

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sftim 
- @devlware

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  	https://github.com/kubernetes/website/pull/20410
   	https://github.com/kubernetes/website/pull/20204
   	https://github.com/kubernetes/website/pull/20180
   	https://github.com/kubernetes/website/pull/19862
   	https://github.com/kubernetes/website/pull/19637
  	https://github.com/kubernetes/website/pull/19598
	https://github.com/kubernetes/website/pull/20460	
	https://github.com/kubernetes/website/pull/20172
	https://github.com/kubernetes/website/pull/19949
	https://github.com/kubernetes/website/pull/19796

- Issues responded to
 	https://github.com/kubernetes/website/issues/20688
   	https://github.com/kubernetes/website/issues/20701

- SIG projects I am involved with

**Comment by sftim** [comment]
Hi @viniciusbds 
I'm happy to sponsor you as a Kubernetes member. You might want to list SIG Docs as a group you're involved with.

**Comment by devlware** [comment]
Hi @viniciusbds 
I'm also happy to sponsor you as a K8s member.

+1

**Comment by mrbobbytables** [comment]
@viniciusbds , thank you for all your help with the website :)

I've created PR #1894  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
