### ISSUE TITLE
Create the backing repository for staging/controller-manager

### ISSUE THREAD

**Issue by cheftako** [kubernetes/org#1895]
### New Repo, Staging Repo, or migrate existing
staging/controller-manager

### Requested name for new repository
controller-manager

### Which Organization should it reside
kubernetes

### If not a staging repo, who should have admin access
N/A

### If not a staging repo, who should have write access
N/A

### If not a staging repo, who should be listed as approvers in OWNERS
N/A

### If not a staging repo, who should be listed in SECURITY_CONTACTS
N/A

### What should the repo description be
created due to https://github.com/kubernetes/kubernetes/pull/91354

### What SIG and subproject does this fall under in sigs.yaml
This falls under the api-machinery SIG but also involves SIG cloud provider and cloud provider extraction WG.

### Approvals
Approved by SIG api-machinery Chairs (@deads2k @fedebongio) and SIG cloud provider Chairs (@andrewsykim @cheftako)

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

### Additional context for request
This repo is intended to contain common public library code for kube-controller-manager, cloud-controller-manager as well as any other controller managers which people build.

**Comment by dims** [comment]
+1 from me.

**Comment by nikhita** [comment]
For the record, approval from @deads2k is at https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/Y0rOAu5xdYI

**Comment by nikhita** [comment]
Repo has been created with no initial commits (necessary for publishing-bot) - https://github.com/kubernetes/controller-manager

Also created:
1. https://github.com/kubernetes/test-infra/pull/17712 - to enable branch protection for the repo
2. https://github.com/kubernetes/community/pull/4809 - to add the repo to sigs.yaml
3. https://github.com/kubernetes/publishing-bot/pull/224 - to add the repo to the testing script in the publishing-bot repo

We can close this issue once 1, 2 and https://github.com/kubernetes/kubernetes/pull/91354 have merged (3 can be tracked separately) and the repo has been synced.

**Comment by nikhita** [comment]
Repo has been synced - https://github.com/kubernetes/controller-manager :tada:

**Comment by dims** [comment]
nice work @nikhita thanks!
