### ISSUE TITLE
REQUEST: New membership for @pohly

### ISSUE THREAD

**Issue by pohly** [kubernetes/org#1897]
### GitHub Username
@pohly 

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @humblec 
- @msau42

### List of contributions to the Kubernetes project
- various contributions, I am already officially a Kubernetes contributor

**Comment by nikhita** [comment]
You don't need sponsorship since you are already a @kubernetes member.

The GitHub Admin team can handle this with the next batch of adding members but if you'd like membership sooner, feel free to create a PR yourself. :)

**Comment by pohly** [comment]
I was following https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem which says that an issue should be opened. I suppose that should mention the possibility to create a PR.

**Comment by humblec** [comment]
LGTM .
@nikhita Is it possible to get this approved without PR ? If yes, please approve :)

**Comment by pohly** [comment]
I've submitted a PR with the org change: https://github.com/kubernetes/org/pull/1901
