### ISSUE TITLE
REQUEST: New membership for eddiezane

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/org#1898]
### GitHub Username
@eddiezane

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@soltysh 
@pwittrock 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kustomize/pull/2192
https://github.com/kubernetes/kubernetes/pull/89840
https://github.com/kubernetes/kubernetes/pull/89841
https://github.com/kubernetes/community/pull/4160

- Issues responded to
https://github.com/kubernetes/kubectl/issues/870
https://github.com/kubernetes/kubectl/issues/776
https://github.com/kubernetes/kubectl/issues/780
https://github.com/kubernetes/kubectl/issues/781
https://github.com/kubernetes/kubectl/issues/396
https://github.com/kubernetes/kubectl/issues/500
https://github.com/kubernetes/kubectl/issues/765
https://github.com/kubernetes/kubectl/issues/766
https://github.com/kubernetes/kubectl/issues/769

- SIG projects I am involved with
  * SIG CLI
    * kubectl
    * Organizing and leading SIG CLI monthly bug scrubs.

**Comment by pwittrock** [comment]
@soltysh

**Comment by soltysh** [comment]
:+1:

**Comment by nikhita** [comment]
@eddiezane thank you for all your contributors with SIG CLI :)

I've created PR #1902 to add you to the Kubernetes and Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! 🎉

/assign
