### ISSUE TITLE
REQUEST: New membership for adisky

### ISSUE THREAD

**Issue by adisky** [kubernetes/org#190]
### GitHub Username
@adisky

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @zetaab 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=is%3Apr+is%3Amerged+org%3Akubernetes+author%3Aadisky
https://github.com/search?q=is%3Apr+reviewed-by%3Aadisky+org%3Akubernetes+-author%3Aadisky

- Issues responded to
https://github.com/search?q=is%3Aissue+commenter%3Aadisky+org%3Akubernetes
- SIG projects I am involved with
 kubernetes/cloud-provider-openstack

/area github-membership

**Comment by zetaab** [comment]
+1
