### ISSUE TITLE
Request token for google/triage-party

### ISSUE THREAD

**Issue by ameukam** [kubernetes/org#1903]
### Organization or repository
kubernetes/kubernetes

### Name of integration
Triage Party

### Link to integration website
https://github.com/google/triage-party

### Describe what is attempting to be accomplished
SIG-Release is exploring Triage Party as a triage tool that will help the bug-triage team during release cycles. Triage Party needs a [Github access token with read access](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line).

### Additional context for request
The token will be stored as a kubernetes `Secret` in `aaa` cluster where triage-party is planned to be hosted. 

/assign @cblecker @spiffxp 
cc @markyjackson-taulia 
/sig release
/area release-eng

**Comment by justaugustus** [comment]
/assign
Spoke w/ @spiffxp during the GH Admin meeting. I'll pick this up.

**Comment by ameukam** [comment]
ghproxy provide a flag (`--github-api-url`) that allow to override the GitHub API URL but It's only compatible with GitHub Enterprise : https://github.com/google/triage-party/blob/v1.1.0/pkg/triage/github.go#L55-L64.

We may need to patch triage-party in order to support ghproxy.

**Comment by coderanger** [comment]
To copy a conclusion from Slack, triage-party has its own persistence layer so we can probably skip ghproxy for now. So next step would probably be a test deployment against a smaller repo with test token?

**Comment by ameukam** [comment]
Link of the conclusion from Slack: https://kubernetes.slack.com/archives/C1TU9EB9S/p1591822629213000?thread_ts=1591822021.211300&cid=C1TU9EB9S. 

@coderanger Something more ambitious: Running triage-party again the `ĸubernetes/kubernetes` repo: https://github.com/kubernetes/k8s.io/pull/967. :-)

**Comment by tstromberg** [comment]
@coderanger - Hi! I'm the author of triage-party. I believe that `--github-api-url` may still work for ghproxy, if the go-github API docs are to be believed: https://pkg.go.dev/github.com/google/go-github/v32/github?tab=doc#NewEnterpriseClient

If you run into any issues or have questions getting Triage Party setup, please let me know (@tstromberg on Kubernetes Slack).

**Comment by justaugustus** [comment]
Created https://github.com/k8s-triage-party-sig-release-bot and generated a token with `public_repo` OAuth scope (ref: https://github.com/google/triage-party/commit/e4b59f27c8b14f08b6c11a7dd80733f30cc3fb02).

Handed that token off to @spiffxp for deployment.
The deployment is tracked in https://github.com/kubernetes/k8s.io/pull/967.

/close

**Comment by justaugustus** [comment]
Example from @Riaankl in [yesterday's GH Admin meeting](https://docs.google.com/document/d/1IiVrr1hcFWmbboExk971FsMUGfr2Wp68mdMribCuzLs/edit#heading=h.5wzcacxwipf3):
- Test run of the Triage party in Kubernetes can be seen here: http://heyste.ii.coop:11083/s/daily
- Docs:
  - Checking Conformance Progress with Triage Party: https://github.com/cncf/apisnoop/blob/4dd2abbaeb0c3fe8ecbbd832b8aa0882928551c0/docs/checking-conformance-progress-with-triage-party.org
  - k8s-area-conformance-triage-party.yaml: https://github.com/cncf/apisnoop/blob/4dd2abbaeb0c3fe8ecbbd832b8aa0882928551c0/docs/k8s-area-conformance-triage-party.yaml
