### ISSUE TITLE
New Org

### ISSUE THREAD

**Issue by copejon** [kubernetes/org#1904]
### Organization or repository
kubernetes-cosi

### Users affected
n/a

### Describe the issue
We're in the process of opening a new sub-project under sig-storage, for which we'd like to have a git org. As our team had already created an org named kubernetes-cosi, which we'd now like to hand it over to the sig. Any code in the org has been transferred out and all repos have been removed.  It's completely empty.

What's the process by which we can do this? I was weary of opening a New/Migrate Repo issue as most of the fields pertained to repo-level configs.

**Comment by spiffxp** [comment]
Is there any specific reason these repositories can't be donated to kubernetes-sigs and grouped together via a topic?

The team discussed this at our last meeting, and while I apologize for the lack of documentation on this policy, our consensus is we'd rather not add the overhead of managing another github org unless there's a strong reason to do so.

One of the benefits of going with kubernetes-sigs is the number of people who are already members there (we one day hope to keep this in sync with kubernetes (ref: https://github.com/kubernetes/org/issues/966); keeping N orgs in sync is much more overhead)

**Comment by copejon** [comment]
> One of the benefits of going with kubernetes-sigs is the number of people who are already members there (we one day hope to keep this in sync with kubernetes (ref: #966); keeping N orgs in sync is much more overhead)

Ah! Sorry, I hadn't realized that.  Would it be better to create a topic now, then migrate/create repo(s) later?  Or should we wait until we're ready to push some code?

**Comment by copejon** [comment]
cc @saad-ali as I'm not very attuned to kube's meta architecture.   What are your thoughts on topic vs org?  I suggested an org initially, thinking that that COSI may mature beyond a small number of repos (code, examples, drivers, etc).

**Comment by mrbobbytables** [comment]
With that do you think this issue can be closed?

**Comment by copejon** [comment]
Yes, will follow up on a new git topic in a new issue.
