### ISSUE TITLE
REQUEST: New membership for giuseppe

### ISSUE THREAD

**Issue by giuseppe** [kubernetes/org#1905]
### GitHub Username
giuseppe

### Organization you are requesting membership in
kubernetes, kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @derekwaynecarr (Red Hat)
- @dashpole (Google)

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Agiuseppe
- https://github.com/kubernetes/enhancements/pull/1370
- Mostly working in sig-node

**Comment by derekwaynecarr** [comment]
+1

**Comment by dashpole** [comment]
+1

**Comment by nikhita** [comment]
@giuseppe thank you for all your contributors with sig node so far :)

I've created PR #1914 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification. The issue body requests for @kubernetes-sigs membership as well but you are already a member of k-sigs. :)

Welcome to @kubernetes! 🎉

/assign
