### ISSUE TITLE
A new SIG repo for instrumentation-tools

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/org#1907]
### New Repo, Staging Repo, or migrate existing

We'd like a new repository for hosting instrumentation-tooling code.

### Requested name for new repository

instrumentation-tools

### Which Organization should it reside

kubernetes-sigs

### If not a staging repo, who should have admin access

sig-instrumentation-leads (i.e. @dashpole, @brancz, @ehashman, @logicalhan)

### If not a staging repo, who should have write access

same

### If not a staging repo, who should be listed as approvers in OWNERS

same

### If not a staging repo, who should be listed in SECURITY_CONTACTS

same

### What should the repo description be

Repository for tools and artifacts related to the sig-instrumentation charter in Kubernetes.

### What SIG and subproject does this fall under in sigs.yaml

sig-instrumentation

### Approvals

As per SIG-Instrumentation charter, the approval process falls to the SIG Leads.

/sig instrumentation
/assign @dashpole @ehashman @brancz

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/instrumentation-tools :tada: 

Also created:
- https://github.com/kubernetes/org/pull/1910 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4828 - to add the repo to sigs.yaml

Once both PRs get merged, we can close this issue.

**Comment by logicalhan** [comment]
Thanks @nikhita!!

**Comment by RainbowMango** [comment]
Wonderful!
