### ISSUE TITLE
REQUEST: New membership for rajula96reddy

### ISSUE THREAD

**Issue by rajula96reddy** [kubernetes/org#1908]
### GitHub Username
@rajula96reddy

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman
- @jonasrosland

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/k8s.io/pull/720
  - https://github.com/kubernetes/minikube/pull/5844
- Issues responded to
  - https://github.com/kubernetes/community/issues/4446
  - https://github.com/kubernetes/community/issues/4825
- SIG projects I am involved with
  - sig-contribex

**Comment by jonasrosland** [comment]
+1 from me!
Thank you Rajula for all the things you're driving in Contribex!

**Comment by chris-short** [comment]
Huge +1 from me. Thank you for all the work you’re doing in the community, Rajula.

**Comment by nikhita** [comment]
@rajula96reddy thank you for all your contributors to sig contribex so far :)

I've created PR #1961 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
