### ISSUE TITLE
REQUEST: New membership for bsdnet

### ISSUE THREAD

**Issue by bsdnet** [kubernetes/org#1913]
### GitHub Username
 @bsdnet

### Organization you are requesting membership in
@kubernetes

### Requirements
- [ X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X ] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp 
- @MHBauer 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
kubernetes/kubernetes#91543
kubernetes/kubernetes#91612
kubernetes/test-infra#17770 
kubernetes/test-infra#17695
kubernetes/test-infra#17692
kubernetes/test-infra#17677
kubernetes/test-infra#17670

- Issues responded to:
kubernetes/kubernetes#91641
kubernetes/test-infra#17743
kubernetes/test-infra#17734
kubernetes/test-infra#17722
kubernetes/test-infra#17687

- SIG projects I am involved with
 sig-node/sig-testing

**Comment by spiffxp** [comment]
+1 from sponsor

The issue numbers above don't link but FWIW I know these are kubernetes/kubernetes (91...) and kubernetes-test-infra (17...)

**Comment by MHBauer** [comment]
@bsdnet has been a great help with sig-node testing effort and especially helpful with understanding the cos images! 👍

**Comment by bsdnet** [comment]
Thanks @spiffxp  for the example.  Corrected.

Thanks @MHBauer. Good to work with you, and try my best to make sig-node/testing better.

**Comment by alejandrox1** [comment]
want to add another +1 here :smile: 
Thank you for all your work @bsdnet !

**Comment by bsdnet** [comment]
Thanks @alejandrox1

**Comment by nikhita** [comment]
@bsdnet thank you for all your contributors with sig node and testing so far :)

I've created PR #1914 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification. :)

Welcome to @kubernetes! 🎉

/assign
