### ISSUE TITLE
REQUEST: New membership for celestehorgan

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/org#1915]
### GitHub Username
@celestehorgan

### Organization you are requesting membership in
kubernetes/website

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @jimangel 

### List of contributions to the Kubernetes project
- [My PRs](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3A%40me+)
- [Issues I've worked on](https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3A%40me+) and [Other things I've participated in](https://github.com/kubernetes/website/issues?q=mentions%3A%40me+is%3Aclosed)
- SIG projects I am involved with: SIG-Docs

**Comment by mrbobbytables** [comment]
+1 from me :)
/pony party

**Comment by jimangel** [comment]
Strong +1! Thanks for your contributions @celestehorgan! :tada:

**Comment by dims** [comment]
+1 from me!

**Comment by nikhita** [comment]
I'll add my +1 too :woman_dancing:

**Comment by nikhita** [comment]
@celestehorgan thank you for all your contributors with SIG Docs, and especially for helping out real quick with the steering-related discussion :)

I've created PR #1917 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
