### ISSUE TITLE
REQUEST: New membership for Arhell

### ISSUE THREAD

**Issue by Arhell** [kubernetes/org#1916]
### GitHub Username
@Arhell

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @jimangel 
- @dims 

### List of contributions to the Kubernetes project
- PRs  authored https://github.com/kubernetes/website/pulls?q=author%3AArhell
https://github.com/kubernetes-sigs/reference-docs/pulls?q=author%3AArhell+

- Issues responded to https://github.com/kubernetes/website/issues/created_by/Arhell

**Comment by dims** [comment]
+1 from me!

**Comment by jimangel** [comment]
+1 as well, thanks @Arhell! 🎉

**Comment by zacharysarah** [comment]
+1 from me as well!

**Comment by nikhita** [comment]
@Arhell thank you for all your contributors with SIG Docs so far :)

I've created PR #1923 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
