### ISSUE TITLE
REQUEST: New membership for jherrera123

### ISSUE THREAD

**Issue by jherrera123** [kubernetes/org#1926]
### GitHub Username
@jherrera123

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @BenTheElder 
- @oomichi 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - Prevent release note duplicate messages https://github.com/kubernetes/test-infra/pull/17912
  - Relabel WIP issue when moving from normal to draft https://github.com/kubernetes/test-infra/pull/17766
  - Fix runtime admission flaky test due to race condition https://github.com/kubernetes/kubernetes/pull/91315
  - Make flexvolume e2e tests runnable again https://github.com/kubernetes/kubernetes/pull/90707
- Issues responded to
  - WIP plugin doesn't properly handle draft PRs after changes to GH API https://github.com/kubernetes/test-infra/issues/17583
  - flake: [sig-node] RuntimeClass should reject a Pod requesting a RuntimeClass with an unconfigured handler https://github.com/kubernetes/kubernetes/issues/90653
  - repeated commenting on release-note-needed when cherry pick is filed https://github.com/kubernetes/test-infra/issues/16971
  - Flexvolume e2e tests are skipped in sig-storage test dashboards https://github.com/kubernetes/kubernetes/issues/88132
  - Pod affinity with operator "DoesNotExist" does not work https://github.com/kubernetes/kubernetes/issues/90679
  - Improve Scheduler Logging https://github.com/kubernetes/kubernetes/issues/91633
- SIG projects I am involved with
  - sig-testing
  - sig-node
  - sig-scheduling

**Comment by BenTheElder** [comment]
+1, thanks!

**Comment by nikhita** [comment]
@jherrera123 Can you please add the list of sponsors in your issue body? All membership applications require 2 sponsors :)

**Comment by oomichi** [comment]
+1, thanks for your contribution!

**Comment by nikhita** [comment]
@jherrera123 thank you for all your contributors so far :)

I've created PR #1933 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
