### ISSUE TITLE
add roycaihw as a member of kubernetes-sigs

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/org#1927]
### GitHub Username
@roycaihw

### Organization you are requesting membership in
@kubernetes-sigs

I'm already a member of the Kubernetes org.

ref https://github.com/kubernetes-sigs/kube-storage-version-migrator/issues/69#issuecomment-643005826

/assign @spiffxp

**Comment by nikhita** [comment]
@roycaihw Created https://github.com/kubernetes/org/pull/1928 to add you to @kubernetes-sigs. Can you lgtm the PR? Thanks :)
