### ISSUE TITLE
REQUEST: New membership for @alonyb

### ISSUE THREAD

**Issue by alonyb** [kubernetes/org#1929]
### GitHub Username
@alonyb

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @medyagh 
- @sharifelgamal
- @afbjorklund

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/minikube/pull/7603
https://github.com/kubernetes/minikube/pull/6580
https://github.com/kubernetes/minikube/pull/6517
https://github.com/kubernetes/minikube/pull/6150

- Issues responded to
https://github.com/kubernetes-sigs/krew-index/pull/462

- SIG projects I am involved with
https://github.com/kubernetes-sigs/krew/pull/461
https://github.com/kubernetes-sigs/krew/pull/491
https://github.com/kubernetes-sigs/krew-index/pull/437
https://github.com/kubernetes-sigs/krew-index/pull/476

**Comment by sharifelgamal** [comment]
+1

**Comment by medyagh** [comment]
I support @alonyb to be in the kubernetes orgs, he has done multiple good contributions to the minikube project

**Comment by nikhita** [comment]
@alonyb Sponsors need to have different employers. Do you happen to know anyone not from Google who can sponsor you?

**Comment by afbjorklund** [comment]
I sponsor @alonyb for membership in the minikube project and kubernetes organisation

**Comment by nikhita** [comment]
@alonyb thank you for all your contributors to minikube so far :)

I've created PR #1941 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
