### ISSUE TITLE
REQUEST: New membership for swamymsft

### ISSUE THREAD

**Issue by swamymsft** [kubernetes/org#1930]
### GitHub Username
@swamymsft

### Organization you are requesting membership in
@Kubernetes

### Requirements
- [Yes] I have reviewed the community membership guidelines 
- [Yes] I have enabled 2FA on my GitHub account
- [Yes] I have subscribed to the kubernetes-dev e-mail list 
- [Yes] I am actively contributing to 1 or more Kubernetes subprojects
- [Yes] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [Yes] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@tallclair 
@ritazh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- I'm involved with Kubernetes PSC

**Comment by swamymsft** [comment]
Adding couple of links to the pull requests:
https://github.com/kubernetes/security/pull/40 
https://github.com/kubernetes/security/pull/50

**Comment by tallclair** [comment]
+1 for Swamy's membership. He is already helping out with the PSC, and it is important for him to be an org member in order to carry out all the PSC responsibilities.

**Comment by ritazh** [comment]
+1
Have been working with Swamy on security issues for Kubernetes.

**Comment by mrbobbytables** [comment]
@swamymsft , thank you for all your help with the PSC \o/

I've created PR #1968   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by swamymsft** [comment]
> @swamymsft , thank you for all your help with the PSC \o/
> 
> I've created PR #1968 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉
> 
> /assign

Thanks @mrbobbytables, I got the invite and joined the greater Kubernetes Org.

Thanks @ritazh & @tallclair for supporting my sponsorship!
