### ISSUE TITLE
Migrate packethost/cluster-api-provider-packet to kubernetes-sigs

### ISSUE THREAD

**Issue by gianarb** [kubernetes/org#1934]
### New Repo, Staging Repo, or migrate existing
Migrate existing [packethost/cluster-api-provider-packet](https://github.com/packethost/cluster-api-provider-packet)

### Requested name for new repository
cluster-api-provider-packet

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@mrmrcoleman @deitch

### If not a staging repo, who should have write access
@gianarb @deitch @jacobsmith928 @mrmrcoleman probably we need a team for it: `cluster-api-packet-maintainers`

### If not a staging repo, who should be listed as approvers in OWNERS

This is the issue that tracks this work: https://github.com/packethost/cluster-api-provider-packet/issues/114

### If not a staging repo, who should be listed in SECURITY_CONTACTS
This is the issue that tracks this work: https://github.com/packethost/cluster-api-provider-packet/issues/121

### What should the repo description be
"Packet Cloud Provider for Cluster API"

### What SIG and subproject does this fall under in sigs.yaml
sig-cluster-lifecycle

### Approvals
- [Wed 10 June](https://docs.google.com/document/d/1fQNlqsDkvEggWFi51GVxOglL2P1Bvo2JhZlMhm2d-Co/edit#heading=h.fkoj468t0pcr) during cluster-api Office Hour, we raised our desire to move the repo under kubernetes-sigs.  The video will be linked as soon as available.

### Additional context for request

16th June I will bring this topic to sig-cluster-lifecycle be-weekly meeting because for now I just had a chat in ClusterAPI meeting. Will update this PR with more information

**Comment by mrbobbytables** [comment]
/assign @justinsb @neolit123 @timothysc @fabianofranz 
For sign off

After sign off from the leads,  @deitch @jacobsmith928 @mrmrcoleman  will need to apply for membership to kubernetes-sigs 👍

**Comment by nikhita** [comment]
Aside from what @mrbobbytables has detailed in https://github.com/kubernetes/org/issues/1934#issuecomment-644100402, the repo will need some more updates before it is ready for migration.

- As per the [rules](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories), all contributors must have signed the CNCF CLA. @rkoster has not signed the CLA yet (@rkoster -- you can find instructions for singing the CLA [here](https://github.com/kubernetes/community/blob/master/CLA.md)).

- Add all template files including `code-of-conduct.md`, `CONTRIBUTING.md`, `OWNERS`, etc as per https://github.com/kubernetes/kubernetes-template-project. Please also add a note in your README for https://github.com/kubernetes/kubernetes-template-project#community-discussion-contribution-and-support.

- The [LICENSE](https://github.com/packethost/cluster-api-provider-packet/blob/master/LICENSE) needs to be updated to Apache v2.

- All files need the standard Kubernetes copyright header. You can find the boilerplate for different file extensions [here](https://github.com/kubernetes/kubernetes/tree/master/hack/boilerplate). Please also update the [boilerplate used by generator tools](https://github.com/packethost/cluster-api-provider-packet/blob/master/hack/boilerplate.go.txt).

- Once everything is ready, please add me and @mrbobbytables as admins to the repo and we can migrate it to @kubernetes-sigs. :)

**Comment by rkoster** [comment]
S&W had already signed: https://identity.linuxfoundation.org/content/cncf-stark-wayne, but apparently I did not yet connect my linux foundation account to github. It should all be set now.

**Comment by nikhita** [comment]
@rkoster Thanks for the quick response! Can confirm that the CLA looks fine now :smile:

**Comment by mrbobbytables** [comment]
> /unassign @fabianofranz
> /assign @fabriziopandini

Oh woops, sorry about that misassign >_> auto-complete got me.

**Comment by neolit123** [comment]
thank you for joining the meeting today @gianarb 
we've +1 for the migration from the SIG CL standpoint.
/lgtm

the subproject addition is in this PR, but we requested an amends to it:
https://github.com/kubernetes/community/pull/4861
(to add it as `cluster-api-provider-packet` under SIG CL and not SIG CP).

**Comment by nikhita** [comment]
@gianarb tiny nit: the copyright header needs to have newlines. example https://github.com/packethost/cluster-api-provider-packet/blob/master/controllers/packetcluster_controller.go#L3 and https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.go.txt#L3 for comparison.

Can you ping here once all membership requests are processed as per https://github.com/kubernetes/org/issues/1934#issuecomment-644100402? Will migrate the repo after that. :+1:

**Comment by nikhita** [comment]
Some more small updates needed:

- The repo has an OWNERS file that mentions aliases like `cluster-api-packet-maintainers` but doesn't have an `OWNERS_ALIASES` file at the root to define these aliases. You can find the format for the aliases file [here](https://github.com/kubernetes/kubernetes-template-project/blob/master/OWNERS_ALIASES).

- Can you also add a note in the README for the "Community, discussion, contribution, and support" section as per https://github.com/kubernetes/kubernetes-template-project#community-discussion-contribution-and-support? This is to ensure that all repos have links to slack channels, mailing lists and a link to the CoC in the README.

**Comment by gianarb** [comment]
@nikhita thank you for your help.
I think we are all set! Do you agree?

Thanks

**Comment by nikhita** [comment]
@gianarb There are a few things still outstanding :grimacing: 

- The link to the slack channels, CoC still needs to be added in the README as per https://github.com/kubernetes/org/issues/1934#issuecomment-645170323

- There are still a few copyright headers that need newlines. Example - https://github.com/packethost/cluster-api-provider-packet/blob/master/main.go#L2

-  @deitch @jacobsmith928 @mrmrcoleman will need to apply for membership to kubernetes-sigs (https://github.com/kubernetes/org/issues/1934#issuecomment-644100402)

**Comment by nikhita** [comment]
For the record -- I discussed with @gianarb, we are sorting out some org level settings around who can transfer the repo. Everything looks good otherwise, I'll migrate the repo once the settings have been fixed. :+1: 

@gianarb also thank you for taking care of all the prerequisites and being so responsive with everything! :heart:

**Comment by neolit123** [comment]
the up to date list for this:
https://github.com/packethost/cluster-api-provider-packet/blob/master/OWNERS_ALIASES#L4-L7

is here:
https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES#L4-L8

but we can update it later too.

**Comment by nikhita** [comment]
Repo has been migrated - https://github.com/kubernetes-sigs/cluster-api-provider-packet :tada: 

Teams have been granted access and sigs.yaml has been updated.

@neolit123 -- also, OWNERS_ALIASES has been updated in https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/138 :smile: 

/close

**Comment by neolit123** [comment]
awesome :tada:

**Comment by nikhita** [comment]
The repo was moved a few minutes ago but @fejta-bot is already in action :laughing: 

https://github.com/kubernetes-sigs/cluster-api-provider-packet/issues/8#issuecomment-650181886

**Comment by gianarb** [comment]
Thanks a lot for your support!! We are happy and excited about all of this!! :D Now let's try to make @fejta-bot happy!
