### ISSUE TITLE
REQUEST: New membership for chizhg

### ISSUE THREAD

**Issue by chizhg** [kubernetes/org#1936]
### GitHub Username
chizhg

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cjwagner
- @alvaroaleman

### List of contributions to the Kubernetes project
- PRs reviewed / authored
So far had 7 PRs merged, examples:
https://github.com/kubernetes/test-infra/pull/17188
https://github.com/kubernetes/test-infra/pull/17649

- Issues responded to
https://github.com/kubernetes/test-infra/issues/10884
https://github.com/kubernetes/test-infra/issues/15971

**Comment by cjwagner** [comment]
+1 from me 👍

**Comment by alvaroaleman** [comment]
+1

**Comment by nikhita** [comment]
@chizhg thank you for all your contributors to test-infra so far :)

I've created PR #1937 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
