### ISSUE TITLE
REQUEST: New membership for yodahekinsew

### ISSUE THREAD

**Issue by yodahekinsew** [kubernetes/org#1939]
### GitHub Username
@yodahekinsew

### Organization you are requesting membership in
@kubernetes

### Requirements
- [Yes] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [Yes] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [Yes] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [Yes] I am actively contributing to 1 or more Kubernetes subprojects
- [Yes] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [Yes] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@listx

### List of contributions to the Kubernetes project
I'm involved with the [Kubernetes Container Image Promoter](https://github.com/kubernetes-sigs/k8s-container-image-promoter) project
[PR #219](https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/219) 
[PR #218](https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/218) 
[PR #217](https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/217)

**Comment by listx** [comment]
Confirming from my end that @yodahekinsew is indeed who he says he is.

/cc @justaugustus

**Comment by justaugustus** [comment]
Approved on behalf of SIG Release.
Note that this membership for the `kubernetes-sigs` org (where https://github.com/kubernetes-sigs/k8s-container-image-promoter is), not the `kubernetes` org.

I've opened the PR for membership: https://github.com/kubernetes/org/pull/1943
