### ISSUE TITLE
New Repository for Container Object Storage Interface implementation

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/org#1942]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
container-object-storage-interface-spec   (Container Object Storage Specification)
container-object-storage-interface-csi-adapter (CSI driver to bootstrap COSI workloads)

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@jsafrane
@msau42
@saad-ali
@xing-yang

### If not a staging repo, who should have write access
@saad-ali 
@jsafrane
@msau42
@xing-yang
@copejon 
@wlan0 
@brahmaroutu 

### If not a staging repo, who should be listed as approvers in OWNERS
@jsafrane
@msau42
@saad-ali
@xing-yang

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@jsafrane
@msau42
@saad-ali
@xing-yang

### What should the repo description be
Kubernetes specific Container Object Storage Interface (COSI) components

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject for sig-storage called kubernetes-cosi

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

Need sig-storage approval from:  @saad-ali and @xing-yang

Please refer to KEP:  https://github.com/kubernetes/enhancements/pull/1383

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
Since the design mentioned in the KEP constitute multiple components, this issue is requesting for multiple repos under new subproject(Kubernetes-cosi) that belongs to sig-storage.

**Comment by brahmaroutu** [comment]
/sig storage
/assign @xing-yang 
ping @copejon @wlan0 Please review.

**Comment by copejon** [comment]
WRT to 
> "including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)"

See too #1904

**Comment by xing-yang** [comment]
Can you send an email to sig-storage mailing list about this request?
Other than that, this looks good to me.

**Comment by brahmaroutu** [comment]
> Can you send an email to sig-storage mailing list about this request?
> Other than that, this looks good to me.

thanks. I just sent out email about the request.

**Comment by saad-ali** [comment]
Suggestions:

* For repo names, spell out `container-object-storage-interface` rather than using abbreviation `COSI`
* Align naming with [CSI repos](https://github.com/container-storage-interface/) where possible, to lower cognitive overhead.
* Start with just the spec and adapter repos, and wait to create the other repos until the architecture is finalized (do we want one sidecar or more? will there be one central controller? what will be the separation of between controllers and sidecars? etc.)
* So:
  * `cosi-grpc-interface` -> `container-object-storage-interface-spec`
  * `cosi-csi-driver` -> `container-object-storage-interface-csi-adapter` (CSI driver to bootstrap COSI workloads)
  * `cosi-controller`-> Drop for now
  * `cosi-sidecar-controller` -> Drop for now

**Comment by copejon** [comment]
> cosi-controller-> Drop for now
> cosi-sidecar-controller -> Drop for now

@saad-ali While we haven't hammered out a complete design for automation, it would still be beneficial to have a common space for prototyping.  Is this work something we should handle out of band?

**Comment by saad-ali** [comment]
I guess my concern is are you boxing yourself in by having a single repo called `cosi-controller` and `cosi-sidecar-controller`. Are you going to want more then one COSI controller or sidecar in the future (given that CSI has more than one sidecar)?

**Comment by copejon** [comment]
Fair point, I think we'd be fine then with your suggested repos, with the architecture to follow once the design is settled on: 

1. `container-object-storage-interface-spec`
2. `container-object-storage-interface-csi-adapter`

**Comment by brahmaroutu** [comment]
I have updated the issue and I believe this will give us the start we need right now.
Please review and approve @saad-ali

**Comment by nikhita** [comment]
The repos have been created:

- https://github.com/kubernetes-sigs/container-object-storage-interface-spec
- https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter

Also created:

- https://github.com/kubernetes/org/pull/1956 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4895 - to add the repos to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by nikhita** [comment]
All PRs have merged :)

/close
