### ISSUE TITLE
REQUEST: New membership for mrmrcoleman

### ISSUE THREAD

**Issue by mrmrcoleman** [kubernetes/org#1946]
### GitHub Username
- @mrmrcoleman

### Organization you are requesting membership in
- @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timothysc
- @fabriziopandini

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/org/issues/1934

**Comment by timothysc** [comment]
+1 From me 
/lgtm 
/approve 

xref - https://github.com/kubernetes/org/issues/1934

**Comment by jdumars** [comment]
also happy to sponsor with a +1

**Comment by fabriziopandini** [comment]
+1
To kick start the cluster-api-provider-packet work

**Comment by nikhita** [comment]
@mrmrcoleman thank you for kick starting the cluster-api-provider-packet work :)

I've created PR #1948 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by mrmrcoleman** [comment]
Thanks @nikhita !
