### ISSUE TITLE
REQUEST: New membership for gianarb

### ISSUE THREAD

**Issue by gianarb** [kubernetes/org#1949]
### GitHub Username
@gianarb

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jdumars 
- @fabriziopandini

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/org/issues/1934

**Comment by nikhita** [comment]
@gianarb - both @timothysc and @fabriziopandini are from VMware and sponsors need to have different employers. I would have been happy to act as a sponsor, but I'm from VMware too :upside_down_face:

**Comment by gianarb** [comment]
I didn't realize that!! :D I added @jdumars to the party!! :D

**Comment by nikhita** [comment]
Oh just realized you don't really need sponsors, since you are already a member of the @kubernetes github org. :smile: 

Feel free to create a PR to add yourself and I'll approve it!
