### ISSUE TITLE
REQUEST: New membership for gnufied

### ISSUE THREAD

**Issue by gnufied** [kubernetes/org#1951]
### GitHub Username
gnufied

### Organization you are requesting membership in
kubernetes-sig

### Requirements
- [ x ]  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x ] I am actively contributing to 1 or more Kubernetes subprojects
- [ x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @msau42 
- @jsafrane 

### List of contributions to the Kubernetes project
- I am co-maintainer of EBS CSI and EBS in-tree driver 
- I am co-maintainer and frequent contributor to all aspects of sig-storage 
- I am already a member of kubernetes and kubernetes-csi org.

**Comment by nikhita** [comment]
@gnufied since you are already a member of the @kubernetes github org, you don't need sponsors. Feel free to create a PR directly and I'll approve it! :)

**Comment by gnufied** [comment]
@nikhita done - https://github.com/kubernetes/org/pull/1952 ! thank you.

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/org/pull/1952
