### ISSUE TITLE
REQUEST: New membership for jacobsmith928

### ISSUE THREAD

**Issue by jacobsmith928** [kubernetes/org#1953]
### GitHub Username
@jacobsmith928 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timothysc
- @jdumars

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/org/issues/1934

**Comment by gianarb** [comment]
As soon as the sponsors will approve I will make the PR 👍

**Comment by jdumars** [comment]
/approve

Welcome to the org!
