### ISSUE TITLE
REQUEST: New membership for knight42

### ISSUE THREAD

**Issue by knight42** [kubernetes/org#1955]
### GitHub Username
@knight42

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @soltysh 
- @caesarxuchao 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/pulls?q=is%3Apr+author%3Aknight42+org%3Akubernetes
for instance:
https://github.com/kubernetes/kubernetes/pull/80572
https://github.com/kubernetes/kubernetes/pull/80699
https://github.com/kubernetes/kubernetes/pull/81342
https://github.com/kubernetes/kubernetes/pull/89505
https://github.com/kubernetes/kubernetes/pull/91616
https://github.com/kubernetes/kubernetes/pull/92163 (in progress)
https://github.com/kubernetes/kubernetes/pull/92343 (in progress)

- Issues responded to
https://github.com/issues?q=is%3Aissue+org%3Akubernetes+involves%3Aknight42
for instance:
https://github.com/kubernetes/kubernetes/issues/92280
https://github.com/kubernetes/kubectl/issues/884
https://github.com/kubernetes/kubernetes/issues/91876
https://github.com/kubernetes/kubernetes/issues/91565
https://github.com/kubernetes/kubernetes/issues/91404
https://github.com/kubernetes/kubernetes/issues/90047

- SIG projects I am involved with
sig-cli
sig-apimahinery

**Comment by caesarxuchao** [comment]
+1

**Comment by soltysh** [comment]
:+1:

**Comment by nikhita** [comment]
@knight42 thank you for all your contributors to sig api-machinery and sig cli so far :)

I've created PR #1961 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
