### ISSUE TITLE
REQUEST: New membership for deitch

### ISSUE THREAD

**Issue by deitch** [kubernetes/org#1957]
### GitHub Username
@deitch

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timothysc
- @jdumars

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/org/issues/1934

cc @gianarb 
ref #1934

**Comment by jdumars** [comment]
Can you confirm you are subscribed to kubernetes-dev mailing list please?  :) I will approve once that box is checked.

**Comment by deitch** [comment]
Ha, I missed that. Subscribed to so many mailing lists that I passed it and said, "I cannot recall, I will check it afterwards", and promptly forgot. I will resubscribe if I am not now.

**Comment by deitch** [comment]
Confirmed.

**Comment by jdumars** [comment]
Great! Thank you.
/approve 

Welcome to the org!

**Comment by deitch** [comment]
Thanks @jdumars . Happy to be here!
