### ISSUE TITLE
REQUEST: New membership for emilym1

### ISSUE THREAD

**Issue by EmilyM1** [kubernetes/org#1959]
### GitHub Username
@emilym1

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/22039
https://github.com/kubernetes/website/pull/22063

- Issues responded to
https://github.com/kubernetes/kube-state-metrics/issues/554
https://github.com/kubernetes/kube-state-metrics/issues/555

- SIG projects I am involved with
Joining sig node

**Comment by dims** [comment]
+1 welcome!

**Comment by parispittman** [comment]
100% +1

yay welcome

**Comment by nikhita** [comment]
@EmilyM1 thank you for all your contributors so far and thanks for participating with sig node :)

I've created PR #1961 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
