### ISSUE TITLE
Create repository for cluster-api-provider-digitalocean as a SIG Cluster Lifecycle subproject

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/org#196]
### New Repo, Staging Repo, or migrate existing
migrate repository.
Original repository: https://github.com/kubermatic/cluster-api-provider-digitalocean

### Requested name for new repository
cluster-api-provider-digitalocean

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
SIG-Cluster-Lifecycle leads:
- luxas
- roberthbailey
- timothysc

DO provider maintainers:
- xmudrii

### If not a staging repo, who should have write access
OWNERS file defined here: https://github.com/kubermatic/cluster-api-provider-digitalocean/blob/master/OWNERS_ALIASES

### What should the repo description be
The DigitalOcean provider implementation of the Cluster Management API

### What SIG and subproject does this fall under in sigs.yaml
This is a subproject for SIG-Cluster-Lifecycle and Cluster-API

### Approvals
1. SIG-Cluster-Lifecycle discussed and approved upstreaming this Cluster-API provider on the meeting held on 10/23. [Meeting notes](https://docs.google.com/document/d/1deJYPIF4LmhGjDVaqrswErIrV7mtwJgovtLnPCDxP7U/edit#heading=h.u0dmn4xhr8u1) and [Recording (discussion about this starts at 21:22)](https://youtu.be/ECKy4Ql9A74?t=1282)
1. [SIG-Cluster-Lifecycle mailing post for lazy consensus](https://groups.google.com/d/msg/kubernetes-sig-cluster-lifecycle/rvCtQRuE4J4/aAfXzywvBAAJ). There is also approval by SIG leads in this thread.
1. The repository uses Apache License v2: https://github.com/kubermatic/cluster-api-provider-digitalocean/blob/master/LICENSE
1. Kubernetes Community Code of Conduct is adopted: https://github.com/kubermatic/cluster-api-provider-digitalocean/blob/master/code-of-conduct.md
1. [All contributors listed on GitHub](https://github.com/kubermatic/cluster-api-provider-digitalocean/graphs/contributors) are active contributors to Kubernetes project, so they have CNCF CLA signed.
1. @nikhita has done Dependency License checks and the results are available on [the mailing list post](https://groups.google.com/d/msg/kubernetes-sig-cluster-lifecycle/rvCtQRuE4J4/i0nanNk_BwAJ).

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

### Additional context for request
Any additional information or context to describe the request.

TODO:
1. Update [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) once the repository is transferred.

/area github-repo

**Comment by cblecker** [comment]
@nikhita The only open question I have is around webhooks and automation. Looks like you have an external prow, CircleCI, and zenhub configured. Will these continue to be used?

**Comment by cblecker** [comment]
@xmudrii Sounds good.

**Comment by cblecker** [comment]
@xmudrii Initial transfer is complete. Automation should kick in soon. Can you have a look around and see if everything is right?

sigs.yaml can now be updated too

**Comment by xmudrii** [comment]
@cblecker Will do that now. I'll create a PR for sigs.yaml too :)

**Comment by xmudrii** [comment]
@cblecker Created a pull request to add project to `sigs.yaml` https://github.com/kubernetes/community/pull/2864

**Comment by xmudrii** [comment]
@cblecker I'm going thorough the repository right now and most of things seems okay! :slightly_smiling_face: 

I have several questions:

1. I see CircleCI webhook enabled. Is CircleCI usable until we migrate testing to Prow?
1. Regarding Cluster-API DigitalOcean Maintainers Kubernetes SIGs team (https://github.com/orgs/kubernetes-sigs/teams/cluster-api-provider-digitalocean-maintainers), I see only me, Robert and Tim. Is this as expected or other maintainers should be present as well?
1. The `master` branch is not protected anymore. Is there any defaults that we should establish? Are you going to handle this or can I do it?
1. Will CNCF CLA bot be set up by you?
1. Is there anything else we should pay attention to now? :) 

Some TODOs that are here for reference what we should do now that migration is done:
- [x] Update README in Cluster-API repository with new URL
- [ ] Update all URLs in current project documentation (e.g. update Go Report Card, etc)
- [ ] Update Go import paths to reflect migration
- [ ] Follow up with SIG Testing about moving to Prow and moving Docker images

I'll continue verifying the repository and will follow up if I find anything. Thank you so much for everything! :tada: :smile:

**Comment by cblecker** [comment]
1. CircleCI will continue to function.
2. You've been given maintainer abilities on the team, so you can add others at will.
3. Branch protection will automatically kick in automatically on a cron
4. CLA bot is automatic on all repos in k-sigs

Basic prow functions (like the bot, labels, etc) will start functioning immediately. If you want to enforce the use of CircleCI until you can move to prow, you can add additional required contexts here: https://github.com/kubernetes/test-infra/blob/753c67473c9054c4978d8bfda81be8840ba9c23c/prow/config.yaml#L288

But things like auto merging on lgtm/approve and stuff like that should already be active.

**Comment by cblecker** [comment]
oh, and for go import path, you can use `sigs.k8s.io/cluster-api-provider-digitalocean/...` if you like (the github path will work too)

**Comment by xmudrii** [comment]
@cblecker Once again, thank you so much! We're so happy to see this provider upstreamed and migrated to Kubernetes SIGs.

> 1. CircleCI will continue to function.

Great! I've asked on #sig-testing about moving forward on this. We will try to get this sorted out soonly.

> 2. You've been given maintainer abilities on the team, so you can add others at will.

Sounds good. I've already added Nikhita and Alvaro. We will add Andrew once he joins the Kubernetes SIGs organization (he is Kubernetes member already).

> 3. Branch protection will automatically kick in automatically on a cron

Can confirm it is configured now. :slightly_smiling_face:

> 4. CLA bot is automatic on all repos in k-sigs

Sounds good :+1: 

> Basic prow functions (like the bot, labels, etc) will start functioning immediately. If you want to enforce the use of CircleCI until you can move to prow, you can add additional required contexts here: https://github.com/kubernetes/test-infra/blob/753c67473c9054c4978d8bfda81be8840ba9c23c/prow/config.yaml#L288

One more question regarding `prow/config.yaml`: is there need to add the repository here? I see some of Cluster-API repositories are already listed https://github.com/kubernetes/test-infra/blob/753c67473c9054c4978d8bfda81be8840ba9c23c/prow/config.yaml#L418-L421

I will add CircleCI contexts as well.

> But things like auto merging on lgtm/approve and stuff like that should already be active.

It seems like basic commands works, at least `/meow` works :smile: 

> oh, and for go import path, you can use sigs.k8s.io/cluster-api-provider-digitalocean/... if you like (the github path will work too)

Sounds great, I'll update this as soon as possible!

**Comment by cblecker** [comment]
you only have to add the squash command if you want all PRs to squash merge, instead of a regular git merge.

**Comment by xmudrii** [comment]
@cblecker Great! Created a PR to add merge method and required checks https://github.com/kubernetes/test-infra/pull/9938, hope it's okay :slightly_smiling_face:

**Comment by nikhita** [comment]
Sorry for the delay here, I had logged off for the day. :grimacing: 

@cblecker Thanks for handling that so quick! Do you think this issue can be closed now?

PRs to add the new repo to sigs.yaml (https://github.com/kubernetes/community/pull/2864) and add the necessary required contexts to prow (https://github.com/kubernetes/test-infra/pull/9938) have been created.

**Comment by nikhita** [comment]
Bump.

@cblecker can this be closed? :)

**Comment by cblecker** [comment]
This looks done!
/close
