### ISSUE TITLE
kubernetes-sigs membership issue for yuanchen8911

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/org#1964]
I'm a kubernetes org member and submitted a PR (https://github.com/kubernetes/org/pull/1963) for kubernetes-sigs membership. The PR was approved and merged yesterday.  

However, my name is not included in the [kubernetes-sigs member list](https://github.com/orgs/kubernetes-sigs/people).  
My profile does not show the new org either. I was wondering if it just takes time or something is wrong. Thanks.

**Comment by nikhita** [comment]
I can see a pending invitation for you. If you go to https://github.com/kubernetes-sigs, you should see a link to accept the invite.

**Comment by yuanchen8911** [comment]
> I can see a pending invitation for you. If you go to https://github.com/kubernetes-sigs, you should see a link to accept the invite. 

Thanks, it works.

**Comment by nikhita** [comment]
Closing :)
