### ISSUE TITLE
REQUEST: New membership for SergeyKanzhelev

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/org#1965]
### GitHub Username

@SergeyKanzhelev

### Organization you are requesting membership in

@kubernetes
@kubernetes-sigs 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dchen1107 
- @matthyx

### List of contributions to the Kubernetes project
- PRs merged:
   - https://github.com/kubernetes/kubernetes/pull/91971
  - https://github.com/kubernetes/kubernetes/pull/91303
- a few PRs reviewed in sig/node in kubernetes and critools repository. Some highlights:
  - https://github.com/kubernetes/kubernetes/pull/92196
  - https://github.com/kubernetes/kubernetes/pull/92239
  -  https://github.com/kubernetes/kubernetes/pull/92385
  - https://github.com/kubernetes/kubernetes/pull/92465
- SIG projects I am involved with
  - SIG node

**Comment by dchen1107** [comment]
Welcome!

Sergey, thank you again for your help.

**Comment by matthyx** [comment]
+1 welcome Sergey!

**Comment by mrbobbytables** [comment]
@SergeyKanzhelev, thank you for all your contributions so far :)

I've created PR #1968  to add you to both the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them \o/

Welcome to @kubernetes! 🎉

/assign
