### ISSUE TITLE
REQUEST: New membership for saikat-royc

### ISSUE THREAD

**Issue by saikat-royc** [kubernetes/org#1966]
### GitHub Username
@saikat-royc

### Organization you are requesting membership in
kubernetes, kubernetes-sigs, kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @msau42 
- @gnufied 

### List of contributions to the Kubernetes project
- PR: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Asaikat-royc, https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pulls?q=is%3Apr+author%3Asaikat-royc, https://github.com/kubernetes-csi/external-resizer/pulls?q=is%3Apr+author%3Asaikat-royc
- Issues responded to: https://github.com/pulls?q=is%3Apr+mentions%3Asaikat-royc+archived%3Afalse+
- SIG projects: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, https://github.com/kubernetes-sigs/gcp-filestore-csi-driver

**Comment by msau42** [comment]
+1! Saikat has been actively working on snapshots and csi in general for sig-storage.

**Comment by gnufied** [comment]
+1

**Comment by nikhita** [comment]
@saikat-royc thank you for all your contributors with sig storage so far :)

I've created PR #1980 to add you to the 3 GitHub orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
