### ISSUE TITLE
REQUEST: New membership for kaslin

### ISSUE THREAD

**Issue by kaslin** [kubernetes/org#1967]
### GitHub Username
@kaslin

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman
- @mrbobbytables   

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/community/pull/4758
- Issues responded to
https://github.com/kubernetes/community/issues/4798 (created)
https://github.com/kubernetes/community/issues/3654 (mentioned in)
- SIG projects I am involved with
sig-contribex

**Comment by mrbobbytables** [comment]
+1 from me :) 
/pony party

**Comment by parispittman** [comment]
+1

**Comment by mrbobbytables** [comment]
@kaslin, thank you for all your help with the marketing team :)

I've created PR #1968   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
