### ISSUE TITLE
REQUEST: New repo sigs.k8s.io/mcs-api

### ISSUE THREAD

**Issue by JeremyOT** [kubernetes/org#1970]
### New Repo, Staging Repo, or migrate existing
New repo

### Requested name for new repository
sigs.k8s.io/mcs-api

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@pmorie 
@JeremyOT 

### If not a staging repo, who should have write access
@pmorie 
@JeremyOT 

### If not a staging repo, who should be listed as approvers in OWNERS
@pmorie 
@JeremyOT 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@pmorie 
@JeremyOT 

### What should the repo description be
This repository hosts the Multi-Cluster Service APIs. Providers can import packages in this repo to ensure their multi-cluster service controller implementations will be compatible with MCS data planes.

### What SIG and subproject does this fall under in sigs.yaml
This is part of a new Multi-Cluster Services subproject for `sig-multicluster` called `mcs-api`

### Approvals
@pmorie 

### Additional context for request

KEP: [1645](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api)
Discussion on approaches: http://bit.ly/k8s-mcs-repo-discussion
Thread: https://groups.google.com/forum/?oldui=1#!topic/kubernetes-sig-architecture/tzn9cfULDfw

**Comment by andrewsykim** [comment]
+1 from me!

**Comment by RainbowMango** [comment]
Wouldn't it be better to have a full name? such as `multi-cluster-service-api`?

**Comment by JeremyOT** [comment]
I don't have strong preference for the name (multi-cluster-service-api would be fine), but shorter seems better

**Comment by pmorie** [comment]
I also prefer shorter, I'm +1 on creating this repo now that the direction seems to be reasonably settled.

**Comment by JeremyOT** [comment]
Thanks! I believe with that we have the approval we need

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/mcs-api

Also created:
- https://github.com/kubernetes/org/pull/2090 - to add GitHub teams for granting access
- https://github.com/kubernetes/community/pull/5012 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/5022 has merged. Closing.
