### ISSUE TITLE
Contributor-tweets repo creation

### ISSUE THREAD

**Issue by kaslin** [kubernetes/org#1971]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
contributor-tweets

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
sig-contributor-experience-leads (@mrbobbytables, @castrojo, @cblecker, @nikhita)

### If not a staging repo, who should have write access
sig-contributor-experience-leads (@mrbobbytables, @castrojo, @cblecker, @nikhita)

### If not a staging repo, who should be listed as approvers in OWNERS
@parispittman
@chris-short
@kaslin
@mbbroberg 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
sig-contributor-experience-leads (@mrbobbytables, @castrojo, @cblecker, @nikhita)
@parispittman
@chris-short
@kaslin

### What should the repo description be
Repo for automating tweets to the K8sContributor twitter account owned by the k8s Upstream Marketing Team within SIG-contribex (https://github.com/kubernetes/community/tree/master/communication/marketing-team).

### What SIG and subproject does this fall under in sigs.yaml
this is part of the k8s upstream marketing (contributor-comms) group within sig-contribex

### Approvals
Link to email thread:
https://groups.google.com/g/kubernetes-sig-contribex/c/FiRPTzneK7I/m/86F7teAkCAAJ
Link to meeting minutes for k8s upstream marketing where the need for automation for the twitter account was discussed: https://docs.google.com/document/d/1KDoqbw2A6W7rLSbIRuOlqH8gkoOnp2IHHuV9KyJDD2c/edit

/cc @parispittman

**Comment by mrbobbytables** [comment]
The repo has been create: https://github.com/kubernetes-sigs/contributor-tweets
Membership and teams have been added: https://github.com/kubernetes/org/pull/1981
Once https://github.com/kubernetes/community/pull/4914 merges adding it as a subproject under contribex is merged everything should be good to go \o/

**Comment by mrbobbytables** [comment]
All parts are merged and complete, going to go ahead and close this out :)
Happy tweeting~

/close
