### ISSUE TITLE
REQUEST: New membership for JeremyOT

### ISSUE THREAD

**Issue by JeremyOT** [kubernetes/org#1973]
### GitHub Username
@JeremyOT

### Organization you are requesting membership in
@kubernetes, @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pmorie
- @thockin

### List of contributions to the Kubernetes project
- PRs:
    - https://github.com/kubernetes/enhancements/pulls?q=is%3Apr+author%3AJeremyOT
    - https://github.com/kubernetes/community/pulls?q=is%3Apr+author%3AJeremyOT
- SIG projects:
    - sig-multicluster - Multi-Cluster Services
        - [KEP-1645](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api)
        - [API draft design](https://docs.google.com/document/d/1hFtp8X7dzVS-JbfA5xuPvI_DNISctEbJSorFnY-nz6o)
        - Frequent presenter at SIG meetings - [Meeting Notes](https://docs.google.com/document/d/18mk62nOXE_MCSSnb4yJD_8UadtzJrYyJxFwbrgabHe8)
    - sig-network - service-apis
        - Contributor for L4 design [Meeting Notes](https://docs.google.com/document/d/1eg-YjOHaQ7UD28htdNxBR3zufebozXKyI28cl2E11tU)

**Comment by pmorie** [comment]
+1

**Comment by thockin** [comment]
+1

**Comment by nikhita** [comment]
@JeremyOT thank you for all your contributors so far :)

I've created PR #1980 to add you to the Kubernetes and Kubernetes SIGs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
