### ISSUE TITLE
REQUEST: New membership for lixiang233

### ISSUE THREAD

**Issue by lixiang233** [kubernetes/org#1974]
### GitHub Username
@lixiang233

### Organization you are requesting membership in
@kubernetes-sigs
### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ingvagabund
- @seanmalloy

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/descheduler/pulls?q=is%3Apr+author%3Alixiang233
- Issues responded to
https://github.com/kubernetes-sigs/descheduler/issues?q=is%3Aissue+author%3Alixiang233+
- SIG projects I am involved with
[kubernetes-sigs/descheduler](https://github.com/kubernetes-sigs/descheduler)

**Comment by seanmalloy** [comment]
+1

**Comment by ingvagabund** [comment]
+1

**Comment by nikhita** [comment]
@lixiang233, thank you for all your contributions to descheduler so far :)

I've created PR #2000 (what a PR number! :)) to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
