### ISSUE TITLE
REQUEST: New membership for spurin

### ISSUE THREAD

**Issue by spurin** [kubernetes/org#1975]
### GitHub Username
@spurin

### Organization you are requesting membership in
@kubernetes, @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @irvifa 
- @zacharysarah 

##### Merged

|Description|Origin (Created by me)|Origin (Created by others)|FR Equivalent|ID Equivalent|JA Equivalent|KO Equivalent|ZH Equivalent|
|-----------|----------------------|--------------------------|-------------|-------------|-------------|-------------|-------------|
|Nslookup target to include fully qualified service name|[PR19603](https://github.com/kubernetes/website/pull/19603)||[PR19603](https://github.com/kubernetes/website/pull/19603)|[PR19603](https://github.com/kubernetes/website/pull/19603)|[PR19603](https://github.com/kubernetes/website/pull/19603)|[PR19603](https://github.com/kubernetes/website/pull/19603)|[PR19603](https://github.com/kubernetes/website/pull/19603)|
|Add note, regarding example requirement for nfs helper /sbin/mount.nfs|[PR19774](https://github.com/kubernetes/website/pull/19774)||[PR19807](https://github.com/kubernetes/website/pull/19807)|[PR19808](https://github.com/kubernetes/website/pull/19808)||||||
|Remove Namespace specifics for horizontal pod autoscale walkthrough|[PR20555](https://github.com/kubernetes/website/pull/20555)|||||[PR20563](https://github.com/kubernetes/website/pull/20563)|[PR20564](https://github.com/kubernetes/website/pull/20564)|
|update storage-classes pv section link||[PR22108](https://github.com/kubernetes/website/pull/22108) [ISSUE:22107](https://github.com/kubernetes/website/issues/22107)||[PR22109](https://github.com/kubernetes/website/pull/22109)||||

##### Feedback

|Description|Links|
|-----------|-----|
|Fix dead link of api-conventions doc (ja)|[PR19801](https://github.com/kubernetes/website/pull/19801)|
|replace http helm link with https|[PR19803](https://github.com/kubernetes/website/pull/19803)|
|Update minikube documentation|[PR19756](https://github.com/kubernetes/website/pull/19756)|

## SIG projects I am involved with

sig-docs

**Comment by irvifa** [comment]
👍 from me thanks for your contributions @spurin

**Comment by zacharysarah** [comment]
+1, thanks for your contributions so far!

**Comment by nikhita** [comment]
@spurin thank you for all your contributors with sig docs so far and thank you for creating such a wonderfully detailed table in the issue body! :raised_hands: 

I've created PR #1980 to add you to the Kubernetes and Kubernetes SIGs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
