### ISSUE TITLE
Repo creation request: kubernetes-sigs/kubetest2

### ISSUE THREAD

**Issue by amwat** [kubernetes/org#1977]
### New Repo, Staging Repo, or migrate existing
new repository (will move https://github.com/kubernetes/test-infra/tree/master/kubetest2 into this repository)

### Requested name for new repository
`kubetest2`
### Which Organization should it reside
`kubernetes-sigs`

### If not a staging repo, who should have admin access
@amwat 
@BenTheElder 
@spiffxp 

### If not a staging repo, who should have write access
@amwat 
@BenTheElder 
@spiffxp 

### If not a staging repo, who should be listed as approvers in OWNERS
@amwat 
@BenTheElder 
@spiffxp 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@amwat 
@BenTheElder 
@spiffxp 

### What should the repo description be
Kubetest2 is the framework for launching and running end-to-end tests on kubernetes.

### What SIG and subproject does this fall under in sigs.yaml
this is part of the kubetest2 subproject for sig-testing 
https://github.com/kubernetes/community/tree/master/sig-testing#kubetest2
https://github.com/kubernetes/community/blob/master/sigs.yaml#L2160

### Approvals
I am one of the existing approvers for kubetest2 https://github.com/kubernetes/test-infra/blob/master/kubetest2/OWNERS

This was discussed at a sig-testing biweekly meeting ([video recording](https://www.youtube.com/watch?v=m3vd5OlpAhY), [notes](https://docs.google.com/document/d/1z8MQpr_jTwhmjLMUaqQyBk1EYG_Y_3D4y4YdMJ7V1Kk/edit#heading=h.ksijlng7t2ta)) where I also shared a [doc](https://docs.google.com/document/d/10Zfu0KiJVMxHL-rNMW9pOESdFcdCuw2ABrDFKVQqooM/edit?usp=sharing) suggesting this repository move, among other items.

### Additional context for request
n/a

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/kubetest2 :tada: 

Also created:

- https://github.com/kubernetes/org/pull/1979 - to create GitHub teams to grant access
- https://github.com/kubernetes/community/pull/4911 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by BenTheElder** [comment]
thanks @nikhita! following up on these now

**Comment by nikhita** [comment]
Teams have been setup and repo has been added to sigs.yaml

/close
