### ISSUE TITLE
REQUEST: New membership for hakman

### ISSUE THREAD

**Issue by hakman** [kubernetes/org#1985]
### GitHub Username
@hakman

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
I am already a member in @kubernetes.
Ref: https://github.com/kubernetes/org/issues/1514

### Sponsors
n/a

### List of contributions to the Kubernetes project
n/a

**Comment by nikhita** [comment]
@hakman I've created https://github.com/kubernetes/org/pull/1986 to add you to @kubernetes-sigs. Since you are already a member of @kubernetes and don't need sponsors, feel free to lgtm the PR directly to get it merged :)
