### ISSUE TITLE
REQUEST: New membership for emedina

### ISSUE THREAD

**Issue by emedina** [kubernetes/org#1990]
### GitHub Username
emedina

### Organization you are requesting membership in
kubernetes/org

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @raelga 
- @remyleone

### List of contributions to the Kubernetes project
- Translation of the documentation to Spanish
https://github.com/kubernetes/website/pull/13641
https://github.com/kubernetes/website/pull/13643
https://github.com/kubernetes/website/pull/13658
https://github.com/kubernetes/website/pull/13659
https://github.com/kubernetes/website/pull/13880
https://github.com/kubernetes/website/pull/13946
https://github.com/kubernetes/website/pull/14026
https://github.com/kubernetes/website/pull/14850
https://github.com/kubernetes/website/pull/14851
https://github.com/kubernetes/website/pull/14852
https://github.com/kubernetes/website/pull/13981

**Comment by raelga** [comment]
Heavy +1 to @emedina, has been doing amazing contributions to the spanish content and will be a great reviewer!

**Comment by remyleone** [comment]
👍
