### ISSUE TITLE
REQUEST: New membership for kishorj

### ISSUE THREAD

**Issue by kishorj** [kubernetes/org#1995]
### GitHub Username
@kishorj

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @M00nF1sh
- @a_sykim

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/kubernetes/kubernetes/pulls?q=kishorj
   - https://github.com/kubernetes-sigs/aws-load-balancer-controller/pulls?q=is%3Apr+kishorj
- Issues responded to
   - https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+kishorj 
   - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues?q=is%3Aissue+kishorj
- SIG projects I am involved with
   - kubernetes-sigs/aws-load-balancer-controller

**Comment by M00nF1sh** [comment]
+1

**Comment by micahhausler** [comment]
+1

**Comment by nikhita** [comment]
@kishorj sponsors need to have different employers. Can you please add another sponsor who is not from Amazon?

**Comment by kishorj** [comment]
> @kishorj sponsors need to have different employers. Can you please add another sponsor who is not from Amazon?

Both sponsors need to be from different employers?

**Comment by nikhita** [comment]
> Both sponsors need to be from different employers?

Yes, from https://github.com/kubernetes/community/blob/master/community-membership.md:

> Sponsors must be from multiple member companies to demonstrate integration across community.

**Comment by kishorj** [comment]
> > Both sponsors need to be from different employers?
> 
> Yes, from https://github.com/kubernetes/community/blob/master/community-membership.md:
> 
> > Sponsors must be from multiple member companies to demonstrate integration across community.

Thanks. I will withdraw my request for now.

**Comment by nikhita** [comment]
I'll close this issue then, but please reopen when you are ready. :)

**Comment by andrewsykim** [comment]
+1 :)

**Comment by M00nF1sh** [comment]
+1 :D

**Comment by nikhita** [comment]
@kishorj thank you for all your contributions so far \o/

I've created PR #2503 to add you to the Kubernetes and Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! 🎉

/assign
