### ISSUE TITLE
REQUEST: New membership for voor

### ISSUE THREAD

**Issue by voor** [kubernetes/org#1998]
### GitHub Username
`voor`

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @moshloop
- @randomvariable

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/cluster-api/pull/3034
- https://github.com/kubernetes-sigs/image-builder/pull/195
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1612
- https://github.com/kubernetes-sigs/image-builder/pull/170
- https://github.com/kubernetes-sigs/cluster-api/pull/2663
- https://github.com/kubernetes/kubernetes/pull/92219
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1597
- SIG Cluster Lifecycle
  - Cluster API
  - Cluster API AWS Provider
  - Cluster API VMware Provider
  - Cluster API Azure Provider
  - Image Builder

**Comment by nikhita** [comment]
+1 from me as well :smile:

**Comment by nikhita** [comment]
@voor, thank you for all your contributions to cluster api and image builder so far :)

I've created PR #2000 (what a PR number! :)) to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
