### ISSUE TITLE
REQUEST: New membership for phyber

### ISSUE THREAD

**Issue by phyber** [kubernetes/org#200]
### GitHub Username

@phyber

### Organization you are requesting membership in

  - @kubernetes
  - @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @detiber 
- @randomvariable 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - Authored
    - Cluster API Provider AWS
      - [machineactuator: Initial Delete implementation](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/80)
      - [machineactuator: Initial Update implementation](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/91)
      - [machineactuator: Update Tags and SecurityGroups implementation](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/104)
      - [services/ec2/instances: Add some more glogging to methods](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/183)
      - [bastion: Fix bastion code to always lookup via tags](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/216)
      - [machineactuator: Move some methods to more correct locations](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/232)
    - Cluster API
      - [Documentation: Basic internals docs](https://github.com/kubernetes-sigs/cluster-api/pull/542)
- Issues responded to (or involved with)
  - Cluster API Provider AWS
    - [Add README to ./cloud/aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/125)
    - [Makefile assume dep is installed via go toolchain](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/320)
    - [Unable to run generate-yaml.sh on Mac OS X](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/233)
    - [Need to reconcile instances better](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/173)
    - [machine actuator: Implement Delete](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/32)
    - [machine actuator: Implement Update](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/33)
- SIG projects I am involved with
  - SIG AWS
  - SIG Cluster Lifecycle

/area github-membership

**Comment by detiber** [comment]
+1 from me

**Comment by randomvariable** [comment]
+1 from me

**Comment by mrbobbytables** [comment]
Hey there @phyber , thanks for all the work you've done so far :)

I've created PR #207  to add you to both Kubernetes and the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
