### ISSUE TITLE
REQUEST: New membership for dominicgunn

### ISSUE THREAD

**Issue by dominicgunn** [kubernetes/org#2005]
### GitHub Username
dominicgunn

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@neolit123
@justinsb.

### List of contributions to the Kubernetes project
- PRs reviewed / authored
Lots of things under kube-aws
https://github.com/kubernetes-incubator/kube-aws/pull/1872
https://github.com/kubernetes-incubator/kube-aws/pull/1863
https://github.com/kubernetes-incubator/kube-aws/pull/1860
https://github.com/kubernetes-incubator/kube-aws/pull/1873
https://github.com/kubernetes-incubator/kube-aws/pull/1854
https://github.com/kubernetes-incubator/kube-aws/pull/1848

- Issues responded to
https://github.com/kubernetes-incubator/kube-aws/issues/1876
https://github.com/kubernetes-incubator/kube-aws/issues/1876

- SIG projects I am involved with
sig-cluster-lifecycle

**Comment by dominicgunn** [comment]
@nikhita, I haven't listed any sponsors explicitly as I haven't contacted anybody officially about sponsoring my joining the organizations, rather it feels a necessity per guidelines laid out for the movement of the kube-aws repository.

If required, I could reach out to the same sponsors of the project move per https://github.com/kubernetes/org/issues/2004

**Comment by nikhita** [comment]
@dominicgunn While it might just be formality for this one, we'd need sponsors since that's the process we follow for _all_ membership requests. :grimacing:

**Comment by dominicgunn** [comment]
No problem, I'll try and get that sorted.

**Comment by neolit123** [comment]
> @kubernetes

i think we can exclude the kubernetes org for now, unless you had prior contributions to projects in it.

**Comment by dominicgunn** [comment]
Sure, whatever helps get this across the line :)

**Comment by neolit123** [comment]
> Sure, whatever helps get this across the line :)

just remove `@kubernetes` from the issue description.

**Comment by dominicgunn** [comment]
Snipped!

**Comment by neolit123** [comment]
thanks.
+1, for the k-sig membership as the kube-aws maintainers have to be members, post the repository move from incubator.

**Comment by mrbobbytables** [comment]
With the plan to spin out kube-aws would you still like to apply for membership or should this be closed? :x

**Comment by dominicgunn** [comment]
Let's close this for now. II've got no immediate need for memebership given the spin-out of kube-aws.
