### ISSUE TITLE
REQUEST: New membership for onlydole

### ISSUE THREAD

**Issue by onlydole** [kubernetes/org#2006]
### GitHub Username
@onlydole 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @tengqm 

### List of contributions to the Kubernetes project
- [1.19 Release Lead](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/release_team.md)
- [Technical Lead for SIG Docs](https://github.com/kubernetes/org/blob/master/OWNERS_ALIASES#L45)

**Comment by mrbobbytables** [comment]
@onlydole you can PR yourself in as you're already a member of kubernetes 👍  If you don't need immediate access, we'll add you in later as a batch
