### ISSUE TITLE
REQUEST: New membership for mumoshu

### ISSUE THREAD

**Issue by mumoshu** [kubernetes/org#2007]
### GitHub Username
mumoshu

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123 
- @justinsb 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - [203 PRs authored in kube-aws](https://github.com/kubernetes-incubator/kube-aws/pulls?q=is%3Apr+is%3Aclosed+author%3Amumoshu+)
  - [262 PRs reviewed in kube-was](https://github.com/kubernetes-incubator/kube-aws/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3A%40me+)
- Issues responded to
  - [286 issues responded in kube-aws](https://github.com/kubernetes-incubator/kube-aws/issues?q=is%3Aissue+mumoshu+is%3Aclosed)
- SIG projects I am involved with
  - sig-cluster-lifecycle

**Comment by neolit123** [comment]
+1,
the kube-aws maintainers have to be members of k-sigs, post the repository move from incubator.

**Comment by mrbobbytables** [comment]
With the plan to spin out kube-aws would you still like to apply for membership or should this be closed? :x

**Comment by mrbobbytables** [comment]
Going to go ahead and close as kube-aws has been spun out. If you'd still like to pursue kubernetes-sigs org membership, please go ahead and reopen 👍 
/close
