### ISSUE TITLE
REQUEST: New membership for tossmilestone

### ISSUE THREAD

**Issue by tossmilestone** [kubernetes/org#201]
### GitHub Username
@tossmilestone

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bsalamat
- @k82cn

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Atossmilestone+
- Issues responded to
https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Atossmilestone
- SIG projects I am involved with
sig/scheduling, sig/api-machinery, sig/cli

/area github-membership

**Comment by bsalamat** [comment]
+1

**Comment by k82cn** [comment]
+1

**Comment by tossmilestone** [comment]
Thanks support from @bsalamat and @k82cn !

**Comment by mrbobbytables** [comment]
Hey there @tossmilestone  , thanks for all the contributions you've done so far :)

I've created PR #207 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by tossmilestone** [comment]
@mrbobbytables Thanks a lot!
