### ISSUE TITLE
REQUEST: New membership for rrati

### ISSUE THREAD

**Issue by rrati** [kubernetes/org#2016]
### GitHub Username
@rrati 

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @saad-ali 
- @xing-yang 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pull/53821
- https://github.com/kubernetes/kubernetes/pull/53809
- https://github.com/kubernetes/kubernetes/pull/52656
- https://github.com/kubernetes/kubernetes/pull/50329
- https://github.com/kubernetes/kubernetes/pull/49215
- https://github.com/kubernetes/kubernetes/pull/47919
- https://github.com/kubernetes/kubernetes/pull/47177
- https://github.com/kubernetes/kubernetes/pull/44680
- https://github.com/kubernetes/kubernetes/pull/40809
- https://github.com/kubernetes/kubernetes/pull/39478
- https://github.com/kubernetes/kubernetes/pull/37299
- https://github.com/kubernetes/kubernetes/pull/25968
- https://github.com/kubernetes/kubernetes/pull/25813
- https://github.com/kubernetes/kubernetes/pull/24142
- https://github.com/kubernetes/kubernetes/pull/23819
- https://github.com/kubernetes/kubernetes/pull/8809
- https://github.com/kubernetes/kubernetes/pull/8500
- https://github.com/kubernetes/kubernetes/pull/7573
- https://github.com/kubernetes/kubernetes/pull/6995
- https://github.com/kubernetes/kubernetes/pull/4223
- Kubernetes COSI

**Comment by xing-yang** [comment]
+1

**Comment by saad-ali** [comment]
+1
@rrati appears to have many contribution to k/k https://github.com/kubernetes/kubernetes/pulls?page=2&q=is%3Apr+author%3Arrati+is%3Aclosed and will be working on the Container Object Storage Interface effort.

**Comment by xing-yang** [comment]
@rrati Since you'll be working on COSI which is under kubernetes-sigs, you should also request membership in kubernetes-sigs.  Just add "kubernetes-sigs" under "kubernetes".

**Comment by rrati** [comment]
Done

**Comment by nikhita** [comment]
@rrati thank you for all your contributions so far :)

You are already a member of the @kubernetes org. :smile: 

I've created PR #2022 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
