### ISSUE TITLE
REQUEST: New membership for charleszheng44

### ISSUE THREAD

**Issue by charleszheng44** [kubernetes/org#2017]
### GitHub Username
@charleszheng44

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Fei-Guo
- @christopherhein 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/multi-tenancy/pull/829
https://github.com/kubernetes-sigs/multi-tenancy/pull/786
https://github.com/kubernetes-sigs/multi-tenancy/pull/682
https://github.com/kubernetes-sigs/multi-tenancy/pull/678
https://github.com/kubernetes-sigs/multi-tenancy/pull/668
https://github.com/kubernetes-sigs/multi-tenancy/pull/662
https://github.com/kubernetes-sigs/multi-tenancy/pull/648
https://github.com/kubernetes-sigs/multi-tenancy/pull/633
https://github.com/kubernetes-sigs/multi-tenancy/pull/610
https://github.com/kubernetes-sigs/multi-tenancy/pull/600
https://github.com/kubernetes-sigs/multi-tenancy/pull/562
https://github.com/kubernetes-sigs/multi-tenancy/pull/540
https://github.com/kubernetes-sigs/multi-tenancy/pull/527
https://github.com/kubernetes-sigs/multi-tenancy/pull/521
https://github.com/kubernetes-sigs/multi-tenancy/pull/517
https://github.com/kubernetes-sigs/multi-tenancy/pull/470
https://github.com/kubernetes-sigs/multi-tenancy/pull/461
https://github.com/kubernetes-sigs/multi-tenancy/pull/452
https://github.com/kubernetes-sigs/multi-tenancy/pull/440
https://github.com/kubernetes-sigs/multi-tenancy/pull/422
https://github.com/kubernetes-sigs/multi-tenancy/pull/393
https://github.com/kubernetes-sigs/multi-tenancy/pull/392
https://github.com/kubernetes-sigs/multi-tenancy/pull/389
https://github.com/kubernetes-sigs/multi-tenancy/pull/388
https://github.com/kubernetes-sigs/multi-tenancy/pull/382
https://github.com/kubernetes-sigs/multi-tenancy/pull/378
https://github.com/kubernetes-sigs/multi-tenancy/pull/375
https://github.com/kubernetes-sigs/multi-tenancy/pull/372
https://github.com/kubernetes-sigs/multi-tenancy/pull/365
https://github.com/kubernetes-sigs/multi-tenancy/pull/348
https://github.com/kubernetes-sigs/multi-tenancy/pull/346
https://github.com/kubernetes-sigs/multi-tenancy/pull/343
https://github.com/kubernetes-sigs/multi-tenancy/pull/338
https://github.com/kubernetes-sigs/multi-tenancy/pull/335
https://github.com/kubernetes-sigs/multi-tenancy/pull/311
https://github.com/kubernetes-sigs/multi-tenancy/pull/272
https://github.com/kubernetes-sigs/multi-tenancy/pull/229
https://github.com/kubernetes-sigs/multi-tenancy/pull/205
https://github.com/kubernetes-sigs/multi-tenancy/pull/204
https://github.com/kubernetes-sigs/multi-tenancy/pull/186
https://github.com/kubernetes-sigs/multi-tenancy/pull/182
https://github.com/kubernetes-sigs/multi-tenancy/pull/177
https://github.com/kubernetes-sigs/multi-tenancy/pull/167
https://github.com/kubernetes-sigs/multi-tenancy/pull/153
https://github.com/kubernetes-sigs/multi-tenancy/pull/141
https://github.com/kubernetes-sigs/multi-tenancy/pull/140
https://github.com/kubernetes-sigs/multi-tenancy/pull/139
https://github.com/kubernetes-sigs/multi-tenancy/pull/138
https://github.com/kubernetes-sigs/multi-tenancy/pull/137
https://github.com/kubernetes-sigs/multi-tenancy/pull/136
https://github.com/kubernetes-sigs/multi-tenancy/pull/135
https://github.com/kubernetes/kubernetes/pull/85188
https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/115

- Issues responded to
https://github.com/kubernetes-sigs/multi-tenancy/issues/477
https://github.com/kubernetes-sigs/multi-tenancy/issues/425
https://github.com/kubernetes-sigs/multi-tenancy/issues/391
https://github.com/kubernetes-sigs/multi-tenancy/issues/390

- SIG projects I am involved with
kubernetes-sigs/multi-tenancy
kubernetes-sigs/apiserver-network-proxy

**Comment by Fei-Guo** [comment]
+1 
Chao has been actively working on virtual cluster project in SIG multi-tenancy. I strongly support him to be SIG member.

**Comment by christopherhein** [comment]
+1
Fully support Chao becoming a Org member.

**Comment by nikhita** [comment]
@charleszheng44 thank you for all your contributions so far :)

We require that sponsors be reviewers/approvers for the orgs that they are sponsoring for. @Fei-Guo and @christopherhein can sponsor you for kubernetes-sigs, but cannot act as sponsors for the @kubernetes org. If you need membership to kubernetes, please create a new issue with additional sponsors.

To that end, I've created https://github.com/kubernetes/org/pull/2022 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! :tada: 

/assign
