### ISSUE TITLE
Add carolynvs as adminstrator to kubernetes-sigs/minibroker

### ISSUE THREAD

**Issue by carolynvs** [kubernetes/org#2019]
### Organization or repository
kubernetes-sigs/minibroker

### Users affected
carolynvs

### Describe the issue
When I donated minibroker, no one was made admin or given write access. So we can't tag new releases right now. We also have been having trouble with our travis builds occasionally because no one is an admin (we can't do things like cancel builds or configure settings). It would really help if I could be made an admin of the minibroker repo to cut releases and deal with administrative issues that arise.

Thanks! 🙇‍♀️

**Comment by nikhita** [comment]
/assign 

created https://github.com/kubernetes/org/pull/2021 :)
