### ISSUE TITLE
REQUEST: New membership for Bobgy

### ISSUE THREAD

**Issue by Bobgy** [kubernetes/org#2023]
### GitHub Username
@Bobgy

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ ] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jlewi
- (at)sponsor-2

### List of contributions to the Kubernetes project
- PRs reviewed / authored
PRs in kubernetes/test-infra for Kubeflow test config
https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3ABobgy+is%3Aclosed
- Issues responded to
- SIG projects I am involved with

**Comment by Bobgy** [comment]
Per discussion in https://github.com/kubernetes/test-infra/pull/18122#issuecomment-655804414,

I need kubernetes group membership to help Kubeflow maintain its test infra on kubernetes/test-infra, to be added as OWNER, lgtm, approve, etc.

This is kind of awkward, because I don't contribute to kubernetes. Can we allow this exception case?

**Comment by Bobgy** [comment]
@jlewi what dev estimate would you give for moving to https://github.com/GoogleCloudPlatform/oss-test-infra?

probably after KF 1.1 release can be a good timing?

**Comment by nikhita** [comment]
@Bobgy What would be the blockers to get kubeflow stuff moved to https://github.com/GoogleCloudPlatform/oss-test-infra today?

**Comment by jlewi** [comment]
Hi @nikhita I don't think anything is blocking it.
@clarketm was working on it and he completed the first half of it.
https://github.com/kubernetes/test-infra/issues/14343#issuecomment-658351189

So biggest blocker is probably just figuring out what work remains and who has cycles to do it.

**Comment by cblecker** [comment]
Yeah, I think the answer here is kubeflow should migrate off our prow instance: https://github.com/kubernetes/test-infra/issues/12863

**Comment by BenTheElder** [comment]
clarketm has moved on.

I agree that kubeflow should migrate off.

**Comment by jlewi** [comment]
@cblecker @BenTheElder I think we are all in agreement that we want to move kubeflow off the kubernetes instance. 

Should we close this PR and continue the discussion on kubernetes/test-infra#14343  to figure out what needs to happen next?

**Comment by Bobgy** [comment]
Thanks! Sounds good to me
