### ISSUE TITLE
Request for new repository: kubernetes-sigs/secret-sync-rotation

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/org#2026]
### New Repo, Staging Repo, or migrate existing
New repo

### Requested name for new repository
secret-sync-rotation

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
spiffxp, bentheelder

### If not a staging repo, who should have write access
spiffxp, bentheelder

### If not a staging repo, who should be listed as approvers in OWNERS
spiffxp, bentheelder

### If not a staging repo, who should be listed in SECURITY_CONTACTS
spiffxp, bentheelder

### What should the repo description be
Controllers to sync and rotate kubernetes secrets with google cloud secret manager

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject called secret-sync-rotation for sig-testing

### Approvals
The design proposal for this subproject was reviewed during today's SIG Testing meeting.  https://docs.google.com/document/d/1z8MQpr_jTwhmjLMUaqQyBk1EYG_Y_3D4y4YdMJ7V1Kk/edit

I approve of this as a chair of SIG Testing

### Additional context for request
We were originally trying to land this in kubernetes/test-infra but have been unable to do so due to bazel (ref: https://github.com/kubernetes/test-infra/pull/18244)

**Comment by BenTheElder** [comment]
+1, this will be super helpful work for WG-K8s and I expect some others may be interested in consuming this in the future.
We discussed this project in depth in the SIG meeting, no objections but some useful feedback :-)

Thanks for filing this @spiffxp

**Comment by mrbobbytables** [comment]
Repo has been created: https://github.com/kubernetes-sigs/secret-sync-rotation
Teams have been created and added to the repo: https://github.com/kubernetes/org/pull/2029
Subproject was added to sigs.yaml: https://github.com/kubernetes/community/pull/4963

Once https://github.com/kubernetes/community/pull/4963 is merged, this should be good to close \o/

**Comment by mrbobbytables** [comment]
Everything is merged, going to go ahead and close 👍 
/close

**Comment by BenTheElder** [comment]
thank you!
