### ISSUE TITLE
REQUEST: New membership for ginnyji

### ISSUE THREAD

**Issue by GinnyJI** [kubernetes/org#2028]
### GitHub Username
@ginnyji

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@tashimi 
@rjbez17  

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/multi-tenancy/pull/888
https://github.com/kubernetes-sigs/multi-tenancy/pull/884
https://github.com/kubernetes-sigs/multi-tenancy/pull/882
https://github.com/kubernetes-sigs/multi-tenancy/pull/860
https://github.com/kubernetes-sigs/multi-tenancy/pull/858
https://github.com/kubernetes-sigs/multi-tenancy/pull/842
https://github.com/kubernetes-sigs/multi-tenancy/pull/832

- Issues responded to
https://github.com/kubernetes-sigs/multi-tenancy/issues/881
https://github.com/kubernetes-sigs/multi-tenancy/issues/825

- SIG projects I am involved with
https://github.com/kubernetes-sigs/multi-tenancy

**Comment by rjbez17** [comment]
+1

Welcome!

**Comment by tashimi** [comment]
+1 , thanks for all your work on HNC so far!

![tenor-199545472](https://user-images.githubusercontent.com/719646/87477537-1e98dc00-c5dd-11ea-8f63-c977d8cf9b36.gif)

**Comment by mrbobbytables** [comment]
Just for clarification are you looking for membership to kubernetes or kubernetes-sigs? It looks like kubernetes-sigs :x

**Comment by adrianludwin** [comment]
That's right, it's k8s-sigs so she can work on wg-multitenancy

**Comment by nikhita** [comment]
@GinnyJI, thanks for all your contributions to multitenancy so far :)

I've created PR #2049 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
