### ISSUE TITLE
kubernetes-sigs membership for mirwan

### ISSUE THREAD

**Issue by mirwan** [kubernetes/org#203]
### GitHub Username
@mirwan

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects

I am a member of kubernetes-incubator (cf. #50 ), with [kubespray ](https://github.com/kubernetes-incubator/kubespray) moving out from it to kubernetes-sigs, I would need the membership.

/area github-membership

**Comment by justaugustus** [comment]
Thanks for contributing to kubespray! I'll take care of this. :)
/assign

**Comment by mirwan** [comment]
Thank you @justaugustus !

**Comment by justaugustus** [comment]
+1 to sponsor, given the circumstance.

Assuming sponsorship from @ant31, [given this comment](https://github.com/kubernetes/org/pull/212#issuecomment-434999724):
> @spiffxp all of them have been added recently to the incubator.
> If possible, I'll be one of the sponsors.
