### ISSUE TITLE
REQUEST: New membership for richardcase

### ISSUE THREAD

**Issue by richardcase** [kubernetes/org#2033]
### GitHub Username
@richardcase

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @randomvariable 
- @rudoi

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - [4 PRs in cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3Arichardcase)
  - [2 PRs in cluster-api-provider-azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+author%3Arichardcase) 
- Issues responded to
  - [8 issues raised in cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues?q=is%3Aissue+author%3Arichardcase)
  - [4 issues raised in cluster-api-provider-azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues?q=is%3Aissue+author%3Arichardcase)
- SIG projects I am involved with
   - sig-cluster-lifecycle

**Comment by rudoi** [comment]
+1 🎉

**Comment by randomvariable** [comment]
+1 :heart:

**Comment by mrbobbytables** [comment]
@richardcase  , thank you for all your contributions so far :)

I've created PR #2037  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
