### ISSUE TITLE
REQUEST: New membership for @nicoleyson

### ISSUE THREAD

**Issue by NicoleYson** [kubernetes/org#2034]
### GitHub Username
@nicoleyson

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rudoi
- @detiber

### List of contributions to the Kubernetes project
- PRs reviewed / authored: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1815
- SIG projects I am involved with: https://github.com/kubernetes-sigs/cluster-api-provider-aws

**Comment by rudoi** [comment]
👍 +1 yayayayay!

**Comment by detiber** [comment]
+1 from me as well

**Comment by banthaherder** [comment]
+1 from me too!

**Comment by randomvariable** [comment]
+1 from here!

**Comment by mrbobbytables** [comment]
@NicoleYson , thank you for all your contributions so far :)

I've created PR #2037  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by NicoleYson** [comment]
Thanks!!! 😄

**Comment by taiidani** [comment]
Late to the party but +1 as well!
