### ISSUE TITLE
REQUEST: New membership for michaelmdresser

### ISSUE THREAD

**Issue by michaelmdresser** [kubernetes/org#2040]
### GitHub Username
@michaelmdresser

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @amwat
- @cblecker 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/test-infra/pull/17858
https://github.com/kubernetes/test-infra/pull/17964
https://github.com/kubernetes/test-infra/pull/18004
https://github.com/kubernetes/test-infra/pull/18021
https://github.com/kubernetes/test-infra/pull/18020
https://github.com/kubernetes/test-infra/pull/18083
https://github.com/kubernetes/cloud-provider-gcp/pull/155
https://github.com/kubernetes/cloud-provider-gcp/pull/154
https://github.com/kubernetes/cloud-provider-gcp/pull/153
https://github.com/kubernetes/test-infra/pull/18124
https://github.com/kubernetes/test-infra/pull/18128
https://github.com/kubernetes/kubernetes/pull/92668
https://github.com/kubernetes-sigs/kubetest2/pull/4
- Issues responded to
  - https://github.com/kubernetes/test-infra/issues/14201
https://github.com/kubernetes/test-infra/issues/12346
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/kubetest2

**Comment by cblecker** [comment]
+1, thanks for your contributions so far!

**Comment by amwat** [comment]
+1 thanks for all your work!
would also encourage getting membership into the kubernetes-sigs org as well with all your contributions to kubetest2

**Comment by nikhita** [comment]
@michaelmdresser, thanks for all your help with test-infra \o/

I've created PR #2049  to add you to both the Kubernetes and Kubernetes SIGs Orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign
