### ISSUE TITLE
REQUEST: New membership for trutx

### ISSUE THREAD

**Issue by trutx** [kubernetes/org#2042]
### GitHub Username
@trutx

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @detiber
- @rudoi

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api/pull/2594
https://github.com/kubernetes-sigs/cluster-api/pull/2664
https://github.com/kubernetes/kubernetes/pull/87689
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/664

- Issues responded to

- SIG projects I am involved with
CAPI
CAPA
CABPK

**Comment by rudoi** [comment]
+1! 😎

**Comment by detiber** [comment]
+1 from me

**Comment by nikhita** [comment]
@trutx, thanks for all your contributions to cluster api so far :)

I've created PR #2049 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
