### ISSUE TITLE
REQUEST: New membership for sattarfeizollahibarough

### ISSUE THREAD

**Issue by sattarfeizollahibarough** [kubernetes/org#2058]
### GitHub Username
sattarfeizollahibarough

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @sftim 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   -https://github.com/kubernetes/org/pull/2051
   -https://github.com/cncf/foundation/pull/101
   -https://github.com/kubernetes/website/pull/22565
   -https://github.com/kubernetes/test-infra/pull/18369
- Issues responded to 
- SIG projects I am involved with
   -sig-docs

**Comment by sftim** [comment]
It's a :+1: from me @sattarfeizollahibarough

**Comment by sattarfeizollahibarough** [comment]
> 
> 
> It's a +1 from me @sattarfeizollahibarough

And I appreciate that :pray: @sftim

**Comment by zacharysarah** [comment]
The org should be `kubernetes` instead of `kubernetes-sigs`, otherwise +1 for our new Persian localization lead.

**Comment by sftim** [comment]
Ah yes, good spot @zacharysarah

**Comment by sattarfeizollahibarough** [comment]
I have modified that. @zacharysarah

**Comment by sattarfeizollahibarough** [comment]
Hi guys, @zacharysarah @sftim 
I hope you are doing well. I am sorry for bugging you. You have approved my membership request kindly, but the request is "open" now. What would be the next step? Thank you in advanced for your response.

**Comment by nikhita** [comment]
@sattarfeizollahibarough that would be on me :) 

Thanks for kickstarting the Persian localization for docs! :100: 

I've created PR #2061 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by sattarfeizollahibarough** [comment]
@nikhita Thank you so much.
