### ISSUE TITLE
REQUEST: New membership for ellistarn

### ISSUE THREAD

**Issue by ellistarn** [kubernetes/org#2068]
### GitHub Username
@ellistarn

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @shyamjvs 
- @MaciekPytel

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/autoscaler/pull/3363
  - https://github.com/kubernetes/kubernetes/pull/92549
  - https://github.com/kubernetes/kubernetes/pull/93201
  - https://github.com/kubernetes/autoscaler/pull/3373
- SIG projects I am involved with
  - SIG Autoscaling requested I become an owner of the Kubemark Cloud Provider: https://github.com/kubernetes/autoscaler/pull/3363, https://github.com/kubernetes/autoscaler/pull/3364

**Comment by shyamjvs** [comment]
+1

**Comment by MaciekPytel** [comment]
+1

**Comment by elmiko** [comment]
+1

**Comment by nikhita** [comment]
@ellistarn thanks for all your contributions with SIG Autoscaling :)

I've created PR #2086 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
