### ISSUE TITLE
REQUEST: New membership for brett-elliott

### ISSUE THREAD

**Issue by brett-elliott** [kubernetes/org#2070]
### GitHub Username
brett-elliott

### Organization you are requesting membership in
Kubernetes

### Requirements
- [ x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x ] I am actively contributing to 1 or more Kubernetes subprojects
- [ x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- gjtempleton
- MaciekPytel

### List of contributions to the Kubernetes project

https://github.com/kubernetes-sigs/metrics-server/pull/242
https://github.com/kubernetes/autoscaler/pull/3148
https://github.com/kubernetes/autoscaler/pull/3120
https://github.com/kubernetes/autoscaler/pull/3119

**Comment by mrbobbytables** [comment]
cc @gjtempleton @MaciekPytel

**Comment by MaciekPytel** [comment]
Sorry, I missed the PR. +1 from me, thanks for your ongoing contributions @brett-elliott

**Comment by gjtempleton** [comment]
+1 from me as well, thanks for your contributions so far, and look forward to seeing your future ones @brett-elliott !

**Comment by savitharaghunathan** [comment]
Hi @brett-elliott 👋, Thanks for all your help with autoscaler :) 

I've created PR #2108  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes!  🎉

/assign
