### ISSUE TITLE
REQUEST: membership for Arhell

### ISSUE THREAD

**Issue by Arhell** [kubernetes/org#2072]
### GitHub Username
@Arhell 

### Organization you are requesting membership in
[sig-docs website](https://github.com/kubernetes/website)

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@Potapy4
@msheldyakov

### List of contributions to the Kubernetes project
I am already a member of the organization, I need to add a user to the team
[PR in website repo](https://github.com/kubernetes/website/pull/22629) 
[PR in this repo](https://github.com/kubernetes/org/pull/2067)

**Comment by idvoretskyi** [comment]
@Arhell please mention your sponsors in the application and ask them to approve your request.

**Comment by idvoretskyi** [comment]
@Arhell my apologies, I've noticed that you are already an org member -https://github.com/kubernetes/org/blob/master/config/kubernetes/org.yaml#L87.

No need for this issue anymore, but thanks for submitting it.

/close
