### ISSUE TITLE
Clean up of Inactive Members -  August

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/org#2076]
This is the list of [inactive members](https://github.com/kubernetes/community/blob/master/communitymembership.md#inactive-members) that are slated to be removed from our Github Orgs. They have had no devstats recorded since the beginning of 2019.

**Inactive members**
- abhi
- abrarshivani
- adityakali
- ajaeger
- alejandroesc
- alfred-huangjian
- arschles
- benjigoldberg
- bobsky
- brejoc
- caoshufeng
- cheld
- colemickens
- david-mcmahon
- dhirajh
- dmyerscough
- dstorck
- euank
- guangxuli
- hhoover
- ideahitme
- k4leung4
- konryd
- lwander
- medinatiger
- mkurylec
- mwringe
- nickchase
- nicksardo
- paulczar
- pengx17
- qhuynh96
- rutsky
- sgoings
- skuda
- spxtr
- staebler
- suleisl2000
- tianshapjq
- viglesiasce
- yanxuean

---

Repos with inactive owners that need follow-up clean up:
- [x] [kubernetes/cloud-provider-gcp](https://github.com/kubernetes/cloud-provider-gcp) - https://github.com/kubernetes/cloud-provider-gcp/pull/162
  - nicksardo
- [x] [kubernetes/cloud-provider-vsphere](https://github.com/kubernetes/cloud-provider-vsphere) - https://github.com/kubernetes/cloud-provider-vsphere/pull/376
  - abrarshivani
- [x] [kubernetes/examples](https://github.com/kubernetes/examples) - https://github.com/kubernetes/examples/pull/394
  - david-mcmahon
- [x] [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) - https://github.com/kubernetes/kubernetes/pull/93848, https://github.com/kubernetes/kubernetes/pull/93849, https://github.com/kubernetes/kubernetes/pull/93850, https://github.com/kubernetes/kubernetes/pull/93852
  - nicksardo
  - konryd
  - euank
  - cheld
  - caoshufeng
  - abrarshivani
- [x] [kubernetes/sig-release](https://github.com/kubernetes/sig-release) - https://github.com/kubernetes/sig-release/pull/1176
  - nickchase
- [x] [kubernetes/test-infra](https://github.com/kubernetes/test-infra) - https://github.com/kubernetes/test-infra/pull/18761, https://github.com/kubernetes/test-infra/pull/18760
  - viglesiasce
  - abrarshivani
- [x] [kubernetes-sigs/application](https://github.com/kubernetes-sigs/application) - https://github.com/kubernetes-sigs/application/pull/202
  - viglesiasce
- [x] [kubernetes-sigs/cri-tools](https://github.com/kubernetes-sigs/cri-tools) - https://github.com/kubernetes-sigs/cri-tools/pull/649
  - euank
- [x] [kubernetes-sigs/sig-storage-local-static-provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner) - https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/211
  - dhirajh
---

/area github-membership

**Comment by paulczar** [comment]
Just a heads up on the general experience of being removed...  I was (unknown to me) on this list and if it hadn't been for @castrojo mentioning it to me in passing ( while ironically I was working on a pair [1](https://github.com/kubernetes/website/pull/22934) [2](https://github.com/kubernetes/examples/pull/393) of k8s PRs on monday ) I would have had no clue that this was happening apart from the github email "you've been removed from the kubernetes organization".   This is definitely not a contributor friendly experience to have.  

note, that at time of #2077 being merged I would not have been counted as an inactive member according to the inactivity guidelines including PRs.

I noticed in #2013, people where @ mentioned, which would have created a github notification, whereas in August we weren't.

Timing wise, having made a pair of PRs on Monday, it should have probably even pulled me off this list.

Now I know that Membership of the org != membership of k8s community, and its a fairly simple PR to be added back in, However I don't know that would be obvious to others, and regardless of those words, its still hard to not feel like having been kicked out of the club.

Anyways I just wanted to offer some details on my experience of the removal (less about me, I can re-add myself with a PR pretty easily), I would suggest the main takeaway from the experience would be to have some formal notification, even an @ mention in github would be better than nothing, but ( I know its probably not easy match up emails ) an email with some kind of notification and perhaps a link to "help wanted" or "low hanging fruit" bugs would also offer people a great reminder that its not hard to stay active.  Hopefully this feedback is useful :+1:

**Comment by mrbobbytables** [comment]
Hey there @paulcza,
The ping was missed on my part with this, but the long term plan is to eventually automate this process (members being removed won't receive a ping). We updated our [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#inactive-members) outlining who is defined as inactive and how it is counted. For reference, we use [devstats](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All) as our means to measure inactivity as it takes into account different types of GitHub actions, not just PRs or issues - but edits, comments and more. A general community notification about this policy was then sent to the  [k-dev mailing list.](https://groups.google.com/g/kubernetes-dev/c/AvCa-sGx9Jw/m/zByeyP9LAgAJ).

We want to limit access to people that are consistently remain active. Org membership grants permissions to Kubernetes project repos and our CI system. If those privileges aren’t being actively used, we remove them to ensure we don’t have security issues down the road. 

Not being a member doesn't mean you can't contribute. Many of our contributions come from non-org members. If you're ramping back up within the project, our org membership process has been streamlined. With a few PRs and two sponsors, we can add you back as a member.

**Comment by nikhita** [comment]
All PRs to cleanup OWNERS have merged. Closing.
