### ISSUE TITLE
REQUEST: New membership for mboersma

### ISSUE THREAD

**Issue by mboersma** [kubernetes/org#2078]
### GitHub Username
@mboersma

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @CecileRobertMichon
- @nader-ziada

### Partial list of contributions to the Kubernetes project
- kubernetes/kubernetes#89319
- kubernetes/utils#148
- kubernetes-sigs/cluster-api#3070
- kubernetes-sigs/cluster-api-provider-azure#793
- kubernetes-sigs/cluster-api-provider-azure#740
- kubernetes-sigs/cluster-api-provider-azure#650
- kubernetes-sigs/cluster-api-provider-azure#645

**Comment by CecileRobertMichon** [comment]
Big +1 from me! 🎉

**Comment by nader-ziada** [comment]
+1 from me, thanks @mboersma for all the awesome work

**Comment by nikhita** [comment]
@mboersma thanks for all your contributions with cluster api  :)

I've created PR #2086 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
