### ISSUE TITLE
Migrate Kubespray to kubernetes-sigs

### ISSUE THREAD

**Issue by ant31** [kubernetes/org#208]
### New Repo, Staging Repo, or migrate existing
As discussed with sig-cluster-lifecycle in the  [28th Sept meeting](https://docs.google.com/document/d/1deJYPIF4LmhGjDVaqrswErIrV7mtwJgovtLnPCDxP7U/edit#heading=h.mhdh6zeg1w9d) we'd like to migrate https://github.com/kubernetes-incubator/kubespray to the https://github.com/kubernetes-sigs org.

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
ant31, mattymo

### If not a staging repo, who should have write access
ant31, mattymo, riverzhang, chadswen, atoms, mirwan, woopstar

### What SIG and subproject does this fall under in sigs.yaml
subproject for sig-cluster-lifecycle
note: Kubespray is already listed in the sigs.yaml

### Approvals

- [x] @timothysc 
- [x] @justinsb 

### Additional context for request

Kubespray is today one of the most active projects by many metrics in the kubernetes/* orgs ([k8s.devstats.cncf.io](https://k8s.devstats.cncf.io/d/49/github-stats-by-repository?orgId=1&var-stat=commits&from=now-90d&to=now)), it has more 300+ contributors and many users. 
As the incubator org is deprecated and the project is still very active, the sig cluster-lifecycle agreed to host it in kubernetes-sigs. 

/area github-repo

**Comment by timothysc** [comment]
Awesome @ant31

**Comment by justinsb** [comment]
I don't think I'm needed to approve it.  If I am needed, you have my approval though!

**Comment by ant31** [comment]
@cblecker What are the next steps? All maintainers have been added the kubernetes-sig org, the repo is ready to be moved!

**Comment by cblecker** [comment]
This is mostly done now.

@ant31 @timothysc -- Can you please open a PR to update sigs.yaml with the new location?
