### ISSUE TITLE
REQUEST: New membership for jsturtevant

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/org#2083]
### GitHub Username
@jsturtevant

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@chewong 
@ddebroy 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/93588
https://github.com/kubernetes/kubernetes/pull/93475
https://github.com/kubernetes/kubernetes/pull/92355
https://github.com/kubernetes/test-infra/pull/18401
https://github.com/kubernetes/test-infra/pull/18123
https://github.com/kubernetes/test-infra/pull/18085
https://github.com/kubernetes/website/pull/21652

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/64801
https://github.com/kubernetes/kubernetes/issues/93262
https://github.com/kubernetes/kubernetes/issues/93590
https://github.com/kubernetes/kubernetes/issues/93349
https://github.com/kubernetes/kubernetes/issues/93276
https://github.com/kubernetes/kubernetes/issues/93165
https://github.com/kubernetes/kubernetes/issues/93278

- SIG projects I am involved with
https://github.com/kubernetes-sigs/cluster-api-provider-azure
https://github.com/kubernetes-sigs/windows-testing

PRs to sigs
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/806
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/640
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/468
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/642
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/719

**Comment by chewong** [comment]
+1

**Comment by ddebroy** [comment]
+1 to @jsturtevant 's request for membership. James has been an active contributor to sig-windows.

**Comment by justaugustus** [comment]
+1!

**Comment by nikhita** [comment]
@jsturtevant thanks for all your contributions so far :)

I've created PR #2086 to add you to the Kubernetes and Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
