### ISSUE TITLE
REQUEST: New membership for michaelkolber

### ISSUE THREAD

**Issue by michaelkolber** [kubernetes/org#2087]
### GitHub Username
@michaelkolber

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp
- @dims

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
   - https://github.com/kubernetes/test-infra/pull/18193
   - https://github.com/kubernetes/test-infra/pull/18273
   - https://github.com/kubernetes/test-infra/pull/18684
- Issues responded to:
   - https://github.com/kubernetes/test-infra/issues/18322
- SIG projects I am involved with
   - SIG-testing

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by dims** [comment]
+1 from me!

**Comment by spiffxp** [comment]
@michaelkolber thanks for all your contributions so far :)

I've created PR #2088 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/meow
