### ISSUE TITLE
REQUEST: New membership for jackielii

### ISSUE THREAD

**Issue by jackielii** [kubernetes/org#2095]
### GitHub Username
e.g. @jackielii

### Organization you are requesting membership in
e.g. kubernetes-sigs/nfs-subdir-external-provisioner

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @kmova
- @wongma7

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-retired/external-storage/pull/87

**Comment by kmova** [comment]
+1

**Comment by wongma7** [comment]
+1

**Comment by mrbobbytables** [comment]
@jackielii , thank you for your help with the nfs-external-provisioner :)

I've created PR #2101  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
