### ISSUE TITLE
REQUEST: New membership for ZhiFeng1993

### ISSUE THREAD

**Issue by ZhiFeng1993** [kubernetes/org#2096]
### GitHub Username
@ZhiFeng1993

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp 
- @alejandrox1 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/test-infra/pull/18636
https://github.com/kubernetes/test-infra/pull/18621
https://github.com/kubernetes/test-infra/pull/18620
https://github.com/kubernetes/test-infra/pull/18619
https://github.com/kubernetes/test-infra/pull/18300
https://github.com/kubernetes/test-infra/pull/18103
https://github.com/kubernetes/test-infra/pull/17898
https://github.com/kubernetes/kubernetes/pull/92208
https://github.com/kubernetes/kubernetes/pull/90688
https://github.com/kubernetes/kubernetes/pull/93213
https://github.com/kubernetes/kubernetes/pull/93047
https://github.com/kubernetes/kubernetes/pull/93036
https://github.com/kubernetes/kubernetes/pull/91747
https://github.com/kubernetes/kubernetes/pull/91479
https://github.com/kubernetes/kubernetes/pull/90693
https://github.com/kubernetes/website/pull/22792
https://github.com/kubernetes-sigs/yaml/pull/36
https://github.com/kubernetes/website/pull/21781
https://github.com/kubernetes/website/pull/21467

- Issues responded to
https://github.com/kubernetes/test-infra/issues/18583
https://github.com/kubernetes/test-infra/issues/18579
https://github.com/kubernetes/test-infra/issues/18578
https://github.com/kubernetes/test-infra/issues/18577
https://github.com/kubernetes/kubernetes/issues/81245
https://github.com/kubernetes/kubernetes/issues/92911
https://github.com/kubernetes/kubernetes/issues/91042
https://github.com/kubernetes/kubernetes/issues/90624
https://github.com/kubernetes/kubernetes/issues/93609
https://github.com/kubernetes/kubeadm/issues/2229
https://github.com/kubernetes/kubeadm/issues/2230
https://github.com/kubernetes-sigs/yaml/issues/35
https://github.com/kubernetes/website/issues/22488
https://github.com/kubernetes/website/issues/22096
https://github.com/kubernetes/website/issues/21771
https://github.com/kubernetes/website/issues/21735
https://github.com/kubernetes/test-infra/issues/17862
https://github.com/kubernetes/kubeadm/issues/2160
https://github.com/kubernetes/kubernetes/issues/90632
https://github.com/kubernetes/website/issues/20673
https://github.com/kubernetes/test-infra/issues/17193
https://github.com/kubernetes/kubernetes/issues/86597

- SIG projects I am involved with
sig-testing
sig-node

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by alejandrox1** [comment]
huge +1 as well

**Comment by mrbobbytables** [comment]
@ZhiFeng1993 , thank you for all your contributions so far :)

I've created PR #2101  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
