### ISSUE TITLE
REQUEST: New membership for riverzhang

### ISSUE THREAD

**Issue by riverzhang** [kubernetes/org#21]
### GitHub Username
riverzhang

### Organization you are requesting membership in
kubernetes-incubator

### Requirements

- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ant31 
- @mattymo

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - https://github.com/kubernetes-incubator/kubespray/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+riverzhang
- Issues responded to
    - https://github.com/kubernetes-incubator/kubespray/issues?q=is%3Aissue+riverzhang+is%3Aopen
- SIG projects I am involved with
    - kubernetes-incubator/kubespray
    - https://github.com/kubernetes-incubator/kubespray/pulls?utf8=%E2%9C%93&q=author%3Ariverzhang+

**Comment by spiffxp** [comment]
/assign @ant31 
/assign @mattymo
Can we get +1's from the sponsors?

**Comment by ant31** [comment]
+1

**Comment by mattymo** [comment]
+1

**Comment by spiffxp** [comment]
/close
invite sent
