### ISSUE TITLE
request to join kubernetes-sigs

### ISSUE THREAD

**Issue by akutz** [kubernetes/org#210]
### GitHub Username
@akutz

### Organization you are requesting membership in
[@kubernetes-sigs](https://github.com/kubernetes-sigs)

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] ~I have two sponsors that meet the sponsor requirements listed in the community membership guidelines~
- [ ] ~I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application~

### Sponsors
NA. Member of [@kubernetes](https://github.com/kubernetes)

### List of contributions to the Kubernetes project
Please see my original Kubernetes membership [application](https://groups.google.com/d/msg/kubernetes-membership/PiSicVDtznQ/FOr-CCs1DAAJ).

/area github-membership

**Comment by justaugustus** [comment]
Thanks for contributions! I'll take care of this. :)
/assign
