### ISSUE TITLE
REQUEST: New membership for kasramp

### ISSUE THREAD

**Issue by kasramp** [kubernetes/org#2103]
### GitHub Username
@kasramp

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah
- @sftim

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/website/pull/22565
- Issues responded to
- SIG projects I am involved with

**Comment by zacharysarah** [comment]
+1, thanks for helping with Persian localization!

**Comment by sftim** [comment]
:+1:, thanks for helping with Persian localization!

**Comment by savitharaghunathan** [comment]
Hi @kasramp 👋, Thanks for all your help with k/website localization effort :) 

I've created PR #2108 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes!  🎉

/assign
