### ISSUE TITLE
REQUEST: New membership for FaezeAzimi

### ISSUE THREAD

**Issue by FaezeAzimi** [kubernetes/org#2105]
### GitHub Username
@FaezeAzimi

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah
- @sftim

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/22565/commits/e0bf95fbacdc5b8b52e59f676b9a36dc8435e798
- Issues responded to
- SIG projects I am involved with
-sig-docs

**Comment by zacharysarah** [comment]
+1, thanks for contributing to the Persian localization!

**Comment by sftim** [comment]
:+1: from me

**Comment by savitharaghunathan** [comment]
Hi @FaezeAzimi 👋, Thanks for all your help with k/website localization effort :) 

I've created PR #2108 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes!  🎉

/assign
