### ISSUE TITLE
REQUEST: New membership for SomtochiAma

### ISSUE THREAD

**Issue by SomtochiAma** [kubernetes/org#2107]
### GitHub Username
@SomtochiAma

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justinsb 
- @stealthybox

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  **Repository: cluster-addons**
1. [kubernetes-sigs/cluster-addons#75](https://github.com/kubernetes-sigs/cluster-addons/pull/75) - Generic controller
2. [kubernetes-sigs/cluster-addons#73](https://github.com/kubernetes-sigs/cluster-addons/pull/73) - Kubectl plugin for resources that have a particular ownerref
3. [kubernetes-sigs/cluster-addons#71](https://github.com/kubernetes-sigs/cluster-addons/pull/71) - Uses packages from declarative pattern repo
4. [kubernetes-sigs/cluster-addons#70](https://github.com/kubernetes-sigs/cluster-addons/pull/70) - Adds role for manager
5. [kubernetes-sigs/cluster-addons#69](https://github.com/kubernetes-sigs/cluster-addons/pull/69) - Flannel Operator
6. [kubernetes-sigs/cluster-addons#68](https://github.com/kubernetes-sigs/cluster-addons/pull/68) - Takes in manifest and generates role
7. [kubernetes-sigs/cluster-addons#67](https://github.com/kubernetes-sigs/cluster-addons/pull/67) - [WIP] RBAC gen
8. [kubernetes-sigs/cluster-addons#59](https://github.com/kubernetes-sigs/cluster-addons/pull/59) - NodeLocalDNS operator
9. [kubernetes-sigs/cluster-addons#56](https://github.com/kubernetes-sigs/cluster-addons/pull/56) - Readme for dashboard operator and updates stable version
10. [kubernetes-sigs/cluster-addons#49](https://github.com/kubernetes-sigs/cluster-addons/pull/49) - Updates installer instructions for Mac OS
11. [kubernetes-sigs/cluster-addons#45](https://github.com/kubernetes-sigs/cluster-addons/pull/45) - Updates CoreDNS readme for kubebuilder 2.0
12. [kubernetes-sigs/cluster-addons#44](https://github.com/kubernetes-sigs/cluster-addons/pull/44) - Operator for the Kubernetes dashboard
13. [kubernetes-sigs/cluster-addons#42](https://github.com/kubernetes-sigs/cluster-addons/pull/42) - Adds docs on how to run operator locally

**Repository: kubebuilder-declarative-pattern**
1. [kubernetes-sigs/kubebuilder-declarative-pattern#112](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/112) - Unstructured support in different functions
2. [kubernetes-sigs/kubebuilder-declarative-pattern#111](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/111) - Checks for annotation for objects in-cluster
3. [kubernetes-sigs/kubebuilder-declarative-pattern#110](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/110) - Uses kstatus to compute status of CR
4. [kubernetes-sigs/kubebuilder-declarative-pattern#105](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/105) - Checks for ignore reconciliation annotations
5. [kubernetes-sigs/kubebuilder-declarative-pattern#104](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/104) - Base git repository working
6. [kubernetes-sigs/kubebuilder-declarative-pattern#103](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/103) - Adds function for parsing list
7. [kubernetes-sigs/kubebuilder-declarative-pattern#102](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/102) - Adds Version Check
8. [kubernetes-sigs/kubebuilder-declarative-pattern#101](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/101) - Uses new apply function so we don't need kubectl
9. [kubernetes-sigs/kubebuilder-declarative-pattern#100](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/100) - Moves some functions from Coredns operator that could be reused
10. [kubernetes-sigs/kubebuilder-declarative-pattern#96](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/96) - Removes some steps that are now been built into kubebuidler
11. [kubernetes-sigs/kubebuilder-declarative-pattern#78](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/78) - Makes file loading more flexible

- Issues responded to
1. [kubernetes-sigs/kubebuilder-declarative-pattern#84](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/84) - Test framework for the addons

- SIG projects I am involved with
- sig-cluster-lifecylce(cluster-addons)

**Comment by stealthybox** [comment]
+1
It is terrific working with you @SomtochiAma

**Comment by justinsb** [comment]
Big +1 from me also

**Comment by ameukam** [comment]
Hi @SomtochiAma, thank you for all your contributions so far :)

I've created #2114 to add you to the Kubernetes-sigs Org. Now it's merged, you should have received a membership invitation notification.

Welcome to @kubernetes-sigs! :tada:
