### ISSUE TITLE
Membership Request: cody-clark 

### ISSUE THREAD

**Issue by cody-clark** [kubernetes/org#211]
### GitHub Username
@cody-clark

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @chenopis 

### List of contributions to the Kubernetes project
- [PRs reviewed / authored](https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Acody-clark+is%3Amerged)
- Issues responded to
- SIG projects I am involved with
   * sig-docs approver

/area github-membership

**Comment by zacharysarah** [comment]
Enthusiastic +1. @cody-clark is a returning contributor to SIG Docs.

**Comment by chenopis** [comment]
Ditto! +1 for me too. It's great to have @cody-clark back!

**Comment by justaugustus** [comment]
Thanks for your contributions! I'll take care of this. :)
/assign

**Comment by zacharysarah** [comment]
@justaugustus I see that https://github.com/kubernetes/org/pull/212 merged, but @cody-clark doesn't show up as an org member yet:

![screen shot 2018-11-01 at 1 08 00 pm](https://user-images.githubusercontent.com/3210446/47876810-72e33480-ddd7-11e8-8adb-beb745f91a4c.png)

I'm likewise unable to add him to SIG Docs teams. 

![screen shot 2018-11-01 at 1 08 20 pm](https://user-images.githubusercontent.com/3210446/47876809-72e33480-ddd7-11e8-81c6-f00940da5dd8.png)

Would you PTAL? 🙇

**Comment by justaugustus** [comment]
@zacharysarah -- sorry for any confusion. Once the PR merges, that triggers a Github org invitation. @cody-clark will need to accept it to be listed in the org.
