### ISSUE TITLE
Netlify site request for CAPZ

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes/org#2122]
### Repository
kubernetes-sigs/cluster-api-provider-azure

### Project domain
capz.sigs.k8s.io

NOTE: Must match domain request.
See subproject site request docs for more information:
http://git.k8s.io/community/github-management/subproject-site-requests.md#subproject-domain-request

### Additional context for request
Any additional information or links to discussions regarding the request.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/858
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/netlify.toml

**Comment by mrbobbytables** [comment]
The site has been created and is available here:
https://kubernetes-sigs-cluster-api-provider-azure.netlify.app/

At this point a PR needs to be opened in https://github.com/kubernetes/k8s.io to add the domain. Once that PR is merged, I can finish configuring the netlify site 👍 

/assign

**Comment by CecileRobertMichon** [comment]
Filed https://github.com/kubernetes/k8s.io/issues/1182

**Comment by CecileRobertMichon** [comment]
@mrbobbytables https://github.com/kubernetes/k8s.io/pull/1197 has merged.

 We ended up changing the domain name to `capz.sigs.k8s.io`, hope that's okay.

**Comment by mrbobbytables** [comment]
its setup for it, but netlify is having an issue provisioning the ssl cert at the moment. You can verify its up at http://capz.sigs.k8s.io

**Comment by mrbobbytables** [comment]
https://capz.sigs.k8s.io works now \o/ just took a little time for the letsencrypt cert to get provisioned. 

With that I'm going to go ahead and close this out. If you have any other questions or issues, feel free to re-open :)

/close

**Comment by CecileRobertMichon** [comment]
Thank you!
