### ISSUE TITLE
Please create kubernetes-sigs/yaml (for forking https://github.com/ghodss/yaml/)

### ISSUE THREAD

**Issue by dims** [kubernetes/org#213]
### New Repo, Staging Repo, or migrate existing
Import https://github.com/ghodss/yaml/ into kubernetes-sigs org

### Requested name for new repository
`yaml`

### Which Organization should it reside
`kubernetes-sigs`

### If not a staging repo, who should have admin access
@lavalamp @deads2k @liggitt @dims 

### If not a staging repo, who should have write access
@lavalamp @deads2k @liggitt @dims 

### If a new repo, who should be listed as approvers in OWNERS
same as https://raw.githubusercontent.com/kubernetes/apimachinery/master/OWNERS

### If a new repo, who should be listed in SECURITY_CONTACTS
same as https://github.com/kubernetes/apimachinery/blob/master/SECURITY_CONTACTS

### What should the repo description be
A better way to marshal and unmarshal YAML in Golang (fork of https://github.com/ghodss/yaml/)

### What SIG and subproject does this fall under in sigs.yaml
sig-api-machinery `universal-machinery` subproject

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

Please see email thread : https://groups.google.com/d/msg/kubernetes-sig-api-machinery/mzSP44WMJl4/m1p6U4qVBwAJ

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
Any additional information or context to describe the request.

/area github-repo

**Comment by timothysc** [comment]
+100 this solves a long-standing user facing issue. 

/assign @cblecker

**Comment by bgrant0607** [comment]
+1

**Comment by deads2k** [comment]
> +100 this solves a long-standing user facing issue.
> 
> /assign @cblecker

This isn't signing up to fix that issue. This is creating a place that we own where it could be changed if someone worked through the backward compatibility concerns and was motivated to address it.

/approve

**Comment by cblecker** [comment]
This is forked into https://github.com/kubernetes-sigs/yaml . Haven't fully finished all the automation pieces, but it's in progress :)

**Comment by cblecker** [comment]
@dims Can you get this added to sigs.yaml? Then we can close this out.

**Comment by dims** [comment]
Thanks @cblecker !
