### ISSUE TITLE
REQUEST: New membership for Divya063

### ISSUE THREAD

**Issue by Divya063** [kubernetes/org#2130]
### GitHub Username
@Divya063

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @JimBugwadia
- @rjbez17

### List of contributions to the Kubernetes project
**Repository: multi-tenancy**

Total Pull Requests Created: 23
1. [kubernetes-sigs/multi-tenancy#1034](https://github.com/kubernetes-sigs/multi-tenancy/pull/1034) - [MTB] Added script to run CI tests
2. [kubernetes-sigs/multi-tenancy#993](https://github.com/kubernetes-sigs/multi-tenancy/pull/993) - [MTB] Sort benchmarks in scorecard
3. [kubernetes-sigs/multi-tenancy#987](https://github.com/kubernetes-sigs/multi-tenancy/pull/987) - [MTB] Updated Docs
4. [kubernetes-sigs/multi-tenancy#981](https://github.com/kubernetes-sigs/multi-tenancy/pull/981) - [MTB] Added leveled logging 
5. [kubernetes-sigs/multi-tenancy#968](https://github.com/kubernetes-sigs/multi-tenancy/pull/968) - Added coverage tool
6. [kubernetes-sigs/multi-tenancy#967](https://github.com/kubernetes-sigs/multi-tenancy/pull/967) - Changed policies directory structure
7. [kubernetes-sigs/multi-tenancy#952](https://github.com/kubernetes-sigs/multi-tenancy/pull/952) - [MTB] Remove typos
8. [kubernetes-sigs/multi-tenancy#945](https://github.com/kubernetes-sigs/multi-tenancy/pull/945) - [MTB] Update Docs
9. [kubernetes-sigs/multi-tenancy#940](https://github.com/kubernetes-sigs/multi-tenancy/pull/940) - [MTB] Added Policies
10. [kubernetes-sigs/multi-tenancy#910](https://github.com/kubernetes-sigs/multi-tenancy/pull/910) - [MTB] Added docs
11. [kubernetes-sigs/multi-tenancy#897](https://github.com/kubernetes-sigs/multi-tenancy/pull/897) - [MTB]Changed unit test setup
12. [kubernetes-sigs/multi-tenancy#893](https://github.com/kubernetes-sigs/multi-tenancy/pull/893) - [MTB]Added check for tenant-admin and tenant namespace
13. [kubernetes-sigs/multi-tenancy#883](https://github.com/kubernetes-sigs/multi-tenancy/pull/883) - [MTB]Added table to display benchmark summary
14. [kubernetes-sigs/multi-tenancy#880](https://github.com/kubernetes-sigs/multi-tenancy/pull/880) - [MTB]Added Remaining benchmarks
15. [kubernetes-sigs/multi-tenancy#878](https://github.com/kubernetes-sigs/multi-tenancy/pull/878) - [MTB] Sort benchmarks according to profile level, category and id respectively
16. [kubernetes-sigs/multi-tenancy#864](https://github.com/kubernetes-sigs/multi-tenancy/pull/864) - [MTB]Setup to Add Unittests
17. [kubernetes-sigs/multi-tenancy#857](https://github.com/kubernetes-sigs/multi-tenancy/pull/857) - Changes to import tenant namespace controller
18. [kubernetes-sigs/multi-tenancy#850](https://github.com/kubernetes-sigs/multi-tenancy/pull/850) - [WIP][MTB] Setup for adding unittest
19. [kubernetes-sigs/multi-tenancy#837](https://github.com/kubernetes-sigs/multi-tenancy/pull/837) - Fix compilation error with latest k8s API
20. [kubernetes-sigs/multi-tenancy#826](https://github.com/kubernetes-sigs/multi-tenancy/pull/826) - [MTB]Add additional fields dynamically to README
21. [kubernetes-sigs/multi-tenancy#811](https://github.com/kubernetes-sigs/multi-tenancy/pull/811) - Lifecycle
22. [kubernetes-sigs/multi-tenancy#809](https://github.com/kubernetes-sigs/multi-tenancy/pull/809) - Added README generator
23. [kubernetes-sigs/multi-tenancy#806](https://github.com/kubernetes-sigs/multi-tenancy/pull/806) - Added config files as static asset

Total Issues Opened: 2
1. [kubernetes-sigs/multi-tenancy#937](https://github.com/kubernetes-sigs/multi-tenancy/issues/937) - [MTB] Add support for cross platform file paths
2. [kubernetes-sigs/multi-tenancy#828](https://github.com/kubernetes-sigs/multi-tenancy/issues/828) - Error while importing tenant-controller

**Repository: test-infra**

Total Pull Requests Created: 1
1. [kubernetes/test-infra#18922](https://github.com/kubernetes/test-infra/pull/18922) - Added presubmit prow job for kubernetes-sigs/multi-tenancy kubectl-mtb project

**Comment by rjbez17** [comment]
+1

Welcome!!

**Comment by JimBugwadia** [comment]
+1

**Comment by palnabarun** [comment]
@Divya063, thank you for all your contributions to the Multitenancy Working Group :)

I've created PR #2129 to add you to the @kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! :tada:

/assign

/honk
