### ISSUE TITLE
Migration request: chuckha/downloadkubernetes --> Release Engineering

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#2131]
### New Repo, Staging Repo, or migrate existing
Migrate existing: https://github.com/chuckha/downloadkubernetes

### Requested name for new repository
downloadkubernetes

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
SIG Release leads (@justaugustus, @tpepper, @alejandrox1, @saschagrunert)

### If not a staging repo, who should have write access
https://github.com/chuckha/downloadkubernetes/blob/1ec189ae4c2b43a984cd4ef348c29a4504c1e89f/OWNERS#L3-L9

### If not a staging repo, who should be listed as approvers in OWNERS
Already listed: https://github.com/chuckha/downloadkubernetes/blob/1ec189ae4c2b43a984cd4ef348c29a4504c1e89f/OWNERS#L3-L9

### If not a staging repo, who should be listed in SECURITY_CONTACTS
https://github.com/chuckha/downloadkubernetes/blob/1ec189ae4c2b43a984cd4ef348c29a4504c1e89f/OWNERS#L3-L9

### What should the repo description be
The easy way to get the Kubernetes binaries you need!

### What SIG and subproject does this fall under in sigs.yaml
SIG Release / Release Engineering subproject

### Approvals

Approving as a SIG Release Chair after discussing potential donation with @chuckha yesterday.
Adding other @kubernetes/sig-release-leads for approvals.

### Additional context for request

Chuck recently updated https://downloadkubernetes.com/ and tweeted about it: https://twitter.com/chuck_ha/status/1297606219167924224?s=20
I've seen lots of support for this site in the past and figured it'd cool to see if we could bring it into the community and make it part of the release process.

Can be eventually integrated with a proposal from @sftim around a releases page for k/website: https://github.com/kubernetes/website/pull/22736

cc: @kubernetes/release-engineering @mauilion

**Comment by justaugustus** [comment]
PTAL @kubernetes/owners -- Much of the migration administrivia from Chuck's side has already been completed: adding LICENSES, OWNERS, CLA

**Comment by saschagrunert** [comment]
LGTM 👍

**Comment by mauilion** [comment]
This would be great. I'd love to see this be the "browser based" landing page for dl.k8s.io and setup header filtering there so that anything not a browser would kick to the existing link.

**Comment by jimangel** [comment]
This is great! I'm happy to help support this from a Docs perspective. It definitely ties into the work @sftim has been doing in https://github.com/kubernetes/website/pull/22736.

Issue ref: https://github.com/kubernetes/website/issues/20293

**Comment by cpanato** [comment]
this is awesome!
LGTM

**Comment by nikhita** [comment]
@chuckha can you also add [CONTRIBUTING.md](https://github.com/kubernetes/kubernetes-template-project/blob/master/CONTRIBUTING.md), SECURITY_CONTACTS and add this section - https://github.com/kubernetes/kubernetes-template-project#community-discussion-contribution-and-support - to the README?

Once that's done, please transfer the repo to https://github.com/kubernetes-purgatory and I can then transfer it to k-sigs. Kubernetes org admins need to be added to the repo for transferring it, but GitHub doesn't allow adding admins to a "user-owned" repo, so we'll need to move it to a dummy org first.

**Comment by chuckha** [comment]
@nikhita done & transferred!

**Comment by nikhita** [comment]
Repo has been transferred - https://github.com/kubernetes-sigs/downloadkubernetes

- https://github.com/kubernetes/community/pull/5070 - to add to sigs.yaml
- https://github.com/kubernetes/org/pull/2136 - to add GitHub teams

**Comment by nikhita** [comment]
Repo has been migrated and added to sigs.yaml, and teams have been granted access :)
