### ISSUE TITLE
REQUEST: New membership for thebsdbox

### ISSUE THREAD

**Issue by thebsdbox** [kubernetes/org#2133]
### GitHub Username
@thebsdbox (Dan Finneran)

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gianarb 
- @deitch

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
https://github.com/kubernetes-sigs/cluster-api (CAPD)
https://github.com/kubernetes-sigs/cluster-api-provider-packet

**Comment by gianarb** [comment]
+1

**Comment by deitch** [comment]
Definitely! +1

**Comment by justaugustus** [comment]
+1!

**Comment by nikhita** [comment]
Should the org be @kubernetes or @kubernetes-sigs in the issue body? I noticed https://github.com/kubernetes/org/pull/2134 adds @thebsdbox to k-sigs.

**Comment by gianarb** [comment]
Yes @nikhita ! @thebsdbox is updating the issue body! Thanks

**Comment by thebsdbox** [comment]
Apologies, updated 👍
