### ISSUE TITLE
REQUEST: New membership for @Shell32-natsu

### ISSUE THREAD

**Issue by Shell32-Natsu** [kubernetes/org#2135]
### GitHub Username
@Shell32-natsu

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @monopole
- @pwittrock 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/kustomize/pulls?q=is%3Apr+is%3Aclosed+author%3AShell32-Natsu
- Issues responded to
  - https://github.com/kubernetes-sigs/kustomize/issues?q=is%3Aissue+mentions%3A%40me+
- SIG projects I am involved with
  - kustomize

**Comment by savitharaghunathan** [comment]
Pinging @monopole @pwittrock

**Comment by monopole** [comment]
yes please :)

**Comment by savitharaghunathan** [comment]
Hi @Shell32-Natsu 👋 , Thank you for contributing to kustomize :) 

I've created PR #2160 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
