### ISSUE TITLE
Membership Request: yue9944882

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/org#214]
### GitHub Username
@yue9944882 

### Organization you are requesting membership in
@kubernetes-incubator

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@pwittrock 

### List of contributions to the Kubernetes project

[https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=+is%3Apr+author%3Ayue9944882+](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=+is%3Apr+author%3Ayue9944882+)

i've been contributing k/k for about a year. (mostly active in sig api-machinery). i know how the codebase runs especially for k/k apiserver (aggregator/master/CRDs) for recent releases. 

i'm joining this org to help maintaining [apiserver-builder](https://github.com/kubernetes-incubator/apiserver-builder). even tho this repo has been officially deprecated, it still need bandwidth for compatibility w/ legacy external AA servers. i will update its vendor w/ k/k and collect minor patches for the repo (by which i mean excluding features). 

/area github-membership

**Comment by mrbobbytables** [comment]
Hey there @yue9944882, as you are a member of the kubernetes-org you automatically have permission to join the @kubernetes-incubator org. :) I've gone ahead and created PR #215. Once that gets merged you should get an invite to join the @kubernetes-incubator org.

Thanks!

/assign
