### ISSUE TITLE
REQUEST: New membership for hickeyma

### ISSUE THREAD

**Issue by hickeyma** [kubernetes/org#2146]
### GitHub Username
@hickeyma

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @saschagrunert 
- @feiskyer 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
  - https://github.com/kubernetes-sigs/cri-tools/pull/594
  - https://github.com/kubernetes-sigs/cri-tools/pull/595
  - https://github.com/kubernetes-sigs/cri-tools/pull/598
  - https://github.com/kubernetes-sigs/cri-tools/pull/599
  - https://github.com/kubernetes-sigs/cri-tools/pull/604
  - https://github.com/kubernetes-sigs/cri-tools/pull/606
  - https://github.com/kubernetes-sigs/cri-tools/pull/607
  - https://github.com/kubernetes-sigs/cri-tools/pull/611
  - https://github.com/kubernetes-sigs/cri-tools/pull/615
  - https://github.com/kubernetes-sigs/cri-tools/pull/623
  - https://github.com/kubernetes-sigs/cri-tools/pull/630
  - https://github.com/kubernetes-sigs/cri-tools/pull/631
  - https://github.com/kubernetes-sigs/cri-tools/pull/634
  - https://github.com/kubernetes-sigs/cri-tools/pull/635
  - https://github.com/kubernetes-sigs/cri-tools/pull/641
  - https://github.com/kubernetes-sigs/cri-tools/pull/647
  - https://github.com/kubernetes-sigs/cri-tools/pull/648
  - https://github.com/kubernetes-sigs/cri-tools/pull/626
  - https://github.com/kubernetes-sigs/cri-tools/pull/622
  - https://github.com/kubernetes-sigs/cri-tools/pull/603
  - https://github.com/containerd/cri/pull/1457
  - https://github.com/kubernetes/community/pull/4720
- Issues responded to:
  - https://github.com/kubernetes-sigs/cri-tools/issue/592
  - https://github.com/kubernetes-sigs/cri-tools/issue/597
  - https://github.com/kubernetes-sigs/cri-tools/issue/639
  - https://github.com/kubernetes-sigs/cri-tools/issue/613
  - https://github.com/kubernetes-sigs/cri-tools/issue/608
  - https://github.com/kubernetes-sigs/cri-tools/issue/605
  - https://github.com/kubernetes-sigs/cri-tools/issue/602
- SIG projects I am involved with:
  - https://github.com/kubernetes-sigs/cri-tools

**Comment by hickeyma** [comment]
Hi @feiskyer. Would you mind sponsoring me for kubernetes-sig membership? Sorry for asking in the request but I was unable to make contact with otherwise.

**Comment by saschagrunert** [comment]
+1 :partying_face:

**Comment by mrbobbytables** [comment]
+1 from me :D

**Comment by savitharaghunathan** [comment]
Hi @hickeyma 👋 , Thanks for all your contributions to cri-tools :)

I've created PR #2148 to add you to the @kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by feiskyer** [comment]
+1 (sorry for the late response)

**Comment by hickeyma** [comment]
Thank you @saschagrunert and @feiskyer for sponsorship and support in the project.

Thank you @mrbobbytables for the +1.

Thank you @savitharaghunathan for creating and merging the the PR for membership.
