### ISSUE TITLE
REQUEST: New membership for soulxu

### ISSUE THREAD

**Issue by soulxu** [kubernetes/org#2147]
### GitHub Username
@soulxu

### Organization you are requesting membership in
@kubernetes

### Requirements
* [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
* [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
* [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
* [x] I am actively contributing to 1 or more Kubernetes subprojects
* [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
* [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@Huang-Wei 
@chendave 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+label%3Asig%2Fscheduling+author%3Asoulxu+
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+label%3Asig%2Fscheduling+reviewed-by%3Asoulxu
- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+is%3Aopen+commenter%3Asoulxu
- SIG projects I am involved with
sig/scheduling

**Comment by Huang-Wei** [comment]
+1 and looking forward to seeing more contributions!

**Comment by chendave** [comment]
+1 warmly welcome onboard!

**Comment by soulxu** [comment]
@Huang-Wei @chendave thank you guys!

**Comment by ameukam** [comment]
Hi @soulxu, thank you for all your contributions so far :)

I've created the PR https://github.com/kubernetes/org/pull/2154 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

**Comment by soulxu** [comment]
@ameukam, thanks!
