### ISSUE TITLE
REQUEST: New membership for gabbifish

### ISSUE THREAD

**Issue by gabbifish** [kubernetes/org#2149]
### GitHub Username
@gabbifish

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pwittrock 
- @camilamacedo86

### List of contributions to the Kubernetes project
- Wrote envtest docs for the kubebuilder project, so people can get a more general intro to envtest
  - Issue: https://github.com/kubernetes-sigs/kubebuilder/issues/1518
  - PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1521
- Reviewed kubebuilder project PRs:
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1569
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1570
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1571
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1623
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1626
- Issues opened/investigating:
  - https://github.com/kubernetes/kubernetes/issues/94313

**Comment by pwittrock** [comment]
Thanks @gabbifish for all your hard work :)

**Comment by savitharaghunathan** [comment]
Hi @gabbifish  👋 , Thanks for all your contributions to kubebuilder :)

I've created PR #2148 to add you to the @kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
