### ISSUE TITLE
REQUEST: New membership for bmelbourne

### ISSUE THREAD

**Issue by bmelbourne** [kubernetes/org#2151]
### GitHub Username
@bmelbourne

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @floryut
- @Miouge1 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pull/6414
https://github.com/kubernetes-sigs/kubespray/pull/6549
https://github.com/kubernetes-sigs/kubespray/pull/6563
https://github.com/kubernetes-sigs/kubespray/pull/6572
https://github.com/kubernetes-sigs/kubespray/pull/6576
https://github.com/kubernetes-sigs/kubespray/pull/6580
https://github.com/kubernetes-sigs/kubespray/pull/6581
https://github.com/kubernetes-sigs/kubespray/pull/6600
- Issues responded to
https://github.com/kubernetes-sigs/kubespray/issues/4831
https://github.com/kubernetes-sigs/kubespray/issues/5217
https://github.com/kubernetes-sigs/kubespray/issues/5981
https://github.com/kubernetes-sigs/kubespray/issues/6535
https://github.com/kubernetes-sigs/kubespray/issues/6548
- SIG projects I am involved with
https://github.com/kubernetes-sigs/kubespray

**Comment by floryut** [comment]
+1
Lots of good contributions and involvement from Barry, keep it up 👍

**Comment by Miouge1** [comment]
+1 👍

**Comment by ameukam** [comment]
Hi @bmelbourne, thank you for all your contributions so far :)

I've created the PR https://github.com/kubernetes/org/pull/2154 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

**Comment by nikhita** [comment]
@bmelbourne :wave: did you want to request membership to @kubernetes-sigs instead of @kubernetes (since kubespray is in k-sigs)?

If your original request stands and you need membership to @kubernetes, you'll need additional sponsors because all sponsors need to be in an OWNERS file in the @kubernetes org. If it's just @kubernetes-sigs, we can go ahead with the request. :)

**Comment by bmelbourne** [comment]
> @bmelbourne 👋 did you want to request membership to @kubernetes-sigs instead of @kubernetes (since kubespray is in k-sigs)?
> 
> If your original request stands and you need membership to @kubernetes, you'll need additional sponsors because all sponsors need to be in an OWNERS file in the @kubernetes org. If it's just @kubernetes-sigs, we can go ahead with the request. :)

Yes, it's just https://github.com/kubernetes-sigs thanks
