### ISSUE TITLE
REQUEST: New membership for https://github.com/abraaojs

### ISSUE THREAD

**Issue by abraaojs** [kubernetes/org#2152]
### GitHub Username
e.g. (at)example_user

### Organization you are requesting membership in
e.g. (at)kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- (at)sponsor-1
- (at)sponsor-2

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by savitharaghunathan** [comment]
Hi, @abraaojs 👋 Thanks for creating this issue. Could you fill in the template and add sponsors, list of contributions, and the org you are requesting membership for? Thanks :)

**Comment by ameukam** [comment]
Hi @abraaojs :wave:, Since you still have no sponsors added in your request, we will close this issue. Please feel free to reopen the issue with an update of the sponsors and the list of your contributions.

/close
