### ISSUE TITLE
REQUEST: New membership for displague

### ISSUE THREAD

**Issue by displague** [kubernetes/org#2153]
### GitHub Username
@displague

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @detiber 
- @hasheddan 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  * https://github.com/kubernetes/kubernetes/pull/75487
  * https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/165
  * https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/152
  * https://github.com/kubernetes-sigs/external-dns/pull/796
  * https://github.com/kubernetes/autoscaler/pull/3480
- Issues responded to
  * https://github.com/kubernetes/kubeadm/issues/1454
  * https://github.com/kubernetes-sigs/cluster-api-provider-packet/issues/164
  * https://github.com/kubernetes-sigs/cluster-api-provider-packet/issues/151
  * https://github.com/kubernetes-sigs/external-dns/issues/1604
  * https://github.com/kubernetes-sigs/kubebuilder/issues/962
  * https://github.com/kubernetes-sigs/controller-runtime/issues/849
- SIG projects I am involved with

  I've attended some sig-cluster-lifecycle and sig-storage meetings in the past and I've responded in the Slack channels for these and other sigs, from time to time.
  My activities have primarily been in implementing cloud provider integrations (CCM, CSI, cluster-api, external-dns, autoscalar), first at @Linode and now at @Packethost.  As a contributor to the CNCF sandbox @crossplane project, I became interested in kubebuilder and controller-runtime.

**Comment by hasheddan** [comment]
+1 from me! :tada:

**Comment by detiber** [comment]
+1 from me

**Comment by ameukam** [comment]
Hi @displague, thank you for all your contributions so far :)

I've created the PR https://github.com/kubernetes/org/pull/2154 to add you to the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get membership invites notifications.

Welcome! :tada:
