### ISSUE TITLE
REQUEST: New membership for deitch

### ISSUE THREAD

**Issue by deitch** [kubernetes/org#2157]
### GitHub Username

@deitch

### Organization you are requesting membership in

@kubernetes

### Requirements

- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @ncdc 
- @liggitt  

### List of contributions to the Kubernetes project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with - https://github.com/kubernetes/autoscaler/ , http://github.com/kubernetes-sigs/cluster-api-provider-packet

**Comment by gianarb** [comment]
welcome!

**Comment by ncdc** [comment]
👍

**Comment by liggitt** [comment]
👍

**Comment by savitharaghunathan** [comment]
Hi @deitch 👋 , Thank you for your contributions.

I've created PR #2160 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
