### ISSUE TITLE
REQUEST: New membership for pacoxu

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/org#2158]
### GitHub Username
pacoxu

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @aojea 
- zhouya0
- @prameshj

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/18667
https://github.com/kubernetes/website/pull/15285
https://github.com/kubernetes-sigs/kubefed/pull/1228
https://github.com/kubernetes/kubernetes/pull/89251
https://github.com/kubernetes/kubernetes/pull/94389 （WIP）
https://github.com/kubernetes/enhancements/pull/1907 （WIP） 
https://github.com/kubernetes/kubernetes/pull/90109

- Issues responded to
https://github.com/kubernetes/dns/issues/318#issuecomment-520767566
https://github.com/kubernetes/kubernetes/issues/75173#issuecomment-470951929

- SIG projects I am involved with
storage and multi cluster
Writign a kep in https://github.com/kubernetes/enhancements/pull/1907
https://github.com/moby/moby/pull/32288/files
https://github.com/docker/docker-py/pull/1231

**Comment by zhouya0** [comment]
/lgtm
Thanks for contributions!

**Comment by palnabarun** [comment]
@pacoxu, thank you for all your contributions so far :)

I've created PR #2168 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
