### ISSUE TITLE
REQUEST: New membership for d-mo

### ISSUE THREAD

**Issue by d-mo** [kubernetes/org#2159]
### GitHub Username
@d-mo

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mwielgus
- @detiber 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/autoscaler/pull/2101
https://github.com/kubernetes/autoscaler/pull/2490
- Issues responded to
- SIG projects I am involved with
https://github.com/kubernetes/autoscaler/

**Comment by detiber** [comment]
+1 from me

**Comment by mwielgus** [comment]
+1 from me

**Comment by savitharaghunathan** [comment]
Hi, @d-mo 👋 Thank you for all your contributions :) 

I've created PR #2160 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
