### ISSUE TITLE
REQUEST: New membership for vinny-sabatini

### ISSUE THREAD

**Issue by vinny-sabatini** [kubernetes/org#2176]
### GitHub Username

@vinny-sabatini

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @seanmalloy
- @Raffo

### List of contributions to the Kubernetes project
- PRs reviewed
  - https://github.com/kubernetes-sigs/external-dns/pull/1507
  - https://github.com/kubernetes-sigs/external-dns/pull/1436
- PRs authored
  - https://github.com/kubernetes-sigs/external-dns/pull/1752
  - https://github.com/kubernetes-sigs/external-dns/pull/1748
  - https://github.com/kubernetes-sigs/external-dns/pull/1736
  - https://github.com/kubernetes-sigs/external-dns/pull/1731
- Issues responded to
  - https://github.com/kubernetes-sigs/external-dns/issues/1558
  - https://github.com/kubernetes-sigs/external-dns/issues/1675
  - https://github.com/kubernetes-sigs/external-dns/issues/1754
- SIG projects I am involved with
  - [kubernetes-sigs/external-dns](https://github.com/kubernetes-sigs/external-dns)

**Comment by seanmalloy** [comment]
+1

**Comment by Raffo** [comment]
+1

**Comment by vinny-sabatini** [comment]
@kubernetes/owners I believe I meet all of the requirements for membership

**Comment by ameukam** [comment]
Hi @vinny-sabatini , thank you for all your contributions so far :)

I've created PR #2185  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
/assign
