### ISSUE TITLE
Rename k-sigs/seccomp-operator to k-sigs/security-profiles-operator

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/org#2177]
### New Repo, Staging Repo, or migrate existing
Renaming of the existing repository [seccomp-operator](https://github.com/kubernetes-sigs/seccomp-operator) repository to security-profiles-operator.

### Requested name for new repository
security-profiles-operator

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
the same as before

### If not a staging repo, who should have write access
the same as before

### If not a staging repo, who should be listed as approvers in OWNERS
the same as before

### If not a staging repo, who should be listed in SECURITY_CONTACTS
the same as before

### What should the repo description be
the same as before

### What SIG and subproject does this fall under in sigs.yaml
the same as before

### Approvals
Requesting approval from @hasheddan and @pjbgf 

### Additional context for request
The project should evolve in a more general direction to support other technologies like AppArmor. Therefore the name `seccomp-operator` does not fit any more and has to be changed. We would like to do it early on, because we only have 1 release so far. :)

**Comment by saschagrunert** [comment]
@nikhita, do we have to consider anything else beside changing all paths in all released, repositories?

**Comment by nikhita** [comment]
@saschagrunert we'll also need updates to k/org, k/test-infra, k/k8s.io and k/community at these places - https://cs.k8s.io/?q=seccomp-operator&i=nope&files=&repos=

We'll need to ensure that the changes to the config in these repos merge as soon as we rename the repo on GitHub..or prow could throw warnings when it doesn't find the seccomp-operator repo.

I can do the above when we this request is approved. Since this is a sig-node repo, we'll need approval from the leads.

/assign @derekwaynecarr @dchen1107

**Comment by saschagrunert** [comment]
> I can do the above when we this request is approved. Since this is a sig-node repo, we'll need approval from the leads.

@hasheddan or @pjbgf do you think you could attend the SIG Node meeting today (I can't) and ask for their approval? :innocent:

**Comment by pjbgf** [comment]
@saschagrunert I will attend next week's SIG Node meeting and bring it up.

**Comment by pjbgf** [comment]
A new name (`security-profiles-operator`) has emerged, we will present it on next SIG Node and will update this thread accordingly.

**Comment by dchen1107** [comment]
We discussed this at today's SIG Node meeting, and there is no objection for the new name. cc/ @derekwaynecarr 

+1

**Comment by nikhita** [comment]
@saschagrunert @pjbgf :wave: can you confirm if it should be `security-operator` or `security-profiles-operator`?

**Comment by saschagrunert** [comment]
> @saschagrunert @pjbgf 👋 can you confirm if it should be `security-operator` or `security-profiles-operator`?

Yes, it should become the security-profiles-operator. I changed the issue accordingly.

**Comment by pjbgf** [comment]
Yep, I also confirm `security-profiles-operator`. 🚀

**Comment by saschagrunert** [comment]
@nikhita I'll work on proposing the renaming PRs if you don't mind.

**Comment by saschagrunert** [comment]
Here we go:
- https://github.com/kubernetes/org/pull/2246
- https://github.com/kubernetes/enhancements/pull/2084
- https://github.com/kubernetes/community/pull/5195
- https://github.com/kubernetes/k8s.io/pull/1313
- https://github.com/kubernetes/test-infra/pull/19476
- https://github.com/kubernetes-sigs/seccomp-operator/pull/139

**Comment by nikhita** [comment]
@saschagrunert Thanks for creating the PRs! Repo has been renamed - https://github.com/kubernetes-sigs/security-profiles-operator :tada: 

Let's keep the issue open until all linked PRs have merged (to ensure we have a place to track them) :)

**Comment by nikhita** [comment]
Looks like https://github.com/kubernetes/enhancements/pull/2084 is the only remaining PR to update references with the old name of the repo. IMO it should be fine to track that PR separately so I'll go ahead and close this issue. :)
