### ISSUE TITLE
REQUEST: New membership for @neolit123 (for k-sigs)

### ISSUE THREAD

**Issue by neolit123** [kubernetes/org#218]
### GitHub Username
@neolit123 

### Organization you are requesting membership in
@kubernetes-sigs

/assign @dims

already a member of @kubernetes
requesting membership for k-sigs, as implicitly eligible?

https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem
> There are related Kubernetes GitHub organizations, such as kubernetes-sigs. We are currently working on automation that would transfer membership in the Kubernetes organization to any related orgs automatically, but such is not the case currently. **If you are a Kubernetes org member, you are implicitly eligible for membership in related orgs**, and can request membership when it becomes relevant, by opening an issue against the kubernetes/org repo, as above.

/area github-membership

**Comment by dims** [comment]
+1 from me!

**Comment by nikhita** [comment]
:tada:

**Comment by cblecker** [comment]
Invite will be sent out as soon as #220 merges. Welcome to @kubernetes-sigs! 🚀
