### ISSUE TITLE
REQUEST: New membership for Pluies

### ISSUE THREAD

**Issue by Pluies** [kubernetes/org#2181]
Hello! 👋 
I'm opening this PR to ask for membership to the kubernetes-sig organisation in order to maintain the [Zeitgeist](https://github.com/kubernetes-sigs/zeitgeist) project which just got donated to Kubernetes.

### GitHub Username

@Pluies

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements

- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @justaugustus 
- @nikhita 
- @saschagrunert 

### List of contributions to the Kubernetes project

- Recently donated [Zeitgeist](https://github.com/kubernetes-sigs/zeitgeist) to the kubernetes-release SIG
- https://github.com/kubernetes/kubernetes/pull/74522
- Three-time Kubecon EU attendee and big ol' Kubenerd :)

**Comment by justaugustus** [comment]
+1 to Florent's membership! Thanks so much for donating [zeitgeist](https://github.com/kubernetes-sigs/zeitgeist) to the project! :)
ref: https://github.com/kubernetes/org/issues/2172

**Comment by justaugustus** [comment]
PR to add Florent to k-sigs is here: https://github.com/kubernetes/org/pull/2180

**Comment by saschagrunert** [comment]
+1 from my side. 👍

**Comment by Pluies** [comment]
I think @k8s-ci-robot was a bit quick on the trigger here - #2180 doesn't solve this PR :)

**Comment by nikhita** [comment]
@Pluies you should see an invite if you go to https://github.com/kubernetes-sigs :)

**Comment by justaugustus** [comment]
@Pluies -- I think there are probably two reconciliation bits you're waiting for:
1. Our bot will send you an invite to join the kubernetes-sigs
2. Once the invite is accepted, you'll need to be synced into the group to restore access (I think)

**Comment by nikhita** [comment]
> Our bot will send you an invite to join the kubernetes-sigs

Just checked the postsubmit -- the bot has already sent an invite! :)

> Once the invite is accepted, you'll need to be synced into the group to restore access (I think)

This will be done automatically once you accept the invite.

**Comment by Pluies** [comment]
Heck! That robot is much more powerful than I thought 😄 

I've just accepted the invite, everything is perfect! Thank you for jumping on this, sorry for the spam!
