### ISSUE TITLE
REQUEST: New membership for @salaxander

### ISSUE THREAD

**Issue by salaxander** [kubernetes/org#2184]
### GitHub Username
@salaxander

### Organization you are requesting membership in
Kubernetes SIGs, Kubernetes

### Requirements
- [ X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X ] I am actively contributing to 1 or more Kubernetes subprojects
- [ X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @christopherhein 
- @parispittman
- @onlydole 
- @karenhchu 
- @jeremyrickard 

### List of contributions to the Kubernetes project
- PRs: 
https://github.com/kubernetes-sigs/multi-tenancy/pull/1099
https://github.com/kubernetes-sigs/multi-tenancy/pull/1065
https://github.com/kubernetes-sigs/multi-tenancy/pull/1005

- Issues responded to:
https://github.com/kubernetes-sigs/multi-tenancy/issues/1064
https://github.com/kubernetes-sigs/multi-tenancy/issues/1044

- SIGs:
 multi-tenancy

**Comment by onlydole** [comment]
A huge +1 to @salaxander 🎉

**Comment by christopherhein** [comment]
👏  thanks @salaxander for your contributions so far.

**Comment by ameukam** [comment]
HI @salaxander, thank you for all your contributions so far :)

I've created PR #2185 to add you to the Kubernetes and Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada: 
/assign

**Comment by jeremyrickard** [comment]
+1 from me, thanks @salaxander  :)
