### ISSUE TITLE
REQUEST: New membership for jqmichael

### ISSUE THREAD

**Issue by jqmichael** [kubernetes/org#2186]
### GitHub Username
@jqmichael

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [Y] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [Y] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [Y] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [Y] I am actively contributing to 1 or more Kubernetes subprojects
- [Y] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [Y] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @leakingtapan (https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/OWNERS)
- @wongma7 (https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/OWNERS)

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/165
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/169
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/179
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/181
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/212
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/217

- Issues responded to
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/205

- SIG projects I am involved with
aws-efs-csi-driver

**Comment by leakingtapan** [comment]
+1 thanks for the helps!

**Comment by wongma7** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi, @jqmichael 👋 Thank you for all your contributions :)

I've created PR #2197 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉 

/assign

**Comment by jqmichael** [comment]
Much appreciate the help @savitharaghunathan !
