### ISSUE TITLE
REQUEST: New membership for chethanv28

### ISSUE THREAD

**Issue by chethanv28** [kubernetes/org#2189]
### GitHub Username
@chethanv28

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xing-yang 
- @divyenpatel 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/vsphere-csi-driver/pulls?q=is%3Apr+is%3Aclosed+author%3Achethanv28
https://github.com/kubernetes-sigs/vsphere-csi-driver/commits?author=chethanv28
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aclosed+author%3Achethanv28

- Issues responded to
https://github.com/kubernetes-sigs/vsphere-csi-driver/issues?q=is%3Aissue+is%3Aclosed+assignee%3Achethanv28
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+is%3Aclosed+author%3Achethanv28

- SIG projects I am involved with
https://github.com/kubernetes-sigs/vsphere-csi-driver

**Comment by divyenpatel** [comment]
Thank you @chethanv28 for your contributions.
I recommand to approve membership request for @chethanv28

**Comment by divyenpatel** [comment]
+1

**Comment by xing-yang** [comment]
+1

**Comment by palnabarun** [comment]
Hi @chethanv28 :wave:, thank you for applying to be a @kubernetes-sigs organization member.

A requirement for sponsors is that they need to be from different companies. Unfortunately, both sponsors @divyenpatel and @xing-yang belong to the same company.

Can you please add one more sponsor satisfying all the guidelines mentioned in https://github.com/kubernetes/community/blob/master/community-membership.md#requirements?

Thank you. :slightly_smiling_face:

**Comment by oomichi** [comment]
Thanks for your contribution @chethanv28 :-)
I have seen his contribution on testing area, and I am happy to support him from different company.

**Comment by oomichi** [comment]
+1

**Comment by chethanv28** [comment]
> Can you please add one more sponsor satisfying all the guidelines mentioned in https://github.com/kubernetes/community/blob/master/community-membership.md#requirements?

Thanks @palnabarun for taking a look. I have received sponsorships which meets the requirements. Can you help with the review and approval

**Comment by savitharaghunathan** [comment]
Hi, @chethanv28 👋 Thank you for all your contributions :)

I've created PR #2273 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by chethanv28** [comment]
Thanks @savitharaghunathan
