### ISSUE TITLE
New kubernetes-sigs membership for animeshsingh

### ISSUE THREAD

**Issue by animeshsingh** [kubernetes/org#219]
### GitHub Username

@animeshsingh

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@k82cn
@jinzhejz
@dmatch01

### List of contributions to the Kubernetes project
- Istio tutorials, presentations
- kubernetes tutorials, presentations

https://github.com/IBM/FfDL
https://github.com/IBM/spring-boot-microservices-on-kubernetes
https://github.com/IBM/Scalable-Cassandra-deployment-on-Kubernetes
https://github.com/IBM/Kubernetes-container-service-GitLab-sample
https://github.com/IBM/GameOn-Java-Microservices-on-Kubernetes

- kubernetes-batch

https://github.com/kubernetes-sigs/kube-batch

- istio
- knative

/area github-membership

**Comment by k82cn** [comment]
+1

**Comment by jinzhejz** [comment]
+1

**Comment by k82cn** [comment]
@animeshsingh , thanks for your contribution :)

**Comment by mrbobbytables** [comment]
Hey there @animeshsingh, just to cover our bases would you mind editing your issue and checking off the requirements that you have completed?  Once that's done we can proceed with processing your membership request. 

Thanks! :)

**Comment by dmatch01** [comment]
+1

**Comment by dmatch01** [comment]
@animeshsingh , thank you!

**Comment by mrbobbytables** [comment]
Thanks @animeshsingh ! Really excited for all the work going in to kube-batch! I've gone ahead and created PR #226 . When that gets merged, you should get an invite to join @kubernetes-sigs. :) 🎉 



/assign

**Comment by dmatch01** [comment]
@mrbobbytables It seems that these to are not in sync: https://github.com/orgs/kubernetes-sigs/people (does not list animeshsingh) and https://github.com/kubernetes/org/blob/master/config/kubernetes-sigs/org.yaml (lists animeshsingh).  The `k8s-ci-robot` failed to allow assignment of a PR to animeshsingh since his ID was not listed in https://github.com/orgs/kubernetes-sigs/people.  Do you know hot to fix this sync?  Please advise.  Thanks!

**Comment by mrbobbytables** [comment]
@dmatch01 @animeshsingh must accept the membership invite before being able to have issues assigned. Github sends out an email with the invitation link shortly after the  PR is merged. 

Alternatively it can be accepted by going to the @kubernetes-sigs org page directly and accepting the invite there (there'll be a notification at the top asking if they wish to accept).

Hope that helps!

**Comment by dmatch01** [comment]
@mrbobbytables It did help!  Thank you
