### ISSUE TITLE
Netlify site request for Cluster API Provider AWS

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/org#2190]
Part of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1896

### Repository
kubernetes-sigs/cluster-api-provider-aws

### Project domain
cluster-api-aws.sigs.k8s.io

### Additional context for request
Netlify configuration in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1947/files#diff-5db06fd2327543bbb72119cd1e5761cf

**Comment by mrbobbytables** [comment]
The site will not appear until it's merged, but the preview URL is here:
https://kubernetes-sigs-cluster-api-provider-aws.netlify.app

You will also need to open an issue or PR in https://github.com/kubernetes/k8s.io to add the dns entry 👍

**Comment by randomvariable** [comment]
Thanks @mrbobbytables!

**Comment by randomvariable** [comment]
Does the CNAME and TLS cert need to be setup on the Netlify side? 

DNS was set up in https://github.com/kubernetes/k8s.io/pull/1249

**Comment by mrbobbytables** [comment]
Yup, I've finished configuring it on the netlify side:
https://cluster-api-aws.sigs.k8s.io/

  You should be good to go :D

With that I'm going to go ahead and close the issue, if you have any questions, please feel free to reopen or give me a ping.

Thanks!

/close
