### ISSUE TITLE
REQUEST: New membership for frankfarzan

### ISSUE THREAD

**Issue by frankfarzan** [kubernetes/org#2194]
### GitHub Username
@frankfarzan

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@Liujingfang1
@pwittrock 
@mortent 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kustomize/pull/1889
https://github.com/kubernetes-sigs/kustomize/pull/2165
https://github.com/kubernetes-sigs/kustomize/pull/1927
https://github.com/kubernetes-sigs/kustomize/pull/1917

- Issues responded to
https://github.com/kubernetes-sigs/kustomize/issues/2996
https://github.com/kubernetes-sigs/kustomize/issues/2823
https://github.com/kubernetes-sigs/kustomize/issues/1990
https://github.com/kubernetes-sigs/kustomize/issues/1989

- SIG projects I am involved with
https://github.com/kubernetes-sigs/kustomize

**Comment by Liujingfang1** [comment]
A big +1!

**Comment by mortent** [comment]
+1

**Comment by pwittrock** [comment]
Lgtm

**Comment by savitharaghunathan** [comment]
Hi, @frankfarzan 👋 Thank you for all your contributions :)

I've created PR #2197 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉 

/assign
