### ISSUE TITLE
REQUEST: New membership for howieyuen

### ISSUE THREAD

**Issue by howieyuen** [kubernetes/org#2199]
### GitHub Username
@howieyuen

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tengqm 
- @tanjunchen 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - [[zh] Translate /docs/concepts/cluster-administration/flow-control.md](https://github.com/kubernetes/website/pull/23910)
  - [[zh] optimize the translation of /docs/concepts/cluster-administration/flow-control.md](https://github.com/kubernetes/website/pull/23937)
  - [Add missing descriptions for /zh/docs/tasks](https://github.com/kubernetes/website/pull/23938)
  - [update kubectl api-resouces list based on 1.19.1](https://github.com/kubernetes/website/pull/23975)
  - [[zh] add missing links in/zh/docs/home/contribute](https://github.com/kubernetes/website/pull/23981)
  - [[zh]translate /zh/docs/tasks/configmap-secret/managing-secret-using-kubectl.md](https://github.com/kubernetes/website/pull/23983)
  - [[en] fix code block rendering mistake](https://github.com/kubernetes/website/pull/23986)
  - [[zh] translate zh/docs/tasks/configmap-secret/managing-secret-using-config-file.md](https://github.com/kubernetes/website/pull/24006)
  - [[zh] translate /zh/docs/tasks/configmap-secret/managing-secret-using-kustomize.md](https://github.com/kubernetes/website/pull/24016)
- Issues responded to
  - https://github.com/kubernetes/website/issues/23849
  - https://github.com/kubernetes/website/issues/23932
  - https://github.com/kubernetes/website/issues/23934
  - https://github.com/kubernetes/website/issues/23967
  - https://github.com/kubernetes/website/issues/23980
  - https://github.com/kubernetes/website/issues/24018
- SIG projects I am involved with
  - sig-docs

**Comment by tengqm** [comment]
LGTM, @howieyuen has been an active contributor to the Chinese localization of Kubernetes website and he has demonstrated good understanding of the technology and the documentation process.

**Comment by tanjunchen** [comment]
+1  @howieyuen   Thanks for your contribution.

**Comment by savitharaghunathan** [comment]
Hi, @howieyuen 👋 Thanks for your Chinese localization effort! 

I've created PR #2202 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by howieyuen** [comment]
> Hi, @howieyuen 👋 Thanks for your Chinese localization effort!
> 
> I've created PR #2202 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉
> 
> /assign

thanks 😄
