### ISSUE TITLE
Retire kubernetes-client/typescript

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/org#22]
### Repository to archive
kubernetes-client/typescript

### Repository and/or sig subproject owners that are approving this archival
@brendandburns 

### When should this be done
Anytime

### Additional context for request
https://github.com/kubernetes-client/typescript/issues/33

**Comment by cblecker** [comment]
+1

**Comment by spiffxp** [comment]
/assign
working on this now

**Comment by spiffxp** [comment]
/close
done

- https://github.com/kubernetes-retired/typescript
- [k-dev@ announcement](https://groups.google.com/forum/#!topic/kubernetes-dev/nlc7SKJc9Bg)
- added to this week's community meeting announcements
