### ISSUE TITLE
REQUEST: New membership for sfotony

### ISSUE THREAD

**Issue by sfotony** [kubernetes/org#2200]
### GitHub Username
e.g. @sfotony

### Organization you are requesting membership in
e.g. @kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jeremyrickard 
- @jrsapi

### List of contributions to the Kubernetes project
- I'm humbled to be a comms-shadow for the Kubernetes 1.20 release team.

**Comment by jrsapi** [comment]
Thanks for joining the Comms team as a shadow. Lgtm.

**Comment by savitharaghunathan** [comment]
+1. Welcome to the 1.20 release team! 🎉

**Comment by savitharaghunathan** [comment]
Hi, @sfotony 👋. Excited to have you as a part of the 1.20 cycle! Congratulations 🎉 

I've created PR #2202 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by palnabarun** [comment]
+1. Welcome to the 1.20 Release Team @sfotony! :tada:

**Comment by jeremyrickard** [comment]
+1
