### ISSUE TITLE
REQUEST: New membership for @eagleusb

### ISSUE THREAD

**Issue by eagleusb** [kubernetes/org#2201]
### GitHub Username

@eagleusb

### Organization you are requesting membership in

@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @annajung 
- @jeremyrickard 

### List of contributions to the Kubernetes project

- glad to join SIG Docs 1.20 release team !

**Comment by annajung** [comment]
+1 from me! Welcome to the team 🎉

**Comment by annajung** [comment]
cc @savitharaghunathan @palnabarun @hasheddan

**Comment by hasheddan** [comment]
+1 from me :rocket:

**Comment by savitharaghunathan** [comment]
+1. Welcome to the 1.20 team 🎉

**Comment by savitharaghunathan** [comment]
Hi, @eagleusb 👋  Excited to have you as a part of the 1.20 cycle! Congratulations 🎉 

I've created PR #2202 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by palnabarun** [comment]
+1. Welcome to the 1.20 Release Team @eagleusb! :tada:
