### ISSUE TITLE
REQUEST: New membership for SomtochiAma

### ISSUE THREAD

**Issue by SomtochiAma** [kubernetes/org#2204]
### GitHub Username
@SomtochiAma

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @annajung 
-  @jeremyrickard 
### List of contributions to the Kubernetes project
- PRs reviewed / authored
[kubernetes/kubernetes #88218](https://github.com/kubernetes/kubernetes/pull/88218) - Refactors MakeSecPods function
[kubernetes/kubernetes #87919](https://github.com/kubernetes/kubernetes/pull/87919) - Adds additional documentation for job status
[kubernetes/kubernetes #87565](https://github.com/kubernetes/kubernetes/pull/87565) - More unit tests for scheduler
[kubernetes/kubernetes #87455](https://github.com/kubernetes/kubernetes/pull/87455) - Adds unit test on Bind extension for the scheduler 
- Issues responded to
- SIG projects I am involved with
  - release

**Comment by annajung** [comment]
+1 from me! Welcome to the team! 🎉

cc @savitharaghunathan @hasheddan @palnabarun

**Comment by hasheddan** [comment]
+1 from me :)

**Comment by savitharaghunathan** [comment]
Hi, @SomtochiAma 👋. Excited to have you as a part of the 1.20 cycle! Congratulations 🎉

I've created PR #2202 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by palnabarun** [comment]
+1. Welcome to the 1.20 Release Team! :tada:

**Comment by SomtochiAma** [comment]
Thank you @palnabarun  @savitharaghunathan @annajung @hasheddan. Excited to be a part of the 1.20 Release Team!
