### ISSUE TITLE
REQUEST: New membership for adtac

### ISSUE THREAD

**Issue by adtac** [kubernetes/org#2205]
### GitHub Username
@adtac

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ahg-g 
- @Huang-Wei 

### List of contributions to the Kubernetes project
- PRs authored:
  - kubernetes/kubernetes and documentation:
    - https://github.com/kubernetes/kubernetes/pull/93252
    - https://github.com/kubernetes/kubernetes/pull/94814
    - https://github.com/kubernetes/kubernetes/pull/92200
    - https://github.com/kubernetes/kubernetes/pull/92391
    - https://github.com/kubernetes/kubernetes/pull/92840
    - https://github.com/kubernetes/kubernetes/pull/93026
    - https://github.com/kubernetes/kubernetes/pull/93730
    - https://github.com/kubernetes/kubernetes/pull/93733
    - https://github.com/kubernetes/kubernetes/pull/94782
    - https://github.com/kubernetes/website/pull/22038
  - kubernetes/perf-tests and kubernetes/test-infra:
    - https://github.com/kubernetes/perf-tests/pull/1419
    - https://github.com/kubernetes/perf-tests/pull/1442
    - https://github.com/kubernetes/perf-tests/pull/1464
    - https://github.com/kubernetes/perf-tests/pull/1467
    - https://github.com/kubernetes/perf-tests/pull/1474
    - https://github.com/kubernetes/perf-tests/pull/1418
    - https://github.com/kubernetes/test-infra/pull/19044
    - https://github.com/kubernetes/test-infra/pull/19165
- PRs reviewed:
  - https://github.com/kubernetes/kubernetes/pull/93425
  - https://github.com/kubernetes/kubernetes/pull/93511
  - https://github.com/kubernetes/kubernetes/pull/93831
  - https://github.com/kubernetes/kubernetes/pull/93959
  - https://github.com/kubernetes/kubernetes/pull/94884
  - https://github.com/kubernetes/kubernetes/pull/94636
- Issues responded to:
  - https://github.com/kubernetes/kubernetes/issues/93117
  - https://github.com/kubernetes/kubernetes/issues/89036
  - https://github.com/kubernetes/kubernetes/issues/94009
  - https://github.com/kubernetes/kubernetes/issues/93760
  - https://github.com/kubernetes/kubernetes/issues/93793
  - https://github.com/kubernetes/kubernetes/issues/94601
  - https://github.com/kubernetes/kubernetes/issues/93792
  - https://github.com/kubernetes/kubernetes/issues/93795
  - https://github.com/kubernetes/kubernetes/issues/93794
  - https://github.com/kubernetes/kubernetes/issues/94404
  - https://github.com/kubernetes/kubernetes/issues/94665
  - [full list](https://github.com/issues?q=is%3Aissue+author%3Aadtac+user%3Akubernetes+)
- SIG projects I am involved with:
  - sig scheduling

**Comment by ahg-g** [comment]
/lgtm

Thanks Adi, looking forward for more contributions in the future!

**Comment by Huang-Wei** [comment]
+1!

Looking forward to seeing more contributions!

**Comment by savitharaghunathan** [comment]
Hi, @adtac 👋 Thanks for all your contributions to the Kubernetes project!

I've created PR #2202 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
