### ISSUE TITLE
REQUEST: New membership for erismaster

### ISSUE THREAD

**Issue by erismaster** [kubernetes/org#2207]
### GitHub Username
@erismaster

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bai 
- @jeremyrickard 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
  * Release team 1.20 - Bug Triage
- Other
  * Kubernetes Office Hours

**Comment by savitharaghunathan** [comment]
+1. Welcome to the team, @erismaster! 👋

**Comment by palnabarun** [comment]
+1. Welcome to the release team @erismaster! :tada:

**Comment by palnabarun** [comment]
@erismaster, Excited to have you on the release team. Congratulations! :smile: 

I've created PR #2210 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign

**Comment by bai** [comment]
+1, glad to have you on the team!
