### ISSUE TITLE
REQUEST: New membership for srm09

### ISSUE THREAD

**Issue by srm09** [kubernetes/org#2208]
### GitHub Username
@srm09

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @vincepri 
- @CecileRobertMichon 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * https://github.com/kubernetes-sigs/cluster-api/pull/3508
  * https://github.com/kubernetes-sigs/cluster-api/pull/3166
  * https://github.com/kubernetes-sigs/cluster-api/pull/3164
  * https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/639
  * https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/658

- Issues responded to
  * https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+assignee%3Asrm09
  * https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/561
  * https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/557

- SIG projects I am involved with
  * kubernetes-sigs/cluster-api
  * kubernetes-sigs/cluster-api-provider-azure

**Comment by vincepri** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi @srm09 👋 Thanks for all your contributions to cluster-api :) 

I've created PR #2217 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
