### ISSUE TITLE
REQUEST: New membership for kinarashah

### ISSUE THREAD

**Issue by kinarashah** [kubernetes/org#2209]
### GitHub Username
@kinarashah

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @kikisdeliveryservice 
- @jeremyrickard 
- @savitharaghunathan  
- @palnabarun 

### List of contributions to the Kubernetes project
- I'm excited to join as Enhancements shadow for the Kubernetes 1.20 release team 🙂

**Comment by kikisdeliveryservice** [comment]
+1

Welcome Kinara! So happy to have you on the team!

/lgtm

**Comment by palnabarun** [comment]
+1. Welcome to the 1.20 Enhancements team @kinarashah :tada:

**Comment by palnabarun** [comment]
@kinarashah, Excited to have you on the release team. Congratulations! :smile: 

I've created PR #2210 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
