### ISSUE TITLE
REQUEST: New membership for @ScrapCodes

### ISSUE THREAD

**Issue by ScrapCodes** [kubernetes/org#2211]
### GitHub Username
@ScrapCodes

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @RobertKielty 
- @jeremyrickard 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/94717
https://github.com/kubernetes/kubernetes/pull/94716
https://github.com/kubernetes/kubernetes/pull/90165
https://github.com/kubernetes/kubernetes/pull/89725
https://github.com/kubernetes/kubernetes/pull/88364
https://github.com/kubernetes/kubernetes/pull/94082

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/94520
https://github.com/kubernetes/kubernetes/issues/89719
https://github.com/kubernetes/kubernetes/issues/94221

- SIG projects I am involved with
release - Shadow at CI signal team

**Comment by savitharaghunathan** [comment]
+1. Welcome to the 1.20 RT, @ScrapCodes 🎉

**Comment by palnabarun** [comment]
+1. Welcome to the 1.20 Release Team @ScrapCodes! :tada:

**Comment by palnabarun** [comment]
@ScrapCodes, excited to have you in the release team! :smiley:

I've created PR #2214 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign

**Comment by ScrapCodes** [comment]
Thank you so much, @savitharaghunathan and @palnabarun 😄  Excited to join the team !
