### ISSUE TITLE
REQUEST: New membership for thejoycekung

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/org#2212]
### GitHub Username
@thejoycekung

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @RobertKielty 
- @jeremyrickard 

### List of contributions to the Kubernetes project
- SIG projects I am involved with:
Release - CI Signal Shadow for 1.20

**Comment by savitharaghunathan** [comment]
+1. Welcome to the 1.20 RT, @thejoycekung 🎉

**Comment by palnabarun** [comment]
+1. Welcome to the 1.20 Release Team @thejoycekung! :tada:

**Comment by palnabarun** [comment]
@thejoycekung, excited to have you in the release team! :smiley:

I've created PR #2214 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign

**Comment by RobertKielty** [comment]
A late +1 Welcome to the 1.20 Release Team @thejoycekung!
