### ISSUE TITLE
REQUEST: New membership for MonzElmasry

### ISSUE THREAD

**Issue by MonzElmasry** [kubernetes/org#2215]
### GitHub Username
@MonzElmasry
### Organization you are requesting membership in
@kubernetes
### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bai 
- @jeremyrickard 

### List of contributions to the Kubernetes project
- SIG projects I am involved with:
Release - Bug Triage Shadow for 1.20

**Comment by bai** [comment]
Glad to have you on the team! 🐛

**Comment by palnabarun** [comment]
+1. Welcome to the 1.20 Release Team @MonzElmasry! :tada:

**Comment by savitharaghunathan** [comment]
+1. Excited to have you in the 1.20 Release Team, @MonzElmasry! 🎉

**Comment by palnabarun** [comment]
@MonzElmasry, excited to have you in the release team :smile: 

I've created PR #2214 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
