### ISSUE TITLE
REQUEST: New membership for tanjacky

### ISSUE THREAD

**Issue by tanjacky** [kubernetes/org#2216]
### GitHub Username
@tanjacky

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @JamesLaverack 
- @lachie83

### List of contributions to the Kubernetes project
Release Notes Shadow for 1.20

**Comment by JamesLaverack** [comment]
+1, welcome 🎉

**Comment by savitharaghunathan** [comment]
+1. Welcome to the team @tanjacky 🎉

**Comment by savitharaghunathan** [comment]
Hi, @tanjacky 👋. Excited to have you as a part of the 1.20 release cycle! Congratulations 🎉

I've created PR #2202 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
