### ISSUE TITLE
REQUEST: New membership for michaelbeaumont

### ISSUE THREAD

**Issue by michaelbeaumont** [kubernetes/org#2224]
### GitHub Username
@michaelbeaumont

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@richardcase
@randomvariable 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - [5 PRs contributed, 1 review in `cluster-api-provider-aws`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+involves%3Amichaelbeaumont)
- SIG projects I am involved with
  - sig-cluster-lifecycle

**Comment by randomvariable** [comment]
+1 from me

**Comment by richardcase** [comment]
+1 from me as well :+1:

**Comment by ameukam** [comment]
Hi @michaelbeaumont, thank you for all your contributions so far :)

I've created PR #2237 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! :tada:
