### ISSUE TITLE
Request for new repository: kubernetes/component-helpers

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/org#2231]
### New Repo, Staging Repo, or migrate existing
staging repo

### Requested name for new repository
component-helpers

### Which Organization should it reside
kubernetes

### If not a staging repo, who should have admin access
NONE

### If not a staging repo, who should have write access
NONE

### If not a staging repo, who should be listed as approvers in OWNERS
NONE

### If not a staging repo, who should be listed in SECURITY_CONTACTS
NONE

### What should the repo description be
High-level helpers for kubernetes components

### What SIG and subproject does this fall under in sigs.yaml
this is a new staging repository component-helpers for sig-arch

### Approvals
The new repository was discussed during sig-arch meeting https://youtu.be/yngBgHeLOW8.
I have addressed comments and requests for changes.

k/k PR adding the new repository with ongoing discussion: https://github.com/kubernetes/kubernetes/pull/92507

### Additional context for request
Any additional information or context to describe the request.

**Comment by ingvagabund** [comment]
@dims @liggitt I think I have addressed all you requested for. Can you approve?

**Comment by dims** [comment]
+1 from me. Did you already throw an email to sig-arch @ingvagabund ? please do if not

cc @johnbelamaric @derekwaynecarr

**Comment by ingvagabund** [comment]
> Did you already throw an email to sig-arch

https://groups.google.com/g/kubernetes-sig-architecture/c/U05V0W2zTi4/m/QU0stWTICAAJ

**Comment by nikhita** [comment]
/assign

@dims @ingvagabund let me know when you are good to go ahead with repo creation and I'll get that setup!

**Comment by ingvagabund** [comment]
@derekwaynecarr posted his +1 in https://groups.google.com/g/kubernetes-sig-architecture/c/U05V0W2zTi4/m/jIGMlOQDCgAJ

@dims should we wait for @johnbelamaric or it is safe to go ahead and unhold?

**Comment by dims** [comment]
@ingvagabund +1 to go ahead :)

/hold cancel

**Comment by ingvagabund** [comment]
@nikhita we are good to go. Thanks!!!

**Comment by nikhita** [comment]
Repo has been setup - https://github.com/kubernetes/component-helpers

Also created:

- https://github.com/kubernetes/test-infra/pull/19422 - to setup prow configuration for the staging repo
- https://github.com/kubernetes/community/pull/5184 - to add the repo to sigs.yaml
- https://github.com/kubernetes/publishing-bot/pull/237 - to add the repo to publishing-bot test scripts

Once the above PRs have merged, we can close this issue.

**Comment by nikhita** [comment]
Closing. We can follow up on the publishing-bot PR separately.
