### ISSUE TITLE
REQUEST: New membership for rikatz - kubernetes-sigs

### ISSUE THREAD

**Issue by rikatz** [kubernetes/org#2240]
### GitHub Username
@rikatz

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

I'm already a member of kubernetes org, need membership in kubernetes-sigs because we're planning to move the sig-network network policy subproject to k-sigs as well :)

Thank you very much!

**Comment by mrbobbytables** [comment]
No sponsorship needed :) if you want, you can PR yourself in (just please follow the commit msg convention). Otherwise you'll get added in the next batch of membership requests :+1:

**Comment by rikatz** [comment]
oh right, thanks! :) Will do the PR then.
