### ISSUE TITLE
REQUEST: New membership for tkashem

### ISSUE THREAD

**Issue by tkashem** [kubernetes/org#2242]
### GitHub Username
@tkashem

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
Already member of @kubernetes

**Comment by palnabarun** [comment]
Hi @tkashem, I have raised #2258 to add you to the @kubernetes-sigs organization. You should get a membership invite notification once that gets merged. :tada:

**Comment by nikhita** [comment]
Done in https://github.com/kubernetes/org/pull/2258 :)
