### ISSUE TITLE
REQUEST: New membership for knabben

### ISSUE THREAD

**Issue by knabben** [kubernetes/org#2248]
### GitHub Username
@knabben

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mtaufen
- @alejandrox1 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=org%3Akubernetes+knabben&type=commits
https://github.com/search?q=org%3Akubernetes-sigs+knabben&type=commits

- Issues responded to
https://github.com/search?q=org%3Akubernetes+knabben&type=issues

- SIG projects I am involved with
*WG Component Standard*
*SIG Node CI Group*

**Comment by alejandrox1** [comment]
Huge +1!
Thank you for all your contributions @knabben

**Comment by mtaufen** [comment]
+1! Thank you @knabben for all your work :)

**Comment by palnabarun** [comment]
@knabben, thank you for all your contributions so far :)

I've created PR #2253 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
