### ISSUE TITLE
REQUEST: New membership for jbartosik

### ISSUE THREAD

**Issue by jbartosik** [kubernetes/org#225]
### GitHub Username
@jbartosik

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jberkus 
- @MaciekPytel 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * Refactoring Horizontal Pod Autoscaler: [1](https://github.com/kubernetes/kubernetes/pull/65828), [2](https://github.com/kubernetes/kubernetes/pull/65901), [3](https://github.com/kubernetes/kubernetes/pull/65907), 
  * Improving HPA algorithm: [1](https://github.com/kubernetes/kubernetes/pull/66615), [2](https://github.com/kubernetes/kubernetes/pull/67252), [3](https://github.com/kubernetes/kubernetes/pull/68831),
  * Deflaking HPA e2e tests: [1](https://github.com/kubernetes/kubernetes/pull/70125), [2](https://github.com/kubernetes/kubernetes/pull/70233), [3](https://github.com/kubernetes/kubernetes/pull/70441), [4](https://github.com/kubernetes/kubernetes/pull/70579), [5](https://github.com/kubernetes/kubernetes/pull/70649),
  * Refactoring Cluster Autoscaler: [1](https://github.com/kubernetes/autoscaler/pull/1016/files), [2](https://github.com/kubernetes/autoscaler/pull/880/files).
- Issues responded to
  * Flaky e2e HPA tests: [1](https://github.com/kubernetes/kubernetes/issues/69444), [2](https://github.com/kubernetes/kubernetes/issues/70655).

- SIG projects I am involved with

sig-autoscaling

/area github-membership

**Comment by MaciekPytel** [comment]
Big +1 from me: @jbartosik has became a regular contributor in sig-autoscaling. He has already made significant improvements to HPA algorithm and he did much more than his fair share of maintenance work debugging and fixing tests to unblock 1.13 release.

**Comment by jberkus** [comment]
+1  jbartosik is the lead in resolving issues with HPA for this release.

**Comment by mrbobbytables** [comment]
Hey there @jbartosik , thank you for all your help with the HPA and the other work you've done :)

I've created PR #226   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
