### ISSUE TITLE
REQUEST: New membership for nicolehanjing

### ISSUE THREAD

**Issue by nicolehanjing** [kubernetes/org#2250]
### GitHub Username
@nicolehanjing

### Organization you are requesting membership in
@kubernetes-sigs @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andrewsykim 
- @nckturner 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/95342
https://github.com/kubernetes/cloud-provider-aws/pull/131
https://github.com/kubernetes/cloud-provider-aws/pull/128
https://github.com/kubernetes/cloud-provider-aws/pull/136
https://github.com/kubernetes/cloud-provider-aws/pull/129
https://github.com/kubernetes/kubernetes/pull/94736
- Issues responded to
https://github.com/kubernetes/cloud-provider-aws/issues/125
- SIG projects I am involved with
cloud-provider

**Comment by andrewsykim** [comment]
+1 from me, thanks @nicolehanjing!

**Comment by nckturner** [comment]
+1 from me

**Comment by palnabarun** [comment]
@nicolehanjing, thank you for all your contributions so far :)

I've created PR #2258 to add you to the @kubernetes and @kubernetes-sigs organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! :tada:

/assign

**Comment by nicolehanjing** [comment]
> @nicolehanjing, thank you for all your contributions so far :)
> 
> I've created PR #2258 to add you to the @kubernetes and @kubernetes-sigs organizations. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes and @kubernetes-sigs! 🎉
> 
> /assign

thank you!
