### ISSUE TITLE
REQUEST: New membership for zhiguo-lu

### ISSUE THREAD

**Issue by zhiguo-lu** [kubernetes/org#2252]
### GitHub Username
@zhiguo-lu

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @idealhack 
- @tengqm 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   kubernetes/website #24406 
   kubernetes/website #24179
   kubernetes/website #24159
   kubernetes/website #24099
   kubernetes/website #24087
   kubernetes/website #24062
   kubernetes/website #24060
   kubernetes/website #24012
   kubernetes/website #23971
   kubernetes/website #23872
   kubernetes/website #23813

- Issues responded to
   kubernetes/website #24396
   kubernetes/website #24362
   kubernetes/website #24177
   kubernetes/website #24157
   kubernetes/website #24097
   kubernetes/website #24086
   kubernetes/website #24061
   kubernetes/website #24025
   kubernetes/website #24011
   kubernetes/website #23950
   kubernetes/website #23920
   kubernetes/website #23810
- SIG projects I am involved with

**Comment by tengqm** [comment]
+1

**Comment by idealhack** [comment]
+1

Thank you for all the contributions and welcome on board!

**Comment by palnabarun** [comment]
@zhiguo-lu, thank you for your contributions to the Kubernetes Documentation :)

I've created PR #2253 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
