### ISSUE TITLE
REQUEST: New membership for zshihang

### ISSUE THREAD

**Issue by zshihang** [kubernetes/org#2255]
### GitHub Username
@zshihang

### Organization you are requesting membership in
@kubernetes @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
 
- @liggitt
- @micahhausler 
- @mikedanese

### List of contributions to the Kubernetes project
- PRs reviewed / authored: 
    - [KEPs](https://github.com/search?q=is%3Apr+author%3Azshihang+repo%3Akubernetes%2Fenhancements&type=Issues)
    - [CRs](https://github.com/search?p=2&q=is%3Apr+author%3Azshihang+repo%3Akubernetes%2Fkubernetes&type=Issues)
- Issues responded to
- SIG projects I am involved with
    - @sig-auth
    - @sig-storage

**Comment by liggitt** [comment]
+1

**Comment by micahhausler** [comment]
+1

**Comment by palnabarun** [comment]
@zshihang, thank you for all your contributions so far :)

I've created PR #2258 to add you to the @kubernetes and @kubernetes-sigs Organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! :tada:

/assign
