### ISSUE TITLE
REQUEST: New membership for @wilsonehusin

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/org#2257]
### GitHub Username
@wilsonehusin 

### Organization you are requesting membership in
@kubernetes-sigs 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects (1.20 Release Notes Shadow)
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @JamesLaverack (1.20 Release Notes Lead)
- already a member of @kubernetes

### List of contributions to the Kubernetes project
- Release Notes for 1.19
- Upcoming Release Notes for 1.20

**Comment by palnabarun** [comment]
Hi @wilsonehusin, I have raised #2258 to add you to the @kubernetes-sigs organization. You should get a membership invite notification once that gets merged. :tada: 

Thank you for all your help with the Release Notes! :)

**Comment by nikhita** [comment]
Done in https://github.com/kubernetes/org/pull/2258 :)
