### ISSUE TITLE
REQUEST: New membership for @gkarthiks

### ISSUE THREAD

**Issue by gkarthiks** [kubernetes/org#2259]
### GitHub Username
@gkarthiks 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @chris-short 
- @mbbroberg 

#### PRs reviewed / authored
- https://github.com/kubernetes/kubernetes/pull/95201
- https://github.com/kubernetes/kubernetes/pull/88217
- https://github.com/kubernetes/test-infra/pull/16009
- https://github.com/kubernetes/community/pull/4045
- https://github.com/kubernetes/community/pull/4648
- https://github.com/kubernetes/kubernetes/pull/85562
- https://github.com/kubernetes/kubernetes/pull/85440
- https://github.com/kubernetes/kubernetes/pull/88084
- https://github.com/kubernetes/kubernetes/pull/63707
- https://github.com/kubernetes/autoscaler/pull/3487
- https://github.com/kubernetes/kubernetes/pull/88484
#### Issues responded to
- https://github.com/kubernetes/client-go/issues/788
- https://github.com/kubernetes/community/issues/5201
- https://github.com/kubernetes/community/issues/2565
- https://github.com/kubernetes/website/issues/21030
- https://github.com/kubernetes-sigs/metrics-server/issues/36
- https://github.com/kubernetes-sigs/metrics-server/issues/34
- https://github.com/kubernetes/community/issues/4430
- https://github.com/kubernetes/kubectl/issues/809
- https://github.com/kubernetes/kubectl/issues/505

#### SIG projects I am involved with
- sig-contributor-experience (https://github.com/kubernetes/community)
   - [upstream marketing team with sig-contributor-experience]
- WG Naming

**Comment by chris-short** [comment]
+1

**Comment by mbbroberg** [comment]
+10000 -- so happy to have you as part of our working group @gkarthiks!

**Comment by palnabarun** [comment]
Hi @gkarthiks :wave:, thank you for helping out with the upstream marketing team and for applying to be a @kubernetes-sigs organization member.

A requirement for sponsors is that they need to be from different companies. Unfortunately, both sponsors @chris-short and @mbbroberg are from the same company.

Can you please add one more sponsor satisfying all the guidelines mentioned in https://github.com/kubernetes/community/blob/master/community-membership.md#requirements?

Thank you. :slightly_smiling_face:

**Comment by palnabarun** [comment]
Oh, wait! I just saw that you are already a member of @kubernetes. In that case, you are automatically eligible for a membership to @kubernetes-sigs and hence don't need fresh sponsorship. :slightly_smiling_face: 

Sorry for the confusion! :sweat_smile: 

I will raise a PR shortly to add you to @kubernetes-sigs.

**Comment by palnabarun** [comment]
I have raised # to add you to the @kubernetes-sigs organization. Once merged, you will get a membership invite notification.

Welcome to @kubernetes-sigs as well! :tada: 

/assign
