### ISSUE TITLE
REQUEST: New membership for @troy0820

### ISSUE THREAD

**Issue by troy0820** [kubernetes/org#2261]
### GitHub Username
@troy0820

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @kikisdeliveryservice 
### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pulls?q=+is%3Apr+author%3Atroy0820+

- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+commenter%3Atroy0820+

- Other 
  - Program committee member for KubeCon/CloudNativeCon 2019 (Barcelona & San Diego)
  - Program committee member for KubeCon/CloudNativeCon 2020 (EU & NA)

**Comment by kikisdeliveryservice** [comment]
Troy is a great k8s member, and should have already become a member via his kubecon program committee work some time ago!! :eyes: 

+100

**Comment by dims** [comment]
+1 from me. welcome aboard!

**Comment by parispittman** [comment]
+1!! so glad to have you

**Comment by palnabarun** [comment]
@troy0820, thank you for all your contributions so far :)

I've created PR #2262 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
