### ISSUE TITLE
REQUEST: New membership for arghya88

### ISSUE THREAD

**Issue by arghya88** [kubernetes/org#2264]
### GitHub Username
@arghya88

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @randomvariable 
- @richardcase

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2010
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2006
https://github.com/kubernetes-sigs/cluster-api/pull/3721
https://github.com/kubernetes-sigs/cluster-api/pull/3776
https://github.com/kubernetes/kubernetes/pull/95085
https://github.com/kubernetes/kubernetes/pull/94884
https://github.com/kubernetes/kubernetes/pull/95001
- Issues responded to
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2020
- SIG projects I am involved with: cluster-api, cluster-api-provider-aws

**Comment by richardcase** [comment]
Yes please on @arghya88 membership so....
+1

**Comment by randomvariable** [comment]
+1

**Comment by palnabarun** [comment]
@arghya88, thank you for all your contributions so far :)

I've created PR #2267 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! :tada:

/assign
