### ISSUE TITLE
REQUEST: New membership for ysy2020

### ISSUE THREAD

**Issue by ysy2020** [kubernetes/org#2265]
### GitHub Username
@ysy2020

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Jeffwan
- @RainbowMango

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/autoscaler/pull/3339
https://github.com/kubernetes/autoscaler/pull/3406
https://github.com/kubernetes/autoscaler/pull/3573

- Issues responded to
- SIG projects I am involved with

**Comment by RainbowMango** [comment]
+1

**Comment by Jeffwan** [comment]
+1

I'd like to sponsor @ysy2020 's membership. Thanks for the contribution on cluster autoscaler.

**Comment by savitharaghunathan** [comment]
Hi, @ysy2020 👋 Thank you for all your contributions :)

I've created PR #2273 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
