### ISSUE TITLE
REQUEST: New membership for dthorsen

### ISSUE THREAD

**Issue by dthorsen** [kubernetes/org#2266]
### GitHub Username
@dthorsen

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @richardcase
- @randomvariable

### List of contributions to the Kubernetes project
- PRs reviewed / authored
-- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1992
-- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1994
-- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2007
-- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2021
-- https://github.com/kubernetes-sigs/cluster-api/pull/3673

- Issues responded to
-- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2022
-- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2023
-- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1764
-- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1534

- SIG projects I am involved with
-- cluster-api
-- cluster-api-provider-aws

**Comment by richardcase** [comment]
+1

**Comment by randomvariable** [comment]
+1

**Comment by palnabarun** [comment]
@dthorsen, thank you for all your contributions so far :)

I've created PR #2267 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! :tada:

/assign
