### ISSUE TITLE
REQUEST: New membership for @wenjiaswe

### ISSUE THREAD

**Issue by wenjiaswe** [kubernetes/org#227]
### GitHub Username
@wenjiaswe

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jpbetz 
- @gyuho 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/70144
https://github.com/kubernetes/kubernetes/pull/70663
https://github.com/kubernetes/kubernetes/pull/68530
https://github.com/kubernetes/kubernetes/pull/61241
https://github.com/kubernetes/kubernetes/pull/60173
https://github.com/kubernetes/kubernetes/pull/59897
https://github.com/kubernetes/kubernetes/pull/59836
https://github.com/kubernetes/community/pull/2835

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/70143
https://github.com/kubernetes/kubernetes/issues/58552

- SIG projects I am involved with
sig api-machinery

/area github-membership

**Comment by gyuho** [comment]
+1

**Comment by jpbetz** [comment]
+1

**Comment by jpbetz** [comment]
+1

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #228  to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome (in advance)! :)
/assign

**Comment by wenjiaswe** [comment]
Thanks Stephen, Joe and Gyuho! @justaugustus @jpbetz @gyuho
