### ISSUE TITLE
Repo request: kubernetes-sigs/e2e-framework

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/org#2271]
### New Repo, Staging Repo, or migrate existing
New Repo

### Requested name for new repository
e2e-framework

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@andrewsykim @alejandrox1 @BenTheElder @spiffxp 

### If not a staging repo, who should have write access
@andrewsykim @alejandrox1 @BenTheElder @spiffxp 

### If not a staging repo, who should be listed as approvers in OWNERS
@andrewsykim @alejandrox1 @BenTheElder @spiffxp 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@andrewsykim @alejandrox1 @BenTheElder @spiffxp 

### What should the repo description be
An experimental e2e testing framework for Kubernetes clusters.

### What SIG and subproject does this fall under in sigs.yaml
sig-testing

### Approvals
https://github.com/kubernetes/enhancements/pull/1763

Requires approval from SIG Testing chairs

### Additional context for request
Following up from discussions in https://github.com/kubernetes/enhancements/pull/1763, there was general agreement that starting a new framework external to the one in kubernetes/kubernetes would yield better results. This repo is a starting point for something experimental that will help move projects off of vendoring kubernetes/kubernetes for an e2e testing framework.

**Comment by alejandrox1** [comment]
+1
:rocket:

**Comment by spiffxp** [comment]
+1 as SIG Testing chair

**Comment by BenTheElder** [comment]
+2 :+1: :+1:

**Comment by nikhita** [comment]
Here we go - https://github.com/kubernetes-sigs/e2e-framework :) 

- https://github.com/kubernetes/org/pull/2278 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/5252 - to add the repo to sigs.yaml

**Comment by andrewsykim** [comment]
Thanks @nikhita!

**Comment by nikhita** [comment]
Teams have been granted access, and sigs.yaml has been updated. Closing!
