### ISSUE TITLE
REQUEST: New membership for Promaethius

### ISSUE THREAD

**Issue by Promaethius** [kubernetes/org#2274]
### GitHub Username
@Promaethius

### Organization you are requesting membership in
sigs@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @randomvariable 
- @rudoi

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
  https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1924
  https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1864
  https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1858
- Issues responded to:
- SIG projects I am involved with:
  cluster-api
  cluster-api-provider-aws
  image-builder

**Comment by rudoi** [comment]
+1 🎉

**Comment by randomvariable** [comment]
+1
