### ISSUE TITLE
 Set code owners for /.github

### ISSUE THREAD

**Issue by sftim** [kubernetes/org#2276]
### Organization or repository

I think this is relevant to most repos in the Kubernetes organization.

### Describe the issue
Granting people the ability to write into `/.github/workflows` can provide some measure of privilege escalation, so I recommend locking down access there.
Specifically, I would add an `OWNERS` file inside `.github/workflows` with a limited set of approvers, possibly narrower than the repository root OWNERS file.

#### Example
[/.github/OWNERS](https://github.com/kubernetes/kubernetes/blob/b206f6695f5355d9a671ca9b0ceb099333b818c5/.github/OWNERS) for _k/kubernetes_ lists SIG Contributor Experience reviewers as controlling changes, which does make sense - however, access to approve GitHub Action changes also implies escalation to run repository actions as the repository, which may not be intended.
Perhaps SIG Release would be a better fit here?

**Comment by mrbobbytables** [comment]
Broadly, we encourage people to use prow over actions with a few exceptions. It may be worth just disabling actions at the org level and request folks to opt into it being enabled for the repo.

Regarding k/k - I don't think we have any intention of enabling github actions for k/k. Anything in there we would do through prow.

**Comment by sftim** [comment]
Disabling Actions at the repo level is a valid way to achieve the same outcome (likewise at the org level, if that's an option).

**Comment by spiffxp** [comment]
Out of curiosity, what's the case for narrowing github action approval further than root owners?

**Comment by sftim** [comment]
SIG Contribex quite rightly get to update the issue and PR templates. It's a little surprising if that access also allows running Actions (and the things that Actions are allowed to do, such as pushing branches).

**Comment by mrbobbytables** [comment]
With regard to the owners in k/k - contribex wouldn't enable actions. The approvers are on the GitHub admin team. There is enough trust there where I don't think its an issue.

**Comment by spiffxp** [comment]
/close
I think it's a valid concern @sftim, but it's not something I feel inclined to enforce or disable org-wide at the moment.  Some of our subprojects use Actions today, and tide/prow is able to read Checks, so there is better support than there used to be.  If they become too much of a support burden, we'll revisit.

Specifically for kubernetes/kubernetes I agree with @mrbobbytables that we can trust the current OWNERS.
