### ISSUE TITLE
Need help in adding deprecated messages to (retired) kubernetes-incubator nfs sub-projects

### ISSUE THREAD

**Issue by kmova** [kubernetes/org#2279]
### Organization or repository
https://github.com/kubernetes-retired/external-storage

### Users affected
(Affects the contributors trying to look for information on the new home for the migrated repositories.)

### Describe the issue

As part of retiring the kubernetes-incubator/external-storage repository, the following sub-projects have been migrated to kubernetes-sigs. 

* https://github.com/kubernetes-retired/external-storage/tree/master/nfs is moved to https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner
* https://github.com/kubernetes-retired/external-storage/tree/master/nfs-client is moved to https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner

Prior to migration, I missed updating the corresponding README under the subprojects to point to the new home for the code. 

I need admin help in updating the following README.md files with a deprecated message and giving information about the new location.  

https://github.com/kubernetes-retired/external-storage/blob/master/nfs/README.md
```
## Deprecated

Moved to https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner. This will no longer be updated. Please open issues or PRs there!
```

https://github.com/kubernetes-retired/external-storage/blob/master/nfs-client/README.md
```
## Deprecated

Moved to https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. This will no longer be updated. Please open issues or PRs there!
```

**Comment by nikhita** [comment]
/assign

Done :) 

- https://github.com/kubernetes-retired/external-storage/tree/master/nfs-client
- https://github.com/kubernetes-retired/external-storage/tree/master/nfs

If you need any more help, please feel free to reopen this issue!

**Comment by kmova** [comment]
That was super fast. thank you @nikhita
