### ISSUE TITLE
REQUEST: New membership for makkes

### ISSUE THREAD

**Issue by makkes** [kubernetes/org#2282]
### GitHub Username
@makkes

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jimmidyson 
- @irfanurrehman 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/kubefed/pulls?q=+is%3Apr+author%3Amakkes
  - outside of multicluster SIG: 
    - https://github.com/kubernetes-csi/external-snapshotter/pull/334
    - https://github.com/kubernetes/enhancements/pull/1532
- Issues responded to
  - https://github.com/kubernetes-sigs/kubefed/issues?q=is%3Aissue+makkes+
- SIG projects I am involved with
  - kubefed

**Comment by jimmidyson** [comment]
:+1:

**Comment by irfanurrehman** [comment]
I endorse @makkes membership. He has been ardently reviewing PRs in the kubefed project and has additionally done many small contributions to the same.

**Comment by savitharaghunathan** [comment]
Hi, @makkes 👋 Thank you for all your contributions :)

I've created PR #2292 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
