### ISSUE TITLE
REQUEST: New membership for endocrimes

### ISSUE THREAD

**Issue by endocrimes** [kubernetes/org#2283]
### GitHub Username
@endocrimes

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @ehashman 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr++commenter%3Aendocrimes
- Issues responded to
    https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+commenter%3Aendocrimes
- SIG projects I am involved with
    sig-node mentorship program

**Comment by troy0820** [comment]
+1

**Comment by ehashman** [comment]
+1, confirming my sponsorship :)

**Comment by justaugustus** [comment]
Yayyy, +1!

**Comment by dims** [comment]
+1 about time! :)

**Comment by savitharaghunathan** [comment]
Hi, @endocrimes 👋 Thank you for all your contributions :)

I've created PR #2292 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by endocrimes** [comment]
@savitharaghunathan thank you! ✨

**Comment by troy0820** [comment]
YAY!!!! 🎉  ✨ 👍
