### ISSUE TITLE
REQUEST: New membership for michaelgugino

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/org#2284]
### GitHub Username
@michaelgugino

### Organization you are requesting membership in
kubernetes

### Requirements
- [x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x ] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mortent 
- @derekwaynecarr 

### List of contributions to the Kubernetes project
I've contributed to the eviction API as well as kubectl/drain numerous times.  Here's some of that work

Eviction API work:
https://github.com/kubernetes/kubernetes/pull/94381
https://github.com/kubernetes/kubernetes/pull/91342

Drain Work:
https://github.com/kubernetes/kubernetes/pull/93947
https://github.com/kubernetes/kubernetes/pull/88337
https://github.com/kubernetes/kubernetes/pull/85577

**Comment by mortent** [comment]
+1

**Comment by derekwaynecarr** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi, @michaelgugino 👋 Thank you for all your contributions :)

I've created PR #2292  to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
