### ISSUE TITLE
Add a site: cli-docs.sigs.k8s.io

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/org#2287]
### Repository

https://github.com/kubernetes-sigs/cli-experimental

### Project domain

cli-docs.sigs.k8s.io

NOTE: Must match domain request.
See subproject site request docs for more information:
http://git.k8s.io/community/github-management/subproject-site-requests.md#subproject-domain-request

### Additional context

👋 I'm making this request as a [temporary SIG CLI admin](https://github.com/kubernetes/org/pull/2286), in consultation with @pwittrock. 

The initial domain request was for `cli.docs.kubernetes.io`. After advice from @mrbobbytables, I'm modifying the request to conform with community standards: `cli-docs.sigs.k8s.io`. 

/assign @pwittrock

**Comment by pwittrock** [comment]
We already have http://kubectl.docs.kubernetes.io.  Can we update the link to point to new site?

**Comment by cblecker** [comment]
I've approved the Netlify integration for the cli-experimental repo.

@zacharysarah You should be able to proceed with next steps on the Netlify side. We'll still need to get the DNS bits though.

**Comment by pwittrock** [comment]
Thanks!  How do we update the DNS for netlify?  Is it here?  https://github.com/kubernetes/website

**Comment by pwittrock** [comment]
Looks like we need to make a change [here](https://github.com/kubernetes/k8s.io/blob/master/dns/zone-configs/k8s.io._0_base.yaml)?

Are there instructions explaining what we need to do?

**Comment by pwittrock** [comment]
Looks like we just copy this: https://github.com/kubernetes/k8s.io/commit/de672008ff5b0e1449247586cd72ac9dcc365ac2

**Comment by nikhita** [comment]
@pwittrock https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md :)

**Comment by pwittrock** [comment]
Thanks!  This is exactly what I was looking for!

**Comment by nikhita** [comment]
@pwittrock :wave: just following up, are there any more outstanding issues that you need help with?

**Comment by mrbobbytables** [comment]
Are there any more action items with this?

**Comment by mrbobbytables** [comment]
As there hasn't been any follow up since October, I'm going to mark this as rotten.
/lifecycle rotten

@pwittrock If you still need assistance, please go ahead and mark it as active.

**Comment by pwittrock** [comment]
Sorry didn't see this.  Thanks for all the help!  Everything is working great now.

**Comment by mrbobbytables** [comment]
Thanks!
/close
