### ISSUE TITLE
REQUEST: New membership for benmoss

### ISSUE THREAD

**Issue by benmoss** [kubernetes/org#229]
### GitHub Username
@benmoss

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @michmike  
- @PatrickLang 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/community/pull/2615
https://github.com/kubernetes/kubernetes/pull/70379
https://github.com/kubernetes/kubernetes/pull/67447
https://github.com/kubernetes/kubernetes/pull/69439
https://github.com/kubernetes/kubernetes/pull/70121
https://github.com/kubernetes/kubernetes/pull/70482
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/69450
https://github.com/kubernetes/kubernetes/pull/67435
https://github.com/kubernetes/kubernetes/issues/68189
- SIG projects I am involved with
sig-windows

/area github-membership

**Comment by hoegaarden** [comment]
+1
/lgtm
🎉

**Comment by mrbobbytables** [comment]
Hey there @benmoss . Unfortunately, @hoegaarden cannot sponsor you for membership in the @kubernetes org.

An approver/reviewer in @kubernetes, may sponsor someone for the @kubernetes org or any of the related organizations (@kubernetes-sigs, @kubernetes-incubator etc); as long as its a project they're involved with.

However, this does not work the other way around. A sponsor that is only an approver/reviewer in @kubernetes-sigs cannot sponsor someone for membership in @kubernetes. They are scoped to sponsor those just to the org they're associated with.

With that in mind, would you mind soliciting another sponsor from the @kubernetes org?

Thanks!

**Comment by michmike** [comment]
+1

**Comment by mrbobbytables** [comment]
Thanks for stepping in @michmike :) 

@benmoss I've created PR #234   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
