### ISSUE TITLE
REQUEST: New membership for dprotaso

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/org#2294]
### GitHub Username
dprotaso

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @nader-ziada
- @liggitt

### List of contributions to the Kubernetes project
- PRs reviewed / authored - https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr++commenter%3Adprotaso
- Issues responded to - https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+commenter%3Adprotaso
- SIG projects I am involved with 
   - api-machinery

**Comment by nikhita** [comment]
+1 from me!

/woof

**Comment by dprotaso** [comment]
haha

**Comment by nader-ziada** [comment]
+1 from me as well 🎉

**Comment by nikhita** [comment]
Looks like @liggitt did a :+1: on the issue body so we now have +1s from sponsors from different employers. :) 

We add members in batches, so this will get processed when the next batch is added.

**Comment by ameukam** [comment]
Hi @dprotaso, thank you for all your contributions so far :)

I've created PR #2316 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada: 
/assign

**Comment by dprotaso** [comment]
Wooo thanks everyone!
