### ISSUE TITLE
REQUEST: New membership for ilya-zuyev

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/org#2295]
### GitHub Username
@ilya-zuyev

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@medyagh 
@sharifelgamal
@blueelvis 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/minikube/pull/9365
https://github.com/kubernetes/minikube/pull/9300

- Issues responded to
https://github.com/kubernetes/minikube/issues/9463
https://github.com/kubernetes/minikube/issues/9495
https://github.com/kubernetes/minikube/issues/9116
https://github.com/kubernetes/minikube/issues/9227

- SIG projects I am involved with
sig-cluster-lifecycle/minikube

**Comment by sharifelgamal** [comment]
I'll sponsor @ilya-zuyev

**Comment by blueelvis** [comment]
I will also sponsor @ilya-zuyev

**Comment by palnabarun** [comment]
@ilya-zuyev, thank you for all your contributions so far :)

I've created PR #2310 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
