### ISSUE TITLE
New repo sigs.k8s.io/cluster-api-provider-kubemark

### ISSUE THREAD

**Issue by benmoss** [kubernetes/org#2296]
### New Repo, Staging Repo, or migrate existing
migrate existing
https://github.com/benmoss/cluster-api-provider-kubemark/

### Requested name for new repository
cluster-api-provider-kubemark

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
- @benmoss
- @elmiko 
- https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES

### If not a staging repo, who should have write access
- @benmoss
- @elmiko 

### If not a staging repo, who should be listed as approvers in OWNERS
- @benmoss
- @elmiko 
- https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES

### If not a staging repo, who should be listed in SECURITY_CONTACTS
- @benmoss
- @elmiko 
- https://github.com/kubernetes-sigs/cluster-api/blob/master/SECURITY_CONTACTS

### What should the repo description be
Cluster API Provider Kubemark

### What SIG and subproject does this fall under in sigs.yaml
sig-cluster-lifecycle

### Approvals
This thread from sig-cluster-lifecycle: https://groups.google.com/u/1/g/kubernetes-sig-cluster-lifecycle/c/n9j1bOLVIw4

**Comment by benmoss** [comment]
cc @neolit123

**Comment by elmiko** [comment]
thanks for posting this Ben!

**Comment by neolit123** [comment]
+1, thanks for logging the issue.

**Comment by nikhita** [comment]
@benmoss this looks almost good to go! Can you also add LICENSE and other template files as per https://github.com/kubernetes/kubernetes-template-project?

**Comment by neolit123** [comment]
both PRs merged. :tada:

**Comment by nikhita** [comment]
Teams have been granted access and sigs.yaml has been updated. Closing :)
