### ISSUE TITLE
REQUEST: New membership for huffmanca

### ISSUE THREAD

**Issue by huffmanca** [kubernetes/org#2297]
### GitHub Username
@huffmanca 

### Organization you are requesting membership in
@kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
I'm already a member of kubernetes, and need to be included in the kubernetes-csi organization.

### List of contributions to the Kubernetes project
- PRs reviewed / authored
-- Introduced a new API type in the CSIDriver spec - https://github.com/kubernetes/kubernetes/pull/92001
-- Expanded PVC validation failures - https://github.com/kubernetes/kubernetes/pull/89300
-- Included e2e test for the FSGroupPolicy - https://github.com/kubernetes/kubernetes/pull/95572
-- Tested - https://github.com/kubernetes-csi/external-snapshotter/pull/360
- Issues responded to
-- https://github.com/kubernetes/enhancements/issues/1682
- SIG projects I am involved with
-- sig-storage

**Comment by palnabarun** [comment]
Hi @huffmanca 👋🏽, I have raised PR #2310 to add you to @kubernetes-csi. Once that merges, you should get a membership invite notification.

/assign
