### ISSUE TITLE
REQUEST: New membership for n3wscott

### ISSUE THREAD

**Issue by n3wscott** [kubernetes/org#2299]
### GitHub Username
@n3wscott

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @pmorie 

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/zeitgeist/pull/14
- 44 PRs: https://github.com/kubernetes-sigs/service-catalog/pulls?q=is%3Apr+author%3An3wscott+is%3Aclosed
- https://github.com/kubernetes/gengo/pull/178
 - I am involved in https://github.com/kubernetes-sigs/zeitgeist

**Comment by justaugustus** [comment]
+1!
Scott recently [donated](https://github.com/kubernetes-sigs/zeitgeist/pull/14) buoy (https://github.com/n3wscott/buoy) to zeitgeist (https://github.com/kubernetes-sigs/zeitgeist) and we'll be adding his as a maintainer to help [integrate the two tools](https://github.com/kubernetes-sigs/zeitgeist/issues/15)!

/pony party

**Comment by justaugustus** [comment]
FYI @kubernetes/release-engineering for sponsorship.

**Comment by justaugustus** [comment]
Opened https://github.com/kubernetes/org/pull/2300 for org and team membership.
