### ISSUE TITLE
NodeResourceTopology API to enable Topology aware scheduling in kubernetes

### ISSUE THREAD

**Issue by swatisehgal** [kubernetes/org#2302]
### New Repo, Staging Repo, or migrate existing
Staging Repo

### Requested name for new repository
noderesourcetopology-api

### Which Organization should it reside
kubernetes

### What should the repo description be
NodeResourceTopology API

### What SIG and subproject does this fall under in sigs.yaml
sig-node and sig-scheduling

### Approvals
Email thread: [here](https://groups.google.com/g/kubernetes-sig-node/c/Fz-JjB-eyvc/m/bDMC0_bMBwAJ)

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
This API is needed to enable Topology aware scheduling in kubernetes. It is needed by the following two proposed components:

1. [**Topology exporter daemon**](https://github.com/kubernetes/enhancements/pull/1870) which is to be implemented as part of Node feature Discovery (NFD)

1. [**Topology aware scheduler plugin**](https://github.com/kubernetes/enhancements/pull/1858) proposed as an in-tree plugin as part of kube-scheduler

**Comment by nikhita** [comment]
> sig-node and sig-scheduling

@swatisehgal Is this intended to be a sig-node subproject or a sig-scheduling one? Depending on the SIG, we'll also need sign off from the respective SIG's leads.

I already see @Huang-Wei's +1 on the email thread, so if it's sig-scheduling, we are good to go! If it's sig-node, we'll need +1s from sig-node leads too.

**Comment by dims** [comment]
@derekwaynecarr @dchen1107 please approve

**Comment by dchen1107** [comment]
Approved!

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes/noderesourcetopology-api :tada: 

Also created two PRs:

- https://github.com/kubernetes/test-infra/pull/19814 - for branch protection rules
- https://github.com/kubernetes/community/pull/5290 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue. :+1:

**Comment by nikhita** [comment]
Branch protection rules have been updated, and repo has been added to sigs.yaml. Closing.
