### ISSUE TITLE
Netlify site request for Secrets Store CSI Driver

### ISSUE THREAD

**Issue by aramase** [kubernetes/org#2303]
### Repository
[kubernetes-sigs/secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver)

### Project domain
secrets-store-csi-driver.sigs.k8s.io

NOTE: Must match domain request.
See subproject site request docs for more information:
http://git.k8s.io/community/github-management/subproject-site-requests.md#subproject-domain-request

### Additional context for request
Any additional information or links to discussions regarding the request.
https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/335
https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/360

cc @ritazh

**Comment by nikhita** [comment]
@aramase Once the netlify site is created, it will try to deploy the master branch. Please get https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/360 merged and I can then create the site so that the deploy works :)

**Comment by nikhita** [comment]
/unassign
/assign @mrbobbytables 

Bob knows Netlify best :)

**Comment by mrbobbytables** [comment]
Netlify has been configured, and the domain is set for.
https://kubernetes-sigs-secrets-store-csi-driver.netlify.app

You will need to open a PR adding the stecrets-store-csi-driver.k8s.io CNAME in the [k8s.io](https://github.com/kubernetes/k8s.io/blob/master/dns/zone-configs/k8s.io._0_base.yaml#L295) repo 👍 

Once that's merged, the site can finish being provisioned and ssl setup :)

**Comment by aramase** [comment]
Thank you @mrbobbytables. Opened PR https://github.com/kubernetes/k8s.io/pull/1398 to add the CNAME.

**Comment by mrbobbytables** [comment]
DNS has been updated, you should be good to go to merge 👍

**Comment by aramase** [comment]
Thank you @mrbobbytables. We'll get the PR in the driver reviewed and merged.

**Comment by nikhita** [comment]
:wave: Are there any more outstanding items here? Can we close this issue?

**Comment by aramase** [comment]
There are no outstanding items. Thank you for helping set this up.

/close
