### ISSUE TITLE
REQUEST: New membership for hi-rustin

### ISSUE THREAD

**Issue by hi-rustin** [kubernetes/org#2305]
### GitHub Username
@hi-rustin

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @fejta 
- @alvaroaleman 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   https://github.com/kubernetes/test-infra/pulls?q=is%3Apr++commenter%3Ahi-rustin+

   [Created 16 prs](https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Ahi-rustin+)

- Issues responded to
   https://github.com/kubernetes/test-infra/issues?q=is%3Aissue++commenter%3Ahi-rustin+
- SIG projects I am involved with
   @k8s-sig-testing
   **prow**

**Comment by alvaroaleman** [comment]
Hey @hi-rustin ,

I am happy to sponsor your membership request once I have seen a bit more of your work.

**Comment by hi-rustin** [comment]
> Hey @hi-rustin ,
> 
> I am happy to sponsor your membership request once I have seen a bit more of your work.

@alvaroaleman @fejta How about now? 😄
I have created 15 PRs for test-infra, and 12 PRs have been merged.

**Comment by fejta** [comment]
+1

**Comment by alvaroaleman** [comment]
+1

**Comment by hi-rustin** [comment]
/assign @savitharaghunathan

Could you please add me to the @kubernetes organization?

Thanks!

**Comment by palnabarun** [comment]
@hi-rustin, thank you for all your contributions so far :)

I've created PR #2347 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
