### ISSUE TITLE
REQUEST: New membership for ydcool

### ISSUE THREAD

**Issue by ydcool** [kubernetes/org#2306]
### GitHub Username
@ydcool

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timyinshi 
- @tengqm 
- @tanjunchen 

### List of contributions to the Kubernetes project
- PRs reviewed / authored 
  - in kubernetes/website
    * https://github.com/kubernetes/website/pulls?q=is%3Apr+commenter%3Aydcool&utf8=%E2%9C%93
    * https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Aydcool&utf8=%E2%9C%93
  - in other cncf projects
    * [update dependencies management instruction in CONTRIBUTING.md](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/pull/70)
    * [add mips64le to released ARCH ](https://github.com/coredns/coredns/pull/3589)
    * [Bump version to 1.6.7](https://github.com/coredns/coredns/pull/3594)
    * [fix broken link ](https://github.com/kubernetes/enhancements/pull/1459)
    * [update zh translation](https://github.com/kubernetes/minikube/pull/6176)
    * [Blog post links (hugo issue)](https://github.com/kubernetes/website/pull/18307)
    * [use emoji flag in zh translation links](https://github.com/openebs/openebs/pull/2847)
    * [add chinese translation ](https://github.com/openebs/openebs/pull/2845)
    * [fix broken link](https://github.com/kubernetes/ingress-gce/pull/977)

- Issues responded to
  - in kubernetes/website
    * https://github.com/kubernetes/website/issues?utf8=%E2%9C%93&q=is%3Aissue+assignee%3Aydcool
    * https://github.com/kubernetes/website/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Aydcool
  - in other cncf projects
    * [error logs 'ERROR: logging before flag.Parse: ' when make extract](https://github.com/kubernetes/minikube/issues/6170)
    * [Suggestion: use go module instead of dep ](https://github.com/kubernetes-sigs/service-catalog/issues/2756)

- SIG projects I am involved with
  * sig-docs

**Comment by timyinshi** [comment]
ok,@ydcool  is a k8S open source enthusiast,he is providing his own experience and capabilities to the K8S community

**Comment by tengqm** [comment]
+1 

Looking forward to more contributions from you!

**Comment by tanjunchen** [comment]
+1
@ydcool 
Thanks for your contributions for k8s.

**Comment by palnabarun** [comment]
@ydcool, thank you for all your contributions so far :)

I've created PR #2310 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
