### ISSUE TITLE
REQUEST: New membership for @swatisehgal

### ISSUE THREAD

**Issue by swatisehgal** [kubernetes/org#2307]
### GitHub Username
@swatisehgal

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @huang-wei
- @dchen1107

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * kubernetes/enhancements#1870
  * kubernetes/enhancements#1858
  * kubernetes/enhancements#1884
  * kubernetes/kubernetes#90708
  * kubernetes/kubernetes#93243

- SIG projects I am involved with
  * sig-node
  * sig-scheduling

**Comment by nikhita** [comment]
+1 from me :)

**Comment by dims** [comment]
Sad that you didn't ask me and @nikhita !! +1 from me as well :)

**Comment by Huang-Wei** [comment]
+1

**Comment by palnabarun** [comment]
@swatisehgal, thank you for all your contributions so far :)

I've created PR #2310 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
