### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for xiangpengzhao

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/org#231]
### GitHub Username
@xiangpengzhao 

### Organization you are requesting membership in
@kubernetes-sigs

I'm already a member of @kubernetes and helping organize [NCW of Kubecon Shanghai](https://github.com/kubernetes-sigs/contributor-playground/tree/master/shanghai)

/assign @cblecker 
/cc @jberkus @idealhack

/area github-membership

**Comment by idealhack** [comment]
+1

**Comment by riverzhang** [comment]
+1

**Comment by puja108** [comment]
Can I +1 this? Also organizing the NCW

**Comment by xiangpengzhao** [comment]
also
/assign @mrbobbytables 
Hopefully one of you and Christoph can process this request before Kubecon Shanghai :) Thanks!

**Comment by mrbobbytables** [comment]
Thanks for everything @xiangpengzhao :) I've created PR #234 to add you to k-sigs, once that gets merged, you should get a membership invite. 🎉

**Comment by xiangpengzhao** [comment]
Thanks Bob! Invitation received :)
