### ISSUE TITLE
REQUEST: New membership for JornShen

### ISSUE THREAD

**Issue by JornShen** [kubernetes/org#2313]
### GitHub Username
@JornShen

### Organization you are requesting membership in

@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Lion-Wei 
- @msau42 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  * https://github.com/kubernetes/kubernetes/pull/95892
  * https://github.com/kubernetes/kubernetes/pull/95866
  * https://github.com/kubernetes/kubernetes/pull/95065
  * https://github.com/kubernetes/kubernetes/pull/94822
  * https://github.com/kubernetes/kubernetes/pull/94676 
  * https://github.com/kubernetes/kubernetes/pull/94386
  * https://github.com/kubernetes/website/pull/24585
  * https://github.com/kubernetes/website/pull/24519
  * https://github.com/kubernetes/website/pull/24125

  review:
    * https://github.com/kubernetes/kubernetes/pull/94599
    * https://github.com/kubernetes/kubernetes/pull/94674
    * https://github.com/kubernetes/kubernetes/pull/94643
    * https://github.com/kubernetes/kubernetes/pull/93445
    * https://github.com/kubernetes/website/pull/24245
    * https://github.com/kubernetes/kubernetes/pull/94736

- Issues responded to

   * https://github.com/kubernetes/kubernetes/issues?q=involves%3Ajornshen+is%3Aissue+is%3Aopen
   * https://github.com/kubernetes/website/issues?q=involves%3Ajornshen+is%3Aissue+is%3Aopen+

- SIG projects I am involved with

   * sig-docs
   * sig-storage
   * sig-networking
   * sig-Instrumentation

**Comment by Lion-Wei** [comment]
I'll sponsor @JornShen

**Comment by msau42** [comment]
+1 @JornShen has been helping sig-storage with implementing metrics

**Comment by JornShen** [comment]
Thanks！ @Lion-Wei @msau42  
I will keep trying my best to help community more better. :)

**Comment by ameukam** [comment]
Hi @JornShen, thank you for all your contributions so far :)

I've created PR #2316 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada: 
/assign

**Comment by JornShen** [comment]
> Hi @JornShen, thank you for all your contributions so far :)
> 
> I've created PR #2316 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉
> /assign

@ameukam thanks for adding !
