### ISSUE TITLE
REQUEST: New membership for tam7t

### ISSUE THREAD

**Issue by tam7t** [kubernetes/org#2317]
### GitHub Username
@tam7t

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@aramase 
@ritazh 
@jimangel

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/266
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/267
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/280
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/340
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/371
- Issues responded to
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/243
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/256
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver

**Comment by aramase** [comment]
+1 for @tam7t's membership

Tommy has been actively contributing to the Secrets Store CSI Driver project

**Comment by ritazh** [comment]
+1 🎉 

Thank you for your contribution on the sig-auth subproject: https://github.com/kubernetes-sigs/secrets-store-csi-driver

**Comment by savitharaghunathan** [comment]
Hi, @tam7t 👋. Thanks for all your contributions 🎉 

According to the [sponsor requirements](https://github.com/kubernetes/community/blob/master/github-management/new-membership-procedure.md#sponsor-requirements), it requires the sponsors to be from different companies. Can you add another sponsor from another company to maintain integration across the community? @ritazh & @aramase's GH profile has listed Microsoft as their employer. Thanks!

**Comment by tam7t** [comment]
Ah apologies I misread and thought that separate company was sufficient. Added @jimangel from Google

**Comment by jimangel** [comment]
+1 🎉 
Look forward to seeing more work on the secrets CSI driver!
Thanks @savitharaghunathan!

**Comment by savitharaghunathan** [comment]
Hi, @tam7t 👋 

I've created PR #2320 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
