### ISSUE TITLE
REQUEST: New membership for Cweiping

### ISSUE THREAD

**Issue by Cweiping** [kubernetes/org#2318]
### GitHub Username
@Cweiping

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@tengqm 
@sftim 
@zhouya0 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/21447
https://github.com/kubernetes/website/pull/21536
https://github.com/kubernetes/website/pull/21537
https://github.com/kubernetes/website/pull/21707
https://github.com/kubernetes/website/pull/21811
https://github.com/kubernetes/website/pull/21950
https://github.com/kubernetes/website/pull/22642
https://github.com/kubernetes/website/pull/22725
https://github.com/kubernetes/website/pull/23100
https://github.com/kubernetes/website/pull/23699

- Issues responded to
https://github.com/kubernetes/website/issues/22777
https://github.com/kubernetes/website/issues/22173

- SIG projects I am involved with
`sig/doc`

**Comment by tengqm** [comment]
+1.
Looking forward to see more contributions from you.

**Comment by zhouya0** [comment]
+1
/lgtm
Thanks for you contributions!

**Comment by savitharaghunathan** [comment]
Hi, @Cweiping 👋 Thank you for all your contributions :)

I've created PR #2320 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by Cweiping** [comment]
Thank you for your sponsorship. @tengqm @zhouya0 
Looking forward to growing with @kubernetes community. 
By the way, the title date of PR is wrong. @savitharaghunathan
