### ISSUE TITLE
REQUEST: New membership for pasqualet

### ISSUE THREAD

**Issue by pasqualet** [kubernetes/org#2319]
### GitHub Username
@pasqualet

### Organization you are requesting membership in
@kubernetes @kubernetes-sigs
### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@Miouge1 
@floryut

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pull/6830
https://github.com/kubernetes-sigs/kubespray/pull/6694
https://github.com/kubernetes-sigs/kubespray/pull/6329
https://github.com/kubernetes-sigs/kubespray/pull/6256
https://github.com/kubernetes-sigs/kubespray/pull/6006
https://github.com/kubernetes-sigs/kubespray/pull/5933
https://github.com/kubernetes-sigs/kubespray/pull/5920
https://github.com/kubernetes-sigs/kubespray/pull/5497
https://github.com/kubernetes-sigs/kubespray/pull/3839

- Issues responded to
https://github.com/kubernetes-sigs/kubespray/issues/6015

- SIG projects I am involved with
https://github.com/kubernetes-sigs/kubespray

**Comment by floryut** [comment]
👍 lots of good contributions from @pasqualet

**Comment by Miouge1** [comment]
Happy to sponsor @pasqualet he has been helpful on the Kubespray project


I haven't sponsored anyone for the @kubernetes org before, so I'm not sure if am an eligible sponsor for that org

**Comment by savitharaghunathan** [comment]
@pasqualet 👋  Thanks for all your contributions 🎉 . To be added to Kubernetes org, you need one more sponsor who is a reviewer or approver in at least 1 OWNERS file in any repo in the Kubernetes org (floryut qualifies to sponsor only for Kubernetes-sigs org)

**Comment by electrocucaracha** [comment]
I'm not sure if my vote counts here but I give a +1 to this. @pasqualet has been helpful on this project.

**Comment by pasqualet** [comment]
@savitharaghunathan thanks for you help! As far I can see @electrocucaracha can sponsor me for Kubernetes org. If not, I'm going to apply just to Kubernetes-Sigs.

**Comment by savitharaghunathan** [comment]
Hi, @pasqualet 👋 Thanks for all your contributions.

I've created PR #2326 to add you to the @kubernetes & @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
