### ISSUE TITLE
REQUEST: New membership for @electrocucaracha

### ISSUE THREAD

**Issue by electrocucaracha** [kubernetes/org#2321]
### GitHub Username
@electrocucaracha 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @floryut
- @mattymo
- @EppO

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pull/4542
https://github.com/kubernetes-sigs/kubespray/pull/4582
https://github.com/kubernetes-sigs/kubespray/pull/4780
https://github.com/kubernetes-sigs/kubespray/pull/5445
https://github.com/kubernetes-sigs/kubespray/pull/5493
https://github.com/kubernetes-sigs/kubespray/pull/5662
https://github.com/kubernetes-sigs/kubespray/pull/6180
https://github.com/kubernetes-sigs/kubespray/pull/6830
https://github.com/kubernetes-sigs/kubespray/pull/6862

- Issues responded to
https://github.com/kubernetes-sigs/kubespray/issues/4737
https://github.com/kubernetes-sigs/kubespray/issues/5472
https://github.com/kubernetes-sigs/kubespray/issues/6065
https://github.com/kubernetes-sigs/kubespray/issues/6742

- SIG projects I am involved with
[Kubespray](https://github.com/kubernetes-sigs/kubespray)

**Comment by mattymo** [comment]
I agree to sponsor @electrocucaracha

**Comment by EppO** [comment]
+1 
welcome on board!

**Comment by savitharaghunathan** [comment]
Hi, @electrocucaracha 👋.

I've created PR #2326 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by floryut** [comment]
Too late but :+1: 😄
