### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for puja108

### ISSUE THREAD

**Issue by puja108** [kubernetes/org#233]
### GitHub Username

@puja108

### Organization you are requesting membership in

@kubernetes-sigs

I'm helping organize [NCW at KubeCon Shanghai](https://github.com/kubernetes-sigs/contributor-playground/tree/master/shanghai)

/assign @cblecker
/cc @jberkus @idealhack

/area github-membership

**Comment by idealhack** [comment]
+1

I'd happily be one of the sponsors.

**Comment by xiangpengzhao** [comment]
also
/assign @mrbobbytables

**Comment by mrbobbytables** [comment]
Thanks @puja108 ! I've created PR #234 to add you to the kubernetes-sigs org. Once that gets merged, you should get an invite :)
