### ISSUE TITLE
REQUEST: New membership for vteratipally

### ISSUE THREAD

**Issue by vteratipally** [kubernetes/org#2331]
### GitHub Username
@vteratipally

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Random-Liu 
- @bsdnet

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/node-problem-detector/pull/488
  https://github.com/kubernetes/node-problem-detector/pull/472
  https://github.com/kubernetes/node-problem-detector/pull/453
  https://github.com/kubernetes/node-problem-detector/pull/452
  https://github.com/containerd/cri/pull/1575

- Issues responded to
  https://github.com/kubernetes/node-problem-detector/issues/471

- SIG projects I am involved with
  [SIG Node](https://github.com/kubernetes/community/blob/master/sig-node/README.md)

**Comment by Random-Liu** [comment]
+1 vteratipally is actively contributing to NPD for several months.

**Comment by bsdnet** [comment]
+1 vteratipally is actively contributing to NPD and COS related issues for a while

**Comment by dchen1107** [comment]
+1 We also introduced vteratipally@ at SIG Node two weeks ago as one of the new owners for NPD.

**Comment by palnabarun** [comment]
Hi @vteratipally 👋🏽, Thank you for your contributions to Node Problem Detector.

One requirement for sponsoring new members is that the sponsors need to be from companies. However, all of your sponsors (@Random-Liu, @bsdnet, @dchen1107) are from the same company. Please let me know if it is otherwise.

Can you please add another sponsor from a different company? :)

**Comment by vteratipally** [comment]
Hi @palnabarun,

Thanks for the help! If someone you know that's not from Google would like to sponsor me, that'd be great! :)

**Comment by vteratipally** [comment]
Adding @xueweiz as the sponsor

Spoke to @xueweiz, he is one of the contributors to NPD.

**Comment by xueweiz** [comment]
Hi @palnabarun , I'm happy to be the external sponsor for @vteratipally  (I currently work at [observe](https://www.observeinc.com/)). I'm one of the owner of NPD as well, and can confirm Varsha has been working on NPD a lot these days, and delivering a lot of value. :)

**Comment by vteratipally** [comment]
@palnabarun , gentle reminder

**Comment by savitharaghunathan** [comment]
Hi, @vteratipally 👋  Thanks for all your contributions to the Kubernetes project :)

I've created PR #2393 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
