### ISSUE TITLE
REQUEST: New membership for @raghvenders

### ISSUE THREAD

**Issue by raghvenders** [kubernetes/org#2333]
### GitHub Username
@raghvenders

### Organization you are requesting membership in
kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sftim 
- @jimangel 

### List of contributions to the Kubernetes project
- PRs - https://github.com/pulls?q=is%3Apr+author%3Araghvenders+archived%3Afalse+is%3Aclosed

- Issues - https://github.com/issues?q=is%3Aissue+author%3Araghvenders+archived%3Afalse+is%3Aclosed
- Responsed to certain issues in slack channel as well - #sig-docs

- Kubernetes Website

**Comment by sftim** [comment]
Hi @raghvenders 

You should speak to your other sponsor too and check they're happy to sponsor you.
Also, to help reviewers, I recommend expanding the list of contributions above so that it's right there in the PR description.

**Comment by raghvenders** [comment]
@sftim , thanks Tim.
I am on my way to the 2nd sponsor.



> Hi @raghvenders
> 
> You should speak to your other sponsor too and check they're happy to sponsor you.
> Also, to help reviewers, I recommend expanding the list of contributions above so that it's right there in the PR description.

Sorry @sftim  , i am not clear on the expanding list contributions part.I have created an issue though not a PR.

**Comment by spiffxp** [comment]
Awaiting response from sponsor

**Comment by raghvenders** [comment]
@spiffxp - Thanks for the reminder.Me too.

I will remind jimangel about this.

@jimangel  - can you please be one add with Tim @sftim .

I would appreciate this.

**Comment by annajung** [comment]
+1 from me @raghvenders was always trying to help review PRs for 1.20 release

**Comment by savitharaghunathan** [comment]
@sftim: Can you add a +1 or thumbs up if you are sponsoring @raghvenders for k8s org membership? Sorry the comment here is not clear - https://github.com/kubernetes/org/issues/2333#issuecomment-730620008

**Comment by jimangel** [comment]
+1 from me as well. Sorry for the delayed 🎉

**Comment by raghvenders** [comment]
Thanks @sftim @jimangel @annajung .

**Comment by mrbobbytables** [comment]
@raghvenders reviewer and approvers take quite a bit of time and review specific areas. The general guideline is 3 months of consistent reviewing in one area to go for reviewers in that area.

**Comment by raghvenders** [comment]
@mrbobbytables sure bob understood.

**Comment by savitharaghunathan** [comment]
Hi, @raghvenders  👋  Thanks for all your contributions to the Kubernetes ecosystem :)

I've created PR #2384 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
