### ISSUE TITLE
REQUEST: New membership for lianghao208

### ISSUE THREAD

**Issue by lianghao208** [kubernetes/org#2335]
### GitHub Username
lianghao208

### Organization you are requesting membership in
kubernetes-sigs
kubernetes
### Requirements
- [x]  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x]  I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x]  I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x]  I am actively contributing to 1 or more Kubernetes subprojects
- [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

I am working on scheduler-plugins (podstate plugin， [kubernetes-sigs/scheduler-plugins#103](https://github.com/kubernetes-sigs/scheduler-plugins/pull/103) ), I would like to be a member to help me send PRs more conveniently.
### Sponsors
 @Huang-Wei 
 @denkensk 
### List of contributions to the Kubernetes project
kubernetes/kubernetes
 [#96777](https://github.com/kubernetes/kubernetes/pull/96777)
kubernetes-sigs/scheduler-plugins
 [#103](https://github.com/kubernetes-sigs/scheduler-plugins/pull/103)
 [#79](https://github.com/kubernetes-sigs/scheduler-plugins/pull/79)
 [#92](https://github.com/kubernetes-sigs/scheduler-plugins/pull/92)

**Comment by Huang-Wei** [comment]
@lianghao208 Could you list other contributions (reviewed PRs are also counted) according to the template? in both k/k and k-sigs/scheduler-plugins.

**Comment by lianghao208** [comment]
> @lianghao208 Could you list other contributions (reviewed PRs are also counted) according to the template? in both k/k and k-sigs/scheduler-plugins.

By far, I submit 3 merged PRs for k-sigs/scheduler-plugins and listed on comment. Is that a minimum contributions quantity requirement for being a k-sigs member?

**Comment by Huang-Wei** [comment]
I'm not 100% sure there is a fixed number, but listing all your contributions can always help sponsors make the decision easier :)

**Comment by Huang-Wei** [comment]
+1

Looking forward to seeing more contributions!

(BTW: you need another sponsor)

**Comment by lianghao208** [comment]
@Huang-Wei thanks!

**Comment by lianghao208** [comment]
@denkensk 
Would you like to be my sponsor? Thanks!!

**Comment by denkensk** [comment]
+1 
Looking forward to more contributions

**Comment by lianghao208** [comment]
#2337

**Comment by palnabarun** [comment]
@lianghao208, thank you for all your contributions so far :)

Since both #2347 and #2337 merged, you should get membership invite notifications to both the organizations you requested for.

Welcome to @kubernetes and @kubernetes-sigs! :tada:

/assign

**Comment by palnabarun** [comment]
Oops! I think I was a bit early to say that #2337 merged. It is being retested, although it is highly likely to go through. :)
