### ISSUE TITLE
REQUEST: New membership for kosehy

### ISSUE THREAD

**Issue by kosehy** [kubernetes/org#2338]
### GitHub Username
@kosehy

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @seokho-son 
- @gochist 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=org%3Akubernetes+is%3Apr+author%3Akosehy
- Issues responded to
https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Akosehy
- SIG projects I am involved with
kubernetes/sig-docs

**Comment by seokho-son** [comment]
+1, @kosehy is a contributor for Korean localization for k/website. I'm happy to work with @kosehy !

**Comment by pjhwa** [comment]
+1
@kosehy is a active contributor for Korean localization. 
Thank you for your hard work for localization, @kosehy !

**Comment by gochist** [comment]
+1, @kosehy is one of the most active contributor recently!

**Comment by savitharaghunathan** [comment]
Hi, @kosehy 👋  Thanks for your contributions to the k/website localization project :) 

I've created PR #2343 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
