### ISSUE TITLE
REQUEST: New membership for wangshiqi308

### ISSUE THREAD

**Issue by wangshiqi308** [kubernetes/org#2339]
### GitHub Username
@wangshiqi308

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@RainbowMango 
@Jeffwan

### List of contributions to the Kubernetes project
- PRs reviewed / authored
kubernetes/autoscaler#3707
kubernetes/autoscaler#3685
kubernetes/autoscaler#3676
kubernetes/autoscaler#3671

- Issues responded to
- SIG projects I am involved with

**Comment by RainbowMango** [comment]
+1 
Thanks @wangshiqi308 for your contribution to autoscaler. :)

**Comment by Jeffwan** [comment]
+1 
Thanks for the contribution. I would like to sponsor the membership @wangshiqi308

**Comment by savitharaghunathan** [comment]
Hi, @wangshiqi308 👋  Thanks for your contributions to the Autoscalar project :) 

I've created PR #2343 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
