### ISSUE TITLE
REQUEST: New membership for ruiwen-zhao

### ISSUE THREAD

**Issue by ruiwen-zhao** [kubernetes/org#2340]
### GitHub Username
@ruiwen-zhao

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dashpole 
- @hasheddan 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/96695
https://github.com/kubernetes/kubernetes/pull/95810
https://github.com/kubernetes/kubernetes/pull/96276
https://github.com/kubernetes/website/pull/24936
https://github.com/kubernetes/kubernetes/pull/96123
https://github.com/kubernetes/kubernetes/pull/96054
https://github.com/kubernetes/kubernetes/pull/95661
https://github.com/kubernetes/kubernetes/pull/96156

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/96519
https://github.com/kubernetes/kubernetes/issues/96044
https://github.com/kubernetes/kubernetes/issues/96641

- SIG projects I am involved with
sig-node

**Comment by dashpole** [comment]
I support membership for @ruiwen-zhao

**Comment by hasheddan** [comment]
I support membership for @ruiwen-zhao :+1:

**Comment by savitharaghunathan** [comment]
Hi, @ruiwen-zhao 👋 Thanks for your contributions to Kubernetes :) 

I've created PR #2343 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
