### ISSUE TITLE
REQUEST: New membership for cmurphy (kubernetes-sigs)

### ISSUE THREAD

**Issue by cmurphy** [kubernetes/org#2341]
### GitHub Username
@cmurphy

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @saschagrunert 
- @hasheddan 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - https://github.com/kubernetes-sigs/security-profiles-operator/pulls?q=is%3Amerged+is%3Apr+author%3Acmurphy+
- Issues responded to
    - https://github.com/kubernetes-sigs/security-profiles-operator/issues/150
    - https://github.com/kubernetes-sigs/security-profiles-operator/issues/135
    - https://github.com/kubernetes-sigs/security-profiles-operator/issues/131
    - https://github.com/kubernetes-sigs/security-profiles-operator/issues/117
    - https://github.com/kubernetes-sigs/security-profiles-operator/issues/106
- SIG projects I am involved with
    - https://github.com/kubernetes-sigs/security-profiles-operator

**Comment by hasheddan** [comment]
I support adding @cmurphy as a @kubernetes-sigs member!

**Comment by saschagrunert** [comment]
Yep yep, huge +1 from my side, too! 😊

**Comment by saschagrunert** [comment]
/assign @nikhita  
for a final approval :innocent:

**Comment by savitharaghunathan** [comment]
Hi, @cmurphy 👋  Thanks for your contributions to the security profiles operator project :) 

I've created PR #2343 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by cmurphy** [comment]
Thank you!
