### ISSUE TITLE
REQUEST: New membership for SyamSundarKirubakaran

### ISSUE THREAD

**Issue by SyamSundarKirubakaran** [kubernetes/org#2345]
### GitHub Username
@SyamSundarKirubakaran

### Organization you are requesting membership in
@kubernetes, @kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pwittrock
- @soltysh

### List of contributions to the Kubernetes project
- Worked with SIG CLI as a part of ***Google Season of Docs*** and built: https://kubectl.docs.kubernetes.io/ which is now the official documentation for kubectl and kustomize.

**Comment by soltysh** [comment]
:+1:

**Comment by palnabarun** [comment]
@SyamSundarKirubakaran, thank you for all your contributions to the awesome `kubectl` documentation :)

I've created PR #2347 to add you to the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! :tada:

/assign
