### ISSUE TITLE
REQUEST: New membership for yagonobre

### ISSUE THREAD

**Issue by yagonobre** [kubernetes/org#235]
### GitHub Username
@yagonobre

### Organization you are requesting membership in
kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@neolit123 
@timothysc 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls/yagonobre
- SIG projects I am involved with
Kubeadm

/area github-membership

**Comment by timothysc** [comment]
+1 from me

/assign @cblecker

**Comment by neolit123** [comment]
+1

**Comment by mrbobbytables** [comment]
@yagonobre, thank you for all your contributions so far :)

I've created PR #234  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
