### ISSUE TITLE
Migrate https://github.com/liggitt/kubectl-check-ownerreferences to kubernetes-sigs

### ISSUE THREAD

**Issue by liggitt** [kubernetes/org#2350]
### New Repo, Staging Repo, or migrate existing
migrate https://github.com/liggitt/kubectl-check-ownerreferences/ to kubernetes-sigs

### Requested name for new repository
kubectl-check-ownerreferences

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
deads2k, liggitt, caesarxuchao

### If not a staging repo, who should have write access
deads2k, liggitt, caesarxuchao

### If not a staging repo, who should be listed as approvers in OWNERS
deads2k, liggitt, caesarxuchao

### If not a staging repo, who should be listed in SECURITY_CONTACTS
deads2k, liggitt, caesarxuchao

### What should the repo description be
Read-only tool to check metadata.ownerReferences

### What SIG and subproject does this fall under in sigs.yaml
This is part of the control-plane-features subproject of sig-apimachinery (https://github.com/kubernetes/community/tree/master/sig-api-machinery#control-plane-features)

### Approvals

Proposed and approved by sig-apimachinery TLs @deads2k and @lavalamp 

### Additional context for request

Related to tooling to diagnose issues like http://issue.k8s.io/65200 and http://issue.k8s.io/92743

**Comment by liggitt** [comment]
/assign @deads2k @lavalamp 
for ack

**Comment by nikhita** [comment]
/assign

@liggitt can you move the repo to https://github.com/kubernetes-purgatory? :) I can then transfer the repo to k-sigs.

Also, can you also add the [boilerplate header](https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.sh.txt) to the bash scripts when you get a chance? After the transfer is also fine.

**Comment by liggitt** [comment]
> @liggitt can you move the repo to https://github.com/kubernetes-purgatory? :) I can then transfer the repo to k-sigs.
> 
> Also, can you also add the [boilerplate header](https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.sh.txt) to the bash scripts when you get a chance? After the transfer is also fine.

both done 

https://github.com/kubernetes-purgatory/kubectl-check-ownerreferences

**Comment by nikhita** [comment]
Repo has been migrated - https://github.com/kubernetes-sigs/kubectl-check-ownerreferences

Also created:
- https://github.com/kubernetes/org/pull/2351 - to add GitHub team to grant access
- https://github.com/kubernetes/community/pull/5338 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by nikhita** [comment]
Teams have been granted access and sigs.yaml has been updated. Closing.
