### ISSUE TITLE
REQUEST: New membership for jeremyje

### ISSUE THREAD

**Issue by jeremyje** [kubernetes/org#2352]
### GitHub Username
jeremyje

### Organization you are requesting membership in
kubernetes
kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- pjh
- marosset
- mattcary

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/94052
https://github.com/kubernetes/kubernetes/pull/93765
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/586
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/587
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/588
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/590
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/597
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/601

- Issues responded to
https://github.com/kubernetes/node-problem-detector/issues/461 -> https://docs.google.com/document/d/1eiK6KAp_TFR0PgBMu2WCf49fMZcg-HHnBHMc9fALquU/edit
- SIG projects I am involved with
sig-windows
sig-storage
sig-node

**Comment by marosset** [comment]
/lgtm
Thanks for your contributions @jeremyje and I look forward to continue working with you!

**Comment by pjh** [comment]
/lgtm

Thanks for your contributions so far Jeremy!

**Comment by spiffxp** [comment]
Hi @jeremyje, thanks for your contributions to the project!

I created PR https://github.com/kubernetes/org/pull/2366 to add you to the @kubernetes and @kubernetes-sigs organizations.  Once that gets merged, you should receive a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! 🎉 

/meow
