### ISSUE TITLE
REQUEST: New membership for lala123912

### ISSUE THREAD

**Issue by lala123912** [kubernetes/org#2353]
### GitHub Username
@lala123912

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Lion-Wei 
- @sttts

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pull/94992
  https://github.com/kubernetes/kubernetes/pull/95640
  https://github.com/kubernetes/kubernetes/pull/96802
  https://github.com/kubernetes/kubernetes/pull/96373
  https://github.com/kubernetes/kubernetes/pull/96402
  https://github.com/kubernetes/kubernetes/pull/96917
  https://github.com/kubernetes/kubernetes/pull/96359

- Issues responded to
  https://github.com/kubernetes/kubernetes/issues/95552
  https://github.com/kubernetes/kubernetes/issues/96408
  https://github.com/kubernetes/kubernetes/issues/96587
  https://github.com/kubernetes/kubernetes/issues/96916
  https://github.com/kubernetes/kubernetes/issues/96342
  
- SIG projects I am involved with
  sig-api-machinery
  sig-storage

**Comment by sttts** [comment]
+1 for Melisa to become a member.

**Comment by Lion-Wei** [comment]
+1 for Melisa to become a member.

**Comment by savitharaghunathan** [comment]
Hi, @lala123912 👋  Thanks for all your contributions to the Kubernetes ecosystem :)

I've created PR #2361 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by lala123912** [comment]
> Hi, @lala123912 👋 Thanks for all your contributions to the Kubernetes ecosystem :)
> 
> I've created PR #2361 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉
> 
> /assign

Thanks for the invitation.
