### ISSUE TITLE
REQUEST: New membership for kkeshavamurthy

### ISSUE THREAD

**Issue by kkeshavamurthy** [kubernetes/org#2354]
### GitHub Username
@kkeshavamurthy

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Eleanorrigby
- @CecileRobertMichon 
- @codenrhoden 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/image-builder/pulls?q=is%3Apr+author%3Akkeshavamurthy
  - https://github.com/kubernetes/test-infra/pulls/kkeshavamurthy
  - https://github.com/kubernetes-sigs/boskos/pulls?q=+is%3Apr+author%3Akkeshavamurthy+

- Issues responded to
  - https://github.com/kubernetes-sigs/image-builder/issues?q=is%3Aissue+kkeshavamurthy

- SIG projects I am involved with
  - kubernetes-sigs/image-builder
  - kubernetes/test-infra
  - kubernetes-sigs/boskos

**Comment by CecileRobertMichon** [comment]
+1

**Comment by EleanorRigby** [comment]
I +1 the nomination for Kiran. 
@kkeshavamurthy has done good work to improve CI for OVA image building. He continues to contribute more, review, and help push PRs for merge.

**Comment by savitharaghunathan** [comment]
Hi, @kkeshavamurthy 👋  Thank you for all your contributions to the Kubernetes ecosystem so far :)

In order to be added to the Kubernetes-sigs org, you will need one more sponsor who is either an approver or reviewer in the @kubernetes org projects or @kubernetes-sigs projects (@EleanorRigby is not an approver or reviewer, so their +1 doesn't count)

**Comment by codenrhoden** [comment]
I'd be happy to take on this sponsorship. @kkeshavamurthy please put me down here and I'll give this a resounding +1. You've basically taken over my duties for `image-builder`!

**Comment by kkeshavamurthy** [comment]
Thanks a lot @EleanorRigby @CecileRobertMichon @codenrhoden

**Comment by codenrhoden** [comment]
Just in case I need a separate message about it, this is a +1 for me.

Also makes it clear we need to get @EleanorRigby into a reviewer status, which was a topic in today's office hours. Very prescient.

**Comment by spiffxp** [comment]
Hi @kkeshavamurthy, thanks for your contributions to the project!

I created PR https://github.com/kubernetes/org/pull/2366 to add you to the @kubernetes-sigs organization.  Once that gets merged, you should receive a membership invite notification.

Welcome to @kubernetes-sigs! 🎉 

/meow
