### ISSUE TITLE
REQUEST: New membership for zhaojizhuang

### ISSUE THREAD

**Issue by zhaojizhuang** [kubernetes/org#2355]
### GitHub Username
@zhaojizhuang

### Organization you are requesting membership in
@kubernetes

### Requirements
  - [x]  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
  - [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
  - [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [x] I am actively contributing to 1 or more Kubernetes subprojects
  - [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
  - [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
### Sponsors
@tengqm 
@howieyuen 
#### PRs
https://github.com/kubernetes/website/pull/25314
https://github.com/kubernetes/website/pull/25257
https://github.com/kubernetes/website/pull/25234
https://github.com/kubernetes/website/pull/25167
https://github.com/kubernetes/website/pull/25156 
https://github.com/kubernetes/website/pull/25141
https://github.com/kubernetes/website/pull/25116 
https://github.com/kubernetes/website/pull/25113
https://github.com/kubernetes/website/pull/25112

#### Issues
https://github.com/kubernetes/website/issues/25145
https://github.com/kubernetes/website/issues/25140
https://github.com/kubernetes/website/issues/25114
https://github.com/kubernetes/website/issues/25193

### SIG projects I am involved with

kubernetes/sig-docs

**Comment by tengqm** [comment]
+1
It would be great to have new members joining the zh localization team.

**Comment by howieyuen** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi, @zhaojizhuang 👋 Thanks for all your contributions to k/website :)

I've created PR #2361 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
