### ISSUE TITLE
REQUEST: New membership for helight

### ISSUE THREAD

**Issue by helight** [kubernetes/org#2356]
### GitHub Username
@helight

### Organization you are requesting membership in
@kubernetes

### Requirements
* [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
* [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
* [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
* [x] I am actively contributing to 1 or more Kubernetes subprojects
* [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
* [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zehuaiWANG 
- @hwdef 

### List of contributions to the Kubernetes project
- PRs reviewed / authored 
https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Aclosed++helight
https://github.com/kubernetes/dashboard/pulls?q=is%3Apr+is%3Aclosed++helight
- Issues responded to
- SIG projects I am involved with
kubernetes/sig-docs

**Comment by hwdef** [comment]
+1 from me
Thanks for your contribution to Kubernetes!

**Comment by zehuaiWANG** [comment]
+1
Thanks for the contribution, welcome to join us.

**Comment by savitharaghunathan** [comment]
Hi, @helight 👋 Thanks for all the contributions to k/website :)

I've created PR #2361 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
