### ISSUE TITLE
REQUEST: New membership for @MarcusNoble

### ISSUE THREAD

**Issue by MarcusNoble** [kubernetes/org#2358]
### GitHub Username
@MarcusNoble

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @randomvariable 
- @richardcase

### List of contributions to the Kubernetes project
- PRs reviewed / authored - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3AMarcusNoble+
- Issues responded to - https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues?q=is%3Aissue+sort%3Aupdated-desc+author%3AMarcusNoble+
- SIG projects I am involved with - https://github.com/kubernetes-sigs/cluster-api-provider-aws

**Comment by randomvariable** [comment]
+1

**Comment by richardcase** [comment]
Yes please

+1

**Comment by savitharaghunathan** [comment]
Hi, @MarcusNoble 👋 Thanks for your contributions to the Cluster API provider AWS project :)

I've created PR #2361 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
