### ISSUE TITLE
REQUEST: New membership for aoxn

### ISSUE THREAD

**Issue by aoxn** [kubernetes/org#236]
### GitHub Username
@aoxn

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andrewsykim 
- @cheyang 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - Primary Author of [Alibaba CloudProvider of kubernetes org.](https://github.com/kubernetes/cloud-provider-alibaba-cloud/graphs/contributors) 50 commits. 
    - https://github.com/kubernetes/kubernetes/pull/35948 （support customize repository prefix of image through environment）
    - https://github.com/kubernetes/community/pull/2394 （KEP proposals for adding Alibaba Cloud Provider into kubernetes ecosystem）
    - https://github.com/cncf/k8s-conformance/pull/36 （Conformance results for v1.8/AlibabaCloud）
    - https://github.com/kubernetes/kubernetes/pull/60292 （Route controller may trigger cloudprovider api throttle when adding route）
    - https://github.com/cncf/k8s-conformance/pull/165 （Conformance test results for v1.9/alibaba cloud）
    - https://github.com/kubernetes/kubernetes/pull/60607 （kubeadm cannot work with external cloudprovier under selfhosting mode）
    - https://github.com/kubernetes/kubernetes/pull/40334 （Add Alicloud Provider support which include SLB with https ）
        
- Issues responded to
    - https://github.com/kubernetes/kubernetes/issues/66273
- SIG projects I am involved with
    - sig-cloud-provider

/area github-membership

**Comment by andrewsykim** [comment]
+1

**Comment by cheyang** [comment]
+1
Welcome to kubernetes community!

**Comment by mrbobbytables** [comment]
@aoxn, thank you for all the effort you've put in so far for the Kubernetes project :)

I've created PR #241  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification in your email.

Welcome to @kubernetes! 🎉

/assign
