### ISSUE TITLE
New membership for chenrui333

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/org#237]
### GitHub Username
chenrui333

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah
- @chenopis 
- @zhangxiaoyu-zidif 

### List of contributions to the Kubernetes project
- PRs reviewed / authored (https://github.com/kubernetes/website/pull/10976, https://github.com/kubernetes/website/pull/10975)
- Issues responded to
- SIG projects I am involved with

/area github-membership

**Comment by zacharysarah** [comment]
+1, thanks for the valuable discussion in Shanghai!

**Comment by zhangqx2010** [comment]
+1

**Comment by zhangxiaoyu-zidif** [comment]
+1

**Comment by mrbobbytables** [comment]
@chenrui333, thank you for all your work so far with the translation project :)

I've created PR #253   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
