### ISSUE TITLE
Archive csi fibre-channel and flex repos

### ISSUE THREAD

**Issue by msau42** [kubernetes/org#2371]
### Repository to archive
kubernetes-csi/csi-driver-fibre-channel
kubernetes-csi/csi-driver-flex

### Repository and/or sig subproject owners that are approving this archival
msau42

### When should this be done
anytime

### Additional context for request
Any additional information or context to describe the request.
Due to lack of maintainers, we are archiving these two repos. We announced intend to archive almost a year ago:
https://groups.google.com/g/kubernetes-sig-storage/c/2VYX1B5RweQ/m/BD4eDZLLEQAJ

**Comment by nikhita** [comment]
/assign

@msau42 looks like the PR to add the archival note for csi-driver-fibre-channel still needs approval - https://github.com/kubernetes-csi/csi-driver-fibre-channel/pull/7. I'll archive both the repos once the PR is merged. If you need me to manually merge that PR to get the archival done sooner, please let me know!

In the meanwhile, I have created the following PRs to remove prowjobs/docs for both the repos. PTAL :)

- https://github.com/kubernetes/test-infra/pull/20162 - remove prowjobs for csi-driver-flex
- https://github.com/kubernetes/org/pull/2372 - remove GitHub teams for both repos
- https://github.com/kubernetes/community/pull/5354 - remove repos from sigs.yaml

**Comment by nikhita** [comment]
Repos have been archived:
- https://github.com/kubernetes-retired/csi-driver-fibre-channel
- https://github.com/kubernetes-retired/csi-driver-flex

Also sent a notice to k-dev and the sig-storage mailing lists - https://groups.google.com/g/kubernetes-dev/c/ciY1wg7nYF8

We can close this issue once https://github.com/kubernetes/org/pull/2372 merges.
