### ISSUE TITLE
REQUEST: New membership for mrueg

### ISSUE THREAD

**Issue by mrueg** [kubernetes/org#2378]
### GitHub Username
@mrueg

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lilic 
- @tariq1890 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/sig-release/commit/f067023da80dc9706ec1f4e89493a4170cf5ab36
- https://github.com/kubernetes/kubernetes/commit/912794b3026ce7bea1d6619aa260678c370f9985
- https://github.com/kubernetes/kubernetes/commit/f289a3d6a714c1e13019fcc0da3aebefbd3cce2a
- https://github.com/kubernetes/kubernetes/commit/eb6c7169276a1978b851deafb25b507caf696ac4
- https://github.com/kubernetes/k8s.io/commit/c1607c2064c4b7731f713fe302447aec69075307
- https://github.com/kubernetes/kube-state-metrics/commit/8a96896eaf60da3af3347d43936cd55b8e4477c3
- https://github.com/kubernetes/kube-state-metrics/commit/ac158a6467e80a33bd54203ab70cc46368eec71f
- https://github.com/kubernetes/kube-state-metrics/commit/655f89bfe85d35b18f030afc6209b2e118e18fd2
- https://github.com/kubernetes/kube-state-metrics/commit/2ea60aa0cee668a81286dd10026b059890fcc477
- https://github.com/kubernetes/kube-state-metrics/commit/87ce1eeb38c9d787b296560072d623f3975de12b
- https://github.com/kubernetes/kube-state-metrics/commit/15582fef0925350a9c8717ad90e93103ba784e26
- https://github.com/kubernetes/kube-state-metrics/commit/98e0bcbcd366a6e99392db55953355b3f9210d4c
- https://github.com/kubernetes/kube-state-metrics/commit/0be9f6ea7fea04301e507e18af5427b3bcf60e47
- https://github.com/kubernetes/kube-state-metrics/commit/f2cd3e78e2cb526834f44c76458651c352a6cfb5
- https://github.com/kubernetes/kube-state-metrics/commit/c9d367c97fa3c4098f3ecb33f48748d28cfcb2fa
- https://github.com/kubernetes/kube-state-metrics/commit/07b5d0ceb6f451a61f946388a4313bb4d453bb47
- https://github.com/kubernetes/kube-state-metrics/commit/be2ba71bc7ec846ce167b2a1a8746cb7a0404daa
- https://github.com/kubernetes/kube-state-metrics/commit/5e055802ab39ef75114c351065663cbd7c09bb9f
- https://github.com/kubernetes/kube-state-metrics/commit/43f230c0c47f851668cb6942321e8c372a9c156f
- https://github.com/kubernetes/kube-state-metrics/commit/9c487adc16e794c3b3b706ddd5155cecb156da0f
- https://github.com/kubernetes/kube-state-metrics/commit/818bc927c94fce2c0bf5fadefca7f07a271b36db
- https://github.com/kubernetes/kube-state-metrics/commit/602392f528929c9e9ac865f8e8c0dbd88f192cd5
- https://github.com/kubernetes/kube-state-metrics/commit/99bf43405f268a3e3f2a33221fa7c32da677e3f2
- https://github.com/kubernetes/kube-state-metrics/commit/422576c12543f9dadf3426de6cb8b416a8633d74
- https://github.com/kubernetes/kube-state-metrics/commit/4de0c3ed140603df1ee5d63af87692d08e4abf49
- https://github.com/kubernetes/kube-state-metrics/commit/28030271ceb061145098576dd8424fdb8ce3586e
- https://github.com/kubernetes/perf-tests/commit/9c30c99b1e7fa312feb4b843d4917dfac9680a17
- https://github.com/kubernetes/perf-tests/commit/eeb80d4d75c9f4330c10d280abc53b12d61e2ec1
- https://github.com/kubernetes/perf-tests/commit/5a04b5c641f49e93aaf16a59f9d3bad40b0239e7
- https://github.com/kubernetes/perf-tests/commit/ae121aaed7c384169632e05f9da002de14c9b57c
- https://github.com/kubernetes/website/commit/8f5fbc0222f532ab05883606fd159248c041c976
- https://github.com/kubernetes/website/commit/4f0d3d501ea53ae89ad4a63139d3cd568279240e
- https://github.com/kubernetes/website/commit/f3cde84ea79667dd4b8020c61bd344dc88bcc1b8
- https://github.com/kubernetes/website/commit/1d08290c55cff8236b44e01450cfe19afbd7df5f

Active mainly on kube-state-metrics

**Comment by lilic** [comment]
+1 from me, super happy to sponsor @mrueg to be added to the Kubernetes org! Thanks for all the work in kube-state-metrics! 🎉

**Comment by tariq1890** [comment]
+1 from me too, a pleasure to vouch for @mrueg! Thanks for all your contributions Manuel!

**Comment by savitharaghunathan** [comment]
Hi, @mrueg  👋  Thanks for all your contributions to the Kubernetes ecosystem :)

I've created PR #2384 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
