### ISSUE TITLE
REQUEST: New membership for habibrosyad

### ISSUE THREAD

**Issue by habibrosyad** [kubernetes/org#2379]
### GitHub Username
@habibrosyad

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @girikuncoro 
- @irvifa 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - k/website
        - https://github.com/kubernetes/website/pull/23708
        - https://github.com/kubernetes/website/pull/23534
        - https://github.com/kubernetes/website/pull/23987
        - https://github.com/kubernetes/website/pull/24019
        - https://github.com/kubernetes/website/pull/25138
        - [more...](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ahabibrosyad+)
    - k/k
        - https://github.com/kubernetes/kubernetes/pull/94476
        - https://github.com/kubernetes/kubernetes/pull/94387
        - https://github.com/kubernetes/kubernetes/pull/94100
        - https://github.com/kubernetes/kubernetes/pull/93960
        - https://github.com/kubernetes/kubernetes/pull/93871
        - [more...](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Ahabibrosyad+)
    - k/test-infra
        - https://github.com/kubernetes/test-infra/pull/18946
        - https://github.com/kubernetes/test-infra/pull/19027
        - https://github.com/kubernetes/test-infra/pull/19055
        - https://github.com/kubernetes/test-infra/pull/19304
        - https://github.com/kubernetes/test-infra/pull/19435
        - [more...](https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Ahabibrosyad+)
    - https://github.com/kubernetes/autoscaler/pull/3435
- Issues responded to:
    - https://github.com/kubernetes/website/issues/24382
    - https://github.com/kubernetes/website/issues/22296
    - https://github.com/kubernetes/website/issues/23660
    - https://github.com/kubernetes/website/issues/24488
    - https://github.com/kubernetes/website/issues/24334
- SIG projects I am involved with
    SIG Docs

**Comment by irvifa** [comment]
+1

**Comment by girikuncoro** [comment]
+1 from me, glad to have @habibrosyad in kubernetes community!

**Comment by savitharaghunathan** [comment]
Hi, @habibrosyad  👋  Thanks for all your contributions to the Kubernetes ecosystem :)

I've created PR #2384 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by habibrosyad** [comment]
Thanks @irvifa @girikuncoro @savitharaghunathan 👍
