### ISSUE TITLE
REQUEST: New kubernetes membership for zhangqx2010

### ISSUE THREAD

**Issue by zhangqx2010** [kubernetes/org#238]
### GitHub Username
@zhangqx2010

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@zacharysarah
@zhangxiaoyu-zidif 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-retired/kubernetes-docs-zh/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+zhangqx2010
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/38923
- SIG projects I am involved with
kubernetes-sigs/docs

/area github-membership

**Comment by zacharysarah** [comment]
+1, thanks for participating in the Shanghai doc sprint!

**Comment by zhangxiaoyu-zidif** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @zhangqx2010, just for clarification are you looking for membership to @kubernetes or @kubernetes-sigs? The issue title is referencing @kubernetes-sigs, but the request in the issue itself is referencing @kubernetes. If you could fix the discrepancy, it'd be much appreciated :) 

Thanks!

**Comment by zhangqx2010** [comment]
@mrbobbytables My bad. It should be sig-docs. I have modified the content. Is that OK now?

**Comment by mrbobbytables** [comment]
@zhangqx2010 I think you're looking for membership to @kubernetes to help with sig-docs (They are the owners of https://github.com/kubernetes/website repo).

Membership to @kubernetes-sigs  gives you member permissions over the various sub-projects that can be found under http://github.com/kubernetes-sigs.

**Comment by mrbobbytables** [comment]
@zhangqx2010, thank you for all your contributions so far :)

I've created PR #241   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by zhangqx2010** [comment]
Thank you!
