### ISSUE TITLE
REQUEST: New membership for ArangoGutierrez

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes/org#2383]
### GitHub Username
@ArangoGutierrez 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mrbobbytables 
- @marquiz

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- https://github.com/kubernetes/test-infra/pull/19135
- https://github.com/kubernetes/test-infra/pull/19139
- https://github.com/kubernetes/test-infra/pull/19140
- https://github.com/kubernetes/test-infra/pull/19141
- https://github.com/kubernetes/test-infra/pull/19373
- https://github.com/kubernetes/test-infra/pull/19549
- https://github.com/kubernetes/test-infra/pull/20008
- https://github.com/kubernetes/test-infra/pull/20017
- https://github.com/kubernetes/k8s.io/pull/1484

- Issues responded to
- https://github.com/kubernetes/test-infra/issues/20112
- https://github.com/kubernetes/sig-release/discussions/1290#discussioncomment-206594

- SIG projects I am involved with

-   https://github.com/kubernetes-sigs/node-feature-discovery
-   https://github.com/kubernetes-sigs/node-feature-discovery-operator

**Comment by mrbobbytables** [comment]
+1
/pony ya

**Comment by marquiz** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi, @ArangoGutierrez 👋  Thanks for all your contributions to the Kubernetes ecosystem :)

I've created PR #2393 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
