### ISSUE TITLE
REQUEST: New membership for richardcase

### ISSUE THREAD

**Issue by richardcase** [kubernetes/org#2386]
### GitHub Username
@richardcase

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @randomvariable 
- @detiber

### List of contributions to the Kubernetes project
- PRs reviewed / authored
 - [27 PRs in cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3Arichardcase)
- Issues responded to
  - [25 issues created in cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues?q=is%3Aissue+author%3Arichardcase)
- SIG projects I am involved with
  - sig-cluster-lifecycle
     - [Cluster API Provider AWS](https://github.com/kubernetes-sigs/cluster-api-provider-aws) maintainer

**Comment by randomvariable** [comment]
+1

**Comment by detiber** [comment]
+1 from me, `kubernetes` org membership is needed to help with `kubernetes/test-infra` and `kubernetes/k8s.io` related work

**Comment by savitharaghunathan** [comment]
Hi, @richardcase 👋  Thanks for all your contributions to the cluster-api-provider-aws :)

I've created PR #2393 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
