### ISSUE TITLE
REQUEST: New membership for timoreimann (kubernetes-sigs)

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/org#2388]
### GitHub Username
@timoreimann

### Organization you are requesting membership in
@kubernetes-sigs

_I am already a member of the `kubernetes` organization._

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xmudrii 

### List of contributions to the kubernetes-sigs project
- PRs authored: [9](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pulls?q=is%3Apr+is%3Amerged+author%3Atimoreimann)
- PRs reviewed: [4](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pulls?q=is%3Apr+reviewed-by%3Atimoreimann)
- SIG projects I am involved with: Cluster API / Cluster API DigitalOcean (CAPDO)

**Comment by xmudrii** [comment]
+1 :100:

**Comment by savitharaghunathan** [comment]
Hi, @timoreimann 👋 Thanks for all your contributions :)

I've created PR #2393 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
