### ISSUE TITLE
grant admin access to kmova for NFS provisioner projects under kubernetes-sigs

### ISSUE THREAD

**Issue by kmova** [kubernetes/org#2389]
### Organization or repository
kubernetes-sigs/nfs-subdir-external-provisioner
kubernetes-sigs/nfs-ganesha-server-and-external-provisioner

### Users affected
@kmova

### Describe the issue
Grant admin access for the repository to help with making releases on the above-mentioned repositories. I need this to proceed with creating release branches and tags from the migrated repositories.  

### Approvals
Need sig-storage approval from @msau42,  @saad-ali, and @xing-yang 

/area github-repo
/sig storage

**Comment by msau42** [comment]
+1 @kmova is going to be the primary maintainer for these two repos and will need admin access
