### ISSUE TITLE
Request Memership Request at KubeCon

### ISSUE THREAD

**Issue by YouthLab** [kubernetes/org#239]
### GitHub Username
@YouthLab

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ ] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- chenopis
- zacharysarah
- bradtopol

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

/area github-membership

**Comment by zacharysarah** [comment]
+1, nice to meet you in person!

**Comment by justaugustus** [comment]
@YouthLab -- Before we can invite you to the org, we'll need another sponsor.

@chenopis / @bradtopol -- you were both listed as potential sponsors. Would you care to +1 this?

**Comment by markthink** [comment]
+1
