### ISSUE TITLE
REQUEST: New membership for 249043822

### ISSUE THREAD

**Issue by 249043822** [kubernetes/org#2391]
### GitHub Username
@249043822

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @caesarxuchao 
- @chendave 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pulls/249043822
- Issues responded to
  https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3A249043822+
- SIG projects I am involved with
  /sig apps
  /sig release
  /sig scheduling

**Comment by chendave** [comment]
Thanks for the contribution so far, +1 from me!

**Comment by caesarxuchao** [comment]
+1, but can you update the PR & issue list? They are all empty.

**Comment by 249043822** [comment]
@caesarxuchao Fixed!

**Comment by caesarxuchao** [comment]
+1！

**Comment by mrbobbytables** [comment]
Hey there @249043822, thank you for all your contributions so far :)

I've created PR #2401  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
