### ISSUE TITLE
REQUEST: New membership for dougsland

### ISSUE THREAD

**Issue by dougsland** [kubernetes/org#2392]
### GitHub Username
dougsland

### Organization you are requesting membership in
kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@eddiezane 
@pwittrock

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pull/95292
  https://github.com/kubernetes/kubernetes/pull/95076
  https://github.com/kubernetes/kubernetes/pull/95678
  https://github.com/kubernetes/kubernetes/pull/95260

- Issues responded to
  https://github.com/kubernetes/kubernetes/issues/80228
  https://github.com/kubernetes/kubernetes/issues/56402
  https://github.com/kubernetes/kubernetes/issues/95074
  https://github.com/kubernetes/kubernetes/issues/95293

- SIG projects I am involved with SIG-CLI

**Comment by eddiezane** [comment]
+1 to have Doug!

**Comment by savitharaghunathan** [comment]
Hi, @dougsland 👋 Thanks for all your contributions to the Kubernetes ecosystem :)

I've created PR #2393 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
