### ISSUE TITLE
REQUEST: New membership for @nate-double-u

### ISSUE THREAD

**Issue by nate-double-u** [kubernetes/org#2396]
### GitHub Username
@nate-double-u

### Organization you are requesting membership in
@kubernetes (kubernetes/website)

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @celestehorgan
- @sftim

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/website/pull/25289
  https://github.com/kubernetes/website/pull/24416
  https://github.com/kubernetes/website/pull/24753
  https://github.com/kubernetes/website/pull/24728
  https://github.com/kubernetes/website/pull/25246
  https://github.com/kubernetes/website/pull/25259 (still open)
- Issues responded to
  https://github.com/kubernetes/website/issues/24731
  https://github.com/kubernetes/website/issues/23354
- SIG projects I am involved with
  [sig-docs](https://github.com/kubernetes/community/tree/master/sig-docs)

**Comment by sftim** [comment]
:+1:
LGTM!

**Comment by celestehorgan** [comment]
👍 

LGTM!

**Comment by mrbobbytables** [comment]
@nate-double-u, thank you for all your contributions so far :D

I've created PR #2401  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by nate-double-u** [comment]
Thanks everyone!
