### ISSUE TITLE
REQUEST: New membership for Kartik494

### ISSUE THREAD

**Issue by Kartik494** [kubernetes/org#2397]
### GitHub Username
@Kartik494

### Organization you are requesting membership in
@kubernetes-csi

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xing-yang 
- @msau42 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/kubernetes-csi/external-snapshotter/pull/307
   - https://github.com/kubernetes-csi/csi-driver-host-path/pull/196
   - https://github.com/kubernetes-csi/external-resizer/pull/128
   - https://github.com/kubernetes-csi/csi-driver-host-path/pull/160
   - https://github.com/kubernetes-csi/external-snapshotter/pull/367

- Issues responded to
  - https://github.com/kubernetes-csi/external-snapshotter/issues/186
  - https://github.com/kubernetes-csi/csi-driver-host-path/issues/170
  - https://github.com/kubernetes-csi/csi-driver-host-path/issues/152
  - https://github.com/kubernetes-csi/csi-test/issues/248

- SIG projects I am involved with
  - https://github.com/kubernetes-csi/external-snapshotter
  - https://github.com/kubernetes-csi/csi-driver-host-path
  - https://github.com/kubernetes-csi/docs
  - https://github.com/kubernetes-csi/external-resizer

**Comment by xing-yang** [comment]
+1 @Kartik494 has done a lot of work in external-snapshotter.

**Comment by msau42** [comment]
+1!

**Comment by nikhita** [comment]
@Kartik494 thank you for all your contributions so far \o/

I've created PR #2412 to add you to the Kubernetes CSI Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-csi! 🎉

/assign
