### ISSUE TITLE
REQUEST: New membership for @christopherhein

### ISSUE THREAD

**Issue by christopherhein** [kubernetes/org#24]
### GitHub Username
@christopherhein

### Organization you are requesting membership in
@kubernetes-sigs
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nckturner 
- @mattmoyer
- @errordeveloper  
- @d-nishi

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/issues/19033
- https://github.com/kubernetes/kubernetes/issues/55278
- https://github.com/kubernetes/kubernetes/pull/62774
- https://github.com/kubernetes/kops/pull/4481
- https://github.com/kubernetes/website/pull/6692
- https://github.com/kubernetes/kops/pull/5197
- https://github.com/kubernetes/website/pull/6260
- https://github.com/kubernetes/autoscaler/issues/113
- https://github.com/kubernetes-sigs/aws-iam-authenticator
- https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/72
- https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/122
- https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/124
- https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/128
- https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/116
- https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/97
- https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/95
- https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/97
- https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/359
- https://github.com/kubernetes-client/java/issues/315
- https://github.com/kubernetes-incubator/external-dns/issues/672
- https://github.com/kubernetes-incubator/external-dns/pull/673

**Comment by errordeveloper** [comment]
+1

**Comment by d-nishi** [comment]
+1

**Comment by cblecker** [comment]
Invites sent! Welcome to @kubernetes :)

**Comment by christopherhein** [comment]
👏 thanks, @cblecker @errordeveloper @d-nishi @mattmoyer !
