### ISSUE TITLE
REQUEST: New membership for Mr-Linus at KubeCon

### ISSUE THREAD

**Issue by Mr-Linus** [kubernetes/org#240]
### GitHub Username
@Mr-Linus 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @chenopis

- @bradtopol

- @zacharysarah

### List of contributions to the Kubernetes project
- PRs reviewed / authored
<https://github.com/kubernetes-retired/kubernetes-docs-zh/pull/532>
<https://github.com/kubernetes-retired/kubernetes-docs-zh/pull/541>
<https://github.com/kubernetes/website/pull/10095>
- Issues responded to
<https://github.com/kubernetes/test-infra/issues/9194>

- SIG projects I am involved with

/area github-membership

**Comment by bradtopol** [comment]
+1 from me as well
 
Thanks!
 
Brad
  
Brad Topol, Ph.D.IBM Distinguished Engineer 
Open Technology & Developer AdvocacyKubernetes Contributor and Conformance Workgroup Member(919) 543-0646Internet: btopol@us.ibm.comAssistant: Kendra Witherspoon (919) 254-0680 
 
 
----- Original message -----From: Zach Corleissen <notifications@github.com>To: kubernetes/org <org@noreply.github.com>Cc: Brad Topol <btopol@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [kubernetes/org] REQUEST: New membership for Mr-Linus at KubeCon (#240)Date: Wed, Nov 14, 2018 1:22 AM 
+1

**Comment by mrbobbytables** [comment]
@Mr-Linus, thank you for all your contributions so far :)

I've created PR #253  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
