### ISSUE TITLE
REQUEST: New membership for carlory

### ISSUE THREAD

**Issue by carlory** [kubernetes/org#2402]
### GitHub Username
carlory

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@pacoxu 
@oomichi 
@markthink 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/kubernetes/website/pull/25935
   - https://github.com/kubernetes/kubernetes/pull/97592
   - https://github.com/kubernetes/kubernetes/pull/97563
   - https://github.com/kubernetes/kubernetes/pull/97558
   - https://github.com/kubernetes/kubernetes/pull/97547
   - https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/419
   - https://github.com/kubernetes/kubernetes/pull/81987
   - https://github.com/kubernetes/kubernetes/pull/81985
   - https://github.com/kubernetes/kubernetes/pull/81983
   - https://github.com/kubernetes/kubernetes/pull/81980
   - https://github.com/kubernetes/kubernetes/pull/81978
   - https://github.com/kubernetes/kubernetes/pull/81974
   - https://github.com/kubernetes/kubernetes/pull/81944
   - https://github.com/kubernetes/kubernetes/pull/81940
   - https://github.com/kubernetes/kubernetes/pull/81928
   - https://github.com/kubernetes/kubernetes/pull/81335
   - https://github.com/kubernetes/kubernetes/pull/74117
   - https://github.com/kubernetes-sigs/service-catalog/pull/2446
   - https://github.com/kubernetes-sigs/service-catalog/pull/2429
   - https://github.com/kubernetes-sigs/service-catalog/pull/2423
   - https://github.com/kubernetes/kubernetes/pull/58438
   - https://github.com/helm/helm/pull/2715
- Issues responded to
   - https://github.com/kubernetes/kubernetes/issues/96303
   - https://github.com/kubernetes/kubernetes/issues/97549
   - https://github.com/kubernetes/kubernetes/issues/96760
   - https://github.com/kubernetes/kubernetes/issues/81427
   - https://github.com/kubernetes/kubernetes/issues/81657
   - https://github.com/kubernetes-sigs/service-catalog/issues/2494
   - https://github.com/kubernetes/kubernetes/issues/64207
   - https://github.com/kubernetes/kubernetes/issues/58427 
   - https://github.com/kubernetes/kubernetes/issues/47006
- SIG projects I am involved with
   - kubernetes/kubernetes
   - kubernetes-sigs/website
   - kubernetes-sigs/apiserver-builder-alpha
   - kubernetes-sigs/service-catalog
   - helm/helm

**Comment by pacoxu** [comment]
/lgtm

Thanks for contributions!

**Comment by oomichi** [comment]
I was surprised @carlory is not the organization member yet :-)
+1 for his membership.

**Comment by nikhita** [comment]
@carlory sponsors need to be in an OWNERS file in any repo in the @kubernetes org. Unfortunately, due to this restriction, @pacoxu would not be able to sponsor.

Can you please find an additional sponsor who is in the OWNERS file?

**Comment by markthink** [comment]
/lgtm

Thanks for contributions!

**Comment by carlory** [comment]
@nikhita Thanks,  there're 2 sponsors now.

**Comment by nikhita** [comment]
Unfortunately, @markthink is also not in an OWNERS file in the @kubernetes org, so you'll still need an additional sponsor.

**Comment by xichengliudui** [comment]
not sure I have permissions here but let's see
+1

**Comment by nikhita** [comment]
@xichengliudui's +1 did the magic! :sparkles:  

@carlory I've created PR #2412 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
