### ISSUE TITLE
REQUEST: New membership for spowelljr

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/org#2403]
### GitHub Username
@spowelljr

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @medyagh 
- @afbjorklund

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/minikube/pull/9814
https://github.com/kubernetes/minikube/pull/9904
https://github.com/kubernetes/minikube/pull/9935
https://github.com/kubernetes/minikube/pull/9978
https://github.com/kubernetes/minikube/pull/9994
https://github.com/kubernetes/minikube/pull/10042

- Issues responded to
https://github.com/kubernetes/minikube/issues/9661

- SIG projects I am involved with
sig-cluster-lifecycle/minikube

**Comment by medyagh** [comment]
I sponsor @spowelljr

**Comment by nikhita** [comment]
@afbjorklund ping for sponsorship

**Comment by afbjorklund** [comment]
I sponsor @spowelljr

**Comment by nikhita** [comment]
@spowelljr thank you for all your contributions so far \o/

I've created PR #2412 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
