### ISSUE TITLE
REQUEST: New membership for feloy

### ISSUE THREAD

**Issue by feloy** [kubernetes/org#2404]
### GitHub Username

@feloy 

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @kbhawkey 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/website/pull/23294
  - https://github.com/kubernetes-sigs/reference-docs/pull/179
  - https://github.com/kubernetes-sigs/reference-docs/pull/186
  - https://github.com/kubernetes-sigs/reference-docs/pull/91
  - https://github.com/kubernetes-sigs/reference-docs/pull/87
  - https://github.com/kubernetes/website/pull/25404
  - https://github.com/kubernetes/website/pull/22860
  - https://github.com/kubernetes/website/pull/22853
  - https://github.com/kubernetes/website/pull/21372
  - https://github.com/kubernetes/website/pull/21125
  - https://github.com/kubernetes/website/pull/21123
  - https://github.com/kubernetes/website/pull/21106
  - https://github.com/kubernetes/website/pull/18711
  - https://github.com/kubernetes/website/pull/16595
  - https://github.com/kubernetes/website/pull/16594
  - https://github.com/kubernetes/website/pull/16593
  - https://github.com/kubernetes/website/pull/16590
  - https://github.com/kubernetes/website/pull/16585
  - https://github.com/kubernetes/website/pull/16568
  - https://github.com/kubernetes/website/pull/15213
  - https://github.com/kubernetes/website/pull/15211
  - https://github.com/kubernetes/website/pull/13368
  - https://github.com/kubernetes/website/pull/13240
  - https://github.com/kubernetes/website/pull/13218
  - https://github.com/kubernetes/website/pull/13142
  - https://github.com/kubernetes/website/pull/13059
  - https://github.com/kubernetes/website/pull/13058
  - https://github.com/kubernetes/website/pull/12863
  - https://github.com/kubernetes/website/pull/12803
  - https://github.com/kubernetes/dashboard/pull/5041
  - https://github.com/kubernetes/dashboard/pull/4828
  - https://github.com/kubernetes/dashboard/pull/4697
  - https://github.com/kubernetes/dashboard/pull/4412
  - https://github.com/kubernetes/dashboard/pull/4324
  - https://github.com/kubernetes/dashboard/pull/4279
  - https://github.com/kubernetes/dashboard/pull/4101
  - https://github.com/kubernetes/dashboard/pull/3812
  - https://github.com/kubernetes/dashboard/pull/3785
  - https://github.com/kubernetes/dashboard/pull/3783
  - https://github.com/kubernetes/dashboard/pull/3770
  - https://github.com/kubernetes/dashboard/pull/3767
  - https://github.com/kubernetes/dashboard/pull/3766
- Issues responded to
  - https://github.com/kubernetes/website/issues/23809
- SIG projects I am involved with
  - sig docs
  - sig ui

**Comment by zacharysarah** [comment]
Plus one. 👍🏻

**Comment by kbhawkey** [comment]
+1

**Comment by nikhita** [comment]
@feloy thank you for all your contributions so far \o/

I've created PR #2412 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
