### ISSUE TITLE
REQUEST: New membership for hbagdi

### ISSUE THREAD

**Issue by hbagdi** [kubernetes/org#2406]
### GitHub Username
@hbagdi

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bowei 
- @cmluciano 

### List of contributions to the Kubernetes project
- SIG projects I am involved with: I'm a regular contributor and one of the maintainers for [Service APIs](https://github.com/kubernetes-sigs/service-apis).

**Comment by cmluciano** [comment]
+1 Harry’s contributions to the service-api community have been valuable and consistent. I fully support adding him to the org.

**Comment by bowei** [comment]
+1 Harry has done a ton of work, fully support adding to the org.

**Comment by nikhita** [comment]
@hbagdi thank you for all your contributions so far \o/

I've created PR #2412 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by hbagdi** [comment]
Thank you @nikhita!
