### ISSUE TITLE
REQUEST: New membership for heqg

### ISSUE THREAD

**Issue by heqg** [kubernetes/org#2407]
### GitHub Username
@heqg

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @klueska
- @MrHohn

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/97911
https://github.com/kubernetes/kubernetes/pull/97873
https://github.com/kubernetes/kubernetes/pull/97787
https://github.com/kubernetes/kubernetes/pull/97749
https://github.com/kubernetes/kubernetes/pull/97711
https://github.com/kubernetes/kubernetes/pull/97666
https://github.com/kubernetes/kubernetes/pull/97653
https://github.com/kubernetes/kubernetes/pull/97631
https://github.com/kubernetes/kubernetes/pull/97629
https://github.com/kubernetes/kubernetes/pull/97590
https://github.com/kubernetes/kubernetes/pull/97587
https://github.com/kubernetes/kubernetes/pull/97536
https://github.com/kubernetes/kubernetes/pull/97518
https://github.com/kubernetes/kubernetes/pull/97477
https://github.com/kubernetes/website/pull/17063
- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3Aheqg+
- SIG projects I am involved with
/sig node
/sig testing
/sig release

**Comment by heqg** [comment]
> @heqg: The label(s) `sig/cloud, sig/provider, sig/story` cannot be applied, because the repository doesn't have them

Fixed it.

**Comment by nikhita** [comment]
@klueska @MrHohn ping for sponsorship

**Comment by klueska** [comment]
I don't believe I am a good candidate for sponsorship.
The only PRs I reviewed for @heqg were two one line fixes that renamed variables and fixed some comments.
It would be better to find a sponsor that is familiar with more substantial contributions @heqg has made.

**Comment by heqg** [comment]
@dougsland  ping for sponsorship， thanks very much。

**Comment by dougsland** [comment]
> @dougsland ping for sponsorship， thanks very much。

AFAIK, I don't have the power to sponsor new members.

**Comment by ehashman** [comment]
@heqg did not reach out to me in advance asking me to sponsor; I am not willing to sponsor at this time.

**Comment by heqg** [comment]
> @heqg did not reach out to me in advance asking me to sponsor; I am not willing to sponsor at this time.


> I'm sorry, I'm not familiar with the sponsorship application procedure。 Thank you.

**Comment by mrbobbytables** [comment]
@heqg sponsors are usually people you've worked closely with and spoken to about sponsorship before applying for membership.

For the other membership requests, please see our [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements)

**Comment by heqg** [comment]
> @heqg sponsors are usually people you've worked closely with and spoken to about sponsorship before applying for membership.
> 
> For the other membership requests, please see our [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements)

ok， i hava got it, thanks
