### ISSUE TITLE
REQUEST: New membership for bmelbourne

### ISSUE THREAD

**Issue by bmelbourne** [kubernetes/org#2408]
### GitHub Username

@bmelbourne

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hakman 
- @rifelpet 
- @olemarkus 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kops/pull/9879
https://github.com/kubernetes/kops/pull/9989
https://github.com/kubernetes/kops/pull/10099
https://github.com/kubernetes/kops/pull/10109
https://github.com/kubernetes/kops/pull/10189
https://github.com/kubernetes/kops/pull/10285
https://github.com/kubernetes/kops/pull/10307
https://github.com/kubernetes/kops/pull/10370
https://github.com/kubernetes/kops/pull/10371
https://github.com/kubernetes/kops/pull/10520
https://github.com/kubernetes/kops/pull/10550

- Issues responded to
https://github.com/kubernetes/kops/pull/10419

- SIG projects I am involved with
https://github.com/kubernetes-sigs/kubespray

**Comment by hakman** [comment]
Happy to sponsor @bmelbourne. Thanks for all you did so far!
😄

**Comment by rifelpet** [comment]
+1 from me, thanks for all your hard work!

**Comment by olemarkus** [comment]
+1 from me as well!

**Comment by nikhita** [comment]
@bmelbourne thank you for all your contributions so far \o/

I've created PR #2412 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
