### ISSUE TITLE
REQUEST: New membership for seh

### ISSUE THREAD

**Issue by seh** [kubernetes/org#2409]
### GitHub Username
@seh

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed [the community membership guidelines]((https://git.k8s.io/community/community-membership.md))
- [x] I have enabled 2FA on my GitHub account
- [x] I have subscribed to [the _kubernetes-dev_ e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to one or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hakman
- @olemarkus
- @rifelpet

### List of contributions to the Kubernetes project
- PRs of which I am the author
  - [_kubernetes/helm_](https://github.com/helm/helm/pulls?q=is%3Apr+author%3Aseh)
  - [_kubernetes/kops_](https://github.com/kubernetes/kops/pulls?q=is%3Apr+author%3Aseh)
  - [_kubernetes/kubernetes_](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Aseh+)
  - [_kubernetes-sigs/controller-runtime_](https://github.com/kubernetes-sigs/controller-runtime/pulls?q=is%3Apr+author%3Aseh)
- Issues of which I am the author
  - [_kubernetes/helm_](https://github.com/helm/helm/issues?q=is%3Aissue+author%3Aseh)
  - [_kubernetes/kops_](https://github.com/kubernetes/kops/issues?q=is%3Aissue+author%3Aseh)
  - [_kubernetes/kubeadm_](https://github.com/kubernetes/kubeadm/issues?q=is%3Aissue+author%3Aseh)
  - [_kubernetes/kubernetes_](https://github.com/kubernetes/kubernete/issues?q=is%3Aissue+author%3Aseh)
  - [_kubernetes-sigs/controller-runtime_](https://github.com/kubernetes-sigs/controller-runtime/issues?q=is%3Aissue+author%3Aseh)
- SIG projects with which I am involved with
  - [_kubernetes/kops_](https://github.com/kubernetes/kops)

**Comment by hakman** [comment]
Happy to sponsor @bmelbourne. Thanks for all you did so far!
😄

**Comment by rifelpet** [comment]
+1 from me, thanks for all your hard work!

**Comment by olemarkus** [comment]
+1 from me as well

**Comment by nikhita** [comment]
@seh thank you for all your contributions so far \o/

I've created PR #2412 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
