### ISSUE TITLE
New (staging) repo for k8s network information distributor / aka kube-proxy2

### ISSUE THREAD

**Issue by mcluseau** [kubernetes/org#2410]
### New Repo, Staging Repo, or migrate existing
new repository (can migrate from https://github.com/mcluseau/kube-proxy2)

### Requested name for new repository

Edit (nikhita): final name is `kpng`. See discussion below.

TBD: the name is not yet decided. Proposals:
- knid (k8s network information distribution)
- ksdn
- kube-proxy-ng
- ...

### Which Organization should it reside
kubernetes-sigs / sig-network

### If not a staging repo, who should have admin access
staging repo

### If not a staging repo, who should have write access
staging repo

### If not a staging repo, who should be listed as approvers in OWNERS
staging repo

### If not a staging repo, who should be listed in SECURITY_CONTACTS
staging repo

### What should the repo description be
depends on the chosen name

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject for sig-network called [TBD: chosen name]

### Approvals

Creation advised by @thockin

**Comment by nikhita** [comment]
@mcluseau since this would be a staging repo, this will also need approval from sig-architecture.

> Creation advised by @thockin

/assign @thockin 
to ack on approval for the record

**Comment by mcluseau** [comment]
@nikhita thanks for your answer, on the "staging" part, it's what looked like my idea, but it's incubating, ie publishing the code in the k8s realm so others can contribute, until we reach the next stage.

**Comment by thockin** [comment]
A staging repo, as fart as I understand, exists in k/k/staging/src/k8s.io/... - I do not think that's what we want here.

As for names, I am terrible at naming things but I can filter some out :)

"knid" is too close to "kind"
"ksdn" carries SDN connotation that I don't think we want.
 "kube-proxy-ng" is a little long, but clear.  I don't like "kube-proxy" as a name because it's really not a proxy.

Throwing some suggestions:

epsel - the endpoints selector
kp2
kpng - pronounced "kaping"
kpow - kupe-proxy object watcher
seppi - service/endpoint preprocessing interface

brainstorm!

**Comment by justaugustus** [comment]
(Drive-by comment to say I like kpng and kpow. 🙃)

**Comment by mcluseau** [comment]
kest - kubernetes endpoints & services transport (pronounced "quest")
knest - k8s network endpoitns & services transport (fun too, matures the eggs to produce the final flying thing)

**Comment by mcluseau** [comment]
ksept - work too (service endpoints transport), where sept is seven in french, and the number of edges in the k8s logo

**Comment by mcluseau** [comment]
seems like kpng is the winner here so let's go for it ;-)

**Comment by thockin** [comment]
I can live with kpng - it's not like we can't change it as we evolve it.

**Comment by dims** [comment]
+1 to `kpng`

**Comment by nikhita** [comment]
@mcluseau is the repo meant to contain code migrated from https://github.com/mcluseau/kube-proxy2?

If so, can you update the `kube-proxy2` repo as per https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories?

**Comment by mcluseau** [comment]
@nikhita ok wilco and notify here when done, thanks :)

**Comment by mcluseau** [comment]
ok, I think I've gone through the checklist

**Comment by nikhita** [comment]
@mcluseau Can you also update the template files to match the repo? For instance, these files would need update - README.md, OWNERS, OWNERS_ALIASES (this can be deleted if not needed), and SECURITY_CONTACTS.

**Comment by mcluseau** [comment]
ohhh... ok... I'm responsible of those too now, that's something real :scream: ;-)

**Comment by nikhita** [comment]
@mcluseau if you are in the OWNERS file, you also need to be a member of the @kubernetes-sigs GitHub organization to be able to approve PRs.

Can you create an issue to request membership? Detailed instructions are here - https://github.com/kubernetes/community/blob/master/community-membership.md#member

**Comment by nikhita** [comment]
@mcluseau I think we're good to go ahead with the migration!

Can you move https://github.com/mcluseau/kube-proxy2 to https://github.com/kubernetes-purgatory? (you should have an invite)

I'll need admin access to the repo to be able to migrate it to k-sigs, but GitHub doesn't allow adding admins to user-owned repos so we'll need to migrate it to a dummy org first.

**Comment by mcluseau** [comment]
Hi @nikhita , yes the time has come :) I pushed under the voted name (kpng): https://github.com/kubernetes-purgatory/kpng

**Comment by nikhita** [comment]
Repo has been migrated - https://github.com/kubernetes-sigs/kpng

Also created:
- https://github.com/kubernetes/org/pull/2598 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/5659 - to add the repo to sigs.yaml

Once both PRs merge, this issue can be closed.

**Comment by nikhita** [comment]
All PRs have merged and teams have been granted access. Closing.
