### ISSUE TITLE
REQUEST: New membership for fleeto

### ISSUE THREAD

**Issue by fleeto** [kubernetes/org#242]
### GitHub Username

@fleeto

### Organization you are requesting membership in

kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @idealhack 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

https://github.com/kubernetes/website/pull/4105

- Issues responded to
- SIG projects I am involved with

/area github-membership

**Comment by idealhack** [comment]
+1 on this. I read many Chinese articles by Vincent when I get started with Kubernetes. His blog is https://blog.fleeto.us.

/reopen

**Comment by fleeto** [comment]
Hi @zacharysarah, nice to meet you yesterday, and showed you how we are working for `istio.io`, I'd thought that @markthink had told you that I'll make the request to be a member of k8s. So I choose you as my sponsor.

I am one of the main contributors of [`istio.io/zh`](https://github.com/istio/istio.io/graphs/contributors), at the same time, I'm one of the authors of a  book about Kubernetes, which maybe the most popular one in Chinese world.

**Comment by zacharysarah** [comment]
@fleeto It was good to meet you also! I’m happy to sponsor you.

+1

**Comment by mrbobbytables** [comment]
Hey there @fleeto, thanks for all your translation and education work :)

I've created PR #247   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
