### ISSUE TITLE
REQUEST: New membership for n3wscott

### ISSUE THREAD

**Issue by n3wscott** [kubernetes/org#2421]
### GitHub Username
@n3wscott

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @thejoycekung
- @palnabarun

### List of contributions to the Kubernetes project

CI Signal shadow for Kubernetes 1.21

**Comment by thejoycekung** [comment]
Yay!! +1 -- super excited to have you join the release team Scott -- 1.21 is going to be awesome! 🎉

**Comment by palnabarun** [comment]
@n3wscott -- Yay!!! Welcome to the 1.21 Release Team! 🎉 

/honk

**Comment by justaugustus** [comment]
+1! Welcome to the team, Scott!

/pony party

**Comment by savitharaghunathan** [comment]
Hi, @n3wscott 👋 Welcome to the 1.21 Release Team 🎉

I've created PR #2427 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
