### ISSUE TITLE
REQUEST: New membership for desponda

### ISSUE THREAD

**Issue by desponda** [kubernetes/org#2424]
### GitHub Username
@desponda

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @erismaster 
- @jeremyrickard 

### List of contributions to the Kubernetes project
- Bug Triage Shadow for Kubernetes 1.21

**Comment by erismaster** [comment]
+1

Welcome!

**Comment by savitharaghunathan** [comment]
+1. Welcome to the 1.21 Release Team @desponda 🎉 

/assign

**Comment by soniasingla** [comment]
Welcome to the team 🙌

**Comment by savitharaghunathan** [comment]
Hi, @desponda 👋 Welcome again to the 1.21 Release Team 🎉

I've created PR #2427 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by palnabarun** [comment]
@desponda -- Welcome to the team! 🎉 Great to have you here! :)

/honk
