### ISSUE TITLE
REQUEST: New membership for ams0

### ISSUE THREAD

**Issue by ams0** [kubernetes/org#2426]
### GitHub Username
@ams0

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @erismaster 
- @onlydole 

### List of contributions to the Kubernetes project
- Bug Triage Shadow for Kubernetes 1.21

**Comment by erismaster** [comment]
+1

Welcome to the release team!

**Comment by onlydole** [comment]
A huge +1 here! Welcome to the team, @ams0 :tada: 1.21 is going to be a fun and epic release :smile:

**Comment by savitharaghunathan** [comment]
Hi, @ams0 👋  Welcome to the 1.21 Release Team 🎉

I've created PR #2427 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by palnabarun** [comment]
@ams0 -- Welcome to the 1.21 Release Team! 🎉 Glad to have you here.

/honk
