### ISSUE TITLE
REQUEST: New membership for PI-Victor

### ISSUE THREAD

**Issue by PI-Victor** [kubernetes/org#2428]
### GitHub Username
@pi-victor

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @reylejano 
- @palnabarun 

### List of contributions to the Kubernetes project
Selected as shadow for SIG Docs 1.21 Release Team

**Comment by reylejano** [comment]
+1 Welcome to the 1.21 SIG Docs Release Team @PI-Victor 🎉

**Comment by savitharaghunathan** [comment]
+1. Welcome to the 1.21 Release Team, @PI-Victor! 🎉 

/assign

**Comment by savitharaghunathan** [comment]
Hi, @PI-Victor 👋  Welcome again to the 1.21 Release Team 🎉

I've created PR #2433 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/pony party

**Comment by PI-Victor** [comment]
@savitharaghunathan thank you, appreciate the help!

**Comment by palnabarun** [comment]
@PI-Victor -- Welcome to the 1.21 Release Team! Glad to have you here. 🎉 

/woof

**Comment by PI-Victor** [comment]
thanks for the help @palnabarun!
