### ISSUE TITLE
REQUEST: New membership for melodychn

### ISSUE THREAD

**Issue by melodychn** [kubernetes/org#2429]
### GitHub Username
@melodychn

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @wilsonehusin 
- @onlydole 

### List of contributions to the Kubernetes project
Selected as Release Notes Shadow for 1.21

**Comment by wilsonehusin** [comment]
/lgtm

welcome! 🎉

**Comment by onlydole** [comment]
Welcome to the 1.21 Release Team, @melodychn! It's going to be an epic endeavor 😁

**Comment by savitharaghunathan** [comment]
Hi, @melodychn 👋 Welcome to the 1.21 Release Team! 🎉

I've created PR #2433 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/pony party

**Comment by palnabarun** [comment]
@melodychn -- Welcome to the 1.21 Release Team! 🎉 Glad to have you here.

/honk
