### ISSUE TITLE
REQUEST: New membership for @Aut0R3V

### ISSUE THREAD

**Issue by Aut0R3V** [kubernetes/org#2431]
### GitHub Username
@Aut0R3V

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@sftim 
@tengqm 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
kubernetes/website#26041 
kubernetes/kubernetes#97561
kubernetes/website#26050 
kubernetes/website#26022 
kubernetes/website#26014 
kubeflow/internal-acls#425 
kubernetes/website#26060 
kubernetes/website#25460 
kubernetes/website#25459
kubernetes/website#25541 
kubernetes/website#25580 
kubernetes/website#26023 
kubernetes/website#24949 
kubernetes/website#25904 
kubernetes/enhancements#2169 

- SIG projects I am involved with
kubernetes/website

**Comment by tengqm** [comment]
+1 looking forward to more contributions from you.

**Comment by sftim** [comment]
@Aut0R3V, thanks for stepping forward. :+1:

**Comment by Aut0R3V** [comment]
Thanks for the help@sftim @tengqm

**Comment by nikhita** [comment]
@Aut0R3V thank you for all your contributions so far \o/

I've created PR #2438 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by Aut0R3V** [comment]
Thanks a lot!
