### ISSUE TITLE
REQUEST: New membership for @mvortizr

### ISSUE THREAD

**Issue by mvortizr** [kubernetes/org#2432]
### GitHub Username
@mvortizr

### Organization you are requesting membership in
kubernetes-sigs, kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @reylejano
- @palnabarun

### List of contributions to the Kubernetes project
- SIG projects I am involved with
I was selected as shadow for the SIG Docs 1.21 Release Team

**Comment by savitharaghunathan** [comment]
+1. Welcome to the 1.21 Release Team, @mvortizr! 🎉 

/assign

**Comment by savitharaghunathan** [comment]
@mvortizr - Are you looking for a membership only for @kubernetes-sigs org? Creating PRs & reviews in k/website would require @kubernetes org membership. Asking because the docs work will mostly happen in k/website repo.
cc: @reylejano

**Comment by reylejano** [comment]
+1 Welcome to the 1.21 SIG Docs Release Team @mvortizr  🎉

**Comment by reylejano** [comment]
Hi @mvortizr, can you edit the organization in the issue to @kubernetes. As @savitharaghunathan stated, the Release Docs work will mostly be in the k/website repo.

**Comment by mvortizr** [comment]
@reylejano ok, thank you!!

**Comment by savitharaghunathan** [comment]
Hi, @mvortizr 👋 Happy to have you on the 1.21 Release Team! 🎉

I've created PR #2433 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/pony party

**Comment by palnabarun** [comment]
@mvortizr -- Welcome to the 1.21 Release Team! 🎉 Glad to have you here!

/honk
