### ISSUE TITLE
REQUEST: New membership for harche

### ISSUE THREAD

**Issue by harche** [kubernetes/org#2434]
### GitHub Username
@harche

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sjenning
- @rphillips 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Aharche+is%3Aclosed
https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+is%3Aclosed+author%3Aharche
https://github.com/cri-o/cri-o/pulls?q=is%3Apr+is%3Aclosed+author%3Aharche

- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=commenter%3Aharche+

- SIG projects I am involved with
@sig-node

**Comment by rphillips** [comment]
+1

/cc @ehashman @bobbypage

**Comment by ehashman** [comment]
+1

You need sponsors from two different companies, @bobbypage would you be willing to sponsor?

**Comment by dims** [comment]
+1 from me.

**Comment by bobbypage** [comment]
+1 

@harche has contributed quite a bit to SIG-Node and to improving e2e testing

**Comment by nikhita** [comment]
@harche thank you for all your contributions so far \o/

I've created PR #2438 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by harche** [comment]
Thanks @nikhita @bobbypage @dims @ehashman @rphillips
