### ISSUE TITLE
REQUEST: New membership for JAORMX

### ISSUE THREAD

**Issue by JAORMX** [kubernetes/org#2435]
### GitHub Username
JAORMX

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @saschagrunert 
- @pjbgf

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/security-profiles-operator/pulls?q=is%3Apr+author%3AJAORMX+
- https://github.com/kubernetes-sigs/security-profiles-operator/issues?q=is%3Aissue+author%3AJAORMX
- https://github.com/kubernetes-sigs/security-profiles-operator

**Comment by saschagrunert** [comment]
+1 I'd be happy to welcome @JAORMX at k-sigs

**Comment by pjbgf** [comment]
+1 also happy for @JAORMX to join k-sigs!

**Comment by nikhita** [comment]
@JAORMX thank you for all your contributions so far \o/

I've created PR #2438 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
