### ISSUE TITLE
REQUEST: New membership for ChandaniM123

### ISSUE THREAD

**Issue by ChandaniM123** [kubernetes/org#2436]
### GitHub Username
ChandaniM123

### Organization you are requesting membership in
Kubernetes

### Requirements
- [ Y ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ Y ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ Y ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ Y ] I am actively contributing to 1 or more Kubernetes subprojects
- [ Y ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ Y ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- Rey Lejano(@reylejano)
- Nabarun Pal(@palnabarun)

### List of contributions to the Kubernetes project
- SIG Docs Release Shadow

**Comment by reylejano** [comment]
+1 Welcome to the 1.21 SIG Docs Release Team @ChandaniM123  🎉

**Comment by palnabarun** [comment]
+1. Welcome to the 1.21 Release Team! 🎉 

Glad to have you here. 👍🏽 

/honk

**Comment by savitharaghunathan** [comment]
Hi, @ChandaniM123 👋  Welcome to the 1.21 Release Team! 🎉

I've created PR #2441 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/pony party
