### ISSUE TITLE
New repo for kubernetes-incubator/external-storage/local-volume

### ISSUE THREAD

**Issue by cofyc** [kubernetes/org#244]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
sig-storage-local-static-provisioner

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@msau42
@saad-ali 
@jsafrane 

### If a new repo, who should be listed as approvers in OWNERS
@msau42
@saad-ali
@wongma7
@jsafrane
@dhirajh
@cofyc

### If a new repo, who should be listed in SECURITY_CONTACTS
@msau42 
@saad-ali 
@jsafrane 

### What should the repo description be
Static provisioner of local volumes

### What SIG and subproject does this fall under in sigs.yaml
sig-storage

### Approvals
Need sig-storage approval from: @childsb, @saad-ali and @msau42
See "Break out local-provisioner from external-storage repo" in https://docs.google.com/spreadsheets/d/1t4z5DYKjX2ZDlkTpCnp18icRAQqOE85C1T1r2gqJVck/edit#gid=1566770776

### Additional context for request
Current, kubernetes-incubator/external-storage houses a lot of different provisioners. Different provisioners may have theirs own dependency/ci requirements, etc. For dependency management, it resulted that external-storage repo has huge dependency chain, and updating dependencies for one provisioner requires updating it for all provisioners which is not convenient and may have risk. So we are going to break out local-provisioner from external-storage repo first.

/area github-repo

**Comment by msau42** [comment]
@jsafrane @gnufied what do you think of the repo name and description?

**Comment by cofyc** [comment]
Updated.

**Comment by msau42** [comment]
Maybe the description should emphasize that it does do dynamic provisioning.  Something like "The local volume static provisioner manages the PersistentVolume lifecycle for pre-allocated disks by detecting and creating PVs for each local disk on the host, and cleaning up the disks when released.  It does not support dynamic provisioning."

**Comment by cofyc** [comment]
I think this repo description is only used as initial description value on repo creation, we can change it later. And I think it's better to add this long detail description in README.md file.

**Comment by cblecker** [comment]
Waiting on explicit sig-storage approval on this one

**Comment by saad-ali** [comment]
Approved on behalf of SIG Storage.

**Comment by cblecker** [comment]
Created: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner

**Comment by cofyc** [comment]
Thanks!
