### ISSUE TITLE
REQUEST: New membership for natasha41575

### ISSUE THREAD

**Issue by natasha41575** [kubernetes/org#2447]
### GitHub Username

@natasha41575

### Organization you are requesting membership in

@kubernetes-sigs, and its kustomize subteam.

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pwittrock
- @monopole 

### List of contributions to the Kubernetes project
- involved in kustomize
- [PRs authored](https://github.com/kubernetes-sigs/kustomize/pulls?q=is%3Aclosed+is%3Apr+author%3Anatasha41575+)
- [Issues responded to](https://github.com/kubernetes-sigs/kustomize/issues?q=is%3Aissue++commenter%3Anatasha41575+author%3Anatasha41575+)

**Comment by palnabarun** [comment]
@natasha41575 -- Thank you for your contributions to Kustomize!

Once #2448 merges, you will get an invite to the @kubernetes-sigs GitHub organization. 

Welcome to the @kubernetes-sigs! 🎉 

---

PS: Anyone looking at this request later, the sponsor approval was done in the PR #2448 itself.

**Comment by palnabarun** [comment]
/close

(as #2448 merged)
