### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for @cofyc 

### ISSUE THREAD

**Issue by cofyc** [kubernetes/org#245]
### GitHub Username
@cofyc 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] ~~I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application~~

### Sponsors / List of contributions to the Kubernetes project

Member of @kubernetes, you can view my original member ship request at https://groups.google.com/forum/#!topic/kubernetes-membership/MY76kYKTbrs.

We're currently migrating local static provisioner from kubernetes-incubator/external-storage to kubernetes-sigs (#244), I need to be a member of it first. Thanks!

/area github-membership

**Comment by mrbobbytables** [comment]
@cofyc I've created PR #247 to add you to the Kubernetetes-sigs Org. As soon as that gets merged, you should get a membership invite and be good to go :)
