### ISSUE TITLE
REQUEST: New membership for shysank

### ISSUE THREAD

**Issue by shysank** [kubernetes/org#2455]
### GitHub Username
@shysank

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @CecileRobertMichon
- @nader-ziada 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+shysank
   https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+shysank
- Issues responded to
   https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues?q=is%3Aissue+shysank
   https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+shysank
- SIG projects I am involved with
  kubernetes-sigs/cluster-api
  kubernetes-sigs/cluster-api-provider-azure

**Comment by CecileRobertMichon** [comment]
Big +1!

Thank you @shysank for all your contributions thus far 👏

**Comment by nader-ziada** [comment]
Another big +1
thank you @shysank for all the great work

**Comment by palnabarun** [comment]
@shysank -- thank you for all your contributions so far :)

I've created PR #2460 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign

**Comment by CecileRobertMichon** [comment]
@shysank, just noticed this, you need @kubernetes-sigs membership since that's where CAPI/CAPZ are hosted, @kubernetes org is separate.
