### ISSUE TITLE
REQUEST: New membership for wzshiming

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/org#2459]
### GitHub Username
@wzshiming

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @neolit123
- @liggitt
- 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Awzshiming
  https://github.com/kubernetes/gengo/pulls?q=is%3Apr+author%3Awzshiming
  https://github.com/kubernetes/gengo/pull/117
  https://github.com/kubernetes/gengo/pull/162
  WIP https://github.com/kubernetes/kubernetes/pull/97686
  https://github.com/kubernetes/kubernetes/pull/97754
  https://github.com/kubernetes/kubernetes/pull/97950
  WIP https://github.com/kubernetes/kubernetes/pull/98005
  https://github.com/kubernetes/kubernetes/pull/98088
  https://github.com/kubernetes/kubernetes/pull/98200
  WIP https://github.com/kubernetes/kubernetes/pull/98343

- Issues responded to
  https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3Awzshiming
  https://github.com/kubernetes/kubernetes/issues/97951
  https://github.com/kubernetes/kubernetes/issues/98004
  https://github.com/kubernetes/kubernetes/issues/98087
  https://github.com/kubernetes/kubernetes/issues/98260

**Comment by neolit123** [comment]
+1 thanks @wzshiming

**Comment by liggitt** [comment]
+1

**Comment by palnabarun** [comment]
@wzshiming -- thank you for all your contributions so far :)

I've created PR #2460 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign

**Comment by bobbypage** [comment]
a little late, but +1 from me also, thanks @wzshiming for your contributions!  :)

**Comment by mrunalp** [comment]
:+1:
