### ISSUE TITLE
REQUEST: New membership for @danielqsj

### ISSUE THREAD

**Issue by danielqsj** [kubernetes/org#246]
### GitHub Username
@danielqsj

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @aledbf 
- @k82cn 

### List of contributions to the Kubernetes project

Sponsor and maintainer of one prometheus exporter: https://github.com/danielqsj/kafka_exporter
Speaker in KubeCon China 2018: https://sched.co/FuK6

- PRs reviewed / authored
  - https://github.com/kubernetes/ingress-nginx/pull/351
  - https://github.com/kubernetes/ingress-nginx/pull/454
  - https://github.com/kubernetes/kubernetes/pull/44837
  - https://github.com/kubernetes/ingress-nginx/pull/1179
  - https://github.com/kubernetes/ingress-nginx/pull/1198
  - https://github.com/kubernetes/ingress-nginx/pull/1212
  - https://github.com/kubernetes/ingress-nginx/pull/1226
  - https://github.com/kubernetes/ingress-nginx/pull/1227
  - https://github.com/kubernetes/ingress-nginx/pull/1228
  - https://github.com/kubernetes/ingress-nginx/pull/1230
  - https://github.com/kubernetes/ingress-nginx/pull/1272
  - https://github.com/kubernetes/ingress-nginx/pull/1277
  - https://github.com/kubernetes/kubernetes/pull/57146

- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/13241
  - https://github.com/kubernetes/kubernetes/issues/44894
  - https://github.com/kubernetes/kubernetes/issues/56806
  - https://github.com/kubernetes/kubernetes/issues/28943
  - https://github.com/kubernetes/kubernetes/issues/28951
  - https://github.com/kubernetes/kubernetes/issues/29974
  - https://github.com/kubernetes/ingress-nginx/issues/350
  - https://github.com/kubernetes/ingress-nginx/issues/453
  - https://github.com/kubernetes/ingress-nginx/issues/1197
  - https://github.com/kubernetes/ingress-nginx/issues/1211
  - https://github.com/kubernetes/kubernetes/issues/56958
  - https://github.com/kubernetes/kubernetes/issues/56988

- SIG projects I am involved with
  sig network

/area github-membership

**Comment by k82cn** [comment]
+1

**Comment by aledbf** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @danielqsj,  thank you for all your contributions so far :)

I've created PR #249  to add you to both the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification for both of them.

Welcome to @kubernetes! 🎉

**Comment by danielqsj** [comment]
Thanks @mrbobbytables @k82cn @aledbf !
