### ISSUE TITLE
REQUEST: New membership for haircommander

### ISSUE THREAD

**Issue by haircommander** [kubernetes/org#2463]
### GitHub Username
@haircommander

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mrunalp
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/98424
https://github.com/kubernetes/kubernetes/pull/96025
https://github.com/kubernetes/website/pull/23000
https://github.com/kubernetes/enhancements/pull/1621
https://github.com/kubernetes/test-infra/pull/14094

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/98142
https://github.com/kubernetes/kubernetes/issues/93064
https://github.com/kubernetes/kubernetes/issues/92766

[and more!](https://github.com/pulls?q=org%3Akubernetes+commenter%3Ahaircommander+)
- SIG projects I am involved with
sig-node

**Comment by dims** [comment]
+1 from me. Welcome!

**Comment by ehashman** [comment]
+1 from me too!!

**Comment by mrunalp** [comment]
:+1:

**Comment by rphillips** [comment]
+1 from me
/lgtm

**Comment by nikhita** [comment]
@haircommander thank you for all your contributions so far \o/

I've created PR #2479 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by haircommander** [comment]
thanks everyone :smile:
