### ISSUE TITLE
Use peribolos to manage team repo permissions

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/org#2465]
Peribolos supports defining which repos a given team should have which level of access to (ref: https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos#org-configuration)

Currently this is all done manually.  I think it would reduce our toil and make team permission changes more auditable if we drove this through our config files.

Some things to consider:
- the config looks like it only supports in-org assignments, do we need to support out-of-org assignments?
- we might want to consider adding a restrictions model to peribolos (similar to slack-infra), so that e.g. a team in a sub-folder can't arbitrarily give themselves kubernetes/kubernetes admin access

**Comment by nikhita** [comment]
> the config looks like it only supports in-org assignments, do we need to support out-of-org assignments?

Since GitHub teams are scoped to an org, I think it should be fine to just support in-org assignments.

> we might want to consider adding a restrictions model to peribolos (similar to slack-infra), so that e.g. a team in a sub-folder can't arbitrarily give themselves kubernetes/kubernetes admin access

Created https://github.com/kubernetes/org/pull/2614

**Comment by spiffxp** [comment]
/milestone v1.23
My read of https://github.com/kubernetes/org/pull/2614 is we need to consider putting in something akin to the restrictions we use for kubernetes-sigs/slack-infra and kubernetes/k8s.io/groups before we want to move forward with this
