### ISSUE TITLE
Rename default branch for kubernetes/org

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/org#2466]
Part of umbrella issue https://github.com/kubernetes/org/issues/2222

Issue to spec out and then run through renaming the default branch for this repository

- update pre/postsubmits to trigger on old branch name and new branch name
- determine whether periodics use default branch or have name hardcoded in git commands
  - if hardcoded, does attempting to checkout old name break?
- determine whether branch name is part of any job names
- determine if any docs need to be updated
- send notice
- rename branch (ref: https://github.com/github/renaming#renaming-existing-branches)
- if necessary, update periodics to refer to new branch name
- if necessary, rename jobs
- update branch protection config
- update jobs to only trigger on new branch name
- make sure things still work
  - keep an eye on ci and prs for a bit
  - trial the local development experience with pre-rename clone
- send notice

/sig contributor-experience
/area github-management
owns the repo
/sig testing
to discover any prow issues
/milestone v1.21
/priority important-soon
/assign @spiffxp 
I plan on working through this

**Comment by spiffxp** [comment]
prowjob configs:
- presubmits: don't explicitly mention master -> do nothing, should work fine post-rename
- postsubmits: trigger on master -> add main, remove master post-rename
- periodics: ci-org-peribolos uses pod-utils to explicitly clone master branch -> can we remove the branch reference up front? or will we need to update post-migration...
prowjob names:
- master isn't in their names
prowjob contents:
- kubernetes/org doesn't contain reference to 'master' in its codebase
prow configs:
- plugins:
  - slack: repo is mentioned explicitly, but branch name is not (actually no repo mentions it, so probably don't need to check going forward)
  - repo_milestone: repo is mentioned explicitly, but /milestone doesn't depend on branchnn
  - adding milestone_applier plugin config to see how it behaves w/o pre-emptive add of main branch: https://github.com/kubernetes/test-infra/pull/20664
- configs:
  - branch_protector: repo is mentioned explicitly, but branch name is not
docs:
  - cs.k8s.io shows some links with branch in their uri, but github should handle redirecting these post-rename

**Comment by spiffxp** [comment]
OK I'm going to click the button...
![Screen Shot 2021-01-29 at 2 31 22 PM](https://user-images.githubusercontent.com/49258/106318920-aa531c80-623e-11eb-9a8d-5c82ba73eb8d.png)

**Comment by justaugustus** [comment]
Do itttttt 🎉 ✨ 
/pony party

**Comment by spiffxp** [comment]
Pushed the button.

Slack alerter fired:
<img width="928" alt="Screen Shot 2021-01-29 at 2 40 19 PM" src="https://user-images.githubusercontent.com/49258/106319750-ea66cf00-623f-11eb-9ba3-d92b735fa808.png">

presubmits for open PRs and postsubmits were retriggered:
![Screen Shot 2021-01-29 at 2 40 50 PM](https://user-images.githubusercontent.com/49258/106319789-fd799f00-623f-11eb-9c2e-84a4dd9857c4.png)

visiting the repo via the website now shows a popup
![Screen Shot 2021-01-29 at 2 41 46 PM](https://user-images.githubusercontent.com/49258/106319899-1e41f480-6240-11eb-94a0-cb627653fdac.png)

**Comment by spiffxp** [comment]
Doing a PR via the UI already uses the correct branch name.  I happen to use `hub pull-request` a lot locally, let me see what that experience is like...

trying `hub pull-request` from a local copy of the repo that hasn't been updated at all:
```
$ hub pull-request
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "base"
```

trying git fetch from a local copy of the repo that hasn't been updated at all
```
$ git fetch origin master
fatal: couldn't find remote ref master
```

updated per their instructions
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

`hub pull-request` still not working...


Fetch origin as I usually do...
```
$ git fetch --prune origin
From github.com:kubernetes/org
 - [deleted]           (none)     -> origin/master
   (refs/remotes/origin/HEAD has become dangling)
```

dangling you say?
```
$ cat .git/refs/remotes/origin/HEAD
ref: refs/remotes/origin/master
```

let's update that
```
$ git remote set-head origin -a
origin/HEAD set to main
```

`hub pull-request` works now, yay

**Comment by spiffxp** [comment]
Sample PR to confirm things still work (without a post-rename PR yet): https://github.com/kubernetes/org/pull/2473

**Comment by mrbobbytables** [comment]
The pre/post submits getting re-triggered for smaller repos will probably be fine, but I fear what it'd do for k/k 😬

**Comment by spiffxp** [comment]
Yeah once I wrap this up I'd like to writeup where we got lucky and what we should watch out for to help choose other candidates and identify blockers/mitigations

**Comment by spiffxp** [comment]
Post-rename cleanup PR merged: https://github.com/kubernetes/test-infra/pull/20669

**Comment by spiffxp** [comment]
Notice sent to https://groups.google.com/g/kubernetes-dev/c/mKwxJW5z2Lk

**Comment by spiffxp** [comment]
Where we got lucky:
- few open PRs; we didn't have to mitigate a huge spike in CI load
- infrequent periodics; we didn't have to mitigate periodics breaking pre-rename or post-rename
- `master` not in job names; we didn't have to deal with status-context renames or loss of testgrid history
- jobs didn't explicitly reference 'master' in their code

Lessons learned:
- the only plugin config that explicitly lists `master` is milestone_applier - try adding both branches pre-rename
- the only prow config that explicitly lists `master` is branch-protection (for kubernetes/website)
- the branch rename looks like a delete/create via the API
- as expected, all presubmits/postsubmits get re-triggered

Some mitigations to consider:
- if we want periodics to support the idea of "use the default branch" so they don't need to be updated pre/post-rename...
  - pod-utils needs to be updated, currently requires hardcoded branch (ref: https://github.com/kubernetes/test-infra/issues/20667)
  - bootstrap needs to be updated, assumes `master` if branch omitted (ref: https://github.com/kubernetes/test-infra/issues/20672)
- prow can throttle how many of a given job can run with `max_concurrency`, but I suspect a large enough flood of pending jobs will timeout before they are all processed

**Comment by spiffxp** [comment]
I'm holding this open until we see the next run of https://testgrid.k8s.io/sig-contribex-org#ci-peribolos to confirm it's using the new branch

**Comment by spiffxp** [comment]
/close
Next run passed, confirmed using main https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-org-peribolos/1355356401299361792
