### ISSUE TITLE
REQUEST: New membership for KentaTada

### ISSUE THREAD

**Issue by KentaTada** [kubernetes/org#2467]
### GitHub Username
@KentaTada

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123
- @odinuge

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/system-validators/pull/20
https://github.com/kubernetes/system-validators/pull/19
https://github.com/kubernetes/system-validators/pull/13
https://github.com/kubernetes/system-validators/pull/12
(WIP) https://github.com/kubernetes/kubernetes/pull/90112

https://github.com/opencontainers/runc/pulls?q=is%3Apr+is%3Aclosed+author%3AKentaTada
https://github.com/opencontainers/runtime-spec/pulls?q=is%3Apr+is%3Aclosed+author%3AKentaTada
https://github.com/containerd/containerd/pulls?q=is%3Apr+is%3Aclosed+author%3AKentaTada
https://github.com/cri-o/cri-o/pulls?q=is%3Apr+is%3Aclosed+author%3AKentaTada
https://github.com/moby/moby/pulls?q=is%3Apr+is%3Aclosed+author%3AKentaTada
- Issues responded to
https://github.com/kubernetes/kubeadm/issues/2335
(WIP) https://github.com/kubernetes/system-validators/issues/21
- SIG projects I am involved with
https://github.com/kubernetes/system-validators

**Comment by neolit123** [comment]
+1 thanks for the contributions @KentaTada

**Comment by odinuge** [comment]
+1

Thanks for your contributions and insights! 👍

**Comment by nikhita** [comment]
@KentaTada thank you for all your contributions so far \o/

I've created PR #2479 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
