### ISSUE TITLE
Create new repo: kubernetes-sigs/work-api

### ISSUE THREAD

**Issue by pmorie** [kubernetes/org#2468]
### New Repo, Staging Repo, or migrate existing
New Repo

### Requested name for new repository
work-api

### Which Organization should it reside
e.g. kubernetes-sigs

### If not a staging repo, who should have admin access
pmorie, jeremyot, jqiu (qiujian16)

### If not a staging repo, who should have write access
pmorie, jeremyot, jqiu (qiujian16)

### If not a staging repo, who should be listed as approvers in OWNERS
pmorie, jeremyot, jqiu (qiujian16)

### If not a staging repo, who should be listed in SECURITY_CONTACTS
pmorie, jeremyot, jqiu (qiujian16)

### What should the repo description be
Kubernetes Work API

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject of sig-multicluster called work-api

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
This will hold design documents and implementation of the [Work API](https://docs.google.com/document/d/1cWcdB40pGg3KS1eSyb9Q6SIRvWVI8dEjFp9RI0Gk0vg/edit#)

**Comment by nikhita** [comment]
Considering this "approved" since @pmorie is a chair for SIG Multicluster

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/work-api

@qiujian16 is not a member of @kubernetes-sigs or @kubernetes GitHub orgs so they would need to [request for membership](https://github.com/kubernetes/community/blob/master/community-membership.md#member).

Also created:
- https://github.com/kubernetes/org/pull/2477 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/5452 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue. :+1:

**Comment by nikhita** [comment]
Teams have been granted access and all related PRs have merged. Closing.
