### ISSUE TITLE
REQUEST: New membership for <your-GH-handle>

### ISSUE THREAD

**Issue by shysank** [kubernetes/org#2470]
### GitHub Username
@shysank

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @CecileRobertMichon
- @nader-ziada 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+shysank
   https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+shysank
- Issues responded to
   https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues?q=is%3Aissue+shysank
   https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+shysank
- SIG projects I am involved with
  kubernetes-sigs/cluster-api
  kubernetes-sigs/cluster-api-provider-azure

**Comment by shysank** [comment]
I recently requested membership in #2455, but forgot to add @kubernetes-sigs which is where I do most of the work. Apologies for the confusion.

**Comment by nikhita** [comment]
@shysank since you are already a member of @kubernetes, you don't need sponsorship for @kubernetes-sigs. Feel free to create a PR to add yourself in here - https://github.com/kubernetes/org/blob/master/config/kubernetes-sigs/org.yaml :smile:

**Comment by shysank** [comment]
Ah, Thanks 🙏  I'll do that, and close this issue.

**Comment by shysank** [comment]
Closing this in favor of #2471
