### ISSUE TITLE
REQUEST: New membership for srikiz

### ISSUE THREAD

**Issue by srikiz** [kubernetes/org#2472]
### GitHub Username
@srikiz

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timoreimann
- @olemarkus 
- @rifelpet 

### List of contributions to the Kubernetes project
- PRs reviewed / authored - [35+](https://github.com/search?q=author%3Asrikiz+is%3Apr+org%3Akubernetes+org%3Akubernetes-sigs+org%3Akubernetes-csi+org%3Acncf)
- Issues responded to - [10+](https://github.com/search?q=commenter%3Asrikiz+-author%3Asrikiz+-reviewed-by%3Asrikiz+org%3Akubernetes+org%3Akubernetes-sigs+org%3Akubernetes-csi+org%3Acncf)
- SIG projects I am involved with: KOPS contributor

**Comment by olemarkus** [comment]
Thanks for all the contributions @srikiz!

+1 from me

**Comment by timoreimann** [comment]
Sri has been delivering improvements to kops and related projects continuously for a long time. Thanks for everything you have done, definitely +1 from my end!

**Comment by nikhita** [comment]
@srikiz All sponsors are required to be a part of at least one OWNERS file in the @kubernetes org. Unfortunately, due to this restriction, @timoreimann cannot act as a sponsor. :(

Can you please look for an additional sponsor to +1 here?

**Comment by srikiz** [comment]
Sure @nikhita, thanks. I will look for an additional sponsor.

**Comment by rifelpet** [comment]
Big +1 one from me, thanks for all of your contributions so far!

**Comment by palnabarun** [comment]
@srikiz, thank you for all your contributions so far :)

I've created PR #2484 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign

**Comment by cjmakwana** [comment]
Many congrats @srikiz for becoming a Kube family member !
