### ISSUE TITLE
REQUEST: New membership for azhao155

### ISSUE THREAD

**Issue by azhao155** [kubernetes/org#2474]
### GitHub Username
@azhao155

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @medyagh 
- @afbjorklund

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   https://github.com/kubernetes/minikube/pull/10118
   https://github.com/kubernetes/minikube/pull/10084
   https://github.com/kubernetes/minikube/pull/10053
   https://github.com/kubernetes/minikube/pull/10028
   https://github.com/kubernetes/minikube/pull/10027
   https://github.com/kubernetes/minikube/pull/10021

- Issues responded to
   https://github.com/kubernetes/minikube/issues/10107
   https://github.com/kubernetes/minikube/issues/10025
   https://github.com/kubernetes/minikube/issues/10015
   https://github.com/kubernetes/minikube/issues/9938
   https://github.com/kubernetes/minikube/issues/9399

- SIG projects I am involved with
   sig-cluster-lifecycle/minikube

**Comment by azhao155** [comment]
@medyagh 
@afbjorklund

**Comment by medyagh** [comment]
I sponsor @azhao155 he has done amazing work for minikube, fixed multiple bugs in minikube that required great persistence and amazing curiosity.

**Comment by afbjorklund** [comment]
I sponsor @azhao155 for minikube

**Comment by nikhita** [comment]
@azhao155 thank you for all your contributions so far \o/

I've created PR #2479 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
