### ISSUE TITLE
REQUEST: New membership for ydFu

### ISSUE THREAD

**Issue by ydFu** [kubernetes/org#2475]
### GitHub Username

@ydFu

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @tengqm
- @sftim

### List of contributions to the Kubernetes project

- PRs reviewed / authored:
  -  PRs authored(Get Merged):
[kubernetes/dashboard #5740](https://github.com/kubernetes/dashboard/pull/5740#event-4145982545)
[kubernetes/dashboard #5762](https://github.com/kubernetes/dashboard/pull/5762#event-4237884786)
[kubernetes/website #26213](https://github.com/kubernetes/website/pull/26213#event-4253684346)
[kubernetes/website #26239](https://github.com/kubernetes/website/pull/26239#event-4253232344)
[kubernetes/website #26237](https://github.com/kubernetes/website/pull/26237#event-4250674818)
[kubernetes/website #26245](https://github.com/kubernetes/website/pull/26245#event-4248973860)
[kubernetes/website #26245](https://github.com/kubernetes/website/pull/26245#event-4248973860)
[kubernetes/website #26235](https://github.com/kubernetes/website/pull/26235#event-4248821605)
[kubernetes/website #26232](https://github.com/kubernetes/website/pull/26232#event-4243537059)
[kubernetes/website #26212](https://github.com/kubernetes/website/pull/26212#issuecomment-766492231)
[kubernetes/website #26208](https://github.com/kubernetes/website/pull/26208#issuecomment-766492261)
[kubernetes/website #26219](https://github.com/kubernetes/website/pull/26219#event-4243259451)
[kubernetes/website #26220](https://github.com/kubernetes/website/pull/26220#event-4243147539)
[kubernetes/website #26195](https://github.com/kubernetes/website/pull/26195#event-4242496588)
[kubernetes/website #26210](https://github.com/kubernetes/website/pull/26210#event-4241652093)
[kubernetes/website #26211](https://github.com/kubernetes/website/pull/26211#event-4241442477)
[kubernetes/website #26200](https://github.com/kubernetes/website/pull/26200#event-4241192481)
[kubernetes/website #26193](https://github.com/kubernetes/website/pull/26193#event-4238650598)
[kubernetes/website #26186](https://github.com/kubernetes/website/pull/26186#event-4236502352)
[kubernetes/website #26165](https://github.com/kubernetes/website/pull/26165#event-4226894174)
[kubernetes/website #26020](https://github.com/kubernetes/website/pull/26020#event-4214732797)
[kubernetes/website #25899](https://github.com/kubernetes/website/pull/25899#event-4192170288)
[kubernetes/website #25871](https://github.com/kubernetes/website/pull/25871#event-4185489694)
[kubernetes/website #25969](https://github.com/kubernetes/website/pull/25969#event-4175769134)
[kubernetes/website #25948](https://github.com/kubernetes/website/pull/25948#event-4168372451)
[kubernetes/website #25891](https://github.com/kubernetes/website/pull/25891#event-4165908665)
[kubernetes/website #25873](https://github.com/kubernetes/website/pull/25873#event-4158019999)
[kubernetes/website #25824](https://github.com/kubernetes/website/pull/25824#event-4151980387)
[kubernetes/website #25820](https://github.com/kubernetes/website/pull/25820#event-4149606216)
    - PRs authored(Still Opened):
[kubernetes/website #25904](https://github.com/kubernetes/website/pull/25904#issuecomment-768818480)
[kubernetes/website #26248](https://github.com/kubernetes/website/pull/26248#pullrequestreview-576893571)
[kubernetes/dashboard #5779](https://github.com/kubernetes/dashboard/pull/5779#issuecomment-769059342)
    - PRs reviewed:
[kubernetes/website #26252](https://github.com/kubernetes/website/pull/26252#issuecomment-768863997)
[kubernetes/website #26257](https://github.com/kubernetes/website/pull/26257#issuecomment-768373910)
[kubernetes/website #26196](https://github.com/kubernetes/website/pull/26196#issuecomment-768565518)
[kubernetes/website #26225](https://github.com/kubernetes/website/pull/26225#pullrequestreview-577090800)
[kubernetes/website #26132](https://github.com/kubernetes/website/pull/26132#issuecomment-767968664)
[kubernetes/website #26236](https://github.com/kubernetes/website/pull/26236#event-4248828423)
[kubernetes/website #26201](https://github.com/kubernetes/website/pull/26201#event-4247727590)
[kubernetes/website #26141](https://github.com/kubernetes/website/pull/26141#issuecomment-766908170)
[kubernetes/website #25996](https://github.com/kubernetes/website/pull/25996#pullrequestreview-575313888)
[kubernetes/website #26022](https://github.com/kubernetes/website/pull/26022#event-4213516259)
[kubernetes/website #26023](https://github.com/kubernetes/website/pull/26023#event-4199224022)
[kubernetes/website #26273](https://github.com/kubernetes/website/pull/26273)
[kubernetes/website #26289](https://github.com/kubernetes/website/pull/26289#issuecomment-769861044)
[kubernetes/website #26256](https://github.com/kubernetes/website/pull/26256#pullrequestreview-578880471)
[kubernetes/website #26227](https://github.com/kubernetes/website/pull/26227#pullrequestreview-578385277)

- Issues responded to:
[kubernetes/website #26178](https://github.com/kubernetes/website/issues/26178)
[kubernetes/website #26177](https://github.com/kubernetes/website/issues/26177#issuecomment-767400616)
[kubernetes/website #25967](https://github.com/kubernetes/website/issues/25967#event-4214732799)
[kubernetes/website #26163](https://github.com/kubernetes/website/issues/26163#issuecomment-768267622)
[kubernetes/website #26234](https://github.com/kubernetes/website/issues/26234#issuecomment-767691184)

- SIG projects I am involved with
   kubernetes/website,kubernetes/dashboard  .

**Comment by tengqm** [comment]
+1  Looking forward to see more contributions from you.

**Comment by sftim** [comment]
+1 from me, too.

**Comment by ydFu** [comment]
Thanks for the help @tengqm , @sftim.

**Comment by nikhita** [comment]
@ydFu thank you for all your contributions so far \o/

I've created PR #2479 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
