### ISSUE TITLE
REQUEST: New membership for shekhar-rajak

### ISSUE THREAD

**Issue by shekhar-rajak** [kubernetes/org#2478]
### GitHub Username
@shekhar-rajak

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman
- @justaugustus

### List of contributions to the Kubernetes project
- PRs reviewed / authored: Merged PRs in : [kubernetes/enhancements ](https://github.com/kubernetes/enhancements/pulls?q=is%3Apr+is%3Amerged+author%3Ashekhar-rajak+) , [kubernetes/website](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ashekhar-rajak+is%3Aclosed)

- Issues responded to  [kubernetes/enhancements](https://github.com/kubernetes/enhancements/issues?q=is%3Aissue+shekhar-rajak+), [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/issues?q=+is%3Aissue+shekhar-rajak+)

- SIG projects I am involved with

kubernetes/enhancements

**Comment by parispittman** [comment]
So happy to have you and looking forward to future! 👍🏻 

lgtm!

**Comment by justaugustus** [comment]
Enthusiastically endorse @shekhar-rajak's membership!
He's been taking on a bunch of work to boost k/enhancements test coverage and convert older KEPs to the new directory format and I'm super appreciative!

/pony party

**Comment by nikhita** [comment]
@shekhar-rajak thank you for all your contributions so far \o/

I've created PR #2479 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
