### ISSUE TITLE
REQUEST: New membership for chymy

### ISSUE THREAD

**Issue by chymy** [kubernetes/org#2480]
### GitHub Username
@chymy

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123 
- @aojea 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Achymy
https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Achymy
https://github.com/kubernetes/community/pulls?q=is%3Apr+author%3Achymy
- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+commenter%3Achymy
- SIG projects I am involved with
kubernetes/kubernetes
kubernetes/website
kubernetes/community

**Comment by aojea** [comment]
+1
he was doing a great job cleaning some of the existing technical debt we have.

**Comment by neolit123** [comment]
+1

**Comment by palnabarun** [comment]
@chymy, thank you for all your contributions so far :)

I've created PR #2484 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
