### ISSUE TITLE
REQUEST: New membership for ayberk

### ISSUE THREAD

**Issue by ayberk** [kubernetes/org#2481]
### GitHub Username
@ayberk

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nckturner 
- @andrewsykim 

### List of contributions to the Kubernetes project
PRs reviewed / authored
- https://github.com/kubernetes/cloud-provider-aws/pull/160
- https://github.com/kubernetes/cloud-provider-aws/pull/167
- https://github.com/kubernetes/cloud-provider-aws/pull/165
- https://github.com/kubernetes/cloud-provider-aws/pull/157
- https://github.com/kubernetes/cloud-provider-aws/pull/149

SIG projects I am involved with
- kubernetes/cloud-provider-aws

**Comment by andrewsykim** [comment]
+1 thanks!

**Comment by nckturner** [comment]
+1

**Comment by palnabarun** [comment]
@ayberk, thank you for all your contributions so far :)

I've created PR #2484 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
