### ISSUE TITLE
REQUEST: New membership for chenxuc

### ISSUE THREAD

**Issue by chenxuc** [kubernetes/org#2483]
### GitHub Username
@chenxuc

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tengqm 
- @sftim 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/26363
https://github.com/kubernetes/website/pull/26332
https://github.com/kubernetes/website/pull/26316
https://github.com/kubernetes/website/pull/26333
https://github.com/kubernetes/website/pull/26283
https://github.com/kubernetes/website/pull/26257
https://github.com/kubernetes/website/pull/26252
https://github.com/kubernetes/website/pull/26250
https://github.com/kubernetes/website/pull/26236
https://github.com/kubernetes/website/pull/26158
https://github.com/kubernetes/website/pull/24442
https://github.com/kubernetes/website/pull/18073

- Issues responded to
https://github.com/kubernetes/website/issues/18055
https://github.com/kubernetes/website/issues/26177
https://github.com/kubernetes/website/issues/26178

- SIG projects I am involved with
kubernetes/website, kubernetes/kubernetes

**Comment by tengqm** [comment]
+1

Look forward to more contributions from you!

**Comment by sftim** [comment]
+1 from me too

**Comment by chenxuc** [comment]
Thanks a lot for your support!

**Comment by palnabarun** [comment]
@chenxuc, thank you for all your contributions so far :)

I've created PR #2484 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
