### ISSUE TITLE
REQUEST: New membership for bharath-123

### ISSUE THREAD

**Issue by bharath-123** [kubernetes/org#2485]
### GitHub Username
@bharath-123

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@hakman 
@rifelpet 
@olemarkus 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kops/pulls?q=is%3Apr+involves%3Abharath-123+
- Issues responded to
https://github.com/kubernetes/kops/issues?q=is%3Aissue+involves%3Abharath-123
- SIG projects I am involved with
kubernetes/kops

**Comment by olemarkus** [comment]
+1 thanks for all your work!

**Comment by hakman** [comment]
Big 👍 from me too!

**Comment by rifelpet** [comment]
Bonus +1 from me 👍🏻

**Comment by bharath-123** [comment]
Thank you!

**Comment by savitharaghunathan** [comment]
Hi, @bharath-123 👋 Thank you for all your contributions! 

I've created PR #2499 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
