### ISSUE TITLE
REQUEST: New membership for mcluseau

### ISSUE THREAD

**Issue by mcluseau** [kubernetes/org#2487]
### GitHub Username
@mcluseau

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [~] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [~] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @thockin 
- (at)saad-ali  if he accepts

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/issues/3760
- https://github.com/kubernetes/kubernetes/pull/9210
- https://github.com/kubernetes/kubernetes/pull/13628
- https://github.com/kubernetes/kubernetes/pull/22575
- https://github.com/kubernetes/kubernetes/pull/26926
- https://github.com/kubernetes/enhancements/issues/2104
- https://github.com/kubernetes/org/issues/2410#issuecomment-771372057

**Comment by mrbobbytables** [comment]
@mcluseau - Sponsors must be from separate organizations per the [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements). Both @thockin and @saad-ali are from Google. Is there someone else that can sponsor you?

**Comment by mcluseau** [comment]
I also worked with @chakri-nelluri but he doesn't seem to be in k8s org; with @childsb too; on the network side, @robscott but he's Google too. I had some good interactions with @dims too, and he seems to support the kpng initiative. Maybe @nikhita would support this request too as she requested it.

**Comment by chakri-nelluri** [comment]
I worked with Mikael and would highly recommend him from my side.

Thanks

**Comment by chakri-nelluri** [comment]
+ Saad.

Saad, if you remember @mikael.cluseau@gmail.com <mikael.cluseau@gmail.com> was
the one who worked on revamping the Flex volume code and has done an
stellar job. Please help me recommend him.

Thanks

**Comment by mcluseau** [comment]
Thanks Chakri :) (tagging @saad-ali as it seemed to be the intent)

**Comment by nikhita** [comment]
@saad-ali friendly ping on this :)

**Comment by rikatz** [comment]
+1 from me

Mikael is doing an amazing job with the evolution of kube-proxy and would love to see his efforts moving on :)

**Comment by dims** [comment]
+1 from me.

**Comment by savitharaghunathan** [comment]
Hi, @mcluseau 👋  Thank you for all your contributions!

I've created PR #2590 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
