### ISSUE TITLE
REQUEST: New membership for cynepco3hahue

### ISSUE THREAD

**Issue by cynepco3hahue** [kubernetes/org#2488]
### GitHub Username
@cynepco3hahue

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ehashman 
- @SergeyKanzhelev 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pull/91243
- https://github.com/kubernetes/kubernetes/pull/93328
- https://github.com/kubernetes/kubernetes/pull/95479
- https://github.com/kubernetes/kubernetes/pull/98019
- https://github.com/kubernetes/test-infra/pull/17066
- https://github.com/kubernetes/test-infra/pull/17634
- https://github.com/kubernetes/test-infra/pull/19643
- https://github.com/kubernetes/test-infra/pull/19868

**Comment by cynepco3hahue** [comment]
@ehashman @SergeyKanzhelev FYI

**Comment by SergeyKanzhelev** [comment]
Happy to sponsor @cynepco3hahue membership! Thank you for your contributions!

**Comment by ehashman** [comment]
:+1:

**Comment by savitharaghunathan** [comment]
Hi, @cynepco3hahue 👋 Thank you for all your contributions! 

I've created PR #2499 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by cynepco3hahue** [comment]
A lot of thanks!
