### ISSUE TITLE
kubernetes/sig-testing repo creation request

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/org#2490]
### New Repo, Staging Repo, or migrate existing

new repository

### Requested name for new repository

sig-testing

### Which Organization should it reside

kubernetes

### If not a staging repo, who should have admin access

myself, @spiffxp @stevekuznetsov (SIG leads)

### If not a staging repo, who should have write access

myself, @spiffxp @stevekuznetsov (SIG leads)

### If not a staging repo, who should be listed as approvers in OWNERS

myself, @spiffxp @stevekuznetsov (SIG leads)

### If not a staging repo, who should be listed in SECURITY_CONTACTS

myself, @spiffxp @stevekuznetsov (SIG leads)

### What should the repo description be

Home for SIG Testing discussion and documents.

### What SIG and subproject does this fall under in sigs.yaml

This is a SIG Testing meta repo, similar to https://github.com/kubernetes/sig-release, we'd like to try async github discussions here in particular.

Note: this is specifically NOT test-infra, which is a high noise mono-repo for infra tools, contributors should be able to "watch" this repo for SIG testing discussions.

### Approvals

Discussed today in SIG testing meeting (video to be uploaded ...), this issue will be forwarded to the mailinglist before moving forward.

EDIT: Mailinglist thread here https://groups.google.com/g/kubernetes-sig-testing/c/ciKOfIqFV3k
sig-arch approval - https://groups.google.com/g/kubernetes-sig-architecture/c/FD_DrHJ1rN0

### Additional context for request

We're looking to move to a more hybrid approach for SIG testing similar to what Contribex has trialed, however we'd like to give GitHub discussions a shot for things that might otherwise have been discussed in the zoom meeting previously, rather than slack threads (hopefully this can be more discoverable and can be higher signal-to-noise watched).

**Comment by dims** [comment]
+1 from me

**Comment by cblecker** [comment]
Would a repo be best? Or would github team discussions be a better fit?

I'm supportive of sig-testing blazing a trail here either way.

**Comment by BenTheElder** [comment]
I think we should go with a repo so we can also put a README for it etc., teams also seem to have poor (zero?) visibility to non-org members which seems problematic.

**Comment by tehcyx** [comment]
+1 from me. I'd like to explore this.

**Comment by cblecker** [comment]
> teams also seem to have poor (zero?) visibility to non-org members which seems problematic

That makes sense, although I'd love to validate this assumption so we could document it in future guidance.

Is there a reason for kubernetes vs k-sigs? (the former will require sig-arch approval)

**Comment by BenTheElder** [comment]
> That makes sense, although I'd love to validate this assumption so we could document it in future guidance.

I've just tested again that I can't visit a github teams page incognito, teams are only visible to people logged in and part of the org AFAICT.

> Is there a reason for kubernetes vs k-sigs? (the former will require sig-arch approval)

Just the existing pattern for easy naming really. Depending on how heavyweight the process is I don't mind asking, I think it's slightly clearer versus the subprojects in k-sigs but if it's going to require a KEP then no thanks ;-)

**Comment by BenTheElder** [comment]
https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams#team-visibility

> Visible teams can be viewed and @mentioned by every organization member.

So even if you configure visibility, they're only visible to org members. You can make them secret even within an org, but not public to the internet.

https://github.com/orgs/kubernetes/teams, https://github.com/orgs/kubernetes/teams/bash-firefighters bounce me to a login page when logged out.

**Comment by nikhita** [comment]
:+1: to this overall.

> This is a SIG Testing meta repo, similar to https://github.com/kubernetes/sig-release, we'd like to try async github discussions here in particular.

Out of curiosity, is this meant to be [GitHub Discussions](https://docs.github.com/en/discussions) (the GitHub feature) or using issues in the GitHub repo (like SIG Release does)?

**Comment by nikhita** [comment]
@BenTheElder since this is a repo in the @kubernetes GitHub org, can you send an email to the sig-arch mailing list about repo creation ?

@dims' +1 (https://github.com/kubernetes/org/issues/2490#issuecomment-776200564) is enough but would be great to continue the practice of sending a heads up to the mailing list :)

**Comment by BenTheElder** [comment]
Sorry the past week was full of surprises, I've gotten this forwarded to SIG Architecture now 😅

**Comment by derekwaynecarr** [comment]
+1 (as sig-arch co-chair)

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes/sig-testing

- @kubernetes/sig-testing-leads have admin access.
- created https://github.com/kubernetes/community/pull/5544 to add the repo to sigs.yaml
