### ISSUE TITLE
Rename Service APIs to Gateway API

### ISSUE THREAD

**Issue by robscott** [kubernetes/org#2492]
### New Repo, Staging Repo, or migrate existing
Migrate existing

### Requested name for new repository
gateway-api

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
service-apis-admins (rename to gateway-api-admins) - done in https://github.com/kubernetes/org/pull/2491/files

### If not a staging repo, who should have write access
service-apis-maintainers (rename to gateway-api-maintainers) - done in https://github.com/kubernetes/org/pull/2491/files

### If not a staging repo, who should be listed as approvers in OWNERS
No changes

### If not a staging repo, who should be listed in SECURITY_CONTACTS
No changes

### What should the repo description be
No changes

### What SIG and subproject does this fall under in sigs.yaml
sig-network

### Approvals
- Initially discussed in https://github.com/kubernetes-sigs/service-apis/issues/536
- Discussed at [Service APIs meetings on Jan 27 and Feb 3
](https://docs.google.com/document/d/1eg-YjOHaQ7UD28htdNxBR3zufebozXKyI28cl2E11tU/edit)
- Sent to sig-network mailing list https://groups.google.com/g/kubernetes-sig-network/c/5Rkg_juNDGc
- Discussed at [sig-network meeting on Feb 4
](https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit)
- PR to rename internal references: https://github.com/kubernetes-sigs/service-apis/pull/541

### Additional context for request
Also created https://github.com/kubernetes/community/pull/5483. Let me know if I can do anything else.

/cc @nikhita @thockin

**Comment by mrbobbytables** [comment]
All needed PRs have been merged, and the repo has been renamed
https://github.com/kubernetes-sigs/gateway-api 👍 

With that, I'm going to go ahead and close the issue out, if you have any issues, please feel free to reopen it.
Thanks!

/assign
/close
