### ISSUE TITLE
REQUEST: New membership for champtar

### ISSUE THREAD

**Issue by champtar** [kubernetes/org#2493]
### GitHub Username
@champtar

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @oomichi 
- @floryut

### List of contributions to the Kubernetes project
- PRs authored: 57 https://github.com/kubernetes-sigs/kubespray/pulls?q=is%3Apr+is%3Amerged+author%3Achamptar
- Issues / PRs where I'm involved: 141 https://github.com/kubernetes-sigs/kubespray/search?q=involves%3Achamptar
- SIG projects I am involved with: https://github.com/kubernetes-sigs/kubespray

**Comment by oomichi** [comment]
Thanks for your continuous contributions.

big +1

**Comment by floryut** [comment]
Impressive work from @champtar
Keep it up 

+1 without hesitation

**Comment by savitharaghunathan** [comment]
Hi, @champtar 👋 Thank you for all your contributions! 

I've created PR #2499 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
