### ISSUE TITLE
REQUEST: New membership for adrianchiris

### ISSUE THREAD

**Issue by adrianchiris** [kubernetes/org#2494]
### GitHub Username
@adrianchiris

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @marquiz
- @zvonkok

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/node-feature-discovery/pull/435
https://github.com/kubernetes-sigs/node-feature-discovery/pull/431
https://github.com/kubernetes-sigs/node-feature-discovery/pull/423
https://github.com/kubernetes-sigs/node-feature-discovery/pull/334
https://github.com/kubernetes-sigs/node-feature-discovery/pull/290
https://github.com/kubernetes-sigs/node-feature-discovery/pull/261

- Issues responded to
https://github.com/kubernetes-sigs/node-feature-discovery/issues/422
https://github.com/kubernetes-sigs/node-feature-discovery/issues/287

- SIG projects I am involved with
[node-feature-discovery](https://github.com/kubernetes-sigs/node-feature-discovery)

**Comment by zvonkok** [comment]
+1

**Comment by marquiz** [comment]
+1 👍

**Comment by savitharaghunathan** [comment]
Hi, @adrianchiris 👋 Thank you for all your contributions! 

I've created PR #2499 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by marquiz** [comment]
Welcome @adrianchiris !
