### ISSUE TITLE
REQUEST: New membership for perithompson

### ISSUE THREAD

**Issue by perithompson** [kubernetes/org#2495]
### GitHub Username
@perithompson

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@kubernetes
- @jsturtevant 
- @jayunit100

@kubernetes-sigs
- @jsturtevant 
- @codenrhoden  

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/website/pull/24884
  https://github.com/kubernetes/kubernetes/pull/96616
  https://github.com/kubernetes/website/pull/26465
  https://github.com/kubernetes-sigs/image-builder/pull/402
  https://github.com/kubernetes-sigs/image-builder/pull/439
  https://github.com/kubernetes-sigs/image-builder/pull/498
  https://github.com/kubernetes-sigs/image-builder/pull/491
  https://github.com/kubernetes-sigs/image-builder/pull/382
  https://github.com/kubernetes-sigs/image-builder/pull/442
  https://github.com/kubernetes-sigs/image-builder/pull/476

- Issues responded to
  https://github.com/kubernetes/kubernetes/issues/98680
  https://github.com/kubernetes/kubernetes/issues/98235
  https://github.com/kubernetes/kubernetes/issues/96512
  https://github.com/kubernetes-sigs/cluster-api/issues/2217
  
  
  
  
- SIG projects I am involved with
  https://github.com/kubernetes-sigs/image-builder
  https://github.com/kubernetes-sigs/cluster-api
  [SIG-Windows](https://github.com/orgs/kubernetes/projects/8)

**Comment by jsturtevant** [comment]
+1 thanks for all your contributions in sig-windows!

**Comment by jayunit100** [comment]
+1 approve !

**Comment by jayunit100** [comment]
thanks for everything!

**Comment by codenrhoden** [comment]
My approval isn't required since if you have `kubernetes` membership (which you already have two +1's for that from diff companies) you are implicitly granted `kubernetes-sigs` membership so long as it is requested. However....

+1! Well deserved, and thanks for you contributions in image-builder.

**Comment by savitharaghunathan** [comment]
Hi, @perithompson 👋 Thank you for all your contributions! 

I've created PR #2499 to add you to the @kubernetes & @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
