### ISSUE TITLE
REQUEST: New membership for lyzs90

### ISSUE THREAD

**Issue by lyzs90** [kubernetes/org#2496]
### GitHub Username
@lyzs90

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mm4tt 
- @shyamjvs 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/perf-tests/pulls?q=is%3Apr+author%3Alyzs90+
  - https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Alyzs90+
  - https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Alyzs90
- Issues responded to
  - https://github.com/kubernetes/perf-tests/issues/assigned/lyzs90
  - https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+assignee%3Alyzs90
- SIG projects I am involved with
  - SIG Scalability

**Comment by mm4tt** [comment]
+1, Shem is doing an amazing job in SIG Scalability. Thank you for all your contributions so far, I'm waiting for more :)

**Comment by shyamjvs** [comment]
+1 and thanks for your contributions!

**Comment by nikhita** [comment]
@lyzs90 thank you for all your contributions so far \o/

I've created PR #2503 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by lyzs90** [comment]
Thank you :)
