### ISSUE TITLE
Sig-leads and github teams

### ISSUE THREAD

**Issue by timothysc** [kubernetes/org#25]
### Organization or repository
kubernetes/*

### Users effected
https://github.com/orgs/kubernetes/teams?utf8=%E2%9C%93&query=cluster-lifecycle 

### Describe the issue
By definition, sig-leads should have maintainer rights to their teams.   

https://github.com/kubernetes/community/pull/2564 
is blocked by this and I can't consolidate the list 

/assign @cblecker 
/cc @roberthbailey

**Comment by cblecker** [comment]
Added! This will get way easier soon, when we have automation around team management
