### ISSUE TITLE
New membership for girikuncoro

### ISSUE THREAD

**Issue by girikuncoro** [kubernetes/org#250]
### GitHub Username
@girikuncoro

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @fanzhangio 
- @dixudx 
- @frapposelli 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/46756
https://github.com/kubernetes-incubator/kubespray/pull/2758
https://github.com/kubernetes-incubator/kubespray/pull/2744
https://github.com/kubernetes-incubator/kubespray/pull/2731
https://github.com/kubernetes/website/pull/8562
https://github.com/pmorie/go-open-service-broker-client/pull/95 (used by sig service catalog)
https://github.com/pmorie/go-open-service-broker-client/pull/100 (used by sig service catalog)

- Issues responded to
None

- SIG projects I am involved with
cluster-lifecycle (about to start), cli, service-catalog

/area github-membership

**Comment by dixudx** [comment]
+1

@girikuncoro Good works. Thanks.

**Comment by fanzhangio** [comment]
+1
Good job man! @girikuncoro

**Comment by mrbobbytables** [comment]
@girikuncoro Unfortunately @fanzhangio does not meet the [sponsorship requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).  A sponsor must be an approver/reviewer within the @kubernetes org. Do you happen to know  another person who could potentially sponsor you?

**Comment by girikuncoro** [comment]
@mrbobbytables I see, let me find around people first and come back here

**Comment by frapposelli** [comment]
+1
Great to see you making contributions to K8s Giri!

**Comment by girikuncoro** [comment]
@frapposelli thanks a lot fabio, looking forward to building something together in the community!

@mrbobbytables it's done, can you help again?

**Comment by mrbobbytables** [comment]
That should do it :) myself or @justaugustus will get a PR out the door within the next 24 hours or so with your Org membership (we try and batch membership changes if we can).

**Comment by cblecker** [comment]
Invite will be sent out as soon as #259 merges. Welcome to @kubernetes! 🚀
