### ISSUE TITLE
REQUEST: New membership for danpopsd

### ISSUE THREAD

**Issue by danpopSD** [kubernetes/org#2500]
### GitHub Username
@danpopsd

### Organization you are requesting membership in
kubernetes
### Requirements
- [ X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X ] I am actively contributing to 1 or more Kubernetes subprojects
- [X ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@mrbobbytables 
@castrojo 

### List of contributions to the Kubernetes project
- Community /Contribex
- Hosted Community Meeting
- docs PR's  https://github.com/kubernetes/website/pull/17914

**Comment by mrbobbytables** [comment]
+1 @danpopSD has been helping with our events like the Contributor Celebration, Office hours and more :)

**Comment by detiber** [comment]
It's about damn time!

**Comment by castrojo** [comment]
+1, I'm working with Dan to transition some of my contribex tasks to him, he's doing a great job and has already been helping with contributor celebration and other multimedia efforts in the SIG.

**Comment by justaugustus** [comment]
Enthusiastic +1 to POP's membership!

Is `/pop` a thing yet? Probably not, but for now:
/honk
/pony party

**Comment by sethmccombs** [comment]
Let's gooooooooo!!

Also retry - 
/pony

**Comment by dims** [comment]
+1 from me. welcome!

**Comment by nikhita** [comment]
@danpopSD thank you for all your contributions so far \o/

I've created PR #2503 to add you to the Kubernetes. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
