### ISSUE TITLE
REQUEST: New membership for aravindhp

### ISSUE THREAD

**Issue by aravindhp** [kubernetes/org#2501]
### GitHub Username
@aravindhp

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jayunit100 
- @ddebroy

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/enhancements/pull/2271
  https://github.com/kubernetes/kubernetes/pull/96120
  https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1035
  https://github.com/kubernetes-sigs/sig-windows-tools/pull/113
  https://github.com/kubernetes/kubernetes/pull/97764
  https://github.com/kubernetes/website/pull/26486

- Issues responded to
  https://github.com/kubernetes/enhancements/issues/2258
  https://github.com/kubernetes/kubernetes/issues/98704

- SIG projects I am involved with
  [sig-windows](https://github.com/orgs/kubernetes/projects/8)

**Comment by jayunit100** [comment]
Approve - @aravindhp has helped us alot with organizing various bits of the windows initiative and sharing lessons from upstream openshift !!!!   

/approve

**Comment by ddebroy** [comment]
I strongly support for @aravindhp 's membership request. He has been a solid contributor to different aspects of Kubernetes through SIG Windows.
/approve

**Comment by nikhita** [comment]
@aravindhp thank you for all your contributions so far \o/

I've created PR #2503 to add you to the Kubernetes and Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! 🎉

/assign

**Comment by aravindhp** [comment]
Thank you @nikhita @ddebroy @jayunit100
