### ISSUE TITLE
Netlify site request for Gateway API

### ISSUE THREAD

**Issue by robscott** [kubernetes/org#2506]
### Repository
kubernetes-sigs/gateway-api

### Project domain
gateway-api.sigs.k8s.io

### Additional context for request
Making subdomain request at same time as Netlify request, not sure on the proper order of operations here but would love to have both enabled soon.

**Comment by mrbobbytables** [comment]
Netlify has been enabled for the repo, the current url is available here:
https://kubernetes-sigs-gateway-api.netlify.app

Once dns is configured and a netlify.toml file present, can finish the setup.

**Comment by robscott** [comment]
Thanks for all the help @mrbobbytables! I think this is all complete now.

/close
