### ISSUE TITLE
REQUEST: New membership for yuga711

### ISSUE THREAD

**Issue by yuga711** [kubernetes/org#2507]
### GitHub Username
@yuga711

### Organization you are requesting membership in
@kubernetes
@kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gnufied 
- @msau42 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
     - https://github.com/kubernetes/kubernetes/pull/96617
     -  https://github.com/kubernetes/kubernetes/pull/91307
     - https://github.com/kubernetes/kubernetes/pull/96689
     - https://github.com/kubernetes/kubernetes/pull/97584
     - https://github.com/kubernetes/kubernetes/pull/97499
     - https://github.com/kubernetes/kubernetes/pull/96224
     - https://github.com/kubernetes/kubernetes/pull/95770
     - https://github.com/kubernetes/kubernetes/pull/95447
     - https://github.com/kubernetes-csi/external-attacher/pull/244
     - https://github.com/kubernetes-csi/csi-test/pull/280
     - https://github.com/kubernetes/kubernetes/pull/89845
     - https://github.com/kubernetes/kubernetes/pull/88602
- Issues authored 
   - https://github.com/kubernetes/kubernetes/issues/94912
   - https://github.com/kubernetes/kubernetes/issues/91784
   - https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/618
   - https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/654
- Issues responded to
   - https://github.com/kubernetes/kubernetes/issues/80488
   - https://github.com/kubernetes/kubernetes/issues/94912
   - https://github.com/kubernetes/kubernetes/issues/95600
   - https://github.com/kubernetes/kubernetes/issues/86281
   - https://github.com/kubernetes/kubernetes/issues/84169
   - https://github.com/kubernetes-csi/external-attacher/issues/243  
- SIG projects I am involved with
    - https://github.com/kubernetes-csi/external-attacher
    - https://github.com/kubernetes-csi/external-snapshotter
    - https://github.com/kubernetes-sigs/vsphere-csi-driver
    - https://github.com/kubernetes-csi/csi-test

**Comment by msau42** [comment]
+1 Jay has been looking into some tricky issues around volume attachment.

@yuga711 can you also modify the request to also be a member of kubernetes-csi? I think we can cover both as part of this.

**Comment by gnufied** [comment]
+1

**Comment by yuga711** [comment]
Thanks Michelle and Hemant. I added kubernetes-csi as well.

**Comment by nikhita** [comment]
@yuga711 thank you for all your contributions so far \o/

I've created PR #2513 to add you to the Kubernetes and Kubernetes CSI Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-csi! 🎉

/assign
