### ISSUE TITLE
REQUEST: New membership for dgrisonnet

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes/org#2508]
### GitHub Username
@dgrisonnet

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lilic 
- @serathius 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/92542
  - https://github.com/kubernetes/kubernetes/pull/96421
  - metrics-server: 
    - 6 PRs authored: https://github.com/kubernetes-sigs/metrics-server/pulls?q=is%3Apr+author%3Adgrisonnet 
    - 14 PRs reviewed: https://github.com/kubernetes-sigs/metrics-server/pulls?q=is%3Apr+commenter%3Adgrisonnet+-author%3Adgrisonnet
  - kube-state-metrics:
    - 5 PRs authored: https://github.com/kubernetes/kube-state-metrics/pulls?q=is%3Apr+author%3Adgrisonnet
    - 8 PRs reviewed: https://github.com/kubernetes/kube-state-metrics/pulls?q=is%3Apr+commenter%3Adgrisonnet+-author%3Adgrisonnet
  - custom-metrics-apiserver:
    - 5 PRs authored: https://github.com/kubernetes-sigs/custom-metrics-apiserver/pulls?q=is%3Apr+author%3Adgrisonnet
    - 3 PRs reviewed: https://github.com/kubernetes-sigs/custom-metrics-apiserver/pulls?q=is%3Apr+commenter%3Adgrisonnet+-author%3Adgrisonnet
  - prometheus-adapter:
    - 4 PRs authored: https://github.com/kubernetes-sigs/prometheus-adapter/pulls?q=is%3Apr+author%3Adgrisonnet 
    - 6 PRs reviewed: https://github.com/kubernetes-sigs/prometheus-adapter/pulls?q=is%3Apr+commenter%3Adgrisonnet+-author%3Adgrisonnet
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/92500
  - https://github.com/kubernetes/kubernetes/issues/95115 
  - 24 issues in prometheus-adapter: https://github.com/kubernetes-sigs/prometheus-adapter/issues?q=is%3Aissue+commenter%3Adgrisonnet 
  - 11 issues in kube-state-metrics: https://github.com/kubernetes/kube-state-metrics/issues?q=is%3Aissue+commenter%3Adgrisonnet 
  - 7 issues in metrics-server: https://github.com/kubernetes-sigs/metrics-server/issues?q=is%3Aissue+commenter%3Adgrisonnet
  - 2 issues in custom-metrics-apiserver: https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues?q=is%3Aissue+commenter%3Adgrisonnet 
- SIG projects I am involved with
  - sig-instrumentation
  - https://github.com/kubernetes/kube-state-metrics
  - https://github.com/kubernetes-sigs/metrics-server
  - https://github.com/kubernetes-sigs/custom-metrics-apiserver
  - https://github.com/kubernetes-sigs/prometheus-adapter

**Comment by lilic** [comment]
+100 I strongly support this!

Thank you Damien for all the work you have been doing for kube-state-metrics in numerous PRs and issues you answered as well as for the prometheus-adapter. Looking forward to future things to come!! 🎉

**Comment by s-urbaniak** [comment]
100% support from my side as well! :tada:

**Comment by sttts** [comment]
+100

**Comment by serathius** [comment]
/lgtm
Thanks for your work on Metrics Server.

**Comment by nikhita** [comment]
@dgrisonnet This is one of the best membership requests I've seen in a while. Thanks for adding details and formatting it so cleanly! :raised_hands: 

Also, sponsorships look good. You'll get added to the GitHub orgs when the next round of membership requests are processed. :)

**Comment by nikhita** [comment]
@dgrisonnet thank you for all your contributions so far \o/

I've created PR #2513 to add you to the Kubernetes and Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! 🎉

/assign
