### ISSUE TITLE
REQUEST: New membership for erain

### ISSUE THREAD

**Issue by erain** [kubernetes/org#2511]
### GitHub Username
@erain 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ehashman 
- @logicalhan

### List of contributions to the Kubernetes project
- PRs reviewed / authored: [link](https://github.com/search?q=author%3Aerain+repo%3Akubernetes%2Fkubernetes&type=commits)
- Issues responded to: [link](https://github.com/search?q=author%3Aerain+repo%3Akubernetes%2Fkubernetes&type=issues)
- SIG projects I am involved with: I am actively in SIG Instrumentation, and also contributed to related projects e.g. logging agents used in Kubernetes ([PRs and Issues in fluent/fluent-bit](https://github.com/search?q=author%3Aerain+repo%3Afluent%2Ffluent-bit&type=commits))

**Comment by ehashman** [comment]
:+1:

**Comment by nikhita** [comment]
@erain thank you for all your contributions so far \o/

I've created PR #2513 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
