### ISSUE TITLE
REQUEST: New membership for edreed

### ISSUE THREAD

**Issue by edreed** [kubernetes/org#2512]
### GitHub Username

@edreed

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andyzhangx 
- @xing-yang 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=org%3Akubernetes-sigs+edreed&type=commits

- Issues responded to
https://github.com/search?q=org%3Akubernetes-sigs+edreed&type=issues

- SIG projects I am involved with
sig-storage

**Comment by andyzhangx** [comment]
+1

**Comment by xing-yang** [comment]
Hi @edreed, thanks for your contributions!  I'm happy to sponsor you to join the kubernetes-sigs org.

I see that you've made contributions in kubernetes-sigs, but I don't see anything under kubernetes org.  Would you mind join kubernetes-sigs org now and apply for kubernetes org in the future after you've made some contributions there?

**Comment by edreed** [comment]
@xing-yang Ah, my apologies for the overreach. I've dropped the request to join kubernetes org and will look for opportunities to contribute to and join the broader org at a later time.

**Comment by nikhita** [comment]
@edreed thank you for all your contributions so far \o/

I've created PR #2513 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
