### ISSUE TITLE
REQUEST: New membership for prezha

### ISSUE THREAD

**Issue by prezha** [kubernetes/org#2514]
### GitHub Username
@prezha

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sharifelgamal
- @medyagh
- @afbjorklund

### List of contributions to the Kubernetes project
- PRs reviewed / authored
kubernetes/minikube#10479
kubernetes/minikube#10439
kubernetes/minikube#10424
kubernetes/minikube#10411
kubernetes/minikube#10369
kubernetes/minikube#9912
kubernetes/minikube#9853
kubernetes/minikube#9852
kubernetes/minikube#9781
kubernetes/minikube#9726
kubernetes/minikube#9713
kubernetes/minikube#9708
kubernetes/minikube#9641
kubernetes/minikube#9632
kubernetes/minikube#9614
kubernetes/minikube#9597
kubernetes/minikube#9592
kubernetes/minikube#9542
kubernetes/minikube#9540
kubernetes/minikube#9532
kubernetes/minikube#9531
kubernetes/minikube#9529
kubernetes/minikube#9506
kubernetes/minikube#9487
kubernetes/minikube#9480
kubernetes/minikube#9464
kubernetes/minikube#9439
kubernetes/minikube#9414
kubernetes/minikube#9390
kubernetes/minikube#9384
kubernetes/minikube#9298
kubernetes/minikube#9281
kubernetes/minikube#9280

- Issues responded to
kubernetes/minikube#10471
kubernetes/minikube#10040
kubernetes/minikube#9938
kubernetes/minikube#9305
kubernetes/minikube#9156
kubernetes/minikube#3327

- SIG projects I am involved with
sig-cluster-lifecycle/minikube

**Comment by sharifelgamal** [comment]
I'll sponsor @prezha

**Comment by medyagh** [comment]
I happily support @prezha to be in k8s org, he has done amazing contributions to minikube

**Comment by afbjorklund** [comment]
I sponsor @prezha for minikube

**Comment by nikhita** [comment]
@prezha thank you for all your contributions so far \o/

I've created PR #2530 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by prezha** [comment]
thank you @sharifelgamal , @medyagh , @afbjorklund and @nikhita !
