### ISSUE TITLE
REQUEST: New membership for jailton

### ISSUE THREAD

**Issue by jailton** [kubernetes/org#2515]
### GitHub Username
@jailton

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jcjesus
- @femrtnz

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - kubernetes/website#26006
  - kubernetes/website#26207
  - kubernetes/website#26388
  - kubernetes/website#26440
  - kubernetes/website#26487
  - kubernetes/website#26556
  - kubernetes/website#26631
  - kubernetes/website#26644
  - kubernetes/website#26645
  - kubernetes/website#26646
  - kubernetes/website#26659

- Issues responded to
  - kubernetes/website#13939
  - kubernetes/website#26640
  - kubernetes/website#26628
  - kubernetes/website#26563
  - kubernetes/website#26457
  - kubernetes/website#26636

- SIG projects I am involved with
sig-docs

**Comment by jcjesus** [comment]
Welcome to the team @jailton!
Thank you for your contribution.
/approved

**Comment by devlware** [comment]
Welcome aboard @jailton!

**Comment by nikhita** [comment]
@jailton thank you for all your contributions so far \o/

I've created PR #2530 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
