### ISSUE TITLE
New repository for hierarchical-namespaces under kubernetes-sigs

### ISSUE THREAD

**Issue by rjbez17** [kubernetes/org#2516]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
hierarchical-namespaces

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
- rjbez17
- srampal
- tashimi
- adrianludwin

### If not a staging repo, who should have write access
- yiqigao217
- GinnyJI

### If not a staging repo, who should be listed as approvers in OWNERS
- rjbez17
- srampal
- tashimi
- adrianludwin

### If not a staging repo, who should be listed in SECURITY_CONTACTS
- rjbez17
- adrianludwin

### What should the repo description be
created due to https://github.com/kubernetes/enhancements/issues/1687

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject for sig-auth called hierarchical-namespace-controller

### Approvals
The KEP has been approved for implementation passing a code review and security review: 

https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/1687-hierarchical-namespaces-subproject

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

**Comment by mikedanese** [comment]
Final announcement was in sig-auth January 9th meeting.

/approve

**Comment by mikedanese** [comment]
cc @enj @tallclair

**Comment by nikhita** [comment]
/assign

Repo has been created - https://github.com/kubernetes-sigs/hierarchical-namespaces

Also created:
- https://github.com/kubernetes/org/pull/2518 - GitHub teams to grant access
- https://github.com/kubernetes/community/pull/5550 - to add the repo to sigs.yaml

**Comment by spiffxp** [comment]
Awaiting approval/merge of https://github.com/kubernetes/community/pull/5550

**Comment by mikedanese** [comment]
kubernetes/community#5550 is approved but needs rebase.
