### ISSUE TITLE
REQUEST: New membership for joadavis-g

### ISSUE THREAD

**Issue by joadavis-g** [kubernetes/org#2519]
### GitHub Username
@joadavis-g

### Organization you are requesting membership in
@kubernetes
sig-instrumentation

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ehashman 
- @logicalhan 

### List of contributions to the Kubernetes project
- sig-instrumentation

**Comment by ehashman** [comment]
Enthusiastic :+1:, @joadavis-g has been regularly attending SIG Instrumentation meetings and contributing for the past year.

**Comment by ehashman** [comment]
Note: Joe's contributions have previously been on a different GH account @joadavis, not sure what the procedure is for this.

https://github.com/pulls?q=org%3Akubernetes+commenter%3Ajoadavis

**Comment by joadavis-g** [comment]
(I wasn't sure either. I created a new account to help separate the change in employer.)

**Comment by ehashman** [comment]
@joadavis-g typically, most people don't make a new account, but they update their affiliations in CNCF/gitdm. e.g. for myself: https://github.com/cncf/gitdm/blob/f4f9700c3695a2051f1e8052acacc58d5fab70ce/developers_affiliations2.txt#L10242-L10244

**Comment by logicalhan** [comment]
+1

**Comment by nikhita** [comment]
> Note: Joe's contributions have previously been on a different GH account @joadavis, not sure what the procedure is for this.

This should be fine as long as they are the same person :smile: 


@joadavis-g thank you for all your contributions so far \o/

I've created PR #2530 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
