### ISSUE TITLE
REQUEST: New membership for rficcaglia for @kubernetes-sigs

### ISSUE THREAD

**Issue by rficcaglia** [kubernetes/org#2520]
### GitHub Username
@rficcaglia 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @JimBugwadia
- (at)sponsor-2

### List of contributions to the Kubernetes project
- Issues: kubernetes/kubernetes#75554
- SIG projects I am involved with: [wg-policy-protoypes](https://github.com/kubernetes-sigs/wg-policy-prototypes)

**Comment by nikhita** [comment]
@rficcaglia you don't need a sponsor because you are already part of the @kubernetes org :)

I've created PR #2530 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
