### ISSUE TITLE
Request to Archive repo 

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/org#2525]
### Repository to archive
https://github.com/kubernetes/utils/mount

### Repository and/or sig subproject owners that are approving this archival
sig-storage

### When should this be done
The only component under k/k that is dependent on this repo is 'cadvisor'.
the 'cadvisor' code is updated  in the pr https://github.com/google/cadvisor/pull/2782 and the code will be merged into k/k and the end of the current release cycle for kubernetes 1.21 release. 
Once the 'cadvisor' is pulled into k/k, PR https://github.com/kubernetes/kubernetes/pull/96130 will take out the dependency on the repo  "https://github.com/kubernetes/utils/mount" and we do not need that repo after that.

### Additional context for request
The repo is moved under k/k staging, please find additional details below.
https://github.com/kubernetes/org/issues/1887

ping @saad-ali @xing-yang @dims

**Comment by brahmaroutu** [comment]
ping @msau42

**Comment by dims** [comment]
+1 from me.

**Comment by msau42** [comment]
Since this is package under the kubernetes/util repo, I don't think we can actually archive this repo right? I think the best we can do is delete the package?

**Comment by nikhita** [comment]
> Since this is package under the kubernetes/util repo, I don't think we can actually archive this repo right? I think the best we can do is delete the package?

Yes, this would involving removing the package (https://github.com/kubernetes/utils/tree/master/mount), not archiving the entire kubernetes/util repo.

Closing, but please reopen if I'm missing something here!
