### ISSUE TITLE
Retiring kubernetes-sigs/mutating-trace-admission-controller

### ISSUE THREAD

**Issue by ehashman** [kubernetes/org#2527]
### Repository to archive

https://github.com/kubernetes-sigs/mutating-trace-admission-controller

### Repository and/or sig subproject owners that are approving this archival

@ehashman 
@logicalhan 
SIG Instrumentation Chairs

Project is a [SIG Instrumentation subproject](https://github.com/kubernetes/community/tree/master/sig-instrumentation#mutating-trace-admission-controller) but has been inactive for over a year.

### When should this be done

Anytime.

### Additional context for request

We identified that this repo is inactive/unmaintained during our annual report review.

cc @Monkeyanator @calebamiles (project contributors)

**Comment by logicalhan** [comment]
Thanks!

**Comment by nikhita** [comment]
/assign

Repo has been archived: https://github.com/kubernetes-retired/mutating-trace-admission-controller

Also sent a note to k-dev ML: https://groups.google.com/g/kubernetes-dev/c/mcKakH5CeLY

- We can remove the repo from sigs.yaml in https://github.com/kubernetes/community/pull/5567
- Created https://github.com/kubernetes/org/pull/2529 to remove the GitHub teams.

Once both PRs merge, we can close this issue.

**Comment by spiffxp** [comment]
Awaiting resolution of https://github.com/kubernetes/community/pull/5567#discussion_r585899387
