### ISSUE TITLE
REQUEST: New membership for nearora-msft

### ISSUE THREAD

**Issue by nearora-msft** [kubernetes/org#2533]
### GitHub Username
@nearora-msft

### Organization you are requesting membership in
@kubernetes-sigs, @kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andyzhangx 
- @msau42 
- @Jiawei0227 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/search?q=org%3Akubernetes-csi+nearora-msft&type=commits
  https://github.com/search?q=org%3Akubernetes-sigs+nearora-msft&type=commits

- Issues responded to
  https://github.com/search?q=org%3Akubernetes-csi+nearora-msft&type=issues
  https://github.com/search?q=org%3Akubernetes-sigs+nearora-msft&type=issues
 

- SIG projects I am involved with
   sig-storage

**Comment by Jiawei0227** [comment]
I am not sure I have the permission to approve but @nearora-msft has been doing some great work on kubernetes-csi for csi sidecars.

**Comment by andyzhangx** [comment]
> I am not sure I have the permission to approve but @nearora-msft has been doing some great work on kubernetes-csi for csi sidecars.

@jiawei0227 you need need to type `+1` in new comment.

**Comment by Jiawei0227** [comment]
+1

**Comment by nikhita** [comment]
@nearora-msft thank you for all your contributions so far \o/

I've created PR #2537 to add you to the Kubernetes SIGs and Kubernetes CSI Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs and @kubernetes-csi! 🎉

/assign
