### ISSUE TITLE
REQUEST: New membership for tanjing2020

### ISSUE THREAD

**Issue by tanjing2020** [kubernetes/org#2536]
### GitHub Username
@tanjing2020

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@chendave
@gavinfish

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/99671
https://github.com/kubernetes/kubernetes/pull/99389
https://github.com/kubernetes/kubernetes/pull/99246
https://github.com/kubernetes/kubernetes/pull/98875
https://github.com/kubernetes/kubernetes/pull/98518
https://github.com/kubernetes/kubernetes/pull/98453
https://github.com/kubernetes/kubernetes/pull/98358
https://github.com/kubernetes/kubernetes/pull/98259
https://github.com/kubernetes/kubernetes/pull/98134
https://github.com/kubernetes/kubernetes/pull/97224
https://github.com/kubernetes/kubernetes/pull/96599

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/98660
https://github.com/kubernetes/kubernetes/issues/99306

- SIG projects I am involved with
sig-scheduling

**Comment by chendave** [comment]
+1

**Comment by gavinfish** [comment]
+1

**Comment by ahg-g** [comment]
+1, thanks for your contributions to sig scheduling so far.

**Comment by nikhita** [comment]
@tanjing2020 thank you for all your contributions so far \o/

I've created PR #2546 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
