### ISSUE TITLE
Release tooling repo migrations: release-sdk and release-utils

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#2539]
### New Repo, Staging Repo, or migrate existing

Migrate existing:
- https://github.com/justaugustus/release-sdk
- https://github.com/justaugustus/release-utils

### Requested name for new repository

- release-sdk
- release-utils

### Which Organization should it reside

kubernetes-sigs

### If not a staging repo, who should have admin access

@kubernetes/sig-release-admins 

### If not a staging repo, who should have write access

@kubernetes/sig-release-admins 

### If not a staging repo, who should be listed as approvers in OWNERS

@kubernetes/sig-release-admins 

### If not a staging repo, who should be listed in SECURITY_CONTACTS

@kubernetes/sig-release-admins 

### What should the repo description be
by default we will set it to "created due to (link to this issue)"

### What SIG and subproject does this fall under in sigs.yaml

Release Engineering subproject of SIG Release

### Approvals

Tagging other @kubernetes/sig-release-leads for approval

### Additional context for request

https://github.com/kubernetes/release/pull/1934

/assign @mrbobbytables @nikhita

**Comment by saschagrunert** [comment]
+1

**Comment by justaugustus** [comment]
Donation PRs:
- https://github.com/justaugustus/release-sdk/pull/1
- https://github.com/justaugustus/release-utils/pull/2

**Comment by hasheddan** [comment]
+1

**Comment by mrbobbytables** [comment]
Repos have been migrated
- https://github.com/kubernetes/org/pull/2540 - teams
- https://github.com/kubernetes/community/pull/5591 - updating subproject

**Comment by mrbobbytables** [comment]
all PRs have merged, teams have been granted permission to the repos. Everything should be good! 👍 

/close

**Comment by justaugustus** [comment]
Thanks Bob!
