### ISSUE TITLE
REQUEST: New membership for MarcelMue

### ISSUE THREAD

**Issue by MarcelMue** [kubernetes/org#2542]
### GitHub Username
@MarcelMue

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @njuettner (same org)
- @puja108 (same org)
- @JoelSpeed
- @CecileRobertMichon 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=org%3Akubernetes-sigs+MarcelMue&type=commits

- Issues responded to
https://github.com/search?q=org%3Akubernetes-sigs+MarcelMue&type=issues

- SIG projects I am involved with
  cluster-api

**Comment by puja108** [comment]
+1 Happy to sponsor Marcel. He's been involving himself deeply recently and has a CAPI presentation in the maintainers track for upcoming KubeCon lined up.

**Comment by MarcelMue** [comment]
Added more sponsors to fulfil `Sponsors must be from multiple member companies to demonstrate integration across community.` properly :)

**Comment by JoelSpeed** [comment]
+1 from me. Marcel is helping us to implement the new CAPI operator project and will in the long term be an owner of the subproject

**Comment by CecileRobertMichon** [comment]
+1 from me as well

**Comment by njuettner** [comment]
+1 from me 🤗

**Comment by nikhita** [comment]
@MarcelMue thank you for all your contributions so far \o/

I've created PR #2550 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
