### ISSUE TITLE
Migrate contributor-site from kubernetes-sigs to kubernetes org

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/org#2544]
### New Repo, Staging Repo, or migrate existing

Migrate [The Contributor Site repo](https://github.com/kubernetes-sigs/contributor-site) from kubernetes-sigs to kubernetes

### Requested name for new repository

contributor-site

### Which Organization should it reside

kubernetes

### If not a staging repo, who should have admin access

Migrate existing team

### If not a staging repo, who should have write access

Migrate existing team

### If not a staging repo, who should be listed as approvers in OWNERS

Leave as is

### If not a staging repo, who should be listed in SECURITY_CONTACTS

Leave as is

### What should the repo description be

Leave as is

### What SIG and subproject does this fall under in sigs.yaml

https://github.com/kubernetes/community/tree/master/sig-contributor-experience#contributors-documentation

### Approvals

SIG Arch mailing list thread: https://groups.google.com/g/kubernetes-sig-architecture/c/FYmPPdMNq8w/m/RIhCXA88DQAJ

---

/assign

**Comment by mrbobbytables** [comment]
Repo has been migrated, once these two PRs have merged and teams re-added, this issue can be closed:
- https://github.com/kubernetes/community/pull/5606
- https://github.com/kubernetes/org/pull/2545

**Comment by nikhita** [comment]
All PRs have merged. Closing.
