### ISSUE TITLE
REQUEST: New membership for alexander-demichev

### ISSUE THREAD

**Issue by alexander-demichev** [kubernetes/org#2547]
### GitHub Username
alexander-demichev

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @JoelSpeed
- @fabriziopandini 

### List of contributions to the Kubernetes project
https://github.com/kubernetes-sigs/cluster-api/pull/2525
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1730
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/655
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/300
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1878
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1926
https://github.com/kubernetes-sigs/cluster-api/pull/3668
https://github.com/kubernetes-sigs/cluster-api/pull/3817
https://github.com/kubernetes-sigs/cluster-api/pull/4164
https://github.com/kubernetes-sigs/cluster-api/issues/3504
https://github.com/kubernetes-sigs/cluster-api/issues/4271
https://github.com/kubernetes-sigs/cluster-api/issues/4270

**Comment by JoelSpeed** [comment]
+1 from me! Alex is starting to get heavily involved in the cluster api project with his contributions to the cluster api operator

**Comment by elmiko** [comment]
+1, full disclosure i work with Alex and think he's a cool dude =)

**Comment by fabriziopandini** [comment]
+1 for me, great to have Alex on board!

**Comment by CecileRobertMichon** [comment]
Piling on, +1 from me!

**Comment by nikhita** [comment]
@alexander-demichev thank you for all your contributions so far \o/

I've created PR #2550 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
