### ISSUE TITLE
create driver-node-registrar

### ISSUE THREAD

**Issue by lpabon** [kubernetes/org#255]
### New Repo, Staging Repo, or migrate existing
kubernestes-csi/driver-node-registrar (filled in from kubernetes-csi/driver-registrar)

### Requested name for new repository
driver-node-registrar

### Which Organization should it reside
kubernetes-csi

### If not a staging repo, who should have admin access
saad-ali, lpabon

### If not a staging repo, who should have write access
saad-ali, lpabon

### If a new repo, who should be listed as approvers in OWNERS
saad-ali, lpabon

### If a new repo, who should be listed in SECURITY_CONTACTS
saad-ali, lpabon

### What should the repo description be
Sidecar container that registers the CSI driver with the Kubernetes cluster

### What SIG and subproject does this fall under in sigs.yaml
sig-storage

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

https://docs.google.com/document/d/1_hvq3nleqQEYatH9V_Gfep39jMzaFJRSN2ioA0PFq-Q/edit#heading=h.l7r2dou210l9

/area github-repo

**Comment by saad-ali** [comment]
We don't need two bugs to track this. We can track creation of both repos in https://github.com/kubernetes/org/issues/254.

/close
