### ISSUE TITLE
REQUEST: New membership for wgahnagl

### ISSUE THREAD

**Issue by wgahnagl** [kubernetes/org#2551]
### GitHub Username
@wgahnagl

### Organization you are requesting membership in
@kubernetes
### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ehashman 
- @pacoxu 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pull/99734
-  https://github.com/kubernetes/kubernetes/pull/99158

**Comment by ehashman** [comment]
:+1: :tada:

**Comment by pacoxu** [comment]
+1

**Comment by palnabarun** [comment]
@wgahnagl, thank you for all your contributions so far :)

I've created PR #2564 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
