### ISSUE TITLE
REQUEST: New membership for gjkim42

### ISSUE THREAD

**Issue by gjkim42** [kubernetes/org#2553]
### GitHub Username
@gjkim42

### Organization you are requesting membership in
@kubernetes 
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ehashman
- @SergeyKanzhelev 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Agjkim42+is%3Aclosed
  - https://github.com/google/cadvisor/pulls?q=is%3Apr+author%3Agjkim42+is%3Aclosed
- Issues responded to
- SIG projects I am involved with

**Comment by ehashman** [comment]
:+1: :confetti_ball:

**Comment by SergeyKanzhelev** [comment]
I support! Welcome, @gjkim42!

**Comment by palnabarun** [comment]
@gjkim42, thank you for all your contributions so far :)

I've created PR #2564 to add you to the @kubernetes and @kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! :tada:

/assign

**Comment by gjkim42** [comment]
Thanks :) @ehashman @SergeyKanzhelev @palnabarun
