### ISSUE TITLE
REQUEST: New membership for Danil-Grigorev

### ISSUE THREAD

**Issue by Danil-Grigorev** [kubernetes/org#2555]
### GitHub Username

Danil-Grigorev

### Organization you are requesting membership in

kubernetes
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @divyenpatel 
- @cheftako
 
### List of contributions to the Kubernetes project

- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/94526
  - https://github.com/kubernetes/kubernetes/pull/97989
  - https://github.com/kubernetes/kubernetes/pull/93971
  - https://github.com/kubernetes/kubernetes/pull/90836
  - https://github.com/kubernetes/kubernetes/pull/90796
  - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1031
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1035
  - https://github.com/kubernetes-sigs/cluster-api/pull/2358
  - https://github.com/kubernetes-sigs/controller-runtime/pull/1022
- Issues authored/working on
  - https://github.com/kubernetes/kubernetes/issues/100024
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2283
- SIG projects I am involved with
  - cluster-api
  - sig-cloud-provider

**Comment by cheftako** [comment]
+1

**Comment by divyenpatel** [comment]
Thanks for your contributions @Danil-Grigorev

+1

**Comment by palnabarun** [comment]
@Danil-Grigorev, thank you for all your contributions so far :)

I've created PR #2564 to add you to the @kubernetes and @kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! :tada:

/assign
