### ISSUE TITLE
REQUEST: New membership for JAORMX

### ISSUE THREAD

**Issue by JAORMX** [kubernetes/org#2556]
### GitHub Username
@JAORMX

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @saschagrunert 
- @pjbgf

### List of contributions to the Kubernetes project
- PRs reviewed/authored: https://github.com/kubernetes-sigs/security-profiles-operator/pulls?q=is%3Apr+author%3Ajaormx and https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Ajaormx
- Issues responded to: https://github.com/kubernetes-sigs/security-profiles-operator/issues?q=is%3Aissue+author%3Ajaormx
- kubernetes-sigs/security-profiles-operator

### Notes
- The main intent is to be able to contribute to CI settings for the security-profiles-operator

**Comment by palnabarun** [comment]
@JAORMX, thank you for all your contributions so far :)

I've created PR #2564 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
