### ISSUE TITLE
REQUEST: New membership for QiWang19

### ISSUE THREAD

**Issue by QiWang19** [kubernetes/org#2557]
### GitHub Username
@QiWang19

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @serathius 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/99001
https://github.com/kubernetes/kubernetes/pull/99799

**Comment by serathius** [comment]
Thanks for the help with Structured Logging, looking forward to your future contributions!

**Comment by ehashman** [comment]
:+1: !! :cake:

**Comment by palnabarun** [comment]
@QiWang19, thank you for all your contributions so far :)

I've created PR #2564 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
