### ISSUE TITLE
REQUEST: New membership for navidshaikh

### ISSUE THREAD

**Issue by navidshaikh** [kubernetes/org#2558]
### GitHub Username
@navidshaikh

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ehashman 
- @nikhita 

### List of contributions to the Kubernetes project
- PRs [authored](https://github.com/kubernetes/kubernetes/pulls?q=author%3Anavidshaikh) / reviewed (multiple PRs in structured logging migration for kubelet)

**Comment by palnabarun** [comment]
A huge +1 from my side as well. Thank you for all your help @navidshaikh !!!

/honk

_(note: my +1 non-binding since Nikhita and I are work for the same employer)_

**Comment by ehashman** [comment]
:+1: !! :partying_face:

**Comment by palnabarun** [comment]
@navidshaikh, thank you for all your contributions so far :)

I've created PR #2564 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
