### ISSUE TITLE
REQUEST: New membership for swetharepakula

### ISSUE THREAD

**Issue by swetharepakula** [kubernetes/org#2561]
### GitHub Username
@swetharepakula

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @robscott 
- @aojea 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Aswetharepakula+is%3Aclosed+
- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+commenter%3Aswetharepakula
- SIG projects I am involved with
SIG Network - https://github.com/kubernetes/community/tree/master/sig-network

**Comment by robscott** [comment]
Thanks for all the k8s contributions @swetharepakula!

+1

**Comment by aojea** [comment]
big +1 from me, thanks for all the current and future contributions @swetharepakula

**Comment by dims** [comment]
+1 welcome!

**Comment by palnabarun** [comment]
@swetharepakula, thank you for all your contributions so far :)

I've created PR #2564 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
