### ISSUE TITLE
REQUEST: New membership for weiling61

### ISSUE THREAD

**Issue by weiling61** [kubernetes/org#2562]
### GitHub Username
weiling61

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @christopherhein 
- @fei-guo

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/perf-tests/pull/1313
https://github.com/kubernetes/perf-tests/pull/1317
https://github.com/kubernetes-sigs/multi-tenancy/pull/1423
https://github.com/kubernetes-sigs/multi-tenancy/pull/1416
https://github.com/kubernetes-sigs/multi-tenancy/pull/1361
https://github.com/kubernetes-sigs/multi-tenancy/pull/1264
https://github.com/kubernetes-sigs/multi-tenancy/pull/1231
https://github.com/kubernetes-sigs/multi-tenancy/pull/1086
https://github.com/kubernetes-sigs/multi-tenancy/pull/1082
https://github.com/kubernetes-sigs/multi-tenancy/pull/1011

- Issues responded to
https://github.com/kubernetes-sigs/multi-tenancy/issues/1388
https://github.com/kubernetes-sigs/multi-tenancy/issues/1315

- SIG projects I am involved with
https://github.com/kubernetes-sigs/multi-tenancy
https://github.com/kubernetes/perf-tests

**Comment by christopherhein** [comment]
Thanks for submitting this @weiling61 👍 to your org membership.

**Comment by parispittman** [comment]
yay!! happy to see ya here @weiling61

**Comment by Fei-Guo** [comment]
Yes, Wei has made a lot of contributions to CAPN and virtualcluster related projects. Strongly support his request for SIG member.

**Comment by palnabarun** [comment]
@weiling61, thank you for all your contributions so far :)

I've created PR #2564 to add you to the @kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! :tada:

/assign

**Comment by weiling61** [comment]
Thanks everyone!
