### ISSUE TITLE
Create kubernetes-sigs/instrumentation

### ISSUE THREAD

**Issue by brancz** [kubernetes/org#2566]
### New Repo, Staging Repo, or migrate existing
New Repo

### Requested name for new repository
instrumentation

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@brancz @logicalhan @ehashman @dashpole 

### If not a staging repo, who should have write access
@brancz @logicalhan @ehashman @dashpole 

### If not a staging repo, who should be listed as approvers in OWNERS
@brancz @logicalhan @ehashman @dashpole 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@brancz @logicalhan @ehashman @dashpole 

### What should the repo description be
"All about Kubernetes SIG Instrumentation"

### What SIG and subproject does this fall under in sigs.yaml
sig-instrumentation

And I suppose the subproject is `instrumentation`. We really want to use this for self-organization of sub-projects.

### Approvals

This was discussed and agreed on in our triage meeting which was not recorded, so maybe if @logicalhan @ehashman @dashpole as co-chairs and TLs besides me can just approve this and we're good? (according to our charter it just requires Chair + TL approval)

**Comment by mrbobbytables** [comment]
> And I suppose the subproject is instrumentation. We really want to use this for self-organization of sub-projects.

It would require approval from sig-arch, but [sig-release](https://github.com/kubernetes/sig-release) and [sig-testing](https://github.com/kubernetes/sig-testing) both have similar repos in the kubernetes org if that is something you'd like to pursue

**Comment by brancz** [comment]
We would just like `kubernetes-sigs/instrumentation`, that's sufficient for us, we don't care about it being under the kubernetes org. Does that make things simpler?

**Comment by dashpole** [comment]
This has my approval FWIW

**Comment by ehashman** [comment]
@mrbobbytables yeah we're looking for something similar to what sig-release has, does it need to go under kubernetes or kubernetes-sigs?

(+1 from me)

**Comment by mrbobbytables** [comment]
It doesn't have to be, but figured I'd toss it out as an option as that seems to be the pattern for other SIGs

**Comment by ehashman** [comment]
If kubernetes/sig-instrumentation is better than kubernetes-sigs/instrumentation I have no objections, we thought kubernetes-sigs was less controversial :smile:

**Comment by dims** [comment]
i'd avoid `kubernetes/` for sig specific work (wearing my arch hat)

**Comment by nikhita** [comment]
/assign
go ahead with k-sigs

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/instrumentation

Also created:
- https://github.com/kubernetes/org/pull/2570 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/5631 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by nikhita** [comment]
All PRs have merged, closing.
