### ISSUE TITLE
Request to archive kubernetes-csi/drivers

### ISSUE THREAD

**Issue by cpanato** [kubernetes/org#2568]
### Repository to archive
kubernetes-csi/drivers

### Repository and/or sig subproject owners that are approving this archival
@saad-ali @chakri-nelluri @lpabon @edisonxiang @sbezverk

### When should this be done
Anytime.

### Additional context for request
Per comment made in this PR https://github.com/kubernetes-csi/drivers/pull/167#issuecomment-796790042

**Comment by nikhita** [comment]
/assign @xing-yang @msau42 
sig-storage leads for approval

**Comment by nikhita** [comment]
Repo has been archived: https://github.com/kubernetes-retired/drivers

Also created:
- https://github.com/kubernetes/org/pull/2578 - to remove GitHub teams
- https://github.com/kubernetes/community/pull/5634 - to remove the repo from sigs.yaml

Once both PRs merge, this issue can be closed.

**Comment by nikhita** [comment]
Both PRs have merged, closing.
