### ISSUE TITLE
REQUEST: New membership for mengjiao-liu

### ISSUE THREAD

**Issue by mengjiao-liu** [kubernetes/org#2569]
### GitHub Username
@mengjiao-liu

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ehashman 
- @neolit123 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Amengjiao-liu
https://github.com/kubernetes/community/pulls?q=is%3Apr+author%3Amengjiao-liu+
https://github.com/kubernetes/kubernetes/pull/100165
https://github.com/kubernetes/kubernetes/pull/99833
https://github.com/kubernetes/kubernetes/pull/99693
https://github.com/kubernetes/kubernetes/pull/99614
https://github.com/kubernetes/kubernetes/pull/99581
https://github.com/kubernetes/kubernetes/pull/99479
https://github.com/kubernetes/kubernetes/pull/99444
https://github.com/kubernetes/kubernetes/pull/99301
https://github.com/kubernetes/kubernetes/pull/98717
https://github.com/kubernetes/community/pull/5461

- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3Amengjiao-liu+
https://github.com/kubernetes/kubernetes/issues/100130
https://github.com/kubernetes/kubernetes/issues/93719
https://github.com/kubernetes/kubernetes/issues/99453

- SIG projects I am involved with
COSI related
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar
https://github.com/kubernetes-sigs/container-object-storage-interface-controller
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter/pull/22
https://github.com/kubernetes-sigs/container-object-storage-interface-controller/pull/38
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/pull/37

**Comment by neolit123** [comment]
thank you for the contributions @mengjiao-liu 
+1

**Comment by ehashman** [comment]
:+1: welcome!

**Comment by nikhita** [comment]
@mengjiao-liu thank you for all your contributions so far \o/

I've created PR #2579 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by wlan0** [comment]
Hi @nikhita! 
 
Does this grant @mengjiao-liu merge privileges on the COSI projects? 

I'm asking because I've never talked to this person, and their involvement with COSI projects is a bunch of unmerged docs PRs. While I really appreciate their contribution and would be happy to facilitate their path towards approvership, I'm not sure if someone who isn't involved with the COSI community at all should be getting merge privileges, atleast not yet. Not to mention, they are new to the kubernetes org as well.

**Comment by ehashman** [comment]
:wave: @wlan0 

per https://github.com/kubernetes/community/blob/master/community-membership.md#member members' privileges are:

> Members are continuously active contributors in the community. They can have issues and PRs assigned to them, participate in SIGs through GitHub teams, and pre-submit tests are automatically run for their PRs.

Merge rights are granted via addition to OWNERS files. Being an org member for [at least three months](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-1) is a prerequisite to become a reviewer. An approver (who has merge rights) must be a reviewer for at least three months.

**Comment by wlan0** [comment]
Thanks, that makes sense

**Comment by mengjiao-liu** [comment]
To clarify, I did not apply for COSI member @wlan0

**Comment by wlan0** [comment]
Got it @mengjiao-liu! Thanks for confirming. That being clarified, I do really appreciate your contributions and I’d be happy to work with you and get you added as you make more of them :-)

**Comment by mengjiao-liu** [comment]
Thanks. I will devote more time to the COSI project.
