### ISSUE TITLE
REQUEST: New membership for @mark-nc

### ISSUE THREAD

**Issue by mark-nc** [kubernetes/org#2574]
### GitHub Username
@mark-nc

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @eddiezane
- @pwittrock

### List of contributions to the Kubernetes project
- PRs reviewed / authored (recently added as a maintainer to https://github.com/IBM/kui/blob/master/OWNERS_ALIASES as Red Hat Advanced Cluster Management for Kubernetes has been a consumer of Kui for over a year)
- Issues responded to (been helping @starpit and @myan9 evolve Kui for use in a containerized form for the last 18 months)
- SIG projects I am involved with: SIG-CLI

**Comment by eddiezane** [comment]
+1

Thanks for your work on Kui!

**Comment by pwittrock** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi, @mark-nc 👋 Thank you for all your contributions!

I've created PR #2590 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
