### ISSUE TITLE
REQUEST: New membership for krishchow

### ISSUE THREAD

**Issue by krishchow** [kubernetes/org#2577]
### GitHub Username
@krishchow

### Organization you are requesting membership in
@kubernetes-sigs
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @wlan0 
- @brahmaroutu

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/pull/39
https://github.com/kubernetes-sigs/container-object-storage-interface-spec/pull/24
https://github.com/kubernetes-sigs/container-object-storage-interface-api/pull/23
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter/pull/21
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter/pull/20
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter/pull/18
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter/pull/15
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter/pull/11
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter/pull/10
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter/pull/6
https://github.com/kubernetes-sigs/container-object-storage-interface-controller/pull/42
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/pull/38
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/pull/1
https://github.com/kubernetes-sigs/container-object-storage-interface-spec/pull/6

- Issues responded to
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter/issues/13
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/issues/35

- SIG projects I am involved with
https://github.com/kubernetes-sigs/container-object-storage-interface-controller
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar
https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter
https://github.com/kubernetes-sigs/container-object-storage-interface-spec
https://github.com/kubernetes-sigs/container-object-storage-interface-api

**Comment by wlan0** [comment]
+1, thanks! Krish has made great contributions to the object storage effort

**Comment by jeffvance** [comment]
+1 from me too!

**Comment by nikhita** [comment]
@krishchow thank you for all your contributions so far \o/

I've created PR #2579 to add you to the Kubernetes and Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! 🎉

/assign
