### ISSUE TITLE
Create windows-testing repo

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/org#258]
### New Repo, Staging Repo, or migrate existing
Migrate existing from https://github.com/e2e-win/k8s_images

### Requested name for new repository
kubernetes-sigs/windows-testing

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@michmike, @patricklang, @Adelina-t

### If not a staging repo, who should have write access
@michmike, @patricklang, @Adelina-t, @bclau

### If a new repo, who should be listed as approvers in OWNERS
@michmike, @patricklang, @Adelina-t

### If a new repo, who should be listed in SECURITY_CONTACTS
@michmike, @patricklang, @Adelina-t

### What should the repo description be
Test infrastructure and containers for testing Windows Kubernetes nodes

### What SIG and subproject does this fall under in sigs.yaml
sig-windows

### Approvals

No objections in 11/20 SIG meeting, so email thread sent:
https://groups.google.com/forum/#!topic/kubernetes-sig-windows/lxK6CuPhv34
https://groups.google.com/forum/#!topic/kubernetes-sig-testing/MN8DEiM95Z4

No objections in threads or 11/27 SIG-Windows meeting, so we have lazy consensus.

### Additional context for request
Testing Windows nodes needs extra container images to be built that are not currently built from kubernetes/kubernetes or kubernetes/test-infra.

This repo will hold the code that's built by SIG-Windows until we can find a way to merge it into the main project, or eliminate the need for them.

/sig windows

/area github-repo

**Comment by PatrickLang** [comment]
I'm opening this now for discussion, but I know there are a few things needed. If more is needed, please let me know.

1. Add the Kubernetes license, contributor & code of conduct to the e2ewin/k8s_images repo
2. Verify the 4 contributors there have signed the CLA
3. If any non-Kubernetes code was used there, make sure to add the right LICENSE & attributions in those folders
4. Get a lazy consensus from SIG-Windows members (ETA 11/27)

**Comment by adelina-t** [comment]
@bclau Can you please look over point 1 of the last comment from @PatrickLang  and update e2e-win/k8s_images accordingly. We basically need to copy the licenses of k/k repo and add whatever other licenses for any image code used that is not apache2.

**Comment by PatrickLang** [comment]
Just updated the write list with latest contributors

**Comment by cblecker** [comment]
To avoid confusion, I'd recommend forwarding your lazy consensus e-mail to sig-testing's e-mail list too, as there may be overlap.

Otherwise, please ping me here when lazy consensus is achieved and you're ready for review of the repo.

**Comment by yujuhong** [comment]
+1 for having an official testing repo owned by the SIG until we can merge all changes to the main repo. It'd certainly help the effort to have a centralized place to host and discuss testing-related changes/artifacts for windows.

@pjh and I will be happy to contribute and/or file issues we discover in our test job. Perhaps we can also move our test script for GCE to the new repo once we upstream'd the rest of the cluster setup script.

**Comment by PatrickLang** [comment]
cc @spiffxp @BenTheElder. I forwarded this to the sig-testing list too.

**Comment by PatrickLang** [comment]
Updated links above - we have lazy consensus now. Can we move forward with this repo request?

**Comment by PatrickLang** [comment]
/assign @cblecker 

This is ready for review :)

**Comment by cblecker** [comment]
@PatrickLang Can you please add me as an admin on that repo? I will need this to be able to transfer it.

**Comment by PatrickLang** [comment]
sure. If we want to reorganize code such that:

- k8s_image should become images
- doc : new directory

Should we do that first or later?

**Comment by cblecker** [comment]
Totally up to you.

**Comment by cblecker** [comment]
Also, has @AlexMuresan signed the CLA? I can't verify that, as they haven't opened a PR against the kubernetes org

**Comment by BenTheElder** [comment]
a thought: `kubernetes-sigs/windows-testing`, the current repo has `images` in the name, if hosting windows e2e image sources is still the goal, maybe we should go for a more focused repo name? maybe `kubernetes-sigs/win-e2e-images` or something like that?

Generally adding a repo so we have somewhere to get work done on these images - SGTM! IIRC plenty of the images used for linux e2e testing are from third parties...

**Comment by PatrickLang** [comment]
I wanted to combine all the things needed to run a test pass in a single repo:

- /images - test images
- /docs - latest info on how to build the test images, and run a test pass for the SIG, or upcoming conformance profile
- /scripts - scripts to run test passes with known good parameters, collect logs from Windows nodes

I'm pushing to get more federated test submissions from other distros & cloud providers, so I think getting a premade windows test kit in a single repo will be helpful

**Comment by cblecker** [comment]
I've verified that all users in that repo have signed the CLA :)

Can actually look at moving this repo now, after KubeCon wraps up.

**Comment by cblecker** [comment]
Okay, so it should be transferred to https://github.com/kubernetes-sigs/windows-testing

Still need to provide access.. https://github.com/kubernetes/org/pull/309 will add @michmike and @PatrickLang to @kubernetes-sigs, and then I can add you to the groups that give access.

@adelina-t isn't a member of the kubernetes org, so she'll need to go through the [community membership process](https://git.k8s.io/community/community-membership.md#member) first, before getting access.

**Comment by BenTheElder** [comment]
Happy to be a sponsor for that FYI :-)

**Comment by michmike** [comment]
i can sponsor her as well. this will be approved quickly :)

**Comment by cblecker** [comment]
Have you verified that this looks good @PatrickLang @adelina-t ?

**Comment by PatrickLang** [comment]
Looks good. Thanks!

**Comment by cblecker** [comment]
@PatrickLang Last step: Can you please get this repo added to sigs.yaml under sig-windows?

**Comment by PatrickLang** [comment]
@cblecker I think you already added it: https://github.com/kubernetes/community/blob/964f12113849642381aa376b72313f2cf4444633/sigs.yaml#L2105

Is there another entry needed?

**Comment by cblecker** [comment]
Yup, I did *facepalm*. Sorry!

Yeah, then I think we're done here. Let me know if you run into any issues.
/close
