### ISSUE TITLE
REQUEST: New membership for CKchen0726

### ISSUE THREAD

**Issue by CKchen0726** [kubernetes/org#2582]
### GitHub Username
@CKchen0726

### Organization you are requesting membership in
@kubernetes

### Requirements
+ [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
+ [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
+ [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
+ [x] I am actively contributing to 1 or more Kubernetes subprojects
+ [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
+ [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tanjunchen
- @tengqm
- @JornShen 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/website/pull/25998
  https://github.com/kubernetes/website/pull/26055
  https://github.com/kubernetes/website/pull/26162
  https://github.com/kubernetes/website/pull/27019
  https://github.com/kubernetes/website/pull/27020

- Issues responded to
  https://github.com/kubernetes/website/issues/25860
  https://github.com/kubernetes/website/issues/26150
  https://github.com/kubernetes/website/issues/26834

- SIG projects I am involved with
  sig-docs

**Comment by JornShen** [comment]
I'll sponsor @CKchen0726 
Thanks for contribution to doc.
: )

**Comment by tengqm** [comment]
+1
Looking forward to see more contributions from you.

**Comment by tanjunchen** [comment]
+1
thanks

**Comment by savitharaghunathan** [comment]
Hi, @CKchen0726 👋  Thank you for all your contributions!

I've created PR #2590 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
