### ISSUE TITLE
REQUEST: New membership for jihoon-seo

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/org#2584]
### GitHub Username
@jihoon-seo

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pjhwa
- @seokho-son

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=org%3Akubernetes+is%3Apr+author%3Ajihoon-seo
- Issues responded to
https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Ajihoon-seo
- SIG projects I am involved with
kubernetes/sig-docs

**Comment by pjhwa** [comment]
+1, Thanks! @jihoon-seo has made great contributions to the Korean Team! 👍🏼

**Comment by seokho-son** [comment]
+1, @jihoon-seo is actively involved in Korean localization. I'm happy to work with @jihoon-seo !

**Comment by ysyukr** [comment]
+1, I am happy to sponsor 😄

**Comment by savitharaghunathan** [comment]
Hi, @jihoon-seo 👋  Thank you for all your contributions!

I've created PR #2590 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by jihoon-seo** [comment]
@savitharaghunathan @pjhwa @seokho-son @ysyukr Thank you for your support!
