### ISSUE TITLE
REQUEST: New membership for Samuel Liu(@liupeng0518)

### ISSUE THREAD

**Issue by liupeng0518** [kubernetes/org#2585]
### GitHub Username
@liupeng0518

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @floryut
- @oomichi
- @tanjunchen 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pull/7382
https://github.com/kubernetes-sigs/kubespray/pull/7001
https://github.com/kubernetes-sigs/kubespray/pull/7131
https://github.com/kubernetes-sigs/kubespray/pull/6816
https://github.com/kubernetes-sigs/kubespray/pull/6667
https://github.com/kubernetes-sigs/kubespray/pull/6666
https://github.com/kubernetes/website/pull/23409
https://github.com/kubernetes/kubernetes/pull/100281
https://github.com/kubernetes-sigs/kubespray/pull/6482
https://github.com/kubernetes-sigs/kubespray/pull/6469
https://github.com/kubernetes-sigs/kubespray/pull/6310
https://github.com/kubernetes-sigs/kubespray/pull/6023
https://github.com/kubernetes-sigs/kubespray/pull/6024
https://github.com/kubernetes-sigs/kubespray/pull/6190
https://github.com/kubernetes-sigs/kubespray/pull/5166
https://github.com/kubernetes-sigs/kubespray/pull/5042

- Issues responded to
https://github.com/kubernetes/cloud-provider-openstack/issues/1129
https://github.com/kubernetes/kubernetes/issues/89208
https://github.com/kubernetes-sigs/kubespray/issues/6132
https://github.com/kubernetes-sigs/kubespray/issues/4962

- SIG projects I am involved with
https://github.com/kubernetes-sigs

**Comment by oomichi** [comment]
Thanks for your contributions!

+1 from me.

**Comment by floryut** [comment]
Some good contributions from @liupeng0518 
+1

**Comment by savitharaghunathan** [comment]
@liupeng0518 in order to be added to k/org you will need two sponsors who are reviewers/approvers in the Kubernetes repo.  @floryut is eligible only to sponsor for Kubernetes-sigs/org. Can you add one more sponsor who is a reviewer/approver in any of the Kubernetes repos?

**Comment by tanjunchen** [comment]
/approve
+1
thanks

**Comment by liupeng0518** [comment]
> @liupeng0518 in order to be added to k/org you will need two sponsors who are reviewers/approvers in the Kubernetes repo. @floryut is eligible only to sponsor for Kubernetes-sigs/org. Can you add one more sponsor who is a reviewer/approver in any of the Kubernetes repos?

Done, add tanjunchen

**Comment by oomichi** [comment]
@savitharaghunathan  tanjunchen is one of reviewers in kubernetes/kubernetes repo.
I feel this issue seems ready.

**Comment by savitharaghunathan** [comment]
Hi, @liupeng0518 👋  Thank you for all your contributions!

I've created PR #2626 to add you to the @kubernetes & @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
