### ISSUE TITLE
REQUEST: New membership for yangjunmyfm192085

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/org#2588]
### GitHub Username
@yangjunmyfm192085

### Organization you are requesting membership in
@kubernetes
### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ehashman
- @serathius

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/pulls?q=is%3Amerged+is%3Apr+author%3Ayangjunmyfm192085+archived%3Afalse+
https://github.com/pulls?q=+is%3Apr+author%3Ayangjunmyfm192085+archived%3Afalse+
- Issues responded to
https://github.com/issues?q=is%3Aissue+author%3Ayangjunmyfm192085+archived%3Afalse+
- SIG projects I am involved with
/sig instrumentation
/sig node
/sig api-machinery
/sig release

**Comment by serathius** [comment]
/lgtm
Thanks for all the help with Structured Logging.

**Comment by ehashman** [comment]
:+1:

**Comment by kikisdeliveryservice** [comment]
@yangjunmyfm192085 did a lot of essential work in the 1.21 structured logging effort :heart:

**Comment by nikhita** [comment]
Hi, @yangjunmyfm192085  👋 Thank you for all your contributions!

I've created PR #2619 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
