### ISSUE TITLE
REQUEST: New membership for sedefsavas

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes/org#2593]
### GitHub Username
@sedefsavas

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @richardcase 
- @randomvariable 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - ~[40 PRs in cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3Asedefsavas)
- Issues responded to
  - ~ [30 issues created in cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues?q=is%3Aissue+author%3Asedefsavas)
- SIG projects I am involved with
   sig-cluster-lifecycle
     - Cluster API - reviewer
     - Cluster API Provider AWS - maintainer

**Comment by richardcase** [comment]
+1

Yes please

**Comment by randomvariable** [comment]
+1

**Comment by randomvariable** [comment]
Kubernetes org membership required for access to k8s.io for image promotion processes.

**Comment by sedefsavas** [comment]
Ping
cc @palnabarun

**Comment by savitharaghunathan** [comment]
Hi, @sedefsavas 👋 Thank you for all your contributions!

I've created PR #2626 to add you to the @kubernetes  organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
