### ISSUE TITLE
Please add sig-windows-leads as admin to SIG-Windows project board

### ISSUE THREAD

**Issue by marosset** [kubernetes/org#2599]
Please add sig-windows-leads as admins to our project board

https://github.com/kubernetes/org/blob/03883ef5355f2746aef9935915208b2df36f0de4/OWNERS_ALIASES#L98-L102

https://github.com/orgs/kubernetes/projects/8

**Comment by cblecker** [comment]
Step 1: https://github.com/kubernetes/org/pull/2600

**Comment by cblecker** [comment]
Admin access granted to @kubernetes/sig-windows-leads

**Comment by marosset** [comment]
Thanks!
