### ISSUE TITLE
New repo: kubernetes-sigs/contributor-playground

### ISSUE THREAD

**Issue by cblecker** [kubernetes/org#26]
### New Repo, or migrate existing
new repository

### Requested name for new repository
contributor-playground

### Which Organization should it reside
kubernetes-sigs

### Who should be provided access to this repository
No direct write access required. Automation should be set up.

### Approvals
- Detailed discussion in https://github.com/kubernetes/community/issues/2321
- SIG consensus achieved

ContribEx Tech Leads:
- [x] @cblecker
- [x] @grodrigues3

**Comment by cblecker** [comment]
@grodrigues3 You good with this?

cc: @carolynvs @guineveresaenger @jberkus

**Comment by jberkus** [comment]
Please, I'd like this to be set up well in advance of Shanghai.

/lgtm

**Comment by jberkus** [comment]
Also, if this could happen before August 27th, it would be referenced in a workshop at Gophercon.

**Comment by guineveresaenger** [comment]
Please let me know how I can help!
enthusiastically:
/lgtm

**Comment by cblecker** [comment]
This is done.

PR to enable prow: https://github.com/kubernetes/test-infra/pull/9143 
PR to add to sigs.yaml: https://github.com/kubernetes/community/pull/2582

/close

**Comment by carolynvs** [comment]
omg! 💖 I can't wait to try it out and work it into my workshop next week at gophercon!

**Comment by nikhita** [comment]
Yayyy :tada:
