### ISSUE TITLE
New Repo: kubebuilder-maestro

### ISSUE THREAD

**Issue by droot** [kubernetes/org#260]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
maestro

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@kubernetes-sigs/kubebuilder-admins

### If not a staging repo, who should have write access
@kubernetes-sigs/kubebuilder-admins, @gerred 

### If a new repo, who should be listed as approvers in OWNERS
@kubernetes-sigs/kubebuilder-admins, @gerred

### If a new repo, who should be listed in SECURITY_CONTACTS
@kubernetes-sigs/kubebuilder-admins, gerred

### What should the repo description be
A universal operator that generates and runs operators based on a standard data format.

Associated proposal: https://github.com/kubernetes-sigs/kubebuilder/pull/489

### What SIG and subproject does this fall under in sigs.yaml
This is part of the kubebuilder subproject for SIG API Machinery.

### Approvals
kubebuilder subproject core maintainers should approve this repo:

- [x] pwittrock
- [x] droot
- [x] DirectXMan12

### Additional context for request
While Kubebuilder provides an abstraction around the plumbing for building operators, there is still a lot of work to implement operators in code. To combat this problem, Mesosphere built an SDK for DC/OS, as well as a package data format, that handles a lot of the common high level tasks in running stateful workloads and provides lifecycle hooks. The purpose of Maestro is to take this work and enable the same standard packaging format and lifecycle hooks to be applied to Kubernetes operators.

https://github.com/kubernetes-sigs/kubebuilder/pull/489

/cc @gerred @pwittrock @DirectXMan12

/area github-repo

**Comment by cblecker** [comment]
KEP should be merged first, and will need signoffs from API machinery here before I can take action.

**Comment by deads2k** [comment]
> KEP should be merged first, and will need signoffs from API machinery here before I can take action.

I'm intrigued by the idea, but I'd like to see a little more detail in the sketch of how it would work beyond an initial demo before we move forward with it.  I've seen previous efforts in similar spaces get stalled there.

**Comment by gerred** [comment]
@deads2k :+1:, responded to you over in the KEP.

**Comment by cblecker** [comment]
/lifecycle stale

Marking this as stale.. please advise if this is still required.
