### ISSUE TITLE
REQUEST: New membership for olemarkus

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/org#2605]
### GitHub Username
@olemarkus 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
I am already a @kubernetes member

### Sponsors
N/A

### List of contributions to the Kubernetes project
N/A

**Comment by randomvariable** [comment]
+1

**Comment by nikhita** [comment]
@olemarkus sorry that this slipped through the cracks :disappointed: 

I've created PR #2655 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
