### ISSUE TITLE
REQUEST: New membership for DangerOnTheRanger

### ISSUE THREAD

**Issue by DangerOnTheRanger** [kubernetes/org#2608]
### GitHub Username
@DangerOnTheRanger

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cheftako 
- @nckturner

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/95775
  - https://github.com/kubernetes/cloud-provider-gcp/pull/168
  - [(Full list of PRs submitted against kubernetes/kubernetes)](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3ADangerOnTheRanger)
  - [(Full list of PRs submitted against kubernetes/cloud-provider-gcp)](https://github.com/kubernetes/cloud-provider-gcp/pulls?q=is%3Apr+author%3ADangerOnTheRanger) 
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/98647
  - https://github.com/kubernetes/kubernetes/issues/96965
- SIG projects I am involved with
  - [SIG Cloud Provider](https://github.com/kubernetes/community/tree/master/sig-cloud-provider)

**Comment by nckturner** [comment]
+1 from me! :tada:

**Comment by cheftako** [comment]
+1 :+1:

**Comment by savitharaghunathan** [comment]
Hi, @DangerOnTheRanger 👋 Thank you for all your contributions!

I've created PR #2626 to add you to the @kubernetes & @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
