### ISSUE TITLE
Create new repo: kubernetes-sigs/about-api

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes/org#2609]
### New Repo, Staging Repo, or migrate existing
new repo

### Requested name for new repository
about-api

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
jeremyot, pmorie

### If not a staging repo, who should have write access
jeremyot, pmorie

### If not a staging repo, who should be listed as approvers in OWNERS
jeremyot, pmorie

### If not a staging repo, who should be listed in SECURITY_CONTACTS
jeremyot, pmorie

### What should the repo description be
A CRD for arbitrary properties about a cluster

### What SIG and subproject does this fall under in sigs.yaml
SIG-Multicluster

### Approvals
Approval via comment from @jeremyot and/or @pmorie (SIG-Multicluster chairs)

### Additional context for request
This repo is for the implementation of [KEP-2149: ClusterId for ClusterSet identification](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/2149-clusterid)

**Comment by JeremyOT** [comment]
Thanks @lauralorenz

/lgtm

**Comment by nikhita** [comment]
/assign

Repo has been created - https://github.com/kubernetes-sigs/about-api

Also created:
- https://github.com/kubernetes/org/pull/2618 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/5696 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by nikhita** [comment]
All PRs have merged and teams have been granted access, closing.
