### ISSUE TITLE
yastij membership for kubernetes-sigs

### ISSUE THREAD

**Issue by yastij** [kubernetes/org#261]
### GitHub Username
@yastij 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects

/area github-membership

**Comment by mrbobbytables** [comment]
@yastij I've created PR #263 to add you to @kubernetes-sigs. Once that gets merged, you should get a membership invite  :)
