### ISSUE TITLE
REQUEST: New membership for sladyn98

### ISSUE THREAD

**Issue by sladyn98** [kubernetes/org#2610]
### GitHub Username
@sladyn98

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @puerco 
- @LappleApple

### List of contributions to the Kubernetes project
- PRs reviewed / authored

**Authored**
- https://github.com/kubernetes/kubernetes/pull/99029
- https://github.com/kubernetes/test-infra/pull/21028
- https://github.com/kubernetes/sig-release/pull/1479
- https://github.com/kubernetes/kube-openapi/pull/228
- https://github.com/kubernetes/community/pull/5411

**Reviewed**
- https://github.com/kubernetes/kubernetes/pull/99029
- https://github.com/kubernetes/test-infra/pull/21028
- https://github.com/kubernetes/sig-release/pull/1479

SIG projects I am involved with
   - ci-signal
   - sig-testing
   - release-eng

**Comment by puerco** [comment]
+1 from me, thanks for all you have been doing in SIG Release Sladyn! :tada:

**Comment by savitharaghunathan** [comment]
+1

/pony party

**Comment by savitharaghunathan** [comment]
Hi, @sladyn98 👋 Thank you for all your contributions!

I've created PR #2626 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
