### ISSUE TITLE
New SIG Instrumentation repo request (instrumentation-addons) 

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/org#2611]
### New Repo, Staging Repo, or migrate existing

We're requesting a new repo.

### Requested name for new repository

instrumentation-addons

### Which Organization should it reside

kubernetes-sigs

### If not a staging repo, who should have admin access

@ehashman, @brancz, @logicalhan, @dashpole (sig leads)

### If not a staging repo, who should have write access

@ehashman, @brancz, @logicalhan, @dashpole (sig leads)

### If not a staging repo, who should be listed as approvers in OWNERS

@ehashman, @brancz, @logicalhan, @dashpole (sig leads)

### If not a staging repo, who should be listed in SECURITY_CONTACTS

@ehashman, @brancz, @logicalhan, @dashpole (sig leads)

### What should the repo description be

Addons owned by sig-instrumentation

### What SIG and subproject does this fall under in sigs.yaml

SIG instrumentation (addons subproject)

### Approvals

https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit?disco=AAAAILEoKdU

### Additional context for request
Any additional information or context to describe the request.

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/instrumentation-addons

- Granted admin access to `@kubernetes-sigs/instrumentation-admins` team
- Created https://github.com/kubernetes/community/pull/5697 to add the repo to sigs.yaml

Once https://github.com/kubernetes/community/pull/5697 merges, this issue can be closed.
