### ISSUE TITLE
REQUEST: New membership for kevindelgado

### ISSUE THREAD

**Issue by kevindelgado** [kubernetes/org#2613]
### GitHub Username
@kevindelgado

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @apelisse 
- @kwiesmueller 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Akevindelgado+ 
- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+kevindelgado+
- SIG projects I am involved with
sig-api-machinery
wg-api-expression
kubebuilder/controller-runtime/controller-tools

**Comment by kwiesmueller** [comment]
I confirm my sponsorship.

**Comment by apelisse** [comment]
Same

**Comment by savitharaghunathan** [comment]
Hi, @kevindelgado 👋 Thank you for all your contributions!

I've created PR #2626 to add you to the @kubernetes & @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
