### ISSUE TITLE
REQUEST: New membership for ibabou

### ISSUE THREAD

**Issue by ibabou** [kubernetes/org#2617]
### GitHub Username
@ibabou

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @marosset
- @pjh

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/test-infra/pull/20793
- https://github.com/kubernetes/kubernetes/pull/99742
- https://github.com/kubernetes/kubernetes/pull/99971
- https://github.com/kubernetes/kubernetes/pull/100417

**Comment by marosset** [comment]
+1!

**Comment by pjh** [comment]
LGTM

Thanks Ibrahim for your Windows + containerd contributions so far, especially troubleshooting the container pull performance issue with Windows Defender (https://github.com/containerd/containerd/issues/4989 + https://github.com/microsoft/Windows-Containers/issues/92).

**Comment by ibabou** [comment]
+ @kubernetes/owners

**Comment by nikhita** [comment]
@ibabou Thank you for all your contributions so far \o/

I've created PR #2634 to add you to the @kubernetes and @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! 🎉

/assign
