### ISSUE TITLE
REQUEST: New membership for jonpulsifer

### ISSUE THREAD

**Issue by jonpulsifer** [kubernetes/org#262]
### GitHub Username
@jonpulsifer

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tallclair 
- @philips 
- @jessfraz  

### List of contributions to the Kubernetes project
- PST associate member https://github.com/kubernetes/sig-release/pull/376/files
- shepherd of the 404-server 😄  (`k8s.gcr.io/defaultbackend`) https://github.com/kubernetes/ingress-nginx/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ajonpulsifer+404
- some wg-multitenancy participation

/area github-membership

**Comment by jonpulsifer** [comment]
oops too many googlers on the original issue, added @philips and @jessfraz 🙏

**Comment by mrbobbytables** [comment]
@jonpulsifer Just as an FYI - The @kubernetes-security group is not really an official org. Were you thinking of the security audit working group?

**Comment by cblecker** [comment]
@mrbobbytables It actually is, but it's membership is restricted (https://github.com/kubernetes/community/tree/master/github-management#actively-used-github-organizations)

I'll take care of this one :)

**Comment by mrbobbytables** [comment]
Ahh, thanks for the correction @cblecker :)

**Comment by tallclair** [comment]
@cblecker If we create a new pst-associate team in the @kubernetes-security org, are we able to restrict access to the private repos from that team? Otherwise, I think we should just stick with @kubernetes for now.

_(Not that I don't trust @jonpulsifer, but the PST-associate role is explicitly limited to handling publicly disclosed vulnerabilities)_

**Comment by cblecker** [comment]
@tallclair Yes, we can.. that said, being in the org doesn't really get you anything unless you can see the private repos (there's no public repos). If PST associates don't need access to the private repos, then I'd say just leave it to @kubernetes for now, and we can revisit later if things change.

**Comment by cblecker** [comment]
Looks good. Need a thumbs up from a second sponsor, and we should be good to go.

**Comment by mrbobbytables** [comment]
@jonpulsifer My apologies for the confusion earlier regarding @kubernetes-security. I've gone ahead and created PR #263 to add you to the @kubernetes Org.  Once that gets merged, you should get a membership invite :)

**Comment by cblecker** [comment]
Thanks @mrbobbytables! Welcome @jonpulsifer!
