### ISSUE TITLE
REQUEST: New membership for edsoncelio

### ISSUE THREAD

**Issue by edsoncelio** [kubernetes/org#2628]
### GitHub Username
edsoncelio

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rikatz 
- @jailton 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - [kubernetes/website#27415](https://github.com/kubernetes/website/pull/27415)
    - [kubernetes/website#27255](https://github.com/kubernetes/website/pull/27255)
    - [kubernetes/website#27110](https://github.com/kubernetes/website/pull/27110)
    - [kubernetes/website#26960](https://github.com/kubernetes/website/pull/26960)
    - [kubernetes/website#26924](https://github.com/kubernetes/website/pull/26924)
    - [kubernetes/website#26757](https://github.com/kubernetes/website/pull/26757)
    - [kubernetes/kubernetes#97767](https://github.com/kubernetes/kubernetes/pull/97767)
- Issues responded to
   - [kubernetes/website#13939](https://github.com/kubernetes/website/issues/13939) 
   - [kubernetes/website#21621](https://github.com/kubernetes/website/issues/21621)
   - [kubernetes/kubernetes#97734](https://github.com/kubernetes/kubernetes/issues/97734)
- SIG projects I am involved with
  sig-docs

**Comment by rikatz** [comment]
+1 from me.

Edson is being really helpful with the brazilian localization team, and helping us to strongly move this effort forward

**Comment by jailton** [comment]
+1 from me. 

Edson, thanks!

**Comment by nikhita** [comment]
@edsoncelio Thank you for all your contributions so far \o/

I've created PR #2634 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
