### ISSUE TITLE
REQUEST: New membership for lauchokyip

### ISSUE THREAD

**Issue by lauchokyip** [kubernetes/org#2629]
### GitHub Username
@lauchokyip

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @eddiezane 
- @rikatz 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
 https://github.com/kubernetes/kubernetes/pull/97884
 https://github.com/kubernetes/kubernetes/pull/97981
 https://github.com/kubernetes/kubernetes/pull/97895
 https://github.com/kubernetes/kubernetes/pull/98614
 https://github.com/kubernetes/kubernetes/pull/98747
 https://github.com/kubernetes/kubernetes/pull/98846
 https://github.com/kubernetes-sigs/krew/pull/703
 https://github.com/kubernetes/kubernetes/pull/100505
 https://github.com/kubernetes/kubernetes/pull/100435
 https://github.com/kubernetes/kubernetes/pull/100568
- Issues responded to
 https://github.com/kubernetes/kubectl/issues/1025
 https://github.com/kubernetes/kubectl/issues/965
 https://github.com/kubernetes/kubernetes/pull/99891
- SIG projects I am involved with
   https://github.com/kubernetes/kubectl

**Comment by rikatz** [comment]
+1 from me.

Thanks for all your help in sig-cli Lau :)

**Comment by eddiezane** [comment]
+1

Really glad you've joined the community!

**Comment by lauchokyip** [comment]
Thank you @rikatz  and @eddiezane . Hope to learn more from both of you!

**Comment by nikhita** [comment]
@lauchokyip  Thank you for all your contributions so far \o/

I've created PR #2634 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
