### ISSUE TITLE
REQUEST: New membership for changshuchao

### ISSUE THREAD

**Issue by changshuchao** [kubernetes/org#2630]
### GitHub Username
changshuchao

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@damemi 
@ehashman 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  [https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Achangshuchao+is%3Aclosed+](url)
- Issues responded to
- SIG projects I am involved with
  kubernetes/kubernetes

**Comment by damemi** [comment]
+1!

**Comment by ehashman** [comment]
:+1:

**Comment by nikhita** [comment]
@changshuchao Thank you for all your contributions so far \o/

I've created PR #2634 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
