### ISSUE TITLE
New repository for Container Object Storage Interface - MINIO driver

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/org#2631]
### New Repo, Staging Repo, or migrate existing
New Repository

### Requested name for new repository
cosi-driver-minio

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@jsafrane
@msau42
@saad-ali
@xing-yang

### If not a staging repo, who should have write access
@saad-ali
@jsafrane
@msau42
@xing-yang
@wlan0
@brahmaroutu

### If not a staging repo, who should be listed as approvers in OWNERS
@saad-ali
@jsafrane
@msau42
@xing-yang
@wlan0
@brahmaroutu

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@jsafrane
@msau42
@saad-ali
@xing-yang

### What should the repo description be
Sample Driver that provides reference implementation for Container Object Storage Interface (COSI) api

### What SIG and subproject does this fall under in sigs.yaml
SIG: sig-storage, subproject: kubernetes-cosi

### Approvals
Need sig-storage approval from: @saad-ali and @xing-yang
Please refer to KEP: kubernetes/enhancements#2100
Repos created before for this project apart from this: #2039 and #1942

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

### Additional context for request
COSI is actively developed projects under Sig-Storage and it is required to provide a implementation of a sample driver to test and run e2e use cases using that driver. This driver will be part of the COSI implementation similar to host path driver provided along CSI.

**Comment by brahmaroutu** [comment]
@xing-yang @saad-ali @nikhita  Please help us get this repo setup to continue our development progress on COSI project.

**Comment by nikhita** [comment]
> Need sig-storage approval from: @saad-ali and @xing-yang

/assign @saad-ali @xing-yang

**Comment by xing-yang** [comment]
Requested on the mailing list:
https://groups.google.com/g/kubernetes-sig-storage/c/artGqp42rJM

**Comment by saad-ali** [comment]
SGTM
+1
/lgtm

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/cosi-driver-minio

Also created:
- https://github.com/kubernetes/org/pull/2647 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/5726 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by brahmaroutu** [comment]
thanks @nikhita @xing-yang for getting this in.

**Comment by nikhita** [comment]
Repo added to sigs.yaml and teams have been granted access.

created https://github.com/kubernetes/org/pull/2654 to fix the typo in the team name, but going to close this issue because the typo fix doesn't block any functionality.
