### ISSUE TITLE
REQUEST: New membership for jackfrancis

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes/org#2632]
### GitHub Username
@jackfrancis

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @SergeyKanzhelev 
- @lachie83 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/100200
  - https://github.com/kubernetes/kubernetes/pull/48967
  - https://github.com/kubernetes/kubernetes/pull/46660
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/100198
  - https://github.com/kubernetes/kubernetes/issues/47048
  - https://github.com/kubernetes/kubernetes/issues/48971
- SIG projects I am involved with
  - sig-node
  - sig-arch
  - sig-testing

**Comment by SergeyKanzhelev** [comment]
I support!

**Comment by lachie83** [comment]
I support

**Comment by CecileRobertMichon** [comment]
+1 !

**Comment by nikhita** [comment]
@jackfrancis Thank you for all your contributions so far \o/

I've created PR #2634 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by jackfrancis** [comment]
Thank you @nikhita and everyone! ❤️

**Comment by jackfrancis** [comment]
cc @nojnhuh @nawazkh @willie-yao @dtzar you can follow this issue as a template for adding yourselves to k/k
