### ISSUE TITLE
new repo request for depstat

### ISSUE THREAD

**Issue by RinkiyaKeDad** [kubernetes/org#2636]
### New Repo, Staging Repo, or migrate existing
migrate existing

### Requested name for new repository
depstat

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@alenkacz @dims @navidshaikh @nikhita @RinkiyaKeDad

### If not a staging repo, who should have write access
@alenkacz @dims @navidshaikh @nikhita @RinkiyaKeDad

### If not a staging repo, who should be listed as approvers in OWNERS
@alenkacz @dims @navidshaikh @nikhita @RinkiyaKeDad

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@alenkacz @dims @navidshaikh @nikhita @RinkiyaKeDad

### What should the repo description be
depstat is a dependency analyser which helps evaluate dependency updates to kubernetes

### What SIG and subproject does this fall under in sigs.yaml
SIG Architecture (code organisation subproject)

### Approvals

Requesting for approval from @dims as SIG Architecture lead

### Additional context for request
Repo to be migrated: https://github.com/RinkiyaKeDad/depstat

**Comment by dims** [comment]
+1 from sig-arch side

cc @kubernetes/sig-architecture-leads

**Comment by justaugustus** [comment]
@dims -- Was the plan for this to be a RelEng subproject or Code Org?

FWIW, I'm fine with either.
Noting that my comment [here](https://github.com/kubernetes/repo-infra/pull/236#issuecomment-819180769) was an approval from SIG Release, just with the caveat that managing this through bazel within k/repo-infra was going to be a pain and pull in unnecessary dependencies for the tool.

cc: @kubernetes/sig-release-leads @kubernetes/release-engineering

**Comment by dims** [comment]
@justaugustus got it. let's leave this here for now, we can checkpoint again in a few months. There are still more ideas that we can do here with depstat so it's going to be around for a while and will need sig-release folks to fully engage. So i am hoping it will end up there in the long run.

**Comment by nikhita** [comment]
> We're requesting a new repo.

@RinkiyaKeDad this would actually entail migrating the repo - https://github.com/RinkiyaKeDad/depstat.

Can you please update depstat to satisfy all requirements in https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories? Please ping me once that's done and I can help you with the migration :)

/assign

**Comment by RinkiyaKeDad** [comment]
Hey @nikhita! I've updated the repository with all the necessary files. Let's start the migration process? :) Thanks!

**Comment by nikhita** [comment]
Few more things to do to satisfy the [rules for donate repos](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories) before we can go ahead with the migration:

- Please add the `SECURITY.md` and `RELEASE.md` files too, all template files in https://github.com/kubernetes/kubernetes-template-project must be added to the depstat repo.
- The formatting of the `SECURITY_CONTACTS` file is a little skewed - can you correct it? :)
- The copyright boilerplate header must be added to all files. You can find the template [here](https://github.com/kubernetes/kubernetes/tree/master/hack/boilerplate).

**Comment by nikhita** [comment]
@RinkiyaKeDad thanks for the update, repo looks good!

GitHub doesn't allow migrating user-owned repos, only org-owned repos are allowed. @RinkiyaKeDad can you transfer the repo to https://github.com/kubernetes-purgatory? You should have an invite to the org.

Once the repo is transferred, I can migrate that to k-sigs.

**Comment by nikhita** [comment]
Repo has been migrated - https://github.com/kubernetes-sigs/depstat :rocket: 

Also created:
- https://github.com/kubernetes/org/pull/2646 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/5725 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by nikhita** [comment]
All PRs have merged and teams have been granted access. Closing.
