### ISSUE TITLE
REQUEST: New membership for tam7t

### ISSUE THREAD

**Issue by tam7t** [kubernetes/org#2638]
### GitHub Username
@tam7t

### Organization you are requesting membership in
@kubernetes

### Requirements

- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @aramase 
- @mikedanese 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/266
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/267
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/280
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/340
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/371
- Issues responded to
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/243
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/256
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver

**Comment by aramase** [comment]
+1 for @tam7t's membership

Tommy is a reviewer for the Secrets Store CSI Driver sig-auth subproject.

/lgtm

**Comment by mrbobbytables** [comment]
Thank you!

**Comment by mrbobbytables** [comment]
Woops, thought this would close^^;; Will just take care of that now as #2637 was merged...
/assign
/close
