### ISSUE TITLE
REQUEST: New membership for jackfrancis

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes/org#2641]
### GitHub Username
@jackfrancis

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @devigned 
- @CecileRobertMichon

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/833
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1239
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1242
- Issues responded to
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1015
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/832
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1189
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure
  - https://github.com/kubernetes-sigs/cluster-api

**Comment by devigned** [comment]
+1 to @jackfrancis joining!

**Comment by CecileRobertMichon** [comment]
@jackfrancis since you joined the kubernetes org already, you should be implicitle eligible for membership in the kubernetes-sigs org https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem

that being said, +1

**Comment by nikhita** [comment]
@jackfrancis Like @CecileRobertMichon mentioned, you didn't need sponsorship for getting added to k-sigs :)

I've created PR #2445 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
