### ISSUE TITLE
REQUEST: New membership for RinkiyaKeDad

### ISSUE THREAD

**Issue by RinkiyaKeDad** [kubernetes/org#2642]
### GitHub Username
@RinkiyaKeDad

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@alenkacz @nikhita 

### List of contributions to the Kubernetes project
PRs authored
- https://github.com/kubernetes/kubernetes/pull/100792
- https://github.com/kubernetes/repo-infra/pull/236
- https://github.com/kubernetes/k8s.io/pull/1789

Issues responded to
- https://github.com/kubernetes/kubernetes/issues/98698
- https://github.com/kubernetes/community/issues/5360

SIG projects I am involved with
- sig-architecture (code organisation subproject)

**Comment by alenkacz** [comment]
+1000000 💯

**Comment by nikhita** [comment]
+1! Thanks for all your work in depstat!

/woof

**Comment by RinkiyaKeDad** [comment]
Thank you so much @alenkacz and @nikhita! I'm so grateful to have met you both :)

**Comment by nikhita** [comment]
> Organization you are requesting membership in

> @kubernetes

Hey @RinkiyaKeDad,  given that depstat is moving to kubernetes-sigs, you'll need membership to @kubernetes-sigs. Are you good with modifying the membership request to that?

To be clear, I'm happy to sponsor you for @kubernetes once you've got a few more PRs opened in a repo in the @kubernetes org :)

**Comment by RinkiyaKeDad** [comment]
Updated! Will apply for @kubernetes soon, after contributing more :D

**Comment by nikhita** [comment]
@RinkiyaKeDad Thank you for all your contributions so far \o/

I've created PR #2645 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
