### ISSUE TITLE
REQUEST: New membership for nodo

### ISSUE THREAD

**Issue by nodo** [kubernetes/org#2644]
### GitHub Username
@nodo

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @apelisse 
- @kwiesmueller 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    * https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Anodo

- Issues responded to

    * https://github.com/kubernetes/kubernetes/issues/91111
    * https://github.com/kubernetes/kubernetes/issues/94168
    * https://github.com/kubernetes/kubernetes/issues/95680

- SIG projects I am involved with
    * wg-api-expression

**Comment by kwiesmueller** [comment]
I confirm sponsorship, great to have you with us!

**Comment by apelisse** [comment]
Absolutely confirmed! Thank you so much for your contributions, I'm excited about the future!

**Comment by nikhita** [comment]
@nodo Thank you for all your contributions so far \o/

I've created PR #2645 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
