### ISSUE TITLE
REQUEST: New membership for bswartz

### ISSUE THREAD

**Issue by bswartz** [kubernetes/org#2648]
### GitHub Username
@bswartz

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xing-yang 
- @wlan0 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
kubernetes
kubernetes-csi
sig-storage

**Comment by bswartz** [comment]
I'm already a member of kubernetes and kubernetes-csi. If you want pointers to some of my contributions I could add those but I was told that membership in kubernetes-sigs is more or less automatic for members of those other groups.

**Comment by nikhita** [comment]
> If you want pointers to some of my contributions I could add those but I was told that membership in kubernetes-sigs is more or less automatic for members of those other groups.

@bswartz That's correct, you don't need to list your contributions. You are automatically eligible for kubernetes-sigs membership. :)

I've created PR #2655 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
