### ISSUE TITLE
REQUEST: New membership for lojies

### ISSUE THREAD

**Issue by lojies** [kubernetes/org#2651]
### GitHub Username
@lojies

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123 
- @Huang-Wei 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Alojies+

- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3Alojies+
- SIG projects I am involved with
/sig instrumentation
/sig node
/sig scheduling
/sig release

**Comment by neolit123** [comment]
Hi, lojies. I do not recall reviewing a lot PRs from you, myself. But +1
given you have that many.

Thank you.

**Comment by Huang-Wei** [comment]
+1

**Comment by nikhita** [comment]
@lojies thank you for all your contributions so far \o/

I've created PR #2655 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
