### ISSUE TITLE
REQUEST: New membership for qiiujian16

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/org#2652]
### GitHub Username

qiujian16

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @RainbowMango 
- @pmorie 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
[work-api](https://github.com/kubernetes-sigs/work-api)
sig-multicluster

**Comment by RainbowMango** [comment]
+1 from me.
Thanks for your contributions, dude.

**Comment by pmorie** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi, @qiujian16 👋  Thank you for all your contributions!

I've created PR #2664 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
