### ISSUE TITLE
REQUEST: New membership for nimbinatus

### ISSUE THREAD

**Issue by nimbinatus** [kubernetes/org#2653]
### GitHub Username
@nimbinatus

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mrbobbytables
- @castrojo (double-checking still that he can do so as an emeritus; draft will be removed once we're sure which way to go)

### List of contributions to the Kubernetes project
- Rebooting the community meeting (https://github.com/kubernetes/community/issues/5462)
- Reviewed https://github.com/kubernetes/contributor-site/pull/214
- SIG Contribex member

**Comment by mrbobbytables** [comment]
+1 from me \o/
/pony party

**Comment by castrojo** [comment]
+1 from me! Looking forward to that new energy that we need!

**Comment by nikhita** [comment]
@nimbinatus +1 from me as well, thank you for all your contributions so far \o/

I've created PR #2655 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
