### ISSUE TITLE
REQUEST: New membership for ike-ma

### ISSUE THREAD

**Issue by ike-ma** [kubernetes/org#2657]
### GitHub Username
@ike-ma

### Organization you are requesting membership in
@kubernetes

### Requirements
- [ Y ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ Y ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ Y ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ Y ] I am actively contributing to 1 or more Kubernetes subprojects
- [ Y ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ Y ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @SergeyKanzhelev 
- @ehashman 

#### PRs reviewed
- #97028 - Adding restart kubelet flag on e2e test 
- kubernetes/test-infra#20106  - Node E2E disruptive job
- #96775 - Kubelet exit on lock contention E2E test
- [WIP] Memory Swap KEP - https://github.com/kubernetes/enhancements/pull/2602#discussion_r616211595  
- Regularly attending SIG-Node meeting, and SIG-CI meeting 
  
#### SIG projects I am involved with
sig-node

**Comment by SergeyKanzhelev** [comment]
I support! Thank you @ike-ma for your contributions and looking forward for more!

**Comment by ehashman** [comment]
Hi @ike-ma,

As we previously discussed, I am not willing to sponsor individuals for org membership unless they have at least one merged PR. Please ping me when you have a PR merged or find another sponsor.

**Comment by savitharaghunathan** [comment]
Hi, @ike-ma 👋   Thank you for all your contributions!

I've created PR #2664 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by nikhita** [comment]
@ike-ma closing this issue for now. Please reopen once sponsors are ready. :)
