### ISSUE TITLE
Request: New Membership for AdamDang

### ISSUE THREAD

**Issue by AdamDang** [kubernetes/org#266]
### GitHub Username
@AdamDang 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markthink 
- @zhangxiaoyu-zidif 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/pulls?q=is%3Apr+author%3AAdamDang+archived%3Afalse+is%3Aclosed
- Issues responded to
https://github.com/issues?q=is%3Aissue+assignee%3AAdamDang+archived%3Afalse+is%3Aclosed
- SIG projects I am involved with
website

/area github-membership

**Comment by markthink** [comment]
+1

**Comment by zhangxiaoyu-zidif** [comment]
+1

**Comment by chenrui333** [comment]
+1, Thanks for your contributions on the sig-docs/website project!

**Comment by chenrui333** [comment]
better contribution display:
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AAdamDang+archived%3Afalse+is%3Aclosed+is%3Amerged+repo%3Akubernetes%2Fwebsite

**Comment by zacharysarah** [comment]
+1, thanks for joining!

**Comment by AdamDang** [comment]
@zacharysarah @chenrui333  @markthink  @zhangxiaoyu-zidif 
Thanks a lot for your kind support and help. I've learned so much in the past days from the community.
And I'd like to do more for our community! :)

**Comment by mrbobbytables** [comment]
Hey there @AdamDang , my apologies for all the delays and thank you for all your contributions so far :) 
I've created PR #296  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
