### ISSUE TITLE
REQUEST: New membership for chrisnegus

### ISSUE THREAD

**Issue by chrisnegus** [kubernetes/org#2660]
### GitHub Username
@chrisnegus
### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pi-victor
- @savitharaghunathan

### List of contributions to the Kubernetes project
- Selected as shadow for SIG Docs 1.22 Release Team

**Comment by PI-Victor** [comment]
+1 

Welcome to the SIG Docs release team for v1.22 @chrisnegus

**Comment by savitharaghunathan** [comment]
+1

Hi @chrisnegus 👋 Welcome to the 1.22 Release Team 🎉 

/pony

**Comment by savitharaghunathan** [comment]
Hi, @chrisnegus 👋 Glad to have you on the 1.22 RT 🎉 

I've created PR #2664 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
