### ISSUE TITLE
REQUEST: New membership for ramrodo

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/org#2661]
### GitHub Username
@ramrodo

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mkorbi
- @guineveresaenger

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
  - https://github.com/kubernetes/sig-release/pull/1398

- SIG projects I am involved with:
  - CI Signal shadow for Kubernetes 1.22

**Comment by mkorbi** [comment]
/lgtm
welcome in the team :)

**Comment by savitharaghunathan** [comment]
+1

Welcome to the 1.22 Release Team 🎉 

/pony party

**Comment by savitharaghunathan** [comment]
Hi, @ramrodo 👋 Glad to have you on the 1.22 RT 🎉 

I've created PR #2664 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
