### ISSUE TITLE
REQUEST: New membership for supriya-premkumar

### ISSUE THREAD

**Issue by supriya-premkumar** [kubernetes/org#2662]
### GitHub Username
@supriya-premkumar

### Organization you are requesting membership in
@kubernetes

### Requirements
- [ x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [  x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [  x ] I am actively contributing to 1 or more Kubernetes subprojects
- [  x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [  x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims
-  @savitharaghunathan
- @gsaenger

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/kubernetes/kubernetes/pull/100801
   - https://github.com/kubernetes/kubernetes/pull/99288
   - https://github.com/kubernetes/test-infra/pull/20934
   - https://github.com/kubernetes/test-infra/pull/21276
- Issues responded to
   - https://github.com/kubernetes/kubernetes/issues/99673
   - https://github.com/kubernetes/kubernetes/issues/80481
   - https://github.com/kubernetes/kubernetes/issues/99243
   - https://github.com/kubernetes/test-infra/issues/18388

- SIG projects I am involved with
   - currently in works with sig-autoscaling
   - https://github.com/kubernetes-sigs/kubetest2/pull/111

**Comment by dims** [comment]
+1 from me. welcome!

**Comment by savitharaghunathan** [comment]
@supriya-premkumar can you change my id to @savitharaghunathan in the sponsors' list?

+1 from me
Welcome to the 1.22 Release Team 🎉 

/pony party

**Comment by guineveresaenger** [comment]
+1 from me! Yay!

**Comment by savitharaghunathan** [comment]
Hi, @supriya-premkumar 👋 Glad to have you on the 1.22 RT 🎉 

I've created PR #2664 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
