### ISSUE TITLE
REQUEST: New membership for ritpanjw

### ISSUE THREAD

**Issue by ritpanjw** [kubernetes/org#2665]
### GitHub Username
@ritpanjw

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @PI-Victor 
- @savitharaghunathan 

### List of contributions to the Kubernetes project
- Selected as shadow for SIG Docs 1.22 Release Team

**Comment by PI-Victor** [comment]
+1
Welcome to the SIG Docs release team for v1.22 @ritpanjw

**Comment by pmmalinov01** [comment]
+1
Welcome to the  Kubernetes family 🎉   Happy to have you here

**Comment by ritpanjw** [comment]
Thank you @PI-Victor @pmmalinov01 , excited to join the Kubernetes family

**Comment by palnabarun** [comment]
@ritpanjw -- Welcome to the release team! 🎉 

I have filed PR# to add you to the org. Once that merges, you will get a member invite notification.

/assign
