### ISSUE TITLE
REQUEST: New membership for moonming

### ISSUE THREAD

**Issue by moonming** [kubernetes/org#2667]
### GitHub Username
@moonming

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rikatz
- @ElvinEfendi

### List of contributions to the Kubernetes project
- PRs reviewed / authored: 
    - https://github.com/kubernetes/ingress-nginx/commits?author=moonming
- SIG projects I am involved with `Ingress NGINX`

**Comment by rootsongjc** [comment]
+1

**Comment by rikatz** [comment]
+1

@moonming is proposing to be one of the maintainers/triagers of ingress-nginx :)

Thanks

**Comment by savitharaghunathan** [comment]
Hi @moonming 👋  Can you add one more sponsor? @rootsongjc is not listed as reviewer or approver in the k8s org. 

From the guidelines,

```Sponsors must be reviewers or approvers in at least 1 OWNERS file either in any repo in the Kubernetes org, or the org they are sponsoring for.```

**Comment by ElvinEfendi** [comment]
+1

Looking forward to collaborate with you on ingress-nginx @moonming!

**Comment by tao12345666333** [comment]
+1

**Comment by moonming** [comment]
> +1
> 
> Looking forward to collaborate with you on ingress-nginx @moonming!

thanks:)

**Comment by palnabarun** [comment]
@moonming -- thank you for your contributions to ingress-nginx! 💯 

I have filed PR #2677 to add you to the org. Once that merges, you will receive a member invite notification.

/assign
