### ISSUE TITLE
New Membership for hhoover

### ISSUE THREAD

**Issue by hhoover** [kubernetes/org#267]
### GitHub Username
@hhoover

### Organization you are requesting membership in
@kubernetes

### Requirements
- [:heavy_check_mark:] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [:heavy_check_mark:] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [:heavy_check_mark:] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [:heavy_check_mark:] I am actively contributing to 1 or more Kubernetes subprojects
- [:heavy_check_mark:] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [:heavy_check_mark:] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @alexbrand 

### List of contributions to the Kubernetes project
- Issues/PRs
https://github.com/kubernetes/community/issues?utf8=%E2%9C%93&q=author%3Ahhoover+
https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=author%3Ahhoover+
- SIG projects I am involved with
sig-release
Co-organizer of [Kubernetes San Antonio](https://www.meetup.com/Kubernetes-San-Antonio/members/?op=leaders)

/area github-membership

**Comment by justaugustus** [comment]
Enthusiastic +1!

**Comment by alexbrand** [comment]
+1

**Comment by justaugustus** [comment]
Hey @hhoover, I've created #271 to add you to the kubernetes org. Once that merges, you should receive an invite from our automation framework.

Welcome to the party! :)
/assign
