### ISSUE TITLE
REQUEST: New membership for lambdanis

### ISSUE THREAD

**Issue by lambdanis** [kubernetes/org#2670]
### GitHub Username
@lambdanis

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mkorbi
- @guineveresaenger

### List of contributions to the Kubernetes project
I'm a CI Signal shadow for Kubernetes 1.22

**Comment by mkorbi** [comment]
yeah! welcome in the team
👍

**Comment by pmmalinov01** [comment]
+1
Welcome and thank you for helping 🚢 👪 🍰

**Comment by guineveresaenger** [comment]
+1 from me! <3

**Comment by palnabarun** [comment]
@lambdanis -- Welcome to the release team! 🎉 

I have filed PR #2677 to add you to the org. Once that merges, you will get a member invite notification.

/assign
