### ISSUE TITLE
Donate k8s service binding spec repo to the service catalog SIG

### ISSUE THREAD

**Issue by jhvhs** [kubernetes/org#2671]
### New Repo, Staging Repo, or migrate existing

migrate existing repository https://github.com/k8s-service-bindings/spec

### Requested name for new repository
service-binding-spec

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
arthurdm, nebhale, and jhvhs

### If not a staging repo, who should have write access
arthurdm, nebhale, scothis, and sbose78

### If not a staging repo, who should be listed as approvers in OWNERS
arthurdm, nebhale

### If not a staging repo, who should be listed in SECURITY_CONTACTS
arthurdm, nebhale

### What should the repo description be
Service Binding Specification for Kubernetes

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject for sig-service-catalog called service-binding-spec

**Comment by jhvhs** [comment]
@nikhita Can you help with this issue please?

**Comment by mrbobbytables** [comment]
Which SIG is taking over stewardship of it once its migrated? It needs approval from the leads before we can move to next steps.

**Comment by mrbobbytables** [comment]
Oh wait, @jhvhs you're a lead of service catalog, my bad^^;;; I'm assuming it's going there?

**Comment by baijum** [comment]
@jhvhs In the issue description, the proposed repo name is "service-bindings-spec" whereas the sub-project name given is "service-binding-spec" in the late sentence. (bindings vs binding)

I think the sub-project name also should be changed to "service-bindings-spec".

**Comment by nebhale** [comment]
@mrbobbytables The license boilerplate is updated.

**Comment by baijum** [comment]
> In the issue description, the proposed repo name is "service-bindings-spec" whereas the sub-project name given is "service-binding-spec" in the last sentence. (bindings vs binding)
> 
> I think the sub-project name also should be changed to "service-bindings-spec".

On second thought, I think it's better to align with the spec title where we use the singular form: Service Binding Specification. So, both the repo name and sub-project name could be `service-binding-spec`

cc. @nebhale @arthurdm

**Comment by nikhita** [comment]
/assign

@baijum @jhvhs @nebhale There are a few more prerequisites before we can migrate the repo:

- There is a`NOTICE` file at the root of the repo. This should not be present because `NOTICE` files have other legal connotations.
- Please update `README.md` with the community, discussion and support + code of conduct sections as in the template - https://github.com/kubernetes/kubernetes-template-project#community-discussion-contribution-and-support

-  There are a few contributors who haven't signed the CNCF CLA. The [rules for donated repos](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories) say that all contributors should have signed the CNCF Individual CLA or CNCF Corporate CLA. You will need to reach out to the contributors listed below and ask them to sign the CLA.
    - @pmacik
    - @nebhale
    - @scothis
    - @metacosm
    - @ianpartridge
    - @matthewpwilson
    - @jmesnil
    - @akashshinde
    - @AndrewJSchofield
    - @joicemjoseph

**Note**: if your name is listed above, could you please sign the CNCF CLA so that we can migrate the `k8s-service-bindings/spec` repo to Kubernetes? Instructions on how to sign the CLA can be found [here](https://github.com/kubernetes/community/blob/master/CLA.md). Thank you! :)

**Comment by nikhita** [comment]
@arthurdm, @nebhale, @scothis, and @sbose78 - you are listed in the issue body for admin/approver access. To get this access, you need to be a part of the @kubernetes-sigs GitHub org. Can you please [apply](https://github.com/kubernetes/community/blob/master/community-membership.md#member) for membership?

**Comment by baijum** [comment]
> * Please update `README.md` with the community, discussion and support + code of conduct sections as in the template - https://github.com/kubernetes/kubernetes-template-project#community-discussion-contribution-and-support

PR: https://github.com/k8s-service-bindings/spec/pull/159

**Comment by baijum** [comment]
> * @pmacik
> * @nebhale
> * @scothis
> * @metacosm
> * @ianpartridge
> * @matthewpwilson
> * @jmesnil
> * @akashshinde
> * @AndrewJSchofield
> * @joicemjoseph

Updates:

- `pmacik` - Signed
- `metacosm` - Contacted
- `jmesnil` - Contacted
- `akashshinde` - Contacted
- `joicemjoseph` - Contacted

@arthurdm Can you help with these contributors?
- `ianpartridge`
- `matthewpwilson`
- `AndrewJSchofield`

@nebhale @scothis Not sure why your account shows that it's not signed. Can you check if the CLA account has linked with GitHub. From [the FAQ](https://identity.linuxfoundation.org/projects/cncf)

> 6. I signed the ICLA with the wrong email, what do I do?
>
> Neither the email on the ICLA (captured from you Linux Foundation ID profile when you signed) nor the current email on the profile matters for passing the GitHub check.
>
> For a PR to pass, each commit must pass this check: the Github user that the commit is attributed to (based on a match between the commit authorship and Github profile) must be linked to a Linux Foundation ID user (on the "social network logins" tab), who is authorized by a signed ICLA and/or a CCLA.

**Comment by metacosm** [comment]
@baijum how do I sign the CLA if I'm part of an organization that already has signed it?

**Comment by baijum** [comment]
> * There is a`NOTICE` file at the root of the repo. This should not be present because `NOTICE` files have other legal connotations.

@nikhita We need to add this file if we are not able to contact any of the contributors to sign the CLA, right? Is that going to be a post-migration activity?

**Comment by jmesnil** [comment]
I signed up the CLA

**Comment by scothis** [comment]
I should be signed now. 

...I had signed in the past, maybe it was lost when I had multiple LF accounts merged.

**Comment by baijum** [comment]
> @baijum how do I sign the CLA if I'm part of an organization that already has signed it?

@nikhita I am not sure how the organization CLA works.  BTW, his commits have this email address `metacosm@users.noreply.github.com`. I am not sure if that's causing the issue.

**Comment by arthurdm** [comment]
@AndrewJSchofield has left IBM, but should be able to still sign the CLA as an individual.

@matthewpwilson / @ianpartridge - can you please sign the CLA for your contributions to the k8s service binding spec?

**Comment by joicemjoseph** [comment]
cli signed

**Comment by baijum** [comment]
> > @baijum how do I sign the CLA if I'm part of an organization that already has signed it?
> 
> @nikhita I am not sure how the organization CLA works. BTW, his commits have this email address `metacosm@users.noreply.github.com`. I am not sure if that's causing the issue.

He has confirmed to me that he has signed in with his organization's credentials at https://identity.linuxfoundation.org/projects/cncf . I think that should be sufficient to be authorized.

**Comment by sbose78** [comment]
Sure! Will do!

**Comment by baijum** [comment]
> * `pmacik` - Signed
> * `metacosm` - Contacted (Update: [Signed using Corporate CLA](https://github.com/kubernetes/org/issues/2671#issuecomment-854851869))
> * `jmesnil` - Contacted (Update: [Signed](https://github.com/kubernetes/org/issues/2671#issuecomment-854779961))
> * `akashshinde` - Contacted (Update: Signed)
> * `joicemjoseph` - Contacted (Update: [Signed](https://github.com/kubernetes/org/issues/2671#issuecomment-854829292))

Update: All the contributors I contacted have signed the CLA.

**Comment by nikhita** [comment]
> @nikhita We need to add this file if we are not able to contact any of the contributors to sign the CLA, right? Is that going to be a post-migration activity?

While the rules say that, we've avoided adding the `NOTICE` file in the past because it's desirable to have all contributors sign the CLA. In the past, we've also waited for 2-3 months for all contributors to sign the CLA.

**Comment by sbose78** [comment]
Applied for membership: https://github.com/kubernetes/org/issues/2768

**Comment by nebhale** [comment]
* Applied for membership: kubernetes/org#2774
* Signed the CLA under multiple identities

**Comment by scothis** [comment]
Applied for membership: https://github.com/kubernetes/org/issues/2775

**Comment by nebhale** [comment]
> Please update README.md with the community, discussion and support + code of conduct sections as in the template - https://github.com/kubernetes/kubernetes-template-project#community-discussion-contribution-and-support

Completed.

**Comment by arthurdm** [comment]
Applied for membership: https://github.com/kubernetes/org/issues/2776
