### ISSUE TITLE
REQUEST: New membership for jgavinray

### ISSUE THREAD

**Issue by jgavinray** [kubernetes/org#2672]
### GitHub Username
@jgavinray

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @MonzElmasry
- @savitharaghunathan

### List of contributions to the Kubernetes project
I'm a bug triage shadow for Kubernetes 1.22

**Comment by MonzElmasry** [comment]
Thanks @jgavinray , Happy to have you :rocket:

**Comment by savitharaghunathan** [comment]
+1
Welcome to the 1.22 Release team! 🎉 

/pony party

**Comment by guineveresaenger** [comment]
+1 welcome to 1.22! 🎉

**Comment by palnabarun** [comment]
@jgavinray -- Welcome to the release team! 🎉 

I have filed PR #2677 to add you to the org. Once that merges, you will get a member invite notification.

/assign
