### ISSUE TITLE
REQUEST: New membership for @Damans227

### ISSUE THREAD

**Issue by Damans227** [kubernetes/org#2673]
### GitHub Username
@Damans227

### Organization you are requesting membership in
e.g. (at)kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @guineveresaenger
- @pmmalinov01 

### List of contributions to the Kubernetes project

- PR merged: https://github.com/kubernetes/sig-release/pull/1542
- Release Notes Shadow for 1.22

**Comment by guineveresaenger** [comment]
+1 yes! welcome! ❤️

**Comment by savitharaghunathan** [comment]
+1
Welcome to the 1.22 Release Team @Damans227  🎉

/pony party

**Comment by pmmalinov01** [comment]
+1
Welcome to the team 🚢 👪 👍🏼

**Comment by palnabarun** [comment]
@Damans227 -- Welcome to the release team! 🎉 

I have filed PR #2677 to add you to the org. Once that merges, you will get a member invite notification.

/assign
