### ISSUE TITLE
REQUEST: New membership for kunal-kushwaha

### ISSUE THREAD

**Issue by kunal-kushwaha** [kubernetes/org#2676]
### GitHub Username
@kunal-kushwaha

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Pensu
- @savitharaghunathan

### List of contributions to the Kubernetes project
- PRs reviewed / authored: Sig-Usability Blog WIP
- Issues responded to: contributor-tweets, SIG Profiling Articles
- SIG projects I am involved with: Kubernetes 1.22 Release Shadow, Marketing & ContribEx

**Comment by Pensu** [comment]
+1

Welcome! 👍

**Comment by dims** [comment]
welcome @kunal-kushwaha 

+1

**Comment by palnabarun** [comment]
@kunal-kushwaha -- Welcome to the release team! 🎉 

I have filed PR #2677 to add you to the org. Once that merges, you will get a member invite notification.

/assign
