### ISSUE TITLE
New Repo kubernetes-sigs/network-policy-api

### ISSUE THREAD

**Issue by astoycos** [kubernetes/org#2678]
### New Repo, Staging Repo, or migrate existing

new repository

### Requested name for new repository
network-policy-api

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
astoycos, abhiraut, rikatz

### If not a staging repo, who should have write access
astoycos, abhiraut, rikatz

### If not a staging repo, who should be listed as approvers in OWNERS
astoycos, abhiraut, rikatz

### If not a staging repo, who should be listed in SECURITY_CONTACTS
astoycos, abhiraut, rikatz

### What should the repo description be

This sig-network sub-project addresses further work involving Kubernetes network security beyond the initial NetworkPolicy resource

### What SIG and subproject does this fall under in sigs.yaml

sig-network

### Approvals

thockin, caseydavenport, dcbw, aojea

### Additional context for request

closes [#5747](https://github.com/kubernetes/community/issues/5747)

Any additional information or context to describe the request:

After much discussion in the [Network Policy API Meeting](https://docs.google.com/document/d/1AtWQy2fNa4qXRag9cCp5_HsefD7bxKe3ea2RPn8jnSs), on the [KEP for Cluster Scoped Network Policy](https://github.com/kubernetes/enhancements/pull/2522/files#r600361541)  and in slack([dis 1](https://kubernetes.slack.com/archives/C01CWSHQWQJ/p1619120255062800) [dis 2](https://kubernetes.slack.com/archives/C09QYUH5W/p1618570463278100)) we (the sig-network-policy subgroup within [Sig-Network](https://github.com/kubernetes/community/tree/master/sig-network)) have decided that the best way to iterate on Network Policy, such as with the cluster-scoped network policy and a possible Network Policy V2, is to create a repo which will serve to house CRDs supported by the group.  This follows the same pattern completed  by the [Kubernetes Gateway API](https://github.com/kubernetes-sigs/gateway-api).  It has also been agreed upon that this repo should be called `network-policy-api` as it relates to future work involving k8's network security.   

Putting the project outside of `kubernetes/kubernetes` will allow for faster iterations and greater design freedom for new objects related to kubernetes networking security 

This issue serves to open up further discussion from the greater Sig-Network group around how the internals (CRD groups, api approval process etc should work) and to hopefully get permission to create the new repository.

**Comment by caseydavenport** [comment]
/lgtm

thanks!

**Comment by nikhita** [comment]
Apologies for the delay. The repo has been created - https://github.com/kubernetes-sigs/network-policy-api

Also created:
- https://github.com/kubernetes/org/pull/2697 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/5773 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.
---

@astoycos Since you are not a member of @kubernetes/@kubernetes-sigs GitHub orgs, you'll first need to [apply for membership](https://github.com/kubernetes/community/blob/master/community-membership.md#member). Once you are added as a member, you can be added in OWNERS and GitHub teams. :+1:

**Comment by rikatz** [comment]
@nikhita I thing this can be closed then? :D

**Comment by nikhita** [comment]
@rikatz https://github.com/kubernetes/community/pull/5773 still needs to merge :)
