### ISSUE TITLE
REQUEST: New membership for skrishna-unix

### ISSUE THREAD

**Issue by skrishna-unix** [kubernetes/org#2679]
### GitHub Username

@skrishna-unix

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @Pensu
- @savitharaghunathan

### List of contributions to the Kubernetes project

- SIG projects I am involved with: Kubernetes 1.22 Release Shadow

**Comment by Pensu** [comment]
+1

Welcome!

**Comment by palnabarun** [comment]
+1

/honk

**Comment by palnabarun** [comment]
@skrishna-unix -- Welcome to the Release Team! 🎉 

I have filed PR #2681 to add you to the org. Once that merges, you will receive a membership invite notification.

/assign
