### ISSUE TITLE
github.com/kubernetes-csi/csi-lib-utils

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/org#268]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
csi-lib-utils

### Which Organization should it reside
kubernetes-csi

### If not a staging repo, who should have admin access
@saad-ali 

### If not a staging repo, who should have write access
@saad-ali 

### If a new repo, who should be listed as approvers in OWNERS
@saad-ali 
### If a new repo, who should be listed in SECURITY_CONTACTS
@saad-ali 

### What should the repo description be
by default we will set it to "created due to (link to this issue)"

### What SIG and subproject does this fall under in sigs.yaml
sig-storage

### Approvals
Issue submitted as per @saad-ali  request

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

### Additional context for request
Repo will be used for shared libraries used by CSI external components

/area github-repo

**Comment by saad-ali** [comment]
I approve the creation of `github.com/kubernetes-csi/csi-lib-utils` on behalf of sig-storage.

> **What should the repo description be**
>
> by default we will set it to "created due to (link to this issue)"

Let's make the description: `Common code for Kubernetes CSI sidecar containers (e.g. `external-attacher`, `external-provisioner`, etc.). `

**Comment by saad-ali** [comment]
@cblecker or @spiffxp can you help with this? We need this ASAP

**Comment by cblecker** [comment]
/unassign @saad-ali 
/assign

Yeah, I can kick this out.

**Comment by cblecker** [comment]
Okay, should be good to go. Can you add this to sigs.yaml?

**Comment by saad-ali** [comment]
Done: https://github.com/kubernetes/community/pull/2989

Thanks a lot for the quick turn around @cblecker!!

**Comment by cblecker** [comment]
Cool! Please let me know if you need anything else.
/close
