### ISSUE TITLE
REQUEST: New membership for @simcard0000

### ISSUE THREAD

**Issue by simcard0000** [kubernetes/org#2683]
### GitHub Username
@simcard0000

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects _(although I have not contributed to any Kubernetes subprojects yet, I am a release team shadow for 1.22)_
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pmmalinov01
- @savitharaghunathan

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with _(just joined the release team as a shadow for 1.22)_

**Comment by pmmalinov01** [comment]
LGTM! welcome to Kubernetes 🎉 🚢 💯

**Comment by savitharaghunathan** [comment]
+1

Welcome to the 1.22 Release Team! 🎉 

/pony party

**Comment by guineveresaenger** [comment]
+1 happy to sponsor your org membership! :D

**Comment by pmmalinov01** [comment]
Hey, @palnabarun do you have time to handle this one also? https://github.com/kubernetes/kubernetes/pull/101754 is waiting on this.

**Comment by palnabarun** [comment]
@simcard0000 -- Welcome to the Kubernetes Release Team! 🎉 

I have filed the PR #2690 to add you to the @kubernetes org. Once that merges, you will receive a membership invite notification.

---

@pmmalinov01 -- Thank you for the ping! :)
