### ISSUE TITLE
Request to archive `cosi-driver-minio`

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/org#2687]
### Repository to archive
https://github.com/kubernetes-sigs/cosi-driver-minio

### Repository and/or sig subproject owners that are approving this archival
@saad-ali @xing-yang @wlan0 @brahmaroutu

### When should this be done
Anytime.

### Additional context for request

Given Minio's change in license from Apache2 to AGPL, running CI in CNCF owned repos won't be possible. Therefore, Minio is planning to host their COSI driver in their own external repo. And this repo can be archived.

CC @jeffvance

**Comment by xing-yang** [comment]
+1

**Comment by jeffvance** [comment]
+1

**Comment by nikhita** [comment]
Repo has been archived - https://github.com/kubernetes-retired/cosi-driver-minio

- https://github.com/kubernetes/org/pull/2773 removes GitHub teams
- https://github.com/kubernetes/community/pull/5822 removes the repo from sigs.yaml

Also notified k-dev: https://groups.google.com/g/kubernetes-dev/c/Tf-OiA69Z7c

This issue can be closed once https://github.com/kubernetes/community/pull/5822 gets merged.

**Comment by tuxpeople** [comment]
@saad-ali Given that this is more than 2 yrs ago, do you have more information on when and where the external MinIO repo is coming? Wasn't able to find one. Sorry for bothering you with this question, but your _Additional context for request_ sounds like you had some insights back when you filed this request.

**Comment by xing-yang** [comment]
cc @wlan0

**Comment by wlan0** [comment]
Yes, please archive

**Comment by mrbobbytables** [comment]
The repo has been archived for more than 2 years.^^;;

**Comment by tuxpeople** [comment]
I'm sorry for the confusion. I thought it was clear that the repository has been archived since 2yr. Based on the text of the issue, I was just wondering if @saad-ali has more insights about this repository's successor he announced. As I'm keen to get my hands on said successor. Nevertheless, once again sorry for the trouble I caused.
