### ISSUE TITLE
REQUEST: New membership for mauriciopoppe

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes/org#2688]
### GitHub Username
mauriciopoppe

### Organization you are requesting membership in
kubernetes, kubernetes-csi, kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @msau42
- @ddebroy 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-csi/external-snapshotter/pull/504
  - https://github.com/kubernetes-csi/csi-proxy/pull/124
  - https://github.com/kubernetes-csi/csi-proxy/pull/120
  - https://github.com/kubernetes/kubernetes/pull/100548
  - https://github.com/kubernetes/kubernetes/pull/100377
  - https://github.com/kubernetes/kubernetes/pull/100205
  - https://github.com/kubernetes/kubernetes/pull/100540
  - https://github.com/kubernetes/kubernetes/pull/100057
  - https://github.com/kubernetes/kubernetes/pull/99346
  - https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/742
  - https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/705

- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/101172
  - https://github.com/kubernetes-csi/csi-release-tools/issues/145
 
- SIG projects I am involved with (sig-storage)

**Comment by msau42** [comment]
+1 Mauricio has been doing a lot of work with csi and windows!

**Comment by ddebroy** [comment]
+1 Mauricio is actively involved and contributing to csi-proxy and kubernetes!

**Comment by palnabarun** [comment]
@mauriciopoppe -- thank you for all your contributions to the project! 🎉 

I have filed the PR #2690 to add you to the @kubernetes, @kubernetes-csi and @kubernetes-sigs orgs. Once that merges, you will receive membership invite notifications for each of the GitHub organizations.
