### ISSUE TITLE
REQUEST: New membership for wangyysde

### ISSUE THREAD

**Issue by wangyysde** [kubernetes/org#2689]
### GitHub Username
@wangyysde

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123 
- @pacoxu

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/101693            
  - https://github.com/kubernetes/kubernetes/pull/101307            
  - https://github.com/kubernetes/kubernetes/pull/101448            
  - https://github.com/kubernetes/kubernetes/pull/101057            
  - https://github.com/kubernetes/kubernetes/pull/101247            
  - https://github.com/kubernetes/website/pull/27518                            
  - https://github.com/kubernetes/kubernetes/pull/100942            
  - https://github.com/kubernetes/website/pull/27299     
 
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/101614
  - https://github.com/kubernetes/kubeadm/issues/2453
  - https://github.com/kubernetes/kubernetes/issues/99650
  - https://github.com/kubernetes/kubernetes/issues/100174
  - https://github.com/kubernetes/kubernetes/issues/99630
- SIG projects I am involved with: sig-clusterlifecycle kubeadm

**Comment by pacoxu** [comment]
+1
for works in kubeadm and also some tries on `--image-repo` related settings and issues.

**Comment by neolit123** [comment]
+1. Thank you for the work thus far.

**Comment by palnabarun** [comment]
@wangyysde, thank you for all your contributions so far :)

I've created PR #2707 to add you to the GitHub org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
