### ISSUE TITLE
New repository for Container Object Storage Interface - cosi-driver-sample

### ISSUE THREAD

**Issue by wlan0** [kubernetes/org#2701]
### New Repo, Staging Repo, or migrate existing

New repository

### Requested name for new repository
cosi-driver-sample

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@jsafrane
@msau42
@saad-ali
@xing-yang

### If not a staging repo, who should have write access
@jsafrane
@msau42
@saad-ali
@xing-yang
@wlan0
@krishchow 

### If not a staging repo, who should be listed as approvers in OWNERS
@saad-ali
@jsafrane
@msau42
@xing-yang
@wlan0
@krishchow 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@jsafrane
@msau42
@saad-ali
@xing-yang
@wlan0
@krishchow 

### What should the repo description be
Sample Driver that provides reference implementation for Container Object Storage Interface (COSI) api

### What SIG and subproject does this fall under in sigs.yaml
SIG: sig-storage, subproject: kubernetes-cosi

### Approvals
Need sig-storage approval from: @saad-ali and @xing-yang
Please refer to KEP: kubernetes/enhancements#2100
Repos created before for this project apart from this: #2039 and #1942

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

### Additional context for request
COSI is actively developed projects under Sig-Storage and it is required to provide a implementation of a sample driver to test and run e2e use cases using that driver. This driver will be part of the COSI implementation similar to host path driver provided along CSI.

**Comment by nikhita** [comment]
/assign

Repo has been created - https://github.com/kubernetes-sigs/cosi-driver-sample

Also created:
- https://github.com/kubernetes/org/pull/2711 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/5778 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue. :+1:
