### ISSUE TITLE
REQUEST: New membership for wangyx1992

### ISSUE THREAD

**Issue by wangyx1992** [kubernetes/org#2702]
### GitHub Username
@wangyx1992

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Huang-Wei 
- @ehashman 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  [https://github.com/pulls?q=+is%3Apr+author%3Awangyx1992+archived%3Afalse+](url)
- Issues responded to
- SIG projects I am involved with
  /sig scheduling
  /sig node
  /sig testing
  /sig api-machinery

**Comment by Huang-Wei** [comment]
+1

**Comment by palnabarun** [comment]
@wangyx1992, thank you for all your contributions so far :)

I've created PR #2707 to add you to the GitHub org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
