### ISSUE TITLE
REQUEST: New membership for KofClubs

### ISSUE THREAD

**Issue by KofClubs** [kubernetes/org#2703]
### GitHub Username
@KofClubs

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Huang-Wei
- @neolit123
- @pacoxu

#### PRs reviewed / authored
- https://github.com/kubernetes/kubernetes/pull/99247 (Merged)
- https://github.com/kubernetes/kubernetes/pull/99387 (Merged)
- https://github.com/kubernetes/kubernetes/pull/100004 (Merged)
- https://github.com/kubernetes/kubernetes/pull/100609 (Draft)
- https://github.com/kubernetes/kubernetes/pull/101010 (Closed)
- https://github.com/kubernetes/kubernetes/pull/101014 (Open)
- https://github.com/kubernetes/kubernetes/pull/101600 (Open)
- https://github.com/kubernetes/kubernetes/pull/101774 (Merged)
- https://github.com/kubernetes/website/pull/27930 (Merged)
#### Issues responded to
- https://github.com/kubernetes/kubeadm/issues/2039
- https://github.com/kubernetes/kubeadm/issues/2251
- https://github.com/kubernetes/kubernetes/issues/92229
- https://github.com/kubernetes/kubernetes/issues/94009
- https://github.com/kubernetes/kubernetes/issues/101008
I replied to the above issues to assign jobs.
#### SIG projects I am involved with
- SIG: scheduling
- Subproject: kubeadm
In the future, I shall devote myself to making valuable contributions in the above fields.

**Comment by pacoxu** [comment]
+1

**Comment by palnabarun** [comment]
@KofClubs, thank you for all your contributions so far :)

I've created PR #2707 to add you to the GitHub org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
