### ISSUE TITLE
REQUEST: New membership for GreenApple10

### ISSUE THREAD

**Issue by GreenApple10** [kubernetes/org#2704]
GitHub Username
@GreenApple10

Organization you are requesting membership in
@kubernetes

Requirements
 - [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
 - [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
 - [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
 - [X] I am actively contributing to 1 or more Kubernetes subprojects
 - [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
 - [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors
- @JornShen
- @caesarxuchao
- @SataQiu

List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pull/101523
  https://github.com/kubernetes/kubernetes/pull/101187
  https://github.com/kubernetes/kubernetes/pull/101002
  https://github.com/kubernetes/kubernetes/pull/101508
  https://github.com/kubernetes/kubernetes/pull/101573

  https://github.com/kubernetes/website/pull/28140
  https://github.com/kubernetes/website/pull/28146
  https://github.com/kubernetes/website/pull/28145
  https://github.com/kubernetes/website/pull/28128
  https://github.com/kubernetes/website/pull/28126

- SIG projects I am involved with
sig-dos
sig-api-machinery
sig-cli
sig-cloud-provider

**Comment by JornShen** [comment]
+1 
I sponsor

**Comment by caesarxuchao** [comment]
+1

**Comment by palnabarun** [comment]
Hi @GreenApple10 👋🏽, Thank you for filing the membership request. 🎉 

Unfortunately, @JornShen can't sponsor you for this as they are [not a reviewer/approver in any OWNERS file](https://cs.k8s.io/?q=JornShen&i=fosho&files=OWNERS&excludeFiles=vendor%2F&repos=).

Can you please ask one more person satisfying the [sponsorship guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) to sponsor you?

**Comment by SataQiu** [comment]
+1 @GreenApple10 
Thanks for your contribution to the Kubernetes Chinese Community

**Comment by GreenApple10** [comment]
> +1 @GreenApple10
> Thanks for your contribution to the Kubernetes Chinese Docs

thanks

**Comment by GreenApple10** [comment]
ping @palnabarun

**Comment by palnabarun** [comment]
@GreenApple10 -- I have filed PR #2742 to add you to the @kubernetes org.

Once it merges, you will receive a membership notification.

Welcome again to @kubernetes!!! 🎉
