### ISSUE TITLE
REQUEST: New membership for Priyankasaggu11929

### ISSUE THREAD

**Issue by Priyankasaggu11929** [kubernetes/org#2712]
### GitHub Username
@Priyankasaggu11929

### Organization you are requesting membership in
@kubernetes, @kubernetes-sigs @kubernetes-client/python

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @roycaihw 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - ` kubernetes-client /python`
        - https://github.com/kubernetes-client/python/pull/1454
        - https://github.com/kubernetes-client/python/pull/1452
        - https://github.com/kubernetes-client/python/pull/1450
        - https://github.com/kubernetes-client/python/pull/1448
        - https://github.com/kubernetes-client/python/pull/1437
        - https://github.com/kubernetes-client/python/pull/1435
        - https://github.com/kubernetes-client/python/pull/1433
    - `kubernetes/test-infra`
        - https://github.com/kubernetes/test-infra/pull/22157
        - https://github.com/kubernetes/test-infra/pull/22178
    - `kubernetes/image-builder`
        - https://github.com/kubernetes-sigs/image-builder/pull/606
        - https://github.com/kubernetes-sigs/image-builder/pull/610
    - `containerd/zfs`
        - https://github.com/containerd/zfs/pull/47
    - `google/cadvisor`
        - https://github.com/google/cadvisor/pull/2870
    - `microsoft/hcsshim`
        - https://github.com/microsoft/hcsshim/pull/1027 
    - ` kubernetes/community `
        - https://github.com/kubernetes/community/pull/4896
- Issues responded to
    - https://github.com/kubernetes-client/python/issues/1413
    - https://github.com/kubernetes-client/python/issues/1402
    - https://github.com/kubernetes-client/python/pull/1440#issuecomment-828947667

- SIG projects I am involved with
  - kubernetes-client/python
  - sig-auth

**Comment by nikhita** [comment]
+1 from me as well, but you will need another non-VMware sponsor too :)

/meow

**Comment by dims** [comment]
+1 from me. Welcome!

**Comment by roycaihw** [comment]
+1 :) Welcome!

**Comment by palnabarun** [comment]
@Priyankasaggu11929 -- Thank you for your contribution to the Kubernetes Python client and help with updating the project dependencies! 🎉 

I have filed PR #2724 to add you to the requested Kubernetes organizations. Once, the PR merges you will receive invitations to join them.

/assign
/honk
