### ISSUE TITLE
Request for new repo: kubernetes/pod-security-admission

### ISSUE THREAD

**Issue by tallclair** [kubernetes/org#2713]
### New Repo, Staging Repo, or migrate existing
new staging repo

### Requested name for new repository
pod-security-admission

### Which Organization should it reside
kubernetes

### What should the repo description be
Kubernetes Pod Security Standards implementation - https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/2579-psp-replacement/README.md

(KEP link will be replaced with a documentation link once the docs exist)

### What SIG and subproject does this fall under in sigs.yaml
new subproject for sig-auth

### Approvals
**Pending:** https://groups.google.com/g/kubernetes-sig-architecture/c/T3l02acvHfE

### Additional context for request
This repository is for the implementation of the [Pod Security Admission Control KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement). The goals of the repository are laid out in the [flexible extension support](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement#flexible-extension-support) section.

We plan on including the following in this repo:

- Packages
    - Policy evaluation package (implemented in terms of external PodSpec/annotations, Namespace, etc): policy, version, podspec, annotations -> pass / fail
    - labels → policy+version parsing/selection/validation
    - “Pod extractor” package: Resource object -> annotations + pod spec
    - “Glue” package: namespace, v1 object, v1 old object -> result (status, warnings, audit annotations)
    - metrics package
    - resolve metric version label cardinality (discussion in KEP)
    - Namespace update package: old policy, new policy, pod fetcher -> results
        - resolve timeout & limit on namespace update warnings
    - "API" package (constants for well-known labels, levels, etc)
- test cases
    - positive for each level
    - negative for each forbidding item in each level
    - runnable as unit / integration / e2e tests against opaque implementations
- unit tests for all packages
- Ensure tests exercise versioned policy changes (automatically detect test gap if a new restriction is added in 1.22 and no test exists against 1.21)
- Configuration api
- Webhook admission implementation
    - upgrade order / versioning discussion
    - include manifest with deployment, admission configuration (how to pull in user-specific serving certs and CA? kustomize template?)
- Pod Security Standards documentation generator
- Pod Security Policy migration tooling

/sig auth

**Comment by tallclair** [comment]
/hold
For sig-architecture approval (link to thread to follow)

**Comment by tallclair** [comment]
/assign @dims 

Dims approved this on the sig-architecture thread. We're hoping to kickoff implementation this Friday, so I'd love to get this created before then.

**Comment by dims** [comment]
+1 on behalf of sig-arch ( cc @derekwaynecarr @johnbelamaric )

**Comment by tallclair** [comment]
Is there an ordering dependency between creation of `github.com/kubernetes/pod-security-standards` and the staging directory?

Staging directory PR: https://github.com/kubernetes/kubernetes/pull/102153

**Comment by dims** [comment]
cc @nikhita @cblecker

**Comment by cblecker** [comment]
> Is there an ordering dependency between creation of `github.com/kubernetes/pod-security-standards` and the staging directory?

No. They are both dependencies though on the publishing bot configuration that hooks the two together.

**Comment by tallclair** [comment]
Late-breaking change: looks like we're going to go with `k8s.io/pod-security-admission` instead. See https://kubernetes.slack.com/archives/C0EN96KUY/p1621548129017300?thread_ts=1619801233.246500&cid=C0EN96KUY

I'll go ahead and update everything...

**Comment by dims** [comment]
thanks @tallclair !

**Comment by nikhita** [comment]
> Is there an ordering dependency between creation of github.com/kubernetes/pod-security-standards and the staging directory?

The staging directory can get added, but the publishing rules need to be added _after_ the repo has been created.

It looks like https://github.com/kubernetes/kubernetes/pull/102153 already added the publishing rules -- the bot broke, but that's okay! I'll get the repo created now. The bot should be back on it's feet after the repo exists. :)

/assign

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes/pod-security-admission :tada: 

Also created:
- https://github.com/kubernetes/test-infra/pull/22289 - to set up branch protection rules
- https://github.com/kubernetes/community/pull/5790 - to add the repo to sigs.yaml
- https://github.com/kubernetes/publishing-bot/pull/260 - to add the repo to publishing-bot test script (this is just a script used for testing and doesn't impact the prod bot instance)

The repo should have published code from staging on the next publishing-bot run. :+1: 

We can close this issue after all the linked PRs get merged.

**Comment by tallclair** [comment]
Thank you @nikhita !
