### ISSUE TITLE
REQUEST: New membership for chymy

### ISSUE THREAD

**Issue by chymy** [kubernetes/org#2715]
### GitHub Username
@chymy 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @vincepri 
- @fabriziopandini 
- @sbueringer 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+author%3Achymy
- Issues responded to
  https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+commenter%3Achymy
- SIG projects I am involved with
  kubernetes-sigs/cluster-api

**Comment by fabriziopandini** [comment]
/lgtm
Welcome on board @chymy, and thanks for the contribution so far! 
Looking forward to see you taking up always more complex and different tasks

**Comment by vincepri** [comment]
+1

**Comment by palnabarun** [comment]
Hi @chymy 👋🏽, thank you for filing this membership request. 🎉 

One of the requirements for sponsors is that they need be from two separate companies. @fabriziopandini and @vincepri both work at VMware. Can you please add another sponsor?

**Comment by chymy** [comment]
OK, Thank you. @palnabarun

**Comment by sbueringer** [comment]
+1

here it is :)

**Comment by nikhita** [comment]
@chymy thank you for all your contributions so far \o/

I've created PR #2734 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
