### ISSUE TITLE
Enable Google Cloud build on kubernetes/minikube repo

### ISSUE THREAD

**Issue by medyagh** [kubernetes/org#2716]
### Organization or repository
kubernetes/minikube

### Name of integration
google cloud build

### Link to integration website
https://cloud.google.com/build

### Describe what is attempting to be accomplished
we would like to be able to use google cloud build in minikube ci/ci process, so our internal jenkins can be moved to a cloud build yaml config in github, without having to move our google cloud credentials (used for publishing binaries and images) outside google cloud project .

### Additional context for request
https://github.com/kubernetes/minikube/issues/11436

**Comment by medyagh** [comment]
@mrbobbytables is this the right place that I created this request?

**Comment by dims** [comment]
@medyagh this goes to kubernetes/k8s.io :)

**Comment by medyagh** [comment]
thanks @dims but in the issue template for this ORG I see this

<img width="1849" alt="Screen Shot 2021-06-03 at 2 15 04 PM" src="https://user-images.githubusercontent.com/4564227/120712974-2b812100-c476-11eb-8264-be20484536d9.png">

**Comment by medyagh** [comment]
gentle ping @dims :)

**Comment by dims** [comment]
pinging folks on slack @medyagh

**Comment by dims** [comment]
sorry lost track of this ... looking at https://cloud.google.com/build/docs/automating-builds/build-repos-from-github

**Comment by justaugustus** [comment]
/remove-lifecycle stale
cc: @kubernetes/owners
