### ISSUE TITLE
REQUEST: New membership for chrischdi

### ISSUE THREAD

**Issue by chrischdi** [kubernetes/org#2717]
### GitHub Username
@chrischdi

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sbueringer 
- @jichenjc 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/865
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/853
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/773
  - https://github.com/kubernetes/test-infra/pull/20513
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/863
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/862
- Issues responded to
  - https://github.com/kubernetes-sigs/controller-runtime/issues/1396
  - https://github.com/kubernetes/kubernetes/issues/99751
  - https://github.com/kubernetes/kubernetes/issues/87603
  - https://github.com/kubernetes/kubernetes/issues/87615
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack
  - if taking a look at non-kubernetes-sigs: https://github.com/kubernetes/cloud-provider-openstack/

**Comment by jichenjc** [comment]
+1 to me :)

**Comment by sbueringer** [comment]
+1 from me too :)

**Comment by sbueringer** [comment]
And thank you for all the great work! :)

**Comment by palnabarun** [comment]
@chrischdi -- Thank you for your contribution to the Kubernetes community! 🎉 

I have filed PR #2724 to add you to @kubernetes-sigs org. Once, the PR merges you will receive an invitation to join the org.

Welcome to @kubernetes-sigs!

/assign
