### ISSUE TITLE
REQUEST: New membership for seanschneeweiss

### ISSUE THREAD

**Issue by seanschneeweiss** [kubernetes/org#2719]
### GitHub Username
@seanschneeweiss

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sbueringer 
- @jichenjc 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - kubernetes-sigs/cluster-api-provider-openstack#860
  - kubernetes-sigs/cluster-api-provider-openstack#835
  - kubernetes-sigs/cluster-api-provider-openstack#791
  - kubernetes-sigs/cluster-api-provider-openstack#743
  - kubernetes-sigs/cluster-api-provider-openstack#740
  - kubernetes/cloud-provider-openstack#1402
  - kubernetes/cloud-provider-openstack#1396
  - kubernetes/cloud-provider-openstack#1364
  - kubernetes/cloud-provider-openstack#1283
  - kubernetes/cloud-provider-openstack#1213
  - kubernetes/cloud-provider-openstack#1178
  - kubernetes/cloud-provider-openstack#1151
  - kubernetes/cloud-provider-openstack#1150
  - kubernetes/cloud-provider-openstack#1148
- Issues responded to
  - kubernetes-sigs/cluster-api-provider-openstack#842
  - kubernetes/cloud-provider-openstack#1534
  - kubernetes/cloud-provider-openstack#1167
  - kubernetes/cloud-provider-openstack#912
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack
  - non-kubernetes-sigs: https://github.com/kubernetes/cloud-provider-openstack

**Comment by jichenjc** [comment]
+1 to me , thanks :)

**Comment by sbueringer** [comment]
+1 from me, too.

Thx for all the great work :)

**Comment by palnabarun** [comment]
@seanschneeweiss -- Thank you for your contribution to the Kubernetes community! 🎉 

I have filed PR #2724 to add you to @kubernetes org. Once, the PR merges you will receive an invitation to join the org.

Welcome to @kubernetes!

/assign
