### ISSUE TITLE
New membership request: soggiest

### ISSUE THREAD

**Issue by soggiest** [kubernetes/org#272]
### GitHub Username
@soggiest

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@justaugustus 
@detiber  

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/71479
- SIG projects I am involved with
sig-release

/area github-membership

**Comment by justaugustus** [comment]
A +1 for my soggy friend!

**Comment by detiber** [comment]
+1 for the soggiest

**Comment by justaugustus** [comment]
Hey @soggiest -- I've created #273 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome to the party! :)
