### ISSUE TITLE
REQUEST: New membership for stmcginnis

### ISSUE THREAD

**Issue by stmcginnis** [kubernetes/org#2729]
### GitHub Username

@stmcginnis

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sbueringer 
- @vincepri 
- @CecileRobertMichon 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - [Cluster API PRs](https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+author%3Astmcginnis+)
   - [Reviews](https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+commenter%3Astmcginnis+)
- Issues responded to
   - [Filed issues](https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+author%3Astmcginnis+)
   - [Active issues](https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+stmcginnis+)
- SIG projects I am involved with
   - Cluster-API
   - Various cluster-api-provider-*

**Comment by sbueringer** [comment]
+1 Thank you for all your work!! :)

**Comment by vincepri** [comment]
+1

**Comment by CecileRobertMichon** [comment]
+1

**Comment by dims** [comment]
+1 welcome @stmcginnis
