### ISSUE TITLE
REQUEST: New membership for gautierdelorme

### ISSUE THREAD

**Issue by gautierdelorme** [kubernetes/org#2732]
### GitHub Username
@gautierdelorme

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sttts
- @christopherhein

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/issues?q=involves%3Agautierdelorme
- https://github.com/kubernetes/kube-openapi/issues?q=involves%3Agautierdelorme
- https://github.com/kubernetes-sigs/kustomize/issues?q=involves%3Agautierdelorme

**Comment by dims** [comment]
+1 from me!

**Comment by christopherhein** [comment]
+1 from me

**Comment by nikhita** [comment]
@gautierdelorme whaaaat, I thought you were already part of the org!

+1 from me as well, thank you for all your contributions so far \o/

I've created PR #2734 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
