### ISSUE TITLE
REQUEST: New membership for strongjz

### ISSUE THREAD

**Issue by strongjz** [kubernetes/org#2735]
### GitHub Username
@strongjz

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rikatz 
- @ElvinEfendi 

### List of contributions to the Kubernetes project
- PRs reviewed / authored  [release 0.46 #7098](https://github.com/kubernetes/ingress-nginx/pull/7098), [prep 0.46.0 release](https://github.com/kubernetes/ingress-nginx/pull/7100)
- Issues responded to, [7121](https://github.com/kubernetes/ingress-nginx/pull/7121), [7117](https://github.com/kubernetes/ingress-nginx/pull/7117#issuecomment-838306205)
- Regularly help run Ingress-NGINX sig-network subproject

**Comment by rikatz** [comment]
+1 from me! James is helping us a lot with all the ingress-nginx stuff

**Comment by ElvinEfendi** [comment]
:+1 thanks for helping with ingress-nginx!

**Comment by cpanato** [comment]
big +1

**Comment by moonming** [comment]
big +1, thanks for helping with ingress-nginx

**Comment by palnabarun** [comment]
@strongjz -- Thank you for your contributions to ingress-nginx! 💯 

I have filed PR #2742 to add you to the @kubernetes org. Once that merges, you will receive a membership invite notification.

Welcome to @kubernetes!!! 🎉
