### ISSUE TITLE
REQUEST: New membership for sidharthsurana

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes/org#274]
### GitHub Username
@sidharthsurana

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @roberthbailey 
- @frapposelli 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commits?author=sidharthsurana
  - https://github.com/kubernetes-sigs/cluster-api/commits?author=sidharthsurana

- Issues created/responded to
  - https://github.com/kubernetes-sigs/cluster-api/issues?q=mentions%3Asidharthsurana
  - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues?q=mentions%3Asidharthsurana
- SIG projects I am involved with
https://github.com/kubernetes-sigs/cluster-api
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere

/area github-membership

**Comment by frapposelli** [comment]
+1

Great having you on board Sidharth!

**Comment by mrbobbytables** [comment]
Hey there @sidharthsurana, thank you for all your contributions so far :)

I've created PR #278 to add you to both the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
