### ISSUE TITLE
REQUEST: New membership for AkihiroSuda

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/org#2740]
### GitHub Username
@AkihiroSuda

### Organization you are requesting membership in
@kubernetes-sigs
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @BenTheElder (https://github.com/kubernetes-sigs/kind/pull/2278#issuecomment-849923886)
- @aojea (https://github.com/kubernetes-sigs/kind/pull/2278#issuecomment-849925082)

### List of contributions to the Kubernetes project
- `org:kubernetes-sigs involves:AkihiroSuda` https://github.com/search?q=org%3Akubernetes-sigs+involves%3AAkihiroSuda
- `org:kubernetes involves:AkihiroSuda` https://github.com/search?q=org%3Akubernetes+involves%3AAkihiroSuda

**Comment by aojea** [comment]
+1000

**Comment by BenTheElder** [comment]
+googillion :-)

**Comment by dims** [comment]
About time!!! +1000

**Comment by palnabarun** [comment]
@AkihiroSuda -- Thank you for your contributions to the community!

I have filed PR #2742 to add you to @kubernetes and @kubernetes-sigs orgs. Once that merges, you will receive membership invite notifications to both the orgs.

Welcome again to the Kubernetes community! 🎉 

/assign

**Comment by AkihiroSuda** [comment]
Thank you!
