### ISSUE TITLE
REQUEST: New membership for shannonxtreme

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/org#2751]
### GitHub Username
@shannonxtreme

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@sftim 
@jimangel 

### List of contributions to the Kubernetes project

PRs:
* [Create pod eviction concept topics](https://github.com/kubernetes/website/pull/27739)
* [Correct formatting and style](https://github.com/kubernetes/website/pull/27737)
* [Other PRs](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ashannonxtreme)

**Comment by kbhawkey** [comment]
👀

**Comment by jimangel** [comment]
+1 thanks for your contributions @shannonxtreme! 🎉

**Comment by kbhawkey** [comment]
+1, @shannonxtreme has made some nice contributions to the docs. Thanks.

**Comment by nikhita** [comment]
@shannonxtreme thank you for all your contributions so far \o/

I've created PR #2764 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
