### ISSUE TITLE
REQUEST: New membership for Fei-Guo

### ISSUE THREAD

**Issue by Fei-Guo** [kubernetes/org#2755]
### GitHub Username
Fei-Guo

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @christopherhein 
- @vincepri 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/86
  https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/82
  https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/53

  plus 150+ PRs in  kubernetes-sigs/multi-tenancy/

  
  

- SIG projects I am involved with
   kubernetes-sigs/cluster-api-provider-nested 
   kubernetes-sigs/multi-tenancy/tree/master/incubator/virtualcluster

**Comment by christopherhein** [comment]
+1 to @Fei-Guo joining Kubernetes org so he can be added to https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-nested/OWNERS and https://github.com/kubernetes/k8s.io GCP project.

**Comment by vincepri** [comment]
+1

**Comment by nikhita** [comment]
@Fei-Guo thank you for all your contributions so far \o/

I've created PR #2764 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
