### ISSUE TITLE
REQUEST: New membership for JiaoDean

### ISSUE THREAD

**Issue by JiaoDean** [kubernetes/org#2756]
### GitHub Username
JiaoDean

### Organization you are requesting membership in
kubernetes-sigs org

### Requirements
- [✅] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [✅] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [✅] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [✅] I am actively contributing to 1 or more Kubernetes subprojects
- [✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [✅] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @fredkan 
- @DahuK

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   kubernetes-sigs/alibaba-cloud-csi-driver#456
   kubernetes-sigs/alibaba-cloud-csi-driver#412
   kubernetes-sigs/alibaba-cloud-csi-driver#402
   kubernetes-sigs/alibaba-cloud-csi-driver#394
   kubernetes-sigs/alibaba-cloud-csi-driver#392
   kubernetes-sigs/alibaba-cloud-csi-driver#384
   kubernetes-sigs/alibaba-cloud-csi-driver#382
   kubernetes-sigs/alibaba-cloud-csi-driver#380
   kubernetes-sigs/alibaba-cloud-csi-driver#375
   kubernetes-sigs/alibaba-cloud-csi-driver#358
   kubernetes-sigs/alibaba-cloud-csi-driver#352
   kubernetes-sigs/alibaba-cloud-csi-driver#349
   kubernetes-sigs/alibaba-cloud-csi-driver#344
   kubernetes-sigs/alibaba-cloud-csi-driver#340
   kubernetes-sigs/alibaba-cloud-csi-driver#330
   kubernetes-sigs/alibaba-cloud-csi-driver#327
   kubernetes-sigs/alibaba-cloud-csi-driver#319
   kubernetes-sigs/alibaba-cloud-csi-driver#312
   kubernetes-sigs/alibaba-cloud-csi-driver#311
   kubernetes-sigs/alibaba-cloud-csi-driver#310
   kubernetes-sigs/alibaba-cloud-csi-driver#299
   kubernetes-sigs/alibaba-cloud-csi-driver#293
   kubernetes-sigs/alibaba-cloud-csi-driver#289
   kubernetes-sigs/alibaba-cloud-csi-driver#282
   kubernetes-sigs/alibaba-cloud-csi-driver#214

- Issues responded to
   plus 25 PRs in kubernetes-sigs/alibaba-cloud-csi-driver/

- SIG projects I am involved with
   kubernetes-sigs/alibaba-cloud-csi-driver

**Comment by nikhita** [comment]
@JiaoDean - unfortunately, @DahuK will not be able to sponsor because sponsors need to be a reviewer/approver in the kubernetes or kubernetes-sigs org. :(

If you could a +1 from another sponsor, we should be able to go ahead with this membership application.

**Comment by xianlubird** [comment]
+1.

**Comment by nikhita** [comment]
@JiaoDean thank you for all your contributions so far \o/

I've created PR #2764 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
