### ISSUE TITLE
REQUEST: New membership for hex108

### ISSUE THREAD

**Issue by hex108** [kubernetes/org#276]
### GitHub Username
@hex108

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bsalamat 
- @k82cn 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
MR PRs: https://github.com/kubernetes/kubernetes/pulls/hex108
Proposal: https://github.com/kubernetes/community/pull/2976
I aslo reviewed PRs recently, e.g. https://github.com/kubernetes/kubernetes/pull/71488
- Issues responded to
My issues: https://github.com/kubernetes/kubernetes/issues/hex108
- SIG projects I am involved with
sig-scheduler
sig-autoscaling

/area github-membership

**Comment by k82cn** [comment]
+1 :)

**Comment by bsalamat** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @hex108, thank you for all the work you've done so far! :)

I've created PR #278 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by hex108** [comment]
Thanks all!
