### ISSUE TITLE
REQUEST: New membership for charleszheng44

### ISSUE THREAD

**Issue by charleszheng44** [kubernetes/org#2760]
### GitHub Username
charleszheng44

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@christopherhein 
@vincepri 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
[kubernetes-sigs/cluster-api-provider-nested#40](https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/40)
[kubernetes-sigs/cluster-api-provider-nested#37](https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/37)
[kubernetes-sigs/cluster-api-provider-nested#30](https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/30)
[kubernetes-sigs/cluster-api-provider-nested#28](https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/28)
[kubernetes-sigs/cluster-api-provider-nested#11](https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/11)

- Issues responded to
[kubernetes-sigs/apiserver-network-proxy#149](https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/149)
[kubernetes-sigs/apiserver-network-proxy#146](https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/146)
[kubernetes-sigs/apiserver-network-proxy#142](https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/142)
[kubernetes-sigs/apiserver-network-proxy#114](https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/114)

- SIG projects I am involved with
kubernetes-sigs/cluster-api-provider-nested
kubernetes-sigs/multi-tenancy/tree/master/incubator/virtualcluster
kubernetes-sigs/apiserver-network-proxy

**Comment by christopherhein** [comment]
+1 to @charleszheng44 joining Kubernetes org so he can be added to https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-nested/OWNERS and https://github.com/kubernetes/k8s.io/pull/2123 GCP project.

**Comment by vincepri** [comment]
+1

**Comment by nikhita** [comment]
@charleszheng44 thank you for all your contributions so far \o/

I've created PR #2764 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
