### ISSUE TITLE
REQUEST: New membership for vinayakankugoyal

### ISSUE THREAD

**Issue by vinayakankugoyal** [kubernetes/org#2761]
### GitHub Username
@vinayakankugoyal

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123 
- @BenTheElder 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - kubernetes/kubernetes
    - https://github.com/kubernetes/kubernetes/pull/88185
    - https://github.com/kubernetes/kubernetes/pull/90156
    - https://github.com/kubernetes/kubernetes/pull/91390
    - https://github.com/kubernetes/kubernetes/pull/95418
    - https://github.com/kubernetes/kubernetes/pull/95771
    - https://github.com/kubernetes/kubernetes/pull/96134
    - https://github.com/kubernetes/kubernetes/pull/96622
    - https://github.com/kubernetes/kubernetes/pull/96839
    - https://github.com/kubernetes/kubernetes/pull/99015
    - https://github.com/kubernetes/kubernetes/pull/99022
    - https://github.com/kubernetes/kubernetes/pull/99024
    - https://github.com/kubernetes/kubernetes/pull/99059
    - https://github.com/kubernetes/kubernetes/pull/99067
    - https://github.com/kubernetes/kubernetes/pull/99145
    - https://github.com/kubernetes/kubernetes/pull/99379
    - https://github.com/kubernetes/kubernetes/pull/100234
    - https://github.com/kubernetes/kubernetes/pull/100436
    - https://github.com/kubernetes/kubernetes/pull/101164
    - https://github.com/kubernetes/kubernetes/pull/101207
    - https://github.com/kubernetes/kubernetes/pull/101678
    - https://github.com/kubernetes/kubernetes/pull/101751
    - https://github.com/kubernetes/kubernetes/pull/101881
    - https://github.com/kubernetes/kubernetes/pull/102158
    - https://github.com/kubernetes/kubernetes/pull/102494
  - kubernetes-sigs/apiserver-network-proxy
    - https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/148
  - kubernetes/cloud-provider-gcp
    - https://github.com/kubernetes/cloud-provider-gcp/pull/169
    - https://github.com/kubernetes/cloud-provider-gcp/pull/172
    - https://github.com/kubernetes/cloud-provider-gcp/pull/174
    - https://github.com/kubernetes/cloud-provider-gcp/pull/179
    - https://github.com/kubernetes/cloud-provider-gcp/pull/182
  - kubernetes/test-infra 
    - https://github.com/kubernetes/test-infra/pull/20857
  - kubernetes/release 
    - https://github.com/kubernetes/release/pull/1910
    - https://github.com/kubernetes/release/pull/1911
    - https://github.com/kubernetes/release/pull/1912
    - https://github.com/kubernetes/release/pull/1684
  - kubernetes/k8s.io 
    - https://github.com/kubernetes/k8s.io/pull/1644
  - kubernetes/enhancements
    - https://github.com/kubernetes/enhancements/pull/2569
    - https://github.com/kubernetes/enhancements/pull/2620
    - https://github.com/kubernetes/enhancements/pull/2654
    - https://github.com/kubernetes/enhancements/pull/2739
  
- Issues responded to
  - https://github.com/kubernetes/enhancements/issues/2763
  - https://github.com/kubernetes/enhancements/issues/2568
  - https://github.com/kubernetes/release/issues/1907
- SIG projects I am involved with
  - sig-security
  - worked on running core components as non-root in kube-up
  - driving KEP from running control-plane as non-root in kubeadm (also implementing the changes)
  - driving KEP for adding support for ambient capabilities to kubernetes (https://github.com/kubernetes/enhancements/pull/2757/files)

**Comment by BenTheElder** [comment]
+100 :-)

**Comment by neolit123** [comment]
+1, thank you for the contributions thus far!

**Comment by dims** [comment]
+1 welcome!

**Comment by nikhita** [comment]
@vinayakankugoyal thank you for all your contributions so far \o/

I've created PR #2764 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
