### ISSUE TITLE
REQUEST: New membership for lizhuqi

### ISSUE THREAD

**Issue by lizhuqi** [kubernetes/org#2763]
### GitHub Username
lizhuqi

### Organization you are requesting membership in
kubernetes-csi org

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andyzhangx 
- @msau42 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-csi/csi-driver-smb/pull/201
https://github.com/kubernetes-csi/csi-driver-smb/pull/220
https://github.com/kubernetes-csi/csi-driver-smb/pull/225
https://github.com/kubernetes-csi/csi-driver-smb/pull/264
https://github.com/kubernetes-csi/csi-driver-smb/pull/265
https://github.com/kubernetes-csi/csi-driver-smb/pull/272
https://github.com/kubernetes-csi/csi-driver-smb/pull/273
https://github.com/kubernetes-csi/csi-driver-smb/pull/278
https://github.com/kubernetes-csi/csi-driver-smb/pull/279
https://github.com/kubernetes-csi/csi-driver-smb/pull/282
https://github.com/kubernetes-csi/csi-driver-smb/pull/283
https://github.com/kubernetes-csi/csi-driver-smb/pull/291
https://github.com/kubernetes-csi/csi-driver-smb/pull/292
https://github.com/kubernetes-csi/csi-driver-smb/pull/293
https://github.com/kubernetes-csi/csi-driver-smb/pull/299

- Issues responded to
https://github.com/kubernetes-csi/csi-driver-smb/issues/294

- SIG projects I am involved with
kubernetes-csi/csi-driver-smb

**Comment by andyzhangx** [comment]
+1

**Comment by msau42** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi, @lizhuqi 👋  Thank you for all your contributions!

I've created PR #2787 to add you to the @kubernetes-csi organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
