### ISSUE TITLE
REQUEST: New membership for sbose78

### ISSUE THREAD

**Issue by sbose78** [kubernetes/org#2768]
### GitHub Username
sbose78

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jhvhs
- @jberkhahn

### List of contributions to the Kubernetes project
- https://github.com/k8s-service-bindings/spec/graphs/contributors
- Regular attendee at the spec meetings

**Comment by nikhita** [comment]
@sbose78 You will need two separate sponsors for the application. The current issue body just notes @jhvhs as a sponsor :)

**Comment by sbose78** [comment]
Ah my bad. haha

**Comment by sbose78** [comment]
Fixed, @nikhita !

**Comment by jhvhs** [comment]
👍 from me

**Comment by jberkhahn** [comment]
:+1: from me as well

**Comment by savitharaghunathan** [comment]
Hi, @sbose78 👋  Thank you for all your contributions!

I've created PR #2787 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
