### ISSUE TITLE
REQUEST: New membership for lingxiankong

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/org#277]
### GitHub Username
@lingxiankong

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @hogepodge 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

    - https://github.com/kubernetes/cloud-provider-openstack/commits?author=lingxiankong

- Issues responded to

    - https://github.com/kubernetes/cloud-provider-openstack/issues?q=mentions%3Alingxiankong

- SIG projects I am involved with

    - https://github.com/kubernetes/cloud-provider-openstack

/area github-membership

**Comment by dims** [comment]
+1 from me. welcome!

**Comment by hogepodge** [comment]
+1 from me, thanks and welcome!

**Comment by mrbobbytables** [comment]
Hey there @lingxiankong , thank you for all of your contributions :)

I've created PR #278 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
