### ISSUE TITLE
REQUEST: New membership for HongjiangHuang

### ISSUE THREAD

**Issue by HongjiangHuang** [kubernetes/org#2770]
### GitHub Username
@HongjiangHuang

### Organization you are requesting membership in 

@kubernetes, @kubernetes-client

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the Kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@tengqm 
@pacoxu 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/website/pull/28041
  - https://github.com/kubernetes/website/pull/28250
  - https://github.com/kubernetes/website/pull/28243
  - https://github.com/kubernetes/website/pull/28242
  - https://github.com/kubernetes/website/pull/28241
  - https://github.com/kubernetes/website/pull/28298
  - https://github.com/kubernetes/website/pull/28304
  - https://github.com/kubernetes/website/pull/28330
  - https://github.com/kubernetes/website/pull/28327
  - https://github.com/kubernetes/website/pull/28328
  - https://github.com/kubernetes/website/pull/28329
  - https://github.com/kubernetes-client/gen/pull/191
  - https://github.com/kubernetes-client/gen/pull/192
  - https://github.com/kubernetes/kubernetes/pull/102245

- Issues responded to
  - https://github.com/kubernetes/website/issues/27673
  - https://github.com/kubernetes/website/issues/28284
  - https://github.com/kubernetes/website/issues/28232
  - https://github.com/kubernetes/website/issues/28230
  - https://github.com/kubernetes/website/issues/28228
  - https://github.com/kubernetes/website/issues/28203

**Comment by pacoxu** [comment]
+1

Thanks for the flake fix try and Chinsese website improvements.
Hope to see more contributions from you!

**Comment by tengqm** [comment]
+1
Looking forward to more contributions from you.

**Comment by savitharaghunathan** [comment]
Hi, @HongjiangHuang 👋  Thank you for all your contributions!

I've created PR #2787 to add you to the @kubernetes & cli organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
