### ISSUE TITLE
REQUEST: New membership for pacoxu

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/org#2771]
### GitHub Username
@pacoxu

I opened this request because I sometimes send PR and responses to issues in org kubernetes-sigs.

### Organization you are requesting membership in
Join Org kubernetes-sigs 
https://github.com/kubernetes-sigs
@kubernetes-sigs 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
-  
- 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:  kubernetes-sigs/kustomize#3966 (WIP) \ kubernetes-sigs/cloud-provider-azure#508 (merged) \  https://github.com/kubernetes-sigs/kubefed/pull/1228 (merged) \ kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#785 (WIP) \ kubernetes-sigs/kind#2062 (merged) 
 
- Issues responded to https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/793 (opened) \ https://github.com/kubernetes-sigs/multi-tenancy/issues/1275 (during fixing a k/k issues) \ https://github.com/kubernetes-sigs/kubefed/issues/1255 (opened) \ https://github.com/kubernetes-sigs/kubefed/issues/1240 (still opened) 

- SIG projects I am involved with kubefed\kind\kustomize

**Comment by nikhita** [comment]
@pacoxu since you are already a member of @kubernetes, feel free to open a PR directly to add yourself to k-sigs. :smile: 

Otherwise, we can get this in when we go through the next set of membership requests. :+1:

**Comment by pacoxu** [comment]
thanks. @nikhita
