### ISSUE TITLE
REQUEST: New membership for nebhale

### ISSUE THREAD

**Issue by nebhale** [kubernetes/org#2774]
### GitHub Username
nebhale

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jhvhs
- @jberkhahn

### List of contributions to the Kubernetes project
- https://github.com/k8s-service-bindings/spec/graphs/contributors
- Spec lead and regular attendee at Working Group meetings

**Comment by jberkhahn** [comment]
:+1:

**Comment by jhvhs** [comment]
👍

**Comment by savitharaghunathan** [comment]
Hi, @nebhale 👋  Thank you for all your contributions!

I've created PR #2787 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
