### ISSUE TITLE
REQUEST: New membership for scothis

### ISSUE THREAD

**Issue by scothis** [kubernetes/org#2775]
### GitHub Username
@scothis

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jhvhs
- @jberkhahn

### List of contributions to the Kubernetes project
- https://github.com/k8s-service-bindings/spec/graphs/contributors
- regular attendee at Working Group meetings

**Comment by jhvhs** [comment]
👍

**Comment by savitharaghunathan** [comment]
Friendly ping @jberkhahn for the sponsorship approval :)

**Comment by jberkhahn** [comment]
:+1:

**Comment by savitharaghunathan** [comment]
Hi, @scothis 👋 Thank you for all your contributions!

I've created PR #2787 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by scothis** [comment]
@savitharaghunathan I received an invite to join kubernetes-sigs, but ten minutes later the invite was rescinded.

```
Hi Scott Andrews,

Your invitation to the Kubernetes SIGs organization on GitHub has been canceled. Links to the invitation in previous emails will no longer work.

Thanks,
The GitHub Team
```

/reopen

**Comment by scothis** [comment]
A new invite came across the wire. We're all set here

/close
