### ISSUE TITLE
REQUEST: New membership for luthermonson

### ISSUE THREAD

**Issue by luthermonson** [kubernetes/org#2779]
### GitHub Username
 @luthermonson

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jayunit100
- @reylejano

### List of contributions to the Kubernetes project
- Rancher + RKE, cluster management and k8s distro engineer
 - https://github.com/rancher/rancher/issues/assigned/luthermonson
 - https://github.com/rancher/rancher/commits?author=luthermonson
- Flannel Owner/Maintainer:
 - https://github.com/flannel-io/flannel/blob/master/OWNERS#L7
 - https://github.com/flannel-io/flannel/pulls?q=is%3Apr+author%3Aluthermonson+is%3Aclosed
 - https://github.com/flannel-io/flannel/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3A%40me+
- Participant in sig-windows
 - Actively working working on kubernetes on Windows at SUSE via https://github.com/rancher/rke2
 - Maintainer of https://github.com/rancher/wins a critical util to get around non-priv containers on windows hosts.

**Comment by luthermonson** [comment]
Requesting membership to Kubernetes as there is a PR to add the Rancher cloud provider to autoscaler. I wrote the Rancher API code to support the feature and worked with the PR author @douglasmakey to complete the provider. PR to add the cloud provider to the autoscaler here: https://github.com/kubernetes/autoscaler/pull/4041

**Comment by jayunit100** [comment]
+1, Luther has been an avid contributor to sig-windows on the community side, and the projects that he maintains (`wins`, and `flannel`) are both super important to us and a core part of all of the sig-windows-tooling

**Comment by savitharaghunathan** [comment]
@luthermonson 👋 Thank you for your contributions. Both the sponsors you have mentioned seem to be from the same company. Can you add another sponsor who works at a different company than the above sponsors? Thanks :) 
Ref: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by luthermonson** [comment]
@savitharaghunathan i thought they couldnt be from the same company as me. i will switch back to Rey then i guess... @reylejano

**Comment by savitharaghunathan** [comment]
> @savitharaghunathan i thought they couldnt be from the same company as me. i will switch back to Rey then i guess... @reylejano

Thanks for your quick response. One of the sponsors can be from your company :)

**Comment by luthermonson** [comment]
@savitharaghunathan rey has been added and i pinged him to leave a +1, hopefully this finalizes everything. let me know if i can do anything else.

**Comment by reylejano** [comment]
+1 @luthermonson is an unsung hero to get Kubernetes to work on Windows specially with gmsa

**Comment by mrbobbytables** [comment]
Just as a point of clarification, contributing to a project outside of the kubernetes orgs (kubernetes, kubernetes-sigs, kubernets-client, and kubernetes-csi) does not apply as contributions to the project. The activity within slack does, but org membership here is largely tied to github permissions. I would hold off for a few more PRs to a kubernetes project before applying.

**Comment by nikhita** [comment]
@luthermonson Since this issue has been open for a while, I'll close it for now. Please feel free to reopen when ready. :pray:
