### ISSUE TITLE
REQUEST: New membership for @tylerferrara

### ISSUE THREAD

**Issue by tylerferrara** [kubernetes/org#2783]
### GitHub Username
@tylerferrara

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus
- @listx

### List of contributions to the Kubernetes project
- PRs reviewed / authored: [#305](https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/2305)
- Issues assigned: [#300](https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/300) & [#304](https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/304) 
- SIG projects I am involved with: [CIP](https://github.com/kubernetes-sigs/k8s-container-image-promoter)

**Comment by listx** [comment]
I support this membership proposal.

/assign @justaugustus

**Comment by justaugustus** [comment]
/lgtm
/approve
(for sponsorship)

Thanks so much for your contributions thus far!
I've created https://github.com/kubernetes/org/pull/2784 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome @tylerferrara! :)
