### ISSUE TITLE
SIG Node : requesting a Github Token

### ISSUE THREAD

**Issue by ameukam** [kubernetes/org#2786]
### Organization or repository
kubernetes/kubernetes

### Name of integration
Triage Party

### Link to integration website
https://github.com/google/triage-party

### Describe what is attempting to be accomplished

SIG Node would like a triage party instance for the upcoming June 24-25 bug scrub.

The token will be stored as a kubernetes Secret in aaa cluster where the instance of triage-party is planned to be hosted. 

### Additional context for request

> We've got lots of bugs to scrub! This should help SIG Node power through our ~500 issue backlog.

/assign @ehashman 
/sig node

**Comment by ameukam** [comment]
@cblecker @spiffxp Do we need to get a new Github token or reuse the one used by https://release.triage.k8s.io/ ?

**Comment by cblecker** [comment]
What token are we using? And what scopes does it have?

**Comment by ameukam** [comment]
> What token are we using? And what scopes does it have?

About the scope, [official doc](https://github.com/google/triage-party/#requirements) suggests `public-repo`. 
Conversation about the existing token : https://kubernetes.slack.com/archives/C01672LSZL0/p1593021365021300.

**Comment by cblecker** [comment]
Is there any reason we couldn't reuse the same token, if it's only read permissions needed?

cc @spiffxp @justaugustus

**Comment by justaugustus** [comment]
@cblecker -- I think the concern would be around rate limits between the two instances (SIG Release has a separate account just for triage party).

That said, if Node is only scanning k/k, maybe a shared instance makes sense?

**Comment by ameukam** [comment]
The current instance for SIG Release already scan the https://go.k8s.io/kubernetes. We also have encountered some unresolved issues using Triage Party with ghproxy (some of TP queries were not recognized by ghproxy); this is the reason why we ask a separate token.

**Comment by cblecker** [comment]
The rate limit is 5000 req/hour: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

We'd have to be running many, many triaging sessions at the same time to hit that limit.

My gut says, unless there are objections or other technical reasons, we use the same token for simplicity, and split things up in the future if we start hitting limits.

Thoughts?

**Comment by ehashman** [comment]
I am totally okay with sharing the SIG Release Triage party instance and adding a tab, we will only be using it for the 48h of the event. I will see if I can throw together a PR for k/k8s.io to add a dashboard.
