### ISSUE TITLE
REQUEST: New membership for FriedrichWilken

### ISSUE THREAD

**Issue by FriedrichWilken** [kubernetes/org#2788]
### GitHub Username
@FriedrichWilken

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jsturtevant
- @jayunit100 
- @perithompson

### List of contributions to the Kubernetes project
https://github.com/kubernetes/org/issues/2721#issuecomment-854552166

**Comment by jayunit100** [comment]
@FriedrichWilken has spearheaded the entire windows on kubernetes development environment project, and has been instrumental in centralizing the way we build/test windows in a canonical/open source/developer focused manner .  Hes donating this work to kubernetes sigs and has demo'd it several times at sig-windows meetings , and worked with several folks across different companies involved in upstream .

so, +1 !

**Comment by jsturtevant** [comment]
+1

Thanks for all the work on creating a better developer experience for Windows!

**Comment by perithompson** [comment]
You don't need me for this now as you have enough but thank you for all the hard work on the windows Dev environment work! +1

**Comment by mrbobbytables** [comment]
@FriedrichWilken  thanks for your help with the win dev tools \o/

I've created PR #2802  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
