### ISSUE TITLE
REQUEST: New membership for natasha41575

### ISSUE THREAD

**Issue by natasha41575** [kubernetes/org#2789]
### GitHub Username
@natasha41575

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @KnVerey
- @dims 

### List of contributions to the Kubernetes project
- involved in kustomize
- [PRs authored](https://github.com/kubernetes-sigs/kustomize/pulls?q=is%3Aclosed+is%3Apr+author%3Anatasha41575+)
- [Issues responded to](https://github.com/kubernetes-sigs/kustomize/issues?q=is%3Aissue++commenter%3Anatasha41575+)

**Comment by KnVerey** [comment]
+1

**Comment by dims** [comment]
+1 from me. welcome @natasha41575

**Comment by mrbobbytables** [comment]
@natasha41575 thanks for your help with kustomize :)

I've created PR #2802  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
