### ISSUE TITLE
REQUEST: New membership for Dragoncell

### ISSUE THREAD

**Issue by Dragoncell** [kubernetes/org#2794]
### GitHub Username
Dragoncell

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@dims 
@bobbypage 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
        
  - [containerd/containerd#5475](https://github.com/containerd/containerd/pull/5475)
  - [kubernetes/test-infra#22130](https://github.com/kubernetes/test-infra/pull/22130)
  - [kubernetes/test-infra#22601](https://github.com/kubernetes/test-infra/pull/22601)
  - [kubernetes/kubernetes#99880](https://github.com/kubernetes/kubernetes/pull/99880)
  - [kubernetes/kubernetes#101013](https://github.com/kubernetes/kubernetes/pull/101013)

- Issues responded to
  - [kubernetes/kubernetes#99510](https://github.com/kubernetes/kubernetes/pull/99510)
  - [kubernetes/kubernetes#101541](https://github.com/kubernetes/kubernetes/issues/101541)
  - [kubernetes/kubernetes#95932](https://github.com/kubernetes/kubernetes/issues/95932)
  - [kubernetes/kubernetes#101044](https://github.com/kubernetes/kubernetes/issues/101044)

- SIG projects I am involved with
  - Sig Node

**Comment by bobbypage** [comment]
+1 from me, @Dragoncell has been helping SIG-Node in reviews, enhancements and adding new CI for efforts such as cgroupv2.

**Comment by dims** [comment]
+1 from me. welcome!

**Comment by mrbobbytables** [comment]
@Dragoncell Thanks for your help with sig node :)

I've created PR #2802  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
