### ISSUE TITLE
REQUEST: New membership for JimBugwadia

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes/org#2796]
### GitHub Username

@JimBugwadia 

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cblecker 
- @tallclair 
- @dims 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
   - https://github.com/kubernetes-sigs/wg-policy-prototypes/pull/62
   - https://github.com/kubernetes-sigs/wg-policy-prototypes/pull/39
   - https://github.com/kubernetes-sigs/wg-policy-prototypes/pull/9
   - https://github.com/kubernetes-sigs/multi-tenancy/pull/1204
   - https://github.com/kubernetes-sigs/multi-tenancy/pull/336
   - https://github.com/kubernetes-sigs/multi-tenancy/pull/1318
- Issues responded to
   - https://github.com/kubernetes-sigs/multi-tenancy/issues/1341
- SIG projects I am involved with
   - sig-auth
   - sig-security
   - wg-policy (co-chair)
   - wg-multitenancy (benchmarks lead)

/area github-membership

**Comment by dims** [comment]
+1 from me welcome Jim!!!

**Comment by cblecker** [comment]
+1 from me

**Comment by tallclair** [comment]
+1 from me
Thank's @JimBugwadia for all your contributions!

**Comment by mrbobbytables** [comment]
@JimBugwadia  Thanks for your help with wg-policy \o/

I've created PR #2802  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by JimBugwadia** [comment]
Awesome, looking forward to it. Thanks @mrbobbytables @tallclair @dims @cblecker!
