### ISSUE TITLE
Retire Heapster

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/org#280]
### Repository to archive
e.g. kubernetes/heapster

### Repository and/or sig subproject owners that are approving this archival
e.g. @DirectXMan12 (Heapster subproject, SIG Instrumentation), @brancz (SIG Instrumentation Lead) -- see https://github.com/kubernetes/heapster/pull/2110

### When should this be done
Anytime soon

/area github-repo

**Comment by cblecker** [comment]
CI cleanup: https://github.com/kubernetes/test-infra/pull/10301

The rest of it is done!
/close
