### ISSUE TITLE
REQUEST: New membership for @JayantJain93

### ISSUE THREAD

**Issue by jayantjain93** [kubernetes/org#2801]
### GitHub Username
@JayantJain93

### Organization you are requesting membership in
@Kubernetes
### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @MaciekPytel
- @Elmiko

### List of contributions to the Kubernetes project
- PRs reviewed / authored
Authored
https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+is%3Aclosed+author%3Ajayantjain93

- Issues responded to
 https://github.com/kubernetes/autoscaler/issues/1869

- SIG projects I am involved with
   Autoscaler (Cluster Autoscaler)

**Comment by elmiko** [comment]
+1

**Comment by MaciekPytel** [comment]
+1

**Comment by nikhita** [comment]
@jayantjain93 thank you for all your contributions so far \o/

I've created PR #2805 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by jayantjain93** [comment]
Thank you everyone! :)
