### ISSUE TITLE
REQUEST: New membership for @s-kawamura-w664

### ISSUE THREAD

**Issue by s-kawamura-w664** [kubernetes/org#2803]
### GitHub Username
@s-kawamura-w664

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @inductor
- @atoato88

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/28338
https://github.com/kubernetes/website/pull/28305
https://github.com/kubernetes/website/pull/27952
https://github.com/kubernetes/website/pull/27662
https://github.com/kubernetes/website/pull/27315
https://github.com/kubernetes/website/pull/27173
https://github.com/kubernetes/website/pull/27171
https://github.com/kubernetes/website/pull/27079
https://github.com/kubernetes/website/pull/26965

- Issues responded to
https://github.com/kubernetes/website/issues/28279
https://github.com/kubernetes/website/issues/26885

- SIG projects I am involved with
sig-docs

**Comment by atoato88** [comment]
+1 from me :+1: 
s-kawamura-w664 has contributed to sig-docs Japanese localization frequently, and PRs are precise.

**Comment by inductor** [comment]
+1

Thanks for working for K8s docs continuously :)

**Comment by s-kawamura-w664** [comment]
Thank you so much!

**Comment by nikhita** [comment]
@s-kawamura-w664 thank you for all your contributions so far \o/

I've created PR #2805 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
