### ISSUE TITLE
Migrating ibm-vpc-block-csi-driver to kubernetes-sigs

### ISSUE THREAD

**Issue by arahamad** [kubernetes/org#2804]
### New Repo, Staging Repo, or migrate existing

https://github.com/IBM/ibm-vpc-block-csi-driver

### Requested name for new repository
ibm-vpc-block-csi-driver

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
arahamad
sandaymin123

### If not a staging repo, who should have write access
meghnasiingh
ambiknai

I will setup later for other developers once repo will be ready

### If not a staging repo, who should be listed as approvers in OWNERS
arahamad
sandaymin123

### If not a staging repo, who should be listed in SECURITY_CONTACTS
meghnasiingh
ambiknai

### What should the repo description be
IBM VPC Block CSI driver is responsible to manage the lifecycle of vpc block volume in kubernetes or openshift cluster based on IBM VPC 

### What SIG and subproject does this fall under in sigs.yaml
sig-cloud-provider

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)
Will add, to whom I should get approval, I have approval from my org

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
This is ibm vpc block volume driver(csi based) for kubenetes and openshift cluster based on IBM VPC infrastructure

**Comment by nikhita** [comment]
This needs approval from SIG Storage leads first.

/assign @xing-yang @msau42

**Comment by nikhita** [comment]
@arahamad please also ensure that the repo satisfies all the conditions for donated projects - https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

**Comment by xing-yang** [comment]
@arahamad is this CSI driver for the following cloud environment?
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud#provision-workload-cluster-in-ibm-cloud-vpc

**Comment by xing-yang** [comment]
@arahamad Actually this project should not be a sub-project under sig-storage.  This should be a sub-project under provider-ibmcloud.  For example, vsphere-csi-driver is under provider-vsphere, and gcp-compute-persistent-disk-csi-driver is under provider-gcp, etc.

**Comment by arahamad** [comment]
> @arahamad is this CSI driver for the following cloud environment?
> https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud#provision-workload-cluster-in-ibm-cloud-vpc

@xing-yang , thats correct, to whom I should discuss for the same

**Comment by xing-yang** [comment]
@andrewsykim this should be a sub-project under sig-cloud-provider.  Can you take a look?  Thanks.

**Comment by xing-yang** [comment]
@arahamad It is fine for the repo to be under kubernetes-sigs.  It's just that this should be under the cloud provider sig, not storage sig.

**Comment by arahamad** [comment]
sure @xing-yang , I got it 

I will check with @andrewsykim

**Comment by andrewsykim** [comment]
+1 @cheftako any objections?

**Comment by xing-yang** [comment]
@arahamad, can you change the following section in this issue from "sig-storage" to "sig-cloud-provider"?
```
What SIG and subproject does this fall under in sigs.yaml
sig-storage 
```

**Comment by arahamad** [comment]
@xing-yang , looks I can't change or add labels 

@nikhita , Can you please help to change or add `sig-cloud-provider` label

**Comment by cheftako** [comment]
> +1 Walter Fender any objections?

+1 No objections.

**Comment by arahamad** [comment]
@nikhita , looks we got the approvals, can you please suggest the next action

**Comment by mrbobbytables** [comment]
@arahamad  please see the requirements here:
https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

The project will need all the headers updated, OWNERS file pre created, verify that all contributors have signed the CLA etc.

**Comment by arahamad** [comment]
@mrbobbytables , I have updated headers and OWNERS file,  I am working on CLA

**Comment by arahamad** [comment]
@mrbobbytables , CLA is also ready, Can you please check and let me know if anything missing

**Comment by mrbobbytables** [comment]
@arahamad 
@sandaymin123
@meghnasiingh
@ambiknai

please open up org membership requests for kubernetes-sigs, that should be the final thing 👍

**Comment by spzala** [comment]
> @arahamad
> @sandaymin123
> @meghnasiingh
> @ambiknai
> 
> please open up org membership requests for kubernetes-sigs, that should be the final thing 👍

Cool, thanks @mrbobbytables

**Comment by mrbobbytables** [comment]
Woops forgot to close this earlier - All items have been resolved 👍 

/close
