### ISSUE TITLE
REQUEST: New membership for MaxRink

### ISSUE THREAD

**Issue by MaxRink** [kubernetes/org#2808]
### GitHub Username
@MaxRink

### Organization you are requesting membership in
@kubernetes-sigs
### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yastij 
- @randomvariable 
- @detiber 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/image-builder/issues/530
- https://github.com/kubernetes-sigs/image-builder/issues/396
- https://github.com/kubernetes-sigs/image-builder/pull/557
- https://github.com/kubernetes-sigs/image-builder/pull/469
- https://github.com/kubernetes-sigs/image-builder/pulls?q=is%3Apr+author%3AMaxRink
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues?q=is%3Aissue+author%3AMaxRink+
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pulls?q=is%3Apr+author%3AMaxRink+

**Comment by yastij** [comment]
big +1 from me, @MaxRink has been an active community member, especially in the cluster-lifecycle space

**Comment by randomvariable** [comment]
+1 from me, but both me and @yastij are VMware so need another sponsor.

**Comment by MaxRink** [comment]
> +1 from me, but both me and @yastij are VMware so need another sponsor.

yes, @detiber also agreed to sponsor :)

**Comment by detiber** [comment]
+1 from me as well, @MaxRink has been a valuable contributor across multiple sig-cluster-lifecycle related projects

**Comment by nikhita** [comment]
@MaxRink thank you for all your contributions so far \o/

I've created PR #2810 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
