### ISSUE TITLE
REQUEST: New membership for Haleygo

### ISSUE THREAD

**Issue by Haleygo** [kubernetes/org#2809]
### GitHub Username
@Haleygo

### Organization you are requesting membership in
@Kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123 
- @ahg-g 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3AHaleygo
https://github.com/kubernetes/kubernetes/pull/103187
https://github.com/kubernetes/kubernetes/pull/103027
https://github.com/kubernetes/kubernetes/pull/103183
https://github.com/kubernetes/kubernetes/pull/103117
https://github.com/kubernetes/kubernetes/pull/103056
https://github.com/kubernetes/kubernetes/pull/101478
https://github.com/kubernetes/kubernetes/pull/102239
https://github.com/kubernetes/kubernetes/pull/97947

- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3AHaleygo
https://github.com/kubernetes/kubeadm/issues/2512
https://github.com/kubernetes/kubernetes/issues/103110
https://github.com/kubernetes/kubeadm/issues/2505
https://github.com/kubernetes/kubernetes/issues/101355
https://github.com/kubernetes/kubernetes/issues/102151
https://github.com/kubernetes/kubernetes/issues/97929

- SIG projects I am involved with

**Comment by neolit123** [comment]
+1 thanks for the contributions thus far.

**Comment by ahg-g** [comment]
+1, thanks for your considerations

**Comment by pacoxu** [comment]
+1 and hope to see more contributions from you!
👍

**Comment by nikhita** [comment]
@Haleygo thank you for all your contributions so far \o/

I've created PR #2810 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
