### ISSUE TITLE
Request: New Membership for yue9944882 @kubernetes-client

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/org#281]
### GitHub Username

yue9944882

### Organization you are requesting membership in

@kubernetes-client

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of contributions to the Kubernetes project

hi guys 👋🏻i'm a member of sig apimachinery (working on generic-apimachinery/admission controller/CRDs) and hoping to join @kubernetes-client so that i could be helping building a further integration w/ openapi generated clients and k/k. 😉

/area github-membership

**Comment by mrbobbytables** [comment]
@yue9944882 I've gone ahead and added you to the @kubernetes-client org in PR #282 . Once that gets merged, you should get a membership invite. :)

/assign

**Comment by yue9944882** [comment]
wow, thx for the prompt response 🍀
