### ISSUE TITLE
Automate org membership updates

### ISSUE THREAD

**Issue by nikhita** [kubernetes/org#2812]
Today, GitHub admins and [new membership coordinators](https://github.com/kubernetes/community/tree/master/github-management#new-membership-coordinator):
1. periodically look through membership requests
2. verify if the sponsors satisfy the required criteria (not from the same company)
3. manually add the GitHub usernames to the config files one-by-one

Both GitHub Admins and the NMCs have constrained bandwidth so we should look into automating some of these.

While 1 and 2 can't really be automated because there is no way to easily verify a sponsor's employer, we should look into automating 3.

Some ideas from an old discussion with @palnabarun and @mrbobbytables:

```
add <gh handle> -org kubernetes -org kubernetes-sigs

add <gh handle> -team kubernetes/maintainers
```

Prior art for removing members in:
1. https://github.com/kubernetes/org/blob/main/hack/remove-members.sh (bash)
2. https://github.com/kubernetes/org/pull/2575 (go)

**Comment by nikhita** [comment]
/assign @palnabarun 
because you were interested in working on this. if you don't have the bandwidth, please unassign and we'll mark this as help-wanted

**Comment by RinkiyaKeDad** [comment]
For 2, I know we can't do it for every case but if a sponsor has specified their company on their github we could do something like 
```
curl https://api.github.com/users/RinkiyaKeDad | jq .company
```
and check that the companies of the sponsors aren't the same.

**Comment by palnabarun** [comment]
@RinkiyaKeDad -- that's a great idea! 👍🏽 

However, the caveat is that sometimes capitalization or the way someone has mentioned the company in that field can make the process cumbersome. We can try stripping special characters and asserting to lowercase, but would still require a level of human supervision.

**Comment by RinkiyaKeDad** [comment]
What I was initially thinking was that we could have the lowercase converted company names be commented on the issue request for the membership but I now realize this wouldn't be of much help since it would save the reviewer at max two clicks 🙂
