### ISSUE TITLE
REQUEST: New membership for t-inu

### ISSUE THREAD

**Issue by t-inu** [kubernetes/org#2813]
### GitHub Username
@t-inu

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @inductor
- @atoato88

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pull/28255
https://github.com/kubernetes/website/pull/28322
https://github.com/kubernetes/website/pull/28336
https://github.com/kubernetes/website/pull/28433
https://github.com/kubernetes/website/pull/28524

- Issues responded to
https://github.com/kubernetes/website/issues/28268
https://github.com/kubernetes/website/issues/28281
https://github.com/kubernetes/website/issues/28283
https://github.com/kubernetes/website/issues/28456

- SIG projects I am involved with
sig-docs

**Comment by atoato88** [comment]
+1 from me.
Thank you to contributing to update documents ralated to Japanese localization.

**Comment by inductor** [comment]
+1 
thanks for your work!

**Comment by t-inu** [comment]
Thank you so much!

**Comment by palnabarun** [comment]
@t-inu, thank you for all your contributions so far :)

I've created PR #2819 to add you to the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! :tada:

/assign
