### ISSUE TITLE
REQUEST: New membership for mdbooth

### ISSUE THREAD

**Issue by mdbooth** [kubernetes/org#2814]
### GitHub Username
@mdbooth

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sbueringer
- @lingxiankong 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/924
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/916
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/799

- Issues responded to

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/808

(+ 4 more opened by me)

- SIG projects I am involved with

cluster-api-provider-openstack

**Comment by lingxiankong** [comment]
+1

**Comment by sbueringer** [comment]
+1

**Comment by palnabarun** [comment]
@mdbooth, thank you for all your contributions so far :)

I've created PR #2819 to add you to the @kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! :tada:

/assign
