### ISSUE TITLE
REQUEST: New membership for jayonlau

### ISSUE THREAD

**Issue by jayonlau** [kubernetes/org#2816]
### GitHub Username
@jayonlau

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @liupeng0518
- @oomichi
- @floryut
### List of contributions to the Kubernetes project
- PRs reviewed / authored
- https://github.com/kubernetes-sigs/kubespray/pull/7722#event-4916546533
- https://github.com/kubernetes-sigs/kubespray/pull/7737#event-4938495901
- https://github.com/kubernetes-sigs/kubespray/pull/7744#event-4938807122
- https://github.com/kubernetes-sigs/kubespray/pull/7752#event-4946166837
- https://github.com/kubernetes-sigs/kubespray/pull/7756#event-4964660094
- https://github.com/kubernetes-sigs/kubespray/pull/7774#issuecomment-873901056
- Issues responded to
- SIG projects I am involved with
- https://github.com/kubernetes-sigs

**Comment by liupeng0518** [comment]
+1

**Comment by floryut** [comment]
+1 many contribs, simple for now but with the potential to become greater

**Comment by oomichi** [comment]
+1

**Comment by jayonlau** [comment]
@savitharaghunathan

**Comment by palnabarun** [comment]
@jayonlau, thank you for all your contributions so far :)

I've created PR #2819 to add you to the @kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! :tada:

/assign
