### ISSUE TITLE
REQUEST: New membership for Jerry-Ge

### ISSUE THREAD

**Issue by Jerry-Ge** [kubernetes/org#2817]
### GitHub Username
e.g. @Jerry-Ge

### Organization you are requesting membership in
e.g. @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Huang-Wei 
- @chendave 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/kubernetes/kubernetes/pull/100279
   - https://github.com/kubernetes/kubernetes/pull/102558
   - https://github.com/kubernetes/kubernetes/pull/103475
   - https://github.com/kubernetes/kubernetes/pull/99435
   - https://github.com/kubernetes/kubernetes/pull/102936

- Issues responded to
   - https://github.com/kubernetes/kubernetes/issues/101135
   - https://github.com/kubernetes/kubernetes/issues/101087
   - https://github.com/kubernetes/kubernetes/issues/98086
- SIG projects I am involved with
   - Kubernetes SIG Scheduling

**Comment by Huang-Wei** [comment]
+1, looking forward for more contributions from @Jerry-Ge !

**Comment by Jerry-Ge** [comment]
> +1, looking forward for more contributions from @Jerry-Ge !

Definitely! Thanks Wei

**Comment by chendave** [comment]
+1 for @Jerry-Ge

**Comment by palnabarun** [comment]
@Jerry-Ge, thank you for all your contributions so far :)

I've created PR #2819 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
