### ISSUE TITLE
REQUEST: New membership for @rajaskakodkar

### ISSUE THREAD

**Issue by rajaskakodkar** [kubernetes/org#2820]
### GitHub Username
@rajaskakodkar

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nikhita 
- @knabben 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   `k/k`: 
         https://github.com/kubernetes/kubernetes/pull/103158
         https://github.com/kubernetes/kubernetes/pull/102354
         https://github.com/kubernetes/kubernetes/pull/97346
         https://github.com/kubernetes/kubernetes/pull/94876
         https://github.com/kubernetes/kubernetes/pull/94875
  `k/test-infra`:
        https://github.com/kubernetes/test-infra/pull/22774
        https://github.com/kubernetes/test-infra/pull/18723
   `k/k8s.io`:
        https://github.com/kubernetes/k8s.io/pull/1548

- Issues responded to
  `k/k`:
      https://github.com/kubernetes/kubernetes/issues/102919
      https://github.com/kubernetes/kubernetes/issues/92700
      https://github.com/kubernetes/kubernetes/issues/97318
      
- SIG projects I am involved with
sig/testing
sig/network

**Comment by nikhita** [comment]
+1, welcome!

/woof

**Comment by knabben** [comment]
+1

Raja has been helping in the netpol test suite

**Comment by nikhita** [comment]
@rajaskakodkar thank you for all your contributions so far \o/

I've created PR #2825 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
