### ISSUE TITLE
REQUEST: New membership for Kasakaze

### ISSUE THREAD

**Issue by njuptlzf** [kubernetes/org#2821]
### GitHub Username
@njuptlzf

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @liggitt 
- @aojea 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/103452
https://github.com/kubernetes/kubernetes/pull/103325
https://github.com/kubernetes/kubernetes/pull/102040
https://github.com/kubernetes/kubernetes/pull/101605
https://github.com/kubernetes/kubernetes/pull/101559
https://github.com/kubernetes/kubernetes/pull/101361
https://github.com/kubernetes/kubernetes/pull/100964
https://github.com/kubernetes/kubernetes/pull/100771
https://github.com/kubernetes/website/pull/26833

- Issues responded to
https://github.com/kubernetes/klog/issues/236

- SIG projects I am involved with
https://github.com/kubernetes-sigs/kubespray/pull/7679

**Comment by aojea** [comment]
/lgtm
Looking forward to seeing more contributions and thanks for helping fixing and adding more tests,

**Comment by liggitt** [comment]
+1

**Comment by nikhita** [comment]
@njuptlzf thank you for all your contributions so far \o/

I've created PR #2825 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
