### ISSUE TITLE
REQUEST: New membership for RinkiyaKeDad

### ISSUE THREAD

**Issue by RinkiyaKeDad** [kubernetes/org#2823]
### GitHub Username
@RinkiyaKeDad

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nikhita 
- @liggitt 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
Maintaing https://github.com/kubernetes-sigs/depstat
https://github.com/kubernetes/test-infra/pull/22137
https://github.com/kubernetes/community/pull/5866 (and similar)
https://github.com/kubernetes/contributor-site/pull/223

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/98698
https://github.com/kubernetes/contributor-site/issues/93
https://github.com/kubernetes/k8s.io/issues/1597

- SIG projects I am involved with
sig-architecture
sig-contribex

**Comment by liggitt** [comment]
+1

**Comment by nikhita** [comment]
+1 of course! :)

**Comment by dims** [comment]
+1 from me as well

**Comment by nikhita** [comment]
@RinkiyaKeDad thank you for all your contributions so far \o/

I've created PR #2825 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by MadhavJivrajani** [comment]
/woof
🎉❤️
