### ISSUE TITLE
REQUEST: New membership for @tech-geek29

### ISSUE THREAD

**Issue by tech-geek29** [kubernetes/org#2826]
### GitHub Username
@tech-geek29

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nikhita 
- @richardcase 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   `kubernetes/kubernetes:`
     https://github.com/kubernetes/kubernetes/pull/103350
     https://github.com/kubernetes/kubernetes/pull/103146
     https://github.com/kubernetes/kubernetes/pull/102860
     https://github.com/kubernetes/kubernetes/pull/102850
   `kubernetes/community:`
     https://github.com/kubernetes/community/pull/5867
     https://github.com/kubernetes/community/pull/5834
    `kubernetes/website:`
      https://github.com/kubernetes/website/pull/28605
    `kubernetes-sigs/e2e-framework`
      https://github.com/kubernetes-sigs/e2e-framework/pull/27
      https://github.com/kubernetes-sigs/e2e-framework/pull/26
    `kubernetes-sigs/cluster-api-provider-aws`  
      https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2517
      https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2510
      
- Issues responded to
   https://github.com/kubernetes/kubernetes/issues/101008
   https://github.com/kubernetes/kubernetes/issues/95380
   https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2471
   https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2491
   
- SIG projects I am involved with
   sig/e2e-framework 
   sig/node
   sig/cluster-api-aws-provider

**Comment by richardcase** [comment]
Based on the contributions to the PRs/issues:

+1

**Comment by nikhita** [comment]
+1, welcome!

**Comment by nikhita** [comment]
@tech-geek29 thank you for all your contributions so far \o/

I've created PR #2827 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
