### ISSUE TITLE
REQUEST: New membership for fpetkovski

### ISSUE THREAD

**Issue by fpetkovski** [kubernetes/org#2829]
### GitHub Username
@fpetkovski

### Organization you are requesting membership in
- @kubernetes
- @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dgrisonnet
- @mrueg

### List of contributions to the Kubernetes project
PRs authored:
- https://github.com/kubernetes/kube-state-metrics/pull/1521
- https://github.com/kubernetes/kube-state-metrics/pull/1506
- https://github.com/kubernetes/kube-state-metrics/pull/1505
- https://github.com/kubernetes/kube-state-metrics/pull/1499
- https://github.com/kubernetes-sigs/prometheus-adapter/pull/434/files

PRs reviewed:
- https://github.com/kubernetes-sigs/prometheus-adapter/pull/432
- https://github.com/kubernetes/kube-state-metrics/pull/1520
- https://github.com/kubernetes/kube-state-metrics/pull/1487

Issues responded to:
- https://github.com/kubernetes-sigs/kind/issues/1966
- https://github.com/kubernetes-sigs/prometheus-adapter/issues/422
- https://github.com/kubernetes-sigs/prometheus-adapter/issues/413
- https://github.com/kubernetes/kube-state-metrics/issues/1389
- https://github.com/kubernetes/kube-state-metrics/issues/1422
- https://github.com/kubernetes/kube-state-metrics/issues/1432
- https://github.com/kubernetes/kube-state-metrics/issues/1503
- https://github.com/kubernetes/kube-state-metrics/issues/1527

**Comment by dgrisonnet** [comment]
+100 from my side, thank you for the awesome work in kube-state-metrics and prometheus-adapter! :tada:

**Comment by lilic** [comment]
Thanks for the great work! 🎉 

cc @brancz

**Comment by mrueg** [comment]
+100 as well! Thank You for Your contributions :tada: on the project and welcome aboard! :ship:

**Comment by brancz** [comment]
:100: has my support as well!

**Comment by nikhita** [comment]
@fpetkovski thank you for all your contributions so far \o/

I've created PR #2834 to add you to the @kubernetes and @kubernetes-sigs organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and @kubernetes-sigs! 🎉

/assign
