### ISSUE TITLE
Request: New membership for xichengliudui

### ISSUE THREAD

**Issue by xichengliudui** [kubernetes/org#283]
### GitHub Username
@xichengliudui

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markthink 
- @chenrui333 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Axichengliudui+archived%3Afalse+is%3Aclosed+
- Issues responded to
https://github.com/issues?q=is%3Aissue+assignee%3Axichengliudui+archived%3Afalse+is%3Aclosed
- SIG projects I am involved with
website, kubernetes

/area github-membership

**Comment by markthink** [comment]
+1

**Comment by xichengliudui** [comment]
@markthink  Thanks for XiaoLong support!

**Comment by chenrui333** [comment]
+1, thanks for the your contributions for the i18n-zh localization!

**Comment by xichengliudui** [comment]
@cblecker

**Comment by markthink** [comment]
@xichengliudui  Thank you for your contribution.

**Comment by chenrui333** [comment]
better contribution display for kubernetes/website repo:
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Axichengliudui+archived%3Afalse+is%3Aclosed+is%3Amerged+repo%3Akubernetes%2Fwebsite

**Comment by zacharysarah** [comment]
+1, thanks for joining!

**Comment by xichengliudui** [comment]
@markthink  @chenrui333  @zacharysarah , Thank you for your support!

**Comment by mrbobbytables** [comment]
Hey there @xichengliudui, thank you for all your contributions so far :)

I've created PR #296  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by xichengliudui** [comment]
@chenrui333  @markthink  @zacharysarah  @mrbobbytables ,Thank you very much!
