### ISSUE TITLE
REQUEST: New membership for @mrajashree

### ISSUE THREAD

**Issue by mrajashree** [kubernetes/org#2833]
### GitHub Username
@mrajashree

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @elmiko
- @CecileRobertMichon 
- @sbueringer 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
Authored:
https://github.com/kubernetes-sigs/cluster-api/pull/4659
https://github.com/kubernetes-sigs/cluster-api/pull/4427
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1212
Reviewed:
https://github.com/kubernetes-sigs/cluster-api/pull/4511
https://github.com/kubernetes-sigs/cluster-api/pull/4808
https://github.com/kubernetes-sigs/cluster-api/pull/4390
https://github.com/kubernetes-sigs/etcdadm/pull/220

- Issues responded to
https://github.com/kubernetes-sigs/etcdadm/issues/218
https://github.com/kubernetes-sigs/etcdadm/issues/209
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1211
https://github.com/kubernetes/kubernetes/issues/96183

- SIG projects I am involved with
cluster-api
etcdadm

**Comment by elmiko** [comment]
+1

**Comment by sbueringer** [comment]
Thx for your great contributions so far!!
+1

**Comment by CecileRobertMichon** [comment]
+1 !

**Comment by dims** [comment]
Big +1 @mrajashree !

**Comment by nikhita** [comment]
@mrajashree +1 from me as well, thank you for all your contributions so far \o/

I've created PR #2834 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by fabriziopandini** [comment]
I know I'm late late to the welcome party, nevertheless
+1 !
