### ISSUE TITLE
REQUEST: New membership for tobiasgiese

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes/org#2835]
### GitHub Username
@tobiasgiese

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jichenjc 
- @sbueringer 
- @chrischdi

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/932
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/925
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/937
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/933
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/930
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/944
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/945
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/947
- Issues responded to
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/927
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/856
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/745
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/868
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/920
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/943
  - https://github.com/kubernetes-sigs/service-catalog/issues/2838
- SIG projects I am involved with
  - [kubernetes-sigs/cluster-api-provider-openstack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/)

**Comment by jichenjc** [comment]
+1 to me thanks @tobiasgiese for your great contribution

**Comment by sbueringer** [comment]
Thank you for your great contributions so far!!
+1

**Comment by chrischdi** [comment]
+1 also from my side :rocket:

**Comment by mrbobbytables** [comment]
Hey there @tobiasgiese , thank you for all your contributions so far :)

I've created PR #2848  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
