### ISSUE TITLE
REQUEST: New membership for hidekazuna

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes/org#2836]
### GitHub Username
@hidekazuna

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sbueringer 
- @jichenjc 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/minikube/pull/3286
  - https://github.com/kubernetes/website/pull/11707
  - https://github.com/kubernetes/autoscaler/pull/3805
  - https://github.com/kubernetes/autoscaler/pull/3811
  - https://github.com/kubernetes/autoscaler/pull/3812
- Issues responded to
  - https://github.com/kubernetes/minikube/issues/3277 
  - https://github.com/kubernetes/website/issues/11703
  - https://github.com/kubernetes/autoscaler/issues/3804
- SIG projects I am involved with

**Comment by sbueringer** [comment]
+1

Obviously, thx for all your contributions :)

**Comment by jichenjc** [comment]
+1 
appreciate your help~

**Comment by mrbobbytables** [comment]
@hidekazuna , thank you for all your contributions so far :D

I've created PR #2848  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
