### ISSUE TITLE
Migrate existing repo to kubernetes-sigs

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/org#2839]
### Migrate existing repository

https://github.com/jpbetz/auger

### Requested name for new repository

auger

### Which Organization should it reside

kubernetes-sigs

### If not a staging repo, who should have admin access

@logicalhan, @ehashman, @dashpole, @brancz, @jpbetz, @lilic 

### If not a staging repo, who should have write access

@logicalhan, @ehashman, @dashpole, @brancz, @jpbetz, @lilic 

### If not a staging repo, who should be listed as approvers in OWNERS

@logicalhan, @ehashman, @dashpole, @brancz, @jpbetz, @lilic 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@logicalhan, @ehashman, @dashpole, @brancz, @jpbetz, @lilic 

### What should the repo description be

Directly access data objects stored in etcd by kubernetes.

Encodes and decodes Kubernetes objects from the binary storage encoding used to store data to etcd. Supports data conversion to YAML, JSON and Protobuf.

Automatically determines if etcd data is stored in JSON (kubernetes 1.5 and earlier) or binary (kubernetes 1.6 and newer) and decodes accordingly.

### What SIG and subproject does this fall under in sigs.yaml

SIG-Instrumentation

### Approvals

https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#bookmark=id.2oxueh6uc3as

**Comment by ehashman** [comment]
:+1: We discussed in the 2021-07-22 SIG Instrumentation meeting: https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#heading=h.4wufkfwwyr6x

**Comment by lilic** [comment]
👍 sounds great!

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale
This fell off our radar :x Just double checking...do you still want to proceed with the migration?

**Comment by paramsiddharth** [comment]
> /remove-lifecycle stale This fell off our radar :x Just double checking...do you still want to proceed with the migration?

@logicalhan @jpbetz Thoughts? I suppose we should proceed with the migration, shouldn't we?

**Comment by jpbetz** [comment]
Yeah, I think we should proceed.

**Comment by paramsiddharth** [comment]
> /remove-lifecycle stale
> 
> @logicalhan Apologies for the delayed response. There are a few things we'll need to address before this can be migrated over to kubernetes.
> 
> * One of the contributors (@paramsiddharth) has not signed the CNCF CLA. They'll need to sign the CLA for the repo to be migrated over. @paramsiddharth you can find the instructions for signing the CLA [here](https://github.com/kubernetes/community/blob/master/CLA.md).
> * There is a typo in the `OWNERS` file name right now (s/OWNER/OWNERS). Without this fix, PRs cannot be approved.
> * The `CONTRIBUTING.md` needs to the format in the [template file](https://github.com/kubernetes/kubernetes-template-project/blob/main/CONTRIBUTING.md). Right now, the doc says "contributing to service catalog" so that'll need to be fixed as well.
> * The "community, discussion and support" and the "code of conduct" sections should be added to the README.md as in this [template file](https://github.com/kubernetes/kubernetes-template-project#community-discussion-contribution-and-support).
> 
> Once these issues are addressed, please ping us again and we can help migrate the repo.

@nikhita Are any of these still pending?

**Comment by mrbobbytables** [comment]
The OWNERS file, the template files and something else that was missed - There are 5 files that are missing kubernetes author headers:
```
Dockerfile
Makefile
cmd/analyze.go
cmd/checksum.go
main.go
```

**Comment by mrbobbytables** [comment]
Just a reminder ping, once those files are updated we should be able to proceed with migration.

**Comment by ehashman** [comment]
@logicalhan what's going on with this?
