### ISSUE TITLE
Create github.com/kubernetes-csi/external-resizer repo

### ISSUE THREAD

**Issue by mlmhl** [kubernetes/org#284]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
external-resizer

### Which Organization should it reside
kubernetes-csi

### If not a staging repo, who should have admin access
@saad-ali 

### If not a staging repo, who should have write access
@saad-ali 

### If a new repo, who should be listed as approvers in OWNERS
@saad-ali @gnufied @mlmhl 

### If a new repo, who should be listed in SECURITY_CONTACTS
@saad-ali 

### What should the repo description be
Sidecar container that watches Kubernetes PersistentVolumeClaims objects and triggers controller side expansion operation against a CSI endpoint.

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject for sig-storage

### Approvals

Approved by sig-lead Saad Ali: [https://groups.google.com/forum/#!topic/kubernetes-sig-storage-wg-csi/V8IM3-RYBQ4](https://groups.google.com/forum/#!topic/kubernetes-sig-storage-wg-csi/V8IM3-RYBQ4)

/area github-repo

**Comment by mlmhl** [comment]
cc @saad-ali

**Comment by mlmhl** [comment]
@cblecker or @spiffxp can you help with this issue? Thanks :)

**Comment by mlmhl** [comment]
Ping @kubernetes/owners as this is out of [SLO](https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#slos) :)

**Comment by cblecker** [comment]
Created: https://github.com/kubernetes-csi/external-resizer

**Comment by mlmhl** [comment]
Thanks @cblecker !
