### ISSUE TITLE
REQUEST: New membership for jinsongo

### ISSUE THREAD

**Issue by jinsongo** [kubernetes/org#2840]
### GitHub Username
@jinsongo

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @christopherhein
- @Fei-Guo
- @gyliu513

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/187
https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/191

- Issues responded to
https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/155
https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/156
https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/164
https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/166
https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/176
- SIG projects I am involved with

**Comment by gyliu513** [comment]
+1, thanks @jinsongo for your great contribution to virtual cluster!

**Comment by christopherhein** [comment]
+1, thank you @jinsongo !

**Comment by Fei-Guo** [comment]
+1

**Comment by mrbobbytables** [comment]
@jinsongo , thank you for all your contributions so far :)

I've created PR #2848  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
