### ISSUE TITLE
REQUEST: New membership for @sejr

### ISSUE THREAD

**Issue by sejr** [kubernetes/org#2841]
### GitHub Username

@sejr

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tallclair
- @liggitt 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - kubernetes/website#29124 
  - kubernetes/kubernetes#103560
  - kubernetes/kubernetes#103341
  - kubernetes/kubernetes#103323
  - kubernetes/kubernetes#103316
  - kubernetes/kubernetes#103315
  - kubernetes/website#28903
- Issues responded to
  - kubernetes/kubernetes#103559
  - Issues related to/linked in above PRs
- SIG projects I am involved with
  - SIG Auth / Pod Security Standards (PSP replacement)

**Comment by liggitt** [comment]
+1, thanks for all the help

**Comment by tallclair** [comment]
+1, thanks! @sejr did solid work and communicated well while helping out with PodSecurity. I look forward to future contributions!

**Comment by mrbobbytables** [comment]
@sejr, thank you for all your help with the Pod Security stuff <3

I've created PR #2848  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
