### ISSUE TITLE
Archiving cluster-api-bootstrap-provider-kubeadm

### ISSUE THREAD

**Issue by vincepri** [kubernetes/org#2845]
### Repository to archive
e.g. https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm

### Repository and/or sig subproject owners that are approving this archival
@vincepri 
@neolit123 
@timothysc 

### When should this be done
Anytime.

### Additional context for request
Any additional information or context to describe the request.

**Comment by neolit123** [comment]
+1

**Comment by mrbobbytables** [comment]
notice has been sent out, all PRs merged - going to go ahead and close
/close
