### ISSUE TITLE
REQUEST: New membership for jimdaga

### ISSUE THREAD

**Issue by jimdaga** [kubernetes/org#2851]
### GitHub Username
@jimdaga 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp
- @ameukam

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/k8s.io/pull/2425
  - https://github.com/kubernetes/k8s.io/pull/2303
  - https://github.com/kubernetes/k8s.io/pull/2374
  - https://github.com/kubernetes/k8s.io/pull/2284
  - https://github.com/kubernetes/k8s.io/pull/2317
  - https://github.com/kubernetes/k8s.io/pull/2315
  - https://github.com/kubernetes/k8s.io/pull/2261
  - https://github.com/kubernetes/k8s.io/pull/2304
- Issues responded to
  - https://github.com/kubernetes/k8s.io/issues/2150
  - https://github.com/kubernetes/k8s.io/issues/2316
- SIG projects I am involved with
  - wg-k8s-infra

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by ameukam** [comment]
+1 from sponsor

**Comment by mrbobbytables** [comment]
@jimdaga  thank you for all your contributions so far :)

I've created PR #2853   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by jimdaga** [comment]
Thank you!
