### ISSUE TITLE
REQUEST: New membership for ambiknai

### ISSUE THREAD

**Issue by ambiknai** [kubernetes/org#2855]
### GitHub Username
ambiknai

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- arahamad
- mrbobbytables

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  couple of PRs reviewed and authored under https://github.com/IBM
- Issues responded to
   Responded to issues under https://github.com/IBM

1. https://github.com/openshift/ocs-operator/pull/1088
2. https://github.com/noobaa/noobaa-operator/pull/540
3. https://github.com/s3fs-fuse/s3fs-fuse/pull/1627
4.  https://github.com/IBM/ibmcloud-object-storage-plugin/graphs/contributors

- SIG projects I am involved with
https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver

**Comment by arahamad** [comment]
+1 - @ambiknai is one of contributor to https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver

**Comment by spzala** [comment]
@ambiknai you need another sponsor from a different company. Both sponsors cannot be from the same company.

**Comment by mrbobbytables** [comment]
+1 this is to setup new owners for the imported https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver repo

**Comment by mrbobbytables** [comment]
I've created PR #2869  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
