### ISSUE TITLE
REQUEST: New membership for xinydev

### ISSUE THREAD

**Issue by xinydev** [kubernetes/org#2859]
### GitHub Username
@xinydev

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @BenTheElder 
- @neolit123 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * https://github.com/kubernetes/community/pull/5925
  * https://github.com/kubernetes/kubernetes/pull/103981
  * https://github.com/kubernetes/website/pull/29092
  * https://github.com/kubernetes/website/pull/29076
  * https://github.com/kubernetes-sigs/kind/pull/2359
  * https://github.com/kubernetes-sigs/kind/pull/2358
  * https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/57
  * https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/56
  * https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/54
  * https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/52
  * https://github.com/kubernetes/git-sync/pull/434
  * https://github.com/kubernetes/community/pull/5871
  * https://github.com/kubernetes/dns/pull/471
  * https://github.com/kubernetes/node-problem-detector/pull/589
  * https://github.com/kubernetes/node-problem-detector/pull/588
  * https://github.com/kubernetes/kubernetes/pull/103302
  * https://github.com/kubernetes/test-infra/pull/22726
  * https://github.com/kubernetes-sigs/kubetest2/pull/149
  * https://github.com/kubernetes-sigs/kind/pull/2329
  * https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2541
  * https://github.com/kubernetes-sigs/kubetest2/pull/145
  * https://github.com/kubernetes/kubernetes/pull/91411
- Issues responded to
  * https://github.com/kubernetes/website/issues/29058
  * https://github.com/kubernetes-sigs/kind/issues/2361
- SIG projects I am involved with
  * sig-cluster-lifecycle
  * sig-testing

**Comment by neolit123** [comment]
+1

**Comment by BenTheElder** [comment]
+1

**Comment by mrbobbytables** [comment]
@xinydev  , thank you for all your contributions so far :)

I've created PR #2869  to add you to the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
