### ISSUE TITLE
Membership for new repo "mutating-trace-admission-controller"

### ISSUE THREAD

**Issue by dashpole** [kubernetes/org#286]
### GitHub Username
@dashpole

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Random-Liu 
- @BenTheElder

### List of contributions to the Kubernetes project
- PRs reviewed / authored: https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Adashpole+repo%3Akubernetes%2Fkubernetes
- Issues responded to: https://github.com/issues?q=is%3Aissue+repo%3Akubernetes%2Fkubernetes+mentions%3Adashpole
- SIG projects I am involved with: kubernetes

/area github-membership

**Comment by dashpole** [comment]
This is for https://github.com/kubernetes/org/issues/285

**Comment by Random-Liu** [comment]
:+1:

**Comment by BenTheElder** [comment]
+1

**Comment by dashpole** [comment]
friendly ping to @kubernetes/owners, as this is out of [SLO](https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#slos)
