### ISSUE TITLE
REQUEST: New membership for longwuyuan

### ISSUE THREAD

**Issue by longwuyuan** [kubernetes/org#2861]
### GitHub Username

@longwuyuan

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@rikatz

### Sponsor 2

@strongjz 

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/ingress-nginx/pulls/longwuyuan
- https://github.com/kubernetes/ingress-nginx/issues?q=is%3Aopen+longwuyuan+is%3Aissue
- I help users reporting issues on the K8s slack, more in channels like #ingress-nginx-users, #kubernetes-users, #minikube, #metallb etc https://app.slack.com/client/T09NY5SBT/search/search-eb2da3ca-6462-4db6-be5c-58417ddea45c . 
- Inviting aspiring contributors, from #in-dev and #kubernetes-users channels and conducting training for getting-started as a contributor https://www.youtube.com/watch?v=BRz7vfER6Oc&t=99s  https://www.youtube.com/watch?v=IxByX7z9FX8&t=23s

**Comment by rikatz** [comment]
+1 from me (@longwuyuan will still fix the issue description, but let me justify!)

Long has been an amazing contributor, triaging/helping in ingress-nginx issues (and in #ingress-nginx-users channel) as well as conducting some contribution mentorship with new contributors willing to help in ingress-nginx.

**Comment by strongjz** [comment]
+1 as well, @longwuyuan helps the community learn how to help maintain ingress-nginx all the while triaging and fixing issues in the project.

**Comment by mrbobbytables** [comment]
@longwuyuan  , thank you for all your help with nginx <3

I've created PR #2869  to add you to  all the various orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by longwuyuan** [comment]
No words to express gratitude. No words to express happiness. Means a lot
to me.

Thanks,
; Long
