### ISSUE TITLE
REQUEST: New membership for fgimenez

### ISSUE THREAD

**Issue by fgimenez** [kubernetes/org#2862]
### GitHub Username

@fgimenez

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsor 1

@chaodaiG

### Sponsor 2

@alvaroaleman

### List of contributions to the Kubernetes project

* PRs reviewed / authored
  * https://github.com/kubernetes/test-infra/pull/22582
  * https://github.com/kubernetes/test-infra/pull/22382
  * https://github.com/kubernetes/test-infra/pull/22370
  * https://github.com/kubernetes/test-infra/pull/20902
  * https://github.com/kubernetes/test-infra/pull/22921
  * https://github.com/kubernetes/kubernetes/pull/47593
  * https://github.com/kubernetes/kubernetes/pull/41301
  * https://github.com/kubernetes/kubernetes/pull/19326
  * https://github.com/kubernetes/kubernetes/pull/18562

* Issues responded to
  * https://github.com/kubernetes/test-infra/issues/21908
  * https://github.com/kubernetes/test-infra/issues/22072
  * https://github.com/kubernetes/test-infra/issues/20859
  * https://github.com/kubernetes/test-infra/issues/22417
  * https://github.com/kubernetes/kubernetes/issues/39962

* SIG projects I am involved with
  * sig-testing

**Comment by alvaroaleman** [comment]
+1

**Comment by chaodaiG** [comment]
+1

**Comment by mrbobbytables** [comment]
@fgimenez  , thank you for all your contributions so far :)

I've created PR #2869  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by fgimenez** [comment]
thanks a lot @mrbobbytables!!
