### ISSUE TITLE
REQUEST: New membership for estroz

### ISSUE THREAD

**Issue by estroz** [kubernetes/org#2863]
### GitHub Username
@estroz

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pwittrock
- @vincepri 

### List of contributions to the Kubernetes project
- PRs reviewed / authored, issues responded to
  - https://github.com/kubernetes-sigs/kubebuilder/issues?q=sort%3Aupdated-desc+estroz
  - https://github.com/kubernetes-sigs/controller-runtime/issues?q=sort%3Aupdated-desc+estroz
  - https://github.com/kubernetes/test-infra/issues?q=sort%3Aupdated-desc+estroz
- SIG projects I am involved with
  - [Admin](https://github.com/kubernetes-sigs/kubebuilder/blob/51e4a9aa50555c8c6fcc70902ab0c32befce1486/OWNERS_ALIASES#L8) of https://github.com/kubernetes-sigs/kubebuilder
  - https://github.com/kubernetes-sigs/controller-runtime
  - https://github.com/kubernetes-sigs/controller-tools

**Comment by pwittrock** [comment]
lgtm

**Comment by vincepri** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @estroz , thank you for all your contributions so far :)

I've created PR #2869  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
