### ISSUE TITLE
Membership for new sig-instrumentation repo "mutating-trace-admission-controller"

### ISSUE THREAD

**Issue by Monkeyanator** [kubernetes/org#287]
### GitHub Username
@Monkeyanator

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

* @dashpole 
* @Random-Liu 

### List of contributions to the Kubernetes project
- SIG projects I am involved with: author of sig-instrumentation mutating trace admission controller (https://github.com/kubernetes/org/issues/285)

/area github-membership

**Comment by dashpole** [comment]
+1

**Comment by dashpole** [comment]
Sam hasn't made any contributions yet, as [his work](https://github.com/Monkeyanator/mutating-trace-admission-controller/pull/1) for the [new repo](https://github.com/kubernetes/org/issues/285) is pending the creation of the repository.

**Comment by brancz** [comment]
+1

**Comment by dashpole** [comment]
friendly ping to @kubernetes/owners, as this is out of [SLO](https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#slos)
