### ISSUE TITLE
REQUEST: New membership for ambiknai

### ISSUE THREAD

**Issue by ambiknai** [kubernetes/org#2870]
### GitHub Username

@ambiknai

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@arahamad

### Sponsor 2

@mrbobbytables

### List of contributions to the Kubernetes project

PRs reviewed / authored
couple of PRs reviewed and authored under https://github.com/IBM

Issues responded to
Responded to issues under https://github.com/IBM
Disable CephObjectStore when COS Secret is present on IBMCloud openshift/ocs-operator#1088
In IBM Cloud if COS cred secret is missing use pv-pool for default backing store noobaa/noobaa-operator#540
Change in ibm iam endpoint s3fs-fuse/s3fs-fuse#1627
https://github.com/IBM/ibmcloud-object-storage-plugin/graphs/contributors

**Comment by nikhita** [comment]
@ambiknai Hi! As per the [membership application guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#member), you will need TWO sponsors who are not from the same employer.

Can you please update the issue body to reflect that?

**Comment by ambiknai** [comment]
@nikhita  Thanks for looking into this. Closing this request for time being as @arahamad is working on approvals.
