### ISSUE TITLE
REQUEST: New membership for kerthcet

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/org#2877]
### GitHub Username

kerthcet

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei

### Sponsor 2

@pacoxu

### List of contributions to the Kubernetes project

* PRs reviewed / authored
   * [refactor unreserve test #103642](https://github.com/kubernetes/kubernetes/pull/103642)
   * [update comment with EnqueueExtensions #103686](https://github.com/kubernetes/kubernetes/pull/103686)
   * [revert Bump DynamicKubeConfig metric deprecation to 1.23 by delta update #104075](https://github.com/kubernetes/kubernetes/pull/104075)
   
* Issues responded to
   * [Kubernetes cache data error that block helm install command #104115](https://github.com/kubernetes/kubernetes/issues/104115)
   * ["Error Cleaning Up Jobs" From Cronjob, Which is Not Really an Error #103607](https://github.com/kubernetes/kubernetes/issues/103607)
   * [Container probes support hooks?](https://github.com/kubernetes/kubernetes/issues/104023)
   * [Affinity probably present even after deleting it #103584](https://github.com/kubernetes/kubernetes/issues/103584)
   * [Eviction incorrectly forbids evicting an unready pod that wouldn't affect the PDB #103970](https://github.com/kubernetes/kubernetes/issues/103970)
   * [Scheduler: make KubeSchedulerConfiguration override the default plugins configuration #103956](https://github.com/kubernetes/kubernetes/issues/103956)
   * [In Process!!! Provide an option to mount zram instead of tmpfs when "setting the emptyDir.medium field to "Memory" #103890](https://github.com/kubernetes/kubernetes/issues/103890) 
   * [In Process!!! Allow setting EmptyDir Medium Disk #91262](https://github.com/kubernetes/kubernetes/issues/91262) 
   * [Pod Anti-Affinity not working #103848](https://github.com/kubernetes/kubernetes/issues/103848)

* SIG projects I am involved with
  * sig/scheduling
  * sig/node
  
* Kubernetes subprojects
   * [kubernetes-website: fix punctuation mistyped #29203](https://github.com/kubernetes/website/pull/29203)

**Comment by Huang-Wei** [comment]
+1

**Comment by pacoxu** [comment]
+1

**Comment by nikhita** [comment]
@kerthcet Thanks for all your contributors so far! \o/

I've created PR #2882 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by kerthcet** [comment]
thanks @nikhita , @Huang-Wei @pacoxu , I'll continuously contributing to the community! GLHF!
