### ISSUE TITLE
REQUEST: New membership for nprokopic

### ISSUE THREAD

**Issue by nprokopic** [kubernetes/org#2879]
### GitHub Username

@nprokopic

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@devigned

### Sponsor 2

@nader-ziada

### List of contributions to the Kubernetes project

PRs reviewed/authored:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1582
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1205
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1175
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/978
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/727
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1564
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1210
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1204

Issues responded to/authored:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/847
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/757
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1243
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/712
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1174
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1173
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1176

SIG projects I am involved with:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure

**Comment by nader-ziada** [comment]
+1 

thanks for all the contributions @nprokopic

**Comment by devigned** [comment]
+1

**Comment by nprokopic** [comment]
Thank you both, and of course @CecileRobertMichon, for being awesome maintainers and creating such a welcoming community!

**Comment by nikhita** [comment]
@nprokopic Thanks for all your contributors so far! \o/

I've created PR #2882 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by nprokopic** [comment]
Thanks @nikhita!
