### ISSUE TITLE
REQUEST: New membership for monotek

### ISSUE THREAD

**Issue by monotek** [kubernetes/org#288]
### GitHub Username
@monotek

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @coffeepac 
- @gianrubio 

### List of contributions to the Kubernetes project:

- PRs reviewed / authored
* https://github.com/kubernetes/kubernetes/pull/58063
* https://github.com/kubernetes/kubernetes/pull/58525
* https://github.com/kubernetes/kubernetes/pull/64372
* https://github.com/kubernetes/kubernetes/pull/67434
* https://github.com/kubernetes/kubernetes/pull/67484
* https://github.com/kubernetes/kubernetes/pull/67544
* https://github.com/kubernetes/kubernetes/pull/67582
* https://github.com/kubernetes/kubernetes/pull/71180
* https://github.com/kubernetes/kubernetes/pull/71251
* https://github.com/kubernetes/kubernetes/pull/71252
* https://github.com/kubernetes/kubernetes/pull/67583

- Issues responded to
* https://github.com/kubernetes/kubernetes/issues/58837
* https://github.com/kubernetes/kubernetes/issues/65355

- SIG projects I am involved with
via the pull requests above:
* sig/instrumentation 
* sig/cluster-lifecycle

/area github-membership

**Comment by coffeepac** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @monotek . Unfortunately, @gianrubio cannot sponsor you for membership in the @kubernetes org.  A sponsor must be an approver or reviewer at least one owners file ([membership requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements)).

Do you happen to have someone else that could step in as another sponsor?

**Comment by monotek** [comment]
Ah, sorry, to bad. 

@coffepac suggested @brancz via slack but I did not spoke to him upfront...

**Comment by mrbobbytables** [comment]
Hey there @monotek , thank you for all the work you've done so far :)

I've created PR #296  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
