### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/cluster-api-provider-openstack

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes/org#2883]
### Repository

kubernetes-sigs/cluster-api-provider-openstack

### Project domain

cluster-api-openstack.sigs.k8s.io

### Additional context for request

Corresponding PR: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/963

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes/k8s.io/pull/2654 to get DNS setup

**Comment by spiffxp** [comment]
(I'm not familiar with what else needs to be happen netlify-side for this to work)

**Comment by mrbobbytables** [comment]
Netlify has been configured, the site should be available here:
http://cluster-api-openstack.sigs.k8s.io

Note: The cert request is in flight (netlify can be instant or sometimes an hour~) It will happen eventually automatically 👍 

With that, I'm going to go ahead and close this out, if you have any issues please feel free to reopen or ping in slack.

Thanks!

**Comment by mrbobbytables** [comment]
It'd help if I remembered to close...

/close

**Comment by spiffxp** [comment]
Branch settings have been updated, PTAL

![Screen Shot 2021-11-01 at 9 32 54 AM](https://user-images.githubusercontent.com/49258/139706714-b810dfa7-4560-4a95-b447-401bd0ba3fd7.png)

**Comment by spiffxp** [comment]
Branch settings have been updated again, PTAL

![Screen Shot 2021-11-01 at 10 06 26 AM](https://user-images.githubusercontent.com/49258/139711126-3f623945-8b3e-4239-9e80-c989da858499.png)

**Comment by tobiasgiese** [comment]
Thanks @spiffxp, that's the correct configuration 🙂
