### ISSUE TITLE
Archiving cluster-api-provider-docker

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/org#2888]
### Repository to archive

https://github.com/kubernetes-sigs/cluster-api-provider-docker

### Repository and/or sig subproject owners that are approving this archival

@vincepri @neolit123

### When should this be done

Anytime

### Additional context for request

This repository has been inactive for a long time, and it's due for archival.
Rif https://github.com/kubernetes-sigs/cluster-api/issues/5087

**Comment by mrbobbytables** [comment]
repo has been archived: https://github.com/kubernetes-retired/cluster-api-provider-docker
teams removal: https://github.com/kubernetes/org/pull/3004
sigs.yaml update: https://github.com/kubernetes/community/pull/5945
Notice sent to k-dev: https://groups.google.com/g/kubernetes-dev/c/HBtyoxJbOCU/m/fTN3kBXyCwAJ

All pending items have been taken care. I'm going to go ahead and close this out. If you have any questions please feel free to reopen or ask in slack.

Thanks!

/close
