### ISSUE TITLE
REQUEST: New membership for tstromberg

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/org#289]
### GitHub Username

tstromberg

### Organization you are requesting membership in

kubernetes

### Requirements
- [✓] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [✓] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [✓] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [✓] I am actively contributing to 1 or more Kubernetes subprojects
- [✓] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [✓] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @r2d4
- @dlorenc 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - 44 authored: https://github.com/kubernetes/minikube/pulls?q=is%3Apr+author%3Atstromberg
  - 38 reviewed: https://github.com/kubernetes/minikube/pulls?q=is%3Apr+reviewed-by%3Atstromberg+-author%3Atstromberg

- Issues responded to
  - 224 commented on: https://github.com/kubernetes/minikube/issues?q=is%3Aopen+commenter%3Atstromberg+-author%3Atstromberg

- SIG projects I am involved with

- minikube

/area github-membership

**Comment by r2d4** [comment]
👍

**Comment by mrbobbytables** [comment]
Hey there @tstromberg , thanks for all the work you've put into minikube :) 

I've created PR #296  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by tstromberg** [comment]
> Welcome to @kubernetes! 🎉

Thank you!
