### ISSUE TITLE
REQUEST: New membership for shaneutt

### ISSUE THREAD

**Issue by shaneutt** [kubernetes/org#2892]
### GitHub Username

@shaneutt

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@robscott

### Sponsor 2

@hbagdi

### List of contributions to the Kubernetes project

currently working on:
- https://github.com/kubernetes-sigs/gateway-api/issues/708
- https://github.com/kubernetes-sigs/gateway-api/issues/708
- https://github.com/kubernetes-sigs/gateway-api/pull/786

previously worked on:
- https://github.com/kubernetes-sigs/kubebuilder/issues/2165
- https://github.com/kubernetes-sigs/kind/issues/2143
- https://github.com/kubernetes-sigs/kind/issues/2136
- https://github.com/kubernetes-sigs/kind/issues/732
- https://github.com/kubernetes-sigs/kustomize/issues/847
- https://github.com/kubernetes-sigs/kubebuilder/issues/571
- https://github.com/kubernetes/kubernetes/issues/76671

- https://github.com/kubernetes-sigs/gateway-api/pull/715
- https://github.com/kubernetes-sigs/gateway-api/pull/565
- https://github.com/k8snetworkplumbingwg/multus-cni/pull/555
- https://github.com/kudobuilder/kudo/pull/1488
- https://github.com/istio/istio.io/pull/7155
- https://github.com/kubernetes/community/pull/4661
- https://github.com/kubernetes-sigs/kind/pull/733
- https://github.com/kudobuilder/kudo/pull/201
- https://github.com/kubernetes-sigs/kustomize/pull/845
- https://github.com/kubernetes-sigs/kubebuilder/pull/574
- https://github.com/kubernetes-sigs/kubebuilder/pull/572

**Comment by hbagdi** [comment]
+1

**Comment by robscott** [comment]
Thanks for all the contributions @shaneutt!
 
+1

**Comment by palnabarun** [comment]
@shaneutt -- Welcome to Kubernetes! Thank you for your contributions to the community.

I have filed #2902 to add you to @kubernetes-sigs. Once that merges, you should get an invite to join the org.

Welcome again! 🎉 

/assign

**Comment by shaneutt** [comment]
> @shaneutt -- Welcome to Kubernetes! Thank you for your contributions to the community.
> 
> I have filed #2902 to add you to @kubernetes-sigs. Once that merges, you should get an invite to join the org.
> 
> Welcome again! tada
> 
> /assign

Thank you! :vulcan_salute:
