### ISSUE TITLE
REQUEST: New membership for anubha-v-ardhan

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/org#2895]
### GitHub Username

@anubha-v-ardhan

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sftim

### Sponsor 2

@nikhita

### List of contributions to the Kubernetes project

> ### `hi` localization
>> #### Tracking Issue
>>> https://github.com/kubernetes/website/issues/29353
>> #### My PRs
>>> https://github.com/kubernetes/website/pull/29373
>>> https://github.com/kubernetes/website/pull/29374
>>> https://github.com/kubernetes/website/pull/29413
>>> https://github.com/kubernetes/website/pull/29376
>>> https://github.com/kubernetes/website/pull/29396
>>> https://github.com/kubernetes/website/pull/29399
>>> https://github.com/kubernetes/website/pull/29403
>>> https://github.com/kubernetes/website/pull/29412
>> #### PRs I reviewed or I am reviewing 
>>> https://github.com/kubernetes/website/pull/29383
>>> https://github.com/kubernetes/website/pull/29420
>>> https://github.com/kubernetes/website/pull/29407
>>> https://github.com/kubernetes/website/pull/29416
>>> https://github.com/kubernetes/website/pull/29434
>>> and more .....
> ### Currently working on (other than `hi` localization)
>> https://github.com/kubernetes/website/pull/28720
>> https://github.com/kubernetes/community/issues/4469 ("Meet our contributors" blog series for APAC region)
> ### Previously worked on:
>> https://github.com/kubernetes/website/pull/28920
>> https://github.com/kubernetes/website/pull/28850
>> https://github.com/kubernetes/website/pull/28961
>> https://github.com/kubernetes/k8s.io/issues/1597

**Comment by nikhita** [comment]
+1, thanks for leading and restarting the Hindi localization effort!

/woof

**Comment by sftim** [comment]
+1, I'm happy to sponsor your membership @anubha-v-ardhan

**Comment by verma-kunal** [comment]
yay!! really great to see your contributions @anubha-v-ardhan  ✨ 
Happy to be a part of the `hi `localization effort & the "Meet our contributors" blog series for APAC, with awesome team members like you 🙂

**Comment by ShivamTyagi12345** [comment]
great effort .Happy to be a part of :)

**Comment by palnabarun** [comment]
+1 from me as well. 🚀 

@anubha-v-ardhan  -- Thank you for your contributions to the community. 👍🏽 

I have filed #2902 to add you to @kubernetes. Once that merges, you should get an invite to join the org.

Welcome again! 🎉 

/assign
/honk
