### ISSUE TITLE
REQUEST: New membership for @vrabbi

### ISSUE THREAD

**Issue by vrabbi** [kubernetes/org#2896]
### GitHub Username

@vrabbi

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@randomvariable

### Sponsor 2

@christopherhein

### List of contributions to the Kubernetes project

- Issues / PRs
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1050 
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1014
- https://github.com/kubernetes-sigs/image-builder/issues/595
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1227
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1196
- https://github.com/kubernetes-sigs/image-builder/pull/669
- Sub Projects Im involved with
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere
- https://github.com/kubernetes-sigs/cluster-api-provider-nested
- https://github.com/kubernetes-sigs/image-builder

**Comment by christopherhein** [comment]
👍  @vrabbi's membership, they are an active member in the CAPN community and helping to guide our direction and support of CAPI's APIs.

**Comment by randomvariable** [comment]
+1 from me

**Comment by savitharaghunathan** [comment]
Hi, @vrabbi 👋 Thank you for all your contributions!

I've created PR #2913  to add you to the @kubernetes-sigs organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
