### ISSUE TITLE
REQUEST: New membership for balopat

### ISSUE THREAD

**Issue by balopat** [kubernetes/org#290]
### GitHub Username
@balopat

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X ] I am actively contributing to 1 or more Kubernetes subprojects
- [X ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @r2d4
- @dlorenc

### List of contributions to the Kubernetes project
- 9 PRs authored: https://github.com/kubernetes/minikube/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Abalopat+
- 55 PRs reviewed: https://github.com/kubernetes/minikube/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Abalopat+-author%3Abalopat
- 80 Issues responded to https://github.com/kubernetes/minikube/issues?utf8=%E2%9C%93&q=is%3Aopen+commenter%3Abalopat+-author%3Abalopat
- SIG projects I am involved with
sig-cluster-lifecycle/minikube

/area github-membership

**Comment by r2d4** [comment]
👍

**Comment by dlorenc** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @balopat, thanks for all the work you've put into minikube :) 

I've created PR #296  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
