### ISSUE TITLE
REQUEST: New membership for Xunzhuo

### ISSUE THREAD

**Issue by Xunzhuo** [kubernetes/org#2900]
### GitHub Username

@Xunzhuo

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jimangel

### Sponsor 2

@PI-Victor 

### List of contributions to the Kubernetes project

PRs：
https://github.com/kubernetes/website/pull/27218
https://github.com/kubernetes/website/pull/26703
https://github.com/kubernetes/website/pull/26702
https://github.com/kubernetes/website/pull/26699
https://github.com/kubernetes/website/pull/26692
https://github.com/kubernetes/website/pull/26679
https://github.com/kubernetes/website/pull/27215
https://github.com/kubernetes/website/pull/26698
https://github.com/kubernetes/website/pull/26694
https://github.com/kubernetes/website/pull/26690
https://github.com/kubernetes/website/pull/26688

Issues：
https://github.com/kubernetes/website/issues/26720
https://github.com/kubernetes/client-go/issues/936
https://github.com/kubernetes/website/issues/26704
https://github.com/kubernetes/website/issues/26695
https://github.com/kubernetes/website/issues/26693
https://github.com/kubernetes/kubernetes/issues/94928

Others:
+ I am a cloud native engineer working with `Kubernetes` and a maintainer of some other big projects like `istio`. ☁️  
+ I am a well-experienced contributor and translator of couple of CNCF projects like `envoyproxy` in Chinese localization. ✍️ 
+ I am a popular tech writer, blogger with thousands of fans in China and a Kubernetes Advocate in China 🧑‍💻

**Comment by PI-Victor** [comment]
+1 from me!

**Comment by Xunzhuo** [comment]
@PI-Victor Thanks a lot for your sponsor ! 😄

**Comment by jimangel** [comment]
+1 Thank you for your contributions @Xunzhuo! 🎉

**Comment by Xunzhuo** [comment]
Thanks for your sponsor Jim ! 😀
