### ISSUE TITLE
REQUEST: New membership for iamNoah1

### ISSUE THREAD

**Issue by iamNoah1** [kubernetes/org#2903]
### GitHub Username

@iamNoah1

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@rikatz

### Sponsor 2

@strongjz

### List of contributions to the Kubernetes project

PRs:
- https://github.com/kubernetes/ingress-nginx/pull/7485 
- https://github.com/kubernetes/test-infra/pull/23227
- https://github.com/kubernetes/k8s.io/pull/2504
- https://github.com/kubernetes/ingress-nginx/pull/7473
- https://github.com/kubernetes/k8s.io/pull/2502
- https://github.com/kubernetes/community/pull/5937
- https://github.com/kubernetes/ingress-nginx/pull/7411

Other:
- Actively helping with issue triage 
- Participating in Biweekly meetings

**Comment by rikatz** [comment]
+1

Noah is helping us triaging the most important issues, interacting with users and proposing solutions and priorization, which actually helped us to get some weird bugs. Also helping us on all the image update automation stuff

Thanks Noah

**Comment by strongjz** [comment]
+1 

Noah continuously helps users in slack and in Github issues. He has done the arduous task of updating all the images ingress-nginx maintains and documented it for the next person. 

Thanks @iamNoah1 !

**Comment by savitharaghunathan** [comment]
Hi, @iamNoah1 👋 Thank you for all your contributions!

I've created PR #2913  to add you to the @kubernetes organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
