### ISSUE TITLE
REQUEST: New membership for seanmalloy

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes/org#2907]
### GitHub Username

@seanmalloy

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei

### Sponsor 2

@damemi

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/test-infra/pull/23288
- https://github.com/kubernetes/test-infra/pull/21019
- https://github.com/kubernetes/test-infra/pull/21038
- https://github.com/kubernetes/test-infra/pull/21602
- https://github.com/kubernetes/test-infra/pull/22238
- https://github.com/kubernetes/k8s.io/pull/1879
- https://github.com/kubernetes/k8s.io/pull/1780
- https://github.com/kubernetes/k8s.io/pull/1383

I also regularly attend the SIG scheduling meetings.

**Comment by damemi** [comment]
+1

**Comment by Huang-Wei** [comment]
Big +1!

@seanmalloy has done a lot of fabulous work in k/k, as well as some subprojects like descheduler and scheduler-plugins.

**Comment by savitharaghunathan** [comment]
Hi, @seanmalloy 👋 Thank you for all your contributions!

I've created PR #2913  to add you to the @kubernetes organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
