### ISSUE TITLE
REQUEST: New membership for mcshooter

### ISSUE THREAD

**Issue by mcshooter** [kubernetes/org#2909]
### GitHub Username

mcshooter

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ibabou

### Sponsor 2

@Random-Liu 

### List of contributions to the Kubernetes project

Node-Problem-Detector:
- #https://github.com/kubernetes/node-problem-detector/pull/544
- #https://github.com/kubernetes/node-problem-detector/pull/542
- #https://github.com/kubernetes/node-problem-detector/pull/550
- #https://github.com/kubernetes/node-problem-detector/pull/552
- #https://github.com/kubernetes/node-problem-detector/pull/555
- #https://github.com/kubernetes/node-problem-detector/pull/595
- #https://github.com/kubernetes/node-problem-detector/pull/602

Kubernetes:
- #https://github.com/kubernetes/kubernetes/pull/98705
- #https://github.com/kubernetes/kubernetes/pull/103332
- #https://github.com/kubernetes/kubernetes/pull/104112
- #https://github.com/kubernetes/kubernetes/pull/103963

test-infra
- #https://github.com/kubernetes/test-infra/pull/20757

**Comment by ibabou** [comment]
+1. LGTM

Thanks @mcshooter for all the contributions, and work done for NPD support on windows!

**Comment by Random-Liu** [comment]
LGTM

**Comment by savitharaghunathan** [comment]
Hi, @mcshooter 👋 Thank you for all your contributions!

I've created PR #2913  to add you to the @kubernetes organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by mcshooter** [comment]
Thank you @savitharaghunathan !
