### ISSUE TITLE
Request: New Membership for SataQiu

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/org#291]
### GitHub Username
@SataQiu

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markthink 
- @chenrui333 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/pulls?q=is%3Apr+author%3ASataQiu+archived%3Afalse+is%3Aclosed
- Issues responded to
  https://github.com/issues?q=is%3Aissue+author%3ASataQiu+archived%3Afalse+is%3Aclosed
  https://github.com/issues?q=is%3Aissue+assignee%3ASataQiu+archived%3Afalse+is%3Aclosed
- SIG projects I am involved with
  kubernetes/sig-docs, kubernetes/sig-cluster-lifecycle

/area github-membership

**Comment by markthink** [comment]
+1 Thank you for your contribution to the kubernetes Chinese Community

**Comment by SataQiu** [comment]
@markthink Thank you very much for your support!

**Comment by chenrui333** [comment]
👍 Thanks a lot for your contributions of sig-docs i18n-zh work.

**Comment by SataQiu** [comment]
@chenrui333 Thank you for your support. And I will try my best!

**Comment by chenrui333** [comment]
better contribution display for kubernetes/website repo:
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3ASataQiu+archived%3Afalse+is%3Aclosed+is%3Amerged++is%3Amerged+repo%3Akubernetes%2Fwebsite+

**Comment by zacharysarah** [comment]
+1, thanks for joining!

**Comment by mrbobbytables** [comment]
Hey there @SataQiu, thank you for all your translation efforts :) 

I've created PR #296  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
