### ISSUE TITLE
REQUEST: New membership for natalisucks

### ISSUE THREAD

**Issue by natalisucks** [kubernetes/org#2918]
### GitHub Username

natalisucks

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@enj

### Sponsor 2

@ritazh

### List of contributions to the Kubernetes project

- Actively involved and contributing to #sig-auth PR and Issue triage (weekly)
- Attendance/involvement in #sig-auth community meetings (bi-weekly)
- Enhancements Liaison for #sig-auth during release 1.22

**Comment by ritazh** [comment]
+1 

Thank you for your contributions.

**Comment by cblecker** [comment]
Hi, @natalisucks 👋

Thank you for all your contributions!

I've created PR #2948 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
