### ISSUE TITLE
REQUEST: New membership for @logicalhan

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/org#292]
### GitHub Username
@logicalhan

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cheftako 
- @sttts 

### List of contributions to the Kubernetes project

- PRs authored
  - add unit tests for api-service condition methods and also refactor out getAPIServiceConditionByType - https://github.com/kubernetes/kubernetes/pull/71525
  - increase the liveness probe delay for GCE e2e tests to avoid premature teardown - https://github.com/kubernetes/kubernetes/pull/71054
  - fix healthz checkerNames test so that it tests against the expected output - https://github.com/kubernetes/kubernetes/pull/70753
  - add ability to disable health checks on kube-apiserver for healthz using query-params - https://github.com/kubernetes/kubernetes/pull/70676
  - fix lint issues in the apis/abac directory (except latest.go) - https://github.com/kubernetes/kubernetes/pull/69596
  - refactor index_test to compress the assertions and make consistent with store_test.go - https://github.com/kubernetes/kubernetes/pull/69537
  - Fix a golint error on head (type doesn't need to declared as it will be inferred) - https://github.com/kubernetes/kubernetes/pull/69185
  - fix a few typographic errors in test utils file - https://github.com/kubernetes/kubernetes/pull/68903

- PRs reviewed
  - Log prometheus metric registration error and fix CRD metric names - https://github.com/kubernetes/kubernetes/pull/71767
  - Add gauge metric for master of leader election.- https://github.com/kubernetes/kubernetes/pull/71731
  - Use prometheus conventions for workqueue metrics - https://github.com/kubernetes/kubernetes/pull/71300
  - Fix incorrect url in authorization_test.go - https://github.com/kubernetes/kubernetes/pull/71545
  - aggregator: add APIService unavailability metrics - https://github.com/kubernetes/kubernetes/pull/71380
  - Fix quota controller discovery deadlock - https://github.com/kubernetes/kubernetes/pull/71516
  - add a metric that can be used to notice stuck worker threads - https://github.com/kubernetes/kubernetes/pull/70884
  - Change APIServer startup message - https://github.com/kubernetes-sigs/testing_frameworks/pull/48
  - aggregator: fix available condition transition time - https://github.com/kubernetes/kubernetes/pull/71785

- Issues responded to
  - healthz checker test doesn't test what it should - https://github.com/kubernetes/kubernetes/issues/70752
  - Add the ability to kube-apiserver's healthz endpoint to disable health checks via query params - https://github.com/kubernetes/kubernetes/issues/70591
  - [Failing Test] [sig-cluster-lifecycle] Upgrade and Downgrade jobs are failing - https://github.com/kubernetes/kubernetes/issues/70972
  - API server silently ignoring fields should be verbose - https://github.com/kubernetes/kubernetes/issues/71623
  - LivenessProbe should start after ReadinessProbe Succeeded if ReadinessProbe is specified - https://github.com/kubernetes/kubernetes/issues/27114
  - Use prometheus conventions for workqueue metrics - https://github.com/kubernetes/kubernetes/issues/71165

- SIG projects I am involved with
sig api-machinery

/area github-membership

**Comment by mrbobbytables** [comment]
Hey there @logicalhan , thank you for all your contributions so far :)

I've created PR #296   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
