### ISSUE TITLE
REQUEST: Create or Migrate kubernetes/sig-security

### ISSUE THREAD

**Issue by tabbysable** [kubernetes/org#2923]
### New repo, staging repo, or migrate existing

new repo

### Is it a staging repo?

no

### Requested name for new repository

sig-security

### Which Organization should it reside

kubernetes

### Who should have admin access?

sig-security-leads

### Who should have write access?

sig-security-leads

### Who should be listed as approvers in OWNERS?

sig-security-leads

### Who should be listed in SECURITY_CONTACTS?

IanColdwater, tabbysable

### What should the repo description be?

Process documentation, non-code deliverables, and miscellaneous artifacts of Kubernetes SIG Security

### What SIG and subproject does this fall under?

This is for general use for SIG Security and its subprojects

### Please provide references to appropriate approval for this new repo

https://groups.google.com/g/kubernetes-sig-security/c/sUUZWp5GioU/m/_M1ZtVpSAQAJ

**Comment by mrbobbytables** [comment]
qq - do you want it to be in kubernetes-sigs or kubernetes? Both sig-testing and sig-release have theirs in kubernetes org (just needs an ack from sig-arch for approval)


/assign

**Comment by tabbysable** [comment]
After reviewing the docs again, I agree that our various procedures and deliverables are "project-wide infrastructure" in much the same way as sig-release and the SRC.

I don't like how this will immediately cause `kubernetes/security` and `kubernetes/sig-security` to exist next to each other.

I'll bring this issue up at today's SIG Security meeting for community input, suggest to the SRC that we rename our repo to `kubernetes/security-response-committee`, and get back to you shortly.

Thanks!

**Comment by PushkarJ** [comment]
Adding here what I shared in the meeting:

We have bunch of issues in `k/community` that would find a home in this new repo. Transferring them through [prow](https://groups.google.com/g/kubernetes-dev/c/BKhCfLfUYtg/m/dOIDNv_XBgAJ) would be ideal. At the same time, due to limitation of Github API only issues within the _same_ Org can be transferred. So having `k/sig-security` would be preferable. 

+1 on disambiguating `k/security` and `k/sig-security` by renaming `k/security` to `k/security-response-committee`

**Comment by tabbysable** [comment]
Per the SIG security meeting today, yeah, please put it in `kubernetes/`

**Comment by mrbobbytables** [comment]
/assign @dims @johnbelamaric @derekwaynecarr
For sig-arch approval of a kubernetes org repo. 👍

**Comment by dims** [comment]
+1 from me on behalf of sig-arch

**Comment by mrbobbytables** [comment]
Repo ha been created here: https://github.com/kubernetes/sig-security
Teams will be added once this PR is merged: https://github.com/kubernetes/org/pull/2973
Subproject has been added in this PR: https://github.com/kubernetes/community/pull/6009

Once those 2 follow up items are resolved this can be closed 🎉

**Comment by mrbobbytables** [comment]
All PRs merged, teams added this is good to close 👍 
If you have any questions, please don't hesitate to reach out.

Thanks!

/close
