### ISSUE TITLE
New repo sigs.k8s.io/cluster-api-provider-kubevirt

### ISSUE THREAD

**Issue by cchengleo** [kubernetes/org#2925]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

cluster-api-provider-kubevirt

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

cchengleo, agradouski, https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES

### Who should have write access?

cchengleo, agradouski (we'll likely want to make a team for this in the long term for maintaining this group)

### Who should be listed as approvers in OWNERS?

cchengleo, agradouski, https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES

### Who should be listed in SECURITY_CONTACTS?

cchengleo, agradouski, https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES

### What should the repo description be?

Cluster API Provider for KubeVirt

### What SIG and subproject does this fall under?

sig-cluster-lifecycle

### Please provide references to appropriate approval for this new repo

- Discussed the proposal in [Wednesday August 25th, 2020](https://docs.google.com/document/d/1LdooNTbb9PZMFWy3_F-XAsl7Og5F2lvG3tCgQvoB5e4/edit#heading=h.prrfihu723mh) agenda item.
- Followed up with cluster-api leads afterward on creating the repository and got SGTMs.

### Additional context for request

This repo is meant to house the implementation of Cluster API Provider for KubeVirt. This provider will be used to create VM-based Kubernetes clusters on top of KubeVirt enabled Kubernetes clusters.

We're asking for a repo ahead to allow early collaboration among contributors from different affiliations and enforce better practices.

**Comment by vincepri** [comment]
+1

**Comment by fabiand** [comment]
+1

When can we expect the code to land?

**Comment by neolit123** [comment]
cc @nikhita @mrbobbytables 
could you please help drive this forward.

**Comment by mrbobbytables** [comment]
/assign
I should be able to create it by EoW.

**Comment by nikhita** [comment]
Hi @cchengleo! From the [Cluster API meeting notes on 25 August](https://docs.google.com/document/d/1LdooNTbb9PZMFWy3_F-XAsl7Og5F2lvG3tCgQvoB5e4/edit#heading=h.ru9tfoggfe07), it says:

> Apple team developed new one more aligned to latest Kubernetes/Cluster API and now it is looking forward to donate it to kubernetes-sigs


If the `cluster-api-provider-kubevirt` repo is intended to contain code from an existing repo (public or private), it will need to follow the guidelines listed in https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories.

If the existing repo is not open sourced yet, it will first need to be open sourced. Once this repo satisfies the guidelines linked above, we can then migrate it over to kubernetes-sigs.

If you want to chat about this on slack, feel free to reach out to us on the _#github-management_ channel on the k8s slack :)

**Comment by cchengleo** [comment]
> Hi @cchengleo! From the [Cluster API meeting notes on 25 August](https://docs.google.com/document/d/1LdooNTbb9PZMFWy3_F-XAsl7Og5F2lvG3tCgQvoB5e4/edit#heading=h.ru9tfoggfe07), it says:
> 
> > Apple team developed new one more aligned to latest Kubernetes/Cluster API and now it is looking forward to donate it to kubernetes-sigs
> 
> If the `cluster-api-provider-kubevirt` repo is intended to contain code from an existing repo (public or private), it will need to follow the guidelines listed in https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories.
> 
> If the existing repo is not open sourced yet, it will first need to be open sourced. Once this repo satisfies the guidelines linked above, we can then migrate it over to kubernetes-sigs.
> 
> If you want to chat about this on slack, feel free to reach out to us on the _#github-management_ channel on the k8s slack :)

Hi @nikhita,

After talking with cluster-api leads, we decide not to directly "forklift" the Apple internal repo to open source and migrate. Instead, it would be much easier for my colleagues to become contributors to one of the EXISTING Kubernetes projects.

I'll chat about this on slack channel too.

**Comment by nikhita** [comment]
> After talking with cluster-api leads, we decide not to directly "forklift" the Apple internal repo to open source and migrate. Instead, it would be much easier for my colleagues to become contributors to one of the EXISTING Kubernetes projects.

In the past, we have required all such code to go through the usual donation processes, so I don't think we would be able to do this.

Having said that...@caniszczyk @swinslow can you provide legal guidance if "forklifting" is an option?

**Comment by cchengleo** [comment]
> In the past, we have required all such code to go through the usual donation processes, so I don't think we would be able to do this.

I think it would be easier to use our internal implementation as a reference instead of "forklifting". Our internal implementation has a lot of Apple infrastructure dependencies. "forklifting" our internal implementation will be very "expensive" both in terms of engineering effort and time.

We would like to contribute to a community-owned project by collaborating with other companies and the PR processes.

**Comment by mrbobbytables** [comment]
From slack discussion with @caniszczyk we are good to move forward with a blank repo.
ref: https://kubernetes.slack.com/archives/C01672LSZL0/p1631795697040000

@cchengleo @agradouski as neither of you are org members, you will have to go through our regular org membership process. The [org membership form](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) has links to the relevant docs (namely our community membership guidelines). For sponsors, I'd reach out to the SIG Cluster Lifecycle leads.

Till then we can create the repo, but owners and teams will not be able to be established till org membership is complete.

**Comment by agradouski** [comment]
thanks @mrbobbytables! ack'd on membership process.

**Comment by cchengleo** [comment]
Thanks @mrbobbytables for helping with membership. Now we should be good to get the repo created.

**Comment by mrbobbytables** [comment]
repo has been created: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt
PR to update k/community: https://github.com/kubernetes/community/pull/6058

We're doing a little shuffle work on some tooling in this repo, but I should be able to add the teams before Monday. Once that's done and PRs merged, this should be complete

**Comment by cchengleo** [comment]
Thanks for the help, @mrbobbytables!

**Comment by agradouski** [comment]
super awesome! thanks a lot @mrbobbytables !

**Comment by mrbobbytables** [comment]
Teams were added in PR: https://github.com/kubernetes/org/pull/3015
All remaining AIs complete, going to go ahead and close this out.
If you have any questions, please feel free to reopen or ping in slack.

Thanks!

/close
