### ISSUE TITLE
REQUEST: New membership for abhisheksinghbaghel

### ISSUE THREAD

**Issue by abhisheksinghbaghel** [kubernetes/org#2928]
### GitHub Username

@abhisheksinghbaghel

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Jiawei0227

### Sponsor 2

@andyzhangx

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/search?q=org%3Akubernetes-sigs+abhisheksinghbaghel&type=commits

- Issues responded to
https://github.com/search?q=org%3Akubernetes-sigs+abhisheksinghbaghel&type=issues

- SIG projects I am involved with
sig-storage

**Comment by Jiawei0227** [comment]
+1

**Comment by andyzhangx** [comment]
+1

**Comment by cblecker** [comment]
Hi, @abhisheksinghbaghel 👋

Thank you for all your contributions!

I've created PR #2948 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
