### ISSUE TITLE
REQUEST: New membership for sam-cogan

### ISSUE THREAD

**Issue by sam-cogan** [kubernetes/org#2931]
### GitHub Username

sam-cogan

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@cici37

### Sponsor 2

@reylejano

### List of contributions to the Kubernetes project

Joining the 1.23 release team as a shadow on the release notes team.

**Comment by reylejano** [comment]
+1 Welcome to the 1.23 Release Team!

**Comment by cici37** [comment]
+1 Welcome!
