### ISSUE TITLE
REQUEST: New membership for katcosgrove

### ISSUE THREAD

**Issue by katcosgrove** [kubernetes/org#2933]
### GitHub Username

katcosgrove

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

reylejano

### Sponsor 2

karenhchu

### List of contributions to the Kubernetes project

It's exclusively been comms-related:

https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

https://kubernetes.io/blog/2020/12/02/dockershim-faq/

https://twitter.com/Dixie3Flatline/status/1334188913724850177

https://twitter.com/Dixie3Flatline/status/1415453192662392833

**Comment by karenhchu** [comment]
+1 Happy to have you on the K8s 1.23 RT!

CC: @reylejano

**Comment by reylejano** [comment]
+1 Welcome to the 1.23 Release Team 🎉

**Comment by cblecker** [comment]
Hi, @katcosgrove 👋

Thank you for all your contributions!

I've created PR #2948 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
