### ISSUE TITLE
REQUEST: New membership for leonardpahlke

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/org#2937]
### GitHub Username

@leonardpahlke

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@encodeflush

### Sponsor 2

@mkorbi

### List of contributions to the Kubernetes project

Joining CI Signal shadow for Kubernetes 1.23

**Comment by reylejano** [comment]
Leaonard is a 1.23 Release Team CI Signal shadow
cc @encodeflush @mkorbi

**Comment by mkorbi** [comment]
/lgtm
Happy to have you!

**Comment by encodeflush** [comment]
/lgtm
Welcome on board :)

**Comment by mrbobbytables** [comment]
@leonardpahlke  Thanks for helping out with the Release Team :)

You have now been added to the org and you should have a membership invite notification in your inbox :D

Welcome to @kubernetes! 🎉

/assign

**Comment by leonardpahlke** [comment]
I am very happy to support the project and learn more about it in the process! I have received the notification, thank you :)
