### ISSUE TITLE
REQUEST: New membership for sboeuf

### ISSUE THREAD

**Issue by sboeuf** [kubernetes/org#294]
### GitHub Username
@sboeuf

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @runcom 
- @mrunalp 
- @sameo

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cri-o/pull/566
https://github.com/kubernetes-sigs/cri-o/pull/614
https://github.com/kubernetes-sigs/cri-o/pull/623
https://github.com/kubernetes-sigs/cri-o/pull/1326
https://github.com/kubernetes-sigs/cri-o/pull/1334
https://github.com/kubernetes-sigs/cri-o/pull/1419
https://github.com/kubernetes-sigs/cri-o/pull/1489
https://github.com/kubernetes-sigs/cri-o/pull/1493
https://github.com/kubernetes-sigs/cri-o/pull/1495
https://github.com/kubernetes-sigs/cri-o/pull/1696
https://github.com/kubernetes-sigs/cri-o/pull/1822
https://github.com/kubernetes-sigs/cri-o/pull/1947
https://github.com/kubernetes-sigs/cri-o/pull/1990

- Issues responded (authored) to
https://github.com/kubernetes-sigs/cri-o/issues/659
https://github.com/kubernetes-sigs/cri-o/issues/1327
https://github.com/kubernetes-sigs/cri-o/issues/1418
https://github.com/kubernetes-sigs/cri-o/issues/1488
https://github.com/kubernetes-sigs/cri-o/issues/1491
https://github.com/kubernetes-sigs/cri-o/issues/1492
https://github.com/kubernetes-sigs/cri-o/issues/1662
https://github.com/kubernetes-sigs/cri-o/issues/1695
https://github.com/kubernetes-sigs/cri-o/issues/1704
https://github.com/kubernetes-sigs/cri-o/issues/1945
https://github.com/kubernetes-sigs/cri-o/issues/1946
https://github.com/kubernetes-sigs/cri-o/issues/1989

- SIG projects I am involved with
https://github.com/kubernetes-sigs/cri-o

/area github-membership

**Comment by justaugustus** [comment]
@runcom / @mrunalp -- Bumping this for sponsorship +1s.

**Comment by runcom** [comment]
LGTM

**Comment by idealhack** [comment]
Hey there @sboeuf, could you find another sponsor from a different company? Also, feel free to list your contributions, whether they are issues/PRs or not.

**Comment by mrbobbytables** [comment]
Thanks for catching that @idealhack. 

@sboeuf for more information on the sponsor requirements, please see the [Membership requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) in the k/community repo.

**Comment by sboeuf** [comment]
@mrbobbytables @idealhack I have updated the list of contributions, and about the sponsorship, I have added @sameo from Intel, who's also a CRI-O maintainer.
Let me know if you need anything else.

**Comment by mrunalp** [comment]
lgtm

**Comment by sameo** [comment]
LGTM

**Comment by mrbobbytables** [comment]
Hey there @sboeuf, thank you for all your contributions so far :)

I've created PR #365  to add you to the @kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by sboeuf** [comment]
Sounds good! Thanks @mrbobbytables
