### ISSUE TITLE
REQUEST: New membership for mickeyboxell

### ISSUE THREAD

**Issue by mickeyboxell** [kubernetes/org#2944]
### GitHub Username

@mickeyboxell

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@karenhchu

### Sponsor 2

@reylejano

### List of contributions to the Kubernetes project

Kubernetes 1.23 Release Comms Shadow.

**Comment by karenhchu** [comment]
+1 looking forward to working together on the RT!

**Comment by cblecker** [comment]
Hi, @mickeyboxell 👋

Thank you for all your contributions!

I've created PR #2948 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
