### ISSUE TITLE
REQUEST: New membership for Atharva-Shinde

### ISSUE THREAD

**Issue by Atharva-Shinde** [kubernetes/org#2947]
### GitHub Username

@Atharva-Shinde

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@parispittman

### Sponsor 2

@chris-short

### List of contributions to the Kubernetes project

**PR's I Reviewed**
https://github.com/kubernetes/website/pull/29022
https://github.com/kubernetes-sigs/depstat/pull/53

**My PR's**
https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/704
https://github.com/kubernetes-sigs/depstat/pull/56
https://github.com/kubernetes-sigs/contributor-tweets/pull/68
https://github.com/kubernetes-sigs/contributor-tweets/pull/67

**Created Issues**
https://github.com/kubernetes/community/issues/5976
https://github.com/kubernetes/contributor-site/issues/241

**Currently working on/ part of -**

- Drafting Tweets of _Help-Wanted_ Section for the [Kubernetes Annual Report 2020](https://www.cncf.io/reports/kubernetes-community-annual-report-2020/)
- Mentee at Community Manager Group Mentoring Cohort - https://github.com/kubernetes/community/issues/5906
- Co-ordinator and member of "Meet our contributors" Blog Post Series for the APAC region https://github.com/kubernetes/community/issues/4469

**Comment by chris-short** [comment]
Thank you for your contributions to the community @Atharva-Shinde!

/lgtm

**Comment by parispittman** [comment]
+1 🚀

**Comment by mrbobbytables** [comment]
Hey there @Atharva-Shinde  thank you for all your contributions so far :)

You have now been added to the org and you should have a membership invite notification in your inbox :D

Welcome to @kubernetes! 🎉

/assign

**Comment by Atharva-Shinde** [comment]
yayyy 🎉
Thanks @mrbobbytables
