### ISSUE TITLE
REQUEST: New membership for @geoff_cline

### ISSUE THREAD

**Issue by geoffcline** [kubernetes/org#2949]
### GitHub Username

@geoff_cline

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jimangel

### Sponsor 2

@eddiezane

### List of contributions to the Kubernetes project

- started kubernetes new contributor video project
- https://github.com/kubernetes/website/pull/26405
- https://github.com/kubernetes/website/pull/28695
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1681
- https://github.com/kubernetes/website/pull/24645

**Comment by jimangel** [comment]
+1, thanks for your contributions to k/website! 🎉

**Comment by eddiezane** [comment]
+1 thanks for helping with the kubectl docs!
