### ISSUE TITLE
Request: New Membership for yuexiao-wang

### ISSUE THREAD

**Issue by yuexiao-wang** [kubernetes/org#295]
### GitHub Username
@yuexiao-wang

### Organization you are requesting membership in
@kubernetes

### Requirements
- [√] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [√] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [√] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [√] I am actively contributing to 1 or more Kubernetes subprojects
- [√] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [√] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @fabriziopandini 
- @neolit123 

### List of contributions to the Kubernetes project
- PRs reviewed / authored 
  https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Ayuexiao-wang+is%3Aclosed
  https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ayuexiao-wang+is%3Aclosed
- Issues responded to 
  https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3Ayuexiao-wang+is%3Aclosed
- SIG projects I am involved with
  kubernetes/sig-cluster-lifecycle & kubeadm, kubernetes/sig-docs 

/area github-membership

**Comment by neolit123** [comment]
thank you for you contributions @yuexiao-wang 
+1 :tada:

**Comment by fabriziopandini** [comment]
Happy to get you on be onboard @yuexiao-wang!
+1

**Comment by mrbobbytables** [comment]
Hey there @yuexiao-wang , thank you for all the work you've done so far :)

I've created PR #296   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by yuexiao-wang** [comment]
@fabriziopandini @yuexiao-wang @mrbobbytables Thanks again
