### ISSUE TITLE
REQUEST: New membership for rashmigottipati

### ISSUE THREAD

**Issue by rashmigottipati** [kubernetes/org#2951]
### GitHub Username

@rashmigottipati

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@estroz

### Sponsor 2

@vincepri

### List of contributions to the Kubernetes project

PRs reviewed / authored
Kubebuilder: https://github.com/kubernetes-sigs/kubebuilder/pulls?q=is%3Apr+involves%3Arashmigottipati
Controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/pulls?q=is%3Apr+involves%3Arashmigottipati

Issues responded to
Kubebuilder: https://github.com/kubernetes-sigs/kubebuilder/issues?q=is%3Aissue+involves%3Arashmigottipati
Controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/issues?q=is%3Aissue+involves%3Arashmigottipati

SIG projects I am involved with
kubernetes-sigs/kubebuilder
kubernetes-sigs/controller-runtime

**Comment by vincepri** [comment]
+1

**Comment by estroz** [comment]
💯

**Comment by mrbobbytables** [comment]
@rashmigottipati  thank you for all your help with kubebuilder :)

I've created PR #2962  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
