### ISSUE TITLE
REQUEST: New membership for rajibmitra

### ISSUE THREAD

**Issue by rajibmitra** [kubernetes/org#2954]
### GitHub Username

rajibmitra

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@markyjackson-taulia

### Sponsor 2

@saschagrunert

### List of contributions to the Kubernetes project

Issues that I contributed 
https://github.com/kubernetes/kubernetes/pull/98144
https://github.com/kubernetes/kubernetes/pull/97967
https://github.com/kubernetes/release/pull/1744
https://github.com/kubernetes/k8s.io/pull/576
https://github.com/kubernetes/community/pull/4202
https://github.com/kubernetes/website/pull/19043

reviews - https://github.com/kubernetes/k8s.io/pull/377
https://github.com/kubernetes/kubernetes/pull/75432

desgin doc - https://github.com/kubernetes/k8s.io/issues/436

I have future plan for bengali language localization,will reopen once I am form a team who knows bengali language  - https://github.com/kubernetes/website/pull/17304

working in currently - 
https://github.com/kubernetes/kubernetes/issues/103032
https://github.com/kubernetes/kubernetes/issues/103150
https://github.com/kubernetes/kubernetes/issues/104234

**Comment by saschagrunert** [comment]
+1 :partying_face:

**Comment by markyjackson-taulia** [comment]
+1 my friend! Thank you for all the awesome work you have done for the community

**Comment by mrbobbytables** [comment]
Hey there @rajibmitra , thank you for all your contributions so far :)

I've created PR #2962  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by rajibmitra** [comment]
thank you so much @saschagrunert , @markyjackson-taulia and @mrbobbytables _/\_
