### ISSUE TITLE
REQUEST: New membership for bhumijgupta

### ISSUE THREAD

**Issue by bhumijgupta** [kubernetes/org#2961]
### GitHub Username

@bhumijgupta

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@parispittman

### Sponsor 2

@rikatz

### PRs Authored
- https://github.com/kubernetes/ingress-nginx/pull/7431
- https://github.com/kubernetes/ingress-nginx/pull/7434
- https://github.com/kubernetes/ingress-nginx/pull/7611
- https://github.com/kubernetes/website/pull/28740
- https://github.com/kubernetes/website/pull/29148
- https://github.com/kubernetes/website/pull/29640
- https://github.com/kubernetes/test-infra/pull/22686

### Issues Authored
- https://github.com/kubernetes/ingress-nginx/issues/7607
- https://github.com/kubernetes/ingress-nginx/issues/7447
- https://github.com/kubernetes/website/issues/29143

### Currently working on/part of
- https://github.com/kubernetes/ingress-nginx/issues/7610
- https://github.com/kubernetes/website/issues/28865
- Part of Community Manager Group Mentoring Cohort as mentee

**Comment by parispittman** [comment]
+1 thank you :)

**Comment by savitharaghunathan** [comment]
Hi @bhumijgupta 👋 Thank you for all your contributions!

I've created PR #2974 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
