### ISSUE TITLE
REQUEST: New membership for mmiranda96

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/org#2963]
### GitHub Username

mmiranda96

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@SergeyKanzhelev

### Sponsor 2

@ehashman

### List of contributions to the Kubernetes project

- [kubernetes/kubernetes#94289](https://github.com/kubernetes/kubernetes/issues/94289): Dedupe [Node.*Feature:Foo][Feature:Foo] anti-pattern.
    - [kubernetes/test-infra#22677](https://github.com/kubernetes/test-infra/pull/22677): Add tags `\[Node(?:Alpha|Special)?Feature\]` in several jobs.
    - [kubernetes/kubernetes#103674](https://github.com/kubernetes/kubernetes/pull/103674): Split deprecated tags.
- [kubernetes/test-infra#23216](https://github.com/kubernetes/test-infra/pull/23216): Add notification emails to job `ci-kubernetes-node-kubelet-feature`.
- [kubernetes/test-infra#23131](https://github.com/kubernetes/test-infra/issues/23131): Create canaries for containerd 1.5.
- [kubernetes/kubernetes#103827](https://github.com/kubernetes/kubernetes/pull/103827): Demote sysctl test from its conformance status.
- [kubernetes/node-problem-detector#607](https://github.com/kubernetes/node-problem-detector/pull/607): Create `cloudbuild.yaml` file for NPD.
- [kubernetes/kubernetes#104556](https://github.com/kubernetes/kubernetes/issues/104556): Job pull-kubernetes-node-e2e-alpha constant failure.

**Comment by SergeyKanzhelev** [comment]
I support this request! Thank you @mmiranda96

**Comment by ehashman** [comment]
:+1: Delighted to sponsor!!

**Comment by savitharaghunathan** [comment]
Hi @mmiranda96 👋 Thank you for all your contributions!

I've created PR #2974 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
