### ISSUE TITLE
REQUEST: New membership for jkh52

### ISSUE THREAD

**Issue by jkh52** [kubernetes/org#2965]
### GitHub Username

@jkh52

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@cheftako

### Sponsor 2

@andrewsykim

### List of contributions to the Kubernetes project

K/K
* mentions: https://github.com/kubernetes/kubernetes/issues?q=jkh52
* PR: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Ajkh52

ANP
* mentions: https://github.com/kubernetes-sigs/apiserver-network-proxy/issues?q=jkh52
* PR: https://github.com/kubernetes-sigs/apiserver-network-proxy/pulls?q=is%3Apr+author%3Ajkh52

**Comment by cheftako** [comment]
+1

**Comment by andrewsykim** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi @jkh52 👋 Thank you for all your contributions!

I've created PR #2974 to add you to the @kubernetes organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by jkh52** [comment]
Thanks!
