### ISSUE TITLE
Migrating csi-driver-nvmf to kubernetes-csi

### ISSUE THREAD

**Issue by MeinhardZhou** [kubernetes/org#2966]
### New repo, staging repo, or migrate existing

https://github.com/bytedance/csi-driver-nvmf

### Is it a staging repo?

no

### Requested name for new repository

csi-driver-nvmf

### Which Organization should it reside

kubernetes-csi

### Who should have admin access?

@jsafrane 
@msau42 
@saad-ali 
@xing-yang 
@meinhardzhou

### Who should have write access?

@jsafrane 
@msau42 
@saad-ali 
@xing-yang 
@meinhardzhou

### Who should be listed as approvers in OWNERS?

@jsafrane 
@msau42 
@saad-ali 
@xing-yang 
@meinhardzhou

### Who should be listed in SECURITY_CONTACTS?

@jsafrane 
@msau42 
@saad-ali 
@xing-yang 
@meinhardzhou

### What should the repo description be?

CSI driver NVMf mainly supports RDMA and TCP for Software Defined Storage by NVMf.
https://nvmexpress.org/developers/nvme-of-specification/

### What SIG and subproject does this fall under?

A subproject called csi-driver-nvmf under SIG Storage

### Please provide references to appropriate approval for this new repo

@xing-yang

**Comment by xing-yang** [comment]
Please add sig-storage leads.  See this example: https://github.com/kubernetes/org/issues/2701

**Comment by xing-yang** [comment]
For this question "What SIG and subproject does this fall under?", the answer should be "A subproject called csi-driver-nvmf under SIG Storage".

**Comment by MeinhardZhou** [comment]
@xing-yang Done

**Comment by mrbobbytables** [comment]
@MeinhardZhou For donated repos, theres some additional processes that need to be followed - please see the [rules for donated repos](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories). It includes things like license headers etc.

You will also need to open up an [org membership request](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E). The form has links to the various relevant parts required for membership. For sponsors, I'd suggest reaching out to members from SIG Storage.

**Comment by mrbobbytables** [comment]
@MeinhardZhou a general reminder - we cannot move forward with repo migration till the items outlined in [rules for donated repos](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories) have been completed - this includes adding boilerplate, owners files etc.

**Comment by MeinhardZhou** [comment]
@mrbobbytables I have updated the headers and OWNERS files, could you please check and let me know if anything missing.

**Comment by MeinhardZhou** [comment]
@mrbobbytables PING

**Comment by mrbobbytables** [comment]
The k/community PR has merged. This is good to close out!

/close
