### ISSUE TITLE
Rename kubernetes/security to kubernetes/committee-security-response

### ISSUE THREAD

**Issue by tabbysable** [kubernetes/org#2967]
### Organization or Repo

kubernetes/security

### Describe the issue

To disambiguate things, please rename the repo `kubernetes/security` to `kubernetes/committee-security-response`. See also #2923.

We don't believe there are significant external references to this repo, so renaming it should be safe.

**Comment by PushkarJ** [comment]
/area github-repo

Found one mention of `k/security` in `k/website`. This PR fixes it: https://github.com/kubernetes/website/pull/29693

**Comment by mrbobbytables** [comment]
repo has now been renamed 👍 

Now might be another good time to rename the default branch from `master` -> `main` while we're updating links and such

**Comment by PushkarJ** [comment]
@tabbysable I am happy to migrate from `master` --> `main` for `k/committee-security-response`, if nobody else from SRC can pick it up :)

**Comment by mrbobbytables** [comment]
I can take care of the branch rename in the repo, just want to make sure its done with folks knowledge and the reference in k/community will need to be updated in https://github.com/kubernetes/community/pull/6008

**Comment by tabbysable** [comment]
+1 from me for master->main upgrade, and I've pinged the rest of the SRC

**Comment by mrbobbytables** [comment]
branch has been updated to main 👍

**Comment by mrbobbytables** [comment]
With both the branch and the repo renamed, I'm going to go ahead and close this out. 
If you need anything, please feel free to reopen.

Thanks!

/close
