### ISSUE TITLE
REQUEST: New membership for nirmalaagash

### ISSUE THREAD

**Issue by nirmalaagash** [kubernetes/org#2968]
### GitHub Username

@nirmalaagash

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@AndyXiangLi

### Sponsor 2

@jsafrane

### PR authored
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1019
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/980
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/978
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/976

### Issues responded
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1044
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1033
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1027
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1024
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1012

### Sig projects involved
- AWS-EBS-CSI-DRIVER https://github.com/kubernetes-sigs/aws-ebs-csi-driver

**Comment by AndyXiangLi** [comment]
+1

**Comment by jsafrane** [comment]
+1

**Comment by vdhanan** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi @nirmalaagash 👋 Thank you for all your contributions!

I've created PR #2974 to add you to the @kubernetes organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
