### ISSUE TITLE
REQUEST: New membership for Pingan2017

### ISSUE THREAD

**Issue by Pingan2017** [kubernetes/org#297]
### GitHub Username
@Pingan2017
### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zhangxiaoyu-zidif 
- @xiangpengzhao 
- @soltysh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/pulls?q=is%3Apr+author%3APingan2017+archived%3Afalse
- Issues responded to
https://github.com/issues?q=is%3Aissue+author%3APingan2017+archived%3Afalse
- SIG projects I am involved with
kubernetes/sig-cli
kubernetes/sig-node

/area github-membership

**Comment by xiangpengzhao** [comment]
![image](https://user-images.githubusercontent.com/15881573/49782641-00f4f800-fd52-11e8-9ed3-a18ba8e243d1.png)

**Comment by zhangxiaoyu-zidif** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @Pingan2017, thank you for all your contributions so far :)

I've created PR #306 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
