### ISSUE TITLE
REQUEST: New membership for pydctw

### ISSUE THREAD

**Issue by pydctw** [kubernetes/org#2975]
### GitHub Username

@pydctw

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@randomvariable

### Sponsor 2

@richardcase

### List of contributions to the Kubernetes project

PRs authored
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2728
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2715
- https://github.com/kubernetes-sigs/controller-runtime/pull/1282
- https://github.com/kubernetes-sigs/controller-runtime/pull/1283

PRs reviewed
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2740

SIG projects I am involved with
- https://github.com/kubernetes-sigs/cluster-api-provider-aws
- https://github.com/kubernetes-sigs/controller-runtime

**Comment by richardcase** [comment]
Thanks for your contributions:

+1

**Comment by randomvariable** [comment]
+1

**Comment by shivi28** [comment]
Thanks for your contributions @pydctw 🎉 
+1

**Comment by sedefsavas** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @pydctw, thank you for all your contributions so far :)

I've created PR #3003  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
