### ISSUE TITLE
REQUEST: New membership for kundan2707

### ISSUE THREAD

**Issue by kundan2707** [kubernetes/org#2976]
### GitHub Username

@kundan2707

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@rikatz

### Sponsor 2

@spiffxp

### List of contributions to the Kubernetes project

I m actively involved in bug triaging , Improved documentation, fixing issues etc.

- PRs reviewed / authored
https://github.com/search?q=is%3Apr+author%3Akundan2707++org%3Akubernetes+org%3Akubernetes-sigs&type=Issues
- Issues responded to
 https://github.com/search?q=commenter%3Akundan2707++org%3Akubernetes+org%3Akubernetes-sigs&type=Issues
- SIG projects I am involved with
1. ingress-nginx
2. external-dns
3. gateway-api
4. sig-network
5. kpng

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by rikatz** [comment]
+1 from me

**Comment by mrbobbytables** [comment]
@kundan2707 thank you for all your contributions so far \o/

I've created PR #3003  to add you to both orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
