### ISSUE TITLE
REQUEST: New membership for cici37

### ISSUE THREAD

**Issue by cici37** [kubernetes/org#2981]
### GitHub Username

@cici37

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@wilsonehusin

### Sponsor 2

@reylejano

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/release-notes/pull/239
- https://github.com/kubernetes-sigs/release-notes/pull/244
- https://github.com/kubernetes-sigs/release-notes/pull/243
- I have been mainly involved in release-notes project and be responsible for updating relnotes.k8s.io as 1.23 release team release notes lead.

**Comment by reylejano** [comment]
+1 @cici37 is the Kubernetes 1.23 Release Notes lead 🎉

**Comment by mrbobbytables** [comment]
You're good 👍 as a member already you don't have to request membership :) If you want to open a PR adding you with the commit message `Add cici37 to kubernetes-sigs org` can get it approved quick, otherwise it'll be batched in the next series of org membership requests.

**Comment by cici37** [comment]
Thank you @mrbobbytables ! Will do so^^

**Comment by cici37** [comment]
Replace with https://github.com/kubernetes/org/pull/2982

**Comment by mrbobbytables** [comment]
Should be good to close with #2982 merged 👍 

Let me know if you need anything else!

/close
