### ISSUE TITLE
REQUEST: New membership for verma-kunal

### ISSUE THREAD

**Issue by verma-kunal** [kubernetes/org#2983]
### GitHub Username

@verma-kunal

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@divya-mohan0209

### Sponsor 2

@PushkarJ

### List of contributions to the Kubernetes project

> ### List of contributions to the Kubernetes project
> > ### PRs Authored:
> > 
> > - [**kubernetes/website#29432**](https://github.com/kubernetes/website/pull/29432)
> > - [**kubernetes/website#29421**](https://github.com/kubernetes/website/pull/29421)
> > - [**kubernetes/website#29420**](https://github.com/kubernetes/website/pull/29420)
> > - [**kubernetes/website#29410**](https://github.com/kubernetes/website/pull/29410)
> > - [**kubernetes/website#29408**](https://github.com/kubernetes/website/pull/29408)
> > - [**kubernetes/website#29383**](https://github.com/kubernetes/website/pull/29383)
> > - [**kubernetes/website#29372**](https://github.com/kubernetes/website/pull/29372)
> > - [**kubernetes/community#5844**](https://github.com/kubernetes/community/pull/5844)
> > 
> > 
> > ### PRs I have reviewed/reviewing:
> > 
> > - [**kubernetes/website#29373**](https://github.com/kubernetes/website/pull/29373)
> > - [**kubernetes/website#29412**](https://github.com/kubernetes/website/pull/29412)
> > - [**kubernetes/website#29405**](https://github.com/kubernetes/website/pull/29405)
> >
> > 
> > ### Initiatives I am part of (SIG Projects): 
> > 
> > - "Meet Our Contributors" Blog Series for APAC region - [**kubernetes/community#4469**](https://github.com/kubernetes/community/issues/4469) 
> > - Hindi Docs Localisation - [**kubernetes/community#29353**](https://github.com/kubernetes/website/issues/29353)

**Comment by PushkarJ** [comment]
Big +1 looking forward to more contributions from you, Kunal :-)

**Comment by verma-kunal** [comment]
> Big +1 looking forward to more contributions from you, Kunal :-)

thank you so much!! 🙂

**Comment by divya-mohan0209** [comment]
Super big +1 for Kunal! Hope to see you shine in the community :)

**Comment by verma-kunal** [comment]
> Super big +1 for Kunal! Hope to see you shine in the community :)

Thank you so much!! Means a lot ✨

**Comment by anubha-v-ardhan** [comment]
Big +1, You did great works with Hindi localization and APAC blog series. Looking forward to have you as reviewer for Kubernetes `hi` docs. 
Yayyy!!

**Comment by verma-kunal** [comment]
> Big +1, You're doing great work with Hindi localization and APAC blog series. Looking forward to have you as reviewer for Kubernetes `hi` docs.
> Yayyy!!

Thanks @anubha-v-ardhan !! Its great to be in the network of awesome folks like you in the community 🙂

**Comment by mrbobbytables** [comment]
@verma-kunal , thank you for all your contributions so far :)

I've created PR #3003   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by verma-kunal** [comment]
> @verma-kunal , thank you for all your contributions so far :)
> 
> I've created PR #3003 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉
> 
> /assign

Thank you so much @mrbobbytables !! Means a lot & really glad to be a part of an amazing community ❤️
