### ISSUE TITLE
REQUEST: New membership for meinhardzhou

### ISSUE THREAD

**Issue by MeinhardZhou** [kubernetes/org#2985]
### GitHub Username

@meinhardzhou

### Organization you are requesting membership in

kubernetes-csi

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@msau42

### List of contributions to the Kubernetes project

I am preparing to contribute the code repository("csi-driver-nvmf") to kubernetes-csi

- Issued respond to
   https://github.com/kubernetes/org/issues/2966

**Comment by xing-yang** [comment]
+1

**Comment by MeinhardZhou** [comment]
@msau42 PING

**Comment by msau42** [comment]
+1

**Comment by nikhita** [comment]
@MeinhardZhou Thanks for all your contributors so far! \o/

I've created PR #3025 to add you to the @kubernetes-csi organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-csi! 🎉

/assign
