### ISSUE TITLE
REQUEST: New membership for YuviGold

### ISSUE THREAD

**Issue by YuviGold** [kubernetes/org#2986]
### GitHub Username

@YuviGold

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@chaodaiG

### Sponsor 2

@petr-muller

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/104783
  - https://github.com/kubernetes/test-infra/pull/23483
  - https://github.com/kubernetes/test-infra/pull/22302
  - https://github.com/kubernetes/test-infra/pull/22317
  - https://github.com/kubernetes/test-infra/pull/22580
  - https://github.com/kubernetes/test-infra/pull/22711
  - https://github.com/kubernetes/test-infra/pull/22712
  - https://github.com/kubernetes/test-infra/pull/22747
  - https://github.com/kubernetes/test-infra/pull/22760
  - https://github.com/kubernetes/test-infra/pull/22803
  - https://github.com/kubernetes/test-infra/pull/22812
  - https://github.com/kubernetes/test-infra/pull/22856
  - https://github.com/kubernetes/test-infra/pull/23016
  - https://github.com/kubernetes/test-infra/pull/23088
  - https://github.com/kubernetes/test-infra/pull/23342
  - https://github.com/kubernetes/test-infra/pull/23429
  - https://github.com/kubernetes/test-infra/pull/23645

- Issues responded to
  - https://github.com/kubernetes/test-infra/issues/23062
  - https://github.com/kubernetes/test-infra/issues/14226
  - https://github.com/kubernetes/test-infra/issues/21556
  - https://github.com/kubernetes/test-infra/issues/5183
  - https://github.com/kubernetes/kubernetes/issues/102975
  - https://github.com/kubernetes/test-infra/issues/23025

- SIG projects I am involved with
   - sig-testing

**Comment by chaodaiG** [comment]
LGTM

**Comment by petr-muller** [comment]
LGTM

**Comment by mrbobbytables** [comment]
@YuviGold  thank you for all your contributions so far :)

I've created PR #3003  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
