### ISSUE TITLE
Need Oauth application key for Elekto for SC elections

### ISSUE THREAD

**Issue by jberkus** [kubernetes/org#2987]
### Organization or Repo

kubernetes/community

### Name of integration

Elekto

### Link to integration website

elections.k8s.io

### Describe what is attempting to be accomplished

The Elekto application for the SC elections needs to log in users via GitHub Oauth.  As such, it needs a GH Oauth application key.

Please share the userid and secret for this key with @ameukam, who is doing the setup.

Callback is at /oauth/github/callback

attn: @mrbobbytables 

/sig contributor-experience
/committee steering

**Comment by jberkus** [comment]
Note: this is dependent on a separate request from @ameukam to create elections.k8s.io

**Comment by mrbobbytables** [comment]
@ameukam would this be something that a current infra account could be used for? or do you think we should provision a new one?

**Comment by ameukam** [comment]
> @ameukam would this be something that a current infra account could be used for? or do you think we should provision a new one?

@mrbobbytables we can use a current infra account. It's only for authentication.

**Comment by mrbobbytables** [comment]
This has been configured, @jberkus can you confirm its all in working order?

**Comment by jberkus** [comment]
Confirmed

/close
