### ISSUE TITLE
REQUEST: New membership for shivanshu1333

### ISSUE THREAD

**Issue by shivanshu1333** [kubernetes/org#2993]
### GitHub Username

@shivanshu1333

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@serathius

### Sponsor 2

@mengjiao-liu

### List of contributions to the Kubernetes project

PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/105122
https://github.com/kubernetes/kubernetes/pull/105035
https://github.com/kubernetes/kubernetes/pull/104931
https://github.com/kubernetes/kubernetes/pull/104908
https://github.com/kubernetes/kubernetes/pull/104932
https://github.com/kubernetes/kubernetes/pull/104891
https://github.com/kubernetes/kubernetes/pull/104877

Issues authored
https://github.com/kubernetes/kubernetes/issues/104872
https://github.com/kubernetes/kubernetes/issues/105148

SIG projects I am involved with
[sig-instrumentation](https://github.com/kubernetes/community/tree/master/contributors/devel/sig-instrumentation)

**Comment by serathius** [comment]
/lgtm
Great work on organizing kube-proxy migration!

**Comment by mengjiao-liu** [comment]
+1 
Well done, you get a lot of work done in structured logging.

**Comment by mrbobbytables** [comment]
Hey there @shivanshu1333, thank you for all your contributions so far :)

I've created PR #3003  to add you to both orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by shivanshu1333** [comment]
Thanks a lot everyone <3
/pony party
