### ISSUE TITLE
REQUEST: New membership for cchengleo

### ISSUE THREAD

**Issue by cchengleo** [kubernetes/org#2994]
### GitHub Username

cchengleo

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@fabriziopandini

### Sponsor 2

@parispittman

### List of contributions to the Kubernetes project

- Propose to create cluster-api-provider-kubevirt and leading the effort (pending #2925)
- Early contributions to vsphere-csi-driver
- Feature PRs to kubevirt

**Comment by fabriziopandini** [comment]
+1
Looking forward for @cchengleo to kick off the work on the cluster-api-provider-kubevirt

**Comment by parispittman** [comment]
+1 thanks Cheng!!

**Comment by mrbobbytables** [comment]
Hey there @cchengleo , thank you for all your contributions so far :)

I've created PR #3003  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign

**Comment by cchengleo** [comment]
Thanks @mrbobbytables!
