### ISSUE TITLE
REQUEST: New membership for agradouski

### ISSUE THREAD

**Issue by agradouski** [kubernetes/org#2995]
### GitHub Username

@agradouski

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@fabriziopandini

### Sponsor 2

@parispittman

### List of contributions to the Kubernetes project

- participating in sig-cluster-lifecycle, cluster-api, slack, sig meetings, office hours
- https://github.com/kubernetes-sigs/cluster-api-provider-kubemark
- open sourcing cluster-api-provider-kubevirt (pending https://github.com/kubernetes/org/issues/2925)

**Comment by fabriziopandini** [comment]
+1
Looking forward for @agradouski  to kick off the work on the cluster-api-provider-kubevirt

**Comment by parispittman** [comment]
+1 thanks Alex!!

**Comment by mrbobbytables** [comment]
@agradouski  , thank you for all your contributions so far :)

I've created PR #3003  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉

/assign
