### ISSUE TITLE
REQUEST: New membership for CIPHERTron

### ISSUE THREAD

**Issue by CIPHERTron** [kubernetes/org#2999]
### GitHub Username

@CIPHERTron

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@parispittman

### Sponsor 2

@palnabarun

### List of contributions to the Kubernetes project

- PRs Reviewed/Authored:
  - https://github.com/kubernetes/kubernetes/pull/104908
  - https://github.com/kubernetes-sigs/scheduler-plugins/pull/250
  - https://github.com/kubernetes/website/pull/29644
- Working on:
  - https://github.com/kubernetes/website/issues/29155
  - https://github.com/kubernetes/community/issues/4469
  - https://github.com/kubernetes/community/issues/5906
  - https://github.com/kubernetes/website/issues/29290
- Issue created
  - https://github.com/kubernetes/website/issues/29667
  - https://github.com/kubernetes/community/issues/6042

**Comment by palnabarun** [comment]
+1 from me!

/pony party

**Comment by parispittman** [comment]
+1 

tysm :)

**Comment by anubha-v-ardhan** [comment]
big +1, welcome to Kubernetes, tysm

/woof

**Comment by CIPHERTron** [comment]
Thank you @palnabarun @parispittman & @anubha-v-ardhan 😃🥳

**Comment by nikhita** [comment]
@CIPHERTron Thanks for all your contributors so far! \o/

I've created PR #3025 to add you to the @kubernetes and @kubernetes-sigs organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
