### ISSUE TITLE
REQUEST: New membership for RyanAoh

### ISSUE THREAD

**Issue by RyanAoh** [kubernetes/org#3000]
### GitHub Username

@RyanAoh

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@soltysh

### Sponsor 2

@pacoxu

### List of contributions to the Kubernetes project

- PRs authored：
https://github.com/kubernetes/kubernetes/pull/101370
https://github.com/kubernetes/kubernetes/pull/104332
https://github.com/kubernetes/kubernetes/pull/104570
https://github.com/kubernetes/kubernetes/pull/104799

- Issues authored/responded to
https://github.com/kubernetes/kubernetes/issues/101648
https://github.com/kubernetes/kubernetes/issues/104195
https://github.com/kubernetes/kubernetes/issues/104012
https://github.com/kubernetes/kubernetes/issues/103607
https://github.com/kubernetes/kubernetes/issues/104618
https://github.com/kubernetes/kubernetes/issues/91489
https://github.com/virtual-kubelet/virtual-kubelet/issues/867

**Comment by soltysh** [comment]
:+1: for me :)

**Comment by pacoxu** [comment]
+1 and hope to see more contributions from you!
👍

And I may cooperate with you in area/cronjob. 😄

**Comment by mrbobbytables** [comment]
@RyanAoh  , thank you for all your contributions so far :)

I've created PR #3003  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by RyanAoh** [comment]
Thanks @mrbobbytables @soltysh @pacoxu
