### ISSUE TITLE
REQUEST: New membership for nehaLohia27

### ISSUE THREAD

**Issue by nehaLohia27** [kubernetes/org#3002]
### GitHub Username

@nehaLohia27

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@PushkarJ

### Sponsor 2

@strongjz

### List of contributions to the Kubernetes project

PRs authored
https://github.com/kubernetes/test-infra/pull/23123
https://github.com/kubernetes/test-infra/pull/23419
https://github.com/kubernetes/ingress-nginx/issues/7622
https://github.com/kubernetes/ingress-nginx/pull/7671

Issues authored
https://github.com/kubernetes/test-infra/issues/23112
https://github.com/kubernetes/sig-security/issues/4
https://github.com/kubernetes/ingress-nginx/issues/7617
https://github.com/kubernetes/ingress-nginx/issues/7447

Sig-projects involved in
sig-network
sig-security

**Comment by PushkarJ** [comment]
Big +1. Neha is making a big impact already as a contributor and brings with her deep expertise of Kubernetes having passed CKA and CKAD both. Look forward to even more contributions from you as a member!!

**Comment by rikatz** [comment]
+1 (not counting, as I work on the same company as @PushkarJ but anyway), Neha has been doing some great work helping with ingress issues and PRs, being actually the responsible for v1.0.0 release :)

Also she has been started to help on some kubeproxy cleanup!

**Comment by strongjz** [comment]
+1 for Neha. Working issues and helping with releases! We need more folks like her in this project.

**Comment by nikhita** [comment]
@nehaLohia27 Thanks for all your contributors so far! \o/

I've created PR #3025 to add you to the @kubernetes and @kubernetes-sigs organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
