### ISSUE TITLE
REQUEST: New membership for vedant-kakde

### ISSUE THREAD

**Issue by vedant-kakde** [kubernetes/org#3006]
### GitHub Username

@vedant-kakde

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@parispittman

### Sponsor 2

@divya-mohan0209

### List of contributions to the Kubernetes project

**PRs Authored:**

- [kubernetes/website#29469](https://github.com/kubernetes/website/pull/29469)
- [kubernetes/website#29474](https://github.com/kubernetes/website/pull/29474)
- [kubernetes/website#29465](https://github.com/kubernetes/website/pull/29465)
- [kubernetes/website#29461](https://github.com/kubernetes/website/pull/29461)
- [kubernetes/website#29457](https://github.com/kubernetes/website/pull/29457)

**PRs I have reviewed/reviewing:**

- [kubernetes/website#29518](https://github.com/kubernetes/website/pull/29518)
- [kubernetes/website#29514](https://github.com/kubernetes/website/pull/29514)
- [kubernetes/website#29458](https://github.com/kubernetes/website/pull/29458)
- [kubernetes/website#29469](https://github.com/kubernetes/website/pull/29469)
- [kubernetes/website#29461](https://github.com/kubernetes/website/pull/29461)

**Initiatives I am part of :**

- Mentee at Community Manager Group Mentoring Cohort - [kubernetes/community#5906](https://github.com/kubernetes/community/issues/5906)
- K8s Documentation Localization for the Hindi language - [kubernetes/website#29353](https://github.com/kubernetes/website/issues/29353)
- Co-ordinator for the "Meet Our Contributors" Blog series for the APAC region - [kubernetes/community#4469](https://github.com/kubernetes/community/issues/4469)

**Comment by parispittman** [comment]
+1! tysm!!!

**Comment by vedant-kakde** [comment]
> +1! tysm!!!

Thank you so much ! 🙂✨

**Comment by sftim** [comment]
Thanks for stepping forward, @vedant-kakde

**Comment by divya-mohan0209** [comment]
Huuuuuuge +1 from my side. Thank you Vedant for all your contributions & looking forward to see more of you in the community :)

**Comment by vedant-kakde** [comment]
> Huuuuuuge +1 from my side. Thank you Vedant for all your contributions & looking forward to see more of you in the community :)

Thank you so much Divya 🙂✨
/meow

**Comment by anubha-v-ardhan** [comment]
Wooh @vedant-kakde Thanks for all the amazing work. BIG +1, Glad to see new contributors becoming members !!!!

/woof

**Comment by verma-kunal** [comment]
really glad to see new folks contributing & getting involved in the community🎉
Big +1 from my side as well

**Comment by nikhita** [comment]
@vedant-kakde Thanks for all your contributors so far! \o/

I've created PR #3025 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by vedant-kakde** [comment]
> @vedant-kakde Thanks for all your contributors so far! \o/
> 
> I've created PR #3025 to add you to the @kubernetes organization. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉
> 
> /assign

Thank you so much @nikhita 😄✨

**Comment by vedant-kakde** [comment]
@nikhita will you please add @kubernetes-sigs organizations as well or I need to open another issue for it ?
