### ISSUE TITLE
REQUEST: New membership for interma

### ISSUE THREAD

**Issue by interma** [kubernetes/org#301]
### GitHub Username
@interma

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mengqiy 
- @fanzhangio 
- @hoegaarden

### List of contributions to the Kubernetes project
- PRs authored
https://github.com/kubernetes/kubernetes/pull/65524
https://github.com/kubernetes-incubator/apiserver-builder/pull/255
https://github.com/kubernetes/community/pull/2403
https://github.com/kubernetes-sigs/kubebuilder/pull/352
https://github.com/kubernetes-sigs/controller-runtime/pull/129
https://github.com/kubernetes-sigs/controller-runtime/pull/130
https://github.com/kubernetes-sigs/kubebuilder/pull/463
https://github.com/kubernetes-sigs/controller-runtime/pull/193

- PRs reviewed
https://github.com/kubernetes/kubernetes/pull/66492
https://github.com/kubernetes/kubernetes/pull/66890
https://github.com/kubernetes-sigs/kubebuilder/pull/343
https://github.com/kubernetes/kubernetes/pull/67587
https://github.com/kubernetes/kubernetes/pull/67890
https://github.com/kubernetes-sigs/controller-runtime/pull/136

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/66578
https://github.com/kubernetes/kubernetes/issues/66848
https://github.com/kubernetes/website/issues/9417
https://github.com/kubernetes-incubator/apiserver-builder/issues/253
https://github.com/kubernetes-sigs/kubebuilder/issues/342

- SIG projects I am involved with
SIG-apimachinery
https://github.com/kubernetes-sigs/kubebuilder/

/area github-membership

**Comment by mengqiy** [comment]
+1

**Comment by fanzhangio** [comment]
+1

**Comment by interma** [comment]
Thanks for your help in community. @fanzhangio @mengqiy !
Looking forward to make kubernetes and kubebuilder better.

**Comment by mrbobbytables** [comment]
Hey there @interma, my apologies for the delayed response. I've been slow to catch up on everything after KubeCon. 

Unfortunately @fanzhangio  cannot sponsor you for membership. A sponsor must be an approver or reviewer to be able to +1 a membership request ([sponsor requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements)). 

Is there someone else that might be able to sponsor you?

**Comment by interma** [comment]
@mrbobbytables Thanks for your remind.

I noticed @fanzhangio had an opened PR: https://github.com/kubernetes-sigs/kubebuilder/pull/522, this PR will add him to owner list. 
Does this mean he will meet the sponsor requirements after the PR is merged? If so, I will ping you when the PR is merged.

Thanks.

**Comment by mrbobbytables** [comment]
Sort of. Org membership is scoped with @kubernetes as the parent or root.  Once @fanzhangio is merged, they can sponsor you for membership in @kubernetes-sigs, but could not sponsor you for @kubernetes. @kubernetes-sigs is a _"child"_ org under @kubernetes. If they were an approver/reviewer in a project under the root org (@kubernetes) they could sponsor you for membership in both.

If you'd like to proceed with @fanzhangio as your 2nd sponsor, can you amend your org request to be just @kubernetes-sigs?  I can then get a PR out as soon as they're merge in. :)

If you have any questions, please don't hesitate to ask here or feel free to poke me on slack. 

Thanks!

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #358 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign

**Comment by interma** [comment]
Thank you guys.
