### ISSUE TITLE
REQUEST: New membership for Rajalakshmi-Girish

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/org#3014]
### GitHub Username

@Rajalakshmi-Girish

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mkumatag

### Sponsor 2

@dims

### List of contributions to the Kubernetes project

- PRs reviewed / authored
> - https://github.com/kubernetes/kubernetes/pull/96906
> - https://github.com/kubernetes/test-infra/pulls?q=author%3ARajalakshmi-Girish+
- Issues responded to
> - https://github.com/kubernetes/test-infra/issues/23449
> - https://github.com/kubernetes/kubernetes/issues/102987
> - https://github.com/kubernetes/kubernetes/issues/101657
> - https://github.com/kubernetes/kubernetes/issues/100127
> - https://github.com/kubernetes/kubernetes/issues/97331
> - https://github.com/kubernetes/kubernetes/issues/96853
- SIG projects I am involved with
> - testing
> -  cluster-api-provider-ibmcloud

**Comment by dims** [comment]
+1 from me. thanks for all your work @Rajalakshmi-Girish !

**Comment by mkumatag** [comment]
+1 from me as well.. 

Thanks for your contributions..

**Comment by nikhita** [comment]
@Rajalakshmi-Girish Thanks for all your contributors so far! \o/

I've created PR #3025 to add you to the @kubernetes and @kubernetes-sigs organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
