### ISSUE TITLE
REQUEST: New membership for dcantah

### ISSUE THREAD

**Issue by dcantah** [kubernetes/org#3017]
### GitHub Username

dcantah

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jsturtevant

### Sponsor 2

@claudiubelu

### List of contributions to the Kubernetes project

- PRs authored / reviewed

    - `kubernetes/kubernetes`
        - https://github.com/kubernetes/kubernetes/pull/104952
        - https://github.com/kubernetes/kubernetes/pull/104880
        - https://github.com/kubernetes/kubernetes/pull/104490
        - https://github.com/kubernetes/kubernetes/pull/103434
        - https://github.com/kubernetes/kubernetes/pull/99576

    - `kubernetes-sigs/secrets-store-csi-driver`
        - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/729

    - `kubernetes/enhancements`
        - https://github.com/kubernetes/enhancements/pull/2288
        - https://github.com/kubernetes/enhancements/pull/2865

    - `kubernetes/website`
        - https://github.com/kubernetes/website/pull/29022
        - https://github.com/kubernetes/website/pull/28413

    - `microsoft/hcsshim` (Host Process containers work)
        - https://github.com/microsoft/hcsshim/pull/903
        - https://github.com/microsoft/hcsshim/pull/979
        - https://github.com/microsoft/hcsshim/pull/962
        - https://github.com/microsoft/hcsshim/pull/1057
        - https://github.com/microsoft/hcsshim/pull/983
        - https://github.com/microsoft/hcsshim/pull/954

    - `containerd/containerd`
        - https://github.com/containerd/containerd/pull/4630
        - https://github.com/containerd/containerd/pull/5836
        - https://github.com/containerd/containerd/pull/5865
        - https://github.com/containerd/containerd/pull/4635
        - https://github.com/containerd/containerd/pull/4643

    - `containerd/cgroups`
        - https://github.com/containerd/cgroups/pull/154

    - `containerd/cri`
        - https://github.com/containerd/cri/pull/1505

    - `containernetworking/plugins`
        - https://github.com/containernetworking/plugins/pull/617

- Issues responded to/opened
        - https://github.com/kubernetes/kubernetes/issues/104827
        - https://github.com/kubernetes/kubernetes/issues/92963

- SIG projects I am involved in
    - sig-windows

**Comment by dcantah** [comment]
cc @marosset @jayunit100

**Comment by dims** [comment]
+1 from me as well :)

**Comment by marosset** [comment]
+1 from me!

**Comment by claudiubelu** [comment]
+1 from me, he also helped me with some issues I was having with setting up Windows HostProcesses. His knowledge is invaluable.

**Comment by jsturtevant** [comment]
+1 from me!

**Comment by nikhita** [comment]
@dcantah Thanks for all your contributors so far! \o/

I've created PR #3025 to add you to the @kubernetes and @kubernetes-sigs organizations. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
