### ISSUE TITLE
REQUEST: New membership for syjabri

### ISSUE THREAD

**Issue by syjabri** [kubernetes/org#302]
### GitHub Username
@syjabri

### Organization you are requesting membership in
@kubernetes-sig

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@chaosaffe
@iamemilio  

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/143
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/126
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/111

SIG projects I am involved with

- [ ]            cluster-api
- [ ]            cluster-api-provider-openstack

/area github-membership

**Comment by chaosaffe** [comment]
+1 from me

@syjabri thank you for your work on Cluster API and Cluster API Provider OpenStack!

**Comment by iamemilio** [comment]
+1 @syjabri

**Comment by mrbobbytables** [comment]
Hey there @syjabri, unfortunately @iamemilio cannot sponsor you for membership. A sponsor must be an approver or reviewer to be able to +1 a membership request ([sponsor requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements)). Is there someone else that could sponsor you?

**Comment by dims** [comment]
@mrbobbytables i am willing to sponsor @syjabri for membership. +1 from me

@syjabri please adjust list of sponsors.

**Comment by mrbobbytables** [comment]
Thanks for adding your +1 @dims :)

@syjabri I've gone ahead and created PR #326 to add you to @kubernetes-sigs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉 

/assign
