### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for @swatisehgal

### ISSUE THREAD

**Issue by swatisehgal** [kubernetes/org#3023]
### GitHub Username

swatisehgal

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@marquiz

### Sponsor 2

@Huang-Wei

### List of contributions to the Kubernetes project

Please refer to the approved Kubernetes membership request here: https://github.com/kubernetes/org/issues/2307

- Kubernetes PRs reviewed / authored
  * kubernetes/enhancements#1870
  * kubernetes/enhancements#1858
  * kubernetes/enhancements#1884
  * https://github.com/kubernetes/enhancements/pull/2626
  * https://github.com/kubernetes/enhancements/pull/2932
  * https://github.com/kubernetes/enhancements/pull/2933
  * kubernetes/kubernetes#90708
  * kubernetes/kubernetes#93243
  * https://github.com/kubernetes/kubernetes/pull/101432
  * https://github.com/kubernetes/enhancements/pull/2404
  * https://github.com/kubernetes/enhancements/pull/2811
  * https://github.com/kubernetes/enhancements/pull/2684
  * https://github.com/kubernetes/enhancements/pull/2904
  
- Kubernetes-sigs PRs reviewed / authored
* https://github.com/kubernetes-sigs/node-feature-discovery/pull/49
* https://github.com/kubernetes-sigs/node-feature-discovery/pull/525
* https://github.com/kubernetes-sigs/node-feature-discovery/pull/526
* https://github.com/kubernetes-sigs/node-feature-discovery/pull/587
* https://github.com/kubernetes-sigs/scheduler-plugins/pull/119
* https://github.com/kubernetes-sigs/scheduler-plugins/pull/143

- SIG projects I am involved with
  * sig-node
  * sig-scheduling
  * Node feature Discovery
  * Scheduler plugins

**Comment by marquiz** [comment]
+1

Happy to sponsor @swatisehgal on this!

**Comment by Huang-Wei** [comment]
+1

**Comment by dims** [comment]
+1 from me!

**Comment by nikhita** [comment]
@swatisehgal Thanks for all your contributors so far! \o/

I've created PR #3025 to add you to the @kubernetes-sigs organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
