### ISSUE TITLE
REQUEST: New membership for AvineshTripathi

### ISSUE THREAD

**Issue by AvineshTripathi** [kubernetes/org#3034]
### GitHub Username

@AvineshTripathi

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@parispittman

### Sponsor 2

@divya-mohan0209

### List of contributions to the Kubernetes project

**PRs authored:** 

- [kubernetes/community#6079](https://github.com/kubernetes/community/pull/6078)

- [kubernetes/website#29838](https://github.com/kubernetes/website/pull/29838)

**PRs reviewed:**

- [kubernetes/website#29966](https://github.com/kubernetes/website/pull/29966#pullrequestreview-774697078)

**Issues working on or responded to:**

-[kubernetes/website#29649](https://github.com/kubernetes/website/issues/29649)

-[kubernetes/community#6079](https://github.com/kubernetes/community/issues/5425)

**I am part of:**

- Mentee at Community Manager Group Mentoring Cohort - [kubernetes/community#5906](https://github.com/kubernetes/community/issues/5906)
- Co-ordinator for the "Meet Our Contributors" Blog series for the APAC region - [kubernetes/community#4469](https://github.com/kubernetes/community/issues/4469)

**Comment by parispittman** [comment]
+1 

tysm!
