### ISSUE TITLE
REQUEST: New membership for bang9211

### ISSUE THREAD

**Issue by bang9211** [kubernetes/org#3036]
### GitHub Username

@bang9211

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@seokho-son

### Sponsor 2

@gochist

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/search?q=org%3Akubernetes+is%3Apr+author%3Abang9211
- Issues responded to
https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Abang9211
- SIG projects I am involved with
kubernetes/sig-docs

**Comment by gochist** [comment]
+1
