### ISSUE TITLE
REQUEST: New membership for bgeesaman

### ISSUE THREAD

**Issue by bgeesaman** [kubernetes/org#3037]
### GitHub Username

@bgeesaman

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alisondy

### Sponsor 2

@iancoldwater

### List of contributions to the Kubernetes project

I've contributed to a few security-related CVEs (https://github.com/containerd/containerd/security/advisories/GHSA-742w-89gc-8m9c and https://github.com/kubernetes/kubernetes/issues/104980) , but a lot of my work has been more community focused. I have been honored to be able to speak and evangelize on Kubernetes security topics at multiple KubeCon/CloudNativeCons since 2017. I give advice on Kubernetes slack and Twitter, participate in sig-security when time allows, and love to publish write-ups and proofs of concept for Kubernetes CVEs.

**Comment by nikhita** [comment]
Going to close this due to lack of activity. @bgeesaman if you are still interested, please feel free to reopen after adding more details in the GitHub issue. Thank you!
