### ISSUE TITLE
REQUEST: New membership for @johnSchnake

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/org#3038]
### GitHub Username

@johnSchnake

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@vladimirvivien

### Sponsor 2

@andrewsykim

### List of contributions to the Kubernetes project

PRs currently up on e2e-framework:
    - https://github.com/kubernetes-sigs/e2e-framework/pull/65
    - https://github.com/kubernetes-sigs/e2e-framework/pull/64
    - https://github.com/kubernetes-sigs/e2e-framework/pull/63
I am already a member of k8s/k8s and can provide more issues/PRs/etc if necessary.

**Comment by palnabarun** [comment]
@johnSchnake -- since you are already a member of @kubernetes, you don't need to go through the new member sponsorship process again. I have approved the PR adding you to the @kubernetes-sigs org.
