### ISSUE TITLE
REQUEST: New membership for @kwiesmueller

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/org#304]
### GitHub Username
@kwiesmueller

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @apelisse 
- @lavalamp 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pull/71583
- https://github.com/kubernetes/kubernetes/pull/66814
- https://github.com/kubernetes-sigs/structured-merge-diff/pull/30
- https://github.com/kubernetes-sigs/structured-merge-diff/pull/12
- https://github.com/kubernetes-sigs/structured-merge-diff/pull/34
-https://github.com/kubernetes-sigs/structured-merge-diff
- sig-apimachinery
- wg-apply

/area github-membership

**Comment by justaugustus** [comment]
@apelisse / @lavalamp -- Bumping this for sponsorship +1s.

**Comment by mrbobbytables** [comment]
@apelisse @kwiesmueller Is there someone else that might be able to chime in and offer a +1 in @lavalamp's place?

**Comment by apelisse** [comment]
@jennybuckley

**Comment by idealhack** [comment]
@apelisse I'm afraid the other sponsor should be from another company according to the guidelines... but I think @kwiesmueller should be able to find another one if there're any discussions with current members, also, feel free to list your other kinds of contribution other than issues/PRs.

**Comment by mrbobbytables** [comment]
Thanks for catching that @idealhack. For more information on the sponsor requirements, please see the [Membership requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) in the k/community repo.

**Comment by deads2k** [comment]
I'm the other sig-apimachinery lead.  +1 from me.

**Comment by mrbobbytables** [comment]
@kwiesmueller I've gone ahead and created PR #333 that will add you to the @kubernetes org :) Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
