### ISSUE TITLE
Migrate existing repo to k/release

### ISSUE THREAD

**Issue by alenkacz** [kubernetes/org#3044]
### New Repo, Staging Repo, or migrate existing

migrate to  k/release

### Requested name for new repository
ci-signal-report

### Which Organization should it reside
kubernetes

### If not a staging repo, who should have admin access
same as currently given in k/release

### If not a staging repo, who should have write access
same as currently given in k/release

### If not a staging repo, who should be listed as approvers in OWNERS
same as currently given in k/release

### If not a staging repo, who should be listed in SECURITY_CONTACTS
same as currently given in k/release

### What should the repo description be
Reporting tool to crawl weekly flakeing/failing test at the CI signal dashboard

### What SIG and subproject does this fall under in sigs.yaml
sig-release

### Approvals
Following discussion: https://kubernetes.slack.com/archives/C2C40FMNF/p1622718810193000 and basically approval by the sig-release leads

### Additional context for request
The tool is used by the CI Signal team to create weekly reports and display current changes on the open issues for failing or flaky tests. This request follows the discussion from Slack: https://kubernetes.slack.com/archives/C2C40FMNF/p1622718810193000

**Comment by leonardpahlke** [comment]
Thank you Alena :))

**Comment by encodeflush** [comment]
Thank you!

**Comment by mrbobbytables** [comment]
If the code is being migrated into a directory of another repo there isn't really an action for the github admins to take, the big thing is the code must still follow our [donation guidelines](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories) - have the apache header etc 👍
