### ISSUE TITLE
REQUEST: New membership for @jmwurst

### ISSUE THREAD

**Issue by jmwurst** [kubernetes/org#3045]
### GitHub Username

@jmwurst

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@wongma7

### Sponsor 2

@ayberk

### List of contributions to the Kubernetes project

kubernetes-sigs/aws-fsx-csi-driver
- Storage scaling via ControllerExpandVolume: [https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/209](https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/209)
- Adding FSx API features (WeeklyMaintenanceStartTime, FileSystemTypeVersion) as storage class parameters: [https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/210/files](https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/210/files)
- Directing release of v0.6.0 in conjunction with @wongma7: [https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/211](https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/211)

**Comment by wongma7** [comment]
+1
