### ISSUE TITLE
REQUEST: New membership for jonyhy96

### ISSUE THREAD

**Issue by jonyhy96** [kubernetes/org#3046]
### GitHub Username

jonyhy96

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu

### Sponsor 2

@wojtek-t

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/105375
https://github.com/kubernetes/kubernetes/pull/105344
https://github.com/kubernetes/kubernetes/pull/105343
https://github.com/kubernetes/kubernetes/pull/105342
https://github.com/containerd/containerd/pull/6100
https://github.com/containerd/containerd/pull/6076
https://github.com/containerd/containerd/pull/6070
https://github.com/containerd/containerd/pull/6069
https://github.com/containerd/containerd/pull/6059
https://github.com/kubernetes/kubernetes/pull/105599
https://github.com/kubernetes/kubernetes/pull/105586
https://github.com/kubernetes/gengo/pull/216
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/105439
https://github.com/kubernetes/kubernetes/issues/105589
- SIG projects I am involved with
SIG-Storage
SIG-Scheduling

**Comment by pacoxu** [comment]
Thanks for your contributions to kubeadm and sig-node.
Absolutely +1 and look forward to your contributions in the future.
