### ISSUE TITLE
REQUEST: New membership for jaypipes

### ISSUE THREAD

**Issue by jaypipes** [kubernetes/org#3049]
### GitHub Username

@jaypipes

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@nckturner

### Sponsor 2

@M00nF1sh

### List of contributions to the Kubernetes project

I've been most engaged in AWS-related Kubernetes projects for the past 18 months (github.com/aws-controllers-k8s, github.com/aws/amazon-vpc-cni-k8s, github.com/aws/eks-charts) but still contribute in the kubernetes/community, kubernetes/autoscaler, kubernetes-sigs/aws-iam-authenticator repositories.

I am already a member in the kubernetes GH org.

**Comment by mrbobbytables** [comment]
you don't have to request membership in another org, you can PR yourself in there :) Just make sure to follow the standard formatting of the commit messages 👍

**Comment by jaypipes** [comment]
> you don't have to request membership in another org, you can PR yourself in there :) Just make sure to follow the standard formatting of the commit messages +1

Ah, thank you Bob! Sorry, I was confused by the [docs][https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem]. I will open a PR then :) thanks!
