### ISSUE TITLE
REQUEST: New membership for wentao-zh

### ISSUE THREAD

**Issue by wentao-zh** [kubernetes/org#3051]
### GitHub Username

wentao-zh

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@gyliu513

### Sponsor 2

@k82cn

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/330
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/334
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/298
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/326

**Comment by k82cn** [comment]
+1, thanks for your contribution :)
