### ISSUE TITLE
REQUEST: New membership for pravarag

### ISSUE THREAD

**Issue by pravarag** [kubernetes/org#3058]
### GitHub Username

@pravarag

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei 

### Sponsor 2

@spiffxp

### List of contributions to the Kubernetes project

- PRs reviewed/authored
https://github.com/kubernetes-sigs/descheduler/pull/507
https://github.com/kubernetes/kubernetes/pull/100020
https://github.com/kubernetes-sigs/descheduler/pull/527
https://github.com/kubernetes/test-infra/pull/22391
https://github.com/kubernetes/community/pull/5848
https://github.com/kubernetes/community/pull/5829
https://github.com/kubernetes/community/pull/5864
https://github.com/kubernetes-sigs/kubebuilder/pull/2277
https://github.com/kubernetes-sigs/scheduler-plugins/pull/222
https://github.com/kubernetes-sigs/scheduler-plugins/pull/268

- Issues responded to
- SIG projects I am involved with

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by palnabarun** [comment]
@pravarag -- Thank you for all your contributions so far! :)

I've created PR #3077 to add you to the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the community! :tada:

/assign
