### ISSUE TITLE
REQUEST: New membership for jyz0309

### ISSUE THREAD

**Issue by jyz0309** [kubernetes/org#3063]
### GitHub Username

@jyz0309

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mengjiao-liu 

### Sponsor 2

@serathius 

### List of contributions to the Kubernetes project

PRs reviewed/authored
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+jyz0309
Issue responded to and involved with:
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+is%3Aopen+jyz0309

SIG projects I am involved with:
sig/instrumentation and wg/structured-logging

**Comment by mengjiao-liu** [comment]
I see you've done a lot of work on Structured Logging migration.  Well done!
LGTM

**Comment by palnabarun** [comment]
@jyz0309 -- Thank you for all your contributions so far! :)

I've created PR #3077 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to the community! :tada:

/assign
