### ISSUE TITLE
EasyCLA Feedback & Issues

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/org#3068]
This issue will be used to collect feedback and issues encountered by the Community during the EasyCLA rollout. 

Please post issues encountered here with as much supporting information as possible (screenshots etc).

---
/area github-integration

**Comment by uablrek** [comment]
I have a signed CLA since 2018 (I think), now I get;
![easycla](https://user-images.githubusercontent.com/37046727/141611335-0d731b10-6371-4141-8063-716286dcc843.png)

**Comment by reylejano** [comment]
This came up on the k/website [Official 1.23 Release Docs PR](https://github.com/kubernetes/website/pull/29658) we use to merge PRs from the k/website `dev-1.23` branch into k/website `main`
![Screen Shot 2021-11-13 at 9 07 28 AM](https://user-images.githubusercontent.com/52760880/141652701-85bb662e-ea25-4437-bbd7-ed9b99b224b9.png)

**Comment by Huang-Wei** [comment]
I've singed CLA since mid-2018, but got this error on EasyCLA today:

https://github.com/kubernetes-sigs/scheduler-plugins/pull/290#issuecomment-968187890

**Comment by olemarkus** [comment]
I am covered by a corporate CLA, but I am getting this error https://github.com/kubernetes/kops/pull/12743#issuecomment-968658182

**Comment by wangchen615** [comment]
I am also covered by a corporate CLA, but I am getting this error for [kubernetes/test-infra#23177](https://github.com/kubernetes/test-infra/pull/23177)
![Screen Shot 2021-11-15 at 2 49 28 PM](https://user-images.githubusercontent.com/39573014/141844867-e7420ba3-3c8d-4e8e-8a6c-c08415e434d0.png)

**Comment by dims** [comment]
one more https://github.com/kubernetes/kubernetes/pull/106436

**Comment by bradtopol** [comment]
@mrbobbytables It appears there was no automatic migration of existing folks who had approval.  I am having to manually add each person to the new easyCLA access list.   **For all IBM employees that are running into this issue please contact me on our internal slack and I will add you to the easyCLA.**   
@mrbobbytables if there is an easier way for me to handle this please let me know.  Thanks!

**Comment by mrbobbytables** [comment]
@bradtopol For now, don't worry about adding them 1-by-1, its non-blocking and they can ignore it til the issues are sorted out.

**Comment by dims** [comment]
@pranab-bajpai is there working going on to fix this? I'd like to follow along, looks like slack channel is totally silent and no updates from the easycla team on this issue either. Could we please work in the open?

cc @caniszczyk

**Comment by bradtopol** [comment]
> @bradtopol For now, don't worry about adding them 1-by-1, its non-blocking and they can ignore it til the issues are sorted out.

Really? Folks keep telling me its blocking their PRs.

**Comment by mrbobbytables** [comment]
@bradtopol yup. It's been rolled out in non-blocking mode. The old CLA is still the source of truth. If they have the label `cncf-cla: yes` it'll merge.

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/30504#issuecomment-970187930 suggests a mismatch between the new and old bots.

**Comment by aravindhp** [comment]
I am also running into this: https://github.com/kubernetes/kubernetes/pull/96120#issuecomment-970524140

**Comment by dumb0002** [comment]
@MikeSpreitzer: yes, as long as we have the cncf-cla: yes label we are good to go.  But still I am reporting it here as suggested by @bradtopol

**Comment by mrbobbytables** [comment]
Yes, any instance where we a discrepancy between the two CLA systems should be logged. 👍

**Comment by sftim** [comment]
https://github.com/kubernetes/org/pull/3101#issuecomment-970724326 gets it wrong, I do have a corporate CLA sign off.

**Comment by mrbobbytables** [comment]
@sftim the new cla is a github app and will require authorization. However it should have synced for you. Don't worry about signing it till that issue is sorted out.

**Comment by jimangel** [comment]
Feedback on behavior:

I opened a PR in k/website against the `dev-1.23` branch. I later changed it to `main` in the GH GUI and it pulled in a bunch of unwanted commits (as expected). In the GUI, I swapped the PR back to `dev-1.23` and rebased my local branch (CLI) against main and force pushed it to allow me to move branches in the GH GUI without baggage. EasyCLA proceeded to flag the delta # of users with a giant comment "blocking" (I know it's not) before I could update the GH GUI base branch.

https://github.com/kubernetes/website/pull/30502#issuecomment-970824237

I think this could have all been avoided if I swapped the base branch in the GH GUI first, THEN force pushed the commits (re-triggering an EasyCLA check). I'm assuming (hoping? guessing?) my next force push will resolve it.

**Comment by sftim** [comment]
> I think this could have all been avoided if I swapped the base branch in the GH GUI first, THEN force pushed the commits (re-triggering an EasyCLA check). I'm assuming (hoping? guessing?) my next force push will resolve it.

@jimangel either order would have triggered similar behavior here I'm afraid. Changing the base branch first would have triggered CLA checks for all commits not shared between the two merge bases.

**Comment by sftim** [comment]
What I'd like GitHub to let you do: change the merge base during a forced push using a Git [push option](https://zerokspot.com/weblog/2020/09/28/git-push-options/) (GitLab has features for this, I don't think GitHub does). IMO that's more an issue with atomically changing the merge base during a forced push and less about EasyCLA.

**Comment by jimangel** [comment]
> @jimangel either order would have triggered similar behavior here I'm afraid.

I could have been lucky with timing, but I did update the base branch (saw all the commits appear in the GH GUI) and reverted back, which didn't trigger EasyCLA.

First time:

![image](https://user-images.githubusercontent.com/4601051/142220710-fbdbdf82-79a3-4207-be49-669a69ce225a.png)

Second time:

![image](https://user-images.githubusercontent.com/4601051/142220760-cd5a389d-f793-49d0-b858-42bb1ba55845.png)

The difference being a force push before that included commits not in `dev-1.23` because my origin branch was rebased against `main` before I could toggle the PR target branch in the GUI.

I don't know for sure, but I'm guessing EasyCLA triggers on commit vs. interactions with a PR in the GUI?

**Comment by reylejano** [comment]
We had more that came up in a [PR](https://github.com/kubernetes/website/pull/30536) to sync the `dev-1.23` branch with updates from `main` in k/website
![Screen Shot 2021-11-17 at 11 39 16 AM](https://user-images.githubusercontent.com/52760880/142271494-4ed97bf6-1e89-49a0-b08d-6a1c4a658096.png)
![Screen Shot 2021-11-17 at 11 39 26 AM](https://user-images.githubusercontent.com/52760880/142271522-84618800-5375-480f-af84-dd7560564de9.png)

**Comment by sftim** [comment]
Old CLA bot says no, EasyCLA says yes
https://github.com/kubernetes/website/pull/30543

That might be expected (but confusing) behavior?

**Comment by mrbobbytables** [comment]
@sftim they look to be a new contributor and probably signed EasyCLA instead of signing the old CLA.

**Comment by mikebrow** [comment]
Went through the very manual process steps of having my tech lead @bradtopol add me so I wouldn't have to see the red X for easycla auth over here... https://github.com/kubernetes/kubernetes/pull/94899 fully expected this to be automatic with db sync.  Not sure if this helps but my LF profile was private.. I made it public this morning. Perhaps that may have affected db sync?

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/30019 shows that the bot thinks I haven't signed it; I have - similar to https://github.com/kubernetes/org/issues/3068#issuecomment-970724763.

**Comment by RA489** [comment]
Easy CLA is not getting ignored https://github.com/kubernetes/kubeadm/pull/2611

**Comment by stormqueen1990** [comment]
Hello! I am also seeing this issue in this PR: https://github.com/kubernetes/website/pull/30583

The checks say I am authorized under the Linux Foundation CLA, but EasyCLA says I'm not covered.

**Comment by ehashman** [comment]
EasyCLA Failure here for a cherry-pick from Clayton: https://github.com/kubernetes/kubernetes/pull/104918#issuecomment-978489312

**Comment by ykakarap** [comment]
I have previously signed the old CLA and have been contributing for the ClusterAPI project for a while but now I am getting the following error.

<img width="1004" alt="Screen Shot 2021-11-24 at 9 25 05 PM" src="https://user-images.githubusercontent.com/22120431/143384505-e774fe3c-f794-4670-ac31-67ad5a6bd5b8.png">

**Comment by ansilh** [comment]
```
Welcome! You have been automatically assigned membership in CNCF - SUSE and are authorized to contribute code to this project.
```
Bu still the EasyCLA is not passed in PR https://github.com/kubernetes/ingress-nginx/pull/7977
![image](https://user-images.githubusercontent.com/11064902/143495308-6afa7103-841a-4e0d-8afd-05c625e0c392.png)

**Comment by Shubham82** [comment]
Hi folks,
I am also facing an EasyCLA  check failure in this PR https://github.com/kubernetes/website/pull/30430
even `/easycla ` comment is also not working in my case. please suggest any workaround for it.
![Screenshot](https://user-images.githubusercontent.com/50987400/143821363-3b5d4ed3-4cc2-4fae-a9c0-407ede13259a.png)

**Comment by adisky** [comment]
I have previously signed CLA but Easy CLA is failing for me, I have also tried to sign it but it is redirecting to mail id that no longer exist in my github account
![image](https://user-images.githubusercontent.com/7712693/144002566-cc0f3db4-4cc4-4a6a-ab81-fda68de17691.png)
![image](https://user-images.githubusercontent.com/7712693/144002632-e14503b2-b265-4f2a-b8a5-1f4f74b1bb8a.png)

**Comment by killianmuldoon** [comment]
I signed the old CLA in 2019, and signed again when EasyCLA came out. EasyCLA is now failing again (between commits) on this PR: https://github.com/kubernetes-sigs/cluster-api/pull/5735

**Comment by waltforme** [comment]
Same issue with EasyLCA:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/8633434/144090760-074b17b8-c891-4798-98c9-35ed329e9051.png">

**Comment by sftim** [comment]
EasyCLA didn't like my squash-and-forced-push: https://github.com/kubernetes/website/pull/29685#issuecomment-984126979

**Comment by uablrek** [comment]
Is there a simple way of checking my own CLA status (both)? A button or form perhaps?
I mean not by creating a fake PR.

**Comment by Prajyot-Parab** [comment]
I am covered by a corporate CLA, but I am getting this error for [kubernetes-sigs/cluster-api/pull/5806](https://github.com/kubernetes-sigs/cluster-api/pull/5806#issuecomment-987669173)
<img width="905" alt="Screenshot 2021-12-08 at 7 41 03 PM" src="https://user-images.githubusercontent.com/42934355/145222906-fd57c536-61ae-4e51-8f90-69f12783b945.png">

**Comment by pranab-bajpai** [comment]
Hi All, 
Wanted to thank you for posting issues as we work through the issues with EasyCLA. 
We are going to do weekly DB migration from current Kubernetes CLA to latest EasyCLA DB. Recent migration was completed on 12/7, another one will be completed by 12/9. We are hoping that most of the user mismatch issues should stabilize with latest migration on 12/9. We plan on keeping an eye on the issues reported on this thread and will work with you all to deploy EasyCLA only when Kubernetes community is comfortable. 

Thanks,
-Pranab
(Product Manager EasyCLA)

**Comment by pranab-bajpai** [comment]
> Is there a simple way of checking my own CLA status (both)? A button or form perhaps? I mean not by creating a fake PR.

Only Project Managers can see if a user has signed CLA or not in the Project Control Center admin view of EasyCLA V2. There is no way for an individual to check without creating a PR.

**Comment by uablrek** [comment]
Still problems: https://github.com/kubernetes/kubernetes/pull/97081#issuecomment-992443042

**Comment by uablrek** [comment]
It works! https://github.com/kubernetes/kubernetes/pull/107027#issuecomment-993659944

I permit access and requested acceptance for company CLA for "Nordix". I don't know if anybody did something or if the request/permit was enough. Anyway, I am good. Thanks :+1:

**Comment by aznashwan** [comment]
Hello Everyone,

I have [this PR](https://github.com/kubernetes-sigs/cri-tools/pull/855) on `kubernetes-sigs/cri-tools` where I believe the CLA (re)checking does not work properly.

I had indeed initially submitted the PR without the CLA, but I'm 99% sure me/my management have followed the correct steps for my PR to be accepted afterwards (we contribute to CNCF projects regularly so we're used to the process but I cannot completely rule out a mistake on our end)

Are there any recommended debugging steps which come to mind which might help identify/fix the issue?

**Comment by Shubham82** [comment]
Hi folks!
I am still getting EasyCLA check failure in my every PR. The latest one is [kubernetes/kubernetes#107744 (comment)](https://github.com/kubernetes/kubernetes/pull/107744#issuecomment-1020958251)

Please take a look!

**Comment by mrbobbytables** [comment]
We will close the feedback thread on March 5th, that will have been 1 month post-cut over. 👍

**Comment by RA489** [comment]
> We will close the feedback thread on March 5th, that will have been 1 month post-cut over. 👍

+1. Thanks for driving this effort.

**Comment by MikeSpreitzer** [comment]
Is there a TL;DR here?  What does someone who is getting false CLA failures do?

**Comment by mrbobbytables** [comment]
@MikeSpreitzer we as a project cannot do much, its pretty much follow the link the EasyCLA bot response to log a ticket with the LF. =/

**Comment by mrbobbytables** [comment]
Going to go ahead and close this out. Future issues can be created ad-hoc.

/close
