### ISSUE TITLE
REQUEST: New membership for @ShivamTyagi12345

### ISSUE THREAD

**Issue by ShivamTyagi12345** [kubernetes/org#3072]
### GitHub Username

@ShivamTyagi12345

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@divya-mohan0209

### Sponsor 2

@PushkarJ

### Issues that I have helped and resolved

- https://github.com/kubernetes/website/pull/29971
- https://github.com/kubernetes/website/pull/29471
- https://github.com/kubernetes/website/pull/30303
- https://github.com/kubernetes/website/pull/29970
- https://github.com/kubernetes/website/pull/30304
- https://github.com/kubernetes/website/pull/29967
- https://github.com/kubernetes/sig-security/issues/11

### Issue I am  working on

- https://github.com/kubernetes/dashboard/issues/882#event-5543947975

### Community roles

- https://github.com/kubernetes/community/issues/4469#issuecomment-942422348

**Comment by divya-mohan0209** [comment]
Huge +1 for me! Thank you for all the awesome work you've been doing so far ✨

**Comment by PushkarJ** [comment]
@ShivamTyagi12345 +1 from me as well!! Thank you for your work Shivam, and looking forward to seeing even more of you in the community!

**Comment by palnabarun** [comment]
@ShivamTyagi12345 -- Thank you for all your contributions so far! :)

I've created PR #3077 to add you to the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the community! :tada:

/assign

**Comment by ShivamTyagi12345** [comment]
> @ShivamTyagi12345 -- Thank you for all your contributions so far! :)
> 
> I've created PR #3077 to add you to the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to the community! 🎉
> 
> /assign

Thank you  @palnabarun @PushkarJ @divya-mohan0209 ❤️
