### ISSUE TITLE
REQUEST: New membership for @jayesh-srivastava

### ISSUE THREAD

**Issue by jayesh-srivastava** [kubernetes/org#3073]
### GitHub Username

@jayesh-srivastava

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@cpanato

### List of contributions to the Kubernetes project

- PRs reviewed / authored
[Remove kube-rbac-proxy](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/452)
[Update dependencies for v0.4.4](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/447)
[Added comments to WatchFilterValue in all the Reconcilers types](https://github.com/kubernetes-sigs/cluster-api/pull/5403)

- Issues created / responded to
[Multiple links in README.md are broken](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/424)
[Add Compare to util/version with support for CompareOptions](https://github.com/kubernetes-sigs/cluster-api/issues/5224)

- SIG projects I'm involved with
[cluster-api-provider-gcp](https://github.com/kubernetes-sigs/cluster-api-provider-gcp)
[cluster-api](https://github.com/kubernetes-sigs/cluster-api)

**Comment by dims** [comment]
+1 from me!

**Comment by palnabarun** [comment]
@jayesh-srivastava -- thank you for all your contributions so far :)

I've created PR #3083 to add you to the @kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to the community! :tada:

/assign
