### ISSUE TITLE
REQUEST: New membership for astraw99

### ISSUE THREAD

**Issue by astraw99** [kubernetes/org#3074]
### GitHub Username

astraw99

### Organization you are requesting membership in

kubernetes, kubernetes-csi

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@liggitt

### Sponsor 2

@xing-yang

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Aastraw99
https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Aastraw99
https://github.com/kubernetes/community/pulls?q=is%3Apr+author%3Aastraw99
https://github.com/kubernetes-csi/external-snapshotter/pulls?q=is%3Apr+author%3Aastraw99

- Issues created / responded
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3Aastraw99
https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Aastraw99
https://github.com/kubernetes/community/issues?q=is%3Aissue+author%3Aastraw99
https://github.com/kubernetes-csi/external-snapshotter/issues?q=is%3Aissue+author%3Aastraw99

- SIGs involved with
api-machinery
storage
cli
docs

**Comment by xing-yang** [comment]
+1

**Comment by liggitt** [comment]
+1

**Comment by palnabarun** [comment]
@astraw99 -- Thank you for all your contributions so far! :)

I've created PR #3077 to add you to the @kubernetes and @kubernetes-csi orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the community! :tada:

/assign
