### ISSUE TITLE
REQUEST: New membership for tobiasgiese

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes/org#3078]
### GitHub Username

@tobiasgiese

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@spiffxp

### List of contributions to the Kubernetes project

- Issues
  - https://github.com/kubernetes/k8s.io/issues/2492
  - https://github.com/kubernetes/org/issues/2883
  - https://github.com/kubernetes/ingress-nginx/issues/7445
  - https://github.com/kubernetes/utils/issues/214
  - https://github.com/kubernetes/test-infra/pull/24145
- PRs
  - https://github.com/kubernetes/ingress-nginx/pull/7449
  - https://github.com/kubernetes/utils/pull/215

xref `kubernetes-sigs` membership: https://github.com/kubernetes/org/issues/2835

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by sbueringer** [comment]
+1

**Comment by palnabarun** [comment]
@tobiasgiese -- thank you for all your contributions so far :)

I've created PR #3083 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to the community! :tada:

/assign
