### ISSUE TITLE
Please create repo kubernetes-sigs/etcdadm

### ISSUE THREAD

**Issue by justinsb** [kubernetes/org#308]
### New Repo, Staging Repo, or migrate existing
New Repo

### Requested name for new repository
etcdadm

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
justinsb, dlipovetsky & sig-cluster-lifecycle chairs (roberthbailey, luxas, timothysc)

### If not a staging repo, who should have write access
justinsb, dlipovetsky

### If a new repo, who should be listed as approvers in OWNERS
justinsb, dlipovetsky

### If a new repo, who should be listed in SECURITY_CONTACTS
justinsb, dlipovetsky

### What should the repo description be
tooling & automation for kubernetes etcd clusters

### What SIG and subproject does this fall under in sigs.yaml
etcdadm is a new subproject of sig-cluster-lifecycle

### Approvals
https://github.com/kubernetes/community/pull/2835

### Additional context for request
n/a

/area github-repo

**Comment by cblecker** [comment]
I can’t tell clearly from the KEP.. are we forking an existing project?

**Comment by jberkus** [comment]
@cblecker yes.  I believe this is the current canonical source: https://github.com/platform9/etcdadm

**Comment by cblecker** [comment]
@justinsb can you confirm? rules for importing/donating code is different than a new repo with newly created code.

**Comment by dlipovetsky** [comment]
@cblecker Platform9 would like to donate the code. We can transfer the repo the kubernetes-sigs org, or duplicate the repo (and outstanding issues).

**Comment by cblecker** [comment]
Can you please review the rules for donated repositories, and speak to each of the requirements?: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-new-repositories

also, please add me as an admin to the current repo

**Comment by dlipovetsky** [comment]
@cblecker Absolutely.
- I confirmed that all [contributors](https://github.com/platform9/etcdadm/graphs/contributors) have signed the CNCF CLA.
- Boilerplate text has been [updated](https://github.com/platform9/etcdadm/pull/83) to attribute copyright to "The etcdadm authors"
- Dependencies have MIT, AL2.0, or BSD licenses [0], which I understand are all acceptable.

Although it does not appear in the rules, I realize that--where possible--the use of the same dependencies as k/k is important, too; @justinsb_ was kind enough to submit one patch getting etcdadm closer to this goal. 

[0]
```
$ licenses github.com/platform9/etcdadm
github.com/platform9/etcdadm                                                                 Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/beorn7/perks/quantile                         MIT License (98%)
github.com/platform9/etcdadm/vendor/github.com/coreos/bbolt                                  MIT License
github.com/platform9/etcdadm/vendor/github.com/coreos/etcd                                   Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/coreos/go-semver/semver                       Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/coreos/go-systemd/journal                     Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/coreos/pkg/capnslog                           Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/dgrijalva/jwt-go                              MIT License (98%)
github.com/platform9/etcdadm/vendor/github.com/ghodss/yaml                                   ? (BSD 3-clause "New" or "Revised" License, 83%)
github.com/platform9/etcdadm/vendor/github.com/gogo/protobuf                                 BSD 3-clause "New" or "Revised" License (90%)
github.com/platform9/etcdadm/vendor/github.com/golang/glog                                   Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/golang/protobuf                               BSD 3-clause "New" or "Revised" License (92%)
github.com/platform9/etcdadm/vendor/github.com/google/btree                                  Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/jonboulle/clockwork                           Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/matttproud/golang_protobuf_extensions/pbutil  Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/prometheus/client_golang/prometheus           Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/prometheus/client_model/go                    Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/prometheus/common                             Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/prometheus/procfs                             Apache License 2.0
github.com/platform9/etcdadm/vendor/github.com/satori/go.uuid                                MIT License (98%)
github.com/platform9/etcdadm/vendor/github.com/sirupsen/logrus                               MIT License
github.com/platform9/etcdadm/vendor/github.com/spf13/cobra                                   Apache License 2.0 (95%)
github.com/platform9/etcdadm/vendor/github.com/spf13/pflag                                   BSD 3-clause "New" or "Revised" License (96%)
github.com/platform9/etcdadm/vendor/github.com/ugorji/go/codec                               MIT License
github.com/platform9/etcdadm/vendor/github.com/xiang90/probing                               MIT License
github.com/platform9/etcdadm/vendor/go.uber.org/atomic                                       MIT License (98%)
github.com/platform9/etcdadm/vendor/go.uber.org/multierr                                     MIT License (98%)
github.com/platform9/etcdadm/vendor/go.uber.org/zap                                          MIT License (98%)
github.com/platform9/etcdadm/vendor/golang.org/x/crypto                                      BSD 3-clause "New" or "Revised" License (96%)
github.com/platform9/etcdadm/vendor/golang.org/x/net                                         BSD 3-clause "New" or "Revised" License (96%)
github.com/platform9/etcdadm/vendor/golang.org/x/sys/unix                                    BSD 3-clause "New" or "Revised" License (96%)
github.com/platform9/etcdadm/vendor/golang.org/x/text                                        BSD 3-clause "New" or "Revised" License (96%)
github.com/platform9/etcdadm/vendor/golang.org/x/time/rate                                   BSD 3-clause "New" or "Revised" License (96%)
github.com/platform9/etcdadm/vendor/google.golang.org/genproto/googleapis/rpc/status         Apache License 2.0
github.com/platform9/etcdadm/vendor/google.golang.org/grpc                                   Apache License 2.0
github.com/platform9/etcdadm/vendor/gopkg.in/yaml.v2                                         Apache License 2.0
github.com/platform9/etcdadm/vendor/k8s.io/apimachinery/pkg                                  Apache License 2.0
github.com/platform9/etcdadm/vendor/k8s.io/client-go/util/cert                               Apache License 2.0
github.com/platform9/etcdadm/vendor/k8s.io/kubernetes/pkg/version                            Apache License 2.0
```

**Comment by cblecker** [comment]
I'm ready to go on this.. The one issue is that @dlipovetsky is not a member of the kubernetes or kubernetes-sigs orgs, so I will not be able to provide repo access after the transfer. Would you like to get this corrected first?

**Comment by dlipovetsky** [comment]
@cblecker Thank you for the heads up. I'm submitting an issue to request membership to both, and I'll post an update here.

**Comment by dlipovetsky** [comment]
@cblecker I'm now a member of the @kubernetes and @kubernetes-sigs orgs. One question: Do I need to create an `OWNERS` file before the transfer? If not, please go ahead with the transfer. Thanks again!

**Comment by dlipovetsky** [comment]
@cblecker Anything else we need to take care of?

**Comment by cblecker** [comment]
@dlipovetsky Sorry for the delay in this. I've completed the transfer. You don't need an `OWNERS` right away, but you should merge one soon so that you can use the bot automation and approvers to merge things instead of manual access.

I've opened https://github.com/kubernetes/org/pull/569 to add you to the right teams to get that access.. as soon as that gets merged, you should be good to go.

Can you update [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) with the new repo? (cc: @justinsb )

**Comment by dlipovetsky** [comment]
@cblecker No problem. Thanks for your help!

I'll try updating sigs.yaml

**Comment by nikhita** [comment]
@dlipovetsky bumping this, can you create a PR to update sigs.yaml with this new repo? We can close this issue once it gets merged. :)

**Comment by dlipovetsky** [comment]
@nikhita Thanks for the gentle reminder. PR opened!

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/3439 merged :tada: 

Closing.
/close
