### ISSUE TITLE
REQUEST: New membership for johananl

### ISSUE THREAD

**Issue by johananl** [kubernetes/org#3082]
### GitHub Username

@johananl

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@puja108

### Sponsor 2

@sbueringer

### List of contributions to the Kubernetes project

- Actively involved in Cluster API. Currently working on adding support for Ignition-based Linux distros.
- Authored https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2662 and https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2642.
- Co-authored https://github.com/kubernetes-sigs/cluster-api/pull/4172 (not merged yet).

**Comment by sbueringer** [comment]
+1 Thx for your hard work on the ignition PR! :)

**Comment by MarcelMue** [comment]
+1 Great ongoing contributions!

**Comment by palnabarun** [comment]
Hi @johananl 👋🏽, thank you for applying to be a Kubernetes org member.

One of the requirements for a contributor to be a sponsor is that they have to be at least a Reviewer. Unfortunately, @MarcelMue doesn't satisfy the criteria at this point in time.

Can you please find another sponsor satisfying the criteria?

**Comment by puja108** [comment]
I can sponsor @johananl dito to what @sbueringer mentioned above!

**Comment by CecileRobertMichon** [comment]
+1 from me as well

**Comment by palnabarun** [comment]
All requirements are met now. 🎉 

@johananl, thank you for all your contributions so far :)

I've created PR #3093 to add you to the @kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign

**Comment by johananl** [comment]
Thanks for the trust @palnabarun! Happy to join and will do my best to be useful in this great community :slightly_smiling_face:
