### ISSUE TITLE
REQUEST: enable codecov.io in kubernetes-sigs

### ISSUE THREAD

**Issue by marquiz** [kubernetes/org#3084]
### Organization or Repo

kubernetes-sigs

### Name of integration

codecov.io

### Link to integration website

https://app.codecov.io/gh

### Describe what is attempting to be accomplished

As a project maintainer, I'd like to be able to integrate codecov reports to [Node Featgure Discovery](https://github.com/kubernetes-sigs/node-feature-discovery)

**Comment by zvonkok** [comment]
I second that, also would like to have it enabled on the new repo https://github.com/kubernetes/org/issues/3140

**Comment by marquiz** [comment]
ping @ameukam @cblecker @idvoretskyi @mrbobbytables @nikhita @palnabarun who could comment on this?

**Comment by qbarrand** [comment]
+1 for this.

**Comment by cblecker** [comment]
@marquiz I assume you're still looking for this? Sorry for the delay on response.

**Comment by marquiz** [comment]
> I assume you're still looking for this? Sorry for the delay on response.

Yeah, sure this is still valid 😊

**Comment by cblecker** [comment]
The GitHub authorization parts are set up. You can complete the setup at https://app.codecov.io/gh/kubernetes-sigs/node-feature-discovery/new
