### ISSUE TITLE
REQUEST: New membership for steven-my

### ISSUE THREAD

**Issue by steven-my** [kubernetes/org#3085]
### GitHub Username

@steven-my

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@chenxuc

### Sponsor 2

@tengqm

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/website/pull/29161
https://github.com/kubernetes/website/pull/29451
https://github.com/kubernetes/website/pull/29509
https://github.com/kubernetes/website/pull/29772
https://github.com/kubernetes/website/pull/29797
https://github.com/kubernetes/website/pull/29814
https://github.com/kubernetes/website/pull/29815

**Comment by chenxuc** [comment]
+1, thanks @steven-my for your contribution to Kubernetes docs!

**Comment by tengqm** [comment]
+1

**Comment by NikhilSharmaWe** [comment]
@chenxuc and @tengqm I also want to become member of kubernetes org, but I do not have sponsors that meet the sponsor requirements listed in the community membership guidelines. Could you help in the process to join the organization.

**Comment by palnabarun** [comment]
Hi @steven-my 👋🏽, thank you for your contributions to the localization of documentation.

The organization membership request requires sponsors to be from two different employers. Can you please add a non-IBM Kubernetes contributor as one of your sponsors?

**Comment by chenxuc** [comment]
@palnabarun Actually tengqm (https://github.com/tengqm) is working for Sangfor company now instead of IBM. The sponsor requirement is met.

**Comment by tengqm** [comment]
Yes, @palnabarun, I'm no longer an IBMer. I wasn't able to modify my organization because 1) removing organization from my profile is not straightforward; 2) I'm working with Github on claiming a new organization.

**Comment by palnabarun** [comment]
Thanks for the clarification @chenxuc @tengqm. 👍🏽 

I will process this request in the next batch. 🎉

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3110  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
