### ISSUE TITLE
REQUEST: New membership for <NikhilSharmaWe>

### ISSUE THREAD

**Issue by NikhilSharmaWe** [kubernetes/org#3088]
### GitHub Username

NikhilSharmaWe

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@oomichi

### Sponsor 2

@SergeyKanzhelev

### List of contributions to the Kubernetes project

- PRs authored 
https://github.com/kubernetes/kubernetes/pull/105854
https://github.com/kubernetes/test-infra/pull/24201
https://github.com/kubernetes-sigs/windows-testing/pull/286
https://github.com/kubernetes/kubernetes/pull/106339
https://github.com/kubernetes/kubernetes/pull/105774
https://github.com/kubernetes/kubernetes/pull/106001
https://github.com/kubernetes/kubernetes/pull/106038
https://github.com/kubernetes/kubernetes/pull/105939
https://github.com/kubernetes/kubernetes/pull/106226
https://github.com/kubernetes/kubernetes/pull/106220
https://github.com/kubernetes/kubernetes/pull/106233
https://github.com/kubernetes/kubernetes/pull/106200

**Comment by SergeyKanzhelev** [comment]
Welcome!

**Comment by oomichi** [comment]
Thanks for your contribution.
+1

**Comment by palnabarun** [comment]
@NikhilSharmaWe, thank you for all your contributions so far :)

I've created PR #3093 to add you to the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign

**Comment by NikhilSharmaWe** [comment]
@palnabarun thank you so much.
