### ISSUE TITLE
REQUEST: New membership for sandipanpanda

### ISSUE THREAD

**Issue by sandipanpanda** [kubernetes/org#3091]
### GitHub Username

@sandipanpanda

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@parispittman

### Sponsor 2

@MadhavJivrajani

### List of contributions to the Kubernetes project

- PRs authored
   - https://github.com/kubernetes/community/pull/6205
   - https://github.com/kubernetes/community/pull/5977
   - https://github.com/kubernetes/community/pull/6202
   - https://github.com/kubernetes/website/pull/30159
   - https://github.com/kubernetes/website/pull/30158
   - https://github.com/kubernetes/website/pull/29172
   - https://github.com/kubernetes/website/pull/30388
   - https://github.com/kubernetes/website/pull/30105
   - https://github.com/kubernetes/ingress-nginx/pull/7899
   - https://github.com/kubernetes-sigs/security-profiles-operator/pull/620
   - https://github.com/kubernetes/kube-state-metrics/pull/1621
   - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1305
   - https://github.com/kubernetes/contributor-site/pull/257
- Issues created / responded to
  - https://github.com/kubernetes/community/issues/6201
  - https://github.com/kubernetes/community/issues/6175
  - https://github.com/kubernetes/website/issues/30139
  - https://github.com/kubernetes/website/issues/30101
  - https://github.com/kubernetes/website/issues/29764
  - https://github.com/kubernetes/website/issues/27864
  - https://github.com/kubernetes/website/issues/29139
  - https://github.com/kubernetes/contributor-site/issues/256

- SIG projects I am involved with
  - SIG Contributor Experience
  - SIG Docs
- Non-code contributions:
  - Helped in framing some of the tweets for @K8sContributors to attract contributors for help wanted in specific contribution needs  as mentioned in the Kubernetes Community Annual Report 2020.
  - Helped in framing some of the tweets to be sent out through @K8sContributors during KubeCon NA 2021 to notify contributors for upcoming events.

**Comment by MadhavJivrajani** [comment]
+1
/pony party
Thank you for your contributions!

**Comment by sandipanpanda** [comment]
Thank you @MadhavJivrajani for sponsoring me. :love_you_gesture:

**Comment by parispittman** [comment]
+1 

thank you so much @sandipanpanda  !!!

**Comment by palnabarun** [comment]
@sandipanpanda, thank you for all your contributions so far :)

I've created PR #3093 to add you to the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign

**Comment by sandipanpanda** [comment]
Thank you @parispittman for sponsoring me. :relaxed: 
Thanks you @palnabarun for accepting my membership. :tada: 

/pony party
/meow caturday
