### ISSUE TITLE
REQUEST: Create contributor-katacoda repository

### ISSUE THREAD

**Issue by Debanitrkl** [kubernetes/org#3095]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

contributor-katacoda

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

sig-contributor-experience-leads (@cblecker, @nikhita, @mrbobbytables, @alisondy, @jberkus)

### Who should have write access?

sig-contributor-experience-leads (@cblecker, @nikhita, @mrbobbytables, @alisondy, @jberkus)

### Who should be listed as approvers in OWNERS?

@cblecker, @nikhita, @mrbobbytables, @alisondy, @jberkus, @MadhavJivrajani, @Debanitrkl

### Who should be listed in SECURITY_CONTACTS?

@MadhavJivrajani, @Debanitrkl

### What should the repo description be?

Host repository of katacoda scenarios for upstream contributors. 

### What SIG and subproject does this fall under?

This is a part of sig-contribex 

### Please provide references to appropriate approval for this new repo

Link to slack thread:
https://kubernetes.slack.com/archives/C1TU9EB9S/p1636735712147500
Link to the meeting minutes of sig-contibex, upstream marketing team, mentoring subproject where it was discussed:
https://docs.google.com/document/d/1KDoqbw2A6W7rLSbIRuOlqH8gkoOnp2IHHuV9KyJDD2c/edit#heading=h.n2ohtkgfpifv
https://docs.google.com/document/d/1CBz8qV_mD6rbDmTsMuosTOQGRXGhN3d8UrcULUI6Vkw/edit
https://www.google.com/url?q=https://docs.google.com/document/d/1XiXjDWCc087VKqX2b6LMGRnlaRyLYGh2-eWQQr6dAmc/edit%23heading%3Dh.vs8waxtx792q&sa=D&source=calendar&usd=2&usg=AOvVaw3iWoykXFqe6x2BiIWK4hvC

### Additional context for request

- This kataocda-scenario was created as part of this [discussion](https://github.com/kubernetes/community/issues/5576), there are already enough katacoda scenarios and tutorials available for downstream k8s users, but there weren't any such scenarios that would help upstream contributors to get started with.
- Presently this is the [katacoda-scenario](https://www.katacoda.com/debanitrkl/scenarios/new-scenario), which is hosted in my personal [github repository](https://github.com/Debanitrkl/katacoda-scenarios)
- For further collaboration on this and new additions we need to have a Kubernetes author profile in katacoda and a host repository under kubernetes-sigs repository as mentioned [here](https://www.katacoda.community/essentials/author-profile.html#create-author-profile)

**Comment by jberkus** [comment]
+1 on this.  This will be a subproject of Mentoring.

/assign @cblecker @mrbobbytables

**Comment by mrbobbytables** [comment]
/assign @nikhita @cblecker 
As TLs for contribex to approve an additional repo 👍 
(I cannot as a chair)

**Comment by cblecker** [comment]
Questions:
Is there going to be stuff like tagged releases or something from this repo? Do we need explicit write or admin access here?

Is this a new repo that we will PR things into, or are you looking to transfer the existing repo? I'd suggest the former, as there is a single author, and it allows us to use the existing boilerplate stuff.

Lastly, to clarify, the audience for these scenarios will be new contributors to upstream (as opposed to end users of kubernetes)?

**Comment by Debanitrkl** [comment]
> Questions: Is there going to be stuff like tagged releases or something from this repo? Do we need explicit write or admin access here?
> 
No, there won't be any tagged releases from this repo, as any changes at any point of time would reflect in katacoda. Yes write and admin access is required as we will be integrating the katacoda webhook with this repository. Will open an issue for integrations after this repo is created. So admin access would allows us to manage that integration.

> Is this a new repo that we will PR things into, or are you looking to transfer the existing repo? I'd suggest the former, as there is a single author, and it allows us to use the existing boilerplate stuff.
> 
Yes, this will be a new repository, where we will PR the things.
> Lastly, to clarify, the audience for these scenarios will be new contributors to upstream (as opposed to end users of kubernetes)?
>
Yes, this is for someone who's starting with upstream contribution.

**Comment by cblecker** [comment]
> So admin access would allows us to manage that integration.

It doesn't actually, as webhooks/integrations are managed by the GH admin team. If that's the only use case, then we can manage this through bots/OWNERS files and don't need direct permissions.

> Yes, this is for someone who's starting with upstream contribution.

Can we choose a more descriptive repo name then? I'd suggest maybe something like "upstream-dev-tutorials"? cc @jberkus

**Comment by jberkus** [comment]
Oh, you would ask the hard question.

Ideas:
* k8s-dev-scenario
* contributor-katacoda
* dev-kc-tutorial

I do want to make it kind of clear in the name (as well as the README) that this isn't the only contributor/developer tutorial, since tutorials using other platforms will live elsewhere in our repos.

**Comment by Debanitrkl** [comment]
Contributor-katacoda seems good, rest we can have the details in the description

**Comment by cblecker** [comment]
Repo created: https://github.com/kubernetes-sigs/contributor-katacoda

**Comment by cblecker** [comment]
Actually, before we close this:
@Debanitrkl @jberkus Would you mind adding this repo to sigs.yaml under the mentoring subproject?

/assign

**Comment by Debanitrkl** [comment]
Yeah will add this to sigs.yaml
