### ISSUE TITLE
REQUEST: New membership for yxxhero

### ISSUE THREAD

**Issue by yxxhero** [kubernetes/org#3096]
### GitHub Username

@yxxhero

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@SergeyKanzhelev

### Sponsor 2

@mengjiao-liu

### List of contributions to the Kubernetes project

* PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Ayxxhero+
  https://github.com/kubernetes/minikube/pulls?q=is%3Apr+author%3Ayxxhero+
  https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ayxxhero+

  https://github.com/kubernetes/kubernetes/pull/106201
  https://github.com/kubernetes/kubernetes/pull/105721
  https://github.com/kubernetes/kubernetes/pull/105608
  https://github.com/kubernetes/kubernetes/pull/105430
  https://github.com/kubernetes/kubernetes/pull/105213
  https://github.com/kubernetes/kubernetes/pull/104651
  https://github.com/kubernetes/kubernetes/pull/104650
  https://github.com/kubernetes/kubernetes/pull/104497
  https://github.com/kubernetes/kubernetes/pull/98913
  https://github.com/kubernetes/kubernetes/pull/98824
  https://github.com/kubernetes/kubernetes/pull/98366

  https://github.com/kubernetes/website/pull/29577
  https://github.com/kubernetes/website/pull/28940

  https://github.com/kubernetes/minikube/pull/12514
  https://github.com/kubernetes/minikube/pull/10760

* Issues responded to
  https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+author%3Ayxxhero+
  https://github.com/kubernetes/kubernetes/issues/106246
  https://github.com/kubernetes/kubernetes/issues/106199
  https://github.com/kubernetes/kubernetes/issues/106047
  https://github.com/kubernetes/kubernetes/issues/104496

**Comment by SergeyKanzhelev** [comment]
+1, welcome!

**Comment by mengjiao-liu** [comment]
I see that you have made a lot of contributions to this. Welcome!
LGTM

**Comment by mrbobbytables** [comment]
@yxxhero thank you for all your contributions so far :)

I've created PR #3110  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
