### ISSUE TITLE
REQUEST: New membership for nak3

### ISSUE THREAD

**Issue by nak3** [kubernetes/org#3099]
### GitHub Username

@nak3

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@robscott

### Sponsor 2

@jpeach

### List of contributions to the Kubernetes project

- PRs: https://github.com/kubernetes-sigs/gateway-api/pulls?q=is%3Apr+author%3Anak3+is%3Aclosed
- Issue: https://github.com/kubernetes-sigs/gateway-api/issues?q=is%3Aissue+author%3Anak3
- SIG projects I am involved with
  - Gateway API WG under SIG-Network

**Comment by jpeach** [comment]
+1

**Comment by robscott** [comment]
Thanks for all the help @nak3!
 
+1

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3110  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
