### ISSUE TITLE
REQUEST: New membership for FillZpp

### ISSUE THREAD

**Issue by FillZpp** [kubernetes/org#3100]
### GitHub Username

@FillZpp

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alvaroaleman

### Sponsor 2

@vincepri

### List of contributions to the Kubernetes project

- PRs authored:

  - https://github.com/kubernetes-sigs/controller-runtime/pull/1149
  - https://github.com/kubernetes-sigs/controller-runtime/pull/1274
  - https://github.com/kubernetes-sigs/controller-runtime/pull/1627
  - https://github.com/kubernetes-sigs/controller-runtime/pull/1651
  - https://github.com/kubernetes-sigs/controller-runtime/pull/1703
  - https://github.com/kubernetes/kubernetes/pull/102949
  - https://github.com/kubernetes/kube-state-metrics/pull/1537

- Issues created / responded to:

  - https://github.com/kubernetes-sigs/controller-runtime/issues/308
  - https://github.com/kubernetes-sigs/controller-runtime/issues/797
  - https://github.com/kubernetes-sigs/controller-runtime/pull/1279
  - https://github.com/kubernetes-sigs/controller-runtime/pull/1519
  - https://github.com/kubernetes-sigs/controller-runtime/pull/1570
  - https://github.com/kubernetes-sigs/controller-runtime/pull/1638
  - https://github.com/kubernetes-sigs/controller-runtime/issues/1660
  - https://github.com/kubernetes-sigs/controller-runtime/issues/1673
  - https://github.com/kubernetes-sigs/controller-runtime/issues/1685
  - https://github.com/kubernetes-sigs/controller-runtime/issues/1697
  - https://github.com/kubernetes-sigs/controller-runtime/pull/1710
  - https://github.com/kubernetes-sigs/controller-runtime/issues/1715
  - https://github.com/kubernetes-sigs/controller-tools/issues/457
  - https://github.com/kubernetes-sigs/kubebuilder/issues/505
  - https://github.com/kubernetes-sigs/kubebuilder/issues/510
  - https://github.com/kubernetes-sigs/kubebuilder/issues/2311
  - https://github.com/kubernetes/kubernetes/pull/99728
  - https://github.com/kubernetes/kubernetes/issues/102948
  - https://github.com/kubernetes/kubernetes/pull/103354

- SIG projects I am involved with
  - kubernetes-sigs/controller-runtime
  - kubernetes-sigs/kubebuilder
  - kubernetes/kubernetes
  - kubernetes/kube-state-metrics

**Comment by FillZpp** [comment]
Hey, would you like to be my sponsor? 😄  @alvaroaleman @vincepri

**Comment by alvaroaleman** [comment]
+1

**Comment by vincepri** [comment]
+1

**Comment by mrbobbytables** [comment]
@FillZpp thank you for all your contributions so far :)

I've created PR #3110  to add you to the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
