### ISSUE TITLE
REQUEST: New membership for sbs2001

### ISSUE THREAD

**Issue by sbs2001** [kubernetes/org#3104]
### GitHub Username

@sbs2001

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@surajssd

### Sponsor 2

@hangyan

### List of contributions to the Kubernetes project

Authored PRs:

- https://github.com/kubernetes/kompose/pull/1456
- https://github.com/kubernetes/kompose/pull/1443
- https://github.com/kubernetes/kompose/pull/1430
- https://github.com/kubernetes/kompose/pull/1432
- https://github.com/kubernetes/kompose/pull/1435
- https://github.com/kubernetes/kompose/pull/1441
- https://github.com/kubernetes/kompose/pull/1447
- https://github.com/kubernetes/kompose/pull/1452
- https://github.com/kubernetes/kompose/pull/1455
- https://github.com/kubernetes/k8s.io/pull/3044
- https://github.com/kubernetes/autoscaler/pull/4448
- https://github.com/kubernetes/kompose/pull/1461
- https://github.com/kubernetes/kubernetes/pull/106291

Issues Fixed/Contributed to:

- https://github.com/kubernetes/kompose/issues/1429
- https://github.com/kubernetes/kompose/issues/1416
- https://github.com/kubernetes/kompose/issues/1400
- https://github.com/kubernetes/kompose/issues/698
- https://github.com/kubernetes/kompose/issues/1457

Projects/sigs I'm involved with:

- kompose
- sig-autoscaling
- kubernetes

**Comment by hangyan** [comment]
+1

**Comment by surajssd** [comment]
I endorse Shivam based on his contributions and officially bringing him into our family will be of great help for us.

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3110  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
