### ISSUE TITLE
REQUEST: New membership for @pnbrown

### ISSUE THREAD

**Issue by pnbrown** [kubernetes/org#3105]
### GitHub Username

pnbrown

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@parispittman

### Sponsor 2

@mrbobbytables

### List of contributions to the Kubernetes project

- Active in Contributor Experience Special Interest Group. I have been regularly contributing to meetings, helped plan the contributor summit, and am actively helping figure out solutions for the YouTube channel and automation.

**Comment by parispittman** [comment]
+1 
Reason: Nigel has YouTube admin experience and we need more folks to join us in this area; expecting follow up merged PRs to the YouTube docs. Also supported at day job in this kind of role and has lots of trusted connections within the community.

**Comment by mrbobbytables** [comment]
+1

**Comment by chris-short** [comment]
+1

**Comment by mrbobbytables** [comment]
@pnbrown thanks for stepping up to help us with YT and all the other community places :) 

I've created PR #3110  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
