### ISSUE TITLE
REQUEST: Create sigs.k8s.io/bom

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#3106]
### New repo, staging repo, or migrate existing

New repo

### Is it a staging repo?

no

### Requested name for new repository

https://github.com/kubernetes-sigs/bom

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@sig-release-admins

### Who should have write access?

@sig-release-admins

### Who should be listed as approvers in OWNERS?

@sig-release-admins

### Who should be listed in SECURITY_CONTACTS?

@sig-release-admins

### What should the repo description be?

A utility to generate SPDX-compliant Bill of Materials manifests

### What SIG and subproject does this fall under?

SIG Release

### Please provide references to appropriate approval for this new repo

Self-approve as a SIG Release Chair + Release Engineering subproject owner.
Tagging other @kubernetes/sig-release-admins for consideration.

### Additional context for request

This would start as an empty repository, but soon after be populated with the contents of https://github.com/kubernetes/release/tree/master/cmd/bom (and its associated libraries).

Given this tool is starting to attract attention from other open source foundations, it'd be great to pull the content out into its own repo to:
- reduce friction to contribution
- define a more accelerated release cycle than k/release

cc: @kubernetes/owners

**Comment by justaugustus** [comment]
cc: @kubernetes/sig-release-admins @kubernetes/release-engineering

**Comment by saschagrunert** [comment]
+1 for the new repository

**Comment by mrbobbytables** [comment]
Repo has been created: https://github.com/kubernetes-sigs/bom
teams added in PR: https://github.com/kubernetes/org/pull/3108
subproject added in PR: https://github.com/kubernetes/community/pull/6239

Once all PRs have merged and teams added to the repo this should be good to go :)

**Comment by puerco** [comment]
Thank you @mrbobbytables !!

**Comment by justaugustus** [comment]
You rock, Bob!

**Comment by mrbobbytables** [comment]
Teams have been granted permission over the repo 👍

**Comment by justaugustus** [comment]
We're all set here.
Thanks for the help, Bob!

/close
