### ISSUE TITLE
REQUEST: New membership for riita10069

### ISSUE THREAD

**Issue by riita10069** [kubernetes/org#3107]
### GitHub Username

riita10069

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@nasa9084

### Sponsor 2

@inductor

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  - https://github.com/kubernetes/website/pulls/riita10069
- Issues responded to
  - https://github.com/kubernetes/website/issues/created_by/riita10069
- SIG projects I am involved with
  - SIG Docs

**Comment by inductor** [comment]
Thanks for your contributions! +1

**Comment by nasa9084** [comment]
+1

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3110  to add you to the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
