### ISSUE TITLE
REQUEST: Create design-proposals-archive repo

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/org#3109]
### New repo, staging repo, or migrate existing

New Repo

### Is it a staging repo?

no

### Requested name for new repository

design-proposals-archive

### Which Organization should it reside

kubernetes

### Who should have admin access?

@sig-architecture-leads

### Who should have write access?

none

### Who should be listed as approvers in OWNERS?

@sig-architecture-leads

### Who should be listed in SECURITY_CONTACTS?

@sig-architecture-leads

### What should the repo description be?

Archive of historical Kubernetes design proposals

### What SIG and subproject does this fall under?

SIG Arch / Enhancements

### Please provide references to appropriate approval for this new repo

Not approval, but discussion on the topic:
Mailing list thread: https://groups.google.com/a/kubernetes.io/g/leads/c/nQKpkdZXK-0/m/uUCwGMhnBgAJ
Start of Slack discussion: https://kubernetes.slack.com/archives/C5P3FE08M/p1637157177036800

Dims was open to the idea in the slack discussion - creating this to push things along.

/assign @dims @derekwaynecarr @johnbelamaric 

### Additional context for request

(TL;DR from mailing list thread and slack)

The intent is to create a repo within the kubernetes org to serve as the permanent archival place for design proposals. This would be a special case where the repo -would- be archived in non kubernetes-retired org. The reason for this is because people continue to reference and open PRs/issues against the content in there, despite the blockade setup and sign-posting at the root of the design proposal dir. The only real way we collectively thought of to signal their status was to move them to a repo (with preserved git history) and archive it.

Why not move to kubernetes-retired? There is still a significant amount of useful information in there, and SIGs at their discretion can opt into maintaining an updated copy within their devel directory.

**Comment by dims** [comment]
+1 (let's please try to save history as well)

**Comment by derekwaynecarr** [comment]
+1

**Comment by mrbobbytables** [comment]
Repo was created
Content moved over
sigs.yaml update 👍 

This is good to close!

/close
