### ISSUE TITLE
REQUEST: New repository for kubernetes-csi-tencentcloud

### ISSUE THREAD

**Issue by kinderyj** [kubernetes/org#3114]
### New repo, staging repo, or migrate existing

New repository

### Is it a staging repo?

no

### Requested name for new repository

kubernetes-csi-tencentcloud

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

kinderyj

### Who should have write access?

kinderyj

### Who should be listed as approvers in OWNERS?

kinderyj

### Who should be listed in SECURITY_CONTACTS?

kinderyj

### What should the repo description be?

kubernetes-csi-tencentloud plugins implement interface of CSI. It can enable your Container Orchestrator use Tencent Cloud storage.

### What SIG and subproject does this fall under?

this is a new subproject under kubernetes-sigs

### Please provide references to appropriate approval for this new repo

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

### Additional context for request

kubernetes-csi-tencentloud plugins implement interface of CSI. It can enable your Container Orchestrator use Tencent Cloud storage.
It contains CBS CSI Plugin\CFS CSI Plugin\COS CSI Plugin.

**Comment by mrbobbytables** [comment]
@kinderyj This needs approval from sig-storage leads
Did you also mean to request it for kubernetes-csi or kubernetes-sigs orgs? kubernetes-csi is where the other csi drivers are.
You will also have to file a request for org membership to kubernetes-sigs or kubernetes-csi depending on the org you want the repo to live in. - Please see the [membership requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#member) for more information.

**Comment by kinderyj** [comment]
@mrbobbytables Thanks a lot for your quick response. 

We want to migrate our csi repo `https://github.com/TencentCloud/kubernetes-csi-tencentcloud` to `https://github.com/orgs/kubernetes-sigs` and be part of the sig-cloud-provider. 

Could you tell us what we should do and who to contact? Thanks.

**Comment by mrbobbytables** [comment]
@kinderyj kk, it needs approval from the sig-cloud-provider leads.
There is additional process for donated repos. You can see the requirements for them outline here:
https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories
