### ISSUE TITLE
REQUEST: New membership for stormqueen1990

### ISSUE THREAD

**Issue by stormqueen1990** [kubernetes/org#3115]
### GitHub Username

@stormqueen1990

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@rikatz 

### Sponsor 2

@edsoncelio 

### List of contributions to the Kubernetes project

I have contributed the following pull requests to the Brazilian Portuguese localization of Kubernetes documentation:
- https://github.com/kubernetes/website/pull/29495
- https://github.com/kubernetes/website/pull/28979
- https://github.com/kubernetes/website/pull/29572
- https://github.com/kubernetes/website/pull/30231
- https://github.com/kubernetes/website/pull/30583

**Comment by rikatz** [comment]
+1

Mauren is doing a lot of things on the Kubernetes website localization to pt-br

**Comment by edsoncelio** [comment]
+1 Mauren is doing a great job with the pt-br localization team in Kubernetes docs :)

**Comment by cblecker** [comment]
Thank you for all your contributions so far!

I've created PR #3121 to add you to the requested organizations. Once that gets merged, you should get a membership invite notification, and will need to be accepted.

Welcome to @kubernetes! 🚀
