### ISSUE TITLE
REQUEST: Create kubernetes-sigs/krm-functions-registry

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/org#3117]
### New repo, staging repo, or migrate existing

new repo

### Is it a staging repo?

no

### Requested name for new repository

krm-functions-registry

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

jeremyrickard, KnVerey, mengqiy

### Who should have write access?

jeremyrickard, KnVerey, mengqiy

### Who should be listed as approvers in OWNERS?

jeremyrickard, KnVerey, mengqiy

### Who should be listed in SECURITY_CONTACTS?

jeremyrickard, KnVerey, mengqiy

### What should the repo description be?

Public registry for KRM functions

### What SIG and subproject does this fall under?

This is a new subproject for sig-cli called krm-functions

### Please provide references to appropriate approval for this new repo

The subproject proposal was [presented](https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#bookmark=id.w4zlpjd1ekpf) in the SIG-CLI meeting. There were no objections.
The [official proposal in the SIG-CLI mailing list](https://groups.google.com/g/kubernetes-sig-cli/c/vaAriA5EL_Y/m/PIrAwOIdBAAJ?utm_medium=email&utm_source=footer) has reached lazy consensus by 11/03/2021.

**Comment by KnVerey** [comment]
👍 from me

**Comment by cblecker** [comment]
The repo has been created: https://github.com/kubernetes-sigs/krm-functions-registry
After https://github.com/kubernetes/org/pull/3122 has merged, I'll be able to provide admin/write access

**Comment by mengqiy** [comment]
@cblecker #3122 has been merged.

**Comment by cblecker** [comment]
@mengqiy Access has been provided. The last step is to get the new repo added to sigs.yaml. Would you mind opening a PR to do that? Thanks!

**Comment by mengqiy** [comment]
Sure. https://github.com/kubernetes/community/pull/6249

**Comment by cblecker** [comment]
This is complete!
/close
