### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/cluster-api-provider-ibmcloud

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/org#3118]
### Repository

https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud

### Project domain

cluster-api-ibmcloud.sigs.k8s.io

### Additional context for request

netlify configuration added via: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/442

xref: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/346

**Comment by cblecker** [comment]
/unassign @mrbobbytables 
/assign

Site has been created at: https://kubernetes-sigs-cluster-api-ibmcloud.netlify.app/

You still need to request/add the DNS in k8s.io: https://github.com/kubernetes/community/blob/4026287dc3a2d16762353b62ca2fe4b80682960a/github-management/subproject-site-requests.md#requesting-a-subproject-domain

**Comment by mkumatag** [comment]
> You still need to request/add the DNS in k8s.io: https://github.com/kubernetes/community/blob/4026287dc3a2d16762353b62ca2fe4b80682960a/github-management/subproject-site-requests.md#requesting-a-subproject-domain

created an issue here: https://github.com/kubernetes/k8s.io/issues/3137

**Comment by mkumatag** [comment]
@cblecker can I get an entry configured for the `release-0.1` branch as well?

**Comment by mrbobbytables** [comment]
It has been configured 👍 

![Screen Shot 2022-01-26 at 8 47 06 AM](https://user-images.githubusercontent.com/6500863/151174397-95cba601-b34d-4e44-9762-9f7ab56c23d5.png)


With that, I'm going to go ahead and close this out.
Thanks!

/close

**Comment by mkumatag** [comment]
> With that, I'm going to go ahead and close this out.
> Thanks!

@mrbobbytables how do I access any particular branch site? I tried the following the URL but it is not working.

https://release-0-1--kubernetes-sigs-cluster-api-ibmcloud.netlify.app

**Comment by mrbobbytables** [comment]
something needs to be pushed to the branch to trigger it to build.
