### ISSUE TITLE
REQUEST: New membership for MaxRenaud

### ISSUE THREAD

**Issue by MaxRenaud** [kubernetes/org#3120]
### GitHub Username

MaxRenaud

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

cheftako

### Sponsor 2

lachie83

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/182
- https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/184
- https://github.com/kubernetes-sigs/kind/issues/1826
- https://github.com/kubernetes-sigs/kind/pull/1825

Working on graduating these two KEP:
- https://github.com/kubernetes/enhancements/issues/1864
- https://github.com/kubernetes/enhancements/issues/2086

**Comment by lachie83** [comment]
+1

**Comment by cheftako** [comment]
+1

**Comment by cblecker** [comment]
Thank you for all your contributions so far!

I've created PR #3121 to add you to the requested organizations. Once that gets merged, you should get a membership invite notification, and will need to be accepted.

Welcome to @kubernetes! 🚀
