### ISSUE TITLE
REQUEST: Katacoda integration for contributor-katacoda

### ISSUE THREAD

**Issue by Debanitrkl** [kubernetes/org#3123]
### Organization or Repo

kubernetes-sigs/contributor-katacoda

### Name of integration

Katacoda

### Link to integration website

https://www.katacoda.com/

### Describe what is attempting to be accomplished

This repository, hosts the katacoda scenarios for upstream k8s developers. To have a scenario live in katacoda we need to integrate the source repository with a katacoda author profile as described [here](https://www.katacoda.community/essentials/author-profile.html#github)

Example:
I have implemented it using my own repository
- The host [repo](https://github.com/Debanitrkl/katacoda-scenarios)
- The host [author profile](https://www.katacoda.com/debanitrkl)

**Comment by cblecker** [comment]
Had to play around with the naming to find one that worked, but this should all be hooked up to https://katacoda.com/k8scontributors now
