### ISSUE TITLE
REQUEST: New membership for anusha94

### ISSUE THREAD

**Issue by anusha94** [kubernetes/org#3124]
### GitHub Username

@anusha94

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@enxebre

### List of contributions to the Kubernetes project

- PRs authored
  - https://github.com/kubernetes-sigs/cluster-api/pull/5301
  - https://github.com/kubernetes-sigs/cluster-api/pull/5231
  - https://github.com/kubernetes-sigs/cluster-api/pull/5209
  - https://github.com/kubernetes-sigs/cluster-api/pull/4791
  - https://github.com/kubernetes/test-infra/pull/24220
---
- Active issues assigned
  - https://github.com/kubernetes/test-infra/issues/22721
  - https://github.com/kubernetes-sigs/cluster-api/issues/3728
  - https://github.com/kubernetes-sigs/kpng/issues/136
---
- SIGs projects I'm involved with
   - https://github.com/kubernetes-sigs/cluster-api
   - https://github.com/kubernetes/test-infra
   - https://github.com/kubernetes-sigs/kpng

**Comment by enxebre** [comment]
+1
welcome @anusha94!

**Comment by sbueringer** [comment]
+1
Thank you for your contributions so far :)

**Comment by fabriziopandini** [comment]
+1
Welcome on board @anusha94!

**Comment by rajaskakodkar** [comment]
+1 
welcome @anusha94 !!!

**Comment by Ankitasw** [comment]
+1
welcome @anusha94

**Comment by palnabarun** [comment]
@anusha94 -- Thank you for all your contributions to Cluster API, kpng and test-infra.

I have filed PR #3146 to add you to the requested organisation. Once the PR gets merged, you will membership invite notifications!

Welcome! 🎉
