### ISSUE TITLE
REQUEST: New membership for h4ghhh

### ISSUE THREAD

**Issue by h4ghhh** [kubernetes/org#3128]
### GitHub Username

@h4ghhh

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei

### Sponsor 2

@tengqm

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/kubernetes/pull/97361
- https://github.com/kubernetes/kubernetes/pull/100125
- https://github.com/kubernetes/kubernetes/pull/100598
- https://github.com/kubernetes/kubernetes/pull/104571
- https://github.com/kubernetes/kubernetes/pull/104793
- https://github.com/kubernetes/kubernetes/pull/104841
- https://github.com/kubernetes/kubernetes/pull/105065
- https://github.com/kubernetes/kubernetes/pull/105087
- https://github.com/kubernetes/kubernetes/pull/105088
- https://github.com/kubernetes/kubernetes/pull/105089
- https://github.com/kubernetes/kubernetes/pull/105902
- https://github.com/kubernetes/website/pull/24611
- https://github.com/kubernetes/website/pull/30665
- https://github.com/kubernetes/website/pull/30683

**Comment by tengqm** [comment]
+1

**Comment by Huang-Wei** [comment]
+1

**Comment by Huang-Wei** [comment]
+1

**Comment by palnabarun** [comment]
@h4ghhh -- Thank you for all your contributions so far!

I have filed PR #3146 to add you to the requested organisation. Once the PR gets merged, you will membership invite notifications!

Welcome! 🎉
