### ISSUE TITLE
REQUEST: New membership for mikeshng

### ISSUE THREAD

**Issue by mikeshng** [kubernetes/org#3133]
### GitHub Username

@mikeshng

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@yue9944882

### Sponsor 2

@RainbowMango

### List of contributions to the Kubernetes project

https://github.com/kubernetes-sigs/work-api/pull/12
https://github.com/kubernetes-sigs/work-api/pull/11
https://github.com/kubernetes-sigs/work-api/pull/10#pullrequestreview-758967717

Presented `kubernetes-sigs/work-api` project in the Kubernetes Multi-cluster SIG bi-weekly meeting.

**Comment by yue9944882** [comment]
+1 welcome!

**Comment by RainbowMango** [comment]
+1 from me.

**Comment by palnabarun** [comment]
@mikeshng -- Thank you for all your contributions so far!

I have filed PR #3146 to add you to the requested organisation. Once the PR gets merged, you will membership invite notifications!

Welcome! 🎉
