### ISSUE TITLE
REQUEST: New membership for Xenwar

### ISSUE THREAD

**Issue by Xenwar** [kubernetes/org#3137]
### GitHub Username

Xenwar

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

hidekazuna

### Sponsor 2

mdbooth

### List of contributions to the Kubernetes project

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pulls/Xenwar
https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+author%3AXenwar+is%3Aclosed
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pulls?q=is%3Apr+author%3AXenwar+is%3Aclosed
https://github.com/metal3-io/cluster-api-provider-baremetal/pulls?q=is%3Apr+is%3Aclosed+author%3AXenwar
https://github.com/metal3-io/metal3-dev-env/pulls?q=is%3Apr+author%3AXenwar+is%3Aclosed
https://github.com/metal3-io/baremetal-operator/pulls?q=is%3Apr+author%3AXenwar+is%3Aclosed
https://github.com/metal3-io/cluster-api-provider-metal3/pulls?q=is%3Apr+author%3AXenwar+is%3Aclosed

**Comment by hidekazuna** [comment]
@Xenwar Thank you for your contribution!

**Comment by mdbooth** [comment]
+1 from me!

**Comment by palnabarun** [comment]
@Xenwar -- Thank you for all your contributions so far!

I have filed PR #3146 to add you to the requested organisation. Once the PR gets merged, you will membership invite notifications!

Welcome! 🎉
