### ISSUE TITLE
Sample repo for cloud-provider creation

### ISSUE THREAD

**Issue by cheftako** [kubernetes/org#314]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
cloud-provider-sample

### Which Organization should it reside
sig-cloud-provider

### If not a staging repo, who should have admin access
@cheftako @andrewsykim @mcrute 

### If not a staging repo, who should have write access
@cheftako @andrewsykim @mcrute 

### If a new repo, who should be listed as approvers in OWNERS
@cheftako @andrewsykim @mcrute 

### If a new repo, who should be listed in SECURITY_CONTACTS
@cheftako @andrewsykim @mcrute 

### What should the repo description be
Sample of how to build a cloud provider repo.
This will build a Kubernetes image which deploys on bare metal.
It uses the fake cloud provider.
It consumes the K8s/K8s build artifact and adds to it the Cloud Controller Manager and CSI Daemon Set.

### What SIG and subproject does this fall under in sigs.yaml
This is a sample of how to create a cloud provider repo for sig-cloudprovider 

### Approvals
Conversation with @andrewsykim and @mcrute 

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md
- If this is a SIG repository, then this must follow the procedure spelled out  in that SIG's charter

### Additional context for request
This was discussed in the KubeCon Seattle SIG meeting.

/area github-repo

**Comment by andrewsykim** [comment]
+1 thanks @cheftako

**Comment by mcrute** [comment]
+1

**Comment by calebamiles** [comment]
[done](https://github.com/kubernetes/cloud-provider-sample/tree/master). please update `sigs.yaml` with the new repository

**Comment by andrewsykim** [comment]
Thanks Caleb! PR for sigs.yaml https://github.com/kubernetes/community/pull/3051

**Comment by spiffxp** [comment]
Why isn't this a kubernetes-sigs repo?  Why didn't this get approved through sig-arch?  

https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-1

**Comment by andrewsykim** [comment]
@spiffxp we already went through sig-arch approvals for `kubernetes/cloud-provider-*` repos (see https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/soeIadIeMCs). It also wouldn't make sense for us to host the actual provider repos in `kubernetes` but host the sample repo in `kubernetes-sigs`. Having everything in `kubernetes-sigs` is something we intend to do eventually  (though not urgent).

**Comment by nikhita** [comment]
I came across this repo while working on https://github.com/kubernetes/steering/issues/28 and have created a PR to add template files (LICENSE, CONTRIBUTING.md, README.md, code-of-conduct.md): https://github.com/kubernetes/cloud-provider-sample/pull/1.

The README description is based on the description provided here. PTAL. :)
