### ISSUE TITLE
REQUEST: Create special-resource-operator

### ISSUE THREAD

**Issue by zvonkok** [kubernetes/org#3140]
### New repo, staging repo, or migrate existing

new repo

### Is it a staging repo?

no

### Requested name for new repository

special-resource-operator

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@qbarrand  @pacevedom @bthurber @zvonkok @shivamerla @adrianchiris

### Who should have write access?

@qbarrand  @pacevedom @bthurber @zvonkok @shivamerla @adrianchiris

### Who should be listed as approvers in OWNERS?

@qbarrand  @pacevedom @bthurber @zvonkok @shivamerla @adrianchiris

### Who should be listed in SECURITY_CONTACTS?

@zvonkok @qbarrand

### What should the repo description be?

SRO supports out-of-tree and third-party kernel drivers and the support software for the node OS via containers. 

### What SIG and subproject does this fall under?

sig-node

### Please provide references to appropriate approval for this new repo

- Zvonko Kaiser @zvonkok presented the proposal in [November 30th, 2021](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.bmrg8nwe7k1) agenda item.
- Approved at the [December 7th, 2021](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.6eot4zyi63o4) meeting.

### Additional context for request

This repo is meant to house the Special Resource Operator. SRO enables users to deploy and maintain
out-of-tree drivers by leveraging DriverContainers.

Several companies are using SRO today to provide their customers with a way to use their hardware,
and they are interested in collaborating further on the operator.

**Comment by zvonkok** [comment]
@hbrueckner FYI, see also sig-node recording from Nov. 30th, [kubernetes.sigs/sro](https://docs.google.com/presentation/d/1FHVLwp8QqkpJnsaE3NqvjAu3gsWb3hXQSN4SmyuNuXg/edit#slide=id.g1015afca470_0_83)

**Comment by dchen1107** [comment]
+1

**Comment by derekwaynecarr** [comment]
+1

per discussion in SIG Node 1/11 meeting, it would be good to schedule sub-project readout for how the project is evolving in a few weeks.

**Comment by ybettan** [comment]
+1

**Comment by zvonkok** [comment]
@mrbobbytables @cblecker Anything needed to move this forward?

**Comment by mrbobbytables** [comment]
@zvonkok It's mostly been a bandwidth issue - One thing that does block moving forward, most of the people that are listed are not currently members of any k8s org. They will have to apply and go through the regular process first before they can be added. If you want to proceed with just yourself and @adrianchiris we can do that.

**Comment by zvonkok** [comment]
@mrbobbytables Lets start with @zvonkok and @adrianchiris. I will ping the others for the membership application.

**Comment by mrbobbytables** [comment]
The repo has been created - https://github.com/kubernetes-sigs/special-resource-operator
Once the other 2 PRs are merged adding the teams and updating sigs.yaml this should be done 🎉

**Comment by mrbobbytables** [comment]
All PRs merged, teams have been added to the repo 🎉 Going to go ahead and close this out.

/close
