### ISSUE TITLE
REQUEST: New membership for chrischdi

### ISSUE THREAD

**Issue by chrischdi** [kubernetes/org#3141]
### GitHub Username

@chrischdi

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@jichenjc

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  - https://github.com/kubernetes/kube-state-metrics/pull/1531
  - https://github.com/kubernetes/cloud-provider-openstack/pull/1504
  - https://github.com/kubernetes/test-infra/pull/20513
  - https://github.com/kubernetes/cloud-provider-openstack/pull/831
  - https://github.com/kubernetes/cloud-provider-openstack/pull/631
  - https://github.com/kubernetes/cloud-provider-openstack/pull/617
- Issues responded to
  - https://github.com/kubernetes/cloud-provider-openstack/issues/1242
  - https://github.com/kubernetes/kubernetes/issues/91023
  - https://github.com/kubernetes/cloud-provider-openstack/issues/933
  - https://github.com/kubernetes/kubernetes/issues/87603
  - https://github.com/kubernetes/kubeadm/issues/1655
  - https://github.com/kubernetes/kubernetes/issues/77969
- SIG projects I am involved with
  - already member of kubernetes-sigs
  - reviewer in https://github.com/kubernetes-sigs/cluster-api-provider-openstack
  - non-kubernetes-sigs: https://github.com/kubernetes/cloud-provider-openstack

**Comment by jichenjc** [comment]
+1 to me :)  thanks

**Comment by sbueringer** [comment]
+1

**Comment by palnabarun** [comment]
@chrischdi -- Thank you for all your contributions so far!

I have filed PR #3146 to add you to the requested organisation. Once the PR gets merged, you will membership invite notifications!

Welcome! 🎉
