### ISSUE TITLE
REQUEST: New membership for mdbooth

### ISSUE THREAD

**Issue by mdbooth** [kubernetes/org#3142]
### GitHub Username

@mdbooth

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@seanschneeweiss

### Sponsor 2

@tobiasgiese / @jichenjc 

### List of contributions to the Kubernetes project

I am a maintainer of https://github.com/kubernetes-sigs/cluster-api-provider-openstack. I currently only require access to test-infra to make changes to CAPO tests. I have previously made some minor changes in https://github.com/kubernetes/cloud-provider-openstack, although I expect to that to increase significantly over the next 12 months.

In Kubernetes:
- https://github.com/kubernetes/cloud-provider-openstack/pull/1476
- https://github.com/kubernetes/cloud-provider-openstack/pull/1483
- https://github.com/kubernetes/cloud-provider-openstack/pull/1528

In Kubernetes-SIGs (author):
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1030
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1004
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1032
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1063
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1066

In Kubernetes-SIGS (reviewer):
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1039
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1012
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1003
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1014
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/950

**Comment by tobiasgiese** [comment]
+1 from my side 🙂

**Comment by mdbooth** [comment]
@tobiasgiese points out that both him and @seanschneeweiss work for the same company. I'll look for another sponsor, but as I work for a different company I wonder if the conditions have been met anyway?

**Comment by seanschneeweiss** [comment]
+1 from my side too :) let's see if a third sponsor from a different company is required.

**Comment by mdbooth** [comment]
@jichenjc is also willing to sponsor.

**Comment by palnabarun** [comment]
@mdbooth -- Thank you for all your contributions so far!

I have filed PR #3146 to add you to the requested organisation. Once the PR gets merged, you will membership invite notifications!

Welcome! 🎉
