### ISSUE TITLE
REQUEST: Create oci-proxy

### ISSUE THREAD

**Issue by ameukam** [kubernetes/org#3143]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

oci-proxy

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

ameukam,dims,spiffxp,thockin

### Who should have write access?

ameukam,dims,spiffxp,thockin

### Who should be listed as approvers in OWNERS?

ameukam,dims,spiffxp,thockin

### Who should be listed in SECURITY_CONTACTS?

ameukam,dims,spiffxp,thockin

### What should the repo description be?

# Experimental / Work in Progress

This project exists to explore the creation of a proxy for OCI images.

This project is experimental and may change drastically or be cancelled with little or no public notice.

### What SIG and subproject does this fall under?

sig-k8s-infra

### Please provide references to appropriate approval for this new repo

Have a dedicated repo to host a Golang program : https://github.com/kubernetes/k8s.io/issues/1834#issuecomment-949977061

**Comment by dims** [comment]
+1 from me

**Comment by ameukam** [comment]
cc @spiffxp @thockin
