### ISSUE TITLE
REQUEST: New membership for zhengtianbao

### ISSUE THREAD

**Issue by zhengtianbao** [kubernetes/org#3144]
### GitHub Username

@zhengtianbao

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@floryut

### Sponsor 2

@cristicalin / @oomichi 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pulls?q=is%3Apr+author%3Azhengtianbao
https://github.com/kubernetes/kops/pulls?q=is%3Apr+author%3Azhengtianbao
https://github.com/kubernetes/ingress-nginx/pulls?q=is%3Apr+author%3Azhengtianbao
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3Azhengtianbao
https://github.com/kubernetes-sigs/krew/pulls?q=is%3Apr+author%3Azhengtianbao
- Issues created / responded
https://github.com/kubernetes-sigs/kubespray/issues?q=is%3Aissue+author%3Azhengtianbao
https://github.com/kubernetes/ingress-nginx/issues?q=is%3Aissue+author%3Azhengtianbao
- SIGs involved with
kubernetes-sigs/kubespray
kubernetes-sigs/krew

**Comment by oomichi** [comment]
Thanks for your contributions.

+1 from me.

**Comment by cristicalin** [comment]
Great work and looking forward to more contributions!

+1 from me too.

**Comment by palnabarun** [comment]
@zhengtianbao -- Thank you for all your contributions so far!

I have filed PR #3146 to add you to the requested organisation. Once the PR gets merged, you will membership invite notifications!

Welcome! 🎉

**Comment by floryut** [comment]
No longer really needed but +1 

Thanks @zhengtianbao
