### ISSUE TITLE
REQUEST: New membership for lizhuqi

### ISSUE THREAD

**Issue by lizhuqi** [kubernetes/org#3145]
### GitHub Username

lizhuqi

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@andyzhangx

### Sponsor 2

@jingxu97

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/847
https://github.com/kubernetes/kubernetes/pull/104640
https://github.com/kubernetes/kubernetes/pull/104048
https://github.com/kubernetes/kubernetes/pull/103831
https://github.com/kubernetes/kubernetes/pull/96027
https://github.com/kubernetes/kubernetes/pull/94267
https://github.com/kubernetes/node-problem-detector/pull/596
https://github.com/kubernetes/test-infra/pull/24645
https://github.com/kubernetes/test-infra/pull/23724
https://github.com/kubernetes/test-infra/pull/23085

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/104131
https://github.com/kubernetes/community/issues/4961

- SIG projects I am involved with
sig windows
sig storoage

**Comment by andyzhangx** [comment]
+1

**Comment by jingxu97** [comment]
+1

**Comment by palnabarun** [comment]
@lizhuqi -- thank you for all your contributions so far :)

I've created PR #3167 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the Kubernetes community! :tada:

/assign
