### ISSUE TITLE
REQUEST: New membership for rmohr

### ISSUE THREAD

**Issue by rmohr** [kubernetes/org#3151]
### GitHub Username

@rmohr

### Organization you are requesting membership in

kubernetes-sigs, kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@cchengleo

### Sponsor 2

@agradouski

### List of contributions to the Kubernetes project

- Active maintainer and contributor to the KubeVirt CNCF project since its beginning (https://github.com/kubevirt/kubevirt/graphs/contributors)
- A few contributions to kubernetes/test-infra (https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+is%3Aclosed+author%3Armohr)
- A few minor contributions to  kubernetes/kubernetes: (https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aclosed+author%3Armohr)

I am helping out in the kubernetes-sigs/cluster-api-provider-kubevirt (https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pulls?q=is%3Apr+author%3Armohr+is%3Aclosed) project and @cchengleo and @agradouski are so kind to sponsor me.

**Comment by cchengleo** [comment]
@rmohr has actively contributed to cluster-api-provider-kubevirt since the beginning. We would definitely support his membership!

👍

**Comment by agradouski** [comment]
fully support @rmohr membership! great collaboration, and very insightful contributions!

**Comment by sttts** [comment]
+1 for Roman being an org member!

**Comment by alvaroaleman** [comment]
+1

**Comment by palnabarun** [comment]
@rmohr -- thank you for all your contributions so far :)

I've created PR #3167 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the Kubernetes community! :tada:

/assign
