### ISSUE TITLE
REQUEST: New membership for minbaev - Alexander Minbaev

### ISSUE THREAD

**Issue by minbaev** [kubernetes/org#3152]
### GitHub Username

@minbaev

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei 

### Sponsor 2

@ahg-g 

#### PRs authored

- https://github.com/kubernetes/kubernetes/pull/100026
- https://github.com/kubernetes/kubernetes/pull/100322
- https://github.com/kubernetes/kubernetes/pull/99844
- https://github.com/kubernetes/kubernetes/pull/99439
- https://github.com/kubernetes-sigs/cri-tools/pull/857

#### Issues responded to

- https://github.com/kubernetes/kubernetes/issues/94009
- https://github.com/kubernetes/kubernetes/issues/99966
- https://github.com/kubernetes/kubernetes/issues/98898
- https://github.com/kubernetes/kubernetes/issues/106765

#### SIG Projects I'm involved with

- Scheduling
- Autoscaling
- CRI tools

**Comment by ahg-g** [comment]
/lgtm

Thanks!

**Comment by Huang-Wei** [comment]
+1

**Comment by palnabarun** [comment]
@minbaev -- thank you for all your contributions so far :)

I've created PR #3167 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the Kubernetes community! :tada:

/assign
