### ISSUE TITLE
REQUEST: New membership for <@Garima-Negi>

### ISSUE THREAD

**Issue by Garima-Negi** [kubernetes/org#3154]
### GitHub Username

@Garima-Negi

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@anubha-v-ardhan

### Sponsor 2

@divya-mohan0209

### PRs I have reviewed and provided feedback on:
- [https://github.com/kubernetes/website/pull/30304](https://github.com/kubernetes/website/pull/30304)
- [https://github.com/kubernetes/website/pull/30183](https://github.com/kubernetes/website/pull/30183)
- [https://github.com/kubernetes/website/pull/29416](https://github.com/kubernetes/website/pull/29416)
- [https://github.com/kubernetes/website/pull/29968](https://github.com/kubernetes/website/pull/29968)
- [https://github.com/kubernetes/website/pull/30087](https://github.com/kubernetes/website/pull/30087)
- [https://github.com/kubernetes/website/pull/30627](https://github.com/kubernetes/website/pull/30627)
- [https://github.com/kubernetes/website/pull/30847](https://github.com/kubernetes/website/pull/30847)

### Issues I'm currently working on:
- [https://github.com/kubernetes/website/issues/31011](https://github.com/kubernetes/website/issues/31011)

### Issues resolved:
- kubernetes/dashboard : [https://github.com/kubernetes/website/issues/29917](https://github.com/kubernetes/website/issues/29917)
- resolved by PR [https://github.com/kubernetes/dashboard/pull/6615](https://github.com/kubernetes/dashboard/pull/6615)

### Community work:
-  Created a recurring meeting reminders Slack channel **#sig-contribex-meetings** to assist the team and reduce manual work

**Comment by divya-mohan0209** [comment]
+1 from my side. Thank you for all your contributions 🙌 Welcome to the community!

**Comment by anubha-v-ardhan** [comment]
+1, Thanks for the contributions

**Comment by palnabarun** [comment]
@Garima-Negi -- thank you for all your contributions so far and your help with the Hindi Localization efforts :)

I've created PR #3167 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the Kubernetes community! :tada:

/assign

**Comment by anubha-v-ardhan** [comment]
Welcome to Kubernetes @Garima-Negi 
/meow

**Comment by Garima-Negi** [comment]
> here

Thank you all for this opportunity!
