### ISSUE TITLE
REQUEST: New membership for Jont828

### ISSUE THREAD

**Issue by Jont828** [kubernetes/org#3156]
### GitHub Username

@Jont828

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@CecileRobertMichon

### Sponsor 2

@shysank

### List of contributions to the Kubernetes project

PRs authored:
- [Make inbound NAT rules reconcile/delete async](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1870)
- [Make load balancer reconcile/delete async](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1886)
- [Make subnets reconcile/delete async](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1914)
- [Make network interface reconcile/delete async](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1939)
- [Make bastion hosts reconcile/delete async](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1941)
- [Add async reconciler interface and refactor async service to get existing resources](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1874)
- [Make NAT gateway reconcile/delete async](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1865)
- [Make availability set reconcile/delete async](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1861)
- [Make virtual network peerings reconcile/delete async](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1838)
- [Make disks delete async](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1844)
- [Add support for peering cluster VNet to an existing VNe](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1694)
- [Cluster API GUI/data visualization tool (separate repo)](https://github.com/Jont828/capi-visualization)

Issues responded to:
- Issues tagged in each of the PRs above

SIGs involved in:
- Cluster API
- Cluster API Provider Azure

**Comment by shysank** [comment]
+1, Thanks for all your contributions to capi/capz!

**Comment by CecileRobertMichon** [comment]
Huge +1!!

Sorry for the late response here, I missed the notification while I was on vacation

**Comment by palnabarun** [comment]
@Jont828 -- thank you for all your contributions so far :)

I've created PR #3167 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the Kubernetes community! tada

/assign

**Comment by Jont828** [comment]
Sounds great, thanks everyone!
