### ISSUE TITLE
REQUEST: New membership for MartinForReal

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/org#3157]
### GitHub Username

@MartinForReal

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@feiskyer

### Sponsor 2

@randomvariable 

### List of contributions to the Kubernetes project

PRs reviewed / authored
- https://github.com/kubernetes-sigs/cloud-provider-azure/pull/954
- https://github.com/kubernetes-sigs/cloud-provider-azure/pull/950
- https://github.com/kubernetes-sigs/cloud-provider-azure/pull/930
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1648

Issues responded to:
- https://github.com/kubernetes-sigs/cluster-api/issues/2751
- https://github.com/kubernetes-sigs/metrics-server/issues/124

SIGs involved in:
Cluster API provider aws
Cloud Provider Azure

**Comment by MartinForReal** [comment]
@feiskyer @detiber Could you please sponsor my application? Thanks in advance!

**Comment by feiskyer** [comment]
Thanks for contributions.
+1 from me.

**Comment by randomvariable** [comment]
+1 from me!

**Comment by palnabarun** [comment]
@MartinForReal -- thank you for all your contributions so far :)

I've created PR #3167 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the Kubernetes community! :tada:

/assign
