### ISSUE TITLE
REQUEST: New membership for shuaijinchao

### ISSUE THREAD

**Issue by shuaijinchao** [kubernetes/org#3159]
### GitHub Username

@shuaijinchao

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tengqm

### Sponsor 2

@tao12345666333

##### PRs
- kubernetes/website#31151
- kubernetes/website#31150
- kubernetes/website#31149
- kubernetes/website#31148
- kubernetes/website#31147
- kubernetes/website#31135
- kubernetes/website#31134
- kubernetes/website#31133
- kubernetes/website#31136
- kubernetes/website#31137
- kubernetes/website#31111
- kubernetes/website#31130
- kubernetes/website#31095
- kubernetes/website#31092
- kubernetes/website#31084
- kubernetes/website#31096
- kubernetes/website#31129
- kubernetes/website#31128
- kubernetes/website#31082
- kubernetes/website#31119
- kubernetes/website#31116
- kubernetes/website#31099
- kubernetes/website#31117
- kubernetes/website#31115
- kubernetes/website#31073
- kubernetes/website#31106
- kubernetes/website#31098
- kubernetes/website#31097
- kubernetes/website#31094
- kubernetes/website#31083
- kubernetes/website#31074
- kubernetes/website#31071
- kubernetes/website#31027

##### PR Reviews
- kubernetes/website#31122
- kubernetes/website#31121
- kubernetes/website#31026
- kubernetes/website#31120
- kubernetes/website#30327
- kubernetes/website#31045

**Comment by tao12345666333** [comment]
Thanks for your contributions.

+1 from me.

**Comment by tengqm** [comment]
+1

**Comment by moonming** [comment]
+1

**Comment by palnabarun** [comment]
@shuaijinchao -- thank you for all your contributions so far :)

I've created PR #3167 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the Kubernetes community! :tada:

/assign
