### ISSUE TITLE
REQUEST: New membership for schrej

### ISSUE THREAD

**Issue by schrej** [kubernetes/org#3160]
### GitHub Username

@schrej

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@randomvariable 

### Sponsor 2

@enxebre

### List of contributions to the Kubernetes project

Relevant contributions:

- kubernetes-sigs/cluster-api#4568
- https://github.com/kubernetes-sigs/cluster-api/pull/5608
- https://github.com/kubernetes-sigs/cluster-api/pull/5528
- https://github.com/kubernetes-sigs/cluster-api/pull/5468
- https://github.com/kubernetes-sigs/cluster-api/pull/4944
- https://github.com/kubernetes-sigs/cluster-api/pull/4648
- kubernetes-sigs/cluster-api-provider-vsphere#1277
- kubernetes-sigs/cluster-api/pull/5212 (review)
- [WIP Proposal for CAPI IP Address Management Integration](https://docs.google.com/document/d/1hvirbdV_QTbKBMxgvX045OuV8_f-xZETuH6HENZ0uxQ/edit)

[all kubernetes-sigs contributions](https://github.com/search?q=org%3Akubernetes-sigs+involves%3Aschrej&type=Issues)
[all kubernetes contributions](https://github.com/pulls?q=involves%3Aschrej+archived%3Afalse+org%3Akubernetes+) (just for completeness)

**Comment by enxebre** [comment]
awesome! +1

**Comment by randomvariable** [comment]
Thanks for everything!
+1

**Comment by palnabarun** [comment]
@schrej -- thank you for all your contributions so far :)

I've created PR #3167 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the Kubernetes community! :tada:

/assign
