### ISSUE TITLE
REQUEST: New membership for klaases

### ISSUE THREAD

**Issue by klaases** [kubernetes/org#3162]
### GitHub Username

klaases

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

spowelljr

### Sponsor 2

afbjorklund

### List of contributions to the Kubernetes project

- PRs reviewed / authored
[CI: Print PR title from Go for Github Action.](https://github.com/kubernetes/minikube/pull/13222) minikube#13222
[Bump PreloadVersion via Makefile Script "update-preload-version"](https://github.com/kubernetes/minikube/pull/13217) minikube#13217
[Update triage docs for close with lack of info.](https://github.com/kubernetes/minikube/pull/13177) minikube#13177
[Bootloader ISO EFI Support ](https://github.com/kubernetes/minikube/pull/13123) minikube#13123
[Increase page size to 100 and omit "alpha"](https://github.com/kubernetes/minikube/pull/13119) minikube#13119
[Update containerd to v1.5.8](https://github.com/kubernetes/minikube/pull/13105) #13105
[Stop K8s if running, when '--no-kubernetes' flag used](https://github.com/kubernetes/minikube/pull/13072) #13072
[update cri-o from v1.22.0 to 1.22.1](https://github.com/kubernetes/minikube/pull/13059) minikube#13059

- Issues responded to
[--no-kubernetes fails if "kubernetes-version" defined in config](https://github.com/kubernetes/minikube/issues/12871) minikube#12871

- SIG projects I am involved with
sig-cluster-lifecycle/minikube

Template: #2403

**Comment by spowelljr** [comment]
I sponsor @klaases

**Comment by afbjorklund** [comment]
I sponsor @klaases

**Comment by palnabarun** [comment]
@klaases -- thank you for all your contributions so far :)

I've created PR #3167 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome to the Kubernetes community! :tada:

/assign
