### ISSUE TITLE
REQUEST: New membership for davidvossel

### ISSUE THREAD

**Issue by davidvossel** [kubernetes/org#3166]
### GitHub Username

@davidvossel

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@rmohr

### Sponsor 2

@agradouski

### List of contributions to the Kubernetes project

* Multiple contributions to the kubernetes-sigs/cluster-api-provider-kubevirt project (https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pulls?q=is%3Apr+is%3Aclosed+author%3Adavidvossel)
* Active maintainer and contributor to the KubeVirt CNCF project (https://github.com/kubevirt/kubevirt/graphs/contributors)

**Comment by agradouski** [comment]
strongly support @davidvossel 's membership. his contributions to cluster-api-provider-kubevirt project have been tremendous!

**Comment by palnabarun** [comment]
Hi @davidvossel 👋🏽, The [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require that the sponsors be from two different companies. Since @agradouski and @chhengleo both work at Apple, they can't both sponsor you at the same time.

Can you please add a sponsor who works at a company other than Apple?

/assign

**Comment by davidvossel** [comment]
@rmohr I'm adding you as a sponsor since we can't have two Apple folks as sponsors.

**Comment by rmohr** [comment]
+1. David dies high quality contributions to cluster-api-provider-kubevirt and KubeVirt.

**Comment by davidvossel** [comment]
> Can you please add a sponsor who works at a company other than Apple?

@palnabarun no problem, Roman stepped up. He works at Red Hat.

**Comment by mrbobbytables** [comment]
@davidvossel sponsors must be a r[eviewer or approver in an owners file](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements), neither @agradouski or @rmohr would be valid sponsors. Is there anyone else that could sponsor you?

**Comment by rmohr** [comment]
@mrbobbytables I am approver in the capk repository since a few days. Does that help?

**Comment by rmohr** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/6ec57de19dcaaf4f63649c365627d242d8beb22f/OWNERS#L6

**Comment by davidvossel** [comment]
> @davidvossel sponsors must be a reviewer or approver in an owners file, neither @agradouski or @rmohr would be valid sponsors. Is there anyone else that could sponsor you?

Both @agradouski  and @rmohr are approvers for the [capk project](https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/6ec57de19dcaaf4f63649c365627d242d8beb22f/OWNERS#L6). Does that satisfy the requirements?

**Comment by mrbobbytables** [comment]
@davidvossel  @rmohr - hm...[hound](https://cs.k8s.io) isn't indexing that one, I raised an issue with k8s infra about it. Sorry about that.

We can proceed 👍

**Comment by mrbobbytables** [comment]
Welcome to kubernetes! 🎉

I've created PR #3223  to add you to the Kubernetes project. Once that gets merged, you should get a membership invite notification.
