### ISSUE TITLE
REQUEST: New membership for csantanapr

### ISSUE THREAD

**Issue by csantanapr** [kubernetes/org#3168]
### GitHub Username

csantanapr

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

AuraSinis

### Sponsor 2

JamesLaverack

### List of contributions to the Kubernetes project

I’m a release team shadow for v1.24

- https://github.com/kubernetes/website/pull/27871
- https://github.com/kubernetes/website/issues/13948
- https://github.com/kubernetes/minikube/pull/12709
- https://github.com/kubernetes/sig-release/pull/1808
- https://github.com/kubernetes/sig-release/pull/1809
- Hosted hallway track for virtual kubeconNA2021

**Comment by JamesLaverack** [comment]
+1

Carlos is a release notes shadow on the [Kubernetes v1.24 release team](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.24/release-team.md).

Welcome to the community. 🎉

**Comment by AuraSinis** [comment]
+1

**Comment by palnabarun** [comment]
@csantanapr -- Welcome to Kubernetes Release Team! 🎉 

I've created PR #3200 to add you to the requested org(s). Once that gets merged, you will receive membership invites.

Welcome!

/assign
