### ISSUE TITLE
Delete `github.com/kubernetes-csi/csi-driver-cinder` repo

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/org#317]
### Repository to archive
`github.com/kubernetes-csi/csi-driver-cinder`

### Repository and/or sig subproject owners that are approving this archival
/sig storage

### When should this be done
Anytime

### Additional context for request

This repo was created as part of https://github.com/kubernetes/org/issues/92.

However, SIG storage ended up never using it because Openstack folks who own and maintain Cinder already have a repo: https://github.com/kubernetes/cloud-provider-openstack/tree/master/pkg/csi/cinder.

So no need to "archive" `github.com/kubernetes-csi/csi-driver-cinder` -- just delete it.

/area github-repo

**Comment by cblecker** [comment]
Done
