### ISSUE TITLE
REQUEST: New membership for Lp-Francois

### ISSUE THREAD

**Issue by Lp-Francois** [kubernetes/org#3173]
### GitHub Username

@Lp-Francois

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@AuraSinis

### Sponsor 2

@JamesLaverack

### List of contributions to the Kubernetes project

- SIG projects I am involved with: sig-release
- I will be working in the Kubernetes Release Team as a [Release Notes shadow](https://github.com/kubernetes/sig-release/pull/1806) for v1.24
- https://github.com/kubernetes/website/pull/28047

**Comment by JamesLaverack** [comment]
+1

**Comment by AuraSinis** [comment]
+1

**Comment by palnabarun** [comment]
@Lp-Francois -- Welcome to Kubernetes Release Team! 🎉 

I've created PR #3200 to add you to the requested org(s). Once that gets merged, you will receive membership invites.

Welcome!

/assign
