### ISSUE TITLE
REQUEST: New membership for shuheiktgw

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/org#3175]
### GitHub Username

@shuheiktgw

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@leonardpahlke

### Sponsor 2

@JamesLaverack

### List of contributions to the Kubernetes project

SIG projects @shuheiktgw involved with: sig-release
@shuheiktgw is CI SIgnal Shadow for 1.24 

---

also see [PR comment](https://github.com/kubernetes/release/pull/2382#issuecomment-1010773391)

**Comment by JamesLaverack** [comment]
+1

**Comment by puerco** [comment]
+1 @shuheiktgw is a member of the 1.24 release team.

**Comment by shuheiktgw** [comment]
Should I create a PR like this https://github.com/kubernetes/org/pull/3172 myself?

**Comment by palnabarun** [comment]
@shuheiktgw -- Welcome to Kubernetes Release Team! 🎉 

I've created PR #3200 to add you to the requested org(s). Once that gets merged, you will receive membership invites.

Welcome!

/assign

**Comment by shuheiktgw** [comment]
Thanks, @palnabarun! I'm excited to be part of the team 👍
