### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/prow

### ISSUE THREAD

**Issue by listx** [kubernetes/org#3177]
### Repository

kubernetes-sigs/prow

### Project domain

docs.prow.k8s.io

### Additional context for request

- https://github.com/kubernetes/test-infra/issues/24821
- https://docs.google.com/document/d/17_gyhQipmK_roYqUtwx-hTwi1tn2sd0aG6vdkBn6fKM/edit?usp=sharing

**Comment by ameukam** [comment]
/sig testing
/area prow

cc @mrbobbytables @cblecker

**Comment by mrbobbytables** [comment]
@listx can you add a netlify.toml to the root of the repo first and open up the DNS request? You can find more info on whats needed here: https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md#requesting-a-netlify-site

**Comment by listx** [comment]
> @listx can you add a netlify.toml to the root of the repo first and open up the DNS request? You can find more info on whats needed here: https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md#requesting-a-netlify-site

Thanks for the pointers! I created https://github.com/kubernetes/test-infra/pull/25042 for the `netlify.toml` and https://github.com/kubernetes/k8s.io/issues/3315 for the DNS update request.

**Comment by mrbobbytables** [comment]
Netlify is setup - but currently throws errors when building since the site contents do not exist yet.
https://app.netlify.com/sites/kubernetes-prow/deploys/61f7ec64bf4b25c69f6a9b41

The domain portion will have to wait till k8s.io is updated.

**Comment by ameukam** [comment]
@mrbobbytables Is it possible to override Netlify tests https://github.com/kubernetes/test-infra/pull/24980#issuecomment-1026324015 ?

**Comment by mrbobbytables** [comment]
@ameukam netlify tests aren't actually required status checks, but they should be configured in prow tobe ignored for the test-infra repo. I've disabled all builds for k/test-infra for now.

**Comment by BenTheElder** [comment]
https://groups.google.com/d/msgid/kubernetes-sig-testing/CAPgXYS6Gs6JGz%2BQt%3D%2B86XB1FNGx4quFtcgSaJnCjnBJ_DxTKNQ%40mail.gmail.com?utm_medium=email&utm_source=footer 

can we halt this and enable it on the soon to be requested dedicated repo?

**Comment by listx** [comment]
Let's wait for https://github.com/kubernetes/org/issues/3228 to resolve first (thanks @BenTheElder for the assist).

**Comment by listx** [comment]
@mrbobbytables Can you re-do the Netlify setup to point to the newly created https://github.com/kubernetes-sigs/prow repo, instead of the old https://github.com/kubernetes/test-infra one?

**Comment by listx** [comment]
The Netlify setup has been completed! (Thanks to @mrbobbytables !)

Unfortunately the build is broken, and I hope to address that in https://github.com/kubernetes-sigs/prow/pull/3.

**Comment by listx** [comment]
@mrbobbytables can you confirm that k8s-prow.netlify.app is the domain? (or, if not, switch to to it?) Currently I see in the preview URL link https://deploy-preview-3--kubernetes-prow.netlify.app/ that the name seems to be set to "kubernetes-prow.netlify.app", which is not what we want (we already have a [DNS entry to reroute docs.prow.k8s.io to point to k8s-prow.netlify.app](https://github.com/kubernetes/k8s.io/blob/ab42d92ce9acc9ba18ec33cea7c0c1ee6e6d6587/dns/zone-configs/k8s.io._0_base.yaml#L285-L287)).

**Comment by mrbobbytables** [comment]
Ahh, sorry about that - I've changed it in netlify 👍 It might take a little bit for it to take effect.

**Comment by mrbobbytables** [comment]
@listx looks like its now updated, https://deploy-preview-3--k8s-prow.netlify.app/ works

**Comment by listx** [comment]
Thanks!

The only issue appears to be that Netlify is trying to find the `index.html` file from the root of the repo, instead of under `site/public`. For example, this link https://k8s-prow.netlify.app/OWNERS shows that the [OWNERS file from the root of the repo](https://github.com/kubernetes-sigs/prow/blob/main/OWNERS) is reachable from the root of the site. Is this something you need to fix on your end or something I can fix? The netlify.toml we're using is [here](https://github.com/kubernetes-sigs/prow/blob/main/netlify.toml).

**Comment by mrbobbytables** [comment]
Okay, sorted it out - the config in there still had build root manually configured from when it was in k/test-infra. I tested a build and things look okay:
https://app.netlify.com/sites/k8s-prow/deploys/621f79cc9c3c9e109cdc2ba2

**Comment by listx** [comment]
Awesome, thanks again! One last question: AFAICS the DNS settings are correct [from the k8s.io side](https://github.com/kubernetes/k8s.io/blob/ab42d92ce9acc9ba18ec33cea7c0c1ee6e6d6587/dns/zone-configs/k8s.io._0_base.yaml#L285-L287), and we also refer to the k8s.io domain URL from our [netlify.toml](https://github.com/kubernetes-sigs/prow/blob/6dc36085fc21a3d3e954782d267ba8c9ab6a0591/netlify.toml#L11). Is there anything I'm missing to make docs.prow.k8s.io work?

**Comment by listx** [comment]
Update: @mrbobbytables fixed the DNS settings from the Netlify side, so now the DNS redirect is working correctly!
