### ISSUE TITLE
REQUEST: New membership for ptux

### ISSUE THREAD

**Issue by ptux** [kubernetes/org#3178]
### GitHub Username

ptux

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@inductor

### Sponsor 2

@jihoon-seo

### List of contributions to the Kubernetes project

https://github.com/kubernetes/website/commits/main?author=ptux

**Comment by ptux** [comment]
@jihoon-seo

I had your consent here.
https://github.com/kubernetes/website/pull/30338#issuecomment-981287600

**Comment by inductor** [comment]
+1

**Comment by palnabarun** [comment]
@ptux -- thank you for all your contributions so far :)

I've created PR #3200 to add you to the org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
