### ISSUE TITLE
REQUEST: New membership for @s04

### ISSUE THREAD

**Issue by s04** [kubernetes/org#3180]
### GitHub Username

@s04

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mickeyboxell

### Sponsor 2

@james.laverack

### List of contributions to the Kubernetes project

- Joined Comms Release Team Shadow 1.24
- Employee at company with multiple release team leads and shadows
- No tangible contributions yet

**Comment by mickeyboxell** [comment]
+1

**Comment by palnabarun** [comment]
+1 from my side as well.

**Comment by palnabarun** [comment]
@s04-- Welcome to Kubernetes Release Team! 🎉 

I've created PR #3200 to add you to the requested org(s). Once that gets merged, you will receive membership invites.

Welcome!

/assign
