### ISSUE TITLE
REQUEST: New membership for necatican

### ISSUE THREAD

**Issue by necatican** [kubernetes/org#3183]
### GitHub Username

necatican

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@floryut

### Sponsor 2

@cristicalin

### List of contributions to the Kubernetes project

* [Download crun using download_file.yml](https://github.com/kubernetes-sigs/kubespray/pull/7370)
* [Add identity_allocation_mode support for Cilium](https://github.com/kubernetes-sigs/kubespray/pull/8430)
* [Add kubeadm option to etcd_deployment_type to replace the etcd_kubeadm_enabled variable](https://github.com/kubernetes-sigs/kubespray/pull/8317)
* [Upgrade Cilium to 1.11.0](https://github.com/kubernetes-sigs/kubespray/pull/8354)
* [Add documentation for audit webhook variables](https://github.com/kubernetes-sigs/kubespray/pull/7434)
* [Crun v0.19 support](https://github.com/kubernetes-sigs/kubespray/pull/7433)
* [Add kubeadm_join_phases_skip variable](https://github.com/kubernetes-sigs/kubespray/pull/8067)

**Comment by cristicalin** [comment]
:+1:

@necatican great to see your enthusiasm and looking forward to your future contributions

**Comment by floryut** [comment]
👍 

Lots of useful contribs 🙇

**Comment by palnabarun** [comment]
@necatican -- thank you for all your contributions so far :)

I've created PR #3200 to add you to the org. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
