### ISSUE TITLE
REQUEST: New membership for rtsp

### ISSUE THREAD

**Issue by rtsp** [kubernetes/org#3185]
### GitHub Username

@rtsp

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@floryut

### Sponsor 2

@cristicalin

### List of contributions to the Kubernetes project

- kubernetes-sigs/kubespray#7842
- kubernetes-sigs/kubespray#7850
- kubernetes-sigs/kubespray#7853
- kubernetes-sigs/kubespray#7877
- kubernetes-sigs/kubespray#7888
- kubernetes-sigs/kubespray#7964
- kubernetes-sigs/kubespray#8011
- kubernetes-sigs/kubespray#8036
- kubernetes-sigs/kubespray#8064
- kubernetes-sigs/kubespray#8386
- kubernetes-sigs/kubespray#8393
- kubernetes-sigs/kubespray#8404
- kubernetes-sigs/kubespray#8424
- kubernetes-sigs/kubespray#8433

**Comment by cristicalin** [comment]
:+1: 

Thanks for a great set of contributions so far @rtsp, looking forward to the next ones!

**Comment by floryut** [comment]
👍 

Of course man! my pleasure, thank you for your work.

**Comment by palnabarun** [comment]
@rtsp -- thank you for all your contributions so far :)

I've created PR #3200 to add you to the org. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
