### ISSUE TITLE
REQUEST: New membership for DiptoChakrabarty

### ISSUE THREAD

**Issue by DiptoChakrabarty** [kubernetes/org#3187]
### GitHub Username

DiptoChakrabarty

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jyotimahapatra

### Sponsor 2

@JamesLaverack

### List of contributions to the Kubernetes project

Member of Bug Triage Shadow team for kubernetes release 1.24
Contributions in kubernetes sigs [cluster-api(here)](https://github.com/kubernetes-sigs/cluster-api/commits?author=DiptoChakrabarty) project
Contribution in [kubernetes(here)](https://github.com/kubernetes/kubernetes/pull/105726) project
Other PRs are ongoing in [kustomize(here)](https://github.com/kubernetes-sigs/kustomize/pull/4364) , [node-feature-discovery(here)](https://github.com/kubernetes-sigs/node-feature-discovery/pull/711) , [cluster-api(here)](https://github.com/kubernetes-sigs/cluster-api/pulls/DiptoChakrabarty)

**Comment by jyotimahapatra** [comment]
+1 Welcome to the  team

**Comment by palnabarun** [comment]
+1 from me as well. Welcome to the team!

**Comment by palnabarun** [comment]
@DiptoChakrabarty -- I've created PR #3200 to add you to the requested org(s). Once that gets merged, you will receive membership invites.

Welcome!

/assign
