### ISSUE TITLE
REQUEST: New membership for chriskim06

### ISSUE THREAD

**Issue by chriskim06** [kubernetes/org#3188]
### GitHub Username

@chriskim06

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kubernetes-sigs

### Sponsor 2

@kubernetes-sigs

### List of contributions to the Kubernetes project

I'm a kubernetes-sigs member and [Krew](https://github.com/kubernetes-sigs/krew/) maintainer. I saw [in this comment](https://github.com/kubernetes-sigs/krew/) that membership is equivalent now and that we should just fill out this form to request membership in other orgs.

**Comment by palnabarun** [comment]
Should be fixed in #3200 :)

/assign
