### ISSUE TITLE
REQUEST: New membership for a7i

### ISSUE THREAD

**Issue by a7i** [kubernetes/org#3191]
### GitHub Username

a7i

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ingvagabund

### Sponsor 2

@damemi

### List of contributions to the Kubernetes project

- Sig Projects: https://github.com/kubernetes-sigs/descheduler
- PR: https://github.com/kubernetes-sigs/descheduler/pulls?q=is%3Apr+author%3Aa7i+
- Issues: https://github.com/kubernetes-sigs/descheduler/issues?q=is%3Aissue+author%3Aa7i+

**Comment by damemi** [comment]
+1
Thanks for all of your hard work!

**Comment by ingvagabund** [comment]
+1
Much appreciating all the effort

**Comment by ingvagabund** [comment]
From https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#slos:
```
The GitHub Administration Team will aim to handle requests in the following time frames:

Organization invites should be handled within one week of all requirements for membership being met (all +1s obtained).
...
If a request is taking longer than the above time frames, or there is a need to escalate an urgent request, please mention @kubernetes/owners on the associated issue for assistance.
```

@kubernetes/owners

**Comment by ingvagabund** [comment]
@mrbobbytables @damemi no longer works in RH. Would that help or is there some probation period for which a former RH employee is not allowed to +1 alongside another RH employee?

**Comment by mrbobbytables** [comment]
We usually use github profile and/or devstats to verify employer (both still say RedHat :x). No probation period needed, but would need some verification from @damemi about it.

**Comment by damemi** [comment]
Hi, so sorry to delay this, yes @ingvagabund is correct, I left Red Hat (and forgot to update my Github profile... whoops)

I have updated that now. As an aside, is there anything I need to do to update devstats too?

Let me know if there's anything else you need

**Comment by idvoretskyi** [comment]
@damemi yes, the process is described here - https://github.com/cncf/devstats#company-affiliations

**Comment by a7i** [comment]
Hello @idvoretskyi / @mrbobbytables  @damemi has updated his GitHub profile. Anything pending on my side? Thank you!
