### ISSUE TITLE
REQUEST: New membership for didicodes

### ISSUE THREAD

**Issue by didicodes** [kubernetes/org#3192]
### GitHub Username

@didicodes

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@nate-double-u

### Sponsor 2

@jrsapi

### List of contributions to the Kubernetes project

* I have made two contributions to the Kubernetes documentation. You can find them [here](https://github.com/kubernetes/website/pull/31028) and [here](https://github.com/kubernetes/website/pull/31034). 

* I am part of the KCD (Kubernetes Community Days) Africa core team - where we host events to help sensitize people in Africa about Kubernetes and Cloud Native technologies. We are currently making preparations for our event this year. 

* I recently got accepted into the Docs Shadow Release team and being added as a member of the org will give me access to the resources to perform my duties as a Docs Shadow Release member.

**Comment by nate-double-u** [comment]
👍
LGTM!

**Comment by palnabarun** [comment]
@didicodes -- Welcome to Kubernetes Release Team! 🎉 

I've created PR #3200 to add you to the requested org(s). Once that gets merged, you will receive membership invites.

Welcome!

/assign
