### ISSUE TITLE
REQUEST: New membership for juanfescobar

### ISSUE THREAD

**Issue by juanfescobar** [kubernetes/org#3193]
### GitHub Username

juanfescobar

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

BenTheElder

### Sponsor 2

puerco

### List of contributions to the Kubernetes project

* https://github.com/kubernetes/test-infra/pull/24913
* https://github.com/kubernetes/kubernetes/pull/103876

**Comment by BenTheElder** [comment]
cc @puerco 

thanks @juanfescobar for joining the deb / RPM oncall (https://go.k8s.io/oncall) :-)

**Comment by BenTheElder** [comment]
explicit +1 :-)

**Comment by puerco** [comment]
+1 welcome @juanfescobar ! Looking forward to working with you!

**Comment by palnabarun** [comment]
Thank you @juanfescobar for helping with the deb/RPM packaging! 🎉 

I've created PR #3200 to add you to the requested org(s). Once that gets merged, you will receive membership invites.

Welcome!

/assign

**Comment by BenTheElder** [comment]
thanks @palnabarun !

**Comment by juanfescobar** [comment]
Thank you @BenTheElder , @puerco, and @palnabarun !!
