### ISSUE TITLE
REQUEST: New membership for alexander-demichev

### ISSUE THREAD

**Issue by alexander-demichev** [kubernetes/org#3197]
### GitHub Username

alexander-demichev

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

-

### Sponsor 2

-

### List of contributions to the Kubernetes project

I'm already a member of kubernetes-sigs and would like to request membership in kubernetes as described here https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem the sponsors are not needed in this case.

**Comment by palnabarun** [comment]
should be fixed in #3200 :)

/assign
