### ISSUE TITLE
REQUEST: New membership for heybronson

### ISSUE THREAD

**Issue by heybronson** [kubernetes/org#3198]
### GitHub Username

@heybronson

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@olemarkus

### Sponsor 2

@hakman

### List of contributions to the Kubernetes project

- PR contributions to kubernetes/kops: https://github.com/kubernetes/kops/pulls?q=is%3Apr+author%3Aheybronson

**Comment by olemarkus** [comment]
@heybronson has contributed a number of PRs to the kops project and I am happy to sponsor the membership.
+1

**Comment by hakman** [comment]
+1 from me too :)

**Comment by palnabarun** [comment]
@heybronson -- thank you for all your contributions so far :)

I've created PR #3200 to add you to the orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
