### ISSUE TITLE
REQUEST: New membership for @tnir

### ISSUE THREAD

**Issue by tnir** [kubernetes/org#32]
### GitHub Username
@tnir

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah
- @xiangpengzhao

### List of contributions to the Kubernetes project
- PRs authored: https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Atnir+is%3Aclosed
- issues created: https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Atnir+is%3Aclosed; responded to: https://github.com/kubernetes/website/issues?q=mentions%3Atnir+is%3Aclosed+is%3Aissue
- SIG projects I am involved with
    - sig-docs (k/kubernetes-docs-ja)

**Comment by tnir** [comment]
@zacharysarah @xiangpengzhao Thanks for sponsoring.

**Comment by zacharysarah** [comment]
+1

**Comment by cblecker** [comment]
Invite sent! Welcome

/close
