### ISSUE TITLE
REQUEST: New membership for jayesh-srivastava

### ISSUE THREAD

**Issue by jayesh-srivastava** [kubernetes/org#3202]
### GitHub Username

@jayesh-srivastava

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@cpanato

### List of contributions to the Kubernetes project

- PRs authored
[kubernetes/kubernetes/pull/107603](https://github.com/kubernetes/kubernetes/pull/107603)
[kubernetes/website/pull/31272](https://github.com/kubernetes/website/pull/31272)
[kubernetes/minikube/pull/12381](https://github.com/kubernetes/minikube/pull/12381)

- PRs reviewed
[kubernetes/website/pull/31185](https://github.com/kubernetes/website/pull/31185)
[kubernetes/website/pull/30612](https://github.com/kubernetes/website/pull/30612)
[kubernetes/website/pull/30183](https://github.com/kubernetes/website/pull/30183)
[kubernetes/website/pull/31162](https://github.com/kubernetes/website/pull/31162)
[kubernetes/website/pull/29518](https://github.com/kubernetes/website/pull/29518)
[kubernetes/website/pull/29540](https://github.com/kubernetes/website/pull/29540)
[kubernetes/website/pull/29444](https://github.com/kubernetes/website/pull/29444)
[kubernetes/website/pull/31259](https://github.com/kubernetes/website/pull/31259)
[kubernetes/website/pull/31292](https://github.com/kubernetes/website/pull/31292)
[kubernetes/website/pull/29967](https://github.com/kubernetes/website/pull/29967)

- SIG projects I'm involved with
[kubernetes-sigs/cluster-api-provider-gcp](https://github.com/kubernetes-sigs/cluster-api-provider-gcp)
[kubernetes-sigs/cluster-api](https://github.com/kubernetes-sigs/cluster-api)
[kubernetes-sigs/cluster-api-provider-kubevirt](https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt)

- Other areas I'm involved in
[kubernetes/community/issues/4469](https://github.com/kubernetes/community/issues/4469)("Meet our contributors" blog series for APAC region)

**Comment by cpanato** [comment]
+1

**Comment by dims** [comment]
+1

**Comment by mrbobbytables** [comment]
I've created PR #3223  to add you to the Kubernetes project. Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
