### ISSUE TITLE
REQUEST: New membership for zmalik

### ISSUE THREAD

**Issue by zmalik** [kubernetes/org#3203]
### GitHub Username

@zmalik

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@CecileRobertMichon

### Sponsor 2

@shysank

### List of contributions to the Kubernetes project

PRs reviewed / authored:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1815
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1896
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1945
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1971
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1984

Issues responded to:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1965
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1979
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1981
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1937

SIGS projects I am involved with:
- cluster-api-provider-azure

**Comment by shysank** [comment]
+1, Thanks for all the contributions!

**Comment by CecileRobertMichon** [comment]
+1 👏

**Comment by mrbobbytables** [comment]
I've created PR #3223  to add you to the Kubernetes project. Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
