### ISSUE TITLE
REQUEST: New membership for XudongLiuHarold

### ISSUE THREAD

**Issue by XudongLiuHarold** [kubernetes/org#3207]
### GitHub Username

@XudongLiuHarold

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@lubronzhan

### Sponsor 2

@andrewsykim

### List of contributions to the Kubernetes project

- PR authored:
    - https://github.com/kubernetes/kubernetes/pull/98277
    - https://github.com/kubernetes/kubernetes/pull/103129
    - https://github.com/kubernetes/kubernetes/pull/103273
    - https://github.com/kubernetes/enhancements/pull/2698
    - https://github.com/kubernetes/website/pull/27092
    - https://github.com/kubernetes/website/pull/28051
    - https://github.com/kubernetes/cloud-provider-vsphere/pull/569
   
- Issues opened:
    - https://github.com/kubernetes/kubernetes/issues/99828

I will be actively working and maintaining cloud-provider-vsphere.

**Comment by XudongLiuHarold** [comment]
also cc: @andrewsykim @nicolehanjing as well

**Comment by HanFa** [comment]
+1, kudos! Thanks for all your contributions!

**Comment by andrewsykim** [comment]
+1 thanks @XudongLiuHarold for your work so far!

**Comment by lubronzhan** [comment]
+ Thanks Xudong!

**Comment by mrbobbytables** [comment]
I've created PR #3223  to add you to the Kubernetes project. Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
