### ISSUE TITLE
REQUEST: migrate github.com/dims/maintainers

### ISSUE THREAD

**Issue by dims** [kubernetes/org#3208]
### New repo, staging repo, or migrate existing

migrate dims/maintainers to kubernetes-sigs/maintainers

### Is it a staging repo?

no

### Requested name for new repository

maintainers

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

dims, nikhita

### Who should have write access?

dims, nikhita, MadhavJivrajani, palnabarun, mrbobbytables

### Who should be listed as approvers in OWNERS?

dims, nikhita, MadhavJivrajani, palnabarun, mrbobbytables

### Who should be listed in SECURITY_CONTACTS?

dims, nikhita

### What should the repo description be?

Tools and utilities to parse OWNERS, OWNER_ALIASES in kubernetes related github orgs

### What SIG and subproject does this fall under?

contributor-experience

### Please provide references to appropriate approval for this new repo

This repository was created to help with auditing / cleaning up etc of OWNERS files during annual reviews.

- https://kubernetes.slack.com/archives/D7HJ6KZJN/p1640054607000700
- https://kubernetes.slack.com/archives/CD6LAC15M/p1639578327074300
- https://kubernetes.slack.com/archives/C1TU9EB9S/p1637062642173400

cc @mrbobbytables @alisondy

**Comment by palnabarun** [comment]
xref: https://github.com/dims/maintainers/pull/3 for adding the remaining boilerplate

**Comment by palnabarun** [comment]
/assign
(taking up some of the tasks)

**Comment by justaugustus** [comment]
Huge +1 to this!
Also, happy to help do reviews/approvals here!

**Comment by mrbobbytables** [comment]
LGTM from me, but technically needs approval from our TLs before adopting a subproject. @nikhita has acked, but would like @cblecker to lgtm as well 👍 
/assign @cblecker

**Comment by cblecker** [comment]
Tool is great. The repo name... not so much. "maintainers" is extremely generic. Any suggestions if we can make this more specific? Or does anyone disagree with me?

**Comment by justaugustus** [comment]
> Tool is great. The repo name... not so much. "maintainers" is extremely generic. Any suggestions if we can make this more specific? Or does anyone disagree with me?

Same vibes over here!
I mentioned to @dims when he first unveiled it and he suggested we take the bikeshed as a post-migration step :)

**Comment by dims** [comment]
+1 to bikeshed a name :)

**Comment by cblecker** [comment]
We usually don't bikeshed repo names *after* migrating a repo in though. It's usually a step during this exact process to do any bike shedding.

**Comment by nikhita** [comment]
Maybe `maintainer-stats` similar to devstats? 🤔

**Comment by mrbobbytables** [comment]
FYI - accidentally referenced this issue in 3223, it is not related to org membership requests. XD

**Comment by richardgreg** [comment]
Hi all, I'm an applicant for the Linux Foundation Mentorship program, and I am interested in working on the project. I'm in the process of completing the initial task. Please let me know if there's anything else I have to do. Thank you.

**Comment by nikhita** [comment]
Would really like to move ahead with this, and I'm okay with `maintainers` for the repo name tbh.

@cblecker do you still have concerns and/or do you have ideas for the rename?

**Comment by justaugustus** [comment]
+1 to moving along. Bikeshed seems unnecessary here.

**Comment by dims** [comment]
+1 to move ahead

**Comment by cblecker** [comment]
sounds like there is consensus to move ahead with the name as is.

lgtm from me

**Comment by nikhita** [comment]
/assign

will help move this ahead

**Comment by nikhita** [comment]
Repo has been migrated - https://github.com/kubernetes-sigs/maintainers

Also created:
- https://github.com/kubernetes/org/pull/3300 - to create GitHub teams to grant access
- https://github.com/kubernetes/community/pull/6514 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.
