### ISSUE TITLE
New staging repo for CSI Migration/Translation library

### ISSUE THREAD

**Issue by ddebroy** [kubernetes/org#321]
### New Repo, Staging Repo, or migrate existing

Staging Repo for CSI Migration/Translation library

### Requested name for new repository
github.com/kubernetes/csi-translation-lib

### Which Organization should it reside
kubernetes

### If not a staging repo, who should have admin access
none: staging repo

### If not a staging repo, who should have write access
none: staging repo

### If a new repo, who should be listed as approvers in OWNERS
@davidz627 @ddebroy @leakingtapan @saad-ali @msau42 

### If a new repo, who should be listed in SECURITY_CONTACTS
@davidz627 @ddebroy @leakingtapan @saad-ali @msau42 

### What should the repo description be
Staging repo for CSI Migration/Translation libraries

### What SIG and subproject does this fall under in sigs.yaml
sig-storage

### Approvals
In progress: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/kubernetes-sig-architecture/yYcSj75gaGo

/area github-repo

**Comment by saad-ali** [comment]
`github.com/kubernetes/csi-translation-lib` SGTM from SIG Storage side. The translation library will be added to `kubernetes/stagaing` and automatically published to this new repo.

**Comment by saad-ali** [comment]
@cblecker or @spiffxp can you help with this.

**Comment by cblecker** [comment]
Core repos require sig-arch approval first

**Comment by saad-ali** [comment]
Ack. @ddebroy or @davidz627, could you start a thread with SIG Arch explaining why it is necessary and add it to their next meeting agenda if needed.

**Comment by ddebroy** [comment]
Thread already started with SIG Arch: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/kubernetes-sig-architecture/yYcSj75gaGo 

I will add it to their meeting agenda as well.

**Comment by ddebroy** [comment]
@cblecker, @spiffxp the repo request has been approved in SIG-arch here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/kubernetes-sig-architecture/7LqAhO_RPaI

**Comment by cblecker** [comment]
Repo is created.

Next steps:
- Add repo and staging dir to sigs.yaml (@ddebroy)
- Merge the code into k/k that you need under `staging/src/k8s.io/csi-translation-lib` (@ddebroy)
- Request to have the staging bot set up to publish into this new repo (@sttts or @nikhita can help with that)

**Comment by ddebroy** [comment]
Thanks a lot @cblecker. On to the next steps ...

**Comment by nikhita** [comment]
@ddebroy Just wanted to give an update that I'll take care of this from the publishing-bot side once https://github.com/kubernetes/kubernetes/pull/72770 gets merged :)

**Comment by cblecker** [comment]
@ddebroy @nikhita Are we good to go now?

**Comment by nikhita** [comment]
Yes, this is done now.

/close
