### ISSUE TITLE
REQUEST: New membership for krvaibhaw

### ISSUE THREAD

**Issue by krvaibhaw** [kubernetes/org#3210]
### GitHub Username

krvaibhaw

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Potapy4

### Sponsor 2

@jihoon-seo

### List of contributions to the Kubernetes project

Pull Request : 

- https://github.com/kubernetes/website/pull/31482
- https://github.com/kubernetes/website/pull/31385
- https://github.com/kubernetes/website/pull/31339
- https://github.com/kubernetes/website/pull/31317
- https://github.com/kubernetes/website/pull/28793

Review : 

- https://github.com/kubernetes/website/issues/31400
- https://github.com/kubernetes/website/issues/31384

**Comment by Potapy4** [comment]
+1

**Comment by jihoon-seo** [comment]
+1 :)

**Comment by mrbobbytables** [comment]
I've created PR #3223  to add you to the Kubernetes project. Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
