### ISSUE TITLE
REQUEST: Migrate github.com/relengfam/peribolos

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#3211]
### New repo, staging repo, or migrate existing

https://github.com/relengfam/peribolos

### Is it a staging repo?

no

### Requested name for new repository

https://github.com/kubernetes-sigs/peribolos

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@justaugustus + https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/OWNERS + https://github.com/kubernetes/org/blob/main/OWNERS

### Who should have write access?

@justaugustus + https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/OWNERS + https://github.com/kubernetes/org/blob/main/OWNERS

### Who should be listed as approvers in OWNERS?

@justaugustus + https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/OWNERS + https://github.com/kubernetes/org/blob/main/OWNERS

### Who should be listed in SECURITY_CONTACTS?

@justaugustus + https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/OWNERS + https://github.com/kubernetes/org/blob/main/OWNERS

### What should the repo description be?

Peribolos allows the org settings, teams and memberships to be declared in a yaml file. GitHub is then updated to match the declared configuration.

### What SIG and subproject does this fall under?

SIG ContribEx / GitHub Administration

### Please provide references to appropriate approval for this new repo

I'm opening this issue to start the discussion.
In the course of my other duties, I need to manage several non-Kubernetes orgs and I feel that `peribolos` is one of the most useful tools to do so.

That said, in it's current state, it's tricky to use outside of Kubernetes, so I forked it to start marrying the various components together and make it packagable.

Ideal end state:
- versioned, distributable (say via container image)
- GitHub Action/App to make this plug-and-play for other orgs (via https://github.com/sethvargo/go-githubactions)

I've mentioned this tool elsewhere (internally and TODO Group), so it would be cool to make this usable. (ref: https://github.com/todogroup/governance/issues/106#issuecomment-1000962064)

cc: @kubernetes/sig-contributor-experience-leads @kubernetes/owners

**Comment by mrbobbytables** [comment]
Just to keep sig-testing in the loop as well:
cc @spiffxp @BenTheElder @stevekuznetsov @alvaroaleman @cjwagner 

/assign @cblecker @nikhita 
For sign off from contribex TLs

**Comment by justaugustus** [comment]
> Just to keep sig-testing in the loop as well

Thanks for tagging @kubernetes/sig-testing! Meant to include them in the original text!

**Comment by alvaroaleman** [comment]
First time I see relengfam/peribolos. Do I understand it correctly that the goal of that is to move peribolos out of the test-infra repo into its own, dedicated repo?

Not formally an approver (we might want to change that), but cc @petr-muller

**Comment by cblecker** [comment]
Yeah, same questions as @alvaroaleman.. is there a reason we would maintain a fork of our own project? It's already delivered as a container image.

**Comment by justaugustus** [comment]
> First time I see relengfam/peribolos. Do I understand it correctly that the goal of this is to move peribolos out of the test-infra repo into its own, dedicated repo? Or is it supposed to remain a fork?

> Yeah, same questions as @alvaroaleman.. is there a reason we would maintain a fork of our own project?

@alvaroaleman @cblecker -- It would be to migrate peribolos to a dedicated repo to be managed, not fork it (the fork was just a intermediary step for me to hack on it for non-Kubernetes orgs).

> Not formally an approver (we might want to change that), but cc @petr-muller

@alvaroaleman -- FWIW, no one is an approver for `prow/cmd/peribolos`: https://github.com/kubernetes/test-infra/blob/4815ef39e507764a9b93bf1a2e390cf9273e78a3/prow/cmd/peribolos/OWNERS

It defers to Prow reviewers/approvers, which may or not be appropriate?
Is this really a Prow component?

> It's already delivered as a container image.

@cblecker -- This was maybe more ignorance on my part than an attempt to duplicate work 🙃 

Looking again, I see there is an image config.
...BUT, it's managed by bazel (which I'd prefer not to do): https://github.com/kubernetes/test-infra/blob/4815ef39e507764a9b93bf1a2e390cf9273e78a3/prow/cmd/peribolos/BUILD.bazel#L131-L138

Mentioned in the issue description, here's where I'm hoping to get to:

> That said, in it's current state, it's tricky to use outside of Kubernetes, so I forked it to start marrying the various components together and make it packagable.
> 
> Ideal end state:
> 
>     * versioned, distributable (say via container image)
> 
>     * GitHub Action/App to make this plug-and-play for other orgs (via https://github.com/sethvargo/go-githubactions)
> 
> 
> I've mentioned this tool elsewhere (internally and TODO Group), so it would be cool to make this usable. (ref: [todogroup/governance#106 (comment)](https://github.com/todogroup/governance/issues/106#issuecomment-1000962064))

**Comment by alvaroaleman** [comment]
> It defers to Prow reviewers/approvers, which may or not be appropriate?

Yes, the same group of ppl that maintains Prow also maintains Peribolos

> Is this really a Prow component?

Not a Prow component per se but developed as part of Prow.

> Looking again, I see there is an image config.
> ...BUT, it's managed by bazel (which I'd prefer not to do): https://github.com/kubernetes/test-> infra/blob/4815ef39e507764a9b93bf1a2e390cf9273e78a3/prow/cmd/peribolos/BUILD.bazel#L131-L138

Thanks to @chaodaiG we already do testing without bazel and there is a general consensus on wanting to get rid of Bazel. 

I guess in general I would like to see a case being made for moving it out (This doesn't mean I am opposed to the idea or anything, just that I would like to see a motivation for changing things). The changes you want to make to Peribolos can also be made while keeping it in test-infra, from what I can tell.

**Comment by BenTheElder** [comment]
Without commenting on the other details (too many threads, haven't digested this yet) -- the test-infra bazel removal part @chaodaiG is indeed actively making progress on with a little support from me since ~Q3? 2021, that is tracked in https://github.com/kubernetes/test-infra/issues/23796 and many sub issues. Python for example is fully migrated as of 5 days ago.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/23796 is complete, FWIW.
