### ISSUE TITLE
REQUEST: New membership for aartij17

### ISSUE THREAD

**Issue by aartij17** [kubernetes/org#3215]
### GitHub Username

aartij17

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@srm09

### Sponsor 2

@vrabbi

### List of contributions to the Kubernetes project

PRs reviewed / authored

- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1338
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1323
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1269
- https://github.com/kubernetes-sigs/cluster-api/pull/5969
- https://github.com/kubernetes-sigs/cluster-api/pull/5389
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1379

Issues authored/responded to

- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues?q=is%3Aissue+assignee%3AAartiJivrajani 
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1255
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1267 

SIG Projects I am involved with - 

- kubernetes-sigs/cluster-api-provider-vsphere
- kubernetes-sigs/cluster-api

**Comment by srm09** [comment]
Huge +1 from my side, thanks for all the great work in the CAPV community.

**Comment by vrabbi** [comment]
Huge +1!!

**Comment by mrbobbytables** [comment]
I've created PR #3223  to add you to the Kubernetes project. Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉

**Comment by MadhavJivrajani** [comment]
W00000t
/pony Twilight Sparkle
