### ISSUE TITLE
REQUEST: New membership for dharmjit

### ISSUE THREAD

**Issue by dharmjit** [kubernetes/org#3216]
### GitHub Username

@dharmjit

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@richardcase

### List of contributions to the Kubernetes project

- PRs authored
  - https://github.com/kubernetes-sigs/cluster-api/pull/5441
  - https://github.com/kubernetes-sigs/cluster-api/pull/5697
---
- Active issues assigned
  - https://github.com/kubernetes-sigs/cluster-api/issues/5357
---
- SIGs projects I’m involved with
  - https://github.com/kubernetes-sigs/cluster-api

**Comment by richardcase** [comment]
+1 from me

**Comment by anusha94** [comment]
+1 🚀

**Comment by sbueringer** [comment]
+1 Welcome! :)

**Comment by mrbobbytables** [comment]
I've created PR #3223  to add you to the Kubernetes project. Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
