### ISSUE TITLE
REQUEST: Migrate encodeflush/testgrid-json-exporter

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/org#3218]
### New repo, staging repo, or migrate existing

https://github.com/encodeflush/testgrid-json-exporter

### Is it a staging repo?

no

### Requested name for new repository

sigs.k8s.io/testgrid-json-exporter

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@sig-release-admins

### Who should have write access?

@sig-release-admins

### Who should be listed as approvers in OWNERS?

@sig-release-admins

### Who should be listed in SECURITY_CONTACTS?

@sig-release-admins

### What should the repo description be?

Kuberentes CI Signal Monitoring Dashboard

### What SIG and subproject does this fall under?

SIG Release

### Please provide references to appropriate approval for this new repo

The CI Signal Handbook already references the dashboard as a upocoming tool (see [handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/ci-signal#ci-signal-reporting-tool)).

A issue has been opened in november to move this project forward see [#3071](https://github.com/kubernetes/k8s.io/issues/3071)

The CI Signal Monitoring Dashboard has been under discussion since last release a few times (see [meeting notes](https://docs.google.com/document/d/16GqCjnEh86w8yADcrUylNoE1y1sqjIMYNC_gdk5WPSQ/edit#))

### Additional context for request

See [slack thread](https://kubernetes.slack.com/archives/C2C40FMNF/p1643221900124200) to discuss this PR

@encodeflush
@kubernetes/owners
cc cc: @kubernetes/sig-release-admins @kubernetes/release-engineering

**Comment by saschagrunert** [comment]
+1 from my side

**Comment by justaugustus** [comment]
+1 from me!

**Comment by mrbobbytables** [comment]
@encodeflush can you weigh in as the current owner of the repo? 

There are some changes that need to be merged before we it can be migrated, please see the requirements here: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

**Comment by leonardpahlke** [comment]
I have just added the template files from the [kubernetes-template-project](https://github.com/kubernetes/kubernetes-template-project).

**Comment by encodeflush** [comment]
@mrbobbytables @leonardpahlke 

AFAIC, the above mentioned git repository is following the rules for donated repositories:
- [X] All contributors must have signed the CNCF Individual CLA or CNCF Corporate CLA
- [X] If (a) contributor(s) have not signed the CLA and could not be reached, a NOTICE file should be added referencing section 7 of the CLA with a list of the developers who could not be reached
- [X] Licenses of dependencies are acceptable; project owners can ping @caniszczyk for review of third party deps
- [X] Boilerplate text across all files should attribute copyright as follows: "Copyright <Project Authors>" if no CLA was in place prior to donation
- [X] Additions of the standard Kubernetes header to code created by the contributors can occur post-transfer, but should ideally occur shortly thereafter.
- [X] Should contain template files as per the kubernetes-template-project.

Are we missing something?

**Comment by mrbobbytables** [comment]
@encodeflush - You should be good, I wanted your ack on the issue as we cannot transfer repos without the help of the actual owner of the repo.

**Comment by nikhita** [comment]
/assign

@encodeflush We need to move user-owned repos to a (dummy) org-owned repo to be able to migrate it over to another org. I have invited you to https://github.com/kubernetes-purgatory. Please migrate the repo to that org and I'll migrate it over to k-sigs. Please ping me directly on slack after you move the repo to purgatory.

**Comment by encodeflush** [comment]
The repo has been pushed to [kubernetes-purgatory/testgrid-json-exporter](https://github.com/kubernetes-purgatory/testgrid-json-exporter).

**Comment by leonardpahlke** [comment]
friendly ping @nikhita - The repo has been transferred to kubernetes-purgatory. Thank you!

**Comment by ameukam** [comment]
@leonardpahlke Transfer is done https://github.com/kubernetes-sigs/testgrid-json-exporter.

**Comment by leonardpahlke** [comment]
Thank you! 🙏

**Comment by leonardpahlke** [comment]
@ameukam I cannot fine the repo under https://github.com/kubernetes-sigs/testgrid-json-exporter

**Comment by ameukam** [comment]
> @ameukam I cannot fine the repo under [kubernetes-sigs/testgrid-json-exporter](https://github.com/kubernetes-sigs/testgrid-json-exporter)

@leonardpahlke should be ok now. Forgot to make it public and the transfer
