### ISSUE TITLE
Migrate platform9/cluster-api-provider-azure to kubernetes-sigs

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#322]
### New Repo, Staging Repo, or migrate existing
Migrate existing

### Requested name for new repository
`cluster-api-provider-azure`

### Which Organization should it reside
`kubernetes-sigs`

### If not a staging repo, who should have admin access
@justaugustus 

### If not a staging repo, who should have write access
I can set this up once we get migrated in.

### If a new repo, who should be listed as approvers in OWNERS
Added OWNERS here: https://github.com/platform9/cluster-api-provider-azure/pull/40

### If a new repo, who should be listed in SECURITY_CONTACTS
Added SECURITY_CONTACTS here: https://github.com/platform9/cluster-api-provider-azure/pull/40

### What should the repo description be
`Cluster API implementation for Azure`

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject for sig-azure called cluster-api-provider-azure

### Approvals
Self-approval as SIG Azure Chair.
Mailing list discussion: https://groups.google.com/d/topic/kubernetes-sig-azure/Fvud5JPUtg4/discussion

TODO:
Additional requirements documented here and in progress: https://docs.google.com/document/d/1ygKsgq7wwI01BKYVqFf1cmZ1svcPan1-ddjQTSqA3_A/edit?usp=sharing

### Additional context for request
- Slack channel created: #cluster-api-azure
- We had an initial meeting on 12/18, with [minutes](https://docs.google.com/document/d/1w0_7CIQXF5M8bnRLwfciALE1Glc9gc06xj7GUkH1b_c/edit?usp=sharing). Unfortunately, I was having trouble with Zoom, so we're unable to provide a recording
- Roadmap draft: https://docs.google.com/document/d/1GDkwmEpNaynfZFT4YIlsjRKKbeoAlz_su4JQOFP3QqQ/edit?usp=sharing
- Repo migration steps: https://docs.google.com/document/d/1ygKsgq7wwI01BKYVqFf1cmZ1svcPan1-ddjQTSqA3_A/edit?usp=sharing

/area github-repo

**Comment by justaugustus** [comment]
For approvals:
/assign @dstrebel @khenidak @feiskyer @timothysc @vannrt

**Comment by justaugustus** [comment]
For visibility:
/cc @detiber @soggiest @tariq1890 @marwanad @lachie83

**Comment by justaugustus** [comment]
For moving the GitHub bits:
/assign @cblecker @spiffxp

**Comment by justaugustus** [comment]
I've started a [mailing list topic with SIG Azure & Cluster Lifecycle](https://groups.google.com/d/topic/kubernetes-sig-azure/Fvud5JPUtg4/discussion), as well as noted in #sig-cluster-lifecycle and #cluster-api.

**Comment by feiskyer** [comment]
+1

**Comment by cblecker** [comment]
I've checked the CLAs, and there are two missing: @marwanad and @vannrt. Looking at the contributions, I'm not too concerned about @vannrt, but we need a CLA signed for @marwanad for sure.

**Comment by justaugustus** [comment]
@cblecker -- thanks for vetting that. I'll make sure the CLAs get signed!

**Comment by cblecker** [comment]
@justaugustus repo has been moved. some of the automation won't kick in for a few hours until the next cron run, but let me know if you run into any issues.

Can you also please add this to sigs.yaml now?

**Comment by justaugustus** [comment]
Thanks for migrating, @cblecker!
I've updated `sigs.yaml` here: https://github.com/kubernetes/community/pull/3077
