### ISSUE TITLE
REQUEST: New membership for jamiemonserrate

### ISSUE THREAD

**Issue by jamiemonserrate** [kubernetes/org#3220]
### GitHub Username

@jamiemonserrate

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@fabriziopandini 

### Sponsor 2

@richardcase

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/cluster-api/pull/4791/commits/d6b31bb877d37a629695af530d0c180348b0d2d6

The following commits are on the bringyourownhost repo. This isn't a part of the kubernetes-sigs though, but will soon be. 
- https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/commit/7d64fad54643785027a0de87ab6b564b9709c623
- https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/commit/44a0387c280e39921cc29637f6831f85d0401b4c
- https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/commit/b622ccc5870e6a49a79274414d586dca28385561

SIGs projects I’m involved with
https://github.com/kubernetes-sigs/cluster-api

**Comment by anusha94** [comment]
+1 🚀

**Comment by richardcase** [comment]
+1 :tada:   Yes please, love the BYOH provider

**Comment by richardcase** [comment]
Just to note that https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost is in the process of being donated to kubernetes-sigs

**Comment by mrbobbytables** [comment]
There needs to be contributions to the project before applying for org membership. Can you please link some?

Also both sponsors must be a reviewer/approver, @anusha94 is a member, not a reviewer/approver.^^;;

**Comment by jamiemonserrate** [comment]
@mrbobbytables - Thanks for reviewing this. I've updated the list with my contributions. And changed my sponsor as well. 

Thanks for your help!

**Comment by fabriziopandini** [comment]
+1
Looking forward for to see how the BYOH provider will grow given the initial wave interest this triggered in the community

**Comment by mrbobbytables** [comment]
Even though you plan to donate it to the Kubernetes project, the contributions don't really count until the project has officially been donated and under one of the kubernetes managed orgs.

I'd hold off on applying till then or focus a bit more on in-project things for a bit.^^:;;

**Comment by jamiemonserrate** [comment]
@mrbobbytables - That's fair. I will close this issue, and apply again later when I have more contributions. Thanks!
