### ISSUE TITLE
REQUEST: New membership for ardaguclu

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes/org#3222]
### GitHub Username

@ardaguclu

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1
@sttts 

### Sponsor 2
@apelisse 

### List of contributions to the Kubernetes project

https://github.com/pulls?q=is%3Apr+author%3Aardaguclu+archived%3Afalse+user%3Akubernetes+user%3Akubernetes-sigs+is%3Aclosed

**Comment by sttts** [comment]
+1

**Comment by apelisse** [comment]
+1!

**Comment by ardaguclu** [comment]
Thanks @sttts @apelisse

**Comment by palnabarun** [comment]
@ardaguclu -- thank you for all your contributions so far :)

I've created PR #3247 to add you to the requests org(s). Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign

**Comment by ardaguclu** [comment]
Thanks @palnabarun
