### ISSUE TITLE
REQUEST: New membership for erikgb

### ISSUE THREAD

**Issue by erikgb** [kubernetes/org#3225]
### GitHub Username

@erikgb

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@camilamacedo86

### Sponsor 2

@adrianludwin

### List of contributions to the Kubernetes project

[Merged pull requests as author](https://github.com/pulls?q=is%3Apr+author%3Aerikgb+archived%3Afalse+user%3Akubernetes+user%3Akubernetes-sigs+is%3Aclosed)

Also active in discussions on relevant issues, and on the K8s Slack channels.

Occasional reviews, but since my `/lgtm` does not "count" yet, I haven't been too active with reviews. Planning to do more reviews after my membership is (hopefully) accepted. 😊

**Comment by camilamacedo86** [comment]
+1 . 
/lgtm

**Comment by adrianludwin** [comment]
+1!

**Comment by palnabarun** [comment]
@erikgb -- thank you for all your contributions so far :)

I've created PR #3247 to add you to the requests org(s). Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
