### ISSUE TITLE
REQUEST: Create github repo for Prow docs

### ISSUE THREAD

**Issue by listx** [kubernetes/org#3228]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

prow

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

  - alvaroaleman
  - cblecker
  - cjwagner
  - fejta
  - stevekuznetsov
  - petr-muller

### Who should have write access?

  - alvaroaleman
  - cblecker
  - cjwagner
  - fejta
  - stevekuznetsov
  - petr-muller

### Who should be listed as approvers in OWNERS?

  - alvaroaleman
  - cblecker
  - cjwagner
  - fejta
  - stevekuznetsov
  - petr-muller

### Who should be listed in SECURITY_CONTACTS?

  - alvaroaleman
  - cblecker
  - cjwagner
  - fejta
  - stevekuznetsov
  - petr-muller

### What should the repo description be?

Statically generated docs for Prow (the tool that currently resides in [kubernetes/test-infra](https://github.com/kubernetes/test-infra/tree/master/prow)). For historical reasons Prow lives in kubernetes/test-infra along with other things, but this repo is **all about Prow**.

### What SIG and subproject does this fall under?

sig-testing -> prow

### Please provide references to appropriate approval for this new repo

[Approval email thread](https://groups.google.com/g/kubernetes-sig-testing/c/_kTpso2m6rI/m/10C3Fa_jAAAJ) from the SIG Testing mailing list (owner of Prow)

### Additional context for request

See https://github.com/kubernetes/test-infra/issues/24821 for the tracking issue and https://docs.google.com/document/d/17_gyhQipmK_roYqUtwx-hTwi1tn2sd0aG6vdkBn6fKM/edit?usp=sharing for the design doc (you must be a member of kubernetes-sig-testing@googlegroups.com to have access to the doc).

The reason why we request just `prow` for the repo name here is because that way we leave open the option of migrating the Prow codebase to this repo in the future (if that happens). No other repos named just `prow` exist in the Kubernetes community so this should be fine.

**Comment by BenTheElder** [comment]
+1

**Comment by cjwagner** [comment]
+1, but for all of the "Who" questions we should probably include the maintainers of Prow too rather than only Linus.
Maybe the OWNERS file [approvers](https://github.com/kubernetes/test-infra/blob/1256a81e66d64ace1cf50520e82510a3316319d6/prow/OWNERS#L4-L8)? (which should also [include Petr](https://github.com/kubernetes/test-infra/pull/25078))

**Comment by listx** [comment]
> +1, but for all of the "Who" questions we should probably include the maintainers of Prow too rather than only Linus. Maybe the OWNERS file [approvers](https://github.com/kubernetes/test-infra/blob/1256a81e66d64ace1cf50520e82510a3316319d6/prow/OWNERS#L4-L8)? (which should also [include Petr](https://github.com/kubernetes/test-infra/pull/25078))

Done (updated the responses in my first comment).

**Comment by nikhita** [comment]
/assign

Repo has been created - https://github.com/kubernetes-sigs/prow

Also created:
- https://github.com/kubernetes/org/pull/3237 - to add the GitHub team to grant access
- https://github.com/kubernetes/community/pull/6430 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.
