### ISSUE TITLE
REQUEST: New membership for amacaskill

### ISSUE THREAD

**Issue by amacaskill** [kubernetes/org#3231]
### GitHub Username

amacaskill

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mattcary

### Sponsor 2

@jsafrane

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/870
- https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/854
- https://github.com/kubernetes/kubernetes/pull/106322

**Comment by mattcary** [comment]
+1

**Comment by jsafrane** [comment]
+1

**Comment by jsafrane** [comment]
I knew this sounds familiar. Is it a dup of https://github.com/kubernetes/org/issues/3206 ?

**Comment by mattcary** [comment]
Ah, thank you. I couldn't remember the procedure here. So basically do
https://github.com/kubernetes/org/pull/3199?

**Comment by palnabarun** [comment]
@mattcary -- yes! You got that right. :)
