### ISSUE TITLE
New repo for kubernetes-incubator/external-storage/ceph

### ISSUE THREAD

**Issue by cofyc** [kubernetes/org#324]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
sig-storage-ceph-provisioner

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@rootfs
@wongma7
@cofyc

### If not a staging repo, who should have write access
@rootfs
@wongma7
@cofyc

### If a new repo, who should be listed as approvers in OWNERS
@rootfs
@wongma7
@cofyc

### If a new repo, who should be listed in SECURITY_CONTACTS
@rootfs
@wongma7
@cofyc

### What should the repo description be
Ceph external provisioners for rbd and cephfs

### What SIG and subproject does this fall under in sigs.yaml
this is part of the external-storage subproject for sig-storage

### Approvals
Need sig-storage approval from: @saad-ali and @wongma7
See https://github.com/kubernetes-incubator/external-storage/issues/1083.

### Additional context for request
Current, kubernetes-incubator/external-storage houses a lot of different provisioners. Different provisioners may have theirs own dependency/ci requirements or development/release workflow, etc. As for dependency management, it resulted that external-storage repo has huge dependency chain, and updating dependencies for one provisioner requires updating it for all provisioners which is not convenient and may have risk.
Xref: https://github.com/kubernetes/org/issues/244
Xref: https://github.com/kubernetes/org/issues/88

/area github-repo

**Comment by cofyc** [comment]
cc @saad-ali @wongma7 
What do you think?

**Comment by wongma7** [comment]
sgtm :+1:

**Comment by saad-ali** [comment]
Oh I see it was a legacy external-provisioner (https://github.com/kubernetes-incubator/external-storage/tree/master/ceph) and because that repo is being split up, the ask is for a new home for this. My recommendation would be to deprecate this Ceph external-provisioner, and not find a new home for it, and recommend folks use the Ceph CSI driver.

**Comment by cblecker** [comment]
@saad-ali is this still needed?

**Comment by nikhita** [comment]
/lifecycle stale

Marking this as stale.. please advise if this is still required.

**Comment by wongma7** [comment]
ceph org may be a better home for this. @cofyc any progress on that?
