### ISSUE TITLE
REQUEST: New membership for @rolfedh

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/org#3240]
### GitHub Username

@rolfedh

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@nate-double-u

### Sponsor 2

@sftim

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  - Open
    - Revise dockershim removal article list #31662
    - Updating topics-on-dockershim-and-cri-compatible-runtimes page formatting #31661
  - Closed
    - Collate and list resources about the dockershim removal #31528
    - Add Terraform Kubernetes module comparison blog post #28369
    - Proposed hugo archetype to fix issue `#27843` #27971
    - Updating dockershim FAQ with Mirantis announcement #27886
    - Add Sig-Usability-Spotlight Blog #27809
    - Create blog article "Thank you Dan Kohn" #27633
    - Add blog article on writing a labeling controller #27010
    - Add blog post: Using Finalizers to Control Deletion #26997

- Issues
  - Open: 
    - Clarify `Custom Resources` concept #27333
    - https://k8s.io/dockershim is marked outdated #31663
  - Closed: 
    - Dockershim: collate a list of 3rd party resources on the topic #30919
  
- SIG projects I am involved in:
  - SIG Docs
  - Interested in Localization, too.

**Comment by nate-double-u** [comment]
Rolfe has been a great help as an editor and writer on the website and blog for a while, and I'm happy to sponsor his application for membership!

/lgtm

**Comment by sftim** [comment]
:+1: for sponsorship. Thanks for contributing to SIG Docs.

**Comment by reylejano** [comment]
+1 from me, @rolfedh has been contributing to SIG Docs

**Comment by palnabarun** [comment]
@rolfedh -- thank you for all your contributions so far :)

I've created PR #3247 to add you to the requests org(s). Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign

**Comment by rolfedh** [comment]
Thank you, @nate-double-u, @sftim, @reylejano, and @palnabarun for your help with this. I'm very proud to be a member now and look forward to contributing more!
