### ISSUE TITLE
REQUEST: New membership for lzhecheng

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes/org#3242]
### GitHub Username

@lzhecheng

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@feiskyer

### Sponsor 2

@jayunit100

### List of contributions to the Kubernetes project

PRs reviewed / authored
cloud-provider-azure:
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1104
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1090
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1077
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/982

test-infra:
https://github.com/kubernetes/test-infra/pull/24935
https://github.com/kubernetes/test-infra/pull/25170

kubernetes:
https://github.com/kubernetes/kubernetes/pull/107548
https://github.com/kubernetes/kubernetes/pull/107631

SIG projects I am involved with:
* sig-cloud-provider
* cloud-provider-azure
* sig-testing, test-infra

**Comment by feiskyer** [comment]
+1 for @lzhecheng. Thanks for your contribution!

**Comment by jayunit100** [comment]
+1 from me to !

**Comment by lzhecheng** [comment]
@palnabarun could you help approve my membership? @mrbobbytables doesn't seem available. Thank you!

**Comment by palnabarun** [comment]
Hi @lzhecheng 👋🏽, I have approved the PR. Just as a note, we approve membership requests in batches within 7 days of all requirements being met.

/assign
