### ISSUE TITLE
REQUEST: New membership for @joelanford

### ISSUE THREAD

**Issue by joelanford** [kubernetes/org#3244]
### GitHub Username

@joelanford

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alvaroaleman

### Sponsor 2

@vincepri

### List of contributions to the Kubernetes project

I'm a maintainer and admin of the kubernetes-sigs/controller-runtime and controller-tools projects (and a reviewer for kubebuilder).

My primary interest in membership in the kubernetes org is to maintain and review changes in the configurations for the above projects prow configs in the kubernetes/test-infra repository.

Thanks!

**Comment by palnabarun** [comment]
@joelanford -- I have added you the Kubernetes org in #3247. Since the org memberships are equivalent now, you can directly create a PR adding you to any additional org if you are part of one. A membership request issue isn't needed anymore for such cases. :)

/assign
