### ISSUE TITLE
REQUEST: New membership for benluddy

### ISSUE THREAD

**Issue by benluddy** [kubernetes/org#3245]
### GitHub Username

@benluddy

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sttts

### Sponsor 2

@jpbetz

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/enhancements/pull/3160
- https://github.com/kubernetes/kubernetes/pull/105511
- https://github.com/kubernetes/kubernetes/pull/105800
- https://github.com/kubernetes/kubernetes/pull/106329
- https://github.com/kubernetes/kubernetes/pull/107034
- https://github.com/kubernetes/kubernetes/pull/107060
- https://github.com/kubernetes/kubernetes/pull/107956
- https://github.com/kubernetes/kubernetes/issues/105409
- https://github.com/kubernetes/kubernetes/issues/106328
- https://github.com/kubernetes/kubernetes/issues/107059
- https://github.com/kubernetes/kubernetes/issues/107954

**Comment by sttts** [comment]
Strong +1

**Comment by jpbetz** [comment]
+1

Thanks for all you've done Ben!

**Comment by palnabarun** [comment]
@benluddy -- thank you for all your contributions so far :)

I've created PR #3247 to add you to the requests org(s). Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
