### ISSUE TITLE
REQUEST: New membership in kubernetes-sigs for jyotimahapatra

### ISSUE THREAD

**Issue by jyotimahapatra** [kubernetes/org#3249]
### GitHub Username

jyotimahapatra

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

nic

### Sponsor 2

wongma7

### List of contributions to the Kubernetes project

- I'm involved in the kubernetes-sigs/aws-iam-authenticator [ref](https://github.com/kubernetes-sigs/aws-iam-authenticator/pulls?q=is%3Apr+author%3Ajyotimahapatra+)
- I served as the bug triage shadow in kubernetes release 1.23
- I'm currently serving as the bug triage lead in kubernetes release 1.24
- I'm already a member in the kubernetes/org

**Comment by nckturner** [comment]
+1 from me

**Comment by palnabarun** [comment]
Hi @jyotimahapatra, since you are already a member of the @kubernetes org, you don't need to raise a new membership request again. You can PR yourself into the @kubernetes-sigs org, for example, https://github.com/kubernetes/org/pull/3238, and I can approve the same.

**Comment by jyotimahapatra** [comment]
Thank you @palnabarun . Here's the PR https://github.com/kubernetes/org/pull/3253/files

**Comment by savitharaghunathan** [comment]
https://github.com/kubernetes/org/pull/3253/ merged. Please re-open if there is any issue with the membership invite.

/close
