### ISSUE TITLE
REQUEST: New membership for CatherineF-dev

### ISSUE THREAD

**Issue by CatherineF-dev** [kubernetes/org#3255]
### GitHub Username

CatherineF-dev

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

logicalhan

### Sponsor 2

ehashman

### List of contributions to the Kubernetes project

- [PRs reviewed](https://github.com/search?q=type%3Apr++is%3Amerged++reviewed-by%3ACatherineF-dev+in%3Aname+kubernetes&type=issues)

- [PRs authored](https://github.com/search?q=type%3Apr+is%3Amerged+author%3ACatherineF-dev+in%3Aname+kubernetes&type=issues)
- [Issues responeded to](https://github.com/search?q=type%3Aissue+commenter%3ACatherineF-dev+in%3Aname+kubernetes&type=issues)

**Comment by logicalhan** [comment]
/lgtm
/approve

Welcome!!

**Comment by ehashman** [comment]
+1 :partying_face:

**Comment by palnabarun** [comment]
@CatherineF-dev, thank you for all your contributions so far :)

I've created PR #3286 to add you to the requested organizations. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
