### ISSUE TITLE
REQUEST: New membership for MartinForReal

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/org#3256]
### GitHub Username

@MartinForReal

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@feiskyer

### Sponsor 2

@sbueringer

### List of contributions to the Kubernetes project

prs:
- https://github.com/kubernetes/test-infra/pull/25202
- https://github.com/kubernetes/test-infra/pull/25020
- https://github.com/kubernetes/test-infra/pull/24920

sig-projects:
- [cloud-provider-azure](https://github.com/kubernetes-sigs/cloud-provider-azure)
- [cluster-api](https://github.com/kubernetes-sigs/cluster-api)
- [test-infra](https://github.com/kubernetes/test-infra)

**Comment by sbueringer** [comment]
+1 
from my side

(Afaik kubernetes org membership should be "automatic" because of kubernetes-sigs org membership: https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem)

**Comment by feiskyer** [comment]
+1 from me

Thanks @MartinForReal for the contributions!

**Comment by palnabarun** [comment]
@MartinForReal -- @sbueringer is right. You don't need to raise a new request for membership. You can just PR yourself into the Kubernetes org (like in https://github.com/kubernetes/org/pull/3238) and I can approve the PR.

**Comment by MartinForReal** [comment]
@palnabarun Thanks for the instructions!
