### ISSUE TITLE
REQUEST: New integration for kubernetes-sigs/cloud-provider-azure

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/org#3257]
### Organization or Repo

kubernetes-sigs/cloud-provider-azure

### Name of integration

Microsoft Teams for GitHub

### Link to integration website

https://github.com/marketplace/microsoft-teams-for-github

### Describe what is attempting to be accomplished

send new notification to Microsoft teams.

**Comment by mrbobbytables** [comment]
I don't think this is something we will enable - any notifications should goto the public k8s slack. We do not endorse or use teams.

**Comment by MartinForReal** [comment]
I see. Thanks for the clarification!
