### ISSUE TITLE
REQUEST: New integration for kubernetes-sigs/cloud-provider-azure

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/org#3258]
### Organization or Repo

kubernetes-sigs/cloud-provider-azure

### Name of integration

Azure Boards

### Link to integration website

https://github.com/marketplace/azure-boards

### Describe what is attempting to be accomplished

Track all issues at every development stage and keep team aligned with all code changes in GitHub, which are linked directly to Azure Boards work items.

**Comment by mrbobbytables** [comment]
Similar to #3257 We do not integrate with things that aren't accessible or usable by the broad k8s community. - Slack, GitHub boards etc.

**Comment by MartinForReal** [comment]
I see. Thanks for the clarification!
