### ISSUE TITLE
REQUEST:Migrate leonardpahlke/application-summary

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/org#3259]
### New repo, staging repo, or migrate existing

* ~https://github.com/leonardpahlke/application-summary~
* https://github.com/leonardpahlke/release-team-shadow-stats

### Is it a staging repo?

no

### Requested name for new repository

* ~sigs.k8s.io/application-analysis~
* sigs.k8s.io/release-team-shadow-stats

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@sig-release-admins

### Who should have write access?

@sig-release-admins

### Who should be listed as approvers in OWNERS?

@sig-release-admins

### Who should be listed in SECURITY_CONTACTS?

@sig-release-admins

### What should the repo description be?

* ~Kubernetes shadow program application analysis~
* Kubernetes release team shadow program application analysis

### What SIG and subproject does this fall under?

SIG Release

### Please provide references to appropriate approval for this new repo

This tool has been discussed in sig-release 
* see [sig-release meeting 2022-02-08](https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit)
* [sig-release thread](https://kubernetes.slack.com/archives/C2C40FMNF/p1641917880062200)) 
This topic also has been discussed together with contribEx 
* see [sig-contribEX slack thread](https://kubernetes.slack.com/archives/C1TU9EB9S/p1641941787049000)). 

### Additional context for request

@kubernetes/owners 
cc: @kubernetes/sig-release-admins

**Comment by nikhita** [comment]
@leonardpahlke :wave: There are a few more things we'll need to do as prerequisites for migrating the repo:

- The files in the repo need to match https://github.com/kubernetes/kubernetes-template-project. This would require updates like adding the boilerplate header to all files and updating the README to match the format in the template-project.
- Can you also rename the repo to release-team-shadow-stats?

Once the above two items are done, please ping me here (or on slack) and I'll help you with the migration :+1:

**Comment by leonardpahlke** [comment]
Done +1

**Comment by nikhita** [comment]
/assign

Repo has been created - https://github.com/kubernetes-sigs/release-team-shadow-stats

Also created:
- #3298  - to add the GitHub team to grant access
- https://github.com/kubernetes/community/pull/6509 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by mrbobbytables** [comment]
2nd PR should be merged shortly, going to go ahead and close his out

/close
