### ISSUE TITLE
REQUEST: Archive repo kubernetes-sigs/poseidon

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/org#3262]
### Repository to archive

kubernetes-sigs/poseidon

### Repository and/or sig subproject owners that are approving this archival

@deepak-vij

### When should this be done

Anytime

**Comment by deepak-vij** [comment]
Hi @Huang-Wei & @ahg-g , how easy would it be for me to un-archive the archived project, if needed in future. Is there a process set up to do that? Please let me know, just in case. Thanks.

**Comment by mrbobbytables** [comment]
@deepak-vij repos that are archived are moved to another org and set to an archived state - no new issues/prs can be opened against them, but the code is still public and can be cloned/forked.

We generally encourage people to fork and continue development outside of the kubernetes project if it is something they wish to continue on their own.

**Comment by deepak-vij** [comment]
@mrbobbytables, perfect. Thanks.

**Comment by Huang-Wei** [comment]
I think we can start to archive kubernetes-sigs/poseidon.

**Comment by mrbobbytables** [comment]
Sorry, this has just been blocked on time :( Hopefully soon.

**Comment by ameukam** [comment]
Repo has been archived: https://github.com/kubernetes-retired/poseidon
Teams removal: https://github.com/kubernetes/org/pull/3369
`sigs.yaml` updated: https://github.com/kubernetes/community/pull/6602
Notice sent to k-dev and sig-scheduling: https://groups.google.com/g/kubernetes-sig-scheduling/c/lkzMRoIcN4c/m/GPTwjrZ2CgAJ

If you have any questions please feel free to reopen.

Thank you!

/close
