### ISSUE TITLE
REQUEST: Create repo to host Kueue

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/org#3263]
### New repo, staging repo, or migrate existing

New

### Is it a staging repo?

no

### Requested name for new repository

kueue

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

ahg-g, alculquicondor

### Who should have write access?

ahg-g, alculquicondor

### Who should be listed as approvers in OWNERS?

ahg-g, alculquicondor

### Who should be listed in SECURITY_CONTACTS?

ahg-g, alculquicondor

### What should the repo description be?

Kueue: Kubernetes-native Job Queueing

### What SIG and subproject does this fall under?

sig-scheduling

### Please provide references to appropriate approval for this new repo

Tagging other sig-scheduling leads on this issue.

### Additional context for request

This repository will host an implementation of the [bit.ly/kueue-apis](http://bit.ly/kueue-apis) proposal.

**Comment by ahg-g** [comment]
@Huang-Wei @alculquicondor

**Comment by ahg-g** [comment]
Here is also an email sent to the mailing list: https://github.com/kubernetes/org/issues/3263

**Comment by Huang-Wei** [comment]
+1

I guess we need sponsors from committee?

**Comment by nikhita** [comment]
/assign

Repo has been created - https://github.com/kubernetes-sigs/kueue

Also created:
- https://github.com/kubernetes/org/pull/3264 - to add the GitHub team to grant access
- https://github.com/kubernetes/community/pull/6477 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by ahg-g** [comment]
Thanks @nikhita for the quick response!
