### ISSUE TITLE
REQUEST: New membership for sashrith 

### ISSUE THREAD

**Issue by sashrith** [kubernetes/org#3265]
### GitHub Username

 @sashrith

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@RaunakShah

### List of contributions to the Kubernetes project

PRs reviewed / authored
https://github.com/kubernetes-sigs/vsphere-csi-driver/pulls?q=is%3Apr+author%3Asashrith

SIG projects I am involved with
https://github.com/kubernetes-sigs/vsphere-csi-driver

**Comment by xing-yang** [comment]
+1

**Comment by RaunakShah** [comment]
+1

**Comment by palnabarun** [comment]
@sashrith, thank you for all your contributions so far :)

I've created PR #3286 to add you to the requested organizations. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
