### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/cloud-provider-azure

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/org#3268]
### Repository

kubernetes-sigs/cloud-provider-azure

### Project domain

cloud-provider-azure.sigs.k8s.io

### Additional context for request

Making subdomain request at same time as Netlify request, not sure on the proper order of operations here but would love to have both enabled soon.

**Comment by mrbobbytables** [comment]
Sorry, this dropped through the cracks - do you still want to proceed with netlify?

**Comment by MartinForReal** [comment]
yes. Please

**Comment by mrbobbytables** [comment]
@MartinForReal please create a netlify.toml file in the root of the repo and open up a dns request in the k8s.io repo, I can get going with the creation once the netlify.toml file is there. The default netlify site will be called `kubernetes-sigs-cloud-provide-azure.netlify.app`

**Comment by mrbobbytables** [comment]
It has been enabled, but builds are failing - you should be able to see details on it here:
https://app.netlify.com/sites/kubernetes-sigs-cloud-provide-azure/deploys/62b0cd6d1949a302ad9a89cd

**Comment by MartinForReal** [comment]
@mrbobbytables I found that dns record was correct. Could you please help update the domain config for this project? I'm wondering if the maintainer team could get access to this site. Thanks!

**Comment by mrbobbytables** [comment]
@MartinForReal I updated the config with the dns name and the ssl cert for it should be provisioned pretty quickly.
After this it should all be able to be configed via the config file.

**Comment by MartinForReal** [comment]
The migration is complete! Thanks for the help!
