### ISSUE TITLE
REQUEST: New membership for chaodaiG

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/org#3270]
### GitHub Username

chaodaiG

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

cjwagner

### Sponsor 2

alvaroaleman

### List of contributions to the Kubernetes project

- PR contributed: [430 in k8s/test-infra](https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+is%3Aclosed+author%3AchaodaiG)
- Issues: involved in [84 in k8s/test-infra](https://github.com/kubernetes/test-infra/issues?q=is%3Aissue+chaodaiG+)

**Comment by alvaroaleman** [comment]
+1 but I think you can just add yourself to k-sigs since you are already a k member: https://github.com/kubernetes/org/issues/3244#issuecomment-1035939895

**Comment by chaodaiG** [comment]
> +1 but I think you can just add yourself to k-sigs since you are already a k member: [#3244 (comment)](https://github.com/kubernetes/org/issues/3244#issuecomment-1035939895)

good point, adding myself in https://github.com/kubernetes/org/pull/3271
