### ISSUE TITLE
REQUEST: Migrate aws/cluster-api-provider-cloudstack

### ISSUE THREAD

**Issue by pmotyka** [kubernetes/org#3279]
### New repo, staging repo, or migrate existing

Migrate existing - https://github.com/aws/cluster-api-provider-cloudstack

### Is it a staging repo?

no

### Requested name for new repository

cluster-api-provider-cloudstack

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

pmotyka rohityadavcloud

### Who should have write access?

We will set this up once the repo is migrated in.

### Who should be listed as approvers in OWNERS?

rohityadavcloud davidjumani

### Who should be listed in SECURITY_CONTACTS?

rohityadavcloud davidjumani

### What should the repo description be?

Kubernetes Cluster API Provider implementation for Apache CloudStack.

### What SIG and subproject does this fall under?

This is a new cluster-api provider project for sig-cluster-lifecycle called cluster-api-provider-cloudstack (https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml)

### Please provide references to appropriate approval for this new repo

Mailing list discussion:
https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/sg46hgaIzJs/m/qj0LvP6KAQAJ

### Additional context for request

Slack channel: A request for #cluster-api-cloudstack Slack channel to be created in the Kubernetes Slack workspace for use of community building, participation and discussion around CAPI provider for Apache CloudStack. https://github.com/kubernetes/community/pull/6427

**Comment by pmotyka** [comment]
@caniszczyk

Per - https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

Could you please perform a review of third party dependencies?

**Comment by mrbobbytables** [comment]
@pmotyka  There doesn't appear to be approval from the SCL leads in the thread you linked, we need that first before anything can proceed.

That is also ALOT of people to put in an owners file, and none are currently org members. + more than the total # of contributors to the project already. That list will need to be cut down and they will need to go through the usual process for org membership which means contributing to something in the project beforehand.

**Comment by caniszczyk** [comment]
+1 from a CNCF POV no major issues that would cause a roadblock here

**Comment by rohityadavcloud** [comment]
Thanks for the review @caniszczyk.

@mrbobbytables as Peter advised we have an agenda to discuss, build support, and get approval in the sig-cluster-lifecycle Tuesday meeting. We had discussed this starting with the SIG mailing list and discussed this in the Cluster API project meeting (https://docs.google.com/document/d/1ushaVqAKYnZ2VN_aa3GyKlS4kEd6bSug13xaXOakAQI/edit) on 9th Feb 2022 where we were advised by @fabriziopandini Yassine and Mike. We're happy to trim the owners list down and follow any other guidance.

@pmotyka I suggest we start both the incubator owners and security list to:
```
pmotyka
jweite-amazon
<add any more from aws?>
rohityadavcloud
davidjumani
```

**Comment by neolit123** [comment]
+1 on the repo creation

**Comment by vincepri** [comment]
+1 on the repository

To recap the discussion in today's SIG meeting, we'd like to ask folks here to trim the approvers list to 2-3 members at most to start with and then promote folks over time.

**Comment by fabriziopandini** [comment]
+1 on the repository

**Comment by rohityadavcloud** [comment]
Thanks @neolit123 @vincepri @fabriziopandini for your support, guidance and vote.

@pmotyka can you update/trim the list to just:
```
pmotyka
jweite-amazon
rohityadavcloud
```
We'll get more folks in the future when and as they make contributions as per SIG guidance.

**Comment by rohityadavcloud** [comment]
@neolit123 @vincepri @fabriziopandini as asked during the SIG call, we've put together a short 10-min demo video of CAPC here: https://shapeblue-engineering-videos.s3.eu-west-1.amazonaws.com/capc/capc-demo-acs416.mp4 post-migration of the repo we're aiming to put together proper docs/website, and work on more detailed training/marketing videos and materials.

**Comment by rohityadavcloud** [comment]
Hi @mrbobbytables can you advise us on the logistics of migrating the repository?

**Comment by rohityadavcloud** [comment]
It appears @mrbobbytables is on OOO.
Pinging other members to seek further guidance on how to proceed - @nikhita @palnabarun @cblecker @dims @justaugustus

**Comment by rohityadavcloud** [comment]
Ping2 @nikhita @palnabarun @cblecker @dims @justaugustus - appreciate you're all busy any guidance for us?
Alternatively, please advise how to proceed @neolit123 @vincepri @fabriziopandini ?

Thanks all.

**Comment by nikhita** [comment]
@rohityadavcloud like @mrbobbytables's mentioned before, you will need to have all approvers go through the usual [membership](https://github.com/kubernetes/community/blob/master/community-membership.md#member) process to become members of the Kubernetes SIGs github org first. Only then the approvers will be able to approve PRs.

**Comment by rohityadavcloud** [comment]
Thank you @nikhita for replying.

We only want to be part of the Kubernetes Cluster Lifecycle SIG (https://github.com/kubernetes-sigs) to be able to continue our work on cluster-api-provider-cloudstack in it. The Kubernetes Cluster Lifecycle SIG chair/leads (@vincepri @neolit123 @fabriziopandini) have already +1'd on the issue, we thought that was enough to get moving. My question was more about how to migrate the repository under https://github.com/kubernetes-sigs (for example, do we use Github repo ownership transfer or the k8s/sig admins will create a repo and clone the original repo?).

We (Peter @pmotyka and Rohit @rohityadavcloud) weren't aware or missed that we were required to become members of the org first. If this is still not the case, then pl do advise. Meanwhile, @pmotyka and I will go through the advised document and see if we qualify. Thanks again for the guidance.

**Comment by mrbobbytables** [comment]
@rohityadavcloud anyone that is an owner MUST be an org member (You can reference this issue in the org member request form and say its part of establishing owners for this repo). We do not allow org/repo level outside collaborators. People are still free to contribute, but the owners will be required to review and approve PRs.

Generally because there is so much back and forth, and being a part of the org is not a blocker to contributing, we do not have any SLO on repo migration - its best effort by the 1 or 2 active GitHub admins (we're working on staffing it back up)

For a little more info  - It'll require moving the repo to a temporary org and then move to k-sigs (this is to work around some wonky github issues)

**Comment by rohityadavcloud** [comment]
Fantastic thanks @mrbobbytables for answering in detail and advising on this. Between @pmotyka and I, we'll discuss and see if we can qualify to become a member of the org.

**Comment by rohityadavcloud** [comment]
@mrbobbytables @nikhita thanks for your guidance.

Given the requirement of owners of this new repo to be migrated to be org members, could the initial repo migration happen with just a single owner (the idea that we can add more owners over time)? I'm asking as Peter wasn't sure if he currently meets the membership criteria.

I've raised https://github.com/kubernetes/org/issues/3312 after getting two sponsors and going through the [membership criterias](https://github.com/kubernetes/community/blob/master/community-membership.md#member).

**Comment by rohityadavcloud** [comment]
@pmotyka can you update the list of approves for the owners and security sections in this issue to:
```
rohityadavcloud
davidjumani
```
I think both @davidjumani and I have raised org-membership requests towards meeting the requirement for migration of the repo.

**Comment by davidjumani** [comment]
I've raised https://github.com/kubernetes/org/issues/3319 as well

**Comment by pmotyka** [comment]
Owners and Security sections have been updated to reflect the narrowed list of members pursuing org-membership.

**Comment by rohityadavcloud** [comment]
Ping Hi @mrbobbytables @nikhita and others - any further advise for us, how do we proceed with the repo donation. Both @davidjumani and @rohityadavcloud (owners of repo being migrated) are now members of the kubernetes-sigs org.

**Comment by mrbobbytables** [comment]
@rohityadavcloud we can kick this off now, is there anyone that on the aws side that has rights to migrate the repo to our temporary org - https://github.com/kubernetes-purgatory
We have to migrate to that temp org before we migrate it

**Comment by rohityadavcloud** [comment]
Thanks for advising the next steps @mrbobbytables. I'll discuss with @pmotyka and team on aws side and keep you posted once we're able to migrate the repository to the temporary org. (I'm assuming we simply get the repo migrated via the original Github repo's settings to the temp org https://github.com/kubernetes-purgatory and ping you)

**Comment by mrbobbytables** [comment]
@rohityadavcloud we'll need to add whoever has admin rights to the temp org for them to migrate it to it. 
Migrations require making someone temporarily admin of the org which is why we have to do this shuffle =/

**Comment by pmotyka** [comment]
Thanks for the guidance, excited to have reached this step!  @hyandell will be assisting with the migration activities.

**Comment by mrbobbytables** [comment]
invite has been sent 👍

**Comment by hyandell** [comment]
Thanks - invite accepted. Nice setup - better than the usual "transfer the repo to myself personally and wait for the next party to accept my transfer to their personal account" :)

I'll be waiting on pmotyka to give me a go request internally; for when folk are prepared for permissions to be in flux.

**Comment by hyandell** [comment]
@mrbobbytables @nikhita @pmotyka Repository now transferred to kubernetes-purgatory. Ready to be moved on from there to its next home. Let me know if I can help further :)

**Comment by pmotyka** [comment]
Thank you, @hyandell!  @mrbobbytables @nikhita - could you let us know what next steps are needed to migrate the repository to kubernetes-sigs?

**Comment by rohityadavcloud** [comment]
Thanks @mrbobbytables I see the repo here https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack - looking forward to next steps!

**Comment by pmotyka** [comment]
Thank you @mrbobbytables, a remaining step we could use assistance with is the processing of the PR that aligns the OWNERS file with the intent of this migration issue - https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/44.  Could you assist with this as our approvals don't appear to be satisfying k8s-ci-robot.

**Comment by mrbobbytables** [comment]
Yeah, sorry^^;;; I forgot to update this issue after moving things over. I'll manually merge that PR and get the teams sorted out this morning.

**Comment by mrbobbytables** [comment]
Teams are added to the repo, I merged the OWNERS update. The only remaining item is the k/community issue and once thats merged everything should be good!
