### ISSUE TITLE
REQUEST: add dependabot to kubernetes-sigs org

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/org#3282]
### Organization or Repo

kubernetes-sigs/cloud-provider-azure

### Name of integration

dependabot

### Link to integration website

https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates

### Describe what is attempting to be accomplished

Dependabot automatically sends PRs for updates to dependencies due to security issues.

**Comment by mrbobbytables** [comment]
It looks like its already enabled for that repo - anyone with admin access for the repo should be able to enable/disable it. Alerts are set to goto the [cloud-provider-azure-maintainers team](https://github.com/kubernetes/org/blob/ee94f6e2ad1cf91c2757a3dfb45b4dc113c85cd9/config/kubernetes-sigs/provider-azure/teams.yaml#L12-L21).

**Comment by MartinForReal** [comment]
But I still need to send /ok-to-test for the prs it raises. Could you please help add dependabot to kubernetes-sigs org like https://github.com/kubernetes/org/issues/945

**Comment by mrbobbytables** [comment]
@MartinForReal If you want it to automatically skip `ok-to-test`. You can add the label via the `labels` section of your [dependabot config](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates) (Example: [kubernetes-sigs/zeitgeist](https://github.com/kubernetes-sigs/zeitgeist/blob/master/.github/dependabot.yml))

There isn't anything more we can do on the github-admin side^^;;;

**Comment by MartinForReal** [comment]
Thanks!
