### ISSUE TITLE
REQUEST: New membership for shawnhanx

### ISSUE THREAD

**Issue by shawnhanx** [kubernetes/org#3287]
### GitHub Username

@shawnhanx

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xiangpengzhao

### Sponsor 2

@tengqm

### List of contributions to the Kubernetes project

- kubernetes/kubernetes/pull/97321
- kubernetes/kubernetes/pull/101092
- kubernetes/kubernetes/pull/104429
- kubernetes/kubernetes/pull/104807
- kubernetes/kubernetes/pull/105603
- kubernetes/kubernetes/pull/105621
- kubernetes/kubernetes/pull/106215
- kubernetes/kubernetes/pull/106397
- kubernetes/kubernetes/pull/106398
- kubernetes/kubernetes/pull/100600
- kubernetes/kubernetes/pull/101997
- kubernetes/kubernetes/pull/104353
- kubernetes/kubernetes/pull/104386
- kubernetes/kubernetes/pull/105209
- kubernetes/kubernetes/pull/105229
- kubernetes/kubernetes/pull/105570
- kubernetes/kubernetes/pull/106225
- kubernetes/kubernetes/pull/107362
- kubernetes/website/pull/31752

**Comment by tengqm** [comment]
+1

**Comment by xiangpengzhao** [comment]
+1

**Comment by palnabarun** [comment]
@shawnhanx, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
