### ISSUE TITLE
REQUEST: New membership for SanikaGawhane

### ISSUE THREAD

**Issue by SanikaGawhane** [kubernetes/org#3289]
### GitHub Username

@SanikaGawhane

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@codenrhoden

### Sponsor 2

@CecileRobertMichon

### List of contributions to the Kubernetes project

image-builder
https://github.com/kubernetes-sigs/image-builder/pulls?q=is%3Apr+author%3Asanikagawhane+

k8s.io (for image-promotions)
https://github.com/kubernetes/k8s.io/pulls?q=is%3Apr+author%3ASanikaGawhane

test-infra
https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3ASanikaGawhane

cluster-api-provider-aws
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3ASanikaGawhane

**Comment by codenrhoden** [comment]
+1
This is long overdue!

**Comment by CecileRobertMichon** [comment]
+1!

**Comment by palnabarun** [comment]
@SanikaGawhane, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
