### ISSUE TITLE
REQUEST: New membership for Dyanngg

### ISSUE THREAD

**Issue by Dyanngg** [kubernetes/org#3293]
### GitHub Username

@Dyanngg

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@astoycos

### Sponsor 2

@rikatz

### List of contributions to the Kubernetes project

I have worked on the AdminNetworkPolicy resource KEP (https://github.com/kubernetes/enhancements/pull/2522) since inception. I have also been an active participant of sig-network and sig-network-api meetings. In addition, I'm now working on adding new commits to the new [network-policy-api repo](https://github.com/kubernetes-sigs/network-policy-api), which will house new CRDs related to K8s Security.

**Comment by rikatz** [comment]
+1 

Yang has been working hard on the last year for Cluster NetPol and also with sig-net policy api subproject!

**Comment by astoycos** [comment]
+1 
Yang has been the main contributor working with me on the new AdminNetworkPolicy API and has been an excellent source of advice and help for all the members of the sig-network-policy-api subgroup.

**Comment by palnabarun** [comment]
@Dyanngg, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
