### ISSUE TITLE
REQUEST: New membership for phillipsj

### ISSUE THREAD

**Issue by phillipsj** [kubernetes/org#3294]
### GitHub Username

@phillipsj

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@marosset

### Sponsor 2

@jayunit100

### List of contributions to the Kubernetes project

PRs:
* https://github.com/kubernetes-sigs/windows-gmsa/pull/57
* https://github.com/kubernetes-sigs/windows-gmsa/pull/55
* https://github.com/kubernetes/k8s.io/pull/3161
* https://github.com/kubernetes/klog/pull/271

Issues:
* https://github.com/kubernetes-sigs/windows-gmsa/issues/40
* https://github.com/kubernetes-sigs/windows-gmsa/issues/52

Subprojects Contributions/Participation:
* https://github.com/kubernetes-sigs/windows-gmsa
* https://github.com/kubernetes-sigs/sig-windows-dev-tools

**Comment by marosset** [comment]
Sorry for the delay here.

+1 from me!

**Comment by jayunit100** [comment]
lgtm ! +1 ! jamie has been contributing to sig-windows as a mentor and doing demos of things related to sig-windows-dev-tools, host process conatiners, containerd, and cert manager for several months now and has helped us in multiple pairing sessions to solve intesresting windows upstream problems.

**Comment by jsturtevant** [comment]
+1

**Comment by palnabarun** [comment]
@phillipsj, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
