### ISSUE TITLE
Add @dims to kubernetes-client

### ISSUE THREAD

**Issue by dims** [kubernetes/org#33]
### GitHub Username
@dims 

### Organization you are requesting membership in
@kubernetes-client

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp 
- @mbohlool

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

### Reason for asking
- I believe i was added as a collaborator for helping with the python client. Though to be honest, i haven't been active there lately since the Magnum use case has been stable. Requesting Org membership here per request from @spiffxp in https://github.com/kubernetes/test-infra/pull/9122

**Comment by spiffxp** [comment]
/close
Either someone beat me to sending you an invite or I missed the fact that you're already in the org.  Either way, welcome aboard :)
