### ISSUE TITLE
New staging repo k8s.io/component-base

### ISSUE THREAD

**Issue by sttts** [kubernetes/org#330]
### New Repo, Staging Repo, or migrate existing
staging repository

### Requested name for new repository
component-base

### Which Organization should it reside
kubernetes

### If a new repo, who should be listed as approvers in OWNERS
none: staging repo, owners will be specified in the staging folder according to the KEP.

### If a new repo, who should be listed in SECURITY_CONTACTS
none: staging repo, default Kubernetes security contacts will be specified in the staging folder.

### What should the repo description be
Shared code for kubernetes core components.

### What SIG and subproject does this fall under in sigs.yaml
sig-api-machinery

### Approvals
KEP https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/0032-create-a-k8s-io-component-repo.md

### Additional context for request
none

**Comment by timothysc** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by thockin** [comment]
I'm out of touch with process.  If this is all approved, should I just create the repo?  Do we have a script for doing this in a consistent way wrt group and other stuff?

**Comment by sttts** [comment]
@spiffxp @dims does one of you know ^^ ? I believe there is a script because staging repos aren't that simple permission-wise.

**Comment by spiffxp** [comment]
Leave repo creation up to the k/org team, we're mainly concerned with ensuring appropriate approval has been given.  Looking...

**Comment by spiffxp** [comment]
Even though this is a staging repo, since it's in kubernetes, it needs sig-arch approval.

I don't see a thread about this repo name specifically in kubernetes-sig-arch@

I see https://github.com/kubernetes/community/pull/2977, but I don't see this repo name specifically approved

I see https://github.com/kubernetes/enhancements/pull/653 renames the repo, and mentions discussion at the contrib summit, but I don't see sig-arch approval specifically.

@thockin am I taking your /approve as sig-arch approval here?

**Comment by spiffxp** [comment]
/cc @jdumars @mattfarina 
as SIG Arch chairs

**Comment by dims** [comment]
@sttts yes, they have a list of things they do after they create the repo too

**Comment by mattfarina** [comment]
I found the tracibility for this... https://github.com/kubernetes/community/pull/2977#issuecomment-442992019

From @bgrant0607:

> This was discussed in SIG Arch. At a high level, seems like a good idea. We asked for a slightly less generic repo name, such as componentlib.
> 
> thockin is the designated approver.

@thockin I see you approved. Do you approve of the name and all?

**Comment by bgrant0607** [comment]
Yes, this is approved

**Comment by luxas** [comment]
Thanks!

For reference, I asked for this formal approval in this thread: https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/bm5oN9yp0cc

**Comment by cblecker** [comment]
Repo created.

@sttts @nikhita You should be able to do the publishing bot pieces at any time.
@luxas Would you mind adding this new repo to sigs.yaml?

**Comment by nikhita** [comment]
> @sttts @nikhita You should be able to do the publishing bot pieces at any time.

I have already created https://github.com/kubernetes/publishing-bot/pull/142. Will cancel the hold after https://github.com/kubernetes/test-infra/pull/10635 gets merged. :smile:

**Comment by luxas** [comment]
> Would you mind adding this new repo to sigs.yaml?

@cblecker yes, we'll do so

Thanks!
