### ISSUE TITLE
REQUEST: New membership for marckhouzam

### ISSUE THREAD

**Issue by marckhouzam** [kubernetes/org#3301]
### GitHub Username

@marckhouzam

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@eddiezane

### Sponsor 2

@brianpursley

### List of contributions to the Kubernetes project

Merged PRs:
https://github.com/kubernetes/kubernetes/pull/105711
https://github.com/kubernetes/kubernetes/pull/105851
https://github.com/kubernetes/kubernetes/pull/105141
https://github.com/kubernetes/kubernetes/pull/96087

Open PRs:
https://github.com/kubernetes/kubernetes/pull/108493
https://github.com/kubernetes/kubernetes/pull/105867

Issues I responded to:
https://github.com/kubernetes/kubernetes/issues/59078
https://github.com/kubernetes/kubernetes/issues/74178
https://github.com/kubernetes/kubernetes/issues/94927
https://github.com/kubernetes/kubernetes/issues/105587
https://github.com/kubernetes/kubectl/issues/576
https://github.com/kubernetes/kubectl/issues/613
https://github.com/kubernetes/kubectl/issues/882
https://github.com/kubernetes/kubectl/issues/890
https://github.com/kubernetes/kubectl/issues/1116
https://github.com/kubernetes/kubectl/issues/1119
https://github.com/kubernetes/kubectl/issues/1135
https://github.com/kubernetes/kubectl/issues/1139
https://github.com/kubernetes/kubectl/issues/1157
https://github.com/kubernetes/kubectl/issues/1180
https://github.com/kubernetes/kubectl/issues/1181

**Comment by eddiezane** [comment]
+1

Thanks Marc! Your contributions have been awesome.

**Comment by brianpursley** [comment]
+1

Thanks Marc! and +1 to what Eddie said. You've made some great improvements to kubectl and have been a tremendous help troubleshooting issues.

**Comment by palnabarun** [comment]
@marckhouzam, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
