### ISSUE TITLE
REQUEST: New membership for ahmedkhamessi

### ISSUE THREAD

**Issue by ahmedkhamessi** [kubernetes/org#3302]
Hi,

I would like to join the @kubernetes-sigs inroder to contribute to the development of the core components of Kubernetes first hand.

Best regards,
Ahmed Khamessi.

**Comment by mrbobbytables** [comment]
@ahmedkhamessi you do not need to be an org member to contribute :) There are 10s of thousands of people that do it without being an org member. If, after contributing a bit please open an issue using the [Org member request form](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) with your sponsors and contributions. For more information, please see the [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#member)

/close
