### ISSUE TITLE
REQUEST: New membership for @bigdarkclown

### ISSUE THREAD

**Issue by BigDarkClown** [kubernetes/org#3303]
### GitHub Username

@bigdarkclown

### Organization you are requesting membership in

@kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)

### Sponsor 1

@maciekpytel

### Sponsor 2

@gjtempleton

### List of contributions to the Kubernetes project

- PRs authored
https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+is%3Aclosed+author%3Abigdarkclown

- SIG projects I am involved with
Autoscaler (Cluster Autoscaler)

**Comment by MaciekPytel** [comment]
+1 from me, @BigDarkClown has been regularly contributing to Cluster Autoscaler project for more than a year now

**Comment by gjtempleton** [comment]
+1 from me, @BigDarkClown's already made significant contributions, looking forward to their continued contributions to the Cluster Autoscaler.

**Comment by palnabarun** [comment]
@BigDarkClown, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
