### ISSUE TITLE
REQUEST: New membership for Abirdcfly

### ISSUE THREAD

**Issue by Abirdcfly** [kubernetes/org#3304]
### GitHub Username

@Abirdcfly

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei

### Sponsor 2

@damemi

### List of contributions to the Kubernetes project

Merged PRs:
- https://github.com/kubernetes/kubernetes/pull/108535
- https://github.com/kubernetes/kubernetes/pull/108479
- https://github.com/kubernetes/kubernetes/pull/108473
- https://github.com/kubernetes/kubernetes/pull/108239
- https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/211
- https://github.com/kubernetes/website/pull/29468
- https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/72
- https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/71
- https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/70
- https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/69
- https://github.com/kubernetes-sigs/kubefed/pull/1279

Open PRs:
- https://github.com/kubernetes/website/pull/32116
- https://github.com/kubernetes/kubernetes/pull/108484

**Comment by Huang-Wei** [comment]
+1

**Comment by damemi** [comment]
+1

**Comment by palnabarun** [comment]
@Abirdcfly, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
