### ISSUE TITLE
REQUEST: New membership for JaneLiuL

### ISSUE THREAD

**Issue by JaneLiuL** [kubernetes/org#3306]
### GitHub Username

JaneLiuL

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@damemi

### Sponsor 2

@ingvagabund

### List of contributions to the Kubernetes project

Sig Projects: https://github.com/kubernetes-sigs/descheduler
PR: https://github.com/kubernetes-sigs/descheduler/pulls?q=is%3Apr+is%3Aclosed+janeliul
Issues: https://github.com/kubernetes-sigs/descheduler/issues?q=is%3Aissue+janeliul

**Comment by lianghao208** [comment]
+1 
Looking forward to more contributions

**Comment by ingvagabund** [comment]
+1

**Comment by damemi** [comment]
+1
Thanks for all your work so far @JaneLiuL, looking forward to more!

**Comment by palnabarun** [comment]
@JaneLiuL, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
