### ISSUE TITLE
REQUEST: New membership for chrismetz09

### ISSUE THREAD

**Issue by chrismetz09** [kubernetes/org#3307]
### GitHub Username

@chrismetz09

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Rey Lejano

### Sponsor 2

@jimangel

### List of contributions to the Kubernetes project

[Authored PRs](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Achrismetz09+is%3Aclosed)

[Kubecon 2021 Kubernetes SIG Docs: Deep-Dive, co-author/co-presenter](https://www.youtube.com/watch?v=GDfcBF5et3Q)

[Kubernetes contributor blog, "Improve your documentation with Mermaid.js diagrams" co-author with Tim Bannister](https://www.kubernetes.dev/blog/2021/12/01/improve-your-documentation-with-mermaid.js-diagrams/)

**Comment by rey** [comment]
Perhaps @reylejano?

**Comment by chrismetz09** [comment]
@reylejano @jimangel

**Comment by reylejano** [comment]
+1  🎉 @chrismetz09 has made substantial contributions to SIG Docs like establishing the diagramming guide with mermaid

**Comment by jimangel** [comment]
+1 @chrismetz09 was a huge help with our SIG Docs KCNA 21 presentation and many other contributions as Rey alluded. Welcome! 🎉

**Comment by palnabarun** [comment]
@chrismetz09, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
