### ISSUE TITLE
REQUEST: New membership for josh-ferrell

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes/org#3308]
### GitHub Username

josh-ferrell

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sedefsavas

### Sponsor 2

@richardcase

### List of contributions to the Kubernetes project

- kubernetes-sigs/cluster-api-provider-aws#3133
- kubernetes-sigs/cluster-api-provider-aws#3237
- kubernetes-sigs/cluster-api-provider-aws#3251
- kubernetes-sigs/cluster-api-provider-aws#3285
- kubernetes-sigs/cluster-api-provider-aws#3291
- kubernetes-sigs/cluster-api#6277

**Comment by josh-ferrell** [comment]
Tagging @sedefsavas and @richardcase

**Comment by sedefsavas** [comment]
+1
/lgtm

Josh has done important contributions to cluster-api-provider-aws project over the last few months.

**Comment by richardcase** [comment]
Thank you for your contributions to CAPA, it’s definitely this from me:

+1

**Comment by Ankitasw** [comment]
Thankyou for your contributions @josh-ferrell 
+1

**Comment by palnabarun** [comment]
@josh-ferrell, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
