### ISSUE TITLE
REQUEST: New membership for apricote

### ISSUE THREAD

**Issue by apricote** [kubernetes/org#3309]
### GitHub Username

@apricote

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@tobiasgiese

### List of contributions to the Kubernetes project

- PRs authored
  - [kubernetes-sigs/cluster-api](https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+author%3Aapricote+is%3Aclosed)
  - [kubernetes-sigs/cluster-api-provider-openstack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pulls?q=is%3Apr+author%3Aapricote+is%3Aclosed)
  - [kubernetes-sigs/image-builder](https://github.com/kubernetes-sigs/image-builder/pulls?q=is%3Apr+author%3Aapricote+is%3Aclosed)
- Issues opened
  - [kubernetes-sigs/cluster-api](https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+author%3Aapricote)

**Comment by tobiasgiese** [comment]
+1

Thanks for your great contributions so far! 👍🏻

**Comment by sbueringer** [comment]
+1

Thank you very much!

**Comment by palnabarun** [comment]
@apricote, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
