### ISSUE TITLE
REQUEST: New membership for meghanajangi

### ISSUE THREAD

**Issue by meghanajangi** [kubernetes/org#3310]
### GitHub Username

meghanajangi

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Ankitasw

### Sponsor 2

@richardcase

### List of contributions to the Kubernetes project

**PRs reviewed / authored**
- https://github.com/kubernetes-sigs/cluster-api/pull/6114 
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3222
- https://github.com/kubernetes/test-infra/pull/25294
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3278
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3214

**Issues responded to**
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2152
- https://github.com/kubernetes-sigs/cluster-api/issues/6267
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2127

**SIG projects I am involved with**

- cluster-api
- cluster-api-provider-azure
- cluster-api-provider-aws

**Comment by Ankitasw** [comment]
+1 from my side 🎉 
Thank you @meghanajangi for all your contributions in CAPA/CAPZ/CAPI.

**Comment by Priyankasaggu11929** [comment]
/meow

🥳

**Comment by richardcase** [comment]
+1 from me :tada:

**Comment by palnabarun** [comment]
@meghanajangi, thank you for all your contributions so far :)

I've created PR #3311 to add you to the requested orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign

**Comment by meghanajangi** [comment]
Thank you everyone! ❤️
