### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/cluster-api-provider-cloudstack

### ISSUE THREAD

**Issue by rohityadavcloud** [kubernetes/org#3318]
### Repository

kubernetes-sigs/cluster-api-provider-cloudstack

### Project domain

cluster-api-cloudstack.sigs.k8s.io

### Additional context for request

This is created in anticipation of the repo migration request: https://github.com/kubernetes/org/issues/3279
Post-migration, we would like to have this docs/site for the provider similar to other cluster-api providers.

**Comment by rohityadavcloud** [comment]
We've a staging (work-in-progress) website to test the content here https://cluster-api-provider-cloudstack.netlify.app/

**Comment by rohityadavcloud** [comment]
ping @mrbobbytables do also advise next steps to get this 🙏   /cc @davidjumani @pmotyka

**Comment by davidjumani** [comment]
Created the following to facilitate the request :
- https://github.com/kubernetes/k8s.io/issues/3796
- https://github.com/kubernetes/k8s.io/pull/3797

**Comment by davidjumani** [comment]
@mrbobbytables I think I've raised all the required issues / PRs related to this. Please let me know if there's anything else to be done

**Comment by mrbobbytables** [comment]
I've enabled netlify for the repo, its setup with the domain: "kubernetes-sigs-cluster-api-cloudstack.netlify.app" for now. Once the dns stuff is merged I'll update the settings. 👍 

/assign

**Comment by davidjumani** [comment]
Thanks @mrbobbytables 
Could you let us know who can assist with the DNS stuff ?

**Comment by mrbobbytables** [comment]
@davidjumani the owners for DNS:
https://github.com/kubernetes/k8s.io/blob/main/dns/OWNERS

Those are the only ones who can approve dns changes.

**Comment by davidjumani** [comment]
Thanks @mrbobbytables I'll await their review

**Comment by davidjumani** [comment]
@mrbobbytables The dns PR has been merged. Is there anything else needed to proceed ?

**Comment by rohityadavcloud** [comment]
Thanks @davidjumani for progressing this and @mrbobbytables for your help. Any further advise for us @mrbobbytables on this?

**Comment by davidjumani** [comment]
Thanks @mrbobbytables 
I'll go ahead and close this
/close
