### ISSUE TITLE
REQUEST: New membership for @davidjumani

### ISSUE THREAD

**Issue by davidjumani** [kubernetes/org#3319]
### GitHub Username

@davidjumani

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@fabriziopandini

### Sponsor 2

@elmiko

### List of contributions to the Kubernetes project

PRs authored and merged:
- https://github.com/kubernetes/autoscaler/pull/3629
- https://github.com/kubernetes-sigs/image-builder/pull/792

**Background**: Started from the repo migration request for a new Cluster-API Provider for Apache CloudStack https://github.com/kubernetes/org/issues/3279

**Comment by elmiko** [comment]
+1, thanks for volunteering to maintain the cloudstasck provider @davidjumani

**Comment by fabriziopandini** [comment]
+1 
considering also the ongoing PR/issues for kicking off the Cluster API provider cluodstack 
https://github.com/kubernetes/community/pull/6427
https://github.com/kubernetes/org/issues/3279
https://github.com/kubernetes/org/issues/3318

**Comment by davidjumani** [comment]
Thanks @elmiko @fabriziopandini for your support!

**Comment by Damans227** [comment]
+1 Great work on the Cluster API Provider @davidjumani kudos!

**Comment by rohityadavcloud** [comment]
If I got the process right, I've raised a PR for this here - https://github.com/kubernetes/org/pull/3329
