### ISSUE TITLE
REQUEST: New membership for camilamacedo86

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes/org#3320]
### GitHub Username

camilamacedo86

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

pwittrock

### Sponsor 2

jberkhahn

### List of contributions to the Kubernetes project

I am an admin of Kubuilder from Kubernetes-sig. (https://github.com/kubernetes-sigs/kubebuilder/blob/master/OWNERS_ALIASES#L9)
We use prow to test the changes in the ci and we need to update the files in https://github.com/kubernetes/test-infra. Then, because of this, I am asking to be a member of the k8s org. 

See that I need this one to be able to move forward with: https://github.com/kubernetes/test-infra/pull/24814 and PRs like: https://github.com/kubernetes/test-infra/pull/25594

c/c @jberkhahn, @pwittrock

**Comment by palnabarun** [comment]
Hi @camilamacedo86 👋🏽, since you are already an @kubernetes-sigs member, you don't need to raise an org membership request. You can just PR yourself in to the org.yaml for the orgs that you want to get an invite of.

**Comment by palnabarun** [comment]
For example: https://github.com/kubernetes/org/pull/3316

**Comment by camilamacedo86** [comment]
Done :: https://github.com/kubernetes/org/pull/3325
