### ISSUE TITLE
REQUEST: New membership for Amulyam24

### ISSUE THREAD

**Issue by Amulyam24** [kubernetes/org#3328]
### GitHub Username

@Amulyam24

### Organization you are requesting membership in

kubernetes kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mkumatag

### Sponsor 2

@richardcase

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/490
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/506
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/565
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/579
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/577
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/472
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/555
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/536
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/540
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/340
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/590
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/339
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/450
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/541
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/582
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/528
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/487
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/570
https://github.com/kubernetes/test-infra/pull/25074
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/399
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/435

- Issues responded to
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/569
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/546
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/531
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/524
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/493
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/484
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/448
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/433
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/356
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/328

- SIG projects I am involved with
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud

**Comment by mkumatag** [comment]
+1 from me, thanks for all the contributions.

**Comment by richardcase** [comment]
+1 from me as well. Thanks for your contributions to CAPIBM

**Comment by mrbobbytables** [comment]
thank you for all your contributions so far :)

I've created PR #3366  to add you to the Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
