### ISSUE TITLE
REQUEST: New membership for jmguzik

### ISSUE THREAD

**Issue by jmguzik** [kubernetes/org#3331]
### GitHub Username

jmguzik

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@petr-muller

### Sponsor 2

@cjwagner

### List of contributions to the Kubernetes project

- PRs reviewed/authored
https://github.com/kubernetes/kubernetes/pull/99563
https://github.com/kubernetes/test-infra/pull/24267
https://github.com/kubernetes/test-infra/pull/24447
https://github.com/kubernetes/test-infra/pull/24457
https://github.com/kubernetes/test-infra/pull/24568
https://github.com/kubernetes/test-infra/pull/24847
https://github.com/kubernetes/test-infra/pull/25356
https://github.com/kubernetes/test-infra/pull/25387
https://github.com/kubernetes/test-infra/pull/25669
https://github.com/kubernetes/test-infra/pull/24594
https://github.com/kubernetes/test-infra/pull/24938
https://github.com/kubernetes/test-infra/pull/25299
https://github.com/kubernetes/test-infra/pull/25671
https://github.com/kubernetes/test-infra/pull/25357

- Issues responded to
https://github.com/kubernetes/test-infra/issues/24832
https://github.com/kubernetes/test-infra/issues/24024
https://github.com/kubernetes/test-infra/issues/23205
https://github.com/kubernetes/test-infra/issues/24123

**Comment by cjwagner** [comment]
+1 Thanks Jakub!

**Comment by mrbobbytables** [comment]
thank you for all your contributions so far :)

I've created PR #3366  to add you to the Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
