### ISSUE TITLE
REQUEST: New membership for DiptoChakrabarty

### ISSUE THREAD

**Issue by DiptoChakrabarty** [kubernetes/org#3335]
### GitHub Username

DiptoChakrabarty

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@killianmuldoon

### List of contributions to the Kubernetes project

- PRs authored
https://github.com/kubernetes-sigs/cluster-api/pull/6280
https://github.com/kubernetes-sigs/cluster-api/pull/6205
https://github.com/kubernetes-sigs/node-feature-discovery/pull/779
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3186
https://github.com/kubernetes-sigs/cluster-api/pull/6032
https://github.com/kubernetes-sigs/node-feature-discovery/pull/711
https://github.com/kubernetes-sigs/cluster-api/pull/5822
https://github.com/kubernetes-sigs/cluster-api/pull/5821
https://github.com/kubernetes-sigs/cluster-api/pull/5787
https://github.com/kubernetes-sigs/cluster-api/pull/5550
https://github.com/kubernetes-sigs/cluster-api/pull/5942
https://github.com/kubernetes-sigs/kustomize/pull/4364
https://github.com/kubernetes-sigs/cluster-api/pull/5558

- Issues Responded to
https://github.com/kubernetes-sigs/cluster-api/issues/6264
https://github.com/kubernetes-sigs/cluster-api/issues/6173
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3179
https://github.com/kubernetes-sigs/cluster-api/issues/5820
https://github.com/kubernetes-sigs/cluster-api/issues/5941
https://github.com/kubernetes-sigs/kustomize/issues/4322
https://github.com/kubernetes-sigs/cluster-api/issues/5546
https://github.com/kubernetes-sigs/node-feature-discovery/issues/566

- Sig Projects Involved with
https://github.com/kubernetes-sigs/cluster-api
https://github.com/kubernetes-sigs/cluster-api-provider-aws
https://github.com/kubernetes-sigs/kustomize/

**Comment by killianmuldoon** [comment]
+1 Thanks for all your recent contributions!

**Comment by sbueringer** [comment]
+1 Thank you very much.

But you'll need someone from another company too. (Killian and I are both working for VMWare)
>  I have verified that my sponsors are from different member companies

**Comment by mehabhalodiya** [comment]
+1, thanks for volunteering to help with the project! 🎉 
I have come across Dipto in Kubernetes 1.24 Release Team.

**Comment by mrbobbytables** [comment]
thank you for all your contributions so far :)

I've created PR #3366  to add you to the Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉

**Comment by DiptoChakrabarty** [comment]
Thank You everyone :)
