### ISSUE TITLE
REQUEST: New membership for Jeffwan

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes/org#334]
### GitHub Username
@Jeffwan

### Organization you are requesting membership in
@kubernetes @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mcrute 
- @k82cn 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/71238
https://github.com/kubernetes-sigs/kube-batch/pull/540
https://github.com/kubernetes-sigs/kube-batch/pull/535
https://github.com/kubernetes-sigs/kube-batch/pull/536
https://github.com/kubernetes/autoscaler/pull/1485
https://github.com/kubernetes/autoscaler/pull/1494
https://github.com/kubernetes/autoscaler/pull/1495

- Design Doc
https://github.com/kubernetes/autoscaler/pull/1562

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/68605
https://github.com/kubernetes/kubernetes/issues/66306
https://github.com/kubernetes/autoscaler/issues/1559
https://github.com/kubernetes/autoscaler/issues/1555
https://github.com/kubernetes/autoscaler/issues/1556
https://github.com/kubernetes/autoscaler/issues/1367
https://github.com/kubernetes/autoscaler/issues/1387
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/107

- SIG projects I am involved with
sig-scheduling
sig-autoscaling
sig-aws

**Comment by Jeffwan** [comment]
Please hold review for a while, I will try to find someone sponsor me.

**Comment by mcrute** [comment]
+1

**Comment by k82cn** [comment]
+1, looking forward to more your contribution in sig-scheduling & kube-batch :)

**Comment by Jeffwan** [comment]
Thanks @mcrute @k82cn I will. This is an area we really like to invest on.

**Comment by mrbobbytables** [comment]
Hey there @Jeffwan , thank you for all your contributions so far :) 

I've created PR #338   to add you to both the  @Kubernetes and @Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notifications for both of them.

Welcome to @kubernetes! 🎉

/assign

**Comment by Jeffwan** [comment]
@mrbobbytables Thanks a lot!
