### ISSUE TITLE
REQUEST: New membership for alexzielenski

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes/org#3343]
### GitHub Username

@alexzielenski

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@apelisse

### Sponsor 2

@sttts

## Subprojects
Different aspects of k8s ecosystem my work has touched:

- SIG api-machinery
- kube-openapi
- client-go
- controller-runtime

### Features
- https://github.com/kubernetes/kubernetes/pull/108992
- https://github.com/kubernetes/kube-openapi/pull/293
- https://github.com/kubernetes/kubernetes/pull/107507
- https://github.com/kubernetes/kube-openapi/pull/283
- https://github.com/kubernetes-sigs/controller-runtime/pull/1805

### Bugs/Cleanup
- https://github.com/kubernetes/kube-openapi/pull/282
- https://github.com/kubernetes/kubernetes/pull/108895
- https://github.com/kubernetes/website/pull/31337
- https://github.com/kubernetes/kubernetes/pull/107061
- https://github.com/kubernetes/kubernetes/pull/106195
- https://github.com/kubernetes/kubernetes/pull/106388

## Reviews:
I've also taken part in a review/discussion of some of the work of my teammates:

- https://github.com/kubernetes/kube-openapi/pull/292
- https://github.com/kubernetes/kube-openapi/pull/284
- https://github.com/kubernetes/kubernetes/pull/105916
- https://github.com/kubernetes/kubernetes/pull/109054

**Comment by sttts** [comment]
+1 from me.

**Comment by apelisse** [comment]
+1, and more!

**Comment by mrbobbytables** [comment]
thank you for all your contributions so far :)

I've created PR #3366  to add you to the Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
