### ISSUE TITLE
REQUEST: New membership for deejross

### ISSUE THREAD

**Issue by deejross** [kubernetes/org#3344]
### GitHub Username

@deejross

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@soltysh

### Sponsor 2

@eddiezane

## PRs Authored

* https://github.com/kubernetes/kubernetes/pull/105736
* https://github.com/kubernetes/kubernetes/pull/107083
* https://github.com/kubernetes/kubernetes/pull/107085
* https://github.com/kubernetes/kubernetes/pull/107148
* https://github.com/kubernetes/kubernetes/pull/107151
* https://github.com/kubernetes/kubernetes/pull/107354
* https://github.com/kubernetes/kubernetes/pull/108032

## PRs Reviewed

* https://github.com/kubernetes/kubernetes/pull/104901
* https://github.com/kubernetes/kubernetes/pull/105566
* https://github.com/kubernetes/kubernetes/pull/106824
* https://github.com/kubernetes/kubernetes/pull/107124

## Issues Responded To

* https://github.com/kubernetes/kubernetes/issues/105689
* https://github.com/kubernetes/kubernetes/issues/105735
* https://github.com/kubernetes/kubectl/issues/1046
* https://github.com/kubernetes/kubectl/issues/1171

**Comment by soltysh** [comment]
:+1: from my side

**Comment by eddiezane** [comment]
:+1: thanks for your contributions!

**Comment by mrbobbytables** [comment]
thank you for all your contributions so far :)

I've created PR #3366  to add you to the Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
