### ISSUE TITLE
REQUEST: New membership for 196Ikuchil

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes/org#3346]
### GitHub Username

@196Ikuchil

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@nasa9084

### Sponsor 2

@sanposhiho

### List of contributions to the Kubernetes project

PRs reviewed / authored
- https://github.com/kubernetes/website/pull/32084
- https://github.com/kubernetes/website/pull/32083
- https://github.com/kubernetes/website/pull/31938
- https://github.com/kubernetes/website/pull/31935
- https://github.com/kubernetes/website/pull/32678
- https://github.com/kubernetes/website/pull/31928 
- https://github.com/kubernetes/website/pull/31913
- https://github.com/kubernetes/website/pull/32581
- https://github.com/kubernetes/website/pull/32616 
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/64
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/81
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/102
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/104
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/108
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/111
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/112
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/119 
- etc..

Issues responded to
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/106

SIG projects I am involved with
- https://github.com/kubernetes-sigs/kube-scheduler-simulator

**Comment by sanposhiho** [comment]
Welcome to Kubernetes.
+1

**Comment by nasa9084** [comment]
Thank you for your contributing~
+1

**Comment by mrbobbytables** [comment]
thank you for all your contributions so far :)

I've created PR #3366  to add you to the Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
