### ISSUE TITLE
REQUEST: New membership for AlmogBaku

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes/org#3351]
### GitHub Username

@AlmogBaku

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@camilamacedo86

### Sponsor 2

@pwittrock

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/kubebuilder/pull/2561
- https://github.com/kubernetes-sigs/kubebuilder/pull/2586
- https://github.com/kubernetes-sigs/kubebuilder/pull/2581
- https://github.com/kubernetes/test-infra/pull/25775
- https://github.com/kubernetes-sigs/kubebuilder/pull/2552
- https://github.com/kubernetes-sigs/kubebuilder/pull/2548
- https://github.com/kubernetes-sigs/kubebuilder/issues/2388
- https://github.com/kubernetes-sigs/controller-runtime/pull/1785
- https://github.com/kubernetes-sigs/controller-runtime/pull/1795
- https://github.com/kubernetes-sigs/controller-runtime/pull/1822

Also:
- regular participant of the kubebuilder/controller-runtime bi-weekly meetings
- regular member and giving support on the kubebuilder/controller-runtime slack channels
- maintainer of kubernetes/heapster since 2015 until deprecation (owner of the elasticsearch sink)

**Comment by mrbobbytables** [comment]
thank you for all your contributions so far :)

I've created PR #3366  to add you to the Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
