### ISSUE TITLE
REQUEST: New membership for stlaz

### ISSUE THREAD

**Issue by stlaz** [kubernetes/org#3352]
### GitHub Username

@stlaz

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@s-urbaniak

### Sponsor 2

@enj

### List of contributions to the Kubernetes project

- reviewed:
  - https://github.com/kubernetes/community/pull/6542
  - https://github.com/kubernetes/kubernetes/pull/83459
  - https://github.com/kubernetes/kubernetes/pull/86383
- authored:
  - https://github.com/kubernetes/kubernetes/pull/65135
  - https://github.com/kubernetes/website/pull/9888
  - https://github.com/kubernetes/kubernetes/pull/65218
  - https://github.com/kubernetes/kubernetes/pull/67383
  - https://github.com/kubernetes/kubernetes/pull/71206
  - https://github.com/kubernetes/website/pull/11059
  - https://github.com/kubernetes/kubernetes/pull/95396
  - https://github.com/kubernetes/kubernetes/pull/102523
  - https://github.com/kubernetes/kubernetes/pull/105908
  - https://github.com/kubernetes/kubernetes/pull/109024
- commented on issues:
  - https://github.com/kubernetes/kubernetes/issues/81145

**Comment by s-urbaniak** [comment]
@stlaz has my full support on becoming a member of kubernetes organization 🎉 👍 💯

**Comment by enj** [comment]
I have worked closely with @stlaz for years.  He is easily one of my favorite people, both for being a deeply capable software engineer and a super nice guy.  The Kubernetes community would be lucky to have him as a member 🙂.

**Comment by mrbobbytables** [comment]
thank you for all your contributions so far :)

I've created PR #3366  to add you to the Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉

**Comment by stlaz** [comment]
Many thanks to both my sponsors and for accepting me to the org :bowing_man:
