### ISSUE TITLE
REQUEST: New membership for cprivitere

### ISSUE THREAD

**Issue by cprivitere** [kubernetes/org#3355]
### GitHub Username

@cprivitere

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tabbysable

### Sponsor 2

@detiber

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  - https://github.com/kubernetes/autoscaler/pull/4582
  - https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/307
  - https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/314
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/cluster-api-provider-packet

**Comment by detiber** [comment]
@cprivite has been a very valuable contributor for both kubernetes-sigs/cluster-api-provider-packet and the equinix metal provider for cluster autoscaler hosted at kubernetes/autoscaler. In addition to the PRs linked above, he has contributed in slack and community discussions related to improvements and architecture decisions related to both projects.

Huge +1 from me

**Comment by displague** [comment]
@cprivite is playing a big role in defining the roadmap for CAPP and other Equinix Kubernetes integrations. In addition to that, he's been diving into triage, review, feature work, and documentation.

I know it doesn't count, I'm in the same org as @detiber and @cprivite, but @cprivite has my +1 too.

**Comment by tabbysable** [comment]
@cprivite has been growing his leadership skills and involvement with Kubernetes for some time now, and I'm delighted to see that growth reflected in org membership and movement on the contributor ladder.

+1

/honk

**Comment by cprivitere** [comment]
For clarity, I renamed my github from @cprivite to @cprivitere today.

**Comment by mrbobbytables** [comment]
thank you for all your contributions so far :)

I've created PR #3366  to add you to the Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
