### ISSUE TITLE
REQUEST: Create logtools

### ISSUE THREAD

**Issue by RinkiyaKeDad** [kubernetes/org#3356]
### New repo, staging repo, or migrate existing

New repo

### Is it a staging repo?

no

### Requested name for new repository

logtools

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@ehashman, @logicalhan, @pohly, @serathius

### Who should have write access?

@ehashman, @logicalhan, @pohly, @serathius

### Who should be listed as approvers in OWNERS?

@ehashman, @logicalhan, @pohly, @dims, @serathius, @thockin

### Who should be listed in SECURITY_CONTACTS?

@ehashman, @logicalhan, @pohly, @dims, @serathius, @thockin

### What should the repo description be?

Tools related to log calls for Kubernetes.

### What SIG and subproject does this fall under?

structured-logging subproject under sig-instrumentation

### Please provide references to appropriate approval for this new repo

- Issue requesting for the creation of the repo by current maintainers: https://github.com/kubernetes/klog/issues/312
- Slack thread containing approval from SIG leads: https://kubernetes.slack.com/archives/C20HH14P7/p1648212251580789
- Pinging @ehashman @logicalhan again for explicit approval as SIG leads

**Comment by serathius** [comment]
lgtm

**Comment by pohly** [comment]
lgtm

**Comment by pohly** [comment]
@RinkiyaKeDad do you know whom to ping to get this PR merged?

**Comment by palnabarun** [comment]
Will take a look shortly.
/assign

**Comment by pohly** [comment]
I have a branch ready that I can merge into the new repo:
https://github.com/pohly/klog/commits/logcheck

It was created with this file as logcheck-replacement.txt and the command in the comment:
```
# git-filter-repo --path hack/tools --prune-degenerate=always --no-ff --path-rename hack/tools/go.mod:go.mod --path-rename hack/tools/go.sum:go.sum --path-rename hack/tools/logcheck:logcheck --replace-message logcheck-replacement.txt --replace-text logcheck-replacement.txt
regex:Merge pull request #([0-9]+)==>Merge pull request https://github.com/kubernetes/klog/pull/\1
k8s.io/klog/hack/tools==>k8s.io/logtools
hack/tools: ==>
```

**Comment by palnabarun** [comment]
The repo has been created: https://github.com/kubernetes-sigs/logtools

I've created #3496 to add the teams. Once it merges, I will add the teams to the repo. Also created https://github.com/kubernetes/community/pull/6700 to add logtools to sigs.yaml.

Once the above merges, I will close this issue.

**Comment by pohly** [comment]
Looks good so far, thanks.

Just for my own understanding: what is the difference between "admin" and "write" access for a repo (https://github.com/kubernetes/org/pull/3496/files)?

**Comment by palnabarun** [comment]
Admins get additional privileges like performing sensitive/destructive actions for example deleting issues, in comparison to people with write access.

**Comment by palnabarun** [comment]
All the PRs have merged and the repository permissions have been updated. 🎉 

/close
