### ISSUE TITLE
Create Github App and Github action to automate the bug-triage project beta

### ISSUE THREAD

**Issue by helayoty** [kubernetes/org#3357]
### Organization or Repo

kubernetes/kubernetes

### User affected

@release_team

### Describe the issue

We are working on migrating the bug triage spreadsheet into a [bug-triage](https://github.com/orgs/kubernetes/projects/80/views/1) Github Project Beta. For now, we migrated it manually. 

We found that to have the project updated automatically, it seems we need to create a new Github App and then Github Action as described [here](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects#github-actions-workflows). 

Can you please help us with the following:

- [ ] Create & install Github App in Kubernetes org (Needs owner)
- [ ]  Make sure we have permission to create a new Github action so we can update the Project.

@jyotimahapatra @gracenng @mrbobbytables @JamesLaverack @kubernetes/sig-release-leads

**Comment by justaugustus** [comment]
Tagging @omerbensaadon here to generate some ideas on the "right" approach.

Thoughts from https://twitter.com/stephenaugustus/status/1511775509792833541:

> Is there a concept of org-level Action?
> This is the kind of thing I'd want to enable on an org-level / across multiple repos that fit certain criteria e.g., all Kubernetes SIG Release repos

ref recent announcement:
- https://twitter.com/omer_bensaadon/status/1511733880046247943
- https://github.com/marketplace/actions/add-to-github-projects-beta

xref Slack discussions:
- https://kubernetes.slack.com/archives/C01672LSZL0/p1649262813461049
- https://kubernetes.slack.com/archives/C2C40FMNF/p1649174563749999?thread_ts=1648749214.458319&cid=C2C40FMNF

**Comment by justaugustus** [comment]
Also, highlighting Triage Party, which we have an instance of, but I'm not sure we're actively leveraging:
- https://release.triage.k8s.io/s/milestone
- https://github.com/kubernetes/k8s.io/tree/main/apps/triageparty-release

**Comment by omerbensaadon** [comment]
@justaugustus for now, you'd have to commit identical workflows to each of the repos you're hoping to target. 

In the future, we hope to allow Maintainers to be able to leverage this sort of thing across repo, we're just not quite there yet. 

This seems like the kind of thing which could be spun up as a separate repo and maintained by prow? 

Like you could create a repo called "workflows" and make edits to those files cascade across a list of pre-selected repos?

**Comment by omerbensaadon** [comment]
I'm reminded up label_sync, which does something similar? (though a bit less complicated)

**Comment by helayoty** [comment]
@omerbensaadon  does [this](https://github.com/actions/add-to-project) action needs Github App?

**Comment by omerbensaadon** [comment]
@helayoty unclear what you mean by this! 

The action needs to be a `yml` file in your target repo :)

**Comment by omerbensaadon** [comment]
Nope! 

Check out: https://docs.github.com/en/actions/quickstart

**Comment by cblecker** [comment]
It looks like the action referenced is just using the gh CLI tool to take an action based on a graphql query, correct?

**Comment by helayoty** [comment]
> It looks like the action referenced is just using the gh CLI tool to take an action based on a graphql query, correct?

@cblecker Yes, exactly.

Cc: @mrbobbytables

**Comment by mrbobbytables** [comment]
@helayoty just to confirm, at this point we're moving forward with that action? We don't need to setup a separate GitHub app? If so, I think next steps would be to open a PR on k/k to add the action.

**Comment by helayoty** [comment]
Well, the [linked](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects#github-actions-workflows) documentation from Github got updated

**Comment by helayoty** [comment]
> If the action is just a wrapper for the CLI, it's probably better to do this in prow.

I like the idea of having it as prow. Would you guide me on how to do that?

**Comment by helayoty** [comment]
As we discussed today in the **ContribEx GitHub Administration Subproject** meeting, we are going to implement that using prow job. 

//@mrbobbytables @Priyankasaggu11929
