### ISSUE TITLE
Automate the management of github team membership

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/org#336]
/kind design
/sig contributor-experience
/area github

I was unable to find an issue to point to for "we intend to one day automate team membership via peribolos" so now I've gone and created one.

I have used peribolos in the past to mass-create some teams for kubernetes-csi repos, but it wasn't a very friendly experience.  I used a file to generate the teams and populate members/maintainers, but I still had to go through and manually assign ACLs to repos.  

Ultimately I think we want to make this a self-service experience akin to test-infra's config/jobs directory, where files are sharded and OWNERS files allow sigs to control their thing.  But I hazily recall we have discussed in the past the idea of iterating with one massive file per org to start with.

There's also the question of whether we want to disallow team maintainers as a role, and instead just use members + OWNERS files here.  Today I can find no documented policy on who is supposed to be a Team Maintainer and what their responsibilities are.

/assign @cblecker @fejta 
as the two who have the most hands on experience and best chance of enumerating what remains to be done here

**Comment by fejta** [comment]
> are we sure we're not going to exhaust our tokens anymore?

😆

**Comment by nikhita** [comment]
> what's the process to add new teams?

Created https://github.com/kubernetes/community/issues/3102

**Comment by cblecker** [comment]
Yup, IMO.
/close
