### ISSUE TITLE
REQUEST: New membership for johannesfrey

### ISSUE THREAD

**Issue by johannesfrey** [kubernetes/org#3361]
### GitHub Username

@johannesfrey

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@tobiasgiese

### List of contributions to the Kubernetes project

- PRs reviewed / authored:
  - https://github.com/kubernetes-sigs/cluster-api/pull/6214
  - https://github.com/kubernetes-sigs/cluster-api/pull/6203
  - https://github.com/kubernetes-sigs/cluster-api/pull/6124
  - https://github.com/kubernetes-sigs/cluster-api/pull/6082
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/872

Also:

- Regular participant of the Cluster API weekly meetings

**Comment by sbueringer** [comment]
+1
Thx for your contributions so far !! (and for even more in the future :) )

**Comment by tobiasgiese** [comment]
+1 from me. Thanks for your great contributions so far!

**Comment by sbueringer** [comment]
cc @palnabarun sorry for the ping

Would be great if you can take a look, thank you very much!

(org membership is needed for the contributor summit registration)

**Comment by mrbobbytables** [comment]
thank you for all your contributions so far :)

I've created PR #3366  to add you to the Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
