### ISSUE TITLE
REQUEST: New membership for elbehery

### ISSUE THREAD

**Issue by Elbehery** [kubernetes/org#3365]
### GitHub Username

@elbehery

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jsafrane

### Sponsor 2

@jayunit100

### List of contributions to the Kubernetes project

- reviewed:
  - https://github.com/kubernetes/kubernetes/pull/101116
- authored:
  - https://github.com/kubernetes/kubernetes/pull/101067
  - https://github.com/kubernetes/kubernetes/pull/105788
  - https://github.com/kubernetes/kubernetes/pull/105787
  - https://github.com/kubernetes/kubernetes/pull/105786
  - https://github.com/kubernetes/kubernetes/pull/104551
  - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/912
  - https://github.com/kubernetes/kubernetes/issues/102248
  - https://github.com/kubernetes/kubernetes/pull/101213
  - https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/599
  - https://github.com/kubernetes/kubernetes/issues/101616
  - https://github.com/kubernetes/kubernetes/issues/101212
  - https://github.com/kubernetes/kubernetes/issues/101066

**Comment by jayunit100** [comment]
Lgtm have been working w mustafa on some etcd stuff and his insights are super useful for understanding how we should regression test it

**Comment by ameukam** [comment]
@Elbehery Support from 2 sponsors is required before we move forward with your application.

**Comment by Elbehery** [comment]
@ameukam  thanks a lot for your comment. 

I have two sponsors above, both of them have commented

**Comment by ameukam** [comment]
> @ameukam  thanks a lot for your comment. 
> 
> I have two sponsors above, both of them have commented 

Apologies. I was commenting on a different issue. I'll take care of the issue this week.

**Comment by Elbehery** [comment]
@ameukam  hello :) .. any updates here ?

**Comment by palnabarun** [comment]
@Elbehery -- thank you for all your contributions so far :)

I've created PR #3405 to add you to the orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
