### ISSUE TITLE
REQUEST: New membership for rdpsin

### ISSUE THREAD

**Issue by rdpsin** [kubernetes/org#3372]
### GitHub Username

@rdpsin

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jsafrane

### Sponsor 2

@AndyXiangLi

### List of contributions to the Kubernetes project

- PRs Reviewed/Authored

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1203
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1202
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1199
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1175
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1170
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1167
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1152

- Issues

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1201
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1190
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180

- SIG projects I'm involved in 

https://github.com/kubernetes-sigs/aws-ebs-csi-driver

**Comment by AndyXiangLi** [comment]
+1

**Comment by jsafrane** [comment]
+1
