### ISSUE TITLE
REQUEST: New membership for @mritunjaysharma394

### ISSUE THREAD

**Issue by mritunjaysharma394** [kubernetes/org#3376]
### GitHub Username

@mritunjaysharma394

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@saschagrunert

### List of contributions to the Kubernetes project

- PRs (https://github.com/kubernetes/release/pull/2215, https://github.com/kubernetes/website/pull/29569)
- Issues (https://github.com/kubernetes/kubernetes/issues/107690)
- Active member of kubernetes-sigs/wg-policy-prototypes (https://github.com/kubernetes-sigs/wg-policy-prototypes/pull/105)

**Comment by dims** [comment]
+1 from me. welcome @mritunjaysharma394

**Comment by saschagrunert** [comment]
+1 from me as well, great to have you as part of the community @mritunjaysharma394! 😊

**Comment by palnabarun** [comment]
@mritunjaysharma394 -- thank you for all your contributions so far :)

I've created PR #3405 to add you to the orgs. Once that gets merged, you should get a membership invite notification.

Welcome! :tada:

/assign
