### ISSUE TITLE
Migrate Existing Repo: Lustre CSI Driver Repo to k8s-sigs under provider-azure

### ISSUE THREAD

**Issue by vinli-cn** [kubernetes/org#3379]
### New repo, staging repo, or migrate existing

migrate existing

### Is it a staging repo?

no

### Requested name for new repository

azurelustre

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@andyzhangx, @vincentlimsft, @Justin-Jin, @eridai, @joe-atzinger

### Who should have write access?

@andyzhangx, @vincentlimsft, @Justin-Jin, @eridai, @joe-atzinger

### Who should be listed as approvers in OWNERS?

@vincentlimsft, @Justin-Jin, @eridai, @joe-atzinger

### Who should be listed in SECURITY_CONTACTS?

@vincentlimsft, @Justin-Jin, @eridai, @joe-atzinger

### What should the repo description be?

The CSI drive allows Kubernetes to use Lustre file system

### What SIG and subproject does this fall under?

provider-azure

### Please provide references to appropriate approval for this new repo

1. sig-cloud-provider Group approved this create repo request https://docs.google.com/document/d/1SpxvmOgHDhnA72Z0lbhBffrfe9inQxZkU9xqlafOW9k
2. Kubernetes code of conduct is adopted:  https://github.com/jusjin-org/azurelustre-csi-driver/blob/main/code-of-conduct.md
3. The repo uses Apache License v2:  https://github.com/jusjin-org/azurelustre-csi-driver/blob/main/LICENSE
4. CNCF CLA bot is enabled as a webhook on the repo.
5. All contributors have signed the CNCF individual or corporate CLA
6. The topic for the sponsoring SIG is added as k8s-sig-azure on the repository:  https://github.com/jusjin-org/azurelustre-csi-driver/blob/main/CONTRIBUTING.md
7. Fossabadge was added for a couple of 3rd party dependencies:  Add FOSSA passing shield, [@caniszczyk](https://github.com/caniszczyk) pls review third party deps

**Comment by mrbobbytables** [comment]
@vincentlimsft there isn't a sig-azure, did you mean sig-cloud-provider?
I also believe that repo is private, there is only 2 public repos I can see for Justin-Jin
We also have a number of other requirements for donated repos, they can be found here:
https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

**Comment by feiskyer** [comment]
LGTM (as SIG Cloud Provider and Provider Azure)

**Comment by vincentlimsft** [comment]
@mrbobbytables I did some cleanup in the repo and it's now ready for review, please have a look, thanks!

**Comment by vincentlimsft** [comment]
@justaugustus may I have your attention on this issue?

**Comment by andyzhangx** [comment]
> @vincentlimsft there isn't a sig-azure, did you mean sig-cloud-provider? I also believe that repo is private, there is only 2 public repos I can see for Justin-Jin We also have a number of other requirements for donated repos, they can be found here: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

@mrbobbytables could you help to migrate the repo?

> @vincentlimsft there isn't a sig-azure, did you mean sig-cloud-provider? I also believe that repo is private, there is only 2 public repos I can see for Justin-Jin We also have a number of other requirements for donated repos, they can be found here: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

hi @mrbobbytables, we have already completed the items, could you migrate this repo? thanks.

**Comment by andyzhangx** [comment]
could you approve this? Thanks.
@andrewsykim @cheftako @nckturner

**Comment by andyzhangx** [comment]
btw, repo name should be `azurelustre-csi-driver`

**Comment by nckturner** [comment]
LGTM

**Comment by joe-atzinger** [comment]
Thanks, @mrbobbytables!  I've approved the PRs and assigned them to @andyzhangx for merging.

**Comment by andyzhangx** [comment]
@mrbobbytables so finally the repo admin should be maintained by this file, right? https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/provider-azure/teams.yaml

**Comment by mrbobbytables** [comment]
@andyzhangx that is correct - once the PR I have open is merged and the teams added they will be controlled via that file

**Comment by vinli-cn** [comment]
@mrbobbytables @andyzhangx 
I have closed the two PRs, please add [joe-atzinger](https://github.com/joe-atzinger) and myself as repo admin. thanks!

**Comment by mrbobbytables** [comment]
last remaining PR has been merged, going to go ahead and close this out. 👍 

/close
