### ISSUE TITLE
Enable Google Cloud build on kubernetes/minikube repo

### ISSUE THREAD

**Issue by medyagh** [kubernetes/org#3388]
Hello I would like to enable Google Cloud Build CI on minikube repo, I created an issue here https://github.com/kubernetes/org/issues/2716

 but I was directed to this repo. I hope I am requesting at the right place:

Organization or repository
kubernetes/minikube

Name of integration
google cloud build

Link to integration website
https://cloud.google.com/build

Describe what is attempting to be accomplished
we would like to be able to use google cloud build in minikube ci/ci process, so our internal jenkins can be moved to a cloud build yaml config in github, without having to move our google cloud credentials (used for publishing binaries and images) outside google cloud project .

Additional context for request
kubernetes/minikube#11436

**Comment by cblecker** [comment]
/remove-lifecycle frozen
/close

Closing stale issue. please reopen if there is still discussion.
