### ISSUE TITLE
REQUEST: New membership for dsu-igeek

### ISSUE THREAD

**Issue by dsu-igeek** [kubernetes/org#3389]
### GitHub Username

dsu-igeek

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@yuxiangqian

### List of contributions to the Kubernetes project

- I've been active in the Data Protection Working Group and am one of the authors of the DP Working Group's White Paper
- Currently working on the Changed Block Tracking proposal in the DP Working Group
- As the Velero architect I've been working on Kubernetes data protection (backup/restore) and supporting the K8s community as users of Velero

**Comment by xing-yang** [comment]
+1
Thanks Dave for your contribution to the DP WG!

**Comment by xing-yang** [comment]
Can you add a link to the DP WG white paper and DP WG agenda and CBT proposal?

**Comment by yuxiangqian** [comment]
+1
Dave has been continuously contributing into the data protection working group !

**Comment by dsu-igeek** [comment]
DP Working Group White Paper - https://github.com/kubernetes/community/blob/master/wg-data-protection/data-protection-workflows-white-paper.md

DP Working Group agenda - https://docs.google.com/document/d/15tLCV3csvjHbKb16DVk-mfUmFry_Rlwo-2uG6KNGsfw/edit?usp=sharing

CBT Agenda - https://docs.google.com/document/d/19ExU8VCIEYhmOFeYs2NtWoA13iG7Sp0RvrXpyvmE-fE/edit?usp=sharing

CBT Proposal - https://hackmd.io/VN_TBl3NSLaeiD8BLeeCfw

**Comment by dsu-igeek** [comment]
Thanks!

On May 5, 2022, at 8:58 AM, Nabarun Pal ***@***.***> wrote:

﻿
CAUTION - This email originated from outside of Veeam. Do not click links or open attachments unless you recognize the sender.


@dsu-igeek<https://github.com/dsu-igeek> -- thank you for all your contributions so far :)

I've created PR #3405<https://github.com/kubernetes/org/pull/3405> to add you to the orgs. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉

/assign
