### ISSUE TITLE
REQUEST: New membership for xunpan

### ISSUE THREAD

**Issue by xunpan** [kubernetes/org#339]
### GitHub Username
@xunpan

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev, https://groups.google.com/forum/#!forum/kubernetes-sig-multicluster)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @marun
- @gyliu513

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=is%3Apr+author%3Axunpan+archived%3Afalse+is%3Aclosed
- Issues responded to
https://github.com/search?q=is%3Aissue+author%3Axunpan+archived%3Afalse+is%3Aclosed

- SIG projects I am involved with
kubernetes-sigs/federation-v2, kubernetes-incubator/external-dns

**Comment by gyliu513** [comment]
+1, thanks @xunpan for your great contribution to Kubernetes Federation V2!

**Comment by xunpan** [comment]
@gyliu513 @marun 
Thanks a lot for your support. I'm glad to contribute more for federation v2 project.

**Comment by mrbobbytables** [comment]
Hey there @xunpan thank you for all the work you've put into the federation project :) 

I've created PR #340 to add you to the @kubernetes-sigs org. Once that gets merged, you should get a membership invite notification. 

Welcome to @kubernetes-sigs! 🎉 

/assign
