### ISSUE TITLE
REQUEST: New membership for phuongatemc

### ISSUE THREAD

**Issue by phuongatemc** [kubernetes/org#3390]
### GitHub Username

phuongatemc

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@yuxiangqian

### List of contributions to the Kubernetes project

- I've been active in the Data Protection Working Group
- I am one of the authors of the DP Working Group's White Paper  https://github.com/kubernetes/community/blob/master/wg-data-protection/data-protection-workflows-white-paper.md
- I am currently working on the Changed Block Tracking proposal in the DP Working Group https://hackmd.io/VN_TBl3NSLaeiD8BLeeCfw and CBT weekely syncup Meeting notes: https://docs.google.com/document/d/19ExU8VCIEYhmOFeYs2NtWoA13iG7Sp0RvrXpyvmE-fE/edit#
- I am also contributing to Velero's features such as Backup ResourceOrder etc.  https://github.com/vmware-tanzu/velero/pull/2724

**Comment by xing-yang** [comment]
+1
Thank you @phuongatemc for your contributions to DP WG!

**Comment by xing-yang** [comment]
Can you add links to DP white paper, DP agenda doc, and CBT doc (meeting minutes, proposal, etc.).

**Comment by phuongatemc** [comment]
- Data protection White Paper: https://github.com/kubernetes/community/blob/master/wg-data-protection/data-protection-workflows-white-paper.md
- Changed Block Tracking (aka Differential Snapshot API) proposal: https://hackmd.io/VN_TBl3NSLaeiD8BLeeCfw
- CBT weekely syncup Meeting notes: https://docs.google.com/document/d/19ExU8VCIEYhmOFeYs2NtWoA13iG7Sp0RvrXpyvmE-fE/edit#
- Enhancement to Velero Backup with order resources: https://github.com/vmware-tanzu/velero/pull/2724

**Comment by chris-short** [comment]
Can you update the original request with these links? That'd be most helpful. Thank you.

**Comment by yuxiangqian** [comment]
+1

**Comment by Sea-n** [comment]
Hey @phuongatemc,

As [previous comment](https://github.com/kubernetes/org/issues/3390#issuecomment-1179108889) said, can you add those issues and PRs link to the description of this PR?

It will help your membership review more smooth.

**Comment by phuongatemc** [comment]
@Sea-n  Updated.

**Comment by savitharaghunathan** [comment]
Hi @phuongatemc 👋 Thank you for all your contributions!

I've created PR https://github.com/kubernetes/org/pull/3633 to add you to the k8s organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by phuongatemc** [comment]
Thank you!
