### ISSUE TITLE
REQUEST: New membership for landreasyan

### ISSUE THREAD

**Issue by landreasyan** [kubernetes/org#3392]
### GitHub Username

@landreasyan

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@edreed

### List of contributions to the Kubernetes project

- PRs:
[Scheduler extender implementation](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/37c088d7076743ee18436c0f83f78a7414aa5924)
[bug: Adding supported VolumeCapabilites verification check to CSI RPC… · kubernetes-sigs/azuredisk-csi-driver@71ccbd8 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/71ccbd8b4acb49923bb263448ad0033e26e39f45)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/71ccbd8b4acb49923bb263448ad0033e26e39f45)
[bug: disabling snapshot crd creation on latest v2 side by side instal… · kubernetes-sigs/azuredisk-csi-driver@70a9bcf (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/70a9bcfbecb25360cadbe5e1d1630da19bf28a33)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/70a9bcfbecb25360cadbe5e1d1630da19bf28a33)
[Bug: Filtering replica attachment for a pod when assessing node capac… · kubernetes-sigs/azuredisk-csi-driver@43124a4 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/43124a4ceece7ace0a20d8e60dbd2da7cd99b14c)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/43124a4ceece7ace0a20d8e60dbd2da7cd99b14c)
[bug: Creating an azvolume cri for pre-prov disk cases. (#237) · kubernetes-sigs/azuredisk-csi-driver@050eb80 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/050eb80fd1764cc68e4f6f441da694cc0d19106c)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/050eb80fd1764cc68e4f6f441da694cc0d19106c)
[bug: Adding PVC cleanup to SS cleanup logic, fixing concurrency issu… · kubernetes-sigs/azuredisk-csi-driver@7371c30 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/7371c301c51d97b8c7a01a6880be7f07f7774d95)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/7371c301c51d97b8c7a01a6880be7f07f7774d95)
[Fixing issues causing unnecessary driver restart on scale. (#386) · kubernetes-sigs/azuredisk-csi-driver@a3bae8b (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/a3bae8bbde9535331130015455444e69fb9d657f)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/a3bae8bbde9535331130015455444e69fb9d657f)
[Fix: Adding replica attachments count to the filtering of nodes based… · kubernetes-sigs/azuredisk-csi-driver@50dc0c8 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/50dc0c84d9b31e8c2cf959b0e36029fa1d3b97b9)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/50dc0c84d9b31e8c2cf959b0e36029fa1d3b97b9)
[chore: Updating kube-scheduler version in the scheduler extender setu… · kubernetes-sigs/azuredisk-csi-driver@6e3aac5 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/6e3aac563beb1ca013faa1ab5773407617d2335b)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/6e3aac563beb1ca013faa1ab5773407617d2335b)
[bug: Syncing cloud provider initialization changes between v1 and v2 … · kubernetes-sigs/azuredisk-csi-driver@d1e8e4a (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/d1e8e4ab19a722b2929afc4697b3b1ef30026e28)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/d1e8e4ab19a722b2929afc4697b3b1ef30026e28)
[feat: Adding support for Dangling attachment error to V2 driver (#271) · kubernetes-sigs/azuredisk-csi-driver@4bbbbd3 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/4bbbbd3555a3fec95e76fe8d99d010c6d9a92f35)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/4bbbbd3555a3fec95e76fe8d99d010c6d9a92f35)
[feat: Refactoring and merging v1, v2 util functions (#208) · kubernetes-sigs/azuredisk-csi-driver@23c07d2 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/23c07d2ddb7accf6f90abe182deafe9970df6714)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/23c07d2ddb7accf6f90abe182deafe9970df6714)
[fix: Updating namespace for controllers and minor fixes to create rep… · kubernetes-sigs/azuredisk-csi-driver@3cf15e2 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/3cf15e29b2c775dfd6e552f5106b0fbc9744c03f)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/3cf15e29b2c775dfd6e552f5106b0fbc9744c03f)
[feat: Update default caching value. Keep the default case same as V1 … · kubernetes-sigs/azuredisk-csi-driver@b7cb0f1 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/b7cb0f1bc206d035625dd8a5f9e057ebbdf2892d)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/b7cb0f1bc206d035625dd8a5f9e057ebbdf2892d)
[Making scheduler extender the default scheduler for e2e tests in v2 d… · kubernetes-sigs/azuredisk-csi-driver@3580212 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/3580212f2f690d50fa591882c158e7bbd13d4c15)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/3580212f2f690d50fa591882c158e7bbd13d4c15)
[bug and test: Fixed extender logic to us pv name. Added perf testing.… · kubernetes-sigs/azuredisk-csi-driver@3badb59 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/3badb59959b5d7f45670e70284e535c72c9d78fd)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/3badb59959b5d7f45670e70284e535c72c9d78fd)
[Provisioner bug fixes (#53) · kubernetes-sigs/azuredisk-csi-driver@5422820 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/5422820c62b9160f9e94e846b4903d258981ef34)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/5422820c62b9160f9e94e846b4903d258981ef34)
[feat: Scheduler extender caching and prometheus. (#47) · kubernetes-sigs/azuredisk-csi-driver@22f9c03 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/22f9c032cc0459be2e71930495cba1127feaae3e)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/22f9c032cc0459be2e71930495cba1127feaae3e)
- Smaller PRs:
[Refactoring constants into a separate package · kubernetes-sigs/azuredisk-csi-driver@3efbcba (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/3efbcbaf74a440c4fea22cb354c0c95b72586910)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/3efbcbaf74a440c4fea22cb354c0c95b72586910)
[Refactoring utilities functions to a separate folder. · kubernetes-sigs/azuredisk-csi-driver@abd1f0d (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/abd1f0ddd4f6b3c1227ab51b8b64f267b7f3a065)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/abd1f0ddd4f6b3c1227ab51b8b64f267b7f3a065)
[chore: Removing extra attach operation retry on AttachmentFailed. (#293) · kubernetes-sigs/azuredisk-csi-driver@8d9b9ac (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/8d9b9ac0b33a273149ee129c8b15db64b2da6122)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/8d9b9ac0b33a273149ee129c8b15db64b2da6122)
[fix: Fix recovery for pv-s with no claims. (#290) · kubernetes-sigs/azuredisk-csi-driver@b18c8f5 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/b18c8f5731324cbeba1b5d2dc6560a86484c733f)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/b18c8f5731324cbeba1b5d2dc6560a86484c733f)
[Updating bolilerplate.py to recognize new version of go build tags. · kubernetes-sigs/azuredisk-csi-driver@eeaae31 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/eeaae31558efb55545df852f92b29d74107ae051)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/eeaae31558efb55545df852f92b29d74107ae051)
- Tests:
[Adding e2e test runs to volume-data-source-validator repo. by landreasyan · Pull Request #25663 · kubernetes/test-infra (](https://github.com/kubernetes/test-infra/pull/25663)[github.com](http://github.com/)[)](https://github.com/kubernetes/test-infra/pull/25663)
[Adding external e2e tests to GitHub actions (#341) · kubernetes-sigs/azuredisk-csi-driver@082f3b7](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/082f3b76f99c41ad6b11da0652cf4b4d2a791d38)
[Creating a suite and automating scale testing (#260) · kubernetes-sigs/azuredisk-csi-driver@e9c81c1 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/e9c81c18de3a5886020b84f82d88ed8c4f335efa)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/e9c81c18de3a5886020b84f82d88ed8c4f335efa)
[Adding a workflow for weekly scale test run. (#350) · kubernetes-sigs/azuredisk-csi-driver@5cbf497 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/5cbf497a8b70a0d577e0528e76adc66840136363)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/5cbf497a8b70a0d577e0528e76adc66840136363)
[test: Adding premium disk support to ss and deployments on e2e tests.… · kubernetes-sigs/azuredisk-csi-driver@1c4429b (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/1c4429bc17d8b1b157018cab637e13618c8319b6)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/1c4429bc17d8b1b157018cab637e13618c8319b6)
[chore: Refactoring test resources (#397) · kubernetes-sigs/azuredisk-csi-driver@2edc859 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/2edc85964ae6da1505c431ec01d3f63f2fe49299)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/2edc85964ae6da1505c431ec01d3f63f2fe49299)
[test: Adding e2e tests for AzDiskSchedulerExtender (#19) · kubernetes-sigs/azuredisk-csi-driver@b649e09 (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/b649e09033d119af763bd88955b5098dd048fe7f)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/b649e09033d119af763bd88955b5098dd048fe7f)
- Issues and comments:
[Add initial E2E tests for `AnyVolumeDatasource` feature by mkimuram · Pull Request #108664 · kubernetes/kubernetes (](https://github.com/kubernetes/kubernetes/pull/108664#issuecomment-1087928055)[github.com](http://github.com/)[)](https://github.com/kubernetes/kubernetes/pull/108664#issuecomment-1087928055)
[refine resize e2e test · Issue #716 · kubernetes-sigs/azuredisk-csi-driver (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/716)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/716)
[add dangling error e2e test · Issue #500 · kubernetes-sigs/azuredisk-csi-driver (](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/500)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/500)

**Comment by edreed** [comment]
+1

**Comment by xing-yang** [comment]
+1
Thanks @landreasyan for your contributions!
