### ISSUE TITLE
REQUEST: New membership for kinzhi

### ISSUE THREAD

**Issue by kinzhi** [kubernetes/org#3397]
### GitHub Username

@kinzhi

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tengqm

### Sponsor 2

@mengjiao-liu

### List of contributions to the Kubernetes project

- PR: https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3Akinzhi

- Sig Projects: https://github.com/kubernetes/website

**Comment by mengjiao-liu** [comment]
+1
Thank you for your contribution!

**Comment by mengjiao-liu** [comment]
> @mengjiao-liu -- can you please confirm your affiliation? I couldn't gather much info from your GitHub profile.

Got it, I've updated it.

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
