### ISSUE TITLE
REQUEST: New membership for houjun41544

### ISSUE THREAD

**Issue by houjun41544** [kubernetes/org#3398]
### GitHub Username

@houjun41544

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei 

### Sponsor 2

@chendave

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/kubernetes/pull/108363
- https://github.com/kubernetes/kubernetes/pull/107241
- https://github.com/kubernetes/kubernetes/pull/106421
- https://github.com/kubernetes/kubernetes/pull/100479
- https://github.com/kubernetes/kubernetes/pull/100370
- https://github.com/kubernetes/kubernetes/pull/101793
- https://github.com/kubernetes/kubernetes/pull/101297
- https://github.com/kubernetes/kubernetes/pull/100226
- https://github.com/kubernetes/kubernetes/pull/96946
- https://github.com/kubernetes/kubernetes/pull/100479
- https://github.com/kubernetes/website/pull/27040

**Comment by Huang-Wei** [comment]
+1

**Comment by chendave** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
