### ISSUE TITLE
REQUEST: New membership for rootsongjc

### ISSUE THREAD

**Issue by rootsongjc** [kubernetes/org#34]
### GitHub Username

@rootsongjc

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xiangpengzhao
- @zhangxiaoyu-zidif

### List of contributions to the Kubernetes project
SIG projects I am involved with
- sig-docs (k/kubernetes-docs-zh) https://github.com/kubernetes/kubernetes-docs-zh
- https://github.com/rootsongjc/kubernetes-handbook/

**Comment by xiangpengzhao** [comment]
+1
Jimmy is definitely active on contributing to docs localization in Chinese and sharing his experience on Kubernetes.

**Comment by interma** [comment]
Glad to see Jimmy can become a k8s member, his docs-zh is very helpful! 👍

**Comment by cblecker** [comment]
Invite sent. Welcome to @kubernetes!
