### ISSUE TITLE
Request to get write permissions on aws-iam-authenticator

### ISSUE THREAD

**Issue by jyotimahapatra** [kubernetes/org#3407]
### Organization or Repo

https://github.com/kubernetes-sigs/aws-iam-authenticator

### User affected

jyotimahapatra

### Describe the issue

I'm spending more time in https://github.com/kubernetes-sigs/aws-iam-authenticator and im already in [OWNERS](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/OWNERS#L14) file. I'd like to create releases and based on https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization it looks like i need to have `write` permission to be able to create releases. Can I have the permission ?

**Comment by nckturner** [comment]
I approve granting write to @jyotimahapatra on [kubernetes-sigs/aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator)

**Comment by BenTheElder** [comment]
FYI you can file a PR to one of these teams yourself and be approved by the OWNERS of the directory without depending on the folks running the whole org 😅 

Write access:
https://github.com/kubernetes/org/blob/8cffdd1463d135649e16147aa8d630f475431fe7/config/kubernetes-sigs/sig-cloud-provider/teams.yaml#L40-L42

Admin access:
https://github.com/kubernetes/org/blob/8cffdd1463d135649e16147aa8d630f475431fe7/config/kubernetes-sigs/sig-cloud-provider/teams.yaml#L32-L34

OWNERS:

https://github.com/kubernetes/org/blob/8cffdd1463d135649e16147aa8d630f475431fe7/config/kubernetes-sigs/sig-cloud-provider/OWNERS#L5-L6

**Comment by jyotimahapatra** [comment]
Thank you!! I wasn't familiar, I'll do that

**Comment by jyotimahapatra** [comment]
#3435
