### ISSUE TITLE
REQUEST: New membership for RomanBednar

### ISSUE THREAD

**Issue by RomanBednar** [kubernetes/org#3410]
### GitHub Username

@RomanBednar

### Organization you are requesting membership in

kubernetes, kubernetes-csi, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jsafrane

### Sponsor 2

@andyzhangx

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pull/108628
https://github.com/kubernetes/kubernetes/pull/108561
https://github.com/kubernetes/kubernetes/pull/108000
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/612
https://github.com/kubernetes-csi/external-attacher/pull/342

**Comment by RomanBednar** [comment]
@jsafrane and @andyzhangx Can you please review and +1 to confirm the sponsorship?

**Comment by andyzhangx** [comment]
+1

**Comment by jsafrane** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
