### ISSUE TITLE
REQUEST: New membership for jasonbraganza

### ISSUE THREAD

**Issue by jasonbraganza** [kubernetes/org#3413]
### GitHub Username

jasonbraganza

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@chaodaiG

### List of contributions to the Kubernetes project

- PRs authored
    - https://github.com/kubernetes/kubernetes/pull/109859
    - https://github.com/kubernetes/test-infra/pull/26203
    - https://github.com/kubernetes/test-infra/pull/26204
    - https://github.com/kubernetes/test-infra/pull/26205
    - https://github.com/kubernetes/test-infra/pull/26206
    - https://github.com/kubernetes/test-infra/pull/26207
    - https://github.com/kubernetes/sig-release/pull/1901 
- Issues worked upon
    - https://github.com/kubernetes/test-infra/issues/13129#issuecomment-1118269978

**Comment by dims** [comment]
+1 from me!

**Comment by Priyankasaggu11929** [comment]
+1. Welcome! 🙂 

/woof

**Comment by chaodaiG** [comment]
+1, thank you for contribution, and welcome!

**Comment by jasonbraganza** [comment]
Thank you all, so so much :)

**Comment by fejta** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
