### ISSUE TITLE
REQUEST: New membership for JohnTitor

### ISSUE THREAD

**Issue by JohnTitor** [kubernetes/org#3418]
### GitHub Username

@JohnTitor

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@ahmetb

#### contributions

PRs I opened: https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3AJohnTitor+org%3Akubernetes+org%3Akubernetes-sigs
Issues I'm involved in: https://github.com/issues?q=is%3Aissue+is%3Aopen+archived%3Afalse+commenter%3A%40me+org%3Akubernetes+org%3Akubernetes-sigs

#### SIGs I'm involved in

sig-testing, sig-cli

**Comment by ahmetb** [comment]
+1

**Comment by dims** [comment]
+1 from me. Sorry missed this earlier

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
