### ISSUE TITLE
new repo: kubernetes-csi/csi-release-tools

### ISSUE THREAD

**Issue by pohly** [kubernetes/org#342]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
csi-release-tools

### Which Organization should it reside
kubernetes-csi

### If not a staging repo, who should have admin access
@saad-ali @msau42 

### If not a staging repo, who should have write access
@saad-ali @msau42 

### If a new repo, who should be listed as approvers in OWNERS
@saad-ali @msau42 @pohly

### If a new repo, who should be listed in SECURITY_CONTACTS
@saad-ali @msau42

### What should the repo description be
shared build and test files used by kubernetes-csi projects

### What SIG and subproject does this fall under in sigs.yaml
part of the CSI working group in SIG-storage

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

Discussed and approved on Wednesday, January 9, 2019, in the CSI standup meeting (https://docs.google.com/document/d/1_hvq3nleqQEYatH9V_Gfep39jMzaFJRSN2ioA0PFq-Q/edit#heading=h.8mpy2holi18b).

### Additional context for request
A prototype for the content of the new repo is here: https://github.com/pohly/csi-build-rules/

The less boilerplate files we can have in the repo the better, because the entire repo will be copied into a sub-directory of other kubernetes-csi repos, for example like this: https://github.com/pohly/external-attacher/commits/build-rules

**Comment by cblecker** [comment]
@saad-ali can you approve for sig-storage?

**Comment by saad-ali** [comment]
Approved on behalf of SIG storage.

**Comment by spiffxp** [comment]
>The less boilerplate files we can have in the repo the better, because the entire repo will be copied into a sub-directory of other kubernetes-csi repos

Unfortunately because this is its own repo it will still need boilerplate from kubernetes-template-project.

**Comment by spiffxp** [comment]
/close
I believe this is now done. https://github.com/kubernetes-csi/csi-release-tools

@pohly Extremely sorry for the delay.  Please followup here if there is anything amiss.
