### ISSUE TITLE
REQUEST: New membership for windsonsea

### ISSUE THREAD

**Issue by windsonsea** [kubernetes/org#3423]
### GitHub Username

@windsonsea

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mengjiao-liu

### Sponsor 2

@tengqm

### List of contributions to the Kubernetes project

- PRs authored: [#33677](https://github.com/kubernetes/website/pull/33677), [#33648](https://github.com/kubernetes/website/pull/33648), [#33626](https://github.com/kubernetes/website/pull/33626), [#33616](https://github.com/kubernetes/website/pull/33616), [#33568](https://github.com/kubernetes/website/pull/33568) ([see PRs I authored recently](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Awindsonsea+is%3Aclosed))
- Issues responded to: [#33474](https://github.com/kubernetes/website/issues/33474), [#33475](https://github.com/kubernetes/website/issues/33475), [#33646](https://github.com/kubernetes/website/issues/33646)
- SIG projects I am involved with: [kubernetes/website](https://kubernetes.io/docs/home/)

**Comment by mengjiao-liu** [comment]
+1

**Comment by tengqm** [comment]
+1
Looking forward to more solid contributions from you.

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
