### ISSUE TITLE
REQUEST: New membership for oprinmarius

### ISSUE THREAD

**Issue by oprinmarius** [kubernetes/org#3424]
### GitHub Username

oprinmarius

### Organization you are requesting membership in

kubernetes, kubernetes-csi, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jsturtevant

### Sponsor 2

@claudiubelu

### List of contributions to the Kubernetes project

- Issues responded to/opened:
  - kubernetes/kubernetes
    - https://github.com/kubernetes/kubernetes/issues/108621
  - kubernetes/perf-tests
    - https://github.com/kubernetes/perf-tests/issues/2035
- PRs authored / reviewed:
    - kubernetes/perf-tests
      - https://github.com/kubernetes/perf-tests/pull/2034
      - https://github.com/kubernetes/perf-tests/pull/2041
      - https://github.com/kubernetes/perf-tests/pull/2043
      - https://github.com/kubernetes/perf-tests/pull/2051
      - https://github.com/kubernetes/perf-tests/pull/2061
    - kubernetes/test-infra
      - https://github.com/kubernetes/test-infra/pull/26090
      - https://github.com/kubernetes/test-infra/pull/26194
      - https://github.com/kubernetes/test-infra/pull/26198
      - https://github.com/kubernetes/test-infra/pull/26252
      - https://github.com/kubernetes/test-infra/pull/26279
      - https://github.com/kubernetes/test-infra/pull/26286

- SIG projects I am involved in:
  - SIG Windows

**Comment by oprinmarius** [comment]
cc @marosset

**Comment by claudiubelu** [comment]
+1 from me

He's been active on a few sig-windows related projects and his contributions will help us improve the quality of Windows in Kubernetes. :)

**Comment by marosset** [comment]
+1 from me

@oprinmarius  has been active in our community meetings and has made great progress in adding support for Windows nodes in the perf-tests repo

**Comment by jsturtevant** [comment]
+1 

Thanks for all the work on the perf tests!

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
