### ISSUE TITLE
REQUEST: New membership for zaunist

### ISSUE THREAD

**Issue by zaunist** [kubernetes/org#3427]
### GitHub Username

@zaunist

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tengqm

### Sponsor 2

@mengjiao-liu

### List of contributions to the Kubernetes project

- PRs authored / reviewed:
  - https://github.com/kubernetes/website/pull/33729
  - https://github.com/kubernetes/website/pull/33670
  - https://github.com/kubernetes/website/pull/33634
  - https://github.com/kubernetes/website/pull/33172
  - https://github.com/kubernetes/website/pull/33035
  - https://github.com/kubernetes/website/pull/33004
  - https://github.com/kubernetes/website/pull/32865
  - https://github.com/kubernetes/website/pull/32719
  - https://github.com/kubernetes/website/pull/32716
  - https://github.com/kubernetes/website/pull/32714
  - https://github.com/kubernetes/website/pull/32710
  - https://github.com/kubernetes/website/pull/32707
  - https://github.com/kubernetes/website/pull/32671
  - https://github.com/kubernetes/website/pull/32642
  - https://github.com/kubernetes-sigs/kind/pull/2676
- SIG projects I am involved in:
  - sig-docs

**Comment by tengqm** [comment]
+1 Looking forward to see more contributions from you, @zaunist

**Comment by mengjiao-liu** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
