### ISSUE TITLE
REQUEST: New membership for upodroid

### ISSUE THREAD

**Issue by upodroid** [kubernetes/org#3429]
### GitHub Username

upodroid

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

ameukam

### Sponsor 2

thockin

### List of contributions to the Kubernetes project
K8s PRs:
- https://github.com/kubernetes/test-infra/pull/26046
- https://github.com/kubernetes/test-infra/pull/25582
- https://github.com/kubernetes/k8s.io/pull/3407

I'm a member of the Knative's Productivity WG(the project's combined equivalent of k8s-infra, testing SIGs) and owner of that project's GCP Infra. We share similar tooling and cloud provider and I'm looking forward to improving the project's infra and make some progress on the backlog.

My initial scope will be to help ameukam with k8s-infra project work and then possibly sig-release-engineering and sig-testing with GCP/K8s/infra stuff.

**Comment by upodroid** [comment]
@ameukam @thockin

oops, forgot to tag you properly on the issue body

**Comment by ameukam** [comment]
+1. Help is welcome expend efforts between sig-release and sig-testing

**Comment by thockin** [comment]
+1

**Comment by upodroid** [comment]
Thank you
