### ISSUE TITLE
Repo Creation: k-sigs/metrics-scraper

### ISSUE THREAD

**Issue by jeefy** [kubernetes/org#343]
### New Repo, Staging Repo, or migrate existing
New Repository

### Requested name for new repository
dashboard-metrics-scraper

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@jeefy, @maciaszczykm, @floreks, @bryk 

### If not a staging repo, who should have write access
@jeefy, @maciaszczykm, @floreks, @bryk 

### If a new repo, who should be listed as approvers in OWNERS
@jeefy, @maciaszczykm, @floreks, @bryk 

### If a new repo, who should be listed in SECURITY_CONTACTS
@jeefy, @maciaszczykm, @floreks, @bryk 

### What should the repo description be
Container to scrape, store, and retrieve a window of time from the Metrics Server.

### What SIG and subproject does this fall under in sigs.yaml
sig-ui

### Approvals
(Under Jan 3rd)
https://docs.google.com/document/d/1PwHFvqiShLIq8ZpoXvE3dSUnOv1ts5BTtZ7aATuKd-E/edit#

### Additional context for request
With heapster deprecated, this is a short-term (6-9mo) solution to provide metrics/sparklines to the dashboard by scraping the Metrics API and storing a window of data. The intent is, once this is in place, to build support/integration for other metrics providers (Prometheus to start) and phase this out. Ping me here (or in Slack) with any additional questions. :) Thanks!

**Comment by cblecker** [comment]
Can @danielromlein or @floreks approve for sig-ui?

**Comment by floreks** [comment]
We do need that for sure :slightly_smiling_face:

**Comment by cblecker** [comment]
Repo is created. Direct permissions (admin/write) are still pending team creation.

**Comment by cblecker** [comment]
Team access added

**Comment by cblecker** [comment]
@jeefy Everything working as intended? If so, last step is to add to sigs.yaml

**Comment by jeefy** [comment]
@cblecker Yep things look awesome.

I have a pending PR to update some SIG-UI stuff in sigs.yaml. Want I should add this into that PR? Or should it be kept separate?

**Comment by cblecker** [comment]
Doesn’t matter to me. However you want to do it :)

**Comment by jeefy** [comment]
Let's make fewer PRs. Added it into https://github.com/kubernetes/community/pull/3152 -- If I did something wrong with that lemme know. :)

**Comment by nikhita** [comment]
@jeefy Looks like this can be closed now? :)

**Comment by maciaszczykm** [comment]
I think it can. Otherwise we can reopen 👍 

/close
