### ISSUE TITLE
REQUEST: New membership for Ashley-wenyizha

### ISSUE THREAD

**Issue by Ashley-wenyizha** [kubernetes/org#3431]
### GitHub Username

Ashley-wenyizha

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

wongma7

### Sponsor 2

kbasv

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/680
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/621
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/654
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/599
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/624
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/625
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/626
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/655
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/661
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/663
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/665
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/666
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/667
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/671
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/674
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/675
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/677
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/678
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/679

- Issues responded to
https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/393
note - the releases & CVE mitigation & security patches PR does not have issue opened in correspondence

- SIG projects I am involved with
aws-efs-csi-driver

**Comment by jqmichael** [comment]
As the one of the current maintainers of EFS CSI driver,

I support for the request from @Ashley-wenyizha 

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/OWNERS

**Comment by nckturner** [comment]
+1 from me since @wongma7 is on vacation

**Comment by mrbobbytables** [comment]
@jqmichael can you update your profile or respond here with your employer? Sponsors must be from different member companies^^;;

**Comment by gnufied** [comment]
+1

**Comment by Ashley-wenyizha** [comment]
Hi Bob @mrbobbytables, when got time could you take a look at my on-boarding request again? l now have sponsors from different member companies from Hemant `gnufied` and Nicholas`nckturner`

thanks!!

**Comment by mrbobbytables** [comment]
Thanks!
/assign

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3515  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
