### ISSUE TITLE
REQUEST: New membership for Sea-n

### ISSUE THREAD

**Issue by Sea-n** [kubernetes/org#3440]
### GitHub Username

@Sea-n

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tengqm

### Sponsor 2

@howieyuen

### List of contributions to the Kubernetes project

I mainly contribute to [kubernetes/website](https://github.com/kubernetes/website) for 6 weeks.

- [My own PRs](https://github.com/kubernetes/website/pulls?q=author%3ASea-n+is%3Amerged) (38 for now)
    - kubernetes/website#32897
    - kubernetes/website#32909
    - kubernetes/website#33162
    - kubernetes/website#33711
    - kubernetes/website#33757
    - kubernetes/website#33917
- [PRs reviewed by me](https://github.com/kubernetes/website/pulls?q=commenter%3ASea-n+-author%3ASea-n) (56 for now)
    - <kbd>language/zh</kbd> * 48
    - <kbd>language/en</kbd> * 8

**Comment by tengqm** [comment]
+1 Sea-n has been an active contributor during the past month. Looking forward to see more contributions from you.

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
