### ISSUE TITLE
REQUEST: Create kubernetes-sigs/pspmigrator repo

### ISSUE THREAD

**Issue by samos123** [kubernetes/org#3441]
### New repo, staging repo, or migrate existing

new repo

### Is it a staging repo?

no

### Requested name for new repository

pspmigrator

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

tallclair, samos123

### Who should have write access?

tallclair, samos123

### Who should be listed as approvers in OWNERS?

tallclair, samos123

### Who should be listed in SECURITY_CONTACTS?

tallclair, samos123

### What should the repo description be?

pspmigrator is a tool to migrate from PSP to PSA

### What SIG and subproject does this fall under?

sig-auth

### Please provide references to appropriate approval for this new repo

No approval yet but looking for +1s from TLs

### Additional context for request

I already have a working prototype that would be pushed to this repo. Here is the prototype: https://github.com/samos123/pspmigrator

**Comment by ritazh** [comment]
+1

**Comment by mrbobbytables** [comment]
Repo: https://github.com/kubernetes-sigs/pspmigrator
Teams PR: https://github.com/kubernetes/org/pull/3498
Community PR: https://github.com/kubernetes/community/pull/6701

@samos123 just to move things along I created this with just tallclair as the owner. I didn't realize you weren't an org member >_< Please open an org request issue - myself, @tallclair or @mikedanese can sponsor you from the Google side, @ritazh would you mind being another sponsor?

Assign me to it and I'll take care of it.

**Comment by mrbobbytables** [comment]
All **required** items are done, I think a good follow up though would be to get you admin/write access to the repo (ref PR: https://github.com/kubernetes/org/pull/3498). Do you want to open a PR to add you in there?

**Comment by palnabarun** [comment]
ping @samos123, can you please have a look at the above?

**Comment by samos123** [comment]
I got everything I need. Thanks for all the help!
