### ISSUE TITLE
REQUEST: New membership for szuecs

### ISSUE THREAD

**Issue by szuecs** [kubernetes/org#3442]
### GitHub Username

@szuecs

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@raffo

### Sponsor 2

@njuettner

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/external-dns/pull/365
- https://github.com/kubernetes-sigs/external-dns/pull/1349
- https://github.com/kubernetes-sigs/external-dns/pull/1444
- https://github.com/kubernetes-sigs/external-dns/pull/1462
- https://github.com/kubernetes-sigs/external-dns/issues/731
- https://github.com/kubernetes/kubernetes/issues/73587
- https://github.com/kubernetes/kubernetes/pull/63437
- https://github.com/kubernetes/kubernetes/pull/73342

**Comment by Raffo** [comment]
+1

**Comment by njuettner** [comment]
+1

**Comment by mrbobbytables** [comment]
@szuecs Just as an FYI you don't need sponsors or an application to join another org once your a member of one :) I'm adding you now, but in the future you can just add yourself via a PR 👍

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by szuecs** [comment]
@mrbobbytables thank you!
