### ISSUE TITLE
REQUEST: New membership for wangnyue

### ISSUE THREAD

**Issue by wangnyue** [kubernetes/org#3443]
### GitHub Username

wangnyue

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

wongma7

### Sponsor 2

kbasv

### List of contributions to the Kubernetes project

- SIG projects I am involved with
aws-efs-csi-driver

**Comment by Sea-n** [comment]
Hey @wangnyue,

I cannot find any of your PR or issue for Kubernetes(-sig) [using search filter](https://github.com/search?q=author%3Awangnyue&type=commits) at this time.

It's always welcome to apply for k8s membership when you have start contributing, I will close this issue for now.
/close
