### ISSUE TITLE
REQUEST: New membership for harshitasao

### ISSUE THREAD

**Issue by harshitasao** [kubernetes/org#3444]
### GitHub Username

harshitasao

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@helayoty

### Sponsor 2

_

### List of contributions to the Kubernetes project

**PRs made:**
- https://github.com/kubernetes/sig-release/pull/1904  
- https://github.com/kubernetes/websitehttps://github.com/kubernetes/website/pull/33961  
- https://github.com/kubernetes/websitehttps://github.com/kubernetes/website/pull/33881 
- https://github.com/kubernetes/test-infrahttps://github.com/kubernetes/test-infra/pull/26341  
- https://github.com/kubernetes-client/pythonhttps://github.com/kubernetes-client/python/pull/1804  

**Issue Created:**
  - https://github.com/kubernetes/websitehttps://github.com/kubernetes/website/issues/33705 
  
**Issue Assigned:**
- https://github.com/kubernetes/websitehttps://github.com/kubernetes/website/issues/31584 
- https://github.com/kubernetes/communityhttps://github.com/kubernetes/community/issues/6641 
- https://github.com/fabric8io/kubernetes-clienthttps://github.com/fabric8io/kubernetes-client/issues/4006

**Comment by helayoty** [comment]
+1 from me! Thank you for volunteering to help with the 1.25 release team @harshitasao!

**Comment by helayoty** [comment]
@reylejano

**Comment by reylejano** [comment]
+1 Welcome to the 1.25 Release Team @harshitasao

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
