### ISSUE TITLE
REQUEST: New membership for cezarygerard

### ISSUE THREAD

**Issue by cezarygerard** [kubernetes/org#3446]
### GitHub Username

cezarygerard

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@bowei 

### Sponsor 2

@jaypipes

### List of contributions to the Kubernetes project

kubernetes/kubernetes PRs:
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Acezarygerard+

ingress-gce PRs:
https://github.com/kubernetes/ingress-gce/pulls?q=is%3Apr+author%3Acezarygerard+

**Comment by jaypipes** [comment]
Confirming I am sponsoring @cezarygerard. :+1:

**Comment by bowei** [comment]
I'm am sponsoring as well.

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3474 to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
