### ISSUE TITLE
REQUEST: New membership for Paul Schweigert

### ISSUE THREAD

**Issue by mikebrow** [kubernetes/org#3447]
### GitHub Username

@psschwei

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mikebrow

### Sponsor 2

@mrunalp @saschagrunert

### List of contributions to the Kubernetes project

https://github.com/kubernetes/website/pull/32823
https://github.com/kubernetes/kubernetes/pull/107958
https://github.com/kubernetes/kubernetes/pull/108015
https://github.com/containerd/containerd/pull/6894
https://github.com/containerd/containerd/pull/6938
https://github.com/cri-o/cri-o/pull/5913
https://github.com/kubernetes/enhancements/pull/3067
...

Paul is a Knative maintainer looking to help out more in the k/k stack

**Comment by saschagrunert** [comment]
+1 happy to have Paul as part of the org 😊

**Comment by mrbobbytables** [comment]
@mikebrow issues are not generally opened by folks on behalf of others^^;;; we have the checklist of things that people need to go through and confirm they've done.

@psschwei can you confirm you're interested in org membership and either ack on this issue that you've completed everything in the checklist or open a new one?

**Comment by psschwei** [comment]
@mrbobbytables Yes, I am interested in org membership and am confirming that I have:

* reviewed the community membership guidelines
* enabled 2FA
* subscribed to the dev list
* been actively contributing to 1 or more Kubernetes subprojects
* two sponsors
* gotten said sponsors' agreement to sponsor me
* verified said sponsors are from different member companies
* verified my sponsors are reviewers/approvers

**Comment by mrbobbytables** [comment]
@psschwei , thank you for all your contributions so far :)

I've created PR #3497 to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
