### ISSUE TITLE
REQUEST: New membership for Jont828

### ISSUE THREAD

**Issue by Jont828** [kubernetes/org#3448]
### GitHub Username

Jont828

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@CecileRobertMichon

### Sponsor 2

@shysank

### List of contributions to the Kubernetes project

I requested membership in K8s SIGS in #3156 and joined, but I realized I forgot to request membership in Kubernetes as well.

**Comment by CecileRobertMichon** [comment]
+1 

@Jont828 should already be implicitly eligible for kubernetes org membership as a member and review in kubernetes-sigs https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem

**Comment by mboersma** [comment]
+1 Jonathan has been a big contributor to sig-lifecycle projects. He always does great work and we're lucky to have him in Kubernetes. 😄

**Comment by mrbobbytables** [comment]
Just an FYI - you don't need to open a new request to join a Kubernetes org if you're already an org member of one 👍  I'm adding you now, but in the future you can open a PR to add yourself to an org. :)

/assign

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by mrbobbytables** [comment]
Hey there  thank you for all your contributions so far :)

I've created PR #3456   to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
