### ISSUE TITLE
REQUEST: New membership for AnaMMedina21

### ISSUE THREAD

**Issue by AnaMMedina21** [kubernetes/org#3452]
### GitHub Username

AnaMMedina21

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

katcosgrove

### Sponsor 2

cici37

### List of contributions to the Kubernetes project

- Shadow for Kubernetes 1.25 Comms Team
- Keptn

**Comment by cici37** [comment]
+1

**Comment by cici37** [comment]
@katcosgrove

**Comment by katcosgrove** [comment]
+1 Glad to have you! :D

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3474 to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
