### ISSUE TITLE
REQUEST: New membership for jwtty

### ISSUE THREAD

**Issue by jwtty** [kubernetes/org#3458]
### GitHub Username

@jwtty

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@feiskyer

### Sponsor 2

@endocrimes

### List of contributions to the Kubernetes project

PRs reviewed / authored:
cloud-provider-azure:
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1484
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1500
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1531

kubernetes:
https://github.com/kubernetes/kubernetes/pull/110127

Issues responded to:
https://github.com/kubernetes-sigs/cloud-provider-azure/issues/872
https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1136
https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1643
https://github.com/kubernetes/kubernetes/issues/105678

SIG projects I am involved with:
* sig-cloud-provider
* cloud-provider-azure

**Comment by feiskyer** [comment]
+1 for @jwtty's contribution to kubernetes and cloud provider!

**Comment by endocrimes** [comment]
+1, welcome to the community 💖

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3474 to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by jwtty** [comment]
Thank you so much @mrbobbytables! I'm thrilled to join the community!
