### ISSUE TITLE
REQUEST: New membership for ziyi-xie

### ISSUE THREAD

**Issue by ziyi-xie** [kubernetes/org#3459]
### GitHub Username

ziyi-xie

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@maciaszczykm

### Sponsor 2

@shu-mutou

### List of contributions to the Kubernetes project

- PRs authored:
https://github.com/kubernetes/dashboard/pull/6692
https://github.com/kubernetes/dashboard/pull/6736
https://github.com/kubernetes/dashboard/pull/6821
https://github.com/kubernetes/dashboard/pull/7054
https://github.com/kubernetes/dashboard/pull/7079
https://github.com/kubernetes/dashboard/pull/7096
https://github.com/kubernetes/minikube/pull/13741

- Issues authored:
https://github.com/kubernetes/dashboard/issues/6735

- SIG projects I am involved with:
sig-ui

**Comment by shu-mutou** [comment]
+1 from me! Thank you for contributing to Kubernetes Dashboard!! :heart:

**Comment by ziyi-xie** [comment]
> +1 from my side too.

Many thanks!

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3474 to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by ziyi-xie** [comment]
> Hey there, thank you for all your contributions so far :)
> 
> I've created PR #3474 to add you to the Org. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉

Thanks! I'm so excited!
