### ISSUE TITLE
REQUEST: New membership for Divya063

### ISSUE THREAD

**Issue by Divya063** [kubernetes/org#3462]
### GitHub Username

Divya063

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@csantanapr

### Sponsor 2

@reylejano

### List of contributions to the Kubernetes project

- Shadow on the Release Notes team

**Comment by reylejano** [comment]
+1 welcome to the 1.25 Release Team 🎉

**Comment by csantanapr** [comment]
+1 welcome to 1.25 release team 👍  @Divya063

**Comment by Divya063** [comment]
Thanks @reylejano  and @csantanapr :)

**Comment by mrbobbytables** [comment]
I'm batching requests now, but as an FYI - as a member of the kubernetes project already you don't need to file a request to be added to another org :) You can open a PR adding yourself and the github admins would quickly sign off 👍

**Comment by mrbobbytables** [comment]
fixed in a separate PR, just missed linking it to this one

/close
