### ISSUE TITLE
REQUEST: New membership for ramrodo

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/org#3463]
### GitHub Username

@ramrodo

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@csantanapr

### Sponsor 2

@reylejano

### List of contributions to the Kubernetes project

**PRs reviewed / authored:**
https://github.com/kubernetes/sig-release/pull/1398
https://github.com/kubernetes/website/pull/30103

**SIG projects I am involved with:**
SIG Docs

**Comment by reylejano** [comment]
As a previous Release Team member, you are already an Kubernetes org member, so this request would be for kubernetes-sigs
+1 and welcome to the 1.25 Release Team 🎉

**Comment by ramrodo** [comment]
Ok. Sounds good, Rey. I'll update the issue to only  request for **kubernetes-sigs**

**Comment by csantanapr** [comment]
Welcome to k8s 1.25 release team 👍

**Comment by mrbobbytables** [comment]
I'm batching requests now, but as an FYI for the future, if you're an org member, you do not need to open an issue to be added to another org, you can PR yourself in there 👍 

/assign

**Comment by ramrodo** [comment]
fixed by https://github.com/kubernetes/org/pull/3474
