### ISSUE TITLE
Kubernetes membership not syncing

### ISSUE THREAD

**Issue by Jont828** [kubernetes/org#3471]
### Organization or Repo

kubernetes/org

### User affected

@Jont828

### Describe the issue

I've been added to the [K8s org yaml](https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L619) here, but I'm not showing up in [this query](https://github.com/orgs/kubernetes/people?query=Jont828). I'm trying to get added as a CAPZ reviewer in [this PR](https://github.com/kubernetes/k8s.io/pull/3783) and it's blocked on the membership check.

**Comment by cblecker** [comment]
You need to accept the invitation. You can do this from the e-mail you received, or visiting https://github.com/kubernetes and clicking the banner near the top of the page.

**Comment by mrbobbytables** [comment]
It shows you as a member, going to go ahead and close this out 👍 

/close
