### ISSUE TITLE
REQUEST: New membership for skriss

### ISSUE THREAD

**Issue by skriss** [kubernetes/org#3472]
### GitHub Username

@skriss

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@robscott

### Sponsor 2

@youngnick

### List of contributions to the Kubernetes project

Gateway API conformance tests:
- https://github.com/kubernetes-sigs/gateway-api/pull/1036
- https://github.com/kubernetes-sigs/gateway-api/pull/1130
- https://github.com/kubernetes-sigs/gateway-api/pull/1134
- https://github.com/kubernetes-sigs/gateway-api/pull/1137
- https://github.com/kubernetes-sigs/gateway-api/pull/1144
- https://github.com/kubernetes-sigs/gateway-api/pull/1163
- https://github.com/kubernetes-sigs/gateway-api/pull/1170

Misc. Gateway API enhancements & fixes:
- https://github.com/kubernetes-sigs/gateway-api/pull/909
- https://github.com/kubernetes-sigs/gateway-api/pull/1168

**Comment by robscott** [comment]
Big +1, thanks for all the contributions @skriss!

**Comment by youngnick** [comment]
+1 from me as well!

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3497 to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
