### ISSUE TITLE
REQUEST: New membership for mowangdk

### ISSUE THREAD

**Issue by fredkan** [kubernetes/org#3475]
### GitHub Username

mowangdk

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

fredkan

### Sponsor 2

xianlubird

### List of contributions to the Kubernetes project

https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/651
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/635
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/617

**Comment by mrbobbytables** [comment]
@fredkan they're already a kubernetes-sigs member 👍 
ref: https://github.com/kubernetes/org/pull/2114

**Comment by mrbobbytables** [comment]
As they're already members, I'm going to go ahead and close this out.

/close
