### ISSUE TITLE
REQUEST: Add membership for krol3 to Kubernetes organization

### ISSUE THREAD

**Issue by krol3** [kubernetes/org#3478]
### GitHub Username

@krol

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@reyLejano

### Sponsor 2

@kcmartin

### List of contributions to the Kubernetes project

I need to be part of the Kubernetes Organization as a member of the Shadow program of the Kubernetes Release Team Meeting.

I opened an issue to be part of the kubernetes-sig. https://github.com/kubernetes/org/issues/3377

**Comment by reylejano** [comment]
+1 welcome to the 1.25 release team 🎉

**Comment by kcmartin** [comment]
+1 Welcome to The 1.25 Release team!

**Comment by rikatz** [comment]
+1 same sponsorship I gave in #3377 applies here! Thanks for all the help and thanks for stepping in to the rel team @krol3  :)

**Comment by mrbobbytables** [comment]
I'm batching requests now, but as a general FYI - as a member of another org, you don't need to reapply for org membership. Just need to open a PR adding yourself :)

/assign

**Comment by mrbobbytables** [comment]
Once PR #3497 gets merged you should get an invite 👍
