### ISSUE TITLE
REQUEST: New membership for zhangxyjlu

### ISSUE THREAD

**Issue by zhangxyjlu** [kubernetes/org#3483]
### GitHub Username

@zhangxyjlu

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@howieyuen

### Sponsor 2

@mengjiao-liu

### List of contributions to the Kubernetes project

PRs authored: https://github.com/pulls?q=is%3Apr+author%3Azhangxyjlu+archived%3Afalse+is%3Aclosed
Issues responded to: [#34033](https://github.com/kubernetes/website/issues/34033),[#32440](https://github.com/kubernetes/website/issues/32440)
Issues: https://github.com/issues?q=is%3Aissue+author%3Azhangxyjlu+archived%3Afalse+is%3Aclosed
SIG projects I am involved with: [kubernetes/website](https://kubernetes.io/docs/home/)

**Comment by howieyuen** [comment]
+1
Thanks to your contribution, and welcome to join us 🌷

**Comment by Sea-n** [comment]
(I don't have permission, but +1 in my heart)

I think you are applying @kubernetes `sig-docs` instead of @kubernetes-sig. Maybe you would like to edit the issue content.

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3497 to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
