### ISSUE TITLE
REQUEST: New membership for slaskawi

### ISSUE THREAD

**Issue by slaskawi** [kubernetes/org#3484]
### GitHub Username

@slaskawi

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@s-urbaniak

### Sponsor 2

@tallclair

### List of contributions to the Kubernetes project

* PRs that I authored and got merged:
  * An additional check for StatefulSet tests: https://github.com/kubernetes/kubernetes/pull/38954
  * A fix for printing text by `kubectl explain` https://github.com/kubernetes/kubernetes/pull/107682
  * A warning on emitting space-prefixed tokens https://github.com/kubernetes/kubernetes/pull/109587

* PRs and issues that are in progress:
  * Reinitialize OIDC stack when there's a new Refresh Token. Blocked until e2e testsuite is ready https://github.com/kubernetes/kubernetes/pull/108794
  * Replace form3tech-oss/jwt-go with golang-jwt/jwt. Waiting until https://github.com/heketi/heketi/pull/1898 gets in https://github.com/kubernetes/kubernetes/issues/104007

* PRs that I authored and got rejected (with a good reason):
  * Including raw request and response bodies in audit logs https://github.com/kubernetes/kubernetes/issues/84571

**Comment by s-urbaniak** [comment]
I am 100% positive on this :-) I have been working with Sebastian in the same team, his knowledge in areas of authorization and authentication are highly valuable for the kubernetes community and not limited to this area. He has a significant track record of open source contributions as well.

**Comment by tallclair** [comment]
+1 from me as well.

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3497 to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by slaskawi** [comment]
Thank you @s-urbaniak, @tallclair and @mrbobbytables !
