### ISSUE TITLE
REQUEST: New membership for leonardpahlke

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/org#3487]
### GitHub Username

@leonardpahlke

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@saschagrunert

### Sponsor 2

@cpanato

### List of contributions to the Kubernetes project

- k/release ci reporter: tool author
- k-sigs/kubernetes shadow stats: tool author
- k-sigs/testgrid-json exporter: tool co-author
- k/sig-release: documentation
- K RT orga

**Comment by saschagrunert** [comment]
+1, happy to sponsor @leonardpahlke :blush:

**Comment by leonardpahlke** [comment]
ref: https://github.com/kubernetes-sigs/testgrid-json-exporter/pull/7

**Comment by cpanato** [comment]
+1 :D
