### ISSUE TITLE
REQUEST: New membership for davidjumani

### ISSUE THREAD

**Issue by davidjumani** [kubernetes/org#3488]
### GitHub Username

@davidjumani

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@elmiko

### Sponsor 2

@sbueringer

### List of contributions to the Kubernetes project

PR Authored / Reviewed :
- https://github.com/kubernetes/autoscaler/pull/3629
- https://github.com/kubernetes-sigs/cluster-api/pull/6326
- https://github.com/kubernetes-sigs/image-builder/pull/842
- https://github.com/kubernetes-sigs/image-builder/pull/792
- https://github.com/kubernetes/k8s.io/pull/2654
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/103

**Comment by elmiko** [comment]
+1
thanks for all the work on capc =)

**Comment by davidjumani** [comment]
Thanks for the heads up @mrbobbytables and for your support @sbueringer @elmiko
