### ISSUE TITLE
REQUEST: New membership for @rejoshed

### ISSUE THREAD

**Issue by rejoshed** [kubernetes/org#3490]
### GitHub Username

rejoshed

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

maxdrib

### Sponsor 2

elmiko

### List of contributions to the Kubernetes project

- contributed to the donation of the aws/cluster-api-provider-cloudstack repository to the kubernetes-sigs repo
- am actually the top contributor to the CAPC project by Git stats https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/graphs/contributors
- merged https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/76
- continuing to develop https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack with
https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/101

**Comment by maxdrib** [comment]
+1 /lgtm Joshua is one of the essential CAPC developers and he has big plans for the future

**Comment by mrbobbytables** [comment]
@rejoshed org changes are batch processed by either github admins or the new member coordinators and we try to keep things to a 1 week SLO, but do sometimes go longer. Assigning it doesn't mean it gets done quicker as the admins/nmcs look for unassigned ones for triage. Assigned ones usually mean its been looked at and waiting for additional info from the author.

Either way, I'm doing a batch right now - but something to keep in mind for the future.
/assign

**Comment by mrbobbytables** [comment]
Once PR #3497 gets merged you should get an invite 👍
