### ISSUE TITLE
REQUEST: New membership for @makocchi-git

### ISSUE THREAD

**Issue by makocchi-git** [kubernetes/org#35]
### GitHub Username
@makocchi-git

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah
- @xiangpengzhao

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amakocchi-git+is%3Aclosed+
- Issues responded to
https://github.com/kubernetes/website/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Amakocchi-git+is%3Aclosed+
- SIG projects I am involved with
sig-docs (k/kubernetes-docs-ja)

**Comment by zacharysarah** [comment]
+1

**Comment by xiangpengzhao** [comment]
+1

**Comment by makocchi-git** [comment]
@zacharysarah @xiangpengzhao 
Really I appreciate your kindness!

**Comment by spiffxp** [comment]
/close
invite sent, welcome!
