### ISSUE TITLE
REQUEST: New membership for samos123

### ISSUE THREAD

**Issue by samos123** [kubernetes/org#3502]
### GitHub Username

samos123

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mrbobbytables

### Sponsor 2

@ritazh

### List of contributions to the Kubernetes project

- Creator of pspmigrator which will be part of k8s-sigs org under sig-auth: https://github.com/kubernetes/org/issues/3441

**Comment by mrbobbytables** [comment]
+1 from sponsor, this is to help establish owners for a new donated project

**Comment by ritazh** [comment]
+1 from sig auth

**Comment by samos123** [comment]
@mrbobbytables do we need more +1s?

**Comment by mrbobbytables** [comment]
@samos123 nope, we're good - member requests are processed in batches by the member coordinators / GitHub admins (1 week SLO~).

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3515  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
