### ISSUE TITLE
REQUEST: New membership for aladewberry

### ISSUE THREAD

**Issue by aladewberry** [kubernetes/org#3504]
### GitHub Username

@aladewberry

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@PushkarJ

### Sponsor 2

@savitharaghunathan

### List of contributions to the Kubernetes project

I am the lead for the Self-Assessment subproject in SIG Security! I'm currently working to get the CAPI fuzzing report published and get any issues filed from the results of that report. I've been attending meetings regularly and am building a roadmap for what's next - so far the vSphere CSI driver is in our sites, and I will drop into other SIG meetings to socialize our assessment format and share about our process so that we can make Kubernetes more secure for everyone!

**Comment by PushkarJ** [comment]
/retitle REQUEST: New membership for @aladewberry 

This is a duplicate of #3449 because the issue was closed after adding Ala to `kubernetes-sigs`, whereas in order to work on `kubernetes/sig-security` repo she needs membership access to `kubernetes` Org.

I will open a PR to add her to the correct list now
