### ISSUE TITLE
REQUEST: New membership for mpuckett159

### ISSUE THREAD

**Issue by mpuckett159** [kubernetes/org#3508]
### GitHub Username

@mpuckett159

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@eddiezane

### Sponsor 2

@seans

### List of contributions to the Kubernetes project

- [PR Authored] [Add Ingress Class to kubectl describe ingress output](https://github.com/kubernetes/kubernetes/pull/107921) - simple PR to add the ingress class in the kubectl describe command output.
- [PR Authored] [Move kubectl wait subcommand to informers with cache](https://github.com/kubernetes/kubernetes/pull/108086) - This is a bugfix for the kubectl wait subcommand to allow it to wait properly on objects that may disappear from the cluster, instead of waiting until timeout.
- [PR Authored] [Redact all config keys with datapolicy json tag by default](https://github.com/kubernetes/kubernetes/pull/109189) - This is a feature request PR that changes the redacting policy for client-go for the kube config outputs to ensure that any field with a datapolicy json tag get redacted by default, and introduces a new flag to print secret values in plaintext properly.
- [PR Authored] [Add jsonpath support for kubect config set](https://github.com/kubernetes/kubernetes/pull/110392) - This PR is in progress and pretty messy but I've been working on the general idea for a few months. It is a feature PR that will enable using jsonpath querying to find and set properties in the kube config file. Presently you can not set values in the `users.username.auth-provider` or `users.username.exec` fields. Originally my implementation extended the existing dot delimited pathing syntax as above, but after some discussion it was decided that this extension was too complicated and created a domain specific language that would be difficult to support long term. The original PR can be found [here](https://github.com/kubernetes/kubernetes/pull/107305). Based on that decision it was decided that we should move to using the already existing and maintained jsonpath language provided by client-go.
- [SIG Project] [Break out options and flags](https://github.com/kubernetes/kubernetes/pull/109456) - This is part of an ongoing effort tracked in [this issue](https://github.com/kubernetes/kubectl/issues/1046) to split out options from flags in the kubectl subcommands.
- [Issue Response] [Helping user understand how kube config files work](https://github.com/kubernetes/kubectl/issues/1212#issuecomment-1137561882) - This issue was opened by a user who had confused how to use manifests with setting your kubeconfig file. Provided detailed answer with how to successfully accomplish what they were trying to do.
- [Issue Response] [kubectl config set* commands delete invalid kube config keys](https://github.com/kubernetes/kubectl/issues/1203) - This issue was the result of a kubectl plugin's interaction with the kube config file. The user was expecting the kubectl config set commands to ignore the custom properties that were introduced, however this is not how client-go and thus kubectl work. Unfortunately a bit of confusion on my part with answering but everyone ended up on the same page eventually.

**Comment by eddiezane** [comment]
:+1: thanks for your contributions!

**Comment by seans3** [comment]
+1

Looking forward to working with you more.

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3515  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by mpuckett159** [comment]
Thank you Bob, I look forward to continuing to work with you and everyone else.
