### ISSUE TITLE
REQUEST: New membership for javadoors

### ISSUE THREAD

**Issue by javadoors** [kubernetes/org#3517]
### GitHub Username

javadoors

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tengqm

### Sponsor 2

@mengjiao-liu

### List of contributions to the Kubernetes project

- PRs reviewed / authored
   [ [zh] Translate docs/reference/labels-annotations-taints to Chinese](https://github.com/kubernetes/website/pull/32255)
   [fixed for #32288](https://github.com/kubernetes/website/pull/33727)
   [Update service-account-v1.md](https://github.com/kubernetes/website/pull/34267)
  [[zh] Translate /docs/reference/kubernetes-api/authentication-resource](https://github.com/kubernetes/website/pull/34282)
  [Correct typos](https://github.com/kubernetes/website/pull/34302)
  [remove duplicate words](https://github.com/kubernetes/website/pull/34304)
  [Correct wrong link](https://github.com/kubernetes/website/pull/34323)
  [Modify the wrong link](https://github.com/kubernetes/website/pull/34340)
  [Correct typos](https://github.com/kubernetes/website/pull/34345)
  [[zh] Fix broken hyperlink](https://github.com/kubernetes/website/pull/34412)
- Issues responded to
  [This page docs/reference/labels-annotations-taints/ has no Chinese version](https://github.com/kubernetes/website/issues/32244)
  [Missing /docs/tutorials/clusters/seccomp page or this link is incorrect](https://github.com/kubernetes/website/issues/32273)
  [[zh]Translate /docs/reference/config-api/kubelet-config.v1alpha1/ page into Chinese](https://github.com/kubernetes/website/issues/32317)
  [[zh] Translate /docs/reference/kubernetes-api/authentication-resources/certificate-signing-request-v1/ to Chinese](https://github.com/kubernetes/website/issues/34137)
  [[zh] Translate /docs/reference/kubernetes-api/authentication-resources/token-request-v1/ to Chinese](https://github.com/kubernetes/website/issues/34207)
  [[website]Unable to load specs and/or toc config: Resource policy/v1beta1/PodSecurityPolicy not found in spec](https://github.com/kubernetes-sigs/reference-docs/issues/282)
- SIG projects I am involved with
  kubernetes
  kubernetes-sigs

**Comment by mengjiao-liu** [comment]
+1
Thank you for all your contributions so far :)

**Comment by javadoors** [comment]
> +1 Please do keep contribute to the community.

thanks,-_-,I will do my best.

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3540  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
