### ISSUE TITLE
REQUEST: New membership for @yaroslava-serdiuk

### ISSUE THREAD

**Issue by yaroslava-serdiuk** [kubernetes/org#3519]
### GitHub Username

@yaroslava-serdiuk

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@MaciekPytel

### Sponsor 2

@gjtempleton

### List of contributions to the Kubernetes project

-  PRs authored
https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+is%3Aclosed+author%3Ayaroslava-serdiuk

- SIG projects I am involved with
Autoscaler (Cluster Autoscaler)

**Comment by gjtempleton** [comment]
Big +1 from me, Yaroslava's made a number of significant contributions to the Cluster Autoscaler over an extended period of time. 

Looking forward to their continued contributions!

**Comment by MaciekPytel** [comment]
+1 Yaroslava is a regular Cluster Autoscaler contributor with a long history of features, bugfixes and improvements to the project

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3540  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
