### ISSUE TITLE
REQUEST: New membership for @chetak123

### ISSUE THREAD

**Issue by chetak123** [kubernetes/org#3521]
### GitHub Username

@chetak123

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mehabhalodiya

### Sponsor 2

@sftim

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/sig-security/pull/47
https://github.com/kubernetes/sig-security/pull/12
https://github.com/kubernetes/contributor-site/pull/254
https://github.com/kubernetes/website/pull/30333
https://github.com/kubernetes/website/pull/30686
https://github.com/kubernetes/website/pull/30854
https://github.com/kubernetes/website/pull/30071
https://github.com/kubernetes/website/pull/30059
https://github.com/kubernetes/website/pull/34469
https://github.com/kubernetes/community/pull/6311
along with some other PRs in progress
https://github.com/kubernetes/website/pull/34477
https://github.com/kubernetes/website/pull/34457
https://github.com/kubernetes/website/pull/34455
https://github.com/kubernetes/test-infra/pull/26619
https://github.com/kubernetes-sigs/scheduler-plugins/pull/383
https://github.com/kubernetes/sig-security/pull/24

- Issues responded to
https://github.com/kubernetes/sig-security/issues/14
https://github.com/kubernetes/website/issues/34550

- SIG projects I am involved with
kubernetes
kubernetes-sigs

**Comment by mehabhalodiya** [comment]
+1 
Thanks for all your contributions!
Welcome to the community 🙂

**Comment by sftim** [comment]
+1

Thanks for contributions so far; looking forward to more of them.

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3540  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
