### ISSUE TITLE
REQUEST: New membership for @everettraven

### ISSUE THREAD

**Issue by everettraven** [kubernetes/org#3522]
### GitHub Username

@everettraven

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@camilamacedo86

### Sponsor 2

@jberkhahn

### List of contributions to the Kubernetes project

- PRs reviewed:
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2552
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2571
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2583
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2596
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2608
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2662
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2679
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2682
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2698
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2715
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2720
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2721
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2732
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2733
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2734
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2739
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2741
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2750
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2758
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2764
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2767
    
    - https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/217

- PRs authored:
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2610
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2693
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2706
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2712
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2713
    - https://github.com/kubernetes-sigs/kubebuilder/pull/2723
    
    - https://github.com/kubernetes-sigs/controller-runtime/pull/1873

- Issues responded to:
    - https://github.com/kubernetes-sigs/kubebuilder/issues/2597
    - https://github.com/kubernetes-sigs/kubebuilder/issues/2670
    - https://github.com/kubernetes-sigs/kubebuilder/issues/2716
    - https://github.com/kubernetes-sigs/kubebuilder/issues/2722
    
- Issues authored:
    - https://github.com/kubernetes-sigs/kubebuilder/issues/2689
    - https://github.com/kubernetes-sigs/kubebuilder/issues/2710
    - https://github.com/kubernetes-sigs/kubebuilder/issues/2731
    - https://github.com/kubernetes-sigs/kubebuilder/issues/2690
    
- SIG projects I am involved with:
    - Kubebuilder: https://github.com/kubernetes-sigs/kubebuilder

**Comment by camilamacedo86** [comment]
/lgtm

@everettraven has been contributing a lot with Kubebuilder and indeed already push very considerable changes
He is OK to be Kubebuilder reviewer already and have my total support here🥇

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3540  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
