### ISSUE TITLE
REQUEST: New membership for @dpasiukevich

### ISSUE THREAD

**Issue by dpasiukevich** [kubernetes/org#3524]
### GitHub Username

@dpasiukevich

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@youngnick

### Sponsor 2

@MrHohn

### List of contributions to the Kubernetes project

I'm working on maintenance and support of https://github.com/kubernetes/dns which has deprecated but still used in number of projects kube-dns and an active project nodelocaldns.

PRs authored:
https://github.com/kubernetes-sigs/gateway-api/pull/1208
https://github.com/kubernetes-sigs/gateway-api/pull/1209
https://github.com/kubernetes/dns/pull/521
https://github.com/kubernetes/k8s.io/pull/3869
https://github.com/kubernetes/dns/pull/519
https://github.com/kubernetes/dns/pull/516
https://github.com/kubernetes/dns/pull/515
https://github.com/kubernetes/dns/pull/508
https://github.com/kubernetes/dns/pull/510

**Comment by MrHohn** [comment]
+1 - thanks for all the contributions @dpasiukevich!

**Comment by youngnick** [comment]
+1, thanks @dpasiukevich!

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3540  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
