### ISSUE TITLE
REQUEST: New membership for keithmattix

### ISSUE THREAD

**Issue by keithmattix** [kubernetes/org#3529]
### GitHub Username

keithmattix

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

bridgetkromhout

### Sponsor 2

robscott

### List of contributions to the Kubernetes project

Gateway-API
- https://github.com/kubernetes-sigs/gateway-api/pull/1236
- https://github.com/kubernetes-sigs/gateway-api/pull/1234
- https://github.com/kubernetes-sigs/gateway-api/pull/1233
- Deeply involved in discussion around Gateway API mesh use-cases: https://docs.google.com/document/d/1T_DtMQoq2tccLAtJTpo3c0ohjm25vRS35MsestSL9QU/edit

very involved in kubernetes-adjacent projects:
- Added data source to Kubernetes Terraform provider
- Service Mesh Interface maintainer
- Spearheading creation of new WG Mesh under sig-networking

**Comment by robscott** [comment]
Welcome @keithmattix! Excited to be working with you more. 

+1

**Comment by mrbobbytables** [comment]
@keithmattix do you happen to have another sponsor? Sadly @bridgetkromhout cannot act as a sponsor =/ Sponsors must be a [reviewer or approver in any OWNERS file](https://cs.k8s.io/?q=bridgetkromhout&i=fosho&files=OWNERS&excludeFiles=vendor%2F&repos=). (ref: [community membership guidelines](https://git.k8s.io/community/community-membership.md))

**Comment by keithmattix** [comment]
Ah, missed that qualification. @youngnick has agreed to be my other sponsor

**Comment by youngnick** [comment]
Hopefully, in this instance, I can stand in for @bridgetkromhout. (Pretty sure I can't in any other, she's too great!)

+1 from me, thanks for everything you've done already, looking forward to seeing what's next.

**Comment by mrbobbytables** [comment]
That'll do!

/assign

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3540  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
