### ISSUE TITLE
REQUEST: New membership for howardjohn

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/org#3530]
### GitHub Username

@howardjohn

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@robscott

### Sponsor 2

@shaneutt

### List of contributions to the Kubernetes project

* I have contributed over 50 PRs between kubernetes and kubernete-sigs (mostly gateway-api): https://github.com/search?q=is%3Apr+author%3Ahowardjohn+archived%3Afalse+org%3Akubernetes+org%3Akubernetes-sigs&type=Issues
* Reported ~150 issues: https://github.com/search?q=is%3Aissue+author%3Ahowardjohn+archived%3Afalse+org%3Akubernetes+org%3Akubernetes-sigs&type=Issues

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3540  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
