### ISSUE TITLE
REQUEST: New membership for mikemorris

### ISSUE THREAD

**Issue by mikemorris** [kubernetes/org#3536]
### GitHub Username

mikemorris

### Organization you are requesting membership in

kubernetes

### Requirements

Refs #3470 

> If you are a member of one of these Orgs, you are implicitly eligible for membership in related orgs, and can request membership when it becomes relevant, by creating a PR directly or [opening an issue](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) against the kubernetes/org repo, as above.
https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem

Refs https://github.com/kubernetes/community/pull/6724 - I'm not _quite_ sure where I would PR this, as the proposed working group doesn't exist under SIG-Network yet.

**Comment by keithmattix** [comment]
cc @mrbobbytables please advise on the correct location for this issue

**Comment by mrbobbytables** [comment]
This is the right place, you don't have to be associated with a project. I'll add it to my other PR with the batches to be processed. Missed this one because I was filtering on `area/github-membership` >_>

/assign
