### ISSUE TITLE
REQUEST: New membership for @geetikabatra

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes/org#3538]
### GitHub Username

@geetikabatra

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

vrabbi

### Sponsor 2

srm09

### List of contributions to the Kubernetes project

List of contributions to the Kubernetes project

- PRs reviewed / authored
  -   [Update Cobra to version 1.4.0 and Viper to 1.10.1 ](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1508)
  - [Use new setup-envtest binary to setup envtest](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1474)
  - [Add unit tests for identity package](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1450)
  - [Replace GC_KIND variable with SKIP_RESOURCE_CLEANUP](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1446)
  - [Adds e2e test for Machine Deployment Rollout test](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1411)
  - [Update cluterctl version in e2e to latest patch ](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1397)
  - [Adds provision to check test coverage](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1356)
  - [Add feature gate machinery ](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1239)
  - [Proposal for GPU and PCI passthrough support ](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1237)
  - [Bumps golang from 1.16.0 to 1.16.7.](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1231)
  - [Wait for webhook readiness and healthy](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2685)

- Issues created
  - [[Refactor] Use pointer values for fields.](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1549)
  - [Add Development section in Makefile](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1546)
  - [E2E setup for GPU effort](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1500)
  - [Investigate why the description of all the tests are not logged ](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1496)
  - [Add unit test case for the package govmomi/services.go ](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1479)
  - [[Refactor] Move CAPI related E2E tests to one place](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1476)
  - [Book for Cluster API provider Vsphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1458)
  - [Add README about flavors](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1457)
  - [Use GitHub Release Note Generation](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1444)
  - [Add kubescape security scanner in e2e tests](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1442)
  - [Improving test coverage in pkg/util](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1421)
  - [Improving test coverage in pkg/services](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1420)
  - [Improving test coverage in pkg/manager](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1418)
  - [Improving unit test coverage](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1392)

- SIG projects I am involved with
  - sig-clusteer-lifecycle

**Comment by vrabbi** [comment]
Huge plus 1 from my side! Geetika has been extremely helpful in the ClusterAPI Provider vSphere sub project!

**Comment by Ankitasw** [comment]
+100

**Comment by srm09** [comment]
+1 from me, thanks for all your contributions

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3540  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by geetikabatra** [comment]
Thanks Everyone! :)
