### ISSUE TITLE
REQUEST: New membership for claurence

### ISSUE THREAD

**Issue by claurence** [kubernetes/org#354]
### GitHub Username
@claurence 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp 
- @kacole2 

### List of contributions to the Kubernetes project
- SIG projects I am involved with
    - SIG Release as the 1.14 Enhancements Lead

**Comment by spiffxp** [comment]
+1

**Comment by kacole2** [comment]
Ditto. +1

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #358 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
