### ISSUE TITLE
Add Prajyot-Parab as member in kubernetes

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes/org#3544]
Hi, I'm a member of the [kubernetes-sigs org](https://github.com/kubernetes/org/blob/2d1ce973592fe7d5bbb51275bc48bd92ea7781b5/config/kubernetes-sigs/org.yaml#L605) and would like to get added to the kubernetes. I referred [membership](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem) guide, which says:

> "If you are a member of one of these Orgs, you are implicitly eligible for membership in related orgs, and can request membership when it becomes relevant, by creating a PR directly"

PR - #3545

**Comment by chris-short** [comment]
Hi @Prajyot-Parab. Please close this request and use this template to create a new request: https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E

Thank you!
