### ISSUE TITLE
REQUEST: New membership for @nwoods3

### ISSUE THREAD

**Issue by nwoods3** [kubernetes/org#355]
### GitHub Username
@nwoods3

### Organization you are requesting membership in
Kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ X] I am actively contributing to 1 or more Kubernetes subprojects
- [X ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@spiffxp 
@kbarnard10

### List of contributions to the Kubernetes project
- Communications shadow for 1.8 release
- Communications lead for 1.9. 1.10 and 1.14 releases
- Assist in posting to (@kubernetesio)

**Comment by kbarnard10** [comment]
+1

**Comment by spiffxp** [comment]
+1 from me as well

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #358 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
