### ISSUE TITLE
REQUEST: New membership for koba1t

### ISSUE THREAD

**Issue by koba1t** [kubernetes/org#3554]
### GitHub Username

koba1t

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@natasha41575

### Sponsor 2

@KnVerey

## PR

- https://github.com/kubernetes/ingress-nginx/pull/5613
- https://github.com/kubernetes-sigs/cli-experimental/pull/212
- https://github.com/kubernetes-sigs/kustomize/pull/4411
- https://github.com/kubernetes-sigs/kustomize/pull/4424
- https://github.com/kubernetes-sigs/cli-experimental/pull/240
- https://github.com/kubernetes-sigs/kustomize/pull/4486
- https://github.com/kubernetes-sigs/kustomize/pull/4518
- https://github.com/kubernetes-sigs/kustomize/pull/4558
- https://github.com/kubernetes-sigs/kustomize/pull/4577
- https://github.com/kubernetes-sigs/kustomize/pull/4608
- https://github.com/kubernetes-sigs/kustomize/pull/4692
- https://github.com/kubernetes-sigs/kustomize/pull/4698
- https://github.com/kubernetes-sigs/kustomize/pull/4699

## Issue
- https://github.com/kubernetes/kubectl/issues/1168
- https://github.com/kubernetes-sigs/kustomize/issues/4517
- https://github.com/kubernetes-sigs/kustomize/issues/4053
- https://github.com/kubernetes-sigs/kustomize/issues/4561

**Comment by KnVerey** [comment]
+1 from me!

**Comment by natasha41575** [comment]
+1 from me as well

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3563  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
