### ISSUE TITLE
REQUEST: New membership for <Nitish Kumar>

### ISSUE THREAD

**Issue by NitishKumar06** [kubernetes/org#3557]
### GitHub Username

@NitishKumar06

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mehabhalodiya

### Sponsor 2

@dims

### List of contributions to the Kubernetes project

The following PRs have been merged:
https://github.com/kubernetes/website/pull/34019
https://github.com/kubernetes/website/pull/34173
https://github.com/kubernetes/website/pull/34297
https://github.com/kubernetes/website/pull/34422
https://github.com/kubernetes/website/pull/34560
https://github.com/kubernetes/website/pull/34568
https://github.com/kubernetes/website/pull/34872

The following PRs are Opened:
https://github.com/kubernetes/website/pull/34037
https://github.com/kubernetes/website/pull/34281
https://github.com/kubernetes/website/pull/34471
https://github.com/kubernetes/website/pull/34764
https://github.com/kubernetes/website/pull/34932

Subproject I'm contributing to: Kubernetes/website, Kubernetes/community

**Comment by mehabhalodiya** [comment]
+1

Thanks for your contributions so far; looking forward to more of them.

**Comment by dims** [comment]
+1 from me.

**Comment by mrbobbytables** [comment]
Hey there, thank you for all your contributions so far :)

I've created PR #3563  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
