### ISSUE TITLE
REQUEST: Generate a new GITHUB_TOKEN for Prow tasks running on the GitHub Project Beta board. 

### ISSUE THREAD

**Issue by Priyankasaggu11929** [kubernetes/org#3558]
The Kubernetes Release Team Enhancements sub-project is attempting to move away from using a Google Spreadsheet (as is [presently done](https://docs.google.com/spreadsheets/d/1Lnft8598eIQsqBp8W6X_LwaqBNZViYssQoFgGS8aJ3g/edit#gid=0)) and towards a more GitHub friendly solution for tracking KEP/enhancements that are opted-in during a Kubernetes release cycle.

The team proposes using a Periodic prow job executing a script that will be introduced as part of this PR kubernetes/sig-release#1968 to input and sync data into an Enhancements GitHub Project Beta board.

The script uses GitHub CLI to do the necessary tasks and expects a `GITHUB_TOKEN` Env variable available in the Prow Job container with the following appropriate permissions (for authentication):

- **repo:**
    - **public_repo:** Access public repositories 
- **write:org:** Read and write org and team membership, read and write org projects
- **read:org:** Read org and team membership, read org projects
-  **project:** Full control of projects
    - **read:project** Read access of projects

This issue is to track the creation of the requested `GITHUB_TOKEN` and add it to one of the prow build clusters. 

cc: @ameukam  @palnabarun @mrbobbytables

**Comment by ameukam** [comment]
You can reuse the Github token stored as secret `k8s-triage-robot-github-token` in the GKE cluster `k8s-infra-prow-build-trusted. 

@cblecker WDYT ? it's currently use for triage : https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-contribex-k8s-triage-robot.yaml.

**Comment by cici37** [comment]
cc

**Comment by Priyankasaggu11929** [comment]
Thanks @ameukam. I'll go ahead with using the `k8s-triage-robot-github-token` token for the prow job, once @cblecker confirms. :)

**Comment by Priyankasaggu11929** [comment]
Taking it as no objection on using the token `k8s-triage-robot-github-token` for the periodic runs of automation script for Release Team Enhancements tracking GitHub boards. Thank you!

**Comment by rhockenbury** [comment]
@ameukam - We have tried to use the token `k8s-triage-robot-github-token` but that token does not have the correct scopes to interact with Github project boards.   We need a token that also has the `project` scope. 

For reference - Here's the [full error message](https://prow.k8s.io/log?job=periodic-sync-enhancements-github-project-beta-1-26&id=1569883988930072576), the current [job configuration](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-release-release-team-jobs/release-team-periodics.yaml), and the [enhancement sync script](https://github.com/kubernetes/sig-release/blob/master/release-team/hack/sync-enhancements-github-project-beta.sh).

Can we (1) modify the scope for `k8s-triage-robot-github-token` or (2) generate a new token with the requested scopes?

**Comment by ameukam** [comment]
> @ameukam - We have tried to use the token `k8s-triage-robot-github-token` but that token does not have the correct scopes to interact with Github project boards. We need a token that also has the `project` scope.
> 
> For reference - Here's the [full error message](https://prow.k8s.io/log?job=periodic-sync-enhancements-github-project-beta-1-26&id=1569883988930072576), the current [job configuration](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-release-release-team-jobs/release-team-periodics.yaml?rgh-link-date=2022-09-14T03%3A16%3A46Z), and the [enhancement sync script](https://github.com/kubernetes/sig-release/blob/master/release-team/hack/sync-enhancements-github-project-beta.sh?rgh-link-date=2022-09-14T03%3A16%3A46Z).
> 
> Can we (1) modify the scope for `k8s-triage-robot-github-token` or (2) generate a new token with the requested scopes?

Option (2) seems like the logical path for this use case. I'll try to generate a new token with the required scopes. Is it possible to get the full of permissions required for this token ?

**Comment by rhockenbury** [comment]
Thanks.  I tested the permissions.  The token needs to have **public_repo** and **project**.

**Comment by rhockenbury** [comment]
@ameukam ^ Gentle bump.  Do you have a rough idea of the timeline for getting that new token?

**Comment by ameukam** [comment]
> @ameukam ^ Gentle bump. Do you have a rough idea of the timeline for getting that new token?

@rhockenbury Somehow I missed your comments, I'll try to get this done as soon I have some time.

**Comment by ameukam** [comment]
Created the token and it will be synced to the build cluster as `k8s-release-enhancements-triage-github-token`:  https://github.com/kubernetes/k8s.io/pull/4259.

@rhockenbury @Priyankasaggu11929 we should update the ProwJob to use the new secret.

**Comment by Priyankasaggu11929** [comment]
Thanks so much for the help, @ameukam.

Raised a PR to update the ProwJob to use the new secret - https://github.com/kubernetes/test-infra/pull/27607

**Comment by Priyankasaggu11929** [comment]
Just an update: despite the new secret and GITHUB TOKEN, the job still failed.

Arnaud and I will get on a call, next week and manually test in with a new GITHUB TOKEN before reinstating the job.

cc: @rhockenbury @leonardpahlke

**Comment by leonardpahlke** [comment]
OK! If there is anything I can help with, please let me know. :)

**Comment by palnabarun** [comment]
@Priyankasaggu11929 -- were you able to get on a call and debug this?

@ameukam (when you are back from PTO) -- which account did you create the token for? and are the permissions as mentioned in https://github.com/kubernetes/org/issues/3558#issuecomment-1246822871 ?

**Comment by Priyankasaggu11929** [comment]
The Prow job with bad credentials has not yet been fixed despite many attempts by @ameukam and myself to test with various GH PAT tokens.

The SIG Release leads have agreed to use GitHub Actions Workflow as the latest update on automating the Enhancements board, as discussed in [this slack conversation](https://kubernetes.slack.com/archives/C2C40FMNF/p1667447493240069).

The bug-triage team also has [a similar workflow](https://kubernetes.slack.com/archives/C2C40FMNF/p1670847344108339?thread_ts=1670846775.131279&cid=C2C40FMNF), so it may be useful to adopt a similar approach for automating Enhancements tracking board too.

With that, it seems ok to close this issue for now and reopen if needed in the future.

/close

**Comment by ameukam** [comment]
> @Priyankasaggu11929 -- were you able to get on a call and debug this?
> 
> @ameukam (when you are back from PTO) -- which account did you create the token for? and are the permissions as mentioned in [#3558 (comment)](https://github.com/kubernetes/org/issues/3558#issuecomment-1246822871) ?

Token was created from @k8s-infra-ci-robot but revoked as mentioned in https://github.com/kubernetes/org/issues/3558#issuecomment-1373250662.
