### ISSUE TITLE
REQUEST: New membership for @kkkkun

### ISSUE THREAD

**Issue by kkkkun** [kubernetes/org#3561]
### GitHub Username

@kkkkun 

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

Sponsors

@wojtek-t 
@pacoxu 
@dims 
@humblec 
@serathius 

### List of contributions to the Kubernetes project

authored

- https://github.com/kubernetes/kubernetes/pull/105648
- https://github.com/kubernetes/kubernetes/pull/107042
- https://github.com/kubernetes/kubernetes/pull/107724
- https://github.com/kubernetes/kubernetes/pull/108271
- https://github.com/kubernetes/kubernetes/pull/111835
- https://github.com/kubernetes/kubernetes/pull/111988
- https://github.com/kubernetes/kubernetes/pull/114774
- https://github.com/kubernetes/kubernetes/pull/117332
- https://github.com/kubernetes/kubernetes/pull/117335
- https://github.com/kubernetes/kubernetes/pull/117342
- https://github.com/kubernetes/k8s.io/pull/5157
- https://github.com/kubernetes/kubernetes/pull/117354
- https://github.com/kubernetes/kubernetes/pull/117860
- https://github.com/kubernetes/kubernetes/pull/117879
- https://github.com/kubernetes/kubernetes/pull/117999
- https://github.com/kubernetes/k8s.io/pull/5284

and there are several [working PRs](https://github.com/kubernetes/kubernetes/pulls/kkkkun):
Issues responded to
- https://github.com/kubernetes/kubernetes/issues/106679
- https://github.com/kubernetes/kubernetes/issues/112319
- https://github.com/kubernetes/kubernetes/issues/108630
- https://github.com/kubernetes/kubernetes/issues/117557
- https://github.com/kubernetes/kubernetes/issues/117341
- https://github.com/kubernetes/kubernetes/issues/117957

SIG projects I am involved with
https://github.com/kubernetes/kubernetes
/area github-membership

**Comment by chris-short** [comment]
Hey @kkkkun, we need your sponsors to +1 this request

**Comment by pohly** [comment]
@kkkkun I think your PRs are valuable contributions to Kubernetes, but I have only reviewed one PR from you and it wasn't very complex, therefore I don't believe that I qualify as a sponsor ("sponsors must have close interactions with the prospective member").

Keep up the good work and I'm sure you'll be ready to become a member soon.

**Comment by kkkkun** [comment]
> @kkkkun I think your PRs are valuable contributions to Kubernetes, but I have only reviewed one PR from you and it wasn't very complex, therefore I don't believe that I qualify as a sponsor ("sponsors must have close interactions with the prospective member").
> 
> Keep up the good work and I'm sure you'll be ready to become a member soon.

Thanks.

**Comment by kkkkun** [comment]
@wojtek-t  @dims  @humblec @pacoxu @serathius  Please cc, Thanks.

**Comment by pacoxu** [comment]
+1 
Thanks for your contributions.

**Comment by serathius** [comment]
+1

**Comment by dims** [comment]
+1 from me!

**Comment by Priyankasaggu11929** [comment]
@kkkkun,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4268 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
