### ISSUE TITLE
REQUEST: Need `PullRequests` and `Contents` write permissions for `GITHUB_TOKEN` in CAPA GitHub workflows

### ISSUE THREAD

**Issue by zeborg** [kubernetes/org#3562]
The [kubernetes-sigs/cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws) repository requires `PullRequests` and `Contents` write permissions for `GITHUB_TOKEN` within the [ami_periodic.yaml](https://github.com/zeborg/cluster-api-provider-aws/blob/main/.github/workflows/ami_periodic.yaml) GitHub workflow that we've [tested](https://github.com/zeborg/cluster-api-provider-aws/runs/7005985945?check_suite_focus=true) as being fully functional on [my fork](https://github.com/zeborg/cluster-api-provider-aws). We tried to manually elevate these permissions in an earlier version of this action [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/runs/6375227457?check_suite_focus=true), but the `GITHUB_TOKEN` secret would only reflect with `read` permissions despite providing the `pull-requests: write` and `contents: write` declarations in the workflow.

The PR creation is currently being automated in my fork using a 3rd party GitHub application that I created in order to overcome this GitHub workflow restriction on the target repository, but ideally we would like to refrain from maintaining a custom GitHub application and would instead prefer to utilize `GITHUB_TOKEN` wherever possible.

Following up on the discussion held in the GitHub Administration meeting held on 7th July 2022, we'd like to keep using GitHub actions for this purpose instead of Prow, _at least for now_, due to the following concerns:
* To easen the process of environment secret updates as well as debugging in case of unexpected errors by executing all the workflows related to this action on GitHub alone
* To be able to customize the configuration for the `image-builder` environment variables using a custom config file within the repository itself
* To be able to trigger the PR creation within the repository by manual intervention in addition to the periodic action

Ref: [proposal: CAPA AMI GitHub Action](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3514/files)

/cc @sedefsavas @richardcase @ameukam

**Comment by sedefsavas** [comment]
Thanks for opening the PR @zeborg 

In summary, we want a github action to create a PR whenever a new Kubernetes release is out.

We'd like to understand if at the organizational level `GITHUB_TOKEN` permissions are restrictive. In CAPA repo, our config is permissive so trying to understand the reason why github action is failing to use `GITHUB_TOKEN` to create PRs.  

@ameukam @palnabarun (as you commented on this in the previous meeting), do you know who could check the permissions at the kubernetes sigs level?

**Comment by ameukam** [comment]
I would recommend to create a new token from a pot (k8s-infra-ci-robot ?) and add it as secret for usage the kubernetes infrastructure.

**Comment by richardcase** [comment]
This request is still valid so:

/remove-lifecycle stale

**Comment by richardcase** [comment]
> I would recommend to create a new token from a pot (k8s-infra-ci-robot ?) and add it as secret for usage the kubernetes infrastructure.


@ameukam - how would we go about doing that?

**Comment by richardcase** [comment]
I don't think we need this any more:

/close
