### ISSUE TITLE
REQUEST: Netlify site for Kustomize

### ISSUE THREAD

**Issue by KnVerey** [kubernetes/org#3564]
### Repository

https://github.com/kubernetes-sigs/kustomize

### Project domain

kustomize.io

### Additional context for request

Kustomize's documentation is currently fragmented across several different locations. kustomize.io has the best SEO but was built and maintained by Replicated, not the community. They have donated the domain for us to use, and we would like to consolidate all our content onto a new site on that domain that mirrors the kubernetes.io documentation style. SIG CLI has obtained SIG Docs buy-in for this project, and we have begun to migrate content for this new, consolidated site into the Kustomize repo. Tracking issue is https://github.com/kubernetes-sigs/kustomize/issues/4338.

Although we are not ready to publish the new site, we are hoping to get Netlify set up so that we can take advantage of branch previews to help with the review process during the consolidation effort. Is that possible?

**Comment by ameukam** [comment]
I think it's technical possible. Please see https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md

cc @mrbobbytables @cblecker

**Comment by KnVerey** [comment]
In that case, I'd like to proceed with this Netlify request, without requesting a corresponding domain at this point--we'll use the netlify preview links for now, and make a special request to link the kustomize.io domain rather than the usual SIG subdomain when we're ready. 

> Please see https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md

That's how I got here in the first place. Is there something in particular I should do and have missed? 😄

**Comment by KnVerey** [comment]
Thanks! I'm not sure what the problem is there, but we'll figure it out. 

Would it be possible to disable [pull request comments](https://docs.netlify.com/site-deploys/notifications/#github-pull-request-comments) and [commit checks](https://docs.netlify.com/site-deploys/notifications/#github-commit-checks) for this project? They are very noisy, given that most of our PRs won't be for the site, and it seems like they can only be changed from a Netlify UI I don't have access to.

**Comment by KnVerey** [comment]
Another setting change request: could you please set the base directory to `site` in the UI? I would prefer to keep our `netlify.toml` in there to encapsulate the site, instead of needing to put it in the root. According to the docs, that setting is at `Settings > Build & deploy > Continuous Deployment > Build settings`

**Comment by cblecker** [comment]
@KnVerey I believe I have made all the settings adjustments you have requested. Can you check and verify things are now working as you want? Thanks!

**Comment by KnVerey** [comment]
Thanks! It seems to now pick up the right file, and the commit **checks** are gone, but so is the [commit **status**](https://docs.netlify.com/site-deploys/notifications/#github-commit-statuses). Did you disable that too, and if so can you add it back?

**Comment by cblecker** [comment]
Ah yes, I shut them all off. Can you try again?

**Comment by KnVerey** [comment]
That did it--everything looks good to me now! Site successfully built off a PR changing `site/` in https://github.com/kubernetes-sigs/kustomize/pull/4732, and confirmed to ignore changes in other directories in https://github.com/kubernetes-sigs/kustomize/pull/4735. Also confirmed to skip master builds (for now), e.g.: https://app.netlify.com/sites/kubernetes-sigs-kustomize/deploys/62e435fc4b271a000958f3d8. We'll change that and make the request for the real domain once the site is ready. 

Thanks so much @cblecker @palnabarun !
