### ISSUE TITLE
REQUEST: New membership for sarazqy

### ISSUE THREAD

**Issue by sarazqy** [kubernetes/org#3567]
### GitHub Username

@sarazqy

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tengqm

### Sponsor 2

@mengjiao-liu

### List of contributions to the Kubernetes project

PRs reviewed / authored

https://github.com/kubernetes/website/pull/34985
https://github.com/kubernetes/website/pull/35036
https://github.com/kubernetes/website/pull/34748
https://github.com/kubernetes/website/pull/34746
https://github.com/kubernetes/website/pull/35023
https://github.com/kubernetes/website/pull/34717
https://github.com/kubernetes/website/pull/34256
https://github.com/kubernetes/website/pull/32440

Issues

https://github.com/kubernetes/website/issues/35161
https://github.com/kubernetes/website/issues/35159
https://github.com/kubernetes/website/issues/35158
https://github.com/kubernetes/website/issues/34294
https://github.com/kubernetes/website/issues/34193
https://github.com/kubernetes/website/issues/34192
https://github.com/kubernetes/website/issues/34191
https://github.com/kubernetes/website/issues/33588
https://github.com/kubernetes/website/issues/32875
https://github.com/kubernetes/website/issues/32267

SIG projects I am involved with
kubernetes
kubernetes-sigs

**Comment by mengjiao-liu** [comment]
Thank @sarazqy for the work done so far, and looking forward to what will come!

**Comment by tengqm** [comment]
+1

**Comment by palnabarun** [comment]
@sarazqy -- Thank you for all your contributions so far!

I have raised #3581 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉 

/assign
