### ISSUE TITLE
REQUEST: New membership for yankay

### ISSUE THREAD

**Issue by yankay** [kubernetes/org#3569]
### GitHub Username

@yankay

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@cristicalin

### Sponsor 2

@floryut

### List of contributions to the Kubernetes project

The following PRs have been merged:

https://github.com/kubernetes-sigs/kubespray/pull/9099
https://github.com/kubernetes-sigs/kubespray/pull/9100
https://github.com/kubernetes-sigs/kubespray/pull/9047
https://github.com/kubernetes-sigs/kubespray/pull/9007
https://github.com/kubernetes-sigs/kubespray/pull/9049
https://github.com/kubernetes-sigs/kubespray/pull/9027
https://github.com/kubernetes-sigs/kubespray/pull/9016
https://github.com/kubernetes-sigs/kubespray/pull/8987
https://github.com/kubernetes-sigs/kubespray/pull/8988
https://github.com/kubernetes-sigs/kubespray/pull/8958
https://github.com/kubernetes-sigs/kubespray/pull/8950
https://github.com/kubernetes-sigs/kubespray/pull/8951
https://github.com/kubernetes-sigs/kubespray/pull/8831

https://github.com/kubernetes/autoscaler/pull/4738
https://github.com/kubernetes/node-problem-detector/pull/650
https://github.com/kubernetes-sigs/kpng/pull/275
https://github.com/kubernetes-sigs/kpng/pull/251
https://github.com/kubernetes-sigs/kpng/pull/180

**Comment by floryut** [comment]
👍 very nice contrib from @yankay !

Great to have you onboard and hope for more contrib from you.

谢谢你 (did I get that right ? 😆 )

**Comment by yankay** [comment]
> +1
> 
> 👍 very nice contrib from @yankay !
> 
> Great to have you onboard and hope for more contrib from you.
> 
> 谢谢你 (did I get that right ? 😆 )

Thanks. It's my pleasure to contribute.  :-)

**Comment by cristicalin** [comment]
+1

👍  Thank you @yankay and looking forward to your continued work in the community!

**Comment by yankay** [comment]
> +1
> 
> 👍 Thank you @yankay and looking forward to your continued work in the community!

Thank you. I want to become work better.

**Comment by palnabarun** [comment]
@yankay -- Thank you for all your contributions so far!

I have raised #3581 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉 

/assign

**Comment by yankay** [comment]
Happy to contribute! Will keep improving. 😊
