### ISSUE TITLE
REQUEST: Migrate to a new repo kubernetes-sigs/windows-operational-readiness

### ISSUE THREAD

**Issue by iXinqi** [kubernetes/org#3585]
### New repo, staging repo, or migrate existing

Migrate repo from https://github.com/K8sbykeshed/op-readiness to this new repo

### Is it a staging repo?

no

### Requested name for new repository

windows-operational-readiness

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@knabben, @iXinqi, @jayunit100

### Who should have write access?

@knabben, @iXinqi, @jayunit100

### Who should be listed as approvers in OWNERS?

@knabben, @iXinqi, @jayunit100

### Who should be listed in SECURITY_CONTACTS?

@knabben, @iXinqi

### What should the repo description be?

Define an operational readiness standard for Kubernetes clusters supporting Windows that certifies the readiness of Windows clusters for running production workloads

### What SIG and subproject does this fall under?

this is a new subproject for sig-windows

### Please provide references to appropriate approval for this new repo

Tagging the sig-windows leads on this for across the board approval @jsturtevant @marosset

Reach the maintainers of this project at:

[Slack channel](https://kubernetes.slack.com/messages/sig-windows)
[Mailing list](https://groups.google.com/g/kubernetes-sig-windows)

**Comment by marosset** [comment]
This new repo will the the home for work outlined in https://github.com/kubernetes/enhancements/issues/2578

/lgtm

**Comment by iXinqi** [comment]
Hi @nikhita, may I have your review on this issue? Thanks!

**Comment by iXinqi** [comment]
Hi @caniszczyk, could you please help with checking if the licenses of dependencies are acceptable?

**Comment by caniszczyk** [comment]
@iXinqi this is OK from a CNCF POV, good luck with the new project!

**Comment by nikhita** [comment]
@iXinqi the repo looks ready for migration :+1: 

Can you please give me admin access on the repo so I can migrate it to k-sigs?
Please ping me on slack once you do so. Thanks!

**Comment by nikhita** [comment]
Repo has been migrated! https://github.com/kubernetes-sigs/windows-operational-readiness :tada:

We can close this issue once https://github.com/kubernetes/community/pull/6772 gets merged.

**Comment by nikhita** [comment]
This is now done! Closing.

**Comment by iXinqi** [comment]
Thanks @nikhita @marosset and @caniszczyk! Appreciated!
