### ISSUE TITLE
Repository rename:  https://github.com/kubernetes-sigs/special-resource-operator to https://github.com/kubernetes-sigs/kernel-module-management

### ISSUE THREAD

**Issue by bthurber** [kubernetes/org#3587]
As part of SIG-node we initially received acceptance for creating a new repo and on-boarding technology to assist with managing out-of-tree drivers for Kubernetes.  The repo was created here:  https://github.com/kubernetes-sigs/special-resource-operator  We have received acks to rename the repo to:  https://github.com/kubernetes-sigs/kernel-module-management which matches the new operator, more closely aligning to Kubernetes best practices.  This will allow pushing the code base to the repo and allow for upstream collaboration.

**Comment by cblecker** [comment]
@bthurber I've moved this to the correct repo so that it can be actioned by the github admins.

When would you like to do this? Note that it will likely be disruptive, as there are multiple moving pieces (such as updating test-infra jobs).

**Comment by cblecker** [comment]
test-infra references to this repo: https://cs.github.com/?scopeName=All+repos&scope=&q=repo%3Akubernetes%2Ftest-infra+special-resource-operator

**Comment by bthurber** [comment]
> test-infra references to this repo: https://cs.github.com/?scopeName=All+repos&scope=&q=repo%3Akubernetes%2Ftest-infra+special-resource-operator

Thanks!  It is OK to make the change ASAP.  The repo doesn't have any content in it atm and we are waiting to push our code there post rename.

**Comment by cblecker** [comment]
@bthurber Sounds good. I've renamed the repo. Could you please submit PRs to test-infra to update the jobs, as well as update sigs.yaml in the community repo (https://github.com/kubernetes/community/blob/11f8c35fa86ee29108503aca5532b994cda74926/sigs.yaml#L2110-L2112) ?

**Comment by ybettan** [comment]
@cblecker Here is the PR for test-infra https://github.com/kubernetes/test-infra/pull/27012
