### ISSUE TITLE
REQUEST: New membership for knelasevero

### ISSUE THREAD

**Issue by knelasevero** [kubernetes/org#3588]
### GitHub Username

@knelasevero

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@damemi

### Sponsor 2

@ingvagabund

### PRs involved in (created/reviewed):
https://github.com/kubernetes-sigs/descheduler/pull/888
https://github.com/kubernetes-sigs/descheduler/pull/852
https://github.com/kubernetes-sigs/descheduler/pull/854
https://github.com/kubernetes-sigs/descheduler/pull/871
https://github.com/kubernetes-sigs/descheduler/pull/860
https://github.com/kubernetes-sigs/descheduler/pull/895
https://github.com/kubernetes-sigs/descheduler/pull/861
https://github.com/kubernetes-sigs/descheduler/pull/892
https://github.com/kubernetes/kubernetes/pull/111155

### Issues:
https://github.com/kubernetes-sigs/descheduler/issues/845
https://github.com/kubernetes/kubernetes/issues/111672
https://github.com/kubernetes/kubernetes/issues/91633
https://github.com/kubernetes-sigs/descheduler/issues/884
https://github.com/kubernetes-sigs/descheduler/issues/844
https://github.com/kubernetes-sigs/descheduler/issues/837

### SIGs I am involved with:
sig-scheduling

CC: @damemi @ingvagabund

**Comment by knelasevero** [comment]
@rikatz let me throw you under the bus as well since we chatted about this :joy:

**Comment by rikatz** [comment]
+1 from me :)

**Comment by ingvagabund** [comment]
It has been great working with You :) Happy to see you grow and shine
+1

**Comment by damemi** [comment]
+1, thanks for all the great work!

**Comment by palnabarun** [comment]
@knelasevero -- Thank you for all your contributions so far!

I have raised #3606 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
