### ISSUE TITLE
REQUEST: New membership for bconfiden2

### ISSUE THREAD

**Issue by bconfiden2** [kubernetes/org#3595]
### GitHub Username

bconfiden2

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@yoonian 

### Sponsor 2

@jihoon-seo 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/website/pulls?q=is%3Apr+commenter%3Abconfiden2
- Issues responded to
https://github.com/kubernetes/website/issues/bconfiden2
- SIG projects I am involved with
kubernetes/sig-docs

**Comment by seokho-son** [comment]
+1, 
@bconfiden2 is actively involved in SIG-Docs and Korean localization. 
I'm happy to work with @bconfiden2 !

**Comment by jihoon-seo** [comment]
+1 Thank you for your contribution effort!

**Comment by yoonian** [comment]
+1 It is good to hear, I'm also happy to work together, @bconfiden2!

**Comment by palnabarun** [comment]
Hi @bconfiden2, the sponsors are required to be from different organizations. I noticed that @seokho-son and @jihoon-seo work at the same organization.

@yoonian -- can you please confirm your organization so that we can accept your +1?

**Comment by yoonian** [comment]
@palnabarun Yes, sure.

**Comment by sysnet4admin** [comment]
+1 @bconfiden2 is very active contritutor in SIG-Docs and Korean localization!!!

**Comment by yoonian** [comment]
Also, as a sponsor, I work for a different organization than @seokho-son, @jihoon-seo, and @bconfiden2. You can check it out on my profile.

**Comment by bconfiden2** [comment]
@palnabarun changed the sponsors to @yoonian @jihoon-seo 
Thanks! 😃

**Comment by palnabarun** [comment]
@bconfiden2 -- Thank you for all your contributions so far!

I have raised #3620 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
