### ISSUE TITLE
REQUEST: New membership for yibozhuang

### ISSUE THREAD

**Issue by yibozhuang** [kubernetes/org#3598]
### GitHub Username

@yibozhuang

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei

### Sponsor 2

@wzshiming

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/105196
  - https://github.com/kubernetes/kubernetes/pull/109715
  - https://github.com/kubernetes/kubernetes/pull/105245
  - https://github.com/kubernetes-sigs/scheduler-plugins/pull/408
  - https://github.com/kubernetes-sigs/scheduler-plugins/pull/344

- Issues responded to
  - https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/302
  - https://github.com/kubernetes/kubernetes/issues/109876

- SIG projects I am involved with
  - sig-scheduling
  - sig-storage

**Comment by Huang-Wei** [comment]
+1

**Comment by wzshiming** [comment]
+1

**Comment by palnabarun** [comment]
@yibozhuang -- Thank you for all your contributions so far!

I have raised #3606 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
