### ISSUE TITLE
REQUEST: New membership for jinnypark9393

### ISSUE THREAD

**Issue by jinnypark9393** [kubernetes/org#3599]
### GitHub Username

jinnypark9393

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@seokho-son

### Sponsor 2

@yoonian

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ajinnypark9393+
- Issues responded to
https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Ajinnypark9393
- SIG projects I am involved with
kubernetes/sig-docs

**Comment by jihoon-seo** [comment]
+1 @jinnypark9393 is an active contributor, especially in Korean L10n work of K8s Docs!

**Comment by yoonian** [comment]
+1 @jinnypark9393

**Comment by seokho-son** [comment]
+1  I am happy to be a sponsor for @jinnypark9393

**Comment by palnabarun** [comment]
Hi @jinnypark9393, the sponsors are required to be from different organizations. I noticed that @seokho-son and @jihoon-seo work at the same organization.

@yoonian -- can you please confirm your organization so that we can accept your +1?

**Comment by yoonian** [comment]
@palnabarun Yes, sure.

**Comment by jinnypark9393** [comment]
> Hi @jinnypark9393, the sponsors are required to be from different organizations. I noticed that @seokho-son and @jihoon-seo work at the same organization.
> 
> @yoonian -- can you please confirm your organization so that we can accept your +1?

Apologize for the late reply. I changed sponsor 2 to @yoonian.

> @yoonian, Thanks for the +1 👍

**Comment by sysnet4admin** [comment]
+1 @jinnypark9393 support! I cannot wait for jinny's joining and further contributing.

**Comment by yoonian** [comment]
Also, as a sponsor, I work for a different organization than @seokho-son, @jihoon-seo, and @jinnypark9393. You can check it out on my profile.

**Comment by palnabarun** [comment]
@jinnypark9393 -- Thank you for all your contributions so far!

I have raised #3620 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
