### ISSUE TITLE
REQUEST: New membership for nasa9084

### ISSUE THREAD

**Issue by nasa9084** [kubernetes/org#36]
### GitHub Username
@nasa9084

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah
- @xiangpengzhao

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    + https://github.com/kubernetes/kubernetes-docs-ja/pull/4
- Issues responded to: nil
- SIG projects I am involved with
    + sig-docs (k/kubernetes-docs-ja)

**Comment by zacharysarah** [comment]
+1

**Comment by xiangpengzhao** [comment]
+1

**Comment by spiffxp** [comment]
/close
invite sent, welcome!

**Comment by nasa9084** [comment]
Thanks!
