### ISSUE TITLE
REQUEST: New membership for egernst

### ISSUE THREAD

**Issue by egernst** [kubernetes/org#360]
### GitHub Username
egernst

### Organization you are requesting membership 

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tpepper 
- @tallclair
- @mrunalp 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes-sigs/cri-o/pull/1701
https://github.com/kubernetes-sigs/cri-o/pull/1703
https://github.com/kubernetes-sigs/cri-o/pull/683

- Issues responded (authored) to
https://github.com/kubernetes-sigs/cri-o/issues/1751
https://github.com/kubernetes/enhancements/issues/688

- SIG projects I am involved with: 
https://github.com/kubernetes-sigs/cri-o
https://github.com/kubernetes/community/tree/master/sig-node

**Comment by tpepper** [comment]
This is a slightly odd situation in that historically there’s a desire for a bit of a contribution track record (but a pragmatically low bar to surpass) in the kubernetes org yet there’s almost zero data supporting that in GitHub or DevStats.  Coupled with this being associated with an intent to work on a KEP, the optics here might be misunderstood to the tune of people thinking some big ecosystem vendor is trying to push a feature on the community.  IMHO none of this is the case, but I say just to be explicit.  In fact Eric’s worked extensively over years now on the periphery of core Kubernetes through his Kata Containers and associated runtime and CRI work and it’s great to see him stepping up to do more in the core via an issue that was marked “help wanted” by Tim Allclair.  I believe Eric is a welcome and trusted member of our community.  So a big +1 from me!

**Comment by egernst** [comment]
thanks @tpepper

**Comment by tallclair** [comment]
Well said, @tpepper. +1 from me as well.

**Comment by mrbobbytables** [comment]
@egernst, thank you for all the work you've put into crio :)

I've created PR #365   to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
