### ISSUE TITLE
REQUEST: New membership for mimowo

### ISSUE THREAD

**Issue by mimowo** [kubernetes/org#3602]
### GitHub Username

@mimowo

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alculquicondor

### Sponsor 2

@soltysh

### List of contributions to the Kubernetes project

PRs authored:
https://github.com/kubernetes/kubernetes/pull/110292
https://github.com/kubernetes/kubernetes/pull/111070
https://github.com/kubernetes/kubernetes/pull/111084
https://github.com/kubernetes/kubernetes/pull/111091
https://github.com/kubernetes/kubernetes/pull/110959
https://github.com/kubernetes/kubernetes/pull/111113

https://github.com/kubernetes/enhancements/pull/3374
https://github.com/kubernetes/enhancements/pull/3438
https://github.com/kubernetes/enhancements/pull/3447

https://github.com/kubernetes/website/pull/35219

PRs reviewed:
https://github.com/kubernetes/kubernetes/pull/110294
https://github.com/kubernetes/kubernetes/pull/111475

Issues created:
https://github.com/kubernetes/kubernetes/issues/111140
https://github.com/kubernetes/kubernetes/issues/111183
https://github.com/kubernetes/kubernetes/issues/111308
https://github.com/kubernetes/kubernetes/issues/111612
https://github.com/kubernetes/kubernetes/issues/111614

**Comment by soltysh** [comment]
:+1: from my side

**Comment by alculquicondor** [comment]
:smiley: :+1:

**Comment by palnabarun** [comment]
@mimowo -- Thank you for all your contributions so far!

I have raised https://github.com/kubernetes/org/pull/3606 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
