### ISSUE TITLE
REQUEST: New membership for Shubham82

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/org#3604]
### GitHub Username

@Shubham82

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@gjtempleton

### Sponsor 2

@jihoon-seo

### List of contributions to the Kubernetes project

- PRs reviewed/authored
  https://github.com/search?q=is%3Apr+author%3Ashubham82++org%3Akubernetes+org%3Akubernetes-sigs&type=Issues
- Issues responded to
  https://github.com/search?q=commenter%3Ashubham82++org%3Akubernetes+org%3Akubernetes-sigs&type=Issues
- SIG projects I am involved with
  sig-auth
  sig-autoscaling

**Comment by jihoon-seo** [comment]
+1
@Shubham82 is an active K8s contributor, and I am happy to be a sponsor!

**Comment by gjtempleton** [comment]
+1
Shubam's been actively involved with SIG Autoscaling, improving our docs, answering user queries, and contributing code for a while now, looking forward to his continued involvement!

**Comment by palnabarun** [comment]
@Shubham82 -- Thank you for all your contributions so far!

I have raised https://github.com/kubernetes/org/pull/3606 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign

**Comment by Shubham82** [comment]
Thanks, Everyone!
