### ISSUE TITLE
REQUEST: Migrate oci-proxy

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/org#3605]
### New repo, staging repo, or migrate existing

kubernetes-sigs/oci-proxy

### Is it a staging repo?

no

### Requested name for new repository

registry.k8s.io

### Which Organization should it reside

kubernetes

### Who should have admin access?

ameukam, bentheelder, dims, thockin

### Who should have write access?

ameukam, bentheelder, dims, thockin

### Who should be listed as approvers in OWNERS?

ameukam, bentheelder, dims, thockin

### Who should be listed in SECURITY_CONTACTS?

ameukam, bentheelder, dims, thockin

### What should the repo description be?

A custom HTTP redirector serving Kubernetes container image blobs from existing vendor supported container registries.

### What SIG and subproject does this fall under?

sig-k8s-infra

### Please provide references to appropriate approval for this new repo

https://github.com/kubernetes-sigs/oci-proxy/issues/94#issuecomment-1211308265

**Comment by dims** [comment]
+1

**Comment by ameukam** [comment]
+1

**Comment by Riaankl** [comment]
/assign @nikhita @mrbobbytables 

Is there any "next steps" that we should disucss or start working on?

**Comment by Riaankl** [comment]
This issue was discussed today in SIG K8s Infra meeting.

According to the [guidance given](https://github.com/kubernetes-sigs/oci-proxy/issues/94#issuecomment-1211410066) by @cblecker we need the blessing of SIG Arch to finalize the rename and relocating op OCI-Proxy repo.
It would be good to get that done asap, as reference to register.k8s.io switch-over would be mentioned in the release notes of v1.25 next week.

If we can get a +1 from @johnbelamaric @derekwaynecarr and @dims (this time with your SIG Arch hat on) we can move this forward that would be GREAT. Thanks.

**Comment by dims** [comment]
+1 from me with SIG-Arch hat on :)

**Comment by johnbelamaric** [comment]
+1

**Comment by dims** [comment]
thanks @johnbelamaric

**Comment by Riaankl** [comment]
Thank you @johnbelamaric & @dims 

@nikhita & @mrbobbytables we have the blessing of both SIG K8s Infa and SIG Ach to proceed with the migration and renaming of the OCI-Proxy repo.

**Comment by mrbobbytables** [comment]
repo has been migrated, teams will be added in #3695

**Comment by BobyMCbobs** [comment]
> repo has been migrated, teams will be added in #3695

@mrbobbytables, thank you for your help with this!
Will the repo still be renamed to _kubernetes/registry.k8s.io_?

**Comment by mrbobbytables** [comment]
oh derp, sorry - let me take care of that

**Comment by mrbobbytables** [comment]
Okay, all PRs fixed
k/community update here: https://github.com/kubernetes/community/pull/6880

once all PRs are merged I can update the teams and this will be good

**Comment by Riaankl** [comment]
Thanks @mrbobbytables !

**Comment by BobyMCbobs** [comment]
This is wonderful, thank you @mrbobbytables!

**Comment by mrbobbytables** [comment]
teams are added, this should be good to close 👍 

let me know if theres anything else thats needed!

/close
