### ISSUE TITLE
REQUEST: New membership for pbetkier

### ISSUE THREAD

**Issue by pbetkier** [kubernetes/org#3608]
### GitHub Username

@pbetkier

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mwielgus

### Sponsor 2

@gjtempleton

## PRs
* e2e: Fix ResourceConsumer unstable request interval [#108104](https://github.com/kubernetes/kubernetes/pull/108104)
* Add e2e test for HPA behavior: decreased downscale stabilization [#108264](https://github.com/kubernetes/kubernetes/pull/108264)
* Fix comment in HPA's scale event replicaChange [#111463](https://github.com/kubernetes/kubernetes/pull/111463)
* Add sig-autoscaling as owners of test/e2e/framework/autoscaling [#108702](https://github.com/kubernetes/kubernetes/pull/108702)

## Reviews
* Add e2e HPA Behavior tests: scale up/down limited by number of Pods / min, scale up/down limited by percentage / min [#111346](https://github.com/kubernetes/kubernetes/pull/111346#pullrequestreview-1047965863)
* Add e2e HPA Behavior tests: scale down stabilisation, scale up disabled, scale down disabled [#111253](https://github.com/kubernetes/kubernetes/pull/111253#pullrequestreview-1044608850)
* Add e2e test for HPA behavior: scale up delay [#110385](https://github.com/kubernetes/kubernetes/pull/110385#pullrequestreview-1004234675)
* Only log requests for configured consumptions in ResourceConsumer [#109231](https://github.com/kubernetes/kubernetes/pull/109231#pullrequestreview-930229913)
* Add e2e test for HPA behavior: scale up and down disabled [#110386](https://github.com/kubernetes/kubernetes/pull/110386#pullrequestreview-1011824084)

## Issues
* Increase fallback consumption for HPAs with target over 100% [#111433](https://github.com/kubernetes/kubernetes/issues/111433)

**Comment by mwielgus** [comment]
+1

**Comment by gjtempleton** [comment]
+1 from me as well.

Looking forward to your continuing contributions, and thanks for everything so far!

**Comment by savitharaghunathan** [comment]
Hi @pbetkier 👋 Thank you for all your contributions!

I've created PR https://github.com/kubernetes/org/pull/3633 to add you to the k8s organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
