### ISSUE TITLE
REQUEST: New membership for mukhoakash

### ISSUE THREAD

**Issue by mukhoakash** [kubernetes/org#3609]
### GitHub Username

@mukhoakash

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@edreed

### Sponsor 2

@wlan0

### List of contributions to the Kubernetes project

- PRs reviewed/authored
https://github.com/kubernetes-sigs/container-object-storage-interface-controller/pull/58
https://github.com/kubernetes-sigs/container-object-storage-interface-controller/pull/60
https://github.com/kubernetes-sigs/container-object-storage-interface-api/pull/59
https://github.com/kubernetes-sigs/container-object-storage-interface-api/pull/55
https://github.com/kubernetes-sigs/container-object-storage-interface-api/pull/57
https://github.com/kubernetes-sigs/container-object-storage-interface-spec/pull/38
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/pull/64
- Issues responded to
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/issues/62
https://github.com/kubernetes-sigs/container-object-storage-interface-controller/issues/56
https://github.com/kubernetes-sigs/container-object-storage-interface-spec/issues/37
https://github.com/kubernetes-sigs/container-object-storage-interface-api/issues/52
- SIG projects I am involved with
kubernetes-sigs/container-object-storage-interface-controller
kubernetes-sigs/container-object-storage-interface-api
kubernetes-sigs/container-object-storage-interface-spec
kubernetes-sigs/container-object-storage-interface-provisioner-sidecar

**Comment by edreed** [comment]
+1

Thank you for all of your contributions, @mukhoakash!

**Comment by wlan0** [comment]
+1

Great contributions to COSI @mukhoakash
