### ISSUE TITLE
REQUEST: New membership for yanrongshi

### ISSUE THREAD

**Issue by yanrongshi** [kubernetes/org#3610]
### GitHub Username

yanrongshi

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Sea-n 

### Sponsor 2

@windsonsea 

### List of contributions to the Kubernetes project

PRs authored: https://github.com/kubernetes/website/pull/35804, https://github.com/kubernetes/website/pull/35703, https://github.com/kubernetes/website/pull/35674, https://github.com/kubernetes/website/pull/35607, https://github.com/kubernetes/website/pull/35671 ,
https://github.com/kubernetes/website/pull/35606, https://github.com/kubernetes/website/pull/35682
SIG projects I am involved with: [kubernetes/website](https://kubernetes.io/docs/home/)

**Comment by windsonsea** [comment]
+1
@yanrongshi is a contribution enthusiast with high output, more than 100 PRs authored in last 3 months. 👍

**Comment by Sea-n** [comment]
+1
We all looking forward for more contributions from you! 😊
