### ISSUE TITLE
REQUEST: New membership for Volatus

### ISSUE THREAD

**Issue by Volatus** [kubernetes/org#3614]
### GitHub Username

@Volatus

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@strongjz

### Sponsor 2

@rikatz

### List of contributions to the Kubernetes project

`PRs Authored`
- https://github.com/kubernetes/ingress-nginx/pull/8877
- https://github.com/kubernetes/ingress-nginx/pull/8859
- https://github.com/kubernetes/ingress-nginx/pull/8812
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2724
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2714
- https://github.com/kubernetes-sigs/external-dns/pull/2857

`Issues engaged with`
- https://github.com/kubernetes/ingress-nginx/issues/8874
- https://github.com/kubernetes/ingress-nginx/issues/8828
- https://github.com/kubernetes/ingress-nginx/issues/8824
- https://github.com/kubernetes/ingress-nginx/issues/8823
- https://github.com/kubernetes/ingress-nginx/issues/8745
- https://github.com/kubernetes/ingress-nginx/issues/8702
- https://github.com/kubernetes-sigs/external-dns/issues/2780

**Comment by strongjz** [comment]
@Volatus Has been extremely helpful with fixing long-standing issues in the project.  I support his request to be added to the kubernetes org so that he can continue to help with the ingress-nginx project.

**Comment by tao12345666333** [comment]
+1

**Comment by rikatz** [comment]
+1 @Volatus is helping a lot and stepping forward on hard issues. He's gonna be a great addition to the org

**Comment by savitharaghunathan** [comment]
Hi @Volatus 👋 Thank you for all your contributions!

I've created PR https://github.com/kubernetes/org/pull/3633 to add you to the k8s organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
