### ISSUE TITLE
REQUEST: New membership for qbarrand

### ISSUE THREAD

**Issue by qbarrand** [kubernetes/org#3615]
### GitHub Username

@qbarrand

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mrunalp

### Sponsor 2

@endocrimes

### List of contributions to the Kubernetes project

- Core contributor for [Kernel Module Management](https://github.com/kubernetes-sigs/kernel-module-management), which we are moving into SIG Node (from https://github.com/qbarrand/oot-operator)
- Regular participant in SIG Node weekly meetings

**Comment by endocrimes** [comment]
+1, welcome to the team ✨

**Comment by mrunalp** [comment]
+1

**Comment by palnabarun** [comment]
@qbarrand -- Thank you for all your contributions so far!

I have raised #3620 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign

**Comment by qbarrand** [comment]
Thank you all!
