### ISSUE TITLE
REQUEST: New membership for wangchen615

### ISSUE THREAD

**Issue by wangchen615** [kubernetes/org#3616]
### GitHub Username

wangchen615

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

mrunalp

### Sponsor 2

Huang-Wei

### List of contributions to the Kubernetes project

- PRs reviewed/authored
  - https://github.com/kubernetes/autoscaler/pull/4131
  - https://github.com/kubernetes/autoscaler/pull/3914
  - https://github.com/kubernetes/kubernetes/pull/102884
  - https://github.com/kubernetes-sigs/scheduler-plugins/pull/341
  - https://github.com/kubernetes-sigs/scheduler-plugins/pull/152
- Issues responded to
  - https://github.com/kubernetes-sigs/scheduler-plugins/issues/271
  - https://github.com/kubernetes-sigs/scheduler-plugins/issues/144
  - https://github.com/kubernetes/autoscaler/issues/5046
  - https://github.com/kubernetes/autoscaler/issues/3913
- SIG projects I am involved with
  - https://github.com/kubernetes/autoscaler
  - https://github.com/kubernetes-sigs/scheduler-plugins

**Comment by Huang-Wei** [comment]
+1

**Comment by mrunalp** [comment]
:+1:
