### ISSUE TITLE
REQUEST: New membership for Rishit-dagli

### ISSUE THREAD

**Issue by Rishit-dagli** [kubernetes/org#3617]
### GitHub Username

Rishit-dagli

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jihoon-seo

### Sponsor 2

@mehabhalodiya

### Sponsor 3

@tengqm

#### Reviews or Comments which might have been helpful

* [https://github.com/kubernetes/website/pull/35079#discussion_r924053467](https://github.com/kubernetes/website/pull/35079#discussion_r924053467)
* [https://github.com/kubernetes/website/pull/34465#discussion_r906688935](https://github.com/kubernetes/website/pull/34465#discussion_r906688935)
* [https://github.com/kubernetes/website/issues/34428#issuecomment-1163003762](https://github.com/kubernetes/website/issues/34428#issuecomment-1163003762)
* [https://kubernetes.slack.com/archives/CJDHVD54J/p1655982379049779?thread_ts=1655412831.893609&cid=CJDHVD54J](https://kubernetes.slack.com/archives/CJDHVD54J/p1655982379049779?thread_ts=1655412831.893609&cid=CJDHVD54J)

#### PRs

* [https://github.com/kubernetes-client/python/pull/1860](https://github.com/kubernetes-client/python/pull/1860)
* [https://github.com/kubernetes-client/python/pull/1812](https://github.com/kubernetes-client/python/pull/1812)
* [https://github.com/kubernetes-client/python/pull/1829](https://github.com/kubernetes-client/python/pull/1829)
* [https://github.com/kubernetes/website/pull/35763](https://github.com/kubernetes/website/pull/35763)
* [https://github.com/kubernetes/website/pull/35745](https://github.com/kubernetes/website/pull/35745)
* [https://github.com/kubernetes/website/pull/35391](https://github.com/kubernetes/website/pull/35391)
* [https://github.com/kubernetes/website/pull/35298](https://github.com/kubernetes/website/pull/35298)
* [https://github.com/kubernetes/website/pull/34425](https://github.com/kubernetes/website/pull/34425)
* [https://github.com/kubernetes/website/pull/34399](https://github.com/kubernetes/website/pull/34399)
* [https://github.com/kubernetes/website/pull/34260](https://github.com/kubernetes/website/pull/34260)
* [https://github.com/kubernetes/website/pull/35119](https://github.com/kubernetes/website/pull/35119)
* [https://github.com/kubernetes/website/pull/34499](https://github.com/kubernetes/website/pull/34499)
* [https://github.com/kubernetes/website/pull/34439](https://github.com/kubernetes/website/pull/34439)
* [https://github.com/kubernetes/website/pull/34397](https://github.com/kubernetes/website/pull/34397)
* [https://github.com/kubernetes/website/pull/34387](https://github.com/kubernetes/website/pull/34387)
* [https://github.com/kubernetes/website/pull/34386](https://github.com/kubernetes/website/pull/34386)
* [https://github.com/kubernetes/website/pull/34262](https://github.com/kubernetes/website/pull/34262)
* [https://github.com/kubernetes/website/pull/34081](https://github.com/kubernetes/website/pull/34081)
* [https://github.com/kubernetes/community/pull/6679](https://github.com/kubernetes/community/pull/6679)

#### Issues

* [https://github.com/kubernetes/website/issues/35332](https://github.com/kubernetes/website/issues/35332)
* [https://github.com/kubernetes/website/issues/34355](https://github.com/kubernetes/website/issues/34355)

**Comment by mehabhalodiya** [comment]
+1

Thanks for stepping forward as a potential Kubernetes project member.
Happy to see your contributions so far; looking forward to more of them 🎉

**Comment by jihoon-seo** [comment]
+1
@Rishit-dagli is a promising contributor, and I am happy to be a sponsor for his membership!

**Comment by palnabarun** [comment]
@Rishit-dagli -- Thank you for all your contributions so far!

I have raised #3620 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
