### ISSUE TITLE
REQUEST: New membership for hlipsig

### ISSUE THREAD

**Issue by hlipsig** [kubernetes/org#3619]
### GitHub Username

hlipsig

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

jeremyrickard

### Sponsor 2

palnabarun

### List of contributions to the Kubernetes project

Code of Conduct Committee

**Comment by palnabarun** [comment]
+1, Welcome to the Code of Conduct Committee!

**Comment by jeremyrickard** [comment]
+1 

/lgtm

**Comment by palnabarun** [comment]
@hlipsig -- Thank you for all your contributions so far!

I have raised https://github.com/kubernetes/org/pull/3620 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
