### ISSUE TITLE
REQUEST: New membership for tariq1890

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/org#362]
### GitHub Username
@tariq1890

### Organization you are requesting membership in
kubernetes, kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @feiskyer
- @khenidak  

### List of contributions to the Kubernetes project
 https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/52
 https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/42
 https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/44
 https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/33
 https://github.com/kubernetes/autoscaler/pull/1583
 https://github.com/kubernetes-sigs/cluster-api/pull/668
 https://github.com/kubernetes/kube-state-metrics/pull/626
 https://github.com/kubernetes/autoscaler/pull/1582
 https://github.com/kubernetes/ingress-nginx/pull/3356

### SIG projects I am involved with
https://github.com/kubernetes-sigs/cluster-api-provider-azure
https://github.com/kubernetes-sigs/cluster-api

**Comment by justaugustus** [comment]
+1 from me! 
Tariq has done major work on the cluster-api-provider-azure project and I'd like to get him in the org to officially start reviewing/approving PRs :)

**Comment by mrbobbytables** [comment]
@tariq1890, thank you for all the work you've put into the azure cluster-api provider! :)

I've created PR #365  to add you to both the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notifications for both.

Welcome aboard! 🎉

/assign
