### ISSUE TITLE
REQUEST: New membership for negz

### ISSUE THREAD

**Issue by negz** [kubernetes/org#3623]
### GitHub Username

@negz

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@apelisse

### Sponsor 2

@sttts

### List of contributions to the Kubernetes project

Full set: https://github.com/search?l=&p=3&q=org%3Akubernetes+author%3Anegz&type=Issues

Some more interesting ones:

* https://github.com/kubernetes/autoscaler/pull/462
* https://github.com/kubernetes/kubernetes/pull/110820
* https://github.com/kubernetes/kubernetes/pull/111559
* https://github.com/kubernetes/kubernetes/issues/111880

**Comment by sttts** [comment]
+1 for @negz's membership

**Comment by apelisse** [comment]
+1 for me too!

**Comment by aojea** [comment]
+1

**Comment by savitharaghunathan** [comment]
Hi @negz 👋 Thank you for all your contributions!

I've created PR https://github.com/kubernetes/org/pull/3633 to add you to the k8s organization. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
