### ISSUE TITLE
REQUEST: New membership for qbarrand

### ISSUE THREAD

**Issue by qbarrand** [kubernetes/org#3624]
### GitHub Username

@qbarrand

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mrunalp

### Sponsor 2

@endocrimes

### List of contributions to the Kubernetes project

Follow-up PR to https://github.com/kubernetes/org/issues/3615. I did not realize that I need to be member of `kubernetes` as well [to be an approver in `test-infra`](https://github.com/kubernetes/test-infra/pull/27171#issuecomment-1218551184).
Apologies to everyone for the duplicate PR.

**Comment by endocrimes** [comment]
No worries - my +1 stands (although not technically needed - membership in one qualifies you for the other)

**Comment by palnabarun** [comment]
@qbarrand being part of one of the orgs, you are implicitly approved to be part of all the Kubernetes orgs. 

Please feel free to PR yourself in to @kubernetes! 😀

**Comment by qbarrand** [comment]
Thank you both! I have created https://github.com/kubernetes/org/pull/3625 to add myself to the org directly.
Closing this issue.
