### ISSUE TITLE
Request for new repo: kubernetes/kms

### ISSUE THREAD

**Issue by aramase** [kubernetes/org#3630]
### New repo, staging repo, or migrate existing

new staging

### Is it a staging repo?

yes

### Requested name for new repository

kms

### Which Organization should it reside

kubernetes

### What should the repo description be?

Kubernetes KMS implementation - https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/3299-kms-v2-improvements/README.md

(KEP link will be replaced with a documentation link once the docs exist)

### What SIG and subproject does this fall under?

sig-auth

### Please provide references to appropriate approval for this new repo

Pending approval: https://groups.google.com/g/kubernetes-sig-architecture/c/PkiMsg47TJY/m/ziMP7M0IAwAJ

**Comment by dims** [comment]
+1 from sig-arch hat on. You really need the lgtm(s) from sig-auth folks.

**Comment by ritazh** [comment]
+1 from sig-auth

**Comment by enj** [comment]
+1

**Comment by deads2k** [comment]
+1

**Comment by aramase** [comment]
@dims we have the approvals from sig-auth and I've a [PR](https://github.com/kubernetes/kubernetes/pull/111980) to set up the staging directory. Would you be able to help create the repo? Let me know if I can do anything to help.

**Comment by dims** [comment]
@aramase this is looked after by the github admin team. please give them time.

**Comment by mikedanese** [comment]
+1

**Comment by ameukam** [comment]
Can you complete the issue description ?

```
Who should have admin access?

No response
Who should have write access?

No response
Who should be listed as approvers in OWNERS?

No response
Who should be listed in SECURITY_CONTACTS?

No response
```

**Comment by enj** [comment]
@ameukam those should all be set to just me (@enj).

**Comment by aramase** [comment]
@nikhita @mrbobbytables we have approval from `sig-auth`. Would you be able to set up the staging repo?

**Comment by aramase** [comment]
@ameukam @cblecker we have approval from `sig-auth`. Would you be able to set up the staging repo?

**Comment by aramase** [comment]
pinged on slack https://kubernetes.slack.com/archives/C01672LSZL0/p1662567549252629. @ameukam is going to help with creating the repo soon.

**Comment by ameukam** [comment]
Repo is created: https://github.com/kubernetes/kms.git

I opened:
  - https://github.com/kubernetes/publishing-bot/pull/299 to add the repo to the publishing-bot fetch script
  - https://github.com/kubernetes/test-infra/pull/27579 to setup branch protection rules
  - https://github.com/kubernetes/community/pull/6885 to add the repo to `sigs.yaml` file

**Comment by ameukam** [comment]
> Thank you @ameukam!
> 
> i'll add the publishing rules as part of [kubernetes/kubernetes#111980](https://github.com/kubernetes/kubernetes/pull/111980)

@aramase I see your PR needs a rebase. Do you mind rebase it and get it merged before I merge the branch protection rules ?

**Comment by aramase** [comment]
As per https://github.com/kubernetes/kubernetes/pull/111980#issuecomment-1255832323

/assign @nikhita

**Comment by aramase** [comment]
@nikhita FYI, the PR to setup the staging dir and publishing rules has been merged in `k/k` with reference to `master` branch.

**Comment by nikhita** [comment]
I've fixed the repo to contain the correct commits. I'll close this issue once we have a successful publishing-bot run.

**Comment by nikhita** [comment]
> I'll close this issue once we have a successful publishing-bot run.

This is done - https://github.com/kubernetes/kms. Closing!

**Comment by aramase** [comment]
Thank you @nikhita and @ameukam!
