### ISSUE TITLE
REQUEST: New membership for yevgeny-shnaidman

### ISSUE THREAD

**Issue by yevgeny-shnaidman** [kubernetes/org#3634]
### GitHub Username

@yevgeny-shnaidman

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@qbarrand

### Sponsor 2

@endocrimes

### List of contributions to the Kubernetes project

Core contributor to KMM. Examples of significant PRs:

- https://github.com/qbarrand/oot-operator/pull/102
- https://github.com/qbarrand/oot-operator/pull/82
- https://github.com/qbarrand/oot-operator/pull/70
- https://github.com/qbarrand/oot-operator/pull/80

**Comment by qbarrand** [comment]
+1. Yevgeny is a core developer for KMM and a participant to the upstream community. His membership will allow us to move the development to the [sig-node repository](https://github.com/kubernetes-sigs/kernel-module-management).

**Comment by endocrimes** [comment]
+1, welcome to Kubernetes ✨

**Comment by yevgeny-shnaidman** [comment]
> +1, welcome to Kubernetes sparkles

Thank you!

**Comment by chris-short** [comment]
Hi **@yevgeny-shnaidman**, Thank you for all your contributions!

I've created PR [#](https://github.com/kubernetes/org/pull/3633)3639 to add you to the k8s & k8s-sigs organizations. Once that gets merged, you should get a membership invite notification.

Welcome to [**@kubernetes**](https://github.com/kubernetes)! :tada:
