### ISSUE TITLE
REQUEST: New membership for wespanther

### ISSUE THREAD

**Issue by wespanther** [kubernetes/org#3637]
### GitHub Username

@wespanther

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@puerco

### Sponsor 2

@justaugustus

### List of contributions to the Kubernetes project

- Some PRs I've worked on:
  - Bunch of base image updates, e.g. https://github.com/kubernetes/release/pulls?q=is%3Apr+is%3Aclosed+author%3Awespanther
  - Promotions - https://github.com/kubernetes/k8s.io/pulls?q=is%3Apr+is%3Aclosed+author%3Awespanther+
  - Debian iptables fix - https://github.com/kubernetes/release/pull/1613
  - kpromo support for non-SemVer image tags - https://github.com/kubernetes-sigs/promo-tools/pull/527
- SIGs I'm involved with:
  - Mostly sig-release (for image patching), also sig-security-tooling to a lesser extent

**Comment by justaugustus** [comment]
+1 to @wespanther's membership.
Wes has been assisting in SIG Release for quite some time!

/pony

**Comment by puerco** [comment]
+1 To @wespanther joining the org, he's been taking care of some tasks in SIG Release 

/meow

**Comment by chris-short** [comment]
Hi @wespanther,

I've opened a PR to add you to the kubernetes org (#3638). A membership invite will be sent out once the PR has merged.

Welcome!

**Comment by palnabarun** [comment]
Should be fixed by #3638.

/close
