### ISSUE TITLE
REQUEST: New membership for mxinden

### ISSUE THREAD

**Issue by mxinden** [kubernetes/org#364]
### GitHub Username
@mxinden

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @brancz 
- @andyxning 

### List of contributions to the Kubernetes project
- kube-state-metrics performance optimization:
  - [Initial issue](https://github.com/kubernetes/kube-state-metrics/issues/498)
  - [Design doc](https://docs.google.com/document/d/1Z1q84680vG56SKDi1AMu0x3lFe4bi40DcpMCQDylyMg/edit?usp=sharing)
  - [Main PR](https://github.com/kubernetes/kube-state-metrics/pull/534)
  - [Feedback by the community](https://github.com/kubernetes/kube-state-metrics/issues/498#issuecomment-431882415)
- Various smaller [fixes](https://github.com/kubernetes/kube-state-metrics/pulls?page=1&q=is%3Apr+is%3Aclosed+author%3Amxinden)
- SIG projects I am involved with
  - [sig-instrumentation](https://groups.google.com/forum/#!forum/kubernetes-sig-instrumentation)

**Comment by brancz** [comment]
I think it's fair to explicitly mention the **_26_** pull requests @mxinden has created within the v1.5.0 release of kube-state-metrics! (above only humbly mentioned as "Various smaller fixes") https://github.com/kubernetes/kube-state-metrics/pulls?page=1&q=is%3Apr+is%3Aclosed+author%3Amxinden

Without a doubt huge :+1: from me! We're lucky to have you!

**Comment by andyxning** [comment]
Big thanks for @mxinden to enhance the scrape metrics performance of kube-state-metrics! This enhance version has been available with the v1.5.0 release just like what @brancz said above. 

Just congrats to @mxinden to be a Kubernetes member!

**Comment by ant31** [comment]
+1

**Comment by mrbobbytables** [comment]
Thank you for everything @mxinden! :)

I've created PR #365   to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
