### ISSUE TITLE
Make public "SIG Docs Spanish k/website Board" at GitHub

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/org#3645]
### Organization or Repo

kubernetes/projects

### Describe the issue

As Kubernetes Spanish Translation Group, we created this Github project to track the missing docs to be translated by using cards/issues at the board: https://github.com/orgs/kubernetes/projects/97/views/1

This project is private and we would like to have it public.

Thanks.

**Comment by mrbobbytables** [comment]
The settings shouldn't be restricted, you can flip it public through the settings: https://github.com/orgs/kubernetes/projects/97/settings

**Comment by ramrodo** [comment]
@mrbobbytables It seems I don't have that setting enabled/authorized:

![image](https://user-images.githubusercontent.com/2797052/187728407-a96af553-a5d1-4d47-8e6a-2dcd3627826f.png)

**Comment by ameukam** [comment]
Visibility updated to `public`.

@ramrodo please close this issue if addressed.

**Comment by ramrodo** [comment]
Thanks, @ameukam. It is public now. Closing this issue.
