### ISSUE TITLE
REQUEST: New membership for ybettan

### ISSUE THREAD

**Issue by ybettan** [kubernetes/org#3647]
### GitHub Username

ybettan@redhat.com

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@qbarrand

### Sponsor 2

@dchen1107

### List of contributions to the Kubernetes project

- kubernetes-sigs: https://github.com/kubernetes-sigs/kernel-module-management/commits/main?author=ybettan
- kubernetes: https://github.com/kubernetes/test-infra/commits/master?author=ybettan

**Comment by qbarrand** [comment]
+1. Yoni is a core KMM contributor and a participant in the community.

**Comment by dchen1107** [comment]
+1 

Yoni, thanks for the contribution to KMM and K8s community. 

/lgtm
/approve

**Comment by ybettan** [comment]
Thank you so much @dchen1107 and @qbarrand .

I hope this is the PR you meant :)

**Comment by palnabarun** [comment]
@ybettan -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign

**Comment by palnabarun** [comment]
@ybettan -- The GitHub membership PR is done by one of the New Membership Coordinators. The requests are periodically processed in a batch.

**Comment by ybettan** [comment]
Thank you @palnabarun :)
