### ISSUE TITLE
REQUEST: New membership for oscr

### ISSUE THREAD

**Issue by oscr** [kubernetes/org#3648]
### GitHub Username

@oscr

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@killianmuldoon

### Sponsor 2

@enxebre

### List of contributions to the Kubernetes project

I would like to add `kubernetes` membership in addition to my `kubernetes-sig` since some CI/CD parts for cluster-api are in the `kubernetes` org. For example for this pr I'm working on now: https://github.com/kubernetes/test-infra/pull/27311

Previous membership pr #3539

**Comment by killianmuldoon** [comment]
+1 @oscr has been an amazing contributor to Cluster API in recent months

**Comment by oscr** [comment]
Thank you @killianmuldoon. I really appreciate the kind words :pray:

**Comment by palnabarun** [comment]
@oscr -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign

**Comment by palnabarun** [comment]
@oscr -- bdw, since you were already a member of @kubernetes-sigs, you didn't need to file a new org membership request. Membership in one org implicitly grants membership to other orgs. In those scenarios, you can just raise a PR adding yourself to the requested orgs.

**Comment by oscr** [comment]
@palnabarun Thank you for your help and for the information.
