### ISSUE TITLE
REQUEST: New membership for sanwishe

### ISSUE THREAD

**Issue by sanwishe** [kubernetes/org#3655]
### GitHub Username

@sanwishe

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@liggitt

### Sponsor 2

@serathius

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/pulls?q=is%3Apr+author%3Asanwishe+archived%3Afalse+
- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+commenter%3Asanwishe
- SIG projects I am involved with
kubernetes/kubernetes
kubernetes/perf-tests
kubernetes-sigs/metrics-server
kubernetes-sigs/custom-metrics-apiserver

**Comment by sanwishe** [comment]
@liggitt @serathius thanks~

**Comment by serathius** [comment]
/lgtm
Thanks for great work, and welcome to K8s org!

**Comment by liggitt** [comment]
+1

**Comment by mrbobbytables** [comment]
@sanwishe do you have another sponsor by chance? Sponsors must be from different member companies, and both @liggitt and @serathius are from Google =/

**Comment by sanwishe** [comment]
> @sanwishe do you have another sponsor by chance? Sponsors must be from different member companies, and both @liggitt and @serathius are from Google =/

Sorry for not notice they are both from Google. And @aojea has promised to sponsor me.

**Comment by aojea** [comment]
+1

**Comment by palnabarun** [comment]
@sanwishe  -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign

**Comment by sanwishe** [comment]
Thanks all~~~
