### ISSUE TITLE
REQUEST: Migrate puerco/tejolote

### ISSUE THREAD

**Issue by puerco** [kubernetes/org#3656]
### New repo, staging repo, or migrate existing

migrate existing

### Is it a staging repo?

no

### Requested name for new repository

tejolote

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

cpanato jeremyrickard justaugustus puerco saschagrunert

### Who should have write access?

cpanato jeremyrickard justaugustus puerco saschagrunert

### Who should be listed as approvers in OWNERS?

cpanato jeremyrickard justaugustus puerco saschagrunert

### Who should be listed in SECURITY_CONTACTS?

cpanato jeremyrickard justaugustus puerco saschagrunert

### What should the repo description be?

A highly configurable build executor and observer designed to generate signed SLSA provenance attestations describing builds system runs.

### What SIG and subproject does this fall under?

SIG Release / Release Engineering

## Process Design

Overall design documented in https://github.com/kubernetes/release/issues/2611

## Discussions in Meetings:

Relevant dates from the [SIG Release meeting notes](https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA):

- Plan and design were discussed on July 26
- Project implementation was discussed on Aug 16, Sep 6, possibly others. 

### Additional context for request

Tagging SIG Release leads and Release Managers for visibility
/cc @cpanato @jeremyrickard @justaugustus @puerco @saschagrunert @kubernetes/release-managers

**Comment by cpanato** [comment]
+1

**Comment by jeremyrickard** [comment]
+1

**Comment by saschagrunert** [comment]
+1

**Comment by xmudrii** [comment]
+1 :100:

**Comment by ameukam** [comment]
@puerco Sent you an invite to the https://github.com/orgs/kubernetes-purgatory as member. 

Can you transfer the repo to this org ?

**Comment by puerco** [comment]
Farewell my dear baby :wave: 
It's done @ameukam !

**Comment by ameukam** [comment]
Repo migrated: https://github.com/kubernetes-sigs/tejolote

I opened:
 - https://github.com/kubernetes/org/pull/3780
 - https://github.com/kubernetes/community/pull/6938
 
 The issue can be closed when both PR are merged.

**Comment by puerco** [comment]
Thanks @ameukam !!

Migration is complete.
/close
