### ISSUE TITLE
REQUEST: Migrate huaweicloud-csi-driver to kubernetes-csi

### ISSUE THREAD

**Issue by niuzhenguo** [kubernetes/org#3657]
### New repo, staging repo, or migrate existing

https://github.com/huaweicloud/huaweicloud-csi-driver

### Is it a staging repo?

no

### Requested name for new repository

huaweicloud-csi-driver

### Which Organization should it reside

kubernetes-csi

### Who should have admin access?

@niuzhenguo

### Who should have write access?

@niuzhenguo, @chengxiangdong

### Who should be listed as approvers in OWNERS?

@niuzhenguo, @chengxiangdong

### Who should be listed in SECURITY_CONTACTS?

@niuzhenguo, @chengxiangdong

### What should the repo description be?

Huawei Cloud Container Storage Interface(CSI) Driver

### What SIG and subproject does this fall under?

sig-cloud-provider

### Please provide references to appropriate approval for this new repo

@xing-yang

**Comment by mrbobbytables** [comment]
/assign @andrewsykim @cheftako @nckturner 
for approval

**Comment by niuzhenguo** [comment]
@andrewsykim @cheftako @nckturner please have a look at this, thanks!
