### ISSUE TITLE
REQUEST: New membership for ErikJiang

### ISSUE THREAD

**Issue by ErikJiang** [kubernetes/org#3659]
### GitHub Username

ErikJiang

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@floryut

### Sponsor 2

@cristicalin

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pull/9253
https://github.com/kubernetes-sigs/kubespray/pull/9241
https://github.com/kubernetes-sigs/kubespray/pull/9164
https://github.com/kubernetes-sigs/kubespray/pull/9144
https://github.com/kubernetes-sigs/kubespray/pull/9121
https://github.com/kubernetes-sigs/kubespray/pull/9090
https://github.com/kubernetes-sigs/kubespray/pull/9087
https://github.com/kubernetes-sigs/kubespray/pull/9079
https://github.com/kubernetes-sigs/kubespray/pull/9078
https://github.com/kubernetes-sigs/kubespray/pull/8956
https://github.com/kubernetes-sigs/kubespray/pull/8943
https://github.com/kubernetes-sigs/kubespray/pull/8938
https://github.com/kubernetes-sigs/kubespray/pull/8934
https://github.com/kubernetes-sigs/kubespray/pull/8875
https://github.com/kubernetes-sigs/kubespray/pull/8764

- Issues responded to
https://github.com/kubernetes-sigs/kubespray/issues/9070

- SIG projects I am involved with
[kubernetes-sigs/kubespray](https://github.com/kubernetes-sigs/kubespray)

**Comment by cyclinder** [comment]
+1 for me, Thank you for the job! 👍

**Comment by calvin0327** [comment]
+1 Count me in!

**Comment by cristicalin** [comment]
Great contributions @ErikJiang 

+1 👍

**Comment by floryut** [comment]
+1

Thanks you for your contribs @ErikJiang ! looking forward for the next ones.

**Comment by palnabarun** [comment]
@ErikJiang -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
