### ISSUE TITLE
REQUEST: New membership for @eduartua

### ISSUE THREAD

**Issue by eduartua** [kubernetes/org#366]
### GitHub Username
@eduartua

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman 
- @guineveresaenger 
- @nikhita 

### List of contributions to the Kubernetes project
- PRs reviewed / authored 
  [2860](https://github.com/kubernetes/community/pull/2860)
  [3086](https://github.com/kubernetes/community/pull/3086)
  [2716](https://github.com/kubernetes/community/issues/2716)
  [3099](https://github.com/kubernetes/community/pull/3099)
- Issues responded to
  [3064](https://github.com/kubernetes/community/issues/3064)
  [3097](https://github.com/kubernetes/community/issues/3097)
- SIG projects I am involved with
  SIG [contributor-experience](https://github.com/kubernetes/community/tree/master/sig-contributor-experience)
  Project: [developer guide](https://github.com/kubernetes/community/tree/master/contributors/devel)

**Comment by parispittman** [comment]
+100 - thank you!!

**Comment by nikhita** [comment]
Late to the party, but +10000000 :))
