### ISSUE TITLE
REQUEST: New membership for tssurya

### ISSUE THREAD

**Issue by tssurya** [kubernetes/org#3661]
### GitHub Username

@tssurya

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@astoycos, @danwinship

### Sponsor 2

@robscott

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/kubernetes/pull/95252
- https://github.com/kubernetes/kubernetes/pull/95400
- https://github.com/kubernetes/kubernetes/pull/96959

**Comment by astoycos** [comment]
+1 

Surya has contributed to K8s in sig-network and is going to be getting involved more with https://github.com/kubernetes-sigs/network-policy-api :)

**Comment by tssurya** [comment]
Both sponsors are from same company as myself, should I ask for someone from outside as well (not entirely sure of the definition of "different member companies")?

**Comment by danwinship** [comment]
Yeah, you need to show you're not just a Red Hat shill. :slightly_smiling_face:

**Comment by palnabarun** [comment]
@tssurya -- you need sponsor working at two different companies.

**Comment by robscott** [comment]
+1

Thanks for all the contributions @tssurya!

**Comment by tssurya** [comment]
thanks @robscott !

@palnabarun : does that satisfy the requirements?

**Comment by palnabarun** [comment]
@tssurya  -- Yes, it does! Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
