### ISSUE TITLE
REQUEST: New membership for furkatgofurov7

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes/org#3663]
### GitHub Username

@furkatgofurov7

### Organization you are requesting membership in

kubernetes-sigs, kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@enxebre

### List of contributions to the Kubernetes project

- PRs:
	- Closed:
		- [CAPI](https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+is%3Aclosed+author%3Afurkatgofurov7)
		- [CAPZ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+author%3Afurkatgofurov7+is%3Aclosed) 
		- [test-infra](https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Afurkatgofurov7+is%3Aclosed)
	- Open: [CAPI](https://github.com/kubernetes-sigs/cluster-api/pulls/furkatgofurov7)
- Issues responded:
	- Closed: [CAPI](https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+author%3Afurkatgofurov7+is%3Aclosed) 
	- Open: [CAPI](https://github.com/kubernetes-sigs/cluster-api/issues/created_by/furkatgofurov7) 
- SIG projects I am involved with: 
	- Cluster API (https://github.com/kubernetes-sigs/cluster-api)
	- Cluster API Provider Azure (https://github.com/kubernetes-sigs/cluster-api-provider-azure)

**Comment by sbueringer** [comment]
+1

Thank you very much for all you work on Cluster API & Welcome :tada: :)

**Comment by enxebre** [comment]
+1, welcome @furkatgofurov7! Thanks for your contributions and your willingness to always discuss things thoroughly

**Comment by palnabarun** [comment]
@furkatgofurov7  -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
