### ISSUE TITLE
REQUEST: New membership for aryan9600

### ISSUE THREAD

**Issue by aryan9600** [kubernetes/org#3664]
### GitHub Username

@aryan9600

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@robscott

### Sponsor 2

@shaneutt

### List of contributions to the Kubernetes project

- PRs reviewed/authored:
https://github.com/kubernetes/kubernetes/pull/112260
https://github.com/kubernetes/kubernetes/pull/111635
https://github.com/kubernetes/kubernetes/pull/110484
https://github.com/kubernetes/kubernetes/pull/110483
https://github.com/kubernetes/kubernetes/pull/110482
https://github.com/kubernetes/kubernetes/pull/109875
https://github.com/kubernetes/kubernetes/pull/109624
https://github.com/kubernetes/kubernetes/pull/109514
https://github.com/kubernetes-sigs/gateway-api/pull/1099
https://github.com/kubernetes-sigs/gateway-api/pull/1326
https://github.com/kubernetes-sigs/gateway-api/pull/1373
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/109554
https://github.com/kubernetes/kubernetes/issues/108319
https://github.com/kubernetes/kubernetes/issues/107534
https://github.com/kubernetes/kubernetes/issues/108779
- SIG projects I am involved with
sig-network
Gateway API

**Comment by robscott** [comment]
Thanks for all the contributions @aryan9600!

+1

**Comment by shaneutt** [comment]
Yep, thanks @aryan9600

+1

**Comment by palnabarun** [comment]
@aryan9600 -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
