### ISSUE TITLE
REQUEST: Netlify site for node-feature-discovery

### ISSUE THREAD

**Issue by fmuyassarov** [kubernetes/org#3665]
### Repository

kubernetes-sigs/node-feature-discovery

### Project domain

nfd.sigs.k8s.io

**Comment by mrbobbytables** [comment]
I can get it going, but you'll want to stub out a netlify.toml file and open a PR to k/k8s.io to add the dns entry. If I enable netlify before its ready to be configured in repo it'll report as a failing test on all PRs.

**Comment by fmuyassarov** [comment]
good point, thanks @mrbobbytables . I will come back once we are done with your suggestions.
/hold

**Comment by fmuyassarov** [comment]
Hi @mrbobbytables . We have added the netlify.toml to the repo and we actually don't need a DNS entry because we are not planning to use Netlify to host our docs, but use it as for the preview tool for now. As such, we only need to add a new site based on the github repo, which I can do myself already because I'm already a member of "CNCF projects" team on Netlify. So, there is no more actions required to be done from your side. Thank you.

**Comment by fmuyassarov** [comment]
Actually I just realized that I don't have enough permissions to configure the Netlify on node-feature-discovery repository. @mrbobbytables Can your perhaps help here to add a new site for us? We only need it for master branch for now.

![Screenshot from 2022-09-27 11-12-38](https://user-images.githubusercontent.com/35802557/192471387-1cebc268-014a-4822-850e-ebead7feafef.png)

**Comment by fmuyassarov** [comment]
@mrbobbytables Would you recommend to obtain admins rights on the repo or can we ask someone with admin rights to help us here ?

**Comment by mrbobbytables** [comment]
One of us as github admins sets it up 👍 
I was traveling last week, will enable it now.

**Comment by mrbobbytables** [comment]
Cool - do you want to leave this open till the name is sorted out? or close and follow up later?

**Comment by fmuyassarov** [comment]
Let's close it for now since our original request is completed.  
Thanks again.
/close

**Comment by marquiz** [comment]
Wow, really cool 😎 Thanks again @fmuyassarov and @mrbobbytables for working on this1
