### ISSUE TITLE
REQUEST: New membership for rolfedh

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/org#3666]
### GitHub Username

@rolfedh

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@reylejano

### Sponsor 2

@nate-double-u 

### List of contributions to the Kubernetes project

# PRs I've contributed:
- https://github.com/kubernetes/website/pull/36639
- https://github.com/kubernetes/website/pull/36375
- https://github.com/kubernetes/website/pull/35942
- https://github.com/kubernetes/website/pull/36204
- https://github.com/kubernetes/website/pull/36364
- https://github.com/kubernetes/website/pull/35930
- https://github.com/kubernetes/website/pull/33287
- https://github.com/kubernetes/website/pull/31528
- https://github.com/kubernetes/website/pull/27971

# Issues I've contributed
- [List of issues](https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Arolfedh+)

# SIG Projects I'm involved in: 
- SIG Docs Localization shadow co-chair.

**Comment by reylejano** [comment]
+1 from me, Rolfe continues to contribute to SIG Docs, was part of the effort to remove dockershim from the documentation for the 1.24 release and helped the hindi localization go live

**Comment by nate-double-u** [comment]
+1, Rolfe has been an enthusiastic contributor on the SIG Docs team for a long time and has been involved in multiple parts of the documentation. He's an asset to the team, and I'm happy to sponsor his membership in the org.

**Comment by palnabarun** [comment]
@rolfedh -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign

**Comment by rolfedh** [comment]
Thank you, @reylejano @nate-double-u  and @palnabarun!
