### ISSUE TITLE
REQUEST: New membership for raesene

### ISSUE THREAD

**Issue by raesene** [kubernetes/org#3667]
### GitHub Username

@raesene

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

tabbysable

### Sponsor 2

PushkarJ

### List of contributions to the Kubernetes project

- Docs API Server Bypass risks page - https://github.com/kubernetes/website/pull/35908
- Docs RBAC Good Practice Guide - https://github.com/kubernetes/website/pull/32812
- Website blog on securing admission controllers -https://github.com/kubernetes/website/pull/31221
- SIG-Security - Admission controller threat model - https://github.com/kubernetes/sig-security/pull/27

**Comment by puerco** [comment]
+1

**Comment by PushkarJ** [comment]
@raesene is a thought leader and an amazing example of how to be inclusive, share knowledge in public and improve the project through community collaboration. This is one of those cases where Kubernetes Org is lucky that Rory would like to be its member :)

**Comment by palnabarun** [comment]
@raesene -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
