### ISSUE TITLE
REQUEST: New membership for rollony

### ISSUE THREAD

**Issue by rollony** [kubernetes/org#3670]
### GitHub Username

@rollony

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jihoon-seo

### Sponsor 2

@yoonian 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  https://github.com/kubernetes/website/pulls?q=author%3Arollony+
  https://github.com/kubernetes/dashboard/pulls?q=author%3Arollony+

- Issues responded to
  https://github.com/kubernetes/website/issues?q=author%3Arollony+
  https://github.com/kubernetes/dashboard/issues?q=author%3Arollony+

- SIG projects I am involved with
kubernetes/website, kubernetes/dashboard

**Comment by seokho-son** [comment]
+1 
@rollony is active contributor !

**Comment by jihoon-seo** [comment]
+1, I am happy to be a sponsor of @rollony requesting to be a K8s org member!

**Comment by palnabarun** [comment]
@rollony -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
