### ISSUE TITLE
REQUEST: New membership for daschott

### ISSUE THREAD

**Issue by daschott** [kubernetes/org#3671]
### GitHub Username

daschott

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jayunit100

### Sponsor 2

@jsturtevant

### List of contributions to the Kubernetes project

I am involved with the sig-windows group. 
I have been contributing to Kubernetes and responding to issues since 2018. Examples of some issues I responded to and/or help document are:
- https://github.com/kubernetes/kubernetes/issues/68511
- https://github.com/kubernetes/kubernetes/issues/98680
- https://github.com/kubernetes/kubernetes/issues/93304
- https://github.com/kubernetes/kubernetes/issues/80288
- https://github.com/kubernetes/kubernetes/issues/66947

I have also raised a few PRs such as:
- https://github.com/kubernetes/kubernetes/pull/110701
- https://github.com/kubernetes/kubernetes/pull/109124

which helped resolve issues
- https://github.com/kubernetes/kubernetes/issues/110591
- https://github.com/kubernetes/kubernetes/issues/109162

I have also helped improve documentation of the Kubernetes project, see:
- https://github.com/kubernetes/website/pull/27585
- https://github.com/kubernetes/website/pull/21534
- https://github.com/kubernetes/website/pull/15750

**Comment by jayunit100** [comment]
Without david we wouldnt' really have a coherent, both for CNI and kube proxy, windows networking story, hes one of the most critical assets in the community for deep dives of kube proxy issues, so definetly please lets make his membership official

**Comment by jsturtevant** [comment]
+1 David is a consistent member at our sig meetings and contributes to solving some of the toughest networking bugs we've run into

**Comment by palnabarun** [comment]
@daschott -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign

**Comment by daschott** [comment]
Thank you so much everyone!
