### ISSUE TITLE
REQUEST: New membership for Seo-yul

### ISSUE THREAD

**Issue by Seo-yul** [kubernetes/org#3672]
### GitHub Username

@Seo-yul

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@seokho-son

### Sponsor 2

@yoonian

### List of contributions to the Kubernetes project

PRs reviewed / authored
https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3ASeo-yul
Issues responded to
https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3ASeo-yul+assignee%3ASeo-yul
SIG projects I am involved with
kubernetes/sig-docs

**Comment by seokho-son** [comment]
+1 
@Seo-yul is very supportive contributor!

**Comment by palnabarun** [comment]
@Seo-yul -- Thank you for all your contributions so far!

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
