### ISSUE TITLE
REQUEST: New membership for @bradmccoydev

### ISSUE THREAD

**Issue by bradmccoydev** [kubernetes/org#3676]
### GitHub Username

@bradmccoydev

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@fsmunoz

### Sponsor 2

@leonardpahlke

### List of contributions to the Kubernetes project

- Kubernetes Release team v1.26

**Comment by fsmunoz** [comment]
+1, welcome to the Comms team!

**Comment by palnabarun** [comment]
+1, Welcome to the 1.26 Release Team! Thank you for volunteering! 🎉

**Comment by palnabarun** [comment]
@bradmccoydev -- Thank you again for volunteering! 

I have raised #3677 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
