### ISSUE TITLE
REQUEST: New membership for davidmirror-ops

### ISSUE THREAD

**Issue by davidmirror-ops** [kubernetes/org#3680]
### GitHub Username

davidmirror-ops

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

fsmunoz

### Sponsor 2

leonardpahlke

### List of contributions to the Kubernetes project

- Mostly involved with the [SIG Software Supply Chain](https://github.com/cdfoundation/sig-software-supply-chain#members) at the Continuous Delivery Foundation
- Single PR to the Kubernetes project https://github.com/kubernetes/community/pull/6111

**Comment by leonardpahlke** [comment]
+1 welcome! :) 

ref: https://github.com/kubernetes/org/pull/3686

cc @fsmunoz

**Comment by fsmunoz** [comment]
+1 , welcome to the team!

**Comment by palnabarun** [comment]
@davidmirror-ops -- Thank you for all your contributions so far!

I have raised #3690 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
