### ISSUE TITLE
REQUEST: New membership for @sayantani11

### ISSUE THREAD

**Issue by sayantani11** [kubernetes/org#3681]
### GitHub Username

@sayantani11

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ramrodo

### Sponsor 2

@leonardpahlke

### List of contributions to the Kubernetes project

Part of Kubernetes Release team v1.26

**Test infra**
https://github.com/kubernetes/test-infra/pull/24551
https://github.com/kubernetes/test-infra/pull/25447
https://github.com/kubernetes/test-infra/pull/25605

**Comment by leonardpahlke** [comment]
+1, welcome! :)

**Comment by ramrodo** [comment]
+1, Welcome to the team!

**Comment by dims** [comment]
+1 welcome @sayantani11

**Comment by sayantani11** [comment]
> +1 welcome @sayantani11

Thank you so much @dims 
Means a lot

**Comment by leonardpahlke** [comment]
ref: https://github.com/kubernetes/org/pull/3686

**Comment by palnabarun** [comment]
Welcome again! 🎉 

Note: Since you are already a member of @kubernetes-sigs, you don't need sponsorship to get added to other Kubernetes GitHub orgs.

I have raised #3690 to add you to the requested org. Once that merges, you would get the membership invite notification.

/assign
