### ISSUE TITLE
REQUEST: New membership for @harshanarayana

### ISSUE THREAD

**Issue by harshanarayana** [kubernetes/org#3683]
### GitHub Username

@harshanarayana

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ramrodo

### Sponsor 2

@leonardpahlke

### List of contributions to the Kubernetes project

Part of Kubernetes Release team v1.26 (Release Notes Shadow)

## PRs reviewed/authored
1. https://github.com/kubernetes-sigs/e2e-framework/pull/157
2. https://github.com/kubernetes/kubernetes/pull/110649
3. https://github.com/kubernetes/kubernetes/pull/110294
4. https://github.com/kubernetes/kubernetes/pull/110710
5. https://github.com/kubernetes-sigs/kubebuilder/pull/2733
6. https://github.com/kubernetes-sigs/e2e-framework/pull/157
7. https://github.com/kubernetes-sigs/e2e-framework/pull/143
8. https://github.com/kubernetes-sigs/e2e-framework/pull/120
9. https://github.com/kubernetes-sigs/e2e-framework/pull/118
10. https://github.com/kubernetes-sigs/e2e-framework/pull/73
## Sig projects I'm involved in
- [e2e-framework](https://github.com/kubernetes-sigs/e2e-framework)
- [kind](https://github.com/kubernetes-sigs/kind)
- [klog](https://github.com/kubernetes/klog)
- [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime)

**Comment by leonardpahlke** [comment]
+1, I think you don't need to create this issue to join K8s-sigs if you are already K8s member - you can just add yourself :)

**Comment by leonardpahlke** [comment]
https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/org.yaml

**Comment by leonardpahlke** [comment]
@mrbobbytables perhaps we could update the documentation to highlight that being a K8s member does not require sponsorship of other K8s organizations? I could add a note to the issue template - WDYT?

@mrbobbytables Does this apply the other way around, if you are a K8s-sigs member, you don't need sponsorship for the K8s organization?

**Comment by harshanarayana** [comment]
Thanks @leonardpahlke  I've opened a PR to do the same.

**Comment by palnabarun** [comment]
@leonardpahlke -- Membership of any orgs grants implicit rights to be part of the other orgs. So, both cases that you enumerate hold true.
