### ISSUE TITLE
REQUEST: New membership for @tenzen-y

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes/org#3685]
### GitHub Username

@tenzen-y

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alculquicondor

### Sponsor 2

@kerthcet

### List of contributions to the Kubernetes project

- PRs reviewed/authored
https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Atenzen-y
https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+author%3Atenzen-y

- Issues responded to
https://github.com/kubernetes-sigs/kueue/issues?q=is%3Aissue+assignee%3Atenzen-y
https://github.com/kubernetes-sigs/kueue/issues?q=is%3Aissue+author%3Atenzen-y

- Sig projects I'm involved in
[kueue](https://github.com/kubernetes-sigs/kueue)

**Comment by kerthcet** [comment]
+1, looking forward to your more contributions!

**Comment by alculquicondor** [comment]
+1

**Comment by palnabarun** [comment]
@tenzen-y -- Thank you for all your contributions so far!

I have raised #3690 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
