### ISSUE TITLE
REQUEST: Create kubernetes-sigs/sig-auth-tools

### ISSUE THREAD

**Issue by aramase** [kubernetes/org#3688]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

sig-auth-tools

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

enj, ritazh

### Who should have write access?

enj, ritazh

### Who should be listed as approvers in OWNERS?

enj, ritazh

### Who should be listed in SECURITY_CONTACTS?

enj, ritazh

### What should the repo description be?

Repository for tools and artifacts related to the sig-auth charter in Kubernetes.

### What SIG and subproject does this fall under?

sig-auth

### Please provide references to appropriate approval for this new repo

https://kubernetes.slack.com/archives/C0EN96KUY/p1663091084021459

### Additional context for request

ref: https://github.com/kubernetes/kubernetes/issues/111963

**Comment by aramase** [comment]
cc @deads2k @mikedanese @liggitt

**Comment by enj** [comment]
Probably should use sig-auth-leads owner alias to cover all the leads.

LGTM otherwise.

**Comment by aramase** [comment]
> Probably should use sig-auth-leads owner alias to cover all the leads.

We would need to create that alias in the new repo and use it. I think `sig-auth-leads` is now only relevant in k/k?

**Comment by enj** [comment]
> > Probably should use sig-auth-leads owner alias to cover all the leads.
> 
> We would need to create that alias in the new repo and use it. I think `sig-auth-leads` is now only relevant in k/k? 

I feel like we should have automation for this...

**Comment by mrbobbytables** [comment]
teams have been added, the repo should now be usable 👍

**Comment by mrbobbytables** [comment]
outstanding PRs have been merged, going to go ahead and close 👍 

/close

**Comment by aramase** [comment]
Thank you @mrbobbytables!
