### ISSUE TITLE
REQUEST: New membership for neoaggelos

### ISSUE THREAD

**Issue by neoaggelos** [kubernetes/org#3691]
### GitHub Username

@neoaggelos

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@hosseinsalahi

### Sponsor 2

@leonardpahlke

### List of contributions to the Kubernetes project

SIG projects @neoaggelos involved with: sig-release,  @neoaggelos is Bug Triage Shadow for 1.26

**Comment by leonardpahlke** [comment]
ref PR to add you to the release team group: https://github.com/kubernetes/org/issues/3691

**Comment by hosseinsalahi** [comment]
+1, welcome :)

**Comment by palnabarun** [comment]
+1, welcome! :)

(I am putting a +1 since both sponsors can't be from the same company)

**Comment by palnabarun** [comment]
@neoaggelos  -- Welcome to the Kubernetes Release Team!

I have raised #3708 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
