### ISSUE TITLE
REQUEST: New membership for @SubhasmitaSw

### ISSUE THREAD

**Issue by SubhasmitaSw** [kubernetes/org#3697]
### GitHub Username

@SubhasmitaSw

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@hosseinsalahi

### List of contributions to the Kubernetes project

Part of Kubernetes Release team v1.26 (Bug Triage Shadow)

## **PRs reviewed/authored**

1. https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/655
2. https://github.com/kubernetes/website/pull/364722. 
3. https://github.com/kubernetes-sigs/cluster-api/pull/6252
4. https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/642
5. https://github.com/kubernetes/contributor-site/pull/303
6. https://github.com/kubernetes/contributor-site/pull/293
7. https://github.com/kubernetes/kubernetes/pull/108110
8. https://github.com/kubernetes/kubernetes/pull/107691
9. https://github.com/kubernetes/website/pull/31454

## **Sig projects I'm involved in**

- [cluster-api-provider-gcp](https://github.com/kubernetes-sigs/cluster-api-provider-gcp)
- [cluster-api](https://github.com/kubernetes-sigs/cluster-api)
- [image-builder](https://github.com/kubernetes-sigs/image-builder)

**Comment by dims** [comment]
+1 from me. welcome @SubhasmitaSw

**Comment by richardcase** [comment]
+1 from as well

**Comment by leonardpahlke** [comment]
+1, welcome :) 

ref PR to add you to the release team group: https://github.com/kubernetes/org/pull/3686

**Comment by hosseinsalahi** [comment]
+1, welcome :)

**Comment by palnabarun** [comment]
@SubhasmitaSw  -- Thank you for all your contributions so far! And, Welcome to the Kubernetes Release Team!

I have raised #3708 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
