### ISSUE TITLE
REQUEST: New membership for aniruddha2000

### ISSUE THREAD

**Issue by aniruddha2000** [kubernetes/org#3698]
### GitHub Username

@aniruddha2000

### Organization you are requesting membership in

Kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@palnabarun

### Sponsor 2

@cpanato

### List of contributions to the Kubernetes project

PRs -
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/635
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/597
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/635
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/634
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/586
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/584
- https://github.com/kubernetes-sigs/cluster-api/pull/7111
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/655
- https://github.com/kubernetes-sigs/image-builder/pull/934

SIG projects -
- CAPI
- CAPG
- Image Builder

**Comment by cpanato** [comment]
+1 🎉

**Comment by palnabarun** [comment]
Huge +1!

**Comment by richardcase** [comment]
+1 from me as well

**Comment by dims** [comment]
+1 from me!

**Comment by palnabarun** [comment]
@aniruddha2000  -- Thank you for all your contributions so far!

I have raised #3708 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
