### ISSUE TITLE
REQUEST: New membership for khoang98

### ISSUE THREAD

**Issue by khoang98** [kubernetes/org#3700]
### GitHub Username

@khoang98

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@wongma7

### Sponsor 2

@jmwurst

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/254
- https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/224
- https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/217

**Comment by wongma7** [comment]
+1

**Comment by jmwurst** [comment]
+1 :party_parrot:

**Comment by mrbobbytables** [comment]
@khoang98 do you happen to have another sponsor? @jmwurst [cannot act as a sponsor](https://cs.k8s.io/?q=jmwurst&i=fosho&files=OWNERS&excludeFiles=vendor%2F&repos=) - sponsors must be a reviewer or approver in one of the kubernetes orgs.

**Comment by olemarkus** [comment]
I am happy to sponsor for the work done on the fsx csi driver

+1

**Comment by mrbobbytables** [comment]
That'll do!
/assign

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3720  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
