### ISSUE TITLE
REQUEST: New membership for asim-reza

### ISSUE THREAD

**Issue by asim-reza** [kubernetes/org#3701]
### GitHub Username

@asim-reza

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@aojea

### Overview of Work Done
- I have been working on and completed a pretty big cleanup of Test Job Configurations in [kubernetes/test-infra](https://github.com/kubernetes/test-infra)
- Currently working on writing Stress/Load tests for [kubernetes-sigs/kpng](https://github.com/kubernetes-sigs/kpng) & helping out with 
[k8s.io](https://github.com/kubernetes/k8s.io) image pull url replacement to use `oci-proxy`

### Issues Opened and Completed
[#27457](https://github.com/kubernetes/test-infra/issues/27457)
[#27456](https://github.com/kubernetes/test-infra/issues/27456)
[#27455](https://github.com/kubernetes/test-infra/issues/27455)
[#27454](https://github.com/kubernetes/test-infra/issues/27454)
[#27453](https://github.com/kubernetes/test-infra/issues/27453)
[#27452](https://github.com/kubernetes/test-infra/issues/27452)
[#27451](https://github.com/kubernetes/test-infra/issues/27451)
[#27450](https://github.com/kubernetes/test-infra/issues/27450)
[#27449](https://github.com/kubernetes/test-infra/issues/27449)
[#27448](https://github.com/kubernetes/test-infra/issues/27448)
[#27447](https://github.com/kubernetes/test-infra/issues/27447)
[#27446](https://github.com/kubernetes/test-infra/issues/27446)
[#27445](https://github.com/kubernetes/test-infra/issues/27445)
[#27444](https://github.com/kubernetes/test-infra/issues/27444)
[#27443](https://github.com/kubernetes/test-infra/issues/27443)
[#27442](https://github.com/kubernetes/test-infra/issues/27442)
[#27441](https://github.com/kubernetes/test-infra/issues/27441)
[#27440](https://github.com/kubernetes/test-infra/issues/27440)
[#27439](https://github.com/kubernetes/test-infra/issues/27439)
[#27438](https://github.com/kubernetes/test-infra/issues/27438)
[#27437](https://github.com/kubernetes/test-infra/issues/27437)
[#27435](https://github.com/kubernetes/test-infra/issues/27435)
[#27434](https://github.com/kubernetes/test-infra/issues/27434)
[#27432](https://github.com/kubernetes/test-infra/issues/27432)
[#27431](https://github.com/kubernetes/test-infra/issues/27431)
[#27430](https://github.com/kubernetes/test-infra/issues/27430)
[#27426](https://github.com/kubernetes/test-infra/issues/27426)

### Merged PRs
[#1376](https://github.com/kubernetes-sigs/gateway-api/pull/1376)
[#27391](https://github.com/kubernetes/test-infra/pull/27391)
[#27459](https://github.com/kubernetes/test-infra/pull/27459)
[#27460](https://github.com/kubernetes/test-infra/pull/27460)
[#27462](https://github.com/kubernetes/test-infra/pull/27462)
[#27466](https://github.com/kubernetes/test-infra/pull/27466)
[#27467](https://github.com/kubernetes/test-infra/pull/27467)
[#27469](https://github.com/kubernetes/test-infra/pull/27469)
[#27474](https://github.com/kubernetes/test-infra/pull/27474)
[#27478](https://github.com/kubernetes/test-infra/pull/27478)
[#27479](https://github.com/kubernetes/test-infra/pull/27479)
[#27487](https://github.com/kubernetes/test-infra/pull/27487)
[#27494](https://github.com/kubernetes/test-infra/pull/27494)
[#27495](https://github.com/kubernetes/test-infra/pull/27495)
[#27513](https://github.com/kubernetes/test-infra/pull/27513)
[#27514](https://github.com/kubernetes/test-infra/pull/27514)
[#27515](https://github.com/kubernetes/test-infra/pull/27515)
[#27516](https://github.com/kubernetes/test-infra/pull/27516)
[#27526](https://github.com/kubernetes/test-infra/pull/27526)
[#27529](https://github.com/kubernetes/test-infra/pull/27529)

**Comment by aojea** [comment]
+1

**Comment by dims** [comment]
+1

**Comment by MadhavJivrajani** [comment]
+1 
Thank you for your work! 
/woof

**Comment by palnabarun** [comment]
@asim-reza  -- Thank you for all your contributions so far!

I have raised #3708 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
