### ISSUE TITLE
REQUEST: New membership for Dyanngg

### ISSUE THREAD

**Issue by Dyanngg** [kubernetes/org#3703]
### GitHub Username

@Dyanngg

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@astoycos

### Sponsor 2

@rikatz

### List of contributions to the Kubernetes project

I am already a member of the Kubernetes org. However, to add myself as the owner and security contact for the kubernetes-sigs/network-policy-api repo https://github.com/kubernetes-sigs/network-policy-api/pull/32 which I'm actively contributing to, I need to be a member of the kubernetes-sigs as well. I will be one of the maintainers for the AdminNetworkPolicy API, which is currently housed in that repo. Could you please kindly approve this request, thanks!

**Comment by astoycos** [comment]
+1

Yang has been one of the main contributors to the AdminNetworkPolicy API and needs this membership to help us get the API up and running

**Comment by rikatz** [comment]
+1 
Andrew already said it all! :)

**Comment by palnabarun** [comment]
@Dyanngg  -- Thank you for all your contributions so far!

I have raised #3708 to add you to the requested orgs. Once that merges, you would get the membership invite notifications.

Welcome! 🎉

/assign
