### ISSUE TITLE
REQUEST: New membership for mskrocki

### ISSUE THREAD

**Issue by mskrocki** [kubernetes/org#3712]
### GitHub Username

mskrocki

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

aojea

### Sponsor 2

robscott

### List of contributions to the Kubernetes project

- kick-off and leading the Multi-Network sub-project in SIG Networking - [slides](https://docs.google.com/presentation/d/113zpX7-QWJnKz5QiTPBciXwDGvMMK5r_f_c0fw2zuZg/edit?usp=sharing)
- reviewed a KEP https://github.com/kubernetes/enhancements/pull/2594 that got merged
- created an issue: https://github.com/kubernetes/kubernetes/issues/96018

**Comment by aojea** [comment]
+1 

he has been doing a lot of works leading the multinetwork sub-project.
Looking forward for more contributions on sig-network

**Comment by robscott** [comment]
+1

Looking forward to seeing what you do with multinetwork!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3720  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
