### ISSUE TITLE
REQUEST: New membership for @tuxtof

### ISSUE THREAD

**Issue by vnephologist** [kubernetes/org#3713]
### GitHub Username

@tuxtof

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@CecileRobertMichon

### Sponsor 2

@fabriziopandini

### List of contributions to the Kubernetes project

Actively involved in Cluster API.

https://github.com/kubernetes-sigs/cluster-api/pull/6367
https://github.com/kubernetes-sigs/cluster-api/pull/6378
https://github.com/kubernetes-sigs/cluster-api/pull/7249

**Comment by CecileRobertMichon** [comment]
+1 from my side, looking forward to @tuxtof helping maintain the image-builder nutanix provider

**Comment by fabriziopandini** [comment]
+1 from my side, welcome to the team!

**Comment by chris-short** [comment]
#3715 has been opened to add you to kubernetes-sigs
