### ISSUE TITLE
REQUEST: New membership for melnikalex

### ISSUE THREAD

**Issue by melnikalex** [kubernetes/org#3714]
### GitHub Username

@melnikalex

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@nckturner 

### Sponsor 2

@gyuho

### List of contributions to the Kubernetes project

PRs:
https://github.com/kubernetes/perf-tests/pull/1881
https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/367
https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/489
https://github.com/kubernetes/kubernetes/pull/84659

Participating Issues:
https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/466

SIGs:
sig-auth

**Comment by chris-short** [comment]
Please replace \<your-GH-handle> in the title with your username.

**Comment by mrbobbytables** [comment]
This has been open for some time without any action. I'm going to go ahead and close it out for now. @melnikalex please reopen or create a new issue once you've contributed a bit more and secured some sponsors 👍 

Thanks!

/close
