### ISSUE TITLE
REQUEST: New membership for ConnorJC3

### ISSUE THREAD

**Issue by ConnorJC3** [kubernetes/org#3716]
### GitHub Username

@ConnorJC3

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@torredil

### Sponsor 2

@jsafrane

### List of contributions to the Kubernetes project

- Commits Merged: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commits?author=ConnorJC3
- PRs Authored: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pulls?q=is%3Apr+author%3AConnorJC3
- PRs Reviwed: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pulls?q=is%3Apr+reviewed-by%3AConnorJC3
- Issue Contributions: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues?q=is%3Aissue+mentions%3AConnorJC3

**Comment by jsafrane** [comment]
+1

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3720  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
