### ISSUE TITLE
REQUEST: New membership for @amolmote

### ISSUE THREAD

**Issue by amolmote** [kubernetes/org#3717]
### GitHub Username

@amolmote

### Organization you are requesting membership in

kubernetes, kubernetes-csi, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@natalisucks

### Sponsor 2

@divya-mohan0209 

## Kubernetes
- [kubernetes/community](https://github.com/kubernetes/community/pull/6870)
- [kubernetes/website](https://github.com/kubernetes/website/pull/36911)
- [kubernetes/website](https://github.com/kubernetes/website/pull/36135)
- [kubernetes/website](https://github.com/kubernetes/website/pull/36600)
- [kubernetes/website](https://github.com/kubernetes/website/pull/36881)
- [kubernetes/website](https://github.com/kubernetes/website/pull/36104)

## Kubernetes-csi
- [kubernetes-csi/csi-driver-host-path](https://github.com/kubernetes-csi/csi-driver-host-path/pull/370)
- [kubernetes-csi/external-attacher](https://github.com/kubernetes-csi/external-attacher/pull/376)
- [kubernetes-csi/external-health-monitor](https://github.com/kubernetes-csi/external-health-monitor/pull/133)
- [kubernetes-csi/csi-driver-image-populator](https://github.com/kubernetes-csi/csi-driver-image-populator/pull/23)
- [kubernetes-csi/csi-proxy](https://github.com/kubernetes-csi/csi-proxy/pull/219)
- [kubernetes-csi/external-provisioner](https://github.com/kubernetes-csi/external-provisioner/pull/787)

## Kubernetes-sigs
- [kubernetes-sigs/windows-testing](https://github.com/kubernetes-sigs/windows-testing/pull/341)
-  [kubernetes-sigs/krew](https://github.com/kubernetes-sigs/krew/pull/804)
- [kubernetes-sigs/reference-docs](https://github.com/kubernetes-sigs/reference-docs/pull/298)
- [kubernetes-sigs/azurelustre-csi-driver](https://github.com/kubernetes-sigs/azurelustre-csi-driver/pull/57)
- [kubernetes-sigs/blob-csi-driver](https://github.com/kubernetes-sigs/blob-csi-driver/pull/757)
- [kubernetes-sigs/azurefile-csi-driver](https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1089)
-  [ kubernetes-sigs/release-notes](https://github.com/kubernetes-sigs/release-notes/pull/318)
- [kubernetes-sigs/sig-storage-lib-external-provisioner](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/127)
- [kubernetes-sigs/node-feature-discovery-operator](https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/165)

## Issue I am now working on 
- [kubernetes/website](https://github.com/kubernetes/website/issues/35600)

**Comment by divya-mohan0209** [comment]
+1 for this :) Thank you so much for all your contributions & welcome!

**Comment by natalisucks** [comment]
+1! Thanks for contributing and being a great example to the rest of our docs community – welcome 🎉

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3720  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉

**Comment by amolmote** [comment]
Thank u so much @divya-mohan0209, @natalisucks and @mrbobbytables.
