### ISSUE TITLE
REQUEST: New membership for marcushyungseoklee

### ISSUE THREAD

**Issue by marcushyungseoklee** [kubernetes/org#3727]
### GitHub Username

@marcushyungseoklee

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jihoon-seo

### Sponsor 2

@yoonian

### List of contributions to the Kubernetes project

PRs reviewed / authored
https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Amarcushyungseoklee

Issues responded to
https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Amarcushyungseoklee+assignee%3Amarcushyungseoklee+

SIG projects I am involved with
kubernetes/sig-docs

**Comment by jihoon-seo** [comment]
+1 @marcushyungseoklee is an active contributor of SIG Docs Korean L10n team, and I am happy to be a sponsor of his applying for becoming a K8s org member!

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR #3745  to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉
