### ISSUE TITLE
REQUEST: New membership for alejandrox1

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/org#373]
### GitHub Username
@alejandrox1 

### Organization you are requesting membership in
@kubernetes-sigs 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @BenTheElder 
- @neolit123 

### List of contributions to the Kubernetes project
- PRs reviewed / authored 
  - [kind](https://github.com/kubernetes-sigs/kind/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aalejandrox1)
  - [cluster-api](https://github.com/kubernetes-sigs/cluster-api/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aalejandrox1)
 
- Issues responded to
   - [kind](https://github.com/kubernetes-sigs/kind/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Aalejandrox1) 
    - [kubeadm](https://github.com/kubernetes/kubeadm/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Aalejandrox1)

- SIG projects I am involved with
  - sig-testing
  - sig-cluster-lifecycle

**Comment by BenTheElder** [comment]
+1, thanks for your efforts!

**Comment by neolit123** [comment]
+1 thanks :tada:

**Comment by mrbobbytables** [comment]
Hey there @alejandrox1 , thank you for all your contributions so far :)

I've created PR #378  to add you to the @kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome aboard! :tada:

/assign

/pony party
