### ISSUE TITLE
REQUEST: New membership for @deepakm-ntnx 

### ISSUE THREAD

**Issue by vnephologist** [kubernetes/org#3730]
### GitHub Username

@deepakm-ntnx 

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@CecileRobertMichon

### Sponsor 2

@fabriziopandini

### List of contributions to the Kubernetes project

Authored https://github.com/kubernetes-sigs/image-builder/pull/982

Involved in Cluster API project and maintainer of CAPX provider and associated components.

@CecileRobertMichon @fabriziopandini I believe you already know Deepak from the SIG meetings. He will be the other maintainer of image-builder and other components along with Christophe.

**Comment by fabriziopandini** [comment]
@vnephologist can we get a couple of more PRs/issues in the track?

**Comment by vnephologist** [comment]
> @vnephologist can we get a couple of more PRs/issues in the track?

@fabriziopandini Here are few more for our CAPX provider...

https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/pull/92
https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/pull/105
https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/pull/118
https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/pull/131

**Comment by fabriziopandini** [comment]
We can consider only PRs in the org (Kubernetes or Kubernetes-sigs) 😅

**Comment by mrbobbytables** [comment]
It's been some time since this was originally created. I am going to go ahead and close it for now. @vnephologist please reopen or create a new issue once you've contributed more to the project and gotten the okay from sponsors. 👍 

/close
