### ISSUE TITLE
REQUEST: Create kubernetes-sigs/ingress2gateway

### ISSUE THREAD

**Issue by robscott** [kubernetes/org#3731]
### New repo, staging repo, or migrate existing

New repo

### Is it a staging repo?

no

### Requested name for new repository

kubernetes-sigs/ingress2gateway

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

bowei, robscott, shaneutt, youngnick

### Who should have write access?

bowei, robscott, shaneutt, youngnick

### Who should be listed as approvers in OWNERS?

bowei, robscott, shaneutt, youngnick

### Who should be listed in SECURITY_CONTACTS?

bowei, robscott, shaneutt, youngnick

### What should the repo description be?

Convert Ingress resources to Gateway API resources

### What SIG and subproject does this fall under?

SIG Network Gateway API

### Please provide references to appropriate approval for this new repo

https://groups.google.com/g/kubernetes-sig-network/c/B7OKxLY8Qek

**Comment by robscott** [comment]
cc @caseydavenport @dcbw @thockin

**Comment by mrbobbytables** [comment]
repo created: https://github.com/kubernetes-sigs/ingress2gateway
teams added: https://github.com/kubernetes/org/pull/3758
update to k/community: https://github.com/kubernetes/community/pull/6919

once all PRs are merged and teams added, this should be able to be closed 👍

**Comment by mrbobbytables** [comment]
other PRs have been merged, going to go ahead and close.

/close
