### ISSUE TITLE
REQUEST: New membership for @annasong20

### ISSUE THREAD

**Issue by annasong20** [kubernetes/org#3736]
### GitHub Username

@annasong20

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@knverey

### Sponsor 2

@natasha41575

### List of contributions to the Kubernetes project

SIG project: [kubernetes-sigs/kustomize](https://github.com/kubernetes-sigs/kustomize)

PRs:
* authored:
  * https://github.com/kubernetes-sigs/kustomize/pull/4590
  * https://github.com/kubernetes-sigs/kustomize/pull/4652
  * https://github.com/kubernetes-sigs/kustomize/pull/4677
  * https://github.com/kubernetes-sigs/kustomize/pull/4615
  * https://github.com/kubernetes-sigs/kustomize/pull/4664
  * https://github.com/kubernetes-sigs/kustomize/pull/4541
* helped review:
  * https://github.com/kubernetes-sigs/kustomize/pull/4715
  * https://github.com/kubernetes-sigs/kustomize/pull/4733

Issues
* commented on:
  * https://github.com/kubernetes-sigs/kustomize/issues/4799
  * https://github.com/kubernetes-sigs/kustomize/issues/4722
  * https://github.com/kubernetes-sigs/kustomize/issues/4581
  * https://github.com/kubernetes-sigs/kustomize/issues/4584
  * https://github.com/kubernetes-sigs/kustomize/issues/4795   
* filed:
  * https://github.com/kubernetes-sigs/kustomize/issues/4640 
  * https://github.com/kubernetes-sigs/kustomize/issues/4620
  * https://github.com/kubernetes-sigs/kustomize/issues/4811
  * https://github.com/kubernetes-sigs/kustomize/issues/4622

**Comment by natasha41575** [comment]
+1 from me!

**Comment by KnVerey** [comment]
+1 from me as well!

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR #3745  to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉
