### ISSUE TITLE
REQUEST: New membership for krzysztof-jastrzebski

### ISSUE THREAD

**Issue by krzysztof-jastrzebski** [kubernetes/org#374]
### GitHub Username

krzysztof-jastrzebski

### Organization you are requesting membership in
e.g. (at)kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mwielgus
- @andrewsykim

### List of contributions to the Kubernetes project
- PRs authored
23 PRs merged to kubernetes/kubernetes:
https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Amerged+is%3Aclosed+is%3Apr+author%3Akrzysztof-jastrzebski+
30 PRs merged to kubernetes/autoscaler:
https://github.com/kubernetes/autoscaler/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Akrzysztof-jastrzebski+is%3Amerged

**Comment by andrewsykim** [comment]
+1

**Comment by mrbobbytables** [comment]
@krzysztof-jastrzebski Thank you for all the work you've put in :)

I've created PR #378 to add you to the @kubernetes org. Once it gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
