### ISSUE TITLE
REQUEST: New membership for qinqon

### ISSUE THREAD

**Issue by qinqon** [kubernetes/org#3740]
### GitHub Username

qinqon

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

davidvossel

### Sponsor 2

rmohr

### List of contributions to the Kubernetes project

PRs at kubernetes-sigs/cluster-api-provider-kubevirt
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pulls?q=is%3Aclose+author%3Aqinqon

PRs at kuberentes-sigs/kind
https://github.com/kubernetes-sigs/kind/pull/2321

Issues at kubernetes/kubernetes
https://github.com/kubernetes/kubernetes/issues/94720

**Comment by davidvossel** [comment]
/lgtm

@qinqon has been an active contributor of https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt for some time now. I fully support him becoming a member of kubernetes-sigs

**Comment by rmohr** [comment]
/lgtm

As David said, he is an active and trustworthy contributor in https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt.

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3763  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
