### ISSUE TITLE
REQUEST: New membership for mattfenwick

### ISSUE THREAD

**Issue by mattfenwick** [kubernetes/org#3741]
### GitHub Username

mattfenwick

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

astoycos

### Sponsor 2

rikatz

### GitHub Username

@mattfenwick

PRs reviewed / authored: 

 - https://github.com/kubernetes/kubernetes/pull/94182
 - https://github.com/kubernetes/kubernetes/pull/94015
 - https://github.com/kubernetes/kubernetes/pull/91592
 - https://github.com/kubernetes/kubernetes/pull/97526
 - https://github.com/kubernetes/kubernetes/pull/97571
 - https://github.com/kubernetes/kubernetes/pull/97524

Issues responded to: 

 - https://github.com/kubernetes/kubernetes/issues/97226
 - https://github.com/kubernetes/kubernetes/issues/97425
 - https://github.com/kubernetes/kubernetes/issues/96341
 - https://github.com/kubernetes/kubernetes/issues/94005
 - https://github.com/kubernetes/kubernetes/issues/95879
 - https://github.com/kubernetes/kubernetes/issues/97553
 - https://github.com/kubernetes/kubernetes/issues/97489
 - https://github.com/kubernetes/kubernetes/issues/96786

sigs participated in: sig-network

**Comment by astoycos** [comment]
/lgtm 

Thanks Matt!

**Comment by rikatz** [comment]
/lgtm
Thank you Matt for all the effort in Network Policy area

**Comment by mrbobbytables** [comment]
/assign
I'll be doing a batch of org memberships tonight, but an FYI for the future - as a member of one of the orgs already you don't need to file a request :) you can add yourself to another org with a PR 👍
