### ISSUE TITLE
REQUEST: New membership for moadqassem

### ISSUE THREAD

**Issue by moadqassem** [kubernetes/org#3747]
### GitHub Username

@moadqassem

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [x] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have verified that my sponsors are from different member companies
- [x] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sttts

### Sponsor 2

@displague

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/448
- https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/443

**Comment by sttts** [comment]
+1

**Comment by displague** [comment]
+1 

Thanks for the contributions and discussions @moadqassem

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR #3785 to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign
