### ISSUE TITLE
REQUEST: New membership for shurup

### ISSUE THREAD

**Issue by shurup** [kubernetes/org#3749]
### GitHub Username

shurup

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sftim

### Sponsor 2

@a-mccarthy

### List of contributions to the Kubernetes project

I visited the SIG Docs localization meeting on July 11th, and now I'm trying to revive the Russian-speaking localization team for Kubernetes. There are no active members there anymore (new PRs have stalled for a while), and my recent [appeal in Slack](https://kubernetes.slack.com/archives/CPZ9KD9TN/p1657624554470139) had no reaction. We need someone who can approve translations to proceed with this localization.

GitHub contributions:
- My PR: https://github.com/kubernetes/website/pull/25808
- My PR (small corrections; still not merged): https://github.com/kubernetes/website/pull/31512 + https://github.com/kubernetes/website/pull/35221
- My PR (still not merged): https://github.com/kubernetes/website/pull/35019
- The PR was made by my colleague (it was reviewed by me internally; still not merged): https://github.com/kubernetes/website/pull/34803
- PRs by my colleague with my reviews (still not merged):
  - https://github.com/kubernetes/website/pull/36327
  - https://github.com/kubernetes/website/pull/36328
  - https://github.com/kubernetes/website/pull/36329
  - https://github.com/kubernetes/website/pull/36466
  - https://github.com/kubernetes/website/pull/36467
  - https://github.com/kubernetes/website/pull/36783
  - https://github.com/kubernetes/website/pull/36782
- This my PR was not formally for the Kubernetes project, but still relevant in some way: https://github.com/cncf/foundation/pull/181
- Not related to localization. https://github.com/kubernetes/website/pull/27975
- Not related to localization. In some way (by creating https://github.com/nginxinc/kubernetes-ingress/issues/1910), I initiated this nginx-related issue: https://github.com/kubernetes/ingress-nginx/issues/7554

**Comment by a-mccarthy** [comment]
@shurup +1 from me! Thanks for working on the Russian localization effort 🎉

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3763  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
