### ISSUE TITLE
REQUEST: New membership for dntosas

### ISSUE THREAD

**Issue by dntosas** [kubernetes/org#3753]
### GitHub Username

@dntosas

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@hakman

### List of contributions to the Kubernetes project

Actively involved in multiple projects, both on GH and on Kubernetes Workspace. Looking forward to contributing further to the ecosystem. :)

Sampled list of contributions:
- https://github.com/kubernetes/kubernetes/pull/104518
- https://github.com/kubernetes/kops/pull/12524
- https://github.com/kubernetes/kops/pull/12334
- https://github.com/kubernetes/kops/pull/12292
- https://github.com/kubernetes/kops/pull/12247
- https://github.com/kubernetes/kops/pull/12219
- https://github.com/kubernetes/kops/pull/12198
- https://github.com/kubernetes/kops/pull/12158
- https://github.com/kubernetes/kops/pull/11678
- https://github.com/kubernetes/kops/pull/11583
- https://github.com/kubernetes/kops/pull/11500
- https://github.com/kubernetes/kops/pull/11418
- https://github.com/kubernetes/kops/pull/11381
- https://github.com/kubernetes/kops/pull/11360
- https://github.com/kubernetes/kops/pull/11319
- https://github.com/kubernetes/kops/pull/11304
- https://github.com/kubernetes/kops/pull/11248
- https://github.com/kubernetes/kops/pull/10712
- https://github.com/kubernetes/kops/pull/10281
- https://github.com/kubernetes/kops/pull/10273
- https://github.com/kubernetes/kops/pull/10038
- https://github.com/kubernetes/kops/issues/11450
- https://github.com/kubernetes-sigs/cluster-api/pull/6414
- https://github.com/kubernetes-sigs/cluster-api/pull/5993
- https://github.com/kubernetes-sigs/kubebuilder/pull/2516

**Comment by sbueringer** [comment]
+1
Thx for all your contributions :)

**Comment by hakman** [comment]
+1
Happy to see you finally joining the org. Welcome!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3763  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
