### ISSUE TITLE
REQUEST: New membership for alexander-ding

### ISSUE THREAD

**Issue by alexander-ding** [kubernetes/org#3755]
### GitHub Username

alexander-ding

### Organization you are requesting membership in

kubernetes-csi

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

mauriciopoppe

### Sponsor 2

jingxu97

### List of contributions to the Kubernetes project

Working on csi-proxy migration to use HostProcess Pods
- [PR](https://github.com/kubernetes-csi/csi-proxy/pull/228)
- [PR](https://github.com/kubernetes-csi/csi-proxy/pull/230)
- [PR](https://github.com/kubernetes-csi/csi-proxy/pull/231)

**Comment by jingxu97** [comment]
+1
/approve

**Comment by mauriciopoppe** [comment]
+1
@alexander-ding is helping with the migration of CSI Drivers to become HostProcess pods in Windows

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3763  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
