### ISSUE TITLE
REQUEST: New membership for nabokihms

### ISSUE THREAD

**Issue by nabokihms** [kubernetes/org#3756]
### GitHub Username

@nabokihms

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@enj

### Sponsor 2

@deads2k

### List of contributions to the Kubernetes project

Kubernetes:
- https://github.com/kubernetes/kubernetes/pull/89696
- https://github.com/kubernetes/kubernetes/pull/111333
- https://github.com/kubernetes/kubernetes/pull/112471
- https://github.com/kubernetes/kubernetes/pull/112501
- https://github.com/kubernetes/kubernetes/pull/112753

Enhancements:
- https://github.com/kubernetes/enhancements/issues/3325
- https://github.com/kubernetes/enhancements/issues/3331

Website:
- https://github.com/kubernetes/website/pull/31927
- https://github.com/kubernetes/website/pull/35385

Other projects:
* ingress-nginx:
    - https://github.com/kubernetes/ingress-nginx/pull/5213
    - https://github.com/kubernetes/ingress-nginx/pull/7541
    - https://github.com/kubernetes/ingress-nginx/pull/8256
    - https://github.com/kubernetes/ingress-nginx/pull/8213
    - https://github.com/kubernetes/ingress-nginx/issues/8602
* kube-state-metrics:
    -  https://github.com/kubernetes/kube-state-metrics/pull/1584
    - https://github.com/kubernetes/kube-state-metrics/pull/1814
    - https://github.com/kubernetes/kube-state-metrics/issues/1815

**Comment by deads2k** [comment]
+1

nice work

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3763  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
