### ISSUE TITLE
REQUEST: New membership for @richackard

### ISSUE THREAD

**Issue by richackard** [kubernetes/org#3759]
### GitHub Username

@richackard

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@spiffxp

### Sponsor 2

@dims

### List of contributions to the Kubernetes project

- [PRs](https://github.com/pulls?q=archived%3Afalse++author%3Arichackard+org%3Akubernetes-sigs+org%3Akubernetes+)
- SIG Project Involved: [kubernetes-sigs/kubetest2](https://github.com/kubernetes-sigs/kubetest2)

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by dims** [comment]
+1 welcome Richard!

**Comment by richackard** [comment]
Thank you folks! =)

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3763  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
