### ISSUE TITLE
REQUEST: New membership for @imnmo

### ISSUE THREAD

**Issue by imnmo** [kubernetes/org#3760]
### GitHub Username

@imnmo

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kaslin

### Sponsor 2

@chris-short

### **List of contributions to the Kubernetes project**

- PRs reviewed / authored
   - [Fix broken Charter link](https://github.com/kubernetes/community/pull/6887)
   - [Fix articles publishing too early with Front matter config](https://github.com/kubernetes/contributor-site/pull/331)
   - [Upgrade twitter-together](https://github.com/kubernetes-sigs/contributor-tweets/pull/270)
   - [Technical Lead Role Description](https://github.com/kubernetes/community/pull/6891)
   - [Add correct link for council.md](https://github.com/kubernetes/community/pull/6730)

- Issues responded/assigned to:
    - **[Creating a high-level overview section of the Kubernetes](https://github.com/kubernetes/contributor-site/issues/285)**
    - **[Fixing tweet automation](https://github.com/kubernetes-sigs/contributor-tweets/pull/271)**
   
- SIG projects I am involved with
    - Active participant in sig-contribex-comms sub-project

**Comment by chris-short** [comment]
+1

**Comment by kaslin** [comment]
+1!

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR #3785 to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign

**Comment by imnmo** [comment]
Thanks folks! Awesome timing to become  k8s member 🎉 around kubecon
