### ISSUE TITLE
REQUEST: New membership for @hackeramitkumar

### ISSUE THREAD

**Issue by hackeramitkumar** [kubernetes/org#3761]
### GitHub Username

  @hackeramitkumar

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer 

### Sponsor 2

@elmiko

### List of contributions to the Kubernetes project

**PRs reviewed / authored :**
                   https://github.com/kubernetes-sigs/cluster-api/pull/7418
                   https://github.com/kubernetes-sigs/cluster-api/pull/7377
                   
**Issues responded/assigned to:**
                  https://github.com/kubernetes-sigs/cluster-api/issues/7372
                  https://github.com/kubernetes-sigs/cluster-api/issues/5394

**SIG projects I am involved with:**
                  Active participant in `cluster-api` project.
        
I would like to be a shadow for `cluster-api v1.4.0 release cycle`.

**Comment by sbueringer** [comment]
+1 Welcome! :)

**Comment by elmiko** [comment]
+1 welcome aboard!

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR #3785 to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign
