### ISSUE TITLE
REQUEST: Migrate kubernetes-sigs/cluster-api-addon-provider-helm

### ISSUE THREAD

**Issue by Jont828** [kubernetes/org#3762]
### New repo, staging repo, or migrate existing

Migrate existing

### Is it a staging repo?

no

### Requested name for new repository

cluster-api-addon-provider-helm

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@Jont828, @fabriziopandini, @CecileRobertMichon, @jackfrancis

### Who should have write access?

@Jont828, @fabriziopandini, @CecileRobertMichon, @jackfrancis

### Who should be listed as approvers in OWNERS?

@Jont828, @fabriziopandini, @CecileRobertMichon, @jackfrancis

### Who should be listed in SECURITY_CONTACTS?

@Jont828, @fabriziopandini, @CecileRobertMichon, @jackfrancis

### What should the repo description be?

Implementation of Cluster Add-on Provider for Helm, an add-on orchestration solution for Cluster API using Helm.

### What SIG and subproject does this fall under?

This is a sub project for SIG Cluster Lifecycle

### Please provide references to appropriate approval for this new repo

- Opening as part of the next steps from the [Cluster API Add-on Orchestration Proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220712-cluster-api-addon-orchestration.md)
- Based off of the prototype from [this repository](https://github.com/Jont828/cluster-api-addon-provider-helm)

**Comment by neolit123** [comment]
discussed at the SIG meeting of 18.10.2022.
+1 from me to add this as a SIG subproject

**Comment by CecileRobertMichon** [comment]
+1 

Could we also add the Cluster API maintainers as admin/approvers?

**Comment by Jont828** [comment]
@neolit123 Just wanted to follow up on this, has there been any update on what we need to get this approved/merged?

**Comment by mrbobbytables** [comment]
@Jont828 next steps before migration would be to prepare the repo to be moved (copyright header, owners files etc)

You can read about the requirements here:
https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

**Comment by Jont828** [comment]
Sounds good, I'll get started on that!

**Comment by Jont828** [comment]
@mrbobbytables I've added the OWNERS, README, SECURITY_CONTACTS, CONTRIBUTING, and code of conduct files. I also went ahead and added the Kubernetes copyright headers too. Although there wasn't a CLA in place, @jackfrancis and I were the only ones who contributed code and we both have signed the license. Are we good to migrate the repo?

**Comment by mrbobbytables** [comment]
Repo transferred: https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm
Teams PR: #3937 
k/community PR: https://github.com/kubernetes/community/pull/7043

Teams have been added to the repo, this can be closed once the k/community PR is merged 👍

**Comment by ameukam** [comment]
We can consider this done.
/close
