### ISSUE TITLE
REQUEST: New membership for AverageMarcus

### ISSUE THREAD

**Issue by AverageMarcus** [kubernetes/org#3765]
### GitHub Username

@AverageMarcus

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@richardcase

### Sponsor 2

@njuettner

### List of contributions to the Kubernetes project

* cluster-api-provider-aws - e.g. https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3683, https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2634
* cluster-api - e.g. https://github.com/kubernetes-sigs/cluster-api/pull/7107
* cluster-api-provider-gcp - e.g. https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/616
* image-builder - e.g. https://github.com/kubernetes-sigs/image-builder/pull/956, https://github.com/kubernetes-sigs/image-builder/pull/966, https://github.com/kubernetes-sigs/image-builder/pull/993, https://github.com/kubernetes-sigs/image-builder/pull/994

I also have contributions from an old GitHub account that I no longer use - https://github.com/MarcusNoble

**Comment by njuettner** [comment]
👍🏻 
LGTM 🎉

**Comment by richardcase** [comment]
A big +1 from me.

Thank you, @AverageMarcus, for your contributions to CAPI and its providers.

**Comment by Raffo** [comment]
:+1: on my side

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR #3785 to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign
