### ISSUE TITLE
REQUEST: Create kubernetes-sigs/usage-metrics-collector

### ISSUE THREAD

**Issue by ehashman** [kubernetes/org#3769]
### New repo, staging repo, or migrate existing

New repo

### Is it a staging repo?

no

### Requested name for new repository

usage-metrics-collector

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@ehashman, @pwittrock, @KnVerey, @pmorie

### Who should have write access?

@ehashman, @pwittrock, @KnVerey, @pmorie

### Who should be listed as approvers in OWNERS?

@ehashman, @pwittrock, @KnVerey, @pmorie

### What SIG and subproject does this fall under?

sig-instrumentation

### Please provide references to appropriate approval for this new repo

Discussed at SIG Instrumentation meeting 2022-10-13 and @ehashman (me) was given the go ahead to request a repo for the new subproject.

SIG meeting minutes: https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit?pli=1#bookmark=id.a0xv1hiqjmz5

Proposal document: https://docs.google.com/document/d/12JEje-SpM78N5OhZzWg-_Ba91n6VWRm5c4l_c2U-ljw/edit#

### Additional context for request

This project is intended to fill a gap for highly granular aggregated utilization/capacity metrics at large scale, and give various Kubernetes end users a place to collaborate on shared code that may ultimately be moved in-tree or to other SIG Instrumentation projects.

**Comment by ehashman** [comment]
cc @kubernetes/sig-instrumentation-leads

**Comment by mrbobbytables** [comment]
/assign
Will try and get to it this Friday

**Comment by mrbobbytables** [comment]
1 follow up question - for adding it in sigs.yaml is this a new subproject? or should it be included under another one?

**Comment by mrbobbytables** [comment]
Repo created
Teams added in this PR: https://github.com/kubernetes/org/pull/3842
We can close this issue once teams and eventual k/community PRs are merged

**Comment by ehashman** [comment]
New subproject! Thanks @mrbobbytables!

**Comment by mrbobbytables** [comment]
All PRs merged, going to go ahead and close - thanks!

/close
