### ISSUE TITLE
REQUEST: New membership for nojnhuh

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes/org#3771]
### GitHub Username

@nojnhuh

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@CecileRobertMichon

### Sponsor 2

@sonasingh46

### List of contributions to the Kubernetes project

- Authored PRs: https://github.com/pulls?q=is%3Apr+is%3Amerged+author%3Anojnhuh+archived%3Afalse+org%3Akubernetes-sigs
- Issues I've commented on: https://github.com/issues?q=is%3Aissue+commenter%3Anojnhuh+archived%3Afalse+org%3Akubernetes-sigs

**Comment by CecileRobertMichon** [comment]
Huge +1 from my side! Excited for @nojnhuh to keep contributing to improving the managed cluster experience in Cluster API 🚀

**Comment by sonasingh46** [comment]
Huge +1 from my side too. Thanks for all the contributions so far.

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR #3785 to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign
