### ISSUE TITLE
REQUEST: New membership for danilo-gemoli

### ISSUE THREAD

**Issue by danilo-gemoli** [kubernetes/org#3772]
### GitHub Username

danilo-gemoli

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

chaodaiG

### Sponsor 2

petr-muller

### PRs:
- https://github.com/kubernetes/test-infra/pull/27739
- https://github.com/kubernetes/test-infra/pull/27355
- https://github.com/kubernetes/test-infra/pull/26731
- https://github.com/kubernetes/test-infra/pull/25968
- https://github.com/kubernetes/test-infra/pull/25832
- https://github.com/kubernetes/test-infra/pull/25780
- https://github.com/kubernetes/test-infra/pull/25702

### SIG projects:
- [kubernetes/test-infra](https://github.com/kubernetes/test-infra)

**Comment by petr-muller** [comment]
:+1:

**Comment by chaodaiG** [comment]
+1

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR #3785 to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign
