### ISSUE TITLE
REQUEST: New membership for @lobziik

### ISSUE THREAD

**Issue by lobziik** [kubernetes/org#3773]
### GitHub Username

lobziik

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@elmiko

### Sponsor 2

@lubronzhan

### List of contributions to the Kubernetes project

PRs:
- https://github.com/kubernetes/kubernetes/pull/101028
- https://github.com/kubernetes-sigs/cluster-api/pull/4148
- https://github.com/kubernetes-sigs/cloud-provider-azure/pull/716
- https://github.com/kubernetes/cloud-provider-aws/pull/522
- https://github.com/kubernetes/cloud-provider-aws/pull/499
- https://github.com/kubernetes/cloud-provider-vsphere/pull/560
- https://github.com/kubernetes/cloud-provider-vsphere/pull/626
- https://github.com/kubernetes/cloud-provider-vsphere/pull/658

**Comment by alexander-demichev** [comment]
+1 from me, thanks for all your contributions to cloud providers.

**Comment by Danil-Grigorev** [comment]
+1 from me, Denis is very talented and dedicated person, can't wait to see you being added to kube/kube-sigs

**Comment by JoelSpeed** [comment]
+1, Denis has been actively contributing in both the cloud provider and cluster api ecosystems

**Comment by nikhita** [comment]
@lobziik -- @elmiko and @JoelSpeed are only valid sponsors because they are in OWNERS files. We also require sponsors to be from different companies. Looking at their GitHub profiles, it looks like both of them work at the same employer.

Can you please find another sponsor who is not from Red Hat? Thanks!

**Comment by lubronzhan** [comment]
+1 Denis helped a lot on Cloud provider vsphere!

**Comment by lobziik** [comment]
@nikhita, updated :) Could you please take a look again? Thanks!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3814  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
