### ISSUE TITLE
REQUEST: New membership for luthermonson

### ISSUE THREAD

**Issue by luthermonson** [kubernetes/org#3774]
### GitHub Username

luthermonson

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

jayunit100

### Sponsor 2

reylejano

### List of contributions to the Kubernetes project

Been around the kube space for almost 5yrs and I spend my time today in sig-windows and the individual CAPI providers. My sponsors are one of the leads of sig-windows at vmware and a previous co-worker from rancher, I am employed by spectrocloud.

https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3Aluthermonson+
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pulls?q=is%3Apr+author%3Aluthermonson+
https://github.com/kubernetes-sigs/sig-windows-dev-tools/pulls?q=is%3Apr+author%3Aluthermonson+

I also previously applied #2779 and was denied due to not having enough PRs on kube repos and as you can see, I'm hoping i've now met that requirement. The previous issue will show my contributions on other kube projets and shows my depth of knowledge about the kube eco-system as I've previously worked on the rancher multi-cluster manager and both rke1 and rke2 distros.

**Comment by luthermonson** [comment]
@reylejano @jayunit100

**Comment by reylejano** [comment]
+1 from me

**Comment by jayunit100** [comment]
/lgtm
 Luther has been contributing to the windows effort for quite a while and consulted on many upstream windows issues ... Including the sig windows dev tools project and testing csi providers for windows at the bleeding edge... making our lives much easier.

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/3785 to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign
