### ISSUE TITLE
REQUEST: New membership for @qnetter

### ISSUE THREAD

**Issue by qnetter** [kubernetes/org#3775]
### GitHub Username

@qnetter

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mrbobbytables

### Sponsor 2

@dims

### List of contributions to the Kubernetes project

- active in SIG-ContribEx
   - contributed bingo cards for Valencia and Detroit
   - Shadowed comms and tweeted for Detroit 
- submitted conformance for multiple SUSE pre-Rancher releases
- Worked on early SAFE WG (later SIG-Security) documents

(Honestly not sure how the subprojects check box applies but I hope someone will clarify...)

**Comment by palnabarun** [comment]
+1

**Comment by mrbobbytables** [comment]
+1 from me :)
Thanks for helping with the summit!

/assign

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3814  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
