### ISSUE TITLE
REQUEST: New membership for Skarlso

### ISSUE THREAD

**Issue by Skarlso** [kubernetes/org#3777]
### GitHub Username

@Skarlso

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@richardcase

### Sponsor 2

@Ankitasw

### List of contributions to the Kubernetes project

I don't have any PRs in the Kubernetes organization; however, I'm an active member in the [CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws/) and [CAPI](https://github.com/kubernetes-sigs/cluster-api) projects.
This requires, in some instances, access to image pushes, image changes or working in the Kubernetes organization itself.

**Comment by richardcase** [comment]
A big +1 from me

@Skarlso has just become a maintainer of Cluster API provider AWS (CAPA) and as such needs to join the kubernetes ORG to accomplish certain tasks.

**Comment by Ankitasw** [comment]
+1 from me as well.

**Comment by Skarlso** [comment]
Thank you, both! :) Really appreciate it. :)

**Comment by Ankitasw** [comment]
cc @palnabarun

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/3785 to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign

**Comment by Skarlso** [comment]
Thank you very much! :)))))) 👍 🎉
