### ISSUE TITLE
REQUEST: New membership for kgolab

### ISSUE THREAD

**Issue by kgolab** [kubernetes/org#3779]
### GitHub Username

@kgolab

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

jbartosik

### Sponsor 2

josephburnett

### List of contributions to the Kubernetes project

I sometimes contribute to kubernetes/autoscaler repo.

Last 2 PRs:
- liveness probe for addon-resizer: https://github.com/kubernetes/autoscaler/pull/5234
- VPA API enhancement: https://github.com/kubernetes/autoscaler/pull/4560 and https://github.com/kubernetes/autoscaler/pull/4566

Some non-trivial reviews:
- https://github.com/kubernetes/autoscaler/pull/4329
- https://github.com/kubernetes/autoscaler/pull/4131
- https://github.com/kubernetes/autoscaler/pull/3914

**Comment by jbartosik** [comment]
+1

**Comment by josephburnett** [comment]
+1. Karol had a long history of contributing to Kubernetes autoscaling, in particular VPA. He remains an active contributor and I fully support his membership.

I currently work for GitLab.

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/3785 to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign

**Comment by kgolab** [comment]
Thanks!
