### ISSUE TITLE
REQUEST: New membership for Vincent056

### ISSUE THREAD

**Issue by Vincent056** [kubernetes/org#3783]
### GitHub Username

@Vincent056

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jhrozek

### Sponsor 2

@saschagrunert

### List of contributions to the Kubernetes project

I have authored a couple of PRs in https://github.com/kubernetes-sigs/security-profiles-operator:
https://github.com/kubernetes-sigs/security-profiles-operator/pull/1236
https://github.com/kubernetes-sigs/security-profiles-operator/pull/1216
https://github.com/kubernetes-sigs/security-profiles-operator/pull/1178
https://github.com/kubernetes-sigs/security-profiles-operator/pull/854

**Comment by saschagrunert** [comment]
+1

**Comment by jhrozek** [comment]
+1

**Comment by pjbgf** [comment]
+1

**Comment by palnabarun** [comment]
Thank you for all your contributions so far :)

I've created PR https://github.com/kubernetes/org/pull/3785 to add you to the requested Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉

/assign
