### ISSUE TITLE
REQUEST: New membership for saltbo

### ISSUE THREAD

**Issue by saltbo** [kubernetes/org#3788]
### GitHub Username

@saltbo

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims 

### Sponsor 2

@pacoxu

### List of contributions to the Kubernetes project

PRs authored
https://github.com/kubernetes/kubernetes/pulls?q=author%3Asaltbo+
https://github.com/kubernetes/utils/pull/263
https://github.com/kubernetes/minikube/pull/8787

**Comment by pacoxu** [comment]
+1

Thanks for your ci failure fixes and cleanups.

Hope you can make more contributions to Kuberentes community.

**Comment by nikhita** [comment]
@saltbo can you ping Tim again or ask another sponsor to +1 here?

**Comment by saltbo** [comment]
Thank you for reminding me, I will ask another sponsor later

**Comment by dims** [comment]
+1 from me.

**Comment by nikhita** [comment]
/assign

@saltbo Thank you for all your contributions so far :)

I've created PR #4001 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
