### ISSUE TITLE
REQUEST: New membership for weilaaa

### ISSUE THREAD

**Issue by weilaaa** [kubernetes/org#3789]
### GitHub Username

@weilaaa

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@lavalamp

### Sponsor 2

@wzshiming

### List of contributions to the Kubernetes project

Here I hope to do more interesting and meaningful things.

- PRs authored
[kubernetes/kubernetes PRs](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+weilaaa+author%3Aweilaaa)
[kubernetes/gengo PR](https://github.com/kubernetes/gengo/pull/231#event-7314496647)
[kubernetes-sigs/controller-runtime PR](https://github.com/kubernetes-sigs/controller-runtime/pull/1493)

- Issues responded to
[kubernetes/kubernetes issues](https://github.com/kubernetes/kubernetes/issues/created_by/weilaaa)
[kubernetes-sigs/controller-runtime issues](https://github.com/kubernetes-sigs/controller-runtime/issues?q=+is%3Aissue+author%3Aweilaaa+)
[kubernetes-sigs/hierarchical-namespaces issues](https://github.com/kubernetes-sigs/hierarchical-namespaces/issues?q=is%3Aissue+author%3Aweilaaa+)

- SIG projects iam involved with
kubernetes-sigs/controller-runtime
kubernetes-sigs/hierarchical-namespaces

**Comment by wzshiming** [comment]
+1 🎉

**Comment by weilaaa** [comment]
It seems "assign" did not tigger ci robot to add label, so I try to assign again.

/assign @mrbobbytables

**Comment by mrbobbytables** [comment]
Sorry about missing that before^^;; no idea how the assign didn't actually assign me.

I've created PR #3849  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
