### ISSUE TITLE
REQUEST: Migrate https://github.com/mukho-akash/azure-cosi-driver

### ISSUE THREAD

**Issue by mukhoakash** [kubernetes/org#3790]
### New repo, staging repo, or migrate existing

Migrate existing

### Is it a staging repo?

no

### Requested name for new repository

azure-cosi-driver

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

mukhoakash, aarongalang, edreed

### Who should have write access?

mukhoakash, aarongalang, edreed

### Who should be listed as approvers in OWNERS?

mukhoakash, aarongalang, edreed

### Who should be listed in SECURITY_CONTACTS?

mukhoakash, aarongalang, edreed

### What should the repo description be?

This driver allows Kubernetes to access Azure blob storage using the Container Object Storage Interface (COSI).

### What SIG and subproject does this fall under?

provider-azure

### Please provide references to appropriate approval for this new repo

Kindly refer to COSI community meeting demo for the azure cosi driver: [Demo](https://kubernetes.slack.com/files/U67QQ0A2Y/F0464LW0MMJ/kubernetes_sig_storage_-_object_bucket_api_review_meeting_2022-10-06.mp4 )

https://github.com/kubernetes/org/issues/3790#tasklist-block-e027cee0-b924-4ede-a962-f5fbd2bc8547

**Comment by mrbobbytables** [comment]
/assign @jsafrane @msau42
for sign off

**Comment by mukhoakash** [comment]
As per my discussion with @xing-yang  and @wlan0,  we had decided to migrate this repo under the Azure organization. This repo is now available at https://github.com/Azure/azure-cosi-driver
