### ISSUE TITLE
REQUEST: New membership for gottwald

### ISSUE THREAD

**Issue by gottwald** [kubernetes/org#3792]
### GitHub Username

gottwald

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@MorrisLaw

### Sponsor 2

@cpanato

### List of contributions to the Kubernetes project

- PRs authored
  - [PR #404(cluster-api-do): Add volumes field to DOMachine status](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/404)
  - [PR #403(cluster-api-do): Switch to non-preformatted etcd DOBS volumes](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/403)
  - [PR #232(cluster-api-do): Add managed DNS record support for API endpoint](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/232)
  - [PR #228(cluster-api-do): Add external storage support for etcd](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/228)
  - [PR #7351(cluster-api): Make KCP diskSetup field mutable.](https://github.com/kubernetes-sigs/cluster-api/pull/7351)
  - [PR #4175(cluster-api): Fix nil pointer dereference.](https://github.com/kubernetes-sigs/cluster-api/pull/4175)
  - [PR #225(k/k): Add test for YAMLPrinter.](https://github.com/kubernetes/kubernetes/pull/226)
  - [PR #197(k/k): Add unit test for cloudcfg.LoadAuthInfo.](https://github.com/kubernetes/kubernetes/pull/197)
  - [PR #184(k/k): Fix guestbook example json syntax error.](https://github.com/kubernetes/kubernetes/pull/184)
- PRs reviewed
  - [PR #245(cluster-api-do): Move dns propagation helpers to its own packages](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/245)
  - [PR #242(cluster-api-do): Omitempty ControlPlaneDNS](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/242)
- Issues created
  - [Issue #231(cluster-api-do): Deletion and reconciliation of KAS LB breaks cluster](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/issues/231)
- SIG projects I am involved with
  - sig/cluster-api

**Comment by cpanato** [comment]
string +1 and also recommend to be a member of the kubernetes-sigs as well

**Comment by MorrisLaw** [comment]
+1 from me, keep up the great work!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3814  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
