### ISSUE TITLE
REQUEST: New membership for @lentzi90

### ISSUE THREAD

**Issue by lentzi90** [kubernetes/org#3793]
### GitHub Username

@lentzi90

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tobiasgiese

### Sponsor 2

@sbueringer

### List of contributions to the Kubernetes project

[PRs reviewed / authored](https://github.com/pulls?q=is%3Aissue+author%3Alentzi90+archived%3Afalse+org%3Akubernetes-sigs+is%3Aclosed+):
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1364
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1361
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1354
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1284
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1239
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1199
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1185
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1183
- https://github.com/kubernetes-sigs/cluster-api/pull/6395

Issues [authored](https://github.com/issues?q=is%3Aissue+author%3Alentzi90+archived%3Afalse+org%3Akubernetes-sigs+is%3Aclosed) / [commented](https://github.com/issues?q=is%3Aissue+commenter%3A%40me+archived%3Afalse+org%3Akubernetes-sigs+is%3Aclosed+):
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1280
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1230
- https://github.com/kubernetes-sigs/cluster-api/issues/6285
- https://github.com/kubernetes-sigs/cluster-api/issues/6055

SIG projects I'm involved with:
- Mainly [cluster-api-provider-openstack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack)
- [cluster-api](https://github.com/kubernetes-sigs/cluster-api)

**Comment by sbueringer** [comment]
+1 welcome:)

**Comment by tobiasgiese** [comment]
+1 from me 👍🏻 
Thanks for all your great contributions and participation in the CAPO office hours :)

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3814  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
