### ISSUE TITLE
REQUEST: New membership for @aimuz

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/org#3794]
### GitHub Username

@aimuz

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu

### Sponsor 2

@liggitt

or @aojea 

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pulls/aimuz
 at least 5 merged pr.

- https://github.com/kubernetes/kubernetes/pull/112693
- https://github.com/kubernetes/kubernetes/pull/112691
- https://github.com/kubernetes/kubernetes/pull/106485
- https://github.com/kubernetes/kubernetes/pull/112696
-

**Comment by pacoxu** [comment]
+1 
Thanks for your contributions.

**Comment by aojea** [comment]
+1

**Comment by liggitt** [comment]
+1

**Comment by mrbobbytables** [comment]
@aimuz can you confirm your org membership request? we don't generally have requests where the author is different from the requested user.

**Comment by aimuz** [comment]
Yes, I did. @mrbobbytables 

I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
  I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
  I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
  I am actively contributing to 1 or more Kubernetes subprojects
  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
  I have verified that my sponsors are from different member companies
  I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
  OPTIONAL: I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

**Comment by mrbobbytables** [comment]
Thanks!
/assign

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3849  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
