### ISSUE TITLE
REQUEST: New membership for @mtougeron

### ISSUE THREAD

**Issue by mtougeron** [kubernetes/org#3795]
### GitHub Username

@mtougeron

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@CecileRobertMichon

### Sponsor 2

@jrsapi

### List of contributions to the Kubernetes project

Sponsor 3: @jackfrancis

- Authored PRs in kubernetes-sigs: https://github.com/pulls?q=is%3Apr+is%3Amerged+author%3Amtougeron+archived%3Afalse+org%3Akubernetes-sigs

- Issues & PRs (non-authored) participating in kubernetes-sigs: https://github.com/issues?q=commenter%3Amtougeron+archived%3Afalse+org%3Akubernetes-sigs+-author%3Amtougeron

- Authored PR in kubernetes https://github.com/pulls?q=is%3Apr+is%3Amerged+author%3Amtougeron+archived%3Afalse+org%3Akubernetes

- Participating in weekly cluster-api & cluster-api-provider-azure community meetings

**Comment by CecileRobertMichon** [comment]
big +1 from my side! Thanks for all your contributions so far @mtougeron!

**Comment by jackfrancis** [comment]
+1

Thank you @mtougeron and welcome!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3814  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by mtougeron** [comment]
Thank you! I appreciate it and look forward to continuing to working with everyone!
