### ISSUE TITLE
REQUEST: New membership for @AverageMarcus

### ISSUE THREAD

**Issue by AverageMarcus** [kubernetes/org#3798]
### GitHub Username

@AverageMarcus

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@richardcase

### Sponsor 2

@Skarlso

### List of contributions to the Kubernetes project

Note: Membership required as a reviewer for the Kubernetes SIGs CAPA project. Contributions below related to that.

* cluster-api-provider-aws - e.g. https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3683, https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2634
* cluster-api - e.g. https://github.com/kubernetes-sigs/cluster-api/pull/7107
* cluster-api-provider-gcp - e.g. https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/616
* image-builder - e.g. https://github.com/kubernetes-sigs/image-builder/pull/956, https://github.com/kubernetes-sigs/image-builder/pull/966, https://github.com/kubernetes-sigs/image-builder/pull/993, https://github.com/kubernetes-sigs/image-builder/pull/994

**Comment by richardcase** [comment]
+1 from my side.

@AverageMarcus has recently moved to be a reviewer of the Kubernetes SIG Cluster API Provider AWS project. He will need to be able to review changes to the job definitions for the project which requires kubernetes org membership.

Thanks for all your help @AverageMarcus 🎉

**Comment by Skarlso** [comment]
+1 from me as well! :) Welcome to the family! :)) 🎉

**Comment by AverageMarcus** [comment]
Closing in favour of https://github.com/kubernetes/org/pull/3799 (didn't realise this was allowed when already a member of another org)
