### ISSUE TITLE
Create new github.com/kubernetes/node-api repo

### ISSUE THREAD

**Issue by tallclair** [kubernetes/org#38]
### New Repo, or migrate existing
new repository

### Requested name for new repository
node-api

### Which Organization should it reside
kubernetes

### Who should be provided access to this repository
@tallclair
@dchen1107 
@derekwaynecarr 

### Approvals
Presented to sig-architecture, agreed to make the new API a CRD
https://github.com/kubernetes/community/blob/master/keps/sig-node/0014-runtime-class.md

Based on discussion of CRDs in core components, the new API should be a separate (staging) repo:
https://groups.google.com/forum/#!msg/kubernetes-sig-storage-wg-csi/x5CchIP9qiI/00Trm4g1CwAJ

/cc @thockin 

### Additional context for request
Will provide the node.k8s.io API group (& generated client) for https://github.com/kubernetes/community/blob/master/keps/sig-node/0014-runtime-class.md

**Comment by cblecker** [comment]
@tallclair So your intention here is to have another staging repo that the publishing bot can push to?

**Comment by tallclair** [comment]
Right - I'm adding a new `node.k8s.io` API group (initially for supporting [RuntimeClass](https://github.com/kubernetes/community/blob/master/keps/sig-node/0014-runtime-class.md)), and this repo would house it. It needs to be pushed to from staging since it depends on api machinery, and other internal components in turn depend on the node-api (see linked conversation thread above).

Proposed implementation is in https://github.com/kubernetes/kubernetes/pull/67791.

We should confirm that this is the pattern we want new APIs to follow though. Commented on https://groups.google.com/d/msg/kubernetes-sig-storage-wg-csi/x5CchIP9qiI/cqkt2oH3DQAJ to follow up.

**Comment by cblecker** [comment]
@tallclair any update on this?

**Comment by tallclair** [comment]
I'd still like to add this in 1.13. What is the dependency ordering between creating the repo & merging https://github.com/kubernetes/kubernetes/pull/67791? I.e. which should be approved first?

**Comment by cblecker** [comment]
no specific order. they just both need to be done, if this is to be a staging repo. they key is approval from sig-arch on the name

**Comment by bgrant0607** [comment]
Naming the repo after the API group makes sense to me. 

API approvers @thockin approved and @liggitt didn't object on https://github.com/kubernetes/kubernetes/pull/67791, so I'm going to approve this.

Repos can also be renamed, so this doesn't have to be permanent.

**Comment by cblecker** [comment]
Repo is created. Ready for the publishing bot configs (https://github.com/kubernetes/publishing-bot)

cc: @sttts @nikhita

**Comment by cblecker** [comment]
Also @tallclair, can you add the repo to sigs.yaml?

**Comment by nikhita** [comment]
> Repo is created. Ready for the publishing bot configs

I have created https://github.com/kubernetes/publishing-bot/pull/135 for the publishing-bot so that all processes related to creating the repo are in place. But I've placed a hold on it because it shouldn't get merged until https://github.com/kubernetes/kubernetes/pull/67791 gets merged in k/k.

Also, for the record, https://github.com/kubernetes/test-infra/pull/10194 is the PR updating branch-protection for https://github.com/kubernetes/node-api (thanks @cblecker for taking care of it!)

**Comment by tallclair** [comment]
https://github.com/kubernetes/kubernetes/pull/67791 finally merged! :tada: 

Aside from https://github.com/kubernetes/publishing-bot/pull/135, is there anything else that needs to be done here, or should I close this issue?

**Comment by nikhita** [comment]
> Aside from kubernetes/publishing-bot#135,

Cancelled the hold on that. The repo should get populated once the bot is redeployed.

> is there anything else that needs to be done here, or should I close this issue?

I think the only thing remaining is add the new repo to `sigs.yaml` in k/community. https://github.com/kubernetes/community/pull/3033 does that already so maybe we should just wait for that PR to get merged first (it will automatically close the issue).

**Comment by nikhita** [comment]
Just realized https://github.com/kubernetes/node-api does not have a repo description.
