### ISSUE TITLE
REQUEST: New membership for @Richabanker

### ISSUE THREAD

**Issue by Richabanker** [kubernetes/org#3801]
### GitHub Username

@Richabanker

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@logicalhan

### Sponsor 2

@ehashman

### List of contributions to the Kubernetes project

PRs:
- https://github.com/kubernetes/kubernetes/pull/113057
- https://github.com/kubernetes/kubernetes/pull/113030
- https://github.com/kubernetes/kubernetes/pull/113026
- https://github.com/kubernetes/kubernetes/pull/112846
- https://github.com/kubernetes/kubernetes/pull/113340 (pending review)

**Comment by logicalhan** [comment]
/lgtm

Thanks @Richabanker for all the contributions!!

**Comment by logicalhan** [comment]
/lgtm

Thanks @Richabanker for all the contributions!!

**Comment by Richabanker** [comment]
Thank YOU @logicalhan for mentoring me and providing me with the great opportunities! Look forward to further collaborations  :)

**Comment by ehashman** [comment]
👍 glad to see @Richabanker on board and hope to see more great contributions!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3814  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by Richabanker** [comment]
Thank you so much! 😄
