### ISSUE TITLE
REQUEST: New membership for @wondywang

### ISSUE THREAD

**Issue by wondywang** [kubernetes/org#3803]
### GitHub Username

@wondywang

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Fei-Guo

### Sponsor 2

@christopherhein

### List of contributions to the Kubernetes project

1. https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/323
2. https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/313
3. https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/310
4. https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/307
5. https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/298
6. https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/318

**Comment by Fei-Guo** [comment]
+1, thanks for your contributions, wondy.

**Comment by christopherhein** [comment]
+1 thanks for everything!
