### ISSUE TITLE
REQUEST: New membership for @nawazkh

### ISSUE THREAD

**Issue by nawazkh** [kubernetes/org#3806]
### GitHub Username

@nawazkh

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@CecileRobertMichon

### Sponsor 2

@ykakarap

### List of contributions to the Kubernetes project

- PRs authored: 
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2568
  - https://github.com/kubernetes/test-infra/pull/27165
  - https://github.com/kubernetes/test-infra/pull/27130
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2447
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2424
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2409
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2404
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2075
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2060
- Sig Project I am involved with: 
  - [Kubernetes Cluster API Provider Azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure)

**Comment by CecileRobertMichon** [comment]
+1

Thank you @nawazkh for all your contributions so far and for volunteering to help with the CAPI release team!!

**Comment by ykakarap** [comment]
+1.

Thank you @nawazkh for volunteering to be part of the CAPI release team. Looking forward to working together 🚀

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3814  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
