### ISSUE TITLE
REQUEST: New membership for tomassedovic

### ISSUE THREAD

**Issue by tomassedovic** [kubernetes/org#381]
### GitHub Username

@tomassedovic

### Organization you are requesting membership in

@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @flaper87 
- @chaosaffe 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/172
- Issues responded to
- SIG projects I am involved with
cluster-api-provider-openstack

**Comment by chaosaffe** [comment]
+1 from me!

Thanks @tomassedovic for your contributions 🎉

**Comment by spiffxp** [comment]
I've opened #386, once that merges you'll be sent an invite to the org you requested.  Welcome aboard!

/pony party
