### ISSUE TITLE
REQUEST: New membership for @chengxiangdong

### ISSUE THREAD

**Issue by chengxiangdong** [kubernetes/org#3810]
### GitHub Username

@chengxiangdong

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@RainbowMango

### Sponsor 2

@windsonsea

##### PR created: 
1. https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/pull/119
2. https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/pull/115
3. https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/pull/118
4. https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/pull/113
5. https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/pull/114

##### PR created: 

1. https://github.com/kubernetes/website/pull/37663
2. https://github.com/kubernetes/website/pull/36626
3. https://github.com/kubernetes/website/pull/37643
4. https://github.com/kubernetes/website/pull/37631
5. https://github.com/kubernetes/website/pull/37622
6. https://github.com/kubernetes/website/pull/37662
7. https://github.com/kubernetes/website/pull/37664
8. https://github.com/kubernetes/website/pull/37582

##### Pull Requests Reviewed:

1. https://github.com/kubernetes/website/pull/37633
2. https://github.com/kubernetes/website/pull/37406

**Comment by windsonsea** [comment]
+1

Look forward to your more contributions.

**Comment by RainbowMango** [comment]
+1

Hello Michael, nice to meet you here.

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3814  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
