### ISSUE TITLE
Integration of SemaphoreCI to kubernetes/kompose

### ISSUE THREAD

**Issue by cdrage** [kubernetes/org#382]
### Organization or repository
https://github.com/kubernetes/kompose

### Name of integration
SemaphoreCI

### Link to integration website
https://semaphoreci.com/

### Describe what is attempting to be accomplished
Essentially, we've been using SemaphoreCI for the past two years up until last November 2018. I believe when they "upgraded" to SemaphoreCI 2.0 they re-created their GitHub service token and thus SemaphoreCI was removed from our repo (https://github.com/kubernetes/kompose)

I would like to have SemaphoreCI Classic (not 2.0) re-enabled again so we're able to continue to do our integration tests against Kubernetes.

### Additional context for request
The use-case is to run our integration tests. At the moment we're only running unit tests and command-line tests.

Many thanks!

**Comment by cblecker** [comment]
@cdrage Is there a SemaphoreCI Classic organization for this?

**Comment by cdrage** [comment]
@cblecker Just saw in my e-mail that it got approved, thank you Chris!
