### ISSUE TITLE
new staging repo: k8s.io/dynamic-resource-allocation

### ISSUE THREAD

**Issue by pohly** [kubernetes/org#3821]
From https://groups.google.com/g/kubernetes-sig-architecture/c/DkKQyuUrj9Y:

> The dynamic resource allocation implementation is under review for
> inclusion into Kubernetes 1.26 as new alpha feature. The full set of
> commits is pending in
> https://github.com/kubernetes/kubernetes/pull/111023.
> 
> It contains code that is used in-tree and out-of-tree. Initially we
> thought that we would publish such helper code later, but NVIDIA already
> started using it in their prototype of a dynamic resource allocation
> driver, therefore it makes sense to publish it properly already with
> Kubernetes 1.26.
> 
> Therefore I would like to request a new staging repo
> "k8s.io/dynamic-resource-allocation" where we will publish these helper
> packages. In some earlier revision I had the code under
> "k8s.io/component-helpers", but it changed the dependencies of that
> module. IMHO a separate staging repo is cleaner. It should be owned by
> SIG Node, with the set of people working on dynamic resource allocation
> as reviewers. SIG Node leads would be approvers plus Kevin and myself.

There have been no comments there, so I suppose there are no objections and we can proceed.

/cc @thockin (in case that explicit approval is needed)

**Comment by klueska** [comment]
/assign @derekwaynecarr

This needs sig-node-leads approval as per this slack conversation:
https://kubernetes.slack.com/archives/C01672LSZL0/p1667751787905519

**Comment by alculquicondor** [comment]
I think this needs resolution on https://github.com/kubernetes/kubernetes/pull/111023#issuecomment-1309058680

**Comment by mrbobbytables** [comment]
repo created: https://github.com/kubernetes/dynamic-resource-allocation
PR for branch protection: https://github.com/kubernetes/test-infra/pull/27980
[Final step](https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#staging-repositories) will be completed once PR in k/k is merged.

/assign

**Comment by mrbobbytables** [comment]
I think everything is done as far as getting the repo squared away.

The only administrative action left is to add it to [k/community listed under a subproject](https://github.com/kubernetes/community/tree/master/sig-node#subprojects)

Would it be a new one or should it be listed under one of the others?

**Comment by klueska** [comment]
Let me ask what people prefer in the sig-node meeting today.

**Comment by klueska** [comment]
We discussed this in the sig-node meeting on Tuesday.

The consensus was for me to create a new subproject called `resource-management` which will absorb the existing [`noderesourcetopology-api`](https://github.com/kubernetes/community/tree/master/sig-node#noderesourcetopology-api) subproject and include both this new staging repo and the repo that will result from my recent [request](https://github.com/kubernetes/org/issues/3837) for a `kubernetes-sigs/dra-example-driver` repo.

The first step is to open a PR against https://github.com/kubernetes/community to update the README with the new organization. What are the following steps? It looks like maybe an update to https://github.com/kubernetes/community/blob/master/sigs.yaml as well?

**Comment by klueska** [comment]
PR to add the above:
https://github.com/kubernetes/community/pull/6970

**Comment by klueska** [comment]
With the merging of https://github.com/kubernetes/community/pull/6970, I assume this issue can now be closed?

**Comment by mrbobbytables** [comment]
yup!

/close
