### ISSUE TITLE
REQUEST: New membership for <yanghesong>

### ISSUE THREAD

**Issue by yanghesong** [kubernetes/org#3826]
### GitHub Username

@yanghesong

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@pacoxu

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/109660
https://github.com/kubernetes/kubernetes/pull/112438
https://github.com/kubernetes/kubernetes/pull/112525
https://github.com/kubernetes/kubernetes/pull/109412
https://github.com/kubernetes/kubernetes/pull/109347
https://github.com/kubernetes/kubernetes/pull/109103
https://github.com/kubernetes/kubernetes/pull/109012
https://github.com/kubernetes/kubernetes/pull/107426
https://github.com/kubernetes/kubernetes/pull/107664
https://github.com/kubernetes/kubernetes/pull/107526
https://github.com/kubernetes/kubernetes/pull/107309
https://github.com/kubernetes/kubernetes/pull/107594
https://github.com/kubernetes/kubernetes/pull/107096

- SIG projects I am involved with
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/245

**Comment by pacoxu** [comment]
+1 
Thanks for your work on sig-node and hope you will contribute more in the future.

**Comment by dims** [comment]
+1 from me as well @yanghesong

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3849  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
