### ISSUE TITLE
REQUEST: New membership for rexagod

### ISSUE THREAD

**Issue by rexagod** [kubernetes/org#3830]
### GitHub Username

@rexagod

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@logicalhan

### Sponsor 2

@dgrisonnet

### List of contributions to the Kubernetes project

- PRs authored: https://github.com/kubernetes/kube-state-metrics/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Arexagod
- PRs reviewed: https://github.com/kubernetes/kube-state-metrics/pulls?q=is%3Apr+sort%3Aupdated-desc+reviewed-by%3Arexagod+commenter%3Arexagod+-author%3Arexagod
- Issues responded to: https://github.com/kubernetes/kube-state-metrics/issues?q=is%3Aissue+sort%3Aupdated-desc+commenter%3Arexagod
- SIG projects I'm actively involved with: https://github.com/kubernetes/kube-state-metrics

**Comment by logicalhan** [comment]
/lgtm

Thanks for all the contributions!

**Comment by dgrisonnet** [comment]
/lgtm

Thank you for all the amazing effort you've been putting!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3849  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by rexagod** [comment]
Hello @mrbobbytables, it's been a while since that was merged, but I haven't received any invite. Not sure what went wrong here.
