### ISSUE TITLE
REQUEST: New membership for sunjayBhatia

### ISSUE THREAD

**Issue by sunjayBhatia** [kubernetes/org#3831]
### GitHub Username

@sunjayBhatia

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@robscott

### Sponsor 2

@youngnick

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/gateway-api/pulls/sunjayBhatia
- https://github.com/kubernetes-sigs/gateway-api/issues/created_by/sunjayBhatia
- https://github.com/kubernetes-sigs/gateway-api/issues/assigned/sunjayBhatia
- https://github.com/kubernetes-sigs/ingress-controller-conformance/pulls/sunjayBhatia

**Comment by robscott** [comment]
+1

Thanks for all the contributions @sunjayBhatia!

**Comment by youngnick** [comment]
+1 from me too. Thanks @sunjayBhatia!

**Comment by sunjayBhatia** [comment]
Thanks @robscott @youngnick!
