### ISSUE TITLE
REQUEST: New membership for Garrybest

### ISSUE THREAD

**Issue by Garrybest** [kubernetes/org#3832]
### GitHub Username

@Garrybest

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@fpetkovski

### Sponsor 2

@marquiz

### List of contributions to the Kubernetes project

- PRs authored: https://github.com/pulls?q=archived%3Afalse+is%3Apr+author%3AGarrybest+org%3Akubernetes-sigs+org%3Akubernetes+
- Issues created: https://github.com/issues?q=archived%3Afalse+is%3Aissue+author%3AGarrybest+org%3Akubernetes-sigs+org%3Akubernetes+
- Projects I'm involed in: kubernetes, kube-state-metrics, descheduler, scheduler-plugins, node-feature-discovery, website

**Comment by Garrybest** [comment]
Hi fellows, would you like to sponsor me😊? @fpetkovski @marquiz

**Comment by fpetkovski** [comment]
Thank you for all of your contributions to kube-state-metrics 🎉

@Garrybest has my support 💯 .

**Comment by marquiz** [comment]
@Garrybest good work on https://github.com/kubernetes-sigs/node-feature-discovery/pull/842
+1
