### ISSUE TITLE
REQUEST: New membership for hj-johannes-lee

### ISSUE THREAD

**Issue by hj-johannes-lee** [kubernetes/org#3834]
### GitHub Username

@hj-johannes-lee

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@seokho-son

### Sponsor 2

@gochist

### List of contributions to the Kubernetes project

- PRs authored
 [https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ahj-johannes-lee+is%3Aclosed+](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ahj-johannes-lee+is%3Aclosed+)
- Issues responded to
- SIG projects I am involved with
    kubernetes/sig-docs

**Comment by seokho-son** [comment]
Hi @hj-johannes-lee 

> PRs authored
> https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3A%40me+is%3Aclosed

seems not appropriate link. Could you change it to 
https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ahj-johannes-lee+is%3Aclosed+

**Comment by hj-johannes-lee** [comment]
@seokho-son Sorry for being so careless.! :( I changed!

**Comment by seokho-son** [comment]
+1

@hj-johannes-lee is active and responsive contributor especially for SIG-Docs Korean localization contribution !
Thank you for the contribution ! :)

**Comment by gochist** [comment]
+1

 Thank you for the contribution!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3862   to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
