### ISSUE TITLE
REQUEST: Create kubernetes-sigs/minikube-gui

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/org#3836]
### New repo, staging repo, or migrate existing

New respository

### Is it a staging repo?

no

### Requested name for new repository

minikube-gui

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

spowelljr, medyagh

### Who should have write access?

spowelljr, medyagh

### Who should be listed as approvers in OWNERS?

spowelljr, medyagh

### Who should be listed in SECURITY_CONTACTS?

spowelljr, medyagh

### What should the repo description be?

Use minikube from a GUI

### What SIG and subproject does this fall under?

SIG Cluster Lifecycle

### Please provide references to appropriate approval for this new repo

https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/zj1w6TO2pyk

Will seek approval on November 15 during office hours

**Comment by spowelljr** [comment]
cc @kubernetes/sig-cluster-lifecycle-leads

**Comment by neolit123** [comment]
i am not sure i will be able to join the sig call tomorrow, but you can add it to the agenda and discuss it. please relay this fredback if i am not around.

my take is that unless you want a strictly disjointed release process and a separate issue tracker of a gui, then the gui should probably just live in a go module subfolder in the main project repo.

my vote is +0, but i can see the benefits of a separate repo. we should list this under the minikube subproject and not as a separate subproject.

**Comment by neolit123** [comment]
@fabriziopandini @vincepri 

@justinsb and me discussed this topic during the sig meeting and we do not object to the separate repository.
if you object, please leave a comment.

thanks

one remaining question was the source code licensing, which the minikube maintainers should discuss with contribex.

**Comment by fabriziopandini** [comment]
+1 from my side

**Comment by mrbobbytables** [comment]
repo created: https://github.com/kubernetes-sigs/minikube-gui
teams PR: https://github.com/kubernetes/org/pull/3851
k/community PR: https://github.com/kubernetes/community/pull/6983

I'll add the teams with repo permissions once the PR has been merged 👍

**Comment by mrbobbytables** [comment]
Teams added, all PRs merged - going to go ahead and close this out. Thanks!

/close

**Comment by spowelljr** [comment]
Thanks @mrbobbytables!
