### ISSUE TITLE
REQUEST: Create kubernetes-sigs/dra-example-driver

### ISSUE THREAD

**Issue by klueska** [kubernetes/org#3837]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

dra-example-driver

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

klueska,pohly

### Who should have write access?

byako,bart0sh

### Who should be listed as approvers in OWNERS?

klueska,pohly,byako,bart0sh

### Who should be listed in SECURITY_CONTACTS?

klueska,pohly

### What should the repo description be?

Dynamic Resource Allocation (DRA) is a generalization of the Persistent Volumes API for generic resources. It puts resource scheduling directly in the hands of 3rd-party developers -- moving away from the limited "countable" interface for requesting access to resources  (e.g. "nvidia.com/gpu: 2") to provide an API more akin to that of persistent volumes.

This repo provides an example DRA driver that developers can fork and modify to get them started writing their own. 

### What SIG and subproject does this fall under?

sig: node, subproject: resource-management

### Please provide references to appropriate approval for this new repo

* Dynamic Resource Allocation (DRA) was recently [merged](https://github.com/kubernetes/kubernetes/pull/111023) as an alpha feature for 1.26.
* It is sponsored by sig-node in this [KEP](https://github.com/kubernetes/enhancements/pull/3064/) and this [tracking issue](https://github.com/kubernetes/enhancements/issues/3063).
* I (@klueska) am a [`sig-node-approver`](https://github.com/kubernetes/kubernetes/blob/master/OWNERS_ALIASES#L222...L229), and champion of this feature on behalf of `sig-node`
* I approve the creation of this repo (if you need further approval from `sig-node-leads` please let me know).

**Comment by klueska** [comment]
/assign @mrbobbytables 
This is related to https://github.com/kubernetes/org/issues/3821 and https://github.com/kubernetes/community/pull/6970

**Comment by mrbobbytables** [comment]
Repo create: https://github.com/kubernetes-sigs/dra-example-driver
teams added in: #3850 
k/community update: https://github.com/kubernetes/community/pull/6980

once teams PR is merged I'll add teams to the repo, we can close this out once all PRs are merged.

**Comment by mrbobbytables** [comment]
PRs merged, and teams added with permissions to the repo - going to go ahead and close. - Thanks!

/close
