### ISSUE TITLE
REQUEST: Netlify site for KMM

### ISSUE THREAD

**Issue by iranzo** [kubernetes/org#3839]
### Repository

https://github.com/kubernetes-sigs/kernel-module-management

### Project domain

kmm.sigs.k8s.io

### Additional context for request

https://github.com/kubernetes-sigs/kernel-module-management/issues/27

**Comment by mrbobbytables** [comment]
please create a netlify.toml file in the root of the repo. Without it tests will fail for every build once the integration is made^^;;;

**Comment by iranzo** [comment]
@mrbobbytables it's in the PR I made for this pending merging, ty!

**Comment by iranzo** [comment]
@mrbobbytables PR has been merged in the KMM repo

**Comment by mrbobbytables** [comment]
Doesn't look like DNS has propagated yet, but the site is up at:
kubernetes-sigs-kmm.netlify.app
I'll check again later to finish the dns config in netlify

**Comment by iranzo** [comment]
@mrbobbytables I guess this one can be closed as the netlify render happens already on kubernetes-sigs-kmm.netlify.app


But we still have to sort out the https://github.com/kubernetes/k8s.io/issues/4471 for having the DNS itself pointing to this instance of netlify, TY!

**Comment by mrbobbytables** [comment]
Theres nothing missing in the other issue that I know of

**Comment by cblecker** [comment]
Looks like the DNS is complete, and cert was able to be issued. Closing..
