### ISSUE TITLE
REQUEST: New membership for @niuzhenguo

### ISSUE THREAD

**Issue by niuzhenguo** [kubernetes/org#3840]
### GitHub Username

@niuzhenguo

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tengqm 

### Sponsor 2

@windsonsea or @chengxiangdong 

### List of contributions to the Kubernetes project

- Authored PRs in kubernetes: https://github.com/pulls?q=is%3Apr+author%3Aniuzhenguo+archived%3Afalse+org%3Akubernetes+

- Authored PRs in kubernetes-sigs: https://github.com/pulls?q=is%3Apr+author%3Aniuzhenguo+archived%3Afalse+org%3Akubernetes-sigs

**Comment by chengxiangdong** [comment]
+1, thanks for your contributions,

**Comment by windsonsea** [comment]
+1 
Look forward to your more contributions.

> Tips: You may need to find one more reviewer or approver to [become a member](https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/#becoming-a-member).

**Comment by chengxiangdong** [comment]
+1 from me

**Comment by tengqm** [comment]
+1
Looking forward to work with you in this community.

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3849  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
