### ISSUE TITLE
REQUEST: Create repo for SIG-multicluster high level docs and outreach

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes/org#3841]
### New repo, staging repo, or migrate existing

new repo

### Is it a staging repo?

no

### Requested name for new repository

sig-multicluster-site

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

lauralorenz, pmorie, jeremyot

### Who should have write access?

lauralorenz, pmorie, jeremyot

### Who should be listed as approvers in OWNERS?

lauralorenz, pmorie, jeremyot

### Who should be listed in SECURITY_CONTACTS?

lauralorenz, pmorie, jeremyot

### What should the repo description be?

Outreach and central subproject docs site for SIG-Multicluster

### What SIG and subproject does this fall under?

SIG-Multicluster

### Please provide references to appropriate approval for this new repo

Approval via comment from @JeremyOT and/or @pmorie (SIG-Multicluster chairs)
See also proposal doc: https://docs.google.com/document/d/14okQxJ5Pk8OHEz0VdFhSD4FZrnUr1IqTUt0Yq9KiI0U/edit#

**Comment by mrbobbytables** [comment]
/assign

@lauralorenz what should the subproject be called to be listed in sigs.yaml / multicluster readme?

**Comment by lauralorenz** [comment]
Can we call it just "SIG-Multicluster site" (or `sig-multicluster-site` wherever it might need to be formatted as label)

**Comment by mrbobbytables** [comment]
Repo created: https://github.com/kubernetes-sigs/sig-multicluster-site
Teams PR: https://github.com/kubernetes/org/pull/3945
k/community PR: https://github.com/kubernetes/community/pull/7042

Once all PRs are merged and teams added this can be closed 👍

**Comment by mrbobbytables** [comment]
All outstanding items have been merged / added. Going to go ahead and close this out. :)

/close
