### ISSUE TITLE
REQUEST: New membership for @wanyufe

### ISSUE THREAD

**Issue by wanyufe** [kubernetes/org#3846]
### GitHub Username

@wanyufe

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@maxdrib

### Sponsor 2

@jweite-amazon 

### Sponsor 3

@davidjumani

### Sponsor 4
@elmiko

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/164
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/133
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/191

**Comment by fabriziopandini** [comment]
Hey @wanyufe, I will be happy to sponsor, but what about asking for sponsorship to maintainers and reviewers of cluster-api-provider-cloudstack who knows better about your work?
Also, AFAIK work on eks-anywhere does not count for membership in kubernetes-sigs

**Comment by elmiko** [comment]
> Hey @wanyufe, I will be happy to sponsor, but what about asking for sponsorship from maintainers and reviewers of cluster-api-provider-cloudstack who knows better about your work?

+1, happy to sponsor as well, but it might be good to have a sponsor that is closer to the work as well.

**Comment by wanyufe** [comment]
Thanks. I added @jweite-amazon, @maxdrib  and @davidjumani

**Comment by maxdrib** [comment]
+1 you've done excellent work on CAPC and we look forward to your continued contributions!

**Comment by davidjumani** [comment]
+1

**Comment by maxdrib** [comment]
I don't think this worked. It doesn't appear that @wanyufe is a member in https://github.com/orgs/kubernetes-sigs/people?query=wanyufe. Could you take a look @mrbobbytables?
