### ISSUE TITLE
REQUEST: New membership for olivercodes

### ISSUE THREAD

**Issue by olivercodes** [kubernetes/org#3848]
### GitHub Username

@olivercodes

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@astoycos

### Sponsor 2

@mattfenwick

### List of contributions to the Kubernetes project

Greetings!

I am involved with https://github.com/kubernetes-sigs/network-policy-api, working on conformance tests for AdminNetworkPolicy https://github.com/kubernetes-sigs/network-policy-api/issues/35 and also extending Cyclonus with Matt Fenwick to support ANP going forward (cyclonus deep dive on Antrea live today where Matt and I started looking at how to extend and begin updating Cyclonus going forward https://www.youtube.com/watch?v=iuurc8852mE). 

In addition to ANP, I'll be assisting Matt in further integrating cyclonus into the upstream repo/processes (recently merged into k8s-sigs/network-policy-api!) https://github.com/kubernetes-sigs/network-policy-api/blob/master/cmd/cyclonus/OWNERS working on https://github.com/kubernetes-sigs/network-policy-api/issues/62

I've also contributed via:
https://github.com/kubernetes-sigs/network-policy-api/pull/47
https://github.com/kubernetes-sigs/network-policy-api/pull/51
https://github.com/kubernetes-sigs/network-policy-api/issues/37
https://github.com/kubernetes-sigs/network-policy-api/issues/48
https://github.com/kubernetes-sigs/network-policy-api/issues/61

**Comment by mattfenwick** [comment]
+1 thanks for your contributions @olivercodes and looking forward to hacking with you some more !!

**Comment by astoycos** [comment]
/lgtm 

thanks for all your help so far!! :)

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3862   to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
