### ISSUE TITLE
REQUEST: New membership for craiglpeters

### ISSUE THREAD

**Issue by craiglpeters** [kubernetes/org#385]
### GitHub Username
@craiglpeters

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lachie83 
- @spiffxp 

### List of contributions to the Kubernetes project
- Reviewing PRs for Windows Containers in Kubernetes
- SIG-WIndows, SIG-Architecture, SIG-Node, SIG-Testing, SIG-PM

**Comment by lachie83** [comment]
+1. I confirm sponsoring this membership

**Comment by spiffxp** [comment]
+1

**Comment by spiffxp** [comment]
I've opened #386, once that merges you'll be sent an invite to the org you requested.  Welcome aboard!

/pony party
