### ISSUE TITLE
REQUEST: New membership for carlory

### ISSUE THREAD

**Issue by carlory** [kubernetes/org#3854]
### GitHub Username

@carlory

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu

### Sponsor 2

@wzshiming 

### List of contributions to the Kubernetes project

I'm already a member of kubernetes

PRs: 

- https://github.com/kubernetes-sigs/kwok/pull/75
- https://github.com/kubernetes-sigs/kwok/pull/73
- https://github.com/kubernetes-sigs/kwok/pull/71
- https://github.com/kubernetes-sigs/kwok/pull/70
- https://github.com/kubernetes-sigs/kwok/pull/69

**Comment by wzshiming** [comment]
+1

BTY, you're already a Kubernetes member, you shouldn't need a +1 from anyone else.

https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem

> There are related [Kubernetes GitHub organizations](https://github.com/kubernetes/community/blob/master/github-management#actively-used-github-organizations), such as [kubernetes-sigs](https://github.com/kubernetes-sigs). We are currently working on automation that would transfer membership in the Kubernetes organization to any related orgs automatically, but such is not the case currently. If you are a member of one of these Orgs, you are implicitly eligible for membership in related orgs, and can request membership when it becomes relevant, by creating a PR directly or [opening an issue](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) against the kubernetes/org repo, as above.

**Comment by mrbobbytables** [comment]
@carlory - @wzshiming is correct, you don't need to open an issue, you can add yourself to the org if you're part of K8s already :) I'm going to be doing a batch of org memberships so will take care of adding you in there. Mostly just an FYI for the future that you can do it yourself instead of waiting on the github admins to process you in one of the batches.

/assign
