### ISSUE TITLE
REQUEST: New membership for @kannon92

### ISSUE THREAD

**Issue by kannon92** [kubernetes/org#3861]
### GitHub Username

@kannon92

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alculquicondor

### Sponsor 2

@kerthcet

## PRs Merged
- https://github.com/kubernetes-sigs/kueue/pull/448
- https://github.com/kubernetes-sigs/kueue/pull/442
- https://github.com/kubernetes-sigs/controller-runtime/pull/2071
- https://github.com/kubernetes-sigs/kueue/pull/440
- https://github.com/kubernetes-sigs/controller-runtime/pull/2065
- https://github.com/kubernetes-sigs/controller-tools/pull/743
- https://github.com/kubernetes-sigs/controller-tools/pull/736
- https://github.com/kubernetes-sigs/controller-runtime/pull/2050
- https://github.com/kubernetes/test-infra/pull/27868
- https://github.com/kubernetes-sigs/kueue/pull/423
- https://github.com/kubernetes-sigs/kueue/pull/404
- https://github.com/kubernetes-sigs/kueue/pull/395
- https://github.com/kubernetes-sigs/kueue/pull/382

## Issues Participating

https://github.com/kubernetes/kubernetes/issues/113211

**Comment by alculquicondor** [comment]
+1 Kevin has been helping us improve the coverage and maintainability of kueue

**Comment by kerthcet** [comment]
+1 for Kevin's continuous contributions and hope to see more in the future.

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3862   to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
