### ISSUE TITLE
REQUEST: Create aws-file-cache-csi-driver to kubernetes-csi

### ISSUE THREAD

**Issue by PatrickGhadban** [kubernetes/org#3866]
### New repo, staging repo, or migrate existing

New repository

### Is it a staging repo?

no

### Requested name for new repository

aws-file-cache-csi-driver

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@nckturner

### Who should have write access?

@nckturner

### Who should be listed as approvers in OWNERS?

@nckturner, @wongma7, @khoang98, @jacobwolfaws

### Who should be listed in SECURITY_CONTACTS?

@nckturner

### What should the repo description be?

Amazon File Cache Cloud Container Storage Interface(CSI) Driver

### What SIG and subproject does this fall under?

sig-cloud-provider

### Please provide references to appropriate approval for this new repo

@nckturner

### Additional context for request

I am planning to contribute to this repo but am not a Kubernetes org member yet, so I plan to use my contributions to become a member, and in the meantime @nckturner will be the owner and approver of the repo.

**Comment by PatrickGhadban** [comment]
Hi, is it possible to get a timeline for this issue request? If there is anything which I can do to help it gain traction, I'm more than happy to do so. 

Thank you!

**Comment by nikhita** [comment]
@PatrickGhadban this will require an approval from a sig-storage lead.

/sig storage

**Comment by wongma7** [comment]
> > Which Organization should it reside

> kubernetes-csi

this should say 'kubernetes-sigs', @PatrickGhadban can you fix this?

because that's where FSx,EFS,EBS are held https://github.com/kubernetes-sigs/aws-ebs-csi-driver and they do fall under sig-cloud-provider aws https://github.com/kubernetes/community/tree/master/sig-cloud-provider#provider-aws not sig-storage.

**Comment by PatrickGhadban** [comment]
Thank you very much for the correction, @wongma7, I've updated the request.

@nikhita thank you for the response and apologies for the confusion. As shown under "Additional context for request", we do have the approval from Nic Turner, the [AWS technical lead](https://github.com/kubernetes/community/tree/master/sig-cloud-provider#technical-leads) for SIG establish new subproject. Is there anything else that would be needed from my end for this request to be actioned?

**Comment by nikhita** [comment]
> @nikhita thank you for the response and apologies for the confusion. As shown under "Additional context for request", we do have the approval from @nckturner, the [AWS technical lead](https://github.com/kubernetes/community/tree/master/sig-cloud-provider#technical-leads) for SIG establish new subproject. Is there anything else that would be needed from my end for this request to be actioned?

@PatrickGhadban thanks, this is helpful! We'll still need a +1 from @nckturner to proceed. If this was previously discussed in a SIG meeting, notes/recording should be good enough too.

**Comment by nikhita** [comment]
/assign

Repo has been created - https://github.com/kubernetes-sigs/aws-file-cache-csi-driver

Also created:
- https://github.com/kubernetes/org/pull/3922 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/7033 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by PatrickGhadban** [comment]
Thank you so much!! @nikhita

**Comment by nikhita** [comment]
Both PRs have merged. Closing.
