### ISSUE TITLE
REQUEST: New membership for jzhupup

### ISSUE THREAD

**Issue by jzhupup** [kubernetes/org#3870]
### GitHub Username

@jzhupup

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tengqm

### Sponsor 2

@windsonsea

### List of contributions to the Kubernetes project

PRs authored: https://github.com/kubernetes/website/pull/36146, https://github.com/kubernetes/website/pull/36235, https://github.com/kubernetes/website/pull/36275/files, https://github.com/kubernetes/website/pull/36261/files, https://github.com/kubernetes/website/pull/36757/files
SIG projects I am involved with: [kubernetes/website](https://kubernetes.io/docs/home/)

**Comment by windsonsea** [comment]
+1

Look forward to your more contributions.

**Comment by tengqm** [comment]
+1
