### ISSUE TITLE
REQUEST: New membership for @npintaux

### ISSUE THREAD

**Issue by npintaux** [kubernetes/org#3872]
### GitHub Username

@npintaux

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@lauralorenz

### Sponsor 2

@pmorie

### List of contributions to the Kubernetes project

- SIG-MC: preliminary documentation website setup (https://github.com/lauralorenz/sig-multicluster-site-proposal)
- SIG-MC: additions to documentation web site (slides + videos, blog posts)

**Comment by lauralorenz** [comment]
+1, thank you a ton for all your help in SIG-MC and looking forward to continuing to collaborate! 🥇

**Comment by pmorie** [comment]
+1

**Comment by nikhita** [comment]
/assign

@npintaux  Thank you for all your contributions so far :)

I've created PR #3933 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
