### ISSUE TITLE
REQUEST: migrate kong/blixt

### ISSUE THREAD

**Issue by shaneutt** [kubernetes/org#3875]
### New repo, staging repo, or migrate existing

migrate existing (https://github.com/kong/blixt)

### Is it a staging repo?

no

### Requested name for new repository

blixt

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

shaneutt, astoycos, robscott, mlavacca

### Who should have write access?

shaneutt, astoycos, robscott, mlavacca

### Who should be listed as approvers in OWNERS?

shaneutt, astoycos, robscott, mlavacca

### Who should be listed in SECURITY_CONTACTS?

shaneutt, astoycos, robscott, mlavacca

### What should the repo description be?

A Layer 4 load-balancer for Gateway API conformance testing and examples

### What SIG and subproject does this fall under?

SIG Network Gateway API

### Please provide references to appropriate approval for this new repo

Discussion in https://groups.google.com/g/kubernetes-sig-network/c/z_N1cLTUO8M/m/l6gO6qLeAgAJ

**Comment by shaneutt** [comment]
@thockin, @aojea seemed like everyone was generally positive in the email thread, but wanted to check in with you to see if you're OK with explicitly approving this or if you feel there's more discussion we need to have first?

**Comment by astoycos** [comment]
/assign @thockin
/assign @robscott
/assign @aojea 

(assigning folks from the google groups thread) 

Thanks for opening the issue @shaneutt!

**Comment by robscott** [comment]
Thanks @shaneutt, this request LGTM, but have one request pre-migration: Can you make it slightly more clear that this is never intended to be used for production? It's already clearly stated that the current state of blixt is experimental, but it would be helpful to clarify that it is permanently out of scope for this project.

**Comment by robscott** [comment]
LGTM, thanks @shaneutt!

**Comment by thockin** [comment]
No objections

/lgtm
/approve

**Comment by mrbobbytables** [comment]
/hold

Just a note - we should not proceed on next donation steps till the GPL license question is answered in https://github.com/cncf/foundation/issues/474

**Comment by shaneutt** [comment]
@mrbobbytables given the precedents that have already been set with eBPF inclusion in the CNCF we (the Blixt maintainers) have opted to re-license under dual-licensed `GPLv2 + BSD-2-Clause`:

https://github.com/kong/blixt/pull/79

As I understand it since this is already an accepted license for projects, it should now be the case that we no longer need https://github.com/cncf/foundation/issues/474 is that correct?

**Comment by shaneutt** [comment]
@mrbobbytables https://github.com/cncf/foundation/issues/474 is now resolved, may we unhold this and move forward?

**Comment by mrbobbytables** [comment]
yup!

**Comment by mrbobbytables** [comment]
@shaneutt who from kong has rights to transfer the repo? I'll need to add them to an intermediary org and then we can move it over

**Comment by shaneutt** [comment]
(I'm still working on this, it's just taking a bit longer than I expected)

**Comment by devonl-kong** [comment]
@mrbobbytables I will be transferring ownership of the repo. CC: @shaneutt

**Comment by mrbobbytables** [comment]
kk @devonl-kong I'll shoot you an invite to kubernetes-purgatory, our temp org for transfers.

**Comment by devonl-kong** [comment]
Thanks @mrbobbytables, the move has been completed. https://github.com/kubernetes-purgatory/blixt

**Comment by shaneutt** [comment]
At this point I think we're all set, I think the repository has everything in it that's required as of this morning. @mrbobbytables can we close this, or do we have anything remaining we need to do?

**Comment by mrbobbytables** [comment]
We are good to close! 
/close
