### ISSUE TITLE
REQUEST: New membership for @vinli-cn

### ISSUE THREAD

**Issue by vinli-cn** [kubernetes/org#3882]
### GitHub Username

@vinli-cn

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@andyzhangx

### List of contributions to the Kubernetes project

PRs:
https://github.com/kubernetes-sigs/azurelustre-csi-driver/pull/48
https://github.com/kubernetes-sigs/azurelustre-csi-driver/pull/52
https://github.com/kubernetes-sigs/azurelustre-csi-driver/pull/54
https://github.com/kubernetes-sigs/azurelustre-csi-driver/pull/59
https://github.com/kubernetes-sigs/azurelustre-csi-driver/pull/65
https://github.com/kubernetes-sigs/azurelustre-csi-driver/pull/66
https://github.com/kubernetes-csi/external-provisioner/pull/808
https://github.com/kubernetes-csi/external-provisioner/pull/800

**Comment by andyzhangx** [comment]
+1

**Comment by xing-yang** [comment]
Hi @vinli-cn, as discussed on Slack, can you change the org from kubernetes-csi to kubernetes-sigs?

**Comment by vinli-cn** [comment]
@xing-yang updated the org, thanks!

**Comment by xing-yang** [comment]
+1

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3909 to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
