### ISSUE TITLE
REQUEST: Create kubernetes-sigs/windows-service-proxy

### ISSUE THREAD

**Issue by marosset** [kubernetes/org#3888]
### New repo, staging repo, or migrate existing

New Repo

### Is it a staging repo?

no

### Requested name for new repository

windows-service-proxy

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

marosset; jayunit100; jsturtevant 

### Who should have write access?

marosset; jayunit100; jsturtevant; 

### Who should be listed as approvers in OWNERS?

marosset; jayunit100; jsturtevant; daschott; knabben

### Who should be listed in SECURITY_CONTACTS?

marosset; jayunit100; jsturtevant; 

### What should the repo description be?

Home for an out of tree Windows kube-proxy implementation based on KPNG

### What SIG and subproject does this fall under?

SIG-Windows

### Please provide references to appropriate approval for this new repo

Discussed multiple times at SIG-Windows community meetings
https://docs.google.com/document/d/1Tjxzjjuy4SQsFSUVXZbvqVb64hjNAG5CQX8bK7Yda9w/edit#heading=h.3f5dhus4q8i2
Most recently on `12/02/2022`, `11/29/2022` and `11/08/2022`

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/windows-service-proxy

Also created:
- https://github.com/kubernetes/org/pull/3913 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/7022 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.
