### ISSUE TITLE
REQUEST: New membership for jichenjc

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/org#389]
### GitHub Username
jichenjc

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@chaosaffe 
@adisky 

### List of contributions to the Kubernetes project
https://github.com/kubernetes/cloud-provider-openstack/pull/411
https://github.com/kubernetes/cloud-provider-openstack/pull/398
https://github.com/kubernetes/cloud-provider-openstack/pull/397
https://github.com/kubernetes/cloud-provider-openstack/pull/380
https://github.com/kubernetes/cloud-provider-openstack/pull/379

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/148

**Comment by adisky** [comment]
+1 from me!

**Comment by mrbobbytables** [comment]
Hey there @jichenjc, thank you for all your contributions so far :)

I've created PR #400   to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by jichenjc** [comment]
@mrbobbytables, can you help to check https://github.com/kubernetes/org/pull/400 only added me into kubernetes-sig and didn't in kubernetes org, so I can work on both? Thanks

**Comment by jichenjc** [comment]
@mrbobbytables sorry for inconvenience, in case I need a new PR, please let me know, thanks

**Comment by mrbobbytables** [comment]
You are 100% correct. Will get a fix out shortly.

**Comment by mrbobbytables** [comment]
@jichenjc I have created PR #474 to correct your membership, my apologies for the mistake :(
