### ISSUE TITLE
REQUEST: New membership for jlamillan

### ISSUE THREAD

**Issue by jlamillan** [kubernetes/org#3891]
### GitHub Username

@jlamillan

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@MaciekPytel

### Sponsor 2

@gjtempleton

### List of contributions to the Kubernetes project

[kubernetes/autoscaler](https://github.com/kubernetes/autoscaler) PRs:
- https://github.com/kubernetes/autoscaler/pull/4349
- https://github.com/kubernetes/autoscaler/pull/5335

[kubernetes-sigs/external-dns](https://github.com/kubernetes-sigs/external-dns) PRs:
- https://github.com/kubernetes-sigs/external-dns/pull/917
- https://github.com/kubernetes-sigs/external-dns/pull/687

[Other authored issues, pull-requests](https://github.com/issues?q=author%3Ajlamillan+)

**Comment by MaciekPytel** [comment]
+1 from me. Thanks for your contributions to autoscaler and I'm looking forward to your future work with us :)

**Comment by gjtempleton** [comment]
+1 from me as well, looking forward to your future contributions!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3909 to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
