### ISSUE TITLE
REQUEST: New membership for @nnmin-aws

### ISSUE THREAD

**Issue by nnmin-aws** [kubernetes/org#3894]
### GitHub Username

@nnmin-aws

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-csi, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@nckturner

### Sponsor 2

@chenrui333

### List of contributions to the Kubernetes project

  [PRs](https://github.com/kubernetes-sigs/aws-iam-authenticator/pulls?q=is%3Apr+is%3Aclosed+author%3Annmin-aws)
  [Issues](https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/527)

**Comment by chenrui333** [comment]
LGTM 👍

**Comment by nnmin-aws** [comment]
@savitharaghunathan hey Savitha Could you please kindly approve my request as current coordinators?

thank you!

**Comment by nnmin-aws** [comment]
@ameukam @palnabarun Could you please kindly approve? thank you

**Comment by nnmin-aws** [comment]
`+1`

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #3909 to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
