### ISSUE TITLE
REQUEST: New membership for @MasayaAoyama

### ISSUE THREAD

**Issue by MasayaAoyama** [kubernetes/org#39]
### GitHub Username
@MasayaAoyama

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah
- @xiangpengzhao

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    * https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=author%3AMasayaAoyama+
    * https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=author%3AMasayaAoyama+
    * https://github.com/kubernetes/dashboard/pulls?utf8=%E2%9C%93&q=author%3AMasayaAoyama+
    * https://github.com/kubernetes/charts/pulls?utf8=%E2%9C%93&q=author%3AMasayaAoyama+

- Issues responded to
    * https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3AMasayaAoyama+is%3Aclosed+
    * https://github.com/helm/charts/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3AMasayaAoyama+is%3Aclosed+

- SIG projects I am involved with
    * k/website
    * k/kubernetes
    * k/dashboard
    * k/charts (now helm/charts)

* [Optional] Community Meetup
    * [CNCF Official] Cloud Native Meetup Tokyo organizer（https://cloudnative.connpass.com/）
    * KubeCon Japanese-meeting organizer（https://kubecon-jp.connpass.com/）

**Comment by xiangpengzhao** [comment]
+1

**Comment by MasayaAoyama** [comment]
@zacharysarah @xiangpengzhao 
Thank you a lot!

**Comment by spiffxp** [comment]
/close
invite sent, welcome!
