### ISSUE TITLE
REQUEST: New membership for qingwave

### ISSUE THREAD

**Issue by qingwave** [kubernetes/org#3907]
### GitHub Username

@qingwave

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alexzielenski

### Sponsor 2

@wzshiming

### List of contributions to the Kubernetes project

PRs
- [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/pulls?q=author%3Aqingwave)
- [kuberentes-sigs](https://github.com/pulls?q=is%3Apr+author%3Aqingwave+org%3Akubernetes-sigs+)
- [kubernetes](https://github.com/pulls?q=is%3Apr+author%3Aqingwave+org%3Akubernetes+)

Issues
- [kubernetes](https://github.com/search?p=2&q=org%3Akubernetes+qingwave&type=Issues)
- [kubernetes-sigs](https://github.com/search?p=2&q=org%3Akubernetes-sigs+qingwave&type=Issues)

**Comment by yuzhiquan** [comment]
Well done!
+1 from me, but i'm afraid you need find another sponsor for your entry!

**Comment by wzshiming** [comment]
+1

**Comment by qingwave** [comment]
Thanks of all :)

**Comment by alexzielenski** [comment]
+1

**Comment by nikhita** [comment]
/assign

@qingwave  Thank you for all your contributions so far :)

I've created PR #3965 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
