### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/kwok

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/org#3911]
### Repository

kubernetes-sigs/kwok

### Project domain

kwok.sigs.k8s.io

**Comment by wzshiming** [comment]
cc @cblecker @ameukam

**Comment by wzshiming** [comment]
Hi @mrbobbytables
Could you have time to help me create the `k8s-kwok.netlify.app` website?

I have tested the [netlify configuration](https://github.com/kubernetes-sigs/kwok/blob/main/netlify.toml) without any problems, demo site https://kwok-demo.netlify.app

**Comment by mrbobbytables** [comment]
Site is now live on https://k8s-kwok.netlify.app/
Once DNS is sorted out can finish it up 👍

**Comment by wzshiming** [comment]
https://github.com/kubernetes/k8s.io/pull/4579 
DNS records have been added.

**Comment by mrbobbytables** [comment]
@wzshiming Do you have that dns name in use in another netlify account or anything? It's giving me an error when trying to add it.

**Comment by mrbobbytables** [comment]
yeah, im getting the same error when I try which has meant somehow its configured elsewhere.

**Comment by wzshiming** [comment]
So this means that some account registered k8s.io to [Netlify DNS](https://docs.netlify.com/domains-https/netlify-dns/), I think this may require administrative privileges for that domain, but I can't go into the rest of it so I'll have to rely on you to continue diagnosing, thanks 🙏.

**Comment by Huang-Wei** [comment]
@mrbobbytables do you think if we could open a ticket to netlify to figure out why the DNS record `kwok.sigs.k8s.io` doesn't work?

**Comment by Huang-Wei** [comment]
> I have tried to configure this DNS for a site [kwok-demo.netlify.app](https://kwok-demo.netlify.app/) that links to my fork repo, I think it should not affect other accounts.

Not sure if it works if you remove configuration it in your forked repo?

**Comment by cblecker** [comment]
I've opened a ticket with Netlify.
/unassign @mrbobbytables 
/assign

**Comment by cblecker** [comment]
DNS record and TLS certificate are set up and working.

Netlify support needed to remove a DNS zone that was set up on some other account. I'm guessing that @wzshiming's testing broke things somehow. However things are now all fixed.

/close

**Comment by Huang-Wei** [comment]
Thanks a ton, @cblecker and @mrbobbytables !

**Comment by wzshiming** [comment]
Thanks, @cblecker and @mrbobbytables !!!
