### ISSUE TITLE
REQUEST: New membership for fabi200123

### ISSUE THREAD

**Issue by fabi200123** [kubernetes/org#3915]
### GitHub Username

@fabi200123

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jsturtevant

### Sponsor 2

@claudiubelu

### List of contributions to the Kubernetes project

PRs:
- [kubernetes-sigs](https://github.com/kubernetes-sigs/sig-windows-tools/pulls?q=is%3Apr+author%3Afabi200123)
- [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Afabi200123)

Issues:
- [kubernetes-sigs](https://github.com/kubernetes-sigs/sig-windows-tools/issues?q=is%3Aissue+fabi200123)

**Comment by claudiubelu** [comment]
Fabian has been helping us a lot on sig-windows: documentation & kubeadm windows node joining, helped on node log viewer, pod vertical scaling.

/lgtm

**Comment by jsturtevant** [comment]
+1 Fabian has been an active member contributing tests for the node log viewer and helping improve our documentation around kubeadm. Thanks for all the help!

**Comment by marosset** [comment]
+1 Fabian has been a big help in SIG-Windows!

**Comment by aravindhp** [comment]
+1 @fabi200123 has been a great help with writing e2e tests for the node log query feature.

**Comment by nikhita** [comment]
/assign

@fabi200123  Thank you for all your contributions so far :)

I've created PR #3933 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
