### ISSUE TITLE
REQUEST: New membership for my-git9

### ISSUE THREAD

**Issue by my-git9** [kubernetes/org#3917]
### GitHub Username

@my-git9

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@wzshiming

### Sponsor 2

@Huang-Wei

### List of contributions to the Kubernetes project

PRs:
- https://github.com/kubernetes-sigs/kwok/pull/112
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/470
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/468
- https://github.com/kubernetes-sigs/gateway-api/pull/1621
- https://github.com/kubernetes-sigs/cluster-capacity/pull/163
- https://github.com/kubernetes-sigs/descheduler/pull/1030
- https://github.com/kubernetes-sigs/kubespray/pull/9627

**Comment by wzshiming** [comment]
+1

**Comment by Huang-Wei** [comment]
+1

**Comment by nikhita** [comment]
/assign

@my-git9  Thank you for all your contributions so far :)

I've created PR #3933 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
