### ISSUE TITLE
REQUEST: New membership for xing-yang

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/org#392]
### GitHub Username
@xing-yang 

### Organization you are requesting membership in
@kubernetes-csi
@external-snapshotter-admins

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @saad-ali 
- @rootfs

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-csi/external-snapshotter/pull/78
  - https://github.com/kubernetes-csi/external-snapshotter/pull/74
  - https://github.com/kubernetes-csi/external-snapshotter/pull/71
  - https://github.com/kubernetes-csi/external-snapshotter/pull/66
  - https://github.com/kubernetes-csi/external-snapshotter/pull/65
  - https://github.com/kubernetes-csi/external-snapshotter/pull/61
  - https://github.com/kubernetes-csi/external-snapshotter/pull/39
  - https://github.com/kubernetes-csi/external-snapshotter/pull/33
  - https://github.com/kubernetes-csi/external-snapshotter/pull/16
  - https://github.com/kubernetes-csi/external-snapshotter/pull/7
  - https://github.com/kubernetes-csi/external-snapshotter/pull/6
  - https://github.com/kubernetes-csi/external-provisioner/pull/123
  - https://github.com/kubernetes-csi/external-provisioner/pull/145
  - https://github.com/kubernetes-csi/external-attacher/pull/101
  - https://github.com/kubernetes-csi/external-attacher/pull/76

- Issues responded to
  - https://github.com/kubernetes-csi/external-attacher/issues/99
  - https://github.com/kubernetes-csi/external-provisioner/issues/87
  - https://github.com/kubernetes-csi/external-provisioner/issues/128
  - https://github.com/kubernetes-csi/external-snapshotter/issues/10 

- SIG projects I am involved with
 - SIG-Storage CSI

**Comment by rootfs** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @xing-yang I've created PR #400 to add you to both the kubernetes and kubernetes-csi org, but have not added you to the external-snapshotter-admins group. For that it might be best to get a PR from either of the two current maintainers: @childsb @saad-ali.

In anycase, welcoem to @kubernetes! :) :tada:

/assign

**Comment by xing-yang** [comment]
Thanks!

**Comment by saad-ali** [comment]
I approve on behalf of SIG Storage. @xing-yang has been a very productive contributor.
