### ISSUE TITLE
REQUEST: New membership for LiorLieberman

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes/org#3924]
### GitHub Username

@LiorLieberman

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@shaneutt

### Sponsor 2

@robscott

### List of contributions to the Kubernetes project

Currently I am contributing to k8s and gateway-api, mainly as part of SIG-network

* I am preparing a KEP to propose standards around `appProtocol` (non IANA Service Names) values. 
part of the context is here - https://github.com/istio/istio/issues/42615

* Will soon engage with CNCF about gateway-api conformance centralized report.

- PRs authored:
  * https://github.com/kubernetes/kubernetes/pull/113544
  * https://github.com/kubernetes-sigs/gateway-api/pull/1556
  * https://github.com/kubernetes-sigs/gateway-api/pull/1622
  * https://github.com/kubernetes-sigs/gateway-api/pull/1611
    * also added support in istio for gw-api path prefix redirect - https://github.com/istio/istio/pull/42538

**Comment by shaneutt** [comment]
+1

Thanks @LiorLieberman :vulcan_salute:

**Comment by nikhita** [comment]
/assign

@LiorLieberman Thank you for all your contributions so far :)

I've created PR #3933 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
