### ISSUE TITLE
REQUEST: New membership for fuxiuyin

### ISSUE THREAD

**Issue by fuxiuyin** [kubernetes/org#3929]
### GitHub Username

@fuxiuyin

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@vinli-cn

### List of contributions to the Kubernetes project

PRs in [kubernetes-sigs/azurelustre-csi-driver](https://github.com/kubernetes-sigs/azurelustre-csi-driver/pulls?q=is%3Apr+fuxiuyin)

Other:
https://github.com/kubernetes/kubernetes/pull/113201
https://github.com/kubernetes/kubernetes/issues/114652

**Comment by vinli-cn** [comment]
+1

**Comment by xing-yang** [comment]
+1

**Comment by nikhita** [comment]
/assign

@fuxiuyin  Thank you for all your contributions so far :)

I've created PR #3933 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
