### ISSUE TITLE
REQUEST: New membership for xing-yang

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/org#393]
### GitHub Username
@xing-yang

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @saad-ali 
- @rootfs 
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/72584
  - https://github.com/kubernetes/kubernetes/pull/68979
  - https://github.com/kubernetes/kubernetes/pull/68419
  - https://github.com/kubernetes/kubernetes/pull/67087
  - https://github.com/kubernetes/kubernetes/pull/69036
  - https://github.com/kubernetes/community/pull/2335
  - https://github.com/kubernetes/test-infra/pull/9072
  - https://github.com/kubernetes/website/pull/10296
  - https://github.com/kubernetes/website/pull/9948
  - https://github.com/kubernetes/kubernetes/pull/64663
  - https://github.com/kubernetes/enhancements/pull/705
  - https://github.com/kubernetes-csi/external-snapshotter/pulls?utf8=%E2%9C%93&q=is%3Apr+xing-yang
  - https://github.com/kubernetes-csi/external-provisioner/pulls?utf8=%E2%9C%93&q=is%3Apr+xing-yang
  - https://github.com/kubernetes-csi/external-attacher/pulls?utf8=%E2%9C%93&q=is%3Apr+xing-yang

- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/68688
  - https://github.com/kubernetes/kubernetes/issues/67932

- SIG projects I am involved with
  - SIG-Storage Kubernetes-CSI

**Comment by humblec** [comment]
+1 from me for @xing-yang , she is an active contributor to sig-storage!  welcome!

**Comment by mrbobbytables** [comment]
Replied in #392 :) I've added you to the @kubernetes and @kubernetes-csi orgs.

Welcome to @kubernetes!

/assign
