### ISSUE TITLE
REQUEST: New membership for yrs147

### ISSUE THREAD

**Issue by yrs147** [kubernetes/org#3939]
### GitHub Username

yrs147

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-csi, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@JamesLaverack

### Sponsor 2

@harshanarayana

### List of contributions to the Kubernetes project

I am a Release Notes shadow for the v1.27 release cycle.

**Comment by harshanarayana** [comment]
+1 to @yrs147. Welcome to Kubernetes v1.27 Team.

/cc @JamesLaverack  @salaxander

/assign

**Comment by JamesLaverack** [comment]
+1 Welcome to the release team. 😃

**Comment by nikhita** [comment]
/assign

@yrs147  Thank you for all your contributions so far :)

I've created PR #3965 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
