### ISSUE TITLE
REQUEST: New membership for npolshakova

### ISSUE THREAD

**Issue by npolshakova** [kubernetes/org#3940]
### GitHub Username

@npolshakova

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@marosset

### Sponsor 2

@salaxander

### List of contributions to the Kubernetes project

- Shadow as part of the 1.27 enhancement team

**Comment by marosset** [comment]
/lgtm
/assign @salaxander @JamesLaverack 

Thanks @npolshakova!

**Comment by JamesLaverack** [comment]
+1 Welcome to the release team. 😃
