### ISSUE TITLE
REQUEST: New membership for dkoshkin

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes/org#395]
### GitHub Username
@dkoshkin

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bertinatto 
- @leakingtapan 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - [aws-ebs-csi](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pulls?q=is%3Apr+author%3Adkoshkin+is%3Aclosed)
  - https://github.com/kubernetes/kubernetes/pull/65676

- SIG projects I am involved with
  - sig-storage
  - sig-aws

**Comment by pires** [comment]
Unfortunately, it seems I'm no longer part of any OWNERS file.

**Comment by leakingtapan** [comment]
+1 👍 Happy to sponsor Dimitri

**Comment by bertinatto** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @dkoshkin, thank you for all your contributions so far :)

I've created PR #416 to add you to the @kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
