### ISSUE TITLE
REQUEST: New membership for code-elinka

### ISSUE THREAD

**Issue by code-elinka** [kubernetes/org#3950]
### GitHub Username

elinka

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@aojea

### Sponsor 2

@soltysh

### List of contributions to the Kubernetes project

- 7 [authored PRs](https://github.com/pulls?q=is%3Apr+author%3Acode-elinka+archived%3Afalse+kubernetes+is%3Amerged+) merged (3 for the [k8s/k8s](https://github.com/kubernetes/kubernetes) and 4 for the [k8s/ingress-gce](https://github.com/kubernetes/ingress-gce) one);
-  [4 PRs](https://github.com/pulls?q=is%3Apr+archived%3Afalse+kubernetes+is%3Aopen+author%3Acode-elinka+) are open.

**Comment by aojea** [comment]
+1

she is an active contributor on the [k8s/ingress-gce](https://github.com/kubernetes/ingress-gce) subproject and I'm looking forward to more contributions on the other projects too

**Comment by soltysh** [comment]
:+1: from my side as well

**Comment by nikhita** [comment]
/assign

@code-elinka  Thank you for all your contributions so far :)

I've created PR #3965 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
