### ISSUE TITLE
REQUEST: New membership for Fish-pro

### ISSUE THREAD

**Issue by Fish-pro** [kubernetes/org#3955]
### GitHub Username

@Fish-pro

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@wzshiming

### Sponsor 2

@Huang-Wei

### List of contributions to the Kubernetes project

prs
+ https://github.com/kubernetes-sigs/application/pull/225
+ https://github.com/kubernetes-sigs/kwok/pull/189
+ https://github.com/kubernetes-sigs/kwok/pull/183
+ https://github.com/kubernetes-sigs/kwok/pull/180
+ https://github.com/kubernetes-sigs/kwok/pull/155
+ https://github.com/kubernetes-sigs/kwok/pull/135
+ https://github.com/kubernetes-sigs/kwok/pull/132
+ https://github.com/kubernetes-sigs/kwok/pull/127
+ https://github.com/kubernetes-sigs/kwok/pull/126
+ https://github.com/kubernetes-sigs/kwok/pull/119
+ https://github.com/kubernetes-sigs/kwok/pull/109

**Comment by mrbobbytables** [comment]
@Fish-pro as a member of one org already you don't need to reapply with sponsors :)
If you want, you can add yourself to kubernetes-sigs. You'll just want to follow our commit message formatting of:
```
Add <username> to <org>
```

**Comment by Fish-pro** [comment]
thanks. @mrbobbytables
