### ISSUE TITLE
REQUEST: New membership for Ritikaa96

### ISSUE THREAD

**Issue by Ritikaa96** [kubernetes/org#3956]
### GitHub Username

Ritikaa96

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@natalisucks

### Sponsor 2

@dims

### List of contributions to the Kubernetes project

- PR Reviewed/Authored:
  - https://github.com/search?q=is%3Apr+author%3ARitikaa96++org%3Akubernetes+org%3Akubernetes-sigs&type=Issues
- Issues responded to: 
  - https://github.com/search?q=commenter%3ARitikaa96+org%3Akubernetes+org%3Akubernetes-sigs&type=Issues
- SIG projects I am involved with: 
  - sig-docs

**Comment by natalisucks** [comment]
Very happy to sponsor your @Ritikaa96! Congratulations on your contributions thus far – we look forward to many more 🎉

**Comment by dims** [comment]
+1 from me! welcome @Ritikaa96

**Comment by nikhita** [comment]
/assign

@Ritikaa96  Thank you for all your contributions so far :)

I've created PR #3965 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by Ritikaa96** [comment]
Thank you @natalisucks !!

**Comment by Ritikaa96** [comment]
> /assign
> 
> @Ritikaa96 Thank you for all your contributions so far :)
> 
> I've created PR #3965 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! tada

Thank you @nikhita . Looking forward to continue working as a k8s member. thanks for the support.
