### ISSUE TITLE
REQUEST: New membership for marwanad

### ISSUE THREAD

**Issue by marwanad** [kubernetes/org#396]
### GitHub Username
@marwanad

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus
- @tariq1890 

### List of contributions to the Kubernetes project
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/17
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/21
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/26
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/31
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/32
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/33
### SIG projects I am involved with
https://github.com/kubernetes-sigs/cluster-api-provider-azure

**Comment by justaugustus** [comment]
+1! Marwan has been a primary maintainer of cluster-api-azure!

**Comment by tariq1890** [comment]
Huge +1 from me :). Marwan has done a phenomenal job in bringing cluster-api-azure to where it is now

**Comment by mrbobbytables** [comment]
Hey there @marwanad, thank you for all your contributions so far :)

I created PR #400  to add you to the @kubernetes-sigs Orgs. You should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
