### ISSUE TITLE
REQUEST: New membership for sathyanarays

### ISSUE THREAD

**Issue by sathyanarays** [kubernetes/org#3960]
### GitHub Username

@sathyanarays

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@nikhita 

### Sponsor 2

@mimowo 

### List of contributions to the Kubernetes project

1. https://github.com/kubernetes/kubernetes/pull/114516
2. https://github.com/kubernetes/kubernetes/issues/114391
3. https://github.com/kubernetes/kubernetes/issues/114650
4. https://github.com/kubernetes/kubernetes/issues/114651
5. https://github.com/kubernetes/kubernetes/pull/114768

**Comment by nikhita** [comment]
+1, thanks for collaborating on fixing the job controller in https://github.com/kubernetes/kubernetes/pull/114516!

**Comment by mimowo** [comment]
+1 on this application, thanks for collaborating on the backoff issues!

**Comment by nikhita** [comment]
/assign

@sathyanarays  Thanks again for all your contributions so far :)

I've created PR #3965 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
