### ISSUE TITLE
REQUEST: New membership for jaehnri

### ISSUE THREAD

**Issue by jaehnri** [kubernetes/org#3961]
### GitHub Username

@jaehnri

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@harshitasao

### Sponsor 2

@JamesLaverack

### List of contributions to the Kubernetes project

PRs and Issues responded to:
- [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Ajaehnri)
- [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx/pulls?q=is%3Apr+author%3Ajaehnri)
- [kubernetes-sigs/kpng](https://github.com/kubernetes-sigs/kpng/pulls?q=is%3Apr+author%3Ajaehnri)

I will be working as a Shadow for the Comms Team in the v1.27 release! Also, I am actively involved with the SIG Network in the KPNG project.

**Comment by JamesLaverack** [comment]
+1 Welcome to the release team 😃

**Comment by harshitasao** [comment]
+1, Welcome to the Comms team! Thank you for volunteering! 🎉

**Comment by nikhita** [comment]
/assign

@jaehnri  Thank you for all your contributions so far :)

I've created PR #3965 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by jaehnri** [comment]
Thank you all! Looking forward to contributing more and more :)
