### ISSUE TITLE
netlify integration for kubernetes-sigs/kind

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/org#397]
### Organization or repository
e.g. kubernetes-sigs/kind

### Name of integration
netlify

### Link to integration website
https://www.netlify.com/

### Describe what is attempting to be accomplished
We're attempting to set up a sub project documentation site, per SIG-docs netlify + hugo is the recommended toolset for this.

### Additional context for request
I _think_ the netlify "site" will have access by one member, the maintainers of kind (@munnerz and I) have created https://github.com/kind-ci-robot as a possible option to jointly manage this. If we went this route, the robot would also need to join kubernetes-sigs.

cc @jimangel

**Comment by BenTheElder** [comment]
Additionally, we're hoping to find a workable pattern for other SIG subprojects to use :sweat_smile: 

I think kubebuilder may already be doing something similar (?) cc @mengqiy

**Comment by mengqiy** [comment]
kubebuilder uses netlify + [gitbook](https://www.gitbook.com). And the webhook site is on kubebuilder domain. i.e. [book.kubebuilder.io](https://book.kubebuilder.io/)
We use the preview feature and auto-deploy feature from Netlify.
@BenTheElder I'd be happy to chat f2f if you need more details.

**Comment by BenTheElder** [comment]
that would be great, thanks!

**Comment by lucperkins** [comment]
I'm currently working on a project for the CNCF that's basically a Hugo/Netlify/[Bulma](https://bulma.io) template: https://github.com/cncf/docs-in-a-box. The goal is to have something that you can `git clone` and go in just a few minutes. The template is still mostly a placeholder but I'll be iterating on it in the coming weeks.

I'm 100% open to feedback on what that template would need to include to be usable out of the box for Kubernetes SIGs.

**Comment by lucperkins** [comment]
I'd like to see it become a living, breathing project with lots of contributors across CNCF projects. Basically I want to do whatever it takes for this to become a "default" solution for Kubernetes SIGs (and other CNCF projects, and even projects outside the CNCF if they so choose).

**Comment by BenTheElder** [comment]
re https://github.com/kubernetes/org/issues/397#issuecomment-456935304 This is _really_ cool btw, I forgot to reply here in addition to slack, I would love to see this too :-) :tada:

**Comment by spiffxp** [comment]
AFAICT you may already have what you need? Can you confirm?

**Third -party access:**
![screen shot 2019-01-24 at 2 13 04 pm](https://user-images.githubusercontent.com/49258/51711935-2f692280-1fe2-11e9-9a73-7f7af37dbc93.png)

**Installed GitHub Apps:**
![screen shot 2019-01-24 at 2 12 14 pm](https://user-images.githubusercontent.com/49258/51711879-12ccea80-1fe2-11e9-9a42-7e941f63e95c.png)

**Comment by spiffxp** [comment]
@mengqiy @BenTheElder so, you both had requests pending, even though this is what the app looked like

I went ahead and approved them.  Please let me know if I broke something that was working.

For the record I based my decision off of the fact that we already have this setup for kubernetes/website, so prior art wins.

**Comment by BenTheElder** [comment]
I think this is all we need from k/org for now, but let me confirm -- I think we may also need to either get a site enabled on the netlify end with some help from sig-docs, or see about getting our bot in the org to enable the site against the bot account somehow..

Thank you!

**Comment by mengqiy** [comment]
@spiffxp Everything works fine for kubebuilder on Netlify.
I don't remember why there is a pending request for kubebuilder. Maybe we can get rid of it.

**Comment by BenTheElder** [comment]
Closing the loop a little: Andrew created a Netlify team under Kubernetes for this, thanks everyone!
