### ISSUE TITLE
REQUEST: New membership for saurav-agarwalla

### ISSUE THREAD

**Issue by saurav-agarwalla** [kubernetes/org#3974]
### GitHub Username

saurav-agarwalla

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

olemarkus

### Sponsor 2

dims

### List of contributions to the Kubernetes project

- PRs reviewed / authored

  https://github.com/kubernetes/cloud-provider-aws/pull/387
  https://github.com/kubernetes/cloud-provider-aws/pull/411
  https://github.com/kubernetes/cloud-provider-aws/pull/448
  https://github.com/kubernetes/cloud-provider-aws/pull/484

- Issues responded to (this is also created by me so not sure if it counts)

  https://github.com/kubernetes/cloud-provider-aws/issues/306

- SIG projects I am involved with

  https://github.com/kubernetes/cloud-provider-aws

**Comment by dims** [comment]
@saurav-agarwalla i see way more ... https://github.com/pulls?q=author%3Asaurav-agarwalla+archived%3Afalse+sort%3Aupdated-desc+org%3Akubernetes

+1 from me.

**Comment by olemarkus** [comment]
Thanks for all your contributions. Looking forward to many more. 
+1

**Comment by nikhita** [comment]
/assign

@saurav-agarwalla Thank you for all your contributions so far :)

I've created PR #3986 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

**Comment by saurav-agarwalla** [comment]
Thank you @nikhita and thanks @dims and @olemarkus for your sponsorship.
