### ISSUE TITLE
REQUEST: New membership for sumitranr

### ISSUE THREAD

**Issue by sumitranr** [kubernetes/org#398]
### GitHub Username
@sumitranr

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp 
- @tpepper 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
SIG-release: Release debs/rpms patches for kubernetes (ex: 1.11.6, 1.12.4, 1.13.1).

**Comment by tpepper** [comment]
@sumitranr has been an active member of the Kubernetes release team in 2018, is continuing in 2019 and has also volunteered to contribute on the nascent patch release management team.  I fully support membership.

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by mrbobbytables** [comment]
@sumitranr thank you for all the work you've done so far :)

I created PR #400 to add you to the @kubernetes Org. With that getting merged, you should get a membership invite notification. 

Welcome to @kubernetes! 🎉

/assign
