### ISSUE TITLE
REQUEST: New membership for rayandas

### ISSUE THREAD

**Issue by rayandas** [kubernetes/org#3982]
### GitHub Username

@rayandas

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@palnabarun 

### Sponsor 2

@Priyankasaggu11929

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api/pull/6179
  - https://github.com/kubernetes/test-infra/pull/25359
  - https://github.com/kubernetes/test-infra/pull/24980
  - https://github.com/kubernetes/test-infra/pull/24979
  - https://github.com/kubernetes/test-infra/pull/24462
  - https://github.com/kubernetes/test-infra/pull/23845
  - https://github.com/kubernetes/test-infra/pull/23339
  - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2692
  - https://github.com/kubernetes/test-infra/pull/19851
- Issues  responded to / created
  -  https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2683
  - https://github.com/kubernetes/dns/issues/481
  - https://github.com/kubernetes/test-infra/issues/23822
  - https://github.com/kubernetes-sigs/cluster-api/issues/6141
  - https://github.com/kubernetes/test-infra/issues/18599

**Comment by tokt** [comment]
+1 and thank you!

**Comment by Priyankasaggu11929** [comment]
+1. Welcome :)

**Comment by nikhita** [comment]
Hi, sponsors need to be listed as a reviewer/approver in an OWNERS file in one of @kubernetes or @kubernetes-sigs orgs. It looks like @tokt is not (please correct me if I'm mistaken!).

**Comment by rayandas** [comment]
@nikhita Updated the description and added @palnabarun as a sponsor.

**Comment by palnabarun** [comment]
+1. Welcome again! 🎉

**Comment by nikhita** [comment]
/assign

@rayandas Thank you for all your contributions so far :)

I've created PR #4001 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
