### ISSUE TITLE
REQUEST: New membership for daman1807

### ISSUE THREAD

**Issue by daman1807** [kubernetes/org#3983]
### GitHub Username

@daman1807

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jayunit100

### Sponsor 2

@astoycos

### List of contributions to the Kubernetes project

- PRs reviews/authored
  - SIG KPNG
https://github.com/kubernetes-sigs/kpng/pull/399
https://github.com/kubernetes-sigs/kpng/pull/403
https://github.com/kubernetes-sigs/kpng/pull/417
  - K/K
https://github.com/kubernetes/kubernetes/pull/115207
https://github.com/kubernetes/kubernetes/pull/115283
  - k/test-infra
 https://github.com/kubernetes/test-infra/pull/28511
 https://github.com/kubernetes/test-infra/pull/28523

I'm actively involved with SIG KPNG and SIG Network (Netpol Testing)

**Comment by jayunit100** [comment]
Damans volume of work is self evident, both on the networkpolicy optimization to help us get it fully adopted in openshift and also in kpng, to make the IPVS modernized and fullstate based.  

cc @astoycos @mcluseau @rajaskakodkar

**Comment by astoycos** [comment]
++++1 Thanks for all the effort on KPNG and in upstream netpol tests @daman1807!!

**Comment by rajaskakodkar** [comment]
+100 thanks Daman for all your work in KPNG and netpol.

**Comment by nikhita** [comment]
/assign

@daman1807 Thank you for all your contributions so far :)

I've created PR #3986 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
