### ISSUE TITLE
REQUEST: New membership for g-gaston

### ISSUE THREAD

**Issue by g-gaston** [kubernetes/org#3985]
### GitHub Username

@g-gaston

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@fabriziopandini

### Sponsor 2

@dlipovetsky

### List of contributions to the Kubernetes project

- PRs
  - https://github.com/kubernetes-sigs/cluster-api/pull/5573
  - https://github.com/kubernetes-sigs/cluster-api/pull/6555
  - https://github.com/kubernetes-sigs/etcdadm/pull/239
  - https://github.com/kubernetes-sigs/etcdadm/pull/242
  - https://github.com/kubernetes-sigs/etcdadm/pull/290
- SIG projects I am involved with
  - cluster-api

**Comment by fabriziopandini** [comment]
Welcome on board! 
+1

**Comment by dlipovetsky** [comment]
+1

Thanks for your contributions so far, and those yet to come!

**Comment by fabriziopandini** [comment]
fyi adding links to some more work being done by @g-gaston 
- https://github.com/kubernetes-sigs/cluster-api/pulls?q=author%3Ag-gaston+
- https://github.com/kubernetes-sigs/cluster-api/issues?q=author%3Ag-gaston+

**Comment by nikhita** [comment]
/assign

@g-gaston Thank you for all your contributions so far :)

I've created PR #3986 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
