### ISSUE TITLE
REQUEST: Netlify site for nfd.sigs.k8s.io

### ISSUE THREAD

**Issue by iranzo** [kubernetes/org#3989]
### Repository

https://github.com/kubernetes-sigs/node-feature-discovery/

### Project domain

nfd.sigs.k8s.io

### Additional context for request

Project already has netlify rendering at https://kubernetes-sigs-nfd.netlify.app
 
And  via https://github.com/kubernetes/k8s.io/pull/4653 was expecting for 'https://nfd.sigs.k8s.io' to get routed to that site, but seems that some piece is missing in the netlify setup.

I'm opening this to get this sorted out

Thanks

**Comment by iranzo** [comment]
@mrbobbytables this is similar to what you did for KMM in https://github.com/kubernetes/org/issues/3839, is there anything we should do to get this sorted out?

TIA

**Comment by iranzo** [comment]
Also pinging @cblecker as he did work on the KMM one

**Comment by cblecker** [comment]
/assign
Opened a ticket with Netlify

**Comment by cblecker** [comment]
This is now set up correctly.
/close

**Comment by dims** [comment]
@cblecker curious, what was the problem?

**Comment by cblecker** [comment]
it just wasn't set up originally in Netlify and I misread a button when i tried to set it up this morning

**Comment by dims** [comment]
ah! thanks.
