### ISSUE TITLE
REQUEST: New membership for @taragu

### ISSUE THREAD

**Issue by taragu** [kubernetes/org#399]
### GitHub Username
@taragu

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@stevekuznetsov 
@cjwagner 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
PRs authored: 
https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+is%3Aclosed+author%3Ataragu
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aclosed+author%3Ataragu
PRs reviewed:
https://github.com/kubernetes/test-infra/pull/10401
https://github.com/kubernetes/test-infra/pull/10732
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/71487
https://github.com/kubernetes/kubernetes/issues/69106
https://github.com/kubernetes/kubernetes/issues/70704
https://github.com/kubernetes/test-infra/issues/10514
https://github.com/kubernetes/test-infra/issues/10351
https://github.com/kubernetes/test-infra/issues/9836
https://github.com/kubernetes/test-infra/issues/9431

- SIG projects I am involved with
sig-testing
sig-release: shadowing test-infra for the 1.14 release

**Comment by cjwagner** [comment]
+1 @taragu has made some great contributions to `k/test-infra`. In particular Tara added suggestion support to the golint plugin so that common lint errors can be fixed with a click of a button.
Thanks for your contributions!

**Comment by stevekuznetsov** [comment]
+1 

@taragu has been active and eager to take on issues both in test infrastructure and `kubernetes`. Her work on the lint plugin has been super!

**Comment by mrbobbytables** [comment]
@taragu Thank you for all the work you've put in :)

I've created PR #416 to add you to both the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification from both.

Welcome aboard! :tada:

/assign

**Comment by taragu** [comment]
@mrbobbytables thank you! 😄 also thanks for the sponsorship! @cjwagner @stevekuznetsov
