### ISSUE TITLE
REQUEST: New membership for kidddddddddddddddddddddd

### ISSUE THREAD

**Issue by kidddddddddddddddddddddd** [kubernetes/org#3993]
### GitHub Username

@kidddddddddddddddddddddd

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sanposhiho

### Sponsor 2

@kerthcet

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/pulls?q=is%3Amerged+is%3Apr+author%3Akidddddddddddddddddddddd+archived%3Afalse+
- Issues assigned
https://github.com/issues?q=is%3Aissue+archived%3Afalse+assignee%3Akidddddddddddddddddddddd

**Comment by sanposhiho** [comment]
+1

Thanks for your contribution so far. I'm looking forward to working more with you from here :)

**Comment by nikhita** [comment]
/assign

@kidddddddddddddddddddddd Thank you for all your contributions so far :)

I've created PR #4001 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
