### ISSUE TITLE
REQUEST: Create new repository sigs.k8s.io/logical-cluster (sig-cluster-lifecycle)

### ISSUE THREAD

**Issue by vincepri** [kubernetes/org#3995]
### New repo, staging repo, or migrate existing

New repository

### Is it a staging repo?

yes

### Requested name for new repository

logical-cluster

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

vincepri, fabrizio.pandini

### Who should have write access?

vincepri, fabrizio.pandini

### Who should be listed as approvers in OWNERS?

vincepri, fabrizio.pandini

### Who should be listed in SECURITY_CONTACTS?

vincepri, fabrizio.pandini

### What should the repo description be?

A set of APIs to improve the Kubernetes user experience for cluster administration by offering utilities to interact with fleet of clusters which can be managed by Cluster API, or other entities (like cloud providers). The goal of the repository is going to be to provide high level interfaces and tools to generate clients to interact with many clusters, provide a simple bridge with Controller Runtime, and define common set of tools.

### What SIG and subproject does this fall under?

sig-cluster-lifecycle

### Please provide references to appropriate approval for this new repo

- Discussed with Cluster API and SIG Cluster Lifecycle leads at the [January 24th](https://docs.google.com/document/d/1Gmc7LyCIL_148a9Tft7pdhdee0NBHdOfHS1SAF0duI4/edit#heading=h.xm2jvfwtcfuz) and [January 25th](https://docs.google.com/document/d/1ushaVqAKYnZ2VN_aa3GyKlS4kEd6bSug13xaXOakAQI/edit#heading=h.yvh1c5okfq9s) community meetings.
- Related Slack discussion in the [SIG CL leads](https://kubernetes.slack.com/archives/C9L3M2G82/p1675094512347599) channel.

### Additional context for request

The repository is going to be providing facilities to easily manage set of Cluster API clusters to start with, to manage their lifecycle, and create management-style high level controllers across many (fleet of) clusters.

_No response_

**Comment by nikhita** [comment]
/assign

Will create the repo by tomorrow

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/logical-cluster

Also created:
- https://github.com/kubernetes/org/pull/3999 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/7085 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by vincepri** [comment]
Thanks @nikhita !

**Comment by nikhita** [comment]
Teams have been granted access and repo has been added to sigs.yaml. Closing.
