### ISSUE TITLE
REQUEST: New membership for inteon

### ISSUE THREAD

**Issue by inteon** [kubernetes/org#3996]
### GitHub Username

@inteon

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@vincepri

### Sponsor 2

@sbueringer

### List of contributions to the Kubernetes project

- found & fixed an upstream CEL bug: https://github.com/kubernetes/kubernetes/pull/114857
- https://github.com/kubernetes-sigs/controller-runtime/pull/2158
- https://github.com/kubernetes-sigs/controller-runtime/pull/2147
- https://github.com/kubernetes-sigs/controller-runtime/pull/2122
- https://github.com/kubernetes-sigs/controller-runtime/pull/2121
- https://github.com/kubernetes-sigs/controller-runtime/pull/1674

**Comment by sbueringer** [comment]
+1 Thx for your work on controller-runtime and welcome :)

**Comment by vincepri** [comment]
+1

**Comment by nikhita** [comment]
/assign

@inteon Thank you for all your contributions so far :)

I've created PR #4001 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
