### ISSUE TITLE
Organization domain verification

### ISSUE THREAD

**Issue by cblecker** [kubernetes/org#4]
https://blog.github.com/changelog/2018-08-07-domain-verification/
https://help.github.com/articles/verifying-your-organization-s-domain/
https://github.com/organizations/kubernetes/settings/domains

I'd like to verify our domains with GitHub. The TL;DR is you create a TXT record, and then you get a verified badge. We should do this for all active orgs.

cc: @kubernetes/owners @thockin @ixdy

**Comment by ixdy** [comment]
Seems like a good idea. I can help with the DNS side, but I need an owner to help me on the GitHub side. (Do we need to wait for consensus? Or do we just do this?)

**Comment by cblecker** [comment]
I don't think this is controversial at all, so I think we could probably go ahead whenever you have time. Do you want to tackle this today, or would another day be better for you @ixdy ?

**Comment by cblecker** [comment]
Sync'd with @ixdy and was able to verify both kubernetes.io and k8s.io against all our orgs :)
