### ISSUE TITLE
Add @yliaog to kubernetes-client

### ISSUE THREAD

**Issue by yliaog** [kubernetes/org#40]
### GitHub Username
@yliaog

### Organization you are requesting membership in
@kubernetes-client

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp
- @mbohlool

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by yliaog** [comment]
per https://github.com/kubernetes/test-infra/pull/9122

**Comment by spiffxp** [comment]
/close
invite sent, thanks!
