### ISSUE TITLE
REQUEST: New membership for @danielvegamyhre

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes/org#4000]
### GitHub Username

@danielvegamyhre

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ahg-g

### Sponsor 2

@Huang-Wei

### List of contributions to the Kubernetes project

1. Option to ignore existing pods' preferred inter-pod affinities if the incoming pod has no preferred inter-pod affinities https://github.com/kubernetes/kubernetes/pull/114393
2. Job controller changes to support Elastic Indexed Jobs https://github.com/kubernetes/kubernetes/pull/115349 
3. Update Job docs to include info about enabling pod-to-pod communication within a job using pod hostnames https://github.com/kubernetes/website/pull/37771
4. Add best practices to getting started with GCE docs https://github.com/kubernetes/kops/pull/14569
5. Fix shell block on Job task page https://github.com/kubernetes/website/pull/38180
6. Cherry pick job controller changes into v1.24 (done but awaiting approval): https://github.com/kubernetes/kubernetes/pull/115457
7. Cherry pick job controller changes into v1.25 (done but awaiting approval): https://github.com/kubernetes/kubernetes/pull/115460
8. Cherry pick job controller changes into v1.26 (done but awaiting approval): https://github.com/kubernetes/kubernetes/pull/115462
9. Validation changes to support Elastic Indexed Jobs (in progress): https://github.com/kubernetes/kubernetes/pull/115236

**Comment by ahg-g** [comment]
/lgtm 

Thanks Daniel, looking forward for more contributions and collaboration!

**Comment by Huang-Wei** [comment]
+1

**Comment by nikhita** [comment]
/assign

@danielvegamyhre Thank you for all your contributions so far :)

I've created PR #4001 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by danielvegamyhre** [comment]
@nikhita Thank you! Quick question, I noticed the linked PR #4001 was merged last night but I haven't received any membership invite notification as far as I can tell. Would this be in my Github notifications? Does it take some time for this to occur?

**Comment by Huang-Wei** [comment]
+1

(I +1ed yesterday, but somehow it's gone... no idea why)
