### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/kueue

### ISSUE THREAD

**Issue by moficodes** [kubernetes/org#4002]
### Repository

kubernetes-sigs/kueue

### Project domain

*.kueue.sigs.k8s.io

### Additional context for request

We would want to be able to have the domain for both kueue.sigs.k8s.io and vX-X.kueue.sigs.k8s.io for future versions of kueue.

**Comment by moficodes** [comment]
@alculquicondor ☝🏼

**Comment by mrbobbytables** [comment]
Netlify is setup, but build failed
https://app.netlify.com/sites/kubernetes-sigs-kueue/deploys/63e1a1026a6e653095d88cb0

**Comment by mrbobbytables** [comment]
quick look, the netlify.toml doesn't specify a build dir so its defaulting to the root.
I manually updated it in netlify to use `site` and that worked, but should correct in the netlify.toml file 

For now the site is live here: https://kubernetes-sigs-kueue.netlify.app/

**Comment by mrbobbytables** [comment]
Everything is configured, going to go ahead and close

/close
