### ISSUE TITLE
REQUEST: New membership for voelzmo

### ISSUE THREAD

**Issue by voelzmo** [kubernetes/org#4015]
### GitHub Username

voelzmo

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

jbartosik

### Sponsor 2

gjtempleton

### List of contributions to the Kubernetes project

- Involved in the autoscaling SIG, mostly focused on vertical-pod-autoscaler
- PRs authored by me in github.com/kubernetes: https://github.com/pulls?q=is%3Apr+author%3Avoelzmo+archived%3Afalse+is%3Aclosed+org%3Akubernetes
  - selected examples
    - VPA feature to control scaling behavior: https://github.com/kubernetes/autoscaler/pull/4831
    - Fixing a VPA bug with OOMkill behavior: https://github.com/kubernetes/autoscaler/pull/5326
- Issues with participation by me in github.com/kubernetes: https://github.com/issues?q=is%3Aissue+archived%3Afalse+org%3Akubernetes+involves%3Avoelzmo+is%3Aclosed+
  - selected examples
    - https://github.com/kubernetes/autoscaler/issues/5421
    - https://github.com/kubernetes/autoscaler/issues/5318
    - https://github.com/kubernetes/autoscaler/issues/5455
    - https://github.com/kubernetes/autoscaler/issues/5452

**Comment by voelzmo** [comment]
@jbartosik, @gjtempleton, please have a look. Thanks!

**Comment by gjtempleton** [comment]
+1, @voelzmo's been an active contributor in SIG Autoscaling for an extended period, helping to drive forward the VPA, looking forward to their future contributions!

**Comment by jbartosik** [comment]
+1, @voelzmo has been helping with VPA for an extended period of time (sending PRs, helping with reviews, answering on issues).

**Comment by mrbobbytables** [comment]
Thanksfor all your contributions so far :)

I've created PR #4033  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
