### ISSUE TITLE
REQUEST: New membership for tzneal

### ISSUE THREAD

**Issue by tzneal** [kubernetes/org#4016]
### GitHub Username

@tzneal

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@SergeyKanzhelev

### Sponsor 2

@dims

### List of contributions to the Kubernetes project

PRS
- https://github.com/kubernetes/autoscaler/pull/4873
- https://github.com/kubernetes/kubernetes/pull/112631
- https://github.com/kubernetes/kubernetes/pull/115367
- https://github.com/kubernetes/kubernetes/pull/115643
- https://github.com/kubernetes/kubernetes/pull/115644
- https://github.com/kubernetes/community/pull/7084

Issues
- https://github.com/kubernetes/kubernetes/issues/115459

SIG Projects
- SIG-Node Sidecar WG

**Comment by SergeyKanzhelev** [comment]
+1, thank you for your active work in Sidecar WG and ongoing contributions!

**Comment by dims** [comment]
+1 from me! welcome aboard @tzneal
