### ISSUE TITLE
REQUEST: New membership for  daman1807

### ISSUE THREAD

**Issue by daman1807** [kubernetes/org#4022]
### GitHub Username

@daman1807

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jayunit100

### Sponsor 2

@astoycos

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/kpng/pull/399
- https://github.com/kubernetes-sigs/kpng/pull/403
- https://github.com/kubernetes-sigs/kpng/pull/417
- https://github.com/kubernetes-sigs/kpng/pull/443

**Comment by astoycos** [comment]
/lgtm 

Thanks @daman1807!

**Comment by jayunit100** [comment]
/lgtm 
Thanks sir !
/approve

**Comment by mrbobbytables** [comment]
Just an FYI for the future, you don't have to open a request / get sponsors etc if you're already an org member in one org, you can PR yourself directly in there as long as it follows our git commit message format :)

Either way, you should get an invite to k-sigs as soon as #4033 merges 👍
