### ISSUE TITLE
REQUEST: New membership for deobieta

### ISSUE THREAD

**Issue by deobieta** [kubernetes/org#4029]
### GitHub Username

deobieta

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ameukam

### Sponsor 2

@puerco

### List of contributions to the Kubernetes project

- PRs
https://github.com/kubernetes/k8s.io/pull/4797
https://github.com/kubernetes/k8s.io/pull/4118
https://github.com/kubernetes/k8s.io/pull/2724
https://github.com/kubernetes/k8s.io/pull/2539

- Issues
https://github.com/kubernetes/k8s.io/issues/4684
https://github.com/kubernetes/k8s.io/issues/3667

- [sig-k8s-infra](https://git.k8s.io/community/sig-k8s-infra)

cc @ameukam @puerco

**Comment by ameukam** [comment]
+1!
Gabriel helped us build some aspects of infrastructure for `registry.k8s.io` and want to help for https://github.com/kubernetes/k8s.io/issues/4654.

**Comment by puerco** [comment]
+1!
@deobieta has been working on k8s infra improvements and he will be super valuable to k8s infra as we are shifting more loads to AWS. Welcome Gabo!

**Comment by deobieta** [comment]
Thank you. @ameukam @puerco

**Comment by mrbobbytables** [comment]
Thanksfor all your contributions so far :)

I've created PR #4033  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to kubernetes! 🎉
