### ISSUE TITLE
Please add `dims` as admin for k8s.io/utils repo

### ISSUE THREAD

**Issue by dims** [kubernetes/org#403]
we have a few PRs in the queue that the cncf bot has logged as bad. the PRs are just moving git commits from one repo to another and the bot is not helpful at all. see details in https://github.com/cncf/foundation/issues/26#issuecomment-456842341

the current work around is to run `/override`, so can you please make me an admin to be able to run that command?

Thanks,
Dims

**Comment by cblecker** [comment]
PRs welcome 😜 : https://github.com/kubernetes/org/blob/39ba9bb6358462a1015c0107bdcbb0ab2928df5b/config/kubernetes/org.yaml#L1914-L1923

**Comment by dims** [comment]
Duh! thanks :) https://github.com/kubernetes/org/pull/405

**Comment by nikhita** [comment]
Fixed by https://github.com/kubernetes/org/pull/405. Closing.

/close
