### ISSUE TITLE
REQUEST: New membership for faiq

### ISSUE THREAD

**Issue by faiq** [kubernetes/org#4031]
### GitHub Username

@faiq

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@richardcase

### Sponsor 2

@dlipovetsky

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=author%3Afaiq+
-  https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pulls?q=is%3Apr+author%3Afaiq+is%3Aclosed
- https://github.com/kubernetes-sigs/kind/pull/1690
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/708

**Comment by dlipovetsky** [comment]
+1 

@faiq, thanks for all your contributions to Cluster API. Looking forward to more!

**Comment by richardcase** [comment]
+1

Yes please, @faiq thank you for all your contributions to CAPI and its providers 👍

**Comment by nikhita** [comment]
/assign

@faiq  Thank you for all your contributions so far :)

I've created PR #4042 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
