### ISSUE TITLE
REQUEST: kubernetes-sigs cross-membership for @afirth

### ISSUE THREAD

**Issue by afirth** [kubernetes/org#4035]
### Organization or Repo

kubernetes-sigs

### User affected

@afirth

### Describe the issue

current kubernetes member [member list](https://github.com/orgs/kubernetes/people?query=afirth), opening issue as described in [the docs](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem) to request membership in the kubernetes-sigs org as well

**Comment by nikhita** [comment]
@afirth please feel free to create a PR to add yourself in! You don't need an issue if you are already a @kubernetes org member.
