### ISSUE TITLE
REQUEST: New membership for damdo

### ISSUE THREAD

**Issue by damdo** [kubernetes/org#4039]
### GitHub Username

damdo

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

Fedosin

### Sponsor 2

alexander-demicev

### List of contributions to the Kubernetes project

PRs:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2421
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2528
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2430
- https://github.com/kubernetes-sigs/cluster-api/pull/8162
- https://github.com/kubernetes-sigs/kind/pull/1795
- https://github.com/kubernetes/cloud-provider-alibaba-cloud/pull/323
- https://github.com/kubernetes-sigs/cluster-api/pull/5801
- https://github.com/kubernetes-sigs/controller-runtime/pull/1862

Mostly involved in cluster-api

**Comment by alexander-demicev** [comment]
+1 welcome 🥳

**Comment by Fedosin** [comment]
+1
welcome to the org 🎉

**Comment by fabriziopandini** [comment]
Welcome!

**Comment by sbueringer** [comment]
Welcome :)

**Comment by nikhita** [comment]
/assign

@damdo Thank you for all your contributions so far :)

I've created PR #4042 to add you to the Kubernetes SIGs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉
