### ISSUE TITLE
REQUEST: New membership for ttakahashi21

### ISSUE THREAD

**Issue by ttakahashi21** [kubernetes/org#4040]
### GitHub Username

@ttakahashi21

### Organization you are requesting membership in

kubernetes, kubernetes-csi

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@msau42

### Sponsor 2

@xing-yang

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  -  https://github.com/kubernetes/kubernetes/pull/113186
  - https://github.com/kubernetes-csi/external-provisioner/pull/805
  - https://github.com/kubernetes/website/pull/37802
  - https://github.com/kubernetes/website/pull/37628

**Comment by msau42** [comment]
+1

**Comment by xing-yang** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
@ttakahashi21, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4059 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
