### ISSUE TITLE
REQUEST: New membership for @Sajiyah-Salat

### ISSUE THREAD

**Issue by Sajiyah-Salat** [kubernetes/org#4050]
### GitHub Username

@Sajiyah-Salat

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@camilamacedo86

### Sponsor 2

@shaneutt 

### List of contributions to the Kubernetes project

Hello, I would like to be a member of Kubernetes.
Here are the details of my work in Kubernetes:
PRs:
https://github.com/kubernetes/website/pull/39446
https://github.com/kubernetes/kops/pull/15059
https://github.com/kubernetes/website/pull/39485
https://github.com/kubernetes-sigs/gateway-api/pull/1672
https://github.com/kubernetes-sigs/kubebuilder/pull/3225
Issues I have authored.
https://github.com/kubernetes-sigs/kubebuilder/issues/3162
https://github.com/kubernetes-sigs/kubebuilder/issues/3152
https://github.com/kubernetes/website/issues/38730
My first task in the morning with a cup of black tea is to look at issues in the Kubernetes repository. I may not have complete knowledge, but I am always eager to learn. Check out the good first issues of the Kubenetes repository, and there you will find my comments asking more about the issues and how to solve them. I hope I will get membership in kubernetes repository.
Thank you!

**Comment by Priyankasaggu11929** [comment]
Hello @camilamacedo86, just a friendly ping. This membership request needs a +1 from you as sponsor to move ahead. Thank you. :)

**Comment by camilamacedo86** [comment]
lgtm +1 to be a member

**Comment by camilamacedo86** [comment]
Hello, 

I am not 100% sure with @Sajiyah-Salat comply with already:

> Members are continuously active contributors to the community. They can have issues, and PRs assigned to them, participate in SIGs through GitHub teams, and pre-submit tests are automatically run for their PRs. Members are expected to remain active contributors to the community.

She is beginning to learn and contribute to the projects.

But I am happy to help her and answer questions in this process.

**Comment by Priyankasaggu11929** [comment]
Thanks so much for the feedback @camilamacedo86.

@Sajiyah-Salat, taking into consideration the feedback received, my suggestion is that you continue to actively participate in the project and resubmit your membership request after receiving approval from all sponsors.

Thank you for your hard work and contributions so far. I am excited to see more of your valuable contributions in the future. :slightly_smiling_face: 

/close

**Comment by camilamacedo86** [comment]
HI @Priyankasaggu11929, 

I am looking that it to was closed based on my comment https://github.com/kubernetes/org/issues/4050#issuecomment-1491776690, but that was not my intention.

I just do not know how much contribution and how long the person needs to contribute to the projects to be a member. However, she is pushing herself to do so, and I am more than happy to sponsor and support here.

So, if the contributions made so far are OK. It has my /lgtm 

Sorry for any misunderstanding.

**Comment by Priyankasaggu11929** [comment]
/reopen

Thanks for the clarification (& apologies for misunderstanding). 

@Sajiyah-Salat , thanks again for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4150 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
