### ISSUE TITLE
REQUEST: migrate dims/community-images

### ISSUE THREAD

**Issue by daman1807** [kubernetes/org#4054]
### New repo, staging repo, or migrate existing

migrate existing (https://github.com/dims/community-images)

### Is it a staging repo?

no

### Requested name for new repository

community-images

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

dims

### Who should have write access?

dims

### Who should be listed as approvers in OWNERS?

dims

### Who should be listed in SECURITY_CONTACTS?

dims

### What SIG and subproject does this fall under?

sig-k8s-infra

### Please provide references to appropriate approval for this new repo

https://kubernetes.slack.com/archives/CCK68P2Q2/p1677648264566709

### Additional context for request

This repository will be home to a kubectl plugin that displays images running in a Kubernetes cluster that were pulled from community-owned repositories and warn the user to switch repositories if needed, helping in migrating references from legacy **k8s.gcr.io** to **registry.k8s.io** registry.

**Comment by ameukam** [comment]
+1 (with SIG k8s Infra chair hat)

**Comment by dims** [comment]
+1 from me.

**Comment by daman1807** [comment]
@ameukam gotcha!

**Comment by daman1807** [comment]
@ameukam I have updated the structure of the repository.

**Comment by ameukam** [comment]
Repo transferred: https://github.com/kubernetes-sigs/community-images

I opened:
  - https://github.com/kubernetes/org/pull/4068
  - https://github.com/kubernetes/community/pull/7168

Once those PRs are merged, we can close the issue.

**Comment by nikhita** [comment]
@dims good to close this issue now?

**Comment by dims** [comment]
yes please

/close
