### ISSUE TITLE
REQUEST: New membership for kayrus

### ISSUE THREAD

**Issue by kayrus** [kubernetes/org#4056]
### GitHub Username

@kayrus

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jichenjc

### Sponsor 2

@zetaab

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/cloud-provider-openstack/pull/2135
- https://github.com/kubernetes/cloud-provider-openstack/pull/2134
- https://github.com/kubernetes/cloud-provider-openstack/pull/1384
- https://github.com/kubernetes/cloud-provider-openstack/pull/1382
- https://github.com/kubernetes/cloud-provider-openstack/pull/1311
- https://github.com/kubernetes/cloud-provider-openstack/pull/1123
- https://github.com/kubernetes/cloud-provider-openstack/pull/1041
- https://github.com/kubernetes/kubernetes/pull/33584

and others...

I'm also an active contributor to https://github.com/gophercloud/gophercloud and https://github.com/terraform-provider-openstack/terraform-provider-openstack

**Comment by jichenjc** [comment]
+1 

thanks for the all the great contributions you made :)

**Comment by kayrus** [comment]
@jichenjc thanks :)
I haven't heard for a while from @lingxiankong. @zetaab maybe you can approve?

**Comment by jichenjc** [comment]
I think we need 2 +1 then someone is going to approve, I can only be sponsor , not approver ..

**Comment by kayrus** [comment]
That''s what I'm asking @zetaab for.

**Comment by zetaab** [comment]
+1

**Comment by kayrus** [comment]
@Priyankasaggu11929 could you please let me know what is the next step? Should I submit a PR?

**Comment by Priyankasaggu11929** [comment]
@kayrus, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4065 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

**Comment by kayrus** [comment]
Thank you all.
@jichenjc @zetaab how can I run `/override openstack-cloud-csi-manila-e2e-test` commands? k8s-ci-robot fails with `Unauthorized`: https://github.com/kubernetes/cloud-provider-openstack/pull/2141#issuecomment-1453263554

**Comment by nikhita** [comment]
> @jichenjc @zetaab how can I run /override openstack-cloud-csi-manila-e2e-test commands? k8s-ci-robot fails with Unauthorized: https://github.com/kubernetes/cloud-provider-openstack/pull/2141#issuecomment-1453263554

@kayrus you'll need to be a repo admin for that:

https://github.com/kubernetes/org/blob/029e2b81e5ce29cbccc3b5fa910bbf567a1f60a1/config/kubernetes/provider-openstack/teams.yaml#L2-L10

**Comment by kayrus** [comment]
Shall I create a new ticket for an approval to join kubernetes/cloud-provider-openstack?

**Comment by nikhita** [comment]
> Shall I create a new ticket for an approval to join kubernetes/cloud-provider-openstack?

You can just create a PR to add yourself. Once the relevant folks lgtm/approve the PR, you'll be good to go!
