### ISSUE TITLE
REQUEST: New membership for PatrickGhadban

### ISSUE THREAD

**Issue by PatrickGhadban** [kubernetes/org#4057]
### GitHub Username

@PatrickGhadban

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@khoang98

### Sponsor 2

@jacobwolfaws

### List of contributions to the Kubernetes project

Authored PRs:
- https://github.com/kubernetes-sigs/aws-file-cache-csi-driver/pull/1
- https://github.com/kubernetes-sigs/aws-file-cache-csi-driver/pull/8
- https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/302

Reviewed PRs:
- https://github.com/kubernetes-sigs/aws-file-cache-csi-driver/pull/4
- https://github.com/kubernetes-sigs/aws-file-cache-csi-driver/pull/5
- https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/295

Issues responded to:
- https://github.com/kubernetes-sigs/aws-fsx-csi-driver/issues/255

**Comment by jacobwolfaws** [comment]
+1

**Comment by khoang98** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
Hi @PatrickGhadban, thank you for raising the membership request. :slightly_smiling_face: 

Could you please verify the organization/company affiliation of @khoang98 ? We require two sponsors from separate companies or organizations.

**Comment by Priyankasaggu11929** [comment]
Hello @PatrickGhadban, just following up on my above comment https://github.com/kubernetes/org/issues/4057#issuecomment-1451713254. Thank you!
