### ISSUE TITLE
REQUEST: New membership for ivelichkovich

### ISSUE THREAD

**Issue by ivelichkovich** [kubernetes/org#4060]
### GitHub Username

@ivelichkovich

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@jpbetz

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/kubernetes/pull/115816 (merged)
- https://github.com/kubernetes/kubernetes/pull/115771 (draft of upcoming work)
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3716-admission-webhook-match-conditions
- https://github.com/kubernetes/enhancements/pull/3855 (working with community to try to find solution)
- regularly attend sig-api-machinery, sig-auth, sig-api-machinery-cel calls

**Comment by jpbetz** [comment]
/lgtm

Thanks @ivelichkovich for your contributions!

**Comment by dims** [comment]
+1 welcome @ivelichkovich !

**Comment by Priyankasaggu11929** [comment]
/assign

@ivelichkovich thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4065 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
