### ISSUE TITLE
REQUEST: New membership for zwpaper

### ISSUE THREAD

**Issue by zwpaper** [kubernetes/org#4061]
### GitHub Username

zwpaper

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

Huang-Wei

### Sponsor 2

wzshiming

### List of contributions to the Kubernetes project

PRs authored / reviewed:
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/522
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/519
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/506
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/514
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/521
- https://github.com/kubernetes-sigs/kwok/pull/244
- https://github.com/kubernetes-sigs/kwok/pull/226
- https://github.com/kubernetes-sigs/kwok/pull/289
- https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/77
https://github.com/kubernetes-sigs/node-feature-discovery/pull/623

Issues responded to:
- https://github.com/kubernetes-sigs/scheduler-plugins/issues/485
- https://github.com/kubernetes-sigs/scheduler-plugins/issues/516
- https://github.com/kubernetes-sigs/scheduler-plugins/issues/445
- https://github.com/kubernetes-sigs/scheduler-plugins/issues/446
- https://github.com/kubernetes-sigs/kwok/issues/224
- https://github.com/kubernetes-sigs/kwok/issues/259
- https://github.com/kubernetes-sigs/node-feature-discovery/issues/630
- https://github.com/kubernetes-sigs/node-feature-discovery/issues/600

SIG projects I am involved with
- https://github.com/kubernetes-sigs/scheduler-plugins
- https://github.com/kubernetes-sigs/kwok
- https://github.com/kubernetes-sigs/node-feature-discovery
- https://github.com/kubernetes-sigs/node-feature-discovery-operator

**Comment by Huang-Wei** [comment]
+1, looking forward to seeing more contributions in the future!

**Comment by wzshiming** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@zwpaper, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4065 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
