### ISSUE TITLE
REQUEST: Extending membership for shyamjvs to kubernetes-sigs

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/org#4062]
### GitHub Username

@shyamjvs

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@wojtek-t

### List of contributions to the Kubernetes project

I'm already a contributor of the Kubernetes org for few years - https://github.com/kubernetes/kubernetes/graphs/contributors.

Requesting to extend membership to Kubernetes-sigs manually due to - https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem.

**Comment by wojtek-t** [comment]
LGTM

**Comment by ameukam** [comment]
@shyamjvs As an existing member of the kubernetes org you can PR yourself in the kubernetes-sigs organization. Feel free to tag in the PR.

**Comment by dims** [comment]
👍🏾 to what @ameukam said

**Comment by shyamjvs** [comment]
Thanks! @ameukam can you approve https://github.com/kubernetes/org/pull/4070?
