### ISSUE TITLE
REQUEST: New membership for priyawadhwa

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/org#407]
### GitHub Username
@priyawadhwa

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [ x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tstromberg 
- @balopat 

### List of contributions to the Kubernetes project
12 PRs authored: https://github.com/kubernetes/minikube/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Apriyawadhwa+

2 PRs reviewed: https://github.com/kubernetes/minikube/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Apriyawadhwa+-author%3Apriyawadhwa

7 Issues responded to https://github.com/kubernetes/minikube/issues?utf8=%E2%9C%93&q=+commenter%3Apriyawadhwa+-author%3Apriyawadhwa+

SIG projects I am involved with
sig-cluster-lifecycle/minikube

**Comment by tstromberg** [comment]
I endorse this membership.

**Comment by balopat** [comment]
I endorse @priyawadhwa's membership!

**Comment by justaugustus** [comment]
Hey @priyawadhwa -- per our [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements), sponsors must be from multiple companies.

Can you update the request to include another non-Google sponsor?

**Comment by mrbobbytables** [comment]
@priyawadhwa Thank you for all the work you've put into helping with minikube.

I've created PR #420  to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by priyawadhwa** [comment]
Thanks @mrbobbytables!
