### ISSUE TITLE
REQUEST: New membership for Tal-or

### ISSUE THREAD

**Issue by Tal-or** [kubernetes/org#4072]
### GitHub Username

@titzhak

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei

### Sponsor 2

@marquiz

### List of contributions to the Kubernetes project

PRs Reviewed / Authored
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/197 
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/220 
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/256 
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/318 
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/359 
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/371
- https://github.com/kubernetes-sigs/scheduler-plugins/pull/377
- https://github.com/kubernetes-sigs/node-feature-discovery/pull/625
- https://github.com/kubernetes-sigs/node-feature-discovery/pull/949
- https://github.com/kubernetes-sigs/node-feature-discovery/pull/961
- https://github.com/kubernetes-sigs/node-feature-discovery/pull/966
- https://github.com/kubernetes-sigs/node-feature-discovery/pull/967
- https://github.com/kubernetes-sigs/node-feature-discovery/pull/1028
- https://github.com/kubernetes-sigs/node-feature-discovery/pull/1029

Issues responded to:
- https://github.com/kubernetes-sigs/scheduler-plugins/issues/249 
- https://github.com/kubernetes-sigs/node-feature-discovery/issues/962 

SIG projects I am involved with:

https://github.com/kubernetes-sigs/scheduler-plugins
https://github.com/kubernetes-sigs/node-feature-discovery

**Comment by marquiz** [comment]
+1, good to get you on-board

**Comment by Huang-Wei** [comment]
+100. Thanks for your contributions and looking forward to collaborating more in the future!

**Comment by denkensk** [comment]
+1  Thanks for your contributions. 💪🏻

**Comment by Priyankasaggu11929** [comment]
/assign

Hello @Tal-or, thanks for all your contributions.

Just verifying that your updated GitHub username is `Tal-or`? I'm no longer able to tag you as `titzhak`

**Comment by Priyankasaggu11929** [comment]
Thanks for the confirmation, @Tal-or  :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4084 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

**Comment by Tal-or** [comment]
Thank you @Priyankasaggu11929 appreciate it!

**Comment by marquiz** [comment]
Welcome @Tal-or 🥳

**Comment by Huang-Wei** [comment]
It seems @Tal-or 's membership is not completed via https://github.com/kubernetes/org/pull/4084. cc @Priyankasaggu11929 

(I think there should be 2 entries - config/kubernetes/org.yaml and config/kubernetes-sigs/org.yaml for @Tal-or in https://github.com/kubernetes/org/pull/4084, but there is only one)

**Comment by Tal-or** [comment]
@Huang-Wei I issued a request only for sigs membership. I think the second one it for Kubernetes

**Comment by Priyankasaggu11929** [comment]
@Huang-Wei, yes, the issue description had just `kubernetes-sigs` mentioned under the "Organization you are requesting membership in" field.

@Tal-or, as now you're already a member of `kubernetes-sigs` org, please feel free to open a PR to add yourself to `Kubernetes` org as well. :)

**Comment by Tal-or** [comment]
> @Huang-Wei, yes, the issue description had just `kubernetes-sigs` mentioned under the "Organization you are requesting membership in" field.
> 
> @Tal-or, as now you're already a member of `kubernetes-sigs` org, please feel free to directly open a PR to add yourself to `Kubernetes` org as well. :)

@Priyankasaggu11929 Thank you!
