### ISSUE TITLE
REQUEST: New membership for jmhbnz

### ISSUE THREAD

**Issue by jmhbnz** [kubernetes/org#4074]
### GitHub Username

@jmhbnz

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@jberkus

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/utils/pull/276
- https://github.com/kubernetes/dashboard/pull/7626
- https://github.com/kubernetes/git-sync/pull/678
- https://github.com/kubernetes/community/pull/7083
- https://github.com/kubernetes/dashboard/pull/7513
- https://github.com/kubernetes-sigs/slack-infra/pull/63
- https://github.com/kubernetes-sigs/kustomize/pull/5070
- https://github.com/kubernetes-sigs/sig-multicluster-site/pull/5
- https://github.com/kubernetes-sigs/slack-infra/pull/62
- https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/226
- https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/369
- https://github.com/kubernetes-sigs/krew/pull/821

Note: I am an active contributor within etcd-io, many of my contributions are under that org. Here is a [link to those contributions](https://github.com/pulls?q=is%3Apr+author%3Ajmhbnz+archived%3Afalse+org%3Aetcd-io).

**Comment by dims** [comment]
+1 from me! welcome @jmhbnz

**Comment by jberkus** [comment]
+1 from me

**Comment by Priyankasaggu11929** [comment]
/assign

@jmhbnz, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4084 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
