### ISSUE TITLE
REQUEST: New membership for XDRAGON2002

### ISSUE THREAD

**Issue by XDRAGON2002** [kubernetes/org#4078]
### GitHub Username

@XDRAGON2002

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@yankay

### Sponsor 2

@oomichi

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pull/9811
https://github.com/kubernetes-sigs/kubespray/pull/9856
https://github.com/kubernetes-sigs/kubespray/pull/9827
https://github.com/kubernetes-sigs/kubespray/pull/9805
- Issues responded to
https://github.com/kubernetes-sigs/kubespray/issues/9830
https://github.com/kubernetes/kubernetes/issues/50791
https://github.com/kubernetes-sigs/kubespray/issues/9677
https://github.com/kubernetes/kubernetes/issues/115547
https://github.com/kubernetes/minikube/issues/15841
https://github.com/kubernetes/kubectl/issues/1373
https://github.com/kubernetes/kubectl/issues/1382
- SIG projects I am involved with
https://github.com/kubernetes-sigs/kubespray
https://github.com/kubernetes/kubectl

**Comment by oomichi** [comment]
Thanks for your contribution @XDRAGON2002 
+1 from my side.

**Comment by yankay** [comment]
Thanks @XDRAGON2002
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@XDRAGON2002, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4084 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

**Comment by XDRAGON2002** [comment]
Thanks a lot @Priyankasaggu11929 !
