### ISSUE TITLE
REQUEST: New membership for dipesh-rawat

### ISSUE THREAD

**Issue by dipesh-rawat** [kubernetes/org#4080]
### GitHub Username

@dipesh-rawat

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@bradtopol

### Sponsor 2

@mengjiao-liu

### List of contributions to the Kubernetes project

- PR Reviewed/Authored
https://github.com/search?q=is%3Apr+author%3Adipesh-rawat++org%3Akubernetes+org%3Akubernetes-sigs&type=Issues

- Issues Responded to
https://github.com/search?q=commenter%3Adipesh-rawat++org%3Akubernetes+org%3Akubernetes-sigs&type=Issues

- SIG I'm involved with sig-docs

**Comment by bradtopol** [comment]
+1
@dipesh-rawat has been doing a great job making contributions and also has learned a lot serving as a PR wrangler shadow for me.  I fully support his membership!!!

**Comment by mengjiao-liu** [comment]
+1
Thank you for all of your hard work !🚀

**Comment by Priyankasaggu11929** [comment]
/assign

@dipesh-rawat, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4084 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
