### ISSUE TITLE
REQUEST: New membership for <abhijeet-26>

### ISSUE THREAD

**Issue by abhijeet-26** [kubernetes/org#4082]
### GitHub Username

@abhijeet-26

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mitul3737

### Sponsor 2

@Imtiaz1234   

### List of contributions to the Kubernetes project

https://github.com/kubernetes/website/pull/39325
https://github.com/kubernetes/website/pull/39391
https://github.com/kubernetes/website/pull/39852
https://github.com/kubernetes/website/pull/39885
https://github.com/kubernetes/website/pull/39778
https://github.com/kubernetes/website/pull/39808
https://github.com/kubernetes/website/pull/39902

**Comment by Imtiaz1234** [comment]
@abhijeet-26  has been an awesome contributor towards the Bengali Localization.

**Comment by Priyankasaggu11929** [comment]
Hi, sponsors need to be listed as a reviewer/approver in an OWNERS file in one of https://github.com/kubernetes or https://github.com/kubernetes-sigs orgs. It looks like @mitul3737 and @Imtiaz1234 are not (please correct me if I'm mistaken!).

**Comment by mitul3737** [comment]
@Priyankasaggu11929 Actually as our Bengali localization is still not live and thus the owners are not added right now. But that should do as these id's are mentioned [here](https://github.com/kubernetes/website/blob/dev-1.23-bn.1/OWNERS_ALIASES)

**Comment by Priyankasaggu11929** [comment]
/assign

Thank you so much for confirming, @mitul3737. :slightly_smiling_face: 

@abhijeet-26  , thank you for all your contributions so far. I've created PR https://github.com/kubernetes/org/pull/4099 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

**Comment by abhijeet-26** [comment]
@Priyankasaggu11929 Thank you.
