### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/sig-multicluster-site

### ISSUE THREAD

**Issue by npintaux** [kubernetes/org#4086]
### Repository

kubernetes-sigs/sig-multicluster-site

### Project domain

*.multicluster.sigs.k8s.io

### Additional context for request

Requesting netlify site for new documentation site for Multicluster API.

**Comment by lauralorenz** [comment]
Bump! We fixed our netlify.toml in https://github.com/kubernetes-sigs/sig-multicluster-site/pull/7 based on some out of band suggestions by @mrbobbytables but if a github admin has some time to set up our netlify, would appreciate it :)

**Comment by mrbobbytables** [comment]
Netlify enabled, site is available here: https://kubernetes-sig-multicluster.netlify.app/
When DNS is setup, let me know and I'll update things on the netlify side.

**Comment by jmhbnz** [comment]
Thanks @mrbobbytables - DNS Request has been raised here: https://github.com/kubernetes/k8s.io/issues/4991 :)

**Comment by jmhbnz** [comment]
Hey @mrbobbytables - DNS is now setup via https://github.com/kubernetes/k8s.io/issues/4991, can you please do some magic on the netlify side so `multicluster.sigs.k8s.io` works on the netlify end?

**Comment by mrbobbytables** [comment]
dns has been configured, it might take a little bit for the cert to be provisioned, but it should be within a couple hours.

with that I'm gonna go ahead and close this out. If you need anything else, you can ping me or reopen it 👍 
/close
