### ISSUE TITLE
REQUEST: New membership for MrFreezeex

### ISSUE THREAD

**Issue by MrFreezeex** [kubernetes/org#4089]
### GitHub Username

@MrFreezeex

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@oomichi

### Sponsor 2

@yankay

### List of contributions to the Kubernetes project

- PRs authored in Kubespray:

- https://github.com/kubernetes-sigs/kubespray/pull/9834
- https://github.com/kubernetes-sigs/kubespray/pull/9819
- https://github.com/kubernetes-sigs/kubespray/pull/9718
- https://github.com/kubernetes-sigs/kubespray/pull/9662
- https://github.com/kubernetes-sigs/kubespray/pull/9609
- https://github.com/kubernetes-sigs/kubespray/pull/9553
- https://github.com/kubernetes-sigs/kubespray/pull/6575
- https://github.com/kubernetes-sigs/kubespray/pull/6574
- https://github.com/kubernetes-sigs/kubespray/pull/6519
- https://github.com/kubernetes-sigs/kubespray/pull/6514
- https://github.com/kubernetes-sigs/kubespray/pull/6513
- https://github.com/kubernetes-sigs/kubespray/pull/6473
- https://github.com/kubernetes-sigs/kubespray/pull/6376
- https://github.com/kubernetes-sigs/kubespray/pull/6373
- https://github.com/kubernetes-sigs/kubespray/pull/6334
- https://github.com/kubernetes-sigs/kubespray/pull/5554
- https://github.com/kubernetes-sigs/kubespray/pull/5531
- https://github.com/kubernetes-sigs/kubespray/pull/5529

**Comment by oomichi** [comment]
Thanks for your many contributions for Kubespray.
+1 from my side.

**Comment by yankay** [comment]
Thanks @MrFreezeex 
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@MrFreezeex, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4098 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
