### ISSUE TITLE
REQUEST: New membership for tangwz

### ISSUE THREAD

**Issue by tangwz** [kubernetes/org#4090]
### GitHub Username

@tangwz

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alculquicondor

### Sponsor 2

@sanposhiho 

### List of contributions to the Kubernetes project

- PRs authored:
    - kubernetes/kubernetes:
        - https://github.com/kubernetes/kubernetes/pull/116508
        - https://github.com/kubernetes/kubernetes/pull/115655
        - https://github.com/kubernetes/kubernetes/pull/114390
        - https://github.com/kubernetes/kubernetes/pull/113127
        - https://github.com/kubernetes/kubernetes/pull/96165
        - https://github.com/kubernetes/kubernetes/pull/95687
        - https://github.com/kubernetes/kubernetes/pull/94740
        - https://github.com/kubernetes/kubernetes/pull/94514

**Comment by alculquicondor** [comment]
+1

Thanks @tangwz

**Comment by Priyankasaggu11929** [comment]
/assign

@tangwz, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4098 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
