### ISSUE TITLE
REQUEST: New membership for jbpratt

### ISSUE THREAD

**Issue by jbpratt** [kubernetes/org#4094]
### GitHub Username

jbpratt

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@BenTheElder

### Sponsor 2

@vladimirvivien

### List of contributions to the Kubernetes project

- PRs reviewed/authored
  - https://github.com/kubernetes-sigs/e2e-framework/pull/168
  - https://github.com/kubernetes-sigs/e2e-framework/pull/171
  - https://github.com/kubernetes/test-infra/pull/27758
  - https://github.com/kubernetes/test-infra/pull/27764
  - https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/174
  - https://github.com/kubernetes-sigs/kubespray/pull/8342
- Issues responded to
  - https://github.com/kubernetes/test-infra/issues/27420
  - https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/175
- SIG projects involved with
  - sig-testing

**Comment by BenTheElder** [comment]
+1
thank you!

**Comment by vladimirvivien** [comment]
+1
Thanks @jbpratt

**Comment by Priyankasaggu11929** [comment]
/assign

@jbpratt, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4124 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
