### ISSUE TITLE
REQUEST: New membership for xdu31

### ISSUE THREAD

**Issue by xdu31** [kubernetes/org#4095]
### GitHub Username

xdu31

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

kevin-wangzefeng

### Sponsor 2

wongma7

### List of contributions to the Kubernetes project

- PRs reviewed/authored 
https://github.com/kubernetes-sigs/aws-encryption-provider/pull/91
https://github.com/kubernetes/test-infra/pull/28183
https://github.com/kubernetes/test-infra/pull/27775
https://github.com/kubernetes-sigs/aws-encryption-provider/pull/89
https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/525
https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/521
https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/516
- Issues responded to
https://github.com/kubernetes/test-infra/issues/27759
- SIG projects involved with 
  - k8s-sig-aws
  - k8s-sig-testing
  - k8s-sig-cloud-provider

**Comment by wongma7** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
Hey @dims, just checking in (seems like it got lost in notifications). We need your +1 to proceed with this request. Thank you. :slightly_smiling_face:

**Comment by dims** [comment]
@Priyankasaggu11929 unfortunately @wongma7 and i have the same employer :(

**Comment by Priyankasaggu11929** [comment]
Ah, thanks for pointing Dims.

@xdu31, could you please add another sponsor on the issue (from a different company/org)? Thank you so much! :slightly_smiling_face:

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by xdu31** [comment]
> Hey @dims, just checking in (seems like it got lost in notifications). We need your +1 to proceed with this request. Thank you. :slightly_smiling_face:

Hi @Priyankasaggu11929 Just got another sponsor from Kevin, who is from a different employer of Matthew.
