### ISSUE TITLE
REQUEST: New membership for @maisem

### ISSUE THREAD

**Issue by maisem** [kubernetes/org#410]
### GitHub Username
@maisem

### Organization you are requesting membership in
@kubernetes-sigs

I am already part of the @kubernetes org, I would like my membership to be synced to the @kubernetes-sigs org as I am currently working on the [Cluster API project](https://github.com/kubernetes-sigs/cluster-api)

cc: @roberthbailey

**Comment by mrbobbytables** [comment]
@maisem I've created PR #420 to add you to @kubernetes-sigs. Once it gets merged, you should get a membership invite notification :tada:

/assign
