### ISSUE TITLE
Containers of csi-cephfsplugin-provisioner are getting terminated with exit code 255

### ISSUE THREAD

**Issue by dbenduga** [kubernetes/org#4100]
### Organization or Repo

kubernetes-csi

### Describe the issue

Below listed containers are getting terminated with exit code 255. We are able to provision dynamic PVC and don't see any issue. Just want to know why these many restart.

NAME READY STATUS RESTARTS AGE
csi-cephfsplugin-4kj4f 3/3 Running 0 250d
csi-cephfsplugin-9zhp6 3/3 Running 0 251d
csi-cephfsplugin-d5cqq 3/3 Running 0 250d
csi-cephfsplugin-dn5qp 3/3 Running 0 250d
csi-cephfsplugin-p622p 3/3 Running 0 251d
csi-cephfsplugin-provisioner-84bb5b599c-fkpdz 6/6 Running 65 233d
csi-cephfsplugin-vb9d5 3/3 Running 0 250d

csi-resizer:
Container ID: cri-o://a4eeefd5ea9836c17e16f464623d0236cdd3ce83e62a5afc4d186271a399a026
Image: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
Image ID: k8s.gcr.io/sig-storage/csi-resizer@sha256:9ebbf9f023e7b41ccee3d52afe39a89e3ddacdbb69269d583abfc25847cfd9e4
Port:
Host Port:
Args:
--csi-address=$(ADDRESS)
--v=5
--timeout=150s
--leader-election
--retry-interval-start=500ms
--handle-volume-inuse-error=false
State: Running
Started: Fri, 06 Jan 2023 00:56:09 +0000
Last State: Terminated
Reason: Error
Exit Code: 255

Containers:
csi-provisioner:
Container ID: cri-o://8e06295adee997cf560bde18ad64c101d04ae413b9c00fb3d1bf25c08ac3aa70
Image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
Image ID: k8s.gcr.io/sig-storage/csi-provisioner@sha256:122bfb8c1edabb3c0edd63f06523e6940d958d19b3957dc7b1d6f81e9f1f6119
Port:
Host Port:
Args:
--csi-address=$(ADDRESS)
--v=5
--timeout=150s
--leader-election=true
--retry-interval-start=500ms
--feature-gates=Topology=false
--extra-create-metadata=true
State: Running
Started: Wed, 21 Dec 2022 19:41:32 +0000
Last State: Terminated
Reason: Error

csi-snapshotter:
Container ID: cri-o://fb3d18875fbf297736d0f5c90dd0c257e7f61b85460abe8aa79440c4820b77f8
Image: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
Image ID: k8s.gcr.io/sig-storage/csi-snapshotter@sha256:89e900a160a986a1a7a4eba7f5259e510398fa87ca9b8a729e7dec59e04c7709
Port:
Host Port:
Args:
--csi-address=$(ADDRESS)
--v=5
--timeout=150s
--leader-election=true
State: Running
Started: Tue, 14 Feb 2023 21:21:28 +0000
Last State: Terminated
Reason: Error
Exit Code: 255

csi-cephfsplugin-attacher:
Container ID: cri-o://5b3999e5e9bb0e28dfcc26d8a1bc270e19fd68c603206c576c189f69b3eec617
Image: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
Image ID: k8s.gcr.io/sig-storage/csi-attacher@sha256:8b9c313c05f54fb04f8d430896f5f5904b6cb157df261501b29adc04d2b2dc7b
Port:
Host Port:
Args:
--v=5
--csi-address=$(ADDRESS)
--leader-election=true
--retry-interval-start=500ms
State: Running
Started: Tue, 14 Feb 2023 21:21:29 +0000
Last State: Terminated
Reason: Error
Exit Code: 255
[podlogs.zip](https://github.com/kubernetes/org/files/11002381/podlogs.zip)

**Comment by mrbobbytables** [comment]
This repo is for org membership requests please post in the relevant repo

/close
