### ISSUE TITLE
REQUEST: New membership for asa3311

### ISSUE THREAD

**Issue by asa3311** [kubernetes/org#4101]
### GitHub Username

@asa3311 

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@howieyuen

### Sponsor 2

@windsonsea 

### List of contributions to the Kubernetes project

https://github.com/kubernetes/website/pull/40077
https://github.com/kubernetes/website/pull/40016
https://github.com/kubernetes/website/pull/40007
https://github.com/kubernetes/website/pull/39997
https://github.com/kubernetes/website/pull/39957
https://github.com/kubernetes/website/pull/39884
https://github.com/kubernetes/website/pull/39883
https://github.com/kubernetes/website/pull/39878
https://github.com/kubernetes/website/pull/39874
https://github.com/kubernetes/website/pull/40077
https://github.com/kubernetes/website/pull/40016
https://github.com/kubernetes/website/pull/40007
https://github.com/kubernetes/website/pull/39997
https://github.com/kubernetes/website/pull/39957
https://github.com/kubernetes/website/pull/39868
https://github.com/kubernetes/website/pull/39868
https://github.com/kubernetes/ingress-gce/pull/1989
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1144
https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/124

**Comment by howieyuen** [comment]
+1

**Comment by windsonsea** [comment]
+1

Welcome, look forward to your more contributions.

**Comment by Priyankasaggu11929** [comment]
/assign

@asa3311, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4124 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
