### ISSUE TITLE
REQUEST: New membership for SD-13

### ISSUE THREAD

**Issue by SD-13** [kubernetes/org#4102]
### GitHub Username

@SD-13

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@chris-short

### Sponsor 2

@kaslin

### PRs authored
- https://github.com/kubernetes/community/pull/7136
- https://github.com/kubernetes/community/pull/7089
- https://github.com/kubernetes/kubernetes/pull/111311
### SIG projects I am involved with
- SIG spotlight on SIG-network
- As a social media shadow( Under [Kaslin](https://github.com/kaslin) ), currently working on KubeCon tweets

**Comment by chris-short** [comment]
Big +1 for Sujay!

**Comment by kaslin** [comment]
Yes! We're so glad to have you, Sujay! +1!

**Comment by Priyankasaggu11929** [comment]
/assign

@SD-13, thank you for all your contributions so far :slightly_smiling_face: 

PR https://github.com/kubernetes/org/pull/4133 adds you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
