### ISSUE TITLE
OCI artifact registry support

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/org#4105]
### Organization or Repo

kubernetes-sigs

### User affected

The security-profiles-operator project

### Describe the issue

The security-profiles-operator project would like to push artifacts (security profiles, which are basically just versionized YAML files) via ORAS to compatible OCI registries.

Major benefit compared to artifacts as files in GCS buckets is being able to annotate them, Tag versions and sign them directly using cosign.

ORAS is supported by a few registries, like Google Artifact Registry, Docker hub as well as the GitHub registry. The GitHub registry allows easy push via GitHub actions, while Google Artifact Registry is not completely supported by our staging repositories, yet.

I propose to enable public GitHub packages/repositories to the k-sigs org (which are already enabled somehow), to be able to link them to existing projects. This way we can publish OCI artifacts directly within GitHub, without requiring additional management.

I’m speaking about those two repositories actually:
- https://github.com/kubernetes-sigs/security-profiles-operator/pkgs/container/security-profiles-operator%2Fprofiles%2Frunc
- https://github.com/kubernetes-sigs/security-profiles-operator/pkgs/container/security-profiles-operator%2Fprofiles%2Fcrun

Right now they’re private, making access impossible for most users.

**Comment by saschagrunert** [comment]
cc @kubernetes/sig-release @kubernetes/release-engineering @pjbgf @jhrozek @JAORMX @ccojocar

**Comment by saschagrunert** [comment]
Slack discussion in: https://kubernetes.slack.com/archives/C01672LSZL0/p1679393740253979

**Comment by saschagrunert** [comment]
@kubernetes/sig-contributor-experience any objections against using the GitHub registry for OCI artifacts? If so, then I'm wondering what the alternatives are.

**Comment by saschagrunert** [comment]
@kubernetes/sig-contributor-experience it looks like that there are already public projects in the k-sigs org: https://github.com/orgs/kubernetes-sigs/packages?visibility=public

In the meantime, would it be possible to do the same for:
- https://github.com/kubernetes-sigs/security-profiles-operator/pkgs/container/security-profiles-operator%2Fprofiles%2Frunc
- https://github.com/kubernetes-sigs/security-profiles-operator/pkgs/container/security-profiles-operator%2Fprofiles%2Fcrun

to unblock the features in https://github.com/kubernetes-sigs/security-profiles-operator/pull/1559 and https://github.com/kubernetes-sigs/security-profiles-operator/pull/1560

**Comment by rchincha** [comment]
Hi all, pointing to the `zot` project for consideration.
`zot` is a CNCF sandbox project currently.
https://zotregistry.io
https://zotregistry.io/latest/general/architecture/

The following is "new" with the 2.0.x releases
https://github.com/project-zot/project-zot.github.io/blob/main/docs/general/whats-new.md

https://kubernetes.io/blog/2023/05/24/oci-security-profiles/

**Comment by saschagrunert** [comment]
Thank you @mrbobbytables, closing this for now since we have a workaround using an external org.
