### ISSUE TITLE
 REQUEST: Create aws-fsx-openzfs-csi-driver to kubernetes-sigs

### ISSUE THREAD

**Issue by jacobwolfaws** [kubernetes/org#4106]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

aws-fsx-openzfs-csi-driver

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@nckturner, @jacobwolfaws

### Who should have write access?

@nckturner, @jacobwolfaws

### Who should be listed as approvers in OWNERS?

@nckturner, @jacobwolfaws

### Who should be listed in SECURITY_CONTACTS?

@nckturner

### What should the repo description be?

Amazon FSx for OpenZFS Cloud Container Storage Interface(CSI) Driver

### What SIG and subproject does this fall under?

sig-cloud-provider

### Please provide references to appropriate approval for this new repo

@nckturner 

### Additional context for request

[FSx for OpenZFS](https://aws.amazon.com/fsx/openzfs/) is going to be making a csi driver to support specific their file system type. It's better to have separate csi driver repos for each FSx file system because 1) it’s cleaner in terms of developer iteration and 2) there are significant differences between each file system FSx supports.

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver 🎉 

Also created:
- https://github.com/kubernetes/org/pull/4115 - to create GitHub teams to grant access
- https://github.com/kubernetes/community/pull/7209 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.
