### ISSUE TITLE
REQUEST: New membership for @wyike

### ISSUE THREAD

**Issue by wyike** [kubernetes/org#4108]
### GitHub Username

@wyike

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@richardcase

### Sponsor 2

@Ankitasw

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3921
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3936
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3959
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3999
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4005
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4129
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4142
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4163

- Issues created
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2941
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3315
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3894
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3987
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3998
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4133
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4161
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4031

- SIG projects I am involved with
    sig-cluster-lifecycle

**Comment by richardcase** [comment]
Thank you for all your work on CAPA @wyike, its very much appreciated. From my side:

+1

**Comment by Ankitasw** [comment]
Thank you for being proactive in CAPA. It's really great to see the community growing. From my side:

+1

**Comment by Priyankasaggu11929** [comment]
/assign

@wyike, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4124 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
