### ISSUE TITLE
REQUEST: New membership for swinslow

### ISSUE THREAD

**Issue by swinslow** [kubernetes/org#411]
### GitHub Username
@swinslow

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nikhita
- @dims

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kops/pull/6006
  - https://github.com/cncf/k8s-conformance/pull/413
  - https://github.com/cncf/k8s-conformance/pull/414

- Issues responded to
  - https://github.com/kubernetes/steering/issues/57
  - https://github.com/kubernetes/minikube/issues/3406

- SIG projects I am involved with
  - SIG-release Licensing subproject
  - Conformance WG (drafted program terms of service)
  - CNCF / LF staff member, running license scanning and analysis services and coordinating with CNCF committee / board on licensing matters

**Comment by dims** [comment]
+1 from me. welcome!

**Comment by nikhita** [comment]
+1 from me as well. Thanks for all your help with licensing!

Welcome! :tada:

**Comment by nikhita** [comment]
Just for the record: Steve is also listed as an approver for the licensing subproject under sig-release. He needs to be a member to be able to use these approval powers. :)

- https://github.com/kubernetes/sig-release/blob/master/licensing/OWNERS
- https://github.com/kubernetes/sig-release/pull/453#discussion_r249271164

**Comment by mrbobbytables** [comment]
Great to have you aboard @swinslow :)

I've created PR #416 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign

**Comment by swinslow** [comment]
Thank you @mrbobbytables!  =)
