### ISSUE TITLE
REQUEST: New membership for dtzar

### ISSUE THREAD

**Issue by dtzar** [kubernetes/org#4111]
### GitHub Username

dtzar

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

CecileRobertMichon

### Sponsor 2

fabriziopandini

### List of contributions to the Kubernetes project

I participate in the weekly calls for cluster-API and cluster-API-Provider-Azure.  I have been helping with PM aspects around the new [cluster api addon provider helm](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm) kubernetes sig and a core responsibility of my role is to support CAPZ as a PM.  There are more things I have done than this in the kubernetes-sig community, but here are some of them below.

PRs Authored:

- [:book: Add managed addon info by dtzar · Pull Request #2964 · kubernetes-sigs/cluster-api-provider-azure (](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2964)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2964)
- [Update roadmap by dtzar · Pull Request #3116 · kubernetes-sigs/cluster-api-provider-azure (](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3116)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3116)
- [CAPZ: retain LGTM through squash](https://github.com/kubernetes/test-infra/pull/28394)

PRs Reviewed:
- [Add proposal for Azure Service Operator by nojnhuh · Pull Request #3113 · kubernetes-sigs/cluster-api-provider-azure (](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3113)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3113)

Issues created:
- [Improve PR reviewer efficiency through improved label automation · Issue #6999 · kubernetes/community (](https://github.com/kubernetes/community/issues/6999)[github.com](http://github.com/)[)](https://github.com/kubernetes/community/issues/6999)
- [18 issues in Cluster Api Provider Azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/created_by/dtzar) here (8 closed, 10 open) 
- [Infrastructure Azure not compatible with 1.0](https://github.com/kubernetes-sigs/cluster-api/issues/5448)
- [Cluster API - Improve health check for managed cluster](https://github.com/kubernetes-sigs/cluster-api/issues/6303)

Issues responded to:
- [Cluster API - Review and update staging use cases doc](https://github.com/kubernetes-sigs/cluster-api/issues/5705#issuecomment-1324392348)
- [CAAPH - Support for private helm repositories](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/30#issuecomment-1472720901)
- [CAAPH - Helm chart version in HCP deployment](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/40#issuecomment-1478398019)

**Comment by CecileRobertMichon** [comment]
+1 from my side

@dtzar has been a huge help stepping in as a PM for the projects and already made some improvements to roadmap, milestone, processes, etc. Looking forward to continuing to collaborate with him.

**Comment by devigned** [comment]
+1 from me too!

@dtzar has consistently demonstrated behaviors consistent with CNCF values, and has been a joy to work with in CAPZ.

**Comment by fabriziopandini** [comment]
+1
Welcome on board, looking forward for what comes next!

**Comment by Priyankasaggu11929** [comment]
/assign

@dtzar, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4124 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
