### ISSUE TITLE
REQUEST: New membership for jongwooo

### ISSUE THREAD

**Issue by jongwooo** [kubernetes/org#4112]
### GitHub Username

@jongwooo

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@seokho-son

### Sponsor 2

@yoonian

### List of contributions to the Kubernetes project

**PRs authored**

[k/website](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ajongwooo)
- [https://github.com/kubernetes/website/pull/39812](https://github.com/kubernetes/website/pull/39812)
- [https://github.com/kubernetes/website/pull/39865](https://github.com/kubernetes/website/pull/39865)
- [https://github.com/kubernetes/website/pull/39761](https://github.com/kubernetes/website/pull/39761)
- [https://github.com/kubernetes/website/pull/39545](https://github.com/kubernetes/website/pull/39545)
- [https://github.com/kubernetes/website/pull/39461](https://github.com/kubernetes/website/pull/39461)
- [https://github.com/kubernetes/website/pull/39433](https://github.com/kubernetes/website/pull/39433)

[k/kops](https://github.com/kubernetes/kops/pulls?q=is%3Apr+author%3Ajongwooo)
- [https://github.com/kubernetes/kops/pull/15116](https://github.com/kubernetes/kops/pull/15116)

[k/autoscaler](https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+author%3Ajongwooo)
- [https://github.com/kubernetes/autoscaler/pull/5479](https://github.com/kubernetes/autoscaler/pull/5479)

[k/cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack/pulls?q=is%3Apr+author%3Ajongwooo)
- [https://github.com/kubernetes/cloud-provider-openstack/pull/2088](https://github.com/kubernetes/cloud-provider-openstack/pull/2088)

[k/ingress-nginx](https://github.com/kubernetes/ingress-nginx/pulls?q=is%3Apr+author%3Ajongwooo)
- [https://github.com/kubernetes/ingress-nginx/pull/9581](https://github.com/kubernetes/ingress-nginx/pull/9581)

[k/minikube](https://github.com/kubernetes/minikube/pulls?q=is%3Apr+author%3Ajongwooo)
- [https://github.com/kubernetes/minikube/pull/15245](https://github.com/kubernetes/minikube/pull/15245)

**Issues responded to**

**SIG projects I am involved with**
kubernetes/sig-docs

**Comment by seokho-son** [comment]
++1

I am one of the reviewers for Korean localization contents in k/website (SIG-Docs).
@jongwooo is active and responsive contributor especially for SIG-Docs Korean localization contribution !
