### ISSUE TITLE
REQUEST: Netlify site for  kubernetes-sigs/cluster-api-provider-ibmcloud

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes/org#4118]
### Repository

kubernetes-sigs/cluster-api-provider-ibmcloud

### Project domain

*.cluster-api-ibmcloud.sigs.k8s.io

### Additional context for request

We already have `https://cluster-api-ibmcloud.sigs.k8s.io/` in place. We would like to adopt multi-release documentation for that we need following to be in place -
```
main.cluster-api-ibmcloud.sigs.k8s.io
release-0-4.cluster-api-ibmcloud.sigs.k8s.io
release-0-3.cluster-api-ibmcloud.sigs.k8s.io
release-0-2.cluster-api-ibmcloud.sigs.k8s.io
release-0-1.cluster-api-ibmcloud.sigs.k8s.io
```

**Comment by mrbobbytables** [comment]
I can't add main as that is the current default.
The other branches are added - your netlify config will need to be updated to support it. I'd suggest checking out kubebuilder for examples.

/close
