### ISSUE TITLE
REQUEST: New membership for sohankunkerkar

### ISSUE THREAD

**Issue by sohankunkerkar** [kubernetes/org#412]
### GitHub Username
@sohankunkerkar

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pmorie 
- @droot
- @DirectXMan12 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/pulls?q=is%3Apr+archived%3Afalse+is%3Aclosed+author%3Asohankunkerkar
- Issues responded to
  https://github.com/issues?q=is%3Aissue+mentions%3Asohankunkerkar+archived%3Afalse+is%3Aclosed
- SIG projects I am involved with
   federation-v2, controller-tools
/area github-membership

**Comment by pmorie** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @sohankunkerkar, thank you for all your work so far :) 

I've created PR #416 to add you to the @kubernetes-sigs org. Once it gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! :tada:

/assign
