### ISSUE TITLE
REQUEST: New membership for pkprzekwas

### ISSUE THREAD

**Issue by pkprzekwas** [kubernetes/org#4126]
### GitHub Username

@pkprzekwas

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xmudrii

### Sponsor 2

@ameukam

### List of contributions to the Kubernetes project

- mainly involved in `k8s-sig-infra` topics
- https://github.com/kubernetes/k8s.io/pull/5011
- https://github.com/kubernetes/k8s.io/pull/5038
- https://github.com/kubernetes-sigs/promo-tools/pull/792
- https://github.com/kubernetes/k8s.io/pull/4989

**Comment by ameukam** [comment]
+1

Currently helping with k8s-infra effort to extend the infrastructure to AWS.

**Comment by xmudrii** [comment]
+1

**Comment by dims** [comment]
+1
