### ISSUE TITLE
REQUEST: New membership for ialidzhikov

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/org#4127]
### GitHub Username

@ialidzhikov

### Organization you are requesting membership in

kubernetes

### Requirements

- [x] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have verified that my sponsors are from different member companies
- [x] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@msau42

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/kubernetes/pulls/ialidzhikov
- https://github.com/kubernetes/kubernetes/issues/created_by/ialidzhikov
- https://github.com/kubernetes/website/pulls/ialidzhikov

**Comment by dims** [comment]
+1 from me!

**Comment by msau42** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@ialidzhikov, thank you for all your contributions so far :slightly_smiling_face: 

PR https://github.com/kubernetes/org/pull/4133 adds you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
