### ISSUE TITLE
REQUEST: New membership for abhay-krishna

### ISSUE THREAD

**Issue by abhay-krishna** [kubernetes/org#4132]
### GitHub Username

abhay-krishna

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@oscr

### Sponsor 2

@killianmuldoon

### List of contributions to the Kubernetes project

**Pull requests:**
kubernetes-sigs/cluster-api#8240
kubernetes-sigs/cluster-api#8232
kubernetes-sigs/cluster-api#8289
kubernetes-sigs/image-builder#778
kubernetes-sigs/image-builder#870 (code moved to kubernetes-sigs/image-builder#943)
kubernetes-sigs/image-builder#1095 
kubernetes-sigs/image-builder#1108
kubernetes-sigs/image-builder#1120
kubernetes-sigs/aws-iam-authenticator#437

**Issues opened:**
kubernetes-sigs/cluster-api#6972
kubernetes-sigs/image-builder#1102
kubernetes-sigs/kustomize#5031

**Comment by killianmuldoon** [comment]
+1

Thanks for all your contributions @abhay-krishna! Looking forward to having you in the org :slightly_smiling_face:

**Comment by Priyankasaggu11929** [comment]
/assign

@abhay-krishna , thank you for all your contributions so far :slightly_smiling_face: 

PR https://github.com/kubernetes/org/pull/4133 adds you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
