### ISSUE TITLE
REQUEST: New membership for ystkfujii

### ISSUE THREAD

**Issue by ystkfujii** [kubernetes/org#4134]
### GitHub Username

ystkfujii

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@nasa9084

### Sponsor 2

 @t-inu

### List of contributions to the Kubernetes project

- PRs authored
  - https://github.com/kubernetes/website/pull/40020
  - https://github.com/kubernetes/website/pull/39974
  - https://github.com/kubernetes/website/pull/39841
  - https://github.com/kubernetes/website/pull/39862
  - https://github.com/kubernetes/website/pull/39784
  - https://github.com/kubernetes/website/pull/40115
  - https://github.com/kubernetes/website/pull/40113
  - etc
- SIG project
  - https://github.com/kubernetes/website

**Comment by t-inu** [comment]
+1
Welcome!

**Comment by nasa9084** [comment]
+1
Thank you for your contributing~

**Comment by Priyankasaggu11929** [comment]
/assign

@ystkfujii, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4140 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
