### ISSUE TITLE
REQUEST: New membership for yanggangtony

### ISSUE THREAD

**Issue by yanggangtony** [kubernetes/org#4136]
### GitHub Username

@yanggangtony

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu

### Sponsor 2

@oomichi

### List of contributions to the Kubernetes project

I have commit a lot pr about k8s and cncf proejcts , the summary statistics is: [yanggangtony]( https://github.com/yanggangtony/my-github-status) .

And the kubernetes-sigs repo is like :
[kwok](https://github.com/kubernetes-sigs/kwok/pulls?q=is%3Apr+author%3Ayanggangtony)
[kubespray](https://github.com/kubernetes-sigs/kubespray/pulls?q=is%3Apr+author%3Ayanggangtony)
[controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/pulls?q=is%3Apr+author%3Ayanggangtony)
[node-feature-discovery](https://github.com/kubernetes-sigs/node-feature-discovery/pulls?q=is%3Apr+author%3Ayanggangtony)
[cluster-api](https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+author%3Ayanggangtony)
[scheduler-plugins](https://github.com/kubernetes-sigs/scheduler-plugins/pulls?q=is%3Apr+author%3Ayanggangtony+)
[descheduler](https://github.com/kubernetes-sigs/descheduler/pulls?q=is%3Apr+author%3Ayanggangtony+)
[kind](https://github.com/kubernetes-sigs/kind/pulls?q=is%3Apr+author%3Ayanggangtony+)

Also the k8s main repo is like :
[kubernetes](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Ayanggangtony)
[kubernetes-website](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ayanggangtony+)
[ingress-nginx](https://github.com/kubernetes/ingress-nginx/pulls?q=is%3Apr+author%3Ayanggangtony)

**Comment by pacoxu** [comment]
+1
Thank you for your contributions to the community. We hope that you will continue to contribute in the future.

**Comment by yanggangtony** [comment]
Yes , i will continue👋

**Comment by oomichi** [comment]
@yanggangtony Thank you for your contributions.
I saw your many contributions as https://github.com/kubernetes-sigs/kubespray/pulls?q=is%3Apr+yanggang+is%3Aclosed
+1 from my side.

**Comment by yanggangtony** [comment]
@oomichi 
Thanks very much , i will continue👋

**Comment by Priyankasaggu11929** [comment]
/assign

@yanggangtony, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4150 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
