### ISSUE TITLE
REQUEST: Create JobSet repo

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/org#4137]
### New repo, staging repo, or migrate existing

new

### Is it a staging repo?

no

### Requested name for new repository

jobset

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

ahg-g, danielvegamyhre

### Who should have write access?

ahg-g

### Who should be listed as approvers in OWNERS?

ahg-g, danielvegamyhre

### Who should be listed in SECURITY_CONTACTS?

ahg-g, danielvegamyhre

### What should the repo description be?

JobSet: An API for managing a group of Jobs as a unit

### What SIG and subproject does this fall under?

sig-apps 

### Please provide references to appropriate approval for this new repo

@soltysh @alculquicondor 

### Additional context for request

This repository will host an implementation of the [bit.ly/k8s-jobset](http://bit.ly/k8s-jobset) proposal.

**Comment by alculquicondor** [comment]
I'm not a TL or Chair for SIG Apps, but LGTM :sweat_smile:

**Comment by soltysh** [comment]
:+1: from my side :)

**Comment by nikhita** [comment]
Repo has been created - https://github.com/kubernetes-sigs/jobset

Also created:
- https://github.com/kubernetes/org/pull/4138 - to add GitHub teams to grant access
- https://github.com/kubernetes/community/pull/7231 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by ameukam** [comment]
I think this is done.

/close
