### ISSUE TITLE
REQUEST: New membership for TerryHowe

### ISSUE THREAD

**Issue by TerryHowe** [kubernetes/org#4141]
### GitHub Username

@TerryHowe

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ameukam

### Sponsor 2

@jeremyrickard

### List of contributions to the Kubernetes project

 https://github.com/TerryHowe?tab=overview&from=2023-01-01&to=2023-03-31&org=kubernetes

# PR Created
* https://github.com/kubernetes/registry.k8s.io/pull/183
* https://github.com/kubernetes/registry.k8s.io/pull/184
* https://github.com/kubernetes/test-infra/pull/29032
* https://github.com/kubernetes/test-infra/pull/29036
* https://github.com/kubernetes/registry.k8s.io/pull/176
* https://github.com/kubernetes/registry.k8s.io/pull/177
* https://github.com/kubernetes/registry.k8s.io/pull/192
* https://github.com/kubernetes/registry.k8s.io/pull/190
* https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1404
* https://github.com/kubernetes-sigs/image-builder/pull/669
* https://github.com/kubernetes-sigs/image-builder/pull/1124
* https://github.com/kubernetes-sigs/cluster-api/pull/8428
 
# PR Reviews
 * https://github.com/kubernetes/k8s.io/pull/4874
 * https://github.com/kubernetes/k8s.io/pull/4878
 * https://github.com/kubernetes/test-infra/pull/28951
 * https://github.com/kubernetes/test-infra/pull/28922
 * https://github.com/kubernetes/test-infra/pull/28861
 * https://github.com/kubernetes/test-infra/pull/28861
 * https://github.com/kubernetes/registry.k8s.io/pull/155
 * https://github.com/kubernetes/registry.k8s.io/pull/185
 * https://github.com/kubernetes-sigs/community-images/pull/58
 * https://github.com/kubernetes/registry.k8s.io/pull/212
 * https://github.com/kubernetes/registry.k8s.io/pull/199
 * 

# Projects
 * https://github.com/kubernetes/registry.k8s.io
 *  https://github.com/kubernetes/test-infra
 * https://github.com/kubernetes/k8s.io
 * https://github.com/kubernetes-sigs/cluster-api
 * https://github.com/kubernetes-sigs/image-builder
 * https://github.com/kubernetes-sigs/aws-ebs-csi-driver

**Comment by ameukam** [comment]
+1

Terry is currently working on extending k8s-infra to AWS and helping with maintenance of `registry.k8s.io`

**Comment by dims** [comment]
+1 from me!

**Comment by Priyankasaggu11929** [comment]
/assign

@TerryHowe, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4150 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
