### ISSUE TITLE
REQUEST: New membership for ndixita

### ISSUE THREAD

**Issue by ndixita** [kubernetes/org#4142]
### GitHub Username

@ndixita 

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu 

### Sponsor 2

@bobbypage 

### List of contributions to the Kubernetes project

- PRs authored
https://github.com/kubernetes/kubernetes/pull/111495
https://github.com/kubernetes/kubernetes/pull/111616
https://github.com/kubernetes/enhancements/pull/3818
https://github.com/kubernetes/test-infra/pull/27724
https://github.com/kubernetes/kubernetes/pull/111342

**Comment by pacoxu** [comment]
big +1

Thanks for your work on sig-node.

**Comment by dims** [comment]
+1 from me!

**Comment by bobbypage** [comment]
big +1 from me, @ndixita has been doing an awesome job in SIG-Node across many projects such as GCP credential provider, memory QoS, and CI test group! Keep up the good work!

**Comment by Priyankasaggu11929** [comment]
/assign

@ndixita, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4150 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
