### ISSUE TITLE
REQUEST: New membership for louiscryan

### ISSUE THREAD

**Issue by louiscryan** [kubernetes/org#4147]
### GitHub Username

louiscryan

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

keithmattix

### Sponsor 2

howardjohn

### List of contributions to the Kubernetes project

Involved with sig-gateway &  the GAMMA subproject

I think John and Keith qualify as approvers based on 

https://github.com/kubernetes-sigs/gateway-api/blob/main/OWNERS_ALIASES

but I can also ask Rob & Bowie if thats needed

@keithmattix @howardjohn

**Comment by keithmattix** [comment]
Welcome @louiscryan! +1 from me

**Comment by Priyankasaggu11929** [comment]
> Involved with sig-gateway & the GAMMA subproject

@louiscryan, if there're publicly available links to your contributions, could you please list them under the `List of contributions to the Kubernetes project` section. Thank you so much :slightly_smiling_face:

**Comment by howardjohn** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@louiscryan, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4198 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
