### ISSUE TITLE
REQUEST: New membership for krapie

### ISSUE THREAD

**Issue by krapie** [kubernetes/org#4156]
### GitHub Username

@krapie

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@seokho-son

### Sponsor 2

@ysyukr

### List of contributions to the Kubernetes project

**PRs authored**
[k/website](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Akrapie+)

- https://github.com/kubernetes/website/pull/38300
- https://github.com/kubernetes/website/pull/38445
- https://github.com/kubernetes/website/pull/38446
- https://github.com/kubernetes/website/pull/38632
- https://github.com/kubernetes/website/pull/39900

**Issues responded to**
none

**SIG projects I am involved with**
kubernetes/sig-docs

**Comment by ysyukr** [comment]
+1
Thank you for the contribution!

**Comment by seokho-son** [comment]
++1

I am one of the approvers for Korean localization contents in k/website (SIG-Docs).
@krapie is active contributor especially for SIG-Docs localization !

**Comment by Priyankasaggu11929** [comment]
/assign

@krapie, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4164 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
