### ISSUE TITLE
REQUEST: Create kubernetes-sigs/kubectl-validate

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes/org#4159]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

kubectl-validate

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

alexzielenski, apelisse

### Who should have write access?

alexzielenski, apelisse

### Who should be listed as approvers in OWNERS?

alexzielenski, apelisse, richabanker

### Who should be listed in SECURITY_CONTACTS?

alexzielenski, apelisse, richabanker

### What should the repo description be?

CLI Tool for validating Kubernetes resources from their OpenAPIV3 schemas on client-side aiming for best parity with errors returned by server. Supports core resources, CRDs, CEL validations, and more!

### What SIG and subproject does this fall under?

this is a new subproject for sig-cli for kube-validate

### Please provide references to appropriate approval for this new repo

- Discussed in SIG CLI Meeting: https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#bookmark=kix.8q0ykafq42vp
- https://github.com/kubernetes/org/issues/4159#issuecomment-1505813547

**Comment by seans3** [comment]
I believe a SIG CLI lead client-side validation tool is worthy of a new repository.

/lgtm

**Comment by alexzielenski** [comment]
Given that this is approved by SIG CLI leads for a while, who should I contact to create this repo?

/cc @nikhita

**Comment by mrbobbytables** [comment]
Repo create: https://github.com/kubernetes-sigs/kubectl-validate
teams PR: https://github.com/kubernetes/org/pull/4182
sigs.yaml PR: https://github.com/kubernetes/community/pull/7265

Once all are merged I'll add the teams and this should be good to close 👍

**Comment by mrbobbytables** [comment]
teams are added to the repo, you should be good to go!

/close
