### ISSUE TITLE
REQUEST: Create a Github token for Cluster API jobs

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes/org#4165]
### Organization or Repo

kubernetes-sigs/cluster-api

### Describe the issue

We're having an issue with rate-limits in some of the Cluster API end-to-end tests running on Prow. Adding a github token would make the tests much less flaky.

The token only requires basic read permissions in order to prevent rate-limiting.

@sbueringer

**Comment by killianmuldoon** [comment]
@ameukam I see you worked on something similar here - https://github.com/kubernetes/k8s.io/pull/4259. Any insight into how this should work?

**Comment by ameukam** [comment]
Do you have an example of job failing because of rate-limit ? 

we have a proxy to cache Github tokens (`ghproxy.default.cluster.local`). Maybe we can use that ?

**Comment by sbueringer** [comment]
I was wondering if using ghproxy is an option. To me it felt like depending on an implementation detail of Prow.

Basically clusterctl - our Cluster API cli tool - is pulling files from GitHub releases. But there are probably more places where we call the GitHub API.

Ideally we would prefer testing clusterctl like our users are using it, by interacting with the normal GitHub API.

I think we would probably also have to make a bunch of adjustments to clusterctl to be able to talk to ghproxy instead of the normal GitHub endpoints.

**Comment by sbueringer** [comment]
We just saw that a bunch of jobs across Prow are using their own GitHub tokens, so that felt easier.

**Comment by chrischdi** [comment]
Updated failing job link: https://storage.googleapis.com/k8s-triage/index.html?date=2023-04-27&job=.*-cluster-api-.*&xjob=.*-provider-.*#248b18d3604f56466fe3

Or https://storage.googleapis.com/k8s-triage/index.html?text=rate%20limit%20for%20github%20api%20has%20been%20reached&job=.*-cluster-api-.*&xjob=.*-provider-.*

**Comment by ameukam** [comment]
I'm not sure about the usage of a GitHub token in order to solve the rate limit issue. The prowjob will pull github repos using anonymous auth through HTTPS to run tests. A GitHub token is only used when there is an authentication step needed to the Github API.

**Comment by chrischdi** [comment]
In CAPI's case it is not the prow part, pulling the github repo which fails.

The test itself (after Prow pulled the repo and started the test) has code (in cluster API's CLI) which fetches artifacts from Github (e.g. yaml's from cert-manager releases). And there is the known issue that this may hit the rate-limit of Github. 

The code in CAPI is able to leverage a github token (via the `GITHUB_TOKEN` environment variable) and by that bypass the anonymous rate-limit.

**Comment by killianmuldoon** [comment]
After moving to the EKS community cluster this issue has become much more disruptive, and means CAPI's tests can't be moved to the community cluster as previously planned see https://github.com/kubernetes-sigs/cluster-api/issues/8426#issuecomment-1675918484

@ameukam  - what's the process for providing a Github token on the EKS community cluster?

**Comment by richardcase** [comment]
We are running into rate limiting issues with the e2e tests for CAPA as well for the same reasons.

It would be great if there was a GitHub token available to the tests via a secret (or boskos) in the prow cluster.

We're using the EKS Prow cluster for all our e2e tests.

**Comment by killianmuldoon** [comment]
>Is this something we could reuse? Or should we set up per-project tokens?

I'm not sure we can reuse this token in the EKS cluster as I'm not sure it even exists there. In any case I think it would be good to get a new token created per project that individual projects can control.

**Comment by chrischdi** [comment]
xref: https://github.com/kubernetes/test-infra/pull/30501#issuecomment-1692468791

> with regards to getting a token:
> 
> * Ask for a read-only token in the #github-management channel on Slack from the existing bot accounts
* Get @ameukam to load it in here [kubernetes/k8s.io@be85c53/infra/gcp/terraform/k8s-infra-prow-build/prow-build/resources/test-pods/externalsecrets.yaml](https://github.com/kubernetes/k8s.io/blob/be85c5317cada1f9c04b52e4a9d5d581bbd3c1cd/infra/gcp/terraform/k8s-infra-prow-build/prow-build/resources/test-pods/externalsecrets.yaml)

**Comment by richardcase** [comment]
Having a new read-only token we could use would really help with the e2e tests. Without it, I think we'd have to consider moving the CAPA jobs back to the GCP Prow cluster.

**Comment by killianmuldoon** [comment]
I think we can close this as I'm no longer seeing these flakes in the CAPI e2e tests. If someone wants to reopen though, please do.

/close
