### ISSUE TITLE
REQUEST: New membership for trasc

### ISSUE THREAD

**Issue by trasc** [kubernetes/org#4168]
### GitHub Username

@trasc

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alculquicondor

### Sponsor 2

@tenzen-y

### List of contributions to the Kubernetes project

* kubernetes-sigs/kueue#600
* kubernetes-sigs/kueue#613
* kubernetes-sigs/kueue#615
* kubernetes-sigs/kueue#653
* kubernetes-sigs/kueue#660
* kubernetes-sigs/kueue#667
* kubernetes-sigs/kueue#689
* kubernetes-sigs/kueue#692
* kubernetes-sigs/kueue#695

**Comment by tenzen-y** [comment]
+1

I'm looking forward to collaborating more with you in the future.

**Comment by Priyankasaggu11929** [comment]
/assign

@trasc, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4185 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
