### ISSUE TITLE
REQUEST: Migrate puerco/release-actions

### ISSUE THREAD

**Issue by puerco** [kubernetes/org#4170]
### New repo, staging repo, or migrate existing

kubernetes-sigs/release-actions

### Is it a staging repo?

no

### Requested name for new repository

kubernetes-sigs/release-actions

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

cpanato jeremyrickard justaugustus puerco saschagrunert Verolop

### Who should have write access?

cpanato jeremyrickard justaugustus puerco saschagrunert Verolop

### Who should be listed as approvers in OWNERS?

sig-release-leads

### Who should be listed in SECURITY_CONTACTS?

cpanato jeremyrickard justaugustus puerco saschagrunert Verolop

### What should the repo description be?

A set of reusable GitHub actions based on the Kubernetes Release Engineering Tooling

### What SIG and subproject does this fall under?

sig-release

### Please provide references to appropriate approval for this new repo

TBD (recording coming up)

### Additional context for request

This repository exposes the release engineering tooling as reusable GitHub actions, presented during KubeCon EU '23

**Comment by rikatz** [comment]
Go @puerco !!

**Comment by nikhita** [comment]
@puerco since you are a sig-release TL and you created the issue, should this be considered a go ahead from sig-release to create the repo?

**Comment by cpanato** [comment]
it is a go from sig-release :)

**Comment by nikhita** [comment]
@puerco @cpanato actually, @helayoty brought up https://github.com/kubernetes/org/issues/4218#issuecomment-1561791843 recently.

Is that something sig-release can leverage for actions as well?

**Comment by helayoty** [comment]
@puerco @cpanato , it would be great to get this into the "all-sigs-github-action" repo proposal so other sigs can benefit from this amazing work.

**Comment by cpanato** [comment]
we can move to the repo, the all sigs one is very specific to k8s org, and the one we are proposing to donate can be used inside and outside the k8s as well.
with that will be easier to discover the repo and will not have the entire non related actions as well. my two cents

**Comment by cpanato** [comment]
@nikhita @helayoty hello, any updates on this?

**Comment by helayoty** [comment]
@cpanato, yup, the repo is up and ready for all contributors [here](https://github.com/kubernetes-sigs/sigs-github-actions) :)

**Comment by puerco** [comment]
Hey, thanks @helayoty  I just noticed the last update on the issue.

As @cpanato mentioned above, the intent of this repository is to publish actions that expose the release engineering tooling to make them easier to use for external consumers. This is not intended to be a project-wide repo but rather public-facing tools.

Moreover, we have projects that are already pulling these actions from my personal org so we would like to migrate it to the org to take advantage of github's redirection. So, can we proceed with the donation request?

SIG Release is about to host an event with CNCF using these tools, so I would like to get the actions ready when we start.


Thanks!!

**Comment by cpanato** [comment]
I am super happy to see this happening!

**Comment by Priyankasaggu11929** [comment]
Repo is migrated to kubernetes-sigs - https://github.com/kubernetes-sigs/release-actions :tada: 

I'll work on the PRs for setting up github teams, as well adding the repo to k/community.

@puerco @cpanato, will `release-actions` would be a new subproject of SIG Release? Or part of one of the existing subprojects?

https://github.com/kubernetes/community/tree/master/sig-release#subprojects

**Comment by cpanato** [comment]
Part of the existing ones :)

**Comment by Priyankasaggu11929** [comment]
k-sigs/release-actions is added to k/community and github teams are created with following PRs.

- https://github.com/kubernetes/org/pull/4611
- https://github.com/kubernetes/community/pull/7636

Migration of repo is completed. Closing the issue. Thanks!

/close
