### ISSUE TITLE
REQUEST: New membership for @mrthinger (WIP, need second sponsor from different company)

### ISSUE THREAD

**Issue by mrthinger** [kubernetes/org#4171]
### GitHub Username

@mrthinger

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mskrocki

### Sponsor 2

WIP

## Authored
- https://github.com/kubernetes/cloud-provider-gcp/pull/401
- https://github.com/kubernetes/cloud-provider-gcp/pull/500
- https://github.com/kubernetes/cloud-provider-gcp/pull/418
- https://github.com/kubernetes/cloud-provider-gcp/pull/417
- https://github.com/kubernetes/cloud-provider-gcp/pull/415
- https://github.com/kubernetes/cloud-provider-gcp/pull/412
- https://github.com/kubernetes/cloud-provider-gcp/pull/401
## Reviewed
- https://github.com/kubernetes/cloud-provider-gcp/pull/509
- https://github.com/kubernetes/cloud-provider-gcp/pull/410

**Comment by mrbobbytables** [comment]
@mrthinger do you have a second sponsor lined up?

**Comment by mrthinger** [comment]
> @mrthinger do you have a second sponsor lined up?

I have more than 1 sponsor but they're all from Google. I'm struggling to find one from a different company.

**Comment by Priyankasaggu11929** [comment]
Hi @mrthinger, just following up to check if you're able to add a second sponsor to the request now? Thank you!

**Comment by mrthinger** [comment]
not yet :(

**Comment by mrbobbytables** [comment]
@mrthinger I'd reach out in sig-cloud-provider and work with some other folk there, or potentially on the cloud provider extraction in kubernetes/kubernetes to find another non-googler sponsor.

I'm going to go ahead and close this for now, please reopen when you've found another sponsor.

/close
