### ISSUE TITLE
REQUEST: create kube-scheduler-wasm-extension

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/org#4174]
### New repo, staging repo, or migrate existing

new repo

### Is it a staging repo?

no

### Requested name for new repository

kube-scheduler-wasm-extension

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

sanposhiho, kerthcet

### Who should have write access?

sanposhiho, kerthcet

### Who should be listed as approvers in OWNERS?

sanposhiho, kerthcet

### Who should be listed in SECURITY_CONTACTS?

sanposhiho, kerthcet

### What should the repo description be?

All the things to make the scheduler extendable with wasm.

### What SIG and subproject does this fall under?

sig-scheduling

### Please provide references to appropriate approval for this new repo

https://github.com/kubernetes/org/issues/4174#issuecomment-1538432155

### Additional context for request

https://github.com/kubernetes/kubernetes/issues/112851

<details><summary>Past context. No longer needed to read.</summary><div>

the previous discussion thread: https://kubernetes.slack.com/archives/C09TP78DV/p1676610114431299

What we need to have:
- ABI design documentation.
  - We need to have the documentation how the scheduler plugin(host) communicates with the wasm binary(guest) (= Application Binary Interface (ABI)). Something like [this](https://http-wasm.io/http-handler-abi/). It's important so that not only us, but anyone can create the guest (or SDK) based on the ABI. 
- The scheduler plugin to host wasm runtime.  
- The SDK(s) to build the wasm binary. 
  - It's impossible to require users to build the wasm binary by themselves without any guides. So, in most cases, developers provides the SDK like [this](https://github.com/http-wasm/http-wasm-guest-tinygo) so that people can easily build the wasm binary which follows ABI. We can start with Golang SDK, but we may want to have the SDK in other languages in the future. 

We have two options on the table:
- create the new repository.
- implement them in [sigs/scheduler-plugins](https://github.com/kubernetes-sigs/scheduler-plugins).

---

I'm +1 on the idea to create the new repository because it requires not only implementing scheduler plugin, but also many other stuff, unlike other scheduler plugins developed in sigs/scheduler-plugins.

---

@kubernetes/sig-scheduling-leads Please take a look and give any comments on it. 🙏 I'd like to move this stuck discussion forward.

</div></details>

**Comment by sanposhiho** [comment]
> Can we discuss this in a SIG meeting?

Sure. Please add it to discussion item.
Let's see other members opinion.

**Comment by alculquicondor** [comment]
Added

**Comment by alculquicondor** [comment]
@sanposhiho, here are some guidelines about subprojects:
- https://github.com/kubernetes/community/blob/master/community-membership.md#subproject-owner
- https://github.com/kubernetes/community/blob/master/governance.md#subprojects

In addition to them, I would like to request an update on the SIG scheduling meeting at least once every 4 months, from any of the subproject owners. I hope we could ask the same to other subprojects.

**Comment by Huang-Wei** [comment]
> In addition to them, I would like to request an update on the SIG scheduling meeting at least once every 4 months

+1.

**Comment by sanposhiho** [comment]
Apologize for missing the meeting.
And, @alculquicondor thanks for bringing this topic in sig meeting. 🙇 

So, the conclusion on the sig meeting is to go with creating new repo?

> an update on the SIG scheduling meeting at least once every 4 months

Sure, I can provide updates. (simulator as well)

**Comment by sanposhiho** [comment]
I'd like to have more maintainers (at least, one more reviewer is required; otherwise I cannot submit PR)

@kubernetes/sig-scheduling-misc Is anyone interested in it?

**Comment by Huang-Wei** [comment]
I'd +1 to support this repo's creation, but I'm out of bandwidth to participating as a reviewer/maintainer :(

**Comment by sanposhiho** [comment]
Hmm, I believe the wazero maintainers will help review from wasm side PoV, but I guess no one has membership in this org.
So, I hope someone from sig-scheduling can take on reviewer though... 😞

**Comment by alculquicondor** [comment]
you could ask in the mailing list, but ideally it should be someone that is already a reviewer in another subproject.

**Comment by codefromthecrypt** [comment]
wazero folks can help review unofficially even if not in the org. Please feel free to ping me.

**Comment by kerthcet** [comment]
@sanposhiho I can help with this from scheduling POV, our company met tricky issue as both our company and our customers have specific plugins but we can't compile them together for security reasons, we're searching for solutions like go plugin and wasm.

**Comment by sanposhiho** [comment]
@kerthcet Great. Thanks! 😭

**Comment by Huang-Wei** [comment]
Thanks @kerthcet !

**Comment by salaboy** [comment]
+1 for the repo

**Comment by salaboy** [comment]
+1 for the repo creation

**Comment by kerthcet** [comment]
kindly ping @nikhita @mrbobbytables as we want to push forward the process. Thanks a lot.

**Comment by nikhita** [comment]
/assign

Repo has been created - https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension 🎉 

Also created:
- #4222 - to create GitHub teams to grant access
- https://github.com/kubernetes/community/pull/7297 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.
