### ISSUE TITLE
New repo: kubernetes-sigs/kubebuilder-declarative-pattern

### ISSUE THREAD

**Issue by johnsonj** [kubernetes/org#418]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
kubebuilder-declarative-pattern

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@kubernetes-sigs/kubebuilder-admins, @justinsb, @johnsonj

### If not a staging repo, who should have write access
@kubernetes-sigs/kubebuilder-admins, @justinsb, @johnsonj

### If a new repo, who should be listed as approvers in OWNERS
@kubernetes-sigs/kubebuilder-admins, @justinsb, @johnsonj

### If a new repo, who should be listed in SECURITY_CONTACTS
@kubernetes-sigs/kubebuilder-admins, @justinsb, @johnsonj

### What should the repo description be
A toolkit for building declarative operators with kubebuilder.

### What SIG and subproject does this fall under in sigs.yaml
This is part of the kubebuilder subproject for SIG API Machinery.

### Approvals
- @DirectXMan12 
- @pwittrock 
[src](https://github.com/kubernetes/community/pull/3018#issuecomment-452952984)

### Additional context for request
- https://www.youtube.com/watch?v=LPejvfBR5_w
- https://github.com/kubernetes-sigs/controller-runtime/pull/241

**Comment by DirectXMan12** [comment]
Reiterating my approval: :+1:

**Comment by justinsb** [comment]
@cblecker is this something you can help with please?

**Comment by nikhita** [comment]
Would be awesome if we could have https://github.com/kubernetes/community/pull/3018#issuecomment-454085394 get merged in as well and get ack's from the people listed there.

cc @deads2k @lavalamp @sttts @pwittrock @cheftako

**Comment by spiffxp** [comment]
Until the followup mentioned in https://github.com/kubernetes/community/pull/3018#issuecomment-464818512 is opened and merged, I would like an approval from SIG API machinery leadership, or a confirmation that the earlier approval of "kubebuilder-addon-pattern" applies for "kubebuilder-declaritive-pattern"

**Comment by spiffxp** [comment]
/unassign @lavalamp @deads2k 
/assign
I'll take that for approval and work on this

**Comment by spiffxp** [comment]
- Opened https://github.com/kubernetes/org/pull/505 to create teams for repo admin/write access
- Opened https://github.com/kubernetes/community/pull/3278 to add to sigs.yaml (this was an educated guess based on where kubebuilder fell within existing subprojects)
- Created https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern with default settings
- Set description per the repo creation requested
- Cloned newly created / bare repo locally
- Copied over latest contents of kubernetes/kubernetes-template-project and committed as initial commit with message "Initial commit from kubernetes-template-project"
- Next commit:
  - Updated OWNERS_ALIASES to remove steering-committee alias per the TODO
  - Added a kubebuilder-admins alias, populated based on the @kubernetes-sigs/kubebuilder-admins team
  - Updated OWNERS per this repo creation request (add a labels entry for the sig this repo/subproject belongs to)
  - Updated SECURITY_CONTACTS per this repo creation request (can't use aliases, so expanded the team)
- Pushed directly to master
- Manually update repo topic to "k8s-sig-api-machinery" 

At this point the repo is ready for PR's.

TODO:
- Once https://github.com/kubernetes/org/pull/505 is merged and the postsubmit has finished, the teams should appear, update collaborators manually

**Comment by spiffxp** [comment]
@johnsonj it turns out you are not a member of kubernetes or kubernetes-sigs, so I can't add you to the things, can you please [file a membership request](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E)?

**Comment by nikhita** [comment]
>  Once #505 is merged and the postsubmit has finished, the teams should appear, update collaborators manually

The postsubmit has run and the new teams have been created. I have updated access as follows:

- kubebuilder-admins and kubebuilder-declarative-pattern-admins have admin access
- kubebuilder-declarative-pattern-maintainers has write access

The PR to update sigs.yaml (https://github.com/kubernetes/community/pull/3278) has also merged, so closing this issue.

/close
