### ISSUE TITLE
REQUEST: New membership for @oliviassss

### ISSUE THREAD

**Issue by oliviassss** [kubernetes/org#4183]
### GitHub Username

@oliviassss

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kishorj

### Sponsor 2

@johngmyers

#### The summary of all my PRs so far: [link](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pulls?page=2&q=is%3Apr+is%3Aclosed+author%3Aoliviassss)

- Selected PRs:
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3151
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3119
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2409
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2524
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2480
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2125
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2129
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2146

- Selected issues:
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3155
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2449
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2411
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1900

**Comment by kishorj** [comment]
+1

**Comment by johngmyers** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@oliviassss, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4198 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
