### ISSUE TITLE
REQUEST: New membership for mohitsharma-in

### ISSUE THREAD

**Issue by mohitsharma-in** [kubernetes/org#4187]
### GitHub Username

@mohitsharma-in

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@palnabarun

### Sponsor 2

@liggitt

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/kubernetes/pull/117399 
- https://github.com/kubernetes/kubernetes/pull/117352
- https://github.com/kubernetes/kubernetes/pull/117350
- https://github.com/kubernetes/kubernetes/pull/117349
- https://github.com/kubernetes/kubernetes/pull/117347
- https://github.com/kubernetes/org/pull/4077

**Comment by nikhita** [comment]
+1 from me too!

**Comment by liggitt** [comment]
+1

**Comment by palnabarun** [comment]
+1 from me. Thank you for your contributions! 🙏🏽

**Comment by Priyankasaggu11929** [comment]
/assign

@mohitsharma-in, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4198 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
