### ISSUE TITLE
Set Cluster API Provider Packet packages to public

### ISSUE THREAD

**Issue by cprivitere** [kubernetes/org#4189]
### Organization or Repo

kubernetes-sigs/cluster-api-provider-packet

### Describe the issue

We would like to have the Github Container Registry be a source for Cluster API Provider packet images (in addition to quay.io and docker.io). Can you please set the visibility of the [Cluster API Provider Packet packages](https://github.com/kubernetes-sigs/cluster-api-provider-packet/pkgs/container/cluster-api-provider-packet) to public?

Thanks.

**Comment by displague** [comment]
This would give users more choice in image repositories which has proven to be a valuable as image repository service providers change their policies.

There are other Kubernetes-Sigs projects (including cluster-api related projects) using public GHCR images. https://github.com/orgs/kubernetes-sigs/packages?tab=packages&q=cluster-api

**Comment by mrbobbytables** [comment]
> We would like to have the Github Container Registry be a source for Cluster API Provider packet images (in addition to quay.io and docker.io). Can you please set the visibility of the [Cluster API Provider Packet packages](https://github.com/kubernetes-sigs/cluster-api-provider-packet/pkgs/container/cluster-api-provider-packet) to public?

 @cprivitere We looked into this in a general issue here: https://github.com/kubernetes/org/issues/4514
and unfortunately we can't enable public GHCR repos =/

(copied response from here: https://github.com/kubernetes/org/issues/4514#issuecomment-1939707843)
> We looked into it and unfortunately we can't enable the github package functionality for public use.
Essentially github does not give any granual permissions over repos and which ones can be public or private. It's an all or none thing meaning anyone can create public packages or no one can. Packages also exist outside of github's regular permission system, we cannot create custom roles or anything that could better manage access.
>
> If/when GitHub updates it, we can revisit - but for now it's not something we're going to move forward with enabling. =/

**Comment by cprivitere** [comment]
Thanks for the feedback.
