### ISSUE TITLE
REQUEST: New integration for kubernetes-sigs/cluster-api-provider-azure

### ISSUE THREAD

**Issue by willie-yao** [kubernetes/org#4190]
### Organization or Repo

kubernetes-sigs/cluster-api-provider-azure

### Name of integration

Codecov

### Link to integration website

https://github.com/apps/codecov

### Describe what is attempting to be accomplished

We are working on improving code coverage visualization in CAPZ. Currently, the codecov-commenter bot automatically comments on PRs that upload a codecov report. However, this codecov-commenter bot is outdated and using the Codecov GitHub app is the recommended practice.

Older codecov-commenter: https://github.com/codecov-commenter

**Comment by mrbobbytables** [comment]
It has been enabled, can you verify you see it?

**Comment by willie-yao** [comment]
@mrbobbytables It's now been added. Thank you so much!
