### ISSUE TITLE
REQUEST: New membership for @yulng

### ISSUE THREAD

**Issue by yulng** [kubernetes/org#4194]
### GitHub Username

@yulng

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@windsonsea

### Sponsor 2

@liggitt
@tengqm

### List of contributions to the Kubernetes project

Merged:

> * []()https://github.com/kubernetes/kubernetes/pull/117380
> * []()https://github.com/kubernetes/kubernetes/pull/117237
> * []()https://github.com/kubernetes/kubernetes/pull/114447
> * []()https://github.com/kubernetes-sigs/kwok/pull/554
> * []()https://github.com/kubernetes-sigs/kwok/pull/561
> * []()https://github.com/kubernetes/website/pull/40268
> * []()https://github.com/kubernetes/website/pull/40256
> * []()https://github.com/kubernetes/website/pull/40244
> * []()https://github.com/kubernetes/website/pull/40182
> * []()https://github.com/kubernetes/website/pull/40217
> * []()https://github.com/kubernetes/website/pull/40218
Opened:
> * []()https://github.com/kubernetes/kubernetes/pull/117003
> * []()https://github.com/kubernetes/kubernetes/pull/116949
> * []()https://github.com/kubernetes/kubernetes/pull/116924

**Comment by yulng** [comment]
> ### GitHub Username
> @yulng
> 
> ### Organization you are requesting membership in
> kubernetes, kubernetes-sigs
> 
> ### Requirements
> * [x]  I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
> * [x]  I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
> * [x]  I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
> * [x]  I am actively contributing to 1 or more Kubernetes subprojects
> * [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
> * [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
> * [x]  I have verified that my sponsors are from different member companies
> * [x]  I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
> * [x]  **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
> 
> ### Sponsor 1
> @windsonsea
> 
> ### Sponsor 2
> @liggitt
> @tengqm
> ### List of contributions to the Kubernetes project
> Merged: [kubernetes/kubernetes#117380](https://github.com/kubernetes/kubernetes/pull/117380) [kubernetes/kubernetes#117237](https://github.com/kubernetes/kubernetes/pull/117237) [kubernetes/kubernetes#114447](https://github.com/kubernetes/kubernetes/pull/114447) [kubernetes-sigs/kwok#554](https://github.com/kubernetes-sigs/kwok/pull/554) [kubernetes/website#40268](https://github.com/kubernetes/website/pull/40268) [kubernetes/website#40256](https://github.com/kubernetes/website/pull/40256) [kubernetes/website#40244](https://github.com/kubernetes/website/pull/40244) [kubernetes/website#40182](https://github.com/kubernetes/website/pull/40182) [kubernetes/website#40217](https://github.com/kubernetes/website/pull/40217) [kubernetes/website#40218](https://github.com/kubernetes/website/pull/40218) Opened: [kubernetes/kubernetes#117003](https://github.com/kubernetes/kubernetes/pull/117003) [kubernetes/kubernetes#116949](https://github.com/kubernetes/kubernetes/pull/116949) [kubernetes/kubernetes#116924](https://github.com/kubernetes/kubernetes/pull/116924)

**Comment by windsonsea** [comment]
+1

Look forward to your more contributions, thanks.

**Comment by tengqm** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@yulng, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4198 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

**Comment by yulng** [comment]
> /assign
> 
> @yulng, thank you for all your contributions so far 🙂
> 
> I've created PR #4198 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉

Thank you very much😄😄
