### ISSUE TITLE
REQUEST: New membership for @charles-chenzz

### ISSUE THREAD

**Issue by charles-chenzz** [kubernetes/org#4196]
### GitHub Username

@charles-chenzz

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu

### Sponsor 2

@ahg-g

### List of contributions to the Kubernetes project

- PRs authored
https://github.com/kubernetes/kubernetes/pulls/charles-chenzz
https://github.com/kubernetes-sigs/jobset/pulls/charles-chenzz

- Issues reponded to
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+is%3Aopen+charles-chenzz

- SIG projects I'm involved with
https://github.com/kubernetes-sigs/jobset

**Comment by pacoxu** [comment]
+1 
Thanks for your contributions.

**Comment by ahg-g** [comment]
+1, thanks!

**Comment by Priyankasaggu11929** [comment]
/assign

@charles-chenzz , thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4230 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
