### ISSUE TITLE
REQUEST: New membership for chrisdoherty4

### ISSUE THREAD

**Issue by chrisdoherty4** [kubernetes/org#4199]
### GitHub Username

@chrisdoherty4

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@g-gaston

### Sponsor 2

@rohityadavcloud

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/234
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/233
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/232
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/214
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/216
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/224
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/226

**Comment by rohityadavcloud** [comment]
+1

thanks for your contributions @chrisdoherty4 

/assign

**Comment by g-gaston** [comment]
+1

thanks a lot @chrisdoherty4 and welcome!

**Comment by cprivitere** [comment]
+1
