### ISSUE TITLE
REQUEST: Archive repo kubernetes-sigs/kube-batch

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/org#4200]
### Repository to archive

kubernetes-sigs/kube-batch

### Repository and/or sig subproject owners that are approving this archival

@k82cn

### When should this be done

asap

### Additional context for request

Approval from current owner: https://github.com/kubernetes-sigs/kube-batch/issues/948#issuecomment-1537355908.

**Comment by alculquicondor** [comment]
+1

**Comment by mrbobbytables** [comment]
everything is merged, going to go ahead and close

/close
