### ISSUE TITLE
REQUEST: New membership for @vadasambar

### ISSUE THREAD

**Issue by vadasambar** [kubernetes/org#4203]
### GitHub Username

@vadasambar

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@gjtempleton

### Sponsor 2

@elmiko

### List of contributions to the Kubernetes project

Here's my main contribution (can add more links if you want):
* https://github.com/kubernetes/autoscaler/pull/5507 
* https://github.com/kubernetes/autoscaler/pull/5594 
* https://github.com/kubernetes/autoscaler/pull/5632 
* Ready for review: https://github.com/kubernetes/autoscaler/pull/5672
* WIP: https://github.com/kubernetes/autoscaler/pull/5708
* WIP: https://github.com/kubernetes/autoscaler/pull/5729   

I am mostly involved in sig-autoscaling at this point.

**Comment by gjtempleton** [comment]
👍 From me, Suraj's been making great contributions to SIG autoscaling so far, looking forward to their future contributions!

**Comment by elmiko** [comment]
+1 from me, happy to see Suraj join the organization
