### ISSUE TITLE
REQUEST: Migrate telekom/cluster-api-ipam-provider-in-cluster to kubernetes-sigs

### ISSUE THREAD

**Issue by schrej** [kubernetes/org#4204]
### New repo, staging repo, or migrate existing

Migrate https://github.com/telekom/cluster-api-ipam-provider-in-cluster

### Is it a staging repo?

no

### Requested name for new repository

cluster-api-ipam-provider-in-cluster

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@cecilerobertmichon @fabriziopandini @schrej

### Who should be listed as approvers in OWNERS?

@schrej @srm09 

### Who should be listed in SECURITY_CONTACTS?

@fabriziopandini @cecilerobertmichon @schrej

### What should the repo description be?

A Cluster API IPAM provider that manages addresses as resources in-cluster.

### What SIG and subproject does this fall under?

sig-cluster-lifecycle

### Please provide references to appropriate approval for this new repo

https://github.com/telekom/cluster-api-ipam-provider-in-cluster/issues/110
This issue also contains a checklist with all the preparation tasks required for the move as listed in the documentation.

### Additional context for request

We have additional approvers lined up, but they'll need to join `kubernetes-sigs` first.

@CecileRobertMichon @fabriziopandini would you like approver access as well? I would skip it to avoid unnecessary assignments. (Is there a way to have "passive" approvers to provide SIG leads permissions without getting them assigned automatically?)

**Comment by fabriziopandini** [comment]
/lgtm

> @CecileRobertMichon @fabriziopandini would you like approver access as well? 

I'm ok following the same approach used by other providers (I consider notification only if directly mentioned, otherwise I defer to the project team)

**Comment by CecileRobertMichon** [comment]
/lgtm

> otherwise I defer to the project team

@schrej are there any additional reviews/OWNERs besides yourself? I don't think either myself or @fabriziopandini (I'll let Fabrizio speak for himself though) have the bandwidth to 1) review every single PR, or 2) take over the project if you were to step away from it

Rather than adding us both as individual approvers, I would recommend adding a "group" of owners as admins/approvers (such as CAPI approvers or admins), in addition to the approvers for the IPAM provider (for now sounds like it's just you).

**Comment by christianang** [comment]
We did have some discussion in https://github.com/telekom/cluster-api-ipam-provider-in-cluster/pull/128 about adding @tylerschultz and @srm09 as approvers. Tyler I believe would need approval to be a member, but I can ask him to open an issue to get membership if that is the correct next step.

**Comment by schrej** [comment]
@christianang he'll need sponsors from two different companies and needs to be able to show some contributions to Kubernetes projects (this one probably doesn't count yet), then he can open an issue.

> I don't think either myself or @fabriziopandini have the bandwidth to 1) review every single PR

@CecileRobertMichon that's what I thought. Ideally I'd like to add you as passive approvers so you _can_ approve as technical sig leads, but don't get suggested by the bot. But I don't think thats an option at the moment.

I would suggest to discuss approvers outside of this issue. The plan is to increase them to at least 2-3 people, but we can take care of that after the move. We shouldn't have an issue finding enough people.

**Comment by srm09** [comment]
Awesome to see this move finally happen, thanks for leading the way @schrej 
I agree to have Tyler added as an approver, in the meantime Jakob and I could do the work of PR approval and have Tyler add in passive reviews on any PRs issued.

**Comment by nikhita** [comment]
@CecileRobertMichon @fabriziopandini let us know when you are good with proceeding with the repo transfer and we'll work out next steps.

**Comment by CecileRobertMichon** [comment]
> I agree to have Tyler added as an approver, in the meantime Jakob and I could do the work of PR approval and have Tyler add in passive reviews on any PRs issued.

SGTM

@nikhita we are good to proceed

**Comment by fabriziopandini** [comment]
+1 from me!
