### ISSUE TITLE
REQUEST: New membership for Argh4k

### ISSUE THREAD

**Issue by Argh4k** [kubernetes/org#4205]
### GitHub Username

@Argh4k

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@marseel

### Sponsor 2

@wojtek-t

### List of contributions to the Kubernetes project

Mainly working on perf-tests project

- Custom executor for testing prometheus queries in ClusterLoader2 in perf tests (https://github.com/kubernetes/perf-tests/pull/1948, https://github.com/kubernetes/perf-tests/pull/1949)
- Extended P&F grafana dashboards in perf-tests (https://github.com/kubernetes/perf-tests/pull/1979)
- Fix for a race condition in the timeout handler in k8s/k8s (https://github.com/kubernetes/kubernetes/pull/108455) (cherry-picked to 1.23, 1.22, 1.21)
- Revert of performance regression found by scalability tests (https://github.com/kubernetes/kubernetes/pull/109151)
- Do not print status stack in timeout handler in case of timeout (https://github.com/kubernetes/kubernetes/pull/112374) 
- Active member of SIG Scalability oncall

**Comment by wojtek-t** [comment]
+1

**Comment by marseel** [comment]
huge +1
Thanks for all the contributions so far!
