### ISSUE TITLE
REQUEST: New membership for @vishalanarase

### ISSUE THREAD

**Issue by vishalanarase** [kubernetes/org#4206]
### GitHub Username

@vishalanarase

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@gjtempleton

### Sponsor 2

@elmiko

### List of contributions to the Kubernetes project

Here's my main contribution

https://github.com/kubernetes/autoscaler/pull/4852
https://github.com/kubernetes/autoscaler/pull/5226
https://github.com/kubernetes/autoscaler/pull/5530
https://github.com/kubernetes/autoscaler/pull/5743

I'm involved in sig-autoscaling

**Comment by elmiko** [comment]
+1 from me, happy to see Suraj join the organization

**Comment by vishalanarase** [comment]
> is this a duplicate of https://github.com/kubernetes/org/issues/4203 ?

@elmiko No, I have made a new request. I would also want to join the org.

**Comment by elmiko** [comment]
apologies, i missed the name difference. i will review the contributions and respond here.

**Comment by vishalanarase** [comment]
No worries, I'll appreciate your review.

**Comment by gjtempleton** [comment]
+1 from me, thanks for all your contributions so far!

**Comment by Priyankasaggu11929** [comment]
/assign

@vishalanarase,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4268 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
