### ISSUE TITLE
REQUEST: New membership for moficodes

### ISSUE THREAD

**Issue by moficodes** [kubernetes/org#4215]
### GitHub Username

moficodes

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@furkatgofurov7

### Sponsor 2

@gracenng

### List of contributions to the Kubernetes project

- SIG projects @moficodes involved with: sig-release
- @moficodes is Bug Triage Shadow for 1.28
- Contributor to kubernetes-sigs/kueue

**Comment by furkatgofurov7** [comment]
+1

Welcome to the Release team @moficodes! Thank you for volunteering! 🎉

**Comment by gracenng** [comment]
+1 welcome to the Release Team!

**Comment by Priyankasaggu11929** [comment]
/assign

@moficodes,  I've created PR https://github.com/kubernetes/org/pull/4230 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
