### ISSUE TITLE
REQUEST: Create kubernetes-sigs/sigs-github-actions

### ISSUE THREAD

**Issue by helayoty** [kubernetes/org#4218]
### New repo, staging repo, or migrate existing

New repository

### Is it a staging repo?

no

### Requested name for new repository

sigs-github-actions

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@kubernetes/sig-contributor-experience-leads 

### Who should have write access?

@kubernetes/sig-contributor-experience-leads 

### Who should be listed as approvers in OWNERS?

Each dedicated sig folder will have its sig leads as OWNERS

### Who should be listed in SECURITY_CONTACTS?

 @kubernetes/sig-contributor-experience-leads 

### What should the repo description be?

Repository for GitHub actions and artifacts related to all sigs in Kubernetes.

### What SIG and subproject does this fall under?

@kubernetes/sig-contributor-experience-leads 

### Please provide references to appropriate approval for this new repo

Based on the [slack](https://kubernetes.slack.com/archives/C1TU9EB9S/p1684984449453749) discussion, [this](https://github.com/kubernetes/org/issues/4218#issuecomment-1561791843) issue, and https://github.com/kubernetes/community/issues/7316

### Additional context for request

Following the best practice from sig-auth:
- https://github.com/kubernetes/kubernetes/issues/111963
- https://github.com/kubernetes-sigs/sig-auth-tools
- https://github.com/kubernetes/org/issues/4170#issuecomment-1562242396
- Tools needed to update Github [dashboard](https://github.com/orgs/kubernetes/projects/79/views/1).

@kubernetes/sig-release-leads @kubernetes/sig-scheduling-leads @kubernetes/sig-auth-leads

**Comment by alculquicondor** [comment]
@mrbobbytables it feels like there could be a more generic repo for things like this.

Are you aware of any prior work?

**Comment by helayoty** [comment]
I'm happy to work with @kubernetes/sig-auth-leads to unify the already created [repo](https://github.com/kubernetes-sigs/sig-auth-tools) and add a new GitHub action to it instead of maintaining a new one.

**Comment by kerthcet** [comment]
/cc
Help to see that.

**Comment by aramase** [comment]
> Based on our discussion with https://github.com/orgs/kubernetes/teams/sig-auth-leads today in the biweekly meeting, it would be nice to have a new repo that can host all SIGs Github actions. The repo can be with the ./github/sig-<name> folder structure so each sig can own and maintain their list of GH actions.

I would be happy to modify the code to make it generic enough and add it to the new repo when it's created, so each SIG can use it by passing the config.

**Comment by mrbobbytables** [comment]
FWIW - there are a bunch from kubebuilder that are being reused all over the place too. I do think consolidating makes sense - it also means the repo owners (likely github admins) could rapidly make a change if one is implemented in an insecure way.

**Comment by cpanato** [comment]
+1 i think that will be really useful

**Comment by MadhavJivrajani** [comment]
+1 to the idea with ContribEx hat on
Based on the repo structure described in https://github.com/kubernetes/community/issues/7316, I think we should also move the GitHub admins to be root approvers for this repo.

> All sig leads

Under "Who Should Have Write Access", just making sure I'm understanding this correctly, write access is given to SIG leads that have actions hosted in this repo, correct?

**Comment by helayoty** [comment]
> Based on the repo structure described in https://github.com/kubernetes/community/issues/7316, I think we should also move the GitHub admins to be root approvers for this repo.

Agree

> Under "Who Should Have Write Access", just making sure I'm understanding this correctly, write access is given to SIG leads that have actions hosted in this repo, correct?

@medyagh, ideally, the write access should be for all sig-leads.

**Comment by MadhavJivrajani** [comment]
> the write access should be for all sig-leads.

@helayoty - I'm not sure about this mainly for the reason that at least initially, the number of sig leads will be far greater than the number of sigs hosting actions, and I'm a little concerned about giving unnecessary write access, especially to a repo hosting actions, I could be missing something here though.

One downside of not having _all_ sig leads and only having sig leads who actually have actions hosted is - when we onboard a new sig, the leads would need to be added explicitly (which is preferable imo). We could document this in the README and have an issue template for any sig that wants to start hosting actions here where a checklist item would be `GitHub Admins to give SIG leads write access` or something along those lines.

@Priyankasaggu11929 @nikhita wdyt?

**Comment by Priyankasaggu11929** [comment]
> the number of sig leads will be far greater than the number of sigs hosting actions, and I'm a little concerned about giving unnecessary write access, especially to a repo hosting actions

Totally agree! Currently, I don't think all sig leads should have `write` access by default. The repository will (eventually) have sensitive information needed for running GitHub Actions. Giving such broad `write` access would expose that sensitive info to people who don't need it right now (and might cause unnecessary security issues).

My suggestion is to onboard sigs when there is actually a requirement. 

>We could document this in the README and have an issue template for any sig that wants to start hosting actions here where a checklist item would be GitHub Admins to give SIG leads write access or something along those lines.

+1, this way we (SIG ContribEx / GitHub Admins) can keep track of new sig leads joining the repo.

**Comment by cpanato** [comment]
agree, there is nothing much to change in this repo, so we can limit the access to be easier to manage

**Comment by helayoty** [comment]
Sounds good. Let's limit the write access to Contrib Ex then

**Comment by MadhavJivrajani** [comment]
/assign
Thank you for the discussion, I'll go ahead with creating this repository.
@helayoty - I've edited the description for write access according to https://github.com/kubernetes/org/issues/4218#issuecomment-1578963746

**Comment by MadhavJivrajani** [comment]
The repo has been created here: https://github.com/kubernetes-sigs/sigs-github-actions 🎉 

The following PRs have been created to add GitHub teams and subproject documentation:
- https://github.com/kubernetes/org/pull/4293
- https://github.com/kubernetes/community/pull/7364

Additionally, in the repo, root approval and SECURITY_CONTACTS are listed as ContribEx TLs + GH Admins.

Closing this issue now, thanks!
/close
