### ISSUE TITLE
REQUEST: New membership for rashansmith

### ISSUE THREAD

**Issue by rashansmith** [kubernetes/org#4233]
### GitHub Username

@rashansmith

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sanchita-07

### Sponsor 2

@gracenng

### List of contributions to the Kubernetes project

@rashansmith is Release Notes Shadow for 1.28

**Comment by sanchita-07** [comment]
+1,  Welcome to the release team. :tada:

**Comment by gracenng** [comment]
+1 excited to have you aboard
