### ISSUE TITLE
REQUEST: New membership for weizhouapache

### ISSUE THREAD

**Issue by weizhouapache** [kubernetes/org#4240]
### GitHub Username

@weizhouapache

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@rohityadavcloud

### Sponsor 2

@chrisdoherty4

### List of contributions to the Kubernetes project

Merged PRs
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/238
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/241
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/242
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/243
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/247
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/257

Open issues
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/issues/246

**Comment by rohityadavcloud** [comment]
+1 

Thanks for your contributions @weizhouapache

**Comment by chrisdoherty4** [comment]
+1

Thanks for your contribution!

**Comment by Priyankasaggu11929** [comment]
Hi, sponsors need to be listed as a reviewer/approver in an OWNERS file in one of the https://github.com/kubernetes or https://github.com/kubernetes-sigs orgs. It looks like @chrisdoherty4  is not (please correct me if I'm mistaken!). :slightly_smiling_face:

**Comment by rohityadavcloud** [comment]
@Priyankasaggu11929 can you check https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/blob/main/OWNERS or is there any other OWNERS/SIG file we need to add @chrisdoherty4 ?

**Comment by Priyankasaggu11929** [comment]
> can you check https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/blob/main/OWNERS or is there any other OWNERS/SIG file we need to add @chrisdoherty4 ?

^ works. Thank you. :slightly_smiling_face:

**Comment by Priyankasaggu11929** [comment]
/assign

@weizhouapache,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4246 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
