### ISSUE TITLE
REQUEST: New membership for @cahillsf

### ISSUE THREAD

**Issue by cahillsf** [kubernetes/org#4241]
### GitHub Username

@cahillsf

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@rifelpet

### Sponsor 2

@killianmuldoon

### List of contributions to the Kubernetes project

- PRs authored:
  - [https://github.com/kubernetes-sigs/cluster-api/pull/8463](https://github.com/kubernetes-sigs/cluster-api/pull/8463)
  - [https://github.com/kubernetes-sigs/cluster-api/pull/8423](https://github.com/kubernetes-sigs/cluster-api/pull/8423)
  - [https://github.com/kubernetes-sigs/cluster-api/pull/8422](https://github.com/kubernetes-sigs/cluster-api/pull/8422)
  - [https://github.com/kubernetes-sigs/cluster-api/pull/8351](https://github.com/kubernetes-sigs/cluster-api/pull/8351)
- SIG projects I am involved in: [CAPI](https://github.com/kubernetes-sigs/cluster-api)

**Comment by killianmuldoon** [comment]
+100

@cahillsf  has done some valuable contributions so far - looking forward to working with him in the community going forward.

**Comment by cahillsf** [comment]
thanks @killianmuldoon, looking forward to it as well!

**Comment by rifelpet** [comment]
+1

I'm also looking forward to @cahillsf's future contributions in the community

**Comment by cahillsf** [comment]
thanks for all of your help/input over the past several months @rifelpet !

**Comment by Priyankasaggu11929** [comment]
/assign

@cahillsf, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4246 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
