### ISSUE TITLE
REQUEST: New membership for @vasubabu(https://github.com/vasubabu)

### ISSUE THREAD

**Issue by vasubabu** [kubernetes/org#4249]
### GitHub Username

@vasubabu

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-csi, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@displague

### Sponsor 2

@cprivitere

### List of contributions to the Kubernetes project

 - PRs reviewed/authored
   * https://github.com/kubernetes-sigs/kubespray/pull/10044
   * https://github.com/kubernetes-sigs/cluster-api/pull/8596

 - SIG Projects I am involved with
   * Kubespray https://github.com/kubernetes-sigs/kubespray
   * cluster-api https://github.com/kubernetes-sigs/cluster-api

**Comment by mrbobbytables** [comment]
@vasubabu - it usually takes a bit more in terms of contributions to become an org members.

**Comment by Priyankasaggu11929** [comment]
Hey, it's been more than a month since the issue was opened.

I'll close it for now, but feel free to reopen or start a new issue once the requirements are met.

/close
