### ISSUE TITLE
REQUEST: New membership for sreis

### ISSUE THREAD

**Issue by sreis** [kubernetes/org#425]
### GitHub Username
@sreis

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @d-nishi 
- @leakingtapan

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/187
  - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/183
  - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/163
- SIG projects I am involved with
  - sig-aws
  - sig-storage
  - sig-node

**Comment by leakingtapan** [comment]
+1

**Comment by mrbobbytables** [comment]
@sreis @bertinatto Just pinging to see if another +1 can be added :)

**Comment by sreis** [comment]
@mrbobbytables bertinatto is unreachable and I was asked to do a few more PRs to get approval. Should I leave this one open or do you want me to close and reopen later?

**Comment by mrbobbytables** [comment]
If you think it'll be a few more weeks, I'd go ahead and close/reopen. It'll be a bit more of a fresh ping to process the request.

**Comment by d-nishi** [comment]
Thanks @mrbobbytales @sreis and @leakingtapan
