### ISSUE TITLE
REQUEST: New membership for bugoverdose

### ISSUE THREAD

**Issue by bugoverdose** [kubernetes/org#4250]
### GitHub Username

@bugoverdose

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ysyukr

### Sponsor 2

@jihoon-seo

### List of contributions to the Kubernetes project

PRs authored ([link](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Abugoverdose+))
- https://github.com/kubernetes/website/pull/40972
- https://github.com/kubernetes/website/pull/40985
- https://github.com/kubernetes/website/pull/40988
- https://github.com/kubernetes/website/pull/41253
- https://github.com/kubernetes/website/pull/40989
- https://github.com/kubernetes/website/pull/41254
- https://github.com/kubernetes/website/pull/40980
- https://github.com/kubernetes/website/pull/41417

SIG projects I am involved with
- kubernetes/sig-docs

**Comment by jihoon-seo** [comment]
+1, @bugoverdose has been actively contributing on K8s projects, where one of those is the Korean localization work of K8s docs.

**Comment by ysyukr** [comment]
++1
I am one of the approvers for Korean localization contents in k/website (SIG-Docs).
@bugoverdose is active contributor especially for SIG-Docs localization !

**Comment by seokho-son** [comment]
+1 !!
Hope to keep working with @bugoverdose !

**Comment by Priyankasaggu11929** [comment]
/assign

@bugoverdose,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4268 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
