### ISSUE TITLE
REQUEST: New membership for ocobleseqx

### ISSUE THREAD

**Issue by ocobles** [kubernetes/org#4252]
### GitHub Username

@ocobleseqx

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@detiber

### Sponsor 2

@thebsdbox

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/412
- https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/465
- https://github.com/equinix/cloud-provider-equinix-metal/issues/403
- https://github.com/equinix/cloud-provider-equinix-metal/pull/340#issuecomment-1387307613

**Comment by detiber** [comment]
+1 from me, more than happy to sponsor Oscar for Org membership

**Comment by thebsdbox** [comment]
+1 for me for Oscar!

**Comment by Priyankasaggu11929** [comment]
Hey, it's been about a month since the issue was opened.

I'll close it for now, but feel free to reopen or start a new issue once the requirements are met.

/close

**Comment by displague** [comment]
@ocobles's contributions to cloud-provider-equinix-metal were previously in another GH org, which contributed to the initial comments about applicability. Those contributions are now kubernetes-sigs homed.

**Comment by displague** [comment]
@ocobles please update the username in the issue template and title

**Comment by Priyankasaggu11929** [comment]
Hello @ocobles, could you also please update the `List of contributions to the Kubernetes project` section with your recent contributions?

I wasn't able to find any GH activity after last year's discussion (May, 2023).
https://github.com/search?q=org%3Akubernetes-sigs++author%3Aocobles&type=issues

**Comment by Priyankasaggu11929** [comment]
I'll close it for now, but feel free to reopen or start a new issue when needed. Thank you! 

/close
