### ISSUE TITLE
REQUEST: New membership for ike-ma@

### ISSUE THREAD

**Issue by ike-ma** [kubernetes/org#4257]
### GitHub Username

@ike-ma

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

SergeyKanzhelev

### Sponsor 2

chendave

### List of contributions to the Kubernetes project

- Recent PRs merged
  * https://github.com/kubernetes/perf-tests/pull/2259
  * https://github.com/kubernetes/test-infra/pull/29192
  * https://github.com/kubernetes/kubernetes/pull/117017
  * https://github.com/kubernetes/test-infra/issues/28888

- SIG projects I am involved in
  * sig-node
  * sig-testing

**Comment by SergeyKanzhelev** [comment]
+1 from me.

Welcome @ike-ma!

**Comment by chendave** [comment]
Huge +1

Welcome @ike-ma !

**Comment by Priyankasaggu11929** [comment]
/assign

@ike-ma,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4268 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
