### ISSUE TITLE
REQUEST: New membership for dlipovetsky

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes/org#426]
### GitHub Username
@dlipovetsky

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @roberthbailey 
- @detiber

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api/pull/548
  - https://github.com/kubernetes/kubernetes/pull/73339
  - https://github.com/kubernetes/website/pull/9663
  - https://github.com/kubernetes/community/pull/2692
  - https://github.com/kubernetes-sigs/cluster-api/pull/394
- Issues responded to
  - https://github.com/kubernetes/kubeadm/issues/857
  - https://github.com/kubernetes-sigs/cluster-api/issues/490
  - https://github.com/kubernetes-sigs/cluster-api/issues/639
  - https://github.com/kubernetes/org/issues/308
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/cluster-api

**Comment by detiber** [comment]
+1 from me

**Comment by roberthbailey** [comment]
+1 from me too.

**Comment by mrbobbytables** [comment]
Hey there @dlipovetsky, thank you for all your contributions so far :)

I've created PR #428  to add you to both the  @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign
