### ISSUE TITLE
REQUEST: New membership for chenlin07

### ISSUE THREAD

**Issue by chenlin07** [kubernetes/org#4261]
### GitHub Username

@chenlin07 

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@lubronzhan

### Sponsor 2

@nicolehanjing

### List of contributions to the Kubernetes project

- PR authored
https://github.com/kubernetes/cloud-provider-vsphere/pull/580
https://github.com/kubernetes/cloud-provider-vsphere/pull/579
https://github.com/kubernetes/cloud-provider-vsphere/pull/578
https://github.com/kubernetes/cloud-provider-vsphere/pull/577
https://github.com/kubernetes/cloud-provider-vsphere/pull/570
- issue
https://github.com/kubernetes/cloud-provider-vsphere/issues/565

**Comment by lubronzhan** [comment]
+1 !

**Comment by Priyankasaggu11929** [comment]
Hello @nicolehanjing, just checking in.

We need your +1 as a sponsor, to proceed with this request. Thank you. :slightly_smiling_face:

**Comment by Priyankasaggu11929** [comment]
Ping @nicolehanjing. Just following up for your +1 as a sponsor, to move ahead on the membership. Thank you!

**Comment by Priyankasaggu11929** [comment]
Hello @chenlin07, Could you please follow up with your sponsors to review the ticket? Thanks!

**Comment by Priyankasaggu11929** [comment]
Hey, it's been more than a month since the issue was opened.

I'll close it for now, but feel free to reopen or start a new issue once the requirements are met.

/close
