### ISSUE TITLE
REQUEST: New membership for ricmmartins

### ISSUE THREAD

**Issue by ricmmartins** [kubernetes/org#4269]
### GitHub Username

@ricmmartins

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dougsland

### Sponsor 2

@stormqueen1990

### List of contributions to the Kubernetes project

- PRs authored
https://github.com/kubernetes/website/pull/40549
https://github.com/kubernetes/website/pull/40546
https://github.com/kubernetes/website/pull/40547
https://github.com/kubernetes/website/pull/40511
https://github.com/kubernetes/website/pull/40548
https://github.com/kubernetes/website/pull/40550

- SIG projects I'm involved with: SIG Docs

**Comment by dougsland** [comment]
good stuff @ricmmartins!! Welcome!!
+1
/lgtm

**Comment by stormqueen1990** [comment]
+1

Ricardo is doing a good job on his Brazilian Portuguese localization contributions!

**Comment by Priyankasaggu11929** [comment]
/assign

@ricmmartins,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4276 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
