### ISSUE TITLE
REQUEST: New membership for qedrakmar

### ISSUE THREAD

**Issue by qedrakmar** [kubernetes/org#427]
### GitHub Username
@qedrakmar

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp 
- @mrbobbytables 

### List of contributions to the Kubernetes project
- Previous member of release team (1.10)
- Active member of SIG-contribex
- Helped run New Contributor Workshops
- Currently leading the non-code-contributors effort within the contributor's guide subproject, in which other members are trying to assign issues to me

**Comment by mrbobbytables** [comment]
+1 :D

/pony yay

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by mrbobbytables** [comment]
@qedrakmar once  PR #428 gets merged, you should get your membership invite notification :)

yay! :tada:

/assign
/pony party
