### ISSUE TITLE
REQUEST: New membership for Eileen-Yu

### ISSUE THREAD

**Issue by Eileen-Yu** [kubernetes/org#4270]
### GitHub Username

@Eileen-Yu

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@camilamacedo86

### Sponsor 2

@everettraven

### List of contributions to the Kubernetes project

- PRs:
https://github.com/kubernetes-sigs/kubebuilder/pull/3419
https://github.com/kubernetes-sigs/kubebuilder/pull/3412
https://github.com/kubernetes-sigs/kubebuilder/pull/3231
https://github.com/kubernetes-sigs/kubebuilder/pull/3213
https://github.com/kubernetes-sigs/kubebuilder/pull/3199
https://github.com/kubernetes-sigs/kubebuilder/pull/3191
https://github.com/kubernetes-sigs/kubebuilder/pull/3181
https://github.com/kubernetes-sigs/kubebuilder/pull/2925
https://github.com/kubernetes-sigs/kubebuilder/pull/2924
https://github.com/kubernetes-sigs/kubebuilder/pull/3437
https://github.com/kubernetes-sigs/kubebuilder/pull/3216

- SIGs:
https://github.com/kubernetes-sigs/kubebuilder

**Comment by camilamacedo86** [comment]
+1 
More than happy to sponsor her

/lgtm
/approved

**Comment by Priyankasaggu11929** [comment]
/assign

@Eileen-Yu,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4276 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
