### ISSUE TITLE
REQUEST: New membership for Virusuki

### ISSUE THREAD

**Issue by Virusuki** [kubernetes/org#4272]
### GitHub Username

@Virusuki

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ysyukr

### Sponsor 2

@jihoon-seo

### List of contributions to the Kubernetes project

PRs reviewed ([k/website](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Avirusuki))

- [[ko] Translate tasks/administer-cluster/dns-horizontal-autoscaling in Korean #40265](https://github.com/kubernetes/website/pull/40265)
- [[ko] Update outdated files in dev-1.26-ko.1 (M10-M13) #40721](https://github.com/kubernetes/website/pull/40721)
- [[ko] Translate tasks/debug/debug-application/debug-service in Korean #40463](https://github.com/kubernetes/website/pull/40463)
- [[ko] Translate reference/node/kubelet-checkpoint-api in Korean #41119](https://github.com/kubernetes/website/pull/41119)
- [[ko] Update outdated files in dev-1.26.-ko.1 [M149-155] #40938](https://github.com/kubernetes/website/pull/40938)
- [[ko] modify kubelet in lowercase in kubelet-authn-authz doc. #41467](https://github.com/kubernetes/website/pull/41467)
- [[ko] fix typo in volumes.md #41465](https://github.com/kubernetes/website/pull/41465)

SIG projects I am involved with
kubernetes/sig-docs

**Comment by ysyukr** [comment]
++1
I am one of the approvers for Korean localization contents in k/website (SIG-Docs).
@Virusuki is active contributor especially for SIG-Docs localization !

**Comment by jihoon-seo** [comment]
+1 for the membership of @Virusuki, he is such a passionate contributor!

**Comment by seokho-son** [comment]
+1 !! :)
Thanks @Virusuki

**Comment by Priyankasaggu11929** [comment]
/assign

@Virusuki,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4276 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
