### ISSUE TITLE
Grant admin permissions to Fedosin in kubernetes-sigs/cluster-api-operator

### ISSUE THREAD

**Issue by Fedosin** [kubernetes/org#4277]
### Organization or Repo

kubernetes-sigs/cluster-api-operator

### User affected

@Fedosin

### Describe the issue

Currently I am in [cluster-api-operator-admins](https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/OWNERS_ALIASES#L18) group, but I still don't have admin access for the repository.

**Comment by Fedosin** [comment]
cc: @alexander-demicev @furkatgofurov7

**Comment by furkatgofurov7** [comment]
@Fedosin so you have to add yourself to https://github.com/kubernetes/org/blob/a861b7ea19fb5b945166449cfc55c62de94178ed/config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml#L61-L66 list to get admin rights?

**Comment by Fedosin** [comment]
@furkatgofurov7 thanks for the information! I opened a PR.
