### ISSUE TITLE
REQUEST: New membership for codefromthecrypt

### ISSUE THREAD

**Issue by codefromthecrypt** [kubernetes/org#4280]
### GitHub Username

codefromthecrypt

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

kerthcet

### Sponsor 2

sanposhiho

### List of contributions to the Kubernetes project

My history really began with @sanposhiho, as I followed him and his blog around WebAssembly and the k8s scheduler. So, I [participated in the issue to support this effort](https://github.com/kubernetes/kubernetes/issues/112851) and invited my friends to help discuss. We eventually joined together on [kube-scheduler-wasm-extension](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension) and I had many activities there since, with [many merged pull requests](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/pulls?q=is%3Apr+is%3Aclosed+author%3Acodefromthecrypt). In some cases we researched improvements for k8s such as [allowing plugins to close gracefully](https://github.com/kubernetes/kubernetes/issues/118147). I'm also on the sig-scheduling slack and participate there as well a lot of collaboration with @kerthcet and @sanposhiho directly, like every day. The project is growing and I would like to help review work by a very strong community member @anuraaga as well. Basically, I spoke with folks and I have time to help more in this project and I would use the broader access to help this SIG reach its goals quicker yet with more people involved.

**Comment by sanposhiho** [comment]
+100
@codefromthecrypt has done a lot in https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension with their expertise from any of designs to the implementation / review. Thanks!

**Comment by kerthcet** [comment]
+100 @codefromthecrypt is the integral part of this project.

**Comment by Priyankasaggu11929** [comment]
/assign

@codefromthecrypt,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4299 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
