### ISSUE TITLE
REQUEST: New membership for @pierreprinetti

### ISSUE THREAD

**Issue by pierreprinetti** [kubernetes/org#4281]
### GitHub Username

@pierreprinetti

### Organization you are requesting membership in

kubernetes, kubernetes-csi, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@s-urbaniak

### Sponsor 2

@tobiasgiese

### List of contributions to the Kubernetes project

New features:
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/531
* https://github.com/kubernetes/test-infra/pull/28341

Address security vulnerabilities:
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1182
* https://github.com/kubernetes-csi/csi-driver-nfs/pull/301
* https://github.com/kubernetes/cloud-provider-openstack/pull/2078

Bug fixes:
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/466
* https://github.com/kubernetes/test-infra/pull/15334
* https://github.com/kubernetes/test-infra/pull/27304
* https://github.com/kubernetes/cloud-provider-openstack/pull/2121
* https://github.com/kubernetes/cloud-provider-openstack/pull/2218

Bug reporting:
* https://github.com/kubernetes/cloud-provider-openstack/issues/2224

Documentation:
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1267

Maintenance:
* https://github.com/kubernetes-csi/csi-driver-nfs/pull/241
* https://github.com/kubernetes-csi/csi-driver-nfs/pull/244
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1156
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1402
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1584
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1585

**Comment by s-urbaniak** [comment]
I have been interacting with @pierreprinetti many times and am more than convinced that he is a super valuable member in the Kubernetes community, +100 from my side 👍

**Comment by tobiasgiese** [comment]
+1 from my side 🙂

**Comment by Priyankasaggu11929** [comment]
/assign

@pierreprinetti,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4299 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
