### ISSUE TITLE
REQUEST: New membership for damdo

### ISSUE THREAD

**Issue by damdo** [kubernetes/org#4283]
### GitHub Username

damdo

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Fedosin

### Sponsor 2

@furkatgofurov7

### List of contributions to the Kubernetes project

I already am a member of [@kubernetes-sigs](https://github.com/kubernetes-sigs) and a reviewer of [cluster-api-operator](https://github.com/kubernetes-sigs/cluster-api-operator).
Kindly asking for an extension to [@kubernetes](https://github.com/kubernetes).

PRs:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2421
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2528
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2430
- https://github.com/kubernetes-sigs/cluster-api/pull/8162
- https://github.com/kubernetes-sigs/kind/pull/1795
- https://github.com/kubernetes/cloud-provider-alibaba-cloud/pull/323
- https://github.com/kubernetes-sigs/cluster-api/pull/5801
- https://github.com/kubernetes-sigs/controller-runtime/pull/1862

Mostly involved in cluster-api, cloud-providers

**Comment by furkatgofurov7** [comment]
+1

/lgtm

**Comment by Priyankasaggu11929** [comment]
/assign

@damdo,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4299 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
