### ISSUE TITLE
REQUEST: New membership for mochizuki875

### ISSUE THREAD

**Issue by mochizuki875** [kubernetes/org#4284]
### GitHub Username

@mochizuki875

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@adrianludwin

### Sponsor 2

@rjbez17

### List of contributions to the Kubernetes project

- PR
https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/234
https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/251
https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/254
https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/260
https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/261
https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/283
https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/294
https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/295

- issue
https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/246
https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/252
https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/274
https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/292
https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/296

**Comment by adrianludwin** [comment]
sgtm!

**Comment by rjbez17** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@mochizuki875,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4299 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
