### ISSUE TITLE
REQUEST: Netlify site for kubernetes/ingress-nginx

### ISSUE THREAD

**Issue by tao12345666333** [kubernetes/org#4285]
### Repository

kubernetes/ingress-nginx

### Project domain

ingress-nginx.sigs.k8s.io

### Additional context for request

We hope to enable preview capability for documentation PRs in the [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) project.

ref:

- https://github.com/kubernetes/ingress-nginx/issues/10071
- https://github.com/kubernetes/ingress-nginx/pull/10073

**NOTICE**

The current documentation website address for this project is: https://kubernetes.github.io/ingress-nginx/

We hope that after enabling the Netlify configuration, this address will still be available (or can be automatically redirected).

This is also the reason why I only configured preview in [PR](https://github.com/kubernetes/ingress-nginx/pull/10073).

Thanks!

cc @rikatz @strongjz

**Comment by rikatz** [comment]
Lgtm

**Comment by tao12345666333** [comment]
/assign @mrbobbytables

Thanks!

**Comment by tao12345666333** [comment]
Thank you, I will handle the follow-up matters.

**Comment by mrbobbytables** [comment]
checking back in - have you sorted out the domain name? Once the k8s.io portion is done I can update the config in netlify.
