### ISSUE TITLE
REQUEST: New membership for ashutosh887

### ISSUE THREAD

**Issue by ashutosh887** [kubernetes/org#4287]
### GitHub Username

@ashutosh887 

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@varshaprasad96 

### Sponsor 2

@camilamacedo86 

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/kubebuilder/pull/3287
- https://github.com/kubernetes-sigs/kubebuilder/pull/3381

Currently working on other issues as well. Creating PR soon.

I am eager to participate and contribute as much as I can to the projects and become an active contributor. Although I am new to the ecosystem, I am putting in my best effort to learn and implement as much as possible, and I am also eager to learn more.
I hope I will get membership in kubernetes repository.

Thank you team!

**Comment by varshaprasad96** [comment]
+1
lgtm

**Comment by camilamacedo86** [comment]
/lgtm 

+1

**Comment by ashutosh887** [comment]
@Priyankasaggu11929 
I'm working on more issues as well and will create PRs soon
Also, I'm actively involved in the discussions and reviews

**Comment by Priyankasaggu11929** [comment]
Hey, it's been about a month since the issue was opened.

I'll close it for now, but feel free to reopen or start a new issue once the requirements are met.

/close
