### ISSUE TITLE
REQUEST: New membership for ruquanzhao

### ISSUE THREAD

**Issue by ruquanzhao** [kubernetes/org#4294]
### GitHub Username

@ruquanzhao

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@chendave

### Sponsor 2

@pacoxu

### List of contributions to the Kubernetes project

**PRs:**
Merged:
- https://github.com/kubernetes/perf-tests/pull/1868
- https://github.com/kubernetes/test-infra/pull/23447
- https://github.com/kubernetes/kubernetes/pull/107135
- https://github.com/kubernetes/kubernetes/pull/108557
- https://github.com/kubernetes/kube-openapi/pull/302
- https://github.com/kubernetes/kubernetes/pull/113132
- https://github.com/kubernetes/kubernetes/pull/114063
- https://github.com/kubernetes/kubernetes/pull/114065
- https://github.com/kubernetes/kubernetes/pull/117544
- https://github.com/kubernetes/kubernetes/pull/117836

In process

- https://github.com/kubernetes/kubernetes/pull/114534
- https://github.com/kubernetes/kubernetes/pull/117431
- https://github.com/kubernetes/kubernetes/pull/118068

**Comment by pacoxu** [comment]
+1 
Thanks for your contributions and hope to work with you on kubeadm related tasks.

**Comment by chendave** [comment]
+1 from me!

welcome @ruquanzhao and thanks for the contribution so far.

**Comment by Priyankasaggu11929** [comment]
/assign

@ruquanzhao,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4299 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
