### ISSUE TITLE
REQUEST: Archive repo kubernetes-sigs/multi-tenancy

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/org#4297]
### Repository to archive

https://github.com/kubernetes-sigs/multi-tenancy

### Repository and/or sig subproject owners that are approving this archival

@tashimi @srampal

### When should this be done

when you have time :-)

### Additional context for request

This is the WG repo and the WG was archived https://github.com/kubernetes/community/pull/7362, I think otherwise a slack channel and this repo remains.

The repo also has not been active since 2021.

**Comment by JimBugwadia** [comment]
Hi Tasha, yes we can go ahead and archive. Thanks!

**Comment by mrbobbytables** [comment]
repo has been archived: https://github.com/kubernetes-retired/multi-tenancy
once teams have been cleaned up and k/community PR merged this issue can be closed.

**Comment by mrbobbytables** [comment]
everything has been merged, closing
/close
