### ISSUE TITLE
REQUEST: Netlify site for  https://cloud-provider-azure.sigs.k8s.io

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/org#4298]
### Repository

kubernetes-sigs/cloud-provider-azure

### Project domain

cloud-provider-azure.sigs.k8s.io

### Additional context for request

 we want to change the default document branch to https://github.com/kubernetes-sigs/cloud-provider-azure/tree/documentation
 
I'm wondering if we can change the default production branch to documentation. Thanks in advance!

**Comment by mrbobbytables** [comment]
done, triggered a build and new site based off that branch has been deployed.

/close
