### ISSUE TITLE
REQUEST: New membership for tianshapjq

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/org#43]
### GitHub Username
@tianshapjq

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xiangpengzhao
- @zhangxiaoyu-zidif

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/67653
https://github.com/kubernetes/kubernetes/pull/62636
https://github.com/kubernetes/kubernetes/pull/62530
https://github.com/kubernetes/kubernetes/pull/62444
https://github.com/kubernetes/kubernetes-docs-zh/pull/271
https://github.com/kubernetes/kubernetes-docs-zh/pull/270
https://github.com/kubernetes/kubernetes-docs-zh/pull/254
https://github.com/kubernetes/kubernetes-docs-zh/pull/225
https://github.com/kubernetes/kubernetes-docs-zh/pull/213
https://github.com/kubernetes/website/pull/7016
https://github.com/kubernetes/website/pull/7003
https://github.com/kubernetes/website/pull/6931
https://github.com/kubernetes/website/pull/6872
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/67226
https://github.com/kubernetes/kubernetes/issues/56617
https://github.com/kubernetes/kubernetes/issues/52757
https://github.com/kubernetes/kubernetes-docs-zh/issues/87
- SIG projects I am involved with
k/kubernetes-docs-zh
k/kubernetes
k/website

**Comment by cblecker** [comment]
Invite sent! Welcome to @kubernetes!
