### ISSUE TITLE
REQUEST: New membership for seokho-son

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/org#430]
### GitHub Username
@seokho-son

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@gochist 
@ClaudiaJKang 

### List of contributions to the Kubernetes project
- PRs authored
[kubernetes/website #12418](https://github.com/kubernetes/website/pull/12418)
[kubernetes/website #12382](https://github.com/kubernetes/website/pull/12382)
[kubernetes/website #12308](https://github.com/kubernetes/website/pull/12308)
[kubernetes/website #12298](https://github.com/kubernetes/website/pull/12298)
[kubernetes/website #12272](https://github.com/kubernetes/website/pull/12272)
[kubernetes/website #12208](https://github.com/kubernetes/website/pull/12208)
[kubernetes/website #12178](https://github.com/kubernetes/website/pull/12178)
[kubernetes/website #12176](https://github.com/kubernetes/website/pull/12176)
[kubernetes/website #12174](https://github.com/kubernetes/website/pull/12174)
[kubernetes/website #12126](https://github.com/kubernetes/website/pull/12126)
[kubernetes/website #12067](https://github.com/kubernetes/website/pull/12067)
[kubernetes/website #12054](https://github.com/kubernetes/website/pull/12054)
[kubernetes/website #11937](https://github.com/kubernetes/website/pull/11937)

- Issues responded to
[kubernetes/website #12160](https://github.com/kubernetes/website/issues/12160)
[kubernetes/website #12383](https://github.com/kubernetes/website/issues/12383)
[kubernetes/website #12401](https://github.com/kubernetes/website/issues/12401)
[kubernetes/website #12381](https://github.com/kubernetes/website/issues/12381)
[kubernetes/website #12299](https://github.com/kubernetes/website/issues/12299)
[kubernetes/website #12227](https://github.com/kubernetes/website/issues/12227)
[kubernetes/website #12207](https://github.com/kubernetes/website/issues/12207)
[kubernetes/website #12177](https://github.com/kubernetes/website/issues/12177)
[kubernetes/website #12166](https://github.com/kubernetes/website/issues/12166)
[kubernetes/website #12125](https://github.com/kubernetes/website/issues/12125)
[kubernetes/website #12064](https://github.com/kubernetes/website/issues/12064)
[kubernetes/website #12015](https://github.com/kubernetes/website/issues/12015)
[kubernetes/website #11914](https://github.com/kubernetes/website/issues/11914)

- SIG projects I am involved with
kubernetes/sig-docs

/area github-membership

**Comment by zacharysarah** [comment]
+1, @seokho-son is actively involved in Korean localization.

@seokho-son 👋 You need one more sponsor. Maybe someone from the Korean localization team?

**Comment by gochist** [comment]
+1, I'm happy to work with @seokho-son !

**Comment by ClaudiaJKang** [comment]
👍 Thank you for your contributions! @seokho-son

**Comment by rlenferink** [comment]
Hey @seokho-son, thank you for all your contributions so far :)

I've created PR #437 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
