### ISSUE TITLE
REQUEST: New membership for hangscer8

### ISSUE THREAD

**Issue by hangscer8** [kubernetes/org#4300]
### GitHub Username

@hangscer8

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@floryut

### Sponsor 2

@cyclinder

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes-sigs/kubespray/pull/10068
https://github.com/kubernetes-sigs/kubespray/pull/10013
https://github.com/kubernetes-sigs/kubespray/pull/10005
https://github.com/kubernetes-sigs/kubespray/pull/9883
https://github.com/kubernetes-sigs/kubespray/pull/9873
https://github.com/kubernetes-sigs/kubespray/pull/9734
https://github.com/kubernetes-sigs/kubespray/pull/9516
https://github.com/kubernetes-sigs/kubespray/pull/9513
https://github.com/kubernetes-sigs/kubespray/pull/9437
https://github.com/kubernetes-sigs/kubespray/pull/9348
https://github.com/kubernetes-sigs/kubespray/pull/9227
https://github.com/kubernetes-sigs/kubespray/pull/8975
- Issues responded to

- SIG projects I am involved with
https://github.com/kubernetes-sigs/kubespray

**Comment by cyclinder** [comment]
+1 for me!

Thank you for your contribution!

/lgtm

**Comment by floryut** [comment]
+1 

Thank you for your contribution man

**Comment by ErikJiang** [comment]
+1

🎉 Welcome @hangscer8

**Comment by oomichi** [comment]
Thanks for your contribution!
+1 from my side
