### ISSUE TITLE
REQUEST: New membership for mloiseleur

### ISSUE THREAD

**Issue by mloiseleur** [kubernetes/org#4301]
### GitHub Username

mloiseleur

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Raffo

### Sponsor 2

@szuecs

### List of contributions to the Kubernetes project

PR authored
- https://github.com/kubernetes-sigs/external-dns/pull/3673

PR participated
- https://github.com/kubernetes-sigs/external-dns/pull/3736
- https://github.com/kubernetes-sigs/external-dns/pull/3670
- https://github.com/kubernetes-sigs/external-dns/pull/3605

PR reviewed
- https://github.com/kubernetes-sigs/external-dns/pull/3720
- https://github.com/kubernetes-sigs/external-dns/pull/3711
- https://github.com/kubernetes-sigs/external-dns/pull/3702
- https://github.com/kubernetes-sigs/external-dns/pull/3405
- https://github.com/kubernetes-sigs/external-dns/pull/3482
- https://github.com/kubernetes-sigs/external-dns/pull/3502
- https://github.com/kubernetes-sigs/external-dns/pull/3535
- https://github.com/kubernetes-sigs/external-dns/pull/3616
- https://github.com/kubernetes-sigs/external-dns/pull/3653
- https://github.com/kubernetes-sigs/external-dns/pull/3669
- https://github.com/kubernetes-sigs/external-dns/pull/3660
- https://github.com/kubernetes-sigs/external-dns/pull/3594
- https://github.com/kubernetes-sigs/external-dns/pull/3456
- https://github.com/kubernetes-sigs/external-dns/pull/3705
- https://github.com/kubernetes-sigs/external-dns/pull/3728
- https://github.com/kubernetes-sigs/external-dns/pull/3739
- https://github.com/kubernetes-sigs/external-dns/pull/3629
- https://github.com/kubernetes-sigs/external-dns/pull/3325
- https://github.com/kubernetes-sigs/external-dns/pull/3282

**Comment by Raffo** [comment]
+1 , approved.

**Comment by mloiseleur** [comment]
@Priyankasaggu11929 Sure.

**Comment by johngmyers** [comment]
@Priyankasaggu11929 my understanding from [the requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) is that reviews of PRs count as contributions.

Admittedly, a review without feedback is hard to assess. I did find feedback from a review of kubernetes-sigs/external-dns#3055, so there is some evidence the reviews are not strictly mechanical.

It is the case that external-dns is in severe need of additional reviewers, so it would be helpful for us to know the criteria for when reviews are assessed as contributions.

**Comment by mloiseleur** [comment]
Yes, my reviews are not mechanical :). 
I focused on reviews instead of new PRs for a simple reason: 90 PRs opened on `external-dns`.

**Comment by Priyankasaggu11929** [comment]
> my understanding from [the requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) is that reviews of PRs count as contributions.

@johngmyers, @mloiseleur, PR reviews/triage are definitely valuable contributions (& thanks for pointing to https://github.com/kubernetes-sigs/external-dns/pull/3055)

Regarding org membership, it's important to demonstrate long-term commitment by consistently investing time and effort in the project for a _while_. Right now, it's a bit early.

@mloiseleur, thank you for all your contributions so far. I suggest you keep actively contributing for a bit longer. When you feel ready again, please update the issue description with a list of all your ongoing active contributions. It would be super helpful if you could categorize PRs/issues as authored, reviewed, participated, etc. I'd be happy to review it again.

>It is the case that external-dns is in severe need of additional reviewers, so it would be helpful for us to know the criteria for when reviews are assessed as contributions.

We're actually discussing ways to improve the documentation on org membership requirements, to make it more clear and up-to-date. 
Thanks for bringing it up!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4340  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by mloiseleur** [comment]
Thanks @mrbobbytables
