### ISSUE TITLE
REQUEST: New membership for rayowang

### ISSUE THREAD

**Issue by rayowang** [kubernetes/org#4302]
### GitHub Username

rayowang

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

chaodaiG

### Sponsor 2

@camilamacedo86 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/k8s.io/pull/4853
https://github.com/kubernetes/kubernetes/pull/115996
https://github.com/kubernetes/test-infra/pull/28878
https://github.com/kubernetes/kubernetes/pull/118636
https://github.com/kubernetes/website/pull/41798

- Issues responded to
https://github.com/kubernetes/test-infra/issues/29856
https://github.com/kubernetes/kubernetes/issues/118675
https://github.com/kubernetes-sigs/kubebuilder/issues/3465

- SIG projects I am involved with
sig-kubespray
sig-kubebuiler

**Comment by chaodaiG** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
Hi @rayowang, could you please another sponsor (as per the [sponsor guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements)) to the issue, in order to move ahead with the request? Thank you so much!

**Comment by mrbobbytables** [comment]
Just to ack here @rayowang asked me to be another sponsor, but I cannot as both @chaodaiG and I work for the same employer.

**Comment by camilamacedo86** [comment]
I think it is ok and @rayowang has my LGTM as well

**Comment by Priyankasaggu11929** [comment]
/assign

@rayowang, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4352 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
