### ISSUE TITLE
REQUEST: New membership for joe-atzinger

### ISSUE THREAD

**Issue by joe-atzinger** [kubernetes/org#4308]
### GitHub Username

@joe-atzinger

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@vinli-cn

### List of contributions to the Kubernetes project

PRs
https://github.com/kubernetes-sigs/azurelustre-csi-driver/pull/91
https://github.com/kubernetes-sigs/azurelustre-csi-driver/pull/88 (fixed issues 87/89)

Issues
https://github.com/kubernetes-sigs/azurelustre-csi-driver/issues/87 (opened and fixed)
https://github.com/kubernetes-sigs/azurelustre-csi-driver/issues/89 (opened and fixed)
https://github.com/kubernetes-sigs/azurelustre-csi-driver/issues/90 (opened and fixed)
https://github.com/kubernetes-sigs/azurelustre-csi-driver/issues/96 (opened)

**Comment by vinli-cn** [comment]
+1

**Comment by xing-yang** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@joe-atzinger,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4315 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
