### ISSUE TITLE
REQUEST: New membership for mrgiles

### ISSUE THREAD

**Issue by mrgiles** [kubernetes/org#4312]
### GitHub Username

@mrgiles

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@reylejano

### Sponsor 2

@sftim

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/website/pull/40887
https://github.com/kubernetes/website/pull/40912
https://github.com/kubernetes/website/pull/40915
https://github.com/kubernetes/website/pull/41071
https://github.com/kubernetes/website/pull/41092
https://github.com/kubernetes/website/pull/41094
https://github.com/kubernetes/website/pull/41140
https://github.com/kubernetes/website/pull/41223
https://github.com/kubernetes/website/pull/41226
https://github.com/kubernetes/website/pull/41231
https://github.com/kubernetes/website/pull/41232
https://github.com/kubernetes/website/pull/41236
https://github.com/kubernetes/website/pull/41271
https://github.com/kubernetes/website/pull/41273
https://github.com/kubernetes/website/pull/41287
https://github.com/kubernetes/website/pull/41314
https://github.com/kubernetes/website/pull/41318
https://github.com/kubernetes/website/pull/41330

- Issues responded to
https://github.com/kubernetes/website/issues/22505
https://github.com/kubernetes/website/issues/24627
https://github.com/kubernetes/website/issues/29189
https://github.com/kubernetes/website/issues/30639
https://github.com/kubernetes/website/issues/31699
https://github.com/kubernetes/website/issues/32047
https://github.com/kubernetes/website/issues/32048
https://github.com/kubernetes/website/issues/33925
https://github.com/kubernetes/website/issues/36492
https://github.com/kubernetes/website/issues/37108
https://github.com/kubernetes/website/issues/37738
https://github.com/kubernetes/website/issues/39212
https://github.com/kubernetes/website/issues/39775
https://github.com/kubernetes/website/issues/40582
https://github.com/kubernetes/website/issues/40858

- SIG projects I am involved with
SIG Docs

**Comment by sftim** [comment]
Happy to sponsor. @mrgiles the optional course is not very exciting to take, but I recommend going through it anyway.

**Comment by mrgiles** [comment]
Thanks @sftim. Got it, I will take LFC102

**Comment by reylejano** [comment]
+1 from me, thank you for your contributions and we look forward to future contributions

**Comment by Priyankasaggu11929** [comment]
/assign

@mrgiles,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4322 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
