### ISSUE TITLE
REQUEST: Create endpointslice repo

### ISSUE THREAD

**Issue by mskrocki** [kubernetes/org#4313]
### New repo, staging repo, or migrate existing

staging

### Is it a staging repo?

yes

### Requested name for new repository

endpointslice

### Which Organization should it reside

kubernetes

### What SIG and subproject does this fall under?

sig-network

### Please provide references to appropriate approval for this new repo

- KEP: https://github.com/kubernetes/enhancements/pull/3686/commits/f0e118c01e95b335a2ed8101f0b6a935232d3b8f
- approvals: https://groups.google.com/g/kubernetes-sig-architecture/c/Myu9NPxjp9U

**Comment by mrbobbytables** [comment]
- repo has been created & stage-bots team added
- PR for branch protection: https://github.com/kubernetes/test-infra/pull/29985
- PR for publishing bot: https://github.com/kubernetes/publishing-bot/pull/362


One last thing - should this be added to the gateway-api subproject in sigs.yaml? It currently includes /pkg/controller/endpoint

If not, which other subproject or should I create a new one?

**Comment by mrbobbytables** [comment]
Oh yes - one last bit, please open a PR to https://github.com/kubernetes/kubernetes/blob/master/staging/publishing/rules.yaml to cover any dependencies.

Once all that is in place you should be able to go ahead and create the directory in staging following these instructions:

https://github.com/kubernetes/kubernetes/tree/master/staging#creating-a-new-repository-in-staging

**Comment by mskrocki** [comment]
I have already created https://github.com/kubernetes/kubernetes/pull/118953.

**Comment by mrbobbytables** [comment]
looks like everything is working 👍 
will go ahead and close this out.

/close
