### ISSUE TITLE
Issue with Netlify sites of kubernetes-sigs/cluster-api-provider-ibmcloud

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes/org#4318]
### Organization or Repo

kubernetes-sigs/cluster-api-provider-ibmcloud

### Describe the issue

Issue seen post merge of PR - https://github.com/kubernetes/k8s.io/pull/5397

Now I see that following URLs work -
```
https://release-0-1.cluster-api-ibmcloud.sigs.k8s.io/
https://release-0-3.cluster-api-ibmcloud.sigs.k8s.io/
https://release-0-4.cluster-api-ibmcloud.sigs.k8s.io/
https://release-0-5.cluster-api-ibmcloud.sigs.k8s.io/
```
But the certificates seems to be not secure and DNS entries don't give a clear picture either.
![Screenshot 2023-07-03 at 10 03 33 PM](https://github.com/kubernetes/org/assets/42934355/bf6f2df9-477a-4b6a-9425-eb145f5269ae)

Also the following URLs aren't working -
```
https://release-0-2.cluster-api-ibmcloud.sigs.k8s.io/
```
![Screenshot 2023-07-03 at 10 01 53 PM](https://github.com/kubernetes/org/assets/42934355/dae7a753-108f-4258-9644-6f174a190a1b)

The expected goal is something like this -
![Screenshot 2023-07-03 at 10 11 27 PM](https://github.com/kubernetes/org/assets/42934355/7ffced8a-8aae-4294-b870-8db6c4fc1be6)

Other Ref - https://github.com/kubernetes/org/issues/4118

**Comment by Prajyot-Parab** [comment]
- Open https://release-0-5.cluster-api-ibmcloud.sigs.k8s.io/ and verify that the certificates are valid If they are not, talk to someone with access to Netlify, they have to [click the ](https://app.netlify.com/sites/kubernetes-sigs-cluster-api-ibmcloud/settings/domain#https)renew certificate[ button](https://app.netlify.com/sites/kubernetes-sigs-cluster-api-ibmcloud/settings/domain#https) in the Netlify UI.

need someone to click that renew certificate button for cluster-api-provider-ibmcloud  repo in Netlify UI.

**Comment by palnabarun** [comment]
I will take a look later in the day.

/assign

**Comment by palnabarun** [comment]
FYI, this might not be an issue with the certificate.

The certificate for `cluster-api-ibmcloud.sigs.k8s.io` is valid till 1 Sep 2023. The same certificate is not valid for `*.cluster-api-ibmcloud.sigs.k8s.io` and hence the error that you are seeing.

**Comment by palnabarun** [comment]
I checked the settings for the project on Netlify. I even compared it with Cluster API, which has custom subdomains for their deploy preview branches.

I found this difference for the HTTPS section of the settings:
![image](https://github.com/kubernetes/org/assets/10010419/9da1a39f-05d9-42b5-af1b-e45a840b8b8c)

![image](https://github.com/kubernetes/org/assets/10010419/c8251a79-c37d-4874-9514-db527513dea0)

One thing I noted is that the cert for `*.cluster-api-ibmcloud.sigs.k8s.io` is issued by DigiCert with CN of `netlify.app` and `*.netlify.app` which seems to be inconsistent as the certificate should have been issues by Lets Encrypt. I think we should raise a ticket with Netlify for this inconsistency.

@mrbobbytables -- have we seen similar issues before?

**Comment by Prajyot-Parab** [comment]
any updates/resolution on this one?

**Comment by mrbobbytables** [comment]
I've seen something like this happen before, and forcing a renew of the certificate seems to do the trick. However, when I tried to do it for this project it doesn't seem to do it - or its taking forever to do it and just not updating.
I'd say give it 24hrs to see if it does go through with forcing a renew of the cert. 

From there, we can either log a ticket with netlify or probably the faster option would be to delete and recreate the site on the netlify side.

**Comment by Prajyot-Parab** [comment]
> I've seen something like this happen before, and forcing a renew of the certificate seems to do the trick. However, when I tried to do it for this project it doesn't seem to do it - or its taking forever to do it and just not updating. I'd say give it 24hrs to see if it does go through with forcing a renew of the cert.
> 
> From there, we can either log a ticket with netlify or probably the faster option would be to delete and recreate the site on the netlify side.

Update - the cert did not get renewed/updated

**Comment by mrbobbytables** [comment]
doesn't look like it -_- our best bet (well, fasted option) would be to delete the site and recreate

**Comment by Prajyot-Parab** [comment]
@mkumatag ^^^ your thoughts?

**Comment by palnabarun** [comment]
I've recreated the site, set the default build branch to `release-0.5` and configured HTTPS. Let's see if the subdomains get propagated to the certificate.

**Comment by Prajyot-Parab** [comment]
@mrbobbytables ^^^ ptal when you have bandwidth

**Comment by Prajyot-Parab** [comment]
@mrbobbytables @palnabarun can we please fix this, after recreation now all URLs point to `release-0.5` branch only.

**Comment by mrbobbytables** [comment]
The domains have been removed. Sorry about that, pings get lost in  :hankey: that is github notifications. Assigning so it's more visible to me.

/assign

I'll reach out to support. :+1:

**Comment by Prajyot-Parab** [comment]
> The domains have been removed. Sorry about that, pings get lost in 💩 that is github notifications. Assigning so it's more visible to me.
> 
> /assign
> 
> I'll reach out to support. 👍

Thanks @mrbobbytables, really appreciate your support on this one.

**Comment by mrbobbytables** [comment]
It should work as intended now, but this strategy of branch subdomains might not be sustainable. We are still working with netlify, but as it stands any time a new branch is created that you want to have an associated subdomain it would require a netlify admin to create a ticket and work with support to add that new branch.

This does not appear to be how it works for the main cluster-api site and I've asked netlify to look into it, but it may still come back that a ticket will have to be created for each new branch. 

A longer term solution might be to use a format like this:

cluster-api-ibmcloud.sigs.k8s.io/<version>/

e.g.

cluster-api-ibmcloud.sigs.k8s.io/v0.5/<rest of site>

**Comment by Prajyot-Parab** [comment]
@mrbobbytables thanks for the update, we will look at adopting the new format to ensure things go smoothly in longer run.

Also fyi things aren't working as expected

- working fine with proper certs
https://cluster-api-ibmcloud.sigs.k8s.io/
https://release-0-4.cluster-api-ibmcloud.sigs.k8s.io/

- Insecure cert warning
https://main.cluster-api-ibmcloud.sigs.k8s.io/
https://release-0-5.cluster-api-ibmcloud.sigs.k8s.io/
https://release-0-3.cluster-api-ibmcloud.sigs.k8s.io/

**Comment by mrbobbytables** [comment]
I'll bring it up with them - but yeah, I do definitely think the long term solution is to switch to the other format and not having to go through this every release >_<

**Comment by mrbobbytables** [comment]
Before I do, can you push empty commits to all the previous branches? (0.1 -> 0.4) some don't exist in netlify because they haven't had any commits pushed to them since we disconnected and reconnected the repo so the branch deployed sites don't exist.

**Comment by mrbobbytables** [comment]
@Prajyot-Parab we are looking into an alternative - delegating the dns to netlify - it'd auto create the dns records for the branch deploys and no cname records would need to be setup. Will keep you in the loop.

**Comment by cblecker** [comment]
So the fix, for the record:
- Configure subdomain for Netlify DNS: https://docs.netlify.com/domains-https/netlify-dns/delegate-a-subdomain-to-netlify-dns/#delegate-a-subdomain-to-netlify-dns-through-site-configuration
- Update DNS configuration to point to Netlify DNS servers: https://github.com/kubernetes/k8s.io/pull/5745
- Set up automatic branch deploys to custom domain: https://docs.netlify.com/domains-https/custom-domains/automatic-deploy-subdomains/#set-an-automatic-deploy-subdomain-for-branch-deploys
- Renew the Let's Encrypt certificate to get the wildcard cert provisioned: https://docs.netlify.com/domains-https/https-ssl/#netlify-managed-certificates

/assign
/close
