### ISSUE TITLE
Got removed after change github username

### ISSUE THREAD

**Issue by nayihz** [kubernetes/org#4319]
## Organization or Repo
kubernetes/kubernetes-sigs

## User affected
@nayihz
previous name: czybjtu

## Describe the issue
I previously joined the org via https://github.com/kubernetes/org/issues/4154.
I changed my github username today, and later I was removed from the org.
How can I be a member again? Do I have to open another pr and have two sponsors reply +1 again?

**Comment by mrbobbytables** [comment]
@nayihz please go ahead and open a PR updating your name (they are alpha sorted, so your name will change locations in the file).
