### ISSUE TITLE
REQUEST: New membership for spencerhance

### ISSUE THREAD

**Issue by spencerhance** [kubernetes/org#4324]
### GitHub Username

spencerhance

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@shaneutt

### Sponsor 2

@robscott

### List of contributions to the Kubernetes project

Here are my contributions, I am actively involved with [kubernetes-sigs/gateway-api](https://github.com/kubernetes-sigs/gateway-api) and [kubernetes/ingress-gce](https://github.com/kubernetes/ingress-gce).

* [kubernetes-sigs/gateway-api](https://github.com/kubernetes-sigs/gateway-api)
  * [9 Merged PRs](https://github.com/kubernetes-sigs/gateway-api/pulls?q=is%3Apr+is%3Amerged+author%3Aspencerhance)
* [kubernetes/ingress-gce](https://github.com/kubernetes/ingress-gce)
  * [141 Merged PRs](https://github.com/kubernetes/ingress-gce/pulls?q=is%3Apr+is%3Amerged+author%3Aspencerhance)
  * [38 reviewed PRs](https://github.com/kubernetes/ingress-gce/pulls?q=is%3Apr++reviewed-by%3Aspencerhance+-author%3Aspencerhance)
* [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes)
  * [6 merged PRs](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Amerged+author%3Aspencerhance)
  * [1 Reviewed PR](https://github.com/kubernetes/kubernetes/pulls?q=reviewed-by%3Aspencerhance+type%3Apr+is%3Amerged+-author%3Aspencerhance)
* [kubernetes/k8s.io](https://github.com/kubernetes/k8s.io)
  * [1 Merged PR](https://github.com/kubernetes/k8s.io/pulls?q=is%3Apr+is%3Amerged+author%3Aspencerhance)
* [kubernetes/cloud-provider-gcp](https://github.com/kubernetes/cloud-provider-gcp)
  * [1 Merged PR](https://github.com/kubernetes/cloud-provider-gcp/pulls?q=is%3Apr+is%3Amerged+author%3Aspencerhance)

**Comment by robscott** [comment]
Thanks for all your contributions @spencerhance!

+1

**Comment by Priyankasaggu11929** [comment]
/assign

@spencerhance,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/433 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
