### ISSUE TITLE
REQUEST: New membership for npinaeva

### ISSUE THREAD

**Issue by npinaeva** [kubernetes/org#4325]
### GitHub Username

@npinaeva

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@astoycos

### Sponsor 2

@Dyanngg 

### List of contributions to the Kubernetes project

PRs
- https://github.com/kubernetes-sigs/network-policy-api/pull/119
- https://github.com/kubernetes-sigs/network-policy-api/pull/75
- https://github.com/kubernetes/website/pull/39875
- https://github.com/kubernetes-sigs/network-policy-api/pull/117

Issues
- https://github.com/kubernetes-sigs/network-policy-api/issues/72
- https://github.com/kubernetes-sigs/network-policy-api/issues/73
- https://github.com/kubernetes-sigs/network-policy-api/issues/122

SIG projects I am involved with:
- sig-network-policy-api

**Comment by astoycos** [comment]
/lgtm

@npinaeva Thanks for your efforts!

**Comment by Dyanngg** [comment]
/lgtm

Many thanks to your contributions to the sig-networkpolicy space!

**Comment by Priyankasaggu11929** [comment]
/assign

@npinaeva,  thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/433 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
