### ISSUE TITLE
REQUEST: New membership for ahrtr

### ISSUE THREAD

**Issue by ahrtr** [kubernetes/org#4326]
### GitHub Username

ahrtr

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@BenTheElder

### Sponsor 2

@serathius

### List of contributions to the Kubernetes project

sig-etcd to be created

**Comment by logicalhan** [comment]
/lgtm

Welcome to the community!!

**Comment by BenTheElder** [comment]
The sponsorship / membership [requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#member) include sponsoring existing members from multiple employers, so while I'm +1 you'll need someone other than myself / @serathius / @logicalhan 😅

**Comment by ahrtr** [comment]
Thanks @logicalhan @serathius @BenTheElder 

cc @nikhita @palnabarun

**Comment by serathius** [comment]
cc @jberkus

**Comment by nikhita** [comment]
+1 from me as well

**Comment by palnabarun** [comment]
+1 from me

Welcome to the Kubernetes orgs @ahrtr!

**Comment by jberkus** [comment]
+1 (as Etcd docs maintainer)

**Comment by Priyankasaggu11929** [comment]
/assign

@ahrtr, thank you for all your contributions :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4331 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification. 

Welcome to @kubernetes! :tada:
