### ISSUE TITLE
REQUEST: New membership for hughdanliu

### ISSUE THREAD

**Issue by hughdanliu** [kubernetes/org#4327]
### GitHub Username

@hughdanliu

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jacobwolfaws

### Sponsor 2

@msau42

### List of contributions to the Kubernetes project

PRs authored:
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/1
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/3
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/6
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/30
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/35
\+ many others

PRs reviewed:
https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/339
https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/309
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/4
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/5
\+ many others

Issues responded to: 
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/issues/28
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/issues/47

SIGs projects I am involved in:
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver

**Comment by msau42** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@hughdanliu, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4331 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
