### ISSUE TITLE
REQUEST: New membership for gomesjason

### ISSUE THREAD

**Issue by gomesjason** [kubernetes/org#4328]
### GitHub Username

@gomesjason

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jacobwolfaws

### Sponsor 2

@msau42

### List of contributions to the Kubernetes project

SIG Project Involved With:
https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver

PRs Authored:
- https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/15
- https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/37
- https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/31
- https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/32
- https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/33

PRs Reviewed:
- https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/8
- https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/9
- https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/12
- https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/pull/6

**Comment by jacobwolfaws** [comment]
+1, thanks @gomesjason for all your work!

**Comment by msau42** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@gomesjason, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4331 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
