### ISSUE TITLE
REQUEST: New membership for r-erema

### ISSUE THREAD

**Issue by r-erema** [kubernetes/org#4329]
### GitHub Username

@r-erema

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@enj

### Sponsor 2

@M00nF1sh

### List of contributions to the Kubernetes project

- PRs reviewed
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2735
https://github.com/kubernetes/kubernetes/pull/115122
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/110464
- SIG projects I am involved with
https://github.com/kubernetes/community/blob/master/sig-auth
https://github.com/kubernetes/community/tree/master/sig-cloud-provider

**Comment by enj** [comment]
+1 thanks for all of your contributions so far!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4340  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
