### ISSUE TITLE
REQUEST: New membership for szuecs

### ISSUE THREAD

**Issue by szuecs** [kubernetes/org#433]
### GitHub Username

szuecs

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
   - https://github.com/search?q=org%3Akubernetes+szuecs&type=Commits
   - https://github.com/search?q=org%3Akubernetes+szuecs&type=Issues
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines 
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims
- @derekwaynecarr 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pull/63437
- https://github.com/search?q=org%3Akubernetes+szuecs&type=Commits
- https://github.com/search?q=org%3Akubernetes+szuecs&type=Issues
- SIG projects I am involved with, in slack sig-network, sig-aws, external-dns (subproject of sig-network), PR was XL and most parts sig-node I guess

**Comment by dims** [comment]
+1 welcome!

**Comment by derekwaynecarr** [comment]
+1 welcome!

**Comment by rlenferink** [comment]
Hey @szuecs , thank you for all your contributions so far :)

I've created PR #437 to add you to the @kubernetes org. Once that gets merged, you will receive a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
