### ISSUE TITLE
 REQUEST: New membership for HirazawaUi

### ISSUE THREAD

**Issue by HirazawaUi** [kubernetes/org#4333]
### GitHub Username

@HirazawaUi

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [x] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@thockin

### Sponsor 2

@pacoxu

### List of contributions to the Kubernetes project

PRs reviewed / authored
https://github.com/pulls?page=1&q=is%3Amerged+is%3Apr+author%3AHirazawaUi+archived%3Afalse+kubernetes

Issues assigned
https://github.com/issues?q=is%3Aissue+archived%3Afalse+assignee%3AHirazawaUi

**Comment by pacoxu** [comment]
+1 
Thanks for your contributions.

**Comment by thockin** [comment]
+1 thanks!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4340  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
