### ISSUE TITLE
REQUEST: New membership for ahmedtd

### ISSUE THREAD

**Issue by ahmedtd** [kubernetes/org#4336]
### GitHub Username

@ahmedtd

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mikedanese

### Sponsor 2

@deads2k

### List of contributions to the Kubernetes project

* ClusterTrustBundle / Workload Certificate work under SIG-Auth
  * [KEP-3257](https://github.com/kubernetes/enhancements/issues/3257)
  * [Add certificates.k8s.io/v1alpha1 ClusterTrustBundle](https://github.com/kubernetes/kubernetes/pull/113218)
  * [Implement ClusterTrustBundle projected volume](https://github.com/kubernetes/kubernetes/pull/113374)
 * cloud-provider-gcp
   * Will become OWNER on gcp-controller-manager: [PR](https://github.com/kubernetes/cloud-provider-gcp/pull/514)
   * gcp-controller-manager reviews and fixes: [link](https://github.com/kubernetes/cloud-provider-gcp/pulls?q=is%3Apr+ahmedtd)
* Random Fixes
  * [serviceaccounts: Add JWT KeyIDs to tokens](https://github.com/kubernetes/kubernetes/pull/78502)
  * [Remove MPL-licensed dep from lruexpirecache](https://github.com/kubernetes/kubernetes/pull/95472)

**Comment by mikedanese** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@ahmedtd, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4352 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
