### ISSUE TITLE
REQUEST: New membership for zhanggbj

### ISSUE THREAD

**Issue by zhanggbj** [kubernetes/org#4337]
### GitHub Username

@zhanggbj

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@srm09

### Sponsor 2

@MaxRink

### List of contributions to the Kubernetes project

- PRs reviewed / authored
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2014
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1951
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1937
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1904
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1921
- Issues responded to
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1718
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1914
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1853
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1226
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1746
- SIG projects I am involved with
    - kubernetes-sigs/cluster-api-provider-vsphere

**Comment by MaxRink** [comment]
+1

**Comment by mrbobbytables** [comment]
@zhanggbj unfortunately @MaxRink cannot be a sponsor. Sponsors must be a reviewer or approver in an OWNERS file. Is there someone else that could sponsor you?

**Comment by zhanggbj** [comment]
Hi @mrbobbytables, thanks for the quick reply, @MaxRink is a reviewer of kubernetes-sigs/cluster-api-provider-vsphere, refer to [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/OWNERS_ALIASES#L21C7-L21C14), or I should tag the sponsor name in lowercase?

**Comment by zhanggbj** [comment]
@fabriziopandini Thank you so much for the kind words and support:) looking forward to contributing further.

**Comment by mrbobbytables** [comment]
Your right, and no - it was my bad. Sorry about that. I forgot to click ignore case when looking at owners via cs.k8s.io. 

I can add tomorrow morning 👍

**Comment by zhanggbj** [comment]
@mrbobbytables No problem at all, and there's no hush, just take your time :)

**Comment by mrbobbytables** [comment]
Created #4341 to take care of adding you, again - sorry about that^^;;;

**Comment by zhanggbj** [comment]
@mrbobbytables no worries, thank you for your help!!!
