### ISSUE TITLE
REQUEST: New membership for cartermckinnon

### ISSUE THREAD

**Issue by cartermckinnon** [kubernetes/org#4338]
### GitHub Username

cartermckinnon

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

dims

### Sponsor 2

dgrisonnet

### List of contributions to the Kubernetes project

Authored, merged:
- https://github.com/kubernetes/kubernetes/pull/109676
- https://github.com/kubernetes/kubernetes/pull/117448
- https://github.com/kubernetes/website/pull/40841
- https://github.com/kubernetes/cloud-provider-aws/pull/607
- https://github.com/kubernetes/kubernetes/pull/119241

Authored, open:
- https://github.com/kubernetes/kubernetes/pull/118421
- https://github.com/kubernetes/kubernetes/pull/116192

Reviewed:
- https://github.com/kubernetes/cloud-provider-aws/pull/597
- https://github.com/kubernetes/cloud-provider-aws/pull/598
- https://github.com/kubernetes/kubernetes/pull/119158
- https://github.com/kubernetes/kubernetes/pull/109217
- https://github.com/kubernetes/kubernetes/pull/96120

Triaged:
- https://github.com/kubernetes/cloud-provider-aws/issues/625
- https://github.com/kubernetes/cloud-provider-aws/issues/606

Lead maintainer of related project: https://github.com/awslabs/amazon-eks-ami

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4340  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
