### ISSUE TITLE
REQUEST: New membership for a-hilaly

### ISSUE THREAD

**Issue by a-hilaly** [kubernetes/org#4339]
### GitHub Username

a-hilaly

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@jpbetz

### List of contributions to the Kubernetes project

PRs authored:
- https://github.com/kubernetes/kubernetes/pull/118051
- https://github.com/kubernetes/kubernetes/pull/118319
- https://github.com/kubernetes/kubernetes/pull/119342
- https://github.com/kubernetes/kubernetes/pull/119404
- https://github.com/kubernetes/kubernetes/pull/119380
- https://github.com/kubernetes/test-infra/pull/30096
- https://github.com/kubernetes/website/pull/41292
- https://github.com/kubernetes/autoscaler/pull/5803
- https://github.com/kubernetes/kube-state-metrics/pull/2073

**Comment by jpbetz** [comment]
/lgtm
Thanks for all your contributions @a-hilaly!

**Comment by dims** [comment]
+1 from me!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4340  to add you to the Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
