### ISSUE TITLE
REQUEST: New membership for KlwntSingh

### ISSUE THREAD

**Issue by KlwntSingh** [kubernetes/org#4349]
### GitHub Username

KlwntSingh

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

jayunit100

### Sponsor 2

knabben

### List of contributions to the Kubernetes project

# PR's
kubernetes/kops#15408
kubernetes-sigs/kubespray#10066
kubernetes-csi/csi-driver-smb#614
kubernetes-sigs/windows-operational-readiness#79
kubernetes-sigs/windows-operational-readiness#80

# Projects
https://github.com/kubernetes-sigs/windows-operational-readiness

**Comment by knabben** [comment]
+1

**Comment by jayunit100** [comment]
/lgtm
/approve

Kulwant has done alot of foundational work for windows op readiness, w a few PRs having merged after many wks of other work... and e2e testing and helped us w api issues related to host process and so on.

**Comment by Priyankasaggu11929** [comment]
/assign

@KlwntSingh, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4352 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
