### ISSUE TITLE
REQUEST: New membership for AlbeeSo

### ISSUE THREAD

**Issue by AlbeeSo** [kubernetes/org#4350]
### GitHub Username

AlbeeSo

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@fredkan

### Sponsor 2

@mowangdk

### List of contributions to the Kubernetes project

- PRs 

  - kubernetes-sigs/alibaba-cloud-csi-driver/pull/686
  - kubernetes-sigs/alibaba-cloud-csi-driver/pull/761
  - kubernetes-sigs/alibaba-cloud-csi-driver/pull/802
  - kubernetes-sigs/alibaba-cloud-csi-driver/pull/789
  - kubernetes-sigs/alibaba-cloud-csi-driver/pull/793
  - kubernetes-sigs/alibaba-cloud-csi-driver/pull/794
  - kubernetes-sigs/alibaba-cloud-csi-driver/pull/796

- SIG projects I am involved with
  - alibaba-cloud-csi-driver under kubernetes-sigs

**Comment by mrbobbytables** [comment]
@AlbeeSo do you have another person who could sponsor you? Sponsors must be from different organizations and both @fredkan and @mowangdk are from Alibaba ^^;;

**Comment by mowangdk** [comment]
LGTM

**Comment by xing-yang** [comment]
+1

**Comment by mowangdk** [comment]
@mrbobbytables hello, I think all requirements have been satisfied, ptal~ thx

**Comment by Priyankasaggu11929** [comment]
/assign

@AlbeeSo, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4381 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
