### ISSUE TITLE
REQUEST: New membership for tydra-wang

### ISSUE THREAD

**Issue by tydra-wang** [kubernetes/org#4351]
### GitHub Username

@tydra-wang

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mowangdk

### Sponsor 2

@fredkan

### List of contributions to the Kubernetes project

- PRs
  - https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/806
  - https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/799
  - https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/797
  - https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/786
  - https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/785
  - https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/784
  - https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/781
  - https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/770
  - https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/766
  - https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/764

- SIG projects I am involved with
alibaba-cloud-csi-driver under kubernetes-sigs

**Comment by mrbobbytables** [comment]
@tydra-wang  do you have another person who could sponsor you? Sponsors must be from different organizations and both @fredkan and @mowangdk are from Alibaba ^^;;

**Comment by mowangdk** [comment]
LGTM

**Comment by xing-yang** [comment]
+1

**Comment by mowangdk** [comment]
@mrbobbytables hello, I think all requirements have been satisfied, ptal~ thx

**Comment by Priyankasaggu11929** [comment]
/assign

@tydra-wang, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4381 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
