### ISSUE TITLE
REQUEST: New membership for Sunnatillo

### ISSUE THREAD

**Issue by Sunnatillo** [kubernetes/org#4354]
### GitHub Username

@Sunnatillo

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
-  [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@furkatgofurov7

### List of contributions to the Kubernetes project

SIG projects @Sunnatillo(myself) involved with: CAPI v1.9 Release Team Lead
https://github.com/kubernetes-sigs/cluster-api/pull/10963
https://github.com/kubernetes-sigs/cluster-api/pull/10358
https://github.com/kubernetes-sigs/cluster-api/pull/10334
https://github.com/kubernetes-sigs/cluster-api/pull/10964
https://github.com/kubernetes-sigs/cluster-api/pull/10365
https://github.com/kubernetes-sigs/cluster-api/pull/10359
https://github.com/kubernetes-sigs/cluster-api/pull/10357

**Comment by sbueringer** [comment]
+1 from my side!

**Comment by Sunnatillo** [comment]
PTAL @furkatgofurov7

**Comment by jasonbraganza** [comment]
/assign

@Sunnatillo, thank you for all your contributions. Looking forward to more! 🙂

I’ve created PR #5112 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
