### ISSUE TITLE
REQUEST: New membership for ipochi

### ISSUE THREAD

**Issue by ipochi** [kubernetes/org#4368]
### GitHub Username

ipochi

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

 cheftako

### Sponsor 2

rata

### List of contributions to the Kubernetes project

SIG projects I'm involved with: [kubernetes-sigs/apiserver-network-proxy](https://github.com/kubernetes-sigs/apiserver-network-proxy)

Issues:
 kubernetes-sigs/apiserver-network-proxy/issues/495,kubernetes-sigs/apiserver-network-proxy/issues/474,kubernetes-sigs/apiserver-network-proxy/issues/478,kubernetes-sigs/apiserver-network-proxy/issues/458,kubernetes-sigs/apiserver-network-proxy/issues/455,kubernetes-sigs/apiserver-network-proxy/issues/412,kubernetes-sigs/apiserver-network-proxy/issues/372,kubernetes-sigs/apiserver-network-proxy/issues/311

PRs: 
kubernetes-sigs/apiserver-network-proxy/pull/507,kubernetes-sigs/apiserver-network-proxy/pull/485,kubernetes-sigs/apiserver-network-proxy/pull/506,kubernetes-sigs/apiserver-network-proxy/pull/479,kubernetes-sigs/apiserver-network-proxy/pull/475,kubernetes-sigs/apiserver-network-proxy/pull/381,

**Comment by jkh52** [comment]
Looking at the bulleted list, I see `"I have verified that my sponsors are from different member companies"`. But @cheftako and I both currently work at Google; maybe someone from your company could be the additional sponsor?

**Comment by rata** [comment]
I can happily sponsor @ipochi , I work at Microsoft :)

**Comment by ipochi** [comment]
Whats the next step, who approves this PR ?

**Comment by elmiko** [comment]
+1 from me as well. @ipochi has been doing excellent work on the apiserver network proxy project, happy to sponsor if needed (i am from red hat),

**Comment by Priyankasaggu11929** [comment]
/assign

@ipochi, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4381 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

**Comment by ipochi** [comment]
@Priyankasaggu11929 

It seems ilm obly made part of the kubernetes-sigs org and not the kubernetes org

**Comment by Priyankasaggu11929** [comment]
Hi @ipochi, you're already a member of the Kubernetes org :slightly_smiling_face: 

https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L632

**Comment by ipochi** [comment]
> Hi @ipochi, you're already a member of the Kubernetes org :slightly_smiling_face: 
> 
> https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml#L632

Ah so that's why I was wondering why I am going through this membership process again. This time its only for kubernetes-sigs.

Thanks for that 😌
