### ISSUE TITLE
REQUEST: New membership for mmamczur

### ISSUE THREAD

**Issue by mmamczur** [kubernetes/org#4372]
### GitHub Username

@mmamczur

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

 @aojea

### Sponsor 2

 @shaneutt

### List of contributions to the Kubernetes project

Main work is related to L4 loadbalancers for GKE but also some contributions in gateway-api

gateway-api
https://github.com/kubernetes-sigs/gateway-api/pull/1827
https://github.com/kubernetes-sigs/gateway-api/pull/1673
https://github.com/kubernetes-sigs/gateway-api/pull/1682

ingress-gce
https://github.com/kubernetes/ingress-gce/pull/2013
https://github.com/kubernetes/ingress-gce/pull/2071
https://github.com/kubernetes/ingress-gce/pull/2078
https://github.com/kubernetes/ingress-gce/pull/2155
https://github.com/kubernetes/ingress-gce/pull/2063

https://github.com/kubernetes/cloud-provider-gcp/pull/586

**Comment by aojea** [comment]
+1

**Comment by shaneutt** [comment]
+1

Thank you for your contributions!

**Comment by Priyankasaggu11929** [comment]
/assign

@mmamczur, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4381 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
