### ISSUE TITLE
REQUEST: New membership for stephenfin

### ISSUE THREAD

**Issue by stephenfin** [kubernetes/org#4373]
### GitHub Username

stephenfin

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mdbooth

### Sponsor 2

@jichenjc

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/kubernetes/pull/119129
- https://github.com/kubernetes/cloud-provider-openstack/pull/2006
- https://github.com/kubernetes/cloud-provider-openstack/pull/2007
- https://github.com/kubernetes/cloud-provider-openstack/pull/1815
- https://github.com/kubernetes/kubernetes/pull/107750

**Comment by jichenjc** [comment]
/lgtm

thanks for @stephenfin great help~

**Comment by Priyankasaggu11929** [comment]
/assign

@stephenfin, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4381 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
