### ISSUE TITLE
REQUEST: New membership for shu-mutou

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/org#438]
### GitHub Username
@shu-mutou

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jeefy 
- @danielromlein 

### List of contributions to the Kubernetes project
- PRs reviewed / authored and Issues responded to
https://github.com/search?q=author%3Ashu-mutou+is%3Amerged+repo%3Akubernetes%2Fdashboard
- SIG projects I am involved with
kubernetes/dashboard
kubernetes-sigs/dashboard-metrics-scraper

**Comment by shu-mutou** [comment]
I submitted by mistake before filling all.

**Comment by jeefy** [comment]
Big +1

@shu-mutou has been contributing in SIG-UI and has been active in the community.

**Comment by danielromlein** [comment]
LGTM 👍
Excited to have you contributing more @shu-mutou!

**Comment by mrbobbytables** [comment]
@shu-mutou , thank you for all your contributions to the dashboard project :)

I've created PR #473  to add you to both the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notifications for both of them.

Welcome to @kubernetes! 🎉

/assign
