### ISSUE TITLE
REQUEST: New membership for tzifudzi

### ISSUE THREAD

**Issue by tzifudzi** [kubernetes/org#4383]
### GitHub Username

tzifudzi

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

jayunit100

### Sponsor 2

jsturtevant

### List of contributions to the Kubernetes project

PRs reviewed/authored
- https://github.com/kubernetes-sigs/windows-operational-readiness/pull/77
- https://github.com/kubernetes-sigs/windows-operational-readiness/pull/83
- https://github.com/kubernetes-sigs/windows-operational-readiness/pull/76
- https://github.com/kubernetes/website/pull/42518
- https://github.com/kubernetes-sigs/windows-operational-readiness/pull/87
- https://github.com/kubernetes-sigs/windows-operational-readiness/pull/88

SIG projects I am involved with
- https://github.com/kubernetes-sigs/windows-operational-readiness

Issues created/involved with
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/65
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/66
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/67
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/68
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/69
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/70
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/71
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/72
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/73
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/74
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/84
- https://github.com/kubernetes-sigs/windows-operational-readiness/issues/78

**Comment by jayunit100** [comment]
tatendas been driving all the op-readiness improvements and leading this effort for quite a while. thank you so much Tatenda +1

**Comment by jsturtevant** [comment]
+1 @tzifudzi has been a regular at our sig-windows meetings.  Beyond the work above has also helped with adjacent projects such as  [windows_exporter](https://github.com/prometheus-community/windows_exporter/pull/1218).  Thanks for stepping up and helping out 💯

**Comment by Priyankasaggu11929** [comment]
/assign

@tzifudzi , thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4395 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
