### ISSUE TITLE
REQUEST: New membership for drew-viles

### ISSUE THREAD

**Issue by drew-viles** [kubernetes/org#4386]
### GitHub Username

@drew-viles

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mboersma

### Sponsor 2

@AverageMarcus 

### List of contributions to the Kubernetes project

I'm currently involved with the Image-Builder project and have created the following PR's:

https://github.com/kubernetes-sigs/image-builder/pull/1013
https://github.com/kubernetes-sigs/image-builder/pull/1147
https://github.com/kubernetes-sigs/image-builder/pull/1186
https://github.com/kubernetes-sigs/image-builder/pull/1223

I've commented on and assisted with the following too: https://github.com/kubernetes-sigs/image-builder/pull/1122

I regularly attend the office hours and assist with queries on the slack channel too.

**Comment by AverageMarcus** [comment]
👍  Drew has been a great help with image-builder!

**Comment by mboersma** [comment]
+1 @drew-viles has been a stalwart community member in image-builder with both contributions, reviews, and thoughtful discussion in office hours.

**Comment by Priyankasaggu11929** [comment]
/assign

@drew-viles , thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4395 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
