### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/scheduler-plugins

### ISSUE THREAD

**Issue by zwpaper** [kubernetes/org#4387]
### Repository

kubernetes-sigs/scheduler-plugins

### Project domain

scheduler-plugins.sigs.k8s.io

### Additional context for request

We hope to enable Netlify site for documentation in https://github.com/kubernetes-sigs/scheduler-plugins

we already set the base URL to scheduler-plugins.sigs.k8s.io, and will request for subproject domain after the Netlify is set up and got the Netlify URL.

expected netlify address: kubernetes-sigs-scheduler-plugins.netlify.app.

ref:

- https://github.com/kubernetes-sigs/scheduler-plugins/pull/616

cc @Huang-Wei

**Comment by Huang-Wei** [comment]
/lgtm

Thanks @zwpaper !

**Comment by zwpaper** [comment]
hi @mrbobbytables can you help with this?

/assign @mrbobbytables

**Comment by zwpaper** [comment]
I thought we might do it after this issue has some progress previously, I have created the issue to request a DNS name https://github.com/kubernetes/k8s.io/issues/5774, and a PR to k8s.io https://github.com/kubernetes/k8s.io/pull/5775 for the DNS name

@Huang-Wei

**Comment by cblecker** [comment]
Your site build is failing because your netlify.toml is in the root of your repo, but you're trying to set the base to the site directory. Either you need to move the build command to your root, or the netlify config into site/

**Comment by zwpaper** [comment]
sorry for the mistake, I have created a PR to fix it and tested it personally.

I also see the build result in PR, it seems that the sigs netlify is also working seamlessly.

thanks so much, @cblecker, I will make sure the site works after the PR is merged and close this issue, Thanks again!

**Comment by Huang-Wei** [comment]
@zwpaper the PR in scheduler-plugins has been merged.

**Comment by cblecker** [comment]
Looks like the site is building now: https://scheduler-plugins.sigs.k8s.io/

If all looks good @zwpaper, please feel free to /close :)

**Comment by Huang-Wei** [comment]
Neat! Thanks a lot @cblecker !!

**Comment by zwpaper** [comment]
the site now works like a charm, thanks so much! @cblecker 

/close
