### ISSUE TITLE
REQUEST: New membership for fykaa

### ISSUE THREAD

**Issue by fykaa** [kubernetes/org#4389]
### GitHub Username

fykaa

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kaslin

### Sponsor 2

@chris-short 

### Sponsor 3

@fsmunoz 

### List of contributions to the Kubernetes project

:pushpin: Authoring or reviewing PRs on GitHub:

PRs on kubernetes/community:
- https://github.com/kubernetes/community/pull/7164 **2 March**
- https://github.com/kubernetes/community/pull/7262 **21 April**
- https://github.com/kubernetes/community/pull/7285 **5 May**
- https://github.com/kubernetes/community/pull/7294 **15 May**
- https://github.com/kubernetes/community/pull/7295 **19 May**
- https://github.com/kubernetes/community/pull/7458 **12 August**

PRs on kubernetes/website:
- https://github.com/kubernetes/website/pull/42522 **13 August**
- https://github.com/kubernetes/website/pull/42390 **4 August**

PRs on kubernetes/contributor-site:
- https://github.com/kubernetes/contributor-site/pull/418 **13 August**

:pushpin: Contributions to SIG, subproject, or community discussions:
- Regular member of [Contributor Comms ](https://docs.google.com/document/d/1K3vjCZ9C3LwYrOJOhztQtFuDQCe-urv-ewx1bI8IPVQ/edit?usp=sharing)Subproject meetings, slack discussions. - Since **March 1**
- CNCF KubeCon EU [Tweet Drafts](https://docs.google.com/spreadsheets/d/1Hi2K9YGCKceeqnJtO_H_LAUU536_PDRCnHvSuioHAyc/edit?usp=sharing) - **April 14**
- [KCSNA](https://github.com/kubernetes/community/issues/7354) - Content Shadow - **July 11**

**Comment by chris-short** [comment]
I fully endorse @fykaa org membership!

+1

**Comment by fsmunoz** [comment]
It's a pleasure to sponsor @fykaa 's membership.

+1

**Comment by kaslin** [comment]
Likewise, I am excited to support @fykaa 's org membership!

+1
