### ISSUE TITLE
REQUEST: New membership for @adriananeci

### ISSUE THREAD

**Issue by adriananeci** [kubernetes/org#4393]
### GitHub Username

@adriananeci

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-csi, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jrsapi

### Sponsor 2

@nojnhuh

### List of contributions to the Kubernetes project

- Authored PRs in kubernetes-sigs: https://github.com/pulls?q=is%3Apr+author%3Aadriananeci+archived%3Afalse+org%3Akubernetes-sigs+

- Issues & PRs (non-authored) participating in kubernetes-sigs: https://github.com/issues?q=commenter%3Aadriananeci+archived%3Afalse+org%3Akubernetes-sigs+-author%3Aadriananeci+

- Authored PRs in kubernetes https://github.com/pulls?q=is%3Apr+is%3Amerged+author%3Aadriananeci+archived%3Afalse+org%3Akubernetes+

I'm currently mainly involved in Cluster API ecosystem repos, but looking to extend my focus area.

**Comment by nojnhuh** [comment]
Big +1 from me.

Thank you @adriananeci for your contributions to CAPZ!

**Comment by jrsapi** [comment]
Big +1 to Adrian.

**Comment by Priyankasaggu11929** [comment]
/assign

@adriananeci, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4395 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
