### ISSUE TITLE
REQUEST: New membership for @Sneha-at

### ISSUE THREAD

**Issue by Sneha-at** [kubernetes/org#4394]
### GitHub Username

@Sneha-at

### Organization you are requesting membership in

kubernetes-csi, kubernetes-sigs, kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sunnylovestiramisu

### Sponsor 2

@xing-yang

### List of contributions to the Kubernetes project

**Kubernetes-sigs**
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1330
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1291 
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1287 
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1227 

**Kubernetes-csi**
Sidecar release -rc 
https://github.com/kubernetes-csi/livenessprobe/pull/201
https://github.com/kubernetes-csi/csi-lib-utils/pull/141
https://github.com/kubernetes-csi/node-driver-registrar/pull/318
https://github.com/kubernetes-csi/external-attacher/pull/470
Sidecar release
https://github.com/kubernetes-csi/external-attacher/pull/475
https://github.com/kubernetes-csi/external-health-monitor/pull/207
https://github.com/kubernetes-csi/csi-lib-utils/pull/144
https://github.com/kubernetes-csi/volume-data-source-validator/pull/118
https://github.com/kubernetes-csi/lib-volume-populator/issues/130
https://github.com/kubernetes-csi/node-driver-registrar/issues/323
 https://github.com/kubernetes-csi/livenessprobe/issues/203

**Comment by sunnylovestiramisu** [comment]
+1 

@Sneha-at has been helping with sig-storage releases and ops improvements and will work on features in the future.

**Comment by xing-yang** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@Sneha-at, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4395 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
