### ISSUE TITLE
REQUEST: New membership for pramitagautam

### ISSUE THREAD

**Issue by pramitagautam** [kubernetes/org#4397]
### GitHub Username

pramitagautam

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

jayunit100

### Sponsor 2

jsturtevant

### List of contributions to the Kubernetes project

PRs I have worked on:-
1) https://github.com/kubernetes-sigs/sig-windows-dev-tools/pull/235
2) https://github.com/kubernetes-sigs/sig-windows-dev-tools/pull/236
2) https://github.com/kubernetes/kubernetes/pull/119623

Issues I have created/involved with
1) https://github.com/kubernetes-sigs/sig-windows-dev-tools/issues/220
2) https://github.com/kubernetes-sigs/sig-windows-dev-tools/issues/225
3) https://github.com/kubernetes-sigs/windows-operational-readiness/issues/51
4) https://github.com/kubernetes-sigs/windows-operational-readiness/issues/52
5) https://github.com/kubernetes-sigs/windows-operational-readiness/issues/61
6) https://github.com/kubernetes/kubernetes/issues/119021
7) https://github.com/kubernetes/kubernetes/issues/119022
8) https://github.com/kubernetes/kubernetes/issues/119538
9) https://github.com/kubernetes/kubernetes/issues/119774
10) https://github.com/kubernetes/kubernetes/issues/120071

SIG projects I am involved with:-
1) https://github.com/kubernetes-sigs/sig-windows-dev-tools
2) https://github.com/kubernetes-sigs/windows-operational-readiness
2) https://github.com/kubernetes-sigs/e2e-framework

**Comment by jayunit100** [comment]
/lgtm
/approve 

Pramitas above issues and persistence over a year or so has breathed life into an otherwise dwindling pool of people who cam navigate the windows e2e suite

**Comment by jsturtevant** [comment]
+1 thanks for all the effort on the operational readiness

**Comment by knabben** [comment]
+1
