### ISSUE TITLE
REQUEST: New membership for @pegasas

### ISSUE THREAD

**Issue by pegasas** [kubernetes/org#4405]
### GitHub Username

@pegasas

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tengqm

### Sponsor 2

@windsonsea

### List of contributions to the Kubernetes project

Kubernetes is the basis of cloud-native technology which attracts lots of developers involving in.
I would like to continue to make efforts for this community.

PRs I have worked on:
 
1. https://github.com/kubernetes/website/pull/42161
2. https://github.com/kubernetes/website/pull/42253
3. https://github.com/kubernetes/website/pull/42265
4. https://github.com/kubernetes/website/pull/42350
5. https://github.com/kubernetes/website/pull/42376
6. https://github.com/kubernetes/website/pull/42557
7. https://github.com/kubernetes/website/pull/42631
8. https://github.com/kubernetes/website/pull/42660
9. https://github.com/kubernetes/website/pull/42685
10. https://github.com/kubernetes-sigs/gateway-api/pull/2343

Issues I have created/involved with:

1. https://github.com/kubernetes/website/issues/40220
2. https://github.com/kubernetes/website/issues/42228
3. https://github.com/kubernetes/website/issues/42247
4. https://github.com/kubernetes/website/issues/42034
5. https://github.com/kubernetes/website/issues/42371
6. https://github.com/kubernetes/website/issues/42553
7. https://github.com/kubernetes/website/issues/42603
8. https://github.com/kubernetes/website/issues/42644
9. https://github.com/kubernetes/website/issues/42605
11. https://github.com/kubernetes/kubernetes/issues/119983
12. https://github.com/kubernetes/autoscaler/issues/5934
13. https://github.com/kubernetes-sigs/gateway-api/issues/2324

SIG projects I am involved with:

1. https://github.com/kubernetes-sigs/gateway-api

**Comment by windsonsea** [comment]
+1

Thank you for nominating me. It would be great if you could inform me in advance through Slack, email, or any message.

**Comment by pegasas** [comment]
> +1
> 
> Thank you for nominating me. It would be great if you could inform me in advance through Slack, email, or any message.

Sure. My bad.
I remember your blog mention about it. 
But I can not find any reference this morning.

**Comment by tengqm** [comment]
The contribution stats are not that shining, but we always welcome people who meet the community criteria to join the team.
/lgtm
/approve

**Comment by mrbobbytables** [comment]
@pegasas  I've created PR https://github.com/kubernetes/org/pull/4410 to add you to the Kubernetes orgs. :) 
Once it gets merged you should get a membership invite notification.
Welcome to Kubernetes! 🎉

**Comment by pegasas** [comment]
Many Thanks to you @mrbobby!
will continue to contribute my effort!
