### ISSUE TITLE
REQUEST: New membership for DimpleRajaVamsi

### ISSUE THREAD

**Issue by DimpleRajaVamsi** [kubernetes/org#4408]
### GitHub Username

@DimpleRajaVamsi

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@randomvariable

### Sponsor 2

@jsturtevant

### List of contributions to the Kubernetes project

- PRs reviewed/authored
  - https://github.com/kubernetes-sigs/image-builder/pull/1023 (Authored)
  - https://github.com/kubernetes-sigs/image-builder/pull/1099 (Authored)
  - https://github.com/kubernetes-sigs/image-builder/pull/1105 (Authored)
  - https://github.com/kubernetes-sigs/image-builder/pull/1237 (Authored)
  - https://github.com/kubernetes-sigs/image-builder/pull/1243 (Authored)
  - https://github.com/kubernetes-sigs/image-builder/pull/1146 (Reviewed)

- SIG projects I am involved with
  - [image-builder](https://github.com/kubernetes-sigs/image-builder)

**Comment by randomvariable** [comment]
+1, confirming sponsorship.

**Comment by jsturtevant** [comment]
+1 thanks for your contributions to image builder!

**Comment by mboersma** [comment]
+1 thanks again for the solid contributions to image-builder!
