### ISSUE TITLE
Milestone maintainers on kubernetes-sigs

### ISSUE THREAD

**Issue by timothysc** [kubernetes/org#441]
### Organization or repository
e.g. kubernetes-sigs/* 

### Users effected
All approvers

### Describe the issue
Currently kubernetes_sigs is a federated set of repositories that spans multiple sigs.  Management of those subprojects is meant to be decentralized and for them to live on their own, possibly with their own lifecycle. 

As of today, there is a need to give approvers the ability to set their own milestones but they can not do that given existing permissions model on milestone maintainers.  

This is not tenable. 

@kubernetes/test-infra-maintainers @kubernetes/sig-contributor-experience-bugs

**Comment by vincepri** [comment]
+1 The current workflow requires to either be part of a github group or have complete write access to the repository, as far as I understand. Having approvers be able to set milestone would improve the current workflow *💯and reduce time spent in meetings organizing the backlog.

**Comment by chuckha** [comment]
what do people think about non-approvers who can set milestones? I think I can help triage issues in cluster-api but I am not an approver there.

**Comment by timothysc** [comment]
IMO kubernetes_sigs/* needs this.  It's not just one repo, but if I'm calling things out, everything sig-cluster-lifecycle related is my immediate concern.

**Comment by cblecker** [comment]
@timothysc Who should be given permissions to `/milestone` across the k-sigs org? In k/ that's the release team by default, but as you mention for k-sigs, these subprojects are supposed to be decentralized.

**Comment by nikhita** [comment]
Bumping this.

>  It's not just one repo, but if I'm calling things out, everything sig-cluster-lifecycle related is my immediate concern.

Since different subprojects (even under one SIG) might have different people working on it, I guess it makes sense to scope out milestone rights with a repo <-> team mapping. @timothysc wdyt? does that sound ok to you?

**Comment by nikhita** [comment]
:wave: bump

**Comment by nikhita** [comment]
/assign @timothysc 
ref https://twitter.com/timothysc/status/1116803681083633664 :upside_down_face: 

@timothysc do you think we can close this issue in favour of repo <-> team mapping?

**Comment by timothysc** [comment]
@nikhita yes!

**Comment by adrianludwin** [comment]
@timothysc I got here via a Google search on how to make `/milestone` work in kubernetes-sigs repos, but I don't understand the conclusion to this issue. Can you add a pointer to how we're supposed to make this work? Thanks!

**Comment by justaugustus** [comment]
@adrianludwin -- what repo are you trying to configure a milestone maintainer for?
If it's in kubernetes-sigs, there's a code hint here: https://github.com/kubernetes/test-infra/blob/201c7788b244ab2fc3efae7249fb939223ef6e1e/config/prow/plugins.yaml#L264.

The teams referenced in that config can be viewed here (organized by SIG): https://github.com/kubernetes/org/tree/master/config/kubernetes-sigs

**Comment by adrianludwin** [comment]
Thanks, that hint should be enough. We're looking at kubernetes-sigs/multi-tenancy.

**Comment by justaugustus** [comment]
Awesome!
