### ISSUE TITLE
REQUEST: New membership for AndrewSirenko

### ISSUE THREAD

**Issue by AndrewSirenko** [kubernetes/org#4411]
### GitHub Username

AndrewSirenko

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

ConnorJC3

### Sponsor 2

gnufied

### List of contributions to the Kubernetes project

Merged PRs:
- [Allow customization of aws-secret name and keys in Helm Chart #1668](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1668)
- [Allow additional volume mounts on node pods #1670](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1670)
- [Add Uninstall Documentation to install.md #1696](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1696)
- [Upgrade dependencies for driver v1.22.0 #1718](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1718)
- [Release v1.22.0 #1721](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1721)

WIP PRs:
- [kubernetes-sigs/aws-ebs-csi-driver: CSI driver for Amazon EBS https://aws.amazon.com/ebs/](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1706)

Currently also working on documentation for adding driver integration tests (as well as adding those integration tests for features not covered by kubernetes-e2e tests). 

Involved with Sig-Storage 

Thank you for considering me! :)

**Comment by ConnorJC3** [comment]
+1

**Comment by jasonbraganza** [comment]
Hello @gnufied, just checking in.

We need your +1 as a sponsor, to proceed with this request. Thank you. 🙂

**Comment by gnufied** [comment]
+1

**Comment by jasonbraganza** [comment]
Thank you @ConnorJC3 and @gnufied.

**Comment by ydFu** [comment]
/assign

@AndrewSirenko, I want to express my heartfelt gratitude for your invaluable contributions to our endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #4446 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes ! 🎉🚀

Best regards.

**Comment by Priyankasaggu11929** [comment]
Hello @ydFu, thanks for creating the PR. :slightly_smiling_face: 

But for future -- please note that the Org membership PRs are *only* created by one of the New Membership Coordinators after they've finished reviewing all the requirements for the Org memberships. fFor this issue, the NMC is @jasonbraganza).

**Comment by jasonbraganza** [comment]
@ydFu, thank you for your PR! :)

@priyankasaggu11929, I’m done with the review and all is well. Please approve this PR itself.

Welcome @AndrewSirenko! and Thank you :)
