### ISSUE TITLE
REQUEST: New membership for Vikash-8090-Yadav

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [kubernetes/org#4413]
### GitHub Username

@Vikash-8090-Yadav

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@bishal7679

### Sponsor 2

@anubha-v-ardhan

### List of contributions to the Kubernetes project

- PRs autthored
https://github.com/kubernetes/cloud-provider-openstack/pull/2289
https://github.com/kubernetes/cloud-provider-openstack/pull/2292
https://github.com/kubernetes/cloud-provider-openstack/pull/2301
https://github.com/kubernetes/cloud-provider-openstack/pull/2288
https://github.com/kubernetes/website/pull/41916
https://github.com/kubernetes/website/pull/42036
https://github.com/kubernetes/website/pull/42717

- PRs reviewed
https://github.com/kubernetes/website/pull/42726
https://github.com/kubernetes/website/pull/42709#issuecomment-1693237393
https://github.com/kubernetes/website/pull/42001#discussion_r1297174579
https://github.com/kubernetes/website/pull/42016#event-9831888333
https://github.com/kubernetes/ingress-gce/pull/2193#issuecomment-1638243083
https://github.com/kubernetes/cloud-provider-openstack/pull/2297#event-9833181684
https://github.com/kubernetes/cloud-provider-openstack/pull/2299

- Issue involved in
https://github.com/kubernetes/website/issues/42735
https://github.com/kubernetes/website/issues/42653

**Comment by bishal7679** [comment]
Huge +1 from me!
Thanks for all of your contributions so far; looking forward to more of them
Welcome to kubernetes 🎉

**Comment by anubha-v-ardhan** [comment]
+1 from me as well!
Thank you for your contributions and hope to see more of them in future.
Welcome to Kubernetes!

**Comment by Arhell** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
@Vikash-8090-Yadav, one of our New Membership Coordinators (cc: @jasonbraganza) will be taking a look at your request by the end of the week as part of this week's batch of membership requests.

**Comment by jasonbraganza** [comment]
/assign

@Vikash-8090-Yadav, Thank you for all your contributions so far. We look forward to your continuous contributions in the project.

I've created PR #4444 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to https://github.com/kubernetes! 🎉
