### ISSUE TITLE
REQUEST: New membership for yyy1000

### ISSUE THREAD

**Issue by yyy1000** [kubernetes/org#4417]
### GitHub Username

@yyy1000

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@camilamacedo86

### Sponsor 2

@varshaprasad96

### List of contributions to the Kubernetes project

 - PR authored
https://github.com/kubernetes-sigs/kubebuilder/pull/3378
https://github.com/kubernetes-sigs/kubebuilder/pull/3383
https://github.com/kubernetes-sigs/kubebuilder/pull/3387
https://github.com/kubernetes-sigs/kubebuilder/pull/3389
https://github.com/kubernetes-sigs/kubebuilder/pull/3391
https://github.com/kubernetes-sigs/kubebuilder/pull/3431
https://github.com/kubernetes-sigs/kubebuilder/pull/3461
https://github.com/kubernetes-sigs/kubebuilder/pull/3487
https://github.com/kubernetes-sigs/kubebuilder/pull/3489
https://github.com/kubernetes-sigs/kubebuilder/pull/3497
https://github.com/kubernetes-sigs/kubebuilder/pull/3503
https://github.com/kubernetes-sigs/kubebuilder/pull/3509
https://github.com/kubernetes-sigs/kubebuilder/pull/3544
https://github.com/kubernetes-sigs/kubebuilder/pull/3573

- SIGs
https://github.com/kubernetes-sigs/kubebuilder

**Comment by camilamacedo86** [comment]
+1

/lgtm
