### ISSUE TITLE
REQUEST: New membership for @wyike

### ISSUE THREAD

**Issue by wyike** [kubernetes/org#4428]
### GitHub Username

@wyike

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@lubronzhan 

### Sponsor 2

@HanFa 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  - https://github.com/kubernetes/cloud-provider-vsphere/pull/751
  - https://github.com/kubernetes/cloud-provider-vsphere/pull/752
  - https://github.com/kubernetes/cloud-provider-vsphere/pull/754
  - https://github.com/kubernetes/cloud-provider-vsphere/pull/756
  - https://github.com/kubernetes/cloud-provider-vsphere/pull/758
  - https://github.com/kubernetes/cloud-provider-vsphere/pull/755
  - https://github.com/kubernetes/test-infra/pull/30504
  - https://github.com/kubernetes/test-infra/pull/30531
- SIG projects I am involved with
  - sig-cluster-lifecycle
  - sig-cloud-provider

**Comment by lubronzhan** [comment]
Thanks @wyike for the work!

**Comment by jasonbraganza** [comment]
/assign

@wyike, thank you for all your contributions so far 🙂

I've created PR #4444 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
