### ISSUE TITLE
REQUEST: New membership for @codenrhoden

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/org#443]
### GitHub Username
@codenrhoden

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs
@kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @msau42 
- @frapposelli 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  Authored: https://github.com/kubernetes/kubernetes/pull/68513/, 
https://github.com/kubernetes/website/pull/8765, https://github.com/kubernetes-csi/external-attacher/pull/56, https://github.com/kubernetes-csi/csi-test/pull/84, https://github.com/kubernetes-csi/csi-test/pull/85, https://github.com/kubernetes/cloud-provider-vsphere/pull/85, https://github.com/kubernetes/cloud-provider-vsphere/pull/88, https://github.com/kubernetes/cloud-provider-vsphere/pull/111, https://github.com/kubernetes/cloud-provider-vsphere/pull/112, https://github.com/kubernetes/cloud-provider-vsphere/pull/116, https://github.com/kubernetes/cloud-provider-vsphere/pull/117, https://github.com/kubernetes/cloud-provider-vsphere/pull/121, https://github.com/kubernetes/cloud-provider-vsphere/pull/123, https://github.com/kubernetes/cloud-provider-vsphere/pull/125, https://github.com/kubernetes/cloud-provider-vsphere/pull/126, https://github.com/kubernetes/community/pull/2193
  Reviewed: https://github.com/kubernetes/cloud-provider-vsphere/pull/136, https://github.com/kubernetes/cloud-provider-vsphere/pull/108, https://github.com/kubernetes/cloud-provider-vsphere/pull/110, https://github.com/kubernetes/cloud-provider-vsphere/pull/114, https://github.com/kubernetes/cloud-provider-vsphere/pull/119, https://github.com/kubernetes/cloud-provider-vsphere/pull/124, https://github.com/kubernetes/cloud-provider-vsphere/pull/101, https://github.com/kubernetes/cloud-provider-vsphere/pull/103
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/64953, https://github.com/kubernetes/cloud-provider-vsphere/issues/128, 
- SIG projects I am involved with
sig-storage
sig-vmware
sig-release (branch manager shadow for 1.12)

**Comment by mrbobbytables** [comment]
Hey there @codenrhoden, thank you for all the work you've put towards the project so far :)

I've created PR #446  to add you to all 3 orgs. Once that gets merged, you should get the membership invite notifications.

Welcome to @kubernetes! 🎉

/assign
