### ISSUE TITLE
Github Token for publishing bot to interact with GH repos

### ISSUE THREAD

**Issue by sayanchowdhury** [kubernetes/org#4434]
### Organization or Repo

https://github.com/kubernetes/publishing-bot/

### Describe the issue

We are working on running publishing-bot as a periodic job on the test-infra [1]. The publishing-bot would be interacting with the Github repositories through a Github token. The idea is to create a secret  with the token and deploy it in the `k8s-infra-prow-build-trusted` cluster.

The publishing bot is currently running in a cluster named `aaa` and this cluster already contains a secret `publishing-bot-github-token` which is a github token that has write access to the staging repositories. 

We would like to know if the same token can be reused in the k8s-infra-prow-build-trusted cluster for running the publishing bot or should we file a request for a new token?

[1] https://github.com/kubernetes/publishing-bot/issues/353

/cc @akhilerm

**Comment by ameukam** [comment]
I don't see any issue on reusing the token in the `aaa` cluster. Let's get input from the Github admins. 

cc @MadhavJivrajani @palnabarun @Priyankasaggu11929

**Comment by nikhita** [comment]
I'm good with this. Let's wait until EOD for any blocking comments. 

If there are none, please go ahead with this.

**Comment by Priyankasaggu11929** [comment]
>I don't see any issue on reusing the token in the aaa cluster.

+1.

Just confirming, is [this the only spot](https://github.com/kubernetes/publishing-bot/blob/6fdddca4d0470187bd84c060d4a29e3e654e40d5/artifacts/manifests/podspec.yaml#L33) we're using the existing `publishing-bot-github-token` right now?

**Comment by MadhavJivrajani** [comment]
+1 on reusing the token from the `aaa` cluster.

**Comment by mrbobbytables** [comment]
+1 on reusing as well

**Comment by sayanchowdhury** [comment]
@Priyankasaggu11929 Yes, this is only place the where the token is being used. @akhilerm Could you confirm this info once?

**Comment by ameukam** [comment]
Token is available on the build cluster: https://github.com/kubernetes/k8s.io/pull/5950

**Comment by sayanchowdhury** [comment]
Thanks @ameukam. I go ahead and close this issue.

/close
