### ISSUE TITLE
REQUEST: New membership for AndiDog

### ISSUE THREAD

**Issue by AndiDog** [kubernetes/org#4437]
### GitHub Username

AndiDog

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@richardcase

### Sponsor 2

@Ankitasw

### List of contributions to the Kubernetes project

- PRs

  - [4 merged PRs on cluster-api](https://github.com/pulls?q=is%3Apr+author%3AAndiDog+repo%3Akubernetes-sigs%2Fcluster-api+), 1 in review
  - [7 merged PRs on cluster-api-provider-aws](https://github.com/pulls?q=is%3Apr+author%3AAndiDog+repo%3Akubernetes-sigs%2Fcluster-api-provider-aws), several closed after discussion that resulted in better solution
  - [PRs on several other Kubernetes-related projects](https://github.com/pulls?q=+author%3AAndiDog+org%3Akubernetes)
- Actively working on networking improvement proposal prototype for CAPA ([source issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4026#issuecomment-1423959616))
- Contributing to reconciliation and network related issues in CAPI+CAPA ([example issue 1](https://github.com/kubernetes-sigs/cluster-api/issues/8858), [2](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4071))
- Participating in CAPI+CAPA office hours and Slack sometimes
- Started reviewing PRs occasionally ([1](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4359), [2](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4464))

**Comment by richardcase** [comment]
@AndiDog - thank your for all your contributions to CAPI and CAPA. From me its:

+1

**Comment by Ankitasw** [comment]
Thank you for all the contributions @AndiDog 

+1 from my side as well

**Comment by AndiDog** [comment]
⚠️ I added `kubernetes` as requested org to the issue since @Ankitasw recommended it for making changes to test infra.

**Comment by jasonbraganza** [comment]
/assign

@AndiDog, thank you for all your contributions so far 🙂

I've created PR #4444 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
