### ISSUE TITLE
REQUEST: Create kubernetes-sigs/cloud-pv-admission-labeler

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/org#4438]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

cloud-pv-admission-labeler

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

andrewsykim, cheftako

### Who should have write access?

andrewsykim, cheftako

### Who should be listed as approvers in OWNERS?

andrewsykim, cheftako

### Who should be listed in SECURITY_CONTACTS?

andrewsykim, cheftako

### What should the repo description be?

External admission webhook to label PVs created by cloud providers

### What SIG and subproject does this fall under?

sig-cloud-provider

### Please provide references to appropriate approval for this new repo

- approval from SIG leads (andrewsy, cheftako, elmiko)

**Comment by dims** [comment]
+1 from me.

xref: https://github.com/kubernetes/kubernetes/issues/52617

**Comment by cheftako** [comment]
+1

**Comment by elmiko** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
Thanks for the +1s. (for record -- we've +1s from sig-cloud-provider TL/Chair).

 I'll go ahead with creating this repository.
 
 /assign

**Comment by Priyankasaggu11929** [comment]
@andrewsykim, just to confirm, the requested new repo will be part of which [subproject](https://github.com/kubernetes/community/tree/master/sig-cloud-provider#subprojects) of sig-cloud-provider?

**Comment by Priyankasaggu11929** [comment]
**update**: corrected the username `s/andrewsy/andrewsykim/g` in the issue description.

**Comment by Priyankasaggu11929** [comment]
The repo has been created: https://github.com/kubernetes-sigs/cloud-pv-admission-labeler :tada: 

Created the following PR to add GitHub teams for the new repo:
- https://github.com/kubernetes/org/pull/4445

I'll wait for input on the subproject name https://github.com/kubernetes/org/issues/4438#issuecomment-1711411931 and then create another PR to add subproject documentation. Thanks!

**Comment by andrewsykim** [comment]
> @andrewsykim, just to confirm, the requested new repo will be part of which [subproject](https://github.com/kubernetes/community/tree/master/sig-cloud-provider#subprojects) of sig-cloud-provider?

That's correct

**Comment by andrewsykim** [comment]
Oh, sorry I misread your question. It will be under this subproject: https://github.com/kubernetes/community/tree/master/sig-cloud-provider#cloud-provider-extraction-migration

**Comment by Priyankasaggu11929** [comment]
Thanks for confirming, @andrewsykim!

Created below PR to to add the new repo to k/community sigs.yaml:
- https://github.com/kubernetes/community/pull/7523

With this, the repo creation is completed. I'll wait for the PRs to merge and will close the issue then! Thank you!

**Comment by Priyankasaggu11929** [comment]
All PRs are merged. Closing the issue. Thanks!

/close
