### ISSUE TITLE
REQUEST: New integration for kubernetes-sigs/cluster-api-provider-vsphere

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/org#4439]
### Organization or Repo

kubernetes-sigs/cluster-api-provider-vsphere

### Name of integration

Codecov

### Link to integration website

github.com/apps/codecov

### Describe what is attempting to be accomplished

We are working on improving code coverage visualization in CAPV. Currently, the codecov-commenter bot automatically comments on PRs that upload a codecov report. However, this codecov-commenter bot is outdated and using the Codecov GitHub app is the recommended practice.

(basically copied from https://github.com/kubernetes/org/issues/4190, we want the same that they have :))

**Comment by sbueringer** [comment]
cc @killianmuldoon @chrischdi 

xref: https://kubernetes.slack.com/archives/CEX9HENG7/p1694019429815179

**Comment by MadhavJivrajani** [comment]
@sbueringer I've enabled it for `kubernetes-sigs/cluster-api-provider-vsphere`, can you please verify?

**Comment by sbueringer** [comment]
Looks good, thank you!

/close
