### ISSUE TITLE
REQUEST: Create new repository sigs.k8s.io/cluster-inventory-api (sig-multicluster)

### ISSUE THREAD

**Issue by mikeshng** [kubernetes/org#4440]
### New repo, staging repo, or migrate existing

New repository

### Is it a staging repo?

no

### Requested name for new repository

cluster-inventory-api

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

mikeshng,ryanzhang-oss,RainbowMango,dixudx

### Who should have write access?

mikeshng,ryanzhang-oss,RainbowMango,dixudx

### Who should be listed as approvers in OWNERS?

mikeshng,ryanzhang-oss,RainbowMango,dixudx

### Who should be listed in SECURITY_CONTACTS?

mikeshng,ryanzhang-oss,RainbowMango,dixudx

### What should the repo description be?

The `ClusterInventory API` provides a reliable, consistent, and automated approach for any multi-cluster application (framework, toolset) to discover available clusters and take actions accordingly, in a way similar to service discovery works in a microservice architecture. Through the inventory, the application can query for a list of clusters to access, or watch for an ever-flowing stream of cluster lifecycle events which the application can act upon timely, such as auto-scaling, upgrades, failures, and connectivity issues.
This repo will hold design documents and implementation of the [ClusterInventory API](https://docs.google.com/document/d/1sUWbe81BTclQ4Uax3flnCoKtEWngH-JA9MyCqljJCBM/).

### What SIG and subproject does this fall under?

sig-multicluster

### Please provide references to appropriate approval for this new repo

Discussed with the SIG Multicluster leads at the community meetings:
- [2023-07-11](https://docs.google.com/document/d/18mk62nOXE_MCSSnb4yJD_8UadtzJrYyJxFwbrgabHe8/edit#heading=h.uwx6f737qbra)
- [2023-08-08](https://docs.google.com/document/d/18mk62nOXE_MCSSnb4yJD_8UadtzJrYyJxFwbrgabHe8/edit#heading=h.8vwwnzre52wr)
- [2023-09-05 repo creation verbally approved by the SIG Multicluster chairs](https://docs.google.com/document/d/18mk62nOXE_MCSSnb4yJD_8UadtzJrYyJxFwbrgabHe8/edit#heading=h.18cyk8b5vghk)
- SIG Multicluster community reviewed [proposal](https://docs.google.com/document/d/1sUWbe81BTclQ4Uax3flnCoKtEWngH-JA9MyCqljJCBM/)

### Additional context for request

CC [SIG Multicluster Chairs](https://github.com/kubernetes/community/blob/master/sig-multicluster/README.md#chairs)
@jeremyot
@pmorie
As discussed, we are working on the KEP draft in parallel. Thanks.

**Comment by Priyankasaggu11929** [comment]
cc: @kubernetes/sig-multicluster-leads for review and approval

**Comment by Priyankasaggu11929** [comment]
> What SIG and subproject does this fall under?
>
> sig-multicluster

@mikeshng, could you also mention the name of the [`sig-multicluster` subproject](https://github.com/kubernetes/community/blob/master/sig-multicluster/README.md#subprojects) under which the new requested repo will reside? Thanks!

**Comment by JeremyOT** [comment]
I'm supportive of this repo, but good point about the subproject. I think we need to add a new one for cluster-inventory-api

**Comment by mikeshng** [comment]
> @mikeshng, could you also mention the name of the [`sig-multicluster` subproject](https://github.com/kubernetes/community/blob/master/sig-multicluster/README.md#subprojects) under which the new requested repo will reside? Thanks!

As suggested by Jeremy, the cluster-inventory-api should be a new subproject. Thanks.

**Comment by Priyankasaggu11929** [comment]
For the record, I'll need approvals from at least two SIG Multicluster chairs.

Thanks, JeremyOT, for your approval!

@pmorie, could you please also give a +1 on this issue?

Once I have that, I'll proceed with creating the repository. Thank you!

**Comment by Priyankasaggu11929** [comment]
@pmorie – friendly ping for your +1. :slightly_smiling_face:

**Comment by mrbobbytables** [comment]
Jeremy is a lead, we can move forward with this 👍 I'll go ahead and create
/assign

**Comment by mrbobbytables** [comment]
FYI - ryanzhang-oss is not a k8s org member. Will skip adding him as owners etc.

**Comment by mrbobbytables** [comment]
repo has been created: https://github.com/kubernetes-sigs/cluster-inventory-api
k/community is updated: https://github.com/kubernetes/community/pull/7565
Teams PR: https://github.com/kubernetes/org/pull/4506

once the teams PR is merged, this should be safe to close.

**Comment by mrbobbytables** [comment]
everything has merged, going to go ahead and close this out.
Let me know if you need anything else 👍 

/close
