### ISSUE TITLE
REQUEST: New membership for Songjoy

### ISSUE THREAD

**Issue by Songjoy** [kubernetes/org#4442]
### GitHub Username

Songjoy

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@wzshiming

### Sponsor 2

@pohly

### List of contributions to the Kubernetes project

kwok
https://github.com/kubernetes-sigs/kwok/pull/118
https://github.com/kubernetes-sigs/kwok/pull/496
https://github.com/kubernetes-sigs/kwok/pull/497
https://github.com/kubernetes-sigs/kwok/pull/498
https://github.com/kubernetes-sigs/kwok/pull/500
https://github.com/kubernetes-sigs/kwok/pull/501
https://github.com/kubernetes-sigs/kwok/pull/504
https://github.com/kubernetes-sigs/kwok/pull/519

kubernetes
https://github.com/kubernetes/kubernetes/pull/119463
https://github.com/kubernetes/kubernetes/pull/119468
https://github.com/kubernetes/kubernetes/pull/119501 
https://github.com/kubernetes/kubernetes/pull/119502
https://github.com/kubernetes/kubernetes/pull/119558

**Comment by pohly** [comment]
/lgtm

Your E2E test changes went beyond simple search/replace and made the tests better. Thanks!

**Comment by wzshiming** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@Songjoy, thank you for all your contributions so far 🙂

I've created PR #4444 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
