### ISSUE TITLE
REQUEST: New membership for z1cheng

### ISSUE THREAD

**Issue by z1cheng** [kubernetes/org#4449]
### GitHub Username

@z1cheng

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@rikatz

### Sponsor 2

@tao12345666333

### List of contributions to the Kubernetes project

PRs:
- [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx):
https://github.com/kubernetes/ingress-nginx/pull/10396
https://github.com/kubernetes/ingress-nginx/pull/10394
https://github.com/kubernetes/ingress-nginx/pull/10387
https://github.com/kubernetes/ingress-nginx/pull/10385
https://github.com/kubernetes/ingress-nginx/pull/10196
https://github.com/kubernetes/ingress-nginx/pull/10187
https://github.com/kubernetes/ingress-nginx/pull/10166
https://github.com/kubernetes/ingress-nginx/pull/10156
https://github.com/kubernetes/ingress-nginx/pull/10129
https://github.com/kubernetes/ingress-nginx/pull/10128
https://github.com/kubernetes/ingress-nginx/pull/10062
https://github.com/kubernetes/ingress-nginx/pull/10034

- [kubernetes/release](https://github.com/kubernetes/release): https://github.com/kubernetes/release/pull/3142
- [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes): https://github.com/kubernetes/kubernetes/pull/104939

**Comment by tao12345666333** [comment]
LGTM! Thanks for your contributions

**Comment by ydFu** [comment]
/assign

@z1cheng, I want to express my heartfelt gratitude for your invaluable contributions to our endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request https://github.com/kubernetes/org/pull/4454 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the https://github.com/kubernetes ! 🎉🚀

Best regards.
