### ISSUE TITLE
REQUEST: New membership for a-mccarthy

### ISSUE THREAD

**Issue by krol3** [kubernetes/org#4456]
### GitHub Username

@a-mccarthy

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@krol3

### Sponsor 2

@Priyankasaggu11929

### List of contributions to the Kubernetes project

@a-mccarthy is involved with sig-release, a shadow member of Comms for 1.29 Kubernetes Release

**Comment by mrbobbytables** [comment]
@a-mccarthy you already are a member of kubernetes^^;;

If you want k-sigs org membership as well, please go ahead and open a PR to add yourself. It just has to follow the format of `Add <user> to <org>`.

If you don't mind waiting, it'll be handled in the next batch of org membership requests.
