### ISSUE TITLE
REQUEST: New membership for Princesso

### ISSUE THREAD

**Issue by Princesso** [kubernetes/org#4460]
### GitHub Username

Princesso

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

katcosgrove

### Sponsor 2

Priyankasaggu11929

### List of contributions to the Kubernetes project

v1.29 Release Team

**Comment by katcosgrove** [comment]
+1

Welcome to the v1.29 Release Team!

cc: @Priyankasaggu11929

**Comment by Priyankasaggu11929** [comment]
+1. Welcome to the team :)

**Comment by ydFu** [comment]
Hello@Princesso
I want to express my heartfelt gratitude for your invaluable contributions to community endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #4469 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes family! 🎉🚀

Best regards,

**Comment by Princesso** [comment]
Thank you, @katcosgrove, @Priyankasaggu11929 and @ydFu. I'm elated to be joining the prestigious Kubernetes organization!
