### ISSUE TITLE
REQUEST: New membership for CoderSherlock

### ISSUE THREAD

**Issue by CoderSherlock** [kubernetes/org#4462]
### GitHub Username

CoderSherlock

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

bobbypage

### Sponsor 2

tzneal

### List of contributions to the Kubernetes project

* Authored:
  * https://github.com/kubernetes/kubernetes/pull/117597
  * https://github.com/kubernetes/kubernetes/pull/119212
* Discussion involvement:
  * https://github.com/kubernetes/kubernetes/issues/113480
  * https://github.com/kubernetes/kubernetes/issues/112459 
* Other involvements/Ongoings:
  * Failed eviction test investigation https://github.com/kubernetes/test-infra/pull/28462
  * GPUDevicePlugin failed test triage

**Comment by bobbypage** [comment]
Thanks so much @CoderSherlock for all your contributions to CI Node Group! +1

/lgtm

**Comment by Priyankasaggu11929** [comment]
/assign

@CoderSherlock, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4493 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
