### ISSUE TITLE
REQUEST: New membership for tukwila

### ISSUE THREAD

**Issue by tukwila** [kubernetes/org#4464]
### GitHub Username

tukwila

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu 

### Sponsor 2

@liggitt 

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pull/120499
https://github.com/kubernetes/kubernetes/pull/120116
https://github.com/kubernetes/kubernetes/pull/119274
https://github.com/kubernetes/kubernetes/pull/118967
https://github.com/kubernetes/kubernetes/pull/118781
https://github.com/kubernetes/kubernetes/pull/118218
https://github.com/kubernetes/kubernetes/pull/117169
https://github.com/kubernetes/kubernetes/pull/116569

**Comment by tukwila** [comment]
@liggitt Could you be my sponsor to accept me as member? thank you in advance.

**Comment by Priyankasaggu11929** [comment]
Hello @tukwila, could you please update the ticket to list folks who've agreed to sponsor your org membership request?

Check out the sponsorship requirements here: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements. Thanks! 😊

**Comment by satyampsoni** [comment]
Do sponsors support with the money or is there something else ?

**Comment by pacoxu** [comment]
> Do sponsors support with the money or is there something else ?

@satyampsoni  You can read more details in https://github.com/kubernetes/community/blob/f5cc59a13411e8e5d05ca22dc049183d44dc8598/github-management/new-membership-procedure.md#membership-requirements

> List their active contributions
> 
> This is left purposefully vague. We want to record what those contributions are, but **we leave it up to the sponsors to determine if they are at a bar that warrants membership. We want to make it easy for those who are actively contributing to join, but this bar should be higher than, for example, a few spelling corrections.**

**Comment by pacoxu** [comment]
+1

@tukwila  Thanks for your contributions in some version bumps and test related cleanup. And I hope you can make more contributions to the community.

**Comment by jasonbraganza** [comment]
Hello @liggitt , we need your +1 as a sponsor, to proceed with this request. Thank you. 🙂

**Comment by liggitt** [comment]
+1, sorry, missed the earlier ping

**Comment by jasonbraganza** [comment]
/assign

@tukwila, thank you for all your contributions so far 🙂

I've created PR #4504  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
