### ISSUE TITLE
REQUEST: New membership for elezar

### ISSUE THREAD

**Issue by elezar** [kubernetes/org#4472]
### GitHub Username

@elezar

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@klueska

### Sponsor 2

@bart0sh

### Adding support for CDI devices to the device plugin API:
- KEP: https://github.com/kubernetes/enhancements/pull/4011
- Implementation: https://github.com/kubernetes/kubernetes/pull/118254
- Documentation:
    - https://github.com/kubernetes/website/pull/42001
    - https://github.com/kubernetes/website/pull/42600

### Debugging and fixing a bug when swap is disabled  
- https://github.com/kubernetes/kubernetes/pull/120784

### Address inconsistency in kops for NVIDIA package
- https://github.com/kubernetes/kops/pull/15096

## PRs reviewed
- https://github.com/kubernetes/kubernetes/pull/118635
- https://github.com/kubernetes-sigs/kind/pull/3290

## Other contributions
- Co-chair of the Container Orchestrated Devices WG under TAG Runtime
- Contributions to the Container Device Interface: https://github.com/cncf-tags/container-device-interface/pulls?q=is%3Apr+author%3Aelezar+is%3Amerged

**Comment by bart0sh** [comment]
+1
Evan is a maintainer and an active contributor of https://github.com/klihub/container-device-interface project. He also a contributor to the Kubernetes project. I'm happy to sponsor him.

**Comment by klueska** [comment]
+1 as sig-node-approver from NVIDIA

**Comment by mikebrow** [comment]
SGTM!

**Comment by klueska** [comment]
@natasha41575 what else is needed to move this forward?

**Comment by mrbobbytables** [comment]
They are processed in batches, usually about once a week.

**Comment by Priyankasaggu11929** [comment]
/assign

@elezar, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4493 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
