### ISSUE TITLE
REQUEST: New membership for BlaineEXE

### ISSUE THREAD

**Issue by BlaineEXE** [kubernetes/org#4473]
### GitHub Username

@BlaineEXE

### Organization you are requesting membership in

kubernetes
kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@wlan0

### List of contributions to the Kubernetes project

- Working actively with sig-storage's COSI project: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1979-object-storage-support
  - proposing: https://github.com/kubernetes/enhancements/pull/4196
  - discussing: https://github.com/kubernetes/enhancements/issues/4204
  - worked on build pipeline for image 1 of 2: https://github.com/kubernetes-sigs/container-object-storage-interface-controller
  - next up, image 2 of 2: https://github.com/BlaineEXE/cosi-provisioner-sidecar
- https://github.com/kubernetes/k8s.io/commit/1b1d9cf33de0c91b411c06fbcbf3dc8e4cbd5f78
- 3 Minikube improvements: https://github.com/kubernetes/minikube/pulls?q=+author%3ABlaineEXE+
- 1 controller-runtime improvement: https://github.com/kubernetes-sigs/controller-runtime/issues/1702

**Comment by xing-yang** [comment]
@BlaineEXE I suggest that you also apply for membership in the "kubernetes" org.

+1

**Comment by wlan0** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@BlaineEXE, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4493 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
