### ISSUE TITLE
REQUEST: New membership for @cnmcavoy

### ISSUE THREAD

**Issue by cnmcavoy** [kubernetes/org#4474]
### GitHub Username

cnmcavoy

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@skarlso

### Sponsor 2

@dlipovetsky

### PR's authored:
**Cluster API**
- https://github.com/kubernetes-sigs/cluster-api/pull/8917
- https://github.com/kubernetes-sigs/cluster-api/pull/9419

**Cluster API Provider for AWS:**
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2468
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3727
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3728
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3752
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3757
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3795
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4092
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4117
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4195
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4378
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4380
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4446

**Cluster Autoscaler**
- https://github.com/kubernetes/autoscaler/pull/5382
- https://github.com/kubernetes/autoscaler/pull/5416
- https://github.com/kubernetes/autoscaler/pull/5418
- https://github.com/kubernetes/autoscaler/pull/5951

---
### PR's reviewed:
**Cluster API**
- https://github.com/kubernetes-sigs/cluster-api/pull/7938

**Cluster API Provider for AWS:**
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4037

**Comment by Skarlso** [comment]
Huge +1 from me! Cameron has been an avoid and prolific contributor to CAPA and frequently visited office hours to discuss some modifications or improvements to CAPA. Welcome, Cameron! :)

**Comment by dlipovetsky** [comment]
+1 from me.

Thanks for all your meaningful contributions so far, Cameron, and here's looking forward to more.

**Comment by Priyankasaggu11929** [comment]
/assign

@cnmcavoy, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4493 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
