### ISSUE TITLE
REQUEST: New membership for @gcs278

### ISSUE THREAD

**Issue by gcs278** [kubernetes/org#4476]
### GitHub Username

@gcs278

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@shaneutt 

### Sponsor 2

@robscott 

### List of contributions to the Kubernetes project

I'm actively contributing to the gateway-api project:
- https://github.com/kubernetes-sigs/gateway-api/pull/2315
- https://github.com/kubernetes-sigs/gateway-api/pull/2064
- https://github.com/kubernetes-sigs/gateway-api/pull/1935
- https://github.com/kubernetes-sigs/gateway-api/pull/1889
- https://github.com/kubernetes-sigs/gateway-api/pull/1643
- https://github.com/kubernetes-sigs/gateway-api/pull/2159
- https://github.com/kubernetes-sigs/gateway-api/issues/1619
- https://github.com/kubernetes-sigs/controller-runtime/issues/1869

**Comment by shaneutt** [comment]
:100: thank you Grant for all your contributions, particularly the work you've done on enhancement proposals for Gateway API! :+1:

**Comment by robscott** [comment]
Thanks for all the contributions @gcs278! Big +1 from me.

**Comment by Priyankasaggu11929** [comment]
/assign

@gcs278, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4493 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
