### ISSUE TITLE
REQUEST: New membership for candita

### ISSUE THREAD

**Issue by candita** [kubernetes/org#4477]
### GitHub Username

@candita

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@shaneutt

### Sponsor 2

@robscott

### List of contributions to the Kubernetes project

PRs Authored
https://github.com/kubernetes-sigs/gateway-api/pull/2113
https://github.com/kubernetes-sigs/gateway-api/pull/1906
https://github.com/kubernetes-sigs/gateway-api/pull/1587
https://github.com/kubernetes-sigs/gateway-api/pull/1430

PRs Reviewed
https://github.com/kubernetes-sigs/gateway-api/pull/2171
https://github.com/kubernetes-sigs/gateway-api/pull/1997
https://github.com/kubernetes-sigs/gateway-api/pull/1979
https://github.com/kubernetes-sigs/gateway-api/pull/1383
https://github.com/kubernetes-sigs/gateway-api/pull/1326
https://github.com/kubernetes-sigs/gateway-api/pull/1124
https://github.com/kubernetes-sigs/gateway-api/pull/1086

Discussion
https://github.com/kubernetes-sigs/gateway-api/discussions/1285

Issues 
https://github.com/kubernetes-sigs/gateway-api/issues/2147
https://github.com/kubernetes-sigs/gateway-api/issues/1898
https://github.com/kubernetes-sigs/gateway-api/issues/1897
https://github.com/kubernetes-sigs/gateway-api/issues/1579

**Comment by robscott** [comment]
Thanks for all the contributions @candita! Big +1 from me

**Comment by shaneutt** [comment]
:100: thank you Candace for all your contributions, and particularly your hard work on `BackendTLSPolicy`, BIG +1 from me. :partying_face:  :+1:

**Comment by Priyankasaggu11929** [comment]
/assign

@candita, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4493 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
