### ISSUE TITLE
REQUEST: Archive repo contributor-tweets

### ISSUE THREAD

**Issue by SD-13** [kubernetes/org#4481]
### Repository to archive

https://github.com/kubernetes-sigs/contributor-tweets

### Repository and/or sig subproject owners that are approving this archival

Since SIG-Contributor-comms owns this repo, tagging the leads @chris-short @kaslin here.

### When should this be done

anytime

### Additional context for request

Contributor-comms created this repo to automate sharing stuff in social media, but that didn't work out much.

**Comment by mrbobbytables** [comment]
everything has merged and repo has been migrated, going to go ahead and close this out 👍 
/close
