### ISSUE TITLE
REQUEST: Create Prow repository

### ISSUE THREAD

**Issue by timwangmusic** [kubernetes/org#4482]
### New repo, staging repo, or migrate existing

Prow

### Is it a staging repo?

no

### Requested name for new repository

prow

### Which Organization should it reside

kubernetes-sigs

### Who should be listed as approvers in OWNERS?

cblecker, cjwagner, petr-muller, stevekuznetsov, droslean

### What should the repo description be?

Home repository for Prow

### What SIG and subproject does this fall under?

sig-testing

### Please provide references to appropriate approval for this new repo

There is an increasing demand for moving [Prow](https://docs.prow.k8s.io/docs/overview) out of the [kubernetes test-infra](https://github.com/kubernetes/test-infra) repo. Having a separate repo makes it easier to develop and adapt.

**Comment by palnabarun** [comment]
@timwangmusic -- can you please provide the list of people who should have admin, write access to the repo and a list of security contacts?

/assign

**Comment by ameukam** [comment]
@timwangmusic https://github.com/kubernetes-sigs/prow/ could be used for this ?

**Comment by BenTheElder** [comment]
+1 to we have an existing repo for this already. See also https://github.com/kubernetes/org/issues/3228

> The reason why we request just prow for the repo name here is because that way we leave open the option of migrating the Prow codebase to this repo in the future (if that happens). No other repos named just prow exist in the Kubernetes community so this should be fine.

---

Also @palnabarun for future repos: SIG testing would typically approve a repo by discussion in mailinglist + slack + meeting, I don't think this topic has come up recently in any of those (and it should be all of them) though I've missed a few meetings. I also don't see any references to TL-approval as would typically be required.

**Comment by palnabarun** [comment]
> Also @palnabarun for future repos: SIG testing would typically approve a repo by discussion in mailinglist + slack + meeting, I don't think this topic has come up recently in any of those (and it should be all of them) though I've missed a few meetings. I also don't see any references to TL-approval as would typically be required.

@BenTheElder -- FYI, we (as GitHub admins) don't approve any such requests without SIG TLs providing explicitly +1 to the request. Not sure if anything made you to feel otherwise.

**Comment by timwangmusic** [comment]
Closing due to we decided to use https://github.com/kubernetes-sigs/prow repository.
