### ISSUE TITLE
REQUEST: New membership for prateekgogia

### ISSUE THREAD

**Issue by prateekgogia** [kubernetes/org#4483]
### GitHub Username

@prateekgogia

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@hakman

### Sponsor 2

@dims

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kops/pulls?q=is%3Apr+author%3Aprateekgogia+is%3Aclosed
https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Aprateekgogia+is%3Aclosed
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Aprateekgogia+is%3Aclosed

Working with sig-scalability for adding scale tests on AWS using Kops

**Comment by dims** [comment]
+1 from me!

**Comment by hakman** [comment]
+1 from me too

**Comment by Priyankasaggu11929** [comment]
/assign

@prateekgogia, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4493 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

**Comment by prateekgogia** [comment]
@Priyankasaggu11929 Thanks for looking into this, for some reason I got follow up emails which had membership cancelled, how can we check why it got cancelled?
Subject - `Your invitation to the Kubernetes organization has been canceled`

**Comment by Priyankasaggu11929** [comment]
Hello @hakuna, thanks for the heads-up!

Our org membership invite tool is having some errors right now. I'll look into it tomorrow, and once it's fixed, you'll get a new invite.
