### ISSUE TITLE
REQUEST: New membership for mjudeikis

### ISSUE THREAD

**Issue by mjudeikis** [kubernetes/org#4484]
### GitHub Username

mjudeikis

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-csi, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sttts

### Sponsor 2

@ncdc

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pull/80402
https://github.com/kubernetes/kubernetes/pull/120717

Most of work was done in kcp-dev/kcp which is now sanbox project so sorting out wider access to make sure we are aligned in our code and contributions back

**Comment by sttts** [comment]
@mjudeikis is in the community for ages and has contributions to a couple of repos in kube orgs.

+1

**Comment by jasonbraganza** [comment]
Hello @ncdc, we need your +1 as a sponsor, to proceed with this request. Thank you. 🙂

**Comment by ncdc** [comment]
@jasonbraganza I reacted with a 👍 to the issue. But here is an explicit 👍 😄

**Comment by jasonbraganza** [comment]
/assign

@mjudeikis, thank you for all your contributions so far 🙂

I've created PR #4504  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
