### ISSUE TITLE
REQUEST: New membership for  hakuna-matatah@

### ISSUE THREAD

**Issue by hakuna-matatah** [kubernetes/org#4488]
### GitHub Username

@hakuna-matatah

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@hakman

### List of contributions to the Kubernetes project ( Issues/PRs created/reviewed/responded)

- https://github.com/kubernetes/kubernetes/issues/114049#issuecomment-1326390991
- https://github.com/kubernetes/test-infra/pull/30902
- https://github.com/kubernetes/test-infra/pull/30817
- https://github.com/kubernetes/test-infra/pull/30787
- https://github.com/kubernetes/test-infra/pull/30786
- https://github.com/kubernetes/test-infra/pull/30780
- https://github.com/kubernetes/test-infra/pull/30772
- https://github.com/kubernetes/test-infra/pull/30749
- https://github.com/kubernetes/test-infra/pull/30699
- https://github.com/kubernetes/test-infra/pull/30697
- https://github.com/kubernetes/test-infra/pull/30621
- https://github.com/kubernetes/test-infra/pull/30619
- https://github.com/kubernetes/test-infra/pull/30611
- https://github.com/kubernetes/test-infra/pull/30561
- https://github.com/kubernetes/kops/pull/15932
- https://github.com/kubernetes/kops/pull/15920
- https://github.com/kubernetes/kops/pull/15915
- https://github.com/kubernetes/kops/pull/15908
- https://github.com/kubernetes/kops/pull/15904
- https://github.com/kubernetes/kops/pull/15884
- https://github.com/kubernetes/kops/pull/15875

Collaborated with Hakman and Dims to successfully able to setup 5k load Scale tests on AWS EC2 running/passing - https://testgrid.k8s.io/kops-misc#ec2-master-scale-performance

**Comment by dims** [comment]
+1 from me!

**Comment by Priyankasaggu11929** [comment]
/assign

@hakuna-matatah, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4493 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
