### ISSUE TITLE
REQUEST: New membership for @sdodson

### ISSUE THREAD

**Issue by sdodson** [kubernetes/org#4489]
### GitHub Username

@sdodson

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@liggitt

### Sponsor 2

@deads2k

### List of contributions to the Kubernetes project

I'm actively participating WG-LTS and plan to continue participating there, helping and sharing my experiences from helping Red Hat meet our customer's ever growing lifecycle needs.

https://docs.google.com/document/d/1RI_EL35MwQxrHqlWvtQNINhOSWergL3hmOSgC5PeZss/edit#heading=h.ux0kkzjkdx4m

**Comment by deads2k** [comment]
+1 from me

**Comment by liggitt** [comment]
+1

**Comment by Priyankasaggu11929** [comment]
/assign

@sdodson, thank you for all your contributions so far :slightly_smiling_face: 

I've created PR https://github.com/kubernetes/org/pull/4493 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:
