### ISSUE TITLE
REQUEST: GitHub Larger Runners for kubernetes-sigs/kind

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/org#4490]
### Organization or Repo

kubernetes-sigs/kind

### Name of integration

GitHub Actions (Larger Runners)

### Link to integration website
https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners

### Describe what is attempting to be accomplished

Please see:
- https://github.com/kubernetes-sigs/kind/issues/3364

> https://github.com/kubernetes-sigs/kind/blob/ac28d7fb19b4f353369d889b3900a7a9dd46f4c1/.github/workflows/cgroup2.yaml#L16-L18
> 
> The current CI uses very slow `macos-12` instances for nested virtualization, but the CI can get better performance and stability by switching it to "larger" Linux runners such as `ubuntu-latest-4-cores`: https://github.blog/changelog/2022-10-20-github-actions-larger-hosted-runners-are-now-automatically-created-for-customers/
> 
> CNCF projects have accesses to larger instances, but it has to be explicitly enabled by an admin of https://github.com/kubernetes-sigs :
> - Open https://github.com/organizations/kubernetes-sigs/settings/actions/runner-groups
> - Click `Default Larger Runners`
> - Click `Allow public repositories`
> - Click `Selected repositories`, and choose the `kind` repo
> 
>

**Comment by nikhita** [comment]
This is now enabled.

@AkihiroSuda please close the issue when you've verified.

**Comment by AkihiroSuda** [comment]
Thank you, but it doesn't seem working: https://github.com/kubernetes-sigs/kind/actions/runs/6490355625/job/17625992394?pr=3382

```
Requested labels: ubuntu-latest-4-cores
Job defined at: kubernetes-sigs/kind/.github/workflows/cgroup2.yaml@refs/pull/3382/merge
Waiting for a runner to pick up this job...
```

Could you confirm that
- `Allow public repositories` is checked
-  The `kind` repo is selected
- The status of `ubuntu-latest-4-cores` is `Ready`
![image](https://github.com/kubernetes/org/assets/9248427/6d15df21-771f-46fd-bbc3-48688d8994f3)

**Comment by Priyankasaggu11929** [comment]
Hello @AkihiroSuda, I can confirm the following two:

- Allow public repositories is checked
- The kind repo is selected

![image](https://github.com/kubernetes/org/assets/30499743/477f1be6-e17f-4eb1-8d08-7bea0ed67e9e)

But there're no runners configured atm. Let me have a chat with other GitHub Admins & update back.

**Comment by AkihiroSuda** [comment]
Thank you for taking a look.

> But there're no runners configured atm.

They should automatically show up in the “Default Larger Runners” group if the GitHub org is associated with CNCF’s enterprise account.

**Comment by Priyankasaggu11929** [comment]
Hello @AkihiroSuda, right now, the Kubernetes orgs aren't under the Enterprise account yet, we're planning to do that in the near future.

**Comment by mrbobbytables** [comment]
> associated with CNCF’s enterprise account.

Just to be clear, we are not part of the CNCFs enterprise account, we're a bit too big heh^^;;. Kubernetes has been given it's own enterprise account but we have not brought our orgs under it yet.

**Comment by BenTheElder** [comment]
Thanks, I guess we follow-up here when Kubernetes is in the enterprise account?

Is there a tracking issue we can follow? I couldn't find one with a quick search.

**Comment by saschagrunert** [comment]
Hey folks, I can see benefit in having larger runners for https://github.com/kubernetes-sigs/security-profiles-operator and maybe other projects like minikube (cc @afbjorklund). Would it be generally feasible to enable larger runners for projects being part of the `kubernetes` and `kubernetes-sigs` org?

It could be a good addition to reducing the resource usage in our prow clusters.

cc @kubernetes/release-engineering

**Comment by dims** [comment]
@saschagrunert do they need to be amd64? i am worked with a few folks to roll out in different projects including etcd - https://amperecomputing.com/blogs/ampere-computing-and-cncf-supporting-arm-native-ci-for-ncf-projects

**Comment by saschagrunert** [comment]
@dims yep only x86_64/amd64 right now.

**Comment by alexellis** [comment]
@saschagrunert how big do you need to go? Because the CNCF has sponsored actuated to provide managed Arm CI for a number of projects. The machines we have can go up to really large specs.

You can find out a bit more here:

https://actuated.dev/blog/arm-ci-cncf-ampere

One thing to note is that I see nested virt was mentioned, is that what's driving this, or are the builds too slow etc?

**Comment by BenTheElder** [comment]
> One thing to note is that I see nested virt was mentioned, is that what's driving this, or are the builds too slow etc?

For kind we need virtualization ironically so we can control kernel options (cgroups v1, cgroups v2) for testing host environments.

**Comment by saschagrunert** [comment]
@alexellis if we can choose the operating system image being used then we would not require nested virtualization. We use it for reproducibility and being able to test locally. For example we test on Fedora to utilize SELinux.

Having generally more power would be awesome, it doesn’t really matter for us if we test on x64 or arm, because both are supported.

I can also see benefits for CNCF projects like CRI-O.

**Comment by afbjorklund** [comment]
> maybe other projects like minikube

Minikube is in the process of switching from Google test infrastructure to Community test infrastructure, so it is interesting. There was some talk about it [last KubeCon EU](https://sched.co/1HyUz), and will be another update [this KubeCon NA](https://sched.co/1R2rH)...

**Comment by alexellis** [comment]
The current generation of Arm servers do not support nested virtualisation, but actuated does support nested virt with x86_64:

* [How to run KVM guests in your GitHub Actions](https://actuated.dev/blog/kvm-in-github-actions)
* [Automate Packer Images with QEMU and Actuated](https://actuated.dev/blog/automate-packer-qemu-image-builds)

x86_64 falls outside of the [Ampere/CNCF sponsorship of actuated](https://actuated.dev/blog/arm-ci-cncf-ampere), but if any of you know and speak to @caniszczyk, you may be able to make a case with him for expanding a little

Once you have nested virt, you can run VMs using whatever tooling you would like, in the blog posts we show Firecracker and KVM/qemu separately.

**Comment by saschagrunert** [comment]
@alexellis would it be possible to get actuated support for projects within the `kubernetes` and `kubernetes-sigs` orgs?

**Comment by alexellis** [comment]
Hi @saschagrunert the CNCF/Ampere sponsorship covers a certain number of Arm64 projects. Which ones did you have in mind?

**Comment by AkihiroSuda** [comment]
Standard runners now support nested virt
- https://github.com/kubernetes-sigs/kind/pull/3484
