### ISSUE TITLE
REQUEST: New membership for adikul30

### ISSUE THREAD

**Issue by adikul30** [kubernetes/org#4491]
### GitHub Username

adikul30

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@RaunakShah

### List of contributions to the Kubernetes project

List of contributions to vsphere-csi-driver repository -> https://github.com/kubernetes-sigs/vsphere-csi-driver/commits?author=adikul30

FYI, I have subscribed to the dev email-list with a registered non-primary email.

**Comment by xing-yang** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@adikul30, thank you for all your contributions so far 🙂

I've created PR #4503 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
