### ISSUE TITLE
REQUEST: New membership for <nitishfy>

### ISSUE THREAD

**Issue by nitishfy** [kubernetes/org#4494]
### GitHub Username

nitishfy

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xmudrii

### Sponsor 2

@cpanato

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/release-sdk/pull/246
- https://github.com/kubernetes-sigs/release-sdk/pull/251
- https://github.com/kubernetes-sigs/release-sdk/pull/254
- Responsible for building the Golang library for OBS under the Release Engineering Team as part of LFX mentorship.

**Comment by xmudrii** [comment]
+1 but sponsors are not needed because @nitishfy is already a member of kubernetes

**Comment by mrbobbytables** [comment]
@nitishfy please go ahead and open a PR to add yourself, just remember to use the commit message format of `Add <foo> to kubernetes-sigs org`

**Comment by nitishfy** [comment]
> @nitishfy please go ahead and open a PR to add yourself, just remember to use the commit message format of `Add <foo> to kubernetes-sigs org`

Here's the [PR](https://github.com/kubernetes/org/pull/4495)

**Comment by jasonbraganza** [comment]
Closing this issue, as @nitishfy is already added to the org via #4495.

/close
