### ISSUE TITLE
REQUEST: New membership for nrb

### ISSUE THREAD

**Issue by nrb** [kubernetes/org#4500]
### GitHub Username

@nrb

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@fabriziopandini

### Sponsor 2

@richardcase

### List of contributions to the Kubernetes project

PRs merged:
https://github.com/kubernetes-sigs/logtools/pull/3
https://github.com/kubernetes/cloud-provider-vsphere/pull/727
https://github.com/kubernetes/cloud-provider-vsphere/pull/724
https://github.com/kubernetes-csi/external-snapshotter/pull/207

Issues filed:
[2 in kubernetes-sigs](https://github.com/search?q=org%3Akubernetes-sigs+author%3Anrb&type=issues)
[1 issue in Kubernetes](https://github.com/search?q=org%3Akubernetes+author%3Anrb&type=issues)
[1 issue in kubernetes-csi](https://github.com/search?q=org%3Akubernetes-csi+author%3Anrb&type=issues)

Community interaction:
[Community discussion in kubernetes-sigs](https://github.com/search?q=org%3Akubernetes-sigs+commenter%3Anrb&type=issues)
[Community discussion in Kubernetes-csi](https://github.com/search?q=org%3Akubernetes-csi+commenter%3Anrb&type=issues)

I am also active in the Cluster API community meetings, and looking to help review PRs specifically in the cluster-api-provider-aws subproject.

**Comment by richardcase** [comment]
+1 

I echo what @fabriziopandini said. Nolan has been increasingly active in SIG cluster lifecycle and specifically Cluster API AWS, and he's expressed an interest in becoming a reviewer of the project. 

@nrb thank you for your contributions to date and your interest in the projects.

**Comment by jasonbraganza** [comment]
/assign

@nrb, thank you for all your contributions so far 🙂

I've created PR #4503 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
