### ISSUE TITLE
REQUEST: New integration for kubernetes-sigs/gcp-compute-persistent-disk-csi-driver

### ISSUE THREAD

**Issue by tyuchn** [kubernetes/org#4501]
### Organization or Repo

https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver

### Name of integration

Renovate

### Link to integration website

https://github.com/apps/renovate

### Describe what is attempting to be accomplished

Renovate is required to automate updates to Go versions, base images, and other dependencies in the `kubernetes-sigs/gcp-compute-persistent-disk-csi-driver` repository. We cannot adopt Dependabot because it cannot detect base images with special suffixes such as `-gke.x`.

**Comment by cblecker** [comment]
We don't typically allow third party applications of this type. Dependabot from GitHub does [accept PRs or bug reports](https://github.com/dependabot/dependabot-core) if there is a bug with image version detection logic.

/close
