### ISSUE TITLE
REQUEST: New membership for @Hii-Arpit

### ISSUE THREAD

**Issue by Hii-Arpit** [kubernetes/org#4508]
### GitHub Username

@Hii-Arpit

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kaslin

### Sponsor 2

@chris-short

### List of contributions to the Kubernetes project

Authored PRs:
- https://github.com/kubernetes/kubernetes/pull/119907 (Kubernetes client-go)

**SIG Projects I am Involved with:**

 **SIG Spotlight Blogs (SIG-Contribex-comms)**
- SIG CLI Spotlight Blog post: https://kubernetes.io/blog/2023/07/20/sig-cli-spotlight-2023/
-  - PR for the same Blog post: https://github.com/kubernetes/contributor-site/pull/411
- SIG Node Spotlight Blogpost (In Progress)

**Current Roles:**
- Shadow under Social Media Coordinator (@kaslin) at SIG-Contribex-comms
- - Pr for the same role: https://github.com/kubernetes/community/pull/7438
- - Link to Repo for the role, [Click Here](https://github.com/kubernetes/community/tree/master/communication/contributor-comms#:~:text=%40kaslin-,%40Hii%2DArpit%20(shadow),-Comms%20Tech%20Lead) 

**As a shadow, my contributions are listed below**
 **Non-Github Tracked Contributions**
- Helped Steering Committee Election team to draft the emails for the steering Election
- Written Posts on X(Twitter) and Mastadon regarding Steering Election, Contributor Summit NA 2023 and Kubecon
- - Below are links of some posts
- - https://twitter.com/K8sContributors/status/1694016076713963567
- - https://twitter.com/K8sContributors/status/1694024270224011392
- - https://twitter.com/K8sContributors/status/1696552792528232879
- Writing Tweets for Kuebcon Posts projects (SIG-Contribex-comms) (In-Progress)

**Comment by chris-short** [comment]
Arpit is quickly becoming a vital member of the comms and is ready to take on a more active role. The Comms team has greatly benefitted from his work. @kaslin and I both agree that it's time for @Hii-Arpit to officially join the org to help enable him to help more on behalf of the Comms team and greater Kubernetes project.

I approve Arpit's org membership and look forward to seeing where their contributor journey takes them!

**Comment by kaslin** [comment]
+1, Arpit's work was a great help for the Steering Election.
/lgtm
/approve

**Comment by palnabarun** [comment]
Hi, I have created #4542 to add you to the org(s). Once the PR merges, you will get a membership invite email.

Thank you for your contributions and Welcome to the Kubernetes org(s)! 🎉 

/assign
