### ISSUE TITLE
REQUEST: New membership for bzsuni

### ISSUE THREAD

**Issue by bzsuni** [kubernetes/org#4509]
### GitHub Username

@bzsuni

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu

### Sponsor 2

@liggitt

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pull/114420
https://github.com/kubernetes/kubernetes/pull/118689
https://github.com/kubernetes/kubernetes/pull/119054
https://github.com/kubernetes/kubernetes/pull/119495
https://github.com/kubernetes/kubernetes/pull/119988
https://github.com/kubernetes/kubernetes/pull/119989
https://github.com/kubernetes/kubernetes/pull/120194
https://github.com/kubernetes/kubernetes/pull/120852
https://github.com/kubernetes/kubernetes/pull/120925

**Comment by bzsuni** [comment]
hi @liggitt Would you consider sponsoring me?

**Comment by liggitt** [comment]
+1, thanks for the contributions

**Comment by palnabarun** [comment]
Hi, I have created #4542 to add you to the org(s). Once the PR merges, you will get a membership invite email.

Thank you for your contributions and Welcome to the Kubernetes org(s)! 🎉 

/assign
