### ISSUE TITLE
REQUEST: New membership for fiunchinho

### ISSUE THREAD

**Issue by fiunchinho** [kubernetes/org#4510]
### GitHub Username

fiunchinho

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@richardcase

### Sponsor 2

@Ankitasw

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/cluster-api/pull/3157
- https://github.com/kubernetes-sigs/cluster-api/pull/4929
- https://github.com/kubernetes-sigs/cluster-api/pull/5358
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4524
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4508
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4406
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4304
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1180
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1183
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1188
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1387
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1401
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1411
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1411
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1476
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1489
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1625
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1631
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2111
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/724
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/718
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/713
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/712
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/693
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/677
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/665
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/664

**Comment by Ankitasw** [comment]
Huge +1 from my side.
Thanks for all the contributions in CAPI/CAPA/CAPZ/CAPG 🙏 
(That's a huge list of contributions for someone who is not a member😅 )

**Comment by richardcase** [comment]
+1

Thank you @fiunchinho for all the work you do in CAPI (and its providers). And i agree with @Ankitasw thats quite a list for someone that isn't a member. Your contributions and commitement are greatly appreciated.
