### ISSUE TITLE
REQUEST: New membership for @LingyanYin

### ISSUE THREAD

**Issue by LingyanYin** [kubernetes/org#4513]
### GitHub Username

LingyanYin

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Jeffwan

### Sponsor 2

@M00nF1sh

### List of contributions to the Kubernetes project

- PRs 
- https://github.com/kubernetes/kubernetes/pull/120145
- https://github.com/kubernetes/kubernetes/pull/120432
- Issues created
- https://github.com/kubernetes/kubernetes/issues/120709
- PR/Issue involvement
- https://github.com/kubernetes/kubernetes/pull/117615#issuecomment-1731979254
- https://github.com/kubernetes/enhancements/issues/1287#issuecomment-1738222727

**Comment by Jeffwan** [comment]
+1 from my side.
Thanks for all the contributions lingyan made in sig-node in-place vpa feature 🙏 We will work together to mature this feature   in future release.

**Comment by M00nF1sh** [comment]
+1 from my side as well.
These PR and Issues are valuable contributions.

**Comment by Jeffwan** [comment]
@jasonbraganza Please have a look this issue. Thanks!

**Comment by jasonbraganza** [comment]
> @jasonbraganza Please have a look this issue. Thanks!

@Jeffwan, Membership issues are processed in batches. The request will be picked up by the current coordinator in the next upcoming set of requests :)
