### ISSUE TITLE
Usage of Github Packages / Container repository

### ISSUE THREAD

**Issue by rikatz** [kubernetes/org#4514]
### Organization or Repo

kubernetes/ingress-nginx

### Describe the issue

Hi folks 👋 

At ingress-nginx, we build a bunch of intermediate images that are used for CI, e2e tests, building another final image, etc.

I was testing Github Container Registry / GHCR and figured out it could be used with a Personal Access Token or via Actions (we use GH Actions on ingress-nginx), but the published packages are made available on Org package tab.

There are some approaches to scope the package to a repo, etc etc but before using it I would like to know:
* Can we? Our goal is to use those images just on CI/CD so 99% of its pulls are going to be from Github Actions (there is the 1% of people that may want to run the build and e2e test locally, but it doesn't happens that much)
* Is there any security concern on publishing the packages, as they appear on k org? If so, what is the desired approach?

Thanks

**Comment by rikatz** [comment]
Adding more in here: CNCF is working with [Self actuated to provide ARM runners](https://actuated.dev/blog/arm-ci-cncf-ampere). Today, one of our large build times is on ARM environments (and s390x, but this is another story) and we've been willing to make those builds fast cutting dependencies but also using better architectures.

Having a process that builds each architecture on its own "runner", pushes to ghcr and combines the layers into a single multi-arch layer seems straightforward (eg.: How [atuin](https://github.com/atuinsh/atuin/blob/main/.github/workflows/docker.yaml#L134) does) but we need a place to "push" this layers and then trigger cloudbuild to "get and push to staging", and the promotion stage layer.

**Comment by tao12345666333** [comment]
FYI https://github.com/etcd-io/etcd/pull/16801

The etcd project enables this Arm-based runner

**Comment by mrbobbytables** [comment]
My apologies for the delay in response on this issue (did respond on slack).
We looked into it and unfortunately we can't enable the github package functionality for public use.
Essentially github does not give any granual permissions over repos and which ones can be public or private. It's an all or none thing meaning anyone can create public packages or no one can. Packages also exist outside of github's regular permission system, we cannot create custom roles or anything that could better manage access. 

If/when GitHub updates it, we can revisit - but for now it's not something we're going to move forward with enabling. =/

With that I'm going to close this out, if you wish to discuss further, happy to reopen and continue. 👍 

/close

**Comment by rikatz** [comment]
Thanks for taking care of it Bob, I really appreciate it. We can followup when there is something new on this feature :)
