### ISSUE TITLE
REQUEST: New membership for sdmodi

### ISSUE THREAD

**Issue by sdmodi** [kubernetes/org#4518]
### GitHub Username

sdmodi

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

aojea

### Sponsor 2

cpanato

### List of contributions to the Kubernetes project

PRs to cloud-provider-gcp repo
https://github.com/kubernetes/cloud-provider-gcp/pulls?q=is%3Apr+author%3Asdmodi

PRs to kubernetes repo
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Asdmodi

Issues filed: 
https://github.com/kubernetes/kubernetes/issues/113492

KEPs co-authored:
https://github.com/kubernetes/enhancements/pull/2594

**Comment by aojea** [comment]
+1

**Comment by cpanato** [comment]
+1 🚀

**Comment by cpanato** [comment]
cc @mrbobbytables
