### ISSUE TITLE
REQUEST: New membership for skitt

### ISSUE THREAD

**Issue by skitt** [kubernetes/org#4520]
### GitHub Username

skitt

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jeremyot

### Sponsor 2

@pmorie

### List of contributions to the Kubernetes project

I’m involved in SIG-Multicluster; I’ve co-presented the Deep-Dive sessions for that SIG at KubeCon a few times, contribute regularly in the calls, and have contributed to the MCS API repository:

* https://github.com/kubernetes-sigs/mcs-api/pull/6
* https://github.com/kubernetes-sigs/mcs-api/pull/22
* https://github.com/kubernetes-sigs/mcs-api/pull/24
* https://github.com/kubernetes-sigs/mcs-api/pull/25
* https://github.com/kubernetes-sigs/mcs-api/pull/34
* https://github.com/kubernetes-sigs/mcs-api/pull/36

I’ve contributed a number of changes to `k/k` and `k/u`:

* Bug fixes:
  * https://github.com/kubernetes/utils/pull/286

* Dependency upgrades:
  * https://github.com/kubernetes/kubernetes/pull/108629
  * https://github.com/kubernetes/kubernetes/pull/118036

* Cleanup:
  * https://github.com/kubernetes/kubernetes/pull/114343
  * https://github.com/kubernetes/kubernetes/pull/117900
  * https://github.com/kubernetes/kubernetes/pull/118399
  * https://github.com/kubernetes/kubernetes/pull/118401
  * https://github.com/kubernetes/kubernetes/pull/118403
  * https://github.com/kubernetes/kubernetes/pull/119618
  * https://github.com/kubernetes/kubernetes/pull/120690

* Build infrastructure:
  * https://github.com/kubernetes/kubernetes/pull/114782
  * https://github.com/kubernetes/kubernetes/pull/115733

* Developer features:
  * https://github.com/kubernetes/kubernetes/pull/115685
  * https://github.com/kubernetes/kubernetes/pull/116216
  * intstr (see the extensive discussions with @thockin in https://github.com/kubernetes/kubernetes/pull/117631 and others):
      * https://github.com/kubernetes/kubernetes/pull/116665
      * https://github.com/kubernetes/kubernetes/pull/117622
      * https://github.com/kubernetes/kubernetes/pull/117623
      * https://github.com/kubernetes/kubernetes/pull/117624
      * https://github.com/kubernetes/kubernetes/pull/117625
      * https://github.com/kubernetes/kubernetes/pull/117626
      * https://github.com/kubernetes/kubernetes/pull/117627
      * https://github.com/kubernetes/kubernetes/pull/117628
      * https://github.com/kubernetes/kubernetes/pull/117629
      * https://github.com/kubernetes/kubernetes/pull/117630
      * https://github.com/kubernetes/kubernetes/pull/117631
      * https://github.com/kubernetes/kubernetes/pull/119619
  * https://github.com/kubernetes/kubernetes/pull/117416
  * ptr:
      * https://github.com/kubernetes/utils/pull/283
      * https://github.com/kubernetes/kubernetes/pull/120008
      * https://github.com/kubernetes/kubernetes/pull/120565
      * https://github.com/kubernetes/kubernetes/pull/120566
      * https://github.com/kubernetes/kubernetes/pull/120567

and opened a couple of issues (other than issues fixed by the PRs above):

* https://github.com/kubernetes/kubernetes/issues/116712
* https://github.com/kubernetes/kubernetes/issues/120022

I’ve also reviewed a few PRs:

* https://github.com/kubernetes/kubernetes/pull/115961
* https://github.com/kubernetes/kubernetes/pull/120629
* https://github.com/kubernetes/kubernetes/pull/120631
* https://github.com/kubernetes/kubernetes/pull/120699

**Comment by JeremyOT** [comment]
@skitt has been a valuable contributor to multi-cluster efforts for a while now. +1

**Comment by jasonbraganza** [comment]
ping, @pmorie. we need your approval (+1) to proceed with this request. Thank you :)

**Comment by thockin** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@skitt , thank you for all your contributions so far 🙂

I've created PR #4545 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification. (thank you @thockin for helping expedite this)

Welcome to https://github.com/kubernetes! 🎉
