### ISSUE TITLE
REQUEST: New membership for Ananya2001-an

### ISSUE THREAD

**Issue by Ananya2001-an** [kubernetes/org#4521]
### GitHub Username

Ananya2001-an

### Organization you are requesting membership in

kubernetes-client

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@roycaihw 

### Sponsor 2

@dims 

### List of contributions to the Kubernetes project

- PRs authored
https://github.com/kubernetes-client/javascript/pull/1254
https://github.com/kubernetes-client/javascript/pull/1320
https://github.com/kubernetes-client/python/pull/2122
https://github.com/kubernetes-client/python/pull/2124
https://github.com/kubernetes-client/python/pull/2128
https://github.com/kubernetes/website/pull/43115

- Issues raised
https://github.com/kubernetes-client/javascript/issues/1253
https://github.com/kubernetes-client/java/issues/2786

- Issues responded to
https://github.com/kubernetes-client/python/issues/2133

**Comment by yliaog** [comment]
+1

thanks for the contributions to k8s

**Comment by palnabarun** [comment]
Hi @Ananya2001-an, your sponsors need to be from different companies. Can you please ask someone from a different company to sponsor your membership?

**Comment by Ananya2001-an** [comment]
Hi @palnabarun I am not sure what do u mean by different companies here?

**Comment by Ananya2001-an** [comment]
Hey @brendandburns can u sponsor me?

**Comment by jasonbraganza** [comment]
ping @brendandburns, a “+1” from you, will help expedite this request. thank you :)

**Comment by Ananya2001-an** [comment]
polite ping @brendandburns

**Comment by dims** [comment]
@palnabarun i am happy to sponsor @Ananya2001-an 

@Ananya2001-an Nabarun was talking about how @yliaog and @roycaihw are both from google, you needed at least one from a different company from Google.

**Comment by Ananya2001-an** [comment]
Thank you so much @dims :)

**Comment by ydFu** [comment]
@Ananya2001-an 
I want to express my heartfelt gratitude for your invaluable contributions to community endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #4569 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes family! 🎉🚀

Best regards,

**Comment by Ananya2001-an** [comment]
Thanks @ydFu I am excited to join the organization too!
