### ISSUE TITLE
REQUEST: New membership for sudermanjr

### ISSUE THREAD

**Issue by sudermanjr** [kubernetes/org#4523]
### GitHub Username

@sudermanjr

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@JimBugwadia

### Sponsor 2

@rficcaglia

### List of contributions to the Kubernetes project

- Active member of wg-policy
- Co-author of GRC whitepaper published by wg-policy [PR](https://github.com/kubernetes/sig-security/pull/94)
- Sponsors are mentioned here: https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/OWNERS
- https://github.com/kubernetes/website/pull/40969
- Chosen as co-chair of WG Policy - https://github.com/kubernetes/community/pull/7643
- Continuous participation in WG Policy - https://docs.google.com/document/d/1IjEOvgqQ0ErEEj85z5iWyFP_TK74gmFf2VJZlMoJbqk/edit
- Additional context - https://docs.google.com/document/d/1IjEOvgqQ0ErEEj85z5iWyFP_TK74gmFf2VJZlMoJbqk/edit

I have participated in many different Kubernetes related repositories and projects throughout the years, but here's a few more recent examples:

Goldilocks work with VPA project, where we occasionally work to support issues between the two.
- https://github.com/kubernetes/autoscaler/issues/5836

**Comment by sudermanjr** [comment]
@mrbobbytables Are you specifically referring to the Helm contributions?

**Comment by mrbobbytables** [comment]
Yes, but in addition to that there needs to be significant ongoing contributions to K8s itself to become an org member.

**Comment by JimBugwadia** [comment]
Andy has been an active contributor to the Policy WG and has worked on several initiatives including building the policy report API, writing papers, and policy and governance, and updating the Kubernetes docs.

The WG meeting & activity tracker is available at: 

https://docs.google.com/document/d/1ihFfEfgViKlUMbY2NKxaJzBkgHh-Phk5hqKTzK-NEEs/edit#heading=h.u0h5x9jz9d3r.

I am happy to support Andy's nomination as co-chair and am looking forward to continuing to work together to help secure and scale Kubernetes.

**Comment by mrbobbytables** [comment]
I'll +1 as a sponsor. I've been working with @JimBugwadia and @rficcaglia to get things sorted out for wg-policy. 👍

**Comment by rficcaglia** [comment]
+1 on Andy as a contributor to the WG content both in the wg repo and IRL @ KubeCon at the contributor summit wg-policy session.
