### ISSUE TITLE
REQUEST: New membership for yuji-watanabe-jp

### ISSUE THREAD

**Issue by yuji-watanabe-jp** [kubernetes/org#4524]
### GitHub Username

@yuji-watanabe-jp

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@JimBugwadia

### Sponsor 2

@rficcaglia

### List of contributions to the Kubernetes project

- Kubernetes Policy Working Group
   - [Kubernetes GRC paper](https://github.com/kubernetes/sig-security/blob/main/sig-security-docs/papers/policy_grc/Kubernetes_Policy_WG_Paper_v1_101123.pdf)
   - demo at policy working group call (Feb 15, 2023) - demo on the bridging of compliance (eg Kubernetes CIS Benchmarks or NIST 800-53) into the Kubernetes policy

**Comment by jasonbraganza** [comment]
[Community Membership Guidlines](https://github.com/kubernetes/community/blob/master/community-membership.md#inactive-members) require continuously active contributors with multiple contributions to the project proper. This request currently does not meet these requirements with the data given.

Would you please link to upstream work? List of orgs, considered for this request can be found [here](https://github.com/kubernetes/community/blob/master/github-management/README.md#actively-used-github-organizations)

**Comment by Priyankasaggu11929** [comment]
Hey, it's been more than a month since the issue was opened.

I'll close it for now, but feel free to reopen or start a new issue once the requirements are met.

/close
