### ISSUE TITLE
REQUEST: New membership for bwagner5

### ISSUE THREAD

**Issue by bwagner5** [kubernetes/org#4527]
### GitHub Username

@bwagner5

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dims

### Sponsor 2

@olemarkus

### List of contributions to the Kubernetes project

PRs:
https://github.com/kubernetes/kops/pulls?q=is%3Apr+author%3Abwagner5+is%3Aclosed+

Reviews:
https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+is%3Aclosed+bwagner5

Issues:
https://github.com/kubernetes/kops/issues?q=is%3Aissue+is%3Aclosed+bwagner5

SIGs:
sig-autoscaling WG on Karpenter

**Comment by dims** [comment]
+1 from me!

**Comment by olemarkus** [comment]
Huge +1 from me!

**Comment by palnabarun** [comment]
Hi, I have created #4542 to add you to the org(s). Once the PR merges, you will get a membership invite email.

Thank you for your contributions and Welcome to the Kubernetes org(s)! 🎉 

/assign
