### ISSUE TITLE
REQUEST: New membership for musaprg

### ISSUE THREAD

**Issue by musaprg** [kubernetes/org#4528]
### GitHub Username

@musaprg

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@killianmuldoon

### Sponsor 2

@enxebre

### List of contributions to the Kubernetes project

- PRs authored
  - https://github.com/kubernetes/website/pull/37008
  - https://github.com/kubernetes-sigs/cluster-api/pull/7189
  - https://github.com/kubernetes-sigs/cluster-api/pull/7583
  - https://github.com/kubernetes-sigs/cluster-api/pull/8678
  - https://github.com/kubernetes-sigs/cluster-api/pull/9512
  - https://github.com/kubernetes-sigs/cluster-api/pull/9513
- Issues authored
  - https://github.com/kubernetes-sigs/cluster-api/issues/7796
- Issues responded to
  - https://github.com/kubernetes/examples/issues/447
  - https://github.com/kubernetes/kubernetes/issues/113072
  - https://github.com/kubernetes-sigs/cluster-api/issues/8097
  - https://github.com/kubernetes-sigs/cluster-api/issues/8395
  - https://github.com/kubernetes-sigs/cluster-api/issues/8425
  - https://github.com/kubernetes-sigs/cluster-api/issues/8670
- Examples prepared for PRs
  - https://github.com/musaprg/cluster-api-kubelet-config-examples

**Comment by enxebre** [comment]
+1

**Comment by killianmuldoon** [comment]
+1

**Comment by palnabarun** [comment]
Hi, I have created #4542 to add you to the org(s). Once the PR merges, you will get a membership invite email.

Thank you for your contributions and Welcome to the Kubernetes org(s)! 🎉 

/assign
