### ISSUE TITLE
REQUEST: New membership for daminisatya

### ISSUE THREAD

**Issue by daminisatya** [kubernetes/org#453]
### GitHub Username

daminisatya

### Organization you are requesting membership in

kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@Rajakavitha1 
@zacharysarah 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   [kubernetes/website#12516](https://github.com/kubernetes/website/pull/12516)
   [kubernetes/website#12470](https://github.com/kubernetes/website/pull/12470)
   [kubernetes/website#12461](https://github.com/kubernetes/website/pull/12461)
   [kubernetes/website#12460](https://github.com/kubernetes/website/pull/12460)
   [kubernetes/website#12454](https://github.com/kubernetes/website/pull/12454)
   [kubernetes/website#12435](https://github.com/kubernetes/website/pull/12435)
   [kubernetes/website#12518](https://github.com/kubernetes/website/pull/12518) 
   [kubernetes/website#12509](https://github.com/kubernetes/website/pull/12509) 
   [kubernetes/website#12507](https://github.com/kubernetes/website/pull/12507)
   [kubernetes/website#12490](https://github.com/kubernetes/website/pull/12490)
   [kubernetes/website#12486](https://github.com/kubernetes/website/pull/12486)
   [kubernetes/website#12476](https://github.com/kubernetes/website/pull/12476)
   [kubernetes/website#12446](https://github.com/kubernetes/website/pull/12446)
   [kubernetes/website#12523](https://github.com/kubernetes/website/pull/12523)

   [kubernetes/dashboard#3544](https://github.com/kubernetes/website/pull/3544)

- Issues responded to

   [kubernetes/website#12506](https://github.com/kubernetes/website/pull/12506)
   [kubernetes/website#12436](https://github.com/kubernetes/website/pull/12436)
   [kubernetes/website#12434](https://github.com/kubernetes/website/pull/12434)

**Comment by nikhita** [comment]
+1 from me as well! :heart:

**Comment by mrbobbytables** [comment]
Hey there @daminisatya, thank you for all your contributions so far :)

I've created PR #454 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
