### ISSUE TITLE
REQUEST: New membership for siyuanfoundation

### ISSUE THREAD

**Issue by siyuanfoundation** [kubernetes/org#4530]
### GitHub Username

@siyuanfoundation

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@logicalhan

### Sponsor 2

@ahrtr

### List of contributions to the Kubernetes project

- PRs to etcd repo
https://github.com/etcd-io/etcd/pulls?q=is%3Apr+author%3Asiyuanfoundation

- PRs to kubernetes repo
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Asiyuanfoundation

**Comment by logicalhan** [comment]
/lgtm

Thanks for the contributions!!

**Comment by palnabarun** [comment]
Hi, I have created #4542 to add you to the org(s). Once the PR merges, you will get a membership invite email.

Thank you for your contributions and Welcome to the Kubernetes org(s)! 🎉 

/assign
