### ISSUE TITLE
REQUEST: New membership for DamianSawicki

### ISSUE THREAD

**Issue by DamianSawicki** [kubernetes/org#4532]
### GitHub Username

@DamianSawicki

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@aojea

### Sponsor 2

@sttts

### List of contributions to the Kubernetes project

I have mostly contributed to `ingress-gce` (l7 health checks), with individual contributions to `cloud-provider-gcp` and `kubernetes/kubernetes`: [my PRs](https://github.com/pulls?q=is%3Apr+author%3ADamianSawicki+archived%3Afalse+user%3Akubernetes+user%3Akubernetes-sigs+is%3Aclosed).

**Comment by aojea** [comment]
+1 
looking forward for more contributions Damian

**Comment by sttts** [comment]
+1 
Plenty of contributions to the kube org already. About time to become a member 👍

**Comment by palnabarun** [comment]
Hi, I have created #4542 to add you to the org(s). Once the PR merges, you will get a membership invite email.

Thank you for your contributions and Welcome to the Kubernetes org(s)! 🎉 

/assign
