### ISSUE TITLE
REQUEST: New membership for ty-dc

### ISSUE THREAD

**Issue by ty-dc** [kubernetes/org#4539]
### GitHub Username

ty-dc

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu

### Sponsor 2

@thockin @aojea 

### List of contributions to the Kubernetes project

I mainly working on test related tasks, including adding some UTs.
- I work as a QA in [spidepool](https://github.com/spidernet-io/spiderpool)(applying for CNCF Sandbox) project that allows multiple CNIs  to collaborate effectively.

https://github.com/kubernetes/kubernetes/pull/120397
https://github.com/kubernetes/kubernetes/pull/119959
https://github.com/kubernetes/kubernetes/pull/119705
https://github.com/kubernetes/kubernetes/pull/119033
https://github.com/kubernetes/kubernetes/pull/118709
https://github.com/kubernetes/kubernetes/pull/118061
https://github.com/kubernetes/website/pull/41040
https://github.com/kubernetes/kubernetes/pull/119034

**Comment by aojea** [comment]
+1 looking forward for more contributions

**Comment by pacoxu** [comment]
+1
hoping your more contributions in network and testing

**Comment by palnabarun** [comment]
Hi, I have created #4542 to add you to the org(s). Once the PR merges, you will get a membership invite email.

Thank you for your contributions and Welcome to the Kubernetes org(s)! 🎉 

/assign
