### ISSUE TITLE
REQUEST: New membership for stuton

### ISSUE THREAD

**Issue by stuton** [kubernetes/org#4543]
### GitHub Username

@stuton

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@trasc

### Sponsor 2

@mimowo

### List of contributions to the Kubernetes project

PRs authored:
kubernetes-sigs/kueue#1069
kubernetes-sigs/kueue#1168
kubernetes-sigs/kueue#1220
kubernetes-sigs/kueue#1139
kubernetes-sigs/kueue#1044
kubernetes-sigs/kueue#1035
kubernetes-sigs/kueue#1014
kubernetes-sigs/kueue#1003
kubernetes-sigs/kueue#979
kubernetes-sigs/kueue#978
kubernetes-sigs/kueue#948
kubernetes-sigs/kueue#943
kubernetes-sigs/kueue#928
kubernetes-sigs/kueue#925

kubernetes/kubernetes#121302
kubernetes/kubernetes#121300

Issues created:
kubernetes-sigs/kueue#1034
kubernetes-sigs/kueue#983
kubernetes-sigs/kueue#927
kubernetes-sigs/kueue#926
kubernetes-sigs/kueue#924
kubernetes-sigs/kueue#877

**Comment by trasc** [comment]
+1

Thank you for all your work so far.

**Comment by mimowo** [comment]
👍 from me. Thank you!

**Comment by alculquicondor** [comment]
+1 thanks for your contributions!

**Comment by tenzen-y** [comment]
+1 Thank you!

**Comment by jasonbraganza** [comment]
/assign

@stuton, thank you for all your contributions so far 🙂

I've created PR #4544 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to https://github.com/kubernetes! 🎉
