### ISSUE TITLE
REQUEST: New membership for achernevskii

### ISSUE THREAD

**Issue by achernevskii** [kubernetes/org#4547]
### GitHub Username

@achernevskii

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@trasc

### Sponsor 2

@alculquicondor

### List of contributions to the Kubernetes project

PRs authored:
https://github.com/kubernetes-sigs/kueue/pull/1032
https://github.com/kubernetes-sigs/kueue/pull/1042
https://github.com/kubernetes-sigs/kueue/pull/1072
https://github.com/kubernetes-sigs/kueue/pull/1103
https://github.com/kubernetes-sigs/kueue/pull/1177
https://github.com/kubernetes-sigs/kueue/pull/1247

Issues responded to:
https://github.com/kubernetes-sigs/kueue/issues/1027
https://github.com/kubernetes-sigs/kueue/issues/992
https://github.com/kubernetes-sigs/kueue/issues/976

**Comment by trasc** [comment]
+1

**Comment by alculquicondor** [comment]
+1
Thanks for all your contributions!

**Comment by jasonbraganza** [comment]
@trasc, @alculquicondor, would you folk please update your profiles or reply on this issue, with your employers?
I’m asking because the sponsors need to be from different companies.
It’ll help me process this quicker. Thank you :)

**Comment by trasc** [comment]
I'm from Epam.

**Comment by alculquicondor** [comment]
Updated. I'm from Google.

**Comment by jasonbraganza** [comment]
Thank you both! :)

**Comment by jasonbraganza** [comment]
/assign

@achernevskii, thank you for all your contributions so far 🙂

I've created PR #4555 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to https://github.com/kubernetes! 🎉
