### ISSUE TITLE
REQUEST: Create kubernetes-sigs/obscli

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/org#4550]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

obscli

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

cpanato jeremyrickard justaugustus puerco saschagrunert Verolop

### Who should have write access?

cpanato jeremyrickard justaugustus puerco saschagrunert Verolop

### Who should be listed as approvers in OWNERS?

release-managers

### Who should be listed in SECURITY_CONTACTS?

cpanato jeremyrickard justaugustus puerco saschagrunert Verolop

### What should the repo description be?

Command-line interface for managing OpenBuildService (OBS) assets

### What SIG and subproject does this fall under?

sig-release

### Please provide references to appropriate approval for this new repo

@kubernetes/sig-release-leads to approve this request in a written form on this issue

### Additional context for request

This repository is needed to continue our efforts of completely migrating to the new packages infrastructure hosted at pkgs.k8s.io. This tool is supposed to be something similar to our existing tools like Peribolos, Slack management, i.e. offer options to configure the OpenBuildService assets needed for the project in a declarative and automated way.

**Comment by professorabhay** [comment]
Hey @xmudrii , Is that issue open for all or for internals ? 
I mean that anyone can contribute the it !

**Comment by xmudrii** [comment]
@professorabhay AFAIK, this needs to be taken care of GitHub Admins and SIG Release leads because of required permissions. We're still discussing with SIG Release leads how exactly we want to proceed with this request

**Comment by professorabhay** [comment]
Thanks,@xmudrii for the clarification.

**Comment by nitishfy** [comment]
cc: @kubernetes/sig-release-leads @Priyankasaggu11929

**Comment by xmudrii** [comment]
We discussed this privately and decided to rename the project to `obscli` because `paketo` already exists. @kubernetes/sig-release-leads This request is now ready for review.

**Comment by saschagrunert** [comment]
+1 I'm happy to approve this one.

**Comment by Priyankasaggu11929** [comment]
Thanks for the +1s. 

I'll go ahead with creating this repository.

/assign

@xmudrii, the requested new repo will be part of which [subproject](https://github.com/kubernetes/community/tree/master/sig-release#subprojects) of sig-release? [Release Engineering](https://github.com/kubernetes/community/tree/master/sig-release#release-engineering)?

**Comment by Priyankasaggu11929** [comment]
The repo has been created: https://github.com/kubernetes-sigs/obscli 🎉

Created the following PR to add GitHub teams for the new repo:

- https://github.com/kubernetes/org/pull/4647

will wait for input on the subproject name https://github.com/kubernetes/org/issues/4550#issuecomment-1874932276 and then create another PR to add subproject documentation. Thanks!

**Comment by xmudrii** [comment]
> the requested new repo will be part of which [subproject](https://github.com/kubernetes/community/tree/master/sig-release#subprojects) of sig-release? [Release Engineering](https://github.com/kubernetes/community/tree/master/sig-release#release-engineering)?

@Priyankasaggu11929 Yes, this repository is part of the Release Engineering subproject

**Comment by Priyankasaggu11929** [comment]
PR to document new repo to k/community - https://github.com/kubernetes/community/pull/7665

**Comment by Priyankasaggu11929** [comment]
All PRs are merged. The new repo is setup now.

Closing the issue.

/close
