### ISSUE TITLE
REQUEST: New membership for @mstruebing

### ISSUE THREAD

**Issue by mstruebing** [kubernetes/org#4552]
### GitHub Username

@mstruebing

### Organization you are requesting membership in

kubernetes-client

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@brendandburns

### Sponsor 2

@jimmidyson 

### List of contributions to the Kubernetes project

Created PRs:
- https://github.com/kubernetes-client/javascript/pull/729
- https://github.com/kubernetes-client/javascript/pull/1019
- https://github.com/kubernetes-client/javascript/pull/1023
- https://github.com/kubernetes-client/javascript/pull/1037
- https://github.com/kubernetes-client/javascript/pull/1038
- https://github.com/kubernetes-client/javascript/pull/1044
- https://github.com/kubernetes-client/javascript/pull/1127
- https://github.com/kubernetes-client/javascript/pull/1313
- https://github.com/kubernetes-client/javascript/pull/1314

Additionally, I've reviewed PRs and answered issues 

Note:
I've hit the checkbox `I have two sponsors that meet the sponsor requirements listed in the community membership guidelines *`  and added a second sponsor I do not have "none" as I wasn't able to submit this issue otherwise.

**Comment by Priyankasaggu11929** [comment]
Thanks for creating the issue @mstruebing. Actually, we do need 2 sponsors to move ahead with the org membership.

Could you please find another sponsor per the sponsor requirements listed [here](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) and add them in the issue description.

Following +1s from both your sponsors, one of the New Membership Coordinator will review and process this request in the upcoming batch of membership requests.

**Comment by brendandburns** [comment]
+1 for @mstruebing 

@Priyankasaggu11929 one of the challenges with the client repos is that there are not a lot of community developers in those repos.

We could ask someone from one of the other repos (e.g. @roycaihw) but the truth is that they don't have much experience with the javascript repo.

Thoughts?

**Comment by Priyankasaggu11929** [comment]
Hello @brendandburns, for org membership requirements, the other sponsor doesn't necessarily need to be from the javascript client repo only.

Folks from the wider Kubernetes project who has worked with @mstruebing and is willing to sponsor org membership, that should be fine (as long as the 2 sponsors are from different org/company and listed as approver/reviewer).

**Comment by mstruebing** [comment]
Hey @Priyankasaggu11929 I've found a second person who meets the criteria and is willing to sponsor me, @jimmidyson
I've edited the original issue.

**Comment by jimmidyson** [comment]
+1 for @mstruebing!

**Comment by Priyankasaggu11929** [comment]
Thanks @mstruebing.

cc: @jasonbraganza (NMC) for processing the request. Thanks!

**Comment by jasonbraganza** [comment]
/assign

@mstruebing, thank you for all your contributions! 🙂

I've created PR #4557 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
