### ISSUE TITLE
REQUEST: New membership for jklaw90

### ISSUE THREAD

**Issue by jklaw90** [kubernetes/org#4554]
### GitHub Username

@jklaw90

### Organization you are requesting membership in

kubernetes
kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@a7i

### Sponsor 2

@knelasevero

### List of contributions to the Kubernetes project

Sig Projects: https://github.com/kubernetes-sigs/descheduler
PR: https://github.com/kubernetes-sigs/descheduler/pulls?q=is%3Apr+author%3Ajklaw90+
Issues: https://github.com/kubernetes-sigs/descheduler/issues?q=is%3Aissue+author%3Ajklaw90+

**Comment by a7i** [comment]
+1

thank you for your contribution!

**Comment by jasonbraganza** [comment]
ping, @knelasevero. a +1 would help us expedite the request. Thank you :)

**Comment by knelasevero** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@jklaw90, thank you for all your contributions so far 🙂

I've created PR #4556 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to https://github.com/kubernetes! 🎉
