### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for sflxn

### ISSUE THREAD

**Issue by sflxn** [kubernetes/org#456]
### GitHub Username
sflxn

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
I am already a member of kubernetes and for the last 7 months have been involved with both https://github.com/kubernetes-sigs/cluster-api and
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere

**Comment by mrbobbytables** [comment]
@sflxn I've created PR #463 to add you to @kubernetes-sigs. Once that gets merged, you should get a membership invite notification. :)

/assign
