### ISSUE TITLE
REQUEST: New membership for dejanzele

### ISSUE THREAD

**Issue by dejanzele** [kubernetes/org#4561]
### GitHub Username

dejanzele

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kannon92

### Sponsor 2

@alculquicondor

### List of contributions to the Kubernetes project

- sig-apps
- kubernetes PR - https://github.com/kubernetes/kubernetes/pull/121491
- kubernetes PR - https://github.com/kubernetes/kubernetes/pull/121481
- kubernetes PR - https://github.com/kubernetes/kubernetes/pull/121342
- kubernetes PR - https://github.com/kubernetes/kubernetes/pull/121274
- kubernetes PR - https://github.com/kubernetes/kubernetes/pull/120206
- kubernetes PR - https://github.com/kubernetes/kubernetes/pull/119877
- enhancements PR - https://github.com/kubernetes/enhancements/pull/4316
- KEP - https://github.com/kubernetes/enhancements/issues/3939

**Comment by kannon92** [comment]
+1 for this. @dejanzele has lead the beta promotion for PodReplacementPolicy and has been a very active contributor.  He is interested in continuing to contribute to Kubernetes.

**Comment by ydFu** [comment]
@davidgamero 
I want to express my heartfelt gratitude for your invaluable contributions to community endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #4569 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes family! 🎉🚀

Best regards,

**Comment by dejanzele** [comment]
Thanks @kannon92 and @alculquicondor for sponsoring me, and thanks @ydFu for welcoming me to the community!
