### ISSUE TITLE
REQUEST: New membership for jonathan-innis

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes/org#4571]
### GitHub Username

jonathan-innis

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tzneal

### Sponsor 2

@jackfrancis

### List of contributions to the Kubernetes project

__aws/karpenter-core__
Actively involved in the Karpenter project that has been approved to join SIG Autoscaling and move into the `kubernetes-sigs/karpenter` repo. Tracking request here: https://github.com/kubernetes/org/issues/4258. Given the approval of this repo to be in the sub-project, I'm requesting org membership ahead of the repo move to be able to have org permission and exist in the OWNERS file.

__kubernetes-sigs/controller-runtime__
Discussion over some questions and issues

- https://github.com/kubernetes-sigs/controller-runtime/issues/2112
- https://github.com/kubernetes-sigs/controller-runtime/issues/2220

Active in SIG Autoscaling and driving design docs and discussion around SIG Autoscaling and Karpenter Alignment: https://docs.google.com/document/d/1rHhltfLV5V1kcnKr_mKRKDC4ZFPYGP4Tde2Zy-LE72w/edit

**Comment by jonathan-innis** [comment]
cc: @tzneal, @jackfrancis

**Comment by jackfrancis** [comment]
Jonathan has a been a critical part of the effort to bring the karpenter project (https://github.com/aws/karpenter-core) into SIG Autoscaling.

Big +1 from me

**Comment by dims** [comment]
+1 from me!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4584  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉
