### ISSUE TITLE
REQUEST: New membership for njtran

### ISSUE THREAD

**Issue by njtran** [kubernetes/org#4574]
### GitHub Username

njtran

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tzneal

### Sponsor 2

@gjtempleton

### List of contributions to the Kubernetes project

Actively maintaining the Karpenter project, which has been [approved](https://github.com/kubernetes/org/issues/4258) to join SIG Autoscaling and migrated to `kubernetes-sigs/karpenter`. Given the approval for Karpenter to move under the `kubernetes-sigs` I'm requesting org membership to `kubernetes` and `kubernetes-sigs` ahead of this migration to be able to have org permission and exist as a member of the OWNERS file. 

Some Karpenter contributions: 
- https://github.com/aws/karpenter-core/pull/508
- https://github.com/aws/karpenter-core/pull/472

In discussion for SIG Autoscaling and Karpenter Alignment: https://docs.google.com/document/d/1rHhltfLV5V1kcnKr_mKRKDC4ZFPYGP4Tde2Zy-LE72w/edit

**Comment by njtran** [comment]
@tzneal @gjtempleton

**Comment by tzneal** [comment]
+1 from me, Nick has worked on Karpenter for several years including consolidation performance improvements and node drift among other things.

**Comment by jackfrancis** [comment]
+1, Nick has demonstrated high quality open source habits in both the aws/karpenter-core and aws/karpenter (AWS provider) projects.

**Comment by gjtempleton** [comment]
+1, even before adoption of karpenter was agreed, Nick's been working to ensure shared learnings between the karpenter project and those under SIG Autoscaling. As others have already noted, he's implemented significant pieces of work for the to be adopted karpenter-core itself.

**Comment by dims** [comment]
+1 from me!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4584  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉
