### ISSUE TITLE
REQUEST: New membership for aj11anuj

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/org#4576]
### GitHub Username

@aj11anuj

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dipesh-rawat

### Sponsor 2

@windsonsea

### List of contributions to the Kubernetes project

Contributed to kubernetes/website, kubernetes/community, kubernetes/contributor-site, kubernetes/minikube, kubernetes/sig-release and kubernetes-sigs/prow repository.

- Issues raised 35+ related to website, localization, blog, docs and cmds.
(Some of the notable ones are [#43147](https://github.com/kubernetes/website/issues/43147), [#42961](https://github.com/kubernetes/website/issues/42961), [#43317](https://github.com/kubernetes/website/issues/43317), [#42861](https://github.com/kubernetes/website/issues/42861))
- PR's opened 15+ related to docs, typo and localization.
(Some of the notable ones are [#43225](https://github.com/kubernetes/website/pull/43225), [#43242](https://github.com/kubernetes/website/pull/43242), [#43043](https://github.com/kubernetes/website/pull/43043), [#43044](https://github.com/kubernetes/website/pull/43044))
- PR's reviewed 80+ related to docs, localization, website, blog, typo and minor fixes.
- Bug triage and involvement in several issues and PR.
(Devstats score: [[Rank 4th](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=v1.28.0%20-%20now&var-metric=contributions&var-repogroup_name=SIG%20Docs&var-repo_name=kubernetes%2Fwebsite&var-country_name=All) in SIG Docs kubernetes/website repo 1.28-now], [[Rank 30th](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=v1.28.0%20-%20now&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes&var-country_name=All) in overall k8s 1.28-now])
- Active in K8s community and on meeting calls of SIG-Docs.

**Comment by windsonsea** [comment]
+1

Look forward to your more contributions.

**Comment by dipesh-rawat** [comment]
+1 for me.
Thank you for all your contributions from localization to issues management, reviews and more! 
Look forward to even more from you in the future. 🚀

/pony party

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4584  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉
