### ISSUE TITLE
REQUEST: New membership for mloiseleur

### ISSUE THREAD

**Issue by mloiseleur** [kubernetes/org#4579]
### GitHub Username

mloiseleur

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Raffo

### Sponsor 2

@szuecs

### List of contributions to the Kubernetes project

PR authored:
- https://github.com/kubernetes-sigs/external-dns/pull/3922
- https://github.com/kubernetes-sigs/external-dns/pull/3870
- https://github.com/kubernetes-sigs/external-dns/pull/3673
- https://github.com/kubernetes-sigs/external-dns/pull/3697
- https://github.com/kubernetes-sigs/external-dns/pull/3991
- https://github.com/kubernetes-sigs/external-dns/pull/3829
- https://github.com/kubernetes-sigs/external-dns/pull/3968
- https://github.com/kubernetes-sigs/external-dns/pull/3824

PR reviewed:
- 52 [already merged](https://github.com/kubernetes-sigs/external-dns/issues?q=is%3Apr+assignee%3Amloiseleur+is%3Aclosed)
- 17 [waiting for approval, corrections or rebase](https://github.com/kubernetes-sigs/external-dns/issues?q=is%3Apr+assignee%3Amloiseleur+is%3Aopen)

**Comment by szuecs** [comment]
/approve 
/lgtm

Whatever I need to support here, @mloiseleur helps us a lot 😊

**Comment by Raffo** [comment]
+1 from me.

**Comment by mloiseleur** [comment]
Here is my [Inclusive Open Source Community Orientation certification](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/fd72b4f5-f4f8-4cdf-9919-9303f4d38e22-michel-loiseleur-f8a0ecca-a473-4e00-b73d-9f659bb6f9fa-certificate.pdf)

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4584  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉
