### ISSUE TITLE
REQUEST: New membership for Shashi Kanth M

### ISSUE THREAD

**Issue by mskanth972** [kubernetes/org#4581]
### GitHub Username

mskanth972

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

Ashley-wenyizha

### Sponsor 2

wongma7

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1026
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1158
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1109
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1102
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1101
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1080
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1059
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1058
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1057
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1038
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1037
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1036
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1031
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1029
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1012
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1010
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1007
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/966
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/965
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/942

**Comment by Ashley-wenyizha** [comment]
As the one of the current maintainers of EFS CSI driver, I support this request from @mskanth972 as a new member 

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/OWNERS

**Comment by jacobwolfaws** [comment]
@wongma7 is also part of AWS, I believe you'll need a non-AWS sponsor

**Comment by mrbobbytables** [comment]
@mskanth972 @jacobwolfaws is correct, do you have another non-aws sponsor by chance?

**Comment by jasonbraganza** [comment]
@d-nishi, I couldn’t find your org from a cursory search. would you kindly update your profile with the organisation you work for? or please comment here on the issue?
it’ll help me process this quicker. thank you :)

**Comment by d-nishi** [comment]
@jasonbraganza I am starting my own company Sidecloud LLC (stealth). I was SIG AWS lead, started this project, and was recently employed by Cruise.

To simplify, I am adding @leakingtapan from Cruise to do a LGTM as well. I will update my org details.

**Comment by leakingtapan** [comment]
LGTM

**Comment by MadhavJivrajani** [comment]
Awesome! 
Thanks folks for the clarification ❤️

**Comment by jasonbraganza** [comment]
@d-nishi as long as you’re different organisationally from the other sponsor at the time of the request, we’re good :)
Thank you and @leakingtapan for helping out :)

**Comment by jasonbraganza** [comment]
@mskanth972, you already are a member of the kubernetes-sigs org. 

https://github.com/kubernetes/org/blob/aa419a59f73db4073b6905511335894f70dfe45b/config/kubernetes-sigs/org.yaml#L708

is there anything else, I could help you with?
