### ISSUE TITLE
REQUEST: New membership for  adilGhaffarDev

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes/org#4582]
### GitHub Username

adilGhaffarDev

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@furkatgofurov7

### Sponsor 2

@killianmuldoon

### List of contributions to the Kubernetes project

PRs authored:
- https://github.com/kubernetes/kubernetes/pull/120731
- https://github.com/kubernetes/test-infra/pull/30534
- https://github.com/kubernetes-sigs/cluster-api/pull/8758
- https://github.com/kubernetes/kubernetes/pull/118045
- https://github.com/kubernetes/kubernetes/pull/117502
- https://github.com/kubernetes-sigs/cluster-api/pull/7039
- https://github.com/kubernetes-sigs/cluster-api/pull/6646

**Comment by killianmuldoon** [comment]
+1

Thanks for all your contributions!

**Comment by furkatgofurov7** [comment]
+1

Thank you @adilGhaffarDev for your all contributions!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4584  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to Kubernetes! 🎉
