### ISSUE TITLE
REQUEST: New membership for asm582

### ISSUE THREAD

**Issue by asm582** [kubernetes/org#4594]
### GitHub Username

asm582

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mikebrow 

### Sponsor 2

Huang-Wei

### List of contributions to the Kubernetes project

- Opened issues on batchv1 job API, Cluster autoscaling, dra-driver, and the co-scheduler.
   https://github.com/kubernetes/kubernetes/issues/121987, https://github.com/kubernetes/autoscaler/issues/5170, https://github.com/kubernetes/kubernetes/issues/111948, https://github.com/kubernetes-sigs/scheduler-plugins/issues/575, https://github.com/kubernetes-sigs/scheduler-plugins/issues/416, https://github.com/kubernetes-sigs/scheduler-plugins/issues/420, https://github.com/kubernetes-sigs/scheduler-plugins/issues/444
- PRs merged to clusterloader2 project that extracts metrics from the secondary scheduler.
  https://github.com/kubernetes/perf-tests/pull/2010
- Member of batch-wg, CNCF-batch-wg, and DRA project.

**Comment by Huang-Wei** [comment]
+1

**Comment by jasonbraganza** [comment]
ping @soltysh, a +1 would help me process this membership request. thank you :)

**Comment by jasonbraganza** [comment]
Hello, it's been more than a month since the issue was opened.

I'll close it for now, but feel free to reopen or start a new issue once the requirements are met.

/close

**Comment by mikebrow** [comment]
+1 
Abhishek is working on DRA back in IBM Research has been working on Scheduler and I support his membership.

**Comment by jasonbraganza** [comment]
/assign

@asm582, thank you for all your contributions. Looking forward to more contributions in the future 🙂

I’ve created PR #4788 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
