### ISSUE TITLE
REQUEST: New membership for engedaam

### ISSUE THREAD

**Issue by engedaam** [kubernetes/org#4595]
### GitHub Username

@engedaam

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tzneal

### Sponsor 2

@gjtempleton

### List of contributions to the Kubernetes project

I am currently involved Karpenter project which has been approved to join SIG Autoscaling and is migrating to kubernetes-sigs/karpenter (https://github.com/kubernetes/org/issues/4258). I'm requesting org membership to kubernetes and kubernetes-sigs ahead of this migration to have org permissions and exist as a member of the OWNERS file.

Contributions (aws/karpenter-core):
- [Authored PR ](https://github.com/aws/karpenter-core/pulls?q=is%3Apr+author%3Aengedaam+)
- [Reviewed PR ](https://github.com/aws/karpenter-core/pulls?q=is%3Apr+commenter%3Aengedaam+-author%3Aengedaam+)

**Comment by tzneal** [comment]
+1, Amanuel has implemented several fixes/features in the karpenter-core codebase and will continue working on it.

**Comment by gjtempleton** [comment]
+1 from me as well, Amanuel's implemented a number of significant features to karpenter-core. Looking forward to their continued contributions.

**Comment by ydFu** [comment]
@engedaam 
I want to express my heartfelt gratitude for your invaluable contributions to community endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #4603 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes family! 🎉🚀

Best regards,

/assign
