### ISSUE TITLE
REQUEST: New membership for ubergesundheit

### ISSUE THREAD

**Issue by ubergesundheit** [kubernetes/org#4596]
### GitHub Username

@ubergesundheit

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@rikatz

### Sponsor 2

@strongjz

### List of contributions to the Kubernetes project

Contributed to ingress-nginx code and docs. See https://github.com/kubernetes/ingress-nginx/pulls?q=is%3Apr+author%3Aubergesundheit+is%3Aclosed

**Comment by strongjz** [comment]
/approved
/lgtm

We look forward to your continued help with the ingress-nginx helm charts!

**Comment by jasonbraganza** [comment]
ping @rikatz, a +1 would help us process this faster. Thank you :)

**Comment by jasonbraganza** [comment]
hello @rikatz, please help out with a +1? :)

**Comment by rikatz** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@ubergesundheit , thank you for all your contributions so far 🙂

I've created PR #4628  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
