### ISSUE TITLE
REQUEST: New membership for Gacko

### ISSUE THREAD

**Issue by Gacko** [kubernetes/org#4601]
### GitHub Username

@Gacko

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@strongjz

### Sponsor 2

@rikatz

### List of contributions to the Kubernetes project

List of pull request contributed to Ingress NGINX Controller: https://github.com/kubernetes/ingress-nginx/pulls?q=is%3Apr+author%3AGacko

**Comment by rikatz** [comment]
+1
Marko has been a valuable contributor for ingress-nginx taking the ownership of improving, reviewing, contributing to our helm charts

**Comment by strongjz** [comment]
Big plus one to this!

**Comment by ydFu** [comment]
@Gacko 
I want to express my heartfelt gratitude for your invaluable contributions to community endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #4603 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes family! 🎉🚀

Best regards,

/assign
