### ISSUE TITLE
REQUEST: New membership for mochizuki875

### ISSUE THREAD

**Issue by mochizuki875** [kubernetes/org#4604]
### GitHub Username

@mochizuki875

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@atiratree

### Sponsor 2

@bart0sh

### List of contributions to the Kubernetes project

- PRs
https://github.com/kubernetes/kubernetes/pull/114605
https://github.com/kubernetes/kubernetes/pull/115769
https://github.com/kubernetes/kubernetes/pull/117543
https://github.com/kubernetes/kubernetes/pull/118647
https://github.com/kubernetes/kubernetes/pull/119317
https://github.com/kubernetes/kubernetes/pull/120785
https://github.com/kubernetes/kubernetes/pull/120786
https://github.com/kubernetes/kubernetes/pull/120789
https://github.com/kubernetes/kubernetes/pull/120792
https://github.com/kubernetes/kubernetes/pull/119089
https://github.com/kubernetes/kubernetes/pull/120687
https://github.com/kubernetes/kubernetes/pull/121206

- issues
https://github.com/kubernetes/kubernetes/issues/114546
https://github.com/kubernetes/kubernetes/issues/117405
https://github.com/kubernetes/kubernetes/issues/115920

- others
https://github.com/kubernetes/kubernetes/pull/119200
https://github.com/kubernetes/kubernetes/issues/118791
https://github.com/kubernetes/kubernetes/issues/117130
https://github.com/kubernetes/kubernetes/issues/118962
https://github.com/kubernetes/kubernetes/issues/118823

**Comment by atiratree** [comment]
+1, thanks for your contributions and cooperation

**Comment by bart0sh** [comment]
+1

**Comment by helayoty** [comment]
@mochizuki875, I can see you are already a member of k8s org.

**Comment by mochizuki875** [comment]
Hi, @helayoty
Isn't this file is `kubernetes-sigs`?
I'm already a member of `kubernetes-sigs`, but not `kubernetes`.

Thanks.

**Comment by helayoty** [comment]
> Hi, @helayoty
> 
> Isn't this file is `kubernetes-sigs`?
> 
> I'm already a member of `kubernetes-sigs`, but not `kubernetes`.
> 
> 
> 
> Thanks.

@mochizuki875 the Kubernetes-sigs and kubernetes membership are the same.

**Comment by mochizuki875** [comment]
@helayoty 
Maybe my understanding is insufficient...

The [documentations](https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem) says below and it looks like that I'm a member of `kubernetes-sigs org` so implicitly `kubernetes org` too.

> There are related Kubernetes GitHub organizations, such as kubernetes-sigs. We are currently working on automation that would transfer membership in the Kubernetes organization to any related orgs automatically, but such is not the case currently. If you are a member of one of these Orgs, you are implicitly eligible for membership in related orgs, and can request membership when it becomes relevant, by creating a PR directly or opening an issue against the kubernetes/org repo, as above.

However, I can't actually find my name (`@mochizuki875`) in [kubernetes/org.yaml](https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml) and [member list of kubernetes org](https://github.com/orgs/kubernetes/people?query=mochizuki875), and displayed as `Contributor` not as `Member` like [this](https://github.com/kubernetes/kubernetes/pull/121206#issue-1941139810).


So I've open this issue.
Is there anything else I should do to explicitly become a member of `kubernetes org`?

**Comment by vadasambar** [comment]
> However, I can't actually find my name (@mochizuki875) in [kubernetes/org.yaml](https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml?rgh-link-date=2023-11-27T02%3A16%3A13Z) and [member list of kubernetes org](https://github.com/orgs/kubernetes/people?query=mochizuki875), and displayed as Contributor not as Member like https://github.com/kubernetes/kubernetes/pull/121206#issue-1941139810.

Can confirm this. 

![image](https://github.com/kubernetes/org/assets/34534103/cdba45f8-f644-485d-a8d5-d7849bce667f)

Me:
![image](https://github.com/kubernetes/org/assets/34534103/66d4c270-9018-481b-9587-9e49cec87658)

**Comment by mochizuki875** [comment]
thanks! #4613
