### ISSUE TITLE
REQUEST: New membership for VannTen

### ISSUE THREAD

**Issue by VannTen** [kubernetes/org#4607]
### GitHub Username

@VannTen

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@MrFreezeex

### Sponsor 2

@yankay

### List of contributions to the Kubernetes project

Merged PRs:
kubernetes-sigs/kubespray#10657
kubernetes-sigs/kubespray#10650
kubernetes-sigs/kubespray#10646
kubernetes-sigs/kubespray#10597
kubernetes-sigs/kubespray#10596
kubernetes-sigs/kubespray#10590
kubernetes-sigs/kubespray#10542
kubernetes-sigs/kubespray#10540
kubernetes-sigs/kubespray#10518
kubernetes-sigs/kubespray#10516
kubernetes-sigs/kubespray#10515
kubernetes-sigs/kind#2981
kubernetes-sigs/kubespray#8872
kubernetes-sigs/metrics-server#1003
kubernetes-sigs/kubespray#8347
kubernetes-sigs/kubespray#8334
kubernetes-sigs/kubespray#8329
kubernetes-sigs/kubespray#8101
kubernetes-sigs/kubespray#8001
kubernetes-sigs/kubespray#7532

**Comment by yankay** [comment]
+1

👍 Thank you @VannTen and looking forward to your continued work in the community!

**Comment by MrFreezeex** [comment]
+1

Thank you for your valuable contributions on kubespray :D

**Comment by mzaian** [comment]
+1

Thanks for all of your contributions for Kubespray :)

**Comment by VannTen** [comment]
@kubernetes/owners
(mentioning according to the [SLO guidance](https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#slos) . Is anything missing ?)
