### ISSUE TITLE
REQUEST: New membership for poonam-lamba

### ISSUE THREAD

**Issue by poonam-lamba** [kubernetes/org#4616]
### GitHub Username

poonam-lamba

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@JimBugwadia

### Sponsor 2

@rficcaglia

### List of contributions to the Kubernetes project

Active member of wg-policy

- Co-author of GRC [whitepaper](https://github.com/kubernetes/sig-security/pull/94) published by wg-policy 
- Sponsors are mentioned [here](https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/OWNERS)
- Chosen as [co-chair](https://github.com/kubernetes/community/pull/7643) of WG Policy

**Comment by mrbobbytables** [comment]
Can you please provide links and details about it? there isn't really  anything in github. :x

**Comment by poonam-lamba** [comment]
We had one joint PR for everyone's work , 
I would let my sponsors weigh in @JimBugwadia @rficcaglia

**Comment by poonam-lamba** [comment]
adding a link for proof of work - https://docs.google.com/document/d/1IjEOvgqQ0ErEEj85z5iWyFP_TK74gmFf2VJZlMoJbqk/edit

**Comment by JimBugwadia** [comment]
Thanks, Poonam! 

Yes, Poonam has been an active contributor to the WG and has worked on reviewing the policy report API, helped write papers and policy and governance, and updating the Kubernetes docs.

The WG meeting & activity tracker is available at: https://docs.google.com/document/d/1ihFfEfgViKlUMbY2NKxaJzBkgHh-Phk5hqKTzK-NEEs/edit#heading=h.u0h5x9jz9d3r.

I am happy to support her nomination as co-chair and am looking forward to continuing to work together to help secure and scale Kubernetes.

**Comment by mrbobbytables** [comment]
I'll +1 as a sponsor. I've been working with @JimBugwadia and @rficcaglia to get things sorted out for wg-policy. 👍

**Comment by rficcaglia** [comment]
I can confirm @poonam-lamba has been actively contributing the WG and specifically the content creation.  is there anything specific in git I need to do to assist?
