### ISSUE TITLE
REQUEST: New membership for utam0k

### ISSUE THREAD

**Issue by utam0k** [kubernetes/org#4618]
### GitHub Username

utam0k

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sanposhiho

### Sponsor 2

@kerthcet

### List of contributions to the Kubernetes project

- kubernetes-sigs Issue/PR I was involved in
  - [PRs](https://github.com/search?q=org%3Akubernetes-sigs+involves%3Autam0k+updated%3A%3C2023-12-08&type=pullrequests)
  - [Issues](https://github.com/search?q=org%3Akubernetes-sigs+involves%3Autam0k+updated%3A%3C2023-12-08&type=issues)
- kubernetes Issue/PR I was involved in
  - [PRs](https://github.com/search?q=org%3Akubernetes+involves%3Autam0k+updated%3A%3C2023-12-08&type=pullrequests)
  - [Issues](https://github.com/search?q=org%3Akubernetes+involves%3Autam0k+updated%3A%3C2023-12-08&type=issues)

**Comment by sanposhiho** [comment]
+1, thanks.

**Comment by utam0k** [comment]
@ydFu, I don't know who to ask to do the work after getting approval from my sponsors, but as you seem to be the most active these days, may I ask a favor of you?

**Comment by mrbobbytables** [comment]
@utam0k I opened #4622 to add you to both orgs 👍  Once it merges you should get a membership invite notification.

Just an fyi - we generally try and batch org membership updates, they're usually added once a week or so.

/assign

**Comment by utam0k** [comment]
@mrbobbytables I see! Thanks 😍
