### ISSUE TITLE
REQUEST: New membership for hrak

### ISSUE THREAD

**Issue by hrak** [kubernetes/org#4623]
### GitHub Username

hrak

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

weizhouapache

### Sponsor 2

chrisdoherty4

### List of contributions to the Kubernetes project

Merged PRs

- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/214
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/216
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/235
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/297
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/298
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/306
- https://github.com/kubernetes-sigs/image-builder/pull/1072
- https://github.com/kubernetes-sigs/image-builder/pull/1079
- https://github.com/kubernetes-sigs/image-builder/pull/1093
- https://github.com/kubernetes-sigs/image-builder/pull/1111
- https://github.com/kubernetes-sigs/image-builder/pull/1349
- https://github.com/kubernetes-sigs/image-builder/pull/1350

Open PRs:

- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/308
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/309
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/328
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/329

SIG projects i am involved in:

image-builder
cluster-api-provider-cloudstack

**Comment by chrisdoherty4** [comment]
+1 thanks for all the contributions.

**Comment by g-gaston** [comment]
+1

**Comment by jasonbraganza** [comment]
@g-gaston would you kindly mention place of work on your profile or here on this issue? [Membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md) require the sponsors be from different orgs. Thank you :)

**Comment by g-gaston** [comment]
@chrisdoherty4 and I are both from AWS
But @weizhouapache can give the second sponsor from a different company 😄

**Comment by weizhouapache** [comment]
+1

**Comment by jasonbraganza** [comment]
@weizhouapache would you please mention place of work on your profile or here on this issue? Just want to cross my t’s and dot my i’s. Thank you :)

**Comment by weizhouapache** [comment]
> @weizhouapache would you please mention place of work on your profile or here on this issue? Just want to cross my t’s and dot my i’s. Thank you :)

sure @jasonbraganza 
updated my profile, please check, thanks

**Comment by jasonbraganza** [comment]
Thank you @g-gaston, @chrisdoherty4 & @weizhouapache :)

**Comment by jasonbraganza** [comment]
/assign

@hrak, thank you for all your contributions so far 🙂

I've created PR #4625  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
