### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/cluster-api-provider-ibmcloud

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes/org#4626]
### Repository

kubernetes-sigs/cluster-api-provider-ibmcloud

### Project domain

cluster-api-ibmcloud.sigs.k8s.io

### Additional context for request

New release v0.7.0 is out for kubernetes-sigs/cluster-api-provider-ibmcloud

To update book we need the following:
1. New URL - http://release-0-7.cluster-api-ibmcloud.sigs.k8s.io/
2. Point default book page to above URL

**Comment by cblecker** [comment]
This is complete.

/close
