### ISSUE TITLE
REQUEST: New membership for Gauravpadam

### ISSUE THREAD

**Issue by Gauravpadam** [kubernetes/org#4629]
### GitHub Username

@Gauravpadam

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sftim

### Sponsor 2

@dipesh-rawat

### List of contributions to the Kubernetes project

Here's a gist of my contributions as of now:

- Authored 15+ Pull Requests pertaining to code and documentation changes
 (Some notable ones are [#44029](https://github.com/kubernetes/website/pull/44029), [#42823](https://github.com/kubernetes/website/pull/42823), [#43166](https://github.com/kubernetes/website/pull/43166), [#43211](https://github.com/kubernetes/website/pull/43211))
 - Reviewed 50+ PRs for code and documentation changes, and blogs
 (Some notable ones are [#43740](https://github.com/kubernetes/website/pull/43740), [#43914](https://github.com/kubernetes/website/pull/43914), [#44317](https://github.com/kubernetes/website/pull/44317))
 - Actively engaged in issue assistance
 - Active participant of SIG Docs community meetings and discussions
 
 In the future, I hope to assume more ambitious roles in the SIG Docs community and contribute to the best of my capabilities, Thank you!

**Comment by sftim** [comment]
I support this and am happy to sponsor @Gauravpadam.

**Comment by dipesh-rawat** [comment]
+1 from me.
@Gauravpadam Thank you for all your contributions!
Look forward to even more from you in the future. 🚀

/pony party

**Comment by jasonbraganza** [comment]
/assign

@Gauravpadam, thank you for all your contributions so far 🙂

I've created PR #4632 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
