### ISSUE TITLE
REQUEST: New membership for tamilselvan1102

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/org#4631]
### GitHub Username

@tamilselvan1102

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sftim

### Sponsor 2

@dipesh-rawat

### List of contributions to the Kubernetes project

PRs reviewed / authored
https://github.com/search?q=org%3Akubernetes+is%3Apr+author%3Atamilselvan1102&type=pullrequests

Issues responded to
https://github.com/kubernetes/website/issues?q=is%3Aissue+tamilselvan1102

SIG projects i am involved with -
kubernetes/sig-docs
kubernetes/website
kubernetes/dashboard

**Comment by jasonbraganza** [comment]
ping @sftim, @dipesh-rawat, would you please look at this request and +1 the request?

**Comment by sftim** [comment]
Hi @tamilselvan1102 

Let's follow up via Slack. I don't recall discussing sponsorship.

**Comment by tamilselvan1102** [comment]
Not accepted my member role application.

/close
