### ISSUE TITLE
REQUEST: New membership for alexkats

### ISSUE THREAD

**Issue by alexkats** [kubernetes/org#4633]
### GitHub Username

@alexkats

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@aojea

### Sponsor 2

@marseel

### List of contributions to the Kubernetes project

I mainly contribute to ingress-gce repository which is related to my work on L4 loadbalancers for GKE. I also have some contributions in other places (related to scalability testing)

ingress-gce
https://github.com/kubernetes/ingress-gce/pull/1906
https://github.com/kubernetes/ingress-gce/pull/1965
https://github.com/kubernetes/ingress-gce/pull/2124
https://github.com/kubernetes/ingress-gce/pull/2176
https://github.com/kubernetes/ingress-gce/pull/2295
https://github.com/kubernetes/ingress-gce/pull/2351

other contributions
https://github.com/kubernetes/kubernetes/pull/112392
https://github.com/kubernetes/perf-tests/pull/2243

**Comment by marseel** [comment]
Thanks for all the contributions so far and super excited for next contributions!

/lgtm

**Comment by aojea** [comment]
/lgtm

+1

**Comment by jasonbraganza** [comment]
/assign

@alexkats, thank you for all your contributions so far 🙂

I've created PR #4635 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
