### ISSUE TITLE
REQUEST: New membership for mpatlasov

### ISSUE THREAD

**Issue by mpatlasov** [kubernetes/org#4636]
### GitHub Username

@mpatlasov

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@msau42

### Sponsor 2

@jsafrane

### List of contributions to the Kubernetes project

My PRs:
https://github.com/kubernetes/kubernetes/pull/117022
https://github.com/kubernetes/kubernetes/pull/117574
https://github.com/kubernetes/kubernetes/pull/117575
https://github.com/kubernetes/kubernetes/pull/117577
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1462
https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/2511
https://github.com/kubernetes/kubernetes/pull/117599
https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/2326
https://github.com/kubernetes/kubernetes/pull/116833
https://github.com/kubernetes/kubernetes/pull/114528

Issues:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/1372
https://github.com/kubernetes/kubernetes/issues/117021
https://github.com/kubernetes/kubernetes/issues/116831

Reviewed/commented:
https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/2714
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2134
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1222

**Comment by jasonbraganza** [comment]
ping, @msau42, @jsafrane a +1 to this would help me process this membership request. thank you :)

**Comment by msau42** [comment]
+1

**Comment by dobsonj** [comment]
+1

@mpatlasov do you want to include the `kubernetes` org in your request too? I only see the `kubernetes-sigs` org mentioned in the description.

**Comment by jsafrane** [comment]
+1

**Comment by mpatlasov** [comment]
> +1
> 
> @mpatlasov do you want to include the `kubernetes` org in your request too? I only see the `kubernetes-sigs` org mentioned in the description.

Yes, I do! (The form for request assumed only single option (either `kubernetes-sigs` or `kubernetes`, and I was not sure if it's ok to open two independent requests at once)

**Comment by dobsonj** [comment]
> Yes, I do! (The form for request assumed only single option (either `kubernetes-sigs` or `kubernetes`, and I was not sure if it's ok to open two independent requests at once)

You should include both in the description then :) IIRC, I requested two orgs in my initial request too, it could save you some extra requests later.

**Comment by jasonbraganza** [comment]
/assign

@mpatlasov, thank you for all your contributions so far 🙂

I've created PR #4655  to add you to the Kubernetes(s) Org. (added you to both kubernetes & kubernetes [as you wished](https://github.com/kubernetes/org/issues/4636#issuecomment-1875509088).) Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by divyenpatel** [comment]
+1
