### ISSUE TITLE
REQUEST: New membership for qlijin

### ISSUE THREAD

**Issue by qlijin** [kubernetes/org#4637]
### GitHub Username

qlijin

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@windsonsea

### Sponsor 2

@ydFu

### List of contributions to the Kubernetes project

Merged PRs:
https://github.com/kubernetes/website/pull/30187
https://github.com/kubernetes/website/pull/30403
https://github.com/kubernetes/website/pull/34723
https://github.com/kubernetes/website/pull/36801
https://github.com/kubernetes/website/pull/37076
https://github.com/kubernetes/website/pull/38658
https://github.com/kubernetes/website/pull/39645
https://github.com/kubernetes/website/pull/40417
https://github.com/kubernetes/website/pull/40587
https://github.com/kubernetes/website/pull/43194
https://github.com/kubernetes/website/pull/43221
https://github.com/kubernetes/website/pull/44070
https://github.com/kubernetes/website/pull/44472
https://github.com/kubernetes/website/pull/44508

https://github.com/kubernetes-sigs/kubespray/pull/9185
https://github.com/kubernetes-sigs/kubespray/pull/10030
https://github.com/kubernetes-sigs/kubespray/pull/10142
https://github.com/kubernetes-sigs/kubespray/pull/10154
https://github.com/kubernetes-sigs/kubespray/pull/10480

https://github.com/kubernetes/dashboard/pull/6619

**Comment by ydFu** [comment]
+1 
Thank you for your contributions during this period. I hope you continue to contribute in the future.

**Comment by windsonsea** [comment]
+1

Welcome, look forward to your more contributions 👍

**Comment by jasonbraganza** [comment]
/assign

@qlijin, thank you for all your contributions so far 🙂

I've created PR #4639 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
