### ISSUE TITLE
REQUEST: New membership for MaysaMacedo

### ISSUE THREAD

**Issue by MaysaMacedo** [kubernetes/org#4638]
### GitHub Username

@MaysaMacedo

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dulek

### Sponsor 2

@lentzi90

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1633
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1770
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1715
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1789

**Comment by EmilienM** [comment]
LGTM

**Comment by jasonbraganza** [comment]
/assign

@MaysaMacedo, thank you for all your contributions so far 🙂

I've created PR #4639 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by lentzi90** [comment]
+1

Thank you for your contributions so far!

**Comment by dims** [comment]
Welcome to https://github.com/kubernetes! @MaysaMacedo !

**Comment by MaysaMacedo** [comment]
Thanks everyone!

**Comment by MaysaMacedo** [comment]
@jasonbraganza I didn't get a membership invite notification and [I can't perform members operation](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1807#issuecomment-1874391940), like `ok-to-test` command. 
Do you know what could I be missing? maybe also request membership to `kubernetes`?

**Comment by MaysaMacedo** [comment]
I just found it. Sorry for the noise!
