### ISSUE TITLE
REQUEST: New membership for alejandrox1

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/org#464]
### GitHub Username
@alejandrox1

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp
- @BenTheElder

### List of contributions to the Kubernetes project
- SIG-release
  - CI signal shadow for v1.14

**Comment by BenTheElder** [comment]
+1
cc @neolit123 (@spiffxp and I have the same employer, Lubomir does not)

Previous +1 for kubernetes-sigs here: https://github.com/kubernetes/org/issues/373#issuecomment-454900103

looks like @alejandrox1 just needs to be in the main kubernetes org now 😅

**Comment by nikhita** [comment]
+1 from my side! Happy to have you in @kubernetes! :heart:

**Comment by alejandrox1** [comment]
Thank you @BenTheElder and thank you @nikhita for coming to the rescue :smile:

**Comment by mrbobbytables** [comment]
Thanks for the additional +1 @nikhita.

Thank you @alejandrox1 for your help with the release team :)

I've created PR #466  to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
/pony party
