### ISSUE TITLE
REQUEST: Migrate mneverov/cluster-cidr-controller to kubernetes-sigs/node-ipam-controller

### ISSUE THREAD

**Issue by mneverov** [kubernetes/org#4640]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

node-ipam-controller

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

ameukam, aojea, mneverov, sarveshr7, other members of https://github.com/kubernetes/community/blob/master/sig-network/README.md#chairs

### Who should have write access?

ameukam, aojea, mneverov, sarveshr7, other members of https://github.com/kubernetes/community/blob/master/sig-network/README.md#chairs

### Who should be listed as approvers in OWNERS?

ameukam, aojea, mneverov, sarveshr7, other members of https://github.com/kubernetes/community/blob/master/sig-network/README.md#chairs

### Who should be listed in SECURITY_CONTACTS?

ameukam, aojea, mneverov, sarveshr7, other members of https://github.com/kubernetes/community/blob/master/sig-network/README.md#chairs

### What should the repo description be?

Out of tree implementation of https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2593-multiple-cluster-cidrs

It allows users to use the node-ipam-controller that allocates IP ranges to Nodes, setting the node.spec.PodCIDRs fields The node-ipam-controller is configured via ClusterCIDR CRDs.

### What SIG and subproject does this fall under?

sig-network

### Please provide references to appropriate approval for this new repo

[Naming poll thread](https://groups.google.com/g/kubernetes-sig-network/c/7H1AAZreZX0).

### Additional context for request

Initial "[move out of the tree](https://groups.google.com/g/kubernetes-sig-network/c/nts1xEZ--gQ)" thread

**Comment by aojea** [comment]
+1
/lgtm
/approve

**Comment by ameukam** [comment]
+1

**Comment by ameukam** [comment]
/retitle REQUEST: Migrate mneverov/cluster-cidr-controller to kubernetes-sigs/node-ipam-controller

**Comment by Priyankasaggu11929** [comment]
/assign

Thanks for the +1s.

@mneverov, @ameukam could you please confirm, if this is a request for

1. new repo creation under `kubernetes-sigs` org? OR 
2. migration of https://github.com/mneverov/cluster-cidr-controller to kubernetes-sigs org?

The issue description need updating accordingly.

**Comment by ameukam** [comment]
> /assign
> 
> Thanks for the +1s.
> 
> @mneverov, @ameukam could you please confirm, if this is a request for
> 
>     1. new repo creation under `kubernetes-sigs` org? OR
> 
>     2. migration of https://github.com/mneverov/cluster-cidr-controller to kubernetes-sigs org?
> 
> 
> The issue description need updating accordingly.

@Priyankasaggu11929 Confirming this is a repo migration.

**Comment by mneverov** [comment]
@Priyankasaggu11929 migrated the repo to the [purgatory](https://github.com/kubernetes-purgatory/node-ipam-controller). Please let me know if there is anything else needs to be done from our side.

**Comment by Priyankasaggu11929** [comment]
Thank you @mneverov.

The repo is live at https://github.com/kubernetes-sigs/node-ipam-controller :tada: 

PR to add GitHub teams for the repo - https://github.com/kubernetes/org/pull/4672

Need input on the following two items:

- new repo will be part of which [subproject of SIG Network](https://github.com/kubernetes/community/blob/master/sig-network/README.md#subprojects)?
- need a one liner description for the new repo, one provided in the issue description doesn't fit the character limit. :sweat_smile:

**Comment by Priyankasaggu11929** [comment]
@ameukam, I meant to ask

[1] will the repo be a new subproject on its own? OR
[2] part of an existing [subproject of SIG Network](https://github.com/kubernetes/community/blob/master/sig-network/README.md#subprojects)?

**Comment by ameukam** [comment]
Option 1. a new subproject on its own.

**Comment by Priyankasaggu11929** [comment]
Thanks again, @ameukam. Raised final PR - https://github.com/kubernetes/community/pull/7681

**Comment by Priyankasaggu11929** [comment]
All PRs are merged. The Repo migration is comple.

Closing the ticket.

/close

**Comment by aojea** [comment]
yay, thanks
