### ISSUE TITLE
REQUEST: New membership for ericsmalling

### ISSUE THREAD

**Issue by ericsmalling** [kubernetes/org#4641]
### GitHub Username

@ericsmalling

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@PushkarJ

### Sponsor 2

@tabbysable

### List of contributions to the Kubernetes project

- Active in k8s sig-security for ~3 years
- Shadow for @PushkarJ on the CVE feed effort (run by the sig-security tooling working group)
- Most recent code contribution to the CVE feed prow job: https://github.com/kubernetes/test-infra/pull/31076
- Managed Snyk + CNCF entitlements through Dec 2023

**Comment by PushkarJ** [comment]
Thank you @ericsmalling for your excellent stewardship in maintaining the vulnerability scanning for k8s artifacts as an open source contributor and synk facilitator for CNCF over the last several years, all while being an excellent SIG Security contributor throughout our meetings. 

Fully and wholeheartedly support your org membership

/party

**Comment by jasonbraganza** [comment]
@tabbysable a +1 on this would help me process the request.
Also would you please update this issue (or your profile) with the Org you work at? 
Asking because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md) require the sponsors be from different orgs. Thank you :)

**Comment by tabbysable** [comment]
+1, Eric, I'm so glad we're *finally* getting your paperwork done to recognize the great contributions you've already been making for so long.

/lgtm
/honk

**Comment by tabbysable** [comment]
@jasonbraganza Thanks for checking; I'm at Datadog

**Comment by reylejano** [comment]
Big +1, @ericsmalling has contributed to make Kubernetes more secure with the scanning efforts and other contributions in SIG Security.
I'm with Red Hat.

**Comment by mtardy** [comment]
Huge +1! 🤗

**Comment by jasonbraganza** [comment]
/assign

@ericsmalling, thank you for all your contributions to the project 🙂

I've created PR  #4655 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes 🎉

**Comment by ericsmalling** [comment]
Thank you @jasonbraganza , and to all for the kind comments! :)
