### ISSUE TITLE
REQUEST: New membership for mneverov

### ISSUE THREAD

**Issue by mneverov** [kubernetes/org#4642]
### GitHub Username

mneverov

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

ameukam

### Sponsor 2

aojea

### List of contributions to the Kubernetes project

PRs reviewed / authored:
https://github.com/search?q=org%3Akubernetes-sigs+is%3Apr+author%3Amneverov&type=pullrequests
https://github.com/kubernetes/org/issues/4640

**Comment by aojea** [comment]
+1

Max created a prototype out of tree for a sig-network project https://groups.google.com/g/kubernetes-sig-network/c/nts1xEZ--gQ/m/NzFflTWgAAAJ and the SIG wants to adopt it under the kubernetes-sig org.
Max will be one of the owners and maintainers of this new project

**Comment by jasonbraganza** [comment]
@aojea, @ameukam a +1 on the issue will help me process this request
@ameukam would you also please update your place of work here on this issue or on the profile.
Asking because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md) require the sponsors be from different orgs.
Thank you :)

**Comment by jasonbraganza** [comment]
ping @ameukam, would you please help with a +1 and updation of org? thank you :)

**Comment by ameukam** [comment]
+1
@jasonbraganza I work for VMware by BroadCom

**Comment by jasonbraganza** [comment]
/assign

@mneverov, thank you for all your contributions so far 🙂

I've created PR #4662 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
