### ISSUE TITLE
REQUEST: New membership for Rei1010

### ISSUE THREAD

**Issue by Rei1010** [kubernetes/org#4648]
### GitHub Username

Rei1010

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kerthcet

### Sponsor 2

@pohly

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pull/120305
https://github.com/kubernetes/kubernetes/pull/120306
https://github.com/kubernetes/kubernetes/pull/120402
https://github.com/kubernetes/kubernetes/pull/120405
https://github.com/kubernetes/kubernetes/pull/120629
https://github.com/kubernetes/kubernetes/pull/121145
https://github.com/kubernetes/kubernetes/pull/122135
https://github.com/kubernetes/kubernetes/pull/122409

**Comment by kerthcet** [comment]
Also +1 from me, Thanks @Rei1010

**Comment by jasonbraganza** [comment]
@kerthcet, also would you please comment on here or update you profile with your work org?
asking because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md) require sponsors be from different orgs. Thank you :)

**Comment by kerthcet** [comment]
Thanks for notification, I'm from DaoCloud. Different with Patrick.

**Comment by pohly** [comment]
I'm from Intel.

**Comment by jasonbraganza** [comment]
Thank you @kerthcet and @pohly :)

**Comment by jasonbraganza** [comment]
/assign

@Rei1010, thank you for all your contributions to the project 🙂

I've created PR #4656  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes 🎉

**Comment by Rei1010** [comment]
Thanks @pohly @kerthcet @jasonbraganza 🙂
