### ISSUE TITLE
REQUEST: New membership for khareyash05

### ISSUE THREAD

**Issue by khareyash05** [kubernetes/org#4649]
### GitHub Username

@khareyash05

### Organization you are requesting membership in

kubernetes-sigs , kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@richardcase

### Sponsor 2

@pacoxu

### List of contributions to the Kubernetes project

[https://github.com/kubernetes/autoscaler/pull/6036](https://github.com/kubernetes/autoscaler/pull/6036)
[https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4234](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4234)
[https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4232](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4232)
[https://github.com/kubernetes-sigs/kubebuilder/pull/3352](https://github.com/kubernetes-sigs/kubebuilder/pull/3352)

**Comment by pacoxu** [comment]
+1 
I really appreciate your contributions in testing and also sharing about multi-cluster. Hope your more contributions.

**Comment by richardcase** [comment]
+1

Thanks for your contributions @khareyash05

**Comment by jasonbraganza** [comment]
/assign

@khareyash05, thank you for all your contributions to the project. Look forward to more 🙂

I've created PR #4655 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes 🎉

**Comment by khareyash05** [comment]
hi @jasonbraganza Thank you for the membership. I applied for kubernetes org as well. Can you please help me as to how to add myself to the org. I got an invite for sigs org but not kubernetes
