### ISSUE TITLE
REQUEST: New membership for Bryce Soghigian

### ISSUE THREAD

**Issue by Bryce-Soghigian** [kubernetes/org#4652]
### GitHub Username

Bryce-Soghigian

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jonathan-innis

### Sponsor 2

@tallaxes

### List of contributions to the Kubernetes project

# Kubernetes Organization Membership Request

## Professional Background

I am part of the Azure Kubernetes Service team. I work on AKS's SIG Autoscale Team. My most notable achievement includes being a foundational member in developing the Azure/Karpenter cloud provider, contributing significantly to the productization of Karpenter for Azure, and various critical bug fixes in both the OSS Cluster Autoscaler project, and inside our managed Cluster Autoscaler.

## Contributions to AKS Karpenter Provider

My involvement over the past year with the AKS Karpenter Provider, though majorly unreflected in the history due to a project history reset for our OSS launch, has been substantial(I hope so at least). My public contributions since then add substantial value, as seen here:

- [Bryce Soghigian's Pull Requests on Azure/Karpenter](https://github.com/Azure/karpenter/pulls?q=+is%3Apr+author%3ABryce-Soghigian)

## Impact on Karpenter Pre-OSS
To summarize a couple of the achievements of value I added to the project pre-oss, I made the little list below.
- Established a publishing pipeline for AKS VHDs to the community, enabling Karpenter's compatibility, and community access to ALL AKS Images.
- Developed a framework for adding new CommunityImage Definitions and resolving image versions in Karpenter, facilitating node auto-provisioning for most SKUs.
- Implemented Karpenter image family validation in NodeTemplate and rolling image upgrades for auto-upgrade support.
- Authored the Karpenter bootstrap for GPU nodes, including a full driver matrix.
- Introduced GPU capacity considerations in Karpenter's internal resource calculations.
- Implemented E2E validation for GPU bootstrapping and customer-supported scenarios.
- Developed unavailable offerings and zonal allocation caching to enhance provisioning efficiency.
- Filtered out SKUs detrimental to customer experience and enabled OS disk size customization for optimal disk selection.
- Integrated ephemeral storage awareness and ARM SKU support in Karpenter's autoscaling decisions.
- Implemented VM provisioning in Karpenter with the Track 2 Azure SDK for Go.
- Prioritized comprehensive unit and E2E testing, covering various aspects of Karpenter functionality, including daemonset behavior, consolidation delete and replace, and storage scenarios.
- Introduced Cgroupsv2 support, containerd templating for flexible configuration, etc. 

I can continue to talk about what value I added, but stopped here as I figured this would be sufficent for this portion, and wanted to move onto projects inside of the k8s org even though my karpenter provider work is my largest value I provide to the k8s ecosystem.

## Community Engagement

I actively engage in the community through the Slack channel since the project's OSS inception. My work has been instrumental in promoting Kubernetes SIGS Karpenter as a vendor-neutral platform and representing AKS in the cluster autoscaler space. Relevant discussions and issues include:

- [Kubernetes SIGS Karpenter Issue 832](https://github.com/kubernetes-sigs/karpenter/issues/832)
- [Kubernetes SIGS Karpenter Issue 920](https://github.com/kubernetes-sigs/karpenter/issues/920)
- Kubernetes Autoscaler Issues: [#6360](https://github.com/kubernetes/autoscaler/issues/6360), [#5959](https://github.com/kubernetes/autoscaler/issues/5959), [#5618](https://github.com/kubernetes/autoscaler/issues/5618), [#5952](https://github.com/kubernetes/autoscaler/issues/5952), [#5923](https://github.com/kubernetes/autoscaler/issues/5923)

## Cluster Autoscaler Contributions

My contributions to the cluster autoscaler are evident in several pull requests:

- [Kubernetes Autoscaler Pull Requests](https://github.com/kubernetes/autoscaler/pulls) (PR #6321, #5890, #5965, #5966, #5967, #5949, #5381)
-- Kubernetes Autoscaler Pull Requests:
  - [PR #6321](https://github.com/kubernetes/autoscaler/pull/6321)
  - [PR #5890](https://github.com/kubernetes/autoscaler/pull/5890)
  - [PR #5965](https://github.com/kubernetes/autoscaler/pull/5965)
  - [PR #5966](https://github.com/kubernetes/autoscaler/pull/5966)
  - [PR #5967](https://github.com/kubernetes/autoscaler/pull/5967)
  - [PR #5381](https://github.com/kubernetes/autoscaler/pull/5381)

## Other Contributions

- [Cloud Provider Azure Pull Request 2653](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2653)
- [Cloud Provider Azure Pull Request 4184](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4184)

## Conclusion

These are the highlights of my contributions. I am ready to provide more details if necessary to support my application for community membership.

Both Approvers are part of the main project im involved with See the owners: https://github.com/kubernetes-sigs/karpenter/blob/main/OWNERS_ALIASES#L3

**Comment by jonathan-innis** [comment]
+1, @Bryce-Soghigian has been an active contributor to Azure/Karpenter and has been active in design discussion and contribution on kubernetes-sigs/karpenter

**Comment by tallaxes** [comment]
+1, @Bryce-Soghigian have been an active contributor to Karpenter provider for AKS and Cluster Autoscaler/AKS.

**Comment by jasonbraganza** [comment]
/assign

@Bryce-Soghigian, thank you for all your contributions to the project 🙂

I've created PR #4655 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes 🎉

**Comment by jackfrancis** [comment]
+1, thanks @Bryce-Soghigian for all your work on AKS karpenter!
