### ISSUE TITLE
REQUEST: New membership for wlq1212

### ISSUE THREAD

**Issue by wlq1212** [kubernetes/org#4653]
### GitHub Username

wlq1212

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu

### Sponsor 2

@pohly

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pull/120403
https://github.com/kubernetes/kubernetes/pull/120403
https://github.com/kubernetes/kubernetes/pull/121141
https://github.com/kubernetes/kubernetes/pull/121140
https://github.com/kubernetes/kubernetes/pull/120285
https://github.com/kubernetes/kubernetes/pull/122553

**Comment by pohly** [comment]
:+1: from me (Intel).

**Comment by pacoxu** [comment]
+1

Looking forward to your more contributions in the future.

**Comment by jasonbraganza** [comment]
/assign

@wlq1212, thank you for all your contributions to the project 🙂

I've created PR #4656 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes 🎉

**Comment by wlq1212** [comment]
Thanks @pohly @pacoxu @jasonbraganza
