### ISSUE TITLE
REQUEST: Migrate dims/hydrophone to kubernetes-sigs/hydrophone

### ISSUE THREAD

**Issue by dims** [kubernetes/org#4654]
### New repo, staging repo, or migrate existing

https://github.com/dims/hydrophone

### Is it a staging repo?

no

### Requested name for new repository

hydrophone

### Which Organization should it reside

kubernetes

### Who should have admin access?

dims rjsadow

### Who should have write access?

dims rjsadow

### Who should be listed as approvers in OWNERS?

dims rjsadow aniruddha2000 

### Who should be listed in SECURITY_CONTACTS?

dims rjsadow aniruddha2000 

### What should the repo description be?

Hydrophone is a lightweight Kubernetes conformance tests runner

### What SIG and subproject does this fall under?

sig-testing sig-release

### Please provide references to appropriate approval for this new repo

https://groups.google.com/g/kubernetes-sig-testing/c/OchiSDspgFU/m/r0SQvXX4AwAJ

**Comment by dims** [comment]
cc @jeremyrickard @justaugustus @saschagrunert @Verolop @cpanato @puerco @kubernetes/sig-release-leads 

cc @jbpratt @michelle192837 @xmcqueen @BenTheElder @alvaroaleman @aojea @cjwagner @pohly @kubernetes/sig-testing-leads

**Comment by pohly** [comment]
:+1: from me.

It will be very useful to run conformance testing more or less like real users will before cutting a release. I was discussing this with @hh a bit but we did not make much progress towards that with Sonobuoy.

**Comment by cpanato** [comment]
+1 this is nice

**Comment by aojea** [comment]
+1

**Comment by jbpratt** [comment]
+1 :tada: nice!

**Comment by xmudrii** [comment]
+1

**Comment by upodroid** [comment]
+1

**Comment by jeremyrickard** [comment]
+1 from me for SIG Release

**Comment by BenTheElder** [comment]
+1, as SIG Testing TL (also @pohly https://github.com/kubernetes/org/issues/4654#issuecomment-1876742743 and @aojea https://github.com/kubernetes/org/issues/4654#issuecomment-1876845264 above)

**Comment by neolit123** [comment]
@dims i'm trying to understand what the actual motivation is.

the project is certainly light weight in terms of LoC - https://ghloc.vercel.app/ reports it's 1/100 of the size of sonobuoy.
but sonobuoy also has plugin support and 50% of the LoC there are the "website".
in the README of hydrophone "lightweight" seems to be the main argument for it's existence, but perhaps another reason is "community owned"? i don't know if sonobuoy ever had plans to donate to the k8s orgs, either.

either way, +1 from me because of the community owned and lightweight factors, but -1 due to the OSS fragmentation.

**Comment by MadhavJivrajani** [comment]
/assign

Based on the +1s above from SIGs testing and release, I'll take this up and help create the repo.

**Comment by MadhavJivrajani** [comment]
The repo has been migrated here: https://github.com/kubernetes-sigs/hydrophone 🎉 

PRs to add GH teams and add `hydrophone` to sig-testing are open:
- https://github.com/kubernetes/org/pull/4667
- https://github.com/kubernetes/community/pull/7676

@dims @rjsadow, just FYI, the issue description mentions aniruddha2000 to be part of the OWNERS as well as SECURITY_CONTACTS. However, that does not reflect what those files actually hold currently, please either edit the issue or the respective files in the k-sigs/hydrophone repo.

**Comment by rjsadow** [comment]
@MadhavJivrajani addressing in https://github.com/kubernetes-sigs/hydrophone/pull/79

**Comment by MadhavJivrajani** [comment]
Closing this out now, thanks all!

/close
