### ISSUE TITLE
REQUEST: New membership for sadath-12

### ISSUE THREAD

**Issue by sadath-12** [kubernetes/org#4657]
### GitHub Username

@sadath-12

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jonathan-innis

### Sponsor 2

@tallaxes

#### List of pr's merged

- [x] https://github.com/kubernetes-sigs/karpenter/pull/908
- [x] https://github.com/kubernetes-sigs/karpenter/pull/907
- [x] https://github.com/kubernetes-sigs/karpenter/pull/607
- [x] https://github.com/kubernetes-sigs/karpenter/pull/578
- [x] https://github.com/kubernetes-sigs/karpenter/pull/575
- [x] https://github.com/kubernetes-sigs/karpenter/pull/554

#### List of pr's on the way to get merged

- [x] https://github.com/kubernetes-sigs/karpenter/pull/569
- [x] https://github.com/kubernetes-sigs/karpenter/pull/626
- [x] https://github.com/kubernetes-sigs/karpenter/pull/634
- [x] https://github.com/kubernetes-sigs/karpenter/pull/569
- [x] https://github.com/kubernetes-sigs/karpenter/pull/629

**Comment by jonathan-innis** [comment]
+1, @sadath-12 has been involved in discussions in kubernetes-sigs/karpenter and has a number of contributions, including some larger ones that will support better Observability in Karpenter and support for Native Sidecar containers feature in 1.29

**Comment by tallaxes** [comment]
+1, thank you @sadath-12 for your contributions to Karpenter!

**Comment by sadath-12** [comment]
Thank you @jonathan-innis and @tallaxes for sponsoring this 😊

**Comment by jasonbraganza** [comment]
/assign

@sadath-12, thank you for all your contributions so far 🙂

I've created PR #4659 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by sadath-12** [comment]
thank you @jasonbraganza
