### ISSUE TITLE
REQUEST: New membership for mandre

### ISSUE THREAD

**Issue by mandre** [kubernetes/org#4663]
### GitHub Username

@mandre

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jichenjc

### Sponsor 2

@mdbooth

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/cloud-provider-openstack/pull/2517
- https://github.com/kubernetes/community/pull/7660
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1803
- https://github.com/kubernetes/enhancements/pull/4296
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1696 (co-authored)
- https://github.com/kubernetes/test-infra/pull/26743
- https://github.com/kubernetes/kubernetes/pull/107786
- https://github.com/kubernetes/test-infra/pull/13889
- https://github.com/kubernetes/kubernetes/pull/90717
- https://github.com/kubernetes/kubernetes/pull/90716

**Comment by mdbooth** [comment]
/lgtm

Martin has been contributing across kubernetes and kubernetes-sigs for long enough that it's embarrassing he hasn't joined sooner!

**Comment by jichenjc** [comment]
/lgtm

Martin contributed a lot to CPO and CAPO projects so it's honor to work with him and get his more contributions to the projects

**Comment by jasonbraganza** [comment]
/assign

@mandre, thank you for all your contributions so far 🙂

I've created PR #4664 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
