### ISSUE TITLE
REQUEST: New membership for chansuke

### ISSUE THREAD

**Issue by chansuke** [kubernetes/org#4666]
### GitHub Username

@chansuke

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@koba1t

### Sponsor 2

@natasha41575

### List of contributions to the Kubernetes project

- kubernetes Issue/PR I was involved in
        [PRs](https://github.com/search?q=org%3Akubernetes+involves%3Achansuke+updated%3A%3C2024-01-10&type=pullrequests)
        [Issues](https://github.com/search?q=org%3Akubernetes+involves%3Achansuke+updated%3A%3C2024-01-10&type=issues)
        
- kubernetes-sigs Issue/PR I was involved in
        [PRs](https://github.com/search?q=org%3Akubernetes-sigs+involves%3Achansuke+updated%3A%3C2024-01-10&type=pullrequests)
        [Issues](https://github.com/search?q=org%3Akubernetes-sigs+involves%3Achansuke+updated%3A%3C2024-01-10&type=issues)

**Comment by koba1t** [comment]
+1 from me!

Thanks for your contributions!

**Comment by natasha41575** [comment]
+1 from me as well

**Comment by jasonbraganza** [comment]
/assign

@chansuke, thank you for all your contributions so far 🙂

I've created PR  #4670 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by chansuke** [comment]
@jasonbraganza 
Thanks for your work!
I got follow up emails which had membership of `kubernetes` has been cancelled(`kubernetes-sigs` worked), how can we check why it got cancelled?
Same error below?
https://github.com/kubernetes/org/issues/4483#issuecomment-1741864772

**Comment by Priyankasaggu11929** [comment]
Hello @chansuke, I can verify you've received a new invite for the `kubernetes` org membership an hour back.

Please let us know, if the issue persists. Thanks for pointing!

![image](https://github.com/kubernetes/org/assets/30499743/26def159-571e-4f15-8937-78d991abaa9f)

**Comment by jasonbraganza** [comment]
thank you @Priyankasaggu11929. @chansuke, please let us know if all goes well? (or even if it does not :) )

**Comment by chansuke** [comment]
@Priyankasaggu11929 @jasonbraganza 
It worked. Thank you!

**Comment by jasonbraganza** [comment]
/close

Closing the issue then :)
Nice to hear it all worked out
