### ISSUE TITLE
REQUEST: New membership for sarveshr7

### ISSUE THREAD

**Issue by sarveshr7** [kubernetes/org#4669]
### GitHub Username

sarveshr7

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@aojea

### Sponsor 2

@ameukam

### List of contributions to the Kubernetes project

- Worked on SIG-NET KEP [2593](https://github.com/kubernetes/enhancements/issues/2593): Enhancing NodeIPAM to support multiple ClusterCIDRs
- PRs worked on 
   -  https://github.com/kubernetes/kubernetes/pull/109090
   -  https://github.com/kubernetes/kubernetes/pull/115453
 
Will be a Contributor on an out of tree implementation for the ClusterCIDR project. https://groups.google.com/g/kubernetes-sig-network/c/nts1xEZ--gQ/m/NzFflTWgAAAJ

**Comment by aojea** [comment]
+1

**Comment by ameukam** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@sarveshr7, thank you for all your contributions so far 🙂

I've created PR #4670 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
