### ISSUE TITLE
REQUEST: Migrate danwinship/knftables to kubernetes-sigs/knftables

### ISSUE THREAD

**Issue by danwinship** [kubernetes/org#4673]
### New repo, staging repo, or migrate existing

migrate existing

### Is it a staging repo?

no

### Requested name for new repository

knftables

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

danwinship, aojea, MikeZappa87, shaneutt, thockin

### Who should have write access?

danwinship, aojea, MikeZappa87, shaneutt, thockin

### Who should be listed as approvers in OWNERS?

danwinship

### Who should be listed in SECURITY_CONTACTS?

danwinship

### What should the repo description be?

a golang nftables library for Kubernetes

### What SIG and subproject does this fall under?

sig-network, no subproject

### Please provide references to appropriate approval for this new repo

Original discussion: https://github.com/kubernetes/kubernetes/pull/121046#discussion_r1368606188

Formally proposed  and +1'ed: https://groups.google.com/g/kubernetes-sig-network/c/0cIgcgRbLyk/m/JfguzlApAAAJ

### Additional context for request

The kubernetes-sigs repo rules are not clear if repos _can_ be associated with a subproject or _must_ be associated with a subproject. At the moment, kube-proxy maintenance is considered part of the core SIG Network work, so there is no existing subproject to own this repo, and it's not clear that adding a subproject would be administratively useful to us.

Note that the existing repo already has OWNERS and SECURITY_CONTACTS files (which match the answers given above). For the moment I want to be the only approver but once the API stabilizes I'll add more people there.

**Comment by aojea** [comment]
+1

ping @MadhavJivrajani

**Comment by mrbobbytables** [comment]
/assign
@danwinship I'll invite you to our intermediary org kubernetes-purgatory, if you could transfer it there then we can move it into k-sigs

**Comment by danwinship** [comment]
@mrbobbytables done

**Comment by mrbobbytables** [comment]
FYI I created the team for now with Mike Zappa on there, he's not a member of k-sigs, so should resolve that one first and can sort it out later.

**Comment by mrbobbytables** [comment]
Once the PRs to add teams and update the subproject list are merged, this should be good to close 👍

**Comment by mrbobbytables** [comment]
This should be good to close, the only follow up action would be for Mike to join k-sigs and accept the invite before being added to the group.

**Comment by danwinship** [comment]
Thanks!
