### ISSUE TITLE
REQUEST: New membership for shanduur

### ISSUE THREAD

**Issue by shanduur** [kubernetes/org#4676]
### GitHub Username

@shanduur

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@wlan0

### List of contributions to the Kubernetes project

* Working actively with sig-storage's COSI project: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1979-object-storage-support
  * Updated the COSI Driver Sample to be in line with `container-object-storage-interface-api@v0.1.0` and `container-object-storage-interface-spec@v0.1.0`: https://github.com/kubernetes-sigs/cosi-driver-sample/pull/6
  * Fixing minor issues in COSI repositories:
    * issue with the logs: https://github.com/kubernetes-sigs/container-object-storage-interface-controller/pull/77
    * default value of case sensitive field `DeletionPolicy` in _Bucket_ and _BucketClaim_: https://github.com/kubernetes-sigs/container-object-storage-interface-api/pull/65
  * Continuous work on adding _EventRecorder_ and _EventBroadcaster_ to the COSI components: 
    * https://github.com/kubernetes-sigs/container-object-storage-interface-api/pull/67
    * https://github.com/kubernetes-sigs/container-object-storage-interface-controller/pull/101
    * https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/pull/92
  * Proposing a COSI Testing strategy: https://docs.google.com/document/d/15_Wi-ndKIrrew71J26E9pU7_NlIjrUKOQW-zcTKyLXQ
  * Reviewing:
    * https://github.com/kubernetes-sigs/container-object-storage-interface-controller/pull/79

**Comment by xing-yang** [comment]
+1

**Comment by wlan0** [comment]
+1

**Comment by jasonbraganza** [comment]
@wlan0 would you kindly update your place of work on this issue or on your profile?
asking for clarity, since [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require sponsors be from different orgs.
thank you :)

**Comment by jasonbraganza** [comment]
@wlan0, please help :)

**Comment by wlan0** [comment]
@jasonbraganza All apologies! I work at apple - I've also updated my profile

**Comment by jasonbraganza** [comment]
/assign
@shanduur, thank you for all your contributions 🙂

I’ve created PR #4701  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
