### ISSUE TITLE
Transfer ownership of aws-efs-csi-driver repository as SIG-AWS subproject

### ISSUE THREAD

**Issue by d-nishi** [kubernetes/org#468]
### New Repo, Staging Repo, or migrate existing
New repository

### Requested name for new repository
aws-efs-csi-driver

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@d-nishi 
@leakingtapan 
@justinsb 

### If not a staging repo, who should have write access
@d-nishi 
@leakingtapan 
@justinsb
@jsafrane 

### If a new repo, who should be listed as approvers in OWNERS
@d-nishi 
@leakingtapan 
@justinsb
@jsafrane 

### If a new repo, who should be listed in SECURITY_CONTACTS
@leakingtapan 

### What should the repo description be
This is the Container Storage Interface (CSI) driver implementation of Amazon EFS that provides a CSI interface to be used by Kubernetes to manage lifecycle of Amazon Elastic Filesystem.

### What SIG and subproject does this fall under in sigs.yaml
SIG-AWS
this will be a standalone subproject under SIG-AWS

### Approvals
Complete check-list:
* [x]  Must contain the topic for the sponsoring SIG - e.g. k8s-sig-api-machinery. (Added through the Manage topics link on the repo page.)
* [x]  Must adopt the Kubernetes Code of Conduct
* [x]  All code projects use the Apache License version 2.0. Documentation repositories must use the Creative Commons License version 4.0.
* [ ]  Must adopt the CNCF CLA bot, merge bot and Kubernetes PR commands/bots.
* [x]  All OWNERS of the project must also be active SIG members
* [x]  SIG membership must vote using lazy consensus to create a new repository
* [ ]  SIG must already have identified all of their existing subprojects and code, with valid OWNERS files, in [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml)
* [x]  All contributors must have signed the CNCF Individual CLA (https://github.com/cncf/cla/blob/master/individual-cla.pdf) or CNCF Corporate CLA (https://github.com/cncf/cla/blob/master/corporate-cla.pdf)
* [x]  Licenses of dependencies are acceptable; project owners can ping [@caniszczyk](https://github.com/caniszczyk) for review of third party deps. No dependencies found.
* [x] Received lazy consensus from +8 folks in SIG-AWS meeting held on 02/08/2018: [SIG AWS Meeting minutes](https://docs.google.com/document/d/1-i0xQidlXnFEP9fXHWkBxqySkXwJnrGJP9OGyP2_P14/edit#)

### Additional context for request
N.A.

**Comment by cblecker** [comment]
@d-nishi is this a new repo? or a transfer?

**Comment by leakingtapan** [comment]
/hold

This is an existing projects that is going to be contributed by aws to the community.

See https://github.com/aws/aws-efs-csi-driver

Need to finialize the project name before transfer

**Comment by nikhita** [comment]
:wave: just wanted to check if there are any updates here?

**Comment by leakingtapan** [comment]
@nikhita we are ready for this

**Comment by nikhita** [comment]
@leakingtapan thanks for the update!

/unassign @cblecker 
/assign

**Comment by nikhita** [comment]
for additional context: https://github.com/kubernetes/org/issues/467#issuecomment-476980841

**Comment by nikhita** [comment]
https://github.com/kubernetes/org/issues/467#issuecomment-479063593

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/3552 added repos to sigs.yaml and access has been granted to the respective teams.

/close
