### ISSUE TITLE
REQUEST: New membership for fkautz

### ISSUE THREAD

**Issue by fkautz** [kubernetes/org#4681]
### GitHub Username

fkautz

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

kcmartin

### Sponsor 2

katcosgrove

### List of contributions to the Kubernetes project

I am a new shadow for the release comms.

In the past, I participated in the earliest days of kubernetes and helped with networking and storage. I created the first definition of a CNF that helped guide telecoms towards kubernetes. More recently, I co-chaired kubecon for the last three. I also have an extensive background in contributing to several CNCF projects.

I am looking to help with comms in kubernetes itself.

Thank you!

**Comment by kcmartin** [comment]
+1

Welcome to the 1.30 Release Team!

**Comment by jasonbraganza** [comment]
/assign
@fkautz, thank you for all your contributions so far 🙂

I've created PR #4693 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
