### ISSUE TITLE
REQUEST: New membership for checksumz

### ISSUE THREAD

**Issue by Checksumz** [kubernetes/org#4682]
### GitHub Username

@checksumz

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kcmartin

### Sponsor 2

@katcosgrove

### List of contributions to the Kubernetes project

I have just joined as a shadow for the release comms and have become more active contributing to the Kubernetes release team recently. I have contributed to multiple projects (Argo, Ortelius) and recently spoke at Kubecon + CloudnativeCon. I am currently working towards getting more people involved in open source in ANZ zone :)

**Comment by katcosgrove** [comment]
+1

Welcome to the release team!

**Comment by Checksumz** [comment]
Thanks for having me in the team @kcmartin @katcosgrove :)

**Comment by jasonbraganza** [comment]
@kcmartin, would you kindly update your place of work on this issue or on your github profile?
Asking because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require sponsors be from two different orgs.
Thank you.

**Comment by kcmartin** [comment]
Hi, I am currently unaffiliated/independent.

**Comment by jasonbraganza** [comment]
/assign

@Checksumz, look forward to your contributions 🙂

I've created  PR #4686 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by Checksumz** [comment]
Yay 😊 🎊.

Thank you @jasonbraganza
