### ISSUE TITLE
REQUEST: New membership for DanielXiao

### ISSUE THREAD

**Issue by DanielXiao** [kubernetes/org#4685]
### GitHub Username

DanielXiao

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

HanFa

### Sponsor 2

wyike

### List of contributions to the Kubernetes project

- PRs reviewed / authored
- - https://github.com/kubernetes/cloud-provider-vsphere/pull/796
- - https://github.com/kubernetes/cloud-provider-vsphere/pull/810
- - https://github.com/kubernetes/cloud-provider-vsphere/pull/807
- Issues responded to
- - https://github.com/kubernetes/cloud-provider-vsphere/issues/792
- - https://github.com/kubernetes/cloud-provider-vsphere/issues/789
- - https://github.com/kubernetes/cloud-provider-vsphere/issues/808
- SIG projects I am involved with
- - kubernetes/cloud-provider-vsphere

**Comment by wyike** [comment]
+1
Thanks Yifeng for the contributions!

**Comment by HanFa** [comment]
+1 Thanks for the contributions!

**Comment by DanielXiao** [comment]
@mrbobbytables Could you help to confirm if I meet the requirements for requesting membership?

**Comment by jasonbraganza** [comment]
/assign
@DanielXiao, thank you for all your contributions so far 🙂

I've created PR #4693 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
