### ISSUE TITLE
REQUEST: New membership for mloskot

### ISSUE THREAD

**Issue by mloskot** [kubernetes/org#4687]
### GitHub Username

@mloskot

### Organization you are requesting membership in

@kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@knabben

### Sponsor 2

@jsturtevant

### List of contributions to the Kubernetes project

 - PRs reviewed / authored
    - https://github.com/search?q=org%3Akubernetes+mloskot&type=commits
    - https://github.com/search?q=org%3Akubernetes-sigs+mloskot&type=commits

- Issues responded to
    - https://github.com/search?q=org%3Akubernetes+mloskot&type=issues
    - https://github.com/search?q=org%3Akubernetes-sigs+mloskot&type=issues

- SIG projects I am involved with
    - SIG Windows

**Comment by knabben** [comment]
Matheusz has been working in SIG-Windows for quite some time. 
He has provided guidance, vision, and development efforts for sub-projects. 

+1 for sure!

**Comment by jasonbraganza** [comment]
Note: approvals in issue #4688.

**Comment by jasonbraganza** [comment]
/assign

PR #4693 should get a membership invite notification to this sig too. Welcome again :)
