### ISSUE TITLE
REQUEST: New membership for mloskot

### ISSUE THREAD

**Issue by mloskot** [kubernetes/org#4688]
### GitHub Username

@mloskot

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@knabben

### Sponsor 2

@jsturtevant

### List of contributions to the Kubernetes project

 - PRs reviewed / authored
    - https://github.com/search?q=org%3Akubernetes-sigs+mloskot&type=commits

- Issues responded to
    - https://github.com/search?q=org%3Akubernetes-sigs+mloskot&type=issues

- SIG projects I am involved with
    - SIG Windows

**Comment by knabben** [comment]
Matheusz has been working in SIG-Windows for quite some time.
He has provided guidance, vision, and development efforts for sub-projects.

+1 for sure!

**Comment by jsturtevant** [comment]
+1 thanks for jumping in and helping bring clarity to the dev-tools sub project

**Comment by jsturtevant** [comment]
I think the request for both memberships can/should be on the same issue (https://github.com/kubernetes/org/issues/4687)?

**Comment by mloskot** [comment]
@jsturtevant I couldn't see how to select two items from the drop-down list and I followed #2248 and #2940 as an example.

**Comment by jasonbraganza** [comment]
/assign
@mloskot, thank you for all your contributions so far 🙂

I've created PR #4693 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by mloskot** [comment]
Thank you @jasonbraganza @jsturtevant @knabben !
