### ISSUE TITLE
REQUEST: New membership for satyampsoni

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/org#4689]
### GitHub Username

satyampsoni

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@rashansmith 

### Sponsor 2

@katcosgrove

### List of contributions to the Kubernetes project

- Pull requests
https://github.com/kubernetes/website/pull/43227
https://github.com/kubernetes/website/pull/43161
https://github.com/kubernetes/website/pull/43117
https://github.com/kubernetes/website/pull/42929
https://github.com/kubernetes/website/pull/41584

- Issues
https://github.com/kubernetes/website/issues/43262
https://github.com/kubernetes/website/issues/43291
https://github.com/kubernetes/website/issues/41576
https://github.com/kubernetes/website/issues/43249
https://github.com/kubernetes/website/issues/43271
https://github.com/kubernetes/contributor-site/issues/441

- Reviews
https://github.com/kubernetes/kubernetes/pull/120393/files/76919e9569746e4e1ae0ec190892af3a142553c9
https://github.com/kubernetes/website/pull/43246/files/c1f4b7bdcf3b8b680d615267d237e491295cdc7a

Additionally, I am a release notes shadow for the v1.30.

**Comment by katcosgrove** [comment]
+1

Welcome to the release team!

**Comment by rashansmith** [comment]
+1

Welcome to the team!!

**Comment by satyampsoni** [comment]
@katcosgrove @rashansmith Thanks for having me in the team and sponsoring me!!

**Comment by jasonbraganza** [comment]
@rashansmith would you kindly update your working org, on this issue or your profile?
Need this, because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require sponsors be from different orgs.
Thank you :)

**Comment by jasonbraganza** [comment]
/assign
@satyampsoni, thank you for all your contributions so far 🙂

I've created PR #4695 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
