### ISSUE TITLE
REQUEST: New membership for shraddhabang

### ISSUE THREAD

**Issue by shraddhabang** [kubernetes/org#4691]
### GitHub Username

shraddhabang

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

elmiko

### Sponsor 2

oliviassss

### PRs authored
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3532
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3314
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3332

### SIG project I am actively involved
https://github.com/kubernetes-sigs/aws-load-balancer-controller/

**Comment by elmiko** [comment]
+1 from me, thanks for your contributions @shraddhabang

**Comment by oliviassss** [comment]
+1, thanks for your contribution especially to aws-load-balancer-controller

**Comment by jasonbraganza** [comment]
/assign
@shraddhabang, thank you for all your contributions so far 🙂

I've created PR #4693 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
