### ISSUE TITLE
REQUEST: New membership for Ithrael

### ISSUE THREAD

**Issue by Ithrael** [kubernetes/org#4694]
### GitHub Username

ithrael

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

ardaguclu

### Sponsor 2

seans3

### List of contributions to the Kubernetes project

PR
https://github.com/kubernetes/kubernetes/pull/120119
https://github.com/kubernetes/kubernetes/pull/120195
https://github.com/kubernetes/kubernetes/pull/120159
https://github.com/kubernetes/kubernetes/pull/120118
https://github.com/kubernetes/kubernetes/pull/122587
https://github.com/kubernetes/kubernetes/pull/120444

Issue
https://github.com/kubernetes/kubernetes/issues/122546
https://github.com/kubernetes/kubernetes/issues/122531
https://github.com/kubernetes/kubernetes/issues/120331
https://github.com/kubernetes/kubectl/issues/1467
https://github.com/kubernetes/kubectl/issues/1470
https://github.com/kubernetes/kubectl/issues/1474
https://github.com/kubernetes/kubernetes/issues/122527
https://github.com/kubernetes/kubectl/issues/1242

**Comment by mpuckett159** [comment]
+1 for me thank you for your contributions ❤️

**Comment by seans3** [comment]
+1 Thanks for you commitment

**Comment by jasonbraganza** [comment]
/assign
@Ithrael, thank you for all your contributions so far 🙂

I've created PR #4695 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by ardaguclu** [comment]
+1
Thank you for your commitment @Ithrael
