### ISSUE TITLE
REQUEST: New membership for sfzylad

### ISSUE THREAD

**Issue by sfzylad** [kubernetes/org#470]
### GitHub Username
e.g. (at)example_user

@sfzylad

### Organization you are requesting membership in
e.g. (at)kubernetes

@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @phyber 
- @randomvariable 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * Authored
    * Cluster API Provider AWS
      * kubernetes-sigs/cluster-api-provider-aws#510
      * kubernetes-sigs/cluster-api-provider-aws#538
      * kubernetes-sigs/cluster-api-provider-aws#541
      * kubernetes-sigs/cluster-api-provider-aws#518
      * kubernetes-sigs/cluster-api-provider-aws#517
      * kubernetes-sigs/cluster-api-provider-aws#506
- Issues responded to
  * kubernetes-sigs/cluster-api-provider-aws#536
- SIG projects I am involved with
  * SIG AWS
  * SIG Cluster Lifecycle

**Comment by phyber** [comment]
👍

**Comment by randomvariable** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @sfzylad. Unfortunately @phyber cannot sponsor for org membership. A sponsor must be an approver or reviewer in an associated org. 

Additionally, @randomvariable cannot sponsor you for membership in the @kubernetes org, but CAN sponsor you for membership in @kubernetes-sigs.

An approver/reviewer in @kubernetes, may sponsor someone for the @kubernetes org or any of the related organizations (@kubernetes-sigs, @kubernetes-csi etc); as long as it's a project they're involved with.

However, this does not work the other way around. A sponsor that is only an approver/reviewer in @kubernetes-sigs cannot sponsor someone for membership in @kubernetes. They are scoped just to the org they're associated with.

@sfzylad Is there another person who may be able to sponsor you for @kubernetes? or possibly rescope to just @kubernetes-sigs and a sponsor from there?

If you have any questions don't be afraid to ask.

Thanks!

**Comment by randomvariable** [comment]
Thanks for this. @sfzylad - probably appropriate to drop kubernetes org for now. check in Slack #cluster-api  for a non-VMware sponsor.

**Comment by sfzylad** [comment]
@randomvariable You are right. I dropped `kubernetes` org an will ask on slack. Thank you!

**Comment by mrbobbytables** [comment]
@sfzylad Have you found another sponsor by chance?

**Comment by sfzylad** [comment]
@mrbobbytables I haven't yet. I was on holiday for some time so I was not actively looking.

**Comment by mrbobbytables** [comment]
@sfzylad  Checking back in, have you happened to find another sponsor?

**Comment by sfzylad** [comment]
@mrbobbytables No luck so far.

**Comment by mrbobbytables** [comment]
If that is the case, it may be worth closing the issue and reopening it again when you find a second sponsor. =/

**Comment by ashish-amarnath** [comment]
@sfzylad / @mrbobbytables lmk if I can help here!

**Comment by mrbobbytables** [comment]
@ashish-amarnath with your +1 @sfzylad could be added to @kubernetes-sigs :)

**Comment by ashish-amarnath** [comment]
+1

**Comment by mrbobbytables** [comment]
With the additional +1 I've cut PR #607 to add you to @kubernetes-sigs :)
 Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

/pony pie
(for π day)

**Comment by sfzylad** [comment]
Happy times, thank you kindly! :)
