### ISSUE TITLE
REQUEST: Migrate cncf-infra/verify-conformance

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/org#4706]
### New repo, staging repo, or migrate existing

verify-conformance

### Is it a staging repo?

yes

### Requested name for new repository

verify-conformance

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

hh, heyste, iiamabby, BobyMCbobs

### Who should have write access?

hh, heyste, iiamabby, BobyMCbobs

### Who should be listed as approvers in OWNERS?

hh, heyste, iiamabby, BobyMCbobs

### Who should be listed in SECURITY_CONTACTS?

hh, heyste, iiamabby, BobyMCbobs

### What should the repo description be?

CNCF CI bot for verifying Kubernetes conformance product submissions

### What SIG and subproject does this fall under?

sig-architecture

### Please provide references to appropriate approval for this new repo

- https://kubernetes.slack.com/archives/C78F00H99/p1683662771165129
- https://kubernetes.slack.com/archives/C78F00H99/p1683663250267499
- https://groups.google.com/u/3/g/kubernetes-sig-architecture/c/bEx9fppYQ0Q/m/8ZyumVYUBwAJ
- https://kubernetes.slack.com/archives/C5P3FE08M/p1716308667903599?thread_ts=1705005057.105709&cid=C5P3FE08M

### Additional context for request

CNCF is wanting to donate Kubernetes conformance infrastructure (cncf/apisnoop, cncf-infra/verify-conformance, [conformance-gate](https://git.k8s.io/test-infra/config/jobs/kubernetes/sig-arch/conformance-gate.yaml)) to sig-architecture and sig-k8s-infra.

**Comment by BobyMCbobs** [comment]
For visibility 
cc @MadhavJivrajani

**Comment by BobyMCbobs** [comment]
Migrating the GitHub App (https://github.com/organizations/cncf-infra/settings/apps/prow-cncf-io) is also a required part of this task.

**Comment by jeefy** [comment]
Ping @kubernetes/owners :) 

/remove-lifecycle stale

**Comment by BenTheElder** [comment]
The problem isn't kubernetes/owners, we need the SIG TLs to accept/deny. Will ping SIG Arch again.

**Comment by johnbelamaric** [comment]
/lgtm

+1 with sig arch hat

**Comment by dims** [comment]
/lgtm

+1 with sig arch hat

**Comment by BenTheElder** [comment]
This is approved, we also have Derek's +1 in the mailinglist thread.

So now it's over to @kubernetes/owners 🙏

**Comment by mrbobbytables** [comment]
Okay, once the 2 open PRs are merged things should be good to go.
There is one follow up item - iiamabby was not a member of k-sigs and that can be handled later + adding to the team.

**Comment by BobyMCbobs** [comment]
@mrbobbytables, thank you kindly for your help! Woohoo!
