### ISSUE TITLE
REQUEST: New membership for Okabe-Junya

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/org#4708]
### GitHub Username

@Okabe-Junya

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@atoato88

### Sponsor 2

@nasa9084

### List of contributions to the Kubernetes project

- PRs: https://github.com/pulls?q=+is%3Apr+author%3AOkabe-Junya+org%3Akubernetes+

**Comment by nasa9084** [comment]
He's recently contributing to Japanese localization
+1

**Comment by jasonbraganza** [comment]
@atoato88, would you kindly update your work org on this issue or your profile?
Asking because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require that sponsors be from discrete orgs.

**Comment by atoato88** [comment]
@jasonbraganza 
I've updated my profile.
Could you check that?

**Comment by jasonbraganza** [comment]
Thank you muchly, @atoato88 :) This helps

**Comment by jasonbraganza** [comment]
/assign

@Okabe-Junya, thank you for all your contributions 🙂

I’ve created PR #4718 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
