### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for @figo

### ISSUE THREAD

**Issue by figo** [kubernetes/org#471]
### GitHub Username
@figo 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
I am already a member of @kubernetes and starting to work on https://github.com/kubernetes-sigs/cluster-api-provider-vsphere and https://github.com/kubernetes-sigs/cluster-api

**Comment by mrbobbytables** [comment]
Hey there @figo. I've created PR #473 to add you to the @kubernetes-sigs org. Once it gets merged, you should get a membership invite notification. :)

/assign
