### ISSUE TITLE
REQUEST: New membership for sieben

### ISSUE THREAD

**Issue by sieben** [kubernetes/org#472]
### GitHub Username

@sieben 

### Organization you are requesting membership in

@kubernetes

### Requirements

- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @zacharysarah 
- @Smana 

### List of contributions to the Kubernetes project

I work with for sig-docs on the French localization of the Kubernetes project.

https://github.com/kubernetes/website/pull/12548

**Comment by Smana** [comment]
+1

**Comment by zacharysarah** [comment]
+1 - @sieben is part of the new French localization.

**Comment by mrbobbytables** [comment]
I will add a +1 to sponsor as well :) Thanks for kicking off the French translation efforts!

**Comment by mrbobbytables** [comment]
@sieben, thanks for starting the French translations efforts :)
I've created PR #481  to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
