### ISSUE TITLE
Enable Equinix runners for the etcd org

### ISSUE THREAD

**Issue by palnabarun** [kubernetes/org#4722]
### Organization or Repo

etcd-io

### Describe the issue

CNCF provides apparently provides Equinix runners for projects. etcd-io org wants to run their CI on large runners and the

**Comment by cblecker** [comment]
Are there docs for what is needed here?

**Comment by mrbobbytables** [comment]
/assign @jeefy 
(assigning to get on radar)
do you have any details you can pass our way? This would be to set it large runners either with actuated.dev or the new preferred solution.

**Comment by jeefy** [comment]
We recently set up [GitHub ARC](https://github.com/actions/actions-runner-controller) in Equinix and Oracle in a fashion that autoscales as jobs spin up. Unfortunately it's per GHE, so I would have to set it up separately for the K8s GHE. 

We can talk more about this at KubeCon, but it would be a low lift to set up, and the etcd jobs would just need to change the etcd jobs `runs-on` attribute.

**Comment by cblecker** [comment]
Let's do it! We have a lot of conference driven development lined up for next week haha
