### ISSUE TITLE
REQUEST: New membership for adityabhatia

### ISSUE THREAD

**Issue by adityabhatia** [kubernetes/org#4724]
### GitHub Username

adityabhatia

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@killianmuldoon 

### Sponsor 2

@sbueringer

### List of contributions to the Kubernetes project

Some of my recent contributions:

Issues:
https://github.com/kubernetes-sigs/cluster-api/issues/9532
https://github.com/kubernetes-sigs/cluster-api/issues/9623
https://github.com/kubernetes-sigs/cluster-api/issues/9969
https://github.com/kubernetes-sigs/cluster-api/issues/9434
https://github.com/kubernetes-sigs/cluster-api/issues/9589
https://github.com/kubernetes-sigs/cluster-api/issues/9636
https://github.com/kubernetes-sigs/cluster-api/issues/9851
https://github.com/kubernetes-sigs/cluster-api/issues/10045
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1354
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2058
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2357

Pull requests:
https://github.com/kubernetes-sigs/cluster-api/pull/9471
https://github.com/kubernetes-sigs/cluster-api/pull/9622
https://github.com/kubernetes-sigs/cluster-api/pull/9740
https://github.com/kubernetes-sigs/cluster-api/pull/9865
https://github.com/kubernetes-sigs/cluster-api/pull/9866
https://github.com/kubernetes-sigs/cluster-api/pull/9970
https://github.com/kubernetes-sigs/cluster-api/pull/9985
https://github.com/kubernetes-sigs/cluster-api/pull/10003
https://github.com/kubernetes-sigs/cluster-api/pull/10029
https://github.com/kubernetes-sigs/cluster-api/pull/10039
https://github.com/kubernetes-sigs/cluster-api/pull/10048
https://github.com/kubernetes-sigs/cluster-api/pull/10057
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2312
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2378
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2410
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2484
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2626

**Comment by sbueringer** [comment]
+1

Thank you very much for all your contributions, and welcome :)

**Comment by Priyankasaggu11929** [comment]
/assign

@adityabhatia, thank you for all your contributions 🙂

I’ve created PR https://github.com/kubernetes/org/pull/4729 to add you to the Kubernetes(s) Org.
Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
