### ISSUE TITLE
REQUEST: New membership for B1F030

### ISSUE THREAD

**Issue by B1F030** [kubernetes/org#4732]
### GitHub Username

@B1F030

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kerthcet

### Sponsor 2

@tenzen-y

### List of contributions to the Kubernetes project

PRs authored:
https://github.com/kubernetes-sigs/kueue/pull/1225
https://github.com/kubernetes-sigs/kueue/pull/1286
https://github.com/kubernetes-sigs/kueue/pull/1305
https://github.com/kubernetes-sigs/kueue/pull/1314
https://github.com/kubernetes-sigs/kueue/pull/1331
https://github.com/kubernetes-sigs/kueue/pull/1423
https://github.com/kubernetes-sigs/kueue/pull/1493
https://github.com/kubernetes-sigs/kueue/pull/1507
https://github.com/kubernetes-sigs/kueue/pull/1525
https://github.com/kubernetes-sigs/kueue/pull/1560
https://github.com/kubernetes-sigs/kueue/pull/1567
https://github.com/kubernetes-sigs/kueue/pull/1385
Issues responded to:
https://github.com/kubernetes-sigs/kueue/issues/1276
https://github.com/kubernetes-sigs/kueue/issues/1315
https://github.com/kubernetes-sigs/kueue/issues/1459
https://github.com/kubernetes-sigs/kueue/issues/1649
https://github.com/kubernetes-sigs/kueue/issues/1198
https://github.com/kubernetes-sigs/kueue/issues/1230
https://github.com/kubernetes-sigs/kueue/issues/1235
https://github.com/kubernetes-sigs/kueue/issues/1309
https://github.com/kubernetes-sigs/kueue/issues/1359
https://github.com/kubernetes-sigs/kueue/issues/1461
https://github.com/kubernetes-sigs/kueue/issues/1484
https://github.com/kubernetes-sigs/kueue/issues/1503
https://github.com/kubernetes-sigs/kueue/issues/1593
https://github.com/kubernetes-sigs/kueue/issues/754
https://github.com/kubernetes-sigs/kueue/issues/1224
https://github.com/kubernetes-sigs/kueue/issues/1345
https://github.com/kubernetes-sigs/kueue/issues/1651

**Comment by kerthcet** [comment]
+100, @B1F030 is enthusiastic about the open source technologies especially cloud native ones, and he is really diligent about the works. Hopes to see more contributions in the future!

**Comment by tenzen-y** [comment]
+1

Thank you for your contributions! I'm really looking forward to more collaborations with you!

**Comment by jasonbraganza** [comment]
/assign

@B1F030, thank you for all your contributions 🙂

I’ve created PR #4738  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
