### ISSUE TITLE
REQUEST: New membership for faiq

### ISSUE THREAD

**Issue by faiq** [kubernetes/org#4733]
### GitHub Username

faiq

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@richcase

### Sponsor 2

@dlipovetsky

### List of contributions to the Kubernetes project

I am already a part of kubernetes sigs, but I need access to this organization to review the test infra - see issue https://github.com/kubernetes/test-infra/pull/31176 

https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=author%3Afaiq+
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pulls?q=is%3Apr+author%3Afaiq+is%3Aclosed
https://github.com/kubernetes-sigs/kind/pull/1690
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/708

**Comment by jasonbraganza** [comment]
@faiq, done!  (as soon as PR #4739 gets merged)
Thank you for all you do.
