### ISSUE TITLE
REQUEST: Netlify site for kubernetes-sigs/cluster-api-provider-gcp

### ISSUE THREAD

**Issue by salasberryfin** [kubernetes/org#4736]
### Repository

kubernetes-sigs/cluster-api-provider-gcp

### Project domain

cluster-api-gcp.sigs.k8s.io

### Additional context for request

The PR that adds `netlify.toml` configuration file: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1131.

**Comment by salasberryfin** [comment]
The PR with the netlify configuration has now been merged.

**Comment by damdo** [comment]
Based on previous similar request issues 
/assign @mrbobbytables @cblecker

**Comment by cpanato** [comment]
+1

**Comment by cblecker** [comment]
DNS changes are pending, but also build is failing:
```
3:56:28 PM: build.command from netlify.toml                               
3:56:28 PM: ────────────────────────────────────────────────────────────────
3:56:28 PM: ​
3:56:28 PM: $ make -C docs/book build
3:56:28 PM: make: Entering directory "/opt/build/repo/docs/book"
3:56:28 PM: make -C /opt/build/repo/hack/tools bin/mdbook
3:56:28 PM: make[1]: Entering directory "/opt/build/repo/hack/tools"
3:56:28 PM: mkdir -p bin
3:56:28 PM: mkdir -p share
3:56:28 PM: curl -sL -o share/mdbook.tar.gz "https://github.com/rust-lang/mdBook/releases/download/v0.4.5/mdBook-v0.4.5-x86_64-unknown-linux-gnu.tar.gz"
3:56:28 PM: tar xfvz share/mdbook.tar.gz -C bin
3:56:28 PM: mdbook
3:56:28 PM: chmod +x bin/mdbook
3:56:28 PM: touch -m bin/mdbook
3:56:28 PM: make[1]: Leaving directory "/opt/build/repo/hack/tools"
3:56:28 PM: make -C /opt/build/repo/hack/tools bin/mdbook-tabulate
3:56:28 PM: make[1]: Entering directory "/opt/build/repo/hack/tools"
3:56:28 PM: go build -tags=tools -o bin/mdbook-tabulate sigs.k8s.io/cluster-api/hack/tools/mdbook/tabulate
3:56:28 PM: go: errors parsing go.mod:
3:56:28 PM: /opt/build/repo/hack/tools/go.mod:5: unknown directive: toolchain
3:56:28 PM: make[1]: *** [Makefile:64: bin/mdbook-tabulate] Error 1
3:56:28 PM: make[1]: Leaving directory "/opt/build/repo/hack/tools"
3:56:28 PM: make: *** [Makefile:31: /opt/build/repo/hack/tools/bin/mdbook-tabulate] Error 2
3:56:28 PM: make: Leaving directory "/opt/build/repo/docs/book"
3:56:28 PM: ​
3:56:28 PM: "build.command" failed                                        
3:56:28 PM: ────────────────────────────────────────────────────────────────
```

Please fix the build errors in your repo. Thanks!

**Comment by cblecker** [comment]
I'm guessing the above is related to the go version that is being used in netlify. Please see: https://docs.netlify.com/configure-builds/manage-dependencies/#go

**Comment by salasberryfin** [comment]
Thanks @cblecker. I haven't been able to reproduce this error. Netlify's configuration includes the `GO_VERSION` environment variable https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/f710e8629d17e45d2035071107778fadaba814db/netlify.toml#L7 and it matches the version used in `go.mod`, shouldn't this be enough to set the build version?

**Comment by damdo** [comment]
Check this out https://answers.netlify.com/t/is-go-1-21-not-supported-by-the-build-image/109325/2

**Comment by salasberryfin** [comment]
Thanks @damdo, looks like that was it. This PR https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1146 adds the patch version to the configuration.

**Comment by cblecker** [comment]
Looks like the site is online. Please let us know if you run into issues. 

/close
