### ISSUE TITLE
REQUEST: Create  a repository for a new deployment API LeaderWorkerSet

### ISSUE THREAD

**Issue by liurupeng** [kubernetes/org#4737]
### New repo, staging repo, or migrate existing

New repo

### Is it a staging repo?

no

### Requested name for new repository

~LeaderWorkerSet~ lws

(per https://github.com/kubernetes/org/issues/4737#issuecomment-1951656252)

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

liurupeng, ahg-g

### Who should have write access?

liurupeng, ahg-g

### Who should be listed as approvers in OWNERS?

liurupeng, ahg-g

### Who should be listed in SECURITY_CONTACTS?

liurupeng, ahg-g

### What should the repo description be?

LeaderWorkerSet: An API for deploying a group of pods as a unit of replication

### What SIG and subproject does this fall under?

sig-apps, workloads-api (per https://github.com/kubernetes/org/issues/4737#issuecomment-1958781079)

### Please provide references to appropriate approval for this new repo

http://bit.ly/k8s-LWS

**Comment by ahg-g** [comment]
@liurupeng this is not a "staging repo"

**Comment by janetkuo** [comment]
LGTM 👍 

@soltysh @kow3ns FYI

**Comment by soltysh** [comment]
:+1: from me as well

**Comment by cblecker** [comment]
We don't typically do camelcase for repos. We use dashes to separate words.

Would you prefer:
- leaderworkerset
- leader-worker-set

**Comment by ahg-g** [comment]
Can we do lws?

**Comment by cblecker** [comment]
Yeah, that works.

@janetkuo @soltysh Either of you have concerns with the name "kubernetes-sigs/lws"?

**Comment by janetkuo** [comment]
No concerns from me.

**Comment by ahg-g** [comment]
Thanks @janetkuo; @cblecker can we please go ahead then?

**Comment by Priyankasaggu11929** [comment]
Thanks for the +1s. I'll go ahead with creating the repo `kubernetes-sigs/lws`

**Comment by Priyankasaggu11929** [comment]
New repo is created - https://github.com/kubernetes-sigs/lws :tada: 

- PR to add GitHub teams for the new repo: https://github.com/kubernetes/org/pull/4780

   (Note: @liurupeng is not part of k-sigs org atm, so, the tool doesn't allow adding their username to GH Teams.)

- @ahg-g, the requested new repo will be part of which [subproject](https://github.com/kubernetes/community/tree/master/sig-apps#subprojects) of sig-apps?

**Comment by ahg-g** [comment]
Thank you @Priyankasaggu11929 !

It will be part of "workloads-api"

**Comment by Priyankasaggu11929** [comment]
Repo setup is completed. All PRs are merged.

/close
