### ISSUE TITLE
REQUEST: New membership for adityasamant25

### ISSUE THREAD

**Issue by adityasamant25** [kubernetes/org#4740]
### GitHub Username

@adityasamant25

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dipesh-rawat

### Sponsor 2

@natalisucks

### List of contributions to the Kubernetes project

- PRs authored:
https://github.com/kubernetes/website/pull/44875
https://github.com/kubernetes/website/pull/44832
https://github.com/kubernetes/website/pull/44752
https://github.com/kubernetes/website/pull/44748
https://github.com/kubernetes/kubernetes/pull/122672
https://github.com/kubernetes/website/pull/44693
https://github.com/kubernetes/website/pull/44594
https://github.com/kubernetes/website/pull/44540
https://github.com/kubernetes/website/pull/44569
https://github.com/kubernetes/website/pull/44322
https://github.com/kubernetes/website/pull/44266
https://github.com/kubernetes/website/pull/44239
https://github.com/kubernetes/website/pull/44234
https://github.com/kubernetes/website/pull/44050
https://github.com/kubernetes/website/pull/40514

- PRs reviewed:
https://github.com/kubernetes/website/pull/40241
https://github.com/kubernetes/website/pull/44683
https://github.com/kubernetes/website/pull/44290
https://github.com/kubernetes/website/pull/44279

- Issues responded to:
https://github.com/kubernetes/website/issues/44866
https://github.com/kubernetes/website/issues/44825
https://github.com/kubernetes/website/issues/44756
https://github.com/kubernetes/website/issues/44749
https://github.com/kubernetes/website/issues/44728
https://github.com/kubernetes/website/issues/44706
https://github.com/kubernetes/website/issues/44687
https://github.com/kubernetes/website/issues/44651
https://github.com/kubernetes/website/issues/44558
https://github.com/kubernetes/website/issues/44538
https://github.com/kubernetes/website/issues/44379
https://github.com/kubernetes/website/issues/44375
https://github.com/kubernetes/website/issues/44359
https://github.com/kubernetes/website/issues/44321
https://github.com/kubernetes/website/issues/44271
https://github.com/kubernetes/website/issues/44236
https://github.com/kubernetes/website/issues/44216
https://github.com/kubernetes/website/issues/44189
https://github.com/kubernetes/website/issues/44087
https://github.com/kubernetes/website/issues/43256
https://github.com/kubernetes/website/issues/42777
https://github.com/kubernetes/website/issues/42713
https://github.com/kubernetes/website/issues/41438
https://github.com/kubernetes/website/issues/40645
https://github.com/kubernetes/website/issues/40114

- SIG projects I am involved with:
[sig-docs](https://github.com/kubernetes/community/blob/master/sig-docs/README.md)

**Comment by dipesh-rawat** [comment]
+1 from me. I support this and am happy to sponsor.

@adityasamant25 Although LFC102 is an optional course, I still recommend taking it. Thank you for all your contributions!
Look forward to even more from you in the future. 🚀

/pony party

**Comment by natalisucks** [comment]
+1 from me for Aditya's sponsorship, and I also agree with @dipesh-rawat that taking the optional Inclusive Open Source Community Course would be worthwhile 👍 

/honk

**Comment by jasonbraganza** [comment]
/assign

@adityasamant25, thank you for all your contributions 🙂

I’ve created PR #4743 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
