### ISSUE TITLE
REQUEST: New membership for antoooks

### ISSUE THREAD

**Issue by antoooks** [kubernetes/org#4741]
### GitHub Username

@antoooks

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@koba1t

### Sponsor 2

@varshaprasad96

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/kustomize/issues/5404
- https://github.com/kubernetes-sigs/kustomize/issues/4982
- https://github.com/kubernetes-sigs/kustomize/issues/5449
- https://github.com/kubernetes-sigs/kustomize/issues/5526

**Comment by natasha41575** [comment]
+1 from me!

**Comment by koba1t** [comment]
+1 from me!
Thanks for your contributions!

**Comment by natasha41575** [comment]
Hey actually I am just realizing, the guidelines say the following:

> Sponsors must be reviewers or approvers in at least one OWNERS file within one of the [Kubernetes GitHub organizations](https://github.com/kubernetes/community/blob/master/github-management#actively-used-github-organizations)*.

I am no longer a reviewer or approver in kustomize (or any other k8s project) as of https://github.com/kubernetes/org/pull/4723, so you may need to find another sponsor.

**Comment by antoooks** [comment]
Thanks for clarifying, it is unfortunate that Natasha had to leave. I have asked Varsha to approve my membership request @varshaprasad96, huge thanks !

**Comment by varshaprasad96** [comment]
@antoooks welcome :)
+1!
/lgtm

**Comment by jasonbraganza** [comment]
/assign

@antoooks, thank you for all your contributions 🙂

I’ve created PR #4746 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
