### ISSUE TITLE
REQUEST: New membership for muraee

### ISSUE THREAD

**Issue by muraee** [kubernetes/org#4744]
### GitHub Username

@muraee

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@vincepri

### Sponsor 2

@richardcase

### List of contributions to the Kubernetes project

- cluster-api-provider-aws:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4037
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4147
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4347
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4453
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4665
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4725
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4742
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4759
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4761

- cluster-api
https://github.com/kubernetes-sigs/cluster-api/issues/3486
https://github.com/kubernetes-sigs/cluster-api/pull/9262

**Comment by vincepri** [comment]
+1
