### ISSUE TITLE
REQUEST: New membership for cooldracula

### ISSUE THREAD

**Issue by cooldracula** [kubernetes/org#4745]
### GitHub Username

cooldracula

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@BobyMcBobs

### Sponsor 2

@hh

### List of contributions to the Kubernetes project

- Multiple PR's reviewed and authored in [kubernetes-sigs/apisnoop](https://github.com/kubernetes-sigs/apisnoop)
- Multiple issues for APISnoop
- Multiple PR's reviewed and authored for the prow job [apisnoop-conformance-gate](https://testgrid.k8s.io/sig-arch-conformance#apisnoop-conformance-gate)

**Comment by hh** [comment]
@cooldracula was heavily involved in the creation of apisnoop and the conformance bot. 
We moved the repo from cncf to Kubernetes-sigs and need him to maintain access to the repo.

**Comment by BobyMCbobs** [comment]
@cooldracula has been instrumentally important in sig-architecture's conformance working group for mapping and making it easy to understand the progress through [apisnoop.cncf.io](https://apisnoop.cncf.io) (as listed above). 

+1 from me

**Comment by jasonbraganza** [comment]
@BobyMCbobs would you kindly update your work org, either on your profile or mention it here in the issue? Asking because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require sponsors be from different orgs.

**Comment by MadhavJivrajani** [comment]
just xref, this is needed for completion of https://github.com/kubernetes/org/issues/4705

**Comment by jasonbraganza** [comment]
@BobyMCbobs please help :)

**Comment by BobyMCbobs** [comment]
@jasonbraganza, thank you for assisting. @hh and I work together. Keen to find a sponsor from another org.

**Comment by MadhavJivrajani** [comment]
I'm happy to sponsor here @jasonbraganza 

+1

**Comment by BobyMCbobs** [comment]
@MadhavJivrajani, appreciate your help. What are the next steps and is there any way I'm able to help?

**Comment by MadhavJivrajani** [comment]
Thank you for all your contributions 🙂

I’ve created PR https://github.com/kubernetes/org/pull/4772 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉
