### ISSUE TITLE
REQUEST: Netlify site for Jobset

### ISSUE THREAD

**Issue by moficodes** [kubernetes/org#4748]
### Repository

kubernetes-sigs/jobset

### Project domain

jobset.sigs.k8s.io

**Comment by moficodes** [comment]
@danielvegamyhre FYI ⬆️

**Comment by danielvegamyhre** [comment]
cc @ahg-g

**Comment by moficodes** [comment]
The PR with the hugo changes are already merged in the repo.

Already has the netlify configuration.

https://github.com/kubernetes-sigs/jobset/pull/402

**Comment by cblecker** [comment]
temp site is here pending DNS changes: https://kubernetes-sigs-jobset.netlify.app/

**Comment by moficodes** [comment]
@cblecker Saw your suggestion on the cname pr. Does this mean this would also have to update to kubernetes-docs.netlifyglobalcdn.com ?

**Comment by cblecker** [comment]
@moficodes Nope! The site should be fully set up now, and TLS should provision automatically within 24 hours: https://jobset.sigs.k8s.io/

/close
