### ISSUE TITLE
REQUEST: New membership for koksay

### ISSUE THREAD

**Issue by koksay** [kubernetes/org#4751]
### GitHub Username

@koksay

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xmudrii

### Sponsor 2

@dims

### List of contributions to the Kubernetes project

- I'm involved with sig-k8s-infra
- PRs I authored: 
  - https://github.com/kubernetes/k8s.io/pull/6170
  - https://github.com/kubernetes/k8s.io/pull/6345
  - https://github.com/kubernetes/k8s.io/pull/6360
  - https://github.com/kubernetes/k8s.io/pull/6361
  - https://github.com/kubernetes/k8s.io/pull/6379

**Comment by xmudrii** [comment]
+1 💯

**Comment by ameukam** [comment]
+1

**Comment by dims** [comment]
+1 from me!

**Comment by jasonbraganza** [comment]
/assign

@koksay, thank you for all your contributions 🙂

I’ve created PR #4753 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by koksay** [comment]
Thanks, @jasonbraganza, it's great to be here!

Thank you, @xmudrii @ameukam @dims, for your support!
