### ISSUE TITLE
REQUEST: Migrate jpbetz/auger to etcd-io/auger

### ISSUE THREAD

**Issue by jmhbnz** [kubernetes/org#4754]
### New repo, staging repo, or migrate existing

Migrate existing

### Is it a staging repo?

no

### Requested name for new repository

auger

### Which Organization should it reside

etcd-io

### Who should have write access?

Refer existing OWNERS in jpbetz/auger

### Who should be listed as approvers in OWNERS?

Refer existing OWNERS in jpbetz/auger

### Who should be listed in SECURITY_CONTACTS?

Refer existing SECURITY_CONTACTS in jpbetz/auger

### What should the repo description be?

Directly access data objects stored in etcd by kubernetes.

### What SIG and subproject does this fall under?

sig-etcd

### Please provide references to appropriate approval for this new repo

https://github.com/jpbetz/auger/issues/42

**Comment by jmhbnz** [comment]
cc @wenjiaswe, @siyuanfoundation, @ahrtr, @serathius, @jpbetz

**Comment by serathius** [comment]
+1

**Comment by ahrtr** [comment]
+1

Thanks @jmhbnz for driving this.

**Comment by wenjiaswe** [comment]
+1 Thanks!

**Comment by siyuanfoundation** [comment]
+1. Thanks James for leading this!

**Comment by jpbetz** [comment]
+1

Thank you all for finding a home for auger.

**Comment by mrbobbytables** [comment]
/assign
@jpbetz I'll invite you to our intermediate org to transfer the repo there before we can move it to etcd. 👍

**Comment by mrbobbytables** [comment]
Repo has been migrated - I've opened a PR to add the subproject here:  https://github.com/kubernetes/community/pull/7718
@jmhbnz  opened this PR to add the teams: https://github.com/kubernetes/org/pull/4755
Once both are merged, this should be good to close 👍

**Comment by wenjiaswe** [comment]
Thank you so much @mrbobbytables !
