### ISSUE TITLE
REQUEST: New membership for kirkonru

### ISSUE THREAD

**Issue by kirkonru** [kubernetes/org#4757]
### GitHub Username

kirkonru

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@shurup

### Sponsor 2

@a-mccarthy

### List of contributions to the Kubernetes project

Here are some of my recent contributions:
[[ru] Localize assign-pod-node.md, reference/issues-security/*.md. Add examples/pods/*.yaml ](https://github.com/kubernetes/website/pull/43368)(this one is actually a work in progress; I’m the translator/localizer)
[Updating the interactive tutorials in Russian without Katacoda](https://github.com/kubernetes/website/pull/42530) (I was the reviewer for that one)
And here's a list of my PRs that have been successfully merged:
[[ru] Localization of /concepts/scheduling-eviction/assign-pod-node.md](https://github.com/kubernetes/website/pull/39162)
[[ru] Localization of /concepts/scheduling-eviction/api-eviction.md](https://github.com/kubernetes/website/pull/38081)
[[ru] Add RU localization for proxies.md](https://github.com/kubernetes/website/pull/36783)
[[ru] Add RU localization for system-logs.md](https://github.com/kubernetes/website/pull/36782)
[[ru] Add RU localization – networking.md](https://github.com/kubernetes/website/pull/36467)
[[ru] Add RU localization – manage-deployment.md](https://github.com/kubernetes/website/pull/36466)
[[ru] Add RU localization – logging.md](https://github.com/kubernetes/website/pull/36329)
[[ru] Add RU localization – flow-control.md](https://github.com/kubernetes/website/pull/36328)
[[ru] Add RU localization – certificates.md](https://github.com/kubernetes/website/pull/36327)
[[ru] Translate docs/concepts/containers/ – RU K8s docs](https://github.com/kubernetes/website/pull/34803)

**Comment by shurup** [comment]
I'm grateful for your massive contributions to Russian localization and am happy to support you!

**Comment by a-mccarthy** [comment]
Thanks so much for your contributions to the RU localization effort, i'm happy to support you as you continue to help make the RU docs better.

**Comment by Priyankasaggu11929** [comment]
Thank you for all your contributions 🙂

I’ve created PR https://github.com/kubernetes/org/pull/4773 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉
