### ISSUE TITLE
REQUEST: New membership for carlossg

### ISSUE THREAD

**Issue by carlossg** [kubernetes/org#4759]
### GitHub Username

@carlossg

### Organization you are requesting membership in

kubernetes, kubernetes-client

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jrsapi

### Sponsor 2

@puerco

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-client/javascript/pull/1488
- https://github.com/kubernetes-client/javascript/pull/1487
- https://github.com/kubernetes-client/gen/pull/262
- https://github.com/kubernetes-client/gen/pull/261
- https://github.com/kubernetes/website/pull/16197
- https://github.com/kubernetes/minikube/pull/5056
- https://github.com/kubernetes/autoscaler/pull/635
- https://github.com/kubernetes/kops/pull/3624
- https://github.com/kubernetes/kops/pull/3202
- https://github.com/kubernetes/kubernetes/pull/1188
- https://github.com/kubernetes/kubernetes/issues/2630

**Comment by jrsapi** [comment]
+1 to this request!

**Comment by jasonbraganza** [comment]
@puerco, would you kindly review and +1 this request? :)

**Comment by jasonbraganza** [comment]
@puerco a +1 from you would help me process this request. Thank you :)

**Comment by puerco** [comment]
Hey sorry I totally missed the notifications about this one , solid +1 from me. This org membership has been loooong overdue. We're lucky to have Carlos!

+1

**Comment by jasonbraganza** [comment]
/assign

@carlossg, thank you for all your contributions 🙂

I’ve created PR #4785  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
