### ISSUE TITLE
REQUEST: New membership for @AWKIF

### ISSUE THREAD

**Issue by AWKIF** [kubernetes/org#476]
### GitHub Username
@AWKIF

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
* @yastij
* @zacharysarah

### List of contributions to the Kubernetes project
* SIG-Release/enhancement: shadow 1.14
* SIG-Docs: I work with for sig-docs on the French localization of the Kubernetes project.

**Comment by zacharysarah** [comment]
+1 - @AWKIF is part of the new French localization.

**Comment by yastij** [comment]
+1

**Comment by mrbobbytables** [comment]
@AWKIF, thanks for helping with the French translations efforts and the 1.14 release :)

I've created PR #481  to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by AWKIF** [comment]
Thanks @mrbobbytables
