### ISSUE TITLE
Deploy verify-conformance on aaa cluster

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/org#4760]
### Describe the issue

verify-conformance is a GitHub/Prow bot which runs a test suite to check pull requests in cncf/k8s-conformance.

# Needs
- [ ] transfer repo to kubernetes-sigs: https://github.com/kubernetes/org/issues/4706
- [ ] transfer GitHub App to kubernetes(-sigs)
- [ ] setup external secrets for verify-conformance
- [ ] deploy verify-conformance: https://github.com/kubernetes/k8s.io/pull/6357

---

**Comment by hh** [comment]
@BobyMCbobs do you know what cluster the existing verify-conformance bot is running on?

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs do you know what cluster the existing verify-conformance bot is running on?

It has not moved to the aaa cluster yet.
Please see https://github.com/cncf-infra/verify-conformance/blob/main/docs/resources.md#infra

**Comment by BobyMCbobs** [comment]
As noted here: https://github.com/ii/cncf-okrs/issues/1#issuecomment-2136277260
Deployment to a cluster is no longer required due to the bot running in GitHub Actions.
