### ISSUE TITLE
REQUEST: New membership (to SIG-Docs) for holgers66

### ISSUE THREAD

**Issue by holgers66** [kubernetes/org#4762]
### GitHub Username

@holgers66

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@a-mccarthy

### Sponsor 2

@stormqueen1990 

### List of contributions to the Kubernetes project

This issue is to request membership to SIG-Docs. I have been working on German and Portuguese localization, and wish to continue contributing. I have started attending the regular SIG meetings, and have also been active in Slack.

- PRs authored:
[https://github.com/kubernetes/website/pull/44947](https://github.com/kubernetes/website/pull/44947)
[https://github.com/kubernetes/website/pull/44755](https://github.com/kubernetes/website/pull/44755)
[https://github.com/kubernetes/website/pull/44753](https://github.com/kubernetes/website/pull/44753)
[https://github.com/kubernetes/website/pull/44727](https://github.com/kubernetes/website/pull/44727)
[https://github.com/kubernetes/website/pull/44726](https://github.com/kubernetes/website/pull/44726)
[https://github.com/kubernetes/website/pull/44725](https://github.com/kubernetes/website/pull/44725)
[https://github.com/kubernetes/website/pull/44724](https://github.com/kubernetes/website/pull/44724)
[https://github.com/kubernetes/website/pull/44723](https://github.com/kubernetes/website/pull/44723)
[https://github.com/kubernetes/website/pull/44647](https://github.com/kubernetes/website/pull/44647)
[https://github.com/kubernetes/website/pull/44646](https://github.com/kubernetes/website/pull/44646)

**Comment by a-mccarthy** [comment]
@holgers66 thank you for your contributions to localizations! i am happy to support your membership request, looking forward to see more :)

**Comment by rolfedh** [comment]
@holgers66, I appreciate your solid dedication to enhancing localizations and endorse your membership application. Keep up the great work! :)

**Comment by Priyankasaggu11929** [comment]
Hello @holgers66, sponsors must be reviewers or approvers in at least one OWNERS file within one of the [Kubernetes GitHub organizations](https://github.com/kubernetes/community/blob/master/github-management#actively-used-github-organizations) (as mentioned in [community membership requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).)

I'm unable to find @rolfedh in any of the OWNERS file (please correct me if I'm mistaken!)

/assign

**Comment by holgers66** [comment]
> Hello @holgers66, sponsors must be reviewers or approvers in at least one OWNERS file within one of the [Kubernetes GitHub organizations](https://github.com/kubernetes/community/blob/master/github-management#actively-used-github-organizations) (as mentioned in [community membership requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).)
> 
> I'm unable to find @rolfedh in any of the OWNERS file (please correct me if I'm mistaken!)
> 
> /assign

Hello @Priyankasaggu11929. You're right. I couldn't find him either. I'll ask for a different second sponsor.

**Comment by holgers66** [comment]
Hello @Priyankasaggu11929. I have modified the membership request (I was requesting membership to the kubernetes org, not kubernetes-sigs). I have also spoken with @stormqueen1990, and she has agreed to sponsor me (thanks Mauren!). If there are any other questions or issues, please get in touch.

**Comment by jasonbraganza** [comment]
@stormqueen1990 would you kindly +1 this issue?

**Comment by stormqueen1990** [comment]
@jasonbraganza my apologies for the delay!

Thanks @holgers66 for your contributions to the Brazilian Portuguese localization so far, looking forward to see more 😃

+1

**Comment by Priyankasaggu11929** [comment]
Thank you for all your contributions 🙂

I’ve created PR https://github.com/kubernetes/org/pull/4773 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉
