### ISSUE TITLE
REQUEST: New membership for erikgrinaker

### ISSUE THREAD

**Issue by erikgrinaker** [kubernetes/org#4763]
### GitHub Username

@erikgrinaker

### Organization you are requesting membership in

etcd-io

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ahrtr

### Sponsor 2

@serathius

### List of contributions to the Kubernetes project

etcd-io/raft PRs: https://github.com/etcd-io/raft/pulls?q=is%3Apr+author%3Aerikgrinaker+is%3Aclosed

**Comment by ahrtr** [comment]
+1 for the request, and thanks for all your contributions.

**Comment by serathius** [comment]
+1

**Comment by jmhbnz** [comment]
+1
