### ISSUE TITLE
REQUEST: New membership for astefanutti

### ISSUE THREAD

**Issue by astefanutti** [kubernetes/org#4770]
### GitHub Username

@astefanutti

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alculquicondor

### Sponsor 2

@tenzen-y

### List of contributions to the Kubernetes project

PRs merged:
[11 PRs merged in kubernetes-sigs/kueue](https://github.com/search?q=repo%3Akubernetes-sigs%2Fkueue+++author%3Aastefanutti+++&type=pullrequests&state=closed)
[3 PRs merged in kubernetes-sigs/custom-metrics-apiserver](https://github.com/search?q=repo%3Akubernetes-sigs%2Fcustom-metrics-apiserver+author%3Aastefanutti++++++&type=pullrequests&state=closed)

Issues filed:
[11 Issues filled in kubernetes-sigs](https://github.com/search?q=org%3Akubernetes-sigs+author%3Aastefanutti&type=issues)

Community interaction:
[Discussion in kubernetes-sigs](https://github.com/search?q=org%3Akubernetes-sigs+commenter%3Aastefanutti&type=issues)

**Comment by tenzen-y** [comment]
+1

Thanks for your contributions! I'm looking forward to more collaborations in the future!

**Comment by alculquicondor** [comment]
+100

Thanks a lot for your insightful contributions!

**Comment by MadhavJivrajani** [comment]
Thank you for all your contributions 🙂

I’ve created PR https://github.com/kubernetes/org/pull/4772 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome! 🎉
