### ISSUE TITLE
REQUEST: Archive repo kubernetes-sigs/cloud-provider-baiducloud

### ISSUE THREAD

**Issue by elmiko** [kubernetes/org#4774]
### Repository to archive

kubernetes-sigs/cloud-provider-baiducloud

### Repository and/or sig subproject owners that are approving this archival

@elmiko

### When should this be done

soon, but it's not a rush

### Additional context for request

the kubernetes-sigs/cloud-provider-baiducloud repository has not seen active maintenance in the last 4 years, and there have not been updates to SIG Cloud Provider about its ownership. 

happy to keep the repo open if any of the maintainers are still active, but it does not appear that way.
cc
@tizhou86 
@ZP-AlwaysWin
@hello2mao

**Comment by elmiko** [comment]
cc @bridgetkromhout @andrewsykim @dims

**Comment by mrbobbytables** [comment]
The repo has been archived, once https://github.com/kubernetes/community/pull/7843 merges, this should be good to close 👍

**Comment by Priyankasaggu11929** [comment]
All PRs are merged now.

/close
