### ISSUE TITLE
REQUEST: New membership for rbenzair

### ISSUE THREAD

**Issue by rbenzair** [kubernetes/org#478]
### GitHub Username
@rbenzair

### Organization you are requesting membership in
(at)kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ ] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yastij  
- @Smana

### List of contributions to the Kubernetes project
- I would like to contribute on the  sig-docs on the French localization of the Kubernetes project.
- Contribute on the Chaos Eng Working Group

**Comment by yastij** [comment]
+1

**Comment by Smana** [comment]
+1

**Comment by yastij** [comment]
@rbenzair - is an approver for the FR docs

**Comment by yastij** [comment]
cc @zacharysarah

**Comment by zacharysarah** [comment]
+1

**Comment by mrbobbytables** [comment]
@rbenzair, thanks for helping with the French translations efforts :)

I've created PR #481  to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
