### ISSUE TITLE
REQUEST: New membership for squeed

### ISSUE THREAD

**Issue by squeed** [kubernetes/org#479]
### GitHub Username
(at)squeed

### Organization you are requesting membership in
(at)kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dcbw 
- @bboreham 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/42202 refactor dockershim CNI plugin, support hostport forwarding for cni
  - https://github.com/kubernetes/kubernetes/pull/54800 fix some latency issues
  - https://github.com/kubernetes/kubernetes/pull/55247 fix more kubenet latency issues
  - and lots of PRs on CNI and its library code
- Issues responded to
  - Solving pod latency issues in #54651 and #55060.
  - lots more random networking issues :-)
- SIG projects I am involved with
  - sig-networking
  - maintainer of the [CNI spec](https://github.com/containernetworking/cni) and its [plugins](https://github.com/containernetworking/plugins) (which kubernetes consumes)

**Comment by squeed** [comment]
Whoops, bboreham isn't in an OWNERS file. Mis-grepped. hold please.

**Comment by jellonek** [comment]
I'm also not in it, but +1 from me ;)

**Comment by bboreham** [comment]
The shame!

+1 from this worthless infidel.

**Comment by dcbw** [comment]
@mrbobbytables thoughts on this one? Should Casey submit a PR adding himself or does somebody else handle that? Thanks!

**Comment by mrbobbytables** [comment]
@dcbw Unfortunately @squeed needs another sponsor from @kubernetes org. As @bboreham said, he is not an approver or reviewer in any project and cannot sponsor.

With @jellonek's +1 he could be sponsored for membership in the @kubernetes-sigs org, but not for @kubernetes. 

From @squeed's initial response it looked like they were seeking out another potential sponsor. If one hasn't found the membership request can be amended to @kubernetes-sigs and they could be added today.

I hope that helps, if you have any other questions, please don't hesitate to ping me here or in slack. 

Thanks!

**Comment by mrbobbytables** [comment]
@squeed Have you found another potential sponsor?

**Comment by squeed** [comment]
@m1093782566 has agreed to sponsor me :-).

**Comment by mrbobbytables** [comment]
Great! Once they chime in with their +1, your membership request can be processed :)

**Comment by m1093782566** [comment]
+1

**Comment by mrbobbytables** [comment]
@squeed with @m1093782566 +1 I've created PR #593 to add you to the @kubernetes org :)
Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by nikhita** [comment]
@squeed In case you didn't receive an email invitation already, you should be able to accept the invite by visiting https://github.com/kubernetes.
