### ISSUE TITLE
REQUEST: New membership for asem-hamid

### ISSUE THREAD

**Issue by asem-hamid** [kubernetes/org#4791]
### GitHub Username

@asem-hamid

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@seokho-son

### Sponsor 2

@a-mccarthy

### List of contributions to the Kubernetes project

I have been contributing towards Bengali Localization  .
Here are some of my contributions :

:white_check_mark: PR merged:

 [bn] Localize 5 files in docs/tasks/tools/included : https://github.com/kubernetes/website/pull/45003
 [bn] Localize notes.md  : https://github.com/kubernetes/website/pull/45025
[bn] Fix typo in README-bn.md : https://github.com/kubernetes/website/pull/44684

:white_check_mark: The PR's I created :

[bn] Localize Releases/download.md : https://github.com/kubernetes/website/pull/45325
[bn] Localize concepts/services-networking/_index.md : https://github.com/kubernetes/website/pull/45230
[bn] Localize /docs/concepts/containers/ and /docs/concepts/architecture/ : https://github.com/kubernetes/website/pull/45199
[bn] Update hello-minikube.md : https://github.com/kubernetes/website/pull/45193
[bn] update files in tutorials : https://github.com/kubernetes/website/pull/45196

:white_check_mark: PR  I reviewed :

[bn] Localize releases/patch-releases.md : https://github.com/kubernetes/website/pull/45361
[bn] Localize Content/en/docs/concepts/policy/ index.md  :  https://github.com/kubernetes/website/pull/45335
[bn] Localize configuration/_index.md : https://github.com/kubernetes/website/pull/45215
[bn] Localize search.md : https://github.com/kubernetes/website/pull/45211

:white_check_mark: Issues Created:

[bn] need to Localize some content and take action before go live in bn : https://github.com/kubernetes/website/issues/44993

I am also very much active on [#kubernetes-docs-bn](https://kubernetes.slack.com/archives/CQ0TD298C) and created  [a detailed video ](https://www.youtube.com/watch?v=zlHNWVQwAj0)about Localizing content in bangla  so that more Bengali Contributors can contribute.

I am also an active [contributor](https://github.com/cncf/glossary/pulls?q=is%3Apr++author%3Aasem-hamid)  at cncf/glossary

**Comment by seokho-son** [comment]
+1
@asem-hamid has been actively contributing to Bengali localization in SIG-Docs.
As one of the SIG-Docs localization subproject leads, I'm looking forward to continuing our collaboration with @asem-hamid. :)
Welcome to the membership!

**Comment by a-mccarthy** [comment]
+1 I am happy to support your membership! thank you for your contributions, I look forward to working with you more on sig docs localizations

**Comment by jasonbraganza** [comment]
/assign

@asem-hamid, thank you for all your contributions 🙂

I’ve created PR #4798 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by mitul3737** [comment]
Great work @asem-hamid  ❤️
