### ISSUE TITLE
REQUEST: New membership for PBundyra

### ISSUE THREAD

**Issue by PBundyra** [kubernetes/org#4795]
### GitHub Username

PBundyra

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

alculquicondor

### Sponsor 2

tenzen-y

### List of contributions to the Kubernetes project

I am involved in developing Kueue
List of my PRs: https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+author%3Apbundyra
The most significant ones:
 - https://github.com/kubernetes-sigs/kueue/pull/1251
 - https://github.com/kubernetes-sigs/kueue/pull/1365

**Comment by PBundyra** [comment]
@alculquicondor  @tenzen-y

**Comment by tenzen-y** [comment]
+1

Thank you for your contribution!

**Comment by alculquicondor** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@PBundyra, thank you for all your contributions 🙂

I’ve created PR #4798 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by PBundyra** [comment]
> /assign
> 
> @PBundyra, thank you for all your contributions 🙂
> 
> I’ve created PR #4798 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉

Hi @jasonbraganza, thank you for adding me to the Kubernetes(s) Org! Unfortunately, I haven't received any notification despite the PR being merged, and it seems like my PRs still require `/ok-to-test` command. Is there anything I should do to become a valid member?

Thank you!

**Comment by jasonbraganza** [comment]
@Priyankasaggu11929, @MadhavJivrajani would either of you kindly take a look ☝🏿

**Comment by PBundyra** [comment]
I am sorry for bothering you needlessly. After double-check I did receive an invitation. There is no action required from your side.

Thank you
