### ISSUE TITLE
REQUEST: New membership for xmudrii

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/org#48]
### GitHub Username

@xmudrii

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sttts 
- @detiber 

#### kubernetes

Total Pull Requests Created: 7
1. [kubernetes/kubernetes#67846](https://github.com/kubernetes/kubernetes/pull/67846) - [WIP] admission/podsecuritypolicy: externalize podsecuritypolicy admission controller
2. [kubernetes/kubernetes#67842](https://github.com/kubernetes/kubernetes/pull/67842) - admission/priority: externalize priority admission controller
3. [kubernetes/kubernetes#67831](https://github.com/kubernetes/kubernetes/pull/67831) - admission/exec: externalize exec admission controller
4. [kubernetes/kubernetes#65916](https://github.com/kubernetes/kubernetes/pull/65916) - [1.10] gc: remove crd and apiservice from ignored resources
5. [kubernetes/kubernetes#65206](https://github.com/kubernetes/kubernetes/pull/65206) - sample-apiserver: Add RBAC roles and ClusterRoleBindings for Admission Webhooks
6. [kubernetes/kubernetes#63068](https://github.com/kubernetes/kubernetes/pull/63068) - Add Establishing Controller to avoid race between Established condition and CRs actually served
7. [kubernetes/kubernetes#60592](https://github.com/kubernetes/kubernetes/pull/60592) - apiextensions-apiserver: TestFinaliazationAndDeletion integration test

Total Issues Opened: 5
1. [kubernetes/kubernetes#66448](https://github.com/kubernetes/kubernetes/issues/66448) - Implement mechanism for certificates rotation in aggregated API servers
2. [kubernetes/kubernetes#65442](https://github.com/kubernetes/kubernetes/issues/65442) - Create aggregated ClusterRole for API Servers to allow getting Namespaces and Admission Webhooks
3. [kubernetes/kubernetes#63656](https://github.com/kubernetes/kubernetes/issues/63656) - Revisit Creating CustomResourceDefinitions from apiextensions-apiserver integration tests
4. [kubernetes/kubernetes#62725](https://github.com/kubernetes/kubernetes/issues/62725) - Improve Establishing logic for CRDs by implementing Installing status to prevent race conditions
5. [kubernetes/kubernetes#44240](https://github.com/kubernetes/kubernetes/issues/44240) - kubeadm: unknown flag --api-advertise-addresses on 1.6.1

Total Pull Requests Reviewed: 4
1. [kubernetes/kubernetes#65918](https://github.com/kubernetes/kubernetes/pull/65918) - [1.9] GC: remove CRD and APIService from ignored resources
2. [kubernetes/kubernetes#65856](https://github.com/kubernetes/kubernetes/pull/65856) - only need to ignore resources that match discovery conditions
3. [kubernetes/kubernetes#63587](https://github.com/kubernetes/kubernetes/pull/63587) - apiextensions: handle CRD conflict errs in integration tests
4. [kubernetes/kubernetes#55476](https://github.com/kubernetes/kubernetes/pull/55476) - apiserver: document how to run sample-apiserver standalone outside the cluster

Involved in: https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=involves%3Axmudrii+
Most notable:
* https://github.com/kubernetes/kubernetes/issues/65818
* https://github.com/kubernetes/kubernetes/issues/57042

**Repository: website**

Total Pull Requests Created: 1
1. [kubernetes/website#10084](https://github.com/kubernetes/website/pull/10084) - Remove references to imported for Contributing guides

#### kubernetes-sigs

**Repository: cluster-api**

Total Pull Requests Created: 2
1. [kubernetes-sigs/cluster-api#486](https://github.com/kubernetes-sigs/cluster-api/pull/486) - Remove priority field from the APIService manifest to make it compatible with 1.11+ bootstrap clusters
2. [kubernetes-sigs/cluster-api#478](https://github.com/kubernetes-sigs/cluster-api/pull/478) - clusterctl/cmd: improve error message for not implemented interface

Total Issues Opened: 1
1. [kubernetes-sigs/cluster-api#211](https://github.com/kubernetes-sigs/cluster-api/issues/211) - Proposal: Implement the cluster-api-do controller for handling DigitalOcean Kubernetes clusters

### SIG projects I am involved with
* SIG-API-Machinery
* SIG-Cluster-Lifecycle

**Comment by sttts** [comment]
+1

**Comment by nikhita** [comment]
+100 :tada:

**Comment by detiber** [comment]
+1

**Comment by cblecker** [comment]
Invite sent! Welcome to @kubernetes!

**Comment by yue9944882** [comment]
+1 😃
