### ISSUE TITLE
REQUEST: New membership for jichenjc

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/org#480]
### GitHub Username
jichenjc

note: I requested membership at https://github.com/kubernetes/org/issues/389 and forgot to add kubernetes-sig..so open this issue to handle that part 

### Organization you are requesting membership in
kubernetes-sig

### Requirements
- [ x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of contributions to the Kubernetes project
[kubernetes/cloud-provider-openstack#411](https://github.com/kubernetes/cloud-provider-openstack/pull/411)
[kubernetes/cloud-provider-openstack#398](https://github.com/kubernetes/cloud-provider-openstack/pull/398)
[kubernetes/cloud-provider-openstack#397](https://github.com/kubernetes/cloud-provider-openstack/pull/397)
[kubernetes/cloud-provider-openstack#380](https://github.com/kubernetes/cloud-provider-openstack/pull/380)
[kubernetes/cloud-provider-openstack#379](https://github.com/kubernetes/cloud-provider-openstack/pull/379)

[kubernetes-sigs/cluster-api-provider-openstack#148](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/148)

**Comment by mrbobbytables** [comment]
@jichenjc I've created PR #481 to add you to @kubernetes-sigs. Once again, sorry for the mix up the other day -- after this things should be sorted out :) Once it gets merged you should get a membership invite notification to @kubernetes-sigs.

Thanks!

/assign

**Comment by jichenjc** [comment]
@mrbobbytables Thanks a lot for your help!
