### ISSUE TITLE
REQUEST: New membership for satyampsoni

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/org#4800]
### GitHub Username

satyampsoni

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jberkus

### Sponsor 2

@rashansmith

### List of contributions to the Kubernetes project

https://github.com/pulls?q=is%3Apr+author%3Asatyampsoni+archived%3Afalse+is%3Aclosed+org%3Akubernetes

Apart from that I have been writing other merges section of Last week in kubernetes Development for a while now.

**Comment by jasonbraganza** [comment]
@satyampsoni, have directly added you, since sponsorship has already  happened in #4689 on 2024-01-17.
Once #4803 gets merged, you should get an invite in a bit.

**Comment by satyampsoni** [comment]
Thank you @satyampsoni
