### ISSUE TITLE
REQUEST: New membership for yujuhong

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/org#4801]
### GitHub Username

yujuhong

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mrunalp

### Sponsor 2

@dchen1107

### List of contributions to the Kubernetes project

- Actively participating in weekly SIG Node meetings and discussions
- Reviewed KEPs, e.g., 
  - https://github.com/kubernetes/enhancements/pull/4113
  - https://github.com/kubernetes/enhancements/pull/1592, 
- Triaged issues, joined discussions, and debug issues, e.g., 
  - https://github.com/kubernetes/kubernetes/issues/123057#issuecomment-1960062091
  - https://github.com/kubernetes/kubernetes/issues/123148#issuecomment-1931039424
  - https://github.com/kubernetes/kubernetes/pull/119173,
- Reviewed/approved PRs for bug fixes, e.g., 
  - https://github.com/kubernetes/kubernetes/pull/122846
  - https://github.com/kubernetes/kubernetes/pull/122885
  - https://github.com/kubernetes/kubernetes/pull/122890
  - https://github.com/kubernetes/kubernetes/pull/122846
  - https://github.com/kubernetes/kubernetes/pull/123358

**Comment by yujuhong** [comment]
@dchen1107 @mrunalp

**Comment by dchen1107** [comment]
+1

**Comment by mrunalp** [comment]
👍🏽

**Comment by dims** [comment]
YES PLEASE! welcome back

/woof

**Comment by pacoxu** [comment]
+1 👍

**Comment by jasonbraganza** [comment]
/assign

@yujuhong, thank you for all your contributions 🙂

I’ve created PR #4803 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification in a while.

Welcome! 🎉
