### ISSUE TITLE
REQUEST: New membership for atosatto

### ISSUE THREAD

**Issue by atosatto** [kubernetes/org#4804]
### GitHub Username

atosatto

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

soltysh

### Sponsor 2

Huang-Wei

### List of contributions to the Kubernetes project

List of KEPs:
- https://github.com/kubernetes/enhancements/pull/3901

List of PRs:
- https://github.com/kubernetes/kubernetes/pull/98324
- https://github.com/kubernetes/kubernetes/pull/115840
- https://github.com/kubernetes/kubernetes/pull/116687
- https://github.com/kubernetes/kubernetes/pull/119208

**Comment by soltysh** [comment]
:+1: from me
