### ISSUE TITLE
REQUEST: New membership for s1061123

### ISSUE THREAD

**Issue by s1061123** [kubernetes/org#4807]
### GitHub Username

@s1061123

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@MikeZappa87

### Sponsor 2

@aojea

### List of contributions to the Kubernetes project

- Joined KNI WG actively and multi-network WG. See minutes for the contribution
  https://docs.google.com/document/d/1pe_0aOsI35BEsQJ-FhFH9Z_pWQcU2uqwAnOx2NIx6OY/edit#heading=h.fo1yo94x96wg
  https://docs.google.com/document/d/1F_MsOlUnzy1nocRt6nobhqdCAKlha-YcqXjSnQRBDzc/edit#heading=h.9f4hc2cbrxk6
- I am also a maintainer of CNI and work on CNI/Kubernetes integration

**Comment by aojea** [comment]
+1 Tomo is a long time open source contributor in the networking area, maintainer of CNI and multus projects that are well known in the ecosystem and he recently joined two working groups under SIG network umbrella

**Comment by MikeZappa87** [comment]
@s1061123 is one of the best people in the ecosystem! He is involved with the core networking bits from k8s down to the CNI. 
+100

**Comment by mrbobbytables** [comment]
@s1061123 @aojea @MikeZappa87 My apologies, but our [org membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require demonstrating ongoing contributions to projects within the Kubernetes / etcd orgs. Contributions to projects outside of those are not applicable for org membership. I'd suggest opening an org membership request once you've contributed a bit, and it should then be pretty quick 👍

**Comment by s1061123** [comment]
Sure. I understand the situation. Once I contribute the K8s a lot, then I propose it again.
Thank you for the advice.
