### ISSUE TITLE
REQUEST: New membership for @dougbtv

### ISSUE THREAD

**Issue by dougbtv** [kubernetes/org#4808]
### GitHub Username

dougbtv

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@MikeZappa87

### Sponsor 2

@aojea

### List of contributions to the Kubernetes project

Long time contributor of the https://github.com/k8snetworkplumbingwg which is out of tree. Contributing to K8s Native Multinetworking, and KNI.

**Comment by MikeZappa87** [comment]
+100 for @dougbtv. Doug is involved in nearly every layer of the k8s networking stack, its time to make him a org member

**Comment by mrbobbytables** [comment]
@dougbtv  @aojea @MikeZappa87 My apologies, but our [org membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require demonstrating ongoing contributions to projects within the Kubernetes / etcd orgs. Contributions to projects outside of those are not applicable for org membership. I'd suggest opening an org membership request once you've contributed a bit, and it should then be pretty quick 👍

**Comment by MikeZappa87** [comment]
@mrbobbytables 

Doug is involved in multiple KEPs/Slack channels. I would assume he has commented on issues/PR's and more. I will let @dougbtv  chime in

**Comment by dougbtv** [comment]
@mrbobbytables -- sorry I didn't provide more specific details. I may not 

The SIG Network Multi-network meeting is listed @ https://github.com/kubernetes/community/blob/master/sig-network/README.md which point at [that  agenda](https://docs.google.com/document/d/1s5hQU0CB9ehjFukRmRHQ41f1FA8GX5_1Rv6nHW6NWAA/edit)

You can see my name and email address as a member of this group and regular attendee and contributor since mid 2022.

Additionally, you can find my participation in SIG-Network dating back to 2017 with [a reference to my GH username in the SIG-Network  agenda](https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit)

As mentioned in the [org membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) it says:

>  made multiple contributions to the project or community, enough to demonstrate an ongoing and long-term commitment to the project. *Contributions should include, but is not limited to*

And lists a number of contribution types including:

> Contributing to SIG, subproject, or community discussions (e.g. meetings, Slack, email discussion forums)

And also has:

> Actively contributing to 1 or more subprojects.

Of which I believe my participation in the SIG-Networking Multi Networking WG should show given the agenda as well.

Thanks for reconsidering. Also thanks @MikeZappa87

**Comment by mrbobbytables** [comment]
We don't generally consider just attending meetings a contribution that can be included for org membership. We are looking for active participation in the form of issues/PRs, or if you are involved in a meeting and such, generally running it or helping with a design proposal.

FWIW though, did you link the right agenda? I did find any instances of doug / dougbtv in this one:
> The SIG Network Multi-network meeting is listed @ https://github.com/kubernetes/community/blob/master/sig-network/README.md which point at [that agenda](https://docs.google.com/document/d/1s5hQU0CB9ehjFukRmRHQ41f1FA8GX5_1Rv6nHW6NWAA/edit)

> Additionally, you can find my participation in SIG-Network dating back to 2017 with [a reference to my GH username in the SIG-Network agenda](https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit)

This one I only found 4 instances going back to 2017

**Comment by dougbtv** [comment]
Ooops! That was the wrong link, sorry mistaken  copy/paste: this is the multi network agenda: https://docs.google.com/document/d/1pe_0aOsI35BEsQJ-FhFH9Z_pWQcU2uqwAnOx2NIx6OY/edit

If it's not appropriate to be a member, that's fine. But for more context.. I've been working in the world of trying to make CNI and Kubernetes interoperate since 2016. I was part of SIG Network when we formulated the Network Plumbing Working Group in 2017, you can see our kick off meeting notes there. 

Here's the thing -- we've had to develop and maintain these out of tree solutions to glue them together for years to try to knit these worlds together. 

Our initial goal was multi homed pods in Kubernetes, which we achieve with the specification put forward with the Network Plumbing Working Group. We implement that in https://github.com/k8snetworkplumbingwg/multus-cni and then have a constellation of projects that we've put together: https://github.com/k8snetworkplumbingwg that support this technology.

I'm looking to participate to get technology like this in tree, where it's appropriate. That's why I want to join officially.

Especially related to the KNI effort which I think is one of the best paths forward for bringing technology similar to CNI to something that is further integrated with Kubernetes itself.

**Comment by mskrocki** [comment]
+1 to above, @dougbtv is co-leading the Multi-Network effort, which is ongoing for over a year now. The Multi-Network effort is official SIG Network subproject.

**Comment by mrbobbytables** [comment]
I'm sorry, but this is not going to move forward until there are demonstrable contributions within the kubernetes orgs. We literally just removed 750~ people who did not have any GitHub activity in any of our orgs.

We have this stuff in place to stop people adding friends, previous coworkers etc. We've had other subject matter experts in areas "around" K8s say they deserve org membership, but they did not -need- it, they weren't commenting on issues, or opening/reviewing PRs. They weren't doing any activity in K8s itself that warranted it.

**Comment by mrbobbytables** [comment]
I'm going to go ahead and close this out for now - please feel free to reopen after contributing directly to projects within one of the K8s orgs.

Thanks!

/close
