### ISSUE TITLE
REQUEST: New membership for ivanvc

### ISSUE THREAD

**Issue by ivanvc** [kubernetes/org#4809]
### GitHub Username

@ivanvc

### Organization you are requesting membership in

etcd-io

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jmhbnz

### Sponsor 2

@ahrtr

### List of contributions to the Kubernetes project

Pull Requests both in progress and merged in @etcd-io repositories:

- etcd: https://github.com/etcd-io/etcd/pulls?q=is%3Apr+author%3Aivanvc
- bbolt: https://github.com/etcd-io/bbolt/pulls?q=is%3Apr+author%3Aivanvc
- Raft: https://github.com/etcd-io/raft/pulls?q=is%3Apr+author%3Aivanvc
- website: https://github.com/etcd-io/website/pulls?q=is%3Apr+author%3Aivanvc

**Comment by jmhbnz** [comment]
+1

Many thanks for all your work on etcd @ivanvc, it's great to have you joining the project.  Looking forward to continuing to work together in future.

**Comment by wenjiaswe** [comment]
+1 I am supportive. Thank you very much @ivanvc for your contribution in etcd!

**Comment by ahrtr** [comment]
+1, well deserved! Thanks @ivanvc for you continuous contribution to the community!

**Comment by jmhbnz** [comment]
With both sponsor +1's in @ivanvc please feel free to raise the pull request to add yourself to the org via `config/etcd-io/org.yaml` when you are ready.

**Comment by ivanvc** [comment]
Thanks guys. I look forward to continuing to contribute to the project :)

@jmhbnz, is our process for etcd different? Because according to [Community membership](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements):
> Once your sponsors have responded, your request will be reviewed by the [Kubernetes GitHub Admin team](https://github.com/kubernetes/community/blob/master/github-management/README.md#github-administration-team), in accordance with their [SLO](https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#slos). Any missing information will be requested.

**Comment by ahrtr** [comment]
cc @MadhavJivrajani @mrbobbytables

**Comment by jasonbraganza** [comment]
/assign

@ivanvc , thank you for all you do 🙂

I’ve created PR #4811 to add you to the etcd-io org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
