### ISSUE TITLE
REQUEST: New membership for liurupeng

### ISSUE THREAD

**Issue by liurupeng** [kubernetes/org#4813]
### GitHub Username

@liurupeng

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ahg-g

### Sponsor 2

@kerthcet

### List of contributions to the Kubernetes project

PRs reviewed/authored:
https://github.com/kubernetes-sigs/lws/commit/ecf83e0db44baf4cead19140ab47dad84a090faf
https://github.com/kubernetes-sigs/lws/commit/bb794a764cb780013a7c115e90f2bcac0ef33c1c
https://github.com/kubernetes-sigs/lws/commit/eeb73b921198a5f2aeccb9175a2101d9cf6641f8
Issue assigned/commented:
https://github.com/kubernetes-sigs/lws/issues/6
https://github.com/kubernetes-sigs/lws/issues/7

**Comment by kerthcet** [comment]
+1 glad to see this happens. thanks @liurupeng

**Comment by ahg-g** [comment]
+1 Thanks Rupeng for leading the implementation of the LeaderWorkerSet API.

**Comment by ahg-g** [comment]
> @ahg-g would you kindly update your profile with your place of work? or update this issue?

Google

**Comment by jasonbraganza** [comment]
/assign

@liurupeng, thank you for all your contributions 🙂

I’ve created PR #4815 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by liurupeng** [comment]
Hi @jasonbraganza do you know roughly how long the membership will take effect so that I could use it, thanks!

**Comment by jasonbraganza** [comment]
normally takes about a day or slightly longer at most. if you do not receive an invite within the next six hours, please let me know, and I could request folks to look into it.

Also, please check your spam. Missing invites, more often than not, land in there.

**Comment by Priyankasaggu11929** [comment]
Hello @liurupeng, the org membership invites for both kubernetes & kubernetes-sigs org were sent out successfully.

Please let us know if the issue still persists. Thanks!

![image](https://github.com/kubernetes/org/assets/30499743/d9a2b704-eb0b-4220-81de-3eb74010f6b7)
![image](https://github.com/kubernetes/org/assets/30499743/4339df56-4dd5-4ac6-b651-da5225c3e199)
