### ISSUE TITLE
REQUEST: New membership for sawsa307

### ISSUE THREAD

**Issue by sawsa307** [kubernetes/org#4819]
### GitHub Username

@sawsa307

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@robscott

### Sponsor 2

@shaneutt

### List of contributions to the Kubernetes project

PRs reviewed:
https://github.com/kubernetes/ingress-gce/pull/2436

PRs authored:
https://github.com/kubernetes-sigs/gateway-api/pull/2588
https://github.com/kubernetes-sigs/gateway-api/pull/2699
https://github.com/kubernetes-sigs/gateway-api/pull/2702
https://github.com/kubernetes-sigs/gateway-api/pull/2830
https://github.com/kubernetes-sigs/gateway-api/pull/2853
https://github.com/kubernetes/ingress-gce/pull/2297
https://github.com/kubernetes/ingress-gce/pull/2414
https://github.com/kubernetes/ingress-gce/pull/2458
https://github.com/kubernetes/test-infra/pull/31714
https://github.com/kubernetes/test-infra/pull/31846
https://github.com/kubernetes-sigs/boskos/pull/178
https://github.com/kubernetes-sigs/boskos/pull/181

Issues responded to:
https://github.com/kubernetes-sigs/gateway-api/issues/2622
https://github.com/kubernetes-sigs/gateway-api/issues/2674
https://github.com/kubernetes-sigs/gateway-api/issues/2697
https://github.com/kubernetes-sigs/gateway-api/issues/2833
https://github.com/kubernetes/test-infra/issues/30277

SIG projects I am involved in:
[kubernetes-sigs/gateway-api](https://github.com/kubernetes-sigs/gateway-api)

**Comment by shaneutt** [comment]
LGTM, thanks @sawsa307!

**Comment by robscott** [comment]
Thanks for all the contributions @sawsa307! Big +1 from me

**Comment by jasonbraganza** [comment]
/assign

@sawsa307, thank you for all your contributions 🙂

I’ve created PR #4822 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by sawsa307** [comment]
Hi @jasonbraganza I've accepted the invite, but I just received another email saying `You have been removed from the "Kubernetes" organization`. Do you know what's going on here?

**Comment by jasonbraganza** [comment]
Hello, @sawsa307, the bot will reconcile this eventually. let’s wait a day. and if nothing improves, i pass this up the chain of command!
