### ISSUE TITLE
REQUEST: New membership for tao12345666333

### ISSUE THREAD

**Issue by tao12345666333** [kubernetes/org#482]
### GitHub Username
 @tao12345666333

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @BenTheElder 
- @k82cn 

### List of contributions to the Kubernetes project
- PRs reviewed / authored and Issues responded to
https://github.com/kubernetes-sigs/kind/pulls?q=is%3Aclosed+is%3Apr+author%3Atao12345666333
https://github.com/search?q=author%3Atao12345666333++org%3Akubernetes+is%3Amerged&type=Issues

- SIG projects I am involved with
  `kubernetes-sigs/kind`

**Comment by k82cn** [comment]
+1

Thanks for your contribution :)

**Comment by BenTheElder** [comment]
+1
Thanks for your contributions

**Comment by mrbobbytables** [comment]
Hey there @tao12345666333 , thank you for all that you've done so far :)

I've created PR #489  to add you to the @kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
/pony party
