### ISSUE TITLE
REQUEST: New membership for fatsheep9146

### ISSUE THREAD

**Issue by fatsheep9146** [kubernetes/org#4823]
### GitHub Username

fatsheep9146

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dashpole 

### Sponsor 2

@pohly

### List of contributions to the Kubernetes project

- PR authored: 
  - https://github.com/kubernetes/kubernetes/pull/123584
  - https://github.com/kubernetes/kubernetes/pull/119771
  - https://github.com/kubernetes/kubernetes/pull/120548
  - https://github.com/kubernetes/kubernetes/pull/122087
  - https://github.com/kubernetes/kubernetes/pull/122197 
  - https://github.com/kubernetes/kubernetes/pull/116930
  - https://github.com/kubernetes/kubernetes/pull/116910
  - https://github.com/kubernetes/kubernetes/pull/115049
  - https://github.com/kubernetes/kubernetes/pull/122979
  - https://github.com/kubernetes/kubernetes/pull/121899
- SIG projects: kubernetes, mainly focus on sig instrumentation, for example kubernetes tracing and contextual logging.

**Comment by dashpole** [comment]
I support.  Thanks @fatsheep9146 for all your help!

**Comment by pohly** [comment]
:+1: from me too. Thanks!

**Comment by jasonbraganza** [comment]
/assign

@fatsheep9146, thank you for all your contributions 🙂

I’ve created PR #4830 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
