### ISSUE TITLE
REQUEST: Reactivate membership for dsu-igeek

### ISSUE THREAD

**Issue by dsu-igeek** [kubernetes/org#4824]
### GitHub Username

@dsu-igeek

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@yuxiangqian

### List of contributions to the Kubernetes project

I was previously approved for membership and removed but don't see any notifications about that other than the removal itself.  Approved add request is here: https://github.com/kubernetes/org/issues/3389

I've been active in the Data Protection Working Group and am one of the authors of the DP Working Group's White Paper
Currently working on the Changed Block Tracking proposal in the DP Working Group
As the Velero architect I've been working on Kubernetes data protection (backup/restore) and supporting the K8s community as users of Velero

**Comment by xing-yang** [comment]
+1

**Comment by mrbobbytables** [comment]
@dsu-igeek My apologies, but you were removed as part of the inactive org member clean up. - https://github.com/kubernetes/org/issues/4726
Members with 0 activity across all our GitHub orgs for more than a year were removed. Notifications were sent to kdev, twitter etc.

At this point you will need to reapply for membership after demonstrating consistent contributions to the Kubernetes project (please link issues/PRs etc), contributions to ecosystem projects like velero do not apply towards K8s org membership.

**Comment by mrbobbytables** [comment]
I'm going to go ahead and close this out for now - please reapply once you become active again.

Thanks!

/close
