### ISSUE TITLE
REQUEST: New membership for AnishShah

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/org#4825]
### GitHub Username

AnishShah

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kannon92 

### Sponsor 2

@SergeyKanzhelev 

### List of contributions to the Kubernetes project

- Actively participating in weekly SIG Node CI meetings and discussions.
- Authored PRs
     -  https://github.com/kubernetes/kubernetes/pull/123782
     -  https://github.com/kubernetes/kubernetes/pull/123916
- Authored KEPs
     -  https://github.com/kubernetes/enhancements/pull/4524
- Triage issues, joined discussions, and debug issues
    -   https://github.com/kubernetes/kubernetes/issues/122160
    -   https://github.com/kubernetes/kubernetes/issues/123029
    -  Actively triaging bugs in https://github.com/orgs/kubernetes/projects/59 during sig-node CI meeting

**Comment by SergeyKanzhelev** [comment]
+1, welcome @AnishShah

**Comment by kannon92** [comment]
I support this nomination! @AnishShah has been leading bug triage in sig-node-ci and has started some very relevant KEPs. Looking forward to continue working with you!

**Comment by jasonbraganza** [comment]
/assign

@AnishShah, thank you for all your contributions 🙂

I’ve created PR #4830 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
