### ISSUE TITLE
REQUEST: New membership for vignesh-goutham

### ISSUE THREAD

**Issue by vignesh-goutham** [kubernetes/org#4826]
### GitHub Username

vignesh-goutham

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@AverageMarcus

### Sponsor 2

@rohityadavcloud

### List of contributions to the Kubernetes project

Pull Requests

- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/322
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/289
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/279
- https://github.com/kubernetes-sigs/image-builder/pull/1291
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1236
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/275
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/272
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/245
- https://github.com/kubernetes-sigs/image-builder/pull/1427

Issues

- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/issues/274
- https://github.com/kubernetes-sigs/image-builder/issues/1287
- https://github.com/kubernetes-sigs/cluster-api/issues/8306
- https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/issues/321

SIG Projects: Cluster-API Provider CloudStack, Cluster-API & Image Builder

**Comment by AverageMarcus** [comment]
/lgtm

Thank you so much for your contributions to image-builder!

**Comment by rohityadavcloud** [comment]
/lgtm 

Thanks for your contributions

**Comment by jasonbraganza** [comment]
/assign

@vignesh-goutham, thank you for all your contributions 🙂

I’ve created PR #4830 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
