### ISSUE TITLE
REQUEST: New membership for smana

### ISSUE THREAD

**Issue by Smana** [kubernetes/org#483]
### GitHub Username
@Smana

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yastij
- @rbenzair

### List of contributions to the Kubernetes project
I would like to contribute on the sig-docs on the French localization of the Kubernetes project.

**Comment by yastij** [comment]
+1 @Smana is an approver for FR docs and one of the folks that worked on kubespray originally.

**Comment by mrbobbytables** [comment]
I will add a +1 to sponsor as well :) Thanks for kicking off the French translation efforts!

**Comment by mrbobbytables** [comment]
Hey there @Smana , thank you for helping with the French translation efforts :)

I've created PR #489  to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by rbenzair** [comment]
+1 @Smana
