### ISSUE TITLE
REQUEST: New membership for azaynul10

### ISSUE THREAD

**Issue by azaynul10** [kubernetes/org#4834]
### GitHub Username

azaynul10

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@asem-hamid

### Sponsor 2

@mitul3737

### List of contributions to the Kubernetes project

As an active contributor to the Bengali localization efforts, I have demonstrated my commitment to the project through numerous merged pull requests and ongoing contributions.

Here are some highlights of my contributions :
:white_check_mark: PR merged:
 [bn] Localize concepts/configuration/_index.md : https://github.com/kubernetes/website/pull/45228
[bn] Localize concepts/scheduling-eviction/_index.md : https://github.com/kubernetes/website/pull/45575
[bn] Localize docs/setup/production-environment/tools/kubeadm/_index.md :
https://github.com/kubernetes/website/pull/45601
[bn] update docs/setup/production-environment/turnkey-solutions.md : https://github.com/kubernetes/website/pull/45583
:white_check_mark: The PR's I created :
[bn] Localize concepts/configuration/_index.md : https://github.com/kubernetes/website/pull/45228
[bn] Localize concepts/scheduling-eviction/_index.md : https://github.com/kubernetes/website/pull/45575
[bn] Localize blog/_index.md : https://github.com/kubernetes/website/pull/45580
[bn] Update setup/_index.md : https://github.com/kubernetes/website/pull/45593
[bn] update docs/setup/production-environment/turnkey-solutions.md : https://github.com/kubernetes/website/pull/45583
[bn] Localize docs/setup/production-environment/tools/kubeadm/_index.md : https://github.com/kubernetes/website/pull/45601

Through these contributions, I have demonstrated my ability to understand and translate technical content accurately, while adhering to the project's guidelines and best practices. I am passionate about making Kubernetes accessible to the Bengali-speaking community and committed to continuing my efforts in this area.
I would be honored to have your support and sponsorship for my membership application

**Comment by mitul3737** [comment]
Thank you for your contribution!

**Comment by Imtiaz1234** [comment]
Thank you for your contribution

**Comment by asem-hamid** [comment]
+1
@azaynul10  has been actively contributing to Bengali localization in SIG-Docs.
As one of the SIG-Docs Bengali localization maintainer , I'm looking forward to continuing our collaboration with @azaynul10 . :)
Welcome to the membership!

**Comment by asem-hamid** [comment]
@mitul3737  please add `+1` if you are sponsoring membership

**Comment by mrbobbytables** [comment]
@azaynul10 unfortunately neither @asem-hamid or @mitul3737 can act as a sponsor. Sponsors **must** be in a reviewer or approver following our [org membership guidelines](https://git.k8s.io/community/community-membership.md)

**Comment by asem-hamid** [comment]
@mrbobbytables  We both are approver at sig-docs-bn localization .

https://github.com/kubernetes/website/pull/45400

**Comment by mrbobbytables** [comment]
I see the issue, the PR was merged only against the [1.24-bn.1 deb branch](https://github.com/kubernetes/website/tree/dev-1.24-bn.1) and not the main branch. When doing a [code search through github](https://github.com/search?q=repo%3Akubernetes%2Fwebsite+asem-hamid&type=code) or using our go.k8s.io/owners/<user> (e.g. https://go.k8s.io/owners/asem-hamid) shortcut to search for you as an owner, it will not come up (all searching only targets main/master branch). I'll proceed with this, but IMO it should really go into main too.

/assign

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4869  to add you to org(s). Once that gets merged, you should get a membership invite notification.

Welcome aboard! :D

**Comment by azaynul10** [comment]
Thank you so much @mrbobbytables ,  much appreciated ❤️😊

**Comment by asem-hamid** [comment]
Thank you for proceeding. I have a question: Can we add sig-docs-bn-owners and reviewers to the teams.yaml file now, or should we wait for the launch of our localized website?

https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml
