### ISSUE TITLE
REQUEST: New membership for steve-hardman

### ISSUE THREAD

**Issue by steve-hardman** [kubernetes/org#4835]
### GitHub Username

steve-hardman

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@windsonsea

### Sponsor 2

@dipesh-rawat

### List of contributions to the Kubernetes project

 I've been contributing to Kubernetes documentation for over a year now, with 29 PRs merged across various fixes.
 
 [PR authored by me that have been merged (29+)](https://github.com/kubernetes/website/pulls?q=is%3Amerged+is%3Apr+author%3Asteve-hardman+)
 
 I'm involved in SIG-Docs.

**Comment by dipesh-rawat** [comment]
+1 from me.
@steve-hardman Thank you for all your contributions!
Look forward to even more from you in the future. 🚀

/pony party

**Comment by sftim** [comment]
We recommend you take the [Inclusive Open Source Community Orientation](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) course; it's optional, but it's also something that the Kubernetes project wants people to be up to speed on.

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4869  to add you to org(s). Once that gets merged, you should get a membership invite notification.

Welcome aboard! :D
