### ISSUE TITLE
REQUEST: New membership for rekcah78

### ISSUE THREAD

**Issue by rekcah78** [kubernetes/org#484]
### GitHub Username
@rekcah78

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah
- @yastij

### List of contributions to the Kubernetes project
- SIG-Docs: I work with for sig-docs on the French localization of the Kubernetes project.
- Fews contributions on subproject kops: https://github.com/kubernetes/kops/pull/5529 https://github.com/kubernetes/kops/pull/5708 https://github.com/kubernetes/kops/pull/5953 https://github.com/kubernetes/kops/pull/5529

**Comment by yastij** [comment]
+1 @rekcah78 is a reviewer/approver for FR docs

**Comment by Smana** [comment]
+1 @rekcah78 as reviewer/approver for FR docs

**Comment by mrbobbytables** [comment]
I will add a +1 to sponsor as well :) Thanks for kicking off the French translation efforts!

**Comment by mrbobbytables** [comment]
@rekcah78, thank you for helping with the French translation efforts.

I've created PR #489  to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
