### ISSUE TITLE
REQUEST: New membership for shijinye

### ISSUE THREAD

**Issue by shijinye** [kubernetes/org#4841]
### GitHub Username

shijinye

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@carlory

### Sponsor 2

@pohly

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pull/121146
https://github.com/kubernetes/kubernetes/pull/120407
https://github.com/kubernetes/kubernetes/pull/120401
https://github.com/kubernetes/kubernetes/pull/120347

**Comment by carlory** [comment]
+1

**Comment by pohly** [comment]
+1 from me too.

Thanks @shijinye !

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4869  to add you to org(s). Once that gets merged, you should get a membership invite notification.

Welcome aboard! :D
