### ISSUE TITLE
REQUEST: New membership for elbehery

### ISSUE THREAD

**Issue by Elbehery** [kubernetes/org#4844]
### GitHub Username

elbehery

### Organization you are requesting membership in

etcd-io

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ahrtr

### Sponsor 2

@jmhbnz

### List of contributions to the Kubernetes project

https://github.com/etcd-io/bbolt/pulls?q=is%3Apr+author%3Aelbehery+is%3Aclosed+

https://github.com/etcd-io/etcd/pulls?q=is%3Apr+author%3Aelbehery+is%3Aclosed+

**Comment by ahrtr** [comment]
+1

Thanks @Elbehery for all your contributions to bbolt and etcd.
