### ISSUE TITLE
REQUEST: New membership for bryantbiggs

### ISSUE THREAD

**Issue by bryantbiggs** [kubernetes/org#4845]
### GitHub Username

bryantbiggs

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ameukam

### Sponsor 2

@dims

### List of contributions to the Kubernetes project

PRs
- https://github.com/kubernetes/k8s.io/pull/5920
- https://github.com/kubernetes/k8s.io/pull/5935
- https://github.com/kubernetes/k8s.io/pull/5936
- https://github.com/kubernetes/k8s.io/pull/5942

Reviews:
- https://github.com/kubernetes/k8s.io/pull/5974
- https://github.com/kubernetes/k8s.io/pull/5994
- https://github.com/kubernetes/k8s.io/pull/6137
- https://github.com/kubernetes/k8s.io/pull/6148
- https://github.com/kubernetes/k8s.io/pull/6168
- https://github.com/kubernetes/k8s.io/pull/6355
- https://github.com/kubernetes/k8s.io/pull/6559

Involved:
- sig-infra

**Comment by ameukam** [comment]
+1 from me.
Bryant's deep understanding of Terraform is now assisting us with expanding our infrastructure on AWS.

**Comment by dims** [comment]
Yes please!

/woof

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4869  to add you to org(s). Once that gets merged, you should get a membership invite notification.

Welcome aboard! :D
