### ISSUE TITLE
REQUEST: New membership for sajibadhi

### ISSUE THREAD

**Issue by sajibAdhi** [kubernetes/org#4848]
### GitHub Username

@sajibadhi

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mitul3737

### Sponsor 2

@asem-hamid

### List of contributions to the Kubernetes project

:white_check_mark: PR merged:
 [[bn] localization content/bn/docs/setup/learning-environment/_index.md added](https://github.com/kubernetes/website/pull/39839)
 [[bn] localization content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html](https://github.com/kubernetes/website/pull/41807)
 [[bn] Localization content/bn/docs/setup/production-environment/_index.md](https://github.com/kubernetes/website/pull/41958)
 [[bn] Localize content/bn/docs/concepts/overview/_index.md](https://github.com/kubernetes/website/pull/45362)
:white_check_mark: The PRs I created :
 [[bn] Localize content/bn/docs/setup/production-environment/tools/_index.md](https://github.com/kubernetes/website/pull/45512)
 [[bn] FIX: Localize content/bn/releases/download.md](https://github.com/kubernetes/website/pull/45515)
 [[bn] FIX: Localize content/bn/_index.html](https://github.com/kubernetes/website/pull/45516)
 [[bn] Localize glossary entry for container runtime](https://github.com/kubernetes/website/pull/45533)
 
I am also active on [#kubernetes-docs-bn](https://kubernetes.slack.com/archives/CQ0TD298C) so that more Bengali Contributors can contribute.

Through these contributions, I have demonstrated my ability to understand and translate technical content, while adhering to the project's guidelines and best practices. I am passionate about making Kubernetes accessible to the Bengali-speaking community and am committed to continuing my efforts in this area.
I would be honored to have your support and sponsorship for my membership application

**Comment by asem-hamid** [comment]
+1
@sajibAdhi   I am happy to support your membership! You are one of the valuable team member in our team. Thank you for your contributions . 
As one of the SIG-Docs Bengali localization maintainer , I'm looking forward to continuing our collaboration with @sajibAdhi  .

**Comment by seokho-son** [comment]
+1
@sajibAdhi is contributing to Bengali localization. 
as one of the SIG-Docs localization subproject leads, I'd love to be one of the sponsors. :)

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4869  to add you to org(s). Once that gets merged, you should get a membership invite notification.

Welcome aboard! :D

**Comment by sajibAdhi** [comment]
Thanks, everyone.
