### ISSUE TITLE
REQUEST: New membership for jygastaud

### ISSUE THREAD

**Issue by jygastaud** [kubernetes/org#485]
### GitHub Username
@jygastaud

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ ] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yastij 
- @sieben 

### List of contributions to the Kubernetes project

I would like to contribute on the sig-docs on the French localization of the Kubernetes project.

**Comment by sieben** [comment]
👍

**Comment by yastij** [comment]
+1

**Comment by mrbobbytables** [comment]
@jygastaud Thank you for helping with the French translation efforts :)

I've created PR #489 to add you to the @kubernetes org. Once it gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
