### ISSUE TITLE
Peribolas postsubmit failed for new etcd member

### ISSUE THREAD

**Issue by jmhbnz** [kubernetes/org#4854]
### Organization or Repo

etcd-io

### User affected

@Elbehery

### Describe the issue

We recently merged https://github.com/kubernetes/org/pull/4849.

The postsubmit failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-org-peribolos/1773344561179922432

Logs indicate a permissions failure for the `etcd-io` org?

```bash
{"client":"github","component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/github/client.go:801","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"UpdateOrgMembership(etcd-io, elbehery, false)","severity":"info","time":"2024-03-28T13:42:54Z"}

{"component":"unset","error":"the account is using admin:org_hook, admin:repo_hook, read:org, repo, user, workflow oauth scopes, please make sure you are using at least one of the following oauth scopes: admin:org","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:477","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership(etcd-io, elbehery, false) failed","severity":"warning","time":"2024-03-28T13:42:54Z"}
```

**Comment by Elbehery** [comment]
all the past jobs since `16 feb` are failing

**Comment by atoato88** [comment]
FYI, I'm also facing same issue about syncing org file with members on github site following:
- kubernetes
- kubernetes-sigs

**Comment by Priyankasaggu11929** [comment]
Peribolos jobs are up and running again.

Relevant troubleshooting/discussion recorded here - https://kubernetes.slack.com/archives/C01672LSZL0/p1712182376329389

/close
