### ISSUE TITLE
REQUEST: Create new repository for kube-network-policies

### ISSUE THREAD

**Issue by aojea** [kubernetes/org#4856]
### New repo, staging repo, or migrate existing

New repo

### Is it a staging repo?

no

### Requested name for new repository

kube-network-policies

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

aojea, danwinship, thockin

### Who should have write access?

aojea, danwinship, thockin

### Who should be listed as approvers in OWNERS?

aojea, danwinship, thockin

### Who should be listed in SECURITY_CONTACTS?

aojea, danwinship, thockin

### What should the repo description be?

Kubernetes network policies

### What SIG and subproject does this fall under?

sig-network, subg project https://github.com/kubernetes/community/blob/master/sig-network/README.md#network-policy

### Please provide references to appropriate approval for this new repo

There are only two jobs that test network policies and are using calico
Calico is a third dependency we don't have control and jobs are failing for some time now https://github.com/kubernetes/kubernetes/issues/124130

It turns out that is easier to have our own implementation of network policies, that can also expanded to support admin network policies, than to debug third party network plugins, so I created one in https://github.com/aojea/kube-netpol that I'd like to donate to the kubernetes project

**Comment by danwinship** [comment]
> ### Requested name for new repository
> 
> kube-netpol

Should bikeshed the name a bit; we don't really use "netpol" as an abbreviation anywhere other than `test/e2e/network/netpol/`. Also, if it's going to be in kubernetes-sigs, does it really need "kube" in its name?

Should it have "reference" or "userspace" or something in the name to better distinguish it from other things?

**Comment by ameukam** [comment]
+1 FWIW. 

we could just use an acronym for the name ? nprc (Network Policy Reference Controller) ?

**Comment by aojea** [comment]
> Should bikeshed the name a bit

yes please, I prefer something more sounding

👍 praesidium
😄 netshield
😅 nprc
...

**Comment by aojea** [comment]
/hold

vote with the icons above

**Comment by danwinship** [comment]
If this is purely a "reference implementation" then it should have a boring, obvious name.

If we intend for it to actually be/become a viable option for use in production clusters, then it could have a more "exciting" name (though it doesn't need to, eg, "kube-proxy"). But that also implies more of a commitment from SIG Network and maybe this needs to be discussed somewhere?

FTR I was objecting to "kube-netpol" solely on the grounds that we don't normally use "netpol" as an abbreviation for "NetworkPolicy".

**Comment by aojea** [comment]
> If we intend for it to actually be/become a viable option for use in production cluster

I'd like to make this a kube-proxy like but for network policies, not a project in its own, having adoption on users should not be a goal of the project ... having something that helps us to get CI signal and validate APIs is a goal

`kube-network-policy` then?

**Comment by danwinship** [comment]
/retitle REQUEST: Create new repository for kube-network-policies

(fix typo)

**Comment by ameukam** [comment]
cc @kubernetes/owners 🙏🏾

**Comment by aojea** [comment]
/unassign @mrbobbytables 

I think he is out until next week, maybe someone else from @kubernetes/owners can take it?

**Comment by Priyankasaggu11929** [comment]
/assign

I'll go ahead with creating the new repo

@aojea @danwinship, the requested new repo will be part of which [subproject](https://github.com/kubernetes/community/tree/master/sig-network#subprojects) of sig-network? [network-policy](https://github.com/kubernetes/community/tree/master/sig-network#network-policy)?

**Comment by Priyankasaggu11929** [comment]
New repo: https://github.com/kubernetes-sigs/kube-network-policies

PR to add GitHub teams for the new repo: https://github.com/kubernetes/org/pull/4892

will wait for input on the subproject name https://github.com/kubernetes/org/issues/4856#issuecomment-2067577275 and then create another PR to add documentation in k/community. Thanks!

**Comment by aojea** [comment]
@Priyankasaggu11929 subproject is https://github.com/kubernetes/community/blob/master/sig-network/README.md#network-policy

**Comment by Priyankasaggu11929** [comment]
PR to document new repo to k/community -  https://github.com/kubernetes/community/pull/7832

**Comment by Priyankasaggu11929** [comment]
All PRs are merged. New Repo is ready.

/close
