### ISSUE TITLE
new repo: kubernetes-csi/csi-driver-image-populator

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/org#486]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
 csi-driver-image-populator

### Which Organization should it reside
kubernetes-csi

### If not a staging repo, who should have admin access
@saad-ali @msau42

### If not a staging repo, who should have write access
@saad-ali @msau42

### If a new repo, who should be listed as approvers in OWNERS
@saad-ali @msau42 @kfox1111

### If a new repo, who should be listed in SECURITY_CONTACTS
@saad-ali @msau42 @kfox1111

### What should the repo description be
CSI driver that uses a container image as a volume

### What SIG and subproject does this fall under in sigs.yaml
part of the CSI working group in SIG-storage

### Approvals
Discussed and approved on Thursday, Feb 14, 2019, in the sig-storage meeting
Also discussed on the sig-storage group:
https://groups.google.com/forum/#!topic/kubernetes-sig-storage/6_SpwBiaNtI

**Comment by spiffxp** [comment]
/assign @nikhita 
Please give this one a shot

**Comment by msau42** [comment]
`csi-driver-image` is a confusing name and it might be interpreted to mean something related to storing container images for the drivers we maintain.

I can't really think of something much better. How about something like:
csi-driver-image-volume
csi-driver-container-image-volume

**Comment by kfox1111** [comment]
all the storage drivers are under csi-driver-X. so I think csi-driver-image makes sense. But I'm open to either of the other two as well. all of them make sense in one way or the other.

(There are 2 hard problems in computer science. naming things, cache invalidation, and off by one errors :smile: )

**Comment by kfox1111** [comment]
Are we stuck on naming? Who can pick?

**Comment by msau42** [comment]
@saad-ali and I brainstormed and came up with:
csi-driver-image-populator

wdyt?

**Comment by kfox1111** [comment]
wfm

**Comment by kfox1111** [comment]
Do I need to amend the request?

**Comment by msau42** [comment]
Sure go ahead and edit the first comment with the updated name

**Comment by kfox1111** [comment]
:heavy_check_mark:

**Comment by nikhita** [comment]
Created https://github.com/kubernetes-csi/csi-driver-image-populator :tada: 

I have also created two PRs:

- https://github.com/kubernetes/org/pull/517 - to add GitHub teams for repo admin/write access.
- https://github.com/kubernetes/community/pull/3293 - to add this repo to sigs.yaml.

Once https://github.com/kubernetes/org/pull/517 has merged and the postsubmit has run, the new GitHub teams will be created. I'll manually update the collaborators to the repo to provide access to the teams once that's done. :)

---

@kfox1111 I have added you as an approver for the repo, but to be able to use these approval powers, you need to be a member of @kubernetes-csi. Can you please [file a membership request](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) for this?

**Comment by nikhita** [comment]
The new GitHub teams have been created and I have updated repo permissions. 

`csi-driver-image-populator-admins` has admin access and `csi-driver-image-populator-maintainers` has write access.

I'll close this issue once https://github.com/kubernetes/community/pull/3293 is merged.

**Comment by kfox1111** [comment]
Ok. I'll file a membership request asap.

Thanks everyone for all the help. :)

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/3293 has merged. Closing this issue.

/close
