### ISSUE TITLE
REQUEST: Migrate kube-rbac-proxy to kubernetes-sigs

### ISSUE THREAD

**Issue by upodroid** [kubernetes/org#4861]
### New repo, staging repo, or migrate existing

migrate

### Is it a staging repo?

no

### Requested name for new repository

kube-rbac-proxy

### Which Organization should it reside

kubernetes-sigs

### What SIG and subproject does this fall under?

sig-api-machinery

### Please provide references to appropriate approval for this new repo

The community has been trying to transfer kube-rbac-proxy for a while and it hasn't happened yet. This needs to be done as soon as possible to unblock kubebuilder and sig k8s-infra CI migration efforts from google.com GCP projects.

kubebuilder CI is very convoluted and needs to be reworked from scratch. The project depends on the rbac-proxy and we are doing a complicated [builds](https://github.com/kubernetes-sigs/kubebuilder/blob/master/RELEASE.md#to-build-the-kube-rbac-proxy-images). It is also hosted on a google.com project that will be going away very soon.(sig k8s-infra concern)

https://github.com/brancz/kube-rbac-proxy/issues/169
https://github.com/brancz/kube-rbac-proxy/issues/168
https://kubernetes.slack.com/archives/CCK68P2Q2/p1711913605487359
https://github.com/kubernetes/k8s.io/issues/2647

Ideally, we would like @brancz to transfer the github repo instead of a new one being created so we can preserve the redirects.

/cc @deads2k @fedebongio @camilamacedo86

**Comment by camilamacedo86** [comment]
I think we need to ping here the owner of this project @ibihim 
In the past I spoke with him and I understood that it was in the process to be donated to Kubernetes-SIG
For Kubebuilder, which I take care of, we need to know if it will be migrated or not to solve the build of image process. (as far I understand we need to have it inside of Kubernetes-SIG to be able to build the images)

**Comment by brancz** [comment]
More than happy to initiate the transfer when you tell me to.

**Comment by cblecker** [comment]
A sig would need to agree to take on ownership, and the repo would need to go through the transfer process. sig-api-machinery was tagged in your request @upodroid, but some of the links reference sig-auth. 

This would be the first thing that would need to be solved. There are additional requirements for donated repositories here: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

**Comment by sathieu** [comment]
This is sad. Would this issue be reopened?
