### ISSUE TITLE
REQUEST: New membership for ComradeProgrammer

### ISSUE THREAD

**Issue by ComradeProgrammer** [kubernetes/org#4863]
### GitHub Username

@ComradeProgrammer

### Organization you are requesting membership in

kubernetes,kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@medyagh

### Sponsor 2

@afbjorklund

### List of contributions to the Kubernetes project

PR List:
https://github.com/kubernetes/minikube/pulls/ComradeProgrammer

**Comment by medyagh** [comment]
@ComradeProgrammer has had multiple notable contributors to minikube project including new features and bug fixes and been a very helpful part of our community and I support his membership

**Comment by afbjorklund** [comment]
I sponsor the membership

**Comment by jasonbraganza** [comment]
@afbjorklund would you kindly update your place of work, either on your profile or here in this issue?
Asking because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require sponsors be from different orgs.

**Comment by afbjorklund** [comment]
Not sure what my workplace has to do with my membership, but I work at a company called Something Good IT AB (Sweden)

**Comment by jasonbraganza** [comment]
@afbjorklund not your membership, rather to guide me with the membership for @ComradeProgrammer.
mostly the third sub point here in the [sponsor requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) point
> Sponsors must be from multiple member companies to demonstrate integration across community.

thank you very much for helping out! :)

**Comment by jasonbraganza** [comment]
/assign

@ComradeProgrammer, thank you for all your contributions 🙂

I’ve created PR #4882 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
