### ISSUE TITLE
REQUEST: New membership for sivchari

### ISSUE THREAD

**Issue by sivchari** [kubernetes/org#4864]
### GitHub Username

@sivchari

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sanposhiho

### Sponsor 2

@wzshiming

### PR
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Asivchari+is%3Aclosed

### PR
https://github.com/kubernetes-sigs/kube-scheduler-simulator/pulls?q=is%3Apr+author%3Asivchari+is%3Aclosed

### Issue
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/created_by/sivchari

### PR
https://github.com/kubernetes-sigs/kwok/pulls?q=is%3Apr+author%3Asivchari+is%3Aclosed

### Issue
https://github.com/kubernetes-sigs/kwok/issues?q=is%3Aissue+author%3Asivchari+is%3Aclosed

### PR
https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+author%3Asivchari+is%3Aclosed

### PR
https://github.com/kubernetes-sigs/e2e-framework/pulls?q=is%3Apr+author%3Asivchari+is%3Aclosed

### PR
https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Asivchari+is%3Aclosed

### PR
https://github.com/kubernetes/community/pulls/sivchari

**Comment by wzshiming** [comment]
+1, thank you for your contributions!

**Comment by sanposhiho** [comment]
+1, thanks for all your effort so far

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4869  to add you to org(s). Once that gets merged, you should get a membership invite notification.

Welcome aboard! :D
