### ISSUE TITLE
REQUEST: New membership for H13m0n

### ISSUE THREAD

**Issue by H13m0n** [kubernetes/org#4866]
### GitHub Username

@H13m0n

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@seokho-son

### Sponsor 2

@jongwooo

### List of contributions to the Kubernetes project

PRs reviewed ([k/website](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3AH13m0n))
- https://github.com/kubernetes/website/pull/40610
- https://github.com/kubernetes/website/pull/41276
- https://github.com/kubernetes/website/pull/41532
- https://github.com/kubernetes/website/pull/41628
- https://github.com/kubernetes/website/pull/41635
- https://github.com/kubernetes/website/pull/42223
- https://github.com/kubernetes/website/pull/42267

**Comment by seokho-son** [comment]
+1
@H13m0n is one of the active Korean localization contributors in SIG Docs. As the SIG Docs Korean localization team lead, I'd like to welcome the membership of @H13m0n :)

**Comment by jongwooo** [comment]
+1

Thanks for all your contributions, @H13m0n!

**Comment by mrbobbytables** [comment]
Thank you for all your contributions so far :)

I've created PR #4869  to add you to org(s). Once that gets merged, you should get a membership invite notification.

Welcome aboard! :D
