### ISSUE TITLE
REQUEST: New membership for @hello2mao

### ISSUE THREAD

**Issue by hello2mao** [kubernetes/org#487]
### GitHub Username
@hello2mao 

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andrewsykim
- @mwielgus

### List of contributions to the Kubernetes project
- PRs reviewed / authored && Issues responded to
  - https://github.com/kubernetes/kubernetes/pull/73075
  - https://github.com/kubernetes/kubernetes/pull/73317
  - https://github.com/kubernetes/kubernetes/pull/73403
  - https://github.com/kubernetes/autoscaler/pull/1536
  - https://github.com/kubernetes/autoscaler/pull/1570
  - https://github.com/kubernetes/autoscaler/pull/1626
  - https://github.com/kubernetes/website/pull/12480
  - https://github.com/kubernetes/website/pull/12539
- SIG projects I am involved with
  - kubernetes/kubernetes
  - kubernetes/autoscaler
- Maintainer of baiducloud cluster-autoscaler
  - https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/baiducloud

**Comment by mwielgus** [comment]
+1

**Comment by andrewsykim** [comment]
+1 thank you for your contributions so far :)

**Comment by mrbobbytables** [comment]
Hey there @hello2mao, thank you for all your contributions so far :)

I've created PR #497  to add you to both the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notifications from both of them

Welcome to the project! 🎉

/assign
