### ISSUE TITLE
REQUEST: Archive repo container-object-storage-interface-csi-adapter

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/org#4875]
### Repository to archive

https://github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter

### Repository and/or sig subproject owners that are approving this archival

@saad-ali, @xing-yang, @msau42, @jsafrane, @wlan0

### When should this be done

anytime

### Additional context for request

This repo is no longer active and it is not needed any more.
Discussed about this in the COSI Standup meeting multiple times.

**Comment by Priyankasaggu11929** [comment]
remove documentation from k/community - https://github.com/kubernetes/community/pull/7841
remove associated GH teams from k/org - https://github.com/kubernetes/org/pull/4900

**Comment by mrbobbytables** [comment]
Going to close this out as everything has merged and repo has been migrated/archived 👍 
/close
