### ISSUE TITLE
REQUEST: New membership for @skriss

### ISSUE THREAD

**Issue by skriss** [kubernetes/org#4878]
### GitHub Username

@skriss

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sunjayBhatia

### Sponsor 2

@youngnick

### List of contributions to the Kubernetes project

- Gateway API PRs: https://github.com/kubernetes-sigs/gateway-api/pulls?q=is%3Apr+author%3Askriss
- https://github.com/kubernetes-sigs/kind/pull/3495
- https://github.com/kubernetes/cloud-provider-vsphere/pull/905

I am already a member of kubernetes-sigs org.

**Comment by sunjayBhatia** [comment]
LGTM!

**Comment by jasonbraganza** [comment]
@youngnick, please help :)

**Comment by jasonbraganza** [comment]
@youngnick, gentle ping :)

**Comment by skriss** [comment]
@jasonbraganza Nick did mention he was on leave, hopefully next week he'll see this

**Comment by youngnick** [comment]
Sorry, I was one leave.

+1 on this one for sure.

**Comment by jasonbraganza** [comment]
all done! @skriss welcome :)
have raised #4930. You should receive an invite once that PR is merged.

**Comment by jasonbraganza** [comment]
/assign

all done! @skriss welcome :)
have raised https://github.com/kubernetes/org/pull/4930. You should receive an invite once that PR is merged.
