### ISSUE TITLE
Admin access to cloud-provider-azure project board

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#488]
### Organization or repository
https://github.com/orgs/kubernetes/projects/12

### Users effected
@justaugustus 

### Describe the issue
We're getting rolling on grooming for cp-azure and to start delegating things, I'll need admin access to that board to configure who's got access to what.

I'll be updating the Azure teams across the org at a later date and will update the permissions on this board once that happens.

/assign @cblecker

**Comment by cblecker** [comment]
Done.

FYI @PatrickLang per the above.
