### ISSUE TITLE
REQUEST: New membership for <lowang-bh>

### ISSUE THREAD

**Issue by lowang-bh** [kubernetes/org#4880]
### GitHub Username

@lowang-bh

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@camilamacedo86

### Sponsor 2

@tenzen-y

### List of contributions to the Kubernetes project

1.  [PRs in kubernetes-sigs](https://github.com/kubernetes-sigs/kubebuilder/pulls?q=is%3Apr+author%3Alowang-bh+is%3Aclosed+label%3Aapproved)

- https://github.com/kubernetes-sigs/kubebuilder/pull/3571
- https://github.com/kubernetes-sigs/kubebuilder/pull/3578
- https://github.com/kubernetes-sigs/kubebuilder/pull/3579
- https://github.com/kubernetes-sigs/kubebuilder/pull/3580
- https://github.com/kubernetes-sigs/kubebuilder/pull/3582
- https://github.com/kubernetes-sigs/kubebuilder/pull/3584
- https://github.com/kubernetes-sigs/kubebuilder/pull/3619
- https://github.com/kubernetes-sigs/kubebuilder/pull/3620
- https://github.com/kubernetes-sigs/kubebuilder/pull/3625

2. [PRs in kubernetes](https://github.com/kubernetes/kubernetes/pulls/lowang-bh)
- https://github.com/kubernetes/kubernetes/pull/117390
- https://github.com/kubernetes/kubernetes/pull/118511
- https://github.com/kubernetes/kubernetes/pull/120075
- https://github.com/kubernetes/kubernetes/pull/120101
- https://github.com/kubernetes/kubernetes/pull/117943
- https://github.com/kubernetes/kubernetes/pull/122038

3. [PRs in Kueue]
- https://github.com/kubernetes-sigs/kueue/pull/1121
- https://github.com/kubernetes-sigs/kueue/pull/1124
- https://github.com/kubernetes-sigs/kueue/pull/1131
- https://github.com/kubernetes-sigs/kueue/pull/1949
- https://github.com/kubernetes-sigs/kueue/pull/1955

4. Others
- https://github.com/kubernetes-sigs/gluster-file-external-provisioner/pull/2
- https://github.com/kubernetes/website/pull/41003
- https://github.com/kubernetes/klog/pull/379

**Comment by tenzen-y** [comment]
I'm not sure if I can become a sponsor because I reviewed only 2 small PRs of the above.

> Sponsors must have close interactions with the prospective member - e.g. code/design/proposal review, coordinating on issues, etc.

**Comment by jasonbraganza** [comment]
/assign

@lowang-bh, thank you for all your contributions 🙂

I’ve created PR #4881 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
