### ISSUE TITLE
REQUEST: Create repository kubernetes-sigs/wg-device-management

### ISSUE THREAD

**Issue by johnbelamaric** [kubernetes/org#4886]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

wg-device-management

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

johnbelamaric, pohly, klueska

### Who should have write access?

johnbelamaric, pohly, klueska

### Who should be listed as approvers in OWNERS?

johnbelamaric, pohly, klueska

### Who should be listed in SECURITY_CONTACTS?

johnbelamaric, pohly, klueska

### What should the repo description be?

Prototypes and experiments for WG Device Management.

### What SIG and subproject does this fall under?

SIG Architecture

### Please provide references to appropriate approval for this new repo

This is for experimental work from the new working group, which is sponsored by SIG Arch, Node, Network, Autoscaling, and Scheduling. However, for purposes of this repo, SIG Arch can sponsor it, and as one of the chairs I am granting my approval.

**Comment by johnbelamaric** [comment]
cc @pohly @klueska

**Comment by mrbobbytables** [comment]
For now I think we should hold off on creating this until the charter is approved and the wg is officially a thing.

**Comment by dims** [comment]
do you want `experimental` in the name?

**Comment by johnbelamaric** [comment]
> do you want `experimental` in the name?

:shrug: 

I wanted to make sure it's clear that this is not something "real". But I am OK with just `wg-device-management`, if you think that's better.

**Comment by johnbelamaric** [comment]
> For now I think we should hold off on creating this until the charter is approved and the wg is officially a thing.

Ok. I'll be sending that tomorrow. Just need to give folks a little more time to review. There's quite a bit of urgency here though, so I am trying to nudge stuff along as much as possible :)

**Comment by dims** [comment]
+1 to leave the experimental out. we can make it clear in the readme etc.

**Comment by klueska** [comment]
I have some stuff I'd like to push here.  What (if anything) is blocking https://github.com/kubernetes/community/pull/7805 so that we can move forward with the creation of this repo?

**Comment by johnbelamaric** [comment]
updated the description and title to remove "experimental" as requested by @dims

**Comment by Priyankasaggu11929** [comment]
/assign

I'll go ahead with creating the new repo.

**Comment by Priyankasaggu11929** [comment]
New Repo - https://github.com/kubernetes-sigs/wg-device-management

**Comment by Priyankasaggu11929** [comment]
PR to add GitHub teams for the new repo: https://github.com/kubernetes/org/pull/4927

Working group is already documented under SIG Storage - https://github.com/kubernetes/community/tree/master/sig-architecture#working-groups, so, k/community documentation is also complete.

**Comment by johnbelamaric** [comment]
Since #4927 merged, is this complete?

**Comment by Priyankasaggu11929** [comment]
Yes, all PRs are merged. Repo creation is complete.

/close
