### ISSUE TITLE
REQUEST: New membership for aauren

### ISSUE THREAD

**Issue by aauren** [kubernetes/org#4893]
### GitHub Username

@aauren

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@hakman

### Sponsor 2

@aojea

## PRs:

kops:
* https://github.com/kubernetes/kops/pull/16467
* https://github.com/kubernetes/kops/pull/16440
* https://github.com/kubernetes/kops/pull/16188
* https://github.com/kubernetes/kops/pull/16149
* https://github.com/kubernetes/kops/pull/16110

kubernetes:
* https://github.com/kubernetes/kubernetes/pull/122440
* https://github.com/kubernetes/kubernetes/pull/122633
* https://github.com/kubernetes/kubernetes/pull/123622

test-infra:
* https://github.com/kubernetes/test-infra/pull/31278

## Sigs:

Slightly involved in sig-networking as the maintainer for kube-router CNI.

**Comment by aojea** [comment]
+1

**Comment by hakman** [comment]
+1 from me also 🥳

**Comment by jasonbraganza** [comment]
/assign

@aauren, thank you for all your contributions 🙂

I’ve created PR #4894 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
