### ISSUE TITLE
Conformance github team in k8s org.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/org#49]
### Organization 
kubernetes

### Users effected
the conformance working group

### Describe the issue
We need a (single) github team for general awareness, notification, and assignment of issues and pr's relating to the conformance effort.

/cc @dims @duglin @bradtopol  
/assign @spiffxp @cblecker

**Comment by timothysc** [comment]
I'd also ask to be added to that list.

**Comment by cblecker** [comment]
Is this a part of sig-testing? I don't know that we have a conformance working group. Or are you referring to the cncf conformance working group? Just thinking about team naming

**Comment by duglin** [comment]
I'd like to be added too.
Who has the authority to create such a team?

**Comment by timothysc** [comment]
It's the cncf conformance working group.

**Comment by timothysc** [comment]
@cblecker - ping .

**Comment by cblecker** [comment]
@timothysc I've created https://github.com/orgs/kubernetes/teams/cncf-conformance-wg and added you as a team maintainer. You can add the other members as needed.
