### ISSUE TITLE
REQUEST: New membership for esotsal

### ISSUE THREAD

**Issue by esotsal** [kubernetes/org#4901]
### GitHub Username

@esotsal

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [x] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@SergeyKanzhelev

### Sponsor 2

@bart0sh

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pull/123259

https://github.com/kubernetes/test-infra/pull/32018

https://github.com/kubernetes/community/pull/7727

https://github.com/kubernetes/test-infra/pull/32176

https://github.com/kubernetes/kubernetes/pull/124097

sig-node , sig-testing

Thanks for the support : @bart0sh @SergeyKanzhelev @kannon92 @dims @ffromani @aojea

**Comment by ffromani** [comment]
I support! Welcome!

**Comment by dims** [comment]
+1 from me!

**Comment by aojea** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
I support!

**Comment by bart0sh** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

far be it from me to stand in the way of such overwhelming support @esotsal! Thank you for all your contributions 🙂

I’ve created PR #4905 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
