### ISSUE TITLE
REQUEST: Create repository `kubernetes-sigs/secrets-store-sync-controller`

### ISSUE THREAD

**Issue by aramase** [kubernetes/org#4902]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

secrets-store-sync-controller

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

aramase,enj

### Who should have write access?

aramase,enj,nilekhc

### Who should be listed as approvers in OWNERS?

aramase,enj

### Who should be listed in SECURITY_CONTACTS?

aramase,enj

### What should the repo description be?

This is a Kubernetes controller that watches for changes to a custom resource and syncs the secrets from external secrets-store as Kubernetes secret.

### What SIG and subproject does this fall under?

sig-auth

### Please provide references to appropriate approval for this new repo

Discussed this in the SIG Auth meeting and will get ack/approvals as part of this issue.

**Comment by enj** [comment]
/sig auth

+1 from me, this has been discussed a few times (most recently in today's SIG auth meeting).

**Comment by liggitt** [comment]
+1 from me as well

**Comment by ritazh** [comment]
+1

**Comment by mrbobbytables** [comment]
@aramase Repo has been provisioned - once https://github.com/kubernetes/community/pull/7853 &  https://github.com/kubernetes/org/pull/4926 merge, you should be able to start using it 👍

**Comment by aramase** [comment]
Thank you @mrbobbytables!

**Comment by mrbobbytables** [comment]
verified teams are active, you should be good to go!
With that I'm going to go ahead and close this out.

Thanks!

/close
