### ISSUE TITLE
REQUEST: New membership for sipriyaa

### ISSUE THREAD

**Issue by sipriyaa** [kubernetes/org#4906]
### GitHub Username

sipriyaa

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@RaunakShah
@palnabarun 

### List of contributions to the Kubernetes project

PRs reviewed / authored
https://github.com/kubernetes-sigs/vsphere-csi-driver/pulls?q=is%3Apr+author%3Asipriyaa+

SIG projects I am involved with
https://github.com/kubernetes-sigs/vsphere-csi-driver

**Comment by jasonbraganza** [comment]
@xing-yang, @RaunakShah, can I go ahead? :)

**Comment by xing-yang** [comment]
+1

**Comment by jasonbraganza** [comment]
@RaunakShah, your +1 will help me process this.

**Comment by jasonbraganza** [comment]
@sipriyaa, would it be possible for you to get another sponsor? I can then process your membership as soon as I get another +1

**Comment by sipriyaa** [comment]
@jasonbraganza I have requested @palnabarun for another approval

**Comment by palnabarun** [comment]
@sipriyaa Thanks for nudging me to sponsor you. However, the sponsors need to be from different companies. @xing-yang and I both work at Broadcom and, hence, are not eligible to sponsor together.

Is there a non-Broadcom employee that you can ask to sponsor you?

**Comment by sipriyaa** [comment]
I'm not acquainted with anyone beyond the Broadcom circle. @xing-yang , can you assist me?

**Comment by RaunakShah** [comment]
+1

**Comment by jasonbraganza** [comment]
@RaunakShah thank you for your +1. just for completeness sake and to confirm, your work org is Mirantis?
because like it’s pointed up above the sponsors need to be from different orgs

**Comment by jasonbraganza** [comment]
@RaunakShah would you kindly confirm?

**Comment by Priyankasaggu11929** [comment]
+1.

Happy to be a sponsor, to move this request forward. :slightly_smiling_face:

**Comment by jasonbraganza** [comment]
/assign

@sipriyaa, thank you for all your contributions 🙂

I’ve created PR #4972  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
