### ISSUE TITLE
REQUEST: New membership for IrvingMg

### ISSUE THREAD

**Issue by IrvingMg** [kubernetes/org#4907]
### GitHub Username

@IrvingMg

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@trasc

### Sponsor 2

@alculquicondor

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/kueue/pull/1938
- https://github.com/kubernetes-sigs/kueue/pull/1958
- https://github.com/kubernetes-sigs/kueue/pull/1972
- https://github.com/kubernetes-sigs/kueue/pull/1975
- https://github.com/kubernetes-sigs/kueue/pull/2008
- https://github.com/kubernetes-sigs/kueue/pull/2047

**Comment by alculquicondor** [comment]
+1

Thanks for your contributions!

**Comment by trasc** [comment]
+1 

Thanks

**Comment by jasonbraganza** [comment]
/assign

@IrvingMg, thank you for all your contributions 🙂

I’ve created PR #4912 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
