### ISSUE TITLE
REQUEST: Create etcd-manager repo

### ISSUE THREAD

**Issue by hakman** [kubernetes/org#4908]
### New repo, staging repo, or migrate existing

new

### Is it a staging repo?

no

### Requested name for new repository

etcd-manager

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

justinsb, hakman, ahrtr, wenjiaswe, neolit123

### Who should have write access?

justinsb, hakman, ahrtr, wenjiaswe, neolit123

### Who should be listed as approvers in OWNERS?

justinsb, hakman, rifelpet

### Who should be listed in SECURITY_CONTACTS?

justinsb, hakman

### What SIG and subproject does this fall under?

sig-etcd + sig-cluster-lifecycle

### Please provide references to appropriate approval for this new repo

April 2, 2024 [Community Meeting](https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit#heading=h.3lkbu72cxmnq):
[ahrtr] move etcd-manager into sig-etcd
https://github.com/kubernetes-sigs/etcdadm/tree/master/etcd-manager	
Open to further discussion

### Additional context for request

Moving `etcd-manager` from the `etcdadm/etcd-manager` repo to its own repo.

Would be nice if possible to do something like this for bootstrapping:
https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

**Comment by hakman** [comment]
CC @justinsb @neolit123 @wenjiaswe @ahrtr @fabriziopandini @serathius @jmhbnz

**Comment by ahrtr** [comment]
+1 Thanks

**Comment by neolit123** [comment]
+1

**Comment by wenjiaswe** [comment]
/sig etcd

+1 from me, SIG Cluster Lifecycle and SIG etcd have been talking about this and we are in agreement. Thank you @hakman !

**Comment by jmhbnz** [comment]
+1 - Thanks @hakman.

**Comment by mrbobbytables** [comment]
sorry, this fell through the cracks a bit - I can provision a repo tomorrow. Which SIG should the subproject fall under for updating sigs.yaml purposes?

**Comment by hakman** [comment]
> sorry, this fell through the cracks a bit - I can provision a repo tomorrow. Which SIG should the subproject fall under for updating sigs.yaml purposes?

@mrbobbytables SIG etcd. Thanks!

**Comment by mrbobbytables** [comment]
Repo has been created and fleshed out: https://github.com/kubernetes-sigs/etcd-manager
Once the two open PRs are merged this should be good to close 👍 

One FYI - @ahrtr @wenjiaswe you will need to accept the k-sigs org membership to be added to the repo admin team

**Comment by hakman** [comment]
Thanks @mrbobbytables! 😄

**Comment by mrbobbytables** [comment]
everything has been done, going to go ahead and close this out :+1: 
/close
