### ISSUE TITLE
REQUEST: New membership for ah8ad3

### ISSUE THREAD

**Issue by ah8ad3** [kubernetes/org#4909]
### GitHub Username

@ah8ad3

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@soltysh

### Sponsor 2

@mpuckett159

### List of contributions to the Kubernetes project

PRs reviewed / authored:
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aopen+ah8ad3
https://github.com/kubernetes-sigs/kubectl-validate/pull/113
https://github.com/kubernetes-sigs/kustomize/pulls?q=is%3Apr+is%3Aopen+ah8ad3
https://github.com/etcd-io/etcd/pulls?q=is%3Apr+ah8ad3+is%3Aclosed

Issues
https://github.com/kubernetes/kubectl/issues?q=is%3Aissue+is%3Aopen+commenter%3Aah8ad3
https://github.com/kubernetes-sigs/kustomize/issues?q=is%3Aissue+is%3Aopen+commenter%3Aah8ad3
https://github.com/etcd-io/etcd/issues?q=is%3Aissue+is%3Aopen+commenter%3Aah8ad3

SIG projects I am involved with
SIG/CLI

**Comment by mpuckett159** [comment]
+1 thank you for the help, looking forward to working with you more.

**Comment by jasonbraganza** [comment]
@mpuckett159, would you kindly update your work org on your profile, or here in this issue?
Asking because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require that sponsors be from different organisations.

**Comment by jasonbraganza** [comment]
> I work Integral Ad Science currently though I don't do open source there in an official capacity so I'm listed as Independent everywhere.

@mpuckett159 Thank you! I just needed it to be different from @soltysh :)

**Comment by jasonbraganza** [comment]
/assign

@ah8ad3, thank you for all your contributions 🙂

I’ve created PR#4914  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by soltysh** [comment]
:+1:

**Comment by ah8ad3** [comment]
Thanks you @soltysh, @mpuckett159, i will try my best to hopefully make an impact on Kubernetes with your'e help.
Also thanks @jasonbraganza.

**Comment by jasonbraganza** [comment]
shoot! computer problems! will raise a fresh pr in a bit

**Comment by jasonbraganza** [comment]
@ah8ad3, apologies!
a fresh pr #4920 is now in the pipeline and you should receive an invite, once merged.
