### ISSUE TITLE
REQUEST: New membership for embik

### ISSUE THREAD

**Issue by embik** [kubernetes/org#4916]
### GitHub Username

@embik

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sttts

### Sponsor 2

@xmudrii

### List of contributions to the Kubernetes project

- PRs authored
  - https://github.com/kubernetes-sigs/release-sdk/pull/288
  - https://github.com/kubernetes/release/pull/3559
  - https://github.com/kubernetes/release/pull/3560
  - https://github.com/kubernetes/release/pull/3569
  - https://github.com/kubernetes-sigs/hydrophone/pull/170
  - https://github.com/kubernetes-sigs/hydrophone/pull/179
  - https://github.com/kubernetes/contributor-site/pull/492
  - https://github.com/kubernetes-sigs/krew/pull/854
- Issues responded to
   - https://github.com/kubernetes/release/issues/3392#issuecomment-1849684117

**Comment by xmudrii** [comment]
+1

**Comment by sttts** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@embik, thank you for all your contributions 🙂

I’ve created PR #4920 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
