### ISSUE TITLE
REQUEST: New membership for astrieanna

### ISSUE THREAD

**Issue by astrieanna** [kubernetes/org#492]
### GitHub Username
astrieanna

### Organization you are requesting membership in
kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hoegaarden
- @PatrickLang 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/enhancements/pull/685
https://github.com/kubernetes/enhancements/pull/729
https://github.com/kubernetes/kubernetes/pull/71147
https://github.com/kubernetes/kubernetes/pull/72889
https://github.com/kubernetes/kubernetes/pull/74082
https://github.com/kubernetes/kubernetes/pull/74091
https://github.com/kubernetes-sigs/windows-testing/pull/20

- SIG projects I am involved with
sig-windows

**Comment by PatrickLang** [comment]
I approve. We appreciate your contributions in SIG-Windows :)

**Comment by hoegaarden** [comment]
+1
/lgtm
Thanks!

**Comment by michmike** [comment]
+1 
approve
/lgtm

**Comment by mrbobbytables** [comment]
Hey there @astrieanna, thank you for all the work you've done for the project :)

I've created PR #497   to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
