### ISSUE TITLE
REQUEST: New membership for googs1025

### ISSUE THREAD

**Issue by googs1025** [kubernetes/org#4921]
### GitHub Username

@googs1025

### Organization you are requesting membership in

kubernetes-sigs, kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kannon92

### Sponsor 2

@kerthcet

### Sponsor 3

@danielvegamyhre 

### List of contributions to the Kubernetes project

- PRs
  - [PRs in Kueue](https://github.com/kubernetes-sigs/kueue/pulls?q=is%3Apr+author%3Agoogs1025+is%3Aclosed)
     1. https://github.com/kubernetes-sigs/kueue/pull/2060
     2. https://github.com/kubernetes-sigs/kueue/pull/2055
     3. https://github.com/kubernetes-sigs/kueue/pull/1932
     4. https://github.com/kubernetes-sigs/kueue/pull/1890
     5. https://github.com/kubernetes-sigs/kueue/pull/2011
  
  - [PRs in Jobset](https://github.com/kubernetes-sigs/jobset/pulls?q=is%3Apr+author%3Agoogs1025+is%3Aclosed)
     1. https://github.com/kubernetes-sigs/jobset/pull/426
     2. https://github.com/kubernetes-sigs/jobset/pull/544
     3. https://github.com/kubernetes-sigs/jobset/pull/541
     4. https://github.com/kubernetes-sigs/jobset/pull/540
     5. https://github.com/kubernetes-sigs/jobset/pull/532
     6. https://github.com/kubernetes-sigs/jobset/pull/521
     7. https://github.com/kubernetes-sigs/jobset/pull/507
     8. https://github.com/kubernetes-sigs/jobset/pull/490
     9. https://github.com/kubernetes-sigs/jobset/pull/489
     10. https://github.com/kubernetes-sigs/jobset/pull/503
     11. https://github.com/kubernetes-sigs/jobset/pull/550
     12. https://github.com/kubernetes-sigs/jobset/pull/485

  
  - [PRs in lws](https://github.com/kubernetes-sigs/lws/pulls?q=is%3Apr+author%3Agoogs1025+is%3Aclosed)
     1. https://github.com/kubernetes-sigs/lws/pull/112
     2. https://github.com/kubernetes-sigs/lws/pull/108
     3. https://github.com/kubernetes-sigs/lws/pull/101
     4. https://github.com/kubernetes-sigs/lws/pull/95
     5. https://github.com/kubernetes-sigs/lws/pull/80
     13. https://github.com/kubernetes-sigs/lws/pull/78
- Issues:
   - [Issues in lws]
      1. https://github.com/kubernetes-sigs/lws/issues/100
   - [Issues in Jobset]
      1. https://github.com/kubernetes-sigs/jobset/issues/430
      2. https://github.com/kubernetes-sigs/jobset/issues/506
      3. https://github.com/kubernetes-sigs/jobset/issues/497
      4. https://github.com/kubernetes-sigs/jobset/issues/430
      5. https://github.com/kubernetes-sigs/jobset/issues/548
      6. https://github.com/kubernetes-sigs/jobset/issues/476
      7. https://github.com/kubernetes-sigs/jobset/issues/548
      8. https://github.com/kubernetes-sigs/jobset/issues/360
      9. https://github.com/kubernetes-sigs/jobset/issues/425
      10. https://github.com/kubernetes-sigs/jobset/issues/478
      11. https://github.com/kubernetes-sigs/jobset/issues/519
   - [Issues in Kubernetes]
      1. https://github.com/kubernetes/kubernetes/issues/116733
      2. https://github.com/kubernetes/kubernetes/issues/118594
      3. https://github.com/kubernetes/kubernetes/issues/120776
      4. https://github.com/kubernetes/kubernetes/issues/124238

Thanks for the support : @kerthcet @kannon92 @danielvegamyhre

**Comment by kerthcet** [comment]
+1, great work @googs1025

**Comment by kannon92** [comment]
+1. @googs1025 has been very active to reviews and looking forward to continuing!

I think you should also add yourself to kubernetes org also.

**Comment by jasonbraganza** [comment]
@googs1025, if you modify the issue and add `kubernetes` in your request, I’ll be to do both at once

**Comment by googs1025** [comment]
Thank you for your support, it has been modified. @jasonbraganza @kannon92

**Comment by danielvegamyhre** [comment]
+1, @googs1025 has been very helpful with their contributions to JobSet.

**Comment by jasonbraganza** [comment]
/assign

@googs1025, thank you for all your contributions 🙂

I’ve created PR #4930 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
