### ISSUE TITLE
REQUEST: New membership for levi106

### ISSUE THREAD

**Issue by levi106** [kubernetes/org#4923]
### GitHub Username

@levi106

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@nasa9084

### Sponsor 2

@bells17

### List of contributions to the Kubernetes project

- PRs authored
  - https://github.com/kubernetes/website/pulls?q=+is%3Apr+author%3Alevi106+

**Comment by Okabe-Junya** [comment]
I'm not a sponsor, but +1 from me as a one of the kubernetes member :) Thank you for all contributions to @kubernetes!!

**Comment by bells17** [comment]
+1

**Comment by MadhavJivrajani** [comment]
@bells17 we can move forward with your PR once @nasa9084 gives a +1 as well!

**Comment by inductor** [comment]
@MadhavJivrajani Hey! I'm a localization owner in SIG-Docs. I approve this (in case @nasa9084 is not responding)

**Comment by MadhavJivrajani** [comment]
Awesome, thanks, looks like there's 3 different sponsors, I've approved the PR.

Thanks for your contributions @levi106 and welcome to the org!
