### ISSUE TITLE
REQUEST: New membership for tico88612

### ISSUE THREAD

**Issue by tico88612** [kubernetes/org#4933]
### GitHub Username

@tico88612

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [x] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@tengqm

### Sponsor 2

@yankay

### List of contributions to the Kubernetes project

- kubernetes/website: https://github.com/kubernetes/website/pulls?q=is:pr+author:tico88612+merged:%3C2024-05-05
- kubernetes-sigs/kubespray: https://github.com/kubernetes-sigs/kubespray/pulls?q=is:pr+author:tico88612

**Comment by tengqm** [comment]
+1
and, looking forward to your future contributions.

**Comment by yankay** [comment]
+1,
@tico88612 has been very awsome work in kubespray
Welcome to join 🎉🎉🎉

**Comment by googs1025** [comment]
@tico88612 🎉🎉🎉  +1 
Although I am not qualified to vote, I still want to +1. We come from the same hometown, and we hope that more friends who come here can contribute to the community together!
