### ISSUE TITLE
REQUEST: New membership for leonardoce

### ISSUE THREAD

**Issue by leonardoce** [kubernetes/org#4940]
### GitHub Username

leonardoce

### Organization you are requesting membership in

kubernetes-csi

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

xing-yang

### Sponsor 2

jsafrane

### List of contributions to the Kubernetes project

PRs:

- https://github.com/kubernetes-csi/external-snapshotter/pull/1067
- https://github.com/kubernetes-csi/external-snapshotter/pull/1066
- https://github.com/kubernetes-csi/external-snapshotter/pull/1031
- https://github.com/kubernetes-csi/external-snapshotter/pull/966
- https://github.com/kubernetes-csi/external-snapshotter/pull/961
- https://github.com/kubernetes-csi/external-snapshotter/pull/959
- https://github.com/kubernetes-csi/csi-driver-host-path/pull/475
- https://github.com/kubernetes-csi/external-snapshotter/pull/1079
- https://github.com/kubernetes-csi/external-snapshotter/pull/1069
- https://github.com/kubernetes-csi/external-snapshotter/pull/1068

Issues:

- https://github.com/kubernetes-csi/external-snapshotter/issues/969

**Comment by xing-yang** [comment]
+1

Thank you for your contributions, @leonardoce!

**Comment by xing-yang** [comment]
cc @jsafrane
