### ISSUE TITLE
REQUEST: New membership for liyuerich

### ISSUE THREAD

**Issue by liyuerich** [kubernetes/org#4943]
### GitHub Username

@liyuerich

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@carlory

### Sponsor 2

@pohly

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pull/121256
https://github.com/kubernetes/kubernetes/pull/120631
https://github.com/kubernetes/kubernetes/pull/120251
https://github.com/kubernetes/kubernetes/pull/120250
https://github.com/kubernetes/kubernetes/pull/120038
https://github.com/kubernetes/kubernetes/pull/119948
https://github.com/kubernetes/kubernetes/pull/118006

**Comment by carlory** [comment]
+1 welcome

**Comment by pohly** [comment]
+1

Thanks, and looking forward to more of your contributions.

**Comment by liyuerich** [comment]
thanks carlory and Patrick,  hope I could contribute more with all of your fully support.
