### ISSUE TITLE
REQUEST: New membership for ivanvc

### ISSUE THREAD

**Issue by ivanvc** [kubernetes/org#4946]
### GitHub Username

@ivanvc

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jmhbnz

### Sponsor 2

@ahrtr

### List of contributions to the Kubernetes project

I'm requesting access to `kubernetes` and `kubernetes-sigs`, as I'm working in the test infrastructure for etcd (Prow jobs).

* List of PRs from `etcd-io/etcd`: https://github.com/etcd-io/etcd/pulls?q=+is%3Apr+author%3Aivanvc
* List of issues from `etcd-io/etcd`: https://github.com/etcd-io/etcd/issues?q=is%3Aissue+author%3Aivanvc
* List of PRs reviewed in `etcd-io/etcd`: https://github.com/etcd-io/etcd/pulls?q=is%3Apr+reviewed-by%3Aivanvc
* List of PRs from `etcd-io/bbolt`: https://github.com/etcd-io/bbolt/pulls?q=is%3Apr+author%3Aivanvc+
* List of issues from `etcd-io/bbolt`: https://github.com/etcd-io/bbolt/issues?q=is%3Aissue+author%3Aivanvc
* List of PRs reviewed in `etcd-io/bbolt`: https://github.com/etcd-io/bbolt/pulls?q=is%3Apr+reviewed-by%3Aivanvc
* Participation in `kubernetes/test-infra`:
  * https://github.com/kubernetes/test-infra/issues/32443
  * https://github.com/kubernetes/test-infra/pull/32563
  * https://github.com/kubernetes/test-infra/pull/32446
  * https://github.com/kubernetes/test-infra/pull/32435

**Comment by jmhbnz** [comment]
+1 - Thanks for all your hard work on sig-etcd @ivanvc!

**Comment by ahrtr** [comment]
+1 Thanks for your contributions.

**Comment by MadhavJivrajani** [comment]
+1!
