### ISSUE TITLE
REQUEST: New membership for j-griffith

### ISSUE THREAD

**Issue by j-griffith** [kubernetes/org#495]
### GitHub Username
@j-griffith 
### Organization you are requesting membership in
@kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @msau42 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by msau42** [comment]
+1

John has been active in the kubernetes-csi org for the iscsi library and driver, and namespace transfer and cloning:
https://github.com/kubernetes-csi/csi-lib-iscsi/pull/1
https://github.com/kubernetes-csi/external-provisioner/pull/220
https://github.com/kubernetes/enhancements/pull/643
https://github.com/kubernetes/enhancements/pull/642

**Comment by mrbobbytables** [comment]
@j-griffith I've created PR #497 to add you to @kubernetes-csi. Once it gets merged, you should get a membership invite notification. :)

Just as an FYI for the future, as member of @kubernetes you do not need to seek sponsorship to be added to any of the other related orgs. You're implicitly allowed, just have to request it. There's a long term goal to automate membership in the related orgs, but for now it is still a manual process.

Hope that helps!

/assign
