### ISSUE TITLE
REQUEST: New membership for adilGhaffarDev

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes/org#4953]
### GitHub Username

@adilGhaffarDev

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@furkatgofurov7

### Sponsor 2

@cahillsf

### List of contributions to the Kubernetes project

I am already a member of Kubernetes-sigs, and I want to request membership in Kubernetes. As mentioned here: https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem I am eligible for it

**Comment by furkatgofurov7** [comment]
+1 from me, happy to sponsor Adil for Org membership

**Comment by cahillsf** [comment]
+1 from me as well!

**Comment by Priyankasaggu11929** [comment]
> I am already a member of Kubernetes-sigs, and I want to request membership in Kubernetes. As mentioned here: https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem I am eligible for it

@adilGhaffarDev, please feel free to directly raise a PR to add yourself to kubernetes org.

Or, the NMCs will process this request in the next batch.  :slightly_smiling_face:

**Comment by ydFu** [comment]
@adilGhaffarDev 
I want to express my heartfelt gratitude for your invaluable contributions to community endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #4954 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes family! 🎉🚀

Best regards,

/assign
/cc @Priyankasaggu11929
