### ISSUE TITLE
REQUEST: New membership for snehachhabria

### ISSUE THREAD

**Issue by snehachhabria** [kubernetes/org#4960]
### GitHub Username

snehachhabria

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

youngnick

### Sponsor 2

robscott

### List of contributions to the Kubernetes project

Gateway API
- https://github.com/kubernetes-sigs/gateway-api/pull/3095
- https://github.com/kubernetes-sigs/gateway-api/pull/2629
- https://github.com/kubernetes-sigs/gateway-api/pull/3021

very involved in the Gateway API project

**Comment by robscott** [comment]
Big +1, thanks for all the contributions @snehachhabria!

**Comment by youngnick** [comment]
+1 from me as well, thanks @snehachhabria!

**Comment by jasonbraganza** [comment]
/assign

@snehachhabria, thank you for all your contributions 🙂

I’ve created PR #4961 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
