### ISSUE TITLE
REQUEST: New membership for <your-GH-handle>

### ISSUE THREAD

**Issue by wweiwei-li** [kubernetes/org#4962]
### GitHub Username

@wweiwei-li

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@oliviassss

### Sponsor 2

@josh-ferrell

### List of contributions to the Kubernetes project

PRs merged
* https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3688
* https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3594

**Comment by josh-ferrell** [comment]
+1 from me

**Comment by oliviassss** [comment]
+1, thanks for your contribution!

**Comment by dims** [comment]
@wweiwei-li Do you mind sharing why you are skipping the SUGGESTED check list items?

**Comment by jasonbraganza** [comment]
@josh-ferrell, a cursory search did not lead me to you being listed in a `owners` file in one of the sigs. Please correct me if I’m wrong? Else, @wweiwei-li will have to look for another sponsor

@oliviassss, would you kindly list you work org on your profile or here on this issue? need to confirm that sponsors are from different orgs, as per membership guidelines.

Thank you both!

**Comment by jasonbraganza** [comment]
> @oliviassss, would you kindly list you work org on your profile or here on this issue? need to confirm that sponsors are from different orgs, as per membership guidelines.

Apologies @oliviassss! it’s in the profile! I missed it.

**Comment by josh-ferrell** [comment]
Hey @jasonbraganza I didn't realize the requirement to be in an OWNERs group. @wweiwei-li @oliviassss I'll reach out via DM with some recommendations.
