### ISSUE TITLE
REQUEST: New membership for <Melony - New Release Notes Shadow for K8S 1.31  >

### ISSUE THREAD

**Issue by cloudmelon** [kubernetes/org#4966]
### GitHub Username

cloudmelon

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [x] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Priyankasaggu11929

### Sponsor 2

@neoaggelos

### List of contributions to the Kubernetes project

- Minikube 
- Kubernetes / Kubernetes Docs
- Helm
- Istio
- Open Service Mesh (OSM)
- Docker (? - for the non commercial part :))

**Comment by cloudmelon** [comment]
cc @katcosgrove @gracenng @Priyankasaggu11929 thanks everyone :)

**Comment by Priyankasaggu11929** [comment]
+1

**Comment by npolshakova** [comment]
+1

**Comment by cloudmelon** [comment]
Hi there, anything still needed from me to close this item ? Thanks :)

**Comment by katcosgrove** [comment]
It'll be closed when the person in charge of adding new folks to the org comes through :) You're all good for now!

**Comment by cloudmelon** [comment]
Sounds good ! thanks for the update :)

**Comment by ydFu** [comment]
@cloudmelon 
I want to express my heartfelt gratitude for your invaluable contributions to community endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #4982 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes family! 🎉🚀

Best regards,

/assign

**Comment by cloudmelon** [comment]
Thanks @ydFu for your nice words ! I'm excited to be part of the organization and look forward to make positive impact to the community :)
