### ISSUE TITLE
REQUEST: New membership for wweiwei-li

### ISSUE THREAD

**Issue by wweiwei-li** [kubernetes/org#4968]
### GitHub Username

@wweiwei-li

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@oliviassss

### Sponsor 2

@elmiko

### List of contributions to the Kubernetes project

PRs merged
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3688
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3594

Issue respond
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3692
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3689
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3636

**Comment by dims** [comment]
thanks @wweiwei-li

**Comment by elmiko** [comment]
@wweiwei-li need to update the title, otherwise lgtm

+1 from me

**Comment by oliviassss** [comment]
+1 from me

**Comment by jasonbraganza** [comment]
/assign

@wweiwei-li, thank you for all your contributions 🙂

I’ve created PR #4970 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
