### ISSUE TITLE
REQUEST: New membership for omerap12

### ISSUE THREAD

**Issue by omerap12** [kubernetes/org#4974]
### GitHub Username

@omerap12 

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@oliviassss

### Sponsor 2

@mboersma
@mloiseleur

### List of contributions to the Kubernetes project

List of contributions to the Kubernetes project:
https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/pull/240
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3697
https://github.com/kubernetes-sigs/cluster-api-operator/pull/525
https://github.com/kubernetes/test-infra/pull/32616
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2035
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2034
https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3683
https://github.com/kubernetes-sigs/external-dns/pull/4432
https://github.com/kubernetes-sigs/jobset/pull/558
https://github.com/kubernetes-sigs/descheduler/pull/1390
https://github.com/kubernetes-sigs/prow/pull/141
https://github.com/kubernetes/test-infra/pull/32532
https://github.com/kubernetes-sigs/kubectl-validate/pull/124
https://github.com/kubernetes-sigs/external-dns/pull/4405

**Comment by mloiseleur** [comment]
/approve
/lgtm
+1

**Comment by mboersma** [comment]
/lgtm
+1

Omer has been very productive in kubernetes-sigs, and was responsive to feedback on his PRs I've reviewed. Welcome!

**Comment by oliviassss** [comment]
+1 from me, welcome!

**Comment by jasonbraganza** [comment]
/assign

@omerap12, thank you for all your contributions 🙂

I’ve created PR  #4974 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
