### ISSUE TITLE
REQUEST: New membership for mbianchidev

### ISSUE THREAD

**Issue by mbianchidev** [kubernetes/org#4975]
### GitHub Username

@mbianchidev

### Organization you are requesting membership in

kubernetes
kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [x] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@a-mccarthy

### Sponsor 2

@Priyankasaggu11929

### List of contributions to the Kubernetes project

Sig Projects I'm involved in:

Kubernetes v1.31 (release comms)

#sig-release
#release-comms
#sig-docs
#sig-docs-blog

**Comment by Priyankasaggu11929** [comment]
+1

**Comment by jasonbraganza** [comment]
@a-mccarthy, ping! a +1 will help me process this :)

**Comment by Priyankasaggu11929** [comment]
cc: @neoaggelos, (please +1, if you catch it before) :slightly_smiling_face:

**Comment by neoaggelos** [comment]
+1

**Comment by a-mccarthy** [comment]
+1!

**Comment by jasonbraganza** [comment]
/assign

@mbianchidev, looking forward to all your contributions 🙂

I’ve created PR #4988 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by mbianchidev** [comment]
Hey @jasonbraganza thanks a ton! 
I'll do my best 😎
