### ISSUE TITLE
REQUEST: Membership in netlify project kubernetes-sigs-nfd

### ISSUE THREAD

**Issue by marquiz** [kubernetes/org#4984]
### Organization or Repo

kubernetes-sigs/node-feature-discovery

### User affected

@marquiz

### Describe the issue

I'm an admin of the [node-feature-discovery](https://github.com/kubernetes-sigs/node-feature-discovery) project. I'd like to request access to the corresponding [netlify project](https://app.netlify.com/sites/kubernetes-sigs-nfd).

Ref:
https://kubernetes.slack.com/archives/C1TU9EB9S/p1716879792314289

**Comment by mrbobbytables** [comment]
@marquiz can you reply with or dm me your email address? thats how we are able to add people in netlify.

**Comment by marquiz** [comment]
Resolved. Thanks @mrbobbytables 👍
/close
