### ISSUE TITLE
REQUEST: New membership for ramineni

### ISSUE THREAD

**Issue by ramineni** [kubernetes/org#499]
### GitHub Username
@ramineni

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @adisky 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=is%3Apr+is%3Amerged+org%3Akubernetes+org%3Akubernetes-sigs+author%3Aramineni
https://github.com/search?q=is%3Apr+reviewed-by%3Aramineni+org%3Akubernetes+-author%3Aramineni
- Issues responded to
https://github.com/search?q=is%3Aissue+commenter%3Aramineni+org%3Akubernetes
- SIG projects I am involved with
kubernetes/cloud-provider-openstack

/area github-membership

**Comment by dims** [comment]
+1 welcome!

**Comment by adisky** [comment]
+1 from me!!!

**Comment by mrbobbytables** [comment]
Hey there @ramineni, thank you for  everything you've done for the project so far :)

I've created PR #502 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
