### ISSUE TITLE
REQUEST: Create repository kubernetes-sigs/multi-network-api

### ISSUE THREAD

**Issue by mskrocki** [kubernetes/org#4996]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

multi-network-api

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

mskrocki, dougbtv, MikeZappa87,aojea

### Who should have write access?

mskrocki, dougbtv, MikeZappa87,aojea

### Who should be listed as approvers in OWNERS?

mskrocki, dougbtv, MikeZappa87,aojea

### Who should be listed in SECURITY_CONTACTS?

mskrocki, dougbtv, MikeZappa87,aojea

### What should the repo description be?

API for Multi-Network feature.

### What SIG and subproject does this fall under?

SIG Network

### Please provide references to appropriate approval for this new repo

This is repository for the Multi-Network feature API, that is the result of the subproject in SIG Network of the same name https://github.com/kubernetes/community/pull/7048.

**Comment by mskrocki** [comment]
cc @dougbtv @MikeZappa87 @aojea

**Comment by aojea** [comment]
> This is repository for the Multi-Network feature API, that is the result of the subproject in SIG Network of the same name [kubernetes/community#7048](https://github.com/kubernetes/community/pull/7048).

let's add this to the sig network meeting agenda to discuss there

**Comment by aojea** [comment]
Discussed in sig-network meeting on Jun6th https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit#bookmark=id.g5u0v9owdfdv

/lgtm

**Comment by mrbobbytables** [comment]
repo has been created
teams added in #5078 
updates to sigs.yaml: https://github.com/kubernetes/community/pull/7988

dougbtv is not a k8s org member and cannot be added
mskrocki and MikeZappa87 are not currently members of k-sigs, so for now the teams only have @aojea to get this going.

once those PRs are closed, it should be g2g :+1:

**Comment by Priyankasaggu11929** [comment]
All PRs are merged. Closing.

/close
