### ISSUE TITLE
REQUEST: New membership for geekygirldawn

### ISSUE THREAD

**Issue by geekygirldawn** [kubernetes/org#500]
### GitHub Username
@geekygirldawn

### Organization you are requesting membership in
@kubernetes

### Requirements
- [√] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [√] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [√] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [√] I am actively contributing to 1 or more Kubernetes subprojects
- [√] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [√] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman 
- @castrojo 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
https://github.com/kubernetes/community/commits?author=geekygirldawn
- Issues responded to:
https://github.com/kubernetes/community/issues/3129
- SIG projects I am involved with
[Contributor Summit Barcelona](https://docs.google.com/document/d/1oLXv5_rM4f645jlXym_Vd7AUq7x6DV-O87E6tcW1sjU/edit) - Content (General) and Transparency Lead

**Comment by castrojo** [comment]
+1 from me!

**Comment by parispittman** [comment]
+1! 🎊

**Comment by mrbobbytables** [comment]
@geekygirldawn thanks for everything you're doing with the contributor summit :)

 I've created PR #502 to add you to the @kubernetes org. Once it gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
/pony party
