### ISSUE TITLE
REQUEST: New membership for <yeedove>

### ISSUE THREAD

**Issue by yeedove** [kubernetes/org#5004]
### GitHub Username

@yeedove

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@gauravkghildiyal

### Sponsor 2

@mlavacca

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-sigs/gateway-api/pull/3129
- https://github.com/kubernetes-sigs/gateway-api/pull/3076
- https://github.com/kubernetes-sigs/gateway-api/pull/2934
- https://github.com/kubernetes-sigs/gateway-api/pull/2915
- https://github.com/kubernetes-sigs/gateway-api/pull/2892
- https://github.com/kubernetes-sigs/kueue/pull/2006
- https://github.com/kubernetes-sigs/kustomize/pull/5707

**Comment by mlavacca** [comment]
Thanks for your contributions, @yeedove! 

Big 👍

**Comment by gauravkghildiyal** [comment]
+1

Thanks for all the contributions to gwctl!

**Comment by jasonbraganza** [comment]
@gauravkghildiyal would you kindly mention your work org, either on your profile or here on this issue?
Asking because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require that sponsors be from two different orgss

**Comment by gauravkghildiyal** [comment]
Hi @jasonbraganza, sure updated my profile.

**Comment by jasonbraganza** [comment]
/assign

@yeedove, thank you for all your contributions 🙂

I’ve created PR #5005 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
