### ISSUE TITLE
REQUEST: New membership for gabesaba

### ISSUE THREAD

**Issue by gabesaba** [kubernetes/org#5008]
### GitHub Username

gabesaba

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

alculquicondor

### Sponsor 2

tenzen-y

### List of contributions to the Kubernetes project

I contributed to the Kubernetes Scheduler, and to Kueue.

## PRs
- [k8/scheduler#124618 - gated pod performance](https://github.com/kubernetes/kubernetes/pull/124618)
- [k8/scheduler#125197 - NodeToStatusMap performance](https://github.com/kubernetes/kubernetes/pull/125197)
- [k8/scheduler#124669 - increase gated pod test coverage](https://github.com/kubernetes/kubernetes/pull/124669)
- [Kueue#1952 - fix primary performance issue in Pod Integration](https://github.com/kubernetes-sigs/kueue/pull/1952)
- [Kueue#1973 - Pod Integration performance fixture](https://github.com/kubernetes-sigs/kueue/pull/1973)
- [Kueue#2102 - add exponential backoff when no schedule](https://github.com/kubernetes-sigs/kueue/pull/2102#issue-2271400231)
- [Kueue#1897 - reduce unnecessary reconciles](https://github.com/kubernetes-sigs/kueue/pull/1897)
- [Kueue#1761 - speed up integ tests from 19.0 to 8.5 mins](https://github.com/kubernetes-sigs/kueue/pull/1761)

### Opened
- [gated pods performance issue - fixed above in #124618 ](https://github.com/kubernetes/kubernetes/issues/124384)
- [Improve Handling of NodeStatus](https://github.com/kubernetes/kubernetes/issues/125345)
### Reviewed
- [Kueue#1838](https://github.com/kubernetes-sigs/kueue/pull/1838)
- [Kueue#1869](https://github.com/kubernetes-sigs/kueue/pull/1869)
- [Kueue#1935 (KEP)](https://github.com/kubernetes-sigs/kueue/pull/1935)
- [Kueue#2099](https://github.com/kubernetes-sigs/kueue/pull/2099)
- [Kueue#2210](https://github.com/kubernetes-sigs/kueue/pull/2210)
- [K8#125293](https://github.com/kubernetes/kubernetes/pull/125293)
- [K8#122251](https://github.com/kubernetes/kubernetes/pull/122251)
### Participated
- [Debug testgrid failure - solved in Kueue#2102 above](https://github.com/kubernetes-sigs/kueue/issues/2097)
- [k8/scheduler - throughput degradation daemonset - fixed in #125197 above](https://github.com/kubernetes/kubernetes/issues/124709)

**Comment by mimowo** [comment]
+1 thank you for the contributions!

**Comment by jasonbraganza** [comment]
@alculquicondor request your review and +1 on this please

**Comment by alculquicondor** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@gabesaba, thank you for all your contributions 🙂

I’ve created PR #5014 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by gabesaba** [comment]
Thank you, all :)
