### ISSUE TITLE
REQUEST: Archive repo https://github.com/kubernetes-sigs/etcdadm

### ISSUE THREAD

**Issue by neolit123** [kubernetes/org#5013]
### Repository to archive

https://github.com/kubernetes-sigs/etcdadm

### Repository and/or sig subproject owners that are approving this archival

@justinsb @dlipovetsky

### When should this be done

anytime

### Additional context for request

SIG CL is the owner the etcdadm subproject:
https://github.com/kubernetes-sigs/etcdadm

the project was relatively low activity, but it contained one key component used by the kOps project - etcd-manager.

we opened the conversation on a ticket and on the SIG CL mailing list to archive the etcdadm repository:
https://github.com/kubernetes-sigs/etcdadm/issues/395
https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/SH463K1CmHs

in the meantime we extracted etcd-manager to a new subproject repo that is now owned by SIG etcd:
https://github.com/kubernetes-sigs/etcd-manager

what is left for us to do is archive etcdadm.

**Comment by neolit123** [comment]
cc @fabriziopandini @vincepri @hakman

**Comment by justinsb** [comment]
cc @hakman 

Two things I would ideally like to get done first, but aren't technically blocking:

1) We should decide whether we want to change the path of the image, as @neolit123 pointed out currently that it contains "etcdadm": `registry.k8s.io/etcdadm/etcd-manager-slim:v3.0.20230925`

2) It would be nice if we had the build pipelines working on the new repo, I don't _think_ we've set them up yet.  The concern is that if there's a CVE (or similar), it might slow down a rapid release.

**Comment by hakman** [comment]
@justinsb :

1. For sure we will change the path to something like `registry.k8s.io/etcd-manager/etcd-manager-slim`. Not sure if `registry.k8s.io/etcd-manager` exists yet though.
2. I think we can work on this in the next few weeks and should be relatively simple to get it working, assuming 1) is addressed. The risk should be minimal.

**Comment by neolit123** [comment]
guithub-team, we are ready to proceed with this archival.
PTAL when possible.

**Comment by hakman** [comment]
> 2. It would be nice if we had the build pipelines working on the new repo, I don't think we've set them up yet. The concern is that if there's a CVE (or similar), it might slow down a rapid release.

@justinsb FYI, build pipelines are working on the new `etcd-manager` repo, so there is no blocker remaining for archiving the `etcdadm` repo.

**Comment by neolit123** [comment]
k/community cleanup PR:
- https://github.com/kubernetes/org/issues/5013

**Comment by cblecker** [comment]
This archival is now complete.

**Comment by neolit123** [comment]
thanks  @cblecker
