### ISSUE TITLE
REQUEST: New membership for PrasadG193

### ISSUE THREAD

**Issue by PrasadG193** [kubernetes/org#5019]
### GitHub Username

@PrasadG193

### Organization you are requesting membership in

kubernetes-csi

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@bswartz

### List of contributions to the Kubernetes project

- Co-author: Contributed in designing and implementing prototypes for [KEP-3314: CSI Changed Block Tracking ](https://github.com/kubernetes/enhancements/pull/4082)
- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/2
- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/1

**Comment by jasonbraganza** [comment]
@xing-yang, @bswartz a +1 after you review this request, would help me process this one. Thank you :)

**Comment by jasonbraganza** [comment]
@bswartz, i looked up but I was unable to find you in an OWNERS file. ([a requisite for being a sponsor](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements)).  Would you point me to a place you’re listed in, in case I overlooked someplace?  

Failing, which @PrasadG193 might have to look for another sponsor.

**Comment by bswartz** [comment]
Which owners file are you looking in? I clicked on that link and I can't see what the requirements are for the csi group.

**Comment by jasonbraganza** [comment]
I was pointing to this subpoint in the requirements. 

> - Sponsors must be reviewers or approvers in at least one OWNERS file within one of the [Kubernetes GitHub organizations](https://github.com/kubernetes/community/blob/master/github-management#actively-used-github-organizations)*.

A listing in any OWNERS file in the kubernetes orgs should be fine for me to go ahead. (co sponsor Xing Yang, is listed here, for example: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-csi/OWNERS)

**Comment by bswartz** [comment]
These are the things I own:
* https://github.com/kubernetes-csi/volume-data-source-validator/blob/master/OWNERS
* https://github.com/kubernetes-csi/lib-volume-populator/blob/master/OWNERS
* https://github.com/container-storage-interface/spec/blob/master/OWNERS

They are all tangential to the main kubernetes project. It's up to you to interpret the rules in this case. If the rules require someone that owns code in kubernetes proper we'll need another sponsor.

**Comment by jasonbraganza** [comment]
@bswartz, no this is exactly it. I’m sorry I missed them. Thank you very much
will process the request tomorrow

**Comment by bswartz** [comment]
For the record, I +1 this membership

**Comment by jasonbraganza** [comment]
/assign

@PrasadG193, thank you for all your contributions. Looking forward to so much more 🙂

I’ve created PR #5027 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by PrasadG193** [comment]
Thank you!! 🙏

**Comment by xing-yang** [comment]
Looks like I missed this.

+1
