### ISSUE TITLE
REQUEST: New membership for mauri870

### ISSUE THREAD

**Issue by mauri870** [kubernetes/org#5020]
### GitHub Username

@mauri870

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@MadhavJivrajani

### Sponsor 2

@wojtek-t

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pulls/25486
https://github.com/kubernetes/kubernetes/issues/125484
https://github.com/kubernetes/kubernetes/issues/125234
https://github.com/kubernetes/kubernetes/pull/125136
https://github.com/kubernetes/kubernetes/pull/125450
https://github.com/kubernetes/kubernetes/pull/125272
https://github.com/kubernetes/kubernetes/pull/125176
https://github.com/kubernetes/kubernetes/pull/61595
https://github.com/kubernetes/kubernetes/issues/125339
https://github.com/kubernetes/kubectl/issues/1610

Being a member of the Go open-source team I have also aided in triaging issues related to the project and dependencies, such as containerd.

**Comment by wojtek-t** [comment]
+1

**Comment by mauri870** [comment]
Closing this. After careful consideration and discussion with org members, I need to find sponsors with whom I've worked more closely and have contributed longer to the project.

Sorry for any inconvenience.

**Comment by mauri870** [comment]
Reopening this as @MadhavJivrajani kindly offered to be a sponsor. I appreciate the vote of confidence!

**Comment by MadhavJivrajani** [comment]
+1!

Thanks for your work! And thanks for helping us out with Go related issues as well!

**Comment by jasonbraganza** [comment]
/assign

@mauri870, thank you for all your contributions 🙂

I’ve created PR #5024 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
