### ISSUE TITLE
REQUEST: New membership for ArkaSaha30

### ISSUE THREAD

**Issue by ArkaSaha30** [kubernetes/org#5022]
### GitHub Username

@ArkaSaha30

### Organization you are requesting membership in

etcd-io

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jmhbnz

### Sponsor 2

@ivanvc

### List of contributions to the Kubernetes project

PRs authored/reviewed: https://github.com/pulls?q=is%3Apr+user%3Aetcd-io+mentions%3AArkaSaha30
Issues authored/reviewed: https://github.com/issues?user=etcd-io&q=is%3Aissue+mentions%3AArkaSaha30&user=etcd-io

Additionally I am also involved in Kubernetes and Kubernetes-SIGs projects.

**Comment by henrybear327** [comment]
Thanks for all the great work @ArkaSaha30 !

**Comment by ahrtr** [comment]
+1

Thanks @ArkaSaha30 for all your contribution to etcd!

**Comment by humblec** [comment]
+1
Keep rocking @ArkaSaha30 !

**Comment by ivanvc** [comment]
Thanks for all your contributions, @ArkaSaha30. Looking forward to having you as an etcd team member.

**Comment by jmhbnz** [comment]
+1 Well deserved @ArkaSaha30, thank you.

**Comment by dims** [comment]
+1 from me!

**Comment by MadhavJivrajani** [comment]
+1! ❤️

**Comment by jasonbraganza** [comment]
Done! (or rather it will be as soon as #5024 merges) Thank you for all you do :)
