### ISSUE TITLE
REQUEST: New membership for Kid-Chang

### ISSUE THREAD

**Issue by Kid-Chang** [kubernetes/org#5023]
### GitHub Username

@Kid-Chang

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sftim

### Sponsor 2

@seokho-son

### List of contributions to the Kubernetes project

PRs reviewed ([k/website](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3AKid-Chang))
- https://github.com/kubernetes/website/pull/44511
- https://github.com/kubernetes/website/pull/44483
- https://github.com/kubernetes/website/pull/42991
- https://github.com/kubernetes/website/pull/36865
- https://github.com/kubernetes/website/pull/35444
- https://github.com/kubernetes/website/pull/35441

**Comment by seokho-son** [comment]
+1 !!

**Comment by sftim** [comment]
I recommend taking the (English language only, I think) [course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) on inclusion. It's optional, so:
+1

**Comment by ydFu** [comment]
@Kid-Chang 
I want to express my heartfelt gratitude for your invaluable contributions to community endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #5025 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes family! 🎉🚀

Best regards,

/assign

**Comment by Kid-Chang** [comment]
@sftim 
Thanks for the video recommendation, I'll be watching it soon!
