### ISSUE TITLE
REQUEST: New membership for micheleberardi 

### ISSUE THREAD

**Issue by micheleberardi** [kubernetes/org#503]
### GitHub Username
@micheleberardi

### Organization you are requesting membership in
@kubernetes

### Requirements
- [ x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@zacharysarah
@rlenferink

That will be:

### List of contributions to the Kubernetes project
I will be working with sig-docs on the Italian localization of the Kubernetes project (https://github.com/kubernetes/website/pull/12425)

**Comment by rlenferink** [comment]
+1 @micheleberardi will be part of the Italian localization team

**Comment by mrbobbytables** [comment]
@micheleberardi, unfortunately @rlenferink cannot sponsor you for @kubernetes org membership. A sponsor must be an approver or reviewer within the org you are seeking membership in. For more information, please see the [membership requirements](https://git.k8s.io/community/community-membership.md#requirements).

**Comment by mrbobbytables** [comment]
Follow-up: I will add a +1 as this is for establishing the Italian localization owners. :)

**Comment by zacharysarah** [comment]
+1 for Italian localization!

**Comment by zacharysarah** [comment]
@rlenferink Are you a member of Kubernetes yet? Do you need a sponsor? 😄

**Comment by rlenferink** [comment]
> @rlenferink Are you a member of Kubernetes yet? Do you need a sponsor? 😄

Thanks for the offer, but I'm already a member of Kubernetes 😄

**Comment by mrbobbytables** [comment]
Hey there @micheleberardi , thanks for kicking off the Italian translation efforts. :)

I've created PR #507 to add you to the @kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
