### ISSUE TITLE
REQUEST: New membership for knqyf263

### ISSUE THREAD

**Issue by knqyf263** [kubernetes/org#5031]
### GitHub Username

@knqyf263

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@PushkarJ

### Sponsor 2

@reylejano

### List of contributions to the Kubernetes project

- https://github.com/aquasecurity/vuln-list-k8s, which will be moved under kubernetes-sigs

**Comment by jasonbraganza** [comment]
@PushkarJ confirming that work org is Credit Karma?

**Comment by PushkarJ** [comment]
@jasonbraganza I work as independent so that would be my affiliation not my employer

**Comment by PushkarJ** [comment]
Fully support this org membership request as this will allow us to leverage their expertise in maintaining official kubernetes CVEs.

**Comment by reylejano** [comment]
+1 from me

**Comment by jasonbraganza** [comment]
/assign

@knqyf263, Welcome to @kubernetes! 🎉 🙂

I’ve created PR #5033 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.


(ref #4873)

**Comment by knqyf263** [comment]
Thanks!

**Comment by tabbysable** [comment]
/party

Welcome!
