### ISSUE TITLE
REQUEST: New membership for mszadkow

### ISSUE THREAD

**Issue by mszadkow** [kubernetes/org#5034]
### GitHub Username

@mszadkow

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alculquicondor

### Sponsor 2

@trasc

### List of contributions to the Kubernetes project

- PR authored:
https://github.com/kubernetes-sigs/kueue/pull/2268
https://github.com/kubernetes-sigs/kueue/pull/2315
https://github.com/kubernetes-sigs/kueue/pull/2334
https://github.com/kubernetes-sigs/kueue/pull/2364
https://github.com/kubernetes-sigs/kueue/pull/2366
https://github.com/kubernetes-sigs/kueue/pull/2381
https://github.com/kubernetes-sigs/kueue/pull/2406

**Comment by trasc** [comment]
+1

Thank you for your contributions!

**Comment by alculquicondor** [comment]
+1

Thanks!

**Comment by MadhavJivrajani** [comment]
Thanks for all your contributions @mszadkow!

I've created https://github.com/kubernetes/org/pull/5037 to add you to the kubernetes-sigs org, once merged you should 
get an invite.

Welcome! 🎉
