### ISSUE TITLE
REQUEST: New membership for gujingit

### ISSUE THREAD

**Issue by gujingit** [kubernetes/org#5036]
### GitHub Username

@gujingit

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@liurupeng

### Sponsor 2

@kerthcet

### RPs
- https://github.com/kubernetes-sigs/lws/pull/163
- https://github.com/kubernetes-sigs/lws/pull/133
- https://github.com/kubernetes-sigs/lws/pull/130

### issues
- https://github.com/kubernetes-sigs/lws/issues/164
- https://github.com/kubernetes-sigs/lws/issues/147

**Comment by kerthcet** [comment]
+1 for @gujingit 
Hope to see more contributors in the future.

**Comment by gujingit** [comment]
@ahg-g

**Comment by ahg-g** [comment]
+1, thanks @gujingit

**Comment by liurupeng** [comment]
+1

**Comment by MadhavJivrajani** [comment]
/assign

I've created a PR to add you in: https://github.com/kubernetes/org/pull/5041
Thanks for your work, and welcome! 🎉
