### ISSUE TITLE
REQUEST: New membership for ricardoapl

### ISSUE THREAD

**Issue by ricardoapl** [kubernetes/org#5039]
### GitHub Username

@ricardoapl

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@dgrisonnet

### Sponsor 2

@mrueg

### List of contributions to the Kubernetes project

PRs authored
- https://github.com/kubernetes/kubernetes/pull/122225
- https://github.com/kubernetes/ingress-nginx/pull/10984
- https://github.com/kubernetes/kube-state-metrics/pull/2370
- https://github.com/kubernetes/kube-state-metrics/pull/2381
- https://github.com/kubernetes-sigs/metrics-server/pull/1499
- https://github.com/kubernetes/kube-state-metrics/pull/2398
- https://github.com/kubernetes/kube-state-metrics/pull/2402
- https://github.com/kubernetes/kube-state-metrics/pull/2396
- https://github.com/kubernetes/kube-state-metrics/pull/2395
- https://github.com/kubernetes-sigs/karpenter/pull/884

PRs reviewed
- https://github.com/kubernetes/community/pull/7708
- https://github.com/kubernetes-sigs/metrics-server/pull/1500
- https://github.com/kubernetes/kube-state-metrics/pull/2411

Issues authored
- https://github.com/kubernetes-sigs/metrics-server/issues/1437
- https://github.com/kubernetes-sigs/karpenter/issues/876
- https://github.com/kubernetes-sigs/prometheus-adapter/issues/638

Issues responded to
- https://github.com/kubernetes/kube-state-metrics/issues/2404
- https://github.com/kubernetes/kube-state-metrics/issues/2345
- https://github.com/kubernetes/kube-state-metrics/issues/2382
- https://github.com/kubernetes/kube-state-metrics/issues/2397
- https://github.com/kubernetes/kube-state-metrics/issues/2380
- https://github.com/kubernetes-sigs/metrics-server/issues/1428
- https://github.com/kubernetes/kube-state-metrics/issues/2313

SIG projects I am involved with
- kubernetes-sigs/metrics-server
- kubernetes/kube-state-metrics

**Comment by dgrisonnet** [comment]
+1

**Comment by mrueg** [comment]
+1

**Comment by MadhavJivrajani** [comment]
/assign 

I've created a PR to add you in: https://github.com/kubernetes/org/pull/5041
Thanks for your work, and welcome! 🎉
