### ISSUE TITLE
Grant admin access for ibm-vpc-block-csi-driver project under kubernetes-sigs

### ISSUE THREAD

**Issue by sameshai** [kubernetes/org#5040]
### Organization or Repo

kubernetes-sigs/ibm-vpc-block-csi-driver

### User affected

@sameshai

### Describe the issue

Grant admin access for the repository to help with making releases on the above-mentioned repository. I need this to proceed with creating release branches and tags from the project.

**Comment by Priyankasaggu11929** [comment]
Hello @sameshai, please feel free to create a PR to add yourself to this GitHub team – https://github.com/kubernetes/org/blob/688e9f711d03cac2b4bf6f106e365678c9b7c572/config/kubernetes-sigs/provider-ibmcloud/teams.yaml#L17-L24

PR will need approval from folks in [this OWNER file](https://github.com/kubernetes/org/blob/688e9f711d03cac2b4bf6f106e365678c9b7c572/config/kubernetes-sigs/provider-ibmcloud/OWNERS).

cc: @kubernetes/provider-ibmcloud-misc

**Comment by sameshai** [comment]
@Priyankasaggu11929 Thanks. 

PR Raise https://github.com/kubernetes/org/pull/5057

**Comment by Priyankasaggu11929** [comment]
#5057 merged. 

/close
