### ISSUE TITLE
Got removed after change github username

### ISSUE THREAD

**Issue by deszhou** [kubernetes/org#5051]
### Organization or Repo

kubernetes/kubernetes, kubernetes/kubernetes-sigs

### User affected

@deszhou 
previous name: yeedove

### Describe the issue

I previously joined the org via https://github.com/kubernetes/org/issues/5004.
I changed my github username today, and later I was removed from the org.

**Comment by jasonbraganza** [comment]
all done @deszhou. you should have received a new invite by now, hopefully
