### ISSUE TITLE
REQUEST: Archive repo kubernetes-sigs/kpng

### ISSUE THREAD

**Issue by shaneutt** [kubernetes/org#5054]
### Repository to archive

kubernetes-sigs/kpng

### Repository and/or sig subproject owners that are approving this archival

mcluseau

### When should this be done

anytime

### Additional context for request

As per the following discussions:

* slack: https://kubernetes.slack.com/archives/C02GA1RSCLR/p1717160872720949
* sig network mailing list: https://groups.google.com/g/kubernetes-sig-network/c/bHwg9WYJXTI

**Comment by shaneutt** [comment]
https://github.com/kubernetes-sigs/kpng/pull/534 needs to happen so people who are interested in the project after it's archival can easily see where and how to get in touch with us, then once that merges all good.

**Comment by mrbobbytables** [comment]
all PRs are merged, this should be able to be closed :)
/close
