### ISSUE TITLE
REQUEST: New membership for Sameer Shaikh

### ISSUE THREAD

**Issue by sameshai** [kubernetes/org#5059]
### GitHub Username

sameshai

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@arahamad

### Sponsor 2

@jsafrane 

### List of contributions to the Kubernetes project

**PRs reviewed / authored**
Primary contributor for https://github.com/IBM/ibm-vpc-file-csi-driver/  and https://github.com/IBM/ibmcloud-volume-file-vpc

500+  PRs reviewed and authored under https://github.com/IBM
10+ PRs reviewed and authored under https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/

Introduce Snapshot feature flag to disable/enable on demand - https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/pull/150/files
Multiple tags formatting issue  - https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/pull/103/files

1 PR authored under https://github.com/kubernetes-csi/external-snapshotter

external-snapshotter constantly retrying CreateSnapshot calls on error w/o backoff https://github.com/kubernetes-csi/external-snapshotter/pull/871

2+ PRs reviewed and authored under https://github.com/openshift/installer and https://github.com/openshift/ibm-vpc-block-csi-driver-operator

**Issues responded to**
Responded to issues under https://github.com/IBM
Responded to issues under https://github.com/kubernetes-sigs
Opened issue under https://github.com/red-hat-storage/ocs-ci

**Comment by jasonbraganza** [comment]
@arahamad and @mrbobbytables, your eyes and +1 on this if you approve, please.

**Comment by arahamad** [comment]
@jasonbraganza , Sameer is from my team and aware about his contribution hence approving

**Comment by sameshai** [comment]
@mrbobbytables and @jasonbraganza  Requesting you to please approve.

**Comment by jasonbraganza** [comment]
@sameshai, we need to wait for your sponsor to approve.

**Comment by mrbobbytables** [comment]
@sameshai do you have another sponsor? I am not familiar with you or youe work and should not be a sponsor^^;

**Comment by sameshai** [comment]
@jsafrane Requesting you to please sponsor.

**Comment by jsafrane** [comment]
+1 from me

**Comment by xing-yang** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@sameshai, thank you for all your contributions 🙂

I’ve created PR #5071 to add you to the Kubernetes(s) Org. 
Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
