### ISSUE TITLE
REQUEST: New Membership for Kubernetes GitHub organization

### ISSUE THREAD

**Issue by SamanKhalife** [kubernetes/org#5061]
### GitHub Username

SamanKhalife

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### List of contributions to the Kubernetes project

- https://kubernetes.io/docs/contribute/localization/#join-the-kubernetes-github-organization
To participate in the localization process of Kubernetes into Farsi, I need to become a member of the Kubernetes GitHub organization.
- https://github.com/kubernetes/website/issues/47142

**Comment by jasonbraganza** [comment]
@SamanKhalife, [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require demonstrating ongoing contributions to the project. I request you to link out to your contributions. Also, since you have sponsors listed, do tick both boxes that you have left unchecked.
 
I would suggest you speak in the SIGs slack channel and your (prospective) sponsors to figure out what needs be done, and whether membership is required for what you need to do.

/assign

**Comment by seokho-son** [comment]
While @SamanKhalife is working on Farsi localization in SIG-Docs, the current activity is not yet sufficient to be considered a member.
@SamanKhalife agrees with this and is willing to continue efforts on reinitiating the Farsi localization team as well as looking for contribution points in SIG-Docs.
I would love to be one of the sponsors once @SamanKhalife is ready (soon)!
