### ISSUE TITLE
REQUEST: New membership for b1gb4by

### ISSUE THREAD

**Issue by b1gb4by** [kubernetes/org#5063]
### GitHub Username

b1gb4by

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Okabe-Junya

### Sponsor 2

@bells17

### List of contributions to the Kubernetes project

- PRs authored
  - https://github.com/kubernetes/website/pull/45102
  - https://github.com/kubernetes/website/pull/45749
  - https://github.com/kubernetes/website/pull/46685
  - https://github.com/kubernetes/website/pull/46686
  - https://github.com/kubernetes/website/pull/46787
  - https://github.com/kubernetes/website/pull/46788
  - https://github.com/kubernetes/website/pull/46802
  - https://github.com/kubernetes/website/pull/47059
  - https://github.com/kubernetes/website/pull/47139
- SIG project
  - https://github.com/kubernetes/website

**Comment by Okabe-Junya** [comment]
+1

b1gb4by has been actively contributing to the l10n of the k/website blog. Thank you very much for your all contributions! And welcome to Kubernetes!

**Comment by bells17** [comment]
+1
Thank you for your contribution.

**Comment by jasonbraganza** [comment]
/assign

@b1gb4by, thank you for all your contributions 🙂

Once @Okabe-Junya’s PR #5064 gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
