### ISSUE TITLE
REQUEST: Create repository kubernetes-sigs/wg-serving

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes/org#5072]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

wg-serving

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

ArangoGutierrez, Jeffwan, SergeyKanzhelev, terrytangyuan

### Who should have write access?

ArangoGutierrez, Jeffwan, SergeyKanzhelev, terrytangyuan

### Who should be listed as approvers in OWNERS?

ArangoGutierrez, Jeffwan, SergeyKanzhelev, terrytangyuan

### Who should be listed in SECURITY_CONTACTS?

ArangoGutierrez, Jeffwan, SergeyKanzhelev, terrytangyuan

### What should the repo description be?

Templates and designs for WG Serving.

### What SIG and subproject does this fall under?

SIG Architecture, SIG Apps, SIG Node, SIG Scheduling, SIG Network

### Please provide references to appropriate approval for this new repo

This is for experimental work, and collect community designs from the new working group, which is sponsored by SIG Arch, Node, Network, Autoscaling, and Scheduling.

**Comment by ArangoGutierrez** [comment]
cc @Jeffwan @SergeyKanzhelev @terrytangyuan

**Comment by terrytangyuan** [comment]
LGTM. Thanks!

**Comment by ahg-g** [comment]
I assume we can create owners file for different directories, right?

**Comment by ArangoGutierrez** [comment]
> I assume we can create owners file for different directories, right?

Tha will be a prow config for the repo.

**Comment by Jeffwan** [comment]
lgtm.

**Comment by ArangoGutierrez** [comment]
Cc @mrbobbytables

**Comment by ArangoGutierrez** [comment]
Repo is live at: https://github.com/kubernetes-sigs/wg-serving

**Comment by mrbobbytables** [comment]
repo has been created :+1: 
Once #5078 and https://github.com/kubernetes/community/pull/7988 merge this should be good to close :+1:
