### ISSUE TITLE
REQUEST: New membership for ritikaguptams

### ISSUE THREAD

**Issue by ritikaguptams** [kubernetes/org#5074]
### GitHub Username

@ritikaguptams

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [x] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jsturtevant

### Sponsor 2

@aravindhp

### List of contributions to the Kubernetes project

I am an active member of the sig-windows weekly meetings and help the community on slack/PR reviews wherever possible. I focus on building better windows container compatibility and support on Kubernetes.

- PRs authored: 
https://github.com/kubernetes/k8s.io/pull/6925
https://github.com/kubernetes-sigs/windows-testing/pull/444
https://github.com/kubernetes/k8s.io/pull/7047

- PR reviewed
https://github.com/kubernetes/k8s.io/pull/7027

On behalf of sig-windows I recently worked on enabling 66 failing e2e tests to support windows containers with hyperv isolation on k8s with solution spanning windows-testing repo, hcsshim and calico CNI:
https://github.com/kubernetes-sigs/windows-testing/pull/429
https://github.com/microsoft/hcsshim/pull/2177
https://github.com/projectcalico/calico/pull/8913

**Comment by jsturtevant** [comment]
+1 Thanks for all the help on bringing up the new Azure community subscription and for identifying the issues in the Hyper-v tests

**Comment by jasonbraganza** [comment]
@aravindhp ping, your eyes on this and a plus one if you approve, would help me process this.
also to confirm that your work org is Softdrive?

asking because [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require that sponsors be from different orgs.

Thank you :)

**Comment by aravindhp** [comment]
+1

@ritikaguptams Thanks for all the help with the Azure community subscription transition. Welcome to the Kubernetes community.

**Comment by aravindhp** [comment]
> also to confirm that your work org is Softdrive?

@jasonbraganza that is correct.

**Comment by jasonbraganza** [comment]
/assign

@ritikaguptams, thank you for all your contributions 🙂

I’ve created PR #5077 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
