### ISSUE TITLE
REQUEST: New membership for fengshunli

### ISSUE THREAD

**Issue by fengshunli** [kubernetes/org#5075]
### GitHub Username

@fengshunli

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-csi, kubernetes-sigs, etcd-io

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@yangjunmyfm192085

### Sponsor 2

@pacoxu

### List of contributions to the Kubernetes project

https://github.com/kubernetes-sigs/kubebuilder/issues?q=fengshunli
https://github.com/kubernetes-sigs/metrics-server/pulls?q=fengshunli+
https://github.com/kubernetes/kubernetes/pulls?q=fengshunli

**Comment by yangjunmyfm192085** [comment]
+1 
Thanks for your contributions to Kubernetes

**Comment by jasonbraganza** [comment]
@fengshunli, community membership guidelines require a demonstration of _“ongoing and long-term commitment to the project.”_

I request you to point me to more work in the project in the past few months, or suggest that you raise a new request once you have enough work in the next few months.

Thank you!

**Comment by fengshunli** [comment]
Of course, I will continue to maintain it.

**Comment by jasonbraganza** [comment]
will close this issue for now then. 
Will wait for you to raise a new one, whenever you are ready.

/close

**Comment by jasonbraganza** [comment]
@fengshunli my mistake. I didn’t see the fresh links you have put in.

Once you get the second approva, I’ll raise a request to get you in to the kubernetes and kubernetes-sigs orgs.

The rest, I’d suggest you ask for approvals later  with more work/other sponsors.

@camilamacedo86, your +1, if you approve of the request please?

**Comment by pacoxu** [comment]
+1

Thanks for your contributions.
- https://github.com/search?q=org%3Akubernetes-sigs+author%3Afengshunli&type=pullrequests 

Hope you can have more contributions in the community.

**Comment by pacoxu** [comment]
> kubernetes, kubernetes-client, kubernetes-csi, kubernetes-sigs, etcd-io

BTW, I can find most of your contributions are in `kubernetes-sigs`, and some in `kubernetes` and `kubernetes-csi`.
- no contributions in etcd or kubernetes-client yet.

> @fengshunli, community membership guidelines require a demonstration of _[“ongoing and long-term commitment to the project.”](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements)_

As @jasonbraganza pointed out that we hope you can continue to contribute, I suggest that you may find your interested one or more SIGs/WGs to participate in. You can refer to https://www.kubernetes.dev/community/community-groups/.

**Comment by jasonbraganza** [comment]
/assign
@fengshunli, thank you for all your contributions 🙂

I’ve created PR #5082 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome back to @kubernetes! 🎉
