### ISSUE TITLE
REQUEST: New membership for oussemos

### ISSUE THREAD

**Issue by oussemos** [kubernetes/org#508]
### GitHub Username
@oussemos

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sieben
- @lledru

### List of contributions to the Kubernetes project
I would like to contribute on the sig-docs on the French localization of the Kubernetes project

**Comment by lledru** [comment]
+1 @oussemos is an approver for FR docs

**Comment by zacharysarah** [comment]
+1 for French localization.

**Comment by mrbobbytables** [comment]
@oussemos thanks for helping to kick start the french translation efforts :)

I've created PR #514   to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
