### ISSUE TITLE
REQUEST: New membership for Edwinhr716

### ISSUE THREAD

**Issue by Edwinhr716** [kubernetes/org#5086]
### GitHub Username

@edwinhr716

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@liurupeng

### Sponsor 2

@kerthcet

### List of contributions to the Kubernetes project

PRs reviewed or authored
https://github.com/kubernetes-sigs/lws/pull/146
https://github.com/kubernetes-sigs/lws/pull/127
https://github.com/kubernetes-sigs/lws/pull/125

Issue assigned/commented:
https://github.com/kubernetes-sigs/lws/issues/115
https://github.com/kubernetes-sigs/lws/issues/106

**Comment by jasonbraganza** [comment]
@kerthcet, to confirm, work org is Daocloud? Thank you :)

**Comment by liurupeng** [comment]
I could confirm!

**Comment by jasonbraganza** [comment]
@liurupeng, to clarify, you confirm a +1 on @Edwinhr716’s request? or the fact that @kerthcet is in Daocloud? 
asking because I’m just a wee bit confused :)

**Comment by kerthcet** [comment]
Sorry for the late reply, +100 for @Edwinhr716 

And yes, I'm from Daocloud org.

**Comment by liurupeng** [comment]
@jasonbraganza I would +1 for Edwin's membership!

**Comment by jasonbraganza** [comment]
Thank @kerthcet & @liurupeng! :)

**Comment by jasonbraganza** [comment]
/assign

@Edwinhr716, thank you for all your contributions 🙂

I’ve created PR #5088 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
