### ISSUE TITLE
REQUEST: New membership for bclau

### ISSUE THREAD

**Issue by bclau** [kubernetes/org#509]
### GitHub Username

bclau

### Organization you are requesting membership in

kubernetes
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @PatrickLang 
- @adelina-t 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/73204
https://github.com/kubernetes/kubernetes/pull/71468
https://github.com/kubernetes/kubernetes/pull/71036
https://github.com/kubernetes/kubernetes/pull/72729
https://github.com/kubernetes/kubernetes/pull/66562
https://github.com/kubernetes/kubernetes/pull/70242
https://github.com/kubernetes/kubernetes/pull/69568
https://github.com/kubernetes/kubernetes/pull/71952
https://github.com/kubernetes/kubernetes/pull/70156
https://github.com/kubernetes-sigs/windows-testing/pull/18
https://github.com/kubernetes-sigs/windows-testing/pull/20
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/73415
https://github.com/kubernetes/kubernetes/issues/74066
- SIG projects I am involved with
sig-windows

**Comment by PatrickLang** [comment]
+1 - Claudiu has been working hard over several months to make the Windows tests work :)

**Comment by adelina-t** [comment]
+1 From me as well. Claudiu has had numerous contributions to testing Windows.

**Comment by mrbobbytables** [comment]
Hey there @bclau, thank you for all your windows efforts :)

I've created PR #514  to add you to both the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign
