### ISSUE TITLE
REQUEST: Create etcd-io/etcd-operator

### ISSUE THREAD

**Issue by jmhbnz** [kubernetes/org#5093]
### New repo, staging repo, or migrate existing

New repository

### Is it a staging repo?

no

### Requested name for new repository

etcd-operator

### Which Organization should it reside

etcd-io

### Who should have admin access?

@ahrtr,@jmhbnz,@hakman,@jberkus,@justinsb

### Who should have write access?

@ahrtr,@jmhbnz,@hakman,@jberkus,@justinsb

### Who should be listed as approvers in OWNERS?

@ahrtr,@jmhbnz,@hakman,@jberkus,@justinsb

### Who should be listed in SECURITY_CONTACTS?

@ahrtr,@jmhbnz,@hakman,@jberkus,@justinsb

### What should the repo description be?

The official Kubernetes operator for etcd.

### What SIG and subproject does this fall under?

sig-etcd & sig-cluster-lifecycle joint etcd-operator working group.

### Please provide references to appropriate approval for this new repo

This was discussed and agreed by wg-etcd-operator leads. Refer to action points of 1st wg-etcd-operator meeting: https://docs.google.com/document/d/1CvAxhZShQSSEE7GcCO4sZO4352Z5Dh1WJUPXePruB4I/edit?usp=sharing

Link to recording in YouTube <link once uploaded>

**Comment by jmhbnz** [comment]
@ahrtr,@jmhbnz,@hakman,@jberkus,@justinsb - Can you please confirm with a +1 I have details correct here, then org admins can proceed with repo creation, thanks! 🙏🏻

**Comment by ahrtr** [comment]
+1 

Thanks @jmhbnz for the quick action based on our discussion in our first WG etcd-operator meeting.

**Comment by neolit123** [comment]
+1

**Comment by hakman** [comment]
+1

**Comment by ahrtr** [comment]
@jmhbnz Probably we can temporarily promote etcd maintainer's permission so that we can create the repository ourselves :)

**Comment by jmhbnz** [comment]
> @jmhbnz Probably we can temporarily promote etcd maintainer's permission so that we can create the repository ourselves :)

We elevate permissions usually to make ourselves temporary repository admins for `etcd-io/etcd` repo. To create new repo I think we would need to add ourselves to https://github.com/kubernetes/org/blob/main/config/etcd-io/org.yaml#L1-L10 as organisation admins, this is separate and I don't think we can be listed there anymore now that k8s GitHub enterprise admins manage our org. At very least they would need to approve the pr as they are `OWNERS` for that file (vs the teams file which we manage ourselves).

Let's just use standard process, I've started it early so we should be able to get it ready for our next working group meeting 🙏🏻

**Comment by Priyankasaggu11929** [comment]
/assign

Thanks for the +1 votes. I'll go ahead with creating the new repo.

**Comment by Priyankasaggu11929** [comment]
New repo is created – https://github.com/etcd-io/etcd-operator

PR to add GitHub teams for the new repo: https://github.com/kubernetes/org/pull/5094

Working group is already documented under [SIG Etcd](https://github.com/kubernetes/community/tree/master/sig-etcd#working-groups) & [SIG Cluster Lifecycle](https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle#working-groups), so, k/community documentation is also complete.

Once PR is merged, repo creation process would be complete.

**Comment by neolit123** [comment]
> PR to add GitHub teams for the new repo: https://github.com/kubernetes/org/pull/5094

i added lgtm.

**Comment by ahrtr** [comment]
> https://github.com/etcd-io/etcd-operator

@Priyankasaggu11929 Thanks you so much for your quick response!
