### ISSUE TITLE
REQUEST: New membership for @tfogo

### ISSUE THREAD

**Issue by tfogo** [kubernetes/org#51]
### GitHub Username
@tfogo

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zparnold 
- @zacharysarah 

### List of contributions to the Kubernetes project
- PRs authored: https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=author%3Atfogo
- Some issues/PRs responded to:
https://github.com/kubernetes/website/pull/9706
https://github.com/kubernetes/website/pull/9081
https://github.com/kubernetes/website/pull/10023
https://github.com/kubernetes/website/issues/10080
https://github.com/kubernetes/website/issues/8702
https://github.com/kubernetes/website/issues/8706
- SIG projects I am involved with
Docs shadow for 1.12 release

**Comment by zparnold** [comment]
+1 From me. Tim has been an invaluable member of the Docs 1.12 release team
/lgtm

**Comment by zacharysarah** [comment]
👍 I thought he was already a long-time member, from the amount and scope of contributions he's made!

**Comment by cblecker** [comment]
Invite sent! Welcome to @kubernetes!

**Comment by tfogo** [comment]
@zparnold @zacharysarah Appreciate the kind words. Just getting started ✨
