### ISSUE TITLE
REQUEST: New membership for johnsonj

### ISSUE THREAD

**Issue by johnsonj** [kubernetes/org#510]
### GitHub Username
johnsonj

### Organization you are requesting membership in
- kubernetes
- kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timothysc 
- @krousey 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/controller-runtime/pull/241
- https://github.com/kubernetes-sigs/controller-runtime/pull/250
- https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/1
- https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/2
- https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/8
- https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/10
- https://github.com/kubernetes/org/issues/418#issuecomment-465357261
- sig-cluster-lifecycle

**Comment by krousey** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @johnsonj, I hate to be a stickler, but is there someone else that could potentially sponsor you? Both @justinsb and @krousey are employed by Google, and sponsors must be from separate member organizations per the [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

Thanks!

**Comment by johnsonj** [comment]
I'm on it Bob- thanks!

**Comment by mrbobbytables** [comment]
@johnsonj Any word on another potential sponsor?

**Comment by timothysc** [comment]
Count me on as a sponsor.  
+1 from me.

**Comment by johnsonj** [comment]
all set @mrbobbytables !

**Comment by mrbobbytables** [comment]
Awesome. Thanks for stepping in @timothysc !

**Comment by mrbobbytables** [comment]
@johnsonj, thanks for everything you've done for the project thus far :)

I've created PR #575   to add you to both the  @Kubernetes and @kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign

**Comment by johnsonj** [comment]
Thank you @mrbobbytables !!
