### ISSUE TITLE
REQUEST: New membership for @moficodes

### ISSUE THREAD

**Issue by moficodes** [kubernetes/org#5108]
### GitHub Username

@moficodes

### Organization you are requesting membership in

etcd-io

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jmhbnz

### Sponsor 2

@ivanvc

### List of contributions to the Kubernetes project

PRs
- https://github.com/etcd-io/etcd/pull/17103
- https://github.com/etcd-io/website/pull/880
- https://github.com/etcd-io/website/pull/825
- https://github.com/etcd-io/website/pull/821

Issue Triage
Help Triage new etcd issues.

**Comment by ivanvc** [comment]
+1. Thanks for your contributions to the etcd project, Mofi. Looking forward to having you join the team.

**Comment by jmhbnz** [comment]
+1 - Thanks for helping with etcd @moficodes 🙏🏻

**Comment by jasonbraganza** [comment]
/assign

@moficodes, thank you for all your contributions 🙂

I’ve created PR  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
