### ISSUE TITLE
REQUEST: New membership for javier-b-perez

### ISSUE THREAD

**Issue by javier-b-perez** [kubernetes/org#511]
### GitHub Username
@javier-b-perez

### Organization you are requesting membership in
* kubernetes
* kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @thockin
- @dims

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/community/pull/2695
- https://github.com/kubernetes/kubernetes/pull/67673
- https://github.com/kubernetes-incubator/ip-masq-agent/pull/20
- https://github.com/kubernetes/autoscaler/pull/1186

**Comment by dims** [comment]
+1 welcome!

**Comment by thockin** [comment]
+1

**Comment by mrbobbytables** [comment]
@javier-b-perez, thank you for all your contributions so far :)

I've created PR #514  to add you to both the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign
