### ISSUE TITLE
REQUEST: New membership for manishym

### ISSUE THREAD

**Issue by manishym** [kubernetes/org#5113]
### GitHub Username

@manishym

### Organization you are requesting membership in

kubernetes-csi
kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang 

### Sponsor 2

@Madhu-1

### List of contributions to the Kubernetes project

https://github.com/kubernetes/kubernetes/pull/126326
https://github.com/kubernetes-csi/external-snapshotter/pull/1034
https://github.com/kubernetes-csi/external-snapshotter/pull/1152
https://github.com/kubernetes/test-infra/pull/33417

**Comment by Madhu-1** [comment]
+1

**Comment by jasonbraganza** [comment]
@Madhu-1, I tried looking quite a bit, but I couldn’t find you listed as part of any `OWNERS` file in any of our Org repos.


[Requirements for sponsors according to our membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) are:

> - Sponsors must have close interactions with the prospective member - e.g. code/design/proposal review, coordinating on issues, etc.
> - Sponsors must be reviewers or approvers in at least one OWNERS file within one of the [Kubernetes GitHub organizations](https://github.com/kubernetes/community/blob/master/github-management#actively-used-github-organizations)*.
> - Sponsors must be from multiple member companies to demonstrate integration across community.

If you would point me towards an `OWNERS` listing, I’ll be able to go ahead and process this request; otherwise @manishym will have to go look for another sponsor.

Thank you :)

**Comment by Priyankasaggu11929** [comment]
Hello @manishym, reminder —  this request needs adding another sponsor per the `sponsor requirements` highlighted in previous comment https://github.com/kubernetes/org/issues/5113#issuecomment-2314250543. Thanks!

**Comment by manishym** [comment]
@Priyankasaggu11929 I understand. I am looking for new sponsor.

**Comment by jasonbraganza** [comment]
/close

@manishym, I’m closing this issue for now. Please do reopen this, whenever you find another sponsor.
