### ISSUE TITLE
REQUEST: New membership for @tasdikrahman

### ISSUE THREAD

**Issue by tasdikrahman** [kubernetes/org#5117]
### GitHub Username

@tasdikrahman

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [x]  I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x]  I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have verified that my sponsors are from different member companies
- [x] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] OPTIONAL: I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

Sponsor 1

@dims

Sponsor 2

@damdo 

List of contributions to the Kubernetes project

PRs authored:
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1284
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1262
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1261
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1259
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3460
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3667
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3671
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4171
- https://github.com/kubernetes-sigs/karpenter/pull/845

SIG projects I am involved in: 
- [CAPI](https://github.com/kubernetes-sigs/cluster-api)
  - [release team v1.9](https://github.com/kubernetes-sigs/cluster-api/pull/11097)
- [CAPG](https://github.com/kubernetes-sigs/cluster-api-provider-gcp)
- [CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws)

**Comment by Sunnatillo** [comment]
+1

**Comment by dims** [comment]
+1 from me. thanks @tasdikrahman

**Comment by damdo** [comment]
+1, thanks @tasdikrahman for your past and future contributions!

**Comment by palnabarun** [comment]
+1 from me as well. Thank you for your efforts!

**Comment by ydFu** [comment]
@tasdikrahman 
I want to express my heartfelt gratitude for your invaluable contributions to community endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #5123 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes family! 🎉🚀

Best regards,

/assign
