### ISSUE TITLE
REQUEST: Create kubernetes-sigs/gwctl

### ISSUE THREAD

**Issue by gauravkghildiyal** [kubernetes/org#5121]
### New repo, staging repo, or migrate existing

New repository

### Is it a staging repo?

no

### Requested name for new repository

gwctl

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

mlavacca, robscott, shaneutt, youngnick, gauravkghildiyal

### Who should have write access?

mlavacca, robscott, shaneutt, youngnick, gauravkghildiyal

### Who should be listed as approvers in OWNERS?

mlavacca, robscott, shaneutt, youngnick, gauravkghildiyal

### Who should be listed in SECURITY_CONTACTS?

mlavacca, robscott, shaneutt, youngnick, gauravkghildiyal

### What should the repo description be?

gwctl is a command-line tool for managing and understanding Gateway API resources in your Kubernetes cluster.

### What SIG and subproject does this fall under?

SIG: sig-network, SubProject: gateway-api

### Please provide references to appropriate approval for this new repo

Sent an approval request email on https://groups.google.com/g/kubernetes-sig-network/c/rMpgb1anbzY/m/jIebkeOKCgAJ

**Comment by shaneutt** [comment]
:+1: thanks @gauravkghildiyal

**Comment by robscott** [comment]
+1 thanks for all the work on this @gauravkghildiyal!

**Comment by gauravkghildiyal** [comment]
Hi @mrbobbytables -- Will would be the correct contact to help with this request?

**Comment by gauravkghildiyal** [comment]
@Priyankasaggu11929 Can you please help here, or get someone involved to move this forward?

**Comment by Priyankasaggu11929** [comment]
/assign

I'll take it.

**Comment by Priyankasaggu11929** [comment]
New repo is created – https://github.com/kubernetes-sigs/gwctl

PR to add GitHub teams for the new repo: https://github.com/kubernetes/org/pull/5147

PR to document new repo to k/community - https://github.com/kubernetes/community/pull/8073

Once PR is merged, repo creation process will be complete.

**Comment by gauravkghildiyal** [comment]
Thanks a bunch @Priyankasaggu11929!

**Comment by Priyankasaggu11929** [comment]
All PRs are merged. Repo creation is complete.

/close
