### ISSUE TITLE
REQUEST: New membership for ArvindParekh

### ISSUE THREAD

**Issue by ArvindParekh** [kubernetes/org#5127]
### GitHub Username

@ArvindParekh

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kaslin

### Sponsor 2

@chris-short

## Comms Shadow for KCSNA24

- [CFP Info and Opening](https://groups.google.com/a/kubernetes.io/g/dev/c/3K-S45n75_c/m/lrItXDYqCQAJ)
- [Call For Volunteers](https://groups.google.com/a/kubernetes.io/g/dev/c/p7IFG1zFw8g/m/NWgbdP3YAAAJ)
- [CFP + Reg reminder - July]()
- [Design Reminder August 26th](https://groups.google.com/a/kubernetes.io/g/dev/c/wHq4qFsRljs/m/-VZzFecvCQAJ)
- [Save the date + CFPs (social + slack)](https://x.com/K8sContributors/status/1804220239334228291)
+ reviewed other comms as well

## Blogging Shadow:

- Authored a spotlight-blog on SIG-Scheduling
- Converted the SIG-API Machinery interview into markdown at hackmd.io
- Reviewed other blogs

## Reviewing PRs:

- https://github.com/kubernetes/contributor-site/pull/520 (authored spotlight blog)
- https://github.com/kubernetes/community/pull/7961
- https://github.com/kubernetes/contributor-site/pull/505
- https://github.com/kubernetes/community/pull/7916
- https://github.com/kubernetes/community/pull/7913
- https://github.com/kubernetes/community/pull/7909
- https://github.com/kubernetes/contributor-site/pull/502
- https://github.com/kubernetes/community/pull/7900
- https://github.com/kubernetes/community/pull/7890
- https://github.com/kubernetes/contributor-site/pull/498
- https://github.com/kubernetes/website/pull/45326
- https://github.com/kubernetes/website/pull/45324
- https://github.com/kubernetes/website/pull/45304
- https://github.com/kubernetes/website/pull/43109

## Other contributions (Issues and PRs):

PRs Authored:
- https://github.com/kubernetes/website/pull/45324
- https://github.com/kubernetes/website/pull/43109

Issues assigned:
- https://github.com/kubernetes/website/issues/33169
- https://github.com/kubernetes/website/issues/46405
- https://github.com/kubernetes/contributor-site/issues/508

Authored spotlight blogs:
- https://github.com/kubernetes/contributor-site/pull/520

**Comment by chris-short** [comment]
Big +1 to org membership

**Comment by kaslin** [comment]
+1, Arvind is doing a great job!

**Comment by palnabarun** [comment]
+1, happy to have you onboard!

**Comment by Priyankasaggu11929** [comment]
+1. 

Thank you for all your hard work across SIG ContribEx – ContribEx comms, Events, Elections.
