### ISSUE TITLE
REQUEST: New membership for listx

### ISSUE THREAD

**Issue by listx** [kubernetes/org#513]
### GitHub Username
@listx

### Organization you are requesting membership in
kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp 
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
Author of github.com/GoogleCloudPlatform/k8s-container-image-promoter (this will eventually move to a repo in the kubernetes org --- currently waiting on Google legal team).
- Issues responded to
- SIG projects I am involved with
SIG Release
Not a SIG per se, but [K8s Infra Working Group](https://github.com/kubernetes/community/tree/master/wg-k8s-infra)

**Comment by BenTheElder** [comment]
+1 from me :-)

**Comment by dims** [comment]
+1 from me!

**Comment by mrbobbytables** [comment]
Ben's +1 will do ;) 

@listx I've created PR #514 to add you to the @kubernetes org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! :tada:

/assign
/pony party

**Comment by justaugustus** [comment]
Woooooooooo
