### ISSUE TITLE
REQUEST: New membership for adrianmoisey

### ISSUE THREAD

**Issue by adrianmoisey** [kubernetes/org#5133]
### GitHub Username

@adrianmoisey

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@aojea

### Sponsor 2

@danwinship

### List of contributions to the Kubernetes project

PRs authored:
- https://github.com/kubernetes/autoscaler/pull/7185
- https://github.com/kubernetes/autoscaler/pull/7153
- https://github.com/kubernetes/autoscaler/pull/6910
- https://github.com/kubernetes/autoscaler/pull/6788
- https://github.com/kubernetes/kubernetes/pull/127167
- https://github.com/kubernetes/enhancements/pull/4755

Issues triaged:
- https://github.com/kubernetes/kubernetes/issues/125883
- https://github.com/kubernetes/kubernetes/issues/124290
- https://github.com/kubernetes/kubernetes/issues/124207
- https://github.com/kubernetes/kubernetes/issues/120585
- https://github.com/kubernetes/kubernetes/issues/62334
- https://github.com/kubernetes/autoscaler/issues/7180
- https://github.com/kubernetes/autoscaler/issues/6965
- https://github.com/kubernetes/autoscaler/issues/6946
- https://github.com/kubernetes/autoscaler/issues/6232

PRs reviewed:
- https://github.com/kubernetes/kubernetes/pull/126889
- https://github.com/kubernetes/kubernetes/pull/126847
- https://github.com/kubernetes/kubernetes/pull/125486
- https://github.com/kubernetes/kubernetes/pull/124758
- https://github.com/kubernetes/autoscaler/pull/6909
- https://github.com/kubernetes/autoscaler/pull/7010

**Comment by aojea** [comment]
+1

Looking forward to more contributions

**Comment by danwinship** [comment]
+1 "wait he's not a member already?"

**Comment by bridgetkromhout** [comment]
+1 Super exciting! I am glad to see Adrian taking this (very natural) next step! Welcome!

**Comment by jasonbraganza** [comment]
/assign

@adrianmoisey, thank you for all you do! 🙂

I’ve created PR #5135 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
