### ISSUE TITLE
REQUEST: New membership for sandeepkanabar

### ISSUE THREAD

**Issue by sandeepkanabar** [kubernetes/org#5140]
### GitHub Username

@sandeepkanabar

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kaslin

### Sponsor 2

@chris-short

## Comms Shadow for KCSNA24

- Awards Nominations Reminder to Leads
- [CFP + Reg + Volunteer Reminder, August](https://groups.google.com/a/kubernetes.io/g/dev/c/IUnKwQnCPpY/m/0qBz3JCsCQAJ)
- [Design Reminder](https://groups.google.com/a/kubernetes.io/g/dev/c/wHq4qFsRljs/m/nP-CzzDtCgAJ)
- [Pen-ultimate DesignReminder](https://groups.google.com/a/kubernetes.io/g/dev/c/wqHiAqmGZDg/m/AwzhXE9RAAAJ)
- [Extending Due Date for Designs](https://groups.google.com/a/kubernetes.io/g/dev/c/E49gyfrrtWc/m/ELydj6s-AQAJ)
- [Final Design Reminder](https://groups.google.com/a/kubernetes.io/g/dev/c/wqHiAqmGZDg/m/Si8AF1gbEAAJ)
- As a shadow, helped in reviewing the comms created by other shadows

## Blogging Spotlight:
- Work-in-progress - a blog spotlight for the CNCF Deaf and hard-of-hearing Working Group

## Issues and PRs:
- https://github.com/kubernetes/sig-release/pull/2422
- https://github.com/cncf/tag-contributor-strategy/pull/570
- https://github.com/cncf/tag-contributor-strategy/pull/605
- https://github.com/cncf/tag-contributor-strategy/pull/659
- https://github.com/cncf/tag-contributor-strategy/pull/660
- https://github.com/kubernetes/website/pull/46915

## Reviewing PRs:
- https://github.com/kubernetes/community/pull/7961
- https://github.com/cncf/tag-contributor-strategy/pull/663
- https://github.com/kubernetes/contributor-site/pull/498#pullrequestreview-2056948954
- https://github.com/kubernetes/contributor-site/pull/496#pullrequestreview-2038119620

**Comment by MadhavJivrajani** [comment]
Huge +1! 
Sandeep has been exceptionally consistent and proactive, I love seeing him in the contribex calls, and I can't wait to see all the wonderful things he does in the community 🎉 

/woof

**Comment by kaslin** [comment]
Mega +1! Thank you for all the work you've been doing to support Comms, the New Contributor Orientation initiative, and the Contributor Summit!

**Comment by mfahlandt** [comment]
Huge +1 - Since he got involved Sandeep has been a tremendous help for the Project especially in Comms and ContribEx itself.

**Comment by Priyankasaggu11929** [comment]
+1. :)

Thank you for educating us at the kubernetes community about accessibility improvements in the project.

**Comment by chris-short** [comment]
Big +1 from me. The work Sandeep is doing on the Comms team, the CNCF Deaf & Hard of Hearing Working Group, and beyond are an asset to the community.

**Comment by sandeepkanabar** [comment]
Thank you everyone. This humbles me and encourages me to do my best in contributing to the betterment of open source and driving including in the community!

**Comment by dims** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@sandeepkanabar, thank you for all you do 🙂

I’ve created PR #5144 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
