### ISSUE TITLE
REQUEST: New membership for mtulio

### ISSUE THREAD

**Issue by mtulio** [kubernetes/org#5149]
### GitHub Username

mtulio

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

elmiko

### Sponsor 2

vincepri

### List of contributions to the Kubernetes project

Mostly contributions in [Cluster API Provider AWS(kubernetes-sigs/cluster-api-provider-aws)][capa], including:
- Feature development
- Documentation
- Bug fixes
- PR reviews

[Here][capa-pr] is the list of Pull Requests contributed to the CAPA project.

[capa]: https://github.com/kubernetes-sigs/cluster-api-provider-aws
[capa-pr]:  https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3Amtulio

**Comment by mtulio** [comment]
cc @elmiko @vincepri

**Comment by elmiko** [comment]
+1, Marco has a good understanding of Cluster API, has made contributions to that community, and is helping with the karpenter-provider-cluster-api project.

**Comment by jasonbraganza** [comment]
@vincepri, a +1 once you review this request, will help me expedite it.
Thank you :)

**Comment by jasonbraganza** [comment]
@vincepri please help :)

**Comment by vincepri** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@mtulio, thank you for all your contributions 🙂

I’ve created PR #5176  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
