### ISSUE TITLE
REQUEST: New membership for pjh

### ISSUE THREAD

**Issue by pjh** [kubernetes/org#515]
### GitHub Username
@pjh

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yujuhong 
- @PatrickLang 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/73442 is the most substantial, then I've sent several follow-ups. https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Apjh+

- SIG projects I am involved with
I've been attending SIG-Windows meetings for a couple years and have done some reviews, a little documentation, and have helped find + troubleshoot Windows networking problems.

**Comment by yujuhong** [comment]
+1

**Comment by PatrickLang** [comment]
+1, Peter's been a big help in getting things validated on GCE to prove it works in multiple clouds :)

**Comment by mrbobbytables** [comment]
@pjh, thank you for all the work you've put in for the project so far :)

I've created PR #524  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
