### ISSUE TITLE
REQUEST: New membership for @michellengnx

### ISSUE THREAD

**Issue by michellengnx** [kubernetes/org#5154]
### GitHub Username

michellengnx

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-csi, kubernetes-sigs, etcd-io

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@chanieljdan

### Sponsor 2

@fsmunoz

### List of contributions to the Kubernetes project

- SIG Release team 1.32 cycle

**Comment by chanieljdan** [comment]
+1

Thanks @michellengnx! Welcome to the K8s org! 🙌

**Comment by jasonbraganza** [comment]
@michellengnx, request you to change your sponsor nick to the right one (@chanieljdan instead of chanieldan) in the issue description

@katcosgrove a +1 once you review will help me expedite this.

@chanieljdan, request to to please update you work org, either on your profile on here on this issue, because [our membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require sponsors be from different orgs.

Thank you all :)

**Comment by chanieljdan** [comment]
@jasonbraganza thanks for the heads up! I updated my work org on my profile, let me know if we're good to go.

In case we're not @fsmunoz can also act as a sponsor, just let me know.

**Comment by fsmunoz** [comment]
+1 from me (if needed).

**Comment by jasonbraganza** [comment]
@michellengnx since @fsmunoz has also given a +1 along with @chanieljdan, i am almost good to go. request to to change the issue to reflect  @fsmunoz as sponsor instead of Kat Cosgrove and i’ll procees it asap

**Comment by jasonbraganza** [comment]
/assign

@michellengnx, looking forward to all your contributions 🙂

For now, I’ve created PR #5174 to add you to the Kubernetes & Kubernetes Sigs Org. Once that gets merged, you should get a membership invite notification.

I suggest you raise issues for the other sigs on a need based basis later, with the support of OWNERS in the sigs that you are interested in at the time.

Welcome to https://github.com/kubernetes! 🎉
