### ISSUE TITLE
REQUEST: New membership for abursavich

### ISSUE THREAD

**Issue by abursavich** [kubernetes/org#5155]
### GitHub Username

@abursavich

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mloiseleur

### Sponsor 2

@raffo

### List of contributions to the Kubernetes project

ExternalDNS PRs authored:
- https://github.com/kubernetes-sigs/external-dns/pull/2188
- https://github.com/kubernetes-sigs/external-dns/pull/2190
- https://github.com/kubernetes-sigs/external-dns/pull/2292
- https://github.com/kubernetes-sigs/external-dns/pull/2881
- https://github.com/kubernetes-sigs/external-dns/pull/3268
- https://github.com/kubernetes-sigs/external-dns/pull/3271
- https://github.com/kubernetes-sigs/external-dns/pull/4124
- https://github.com/kubernetes-sigs/external-dns/pull/4610

**Comment by mloiseleur** [comment]
I support this member ship :+1: 
/lgtm
/approve

**Comment by Raffo** [comment]
I support this 👍

**Comment by jasonbraganza** [comment]
/assign

@abursavich, thank you for all your contributions 🙂

I’ve created PR #5164 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
