### ISSUE TITLE
REQUEST: New membership for edithturn

### ISSUE THREAD

**Issue by edithturn** [kubernetes/org#5158]
### GitHub Username

@edithturn

### Organization you are requesting membership in

kubernetes; kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

mbianchidev

### Sponsor 2

katcosgrove

### List of contributions to the Kubernetes project

I'm excited to contribute as a Shadows Comms Release member! The SIGs I'll be contributing to include SIG Release, SIG Docs, and SIG Docs Blogs. I've already been involved in these areas and can't wait to continue contributing! 🙂

**Comment by mbianchidev** [comment]
This issue can be closed since @edithturn is already part of the Kubernetes org since last cycle 👀

**Comment by edithturn** [comment]
Thanks @mbianchidev  I will close it! 🙂
