### ISSUE TITLE
REQUEST: New membership for mattjmcnaughton

### ISSUE THREAD

**Issue by mattjmcnaughton** [kubernetes/org#516]
### GitHub Username
@mattjmcnaughton

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@BenTheElder (Google)
@DirectXMan12 (Google)
@smarterclayton (Red Hat)

thanks again :)

### List of contributions to the Kubernetes project
My [pull requests](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aclosed+author%3Amattjmcnaughton). I've predominately focused on autoscaling and developer tools.

**Comment by BenTheElder** [comment]
+1

**Comment by DirectXMan12** [comment]
Definitely :+1: from me

**Comment by mrbobbytables** [comment]
Hey there @mattjmcnaughton, I don't mean to delay things, but is there someone else that could potentially sponsor you? Both @BenTheElder  and @DirectXMan12  are employed by Google, and sponsors must be from separate member organizations per the [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

Thanks!

**Comment by mattjmcnaughton** [comment]
hi @mrbobbytables, thanks for the heads up! Oh interesting - I actually wasn't aware they were both Googlers :)

@DirectXMan12 any chance you know if any of the HPA contributors are non-googlers?

**Comment by smarterclayton** [comment]
+1

**Comment by mattjmcnaughton** [comment]
@mrbobbytables just pining you because @smarterclayton is employed at RedHat. So I've got a +1 from employees at Google and Red Hat, which I think meets the requirements.

Thanks so much :)

**Comment by mrbobbytables** [comment]
Yup!
Thanks for adding your +1 @smarterclayton :) 

@mattjmcnaughton Can get your org membership processed today. 🎉

**Comment by mattjmcnaughton** [comment]
Woohoo, what a great start to my Thursday :)

Thank you @mrbobbytables and thank you to @smarterclayton , @DirectXMan12 , and @BenTheElder !

**Comment by mrbobbytables** [comment]
@mattjmcnaughton, thanks for everything you've contributed to the project thus far :)

I've created PR #582   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

/pony party
