### ISSUE TITLE
REQUEST: New membership for xcarolan

### ISSUE THREAD

**Issue by xcarolan** [kubernetes/org#5168]
### GitHub Username

xcarolan

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [x] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Priyankasaggu11929 

### Sponsor 2

@jberkus

### List of contributions to the Kubernetes project

https://github.com/search?q=repo%3Akubernetes%2Fminikube+commenter%3Axcarolan+is%3Apr+org%3Akubernetes+org%3Akubernetes-sigs+org%3Akubernetes-client+&type=pullrequests

Minikube Working Group
• Feature enhancements and bug fixes for Minikube (Kubernetes sub-project)
• Minkube conformance testing.
• Git HUB CI/CD automation.
• Bash builds and deploy script enhancements.
• CNI testing for Calico, Kind, and Cilium plugins.
• Docker, Podman, Contained, and CRI-O container/driver testing
• Issue Triage

Special Interest Group (SIG) Contributor Experience
• Co-lead Kubernetes Mentoring Program
• Community Communications contributions
• Weekly community meetings
• Kubernetes Group Mentoring

**GitHub Contribution Events**
PushEvent xcarolan/autodidact.engineer 2024-09-18T00:17:58Z
PushEvent xcarolan/minikube 2024-09-17T15:43:25Z
PushEvent xcarolan/lwkd 2024-09-17T13:52:37Z
PullRequestEvent cncf/gitdm 2024-09-17T00:57:13Z
PushEvent xcarolan/gitdm 2024-09-17T00:56:39Z
PushEvent xcarolan/gitdm 2024-09-17T00:51:47Z
PullRequestEvent cncf/gitdm 2024-09-17T00:47:05Z
PushEvent xcarolan/gitdm 2024-09-17T00:43:52Z
PullRequestEvent cncf/gitdm 2024-09-17T00:37:22Z
PushEvent xcarolan/gitdm 2024-09-17T00:36:28Z
PullRequestEvent kubernetes-sigs/lwkd 2024-09-10T18:51:26Z
PushEvent xcarolan/lwkd 2024-09-10T18:50:29Z
PushEvent xcarolan/minikube 2024-09-09T20:07:28Z
PushEvent xcarolan/minikube 2024-09-09T20:07:15Z
PullRequestEvent kubernetes/minikube 2024-09-08T18:20:54Z
PushEvent xcarolan/minikube 2024-09-08T18:17:24Z
PushEvent xcarolan/minikube 2024-09-07T13:49:57Z
IssueCommentEvent kubernetes/minikube 2024-09-06T17:54:32Z
PushEvent xcarolan/autodidact.engineer 2024-09-02T16:17:39Z
IssueCommentEvent kubernetes/minikube 2024-09-02T00:33:54Z
PushEvent xcarolan/autodidact.engineer 2024-08-31T19:37:20Z
PushEvent xcarolan/autodidact.engineer 2024-08-31T18:41:30Z
PushEvent xcarolan/minikube 2024-08-30T15:55:45Z
PushEvent xcarolan/contributor-site 2024-08-30T14:39:55Z
PushEvent xcarolan/community 2024-08-30T12:41:35Z
PushEvent xcarolan/contributor-site 2024-08-29T22:48:36Z
PushEvent xcarolan/contributor-site 2024-08-29T22:38:34Z
PushEvent xcarolan/contributor-site 2024-08-29T21:54:00Z
PushEvent xcarolan/contributor-site 2024-08-29T21:52:28Z
PushEvent xcarolan/community 2024-08-29T21:47:23Z
PushEvent xcarolan/community 2024-08-29T21:46:25Z
PullRequestEvent xcarolan/community 2024-08-29T21:46:24Z
PushEvent xcarolan/community 2024-08-29T21:42:11Z
PullRequestEvent xcarolan/community 2024-08-29T21:39:06Z
PushEvent xcarolan/community 2024-08-29T21:31:14Z
PushEvent xcarolan/community 2024-08-29T21:29:20Z
PushEvent xcarolan/community 2024-08-29T20:45:33Z
IssueCommentEvent kubernetes/minikube 2024-08-29T19:33:41Z
IssueCommentEvent kubernetes/minikube 2024-08-29T19:29:06Z
PushEvent xcarolan/minikube 2024-08-29T19:00:23Z
IssueCommentEvent kubernetes/minikube 2024-08-29T13:11:25Z
IssueCommentEvent kubernetes/minikube 2024-08-28T23:57:11Z
IssueCommentEvent kubernetes/minikube 2024-08-28T18:20:19Z
PushEvent xcarolan/minikube 2024-08-21T23:40:03Z
IssueCommentEvent kubernetes/minikube 2024-08-21T18:19:08Z
IssueCommentEvent kubernetes/community 2024-08-20T18:06:14Z
PushEvent xcarolan/community 2024-08-18T22:23:51Z
PullRequestEvent kubernetes/community 2024-08-18T22:02:15Z
PullRequestEvent xcarolan/community 2024-08-18T21:59:00Z
PushEvent xcarolan/community 2024-08-18T21:59:00Z
PushEvent xcarolan/community 2024-08-18T21:58:46Z
PullRequestEvent xcarolan/community 2024-08-18T21:55:29Z
PushEvent xcarolan/community 2024-08-18T21:43:28Z
PullRequestEvent xcarolan/community 2024-08-18T21:43:27Z
PullRequestEvent xcarolan/community 2024-08-18T21:43:05Z
IssueCommentEvent kubernetes/community 2024-08-18T21:42:44Z
PullRequestEvent kubernetes/community 2024-08-18T21:42:32Z
PullRequestEvent kubernetes/community 2024-08-18T21:42:15Z
PushEvent xcarolan/community 2024-08-18T21:40:56Z
PushEvent xcarolan/community 2024-08-18T19:26:38Z
PullRequestEvent xcarolan/community 2024-08-18T19:26:37Z
PullRequestEvent xcarolan/community 2024-08-18T19:26:18Z
PullRequestEvent xcarolan/community 2024-08-18T19:24:23Z
PullRequestEvent xcarolan/community 2024-08-18T19:24:14Z
PushEvent xcarolan/community 2024-08-18T19:22:29Z
PushEvent xcarolan/community 2024-08-18T17:53:13Z
IssueCommentEvent kubernetes/community 2024-08-18T16:47:32Z
IssuesEvent kubernetes/community 2024-08-18T16:47:18Z
PushEvent xcarolan/community 2024-08-18T13:58:51Z
PullRequestEvent kubernetes/minikube 2024-08-16T12:00:11Z
PushEvent xcarolan/minikube 2024-08-16T11:58:30Z
IssueCommentEvent kubernetes/minikube 2024-08-16T01:06:14Z
PullRequestEvent kubernetes/minikube 2024-08-15T22:58:06Z
PushEvent xcarolan/minikube 2024-08-15T22:54:44Z
PushEvent xcarolan/community 2024-08-13T23:49:56Z
PullRequestEvent xcarolan/minikube 2024-08-12T00:15:06Z
PushEvent xcarolan/minikube 2024-08-12T00:15:05Z
IssueCommentEvent kubernetes/minikube 2024-08-12T00:13:15Z
PullRequestEvent kubernetes/minikube 2024-08-12T00:12:55Z
PullRequestEvent kubernetes/minikube 2024-08-12T00:06:29Z
PullRequestEvent xcarolan/minikube 2024-08-12T00:05:20Z
PushEvent xcarolan/minikube 2024-08-12T00:03:21Z
PushEvent xcarolan/minikube 2024-08-12T00:02:35Z
PushEvent xcarolan/minikube 2024-08-11T23:41:27Z
IssueCommentEvent kubernetes/community 2024-08-11T15:29:45Z
IssuesEvent kubernetes/community 2024-08-11T15:29:18Z
IssuesEvent kubernetes/community 2024-08-11T15:22:53Z
IssueCommentEvent kubernetes/community 2024-08-11T15:17:44Z
IssuesEvent kubernetes/community 2024-08-11T15:16:36Z
IssueCommentEvent kubernetes/minikube 2024-08-10T17:44:49Z
IssueCommentEvent kubernetes/minikube 2024-08-10T12:56:52Z
PushEvent xcarolan/minikube 2024-08-07T00:19:29Z
PushEvent xcarolan/minikube 2024-08-05T16:07:25Z
PushEvent xcarolan/minikube 2024-08-05T16:07:15Z
IssueCommentEvent kubernetes/minikube 2024-07-30T14:36:39Z
PushEvent xcarolan/setup-minikube 2024-07-21T20:31:25Z
PushEvent xcarolan/setup-minikube 2024-07-21T18:07:22Z
PushEvent xcarolan/setup-minikube 2024-07-21T18:06:23Z
PushEvent xcarolan/setup-minikube 2024-07-21T18:04:57Z
PushEvent xcarolan/setup-minikube 2024-07-21T18:03:55Z
PushEvent xcarolan/minikube 2024-07-20T20:19:56Z
IssueCommentEvent kubernetes/minikube 2024-07-20T16:18:27Z
IssueCommentEvent kubernetes/minikube 2024-07-20T16:16:45Z
IssueCommentEvent kubernetes/minikube 2024-07-15T21:07:24Z
IssueCommentEvent kubernetes/minikube 2024-07-14T22:28:42Z
PushEvent xcarolan/minikube 2024-07-13T18:56:00Z
PushEvent xcarolan/minikube 2024-07-12T00:34:14Z
PushEvent xcarolan/minikube 2024-07-02T23:51:09Z

**Comment by Priyankasaggu11929** [comment]
+1. Thank you for all your contributions @xcarolan :slightly_smiling_face: 


@xcarolan – could you please link the GH handle in the issue description. I missed the notification for this request and I believe same's the case for @jberkus as well. Thanks!

**Comment by xcarolan** [comment]
> +1. Thank you for all your contributions @xcarolan 🙂
> 
> @xcarolan – could you please link the GH handle in the issue description. I missed the notification for this request and I believe same's the case for @jberkus as well. Thanks!

fixed thanks!

**Comment by jasonbraganza** [comment]
@jberkus, ping :) a +1 on the issue will help  me process this request. Thank you!

**Comment by jasonbraganza** [comment]
/assign

@xcarolan, thank you for all your contributions 🙂

I’ve created PR #5188 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by xcarolan** [comment]
Thank you all for your support!
