### ISSUE TITLE
REQUEST: New membership for hairyhum

### ISSUE THREAD

**Issue by hairyhum** [kubernetes/org#5171]
### GitHub Username

@hairyhum

### Organization you are requesting membership in

kubernetes-csi

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@carlbraganza

### List of contributions to the Kubernetes project

- sig-storage project: https://github.com/kubernetes-csi/external-snapshot-metadata
  - https://github.com/kubernetes-csi/external-snapshot-metadata/pull/6
  - https://github.com/kubernetes/test-infra/pull/33303

**Comment by jasonbraganza** [comment]
@xing-yang, @carlbraganza: your +1 on the issue will help me process this. Thank you :)

@carlbraganza, would you also kindly update your work org, on you profile or mention it here on the issue? Our [membership guidelines for sponsors](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require that they be from different orgs

**Comment by xing-yang** [comment]
+1

**Comment by jasonbraganza** [comment]
@carlbraganza, ping, please help :)

**Comment by jasonbraganza** [comment]
@carlbraganza, ping! would you kindly help? :)

**Comment by carlbraganza** [comment]
@jasonbraganza Sorry, just got back from vacation!  Yes, Daniil is working with me on the `kubernetes-csi/external-snapshot-metadata` project.

+1

**Comment by jasonbraganza** [comment]
/assign

@hairyhum, thank you for all your contributions 🙂

I’ve created PR #5207 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
