### ISSUE TITLE
REQUEST: New membership for EandrewJones

### ISSUE THREAD

**Issue by EandrewJones** [kubernetes/org#5172]
### GitHub Username

@EandrewJones

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@shaneutt

### Sponsor 2

@aryan9600 

### List of contributions to the Kubernetes project

Kubernetes SIG / Blixt
---
I've been a community member since early 2024 and have slowly scaled up my engagement. In addition to contributing to PRs / issues, I've helped the core maintainers help community meetings lately while they have limited bandwidth.

### PRs / Issues
-  mTLS for Dataplane - [issue](https://github.com/kubernetes-sigs/blixt/issues/50) / [pr](https://github.com/kubernetes-sigs/blixt/pull/280)
- Convert Repo to Rust Workspace - [issue](https://github.com/kubernetes-sigs/blixt/issues/218) / [pr](https://github.com/kubernetes-sigs/blixt/pull/227)
- Add Cargo to CI for all Rust Code - [issue](https://github.com/kubernetes-sigs/blixt/issues/212) / [pr](https://github.com/kubernetes-sigs/blixt/pull/217)
- Port UDPRoute and TCPRoute Reconciler to rust - no issue created yet

Kubernetes Serving Working Group
---
I've been actively participating in the Serving WG since the Spring, regularly attending meetings, contributing to discussion both on zoom as well as during proposal development. In particular, I've focused my attention on the Orchestration and Autoscaling work streams. Below are a few examples of proposals I've helped with:
- [Benchmarking Workloads for Performance Evaluation and Autoscaling in Kubernetes](https://docs.google.com/document/d/1k4Q4X14hW4vftElIuYGDu5KDe2LtV1XammoG-Xi3bbQ/edit)
- [Blueprint Is All You Need](https://docs.google.com/document/d/1tNWnDAhLj9lsTg5dOIBbe7olPH0-4efe2uN-FZIc_KU/edit#heading=h.5g4h6ryc7d6k)
- [Autoscaling Workload Examples](https://docs.google.com/document/d/1IFsCwWtIGMujaZZqEMR4ZYeZBi7Hb1ptfImCa1fFf1A/edit?resourcekey=0-8lD1pc_wDVxiwyI8SIhBCw#heading=h.msa1v1j90u)
- [Model Server Metrics Research](https://github.com/huggingface/text-generation-inference/issues/1977)
- [Weekly Meeting Notes](https://docs.google.com/document/d/1aExJFtaLnO-TM6_2uILgI8NI0IjOm7FcwLABBKEMEo0/edit?pli=1)

**Comment by jasonbraganza** [comment]
@shaneutt, @aryan9600, your +1 (after review) will help me process this membership. Thank you :)

**Comment by shaneutt** [comment]
+1 for @EandrewJones!

**Comment by jasonbraganza** [comment]
@aryan9600, ping. please help :)

**Comment by aryan9600** [comment]
oops, sorry! +1 for @EandrewJones from me as well :)

**Comment by jasonbraganza** [comment]
/assign

@EandrewJones, thank you for all your contributions 🙂

I’ve created PR #5197 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
