### ISSUE TITLE
REQUEST: New membership for ElijahQuinones

### ISSUE THREAD

**Issue by ElijahQuinones** [kubernetes/org#5177]
### GitHub Username

ElijahQuinones

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@torredil

### Sponsor 2

@jsafrane

### List of contributions to the Kubernetes project

PRs Authored 

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2144
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2142
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2130
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2116
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2115
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2108
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2097
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2094
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2089
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2078
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2060

PRs reviewed 

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2157
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2150
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2149
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2148
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2135

Issues 

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2105
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2087
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1955

Sig projects i'm involved in

https://github.com/kubernetes-sigs/aws-ebs-csi-driver

**Comment by torredil** [comment]
+1

**Comment by jasonbraganza** [comment]
@jsafrane ping. your +1 after review will help me process this request. Thank you :)

**Comment by jasonbraganza** [comment]
/assign

@ElijahQuinones, thank you for all your contributions 🙂

I’ve created PR #5197  to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
