### ISSUE TITLE
REQUEST: New integration for kubernetes

### ISSUE THREAD

**Issue by upodroid** [kubernetes/org#5178]
### Organization or Repo

kubernetes

### Name of integration

OAuth2 Proxy

### Link to integration website

https://oauth2-proxy.k8s.io

### Describe what is attempting to be accomplished

I need to restrict certain apps in our GKE clusters to kubernetes github org members and this program allows us to do that.

https://oauth2-proxy.github.io/oauth2-proxy/

### Additional context for request

Can I have an oauth app created in the kubernetes org with the following configuration:
-  Logo: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/static/img/logos/OAuth2_Proxy_icon.png
- Name: OAuth2 Proxy
- Callback url: https://oauth2-proxy.k8s.io/oauth2/callback
- Homepage: https://oauth2-proxy.k8s.io

**Comment by cblecker** [comment]
@upodroid A couple questions:
- Does this oauth app need the "device flow" enabled? (ref: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#device-flow)
- The URL https://oauth2-proxy.k8s.io/ returns an error. Is that expected, or is there possibly a typo in the desired URL?

**Comment by cblecker** [comment]
Created https://github.com/organizations/kubernetes/settings/applications/2718717 and placed details in 1password.

Pending answers to above questions, and then this can be closed.

**Comment by upodroid** [comment]
> * Does this oauth app need the "device flow" enabled? (ref: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#device-flow)

No
> * The URL https://oauth2-proxy.k8s.io/ returns an error. Is that expected, or is there possibly a typo in the desired URL?

I'm currently running it with a temporary oauth token for testing. This will be fixed once I configure the final tokens

**Comment by cblecker** [comment]
Thanks @upodroid !
