### ISSUE TITLE
REQUEST: New membership for srivastav-abhishek

### ISSUE THREAD

**Issue by srivastav-abhishek** [kubernetes/org#5180]
### GitHub Username

srivastav-abhishek

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mkumatag

### Sponsor 2

@liggitt

### List of contributions to the Kubernetes project

-PRs authored:

-  https://github.com/kubernetes/kubernetes/pull/127422
-  https://github.com/kubernetes/kubernetes/pull/125049
- https://github.com/kubernetes/kubernetes/pull/124004
- https://github.com/kubernetes/kubernetes/pull/123257
- https://github.com/kubernetes/kubernetes/pull/121565
- https://github.com/kubernetes/kubernetes/pull/120599

Issues responded to:

- https://github.com/kubernetes/kubernetes/issues/123991
- https://github.com/kubernetes/kubernetes/issues/123256
- https://github.com/kubernetes/kubernetes/issues/121710
- https://github.com/kubernetes/kubernetes/issues/121564
- https://github.com/kubernetes/kubernetes/issues/125353

SIG projects I am involved with:
- https://github.com/kubernetes/kubernetes

**Comment by jasonbraganza** [comment]
/assign

@srivastav-abhishek, thank you for all your contributions 🙂

I’ve created PR #5184 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by srivastav-abhishek** [comment]
Thank you @mkumatag @liggitt @jasonbraganza 🙂
