### ISSUE TITLE
REQUEST: New membership for @arujjval

### ISSUE THREAD

**Issue by arujjval** [kubernetes/org#5187]
### GitHub Username

@arujjval

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@kaslin

### Sponsor 2

@fsmunoz

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/contributor-site/pull/477 (written Blog)
- https://github.com/kubernetes/website/pull/44817 (PR merged)
- https://github.com/kubernetes/website/pull/46866 (PR merged)
- https://github.com/kubernetes/website/pull/44193 (PR merged)

- https://github.com/kubernetes/contributor-site/pull/534  (PR created, yet to review)
- https://github.com/kubernetes/contributor-site/issues/518 (Blog assigned)

- https://github.com/kubernetes/website/issues/45597 (Issue created and closed)
- https://github.com/kubernetes/website/issues/46864 (Issue created and closed)

**Comment by fsmunoz** [comment]
+1 from me.

**Comment by jasonbraganza** [comment]
@kaslin, ping. a +1 on this issue (after review) will help me process this. Thank you :)

**Comment by kaslin** [comment]
Sorry for the delay! +1, Arujwal has been doing great work with the comms team!

**Comment by jasonbraganza** [comment]
/assign

@arujjval, thank you for all your contributions 🙂

I’ve created PR #5197 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
