### ISSUE TITLE
Requesting owner permissions for https://github.com/kubernetes-csi/* repos

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/org#519]
### Organization or repository

* https://github.com/kubernetes-csi/csi-release-tools
* https://github.com/kubernetes-csi/kubernetes-csi.github.io

### Users effected
saad-ali

### Describe the issue
Need to be owner of these CSI repo in order to cut releases, etc.

This is a follow up on https://github.com/kubernetes/org/issues/141

I already have ownership of all other https://github.com/kubernetes-csi/* except for the two listed above.

**Comment by nikhita** [comment]
`kubernetes-csi/csi-release-tools-admins` and `kubernetes-csi/csi-release-tools-maintainers` teams existed already but didn't have access to the csi-release-tools repo. I have assigned appropriate access to both teams.

@saad-ali You are in both teams, so you should now have admin access to csi-release-tools.

I have created a PR to add a new admin team for kubernetes-csi.github.io: https://github.com/kubernetes/org/pull/521. Once it gets merged, the postsubmit runs and the new GitHub teams are created, I'll give the team admin access. :)

**Comment by saad-ali** [comment]
Thank you very much @nikhita

**Comment by nikhita** [comment]
@saad-ali You should now have admin access for both repos. :)

/close
