### ISSUE TITLE
REQUEST: New membership for thisisharrsh

### ISSUE THREAD

**Issue by thisisharrsh** [kubernetes/org#5192]
### GitHub Username

@thisisharrsh

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mitul3737

### Sponsor 2

@pacoxu 

### List of contributions to the Kubernetes project

- PR Reviewed/Authored:
https://github.com/search?q=is%3Apr+author%3Athisisharrsh+org%3Akubernetes+org%3Akubernetes-sigs&type=pullrequests

- Issues responded to:
https://github.com/search?o=desc&q=commenter%3Athisisharrsh+org%3Akubernetes+org%3Akubernetes-sigs&s=created&type=issues

- SIG projects I am involved with:
sig-docs

**Comment by mitul3737** [comment]
+1

**Comment by jasonbraganza** [comment]
@mengjiao-liu ping. a +1 (after your review) on this issue will help me process this. thank you :)

**Comment by pacoxu** [comment]
+1

**Comment by jasonbraganza** [comment]
@thisisharrsh, considering @pacoxu’s endorsement, you could change your sponsors to reflect his name and then I can go ahead and process this request

**Comment by thisisharrsh** [comment]
> you could change your sponsors to reflect his name and then I can go ahead and process this request

Hi @jasonbraganza, i have changed the sponsor name.

**Comment by jasonbraganza** [comment]
/assign

@thisisharrsh, thank you for all your contributions 🙂

I’ve created PR #5206 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
