### ISSUE TITLE
REQUEST: Archive repo https://github.com/kubernetes-sigs/cluster-api-provider-nested

### ISSUE THREAD

**Issue by neolit123** [kubernetes/org#5194]
### Repository to archive

kubernetes-sigs/cluster-api-provider-nested

### Repository and/or sig subproject owners that are approving this archival

@vincepri @fabriziopandini @justinsb @neolit123

### When should this be done

anytime

### Additional context for request

the project tempo has slowed down and we decided to archive this repo and decommission the subproject of SIG CL
- https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/360

**Comment by fabriziopandini** [comment]
+1
Thanks for opening this issue!

**Comment by Priyankasaggu11929** [comment]
All PRs are merged.

Repo is transferred to `kubernetes-retired` and archived – https://github.com/kubernetes-sigs/cluster-api-provider-nested

This is complete.

/close
