### ISSUE TITLE
Create kubernetes/security Github repo

### ISSUE THREAD

**Issue by philips** [kubernetes/org#520]
### New Repo, Staging Repo, or migrate existing

New Repo

### Requested name for new repository

security

### Which Organization should it reside

kubernetes

### If not a staging repo, who should have admin access

* Brandon Philips (@philips)
* Jess Frazelle (@jessfraz)
* CJ Cullen (@cjcullen) 
* Tim Allclair (@tallclair)
* Jordan Liggitt (@liggitt)

### If not a staging repo, who should have write access

all admins

### If a new repo, who should be listed as approvers in OWNERS

all admins

### If a new repo, who should be listed in SECURITY_CONTACTS

all admins

### What should the repo description be

Kubernetes Security Process and Security Committee docs

### What SIG and subproject does this fall under in sigs.yaml

This is part of the formation of the Kubernetes Product Security Committee which was approved by the Steering committee here https://github.com/kubernetes/steering/issues/89

### Approvals

Steering Committee approval for a new committee https://github.com/kubernetes/steering/issues/89

### Additional context for request

The Product Security Committee will be moving docs from SIG Release to this repo: https://github.com/kubernetes/sig-release/tree/master/security-release-process-documentation

**Comment by tallclair** [comment]
As an aside, we should make sure the security repo issue template declares VERY LOUDLY that it is not a place to file security issues.

**Comment by philips** [comment]
We could also just disable issues on the repo @tallclair.

**Comment by micahhausler** [comment]
Do you think issues could be useful for process questions/suggestions? Or should any suggestion just be made with a PR?

**Comment by tallclair** [comment]
Yeah, I feel like it could be useful for discussing the process (we could even use it for distributors applications). If it becomes a problem, we could disable it later.

**Comment by philips** [comment]
We have a discussion google group for process questions and suggestions
already.

https://groups.google.com/forum/#!forum/kubernetes-security-discuss

**Comment by nikhita** [comment]
https://github.com/kubernetes/security has been created and @kubernetes/product-security-team has admin access to the repo.

**Comment by nikhita** [comment]
This is done from a github-management perspective. We can track committee creation + documenting this repo in https://github.com/kubernetes/steering/issues/89.

/close

**Comment by philips** [comment]
Thank you @nikhita !
