### ISSUE TITLE
REQUEST: New membership for chandankumar4

### ISSUE THREAD

**Issue by chandankumar4** [kubernetes/org#5203]
### GitHub Username

@chandankumar4

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@willie-yao

### List of contributions to the Kubernetes project

- PRs reviewed / authored 

https://github.com/kubernetes-sigs/cluster-api/pull/11177
https://github.com/kubernetes-sigs/cluster-api/pull/11163
https://github.com/kubernetes-sigs/cluster-api/pull/11160
https://github.com/kubernetes-sigs/cluster-api/pull/11158
https://github.com/kubernetes-sigs/cluster-api/pull/11051
https://github.com/kubernetes-sigs/cluster-api/pull/10960
https://github.com/kubernetes-sigs/cluster-api/pull/10529
https://github.com/kubernetes-sigs/cluster-api/pull/10528
https://github.com/kubernetes-sigs/cluster-api/pull/10488
https://github.com/kubernetes-sigs/cluster-api/pull/10435
https://github.com/kubernetes-sigs/cluster-api/pull/10091
https://github.com/kubernetes-sigs/cluster-api/pull/9918
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4188
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4165
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4159
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4021

- SIG projects I am involved with

https://github.com/kubernetes-sigs/cluster-api
https://github.com/kubernetes-sigs/cluster-api-provider-azure

**Comment by sbueringer** [comment]
+1 from my side

**Comment by willie-yao** [comment]
+1 as well! Thanks for all your contributions 🚀

**Comment by jasonbraganza** [comment]
/assign

@chandankumar4, thank you for all your contributions 🙂

I’ve created PR #5206 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
