### ISSUE TITLE
REQUEST: New membership for tpantelis

### ISSUE THREAD

**Issue by tpantelis** [kubernetes/org#5205]
### GitHub Username

tpantelis

### Organization you are requesting membership in

kubernetes-sigs
kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@skitt

### Sponsor 2

@MrFreezeex

### List of contributions to the Kubernetes project

- PRs authored
   - https://github.com/kubernetes-sigs/mcs-api/pull/33
   - https://github.com/kubernetes-sigs/mcs-api/pull/35
   - https://github.com/kubernetes-sigs/mcs-api/pull/57
   - https://github.com/kubernetes-sigs/mcs-api/pull/58
   - https://github.com/kubernetes-sigs/mcs-api/pull/59
   - https://github.com/kubernetes-sigs/mcs-api/pull/60
   - https://github.com/kubernetes-sigs/mcs-api/pull/61
   - https://github.com/kubernetes-sigs/mcs-api/pull/64
   - https://github.com/kubernetes-sigs/mcs-api/pull/73
   - https://github.com/kubernetes-sigs/mcs-api/pull/75
   - https://github.com/kubernetes-sigs/mcs-api/pull/76
   - https://github.com/kubernetes-sigs/mcs-api/pull/77
   - https://github.com/kubernetes-sigs/mcs-api/pull/78
   - https://github.com/kubernetes-sigs/mcs-api/pull/79
   - https://github.com/kubernetes/enhancements/pull/4900
   
- PRs reviewed 
  - https://github.com/kubernetes-sigs/mcs-api/pull/34
  - https://github.com/kubernetes-sigs/mcs-api/pull/62
  - https://github.com/kubernetes/enhancements/pull/4887
  - https://github.com/kubernetes/kubernetes/pull/124344

- Issues opened
  - https://github.com/kubernetes/kubernetes/issues/124337
  - https://github.com/kubernetes/kubernetes/issues/126850
  
- SIG projects I am involved with
  - https://github.com/kubernetes-sigs/mcs-api

**Comment by skitt** [comment]
+1

**Comment by MrFreezeex** [comment]
+1

**Comment by jasonbraganza** [comment]
/assign

@tpantelis, thank you for all your contributions 🙂

I’ve created PR #5206 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
