### ISSUE TITLE
REQUEST: New membership for fanhaouu

### ISSUE THREAD

**Issue by fanhaouu** [kubernetes/org#5208]
### GitHub Username

@fanhaouu

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@ingvagabund

### Sponsor 2

@a7i

### List of contributions to the Kubernetes project

- PRs authored
https://github.com/kubernetes-sigs/descheduler/pull/1435
https://github.com/kubernetes-sigs/descheduler/pull/1369
https://github.com/kubernetes-sigs/descheduler/pull/1395
https://github.com/kubernetes-sigs/descheduler/pull/1436
https://github.com/kubernetes-sigs/descheduler/pull/1508
https://github.com/kubernetes-sigs/descheduler/pull/1517
https://github.com/kubernetes-sigs/descheduler/pull/1520
https://github.com/kubernetes-sigs/descheduler/pull/1521
https://github.com/kubernetes-sigs/descheduler/pull/1522
https://github.com/kubernetes-sigs/descheduler/pull/1523

- PRs reviewed
https://github.com/kubernetes-sigs/descheduler/pull/1527
https://github.com/kubernetes-sigs/descheduler/pull/1466
https://github.com/kubernetes/kubernetes/pull/127692
https://github.com/kubernetes/kubernetes/pull/119553

- Issues opened
https://github.com/kubernetes/kubernetes/issues/124844

**Comment by ingvagabund** [comment]
+1

**Comment by a7i** [comment]
+1

Thank you for all your contribution @fanhaouu

**Comment by ydFu** [comment]
@fanhaouu 
I want to express my heartfelt gratitude for your invaluable contributions to community endeavor 😊.

I'm delighted to inform you that I have initiated Pull Request #5211 to officially extend an invitation for your inclusion within the esteemed Kubernetes organization 🌟. Once this request is successfully merged, you will promptly receive a membership invite notification.

A warm welcome to the @kubernetes family! 🎉🚀

Best regards,

/assign

**Comment by jasonbraganza** [comment]
@fanhaouu would you kindly confirm that you received an invite and accepted it? if so then I can run this up the chain and check for you
