### ISSUE TITLE
REQUEST: New membership for dgrove-oss

### ISSUE THREAD

**Issue by dgrove-oss** [kubernetes/org#5226]
### GitHub Username

dgrove-oss

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

mimowo

### Sponsor 2

tenzen-y

### Configurable Resource Transformations (Kueue 0.9)
1. KEP:  https://github.com/kubernetes-sigs/kueue/pull/3013
2. Impl: https://github.com/kubernetes-sigs/kueue/pull/3026
3. Docs: https://github.com/kubernetes-sigs/kueue/pull/3175

### Support for External Frameworks  (Kueue 0.7)
1. https://github.com/kubernetes-sigs/kueue/pull/2059
2. https://github.com/kubernetes-sigs/kueue/pull/2107
3. https://github.com/kubernetes-sigs/kueue/pull/2186
4. https://github.com/kubernetes-sigs/kueue/pull/2478
5. https://github.com/kubernetes-sigs/kueue/pull/3167     

### Misc. Minor Contributions
1. https://github.com/kubernetes-sigs/kueue/pull/2279
3. https://github.com/kubernetes-sigs/kueue/pull/2601
4. https://github.com/kubernetes-sigs/kueue/pull/2840
5. https://github.com/kubernetes-sigs/kueue/pull/3172
6. https://github.com/kubernetes-sigs/kueue/pull/3260

**Comment by mimowo** [comment]
+1, thank you for all the contributions!

**Comment by tenzen-y** [comment]
+1
Thanks for your contributions!
