### ISSUE TITLE
REQUEST: Create repository kubernetes-sigs/cni-dra-driver

### ISSUE THREAD

**Issue by LionelJouin** [kubernetes/org#5228]
### New repo, staging repo, or migrate existing

new repository

### Is it a staging repo?

no

### Requested name for new repository

cni-dra-driver

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@LionelJouin ; @aojea ; @MikeZappa87

### Who should have write access?

@LionelJouin ; @aojea ; @MikeZappa87

### Who should be listed as approvers in OWNERS?

@LionelJouin ; @aojea ; @MikeZappa87

### Who should be listed in SECURITY_CONTACTS?

@LionelJouin ; @aojea ; @MikeZappa87

### What should the repo description be?

CNI DRA Driver

### What SIG and subproject does this fall under?

sig-network

### Please provide references to appropriate approval for this new repo

https://groups.google.com/g/kubernetes-sig-network/c/8Jfm_Qa-Bl0
https://groups.google.com/a/kubernetes.io/g/wg-device-management/c/E_vIab0M2cA
https://github.com/containernetworking/meeting-notes/blob/main/MEETING-NOTES.md (2024-10-14 ; 2024-10-21)

**Comment by Priyankasaggu11929** [comment]
/assign

New repo is created – https://github.com/kubernetes-sigs/cni-dra-driver

PR to add GitHub teams for the new repo – https://github.com/kubernetes/org/pull/5248

> What SIG and subproject does this fall under?

@LionelJouin, new repo will be (i) a new subproject of SIG Network, OR (ii) part of an [existing subproject of sig-network](https://github.com/kubernetes/community/tree/master/sig-network#subprojects)?

**Comment by aojea** [comment]
> ) a new subproject of SIG Networ

I will put it under https://github.com/kubernetes/community/tree/master/sig-network#pod-networking

**Comment by Priyankasaggu11929** [comment]
Repo creation is complete.

/close
