### ISSUE TITLE
REQUEST: New membership for LionelJouin

### ISSUE THREAD

**Issue by LionelJouin** [kubernetes/org#5229]
### GitHub Username

@LionelJouin

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@aojea

### Sponsor 2

@MikeZappa87

### List of contributions to the Kubernetes project

https://github.com/kubernetes/enhancements/pull/4771
https://github.com/kubernetes/enhancements/pull/4861
https://github.com/kubernetes/kubernetes/issues/126004
https://github.com/kubernetes/kubernetes/pull/128240
https://github.com/kubernetes/kubernetes/pull/126005
https://github.com/kubernetes/kubernetes/pull/127751
https://github.com/kubernetes/kubernetes/pull/126482
https://github.com/kubernetes-sigs/gateway-api/pull/3105

**Comment by aojea** [comment]
+1

Thanks for your great work and looking forward for more contributions

**Comment by jasonbraganza** [comment]
/assign

@LionelJouin, thank you for all your contributions 🙂

I’ve created PR #5232 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
