### ISSUE TITLE
REQUEST: New integration for etcd-io/etcd

### ISSUE THREAD

**Issue by ivanvc** [kubernetes/org#5231]
### Organization or Repo

etcd-io/etcd

### Name of integration

Codecov

### Link to integration website

github.com/apps/codecov

### Describe what is attempting to be accomplished

We already had the Codecov integration, and it used to work fine. But it recently started showing a warning when it comments on pull requests:

> ⚠️ Please install the 'codecov app svg image' to ensure uploads and comments are reliably processed by Codecov.

At the bottom, it says:

> ❗ Your organization needs to install the Codecov GitHub app to enable full functionality.

Refer to a recent comment, i.e., https://github.com/etcd-io/etcd/pull/18767#issuecomment-2428363634

Would it be possible to install the Codecov GitHub app, so we don't get the warning?

**Comment by ivanvc** [comment]
@MadhavJivrajani, would you be able to help us with this request? Thanks!

**Comment by Priyankasaggu11929** [comment]
@ivanvc, could you please provide a list of repos under etcd-io org that require installing codecov app? Thanks!
(we want to avoid installing it org-wide since it includes all future etcd-io org repos as well)

**Comment by ivanvc** [comment]
Hi, @Priyankasaggu11929. At this moment we only want it for the etcd repository. Thank you!

**Comment by Priyankasaggu11929** [comment]
Thank you @ivanvc.

I've installed the codecov app for `etcd-io/etcd` repo:

![image](https://github.com/user-attachments/assets/351a42a4-7bf2-423a-8ae3-2f8650fddcc1)
![image](https://github.com/user-attachments/assets/ca3e4f87-f0c6-4581-8463-9e1f33ace3a5)

**Comment by ivanvc** [comment]
Thanks, @Priyankasaggu11929 🙇. I'll verify that we don't have the warning anymore as soon as we get a new pull request.

**Comment by Priyankasaggu11929** [comment]
yes, let's keep this issue open until we have verified. Thank you! :)

**Comment by ivanvc** [comment]
@Priyankasaggu11929, it works as expected, the warning is fine (i.e., https://github.com/etcd-io/etcd/pull/18939#issuecomment-2495415769). Thank you! 🙇

**Comment by Priyankasaggu11929** [comment]
Thanks for the confirmation.

/close
