### ISSUE TITLE
REQUEST: New membership for zhanggbj

### ISSUE THREAD

**Issue by zhanggbj** [kubernetes/org#5237]
### GitHub Username

zhanggbj

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@XudongLiuHarold 

### Sponsor 2

@HanFa

### List of contributions to the Kubernetes project

- PR authored
	- https://github.com/kubernetes-sigs/cluster-api/pull/10840
	- https://github.com/kubernetes-sigs/cluster-api/pull/10715
	- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3146
	- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3023
	- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2651
	- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2865
	- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2862
	- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2590
	- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2984
- Issue opened
	- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1950
	- https://github.com/kubernetes-sigs/cluster-api/issues/10839
	- https://github.com/kubernetes-sigs/cluster-api/issues/10714

I will be actively working and maintaining cloud-provider-vsphere.

**Comment by XudongLiuHarold** [comment]
+1, thanks for your contributions Gong!

**Comment by lubronzhan** [comment]
+1 welcome to the CPI!

**Comment by HanFa** [comment]
Welcome and thanks for all your contributions!

**Comment by zhanggbj** [comment]
Thanks @XudongLiuHarold @lubronzhan @HanFa for your sponsorship!

**Comment by Priyankasaggu11929** [comment]
/assign

@zhanggbj, thank you for all your contributions 🙂

I’ve created PR https://github.com/kubernetes/org/pull/5241 to add you to the Kubernetes(s) Org. Once that gets merged, you should get a membership invite notification.

Welcome to https://github.com/kubernetes! 🎉
