### ISSUE TITLE
REQUEST: Consolidate COSI Repos

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/org#5238]
### New repo, staging repo, or migrate existing

New repo

### Is it a staging repo?

no

### Requested name for new repository

https://github.com/kubernetes-sigs/container-object-storage-interface

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

@jsafrane, @msau42, @saad-ali, @xing-yang, 

### Who should have write access?

@jsafrane, @msau42, @saad-ali, @xing-yang, @BlaineEXE, @shanduur

### Who should be listed as approvers in OWNERS?

@jsafrane, @msau42, @saad-ali, @xing-yang, @BlaineEXE, @shanduur

### Who should be listed in SECURITY_CONTACTS?

@jsafrane, @msau42, @saad-ali, @xing-yang

### What should the repo description be?

Container Object Storage Interface (COSI) responsible for defining COSI spec and APIs,  interfacing with COSI drivers, and managing the lifecycle of COSI objects.

### What SIG and subproject does this fall under?

SIG: sig-storage, subproject: kubernetes-cosi

### Please provide references to appropriate approval for this new repo

See previous issue when the original repo was created: https://github.com/kubernetes/org/issues/2289
There are multiple COSI repos. It is getting difficult to manage them. We are trying to consolidate them into one repo so that it will be easier for release and testing.
Discussed at SIG Storage meeting on 10/17/2024:  https://docs.google.com/document/d/1-8KEG8AjAgKznS9NFm3qWqkGyCHmvU6HVl0sk5hwoAE/edit?tab=t.0#heading=h.5of1uelb9bht

### Additional context for request

We are merging multiple COSI repos into one (subproject of SIG Storage).  Here are the requests.
1. Copy the content of the repo "https://github.com/kubernetes-sigs/container-object-storage-interface-api" to a new repo "https://github.com/kubernetes-sigs/container-object-storage-interface".
2. Archive the original repo "container-object-storage-interface-api" and point it to the new repo "container-object-storage-interface".
3. Archive the following repos and point them to the new repo "container-object-storage-interface".
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar
https://github.com/kubernetes-sigs/container-object-storage-interface-controller
https://github.com/kubernetes-sigs/container-object-storage-interface-spec

**Comment by Priyankasaggu11929** [comment]
/assign

New repo is created – https://github.com/kubernetes-sigs/container-object-storage-interface

PR to add GitHub teams for the new repo – https://github.com/kubernetes/org/pull/5273

PR to document new repo in k/community – https://github.com/kubernetes/community/pull/8180

Once above PRs are merged, first part of the request (new repo creation) will be complete.

---

> Here are the requests.
> 1. Copy the content of the repo "https://github.com/kubernetes-sigs/container-object-storage-interface-api" to a new repo "https://github.com/kubernetes-sigs/container-object-storage-interface".
> 2. Archive the original repo "container-object-storage-interface-api" and point it to the new repo "container-object-storage-interface".
> 3. Archive the following repos and point them to the new repo "container-object-storage-interface".
> https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar
> https://github.com/kubernetes-sigs/container-object-storage-interface-controller
> https://github.com/kubernetes-sigs/container-object-storage-interface-spec 

@xing-yang – could you take care of above items – copying the content to the new repo? and adding appropriate pointers in the repos to be archived? 

I can then follow up and take care of the archival of all requested repos in a separate set of PRs. Thanks!

**Comment by xing-yang** [comment]
Thanks @Priyankasaggu11929 !

> @xing-yang – could you take care of above items – copying the content to the new repo? and adding appropriate pointers in the repos to be archived?

@BlaineEXE can you please take care of these?  Thanks.

**Comment by Priyankasaggu11929** [comment]
Thank you @xing-yang, @BlaineEXE.

Pending review on PR – https://github.com/kubernetes/community/pull/8180

Following on the second part of the request (archival of requested repos), please review the following PRs:

- https://github.com/kubernetes/org/pull/5277
- https://github.com/kubernetes/community/pull/8195

Once above PRs are merged, I'll archive the repos and send out notice. Thanks!

**Comment by Priyankasaggu11929** [comment]
Following repositories have been transferred to `kubernetes-retired` org and archived:
- https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar
- https://github.com/kubernetes-sigs/container-object-storage-interface-controller
- https://github.com/kubernetes-sigs/container-object-storage-interface-spec

Notice of archival: https://groups.google.com/a/kubernetes.io/g/dev/c/FnlVlSFS63k/m/HWP1XlXoAQAJ

Only remaining item left is merge of PR https://github.com/kubernetes/community/pull/8195

**Comment by BlaineEXE** [comment]
I think the last item that needs to be done is to change current Kubernetes/KEP instances of https://github.com/kubernetes-sigs/container-object-storage-interface-api to https://github.com/kubernetes-sigs/container-object-storage-interface (new monorepo). The new monorepo is now up to date with everything so is ready to be the only reference.

**Comment by Priyankasaggu11929** [comment]
PRs for removing "container-object-storage-interface-api" repo:

- k/community: https://github.com/kubernetes/community/pull/8206
- k/org: https://github.com/kubernetes/org/pull/5294

Please review ^. Thanks! I'll archive the repo once PRs are merged.

**Comment by Priyankasaggu11929** [comment]
Update – https://github.com/kubernetes-sigs/container-object-storage-interface-api is archived as well now.

**Comment by Priyankasaggu11929** [comment]
Closing it as done. Thanks! 

/close
