### ISSUE TITLE
REQUEST: New membership for @bryan-cox

### ISSUE THREAD

**Issue by bryan-cox** [kubernetes/org#5260]
### GitHub Username

@bryan-cox

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mboersma

### Sponsor 2

@enxebre

### List of contributions to the Kubernetes project

Involved with CAPZ SIGS project. Authored the following PRs: 
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4415
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5092
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5099
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5102
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5111
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5200
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5254

**Comment by mboersma** [comment]
/lgtm

@bryan-cox has been a big contributor to CAPZ and has been very active in the community. 💯

**Comment by jasonbraganza** [comment]
@bryan-cox, [Community Membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) require that sponsors be from different work orgs. 
Since Matt’s already approved, I’d request you to get another sponsor in Jon’s place. 
Once that’s done, I’ll quickly raise a membership PR.

**Comment by enxebre** [comment]
+1
Thanks Bryan!

**Comment by jasonbraganza** [comment]
@bryan-cox Thank you. would you also kindly edit your request and change sponsor 2 to @enxebre?

**Comment by bryan-cox** [comment]
@jasonbraganza No problem at all. I updated the sponsor 2.

I also updated the organization to include kubernetes in addition to kubernetes-sigs.

**Comment by jasonbraganza** [comment]
/assign

@bryan-cox, thank you for all your contributions 🙂

I’ve created PR #5262  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
