### ISSUE TITLE
REQUEST: New membership for ghouscht

### ISSUE THREAD

**Issue by ghouscht** [kubernetes/org#5261]
### GitHub Username

@ghouscht

### Organization you are requesting membership in

etcd-io

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jmhbnz

### Sponsor 2

@ivanvc

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/kubernetes/pulls?q=author%3Aghouscht+
- https://github.com/etcd-io/etcd/pulls?q=author%3Aghouscht+

**Comment by jmhbnz** [comment]
+1 Many thanks for your work so far on etcd @ghouscht 🙏🏻

**Comment by ivanvc** [comment]
+1 Thanks for your contributions, @ghouscht. I am excited to have you on the team and look forward to working with you more.

**Comment by jasonbraganza** [comment]
/assign

@ghouscht, thank you for all you do 🙂

I’ve created PR #5264 to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by ivanvc** [comment]
@ghouscht, please open a pull request to add yourself to the "members" team for triaging access. Refer to: #5256
