### ISSUE TITLE
REQUEST: New membership for rschalo

### ISSUE THREAD

**Issue by rschalo** [kubernetes/org#5265]
### GitHub Username

@rschalo

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jonathan-innis

### Sponsor 2

@Bryce-Soghigian

### List of contributions to the Kubernetes project

PRs Authored:
https://github.com/kubernetes-sigs/karpenter/pull/1728
https://github.com/kubernetes-sigs/karpenter/pull/1689
https://github.com/kubernetes-sigs/karpenter/pull/1763
https://github.com/kubernetes-sigs/karpenter/pull/1386
https://github.com/kubernetes-sigs/karpenter/pull/1336

Issues Created/Resolved:
https://github.com/kubernetes/kubernetes/issues/127105
https://github.com/aws/karpenter-provider-aws/issues/7184

SIG Projects Involved with:
https://github.com/kubernetes-sigs/karpenter
https://github.com/aws/karpenter-provider-aws

**Comment by Bryce-Soghigian** [comment]
Fully support @rschalo joining the organization, he has made many valuable contributions to the sig!!

**Comment by jasonbraganza** [comment]
@jonathan-innis, a +1 will  help me process this request. Thank you :)

**Comment by jonathan-innis** [comment]
+1, @rschalo has been heavily contributing to sigs.k8s.ip/karpenter as of late!

**Comment by Priyankasaggu11929** [comment]
/assign

@rschalo, thank you for all your contributions 🙂

I’ve created PR https://github.com/kubernetes/org/pull/5275 to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to https://github.com/kubernetes! 🎉

**Comment by rschalo** [comment]
Hi @Priyankasaggu11929 I unfortuately was OOTO and was unable to accept the invitation before it expired, could it be resent please?

**Comment by rschalo** [comment]
Thank you!
