### ISSUE TITLE
REQUEST: New membership for liu-cong

### ISSUE THREAD

**Issue by liu-cong** [kubernetes/org#5269]
### GitHub Username

liu-cong

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

ahg-g

### Sponsor 2

Jeffwan

### List of contributions to the Kubernetes project

I am actively contributing to the https://github.com/kubernetes-sigs/llm-instance-gateway project.

- Opened 6 issues in the past 2 months: https://github.com/kubernetes-sigs/llm-instance-gateway/issues?q=is%3Aissue+author%3Aliu-cong
- Authored 12 PRS: https://github.com/kubernetes-sigs/llm-instance-gateway/pulls?q=is%3Apr+author%3Aliu-cong

**Comment by Jeffwan** [comment]
+1, @liu-cong made lots of contributions in llm-instance-gateway project and welcome to the community!
