### ISSUE TITLE
REQUEST: New membership for smourapina

### ISSUE THREAD

**Issue by smourapina** [kubernetes/org#527]
### GitHub Username
@smourapina

### Organization you are requesting membership in
@kubernetes

### Requirements
* [x]  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
* [x]  I have enabled 2FA on my GitHub account (https://github.com/settings/security)
* [x]  I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
* [x]  I am actively contributing to 1 or more Kubernetes subprojects
* [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
* [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
* @mariantalla
* @BenTheElder

### List of contributions to the Kubernetes project
* SIG-release
  
  * CI signal shadow for v1.14

**Comment by BenTheElder** [comment]
+1, thanks for your contributions!

**Comment by mariantalla** [comment]
Huge +1, thanks for your awesome work with CI signal so far and excited to see what you do next!

**Comment by mrbobbytables** [comment]
Hey there @smourapina , thank you for all your help with the 1.14 release :)

I've created PR #539  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

/pony yay
