### ISSUE TITLE
REQUEST: Create kjob repo

### ISSUE THREAD

**Issue by mimowo** [kubernetes/org#5279]
### New repo, staging repo, or migrate existing

new

### Is it a staging repo?

no

### Requested name for new repository

kjob

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

mimowo, mwielgus

### Who should have write access?

mimowo, mwielgus

### Who should be listed as approvers in OWNERS?

mimowo, mwielgus

### Who should be listed in SECURITY_CONTACTS?

mimowo, mwielgus

### What should the repo description be?

KJob: Tool for CLI-loving ML researchers

### What SIG and subproject does this fall under?

sig-apps

### Please provide references to appropriate approval for this new repo

The move of the implementation was discussed under:
- [issue: Decide if we release kjobctl as part of Kueue](https://github.com/kubernetes-sigs/kueue/issues/2778) 
- [sig-apps meeting Nov 25, 2024](https://docs.google.com/document/d/1LZLBGW2wRDwAfdBNHJjFfk9CFoyZPcIYGWU7R1PQ3ng/)

### Additional context for request

This repository will host the implementation extracted from the temporary place under the [Kueue](https://github.com/kubernetes-sigs/kueue) repository ( [cmd/experimental/kjobctl](https://github.com/kubernetes-sigs/kueue/tree/main/cmd/experimental/kjobctl) path).

**Comment by soltysh** [comment]
:+1: with my sig-apps lead :tophat:

**Comment by mimowo** [comment]
cc @janetkuo

**Comment by janetkuo** [comment]
LGTM 👍

**Comment by Priyankasaggu11929** [comment]
/assign

New repo is created – https://github.com/kubernetes-sigs/kjobi

PR to add GitHub teams for the new repo – https://github.com/kubernetes/org/pull/5282

@mimowo, the new repo will be a new subproject under `sig-apps`? or part of an [existing subproject](https://git.k8s.io/community/sig-apps#subprojects)?

**Comment by mimowo** [comment]
> @mimowo, the new repo will be a new subproject under sig-apps? or part of an [existing subproject](https://git.k8s.io/community/sig-apps#subprojects)?

I think a new subproject under `sig-apps`, but cc @soltysh @mwielgus

**Comment by soltysh** [comment]
> @mimowo, the new repo will be a new subproject under `sig-apps`? or part of an [existing subproject](https://git.k8s.io/community/sig-apps#subprojects)?

It'll be a new sub-project, since kueue is part of [sig-scheduling](https://github.com/kubernetes/community/tree/master/sig-scheduling#kueue).

**Comment by Priyankasaggu11929** [comment]
> It'll be a new sub-project, since kueue is part of [sig-scheduling](https://github.com/kubernetes/community/tree/master/sig-scheduling#kueue).

created – https://github.com/kubernetes/community/pull/8201

**Comment by Priyankasaggu11929** [comment]
Once PR https://github.com/kubernetes/community/pull/8201 is closed, new repo creation process is complete and ok to close. Thanks!
