### ISSUE TITLE
New repository for multi-tenancy proposals and prototypes

### ISSUE THREAD

**Issue by easeway** [kubernetes/org#528]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
multi-tenancy

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
davidopp, easeway

### If a new repo, who should be listed as approvers in OWNERS
davidopp, easeway

### If a new repo, who should be listed in SECURITY_CONTACTS
davidopp, easeway

### What should the repo description be
A working place for multi-tenancy related proposals and prototypes.

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject for sig-auth called multi-tenancy

### Approvals

Attached the email communication:

```
On Tue, Feb 26, 2019 at 1:25 PM Tim Allclair <tallclair@google.com> wrote:
To create a new repo, file an issue here: https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-repo&template=repo-create.md&title=

Yeah, I think we can sponsor it.

On Tue, Feb 26, 2019 at 1:21 PM David Oppenheimer <davidopp@google.com> wrote:
Hi Tim. The multitenancy working group would like to get a repo under kubernetes-sigs. Would you be willing to sponsor this for us (since the working group is part of sig-auth)? I don't know the full process for getting this approved and set up. If you (Tim) don't know, Yisui can you research this?

```

**Comment by nikhita** [comment]
@easeway Could you list the approvals as in the [issue template](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-repo&template=repo-create.md&title=)?

**Comment by easeway** [comment]
I pasted the email conversation in approvals, is that good enough?

**Comment by nikhita** [comment]
@easeway We need links to approvals on mailing lists. Could you send an email to the sig-auth _and_ multitenancy working group mailing lists and get approvals from the chairs of the working group + technical leads of sig-auth?

(The sig-auth charter delegates the creation of new subprojects to technical leads - https://github.com/kubernetes/community/blob/master/sig-auth/charter.md#subproject-creation)

**Comment by mikedanese** [comment]
I'm pro creating a sandbox for this. cc @tallclair

**Comment by tallclair** [comment]
+1

**Comment by nikhita** [comment]
@davidopp if you could formally comment with a +1 here, I can go ahead and create the repo. :)

**Comment by liggitt** [comment]
+1

regarding prototype code, please add clear language to the repo readme about the support statement (or lack of support statement) of code that could be imported

**Comment by nikhita** [comment]
For the record, notice to:

- sig-auth ML - https://groups.google.com/d/topic/kubernetes-sig-auth/IbPS3qWKxVI/discussion

- wg-multitenancy ML - https://groups.google.com/d/topic/kubernetes-wg-multitenancy/TNphoyPlHQc/discussion

**Comment by davidopp** [comment]
+1

**Comment by nikhita** [comment]
I have created https://github.com/kubernetes-sigs/multi-tenancy.

I have also created https://github.com/kubernetes/org/pull/576 to add teams to provide admin and write access to the repo. Once the PR gets merged, the postsubmit runs and the team gets created, I will grant access to the team.

---

@easeway I noticed that you are not a member of @kubernetes-sigs. Only members can be added to OWNERS files and to teams, so if you could [apply](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) for membership, that would be awesome. You can create a PR to add yourself to OWNERS and the teams after that. :)

--- 

Apart from granting permission to the team, the final step is to add this repo to sigs.yaml in the community repo. @easeway could you create a PR to do that? We can close this issue after it gets added.

**Comment by nikhita** [comment]
Oh, oops looks like @davidopp is also not a @kubernetes-sigs member, but a @kubernetes member.

Members of @kubernetes are implicitly eligible for membership to @kubernetes-sigs, so I'll go ahead and add David to the k-sigs org so that he can be added to the teams.

**Comment by davidopp** [comment]
Thanks

**Comment by nikhita** [comment]
kubernetes-sigs/multi-tenancy-admins@ has admin access and kubernetes-sigs/multi-tenancy-maintainers@ has write access.

**Comment by easeway** [comment]
Thanks @nikhita for setting this up!
