### ISSUE TITLE
REQUEST: Membership in netlify project kubernetes-sigs-cluster-api-ibmcloud

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes/org#5284]
### Organization or Repo

kubernetes-sigs/cluster-api-provider-ibmcloud

### User affected

@Prajyot-Parab

### Describe the issue

I'm a maintainer of the [cluster-api-provider-ibmcloud](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud) project. I'd like to request access to the corresponding [netlify project](https://app.netlify.com/sites/kubernetes-sigs-cluster-api-ibmcloud).

Mail - prajyot.parab2@ibm.com

**Comment by Prajyot-Parab** [comment]
@mrbobbytables can you PTAL

**Comment by mrbobbytables** [comment]
invite is out :+1:

**Comment by Prajyot-Parab** [comment]
Thanks @mrbobbytables for the quick response.

can you please let me know how can I add new DNS records to below list (attached picture), seems like they are auto generated as type is Netlify

<img width="1421" alt="Screenshot 2024-12-04 at 12 08 07 AM" src="https://github.com/user-attachments/assets/91c7959d-98ae-4218-b5c0-781389036b3b">

**Comment by Prajyot-Parab** [comment]
Resolved.
