### ISSUE TITLE
REQUEST: New membership for taragu

### ISSUE THREAD

**Issue by taragu** [kubernetes/org#529]
### GitHub Username
@taragu 

### Organization you are requesting membership in
@kubernetes-incubator 

I'm already a Kubernetes member and I would like to also join kubernetes-incubator to work on kubernetes-incubator/service-catalog. Thanks!

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- (at)sponsor-1
- (at)sponsor-2

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by mrbobbytables** [comment]
@taragu I've created PR #539 to add you to @kubernetes-incubator. Once it gets merged, you should get a invite notification.

Thanks!

/assign

**Comment by taragu** [comment]
Thanks @mrbobbytables !!
