### ISSUE TITLE
REQUEST: New membership for zac-nixon

### ISSUE THREAD

**Issue by zac-nixon** [kubernetes/org#5292]
### GitHub Username

zac-nixon

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [x] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [x] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

oliviassss

### Sponsor 2

elmiko

### List of contributions to the Kubernetes project

Big features:
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3861
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3853

Small features / bug fixes:
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3941
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3936
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3924
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3921

Issues triaged.
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3865
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3940
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3944
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3969

**Comment by shraddhabang** [comment]
+1 from me :)

**Comment by elmiko** [comment]
+1 from me, Zac has made several contributions to the aws lb controller, and hopefully many more =)

**Comment by zac-nixon** [comment]
https://github.com/cncf/gitdm/pull/559

**Comment by jasonbraganza** [comment]
@shraddhabang, I cannot seem to find you in an `OWNERS` file in any of our orgs repos. as per our [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) …

> Sponsors must be reviewers or approvers in at least one OWNERS file within one of the [Kubernetes GitHub organizations](https://github.com/kubernetes/community/blob/master/github-management#actively-used-github-organizations)

I may have missed the mention somewhere. If you are, would you kindly point me to it?
If not, @zac-nixon will have to find another sponsor.

**Comment by shraddhabang** [comment]
Ohh okay. No I missed it. We will find another sponsor for Zac.

**Comment by oliviassss** [comment]
+1 from me. Thanks for your continuous contribution @zac-nixon

**Comment by M00nF1sh** [comment]
+1 for me. Zac has been a valuable member

**Comment by jasonbraganza** [comment]
/assign

@zac-nixon, thank you for all your contributions 🙂

I’ve created PR #5296  to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
