### ISSUE TITLE
REQUEST: Migrate llm-instance-gateway to gateway-api-inference-extension

### ISSUE THREAD

**Issue by robscott** [kubernetes/org#5302]
### New repo, staging repo, or migrate existing

Migrate existing

### Is it a staging repo?

no

### Requested name for new repository

gateway-api-inference-extension

### Which Organization should it reside

kubernetes-sigs

### Who should have admin access?

No change

### Who should have write access?

No change

### Who should be listed as approvers in OWNERS?

No change

### Who should be listed in SECURITY_CONTACTS?

No change

### What should the repo description be?

No change

### What SIG and subproject does this fall under?

SIG Network (see https://github.com/kubernetes/community/pull/8211)

### Please provide references to appropriate approval for this new repo

Lots of different discussions around this, but https://github.com/kubernetes/community/pull/8211 has the most recent one.

**Comment by robscott** [comment]
SIG Net Leads:
/cc @aojea @danwinship @MikeZappa87 @shaneutt @thockin

WG Serving Leads:
/cc @ArangoGutierrez @Jeffwan @SergeyKanzhelev @terrytangyuan

**Comment by aojea** [comment]
I didn't know it was possible to rename a repo

/lgtm

**Comment by BenTheElder** [comment]
> I didn't know it was possible to rename a repo

Yes, and Github will actually serve redirects as long as the old name isn't reused.

https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by terrytangyuan** [comment]
@BenTheElder Who should be the one actually doing the renaming for that repo?

**Comment by Jeffwan** [comment]
it has been discussed.

/lgtm

**Comment by danehans** [comment]
>Yes, and Github will actually serve redirects as long as the old name isn't reused.

To ensure this does not happen, what do you think about the following steps:

1. Create a new gateway-api-inference-extension repo.
2. Move applicable llm-instance-gateway repo content to gateway-api-inference-extension, except for the README stating the repo is retired with a link to the gateway-api-inference-extension repo.
3. After some time, remove the llm-instance-gateway repo.

**Comment by aojea** [comment]
we own the process so for someone to reuse the name has to ask for approval first

**Comment by BenTheElder** [comment]
> @BenTheElder Who should be the one actually doing the renaming for that repo?

The owners of this repo (`@kubernetes/owners`) https://github.com/kubernetes/community/blob/5ed4178ced364351ce4f4e485e7f332c7a481937/github-management/README.md#github-administration-team

**Comment by BenTheElder** [comment]
> To ensure this does not happen, what do you think about the following steps:
>
> Create a new gateway-api-inference-extension repo.
> Move applicable llm-instance-gateway repo content to gateway-api-inference-extension, except for the README stating the repo is retired with a link to the gateway-api-inference-extension repo.
> After some time, remove the llm-instance-gateway repo.

I don't think anyone is likely to reuse the name, not just anyone can create a repo, and even if the name did get reused eventually, I assume by then we would have built awareness around the current project and cleaned up stale inbound links / CI / ... anyhow.

**Comment by BenTheElder** [comment]
> The owners of this repo (@kubernetes/owners)
> https://github.com/kubernetes/community/blob/5ed4178ced364351ce4f4e485e7f332c7a481937/github-management/README.md#github-administration-team

(TLDR: We have a small team in SIG ContribEx with github org admin powers for this sort of thing)

I'm pretty sure most of the Github Management team are at KubeCon India right now.

I'd suggest we can ping them sometime early next week if it's still waiting, post-approval.

They're ideally looking for +1 from the [TLs of SIG Net](https://github.com/kubernetes/community/tree/master/sig-network#:~:text=Technical%20Leads,issues%20and%20decisions.) (and possibly Apps, though https://github.com/kubernetes/community/pull/8211 should cover that), and then at some point they'll get to it in a sweep of the repo.

cc @thockin @danwinship + https://github.com/kubernetes/org/issues/5302#issuecomment-2533110385

**Comment by MadhavJivrajani** [comment]
The repo has been renamed here: https://github.com/kubernetes-sigs/gateway-api-inference-extension
Once https://github.com/kubernetes/org/pull/5309 is merged, we can close this out

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/org/pull/5309 is merged.

/close

Thank you!
