### ISSUE TITLE
REQUEST: New membership for serngawy

### ISSUE THREAD

**Issue by serngawy** [kubernetes/org#5306]
### GitHub Username

serngawy

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@fabriziopandini

### Sponsor 2

@JoelSpeed

### List of contributions to the Kubernetes project

- I have contributed to Cluster-api-provider-aws [PRs](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3Aserngawy)
- I have contributed to Cluster-api [PRs](https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+author%3Aserngawy) 
- I have contributed to Cluster-api-operator [PR](https://github.com/kubernetes-sigs/cluster-api-operator/pulls?q=is%3Apr+author%3Aserngawy) 

I was member of CAPI release team v1.9 and a member of the coming release v1.10 team as well.

**Comment by JoelSpeed** [comment]
+1

I'm in favour of @serngawy joining the org so that he can continue his work within the Cluster API ecosystem

**Comment by fabriziopandini** [comment]
+1

thanks @serngawy for the awesome work so far, looking forward for what comes next!

**Comment by jasonbraganza** [comment]
/assign

@serngawy, thank you for all your contributions 🙂

I’ve created PR #5312 to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
