### ISSUE TITLE
REQUEST: New membership for foxyriver

### ISSUE THREAD

**Issue by foxyriver** [kubernetes/org#531]
### GitHub Username
@foxyriver

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zhangxiaoyu-zidif 
- @xiangpengzhao 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  kubernetes/kubernetes#72802     kubernetes/kubernetes#66818
  kubernetes/kubernetes#66670     kubernetes/kubernetes#66331
  kubernetes/kubernetes#66262     kubernetes/kubernetes#66238
  kubernetes/kubernetes#66210     kubernetes/kubernetes#59026
  kubernetes/kubernetes#58069     kubernetes/kubernetes#57987
  kubernetes/kubernetes#55128     kubernetes/kubernetes#55038
  kubernetes/kubernetes#54278     kubernetes/kubernetes#54275
  kubernetes/kubernetes#53689     kubernetes/kubernetes#52758
  kubernetes/kubernetes#52718     kubernetes/kubernetes#52704
  kubernetes/kubernetes#50052     kubernetes/kubernetes#40412
  kubernetes/kubernetes#40410     kubernetes/kubernetes#40408
  kubernetes/kubernetes#40199     kubernetes/kubernetes#39838
  kubernetes/kubernetes#39837     kubernetes/kubernetes#39507
  kubernetes/kubernetes#39319     kubernetes/kubernetes#38917
  kubernetes/kubernetes#38739     kubernetes/kubernetes#38551
  kubernetes/kubernetes#38351     kubernetes/kubernetes#37364
  kubernetes/kubernetes#37260     kubernetes/kubernetes#35884
  kubernetes/kubernetes#35610
- Issues responded to
  kubernetes/kubernetes#58002
  kubernetes/kubeadm#1340
  kubernetes/kubeadm#1355
  kubernetes/kubeadm#1295
  kubernetes/kubeadm#1105
  kubernetes/kubeadm#1278
- SIG projects I am involved with
  sig/autoscaling

**Comment by zhangxiaoyu-zidif** [comment]
Hi, you can list you PRs like this: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Afoxyriver+is%3Aclosed

**Comment by foxyriver** [comment]
@zhangxiaoyu-zidif keep the sequence?

**Comment by tanshanshan** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @foxyriver, thank you for all your contributions to the project :)

I've created PR #539  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
