### ISSUE TITLE
REQUEST: New membership for Rakshith-R

### ISSUE THREAD

**Issue by Rakshith-R** [kubernetes/org#5313]
### GitHub Username

@Rakshith-R

### Organization you are requesting membership in

kubernetes-csi

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@PrasadG193

https://github.com/kubernetes-csi/external-snapshot-metadata/blob/main/OWNERS

### List of contributions to the Kubernetes project

- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/45
- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/46
- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/47
- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/48
- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/60
- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/72
- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/81
- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/83
- https://github.com/kubernetes-csi/external-snapshot-metadata/pull/89
- https://github.com/kubernetes-csi/external-snapshot-metadata/issues/74

- https://github.com/kubernetes-csi/csi-release-tools/pull/265

- https://github.com/kubernetes-csi/external-snapshotter/pull/825
- https://github.com/kubernetes-csi/external-snapshotter/pull/922

- https://github.com/kubernetes-csi
- Actively invovled in Changed Block Tracking enhancement https://github.com/kubernetes/enhancements/issues/3314 and external-snapshot-metadata sidecar https://github.com/kubernetes-csi/external-snapshot-metadata.

In addition to the above, I'm one of the maintainers of Ceph-CSI.

**Comment by xing-yang** [comment]
+1

**Comment by jasonbraganza** [comment]
@PrasadG193, I cannot seem to find you in an OWNERS file in any of our orgs repos. as per our [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) …

> Sponsors must be reviewers or approvers in at least one OWNERS file within one of the [Kubernetes GitHub organizations](https://github.com/kubernetes/community/blob/master/github-management#actively-used-github-organizations)

I may have missed the mention somewhere. If you are, would you kindly point me to it?
If not, @Rakshith-R will have to find another sponsor.

**Comment by Rakshith-R** [comment]
Hey @jasonbraganza ,

I've already linked the owners file where @PrasadG193 is mentioned in description 
Please refer to
https://github.com/kubernetes-csi/external-snapshot-metadata/blob/main/OWNERS

**Comment by jasonbraganza** [comment]
Thank you very much, @Rakshith-R! Apologies for missing that bit.

**Comment by jasonbraganza** [comment]
/assign

@Rakshith-R, thank you for all your contributions 🙂

I’ve created PR #5320 to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by Rakshith-R** [comment]
> /assign
> 
> @Rakshith-R, thank you for all your contributions 🙂
> 
> I’ve created PR #5320 to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.
> 
> Welcome to @kubernetes! 🎉

Thanks !
