### ISSUE TITLE
REQUEST: New membership for @network-charles

### ISSUE THREAD

**Issue by network-charles** [kubernetes/org#5314]
### GitHub Username

@network-charles

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [ ] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [X] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sftim

### Sponsor 2

@katcosgrove

### List of contributions to the Kubernetes project

PRs Authored
I have authored a lot of PRs below are a few of them. I also participate in the PR Wrangler program.
- https://github.com/kubernetes/website/pull/48531
- https://github.com/kubernetes/website/pull/47977

Issues Reviewed
- https://github.com/kubernetes/website/pull/48655
- https://github.com/kubernetes/website/pull/45485

You can find a list of all the PR/issues I reviewed in the last one year via the heatmap below.
https://github.com/network-charles?from=2024-12-01&to=2024-12-19&org=kubernetes&year_list=1

SIG Project I am involved with 
- SIG Docs

**Comment by sftim** [comment]
Happy to sponsor you, @network-charles

**Comment by network-charles** [comment]
Thank you 🎉

**Comment by katcosgrove** [comment]
Also happy to sponsor!

**Comment by network-charles** [comment]
Thank you 🎉

**Comment by jasonbraganza** [comment]
/assign

@network-charles, thank you for all your contributions 🙂

I’ve created PR #5319 to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

**Comment by network-charles** [comment]
It's a pleasure, @jasonbraganza 🎉
