### ISSUE TITLE
REQUEST: New membership for zhifei92

### ISSUE THREAD

**Issue by zhifei92** [kubernetes/org#5317]
### GitHub Username

@zhifei92

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **SUGGESTED:** Ensure your [affiliation in gitdm](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) is up to date (gitdm is used by [devstats](https://k8s.devstats.cncf.io/) to track affiliation)
- [X] **SUGGESTED:** Ensure your [affiliation in openprofile.dev](https://openprofile.dev/edit/profile) is up to date (used by [LFX Insights](https://insights.lfx.dev/) to track affiliation, will replace gitdm in the future)
- [ ] **SUGGESTED:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@pacoxu

### Sponsor 2

@pohly

### List of contributions to the Kubernetes project

- PRS
  - in kubernetes
    - https://github.com/kubernetes/kubernetes/pull/127495
    - https://github.com/kubernetes/kubernetes/pull/126653
    - https://github.com/kubernetes/kubernetes/pull/126905
    - https://github.com/kubernetes/kubernetes/pull/129070
    - https://github.com/kubernetes/kubernetes/pull/128290
    - https://github.com/kubernetes/kubernetes/pull/128432
    - https://github.com/kubernetes/kubernetes/pull/128857
    - https://github.com/kubernetes/kubernetes/pull/128811
    - https://github.com/kubernetes/kubernetes/pull/129023
    - https://github.com/kubernetes/kubernetes/pull/129156
    - https://github.com/kubernetes/kubernetes/pull/129254
    - https://github.com/kubernetes/kubernetes/pull/124342
    - https://github.com/kubernetes/kubernetes/pull/124901
    - https://github.com/kubernetes/kubernetes/pull/125867
    - https://github.com/kubernetes/kubernetes/pull/126932
    - https://github.com/kubernetes/kubernetes/pull/127060
    - https://github.com/kubernetes/kubernetes/pull/127291
    - https://github.com/kubernetes/kubernetes/pull/127566
    - https://github.com/kubernetes/kubernetes/pull/127704
    - https://github.com/kubernetes/kubernetes/pull/128388
    - https://github.com/kubernetes/kubernetes/pull/128595
    - https://github.com/kubernetes/kubernetes/pull/128525
  - in kubernetes-sig
    - https://github.com/kubernetes-sigs/descheduler/pull/1463
    - https://github.com/kubernetes-sigs/descheduler/pull/1451
    - https://github.com/kubernetes-sigs/descheduler/pull/1445
    - https://github.com/kubernetes-sigs/jobset/pull/501
- Issues
  - https://github.com/kubernetes/kubernetes/issues/127746
  - https://github.com/kubernetes-sigs/descheduler/issues/1449
  - https://github.com/kubernetes/kubernetes/issues/127460
  - https://github.com/kubernetes/kubernetes/issues/97360
  - https://github.com/kubernetes/kubernetes/issues/118992

**Comment by pacoxu** [comment]
Big +1 

Thanks for your contributions.

**Comment by pohly** [comment]
:+1:

**Comment by jasonbraganza** [comment]
/assign

@zhifei92, thank you for all your contributions 🙂

I’ve created PR #5319 to add you to the Kubernetes Org(s). Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉
