### ISSUE TITLE
REQUEST: New membership for abuisine

### ISSUE THREAD

**Issue by abuisine** [kubernetes/org#535]
### GitHub Username
@abuisine

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ ] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rbenzair 
- @sieben 

### List of contributions to the Kubernetes project
- sig-docs-fr-owners

**Comment by rbenzair** [comment]
+1

**Comment by mrbobbytables** [comment]
I will add a +1, @abuisine is listed as both an approver/reviewer for the french translation team :) 
https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L148

**Comment by mrbobbytables** [comment]
@abuisine, thanks for helping kick start the French translations efforts :)

I've created PR #539  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
