### ISSUE TITLE
REQUEST: New membership for tizhou86

### ISSUE THREAD

**Issue by tizhou86** [kubernetes/org#54]
### GitHub Username
@tizhou86

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@k82cn 
@feiskyer 

### List of contributions to the Kubernetes project
- PR authored.
  - https://github.com/kubernetes/kubernetes/pull/67759
  - https://github.com/kubernetes/kubernetes/pull/67758
  - https://github.com/kubernetes/kubernetes/pull/67756
  - https://github.com/kubernetes/kubernetes/pull/67750
  - https://github.com/kubernetes/kubernetes/pull/67642
  - https://github.com/kubernetes/kubernetes/pull/59028
  - https://github.com/kubernetes/kubernetes/pull/53982
  - https://github.com/kubernetes/kubernetes/pull/53783
  - https://github.com/kubernetes/kubernetes/pull/50837
  - https://github.com/kubernetes/website/pull/5005

- Make better sig-cloud-provider.
  - https://github.com/kubernetes/community/pull/2374
  - https://github.com/kubernetes/community/issues/2594

**Comment by feiskyer** [comment]
+1 from me

**Comment by k82cn** [comment]
+1

**Comment by dims** [comment]
+1 from me

**Comment by cblecker** [comment]
Invite sent! Welcome to @kubernetes!
