### ISSUE TITLE
REQUEST: New membership for erikerlandson

### ISSUE THREAD

**Issue by erikerlandson** [kubernetes/org#540]
### GitHub Username
e.g. @erikerlandson

### Organization you are requesting membership in
e.g. @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @liyinan926 
- @foxish 

### List of contributions to the Kubernetes project
- co-chair of the Big Data SIG (transitioning to Big Data User Group)
- https://github.com/kubernetes/website/pull/9750 and https://github.com/kubernetes/website/issues/9078
- #525 and https://github.com/kubernetes/community/pull/3304

**Comment by foxish** [comment]
+1

**Comment by liyinan926** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @erikerlandson, thanks for spearheading the big data usergroup :)

I've created PR #548   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
