### ISSUE TITLE
REQUEST: New membership for bruceauyeung

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/org#542]
### GitHub Username
@bruceauyeung 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [√ ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [√ ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [√ ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [√ ] I am actively contributing to 1 or more Kubernetes subprojects
- [√ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [√ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zhangxiaoyu-zidif  
- @cblecker
- @xiangpengzhao  

### List of contributions to the Kubernetes project
- PRs reviewed / authored
all 25 merged PRs :
https://github.com/kubernetes/kubernetes/pull/69086
https://github.com/kubernetes/kubernetes/pull/46762
https://github.com/kubernetes/kubernetes/pull/46419
https://github.com/kubernetes/kubernetes/pull/41877
https://github.com/kubernetes/kubernetes/pull/41530
https://github.com/kubernetes/kubernetes/pull/41465
https://github.com/kubernetes/kubernetes/pull/40194
https://github.com/kubernetes/kubernetes/pull/40132
https://github.com/kubernetes/kubernetes/pull/39911
https://github.com/kubernetes/kubernetes/pull/39320
https://github.com/kubernetes/kubernetes/pull/39302
https://github.com/kubernetes/kubernetes/pull/39139
https://github.com/kubernetes/kubernetes/pull/38683
https://github.com/kubernetes/kubernetes/pull/38677
https://github.com/kubernetes/kubernetes/pull/38354
https://github.com/kubernetes/kubernetes/pull/37887
https://github.com/kubernetes/kubernetes/pull/37784
https://github.com/kubernetes/kubernetes/pull/37667
https://github.com/kubernetes/kubernetes/pull/37477
https://github.com/kubernetes/kubernetes/pull/37468
https://github.com/kubernetes/kubernetes/pull/36625
https://github.com/kubernetes/kubernetes/pull/36474
https://github.com/kubernetes/kubernetes/pull/36040
https://github.com/kubernetes/kubernetes/pull/35777
https://github.com/kubernetes/kubernetes/pull/35265

- Issues responded to
https://github.com/kubernetes/kubeadm/issues/1254
https://github.com/kubernetes/kubernetes/issues/54130
https://github.com/kubernetes/kubeadm/issues/174
https://github.com/kubernetes/kubernetes/issues/41127
https://github.com/kubernetes/kubeadm/issues/42
https://github.com/kubernetes/kubernetes/issues/35640
https://github.com/kubernetes/kubernetes/issues/34406

- SIG projects I am involved with
sig/kubeadm
sig/node
sig/network
sig/docs
sig/cli

**Comment by tanshanshan** [comment]
+1

**Comment by zhangxiaoyu-zidif** [comment]
+1 from me

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #616 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign

**Comment by justaugustus** [comment]
@bruceauyeung -- would you be able to find another sponsor as Christoph is out on vacation until the end of March?

**Comment by xiangpengzhao** [comment]
+1

**Comment by bruceauyeung** [comment]
@justaugustus i have got sponsor from @xiangpengzhao , PTAL

**Comment by mrbobbytables** [comment]
Thanks for adding your +1 @xiangpengzhao :)

With that, @bruceauyeung your org membership can be processed. I've created PR #625 to add you to the @kubernetes org. :D

Welcome!
