### ISSUE TITLE
REQUEST: New membership for stevesloka

### ISSUE THREAD

**Issue by stevesloka** [kubernetes/org#549]
### GitHub Username
@stevesloka

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timothysc 
- @dims 

### List of contributions to the Kubernetes project
- PRs
  - https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Astevesloka+
  - https://github.com/kubernetes/minikube/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Astevesloka+
- SIG projects I am involved with
  - conformance
  - sig-testing

**Comment by nikhita** [comment]
+1

**Comment by timothysc** [comment]
+1 from me.  

Steve will be working on testing-commons and conformance work  
/cc @spiffxp

**Comment by dims** [comment]
+1 from me!

**Comment by mrbobbytables** [comment]
@stevesloka, thank you for helping with all the conformance work :)

I've created PR #556   to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by justaugustus** [comment]
+1! :)
