### ISSUE TITLE
REQUEST: New membership for johnSchnake

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/org#557]
### GitHub Username
@johnSchnake

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timothysc 
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   - https://github.com/kubernetes/kubernetes/pull/74731
   - https://github.com/kubernetes/kubernetes/pull/68792
   - https://github.com/kubernetes/kubernetes/pull/68753
- Issues responded to
   - https://github.com/kubernetes/kubernetes/pull/74808
- SIG projects I am involved with
    - conformance
    - sig-testing

**Comment by dims** [comment]
+1 from me!

**Comment by timothysc** [comment]
+1 john will be working on testing-commons and the conformance work.

**Comment by mrbobbytables** [comment]
@johnSchnake, thank you for helping with the testing and conformance work :)

I've created PR #561 to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
