### ISSUE TITLE
Keep getting kicked out of cri-o-maintainers list

### ISSUE THREAD

**Issue by sboeuf** [kubernetes/org#559]
### Organization or repository
kubernetes-sigs/cri-o

### Users affected
@sboeuf

### Describe the issue
@mrunalp has been adding me as a `cri-o-maintainers`, but every time, a few hours later, I am removed from the list, with the following message sent by email:
```
You’ve been removed from the cri-o-maintainers team on the Kubernetes SIGs organization.


Cheers & Octocats,

GitHub Support
```

**Comment by mrunalp** [comment]
@rhatdan is also getting affected by this.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/org/pull/560.

Teams are handled via a config today and they get updated each time the postsubmit runs. If someone is added manually to a team, they will be removed on each such postsubmit run.

@sboeuf @rhatdan Once https://github.com/kubernetes/org/pull/560 merges and the postsubmit runs, you should be added to the team for good. :)

**Comment by sboeuf** [comment]
Thank you @nikhita :+1:
