### ISSUE TITLE
REQUEST: Creation of KEP 14 repos

### ISSUE THREAD

**Issue by sttts** [kubernetes/org#56]
To implement [KEP 14](https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/0014-20180707-componentconfig-api-types-to-staging.md), we need a couple of repos.

### New Repo
- ~~cloud-controller-manager~~
- kube-controller-manager
- kube-scheduler
- kubelet
- kube-proxy

### Which Organization should it reside
kubernetes

Note that these are "staging repositories", i.e. they are published by the https://github.com/kubernetes/publishing-bot and therefore must be in the `kubernetes` org.

### Who should be provided access to this repository

We need **admin access for the `stage-bots` team**, compare:

![bildschirmfoto 2018-09-03 um 13 54 46](https://user-images.githubusercontent.com/730123/45020493-70f73200-b02f-11e8-9a2e-797a1e9a2814.png)

We need branch settings like:

![bildschirmfoto 2018-09-03 um 13 55 26](https://user-images.githubusercontent.com/730123/45020616-c3d0e980-b02f-11e8-8e00-95e8e8f95e37.png)

### Approvals

KEP 14: https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/0014-20180707-componentconfig-api-types-to-staging.md

### Additional context for request

The staging repositories have been created [in the staging/ directory of the k/k repo](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io), all approved by top-level approvers @jbeda and @thockin.

/cc @luxas @stewart-yu

**Comment by cblecker** [comment]
@sttts Has sig-arch approved of new core repos? Was there a meeting agenda item or a mailing list thread where they do?

cc: @jdumars @bgrant0607

**Comment by cblecker** [comment]
Looks like this is slated for discussion in sig-arch on Thursday
https://github.com/kubernetes/community/issues/2627

**Comment by sttts** [comment]
Sig-arch approved them: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-architecture/x_-L4dlwbeU/qwlEd64kBgAJ

**Comment by spiffxp** [comment]
/assign
I believe this is done but I'll leave this open to confirm since this is staging

**Comment by spiffxp** [comment]
It's also unclear to me whether/where these repos should fall in sigs.yaml?

**Comment by stewart-yu** [comment]
thanks, but seems no need to create repo for `cloud-controller-manager` now? @spiffxp :grinning:
/cc @sttts

**Comment by GeorgeGuo2018** [comment]
https://github.com/kubernetes/kube-controller-manager
this repo is empty now, what should i do if my older projects referred package from this repo?
Any reply would be appreciated,thx.

**Comment by sttts** [comment]
> thanks, but seems no need to create repo for cloud-controller-manager now.

@stewart-yu thanks for the correction. Yes, we keep those types in the cmd package because the future of the binary is not clear.

**Comment by sttts** [comment]
> this repo is empty now, what should i do if my older projects referred package from this repo?
> Any reply would be appreciated,thx.

@GeorgeGuo2018 I will update github.com/kubernetes/publishing-bot and it will fill that repo.

Which "older projects" do you refer to?

**Comment by sttts** [comment]
@spiffxp we have the OWNERS files in there. Isn't that enough? Listing those repos in sigs.yaml in addition sounds equivalent.

**Comment by sttts** [comment]
@spiffxp as @stewart-yu correctly noted, cloud-controller-manager is not used. You can delete it again.

**Comment by spiffxp** [comment]
@sttts every other repo that comes out of staging is listed in sigs.yaml as belonging to a sig, egs: 

sig-api-machinery has this entry
```
- name: universal-machinery # i.e., both client and server
      owners:
      - https://raw.githubusercontent.com/kubernetes/apimachinery/master/OWNERS
      - https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/src/k8s.io/apimachinery/OWNERS
```

sig-architecture has this entry
```
- name: api
      owners:
      - https://raw.githubusercontent.com/kubernetes/api/master/OWNERS
      - https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/src/k8s.io/api/OWNERS
```

I don't know if the intent is to move to a world where each component is owned by a different sig, eg: 
- sig-node owns kubelet
- sig-network owns kube-proxy
- sig-apps owns kube-controller-manager
- sig-api-machinery owns kube-apiserver
- sig-scheduling owns kube-scheduler

or, if sig-archtecture owns the root of each component, with individual sigs owning packages within (eg: sig-architecture owns api, but sig-apps owns the workload apis)

**Comment by sttts** [comment]
@spiffxp I wasn't aware that we link OWNERS files there. So of course the new repos belong into that file :+1:

**Comment by spiffxp** [comment]
Current status:
- I removed cloud-controller-manager
- The other repos look to be synced by publishing-bot now
- I have yet to confirm that the repos have been added to sigs.yaml

**Comment by spiffxp** [comment]
I chatted with @sttts offline, the repo descriptions have been changed

Just waiting for a sigs.yaml PR to close this out

**Comment by luxas** [comment]
I don't know either whether we want the specialized SIG (e.g. node) to own all of the k8s.io/kubelet repo or if we want it to own e.g. `pkg/` and `cmd/` only?
That really dictates the structure of the sigs.yaml PR. Any preferences?

**Comment by spiffxp** [comment]
Having sig-arch own root and specialized sigs own different packages was one of the suggestions I made above.  I have no strong preference other than an option get chosen.  I will ask the sig-arch mailing list

**Comment by spiffxp** [comment]
[kubernetes-sig-arch@ thread](https://groups.google.com/d/msg/kubernetes-sig-architecture/2Fob-097rA4/RVAEWuAvCAAJ)

**Comment by spiffxp** [comment]
So far I have received two responses, both of which seem to suggest the sig-arch root / sig-foo subdirs approach.

**Comment by luxas** [comment]
The final piece of this was fixed with https://github.com/kubernetes/kubernetes/pull/70453, closing
/close
