### ISSUE TITLE
Convert GitHub team maintainers to members

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/org#563]
Now that we automate the management of GitHub teams (https://github.com/kubernetes/org/issues/336), it is confusing when people try to use GitHub's UI to manually manage teams, only to have their changes reverted (eg: https://github.com/kubernetes/org/issues/559)

While we wait for docs (https://github.com/kubernetes/community/issues/3102) I believe we should move everyone to being a regular team member, and encourage use of PR's against this repo for GitHub team management

That said, one fun little wrinkle I discovered in https://github.com/kubernetes/org/pull/522 is that GitHub Owners need to remain team maintainers

/kind cleanup
/priority important-soon

**Comment by spiffxp** [comment]
[Notified kubernetes-dev@](https://groups.google.com/forum/#!topic/kubernetes-dev/WtvHtt2lR1w)

**Comment by nikhita** [comment]
I'll update the docs and config.

/assign

**Comment by rlenferink** [comment]
> I'll update the docs and config.
> 
> /assign

While we're at it with PR https://github.com/kubernetes/org/pull/546, should I update the other `sig-docs` teams as well to 'convert' maintainers to members?

**Comment by nikhita** [comment]
> @nikhita While we're at it with PR #546, should I update the other sig-docs teams as well to 'convert' maintainers to members?

Sure, that would be good. :)

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/org/pull/566 for the config part.

I'll add the docs later this week.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/community/pull/3368 for the docs.

**Comment by nikhita** [comment]
The config part has now merged: https://github.com/kubernetes/org/pull/566. All existing (non-admin) team maintainers have been converted to members and a test has been added to check that non-admins are not listed as maintainers.

Also notified k-dev that this is done: https://groups.google.com/d/msg/kubernetes-dev/WtvHtt2lR1w/TMiaTjESCAAJ

**Comment by cblecker** [comment]
Take two: https://github.com/kubernetes/org/pull/849

**Comment by justaugustus** [comment]
This is now complete, right?

**Comment by nikhita** [comment]
Yes! :tada: 

/close
