### ISSUE TITLE
REQUEST: New membership for wk8

### ISSUE THREAD

**Issue by wk8** [kubernetes/org#567]
### GitHub Username
@wk8

### Organizations you are requesting membership in
@kubernetes 
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ddebroy 
- @michmike 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Awk8+
- https://github.com/kubernetes-sigs/windows-gmsa/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Awk8+

**Comment by ddebroy** [comment]
+1  
I strongly support Jean's membership for the work he has done during the v1.14 release in the SIG-Windows space around the GMSA feature.

**Comment by michmike** [comment]
+1
thanks for your contributions @wk8

**Comment by mrbobbytables** [comment]
@wk8, thank you for everything you've done for sig-windows :) 

I've created PR #575   to add you to both the  @Kubernetes and @kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign

**Comment by wk8** [comment]
Thank you @mrbobbytables ! :)

(I'm sure I'm not the first to tell you, but I like your handle; well done, sir)
