### ISSUE TITLE
REQUEST: New membership for losipiuk

### ISSUE THREAD

**Issue by losipiuk** [kubernetes/org#57]
### GitHub Username
@losipiuk

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @MaciekPytel 
- @feiskyer 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   * kubernetes/kubernetes: https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Aclosed+is%3Apr+author%3Alosipiuk+
   * kubernetes/autoscaler: https://github.com/kubernetes/autoscaler/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed++author%3Alosipiuk
- Issues responded to:
   * kubernets/autoscaler: https://github.com/kubernetes/autoscaler/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Alosipiuk+
- SIG projects I am involved with
   * mostly sig-autoscaling. I did some work within sig-scheduling

**Comment by MaciekPytel** [comment]
+1 for @losipiuk (based on his many contributions to and active participation in Cluster Autoscaler development)

**Comment by feiskyer** [comment]
+1 for @losipiuk (based on his contributions to k/k and cluster autoscaler)

**Comment by spiffxp** [comment]
/assign
welcome!

invite sent manually, will close via PR

**Comment by losipiuk** [comment]
Thanks! And hello to everyone.
