### ISSUE TITLE
Give bchilds admin access for kubernetes-csi/external-resizer repo

### ISSUE THREAD

**Issue by gnufied** [kubernetes/org#571]
### Organization or repository
e.g. https://github.com/kubernetes-csi/external-resizer

### Users affected
childsb

### Describe the issue
@childsb  is sig-storage lead with @saad-ali , he has admin access to other repository not just this one. It seems like an oversight and should be fixed.

**Comment by nikhita** [comment]
@gnufied or @childsb could you create a PR to add the username here? That should do it :)

https://github.com/kubernetes/org/blob/8f65c91b1f2507a1e21e0b5db7d485fa2d286d96/config/kubernetes-csi/org.yaml#L308-L312

**Comment by gnufied** [comment]
Here we go - https://github.com/kubernetes/org/pull/572
