### ISSUE TITLE
REQUEST: Creation of cli-runtime and sample-cli-plugin repos

### ISSUE THREAD

**Issue by soltysh** [kubernetes/org#58]
To implement https://github.com/kubernetes/features/issues/581 and https://github.com/kubernetes/features/issues/579 we need 2 new repos. One contains library functions for writing plugins, the other shows how to use the first and write a sample CLI plugin.

### New Repo, or migrate existing
* cli-runtime
* sample-cli-plugin

### Which Organization should it reside
kubernetes

### Who should be provided access to this repository
We need admin access for the stage-bots team, compare:
![](https://user-images.githubusercontent.com/730123/45020493-70f73200-b02f-11e8-9a2e-797a1e9a2814.png)
We need branch settings like:
![](https://user-images.githubusercontent.com/730123/45020616-c3d0e980-b02f-11e8-8e00-95e8e8f95e37.png)

### Approvals
https://github.com/kubernetes/community/blob/master/keps/sig-cli/0024-kubectl-plugins.md
https://github.com/kubernetes/kubernetes/pull/67658
https://github.com/kubernetes/kubernetes/pull/67938

/cc @juanvallejo @pwittrock @seans3

**Comment by cblecker** [comment]
@soltysh Has sig-arch approved of new core repos? Was there a meeting agenda item or a mailing list thread where they do?

cc: @jdumars @bgrant0607

**Comment by soltysh** [comment]
@cblecker I've started [this thread](https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/7UcXE9b0lQE) but haven't heard back, I assumed since there were no objections and both PRs merged (with top-level approval) I've created this issue.

**Comment by pohly** [comment]
Note that having references to the k8s.io/cli-runtime package in the upcoming Kubernetes source will make it impossible to use packages like k8s.io/pkg/kubelet in other projects because tools like "go get" or "dep" don't know where to find the new package. I'm running into that when trying to use test/e2e/framework, which uses pkg/kubelet.

**Comment by soltysh** [comment]
@pohly the only reason for that is that we haven't published these repos yet, I just got approval so we will do so soon.

@cblecker just got approval from @bgrant0607 see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-architecture/7UcXE9b0lQE/gPkl3BdhBgAJ

**Comment by spiffxp** [comment]
@soltysh can you add these to sigs.yaml under the appropriate subproject (or make new subproject entries for them if necessary?)

will leave this open waiting for that PR, and to make sure the staging PR merges

**Comment by spiffxp** [comment]
Current status:
- The repos look to be synced by publishing-bot now

@soltysh is there anything more specific you’d like the repo descriptions to be set to? I set them to the issue asking for their request out of habit, but assume it to be temporary

**Comment by soltysh** [comment]
@spiffxp thanks!
