### ISSUE TITLE
REQUEST: New membership for easeway

### ISSUE THREAD

**Issue by easeway** [kubernetes/org#581]
### GitHub Username
@easeway

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @davidopp
- @tallclair

### List of contributions to the Kubernetes project
- wg-multitenancy: https://docs.google.com/document/d/1U8RQQmTUjxgMZY05HG2f7b3KsB94BhK4Ko6aWbLNXcc/edit?ts=5c748d98
- https://github.com/kubernetes/org/issues/528

**Comment by davidopp** [comment]
+1

**Comment by mrbobbytables** [comment]
@easeway I hate to be a stickler, but do you happen to have another potential sponsor? Both @davidopp  and @tallclair  are employed by Google, and sponsors must be from separate member organizations per the [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

Thanks!

**Comment by tashimi** [comment]
+1 

@mrbobbytables I work at VMware and am the co-chair for the multitenancy working group and whole heartedly am in favor of @easeway’s application 😊

**Comment by nikhita** [comment]
@tashimi thank you!

@easeway thank you for your contributions thus far! :tada: 

I have added you and @davidopp to kubernetes-sigs + added both of you to the teams for the k-sigs/multi-tenancy repo in https://github.com/kubernetes/org/pull/576. If someone could lgtm that PR, that'd be awesome. :)

**Comment by nikhita** [comment]
Fixed by https://github.com/kubernetes/org/pull/576.

@easeway Welcome to @kubernetes-sigs! :tada: I have also added you to the multi-tenancy-admins and multi-tenancy-maintainers teams. Once you accept the org invite, you should automatically get added both. :)

/close
