### ISSUE TITLE
REQUEST: New membership for @krmayankk

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/org#584]
GitHub Username
@krmayankk 

Organization you are requesting membership in
kubernetes-milestone-maintainers

Requirements
  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
  I have enabled 2FA on my GitHub account (https://github.com/settings/security)
  I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
  I am actively contributing to 1 or more Kubernetes subprojects
  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
Sponsors
I'm already an org member

List of contributions to the Kubernetes project
- Acting as Bug Triage shadow for release 1.14. I need to be able to modify milestone info on PRs and Issues.
- Made many PR and feature proposals

**Comment by nikhita** [comment]
@krmayankk  can you create a PR to add yourself here? :) https://github.com/kubernetes/org/blob/9d184605dc1868781769becf605321d18407dddc/config/kubernetes/sig-release/teams.yaml#L2

**Comment by krmayankk** [comment]
https://github.com/kubernetes/org/pull/585 @nikhita thanks :-)

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/org/pull/585.

/close
