### ISSUE TITLE
REQUEST: New membership for DanyC97

### ISSUE THREAD

**Issue by DanyC97** [kubernetes/org#589]
### GitHub Username
@DanyC97

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Bradamant3 
- @Rajakavitha1 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+involves%3ADanyC97+
- Issues responded to
https://github.com/kubernetes/website/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+involves%3Adanyc97
- SIG projects I am involved with

  sig/docs

**Comment by Bradamant3** [comment]
+1 confirmation of sponsorship

**Comment by DanyC97** [comment]
wow, that was incredible fast @Bradamant3 , much thanks !

**Comment by Rajakavitha1** [comment]
+1 confirmation of sponsorship

**Comment by mrbobbytables** [comment]
Hey there @DanyC97, thank you for all your help with the Kubernetes website! :)

I've created PR #593  to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by DanyC97** [comment]
thank you kindly @mrbobbytables

**Comment by DanyC97** [comment]
@mrbobbytables i just checked and i haven't received any membership invitation, am i missing something ?

**Comment by nikhita** [comment]
@DanyC97 you should be able to accept the invite by visiting https://github.com/kubernetes.

**Comment by DanyC97** [comment]
spot on @nikhita , many thanks !
