### ISSUE TITLE
REQUEST: New membership for davidewaton

### ISSUE THREAD

**Issue by davidewatson** [kubernetes/org#59]
### GitHub Username
@davidewatson

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mattfarina 
- @dims  

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes-sigs/cluster-api/pull/408
  - https://github.com/kubernetes-sigs/cluster-api/pull/462
  - https://github.com/kubernetes-sigs/cluster-api/pull/481
  - https://github.com/kubernetes/kubernetes/pull/46052
  - https://github.com/helm/charts/pull/3800#issuecomment-376296542 (previously kubernetes/contrib or similar)
- Issues responded to
  - https://github.com/kubernetes-sigs/cluster-api/issues/252
  - https://github.com/kubernetes-sigs/cluster-api/issues/383
- SIG projects I am involved with: https://github.com/kubernetes-sigs/cluster-api

**Comment by dims** [comment]
+1 from me!

**Comment by mattfarina** [comment]
+1 from me as well.

**Comment by spiffxp** [comment]
/assign
invites sent manually, will close this via PR
