### ISSUE TITLE
REQUEST: New membership for aditya-konarde

### ISSUE THREAD

**Issue by aditya-konarde** [kubernetes/org#590]
### GitHub Username
@aditya-konarde
### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@nikhita 
@mkumatag 
@dims 

### List of contributions to the Kubernetes project
Community work in general. I co-organize the Kubernetes BLR meetup, and actively try to help people on slack around Kubernetes and Prometheus. I am also a regular participant for SIG-Instrumentation

**Comment by nikhita** [comment]
+1 from my side.
 Aditya has expressed an interest in serving as a slack admin in an underrepresented time zone (APAC).

**Comment by dims** [comment]
+1 from me.!

**Comment by mrbobbytables** [comment]
@aditya-konarde Thanks for stepping up to help with slack moderation :)

I've created PR #593  to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
