### ISSUE TITLE
REQUEST: New membership for a1h8

### ISSUE THREAD

**Issue by a1h8** [kubernetes/org#594]
### GitHub Username
@a1h8

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yastij 
- @lledru 

### List of contributions to the Kubernetes project
- join the docs-fr translation team

**Comment by lledru** [comment]
+1
Huge welcome !

**Comment by yastij** [comment]
+1

Thanks for the help on this

**Comment by mrbobbytables** [comment]
Hey there @a1h8, thank you for helping with the french translations efforts :)

I've created PR #600  to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
