### ISSUE TITLE
REQUEST: New membership for tashimi

### ISSUE THREAD

**Issue by tashimi** [kubernetes/org#595]
### GitHub Username
tashimi

### Organization you are requesting membership in
Kubernetes 
Kubernetes-SIG 

### Requirements
- [x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x ] I am actively contributing to 1 or more Kubernetes subprojects
- [x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @michelleN 
- @justaugustus 

### List of contributions to the Kubernetes project
- SIG projects I am involved with: co-chair for multi-tenancy working group

**Comment by justaugustus** [comment]
+1!

**Comment by nikhita** [comment]
+1

**Comment by mrbobbytables** [comment]
@tashimi thanks for helping with the multi-tenancy wg :)

I've created PR #600  to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
