### ISSUE TITLE
REQUEST: New membership for JoelSpeed

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes/org#596]
### GitHub Username
@JoelSpeed

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @munnerz 
- @castrojo

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/autoscaler/pull/280
  - https://github.com/kubernetes/kubernetes/pull/65477
  - https://github.com/kubernetes-sigs/controller-runtime/pull/132
  - https://github.com/kubernetes-sigs/controller-runtime/pull/163
  - https://github.com/kubernetes-sigs/controller-runtime/pull/198
  - https://github.com/kubernetes-sigs/controller-runtime/pull/238
  - https://github.com/kubernetes-sigs/controller-runtime/pull/351
- Issues responded to
  - https://github.com/kubernetes/autoscaler/issues/209
  - https://github.com/kubernetes/autoscaler/issues/278
  - https://github.com/kubernetes-sigs/kubebuilder/issues/265
  - https://github.com/kubernetes-sigs/controller-runtime

- SIG projects I am involved with
  - Kubernetes Office Hours [Contributor Experience]
  - https://github.com/kubernetes-sigs/controller-runtime

**Comment by munnerz** [comment]
+1 😄

**Comment by castrojo** [comment]
+1 from me as well!

**Comment by droot** [comment]
+1 (@JoelSpeed has made some very important contributions to controller-runtime projects and has also been an early adopters/power-user of the project). Thanks @JoelSpeed.

**Comment by mrbobbytables** [comment]
I know its not needed at this point, but I'll toss my own +1 in the mix too. :P

/pony yay

**Comment by nikhita** [comment]
+1 :tada: 

(side note: why is the "yay" pony always so sarcastic :P)

**Comment by mrbobbytables** [comment]
@JoelSpeed  thanks for all your contributions and help with the project so far. \o/

I've created PR #600  to add you to the @Kubernetes and @kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notifications from both of them.

Welcome to @kubernetes! 🎉

/assign

**Comment by JoelSpeed** [comment]
Thanks @mrbobbytables and all those who +1'd, really appreciate it 😍
