### ISSUE TITLE
Steering committee acls on the org.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/org#6]
Steering committee members should have admin acls on the org to move repos and add members.

**Comment by bgrant0607** [comment]
Why do SC members need to do this, as opposed to the github admins?

**Comment by timothysc** [comment]
If we delegate to this group I suppose we just route issues to here, but it makes this subproject a blocking resource on execution of things like: 

- transferring repos in (kuberenetes-sigs)
- sunsetting repos (kubernetes-incubator) 
...

**Comment by spiffxp** [comment]
That's exactly the intent of this subproject, and I feel like this was sufficiently communicated to steering ahead of time.

**Comment by cblecker** [comment]
Hey Tim! As Aaron said, the intent of the subproject was to delegate these responsibilities away from "someone from steering" or "someone from contribex" to a small, defined team of volunteers. This avoids tying these permissions to an unrelated role. For example, it isn't a hard requirement of someone elected to steering to be able to transfer github repos, even though many of our current sitting members would be capable of doing this.

We have defined [processes](https://github.com/kubernetes/community/blob/master/github-management/opening-a-request.md) and [SLOs](https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#slos) to handle the types of requests you mention.

Some background threads that included the steering committee:
https://groups.google.com/a/kubernetes.io/d/msg/steering/4hzdh3Ulggk/n-NxuaVxCgAJ
https://groups.google.com/a/kubernetes.io/d/msg/steering/dgJ_ETTRI-Y/i987N9z1AgAJ
https://groups.google.com/a/kubernetes.io/d/msg/steering/3eiJ0Dz-1jE/Yd3mLcFyBgAJ

If you have any other questions or concerns, we'd be happy to address them :)

**Comment by cblecker** [comment]
cc: @kubernetes/steering-committee @kubernetes/owners

**Comment by philips** [comment]
I am OK with delegating admin creds to this sub project. It seems @bgrant0607 and @spiffxp are comfortable as well.

@timothysc are you concerned about not having an escape hatch for the steering committee? I would be OK with always reserving one admin seat for steering committee members similar to the Gsuite situation.

**Comment by bgrant0607** [comment]
@philips This is in line with our general direction of granting github privileges according to need to do the job as opposed to status on the project, similar to revoking direct repo write access of "maintainers". I'm also happy to not be the de facto github admin any longer. :-)  

Contributor Experience is steadily automating more and more operations, which gives us more control, auditability, and consistency. 

It also should help to have admins who stay on top of github feature and policy changes and to field requests from contributors for various changes or support.

**Comment by timothysc** [comment]
I'm fine with it, but the docs on repo requests should be updated to reflect a process change.
We should also define the policy for sunsetting.

**Comment by philips** [comment]
@cblecker those are great docs and I think all of the bases are covered from who is on the team to their responsibilities.

**Comment by timothysc** [comment]
Isn't there a process doc that @brendandburns created for requesting a repo from steering?

**Comment by cblecker** [comment]
I think that document became https://git.k8s.io/community/github-management/kubernetes-repositories.md

**Comment by timothysc** [comment]
@cblecker yup that's the one, we should update that doc to link to the appropriate templates - https://github.com/kubernetes/org/issues/new?template=repo-create.md  
+ Remove 

Then close this issue once it's complete.

**Comment by cblecker** [comment]
/assign

Sounds good. Will add something to those docs 👍
