### ISSUE TITLE
Migrate kubernetes-incubator/cri-o to kubernetes-sigs/cri-o

### ISSUE THREAD

**Issue by runcom** [kubernetes/org#60]
### New Repo, or migrate existing

migrate existing

### Requested name for new repository
cri-o

### Which Organization should it reside
kubernetes-sigs

### Who should be provided access to this repository

@mrunalp 
@runcom

### Approvals

Please include links to the approvals (meeting minutes, e-mail thread, etc)

@dchen1107 approval https://github.com/kubernetes-incubator/cri-o/issues/1639#issuecomment-403896946
@derekwaynecarr  approval https://github.com/kubernetes-incubator/cri-o/issues/1639#issuecomment-403897506

https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.vmu9c89131nt

### Additional context for request

/assign @spiffxp
/cc @mrunalp @derekwaynecarr

**Comment by spiffxp** [comment]
/assign
I will take care of this tomorrow when folks are around in case this disrupts anything

@mrunalp @runcom can you two file issues to be added as org members to kubernetes-sigs so I can give you the appropriate level of access?  you don't need to worry about the full checklist if you're already members of kubernetes, just say that

**Comment by spiffxp** [comment]
Repo has been moved: https://github.com/kubernetes-sigs/cri-tools

The following teams were created
- https://github.com/orgs/kubernetes-sigs/teams/cri-tools-admins/members
- https://github.com/orgs/kubernetes-sigs/teams/cri-tools-maintainers/members

The following users were invited as team maintainers for both teams: 
- @mrunalp
- @runcom 

The following collaborators were removed:
- write @openshift-ci-robot

If you had read access, don't worry, the repo is public, so you don't need it.

If you had write access, please consider filing an issue to join the kubernetes-sigs org, and ask to be added to the cri-o-maintainers team.

This needs a corresponding change to sigs.yaml

**Comment by spiffxp** [comment]
The following team used to have admin access to https://github.com/kubernetes-incubator/cri-o:
- https://github.com/orgs/kubernetes-incubator/teams/admins-cri-o

It has been removed

The members from this team who have not been added to the new teams are:
- @derekwaynecarr 
- @sarahnovotny 
- @vishh 

Please file an issue if you feel you have been removed in error

**Comment by spiffxp** [comment]
The following team used to have write access to https://github.com/kubernetes-incubator/cri-o:
- https://github.com/orgs/kubernetes-incubator/teams/maintainers-cri-o

It has been removed

The members from this team who have not been added to the new teams are:
- @cyphar
- @derekwaynecarr 
- @feiskyer 
- @nalind
- @rhatdan
- @sameo
- @vishh 
- @yujuhong 

Please file an issue if you feel you have been removed in error

**Comment by spiffxp** [comment]
/close
OK I'm calling this done, if there are any issues please follow up here
