### ISSUE TITLE
REQUEST: New membership for srampal

### ISSUE THREAD

**Issue by srampal** [kubernetes/org#603]
### GitHub Username
@srampal

### Organization you are requesting membership in
@kubbernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @davidopp  
- @tashimi 

### List of contributions to the Kubernetes project
- Strongly involved in driving architecture, docs and code for new wg-multitenancy work items + participation in sig-network, sig-auth and related communities like openshift

**Comment by tashimi** [comment]
+1!

**Comment by davidopp** [comment]
+1

**Comment by mrbobbytables** [comment]
@srampal, thanks for helping with wg-multitenancy :)

I've created PR #607  to add you to the @Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

/pony pie
(for π day)
