### ISSUE TITLE
REQUEST: New membership for ltupin

### ISSUE THREAD

**Issue by ltupin** [kubernetes/org#608]
### GitHub Username
@ltupin

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lledru 
- @rekcah78

### List of contributions to the Kubernetes project
- SIG-kubespray
- SIG-Docs: French.

**Comment by rekcah78** [comment]
+1

**Comment by lledru** [comment]
+1 for docs-fr translation effort!

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #616 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign

**Comment by ltupin** [comment]
Thx @justaugustus
