### ISSUE TITLE
REQUEST: New membership for @mauilion

### ISSUE THREAD

**Issue by mauilion** [kubernetes/org#609]
### GitHub Username
@mauilion

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman
- @justaugustus 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/71629
https://github.com/kubernetes/kubernetes/pull/71540
https://github.com/kubernetes/kubernetes/pull/63408
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/66979

- SIG projects I am involved with
sig-cluster-lifecycle specifically kubeadm.
sig-contribx I will be moderating slack and potentially kubernetes-dev
sig-network answer questions and help in slack.
sig-auth answer questions and help in slack.

**Comment by justaugustus** [comment]
An enthusiastic +1 for Duffie's membership!

**Comment by parispittman** [comment]
what @justaugustus said - +1

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #616 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
