### ISSUE TITLE
REQUEST: New membership for parispittman

### ISSUE THREAD

**Issue by parispittman** [kubernetes/org#61]
### GitHub Username
parispittman

### Organization you are requesting membership in
kubernetes/sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
cblecker
spiffxp

### List of contributions to the Kubernetes project
co-chair of contribex, mentoring, events, communication and many other k/community related subprojects as an owner/approver/or reviewer.

**Comment by spiffxp** [comment]
/assign
I'll assume you mean kubernetes-sigs

**Comment by spiffxp** [comment]
invite sent manually, leaving open until I PR
