### ISSUE TITLE
REQUEST: New membership for feloy

### ISSUE THREAD

**Issue by feloy** [kubernetes/org#611]
### GitHub Username
@feloy

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sieben
- @lledru

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/website/pull/13142
  - https://github.com/kubernetes/website/pull/13059
  - https://github.com/kubernetes/website/pull/13058
  - https://github.com/kubernetes/website/pull/12863
  - https://github.com/kubernetes/website/pull/12803
  - https://github.com/kubernetes/website/pull/13126
  - https://github.com/kubernetes/website/pull/12987
  - https://github.com/kubernetes-sigs/kustomize/pull/464
- Issues responded to
- SIG projects I am involved with
  - docs-fr translation team
  - kustomize
  - kubebuilder (https://conferences.oreilly.com/velocity/vl-eu-2018/public/schedule/detail/71703)

**Comment by lledru** [comment]
+1 !! :D

**Comment by sieben** [comment]
+1

**Comment by mrbobbytables** [comment]
@feloy, thank you for all your help with the french translations efforts! :)

I've created PR #620 to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
