### ISSUE TITLE
REQUEST: New membership for awesomenix

### ISSUE THREAD

**Issue by awesomenix** [kubernetes/org#612]
### GitHub Username
@awesomenix

### Organization you are requesting membership in
* kubernetes
* kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @tariq1890 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/52
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/78
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/136
- SIG projects I am involved with
https://github.com/kubernetes-sigs/cluster-api-provider-azure
https://github.com/kubernetes-sigs/cluster-api

**Comment by tariq1890** [comment]
Having worked with @awesomenix for close to a year, It brings me great joy to recommend him to the `kubernetes-sigs` org. He has been very active in the `cluster-api-provider-azure` project and has contributed many valuable enhancements to cluster-api azure provider.

**Comment by justaugustus** [comment]
+1! :)

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #616 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
