### ISSUE TITLE
REQUEST: New membership for @juan-lee

### ISSUE THREAD

**Issue by juan-lee** [kubernetes/org#613]
### GitHub Username
@juan-lee

### Organization you are requesting membership in
- kubernetes
- kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @tariq1890 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/51
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/136
- SIG projects I am involved with
https://github.com/kubernetes-sigs/cluster-api-provider-azure
https://github.com/kubernetes-sigs/cluster-api

**Comment by justaugustus** [comment]
+1! :)

**Comment by tariq1890** [comment]
A Big +1 from me :). Juan-Lee has been leading all of the cluster-api efforts in the Microsoft front.

**Comment by mrbobbytables** [comment]
@juan-lee, thank you for all your contributions to the cluster-api and azure provider! :)

I've created PR #620  to add you to both the @kubernetes and @kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign
