### ISSUE TITLE
REQUEST: New membership for vllry

### ISSUE THREAD

**Issue by vllry** [kubernetes/org#614]
### GitHub Username
@vllry

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @thockin 
- @nikhita 

### List of contributions to the Kubernetes project
- Actively involved in sig-network (meetings, Slack discussions, etc). Becoming involved in sig-scheduling and sig-architecture.
- [Added a missing e2e test](https://github.com/kubernetes/kubernetes/pull/72561), and identified that Kubernetes had [regressed in the absence of a test](https://github.com/kubernetes/kubernetes/pull/72534)
- [Did some tiny GCE e2e test cleanup](https://github.com/kubernetes/kubernetes/pull/72092)
- Participating in other ongoing tasks, like [adding scheduling priority class options](https://github.com/kubernetes/kubernetes/issues/67671)
- Participate in casual k/k bug triage, run a [tacky GitHub bot](https://github.com/athenabot/k8s-issues) to help label uncategorized issues.

**Comment by mrbobbytables** [comment]
Big +1 Here :D 

/pony party

**Comment by castrojo** [comment]
+1!

**Comment by jeefy** [comment]
+1!!!

**Comment by nikhita** [comment]
+1000!!! 

/meow space

**Comment by justaugustus** [comment]
+1!!

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #616 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign

**Comment by bsalamat** [comment]
Late to the party, but +1 from me too!
