### ISSUE TITLE
REQUEST: New membership for @MAKOSCAFEE

### ISSUE THREAD

**Issue by MAKOSCAFEE** [kubernetes/org#619]
### GitHub Username
@MAKOSCAFEE

### Organization you are requesting membership in
- kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jimangel 
- @zparnold 

### List of contributions to the Kubernetes project
- PRs reviewed / authored- 
    - https://github.com/kubernetes/website/pull/12594
    - https://github.com/kubernetes/website/pull/12584
    - https://github.com/kubernetes/website/pull/12397
    - https://github.com/kubernetes/community/pull/2713
    - https://github.com/kubernetes/community/pull/2710
- Issues responded to    
    - https://github.com/kubernetes/enhancements/issues/596
    - https://github.com/kubernetes/website/issues/12389
    - https://github.com/kubernetes/enhancements/issues/603
    - https://github.com/kubernetes/enhancements/issues/625
    - https://github.com/kubernetes/community/issues/2599
    - https://github.com/kubernetes/community/issues/2599
- SIG projects I am involved with
    - Docs shadow for 1.13 release
    - Docs shadow for 1.14 release

**Comment by zparnold** [comment]
+1

**Comment by jimangel** [comment]
+1 @MAKOSCAFEE and I have worked together on the last two releases for #sig-docs (1.13 and 1.14).

**Comment by mrbobbytables** [comment]
@MAKOSCAFEE Thanks for helping with the release process and being a docs shadow! :)

I've created PR #620  to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
