### ISSUE TITLE
REQUEST: New membership for RA489

### ISSUE THREAD

**Issue by RA489** [kubernetes/org#621]
**GitHub Username**

@RA489

**Organization you are requesting membership in**

@kubernetes

**Requirements**

- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x]  I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Sponsors**

- @rosti 
- @yagonobre 

**List of contributions to the Kubernetes project**

- PRs merged / authored 
https://github.com/search?p=1&q=is%3Apr+author%3Ara489+is%3Amerged&type=Issues

- SIG projects I am involved with
   sig-cluster-lifecycle

**Comment by yagonobre** [comment]
+1
/area github-membership

**Comment by rosti** [comment]
+1

**Comment by mrbobbytables** [comment]
@RA489  thank you for all your contributions so far :)

I've created PR #625  to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
