### ISSUE TITLE
REQUEST: New membership for rajat-0

### ISSUE THREAD

**Issue by Rajat-0** [kubernetes/org#623]
### GitHub Username
@rajat-0

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mwielgus
- @adisky

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=is%3Apr+is%3Amerged+org%3Akubernetes+org%3Akubernetes-sigs+author%3Arajat-0
https://github.com/search?q=is%3Apr+reviewed-by%3Arajat-0+org%3Akubernetes+-author%3Arajat-0

- Issues responded to
https://github.com/search?q=is%3Aissue+commenter%3Arajat-0+org%3Akubernetes

- SIG projects I am involved with
kubernetes/autoscaling

/area github-membership

**Comment by mwielgus** [comment]
+1 Thank you for your contributions!

**Comment by adisky** [comment]
+1 from me!!

**Comment by mrbobbytables** [comment]
@Rajat-0 , thank you for all your contributions so far :)

I've created PR #645  to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
