### ISSUE TITLE
New Repo: kubernetes-client perl

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/org#626]
### New Repo, Staging Repo, or migrate existing

new repository

### Requested name for new repository

perl

### Which Organization should it reside

kubernetes-client

### If not a staging repo, who should have admin access

@yue9944882 @mbohlool 

### If not a staging repo, who should have write access

@yue9944882 @mbohlool 

### If a new repo, who should be listed as approvers in OWNERS

@yue9944882 @mbohlool 

### If a new repo, who should be listed in SECURITY_CONTACTS

yue9944882 <291271447@qq.com>

### What should the repo description be

```
Official Perl(5) client library for kubernetes http://kubernetes.io/
```

### What SIG and subproject does this fall under in sigs.yaml

sig-machinery - swagger/openapi clients

### Approvals

We need perl openapi client b/c perl is widely used by system administrators and it also has an integration w/ nginx which is helpful for configuration light-weight routing rules according to the status of kubernetes cluster.

### Additional context for request

not sure, if it's a core repo or sigs repo 🤔

**Comment by nikhita** [comment]
Oh wow, a perl Kubernetes client!!! :tada: :tada: :tada: 

@yue9944882 for approval, can you send an email to the api-machinery ML and ask for approval from David or Daniel?

**Comment by mbohlool** [comment]
/lgtm
I think we at least need approval from @lavalamp or @deads2k as API Machinery leads.

@yue9944882 one way to get the approval is to just add it to the next sig api machinery meeting.

When we have approval for this, please ping me and I will create the repo for you. BTW, it won't be "official" and listed until it gets to at least "silver" feature level.

**Comment by lavalamp** [comment]
I think I am OK with this as long as I don't have to read or write any actual perl :)

**Comment by nikhita** [comment]
> I think I am OK with this as long as I don't have to read or write any actual perl :)

Lol, I'll take this as approval. 

Creating a new repo requires org admin permissions, so I'll take care of this.

**Comment by yue9944882** [comment]
> Creating a new repo requires org admin permissions, so I'll take care of this.

thank you!! 

> When we have approval for this, please ping me and I will create the repo for you. BTW, it won't be "official" and listed until it gets to at least "silver" feature level.

[https://github.com/brendandburns/community/blob/8c745d4b1f24eafba7a1fe31108fae393b973669/contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md#client-capabilities](https://github.com/brendandburns/community/blob/8c745d4b1f24eafba7a1fe31108fae393b973669/contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md#client-capabilities) so i see "silver" as supporting watch, amiright?

> I think we at least need approval from @lavalamp or @deads2k as API Machinery leads.

i swear i was about to mention this in yesterday's meeting, but a part of me seems forgot 😓

**Comment by nikhita** [comment]
https://github.com/kubernetes-client/perl has been created! :tada: 

Once the postsubmit gets run for https://github.com/kubernetes/org/pull/629, I'll assign the teams access. :)

After that's done + https://github.com/kubernetes/community/pull/3475 gets merged, we can close this issue.

**Comment by nikhita** [comment]
> Once the postsubmit gets run for #629, I'll assign the teams access.

Done. @yue9944882 @mbohlool you should now have admin access to the repo.

**Comment by yue9944882** [comment]
@nikhita let's get this close as [https://github.com/kubernetes/community/pull/3475](https://github.com/kubernetes/community/pull/3475) was already in

**Comment by nikhita** [comment]
@yue9944882 :+1: 

/close
