### ISSUE TITLE
REQUEST: New membership for chris-short

### ISSUE THREAD

**Issue by chris-short** [kubernetes/org#627]
### GitHub Username
chris-short

### Organization you are requesting membership in
Kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp 
- @nikhita

### List of contributions to the Kubernetes project
- [Wrap up contributor summit 2018 · Issue #3044 · kubernetes/community](https://github.com/kubernetes/community/issues/3044)
- Boots on ground support at Contributor Summit Seattle 2018
- Moderated several community meetings
- Applying for slack/zoom/etc Moderator duties (forgot I hadn't done this yet)
- sig-contribex (💪💪💪)

**Comment by nikhita** [comment]
Yesssssss! +100, Chris is an active member of sig contribex :)

/meow

**Comment by guineveresaenger** [comment]
+1 from me! yayyyyy!

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by mrbobbytables** [comment]
@chris-short I've created PR #639 to add you to the @kubernetes org. Once it gets merged you should get a membership invite notification. 🎉 
:D

/meow yay
/pony party

**Comment by justaugustus** [comment]
+1!
