### ISSUE TITLE
New repository: addon-operators

### ISSUE THREAD

**Issue by dholbach** [kubernetes/org#630]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
addon-operators

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@justinsb 

### If not a staging repo, who should have write access
@justinsb 

### If a new repo, who should be listed as approvers in OWNERS
@justinsb 

### If a new repo, who should be listed in SECURITY_CONTACTS
@justinsb 

### What should the repo description be
The cluster-addons sub-project was set up in [the 2019-03-12 meeting of SIG Cluster Lifecycle](https://docs.google.com/document/d/1Gmc7LyCIL_148a9Tft7pdhdee0NBHdOfHS1SAF0duI4/edit#heading=h.xhid2p5wz968)

* Slack: https://kubernetes.slack.com/messages/CH21PG8SW
* KEP: https://github.com/kubernetes/enhancements/pull/746

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject for sig-cluster-lifecycle called cluster-addons

### Approvals
 - Meeting minutes 2019-03-12: https://docs.google.com/document/d/1Gmc7LyCIL_148a9Tft7pdhdee0NBHdOfHS1SAF0duI4/edit#heading=h.xhid2p5wz968
 - Decision on name: https://kubernetes.slack.com/archives/C13J86Z63/p1552667179275500
 - Decision on repo name: https://kubernetes.slack.com/archives/C13J86Z63/p1552667403278000

/cc @luxas @timothysc

**Comment by luxas** [comment]
:+1:

**Comment by nikhita** [comment]
Created https://github.com/kubernetes-sigs/addon-operators :tada: 

Once the postsubmit runs for https://github.com/kubernetes/org/pull/631, the teams will be created on GitHub. I will then assign the teams appropriate access to the repo. :)

@dholbach could you create a PR to add this new subproject to sigs.yaml in the community repo?

Once the teams are assigned access + the above PR gets merged, we can close this issue.

**Comment by nikhita** [comment]
Oh also...what should be the one-line description for the repo?

**Comment by nikhita** [comment]
> I will then assign the teams appropriate access to the repo. 

This is done.

**Comment by dholbach** [comment]
> Oh also...what should be the one-line description for the repo?

"Addon operators for Kubernetes clusters"?

Not very witty, but let's add it for now and move on from there.

> @dholbach could you create a PR to add this new subproject to sigs.yaml in the community repo?

Will do.

**Comment by timothysc** [comment]
Please ensure the OWNERs files are updated appropriately to follow standard subproject formats.  

e.g. - https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS

**Comment by timothysc** [comment]
Also ensure the SCL leads have admin rights to that repo.

**Comment by nikhita** [comment]
> "Addon operators for Kubernetes clusters"?

Done.

> Please ensure the OWNERs files are updated appropriately to follow standard subproject formats.

Done. 

> Also ensure the SCL leads have admin rights to that repo.

Created https://github.com/kubernetes/org/pull/634. @luxas was not part of kubernetes-sigs, so I've added him there. @timothysc can you add lgtm?

**Comment by timothysc** [comment]
/lgtm 

Thx @nikhita !

**Comment by nikhita** [comment]
> /lgtm

Oops, you commented on the issue :)

**Comment by nikhita** [comment]
All done!

/close
