### ISSUE TITLE
REQUEST: New membership for hex108

### ISSUE THREAD

**Issue by hex108** [kubernetes/org#632]
### GitHub Username
@hex108 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
I have been kubernetes member, it seems no need for sponsors according to [membership guildlines](https://github.com/kubernetes/community/blob/master/community-membership.md)?

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/kube-batch/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ahex108
- Issues responded to
- SIG projects I am involved with
sig-scheduling

**Comment by nikhita** [comment]
Yes, you don't need sponsors :)

Can you create a PR to add yourself here: https://github.com/kubernetes/org/blob/master/config/kubernetes-sigs/org.yaml#L17?

**Comment by hex108** [comment]
Thanks @nikhita ,  I just sent PR https://github.com/kubernetes/org/pull/633, PTAL.
