### ISSUE TITLE
Please add AzurePipelines to the kubernetes-client org.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/org#635]
### Organization or repository
kubernetes-client organization

### Name of integration
Azure Pipelines

### Link to integration website
https://github.com/marketplace/azure-pipelines

### Describe what is attempting to be accomplished
Azure Pipelines will be used for code coverage, unit and integration testing for some of the kubernetes client libraries (e.g. C#) where Travis is missing functionality.

### Additional context for request
Ref #622

**Comment by spiffxp** [comment]
I don't have an azure account, so this step:
![Screen Shot 2019-03-20 at 4 19 55 PM](https://user-images.githubusercontent.com/49258/54725367-053c6880-4b2c-11e9-9ce5-b550af3a2610.png)

Bailed and put me at a login screen
![Screen Shot 2019-03-20 at 4 21 33 PM](https://user-images.githubusercontent.com/49258/54725450-551b2f80-4b2c-11e9-9170-deb0ba1ae080.png)


However, I believe the integration is now authorized/installed on our end:
![Screen Shot 2019-03-20 at 4 21 24 PM](https://user-images.githubusercontent.com/49258/54725468-68c69600-4b2c-11e9-9d14-efc9c400a231.png)


@brendandburns can you see if you can set things up on your end

**Comment by brendandburns** [comment]
Thanks, I'll give it a try...

**Comment by brendandburns** [comment]
@spiffxp seems to be working, thanks!

Closing.
