### ISSUE TITLE
Migrate kubernetes-incubator/cri-tools to kubernetes-sigs/cri-tools

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/org#64]
### New Repo, or migrate existing

migrate existing repository

### Requested name for new repository

cri-tools

### Which Organization should it reside

kubernetes-sigs

### Who should be provided access to this repository
e.g (at)example_user should have write access

@feiskyer
@Random-Liu 
@mrunalp

### Approvals

Please include links to the approvals (meeting minutes, e-mail thread, etc)

@derekwaynecarr 's approval https://github.com/kubernetes-incubator/cri-tools/issues/331#issuecomment-403897382

sig-node discussion https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.vmu9c89131nt

### Additional context for request
Any additional information or context to describe the request.

/assign @spiffxp
/cc @mrunalp @derekwaynecarr @Random-Liu

**Comment by spiffxp** [comment]
/reopen
Whoops, this repo hasn't actually been moved yet.  My bad

**Comment by spiffxp** [comment]
Repo has been moved: https://github.com/kubernetes-sigs/cri-tools

The following teams were created
- https://github.com/orgs/kubernetes-sigs/teams/cri-tools-admins/members
- https://github.com/orgs/kubernetes-sigs/teams/cri-tools-maintainers/members

The following users were invited as team maintainers for both teams: 
- @feiskyer 
- @Random-Liu 
- @mrunalp

The following collaborators were removed:
- read @miaoyq @yanxuean 
- write @heartlock

If you had read access, don't worry, the repo is public, so you don't need it.

If you had write access, please consider filing an issue to join the kubernetes-sigs org, and ask to be added to the cri-tools-maintainers team.

This needs a corresponding change to sigs.yaml

**Comment by spiffxp** [comment]
The following team used to have admin access to https://github.com/kubernetes-incubator/cri-tools:
- https://github.com/orgs/kubernetes-incubator/teams/maintainers-cri-tools

It has been removed

The members from this team who have not been added to the new teams are:
- @dchen1107 
- @xlgao-zju 
- @yujuhong 

Please file an issue if you feel you have been removed in error

**Comment by spiffxp** [comment]
/close
OK I'm calling this done, if there are any issues please follow up here

**Comment by feiskyer** [comment]
@spiffxp Thanks.

**Comment by xlgao-zju** [comment]
I am still happy to help on `cri-tools`. So if there is anything I can help, do ping me. 😆
