### ISSUE TITLE
REQUEST: New membership for serbrech

### ISSUE THREAD

**Issue by serbrech** [kubernetes/org#640]
### GitHub Username
@serbrech

### Organization you are requesting membership in
kubernetes
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tariq1890 
- @justaugustus 

### List of contributions to the Kubernetes project  
**PR reviewed/authored**  
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/141
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/139  

**Issues responded to**  
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/129  

**SIG projects I am involved with**  
- https://github.com/kubernetes-sigs/cluster-api-provider-azure
- https://github.com/kubernetes-sigs/cluster-api

**Comment by justaugustus** [comment]
+1!

**Comment by tariq1890** [comment]
+100! Stéphane is a colleague and I can definitely vouch for him. He has been closely involved with cluster-api and cluster-api-provider-azure

**Comment by tariq1890** [comment]
@mrbobbytables Following up on this :)

**Comment by mrbobbytables** [comment]
@tariq1890 I'll get a PR out the door later today :)

**Comment by tariq1890** [comment]
Thanks!

**Comment by mrbobbytables** [comment]
@serbrech thanks for helping out azure cluster api :)
I've created PR #645 to add you to both the @kubernetes and @kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉 

/assign
