### ISSUE TITLE
REQUEST: New membership for saschagrunert

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/org#641]
### GitHub Username

@saschagrunert

### Organization you are requesting membership in

kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@mrunalp
@rhatdan

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes-sigs/cri-o/pull/1965
  https://github.com/kubernetes-sigs/cri-o/pull/1974
  https://github.com/kubernetes-sigs/cri-o/pull/1983
  https://github.com/kubernetes-sigs/cri-o/pull/1984
  https://github.com/kubernetes-sigs/cri-o/pull/1985
  https://github.com/kubernetes-sigs/cri-o/pull/1986
  https://github.com/kubernetes-sigs/cri-o/pull/1988
  https://github.com/kubernetes-sigs/cri-o/pull/1992
  https://github.com/kubernetes-sigs/cri-o/pull/1993
  https://github.com/kubernetes-sigs/cri-o/pull/1994
  https://github.com/kubernetes-sigs/cri-o/pull/1996
  https://github.com/kubernetes-sigs/cri-o/pull/2015
  https://github.com/kubernetes-sigs/cri-o/pull/2032
  https://github.com/kubernetes-sigs/cri-o/pull/2042
  https://github.com/kubernetes-sigs/cri-o/pull/2045
  https://github.com/kubernetes-sigs/cri-o/pull/2048
  https://github.com/kubernetes-sigs/cri-o/pull/2052
  https://github.com/kubernetes-sigs/cri-o/pull/2132
  https://github.com/kubernetes-sigs/cri-o/pull/2137
  https://github.com/kubernetes-sigs/cri-o/pull/2138
  https://github.com/kubernetes-sigs/cri-o/pull/2149
  https://github.com/kubernetes-sigs/cri-o/pull/2150
- Issues responded to
  https://github.com/kubernetes-sigs/cri-o/issues/1987
  https://github.com/kubernetes-sigs/cri-o/issues/1971
  https://github.com/kubernetes-sigs/cri-o/issues/1980
- SIG projects I am involved with:
  https://github.com/kubernetes-sigs/cri-o
  https://github.com/kubernetes-sigs/cri-tools

**Comment by rhatdan** [comment]
LGTM

**Comment by mrbobbytables** [comment]
As this is to establish an additional owner for the cri-o, I'll toss in my +1 as well and get this squared away soon :)

**Comment by mrbobbytables** [comment]
@saschagrunert Thanks for helping out so much with cri-o :)

I've created PR #645  to add you to the @Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by saschagrunert** [comment]
Thank you very much! :pray:
