### ISSUE TITLE
REQUEST: New membership for bene2k1

### ISSUE THREAD

**Issue by bene2k1** [kubernetes/org#648]
### GitHub Username
@bene2k1

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rlenferink  
- @zacharysarah 
- @sieben

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/website/pull/13340
- https://github.com/kubernetes/org/pull/647

**Comment by rlenferink** [comment]
+1 @bene2k1 is the initiator behind translation our docs to German 🎉

**Comment by zacharysarah** [comment]
+1, thanks @bene2k1 for starting a German localization!

**Comment by mrbobbytables** [comment]
@bene2k1 , thank you for helping kickstart the German localization efforts!

I've created PR #652  to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
