### ISSUE TITLE
REQUEST: enable travis-ci for kubernetes-client/haskell

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/org#651]
### Organization or repository
kubernetes-client/haskell

### Users affected
N/A

### Describe the issue
We would like https://travis-ci.org/kubernetes-client/haskell to be enabled.

**Comment by nikhita** [comment]
@guoshimin our general recommendation in Kubernetes is to use https://github.com/kubernetes/test-infra/tree/master/prow instead of Travis wherever possible. Do you think that Prow could be used in this case?

**Comment by guoshimin** [comment]
I'll look into it. travis-ci is enabled for other repos in the
kubernetes-client org: https://travis-ci.org/kubernetes-client, so I
thought it would be nice to enable it for haskell too.

**Comment by spiffxp** [comment]
Travis is enabled for the kubernetes-client org, AFAIK there are no per-repo settings for us to configure.  You may want to contact the members of https://github.com/orgs/kubernetes-client/teams/haskell-admins to have them setup this specific repo

![Screen Shot 2019-03-26 at 10 30 43 AM](https://user-images.githubusercontent.com/49258/55019630-82476200-4fb2-11e9-9b3b-8326542dead4.png)

That said, we are big fans of community use of prow.k8s.io, it gives us some additional flexibility that travis does not.  If you have questions #sig-testing or #prow might be able to help you on slack, or take a look at https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md

**Comment by spiffxp** [comment]
/close
Please /reopen if you feel we have not addressed your question

**Comment by spiffxp** [comment]
/assign @spiffxp @nikhita 
(since we participated)

**Comment by guoshimin** [comment]
> Travis is enabled for the kubernetes-client org, AFAIK there are no per-repo settings for us to configure.

It's not enabled for the Haskell repo, as you can see here: https://travis-ci.org/kubernetes-client/haskell


> You may want to contact the members of https://github.com/orgs/kubernetes-client/teams/haskell-admins to have them setup this specific repo

That page is 404 for me.

**Comment by mrbobbytables** [comment]
My knowledge of travis isn't the best, but I believe one of the [admins for the repo](
https://github.com/kubernetes/org/blob/ce67156be20ed7a551b01e67f41d9ad7e8f5e5c3/config/kubernetes-client/org.yaml#L90-L95) needs to [activate](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci) it.

**Comment by akshaymankar** [comment]
I reached out to @brendandburns and @mbohlool to get travis activated on the repo. 
My email couldn't reach @mbohlool. 
@brendandburns said that even he doesn't have rights to activate travis.

**Comment by mrbobbytables** [comment]
/assign @brendandburns @mbohlool 
As admins on the repo, could one of you ack in thread regarding enabling travis?

@akshaymankar -- Long term I would definitely push to migrate to prow. We have a significant amount of tooling built around it.

**Comment by guoshimin** [comment]
What does setting up CI on prow look like? I read https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md when @spiffxp suggested it, and I gotta say, I still don't have a clue.

**Comment by nikhita** [comment]
> What does setting up CI on prow look like? 

Prow has three types of jobs - presubmits (run on a PR), postsubmits (run after a merge) and periodics (run at particular intervals).

I'm guessing you'd want to setup presubmits for your repo...taking client-go as an example, you'd create a file like this for your repo: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/client-go/client-go-presubmits.yaml

`pull-client-go-build` is the name of the job, and it uses the `golang:1.12` image and runs a `go build` command in the container. So for your repo, you'd also specify an image that you'd like to use and the commands to run for the job.

Happy to chat more in real-time on slack about this (I am `@nikhita` on slack as well).

**Comment by akshaymankar** [comment]
Hi @nikhita,

Apologies for silence for so long on this one.

I have created a PR for running unit tests for our repo using prow presubmits here: https://github.com/kubernetes/test-infra/pull/15331

There is a question about caching there, I am not sure if it is possible to cache things in prow.

Also, I copied all the `OWNERS` from the haskell-client repo to prow config directory, now the ci-robot is complaining that some of us are not members of the kubernetes org. I guess we'll have to create issues on this repo to add us there, right?

**Comment by nikhita** [comment]
@akshaymankar :wave: Apologies for not responding to your comment earlier. 

We definitely want to pivot towards using prow and https://github.com/kubernetes/test-infra/pull/15331 looks ready to be merged once the CLA and org membership bits are sorted out.

> Also, I copied all the OWNERS from the haskell-client repo to prow config directory, now the ci-robot is complaining that some of us are not members of the kubernetes org. I guess we'll have to create issues on this repo to add us there, right?

Yes, you'll need to create issues on this repo and add 2 sponsors as per https://git.k8s.io/community/community-membership.md#member.

I'm going to close this issue in favor of https://github.com/kubernetes/test-infra/pull/15331. Please reach out on slack (#sig-contribex, #sig-testing) if you need any help with moving the PR forward.
