### ISSUE TITLE
REQUEST: New membership for @shawn-hurley

### ISSUE THREAD

**Issue by shawn-hurley** [kubernetes/org#655]
### GitHub Username

@shawn-hurley

### Organization you are requesting membership in
@kubernetes-sig

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pmorie 
- @droot

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * https://github.com/kubernetes-sigs/controller-runtime/pull/101
  * https://github.com/kubernetes-sigs/controller-runtime/pull/267
- Issues responded to
  * https://github.com/kubernetes-sigs/controller-runtime/issues/172
  * https://github.com/kubernetes-sigs/controller-runtime/issues/153
- SIG projects I am involved with
  * https://github.com/kubernetes-sigs/controller-runtime

**Comment by pmorie** [comment]
+1

**Comment by droot** [comment]
+1 
Thanks @shawn-hurley for all the contributions and help!

**Comment by mrbobbytables** [comment]
Hey there @shawn-hurley, thank you for all your contributions so far :)

I've created PR #661 to add you to the @Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
