### ISSUE TITLE
REQUEST: New membership for kad

### ISSUE THREAD

**Issue by kad** [kubernetes/org#658]
### GitHub Username
@kad

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of contributions to the Kubernetes project
I'm already member of kubernetes org, and now I'm reviewer for https://github.com/kubernetes-sigs/node-feature-discovery, thus requesting kubernetes-sigs org membership.

**Comment by mrbobbytables** [comment]
@kad I've created PR #661 to add you to the @kubernetes-sigs org. Once it gets merged, you should get a membership invite notification.

Thanks!

/assign

**Comment by kad** [comment]
Thanks @mrbobbytables!
