### ISSUE TITLE
REQUEST: New membership for granular-ryanbonham

### ISSUE THREAD

**Issue by granular-ryanbonham** [kubernetes/org#660]
### GitHub Username
granular-ryanbonham

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mikesplain 
- @justinsb 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kops/pull/5758
- https://github.com/kubernetes/kops/pull/6689
- https://github.com/kubernetes/kops/issues/6688
-https://github.com/kubernetes/kubernetes/pull/72041
- CNCF End User Community
- Involved in KOPS Office Hours

**Comment by mikesplainsonos** [comment]
@granular-ryanbonham has been a great asset to the kops team!

+1

**Comment by mikesplain** [comment]
@granular-ryanbonham has been a great asset to the kops team!

+1

**Comment by justinsb** [comment]
+1

@granular-ryanbonham is very involved in kops and was instrumental in figuring out how we should move forwards with calico

**Comment by mrbobbytables** [comment]
@granular-ryanbonham, thank you for all the work you've done with Kops :)

I've created PR #661  to add you to the @Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
