### ISSUE TITLE
New repo request: kubernetes-sigs/slack-infra

### ISSUE THREAD

**Issue by Katharine** [kubernetes/org#663]
### New Repo, Staging Repo, or migrate existing
New repo

### Requested name for new repository
`slack-infra`

### Which Organization should it reside
`kubernetes-sigs`

### If not a staging repo, who should have admin access
@Katharine, @jeefy 

### If not a staging repo, who should have write access
(nobody?)

### If not a staging repo, who should be listed as approvers in OWNERS
@Katharine, @jeefy 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@Katharine, @jeefy 

### What should the repo description be
Tooling for kubernetes.slack.com

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject for sig-contribex, called slack-infra.

### Approvals
sig-contribex mailing list thread: https://groups.google.com/forum/#!msg/kubernetes-sig-contribex/4zcxLrd-nhg/Qa27nkx7BAAJ

**Comment by rlenferink** [comment]
+1

**Comment by nikhita** [comment]
+1

/assign

**Comment by nikhita** [comment]
Repo created https://github.com/kubernetes-sigs/slack-infra :tada: 

Created:
- https://github.com/kubernetes/org/pull/666: for admins team
- https://github.com/kubernetes/community/pull/3532: for updating sigs.yaml

Will close once admin access is granted and the PR to update sigs.yaml has merged.

**Comment by nikhita** [comment]
@Katharine @jeefy you should now have admin access to the repo. :)

**Comment by jeefy** [comment]
@nikhita You're the best! 😊 Thanks!!

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/3532 has merged.

/close
