### ISSUE TITLE
New repo: kubernetes-sigs/netlify-test

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/org#667]
### New Repo, Staging Repo, or migrate existing
New Repo

### Requested name for new repository
netlify-test

I am impartial on name if another is desired.

### Which Organization should it reside
@kubernetes-sigs

### If not a staging repo, who should have admin access
@mrbobbytables

### If not a staging repo, who should have write access
@mrbobbytables 

### If not a staging repo, who should be listed as approvers in OWNERS
@mrbobbytables

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@mrbobbytables 

### What should the repo description be
Temporary repo to test netlify integration

### What SIG and subproject does this fall under in sigs.yaml
sig-contributor-experience

It is shared partially with sig-docs
This is a short lived repo (hopefully a week at most) to help map the right permissions and workflow needed for subproject netlify site requests. For more information on this effort, see: https://github.com/kubernetes/community/issues/3454

### Approvals
https://github.com/kubernetes/community/issues/3454

If a more solid +1 is needed, I can follow-up and request more explicit approval.

**Comment by nikhita** [comment]
+1 from my side.

> This is a short lived repo (hopefully a week at most)

Let's revisit this on 5 April. If more time is needed, I guess it should be fine but let's publicly update the date so that we have an audit log. :)

@spiffxp if this lgty, can you add your +1? Since this is a temporary repo, I think a github-management owner should have weight in the decision as well.

**Comment by spiffxp** [comment]
+1 from subproject owner

**Comment by nikhita** [comment]
Done https://github.com/kubernetes-sigs/netlify-test :tada: 

@mrbobbytables I assigned you direct admin access since this is a temporary repo and didn't create a new team for it.

/close

**Comment by mrbobbytables** [comment]
Thanks @nikhita! 👍

**Comment by mrbobbytables** [comment]
We should be good to go to delete the repo 👍

**Comment by nikhita** [comment]
> We should be good to go to delete the repo

Deleted. Thanks for all your work on this, Bob!
