### ISSUE TITLE
REQUEST: New membership for bubblemelon

### ISSUE THREAD

**Issue by Bubblemelon** [kubernetes/org#670]
### GitHub Username
@bubblemelon

### Organization you are requesting membership in
kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nikhita 
- @hoegaarden 

### List of contributions to the Kubernetes project via [github-contrib](url)
**Repository: website**

Total Pull Requests Created: 1
- [kubernetes/website#6594](https://github.com/kubernetes/website/pull/6594) 

**Repository: release**

Total Pull Requests Created: 2
- [kubernetes/release#673](https://github.com/kubernetes/release/pull/673) 
- [kubernetes/release#671](https://github.com/kubernetes/release/pull/671)

**Repository: kubeadm**

Total Pull Requests Created: 1
- [kubernetes/kubeadm#1467](https://github.com/kubernetes/kubeadm/pull/1467) 

Total Issues Opened: 1
- [kubernetes/kubeadm#1466](https://github.com/kubernetes/kubeadm/issues/1466) 

**SIG Projects Involved With**
sig-release

It's not much, but it's a start :joy:

**Comment by nikhita** [comment]
+1 

Cheryl is the branch manager lead for 1.15: https://github.com/kubernetes/sig-release/blob/master/releases/release-1.15/release_team.md

She was also the branch manager [shadow in 1.14](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.14/release_team.md) and has been active in the Kubernetes upstream community since more than a year :)

**Comment by hoegaarden** [comment]
+1

**Comment by mrbobbytables** [comment]
@Bubblemelon  thank you for all your help with the release process :) 

I've created PR #674 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by Bubblemelon** [comment]
Thanks everyone! :smile:
