### ISSUE TITLE
REQUEST: New membership for embano1

### ISSUE THREAD

**Issue by embano1** [kubernetes/org#671]
### GitHub Username
@embano1

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cantbewong
- @frapposelli 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/issues/67703 (PRs reviewed linked)
  - https://github.com/kubernetes/kubernetes/issues/64021 (PRs reviewed linked)
  - https://github.com/kubernetes/website/pull/8973
  - https://github.com/kubernetes/website/pull/9716
  - https://github.com/kubernetes/website/pull/10509
  - https://github.com/kubernetes/website/pull/10510
- Issues responded to
  - https://github.com/kubernetes/kubernetes/issues/67703 (PRs reviewed linked)
  - https://github.com/kubernetes/kubernetes/issues/64021 (PRs reviewed linked)
- SIG projects I am involved with
  - SIG VMware
  - SIG Scheduling

**Comment by nikhita** [comment]
+100 :)

**Comment by frapposelli** [comment]
👍 times 💯

**Comment by mrbobbytables** [comment]
Hey there @embano1 , thank you for all your contributions so far :)

I've created PR #674  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by embano1** [comment]
Thank you @mrbobbytables !!! Everything worked like a charme!
Big THX to @frapposelli and @nikhita for their endorsement and inspiring leadership! Feeling blessed and honored.

**Comment by nikhita** [comment]
Thank _you_ for your contributions :heart:
