### ISSUE TITLE
Moving CRI-O to a different github organization

### ISSUE THREAD

**Issue by mrunalp** [kubernetes/org#675]
We are planning to move github.com/kubernetes-sigs/cri-o to github.com/cri-o/cri-o as part of moving to the CNCF. What are the steps that we need to follow?

CNCF is planning to publish a blog on 4th April and would like it if we are at our new location before that.

**Comment by nikhita** [comment]
> What are the steps that we need to follow?

A member from the github-admin team needs to be made admin for the cri-o org for the transfer. Since @cblecker replied on the mailing list, can you add him as an admin to the org?

Btw before that, a github-admin needs to follow the steps here https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#procedure-for-removal (except the kubernetes-retired bits).

**Comment by mrunalp** [comment]
@nikhita I have invited @cblecker to be an admin at github.com/cri-o. Thanks!

**Comment by cblecker** [comment]
@mrunalp What CI are you looking to use? It looks like you have both the kubernetes prow and the OpenShift prow active on the repo, in addition to Travis.

**Comment by cblecker** [comment]
Also, a couple of things I noticed:
- You're not requiring MFA: https://github.com/organizations/cri-o/settings/security
- You have some security settings that are pretty permissive: https://github.com/organizations/cri-o/settings/member_privileges

If you'd like assistance in setting these to the same settings as the Kubernetes organizations, please let me know.

**Comment by mrunalp** [comment]
@cblecker We would like to continue to use the same CI setup that we have today. 
Also, yes, :+1: to updating the settings to be more in line with k8s orgs.

**Comment by mrunalp** [comment]
I enabled the MFA.

**Comment by cblecker** [comment]
I'm not entirely sure which automation pieces are active. Will have to look into it.

**Comment by cblecker** [comment]
I have matched the settings on https://github.com/organizations/cri-o/settings/member_privileges to kubernetes.

**Comment by mrunalp** [comment]
@cblecker Thanks!

**Comment by cblecker** [comment]
@mrunalp Wanted to check in.. how are we looking? Are all the automation pieces looking good? Do you need any further help from us on the Kubernetes side?

**Comment by nikhita** [comment]
:wave: looks like this can be closed?

**Comment by mrunalp** [comment]
Yes, thanks!

**Comment by cblecker** [comment]
/close
:)
