### ISSUE TITLE
REQUEST: New membership for jmyung

### ISSUE THREAD

**Issue by jmyung** [kubernetes/org#676]
GitHub Username
@jmyung

Organization you are requesting membership in
@kubernetes

Requirements
- [v] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [v] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [v] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [v] I am actively contributing to 1 or more Kubernetes subprojects
- [v] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [v] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors
@gochist
@ClaudiaJKang

List of contributions to the Kubernetes project
- PRs authored
https://github.com/kubernetes/website/pull/10980
https://github.com/kubernetes/website/pull/11759
https://github.com/kubernetes/website/pull/12128
https://github.com/kubernetes/website/pull/12565
https://github.com/kubernetes/website/pull/13549

- Issues responded to
https://github.com/kubernetes/website/issues/10902
https://github.com/kubernetes/website/issues/10903
https://github.com/kubernetes/website/issues/11677
https://github.com/kubernetes/website/issues/12127
https://github.com/kubernetes/website/issues/13229

- SIG projects I am involved with
   kubernetes/sig-docs

/area github-membership

**Comment by ClaudiaJKang** [comment]
👍 Thank you for your contributions in Korean localization! @jmyung

**Comment by gochist** [comment]
+1

@jmyoung is one of most important contributors for Korean docs l10n

**Comment by mrbobbytables** [comment]
@jmyung thank you for your help with the Korean localization efforts :)

I've created PR #679  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
