### ISSUE TITLE
REQUEST: New membership for mkimuram

### ISSUE THREAD

**Issue by mkimuram** [kubernetes/org#678]
### GitHub Username
@mkimuram

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @msau42
- @wongma7

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pull/68635
  https://github.com/kubernetes/kubernetes/pull/68025
  https://github.com/kubernetes/kubernetes/pull/66577

- Issues responded to
  https://github.com/kubernetes/kubernetes/issues/68097
  https://github.com/kubernetes/kubernetes/issues/70760
  https://github.com/kubernetes/kubernetes/issues/70239  

- SIG projects I am involved with
  /sig storage

**Comment by msau42** [comment]
+1 @mkimuram has done a lot of work with the raw block feature and e2e test refactoring
/lgtm
/approve

**Comment by wongma7** [comment]
+1 thank you @mkimuram

**Comment by mrbobbytables** [comment]
Hey there @mkimuram , thank you for all your contributions so far :)

I've created PR #679   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
