### ISSUE TITLE
REQUEST: New membership for shavidissa

### ISSUE THREAD

**Issue by shavidissa** [kubernetes/org#682]
### GitHub Username
shavidissa

### Organization you are requesting membership in
kubernetes

### Requirements
- [ y] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [y ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ y] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [y ] I am actively contributing to 1 or more Kubernetes subprojects
- [y ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [y ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @Bradamant3 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ashavidissa+is%3Aclosed

**Comment by Bradamant3** [comment]
+1

**Comment by zacharysarah** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @shavidissa, thank you for all your contributions to the website! :)

I've created PR #686 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
