### ISSUE TITLE
New Repo: legacyflag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/org#683]
### New Repo, Staging Repo, or migrate existing
new repo

### Requested name for new repository
legacyflag

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@mtaufen 
@luxas 
@sttts 

### If not a staging repo, who should have write access
@mtaufen 
@luxas 
@sttts 

### If not a staging repo, who should be listed as approvers in OWNERS
@mtaufen 
@luxas 
@sttts 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@mtaufen 
@luxas 
@sttts 

### What should the repo description be
Provides a pflag wrapper that addresses pain-points of backwards-compatible ComponentConfig migration.

### What SIG and subproject does this fall under in sigs.yaml
This is part of the sig-api-machinery/component-base subproject.

### Approvals
@sttts 

Merged KEP: https://github.com/kubernetes/enhancements/pull/764

### Additional context for request
This may eventually migrate to `k8s.io/legacyflag`, but since it's currently experimental `sigs.k8s.io/legacyflag` seems like the correct location.

**Comment by nikhita** [comment]
This will need apimachinery approval. Per https://github.com/kubernetes/community/blob/master/sig-api-machinery/charter.md#sub-project-repo-creation, @sttts can you approve this?

**Comment by nikhita** [comment]
Created https://github.com/kubernetes-sigs/legacyflag :tada: 

Also created https://github.com/kubernetes/org/pull/698 to add teams for the repo. Once the postsubmit runs for it, I will grant access to those teams. 

@mtaufen @luxas @sttts can you create a PR to add this repo to sigs.yaml in k/community? Once that's done, we can close this issue.

**Comment by mtaufen** [comment]
Will do, thanks @nikhita

**Comment by mtaufen** [comment]
https://github.com/kubernetes/community/pull/3565

**Comment by nikhita** [comment]
> Once the postsubmit runs for it, I will grant access to those teams.

Done.

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/3565 has merged. Closing.

/close
