### ISSUE TITLE
REQUEST: New membership for @electrocucaracha

### ISSUE THREAD

**Issue by electrocucaracha** [kubernetes/org#687]
### GitHub Username
electrocucaracha

### Organization you are requesting membership in
- kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @raelga 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/org/pull/685#issuecomment-480141487

**Comment by zacharysarah** [comment]
+1, @electrocucaracha is a part of the new Spanish localization project.

**Comment by sieben** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @electrocucaracha, thank you for helping kick start the Spanish localization efforts :)

I've created PR #691  to add you to the Kubernetes Org. Once that gets merged, it should unblock #685 and you'll get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
