### ISSUE TITLE
REQUEST: New membership for raelga

### ISSUE THREAD

**Issue by raelga** [kubernetes/org#688]
### GitHub Username

@raelga

### Organization you are requesting membership in

@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @sieben 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/website/pull/13543
- sig-docs

**Comment by sieben** [comment]
👍

**Comment by sieben** [comment]
+1

**Comment by mrbobbytables** [comment]
Thanks for helping bootstrap the initial Spanish translation team 🎉 :)

+1

**Comment by mrbobbytables** [comment]
@raelga, I've created PR #691  to add you to the Kubernetes Org. Once that gets merged, it should unblock #685 and you'll get a membership invite notification. \o/

Welcome to @kubernetes! 🎉

/assign
