### ISSUE TITLE
REQUEST: New membership for s-urbaniak

### ISSUE THREAD

**Issue by s-urbaniak** [kubernetes/org#689]
### GitHub Username
@s-urbaniak

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @brancz 
- @DirectXMan12 

### List of contributions to the Kubernetes project
* Created and contributed the current underlying minikube Linux distribution, replacing boot2docker:
  * https://github.com/kubernetes/minikube/commits?author=sur%40coreos.com
* Contributed to the Kubernetes Mesos scheduler:
  * https://github.com/kubernetes/kubernetes/commits?author=sur%40mesosphere.io

Although not part of the Kubernetes org, I am now actively maintaining k8s-prometheus-adapter: https://github.com/DirectXMan12/k8s-prometheus-adapter.

Additionally I am looking forward to take ownership of the API server machinery for the Kubernetes metrics APIs: https://github.com/kubernetes/kubernetes/pull/76110#issuecomment-479779672

**Comment by nikhita** [comment]
Yay, +1

/meow space

**Comment by brancz** [comment]
This has my full support! :+1: :slightly_smiling_face:

**Comment by mrbobbytables** [comment]
Hey there @s-urbaniak , thank you for stepping in to help wrangle everything with the metrics :)

I've created PR #691 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by DirectXMan12** [comment]
:+1: from me as well
