### ISSUE TITLE
REQUEST: New membership for dholbach

### ISSUE THREAD

**Issue by dholbach** [kubernetes/org#695]
### GitHub Username
@dholbach

### Organization you are requesting membership in 
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @castrojo
- @errordeveloper 

### List of contributions to the Kubernetes project
- Taking care of logistics of [Cluster Addons sub-project](https://github.com/kubernetes-sigs/addon-operators) in SIG-Cluster Lifecycle (with @justinsb)
- PRs/issues:
   - https://github.com/search?q=org%3Akubernetes+dholbach&type=Issues
   - https://github.com/search?q=org%3Akubernetes-sigs+dholbach&type=Issues
- [Moderator of German Regional Board on Discuss](https://github.com/kubernetes/community/blob/master/communication/moderators.md#regional-category-moderators)
- Set up [#gitops Slack channel](https://kubernetes.slack.com/messages/gitops)

**Comment by castrojo** [comment]
+1 good to have you on board!

**Comment by errordeveloper** [comment]
+1


Ilya

**Comment by mrbobbytables** [comment]
@dholbach , thank you for all your contributions so far :)

I've created PR #705  to add you to both the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notifications from both of them.

Welcome to @kubernetes! 🎉

/assign
