### ISSUE TITLE
REQUEST: New membership for ccojocar

### ISSUE THREAD

**Issue by ccojocar** [kubernetes/org#696]
### GitHub Username
ccojocar

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @fejta 
- @cjwagner 
- @stevekuznetsov

### List of contributions to the Kubernetes project
- PRs reviewed / authored

https://github.com/kubernetes/test-infra/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Accojocar+

- Issues responded to

- SIG projects I am involved with

sig-testing

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #699 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
