### ISSUE TITLE
REQUEST: New membership for tahsinrahman

### ISSUE THREAD

**Issue by tahsinrahman** [kubernetes/org#697]
### GitHub Username
@tahsinrahman

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @tamalsaha 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/176
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/170
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/162
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/681
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/175
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/171

- SIG projects I am involved with
cluster-api
cluster-api-provider-azure
cluster-api-provider-aws

**Comment by justaugustus** [comment]
+1! Thanks for getting involved in the Cluster API projects! :)

**Comment by tamalsaha** [comment]
+1

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #699 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
