### ISSUE TITLE
REQUEST: New membership for holmsten

### ISSUE THREAD

**Issue by holmsten** [kubernetes/org#703]
### GitHub Username
@holmsten

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @miouge1
- @Atoms

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- https://github.com/kubernetes-sigs/kubespray/pull/2495
- https://github.com/kubernetes-sigs/kubespray/pull/2910
- https://github.com/kubernetes-sigs/kubespray/pull/3019
- https://github.com/kubernetes-sigs/kubespray/pull/3629
- https://github.com/kubernetes-sigs/kubespray/pull/3639
- https://github.com/kubernetes-sigs/kubespray/pull/3952
- https://github.com/kubernetes-sigs/kubespray/pull/3968
- https://github.com/kubernetes-sigs/kubespray/pull/4405
- https://github.com/kubernetes-sigs/kubespray/pull/4441
- Issues responded to
- SIG projects I am involved with
- https://github.com/kubernetes-sigs/kubespray

**Comment by Atoms** [comment]
+1

**Comment by mrbobbytables** [comment]
@holmsten, thanks for all your help with the kubespray project :)

I've created PR #705  to add you to the kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
