### ISSUE TITLE
REQUEST: New membership for hzxuzhonghu

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/org#707]
### GitHub Username
hzxuzhonghu

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @k82cn 
- @m1093782566

### List of contributions to the Kubernetes project
https://github.com/kubernetes-sigs/kube-batch/pulls?q=is%3Apr+author%3Ahzxuzhonghu+is%3Aclosed

**Comment by k82cn** [comment]
+1 , thanks for your contribution :)

**Comment by m1093782566** [comment]
+1
