### ISSUE TITLE
REQUEST: New membership for TommyLike

### ISSUE THREAD

**Issue by TommyLike** [kubernetes/org#709]
### GitHub Username
TommyLike

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @k82cn
- @m1093782566

### List of contributions to the Kubernetes project
https://github.com/kubernetes-sigs/kube-batch/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Atommylike+is%3Aclosed+

**Comment by k82cn** [comment]
+1 , thanks very much for your contirbution in kube-batch :)

**Comment by m1093782566** [comment]
+1

**Comment by mrbobbytables** [comment]
@TommyLike I hate to be a stickler, but do you happen to know someone else that could potentially sponsor you? Sponsors must be from different organizations per the [membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

Thanks!

**Comment by hex108** [comment]
+1 

@TommyLike is very active in kube-batch, thanks for the contribution!

**Comment by TommyLike** [comment]
@mrbobbytables  what should I do next?

**Comment by mrbobbytables** [comment]
@TommyLike you're good :) I was traveling and a little slow to getting a PR out the door.

With that I've created PR #717   to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
