### ISSUE TITLE
REQUEST: New membership for rojkov

### ISSUE THREAD

**Issue by rojkov** [kubernetes/org#710]
### GitHub Username
@rojkov

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yagonobre 
- @rosti 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+rojkov
  * https://github.com/kubernetes/enhancements/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+rojkov
- Issues responded to
  * https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+rojkov
- SIG projects I am involved with
  * sig-cluster-lifecycle

**Comment by yagonobre** [comment]
Thanks for all your contribution @rojkov
+1

**Comment by rosti** [comment]
Thanks @rojkov 
+1

**Comment by mrbobbytables** [comment]
@rojkov , thank you for all your help with kubeadm :)

I've created PR #717  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
