### ISSUE TITLE
move micro-demos from contrib

### ISSUE THREAD

**Issue by thockin** [kubernetes/org#714]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
micro-demos

### Which Organization should it reside
kubernetes ?

This is a weird case.  There's a framework (a couple files) and a bunch of scripted demos.  It could be 2 repos.  I may be the only contributor to it at all.  But I don't want it to go away.

### If not a staging repo, who should have admin access
thockin

### If not a staging repo, who should have write access
thockin

### If not a staging repo, who should be listed as approvers in OWNERS
thockin

### If not a staging repo, who should be listed in SECURITY_CONTACTS
thockin

### What should the repo description be
"Tiny, focused demos of Kubernetes functionality, that anyone can run."

### What SIG and subproject does this fall under in sigs.yaml
I do not know which SIG would own this.  It's not contribex.  It's more like PM ?

### Approvals
None.

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
Any additional information or context to describe the request.

**Comment by cblecker** [comment]
Finding an owner is probably the biggest question mark here. k-sigs is probably the right organization tho

**Comment by justaugustus** [comment]
@thockin -- sounds like Arch or PM. 
Would be happy to own it if we decide it's PM. :)

**Comment by nikhita** [comment]
For reference, `micro-demos` in this case is: https://github.com/kubernetes-retired/contrib/tree/master/micro-demos

> @thockin -- sounds like Arch or PM.
Would be happy to own it if we decide it's PM. :)

Looks like the next steps should be discussing this on the SIG Arch/PM mailing list? :)

**Comment by justaugustus** [comment]
/remove-sig pm
/sig architecture

@dims @johnbelamaric @derekwaynecarr -- what would you like to do with this one?

**Comment by dims** [comment]
we let it be where it is now https://github.com/kubernetes-retired/contrib/tree/master/micro-demos and close this issue

/close
