### ISSUE TITLE
Need a apiserver-network-proxy for sig-cloud-provider

### ISSUE THREAD

**Issue by cheftako** [kubernetes/org#715]
### New Repo, Staging Repo, or migrate existing
New repo

### Requested name for new repository
apiserver-network-proxy

### Which Organization should it reside
Kubernetes SIGs

### If not a staging repo, who should have admin access
cheftako, mcrute, anfernee, andrewsykim

### If not a staging repo, who should have write access
cheftako, mcrute, anfernee, andrewsykim

### If not a staging repo, who should be listed as approvers in OWNERS
cheftako, mcrute, anfernee, andrewsykim

### If not a staging repo, who should be listed in SECURITY_CONTACTS
cheftako, mcrute, anfernee, andrewsykim

### What should the repo description be
by default we will set it to "created due to (link to this issue)"

### What SIG and subproject does this fall under in sigs.yaml
sig-cloud-provider and cloud-provider-extraction-migration

### Approvals
Chatted with Andrew Sy Kim and Bowei Du. (SIG Cloud Provider and SIG Networking)
https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

### Additional context for request
This is intended to house the proto-type and later reference implementations for server network proxies. Amazon, Azure and Google have all indicated interest in helping in this effort. The server network proxy is a necessary step in extracting cloud provider specific code from the Kube API Server. Also the Networking, API Machinery and Cloud Provider SIGs have all agreed to the work.

**Comment by cblecker** [comment]
sig-cloud-provider isn't an organization. Do you mean @kubernetes-sigs ?

**Comment by cheftako** [comment]
> sig-cloud-provider isn't an organization. Do you mean Kubernetes SIGs ?

Fixed

**Comment by andrewsykim** [comment]
👍 from me!! Would prefer `apiserver-network-proxy` but will defer to @cheftako for naming

**Comment by cheftako** [comment]
I'm fine with apiserver-network-proxy.

**Comment by mcrute** [comment]
This would be really helpful to have pretty soon so we can start collaborating on the server-network-proxy code. Thanks!

**Comment by nikhita** [comment]
For the record: treating https://github.com/kubernetes/org/issues/715#issuecomment-482671605 as approval.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes-sigs/apiserver-network-proxy :tada: 

Also created the PRs:
-  https://github.com/kubernetes/org/pull/724 to add teams for this repo. Once that PR merges, I'll grant access to the teams.
- https://github.com/kubernetes/community/pull/3598 to add this repo to sigs.yaml

Once teams are granted access and https://github.com/kubernetes/community/pull/3598 has merged, we can close this issue.

**Comment by nikhita** [comment]
> Once that PR merges, I'll grant access to the teams.

Done.

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/3598 has merged.

/close
