### ISSUE TITLE
Delete repos: `kubernetes-csi/kubernetes-csi-migration-library` and `kubernetes-csi/csi-lib-common` 

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/org#718]
### Repository to delete

* [kubernetes-csi/csi-lib-common](https://github.com/kubernetes-csi/csi-lib-common)
  * It was never used.

### Repository to archive (or delete, which ever is easier)

* [kubernetes-csi/kubernetes-csi-migration-library](https://github.com/kubernetes-csi/kubernetes-csi-migration-library)
  * It has been replaced by https://github.com/kubernetes/csi-translation-lib

### Repository and/or sig subproject owners that are approving this archival
/sig storage
See [thread](https://groups.google.com/d/msg/kubernetes-sig-storage/6CDDqSNNf8I/wlp3TQ_RAwAJ)

**Comment by nikhita** [comment]
> kubernetes-csi/kubernetes-csi-migration-library 

Would prefer to archive this since it has commits other than the initial commits.

**Comment by nikhita** [comment]
@saad-ali I'll delete https://github.com/kubernetes-csi/csi-lib-common once https://github.com/kubernetes/community/pull/3600 merges.

**Comment by nikhita** [comment]
https://github.com/kubernetes-csi/kubernetes-csi-migration-library has been archived.

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/3600 has merged, deleted https://github.com/kubernetes-csi/csi-lib-common.

/close
