### ISSUE TITLE
REQUEST: New membership for @rajeshdeshpande02

### ISSUE THREAD

**Issue by rajeshdeshpande02** [kubernetes/org#720]
### GitHub Username
@rajeshdeshpande02

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tengqm
- @janetkuo 

### List of contributions to the Kubernetes project
https://github.com/pulls?q=is%3Apr+author%3Arajeshdeshpande02+archived%3Afalse+is%3Aclosed

**Comment by janetkuo** [comment]
@rajeshdeshpande02 Thank you for your contribution to kubernetes/website. 
+1

**Comment by tengqm** [comment]
+1
@rajeshdeshpande02 Looking forward to more contributions from you.

**Comment by mrbobbytables** [comment]
@rajeshdeshpande02 would you mind checking off the requirements that have been completed?

**Comment by rajeshdeshpande02** [comment]
@mrbobbytables Thanks for your quick review. I have updated the issue.

**Comment by mrbobbytables** [comment]
@rajeshdeshpande02,  thank you for all your contributions to the kubernetes website :)

I've created PR #723 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
