### ISSUE TITLE
Need a new Project board for code-organization subproject

### ISSUE THREAD

**Issue by dims** [kubernetes/org#721]
Can you please create a project board for the `code-organization` subproject of sig-architecture?
https://github.com/kubernetes/community/tree/master/sig-architecture#subprojects

Please add me as an editor for the same (@dims)

**Comment by dims** [comment]
Please create a github team as well so we can grant access to people. if it's easier to give everyone in kubernetes org edit access then we don't need a separate team.

**Comment by cblecker** [comment]
https://github.com/orgs/kubernetes/projects/27 is created
https://github.com/kubernetes/org/pull/733 will create the team for admin access

**Comment by dims** [comment]
Thanks @cblecker

**Comment by cblecker** [comment]
Access provided
