### ISSUE TITLE
REQUEST: New membership for @femrntz

### ISSUE THREAD

**Issue by femrtnz** [kubernetes/org#728]
### GitHub Username
@femrtnz

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@remyleone
@rlenferink 

### List of contributions to the Kubernetes project
https://github.com/kubernetes/website/pull/13773

**Comment by zacharysarah** [comment]
+1, @femrtnz is leading the Portuguese localization.

**Comment by rlenferink** [comment]
+1, thanks for your contributions to our docs so far :tada:

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #734 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
