### ISSUE TITLE
New repo request: kubernetes-sigs/vsphere-csi-driver

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/org#730]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
vsphere-csi-driver

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@frapposelli 
@codenrhoden 

### If not a staging repo, who should have write access
@frapposelli 
@codenrhoden 

### If not a staging repo, who should be listed as approvers in OWNERS
This will be imported from the existing cloud-provider-vsphere repo

### If not a staging repo, who should be listed in SECURITY_CONTACTS
This will be imported from the existing cloud-provider-vsphere repo

### What should the repo description be
vSphere storage Container Storage Interface (CSI) plugin

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject for SIG-VMware
PR adding the subproject to the SIG: https://github.com/kubernetes/community/pull/3607

### Approvals
[Meeting minutes](https://docs.google.com/document/d/1RV0nVtlPoAtM0DQwNYxYCC9lHfiHpTNatyv4bek6XtA/edit#heading=h.7ux7o2icdb49) for discussion on 2019/04/04
[Mailing List](https://groups.google.com/forum/#!topic/kubernetes-sig-vmware/F1pvLRhI7c0) Approval after lazy consensus

### Additional context for request
This repo will be populated by splitting out code from the existing [cloud-provider-vsphere repo](https://github.com/kubernetes/cloud-provider-vsphere). To that end, we will be moving over code that preserves commit history from the old location, and it would be useful to have the repo created as a bare repo to begin with.

That may present an issue, however, if merging then requires an OWNERS file, and we want to merge a PR rather than use admin write access. So I suppose it is also possible to have the repo initialized with the OWNERS file, then rebase on top of that. I'm open to suggestions here.

**Comment by codenrhoden** [comment]
/assign @frapposelli 

Fabio, I could use your input on whether I've correctly identified approvers, admin and write access, and security contacts.

I copied security contacts from the vSphere CCM repo

**Comment by nikhita** [comment]
> So I suppose it is also possible to have the repo initialized with the OWNERS file, then rebase on top of that. I'm open to suggestions here.

I'd prefer this from a github-management perspective. The commits/code that you need to move over -- they won't include the template files like OWNERS, etc, would they? If no, I guess it should be fine? :)

**Comment by codenrhoden** [comment]
> The commits/code that you need to move over -- they won't include the template files like OWNERS, etc, would they? If no, I guess it should be fine? :)

Since I've moving code that is coming from an existing k8s repo, I was thinking I would do that, but I don't *have* to. I'll have to level up my git-foo to preserve history for somethings but filter out certain files, but I believe it can be done.

**Comment by frapposelli** [comment]
@codenrhoden yes, keeping the OWNERS file is definitely the best path forward, I would suggest to just clone the original repo and run something like this:

```console
$ git filter-branch --index-filter 'git rm --cached -qr --ignore-unmatch -- . && git reset -q $GIT_COMMIT -- cmd/vsphere-csi pkg/csi OWNERS SECURITY_CONTACTS LICENSE code-of-conduct.md' --prune-empty -- --all
```

**Comment by nikhita** [comment]
:+1: 

> Fabio, I could use your input on whether I've correctly identified approvers, admin and write access, and security contacts.

Let me know if this is ok, and I'll create the new repo. :)

/assign

**Comment by frapposelli** [comment]
@nikhita please add @codenrhoden as part of the admin and write groups.

Also, as this is a kind of "special" case, we need the repo to be created as a bare repo as @codenrhoden is "importing" the filtered history from another repo 😅

**Comment by nikhita** [comment]
Will do! Thanks @frapposelli @codenrhoden

**Comment by codenrhoden** [comment]
I'm going to update the issue description to capture Fabio's comments

**Comment by codenrhoden** [comment]
And thank you @nikhita !

**Comment by nikhita** [comment]
Created repo https://github.com/kubernetes-sigs/vsphere-csi-driver :tada: 

Also created https://github.com/kubernetes/org/pull/737 to add teams for this repo. Once the PR merges and the postsubmit runs, the teams will be created on GitHub. I'll then grant access to the teams.

After teams are granted access + https://github.com/kubernetes/community/pull/3607 has merged, we can close this issue.

**Comment by codenrhoden** [comment]
Hi @nikhita,

I think the only outstanding item left now is to assign the newly created teams to the repo. Thank you so much for working on this!

**Comment by nikhita** [comment]
> I think the only outstanding item left now is to assign the newly created teams to the repo. 

Done :)

/close
