### ISSUE TITLE
Please archive kubernetes/contrib correctly

### ISSUE THREAD

**Issue by fejta** [kubernetes/org#731]
### Repository to archive
https://github.com/kubernetes/contrib

### Repository and/or sig subproject owners that are approving this archival
https://github.com/kubernetes/contrib/issues/3007#

### When should this be done
Anytime

**Comment by nikhita** [comment]
Looks like this is done?

**Comment by fejta** [comment]
I archived the repo but didn't do some other stuff like closing all the PRs and issues. Happy to close this out if that's good enough!

**Comment by cblecker** [comment]
/assign
I can do it.

**Comment by cblecker** [comment]
Done.
/close
