### ISSUE TITLE
REQUEST: New membership for @jcjesus

### ISSUE THREAD

**Issue by jcjesus** [kubernetes/org#735]
GitHub Username
@jcjesus

Organization you are requesting membership in
@kubernetes

Requirements
  - [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
  - [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
  - [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [x] I am actively contributing to 1 or more Kubernetes subprojects
  - [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
  - [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
Sponsors
@remyleone
@rlenferink

List of contributions to the Kubernetes project
kubernetes/website#13773

**Comment by remyleone** [comment]
+1

Em qua, 17 de abr de 2019 15:27, Jesus, Julio Cesar Soares de <
notifications@github.com> escreveu:

**Comment by mrbobbytables** [comment]
+1 Thanks for helping kickstart the Portuguese localization efforts!

**Comment by mrbobbytables** [comment]
@jcjesus I've created PR #736 to add you to the @kubernetes org :)
Once it gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉 

/assign
