### ISSUE TITLE
Archive kubernetes-sigs/architecture-tracking

### ISSUE THREAD

**Issue by nikhita** [kubernetes/org#738]
### Repository to archive

https://github.com/kubernetes-sigs/architecture-tracking

### Repository and/or sig subproject owners that are approving this archival

Lazy consensus email to sig-arch ML: https://groups.google.com/d/topic/kubernetes-sig-architecture/E_iSRgL22hs/discussion

### When should this be done
After lazy consensus timebox ends: April 22, Monday, 5pm PT. 

### Additional context for request

discussion on slack - https://kubernetes.slack.com/archives/C5P3FE08M/p1555524435003800

All the tracking has been moved to org level project boards:
- https://github.com/orgs/kubernetes/projects/13
- https://github.com/orgs/kubernetes/projects/9

**Comment by nikhita** [comment]
cc @jdumars @dims @mattfarina @bgrant0607

**Comment by dims** [comment]
+1 to archive

**Comment by bgrant0607** [comment]
+1

**Comment by bgrant0607** [comment]
cc @derekwaynecarr

**Comment by nikhita** [comment]
Repo has been archived: https://github.com/kubernetes-retired/architecture-tracking.

Created:

- https://github.com/kubernetes/community/pull/3636 - to remove the repo from sigs.yaml
- https://github.com/kubernetes/org/pull/756 - to remove GitHub teams related to the repo

Once both PRs get merged we can close the issue.

**Comment by nikhita** [comment]
Both PRs have merged.

/close
