### ISSUE TITLE
REQUEST: New membership for hidekazuna

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes/org#742]
### GitHub Username
@hidekazuna

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jichenjc
- @adisky 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  kubernetes-sigs/cluster-api-provider-openstack#83
  kubernetes-sigs/cluster-api-provider-openstack#105
  kubernetes-sigs/cluster-api-provider-openstack#206
  kubernetes-sigs/cluster-api-provider-openstack#208
  kubernetes-sigs/cluster-api-provider-openstack#289
  kubernetes-sigs/kubebuilder#470
  kubernetes-sigs/kubebuilder#478
  kubernetes/website#11707
  kubernetes/minikube#3286
- Issues responded to
  kubernetes-sigs/cluster-api-provider-openstack#81
  kubernetes-sigs/cluster-api-provider-openstack#244
  kubernetes-sigs/cluster-api-provider-openstack#286
- SIG projects I am involved with
 kubernetes-sigs/cluster-api-provider-openstack

**Comment by jichenjc** [comment]
+1

**Comment by jichenjc** [comment]
hidekazuna is very helpful and contribute a lot, thanks for the help :)

**Comment by adisky** [comment]
+1 From me :)

**Comment by mrbobbytables** [comment]
Hey there @hidekazuna, thank you for all your  help with the openstack cluster api :)

I've created PR #749  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
