### ISSUE TITLE
REQUEST: New membership for cantbewong

### ISSUE THREAD

**Issue by cantbewong** [kubernetes/org#745]
### GitHub Username
@cantbewong

### Organization you are requesting membership in
@kubernetes

### Requirements
- [ x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x ] I am actively contributing to 1 or more Kubernetes subprojects
- [x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @frapposelli
- @saad-ali

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - [website #10900](https://github.com/kubernetes/website/pull/10900)
  - [community #2300](https://github.com/kubernetes/community/pull/2300)
- SIG projects I am involved with
  - chair SIG VMware
  - lead IoT Edge Working Group
  - member SIG Storage

**Comment by saad-ali** [comment]
+1 @cantbewong has been involved with SIG Storage for quite some time.

**Comment by mrbobbytables** [comment]
👋 @cantbewong Thank you for all your efforts in helping the project :)

I've created PR #746 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification. 🎉 

/assign
