### ISSUE TITLE
REQUEST: New membership for mittalyashu

### ISSUE THREAD

**Issue by mittalyashu** [kubernetes/org#747]
### GitHub Username
@mittalyashu

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Rajakavitha1
- @daminisatya
- @nikhita

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/website/pull/13910
- https://github.com/cncf/foundation/pull/39

**Comment by nikhita** [comment]
+1, @mittalyashu has already created a PR to init Hindi localization: https://github.com/kubernetes/website/pull/13910

**Comment by raelga** [comment]
+1

**Comment by Rajakavitha1** [comment]
+1 
@mittalyashu Welcome !!!We look forward to many more contributions from you in localizing the content in Hindi.

**Comment by daminisatya** [comment]
+1 @mittalyashu Welcome!

**Comment by mrbobbytables** [comment]
@mittalyashu thanks for helping kick start the Hindi localization efforts :)

I've created PR #749   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by mittalyashu** [comment]
Yipeee.
