### ISSUE TITLE
REQUEST: New membership for avidLearnerInProgress

### ISSUE THREAD

**Issue by avidLearnerInProgress** [kubernetes/org#750]
### GitHub Username
@avidLearnerInProgress

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Rajakavitha1
- @daminisatya

### List of contributions to the Kubernetes project
- [kubernetes/website/#13936](https://github.com/kubernetes/website/pull/13936)
- [kubernetes/website/issues/#13957](https://github.com/kubernetes/website/issues/13957)
- [kubernetes/website/issues/#13926](https://github.com/kubernetes/website/issues/13926)

**Comment by Rajakavitha1** [comment]
+1 

Welcome @avidLearnerInProgress !!! We look forward to many more valuable contributions from you.

**Comment by daminisatya** [comment]
+1 

Welcome @avidLearnerInProgress 🎉

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #761 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
