### ISSUE TITLE
REQUEST: New membership for yuwenma

### ISSUE THREAD

**Issue by yuwenma** [kubernetes/org#751]
### GitHub Username
@yuwenma 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @justaugustus 
- @seans3

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * kubernetes/kubernetes#75624
  * kubernetes/kubernetes#72765 
  * kubernetes/kubernetes#73337
  * kubernetes/kubernetes#75856
  * kubernetes/kubernetes#74767
  * kubernetes/kubernetes#73096
 
  * kubernetes/klog#56
  * kubernetes/perf-tests#494
  * kubernetes/sig-release#569 
  * kubernetes/dns#296
  * kubernetes/dns#294
  * kubernetes/ingress-gce#655
  
- Issues responded to 
  * kubernetes/enhancements#900 [authored KEP]
  * kubernetes/klog#55 [filed]
  * kubernetes/kubernetes#76629 [filed]
  
- SIG projects I am involved with 
  * sig/cli
  * sig/release
  * sig/cloud-provider

**Comment by dims** [comment]
+1 from me!

**Comment by justaugustus** [comment]
Big +1 from me!

**Comment by seans3** [comment]
... and +1 from me too.

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #761 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign

**Comment by yuwenma** [comment]
> Thanks so much for your contributions thus far!
> I've created #761 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.
> 
> Welcome! :)
> /assign

Woohoo! Thanks so much!
