### ISSUE TITLE
REQUEST: New membership for sharifelgamal

### ISSUE THREAD

**Issue by sharifelgamal** [kubernetes/org#752]
### GitHub Username
@sharifelgamal

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tstromberg 
- @balopat

### List of contributions to the Kubernetes project
- 5 PRs authored: https://github.com/kubernetes/minikube/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Asharifelgamal+
- 10 PRs reviewed: https://github.com/kubernetes/minikube/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Asharifelgamal+-author%3Asharifelgamal+
- 12 issues responded to: https://github.com/kubernetes/minikube/issues?q=commenter%3Asharifelgamal+-author%3Asharifelgamal+is%3Aclosed
- SIG projects I am involved with: sig-cluster-lifecycle/minikube

**Comment by mrbobbytables** [comment]
@sharifelgamal I hate to be a stickler, but do you happen to have someone else that could sponsor you that does not work for Google? Our membership guidelines require that the [sponsors must be from different member companies](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

**Comment by sharifelgamal** [comment]
@afbjorklund can be my other sponsor

**Comment by afbjorklund** [comment]
Sure, I will sponsor @sharifelgamal

**Comment by justaugustus** [comment]
@tstromberg / @balopat -- I see that you both :+1:-ed, but would you mind explicitly commenting on sponsorship, so we have it as part of record?

**Comment by tstromberg** [comment]
I endorse @sharifelgamal for President.

Well, I endorse him to be a members of the Kubernetes Org, anyways. ☸️

**Comment by justaugustus** [comment]
@sharifelgamal -- Thanks so much for your contributions thus far!
I've created #762 to add you to the relevant org(s). You should receive an invite from our automation framework.

Welcome! :)
/assign

**Comment by balopat** [comment]
Ah, sorry, too late, FWIW, I do endorse @sharifelgamal to be part of the Kubernetes Org!
