### ISSUE TITLE
Archive kubernetes-sigs/website-metadata

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/org#753]
### Repository to archive

https://github.com/kubernetes-sigs/website-metadata/

### Repository and/or sig subproject owners that are approving this archival

@zacharysarah as [chair of SIG Docs](https://github.com/kubernetes/community/blob/master/sig-docs/charter.md#subproject-creation)

### When should this be done

Anytime.

### Additional context for request

Originally created at the request of the Chinese localization team, this repo has not been used in the past 5 months. After [consulting](https://kubernetes.slack.com/archives/CA1MMM1HU/p1553709504053600) with a Chinese localization lead, we've agreed to archive the repo. If future need arises, we can request creation of a new repo.

/cc @kubernetes/sig-docs-zh-owners

**Comment by cblecker** [comment]
As this hasn't been used at all, do you mind if we delete the entire repo?

**Comment by zacharysarah** [comment]
@cblecker 👋 
> As this hasn't been used at all, do you mind if we delete the entire repo?

Go for it!

**Comment by nikhita** [comment]
Repo has been deleted.

Created:

- https://github.com/kubernetes/community/pull/3637 - to remove the repo from sigs.yaml
- https://github.com/kubernetes/org/pull/757 - to remove teams for this repo

Once both PRs get merged, we can close this issue.

**Comment by nikhita** [comment]
Both PRs have merged.

/close

**Comment by idealhack** [comment]
Sorry to say this but honestly I’m sad to see this repo not getting used and deleted. As I understand that owners of current using repos have the ultimate decisions of them, I don’t think contributors can see those repos the same as a kubernetes community maintained repo and work on them.
