### ISSUE TITLE
REQUEST: New membership for droslean

### ISSUE THREAD

**Issue by droslean** [kubernetes/org#758]
### GitHub Username
@droslean

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dhttps://groups.google.com/forum/#!forum/kubernetes-devev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @kargakis 
- @stevekuznetsov

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    * https://github.com/kubernetes/kubernetes/pull/73877
    * https://github.com/kubernetes/kubernetes/pull/73917
    * https://github.com/kubernetes/kubernetes/pull/73970
    * https://github.com/kubernetes/kubernetes/pull/74528
    * https://github.com/kubernetes/test-infra/pull/8579
    * https://github.com/kubernetes/test-infra/pull/8882
    * https://github.com/kubernetes/test-infra/pull/8890
    * https://github.com/kubernetes/test-infra/pull/8932
    * https://github.com/kubernetes/test-infra/pull/9212
    * https://github.com/kubernetes/test-infra/pull/9269
    * https://github.com/kubernetes/test-infra/pull/9992
    * https://github.com/kubernetes/test-infra/pull/12323
- Issues responded to
    * https://github.com/kubernetes/kubernetes/issues/73969
- SIG projects I am involved with
    * test-infra/prow
    * sig-cli

**Comment by kargakis** [comment]
+1 👍

**Comment by stevekuznetsov** [comment]
:+1: 
:)

**Comment by justaugustus** [comment]
@droslean -- Excited to have new members, but before we get you processed, would you be able to find another non-Red Hat sponsor? We have a few requirements for sponsorship (including company diversity of sponsors) that you can check out here: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by cjwagner** [comment]
I sponsor.

**Comment by kargakis** [comment]
@justaugustus for what it's worth, I don't work at Red Hat since January 2019. I realized I was still under the Red Hat CLA so I went ahead and signed the Individual CLA, hope that helps.

**Comment by justaugustus** [comment]
@kargakis -- Apologies, I didn't realize. Thanks for signing the individual CLA!

**Comment by justaugustus** [comment]
@droslean -- Thanks so much for your contributions thus far!
I've created #762 to add you to the relevant org(s). You should receive an invite from our automation framework.

Welcome! :)
/assign
