### ISSUE TITLE
REQUEST: New membership for VonGuard

### ISSUE THREAD

**Issue by vonguard** [kubernetes/org#759]
### GitHub Username
vonguard

### Organization you are requesting membership in
SIG ContribX
### Requirements
- [x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- Paris Pittman
- Elsie Phillips

### List of contributions to the Kubernetes project
- PRs reviewed / authored: https://github.com/kubernetes/website/pull/13455

- SIG ContribX Blogging

**Comment by parispittman** [comment]
So excited to have you on and helping us spread the word about the awesome work our contributors do :)

+1

**Comment by nikhita** [comment]
+100

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #761 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
