### ISSUE TITLE
Define who can approve membership

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#76]
We should clarify who can approve membership requests once the requisites are satisfied.

rel: #75 
/sig contribex
/area github-management
/assign @cblecker @parispittman @castrojo @spiffxp

**Comment by cblecker** [comment]
What do you mean? Once sponsors have signed off?

**Comment by justaugustus** [comment]
Yup! See #75

**Comment by cblecker** [comment]
Per https://github.com/kubernetes/community/blob/master/community-membership.md, the sponsors are the ones who "approve" membership. The GitHub Administration Team are the ones who do the actual inviting.

**Comment by justaugustus** [comment]
@cblecker -- the language is `Once your sponsors have responded, your request will be reviewed. Any missing information will be requested.`, so we don't specify by whom the request will be reviewed.

**Comment by cblecker** [comment]
PRs welcome to improve the wording :)

**Comment by parispittman** [comment]
How is "...your request will be reviewed by the [Kubernetes GitHub Admin team](link to their README)"?

**Comment by justaugustus** [comment]
Hehe, I know. Just wanted to point out the current state. I can push something later. :)

**Comment by justaugustus** [comment]
@parispittman -- that works! Should we specify some timeframe?

**Comment by cblecker** [comment]
SLOs: https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#slos

**Comment by justaugustus** [comment]
PR up here: https://github.com/kubernetes/community/pull/2650
