### ISSUE TITLE
REQUEST: New membership for @dekkagaijin

### ISSUE THREAD

**Issue by dekkagaijin** [kubernetes/org#760]
### GitHub Username
@dekkagaijin

### Organization you are requesting membership in
@kubernetes

### Requirements
- [ x ] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x ] I am actively contributing to 1 or more Kubernetes subprojects
- [ x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @liggitt 
- @deads2k

### List of contributions to the Kubernetes project
* [KEP #789: harden the default RBAC discovery clusterrolebindings](https://github.com/kubernetes/enhancements/issues/789)
  * https://github.com/kubernetes/kubernetes/pull/73807
  * https://github.com/kubernetes/website/pull/12888
* [k/k #63682: header key validation stricter than user.Info.Extra key validation](https://github.com/kubernetes/kubernetes/issues/63682)
  * https://github.com/kubernetes/kubernetes/pull/65799
* Taken over maintaining [GCE's metadata concealment addon](https://github.com/dekkagaijin/k8s-metadata-proxy) and corresponding portions of k/k
  * https://github.com/kubernetes/kubernetes/pull/66630
  * https://github.com/kubernetes/kubernetes/pull/69593
  * https://github.com/kubernetes/kubernetes/pull/70195
  * https://github.com/kubernetes/kubernetes/pull/70253
  * https://github.com/kubernetes/kubernetes/pull/71094

**Comment by liggitt** [comment]
+1

**Comment by deads2k** [comment]
+1

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #761 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign

**Comment by dekkagaijin** [comment]
Thanks, all :)
