### ISSUE TITLE
REQUEST: New membership for tedyu

### ISSUE THREAD

**Issue by tedyu** [kubernetes/org#764]
### GitHub Username
@tedyu

### Organization you are requesting membership in
@kubernetes

### Requirements
- [ X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X ] I am actively contributing to 1 or more Kubernetes subprojects
- [X ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123 
- @Huang-Wei 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
Cleanup as many dirs as possible in CleanupDirs
Return aggregate error from rollbackOldManifests
Return from loop in removeZone when zone is found
Produce map according to the shorter array in haveOverlap

Outstanding PRs:
Refine max job backoff check (#77025)
Bundle multiple creation observations (#77027)

- Issues responded to

- SIG projects I am involved with
/sig kubeadm

**Comment by neolit123** [comment]
@tedyu 
+1 from me.
thanks for the contributions thus far!

> PRs reviewed / authored

it would be best to have some existing PR links.

**Comment by Huang-Wei** [comment]
+1. Thanks for the contributions!

**Comment by mrbobbytables** [comment]
Hey there @tedyu, thank you for all your contributions so far :)

I've created PR #770  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
