### ISSUE TITLE
REQUEST: New membership for ping035627

### ISSUE THREAD

**Issue by ping035627** [kubernetes/org#765]
### GitHub Username
@ping035627

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @neolit123
- @k82cn 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pulls/ping035627
https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Aping035627+is%3Aclosed
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/73189
https://github.com/kubernetes/kubernetes/issues/72846
https://github.com/kubernetes/kubernetes/issues/72799
https://github.com/kubernetes/kubernetes/issues/71363
https://github.com/kubernetes/kubernetes/issues/25649
https://github.com/kubernetes/website/issues/12639
- SIG projects I am involved with
k/kubernetes
k/website
k/test-infra

**Comment by neolit123** [comment]
+1 thanks for the contributions @ping035627 !!

**Comment by k82cn** [comment]
+1, thanks for your contributions :)

**Comment by mrbobbytables** [comment]
@ping035627, thank you for helping the project! :)

I've created PR #770   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by ping035627** [comment]
Thanks, all! :)
