### ISSUE TITLE
Request for admin permission of kubernetes-sigs/sig-storage-local-static-provisioner

### ISSUE THREAD

**Issue by cofyc** [kubernetes/org#766]
### Organization or repository
kubernetes-sigs/sig-storage-local-static-provisioner

### Users affected
@cofyc 

### Describe the issue
I need to push tags to do releasing for this project, etc.

**Comment by cblecker** [comment]
The config for those teams is here:
https://github.com/kubernetes/org/blob/81a77f6f9a869c7bb975571df7448b197cef49f9/config/kubernetes-sigs/org.yaml#L473-L486

PRs accepted :)

**Comment by cofyc** [comment]
That's great! Thanks!
/close
