### ISSUE TITLE
REQUEST: New membership for zvonkok

### ISSUE THREAD

**Issue by zvonkok** [kubernetes/org#768]
### GitHub Username
@zvonkok

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@marquiz 
@vikaschoudhary16 

### List of contributions to the Kubernetes project
- PRs reviewed/authored
node-feature-discovery: #224, #223, #218, #215, #211, #209, #195, #168, #166, #149
- Issues responded to
node-feature-discovery: #229, #224, #215, #207, #195, #167
- SIG projects I am involved with
node-feature-discovery

**Comment by mrbobbytables** [comment]
@zvonkok Can you update your org membership request with the sponsors and information regarding your contributions to a project under kubernetes-sigs? We can't process it until that information has been filled out and the sponsors have given their +1. Please see the [community membership docs](https://github.com/kubernetes/community/blob/master/community-membership.md#member) for more information.

Thanks!

**Comment by zvonkok** [comment]
@mrbobbytables updated. Thanks!

**Comment by mrbobbytables** [comment]
@zvonkok I hate to be a stickler, but can you also include links to some of of your contributions under _"List of contributions to the Kubernetes project"_ part? It looks like you're involved with the node-feature-discovery project and some of those should be fine :)

**Comment by zvonkok** [comment]
@mrbobbytables NP just updated.

**Comment by vikaschoudhary16** [comment]
+1

**Comment by marquiz** [comment]
+1

**Comment by mrbobbytables** [comment]
@zvonkok thanks for getting everything squared away earlier :) With that out of the way, I've gone ahead and created PR #770  to add you to the Kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
