### ISSUE TITLE
REQUEST: New membership for atoato88

### ISSUE THREAD

**Issue by atoato88** [kubernetes/org#771]
### GitHub Username
@atoato88

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @oomichi 
- @neolit123 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
kubernetes/kubernetes#76705
kubernetes/kubernetes#76348
kubernetes/kubernetes#76488
kubernetes/kubernetes#76745
kubernetes/kubernetes#76057
kubernetes-sigs/kubebuilder-declarative-pattern#11
kubernetes-sigs/kubebuilder-declarative-pattern#24
kubernetes/kubernetes#75797
kubernetes/kubernetes#76006
kubernetes/dashboard#3711
kubernetes-sigs/controller-runtime#339
kubernetes/website#12440
kubernetes/website#10571
kubernetes/kubernetes#68311
kubernetes/kubernetes#74064
kubernetes/kubernetes#70405
kubernetes/kubernetes#70625

- Issues responded to
kubernetes-sigs/kubebuilder-declarative-pattern#15
kubernetes/kubeadm#1357
kubernetes/kubeadm#1376
kubernetes/website#12431
kubernetes/website#10569
kubernetes/website#5779

- SIG projects I am involved with
sig-cluster-lifecycle
sig-testing

**Comment by neolit123** [comment]
thank you for your contributions @atoato88 !
+1

**Comment by oomichi** [comment]
Thanks for your work, @neolit123 
big +1 :-)

**Comment by neolit123** [comment]
> Thanks for your work, @neolit123

lol :)

**Comment by oomichi** [comment]
Oops ;-)

**Comment by atoato88** [comment]
Thank you so much!! 😄

**Comment by mrbobbytables** [comment]
@atoato88 Thanks for all your contributions to the project so far :)

I've created PR #773  to add you to both the kubernetes and kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign
