### ISSUE TITLE
REQUEST: New membership for thecrudge

### ISSUE THREAD

**Issue by thecrudge** [kubernetes/org#772]
### GitHub Username
thecrudge

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@jimangel 
@cody-clark 

### List of contributions to the Kubernetes project
- PRs I've Authored
https://github.com/kubernetes/website/pull/14060
https://github.com/kubernetes/website/pull/14059
https://github.com/kubernetes/website/pull/13831
https://github.com/kubernetes/website/pull/13805
https://github.com/kubernetes/website/pull/13747

- Issues responded to
https://github.com/kubernetes/website/issues/12335
https://github.com/kubernetes/website/issues/12330
https://github.com/kubernetes/website/issues/12254
https://github.com/kubernetes/website/issues/12186
https://github.com/kubernetes/website/issues/12149
https://github.com/kubernetes/website/issues/12148
https://github.com/kubernetes/website/issues/12075
https://github.com/kubernetes/website/issues/10917

- SIG projects I am involved with
Docs
Community

Im also Co-Organizer of the CNCF Kubernetes Austin Meetup

**Comment by jimangel** [comment]
+1 Cody has hit the ground running fast! Looking forward to seeing more accomplishments!

**Comment by cody-clark** [comment]
+1 There's never too many Codys! 

Edit: He does good work, too, like Jim mentioned!

**Comment by bradtopol** [comment]
I am happy to sponsor as well. For some reason the tool is not letting Cody add me as a sponsor.  Any idea why????

**Comment by mrbobbytables** [comment]
@bradtopol just adding your +1 in here is good enough 😄 

@thecrudge, thanks for all your help with the website. :) 
I've created PR #773  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by bradtopol** [comment]
Thanks @mrbobbytables!!!

**Comment by thecrudge** [comment]
Thanks everyone, and thanks @mrbobbytables !
