### ISSUE TITLE
REQUEST: New membership for hchenxa

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/org#774]
### GitHub Username
@hchenxa

### Organization you are requesting membership in
@kubernetes-sigs
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gyliu513 
- @k82cn 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
kubernetes:
https://github.com/kubernetes/kubernetes/pull/72142
https://github.com/kubernetes/kubernetes/pull/51072
https://github.com/kubernetes/kubernetes/pull/50822

kubernetes/ingress-nginx:
https://github.com/kubernetes/ingress-nginx/pull/3271
https://github.com/kubernetes/ingress-nginx/pull/3252
https://github.com/kubernetes/ingress-nginx/pull/3215
https://github.com/kubernetes/ingress-nginx/pull/3201
https://github.com/kubernetes/ingress-nginx/pull/3111
https://github.com/kubernetes/ingress-nginx/pull/3108
https://github.com/kubernetes/ingress-nginx/pull/3103
https://github.com/kubernetes/ingress-nginx/pull/3100
https://github.com/kubernetes/ingress-nginx/pull/3073
https://github.com/kubernetes/ingress-nginx/pull/3081

cluster-api-provider-openstack: 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/329
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/326
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/314
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/306
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/305
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/224

- Issues responded to
kubernetes:
https://github.com/kubernetes/kubernetes/issues/72144
https://github.com/kubernetes/kubernetes/issues/69555
https://github.com/kubernetes/kubernetes/issues/67491
https://github.com/kubernetes/kubernetes/issues/67479
https://github.com/kubernetes/kubernetes/issues/67367
https://github.com/kubernetes/kubernetes/issues/67300
https://github.com/kubernetes/kubernetes/issues/66819
https://github.com/kubernetes/kubernetes/issues/66597
https://github.com/kubernetes/kubernetes/issues/65738
https://github.com/kubernetes/kubernetes/issues/65706
https://github.com/kubernetes/kubernetes/issues/64014
https://github.com/kubernetes/kubernetes/issues/63052
https://github.com/kubernetes/kubernetes/issues/62828
https://github.com/kubernetes/kubernetes/issues/62907
https://github.com/kubernetes/kubernetes/issues/56278
https://github.com/kubernetes/kubernetes/issues/55211
https://github.com/kubernetes/kubernetes/issues/54851
https://github.com/kubernetes/kubernetes/issues/51680
https://github.com/kubernetes/kubernetes/issues/51013
https://github.com/kubernetes/kubernetes/issues/51002
https://github.com/kubernetes/kubernetes/issues/50820

kubernetes/ingress-nginx:
https://github.com/kubernetes/ingress-nginx/issues/3273
https://github.com/kubernetes/ingress-nginx/issues/3272
https://github.com/kubernetes/ingress-nginx/issues/3268
https://github.com/kubernetes/ingress-nginx/issues/3071
https://github.com/kubernetes/ingress-nginx/issues/3031

cluster-api-provider-openstack: 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/325
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/318
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/315
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/307
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/304
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/301

- SIG projects I am involved with
cluster-api-provider-openstack

**Comment by gyliu513** [comment]
+1, thanks @hchenxa for your great contribution!

**Comment by xunpan** [comment]
+1, looking forward more active contributions to sig-kubernetes projects.

**Comment by k82cn** [comment]
+1 to me, thanks for your contribution :)

**Comment by mrbobbytables** [comment]
Hey there @hchenxa, unfortunately @gyliu513 cannot sponsor you for membership in the @kubernetes org, but CAN sponsor you for membership in @kubernetes-sigs.

An approver/reviewer in @kubernetes, may sponsor someone for the @kubernetes org or any of the related organizations (@kubernetes-sigs, @kubernetes-csi etc); as long as it's a project they're involved with.

However, this does not work the other way around. A sponsor that is only an approver/reviewer in @kubernetes-csi cannot sponsor someone for membership in @kubernetes. They are scoped just to the org they're associated with.

@hchenxa  If you'd like to amend your request to just @kubernetes-sigs, we can proceed with getting your membership processed. Otherwise, if you could, please find another sponsor from the @kubernetes org.

If you have any questions don't be afraid to ask.

Thanks!

**Comment by wanghaoran1988** [comment]
+1 from me, thanks.

**Comment by mrbobbytables** [comment]
Great :) Thanks for adding your +1 for the kubernetes org @wanghaoran1988.

@hchenxa Thank you for all your contributions thus far 👍 

I've created PR #775 to add you to both the kubernetes and kubernetes-sigs orgs. Once that gets merged, you should get a membership invite notification from both of them.

Welcome to @kubernetes! 🎉

/assign
