### ISSUE TITLE
REQUEST: New membership for Ethyling

### ISSUE THREAD

**Issue by Ethyling** [kubernetes/org#777]
### GitHub Username
@Ethyling

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @marquiz
- @zvonkok

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
  - https://github.com/kubernetes-sigs/node-feature-discovery/pull/221
  - https://github.com/kubernetes-sigs/node-feature-discovery/pull/228
  - https://github.com/kubernetes-sigs/node-feature-discovery/pull/230
  - https://github.com/kubernetes-sigs/node-feature-discovery/pull/231
  - https://github.com/kubernetes-sigs/node-feature-discovery/pull/236

- SIG projects I am involved with:
  - node-feature-discovery

**Comment by zvonkok** [comment]
+1

**Comment by marquiz** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @Ethyling, thank you for all your help with the node-feature-discovery project :)

I've created PR #788   to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
