### ISSUE TITLE
REQUEST: New membership for aojea

### ISSUE THREAD

**Issue by aojea** [kubernetes/org#778]
### GitHub Username
@aojea

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @BenTheElder 
- @neolit123 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

[PRs authored in kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aaojea)
[PRs authored in kubernetes-sigs/kind](https://github.com/kubernetes-sigs/kind/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aaojea)

- Issues responded to

[Issues responded in kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=mentions%3Aaojea)
[Issues responded in kubernetes-sigs/kind](https://github.com/kubernetes-sigs/kind/issues?utf8=%E2%9C%93&q=mentions%3Aaojea)

- SIG projects I am involved with

https://github.com/kubernetes-sigs/kind

**Comment by neolit123** [comment]
+1 thanks for the contributions @aojea !

**Comment by BenTheElder** [comment]
+1, thank you for all the contributions!!!

**Comment by mrbobbytables** [comment]
@aojea thank you for helping out with the kind subproject :)

I've created PR #781  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
/pony party
