### ISSUE TITLE
Need repo permissions on k-i/cluster-proportional-vertical-autoscaler

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/org#779]
### Organization or repository
https://github.com/kubernetes-incubator/cluster-proportional-vertical-autoscaler

### Users affected
@MrHohn 

### Describe the issue
I am in the [OWNERS file](https://github.com/kubernetes-incubator/cluster-proportional-vertical-autoscaler/blob/master/OWNERS) but I need owner permission on the repository itself in order to conduct releases.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/org/pull/780. Once it gets merged and the postsubmit completes, I'll manually grant the team admin access to the repo.

/assign

**Comment by nikhita** [comment]
@MrHohn you should now have admin access to the repo.

**Comment by MrHohn** [comment]
Verified, many thanks @nikhita !
