### ISSUE TITLE
Migrate multicloudlab/cluster-api-provider-ibmcloud to kubernetes-sigs

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/org#782]
### New Repo, Staging Repo, or migrate existing
Migrate existing https://github.com/multicloudlab/cluster-api-provider-ibmcloud

### Requested name for new repository
cluster-api-provider-ibmcloud

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@gyliu513 

### If not a staging repo, who should have write access
I can set this up once we get migrated in.

### If not a staging repo, who should be listed as approvers in OWNERS
We already have OWNER and OWNERS_ALIASES:
- https://github.com/multicloudlab/cluster-api-provider-ibmcloud/blob/master/OWNERS_ALIASES
- https://github.com/multicloudlab/cluster-api-provider-ibmcloud/blob/master/OWNERS

### If not a staging repo, who should be listed in SECURITY_CONTACTS
We already have https://github.com/multicloudlab/cluster-api-provider-ibmcloud/blob/master/SECURITY_CONTACTS

### What should the repo description be
Cluster API implementation for IBM Cloud

### What SIG and subproject does this fall under in sigs.yaml
This is a new subproject for `sig-ibmcloud` called `cluster-api-provider-ibmcloud`.

### Approvals
- sig-ibmcloud: https://groups.google.com/forum/#!topic/kubernetes-sig-ibmcloud/K61oVd5yxv0
- sig-cluster-life-cycle: https://docs.google.com/document/d/1Ys-DOR5UsgbMEeciuG0HOgDQc8kZsaWIWJeKJ1-UfbY/edit# 
   - Please refer to meeting `Wed 1 May 2019 - 10am Pacific`

**Comment by gyliu513** [comment]
@khahmed @spzala @nikhita

**Comment by bradtopol** [comment]
+1 I support this and hope we can move quickly to approve it

**Comment by cblecker** [comment]
/assign

@gyliu513 Can you please add me as an "admin" of the source repo please? I can start running through the pre-requisites to moving.

Do you have a specific time frame you're looking to get this migrated in?

**Comment by cblecker** [comment]
I currently see four contributors. I have verified CLA for the following users:
- @gyliu513 
- @xunpan
- @jichenjc
- @morvencao

**Comment by cblecker** [comment]
Reviewing the approvals you've linked to, sig-cluster-lifecycle has deferred to sig-ibmcloud. The sig-ibmcloud e-mail was sent around the time that this was opened.

Please advise when there is sufficient sig consensus. Typically this is done with a consensus period (usually between 72 hours and a week, but solely at the sig's discretion). The idea is to ensure that the sig has consensus before adopting a piece of outside code.

**Comment by cblecker** [comment]
@nikhita @justaugustus Would one of you mind running a FOSSA scan?

**Comment by gyliu513** [comment]
@cblecker thanks for the quick response for this, really appreciate this! I have added you as admin for the project at https://github.com/multicloudlab/cluster-api-provider-ibmcloud/pull/100

I think I can approval from @khahmed @spzala soon ;-)

**Comment by cblecker** [comment]
Oh, I don't need to be in an OWNERS file, what I need is direct GitHub admin access.

You can follow the directions here: https://help.github.com/en/articles/adding-outside-collaborators-to-repositories-in-your-organization, selecting "admin" at the last step when you are choosing a permission level.

**Comment by gyliu513** [comment]
@cblecker Done ;-)

> Do you have a specific time frame you're looking to get this migrated in?

@cblecker it would be great if we can finish the migration early next week, we want to announce this in the coming KubeCon EU for sig-ibmcloud intro & deep dive.

**Comment by khahmed** [comment]
+1 I approve

**Comment by nikhita** [comment]
> @nikhita @justaugustus Would one of you mind running a FOSSA scan?

Hmm, I'm not entirely sure how to run a FOSSA scan on a non-Kubernetes repo... @justaugustus probably knows about this better. :)

**Comment by dims** [comment]
I was able to run one @nikhita @cblecker 
https://app.fossa.com/projects/git%2Bgitlab.com%2Fdavanum%2Fcluster-api-provider-ibmcloud/refs/branch/master/baf9978932fcef7570eebc3f08663f0ac35eb82a/issues/licensing?filter=policy_flag

There were 2 issues flagged, both in docker/docker repository (deep scan) and both of them were spurious as well. (and we don't import or use those files in this repo).

**Comment by gyliu513** [comment]
Thanks @dims , so no action is need from us for the FOSSA scan, right?

**Comment by dims** [comment]
@gyliu513 correct.

**Comment by spzala** [comment]
+1 from sig-ibmcloud

**Comment by spzala** [comment]
> @cblecker thanks for the quick response for this, really appreciate this! I have added you as admin for the project at [multicloudlab/cluster-api-provider-ibmcloud#100](https://github.com/multicloudlab/cluster-api-provider-ibmcloud/pull/100)
> 
> I think I can get approval from @khahmed @spzala soon ;-)

Done. This is great! Thanks all @gyliu513 @cblecker @dims @nikhita

**Comment by mdelder** [comment]
👍 LGTM.

**Comment by cblecker** [comment]
Opened PR to get the initial teams created: https://github.com/kubernetes/org/pull/784

**Comment by cblecker** [comment]
Okay, so the only item remaining is explicit consensus from the sig.

@spzala @khahmed: Please advise when you feel the sig has had enough time to achieve consensus to adopt this code.

**Comment by gyliu513** [comment]
Wow, really great progress, thanks @cblecker !

I think sig-ibmcloud is ready to adopt this code, @khahmed @spzala , can you please help confirm? Thanks.

**Comment by spzala** [comment]
@cblecker thanks for moving it quick!! The sig is under consensus and two of three sig leads (@khahmed  and myself) has already given +1 here. Hope that sounds good enough? Please let me know if all three leads are needed - the third lead is aware of the work but not reachable right now. I will request him to add his approval in the this issue soon he is available. Thanks!

**Comment by cblecker** [comment]
The migration part is now done. The automation and stuff may take up to 24 h to run and set up things like branch protection and labels.

All direct collaborator access has been revoked. If direct write or admin access is needed, please submit PRs to add usernames to the provisioned teams:
https://github.com/kubernetes/org/blob/c3ce94d4b8b51fd232be3dcc352fc09d45e94db9/config/kubernetes-sigs/sig-ibmcloud/teams.yaml#L1-L11

Can you please also submit a PR to update sigs.yaml in the community repo with the details of this repository?

**Comment by gyliu513** [comment]
@cblecker just created a PR to add more maintainers at https://github.com/kubernetes/org/pull/785

For the PR of updating sig.yaml, do you mean adding the project to https://github.com/kubernetes/community/blob/master/sig-ibmcloud/README.md ? If so, I want to update it after the repo was created as it will request the link of the kubernetes-sigs ibmcloud repo.

**Comment by nikhita** [comment]
>  If so, I want to update it after the repo was created as it will request the link of the kubernetes-sigs ibmcloud repo, comments?

@gyliu513 repo has already been migrated :)

Please see https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud. Also, https://github.com/multicloudlab/cluster-api-provider-ibmcloud will automatically redirect to the kubernetes-sigs repo.

**Comment by nikhita** [comment]
> For the PR of updating sig.yaml, do you mean adding the project to https://github.com/kubernetes/community/blob/master/sig-ibmcloud/README.md and also update https://github.com/kubernetes/community/blob/master/sigs.yaml#L1181 ?

To answer this part -- yes, you'll need to add the repo to sigs.yaml and then run `make generate`. This will automatically update the readme. :)

**Comment by gyliu513** [comment]
Thanks @nikhita , created a PR for ibmcloud at https://github.com/kubernetes/community/pull/3669 , so I think we can close this issue now?

**Comment by nikhita** [comment]
@gyliu513 let's close this after the PR gets merged :)

**Comment by nikhita** [comment]
Closing since https://github.com/kubernetes/community/pull/3669 merged.

/close
