### ISSUE TITLE
REQUEST: New membership for cwdsuzhou

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/org#786]
### GitHub Username

@cwdsuzhou

### Organization you are requesting membership in
kubernetes
kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@msau42 
@gnufied 
@jingxu97

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/76940
https://github.com/kubernetes/kubernetes/pull/76894
https://github.com/kubernetes/kubernetes/pull/76781
https://github.com/kubernetes/kubernetes/pull/76647
https://github.com/kubernetes/kubernetes/pull/76646
https://github.com/kubernetes/kubernetes/pull/76536
https://github.com/kubernetes/kubernetes/pull/76333
https://github.com/kubernetes/kubernetes/pull/76378
https://github.com/kubernetes/kubernetes/pull/75021
https://github.com/kubernetes/kubernetes/pull/75309
https://github.com/kubernetes/kubernetes/pull/74941
https://github.com/kubernetes-csi/external-provisioner/pull/260
https://github.com/kubernetes-csi/external-provisioner/pull/236
https://github.com/kubernetes-csi/external-resizer/pull/30

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/75230
https://github.com/kubernetes/kubernetes/issues/75512
https://github.com/kubernetes/kubernetes/issues/74790
- SIG projects I am involved with
kubernetes
kubernetes-csi/external-provisioner && kubernetes-csi/external-resizer

**Comment by gnufied** [comment]
+1 from me.

**Comment by msau42** [comment]
+1

**Comment by mrbobbytables** [comment]
@cwdsuzhou, thank you for all your contributions so far \o/

I've created PR #788  to add you to both the Kubernetes  and Kubernetes-csi Orgs. Once that gets merged, you should get a membership invite notification from both them.

Welcome to @kubernetes! 🎉

/assign

**Comment by cwdsuzhou** [comment]
Thanks @mrbobbytables @msau42 @gnufied @jingxu97

**Comment by cwdsuzhou** [comment]
@mrbobbytables Due  2-FA change, I was removed from the Kubernetes ORG, can you help me rejoin. Thank you.

![image](https://github.com/user-attachments/assets/72fbc19a-a266-44a9-a34e-13a124544d9b)

**Comment by mrbobbytables** [comment]
You should get an invite again within 24hrs once 2fa is reenabled 👍

**Comment by cwdsuzhou** [comment]
> @mrbobbytables Due 2-FA change, I was removed from the Kubernetes ORG, can you help me rejoin. Thank you.

thank you
