### ISSUE TITLE
REQUEST: New membership for morvencao

### ISSUE THREAD

**Issue by morvencao** [kubernetes/org#789]
### GitHub Username
@morvencao

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@gyliu513 
@xunpan

### List of contributions to the Kubernetes project
- SIG projects I am involved with

cluster-api-provider-ibmcloud

Help to setup the repo https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud and currently I'm one of reviewer, see https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/OWNERS_ALIASES#L38

![image](https://user-images.githubusercontent.com/5468682/57187371-1bf21f80-6f20-11e9-9af6-c449fcde6016.png)

**Comment by gyliu513** [comment]
+1, thanks @morvencao for your contribution to cluster api provider for IBM Cloud.

**Comment by xunpan** [comment]
+1  @morvencao, thanks for your contribution to IBM Cloud provider project. Expect more contributions from you to the community.

**Comment by justaugustus** [comment]
@morvencao -- before we can process this, you'll need one more non-IBM sponsor. See our sponsor requirements here: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by k82cn** [comment]
+1 , just went through morvencao@'s contribution, that's ok to me for k/sigs :)

**Comment by mrbobbytables** [comment]
Thanks for stepping in @k82cn :)

With that @morvencao, thanks for all your help with the ibmcloud cluster api!

I've created PR #796  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
