### ISSUE TITLE
Need repo permission on k/ingress-gce for spencerhance@

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/org#795]
### Organization or repository
e.g. kubernetes/ingress-gce

### Users effected
spencerhance

### Describe the issue
spencerhance is part of the weekly release rotation and needs permissions on the repository in order to push new tags and create Github releases.

**Comment by nikhita** [comment]
/unassign @cblecker 
/assign

Looks like @spencerhance isn't a member of the @kubernetes GitHub org.

@spencerhance can you [apply for membership](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) by creating an issue on this repo? Once you are added to the org, you can be added to a team. :+1:

**Comment by spencerhance** [comment]
Sounds good!  Working on finding an external sponsor and then I'll submit the application.

**Comment by cblecker** [comment]
@spencerhance Once your membership application is handled and you are a member of the org, you can request the right permissions by opening a PR to add your user to this team: https://github.com/kubernetes/org/blob/b5b633c78eadb29d037dc8353c53b63c5e6841b7/config/kubernetes/org.yaml#L1305-L1315

I'm going to close this issue out as you should have all the details you need to action this one. Thanks!
