### ISSUE TITLE
Request for new SIG-CLI kubernetes-sigs repo - cli-utils

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes/org#798]
### New Repo, Staging Repo, or migrate existing
new repo

### Requested name for new repository
cli-utils

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@pwittrock
@seans3
@soltysh

### If not a staging repo, who should have write access
@monopole
@liggitt
@Liujingfang1
@barney-s

### If not a staging repo, who should be listed as approvers in OWNERS
@pwittrock
@seans3
@soltysh

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@pwittrock
@seans3
@soltysh

### What should the repo description be
This repo will contains binaries that built from libraries in cli-runtime.

### What SIG and subproject does this fall under in sigs.yaml
This repo is under sig-cli for the subproject `kubectl`.
The repo will have commands for apply, status, prune and set for data-driven for dynamic commands.

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)
https://github.com/kubernetes/org/issues/662
https://groups.google.com/forum/#!topic/kubernetes-sig-cli/FMl1A8RkK6w
kubernetes/kubectl#622

**Comment by Liujingfang1** [comment]
cc @soltysh
cc @pwittrock 
cc @seans3
cc @juanvallejo

**Comment by pwittrock** [comment]
@Liujingfang1 Thanks.  Lets follow up on this at the next SIG meeting, and send an email out to the SIG.  Developing utilities for apply independent of kubectl has been requested by the community a number of times, so this is consistent with that.

**Comment by Liujingfang1** [comment]
@pwittrock Sounds good to me. Sent out the email and updated the agenda for next SIG meeting.

**Comment by Liujingfang1** [comment]
@pwittrock  As discussed on the SIG meeting, we can move the libraries we developed in cli-experimental into cli-runtime. cli-utils will become a place to publish some commands from cli-runtime as actual binaries.

**Comment by nikhita** [comment]
@Liujingfang1 if this was approved in the meeting, could you link the relevant part in the meeting notes here? thanks!

**Comment by Liujingfang1** [comment]
@nikhita [Cli-runtime will be the library, whereas cli-utils will become a place where we can publish some commands from cli-runtime as actual binaries. This will prolong the process a bit, but we’ll ensure proper API stability due to dogfooding ourselves.](https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#)

**Comment by nikhita** [comment]
@Liujingfang1 awesome, thank you! I'll create the repo in a while. :+1:

**Comment by nikhita** [comment]
Created https://github.com/kubernetes-sigs/cli-utils :tada: 

Also created https://github.com/kubernetes/org/pull/802 to add teams for the repo. Once the PR merges and the postsubmit runs, I'll grant access to the teams.

@Liujingfang1 can you create a PR to add this to sigs.yaml in the community repo? Thanks!

Once access has been granted + the community repo PR has merged, we can close this issue.

**Comment by Liujingfang1** [comment]
@nikhita Thank you. I created a PR to update the sigs.yaml https://github.com/kubernetes/community/pull/3695

**Comment by nikhita** [comment]
Granted access to the relevant teams.
