### ISSUE TITLE
REQUEST: New membership for @sftim

### ISSUE THREAD

**Issue by sftim** [kubernetes/org#799]
### GitHub Username
@sftim

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Rajakavitha1
- @zparnold 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pull/77405
  https://github.com/kubernetes/website/pull/10899
  https://github.com/kubernetes/website/pull/12495
  https://github.com/kubernetes/website/pull/12600
  https://github.com/kubernetes/website/pull/12602
  https://github.com/kubernetes/website/pull/12603
  https://github.com/kubernetes/website/pull/12607
  https://github.com/kubernetes/website/pull/12611
  https://github.com/kubernetes/website/pull/12613
  https://github.com/kubernetes/website/pull/12614
  https://github.com/kubernetes/website/pull/12622
  https://github.com/kubernetes/website/pull/12647
  https://github.com/kubernetes/website/pull/12667
  https://github.com/kubernetes/website/pull/12668
  https://github.com/kubernetes/website/pull/12669
  and [more](https://github.com/kubernetes/website/pulls?page=1&q=is%3Apr+author%3Asftim&utf8=%E2%9C%93)
- Issues responded to
   https://github.com/kubernetes/website/issues/12810
   https://github.com/kubernetes/website/issues/12664
   https://github.com/kubernetes/website/issues/12785
   https://github.com/kubernetes/website/issues/12740
   https://github.com/kubernetes/website/issues/12587
   https://github.com/kubernetes/website/issues/12881
   https://github.com/kubernetes/website/issues/12681
   https://github.com/kubernetes/website/issues/12341
   https://github.com/kubernetes/website/issues/12467
   https://github.com/kubernetes/website/issues/12631
   https://github.com/kubernetes/website/issues/12655
   and more
- SIG projects I am involved with
  [sig-docs](https://github.com/kubernetes/community/tree/master/sig-docs)

**Comment by zparnold** [comment]
/lgtm
@sftim Has been a key contributor to many (as you can tell) Sig Docs initiatives. He's gonna be a rock solid contributor!

**Comment by zacharysarah** [comment]
+1, happy to sponsor @sftim!

**Comment by Rajakavitha1** [comment]
+1, @sftim has been a very enthusiastic and a dedicated contributor to SIG-Docs. The PRs and the issues that @sftim raised reflect his contributions in creating technically accurate and quality Kubernetes documentation.

Welcome @sftim !!!!!

**Comment by DanyC97** [comment]
w00000t !! 

Welcome to the happy family @sftim !!
(now i just need to keep up with you ;) )

**Comment by mrbobbytables** [comment]
@sftim , thank you for all your help with kubernetes website :D

I've created PR #803  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
