### ISSUE TITLE
Move jeefy/relnotes into k-sigs/release-notes

### ISSUE THREAD

**Issue by jeefy** [kubernetes/org#801]
### New Repo, Staging Repo, or migrate existing
Migrate existing: https://github.com/jeefy/relnotes

### Requested name for new repository
release-notes

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
jeefy, marpaia, onyiny-ang

### If not a staging repo, who should have write access
jeefy, marpaia, onyiny-ang, sig-release-leads, release-engineering

### If not a staging repo, who should be listed as approvers in OWNERS
jeefy, marpaia, onyiny-ang, sig-release-leads

### If not a staging repo, who should be listed in SECURITY_CONTACTS
jeefy, marpaia, onyiny-ang

### What should the repo description be
This repo contains tooling around generating and publishing release notes for the Kubernetes organization.

### What SIG and subproject does this fall under in sigs.yaml
sig-release / release-engineering?

### Approvals

Several discussions in #sig-release.

Talk has occurred in a SIG-release meeting https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit

cc @justaugustus 

### Additional context for request
This is looking to consolidate the release-notes-related code by:

1) Migrating the Angular relnotes app currently hosted by me
2) Moving the release-notes specific code out of k/release and into its own repo (outside the scope of this issue but, additional context)

If I missed anything just lemme know :)

**Comment by nikhita** [comment]
/assign

:tada: :tada: :tada:

**Comment by nikhita** [comment]
> Talk has occurred in a SIG-release meeting https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit

I can't find the relevant part in the meeting notes (very probable I missed it). Can you add the relevant excerpt here? :grimacing:

**Comment by justaugustus** [comment]
Awesome, was just about to assign you, Nikhita.
Thanks for moving this forward and for the work that you've been doing, @jeefy!

For SIG Release:
/lgtm
/approve

**Comment by nikhita** [comment]
That'll do it :)

**Comment by nikhita** [comment]
@jeefy you'll need to add me as an admin to the repo...but from previous migrations, I found that you can't add someone as an admin to a personal repo. :neutral_face: 

You'll need to migrate the repo over to a dummy org and then add me as an org admin. I can do the repo transfer after that.

**Comment by jeefy** [comment]
Done! :)

**Comment by nikhita** [comment]
Thanks, @jeefy!

I ran a FOSSA scan on the repo: https://app.fossa.com/projects/git%2Bgithub.com%2Fnikhita%2Frelnotes/refs/branch/master/088719d55931d7dd5f18436ea280fc9a62a94286 (I'm not sure if this link is publicly visible?)

There is one issue flagged by it. relnotes uses the `showdown` dependency: https://github.com/kubernetes-purgatory/relnotes/blob/088719d55931d7dd5f18436ea280fc9a62a94286/package.json#L36.

showdown was originally licensed under GPL v2.0, but has now moved to MIT. See https://github.com/showdownjs/showdown/issues/659 for related discussion and commit https://github.com/showdownjs/showdown/commit/33bba54535d6fcdde5c82d2ec4d7a3bd951b5bb9 which updated it.

The version that `relnotes` uses is 1.9.0 which was _before_ this commit was merged. And sadly, it looks like there hasn't been another release cut after 1.9.0 (which was in November): https://github.com/showdownjs/showdown/releases

Looks like the next step is to ask the showdown maintainers to cut a release?
@jeefy or are there any other alternative options?

**Comment by jeefy** [comment]
Easiest path is probably alternatives. I'll investigate and try to PR in a different library.

**Comment by jeefy** [comment]
Actually, question on preference:

I could (and have) found a couple alternatives, but I could also just pin the version to a specific commit and, when they cut a new version, swap back to using official releases. Is there any precedence set for this? If not, I'll probably just push an updated package(-lock).json with a pinned recent commit.

Thoughts?

**Comment by justaugustus** [comment]
@jeefy -- I was just about to suggest that. If pinning to a commit works it in the interim, let's do that to move this forward. We can explore alternatives, if need be in the future, but I leave that decision to you, @marpaia, and @onyiny-ang, as the maintainers.

**Comment by jeefy** [comment]
If I could :gandalf: in a response, I would. Thanks!

**Comment by jeefy** [comment]
Welp... Pinning to the commit won't work for various reasons. So that's a sad day. I'll work on replacing it and update the thread when complete.

**Comment by jeefy** [comment]
Replaced `showdown` with `ngx-markdown`. @nikhita Run fossa against it again and see if things look green. :)

**Comment by nikhita** [comment]
FOSSA was happy :)

Created https://github.com/kubernetes-sigs/release-notes :tada: 

Also created https://github.com/kubernetes/org/pull/808 to create teams and https://github.com/kubernetes/community/pull/3703 to add it to sigs.yaml.

**Comment by justaugustus** [comment]
Looks like PRs are all merged, so everything should be squared away.
Thanks everyone!

/close
