### ISSUE TITLE
REQUEST: New membership for @hpandeycodeit

### ISSUE THREAD

**Issue by hpandeycodeit** [kubernetes/org#805]
### GitHub Username
@hpandeycodeit

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tstromberg 
- @neolit123 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
https://github.com/kubernetes/minikube/pull/4080
https://github.com/kubernetes/minikube/pull/4177
https://github.com/kubernetes/minikube/pull/3625
https://github.com/kubernetes/kubernetes/pull/74628
https://github.com/kubernetes/kubernetes/pull/74676
https://github.com/kubernetes/website/pull/14217
https://github.com/kubernetes/website/pull/13736
https://github.com/kubernetes/website/pull/12868
https://github.com/kubernetes/website/pull/12649
https://github.com/kubernetes/website/pull/12591
https://github.com/kubernetes/website/pull/12504
https://github.com/kubernetes/test-infra/pull/11486
https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/17
https://github.com/kubernetes-incubator/external-dns/pull/899

- Issues responded to
https://github.com/kubernetes/minikube/issues/3642
https://github.com/kubernetes/minikube/issues/4117
https://github.com/kubernetes/minikube/issues/3760

- SIG projects I am involved with
k8s-container-image-promoter
testing

**Comment by neolit123** [comment]
thanks for the contributions @hpandeycodeit 
+1

**Comment by tstromberg** [comment]
I endorse this membership. Thank you @hpandeycodeit !

**Comment by mrbobbytables** [comment]
Hey there @hpandeycodeit , thank you for all your contributions to the project so far :)

I've created PR #807  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
