### ISSUE TITLE
REQUEST: New membership for diversario

### ISSUE THREAD

**Issue by diversario** [kubernetes/org#806]
### GitHub Username
@diversario

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @fejta 
- @stevekuznetsov

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - [kubernetes/test-infra/12448](https://github.com/kubernetes/test-infra/pull/12448)
  - [kubernetes/test-infra/12389](https://github.com/kubernetes/test-infra/pull/12389)
  - [kubernetes/test-infra/12358](https://github.com/kubernetes/test-infra/pull/12358)
  - [kubernetes/test-infra/12355](https://github.com/kubernetes/test-infra/pull/12355)
  - [kubernetes/test-infra/12191](https://github.com/kubernetes/test-infra/pull/12191)
  - [kubernetes/test-infra/12171](https://github.com/kubernetes/test-infra/pull/12171)
  - [kubernetes/test-infra/12162](https://github.com/kubernetes/test-infra/pull/12162)
  - [kubernetes/test-infra/12003](https://github.com/kubernetes/test-infra/pull/12003)
  - [kubernetes/test-infra/11907](https://github.com/kubernetes/test-infra/pull/11907)
- Issues responded to
  - [kubernetes/test-infra/12461](https://github.com/kubernetes/test-infra/issues/12461)
- SIG projects I am involved with
  - [sig-testing](https://github.com/kubernetes/community/tree/master/sig-testing)

**Comment by fejta** [comment]
Lgtm

**Comment by stevekuznetsov** [comment]
Excited for this! LGTM

**Comment by mrbobbytables** [comment]
@diversario thank you for all your help with test-infra! :)

I've created PR #807  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by diversario** [comment]
Thank you, everybody! 😄
