### ISSUE TITLE
REQUEST: New membership for pigletfly

### ISSUE THREAD

**Issue by pigletfly** [kubernetes/org#81]
### GitHub Username
@pigletfly

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zhangxiaoyu-zidif 
- @xiangpengzhao 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

  https://github.com/kubernetes/kubernetes-docs-zh/pull/75
  https://github.com/kubernetes/kubernetes-docs-zh/pull/95
  https://github.com/kubernetes/kubernetes-docs-zh/pull/102
  https://github.com/kubernetes/kubernetes-docs-zh/pull/105
  https://github.com/kubernetes/kubernetes-docs-zh/pull/104
  https://github.com/kubernetes/kubernetes-docs-zh/pull/109
  https://github.com/kubernetes/kubernetes-docs-zh/pull/108
  https://github.com/kubernetes/kubernetes-docs-zh/pull/189
  https://github.com/kubernetes/kubernetes-docs-zh/pull/190
  https://github.com/kubernetes/kubernetes-docs-zh/pull/207
  https://github.com/kubernetes/kubernetes-docs-zh/pull/209
  https://github.com/kubernetes/website/pull/7196
  https://github.com/kubernetes/kubernetes/pull/59195

- Issues responded to
- SIG projects I am involved with
  k/kubernetes-docs-zh
  k/website

**Comment by zhangxiaoyu-zidif** [comment]
+1

**Comment by xiangpengzhao** [comment]
+1
@pigletfly helps a lot on translating docs to Chinese.

**Comment by spiffxp** [comment]
invite sent manually, welcome!
