### ISSUE TITLE
REQUEST: New membership for lbernail

### ISSUE THREAD

**Issue by lbernail** [kubernetes/org#811]
### GitHub Username
@lbernail

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @m1093782566 
- @yastij 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/75295
https://github.com/kubernetes/kubernetes/pull/75283
https://github.com/kubernetes/kubernetes/pull/72361
https://github.com/kubernetes/kubernetes/pull/72106
https://github.com/kubernetes/kubernetes/pull/71895
https://github.com/kubernetes/kubernetes/pull/71834
https://github.com/kubernetes/kubernetes/pull/71515
https://github.com/kubernetes/ingress-gce/pull/370
https://github.com/kubernetes/kubernetes/pull/65388

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/76664
https://github.com/kubernetes/kubernetes/issues/72236
https://github.com/kubernetes/kubernetes/issues/67730
https://github.com/kubernetes/kubernetes/issues/76544
https://github.com/kubernetes/kubernetes/issues/75290
https://github.com/kubernetes/kubernetes/issues/73154
https://github.com/kubernetes/kubernetes/issues/71596
https://github.com/kubernetes/kubernetes/issues/71071

- SIG projects I am involved with
sig-network

**Comment by yastij** [comment]
+1

**Comment by m1093782566** [comment]
+100

**Comment by mrbobbytables** [comment]
Hey there @lbernail , thank you for all your contributions so far :)

I've created PR #820  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
