### ISSUE TITLE
Request GitHub Package Registry beta for kubernetes-sigs org

### ISSUE THREAD

**Issue by detiber** [kubernetes/org#812]
### Organization or repository
kubernetes-sigs

### Name of integration
GitHub Package Registry and GitHub Actions

### Link to integration website
https://github.com/features/package-registry
https://github.com/features/actions

### Describe what is attempting to be accomplished
Request GitHub Package Registry and GitHub Actions be enabled for the kubernetes-sigs org

### Additional context for request
This will help SIG subprojects with the automation and publishing of container images, this is something that could be used in conjunction with or in place of the image promoter work being done.

**Comment by nikhita** [comment]
/assign @spiffxp 
I believe Aaron already signed up kubernetes and kubernetes-sigs for package-registry.

**Comment by spiffxp** [comment]
Yeah I signed us up within a few hours of the announcement, we'll let you know when we hear more

**Comment by mkumatag** [comment]
> This will help SIG subprojects with the automation and publishing of container images, this is something that could be used in conjunction with or in place of the image promoter work being done.

Good idea but not really how this behaves for non-amd64 architecture images!

**Comment by nikhita** [comment]
Looks like this is enabled now:

- https://github.com/orgs/kubernetes/packages
- https://github.com/orgs/kubernetes-sigs/packages

**Comment by chuckha** [comment]
Following the registry instructions I end up with:

`unsupported: GitHub Package Registry is not enabled for user/org "kubernetes-sigs".Unfortunately, we can't accept package uploads.`

This is for a newly created (this/last week): https://github.com/kubernetes-sigs/cluster-api-provider-docker. Maybe I'm missing some permissions?

**Comment by justaugustus** [comment]
@chuckha -- I believe you need `read:packages` and `write:packages` on your token scope, in addition to having write access to the repo.

**Comment by chuckha** [comment]
i definitely have those in my token scope and have admin on the repository

**Comment by justaugustus** [comment]
(none of which I've tested yet, but ref: https://help.github.com/en/articles/configuring-docker-for-use-with-github-package-registry)

**Comment by justaugustus** [comment]
I'm wondering if there's a delineation between org-scoped packages and repo-scoped ones, in which case there may be a box that @kubernetes/owners needs to check and subsequently integrate in the peribolos config.

**Comment by nikhita** [comment]
I couldn't find any such option :confused: 

But visiting https://github.com/kubernetes-sigs/cluster-api-provider-docker/packages, gives me this:

![Screenshot from 2019-06-27 19-31-17](https://user-images.githubusercontent.com/16105680/60272667-3807b100-9912-11e9-9d55-60e02bcaeb64.png)

I manually typed the URL, and couldn't find an option reach that URL through any place in the UI... :thinking: 

@chuckha are you able to see this as well and can you try clicking on the `Create new package` button and see what happens? I didn't try it yet because I wasn't sure if it'll automatically create a package :woman_shrugging:

**Comment by detiber** [comment]
When I attempted to click the `Create a new package` button it redirected to the Package Registry docs (indicating beta).

**Comment by nikhita** [comment]
@detiber thanks! Going to check with other GitHub admins on this, and will possibly write to GitHub about how to go about it. Will let you know! :+1:

**Comment by chuckha** [comment]
Yep, that's exactly what happened to me, straight to the docs. Maybe it's not enabled in my account and I just have to wait until my name is on the beta list? oh well, i'm pretty excited for this to work!

**Comment by nikhita** [comment]
I just got an email that explicitly said `Congratulations! You now have beta access to GitHub Package Registry for your account @kubernetes, @kubernetes-sigs.`.

@chuckha can you try again? Maybe it'll work now! :smile: :crossed_fingers:

**Comment by detiber** [comment]
@nikhita I now see a packages tag when going to https://github.com/kubernetes-sigs, but I still do not see it for any of the repos that I am a maintainer for (such as cluster-api or cluster-api-provider-aws). Trying to go to the packages subdirectory for a repo (https://github.com/kubernetes-sigs/cluster-api-provider-aws/packages for example) and clicking on `Create new package` still goes straight to documentation.

Out of curiosity I also tried to see if I could just create a package under the org, but there is no `Create new package` option there, I suspect that would require elevated permissions on the org.

**Comment by nikhita** [comment]
> but I still do not see it for any of the repos that I am a maintainer for (such as cluster-api or cluster-api-provider-aws).

I think this is maybe because it requires the packages to exist first? :thinking: 

> Trying to go to the packages subdirectory for a repo (https://github.com/kubernetes-sigs/cluster-api-provider-aws/packages for example) and clicking on Create new package still goes straight to documentation.

Can you try this locally without using the UI? Mainly asking because the email said this:

```
Ready to get started?

If you’d like to publish a package, make sure to read the documentation and configure your client as explained. Once you publish a package, you can find it under the “Releases” tab of your repository. 
```

> Out of curiosity I also tried to see if I could just create a package under the org, but there is no Create new package option there, I suspect that would require elevated permissions on the org.

Heh, I can't see it either. Maybe this would show all packages that exist across all repos in the org?

If this doesn't work locally as described in https://help.github.com/en/articles/configuring-docker-for-use-with-github-package-registry, please let us know. I'll write to GitHub then. :+1:

**Comment by detiber** [comment]
@nikhita just gave it a shot and this is the error message that I get:

```
> docker push docker.pkg.github.com/kubernetes-sigs/cluster-api/cluster-api-controller:v0.1.4
The push refers to repository [docker.pkg.github.com/kubernetes-sigs/cluster-api/cluster-api-controller]
6770958e7df7: Preparing 
01092e5921c5: Preparing 
unsupported: GitHub Package Registry is not enabled for user/org "kubernetes-sigs".Unfortunately, we can't accept package uploads.
```

**Comment by nikhita** [comment]
@detiber :(

I'll write to GitHub and let you know more when I hear back. Thanks for bearing with the back and forth on this!

**Comment by detiber** [comment]
np, thanks for bearing with me through the back and forth

**Comment by nikhita** [comment]
@chuckha @detiber can you try again? :grimacing: 

Heard back from GitHub:

```
Apologies for the trouble, our onboarding process appears to have failed silently at the point of adding the account(s) into the beta, and therefore triggered the notifications.

We're going to improve this process going forwards to catch this scenario.

Have fun using the package registry and please let us know if you face any further issues, have any questions or any feedback about the beta.
```

**Comment by detiber** [comment]
@nikhita omg, it works, it works!

Thank you!

**Comment by nikhita** [comment]
Woot! :tada: :tada: :tada: :tada: 

Closing this as done!

**Comment by nikhita** [comment]
Just as a followup the `/packages` endpoint for the org shows all the packages across all repos in the org: https://github.com/orgs/kubernetes-sigs/packages

**Comment by monotek** [comment]
Could somebody point me to the documentation how to use the registry?
We like to use it for the monitoring images of the EFK stack.

For more information see discussion in https://github.com/kubernetes/kubernetes/pull/79390 and https://github.com/kubernetes/kubernetes/issues/79432

**Comment by nikhita** [comment]
@monotek https://help.github.com/en/articles/configuring-docker-for-use-with-github-package-registry :)

**Comment by cblecker** [comment]
I'd caution beta use of this. There are caveats like you can't delete something you push up: https://help.github.com/en/articles/about-github-package-registry#deleting-a-package

**Comment by monotek** [comment]
Thanks for the link :-)
Need to wait for an own repo in klubernetes-sigs to get startet...

**Comment by nikhita** [comment]
Just posting this here in case anyone stumbles upon this issue:

The current recommendation is to request a staging repo for your sig/subproject. Instructions for it are detailed in this k-dev email: https://groups.google.com/forum/#!topic/kubernetes-dev/ZqdjjDIAISY (thanks @dims!).
