### ISSUE TITLE
Rename kubernetes-sigs/federation-v2 to kubernetes-sigs/kubefed

### ISSUE THREAD

**Issue by pmorie** [kubernetes/org#818]
### New Repo, Staging Repo, or migrate existing

This request is to rename the [`kubernetes-sigs/federation-v2`](https://github.com/kubernetes-sigs/federation-v2) repository to `kubernetes-sigs/kubefed`. This decision was made by the Federation WG, a subproject of SIG multicluster during the [May 1 2019](https://docs.google.com/document/d/1v-Kb1pUs3ww_x0MiKtgcyTXCAuZlbVlz4_A9wS3_HXY/edit#heading=h.jwr083sbbnt2) working group meeting. Notice was previously provided to the [SIG mailing list](https://groups.google.com/forum/#!topic/kubernetes-sig-multicluster/HHyqrfFHQiw) with a tentative date of May 15 2019.

### Requested name for new repository
kubefed

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
existing list

### If not a staging repo, who should have write access
existing list

### If not a staging repo, who should be listed as approvers in OWNERS
existing list

### If not a staging repo, who should be listed in SECURITY_CONTACTS
existing list

### What should the repo description be
by default we will set it to "created due to (link to this issue)"; should be inapplicable because this is a rename

### What SIG and subproject does this fall under in sigs.yaml
This is the rename of an existing repository, which is a subproject of SIG multicluster.

### Approvals

- This decision was made by the Federation WG, a subproject of SIG multicluster during the [May 1 2019](https://docs.google.com/document/d/1v-Kb1pUs3ww_x0MiKtgcyTXCAuZlbVlz4_A9wS3_HXY/edit#heading=h.jwr083sbbnt2) working group meeting
- Notice was previously provided to the [SIG mailing list](https://groups.google.com/forum/#!topic/kubernetes-sig-multicluster/HHyqrfFHQiw) with a tentative date of May 15 2019.

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
Any additional information or context to describe the request.

**Comment by cblecker** [comment]
/assign

Shouldn't be a problem renaming this whenever you're ready. I have #819 to update the groups, and I've verified there aren't any other prow configs that need to be moved.

**Comment by pmorie** [comment]
@cblecker Thanks. I think we are good to pull the trigger now. We are near the reasonable end of the working day now, and the working group would get an extra full working day with this finished if we were to do it now.

**Comment by cblecker** [comment]
Rename complete. Just need sigs.yaml updated, and then this can be closed.

**Comment by nikhita** [comment]
sigs.yaml is updated.

/close
