### ISSUE TITLE
Create repositories for accepted out of tree cloud provider implementations

### ISSUE THREAD

**Issue by calebamiles** [kubernetes/org#82]
### New Repo, or migrate existing
new repositories

### Requested name for new repository
- cloud-provider-alibaba-cloud
- cloud-provider-digitalocean
- cloud-provider-baiducloud

### Which Organization should it reside
- kubernetes (ideally, like other cloud providers but `kubernetes-sigs` is an acceptable temporary home)

### Who should be provided access to this repository
- sig-cloud-provider-leads will handle access but probably sensible to have
- andrewsykim
- hogepodge
- jagosan

as repo admins to ease onboarding

### Approvals

- https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/providers/0020-cloud-provider-alibaba-cloud.md#repositories
- https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/providers/0021-cloud-provider-digitalocean.md#repositories
- https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/providers/0022-cloud-provider-baiducloud.md#repositories

### Additional context for request
Any additional information or context to describe the request.

**Comment by calebamiles** [comment]
[SIG Arch request](https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/soeIadIeMCs)

**Comment by calebamiles** [comment]
Creating the repo for ali cloud per [discussion][]

[discussion]: https://groups.google.com/d/msg/kubernetes-sig-architecture/soeIadIeMCs/3cw7JhYgCQAJ

**Comment by cblecker** [comment]
@calebamiles @andrewsykim What's the status of this one? Looks like alibaba was created, but not the other two.. and I'm not sure the others meet the bar yet that @andrewsykim laid out in the linked sig-arch discussion.

**Comment by andrewsykim** [comment]
@cblecker yeah digitalocean & baidu cloud are still pending, will update here once those requirements are met :)

**Comment by cblecker** [comment]
This doesn't seem to have movement.. can we close this out and open a new issue when those providers are ready?

/lifecycle stale

**Comment by cheftako** [comment]
Do we have anything left to do on this?

**Comment by andrewsykim** [comment]
I think we can close this for now. I don't think DigitalOcean & Baidu cloud will be addressing this anytime soon. We can re-open if they want to revisit this in the future :) 

/close
