### ISSUE TITLE
REQUEST: New membership for inductor

### ISSUE THREAD

**Issue by inductor** [kubernetes/org#822]
### GitHub Username
@inductor

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nasa9084
- @cstoku 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
Translation PRs of Kubernetes document into Japanese
https://github.com/kubernetes/website/pull/12060
https://github.com/kubernetes/website/pull/12065
https://github.com/kubernetes/website/pull/12068
https://github.com/kubernetes/website/pull/12070
https://github.com/kubernetes/website/pull/12071
https://github.com/kubernetes/website/pull/12074
https://github.com/kubernetes/website/pull/12694
https://github.com/kubernetes/website/pull/12866
https://github.com/kubernetes/website/pull/13366
https://github.com/kubernetes/website/pull/13367
- Issues responded to
- SIG projects I am involved with
kubernetes/sig-docs

**Comment by nasa9084** [comment]
+1

**Comment by cstoku** [comment]
+1

Thank you for your contribution!!:+1:

**Comment by mrbobbytables** [comment]
@inductor thank you for all your help with the japanese localization efforts :)

I've created PR #827 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
