### ISSUE TITLE
REQUEST: New membership for juandiegopalomino

### ISSUE THREAD

**Issue by juandiegopalomino** [kubernetes/org#826]
### GitHub Username
e.g. (at)example_user
@juandiegopalomino

### Organization you are requesting membership in
e.g. (at)kubernetes
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zacharysarah 
- @jimangel 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
   https://github.com/kubernetes/website/pull/12409
- Issues responded to
   https://github.com/kubernetes/website/issues/12081
- SIG projects I am involved with
   kubernetes/sig-docs

**Comment by zacharysarah** [comment]
+1, JD is an active and present contributor working to improve content.

**Comment by jimangel** [comment]
+1, JD is always looking for new ways to help sig-docs!

**Comment by mrbobbytables** [comment]
@juandiegopalomino thank you for all your help with sig-docs :)

I've created PR #827  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
