### ISSUE TITLE
REQUEST: New membership for piotrmiskiewicz

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kubernetes/org#830]
### GitHub Username
@piotrmiskiewicz

### Organization you are requesting membership in
@kubernetes-incubator

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jberkhahn
- @jboyd01

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
https://github.com/kubernetes-incubator/service-catalog/pull/2333
https://github.com/kubernetes-incubator/service-catalog/pull/2337
https://github.com/kubernetes-incubator/service-catalog/pull/2370
https://github.com/kubernetes-incubator/service-catalog/pull/2577
https://github.com/kubernetes-incubator/service-catalog/pull/2591

- Issues responded to
https://github.com/kubernetes-incubator/service-catalog/issues/2576
https://github.com/kubernetes-incubator/service-catalog/issues/2563
https://github.com/kubernetes-incubator/service-catalog/issues/1772
https://github.com/kubernetes-incubator/service-catalog/issues/2276

- SIG projects I am involved with
service-catalog

**Comment by jberkhahn** [comment]
I haven't done it the new way yet, do I just approve the PR?
/lgtm

**Comment by mrbobbytables** [comment]
just a gentle reminder ping for @jboyd01 👍

**Comment by soltysh** [comment]
I can vouch for this guy as well :+1:

**Comment by mrbobbytables** [comment]
Thanks for stepping in @soltysh 👍 

@piotrmiskiewicz, thank you for all your help with the service catalog. :)

I've created PR #867  to add you to the Kubernetes-incubator Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-incubator! 🎉

/assign
