### ISSUE TITLE
REQUEST: New membership for @mszostok

### ISSUE THREAD

**Issue by mszostok** [kubernetes/org#832]
### GitHub Username
@mszostok

### Organization you are requesting membership in
- @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- Jonathan Berkhahn (@jberkhahn), IBM
- Carolyn Van Slyck (@carolynvs), Microsoft

### List of contributions to the Kubernetes project
- PRs created:
  - https://github.com/kubernetes/kubernetes/pull/72090
  - https://github.com/kubernetes-sigs/controller-runtime/pull/380
  - https://github.com/kubernetes/utils/pull/92
  - https://github.com/kubernetes-incubator/service-catalog/pull/2493
  - kubernetes-incubator/service-catalog#2628   
  - https://github.com/kubernetes-incubator/service-catalog/pull/2627
  - https://github.com/kubernetes-incubator/service-catalog/pull/2629
  - https://github.com/kubernetes-incubator/service-catalog/pull/2630
- PRs reviewed: 
  - https://github.com/kubernetes-incubator/service-catalog/pull/2609
  - https://github.com/kubernetes-incubator/service-catalog/pull/2580

- Issues created/commented:
  - https://github.com/kubernetes-sigs/kustomize/issues/254
  - https://github.com/kubernetes/kubernetes/issues/72088
  - https://github.com/kubernetes-incubator/service-catalog/issues/1954
  - https://github.com/kubernetes-incubator/service-catalog/issues/2492
  - https://github.com/kubernetes-incubator/service-catalog/issues/2006

- SIG projects I am involved with:
  [SIG Service Catalog](https://github.com/kubernetes-incubator/service-catalog)

**Comment by carolynvs** [comment]
Oops, maybe I’m supposed to say +1. Jonathan threw me off. 😅

**Comment by mrbobbytables** [comment]
A general ack as a plus one is all that's needed :) 👍

**Comment by mrbobbytables** [comment]
@mszostok  thank you for all your contributions so far :)

I've created PR #840  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
