### ISSUE TITLE
REQUEST: New membership for JieJhih

### ISSUE THREAD

**Issue by JieJhih** [kubernetes/org#833]
### GitHub Username
@JieJhih

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bsalamat 
- @neolit123

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/76254
https://github.com/kubernetes/kubernetes/pull/76320
https://github.com/kubernetes/kubernetes/pull/76732
https://github.com/kubernetes/kubernetes/pull/76875
https://github.com/kubernetes/kubernetes/pull/77111
https://github.com/kubernetes/kubernetes/pull/77298
https://github.com/kubernetes/kubernetes/pull/77381
https://github.com/kubernetes/kubernetes/pull/77501
https://github.com/kubernetes/kubernetes/pull/77537
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/76289
https://github.com/kubernetes/kubernetes/issues/75889
- SIG projects I am involved with
k/kubernetes

**Comment by neolit123** [comment]
+1

**Comment by bsalamat** [comment]
+1
Looking forward to seeing more contributions from @JieJhih!

**Comment by mrbobbytables** [comment]
@JieJhih thank you for all your contributions so far :)

I've created PR #834   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
