### ISSUE TITLE
REQUEST: New membership for afirth

### ISSUE THREAD

**Issue by afirth** [kubernetes/org#835]
### GitHub Username
@afirth
### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @parispittman
- @puja108

### List of contributions to the Kubernetes project
https://github.com/kubernetes-sigs/kustomize/pull/984
https://github.com/kubernetes/kops/issues/3993
https://github.com/helm/charts/pull/10255/files
https://github.com/kubernetes/kubernetes/issues/73584#issuecomment-462481514

**Comment by parispittman** [comment]
+1!! 🚀

**Comment by puja108** [comment]
+1! Thanks for your contributions

**Comment by mrbobbytables** [comment]
Hey there @afirth, unfortunately @puja108 cannot sponsor you for membership in the Kubernetes org. =/

A sponsor must be an approver or reviewer to be able to +1 a membership request ([sponsor requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements)). 

Is there someone else that might be able to sponsor you?

Thanks!

**Comment by guineveresaenger** [comment]
+1 from me! Welcome! 🎉

**Comment by mrbobbytables** [comment]
Thanks for stepping in @guineveresaenger :)

With that -- @afirth  thank you for all your contributions so far :)

I've created PR #843  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
/pony party
