### ISSUE TITLE
REQUEST: New membership for nowjean

### ISSUE THREAD

**Issue by nowjean** [kubernetes/org#837]
GitHub Username
@nowjean

Organization you are requesting membership in
@kubernetes

Requirements

[v] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
[v] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
[v] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
[v] I am actively contributing to 1 or more Kubernetes subprojects
[v] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
[v] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
Sponsors
@gochist
@ClaudiaJKang

List of contributions to the Kubernetes project

PRs authored
kubernetes/website#11092
kubernetes/website#13927
kubernetes/website#14024
kubernetes/website#14234
kubernetes/website#14237

Issues responded to
kubernetes/website#14467
kubernetes/website#11854 
kubernetes/website#13976 
kubernetes/website#14232 
kubernetes/website#14230 

SIG projects I am involved with
kubernetes/sig-docs

/area github-membership

**Comment by gochist** [comment]
+1
@nowjean Thank you for your contribution for Ko localization!

**Comment by ianychoi** [comment]
+1
I will also sponsor him :) @nowjean : Thank you for your contribution on K8s Korean localization!

**Comment by ClaudiaJKang** [comment]
👍 Thank you for contributing to Korean localization! @nowjean

**Comment by mrbobbytables** [comment]
@nowjean thank you for your help with sig-docs and the korean localization :)

I've created PR #840  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
