### ISSUE TITLE
REQUEST: New membership for chardch

### ISSUE THREAD

**Issue by chardch** [kubernetes/org#838]
### GitHub Username
@chardch

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jiayingz 
- @johnSchnake

### List of contributions to the Kubernetes project
- PRs reviewed / authored
#77699
#77035
#76401
#76156
- Issues responded to
#73948

**Comment by jiayingz** [comment]
+1

Jiaying

**Comment by mrbobbytables** [comment]
@chardch My apologies for the delay in response -- KubeCon kind of threw everything off for a bit =/

I also hate to be a stickler...but do you happen to have someone else that could sponsor you? Sponsors must be from different organizations per the [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements).

Thanks!

**Comment by chardch** [comment]
Thanks for letting me know @mrbobbytables. I'll find a sponsor from another organization.

**Comment by chardch** [comment]
Hi @johnSchnake,

Would you be willing to sponsor my kubernetes membership?

**Comment by johnSchnake** [comment]
👍 Yes I'll act as a sponsor. I'm from the VMware org and interacted with @chardch numerous times on one of his PRs.

**Comment by chardch** [comment]
Thanks, I appreciate it @johnSchnake!

**Comment by mrbobbytables** [comment]
Hey there @chardch, thank you for all your contributions so far :)

I've created PR #871  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
