### ISSUE TITLE
Please promote me to a maintainer of kubernetes-anywhere-admins

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/org#84]
### Organization or repository
e.g. kubernetes/teams

### Users effected
e.g. (at)example_user

### Describe the issue
https://github.com/orgs/kubernetes/teams/kubernetes-anywhere-admins/members doesn’t have any maintainers, so we can’t self-admin the group. Please add @roberthbailey as a maintainer at which point I will add the other sig leads.

**Comment by spiffxp** [comment]
/close
You're now a team maintainer for https://github.com/orgs/kubernetes/teams/kubernetes-anywhere-admins/members
