### ISSUE TITLE
REQUEST: New membership for micahhausler

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/org#841]
### GitHub Username
@micahhausler

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @liggitt 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
     * [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=author%3Amicahhausler)
     * [kubernetes-sigs/aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator/pulls?utf8=%E2%9C%93&q=author%3Amicahhausler)
- Issues responded to
- SIG projects I am involved with
    * sig-aws
    * product security team (associate member)

**Comment by dims** [comment]
+1 👍

**Comment by liggitt** [comment]
+1

**Comment by christopherhein** [comment]
+1 👍

**Comment by mrbobbytables** [comment]
@micahhausler -- Just as an FYI, as a kubernetes org member you can implicitly be added to the other kubernetes orgs without requiring additional sponsorship. It's just the other way around that sponsors are required. 👍 

With that -- I've created PR #843 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.  🎉 

/assign

**Comment by nikhita** [comment]
@micahhausler Just for future reference...since you are already a member of Kubernetes, you don't need sponsorship to be added to other kubernetes orgs. Feel free to create a PR to add yourself to any other orgs, when needed. :)

**Comment by nikhita** [comment]
Oh derp...I just realized @mrbobbytables said the same above. :smile:
