### ISSUE TITLE
REQUEST: New membership for sethpollack

### ISSUE THREAD

**Issue by sethpollack** [kubernetes/org#842]
### GitHub Username
sethpollack

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [ x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x ] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- micahhausler
- dims    

### List of contributions to the Kubernetes project
- SIG projects I am involved with
https://github.com/kubernetes-sigs/kustomize
https://github.com/kubernetes-sigs/aws-encryption-provider

**Comment by dims** [comment]
+1 👍

**Comment by mrbobbytables** [comment]
@sethpollack  -- Just as an FYI, as a kubernetes org member you can implicitly be added to the other kubernetes orgs without requiring additional sponsorship. It's just the other way around that sponsors are required. 👍 

With that -- I've created PR #843 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.  🎉 

/assign

**Comment by sethpollack** [comment]
thanks
