### ISSUE TITLE
REQUEST: clean up SIG Service Catalog teams

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes/org#844]
### Organization or repository
kubernetes-incubator, kubernetes, and kubernetes-sigs

### Users affected
all users of the `admins-service-catalog` and `maintainers-service-catalog` teams in kubernetes-incubator, as well as members of the `sig-service-catalog-api-reviews`, `sig-service-catalog-bugs`, `sig-service-catalog-feature-requests `, `sig-service-catalog-misc`, `sig-service-catalog-pr-reviews, `sig-service-catalog-proposals`, and `sig-service-catalog-test-failures` teams in kubernetes

### Describe the issue
We're beginning the process of migrating our repos out of kubernetes-incubator to kubernetes-sigs. I need the `admins-service-catalog`  and `maintainers-service-catalog` teams from kubernetes-incubator duplicated in kubernetes and kubernetes-sigs. I would like to change the names to the current naming convention, so they would be called `service-catalog-admins` and `service-catalog-maintainers`. I would also like to delete the other teams from the mainline kubernetes org, as they are deprecated and have no current function.

**Comment by nikhita** [comment]
> We're beginning the process of migrating our repos out of kubernetes-incubator to kubernetes-sigs. I need the admins-service-catalog and maintainers-service-catalog teams from kubernetes-incubator duplicated in kubernetes-sigs. 

I guess it'd be better to wait with the team migration until repo migration is done because the teams are used to provide appropriate access to repos.

**Comment by cblecker** [comment]
@jberkhahn Can I suggest you keep at least one team in the main kubernetes org? This helps with notifications for repos like k/community. Perhaps something like kubernetes/sig-service-catalog (without the -misc or what have you)?

**Comment by cblecker** [comment]
Also, when we create the new teams in k-sigs, can we swap over the naming convention to have the admins/maintainers bit at the end?

**Comment by jberkhahn** [comment]
@nikhita I thought it would be better to move the teams over first, otherwise we won't be able to do anything in the new repos?

@cblecker all good suggestions. I'm fine with changing the names and keeping a `sig-service-catalog` team in kubernetes

**Comment by jberkhahn** [comment]
Actually, now that I think about it, if we're still going to have a team in kubernetes, we might as well just mirror the teams we already have, I'll amend the issue

**Comment by cblecker** [comment]
We have two kinds of teams.. "notification" teams that are sig based, and "permissions" teams that are repo based.

So what makes sense to me is:
kubernetes/sig-service-catalog (notification team for the sig, no permissions)
kubernetes-sigs/service-catalog-admins (permissions team)
kubernetes-sigs/service-catalog-maintainers (permissions team)

We create those teams new, and populate them with folks. And then when the repo moves, we just get rid of everything else.

How does that sound?

**Comment by jberkhahn** [comment]
sounds good :+1:

**Comment by jberkhahn** [comment]
Do you need anything else from me on this?
