### ISSUE TITLE
REQUEST: New membership for ahg-g

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/org#848]
### GitHub Username
@ahg-g

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bsalamat 
- @Huang-Wei 

### List of contributions to the Kubernetes project
- PRs authored
https://github.com/kubernetes/kubernetes/pull/77509
https://github.com/kubernetes/kubernetes/pull/77559
https://github.com/kubernetes/kubernetes/pull/77978
https://github.com/kubernetes/kubernetes/pull/77626
https://github.com/kubernetes/kubernetes/pull/78005

- PRs reviewed 
https://github.com/kubernetes/kubernetes/pull/78162
https://github.com/kubernetes/kubernetes/pull/78009
https://github.com/kubernetes/kubernetes/pull/78317
https://github.com/kubernetes/kubernetes/pull/78339
https://github.com/kubernetes/kubernetes/pull/78301
https://github.com/kubernetes/kubernetes/pull/78275

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/67019
https://github.com/kubernetes/kubernetes/issues/78208
https://github.com/kubernetes/kubernetes/issues/69599
https://github.com/kubernetes/kubernetes/issues/78383
https://github.com/kubernetes/kubernetes/issues/71592
https://github.com/kubernetes/kubernetes/issues/69811

- SIG projects I am involved with
sig scheduling
sig networking

**Comment by bsalamat** [comment]
+1
Looking forward to see more contributions from @ahg-g!

**Comment by Huang-Wei** [comment]
+1
@ahg-g Thanks and looking forward to seeing more contributions!

**Comment by justaugustus** [comment]
@ahg-g -- Thanks so much for your contributions thus far!
I've created #858 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
