### ISSUE TITLE
Tidy up some teams

### ISSUE THREAD

**Issue by cblecker** [kubernetes/org#850]
We need some help cleaning up the descriptions for some of our teams.

For all the `*-admins` teams, we need to update the descriptions to be something like:
```
admins access to the <repo> repo
```

For all the `*-maintainers` teams, we need to update the descriptions to be something like:
```
write access to the <repo> repo
```

And we can remove all the `*-reviewers` teams.

All these configs should be under the `config/` directory. They might be in any of the delegated sig yaml files.

---

If you'd like to do this, please comment that you'd like to on this issue. If you have questions, please ask them here or message me on Slack.

When you open a PR, please `/assign @cblecker`.

**Comment by nzoueidi** [comment]
I can help with this!

**Comment by nzoueidi** [comment]
I will push a PR very soon!

**Comment by cblecker** [comment]
@nzoueidi sounds good! Assign it to me when you push it up. Thank you!
