### ISSUE TITLE
REQUEST: New membership for jiatongw

### ISSUE THREAD

**Issue by jiatongw** [kubernetes/org#854]
### GitHub Username
@jiatongw
### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @andrewsykim 
- @SataQiu 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/77720
https://github.com/kubernetes/kubernetes/pull/77533
https://github.com/kubernetes/kubernetes/pull/77486
https://github.com/kubernetes/kubernetes/pull/77016
https://github.com/kubernetes/kubernetes/pull/76751
https://github.com/kubernetes/kubernetes/pull/76577
https://github.com/kubernetes/kubernetes/pull/76400
https://github.com/kubernetes/kubernetes/pull/76309

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/77197
https://github.com/kubernetes/kubernetes/issues/77359
https://github.com/kubernetes/kubernetes/issues/77095
https://github.com/kubernetes/kubernetes/issues/76206
https://github.com/kubernetes/kubernetes/issues/65618

- SIG projects I am involved with
 testing-commons under sig-testing

**Comment by andrewsykim** [comment]
👍 from me! Thanks for your contributions!

**Comment by SataQiu** [comment]
+1 Thanks for your contributions!

**Comment by justaugustus** [comment]
@jiatongw -- Thanks so much for your contributions thus far!
I've created #858 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
