### ISSUE TITLE
Sub-project website for minikube documentation

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/org#855]
### Repository
e.g. kubernetes-sigs/foo

kubernetes/minikube

### Project domain
e.g. foo.sigs.k8s.io

minikube.sigs.k8s.io

NOTE: Must match domain request.
See subproject site request docs for more information:
http://git.k8s.io/community/github-management/subproject-site-requests.md#subproject-domain-request

### Additional context for request
Any additional information or links to discussions regarding the request.

minikube has a great deal of documentation on GitHub: https://github.com/kubernetes/minikube/tree/master/docs

However, GitHub doesn't do a great job of handling localization of pages. We'd like to use netlify and Hugo be able to use a similar mechanism to the main Kubernetes docs website for hosting localized documentation. Thanks!

**Comment by nikhita** [comment]
minikube is in the main @kubernetes github org, instead of @kubernetes-sigs. Should the project domain still be minikube.sigs.k8s.io or should it be minikube.k8s.io? Personally, I feel like we should go for the latter to ensure consistency but what do y'all think?

cc @cblecker @mrbobbytables

**Comment by mrbobbytables** [comment]
> I feel like we should go for the former to ensure consistency

I agree. I think it'd be best to avoid adding things to the root  of the k8s.io domain directly unless there's a very good reason to do so.

**Comment by tstromberg** [comment]
I prefer shorter names when possible, but I'm entirely amenable to either option. I'm just happy to have a good home for localized project documentation =)

**Comment by nikhita** [comment]
I've _almost_ setup Netlify - the only thing remaining is enabling HTTPS but Netlify tells me that the DNS configuration needs to be setup first. 

@tstromberg can you create a `netlify.toml` file at the root of the minikube repo ([example](https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md#example-netlify-configuration)) and create a [subproject domain request](https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md#subproject-domain-request) or create a PR like https://github.com/kubernetes/k8s.io/pull/267?

**Comment by tstromberg** [comment]
@nikhita - Thanks! My apologies for the delay as I've been away on holiday :) I've added a netlify.toml file, and made a subproject domain request: https://github.com/kubernetes/k8s.io/issues/284

**Comment by nikhita** [comment]
This is done :tada: 

/close

**Comment by tstromberg** [comment]
Thank you @nikhita ! You are awesome!
