### ISSUE TITLE
REQUEST: New membership for damemi

### ISSUE THREAD

**Issue by damemi** [kubernetes/org#860]
### GitHub Username
@damemi

### Organization you are requesting membership in
@kubernetes 
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @soltysh 
- @directxman12

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/controller-tools/pull/184
https://github.com/kubernetes-sigs/controller-tools/pull/172
https://github.com/kubernetes-sigs/controller-tools/pull/170
https://github.com/kubernetes-sigs/controller-tools/pull/144
https://github.com/kubernetes-sigs/controller-tools/pull/142
https://github.com/kubernetes/kube-openapi/pull/139
https://github.com/kubernetes/kubernetes/pull/64097
https://github.com/kubernetes/kubernetes/pull/68795
https://github.com/kubernetes/kubernetes/pull/68019
https://github.com/kubernetes/kubernetes/pull/68015
https://github.com/kubernetes/kubernetes/pull/65059
https://github.com/kubernetes/kubernetes/pull/62351
https://github.com/kubernetes/kubernetes/pull/60723
https://github.com/kubernetes/kubernetes/pull/28234
https://github.com/kubernetes-incubator/custom-metrics-apiserver/pull/28

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/68011
https://github.com/kubernetes-incubator/custom-metrics-apiserver/issues/17

- SIG projects I am involved with
kubebuilder/controller-tools
(previously) autoscaling/HPA

**Comment by soltysh** [comment]
:+1: from me

**Comment by DirectXMan12** [comment]
:+1: from me as well :-)

**Comment by mrbobbytables** [comment]
@damemi Thank you for all your contributions thus far :D

I've created PR #867  to add you to both the Kubernetes and Kubernetes-sigs Orgs. Once that gets merged, you should get a membership invite notifications from both of them.

Welcome to @kubernetes! 🎉

/assign
