### ISSUE TITLE
REQUEST: New membership for @sethp-nr

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes/org#861]
### GitHub Username
@sethp-nr 

For future documentation, I also have a personal account that I don't use much at @sethp, but probably won’t be using that account to contribute to Kubernetes in the near future.

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @vincepri 
- @dims 

### List of contributions to the Kubernetes project
- A lot of little things in various places, but probably the biggest chunk is on CAPA: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?utf8=%E2%9C%93&q=author%3Asethp-nr+

**Comment by dims** [comment]
+1 from me

**Comment by vincepri** [comment]
+1 from me

🎉 👍 💯

**Comment by mrbobbytables** [comment]
@sethp-nr thanks for your help with the aws cluster-api provider :)

I've created PR #867  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
