### ISSUE TITLE
REQUEST: New membership for rudoi

### ISSUE THREAD

**Issue by rudoi** [kubernetes/org#862]
### GitHub Username
@rudoi

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @vincepri 
- @dims 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/790
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/718
- https://github.com/kubernetes-sigs/cluster-api/pull/840
- co-contributed https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/706
- several others in cluster-api and cluster-api-provider-aws

**Comment by dims** [comment]
+1 from me

**Comment by vincepri** [comment]
+1 from me

🎉 👍 💯

**Comment by mrbobbytables** [comment]
@rudoi  thanks for your contributions to the cluster api and aws-cluster-api \o/

I've created PR #867  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
