### ISSUE TITLE
request for new repo for sig-windows called sig-windows-tools

### ISSUE THREAD

**Issue by michmike** [kubernetes/org#863]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
sig-windows-tools

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
michmike, patricklang

### If not a staging repo, who should have write access
michmike, patricklang

### If not a staging repo, who should be listed as approvers in OWNERS
michmike, patricklang

### If not a staging repo, who should be listed in SECURITY_CONTACTS
michmike, patricklang

### What should the repo description be
Repository for tools and artifacts related to the sig-windows charter in Kubernetes. Scripts to assist kubeadm and wincat and flannel will be hosted here.

### What SIG and subproject does this fall under in sigs.yaml
This is a new repo for SIG-Windows.

### Approvals
Patrick and I are the sig co-chairs

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
Any additional information or context to describe the request.

**Comment by michmike** [comment]
cc: @nikhita (I think you are the owner here :) )

**Comment by nikhita** [comment]
@michmike Thanks for the cc! :)

Created https://github.com/kubernetes-sigs/sig-windows-tools :tada: 

Also created https://github.com/kubernetes/org/pull/872 to add teams for the repo and https://github.com/kubernetes/community/pull/3759 to add the repo to sigs.yaml.

Once both PRs merge and teams are granted access (I'll manually grant access after the postsubmit runs), we can close this issue. :+1:

**Comment by michmike** [comment]
thank you so much for doing this so quickly and for editing the yaml files. i was going to do that :)
i approved both PRs

**Comment by nikhita** [comment]
Awesome, thank you! Once the postsubmit run completes and the teams are created on GitHub, I'll grant them access and close this issue. :)

**Comment by nikhita** [comment]
Granted access, will close this after https://github.com/kubernetes/community/pull/3759 merges.

**Comment by nikhita** [comment]
https://github.com/kubernetes/org/issues/863 merged.

/close
