### ISSUE TITLE
k/k, etc. repo write access for release-team-leads

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#864]
### Organization or repository
kubernetes/kubernetes, kubernetes/release, kubernetes/sig-release

### Users affected
@kubernetes/release-team-leads 

### Describe the issue
With #828 merged, we removed Release Team Leads/Shadows from the `release-managers` team, which grants elevated permissions in a few repos. We also created `release-team-leads` to grant this access to Release Team Leads/Shadows.

I'd like to grant write access to kubernetes/kubernetes, kubernetes/release, kubernetes/sig-release to `release-team-leads`.

/assign @cblecker

**Comment by cblecker** [comment]
Done!

**Comment by justaugustus** [comment]
Thanks Christoph! :)
