### ISSUE TITLE
Add Stephen Augustus as Maintainer for the features-maintainers GH team

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/org#87]
### Organization or repository
k/features

### Users effected
@justaugustus

### Describe the issue
As PdM Chair and one of the drivers of the features and KEP delivery processes, I'd like to be able to control who has write access to the k/features repo.

/sig pm
/assign @cblecker

**Comment by cblecker** [comment]
Done!
https://github.com/orgs/kubernetes/teams/features-maintainers/members
