### ISSUE TITLE
New membership for zhucan

### ISSUE THREAD

**Issue by zhucan** [kubernetes/org#870]
### GitHub Username
@zhucan

### Organization you are requesting membership in
@kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@xingyang
@vladimirvivien

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-csi/csi-driver-host-path/pull/51
https://github.com/kubernetes-csi/external-snapshotter/pull/121
https://github.com/kubernetes-csi/external-snapshotter/pull/119

- Issues responded to
https://github.com/kubernetes-csi/external-snapshotter/issues/45

- SIG projects I am involved with
kubernetes

**Comment by xing-yang** [comment]
+1 @zhucan has been contributing in kubernetes-csi.  He should be a member of kubernetes-csi.

**Comment by vladimirvivien** [comment]
+1

**Comment by vladimirvivien** [comment]
@msau42 @jsafrane  Please add @zhucan to kubernetes-sig as a member.

**Comment by msau42** [comment]
+1

**Comment by mrbobbytables** [comment]
Hey there @zhucan, thank you for all your contributions so far :)

I've created PR #  to add you to the Kubernetes-csi Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-csi! 🎉

/assign
