### ISSUE TITLE
REQUEST: New membership for @piotrmiskiewicz

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kubernetes/org#877]
### GitHub Username
@piotrmiskiewicz

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jberkhahn
- @soltysh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
https://github.com/kubernetes-incubator/service-catalog/pull/2333
https://github.com/kubernetes-incubator/service-catalog/pull/2337
https://github.com/kubernetes-incubator/service-catalog/pull/2370
https://github.com/kubernetes-incubator/service-catalog/pull/2577
https://github.com/kubernetes-incubator/service-catalog/pull/2591

- Issues responded to
https://github.com/kubernetes-incubator/service-catalog/issues/2576
https://github.com/kubernetes-incubator/service-catalog/issues/2563
https://github.com/kubernetes-incubator/service-catalog/issues/1772
https://github.com/kubernetes-incubator/service-catalog/issues/2276

- SIG projects I am involved with
[SIG Service Catalog](https://github.com/kubernetes-incubator/service-catalog)

**Comment by soltysh** [comment]
:+1: from me

**Comment by jberkhahn** [comment]
:+1: from me as well

**Comment by mrbobbytables** [comment]
Reconciling the move of service-catalog from incubator to k-sigs 👍

@piotrmiskiewicz, thanks for all your help with service-catalog :)

I've created PR #889 to add you to the kubernetes-sigs org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs 🎉 

/assign
