### ISSUE TITLE
REQUEST: New kubernetes-sigs membership for SataQiu

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/org#878]
### GitHub Username
@SataQiu 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
Already a member of @kubernetes.

**Comment by nikhita** [comment]
Since you already a member of @kubernetes, feel free to create a PR to add yourself :)
