### ISSUE TITLE
New repo for kubernetes-incubator/external-storage/lib

### ISSUE THREAD

**Issue by wongma7** [kubernetes/org#88]
### New Repo, or migrate existing
new repository

### Requested name for new repository
sig-storage-external-provisioner-lib

### Which Organization should it reside
kubernetes-sigs

### Who should be provided access to this repository
@wongma7
@jsafrane 
@childsb

### Approvals
Need sig-storage approval from: @childsb and @saad-ali 
See "External Storage - Moving Project Out" in https://docs.google.com/document/d/1AoemMxRcRDhc3gpChGk-UwCiVsk7Q7E_yKeIKP-7jL4/edit?ts=5ad14c06#heading=h.6ufuho4zfqau

### Additional context for request
Currently, kubernetes-incubator/external-storage houses both a small library under /lib for writing external provisioners and a number of "community-maintained" provisioners which depend on the library. We want to separate the library and the provisioners.

It can be difficult for users/dependers of the library to vendor it and for library maintainers to update it (as frequently as versions of kubernetes are released) due to the need to untangle golang dependency webs if/when conflicts arise.

cc @verult

**Comment by saad-ali** [comment]
Approved from sig-storage

Let's name this: `github.com/kuberentes-sigs/sig-storage-external-provisioner-lib`

**Comment by spiffxp** [comment]
getting to this now...

**Comment by spiffxp** [comment]
Created:
- https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner
- https://github.com/orgs/kubernetes-sigs/teams/sig-storage-lib-external-provisioner-admins
- https://github.com/orgs/kubernetes-sigs/teams/sig-storage-lib-external-provisioner-maintainers

Used https://github.com/kubernetes/kubernetes-template-project for initial commit

Set OWNERS and SECURITY_CONTACTS to @wongma7 @jsafrane @childsb

Verified @wongma7 @jsafrane @childsb are kubernetes org members and invited to kubernetes-sigs org

I've set @wongma7 as a Team Maintainer for both teams as they've already accepted

**Comment by spiffxp** [comment]
Criteria for closing:
- everyone invited has accepted their invite
- the k/community PR adding this to sigs.yaml has merged
- the k/org PR adding the manually invited members has merged

**Comment by spiffxp** [comment]
/close
all of the above has happened
