### ISSUE TITLE
REQUEST: New membership for k-toyoda-pi

### ISSUE THREAD

**Issue by k-toyoda-pi** [kubernetes/org#885]
### GitHub Username
@k-toyoda-pi

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims
- @oomichi

### List of contributions to the Kubernetes project
- PRs reviewed / authored
kubernetes/kubernetes#78279
kubernetes/kubernetes#77909
kubernetes/kubernetes#77901
kubernetes/kubernetes#77852
kubernetes/website#14246
kubernetes/website#14242
kubernetes/kubernetes#77579
kubernetes/community#3683
kubernetes/website#14195
kubernetes/kubernetes#77123
kubernetes/kubernetes#77054
kubernetes/kubernetes#77005
kubernetes/kubernetes#76420
kubernetes/kubernetes#75158
kubernetes/community#3204
kubernetes/kubernetes#73508
kubernetes/website#11800
kubernetes/kubernetes#71199
kubernetes/kubernetes#70474

- Issues responded to
kubernetes/kubernetes#73771
kubernetes/kubernetes#73499
kubernetes/kubernetes#77103
kubernetes/website#13862

- SIG projects I am involved with
sig-testing

**Comment by oomichi** [comment]
Big +1, thanks for your contribution!

**Comment by dims** [comment]
+1 from me

**Comment by k-toyoda-pi** [comment]
Thank you so much!

**Comment by mrbobbytables** [comment]
Hey there @k-toyoda-pi , thank you for all your contributions so far :)

I've created PR #889  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
