### ISSUE TITLE
REQUEST: New membership for s-ito-ts

### ISSUE THREAD

**Issue by s-ito-ts** [kubernetes/org#886]
### GitHub Username
@s-ito-ts

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @oomichi
- @dims

### List of contributions to the Kubernetes project
- PRs reviewed / authored
kubernetes/kubernetes#78283
kubernetes/kubernetes#78163
kubernetes/kubernetes#78021
kubernetes/kubernetes#77913
kubernetes/kubernetes#77902
kubernetes/kubernetes#77113
kubernetes/kubernetes#76475
kubernetes/kubernetes#75662
kubernetes/kubernetes#74570
kubernetes/kubernetes#74013

- Issues responded to
kubernetes/kubernetes#78160
kubernetes/kubernetes#77103
kubernetes/website#13862
kubernetes/kubernetes#75929

- SIG projects I am involved with
sig-testing

**Comment by oomichi** [comment]
+1 for the membership.

**Comment by dims** [comment]
+1 from me

**Comment by s-ito-ts** [comment]
Thank you so much!

**Comment by mrbobbytables** [comment]
@s-ito-ts , thank you for all your help with the various e2e tests and shellcheck lints :)

I've created PR #889  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
