### ISSUE TITLE
REQUEST: New membership for nzoueidi

### ISSUE THREAD

**Issue by nzoueidi** [kubernetes/org#890]
### GitHub Username
@nzoueidi 

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mrbobbytables 
- @nikhita 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
#853
kubernetes/kubernetes#75199
kubernetes/community#3777
kubernetes/community#3766
kubernetes/community#3747
kubernetes/community#3731
kubernetes/community#3501
kubernetes/community#3418
kubernetes/community#3405
kubernetes-sigs/kubebuilder#760
kubernetes-sigs/service-catalog#2643
kubernetes/test-infra#12168
kubernetes/k8s.io#200
kubernetes-sigs/kustomize#1109

- Issues responded to
kubernetes/kops#6475
kubernetes/test-infra#12770
kubernetes/test-infra#12749
- SIG projects I am involved with
SIG-contribex and trying to be active in SIG-service-catalog

**Comment by nikhita** [comment]
+1

@nzoueidi Thanks for consistently helping out contribex related issues :)

**Comment by mrbobbytables** [comment]
Big +1 here :D

**Comment by castrojo** [comment]
Another big +1 from me!

**Comment by cblecker** [comment]
Invite will be sent out as soon as #896 merges. Welcome to @kubernetes! 🚀
