### ISSUE TITLE
REQUEST: New membership for oxddr

### ISSUE THREAD

**Issue by oxddr** [kubernetes/org#891]
### GitHub Username
@oxddr

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mm4tt
- @shyamjvs 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/perf-tests/pull/558 (in progress)
  - https://github.com/kubernetes/perf-tests/pull/557 (in progress)
  - https://github.com/kubernetes/perf-tests/pull/556
  - https://github.com/kubernetes/perf-tests/pull/555
  - https://github.com/kubernetes/perf-tests/pull/517
  - https://github.com/kubernetes/perf-tests/pull/509
  - https://github.com/kubernetes/test-infra/pull/12869
  - https://github.com/kubernetes/test-infra/pull/12868
  - https://github.com/kubernetes/test-infra/pull/12737
  - https://github.com/kubernetes/kubernetes/pull/74809
  - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/67
  - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/65
  - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/54
  - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/39

- Issues responded to: (I've listed all opened, contributed, fixed)
  - https://github.com/kubernetes/perf-tests/issues/559
  - https://github.com/kubernetes/perf-tests/issues/553
  - https://github.com/kubernetes/perf-tests/issues/554
  - https://github.com/kubernetes/test-infra/issues/12867
  - https://github.com/kubernetes/kubernetes/issues/77080
  - https://github.com/kubernetes/kubernetes/issues/76760
  - https://github.com/kubernetes/kubernetes/issues/76579
  - https://github.com/kubernetes/kubernetes/issues/75541
  - https://github.com/kubernetes/website/issues/13332
- SIG projects I am involved with
  - sig-scalability

**Comment by mm4tt** [comment]
+1

**Comment by shyamjvs** [comment]
+1

**Comment by mrbobbytables** [comment]
@oxddr  thank you for all your contributions so far :)

I've created PR #906 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
