### ISSUE TITLE
REQUEST: New membership for moshloop

### ISSUE THREAD

**Issue by moshloop** [kubernetes/org#892]
### GitHub Username
@moshloop

### Organization you are requesting membership in
kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of contributions to the Kubernetes project
- SIG Cluster Lifecycle
https://docs.google.com/document/d/1N65N1vCVa5QmU4BJXeSOImgRE8aq7daWhHt7XE9WCeI/edit#
https://github.com/kubernetes-sigs/etcdadm/pull/103
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/285

**Comment by timothysc** [comment]
+1 from me as sponsor.

**Comment by cblecker** [comment]
@moshloop You will need one additional eligible sponsor.

**Comment by dlipovetsky** [comment]
+1 from me as sponsor as well

(I'm an approver/reviewer in the @kubernetes-sigs org.)

**Comment by mrbobbytables** [comment]
Hey there @moshloop, with @dlipovetsky +1 you're good sponsor wise for membership to kubernetes-sigs. If this is okay, would you mind amending your request and remove kubernetes? If not, could you please find an additional sponsor?

Thanks!

**Comment by moshloop** [comment]
@mrbobbytables done

**Comment by mrbobbytables** [comment]
Great! Thanks @moshloop 😄

**Comment by mrbobbytables** [comment]
With all that sorted out, @moshloop you're good to join kubernetes-sigs :D

I've created PR #906  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by justinsb** [comment]
So I was looking to assign moshloop in https://github.com/kubernetes/kube-deploy/tree/master/imagebuilder but that apparently needs kubernetes org membership.

Is there a reason why kubernetes-sigs org membership is different to kubernetes org membership?

+1 to @moshloop for kubernetes org membership, anyway - there is no difference in my mind.

/reopen

**Comment by justaugustus** [comment]
Approved as @justinsb and @timothysc are kubernetes org sponsors. I've created #947 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign

ref: https://kubernetes.slack.com/archives/C1TU9EB9S/p1561131100303800
