### ISSUE TITLE
REQUEST: New membership for chases2

### ISSUE THREAD

**Issue by chases2** [kubernetes/org#895]
### GitHub Username
e.g. @chases2

### Organization you are requesting membership in
e.g. @kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @spiffxp 
- @stevekuznetsov

### List of contributions to the Kubernetes project
- PRs reviewed / authored
[Modify k8s-bot directive to add approvers](https://github.com/kubernetes/test-infra/pull/12888)
[TestGrid Issue-Gathering Controller: Entomologist](https://github.com/kubernetes/test-infra/pull/12885)
[Addition of Crier/Controller Integration Test](https://github.com/kubernetes/test-infra/pull/12691)
[Unit Test for Crier](https://github.com/kubernetes/test-infra/pull/12571)

- Issues responded to
[Write a GitHub Issue Gatherer to link issues to tests in TestGrid](https://github.com/kubernetes/test-infra/issues/10701)
[Write an integration test for crier/controller](https://github.com/kubernetes/test-infra/issues/11530)
[Unit test prow flags](https://github.com/kubernetes/test-infra/issues/12137)

- SIG projects I am involved with
None to date

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by stevekuznetsov** [comment]
+1 from sponsor as well :)

**Comment by cblecker** [comment]
Invite will be sent out as soon as #896 merges. Welcome to @kubernetes! 🚀
