### ISSUE TITLE
REQUEST: New membership for mirandachrist

### ISSUE THREAD

**Issue by mirandachrist** [kubernetes/org#898]
### GitHub Username
@mirandachrist

### Organization you are requesting membership in
@kubernetes

### Requirements
- [ x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @cjwagner 
- @stevekuznetsov

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - Add link to display prow job YAML on Spyglass: https://github.com/kubernetes/test-infra/pull/12928
  - Add button to directly view prow job YAML via new endpoint: https://github.com/kubernetes/test-infra/pull/12890
  - Makes /meow no post an image of grumpy cat: https://github.com/kubernetes/test-infra/pull/12815
  - Add "grumpy" as a keyword for grumpy cat plugin: https://github.com/kubernetes/test-infra/pull/12841
- Issues responded to:
  - #10845: prow/cat: 'no' keyword should always show grumpy cat
- SIG projects I am involved with:
  - test-infra

**Comment by stevekuznetsov** [comment]
+1 from this sponsor :)

**Comment by cjwagner** [comment]
+1 from me as well!

**Comment by mrbobbytables** [comment]
Hey there @mirandachrist , thank you for your help with test-infra <3

I've created PR #906  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
