### ISSUE TITLE
create repo: kubernetes/funding

### ISSUE THREAD

**Issue by philips** [kubernetes/org#899]
### New Repo, Staging Repo, or migrate existing

new repo

### Requested name for new repository

funding

### Which Organization should it reside

kubernetes

### If not a staging repo, who should have admin access

@kubernetes/steering-committee 

### If not a staging repo, who should have write access

@kubernetes/steering-committee 

### If not a staging repo, who should be listed as approvers in OWNERS
e.g. alice, bob

### If not a staging repo, who should be listed in SECURITY_CONTACTS

@kubernetes/steering-committee 

### What should the repo description be

funding requests for project infrastructure, events, and consulting

### What SIG and subproject does this fall under in sigs.yaml

Steering commitee

### Approvals

Steering approval via https://github.com/kubernetes/steering/pull/106 and https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/JOcrB7PhCTc

### Additional context for request

https://github.com/kubernetes/steering/issues/46

**Comment by dims** [comment]
+1 thanks!

**Comment by timothysc** [comment]
/lgtm 
+1

**Comment by spiffxp** [comment]
/assign
Taking https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#creating-repositories for a test drive

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/community/pull/3789 to add to sigs.yaml

**Comment by spiffxp** [comment]
>Create a PR against kubernetes/org to add teams as per the team guidance for alloting repo admin and write access.

I skipped this step, instead opting to use the `@kubernetes/steering-committee` team directly

**Comment by spiffxp** [comment]
This can be closed once https://github.com/kubernetes/community/pull/3789 merges

**Comment by nikhita** [comment]
https://github.com/kubernetes/community/pull/3789 has merged

/close
