### ISSUE TITLE
REQUEST: New membership for saschagrunert

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/org#902]
### GitHub Username
@saschagrunert 

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jeefy 
- @onyiny-ang

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/release/pull/708
  - https://github.com/kubernetes/release/pull/704
- SIG projects I am involved with
  - https://github.com/kubernetes/sig-release
  - https://github.com/kubernetes-sigs/release-notes
  - https://github.com/kubernetes/release

(I will leave-out the non sig-release specific contributions to k8s)

**Comment by nikhita** [comment]
+1

**Comment by nikhita** [comment]
Since https://github.com/kubernetes-sigs/release-notes is in k-sigs, do you also want membership for k-sigs? :)

**Comment by saschagrunert** [comment]
> Since https://github.com/kubernetes-sigs/release-notes is in k-sigs, do you also want membership for k-sigs? :)

I am already in, thanks! :pray:

**Comment by onyiny-ang** [comment]
+1!


On Jun 11, 2019, at 08:35, Sascha Grunert <notifications@github.com<mailto:notifications@github.com>> wrote:


Since https://github.com/kubernetes-sigs/release-notes is in k-sigs, do you also want membership for k-sigs? :)

I am already in, thanks! 🙏

**Comment by jeefy** [comment]
+1 yay!

**Comment by mrbobbytables** [comment]
@saschagrunert thank you for all your help with sig-release and the release notes project 👍 

I've created PR #906  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
/pony party

**Comment by saschagrunert** [comment]
Thank you so much! 🙏 🙂
