### ISSUE TITLE
REQUEST: New membership for piotrmiskiewicz

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kubernetes/org#907]
### GitHub Username
@piotrmiskiewicz

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jberkhahn
- @soltysh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
https://github.com/kubernetes-incubator/service-catalog/pull/2333
https://github.com/kubernetes-incubator/service-catalog/pull/2337
https://github.com/kubernetes-incubator/service-catalog/pull/2370
https://github.com/kubernetes-incubator/service-catalog/pull/2577
https://github.com/kubernetes-incubator/service-catalog/pull/2591

- Issues responded to
https://github.com/kubernetes-incubator/service-catalog/issues/2576
https://github.com/kubernetes-incubator/service-catalog/issues/2563
https://github.com/kubernetes-incubator/service-catalog/issues/1772
https://github.com/kubernetes-incubator/service-catalog/issues/2276

- SIG projects I am involved with
[SIG Service Catalog](https://github.com/kubernetes-incubator/service-catalog)

This issue is created because of kubernetes-sigs member must be also a kubernetes member, see:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/org/904/pull-org-test-all/1138547913471823872

**Comment by jberkhahn** [comment]
:+1: from me

**Comment by soltysh** [comment]
:+1: from me too

**Comment by mrbobbytables** [comment]
@piotrmiskiewicz -- I've created PR #913  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification. That should take care of the group membership issue from earlier. :)

Welcome to @kubernetes! 🎉

/assign
