### ISSUE TITLE
REQUEST: New membership for hongkailiu

### ISSUE THREAD

**Issue by hongkailiu** [kubernetes/org#908]
### GitHub Username
@hongkailiu

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @stevekuznetsov
- @cjwagner 

### List of contributions to the Kubernetes project
- PRs reviewed / [authored](https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Ahongkailiu)
- [Issues](https://github.com/kubernetes/test-infra/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Ahongkailiu) responded to
- SIG projects I am involved with: [test-infra](https://github.com/kubernetes/test-infra) in [sig-testing](https://github.com/kubernetes/community/blob/master/sig-testing/README.md)

**Comment by cjwagner** [comment]
+1 from me.

**Comment by stevekuznetsov** [comment]
+1 from me as well

**Comment by mrbobbytables** [comment]
@hongkailiu  thank you for all your help with test-infra :D

I've created PR #911   to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by hongkailiu** [comment]
@mrbobbytables Thanks a lot.
