### ISSUE TITLE
REQUEST: New membership for clyang82

### ISSUE THREAD

**Issue by clyang82** [kubernetes/org#909]
### GitHub Username
@clyang82

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @gyliu513 
- @k82cn 

### List of contributions to the Kubernetes project

- I am reviewer of cluster-api-provider-ibmcloud project and also involved the initial creation of this project - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/a302c3577d495966c9a5d81f3936d1476d814bab/OWNERS_ALIASES#L38
- 2 commits in cluster-api
https://github.com/kubernetes-sigs/cluster-api/commits?author=clyang82
- 7 commits in cluster-api-provider-ibmcloud
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/commits?author=clyang82
- 4 issues logged in cluster-api-provider-ibmcloud
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/created_by/clyang82

**Comment by gyliu513** [comment]
+1, thanks @clyang82 for your great contribution to Cluster API !

**Comment by k82cn** [comment]
+1 to me, thanks :)

**Comment by mrbobbytables** [comment]
Hey there @clyang82, thank you for all your help with the ibmcloud cluster-api :)

I've created PR #911  to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by clyang82** [comment]
Thanks @gyliu513 @k82cn @mrbobbytables for your support.
