### ISSUE TITLE
REQUEST: New membership for aaron-prindle

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/org#910]
### GitHub Username
aaron-prindle

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yue9944882 
- @cheftako 

### Info
hi 👋! i'm an ex-maintainer of kubernetes/minikube and currently making contributions related to sig apimachinery (working on control plane fairness and misc api server bugs!) Hoping to join the kubernetes org so that I can triage issues, kickoff tests, and code review PRs!

### List of contributions to the Kubernetes project
Full info [here](https://gist.github.com/aaron-prindle/f1458ccf5f54aa2e1c6897e911d50981) 

**Repository: kubernetes**
Total Pull Requests Created: 7
Total Issues Opened: 3
Total Pull Requests Reviewed: 1

**Repository: website**
Total Pull Requests Created: 1

**Repository: minikube**
Total Pull Requests Created: 182
Total Issues Opened: 43
Total Pull Requests Reviewed: 195

**Repository: enhancements**
Total Pull Requests Reviewed: 2

### Sigs
sig/apimachinery

**Comment by cheftako** [comment]
:+1:

**Comment by cheftako** [comment]
Thanks for all the contributions and reviews.

**Comment by cheftako** [comment]
+1

**Comment by cblecker** [comment]
@aaron-prindle As outlined in our membership guidelines, you need a minimum of two sponsors from different companies. As @cheftako has confirmed sponsorship of your application, you'll need to substitute another sponsor for @lavalamp.

**Comment by yue9944882** [comment]
+1

**Comment by aaron-prindle** [comment]
@cblecker, i've updated my sponsor to be @yue9944882.  Let me know if anything else needs to be done additionally, thanks.

**Comment by mrbobbytables** [comment]
@aaron-prindle  thank you for all your contributions to the project :)

I've created PR #913  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
