### ISSUE TITLE
REQUEST: New membership for mhamdisemah

### ISSUE THREAD

**Issue by mhamdisemah** [kubernetes/org#912]
### GitHub Username
@mhamdisemah

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @guineveresaenger

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/contributor-playground/pull/254
https://github.com/kubernetes/community/pull/3748
https://github.com/kubernetes/website/pull/14791
https://github.com/kubernetes/website/pull/14816
https://github.com/kubernetes/website/pull/14859
https://github.com/kubernetes/website/pull/14875
https://github.com/kubernetes/sig-release/pull/664
- Issues responded to
https://github.com/kubernetes/sig-release/issues/663#event-2410358783
https://github.com/kubernetes/website/issues/14842#issuecomment-501438065
https://github.com/kubernetes/website/issues/14893
- SIG projects I am involved with
SIG-contribex , SIG-DOCS and SIG-RELEASE

**Comment by justaugustus** [comment]
Thanks for contributing, @mhamdisemah!
+1

**Comment by guineveresaenger** [comment]
+1 from me as well!

**Comment by mrbobbytables** [comment]
Hey there @mhamdisemah , thank you for all your contributions to the project \o/

I've created PR #913  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
