### ISSUE TITLE
REQUEST: New membership for simplytunde

### ISSUE THREAD

**Issue by simplytunde** [kubernetes/org#914]
### GitHub Username
@simplytunde

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jimangel 
- @justaugustus 

### List of contributions to the Kubernetes project
- SIG Release Doc Team 1.14 and 1.15

**Comment by justaugustus** [comment]
@simplytunde -- Thank you so much for your contributions on the Release Team! +1! :)

**Comment by jimangel** [comment]
@simplytunde has been helping with the sig-docs release team since 1.14, +1!

**Comment by justaugustus** [comment]
I've created #923 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
