### ISSUE TITLE
REQUEST: New membership for stealthybox

### ISSUE THREAD

**Issue by stealthybox** [kubernetes/org#919]
### GitHub Username
@stealthybox 

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justinsb 
- @luxas 

### List of contributions to the Kubernetes project
https://github.com/issues?utf8=%E2%9C%93&q=author%3Astealthybox+user%3Akubernetes+user%3Akubernetes-sigs+user%3Ahelm+user%3Acncf
- SIG projects I am involved with
Cluster Lifecycle, API Machinery:
kubeadm, component-standard, cluster-addons

**Comment by justaugustus** [comment]
(@stealthybox is already a member of the `kubernetes` org and implicitly eligible for membership to `kubernetes-sigs`)

Thanks so much for your contributions thus far!
I've created #923 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
