### ISSUE TITLE
New repos for kubernetes-csi drivers

### ISSUE THREAD

**Issue by childsb** [kubernetes/org#92]
### New Repo, or migrate existing
batch request for new repositories for CSI drivers and two library repos

### Requested name for new repositories
github.com/kubernetes-csi/driver-cinder
github.com/kubernetes-csi/driver-flex
github.com/kubernetes-csi/driver-host-path
github.com/kubernetes-csi/driver-iscsi
github.com/kubernetes-csi/driver-nfs
github.com/kubernetes-csi/driver-lib-csi-common
github.com/kubernetes-csi/driver-lib-csi-connector

### Which Organization should it reside
kubernetes-csi

### Who should be provided access to this repository
@childsb @saad-ali @vladimirvivien ...  

### Approvals
approvals from sig-storage

### Additional context for request
This request is to create individual csi driver repos and one csi library repo under the kubernetes-csi org.  It's been discussed at length in the sig-storage calls and agreed on by the community.

**Comment by saad-ali** [comment]
> github.com/kubernetes-csi/driver-cinder
> github.com/kubernetes-csi/driver-flex
> github.com/kubernetes-csi/driver-host-path
> github.com/kubernetes-csi/driver-iscsi
> github.com/kubernetes-csi/driver-nfs

Driver repos SGTM.

> github.com/kubernetes-csi/driver-lib-csi-common
> github.com/kubernetes-csi/driver-lib-csi-connector

I think on the call we decided to do separate repos for each library. Something like `kubernetes-csi/csi-common-lib*` where `*` is `iscsi`, etc. Please update this to reflect that.

**Comment by childsb** [comment]
@saad-ali the library name we hadn't nailed down.

One best practice with naming that I was attempting to leverage here is placing the static element of the name first.. That way similar repos will group together on sort

So tweaking your suggestion:

* csi-lib-common 
* csi-lib-iscsi 
* csi-lib-fc 

would group the items in the list making it easier to find.

**Comment by saad-ali** [comment]
> csi-lib-common
> csi-lib-iscsi
> csi-lib-fc

SGTM. What is `csi-lib-common` for?

**Comment by childsb** [comment]
@saad-ali for this https://github.com/kubernetes-csi/drivers/tree/master/pkg/csi-common

**Comment by saad-ali** [comment]
> @saad-ali for this https://github.com/kubernetes-csi/drivers/tree/master/pkg/csi-common

Ah ok. Let's also make sure the description fields on the repos are set to explain what the heck they do.

Also unsure about the `csi-` prefix. Either we should also have it for the drivers, e.g. `csi-driver-cinder` or not have it on either driver or libs e.g. `driver-cinder` and `lib-iscsi` -- let's be consistent.

**Comment by childsb** [comment]
lets keep 'csi' in the name and i'll add to the drivers.. my initial though is that 'csi is redundant with 'csi' in the org name, but if these repos are forked into org's without CSI then the prefix will help clarify the purpose.

So the final list:

github.com/kubernetes-csi/csi-driver-cinder
github.com/kubernetes-csi/csi-driver-flex
github.com/kubernetes-csi/csi-driver-host-path
github.com/kubernetes-csi/csi-driver-iscsi
github.com/kubernetes-csi/csi-driver-nfs
github.com/kubernetes-csi/csi-driver-lib-common
github.com/kubernetes-csi/csi-driver-lib-connector

**Comment by saad-ali** [comment]
Wait you mean:

github.com/kubernetes-csi/csi-driver-cinder
github.com/kubernetes-csi/csi-driver-flex
github.com/kubernetes-csi/csi-driver-host-path
github.com/kubernetes-csi/csi-driver-iscsi
github.com/kubernetes-csi/csi-driver-nfs
github.com/kubernetes-csi/csi-lib-common
github.com/kubernetes-csi/csi-lib-connector

(e.g. last two should be `lib` not `driver-lib`) Right?

Also `kubernetes-csi/csi-lib-connector` I thought we decided to split that up per protocol (e.g. `kubernetes-csi/csi-lib-fc`, `kubernetes-csi/csi-lib-iscsi`, etc.) because we wanted to do independent releases and they don't have shared code?

**Comment by childsb** [comment]
Updated list:

github.com/kubernetes-csi/csi-driver-cinder
github.com/kubernetes-csi/csi-driver-flex
github.com/kubernetes-csi/csi-driver-host-path
github.com/kubernetes-csi/csi-driver-iscsi
github.com/kubernetes-csi/csi-driver-nfs
github.com/kubernetes-csi/csi-lib-common
github.com/kubernetes-csi/csi-lib-fc
github.com/kubernetes-csi/csi-lib-iscsi

**Comment by saad-ali** [comment]
> github.com/kubernetes-csi/csi-driver-cinder
> github.com/kubernetes-csi/csi-driver-flex
> github.com/kubernetes-csi/csi-driver-host-path
> github.com/kubernetes-csi/csi-driver-iscsi
> github.com/kubernetes-csi/csi-driver-nfs
> github.com/kubernetes-csi/csi-lib-common
> github.com/kubernetes-csi/csi-lib-fc
> github.com/kubernetes-csi/csi-lib-iscsi

LGTM!

**Comment by spiffxp** [comment]
Was OOO last week, will get to this in a bit

**Comment by spiffxp** [comment]
@saad-ali @childsb re: "who should have access to this repository", what I need to know is:
- who should have admin access to the repo (these people will be setup as team maintainers for the teams that provide admin and direct write access to the repos)
- who should be listed as approvers in the OWNERS file at repo root

Given the answer of "@childsb @saad-ali @vladimirvivien ..." it's unclear to me whether these three people should have all of the above, and whether there are more than these three implied.  Can you clarify?

**Comment by saad-ali** [comment]
> who should have admin access to the repo (these people will be setup as team maintainers for the teams that provide admin and direct write access to the repos)

@childsb and @saad-ali

> who should be listed as approvers in the OWNERS file at repo root

@childsb and @saad-ali intentionally and we can add in folks as needed.

**Comment by saad-ali** [comment]
> Are these all under the kubernetes-csi subproject, or do you want something like a "csi-drivers" subproject for this?

Either way is ok. Slightly leaning towards putting everything under `kubernetes-csi` subproject.

**Comment by spiffxp** [comment]
/close
OK, this is all done AFAIK
