### ISSUE TITLE
REQUEST: New membership for drubin

### ISSUE THREAD

**Issue by drubin** [kubernetes/org#921]
### GitHub Username
@drubin

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @brendandburns
- @lavalamp

### List of contributions to the Kubernetes project
- [Pull requests to ruby client (3)](https://github.com/kubernetes-client/ruby/pulls?q=is%3Apr+is%3Aclosed+author%3Adrubin)
- [Pull requests to javascript client (9)](https://github.com/kubernetes-client/javascript/pulls?q=is%3Apr+is%3Aclosed+author%3Adrubin)
- SIG-APIMachinery
- Currently the main co-maintainer of both the Typescript/Javascript and Ruby kubernetes client libaries.

#### Extra
Thanks for your consideration, if you require any other infomration let me know?

**Comment by lavalamp** [comment]
+1

**Comment by brendandburns** [comment]
+1

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #923 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
