### ISSUE TITLE
REQUEST: New membership for medmedchiheb

### ISSUE THREAD

**Issue by medmedchiheb** [kubernetes/org#925]
### GitHub Username
@medmedchiheb 
### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rlenferink
- @tpepper

### List of contributions to the Kubernetes project
- PRs reviewed / authored
[kubernetes-sigs/contributor-playground#291]( https://github.com/kubernetes-sigs/contributor-playground/pull/291)
[kubernetes/website#14806](https://github.com/kubernetes/website/pull/14806)
[kubernetes/website#14866](https://github.com/kubernetes/website/pull/14866)
[kubernetes/website#14895](https://github.com/kubernetes/website/pull/14895)
[kubernetes/dashboard#3937](https://github.com/kubernetes/dashboard/pull/3937)
[kubernetes/website#14959](https://github.com/kubernetes/website/pull/14959)
[kubernetes/website#14976](https://github.com/kubernetes/website/pull/14976)
- Issues responded to
[kubernetes/website#14477](https://github.com/kubernetes/website/issues/14477)
[kubernetes/kubernetes#79080](https://github.com/kubernetes/kubernetes/issues/79080)
[kubernetes/kubernetes#79134](https://github.com/kubernetes/kubernetes/issues/79134)
[kubernetes/website#14958](https://github.com/kubernetes/website/issues/14958)

- SIG projects I am involved with
SIG-contribex , SIG-DOCS and  SIG-RELEASE

**Comment by tpepper** [comment]
+1

**Comment by rlenferink** [comment]
+1 thanks for your contributions so far @medmedchiheb 🎉

**Comment by mrbobbytables** [comment]
Hey there @medmedchiheb  thank you for all your contributions thus far \o/

I've created PR #931  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
