### ISSUE TITLE
REQUEST: New membership for @f0rmiga

### ISSUE THREAD

**Issue by f0rmiga** [kubernetes/org#926]
### GitHub Username
@f0rmiga

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nikhita 
- @carolynvs

### List of contributions to the Kubernetes project

I'm involved with the [Minibroker project](https://github.com/kubernetes-sigs/minibroker) under the service-catalog SIG.

#### PR's in the project
- https://github.com/kubernetes-sigs/minibroker/pull/24
- https://github.com/kubernetes-sigs/minibroker/pull/25

**Comment by nikhita** [comment]
+1

/meow space

**Comment by nikhita** [comment]
Just for the record: @f0rmiga also needs to be added as an approver to minibroker (https://github.com/kubernetes-sigs/minibroker/pull/33), which requires membership to the org.

**Comment by carolynvs** [comment]
+1 💯

**Comment by mrbobbytables** [comment]
@f0rmiga thanks for helping with the minibroker project :)

I've created PR # 931 to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign

**Comment by f0rmiga** [comment]
@mrbobbytables Thanks! It's a pleasure helping with it!
