### ISSUE TITLE
REQUEST: New membership for corneliusweig

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes/org#929]
### GitHub Username
@corneliusweig

### Organization you are requesting membership in
(at)kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects (krew)
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ahmetb 
- @soltysh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored: https://github.com/kubernetes-sigs/krew/pull/212, https://github.com/kubernetes-sigs/krew/pull/211, https://github.com/kubernetes-sigs/krew/pull/208, https://github.com/kubernetes-sigs/krew/pull/203, https://github.com/kubernetes-sigs/krew/pull/202, https://github.com/kubernetes-sigs/krew/pull/201, https://github.com/kubernetes-sigs/krew/pull/195, https://github.com/kubernetes-sigs/krew/pull/191, https://github.com/kubernetes-sigs/krew/pull/183, https://github.com/kubernetes-sigs/krew/pull/178, https://github.com/kubernetes-sigs/krew/pull/177, https://github.com/kubernetes-sigs/krew/pull/176
- Issues responded to: (among others) https://github.com/kubernetes-sigs/krew/issues/200, https://github.com/kubernetes-sigs/krew/issues/168, https://github.com/kubernetes-sigs/krew/issues/199, https://github.com/kubernetes-sigs/krew/issues/196, https://github.com/kubernetes-sigs/krew/issues/190, 
- SIG projects I am involved with: `krew`

**Comment by ahmetb** [comment]
I approve.

**Comment by nzoueidi** [comment]
Hey @corneliusweig you will need one additional eligible sponsor. Thus, you should reach out to them so they can sponsor you.

**Comment by corneliusweig** [comment]
Hey @nzoueidi, thanks for the reminder. I reached out to @.soltysh but he's quite busy I presume. So I'm still waiting for his response.

**Comment by justaugustus** [comment]
Hey @soltysh, do you have a moment to approve @corneliusweig's org membership?

**Comment by soltysh** [comment]
Yes, sorry for the delay :+1: from me :)

**Comment by nzoueidi** [comment]
Hey there @corneliusweig, thank you for all your contributions so far :)

I've created PR #967   to add you to the @kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
