### ISSUE TITLE
REQUEST: New membership for mariantalla

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/org#93]
### GitHub Username
@mariantalla

### Organizations I'm requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hoegaarden
- @tpepper

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - [Setup TLS with CA Cert for vsphere cloud provider](https://github.com/kubernetes/kubernetes/pull/64758)
  - [Kubeadm types remove deps](https://github.com/kubernetes/kubernetes/pull/64505) (not merged, conversation evolved in the testing framework KEP)
  - [Script to automatically add licence headers](https://github.com/kubernetes/repo-infra/pull/82)
  - [Support for parallel clusters](https://github.com/kubernetes-sigs/kubeadm-dind-cluster/pull/161)
  - [Introduce tests for IPv6, update documentation about testing/contributing](https://github.com/kubernetes-sigs/kubeadm-dind-cluster/pull/190)
  - [KEP test cluster framework](https://github.com/kubernetes/community/pull/2178) (pair created with @hoegaarden)

- Issues responded to
N/A

- SIG projects I am involved with
  - Testing commons: [testing framework](https://github.com/kubernetes-sigs/testing_frameworks)
  - sig-release: shadowing release for 1.12, shadowing CI signal for 1.13
  - sig-vmware ([PR](https://github.com/kubernetes/kubernetes/pull/64758)) and sig-contributor-experience ([PR to automate licence adds for contributors](https://github.com/kubernetes/repo-infra/pull/82))

**Comment by spiffxp** [comment]
invite sent, welcome!
