### ISSUE TITLE
REQUEST: New membership for onlydole

### ISSUE THREAD

**Issue by onlydole** [kubernetes/org#932]
### GitHub Username
@onlydole

### Organization you are requesting membership in
[@kubernetes](https://github.com/kubernetes?type=source)

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @kbarnard10 
- @castrojo

#### PRs reviewed / authored
- https://github.com/kubernetes/website/pull/14994
- https://github.com/kubernetes/sig-release/pull/671
- https://github.com/kubernetes/sig-release/pull/561
- https://github.com/kubernetes/sig-release/pull/475

#### Issues responded to
- https://github.com/kubernetes/sig-release/issues/578
- https://github.com/kubernetes/sig-release/issues/648
- https://github.com/kubernetes/sig-release/issues/545
- https://github.com/kubernetes/kubernetes/issues/23092

#### SIG projects I am involved with
- [SIG-release](https://github.com/kubernetes/sig-release)

**Comment by kbarnard10** [comment]
+1

**Comment by cblecker** [comment]
I know that guy!
Not a sponsor, but +1 from me too

**Comment by castrojo** [comment]
+1 from me, Taylor's been a shadow for a few releases now on the comms team and will be the lead for 1.16.

**Comment by nwoods3** [comment]
+1 (non-binding), Taylor has been a great Comms shadow for the 1.14 and 1.15 releases.

**Comment by nzoueidi** [comment]
Hey there @onlydole thank you for all your contributions so far :)

I've created PR #942 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign

**Comment by justaugustus** [comment]
+1! Thanks for your help on the Release Team, Taylor!!

**Comment by onlydole** [comment]
Thank you all for being such an incredible team to work with! I'm looking forward to doing more and more within the community 😁 🎉
