### ISSUE TITLE
REQUEST: New membership for mysunshine92

### ISSUE THREAD

**Issue by mysunshine92** [kubernetes/org#933]
### GitHub Username
@mysunshine92

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @zhangxiaoyu-zidif 
- @xiangpengzhao 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amysunshine92+archived%3Afalse+

- Issues responded to
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Amysunshine92+archived%3Afalse+

- SIG projects I am involved with
kubernetes/sig-node
kubernetes/sig-apps

**Comment by zhangxiaoyu-zidif** [comment]
+1

**Comment by xiangpengzhao** [comment]
+1 :+1:

**Comment by nzoueidi** [comment]
Hey there @mysunshine92 thank you for all your contributions so far :)

I've created PR #942 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
