### ISSUE TITLE
REQUEST: New membership for hoyho

### ISSUE THREAD

**Issue by hoyho** [kubernetes/org#935]
### GitHub Username
@hoyho

### Organization you are requesting membership in
@kubernetes
@kubernetes-csi

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pohly
- @msau42 
- @jsafrane 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
[https://github.com/kubernetes/kubernetes/pull/78306](https://github.com/kubernetes/kubernetes/pull/78306)
[https://github.com/kubernetes-csi/docs/pull/174](https://github.com/kubernetes-csi/docs/pull/174)
[https://github.com/kubernetes-csi/external-provisioner/pull/270](https://github.com/kubernetes-csi/external-provisioner/pull/270)
[https://github.com/kubernetes-csi/external-provisioner/pull/271](https://github.com/kubernetes-csi/external-provisioner/pull/271)
[https://github.com/kubernetes-csi/external-attacher/pull/152](https://github.com/kubernetes-csi/external-attacher/pull/152)
[https://github.com/kubernetes-csi/external-snapshotter/pull/130](https://github.com/kubernetes-csi/external-snapshotter/pull/130)
[https://github.com/kubernetes-csi/csi-release-tools/pull/19](https://github.com/kubernetes-csi/csi-release-tools/pull/19)
[https://github.com/kubernetes/kubernetes/pull/78267](https://github.com/kubernetes/kubernetes/pull/78267)

- Issues responded to
[https://github.com/kubernetes/kubernetes/issues/78165](https://github.com/kubernetes/kubernetes/issues/78165)
[https://github.com/kubernetes/kubernetes/issues/77104](https://github.com/kubernetes/kubernetes/issues/77104)
[https://github.com/kubernetes/kubernetes/issues/78149](https://github.com/kubernetes/kubernetes/issues/78149)
[https://github.com/kubernetes/kubernetes/issues/74689](https://github.com/kubernetes/kubernetes/issues/74689)
[https://github.com/kubernetes/kubernetes/issues/72207](https://github.com/kubernetes/kubernetes/issues/72207)
[https://github.com/kubernetes-csi/csi-release-tools/pull/19](https://github.com/kubernetes-csi/csi-release-tools/pull/19)
[https://github.com/kubernetes-csi/csi-driver-nfs/issues/11](https://github.com/kubernetes-csi/csi-driver-nfs/issues/11)

- SIG projects I am involved with
[kubernetes-csi/docs](https://github.com/kubernetes-csi/docs)
[kubernetes-csi/external-provisioner](https://github.com/kubernetes-csi/external-provisioner)
[kubernetes-csi/external-attacher](https://github.com/kubernetes-csi/external-attacher)
[kubernetes-csi/external-snapshotter](https://github.com/kubernetes-csi/external-snapshotter)

**Comment by jsafrane** [comment]
+1 from me as sponsor.

**Comment by msau42** [comment]
+1!

**Comment by nzoueidi** [comment]
Hey there @hoyho thank you for all your contributions so far :)

I've created PR #942  to add you to the Kubernetes and Kubernetes-csi Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes and to @kubernetes-csi! 🎉

/assign
