### ISSUE TITLE
REQUEST: New membership for michaelgugino

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/org#936]
### GitHub Username
@michaelgugino

### Organization you are requesting membership in
@sig-cluster-lifecycle

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timothysc
- @ncdc

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api/pull/905
Lots of proposal discussion participation

- Issues responded to
https://github.com/kubernetes-sigs/cluster-api/issues/963
https://github.com/kubernetes-sigs/cluster-api/issues/994

- SIG projects I am involved with
cluster-api

**Comment by nikhita** [comment]
> @sig-cluster-lifecycle

@michaelgugino just to be clear, you are requesting membership in @kubernetes-sigs, correct?

**Comment by michaelgugino** [comment]
@nikhita I'm looking to work on cluster-api subproject of sig-cluster-lifecycle.  So, whatever membership that entails, I'm not entirely sure?  I thought maybe it was sig-cluster-lifecycle.

**Comment by nikhita** [comment]
Yeah, that would be @kubernetes-sigs :)

**Comment by ncdc** [comment]
Not sure if I need to reply, but I agree to sponsor Michael's application.

**Comment by ncdc** [comment]
@michaelgugino I think you need to have sponsors from different companies, so we'll need to find another person since both Tim & I are at VMware.

**Comment by davidewatson** [comment]
👍 from me.

**Comment by timothysc** [comment]
That's 2 now.

**Comment by timothysc** [comment]
@michaelgugino - welcome.  https://github.com/kubernetes/community/blob/master/sig-cluster-lifecycle/grooming.md is SOP.

**Comment by nzoueidi** [comment]
Hey there @michaelgugino thank you for all your contributions so far :)

I've created PR #942   to add you to the Kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
