### ISSUE TITLE
Request for new repo owned by Cluster API group

### ISSUE THREAD

**Issue by chuckha** [kubernetes/org#937]
### New Repo, Staging Repo, or migrate existing
New repository

### Requested name for new repository
cluster-api-bootstrap-provider-kubeadm

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@chuckha +https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES

### If not a staging repo, who should have write access
@chuckha + https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES

### If not a staging repo, who should be listed as approvers in OWNERS
@chuckha + https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES

### If not a staging repo, who should be listed in SECURITY_CONTACTS
https://github.com/kubernetes-sigs/cluster-api/blob/master/SECURITY_CONTACTS

### What should the repo description be
by default we will set it to "created due to (link to this issue)"

### What SIG and subproject does this fall under in sigs.yaml
This is part of the cluster-api subproject for sig-cluster-lifecycle

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
I will figure out the owners files later as I do not want to be the only approver/etc as the project progresses, but listed above is a basic start

**Comment by nikhita** [comment]
@timothysc can you lgtm here?

**Comment by justaugustus** [comment]
+1

**Comment by mrbobbytables** [comment]
Should be able to get this created later today or at the latest early tomorrow morning 👍

**Comment by mrbobbytables** [comment]
Hey there @chuckha The repo has been created here:
https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm 👍 

Before creating the teams, I just want to double check -- for the admin and write access permissions, are you asking for everyone in the `OWNERS_ALIASES` to be granted access? or just the `sig-cluster-lifecycle-leads` similar to the request in #938 ?

**Comment by chuckha** [comment]
I'm asking for me + leads so I don't have to bug a lead every time I need something, but I defer to @timothysc  who has opinions on this kind of thing.

**Comment by chuckha** [comment]
Let me make my request more clear:

```
admins:
  - sig-cluster-lifecycle-leads
  - me if possible

approvers:
- approvers:
  - sig-cluster-lifecycle-leads
  - cluster-api-admins
  - cluster-api-maintainers
  - cluster-api-bootstrap-provider-kubeadm-maintainers

reviewers:
  - cluster-api-maintainers
  - cluster-api-bootstrap-provider-kubeadm-maintainers
```

**Comment by mrbobbytables** [comment]
- Repo has been created.
- Teams added in #951 
Once https://github.com/kubernetes/community/pull/3839 is merged, things should be good to go, and the issue can be closed 👍

**Comment by mrbobbytables** [comment]
As https://github.com/kubernetes/community/pull/3839 has now been merged, I am going to go ahead and close this issue. 

@chuckha if you need anything else, please feel free to reopen. 😄 

/close
