### ISSUE TITLE
Migrate existing repo

### ISSUE THREAD

**Issue by chuckha** [kubernetes/org#938]
### New Repo, Staging Repo, or migrate existing
migrate existing from https://github.com/chuckha/cluster-api-provider-docker to kubernetes-sigs

### Requested name for new repository
cluster-api-provider-docker

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@chuckha, sig-cluster-lifecycle-leads

### If not a staging repo, who should have write access
@chuckha, sig-cluster-lifecycle-leads

### If not a staging repo, who should be listed as approvers in OWNERS
@chuckha, @sethp-nr, sig-cluster-lifecycle-leads

sig-cluster-lifecycle-leads:
* @justinsb 
* @luxas 
* @timothysc 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
sig-cluster-lifecycle-leads

### What should the repo description be
by default we will set it to "created due to (link to this issue)"

### What SIG and subproject does this fall under in sigs.yaml
this is part of the cluster-api subproject for sig-cluster-lifecycle

### Approvals
Please prove you have followed the appropriate approval process for this new
repo by including links to the relevant approvals (meeting minutes, e-mail
thread, etc.)

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

tl;dr (but really you should read the linked doc, this may be stale)
- If this is a core repository, then sig-architecture must approve
- If this is a SIG repository, then this must follow the procedure spelled out
  in that SIG's charter

### Additional context for request
the owners file will be fleshed out as the project progresses

**Comment by timothysc** [comment]
Could you cross-link a PR to the community to update the OWNERS files references for the subproject.  They should also have similar owners.

**Comment by chuckha** [comment]
isn't it all copy and pasted like https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/OWNERS_ALIASES ?

**Comment by timothysc** [comment]
I was aussuming ~= https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS_ALIASES + whoever has been working on the repo with you.

**Comment by chuckha** [comment]
ok, the goal is to manage owners of projects entirely through the cluster-api OWNERS_ALIAS/OWNERS file?

That seems weird to me, does that mean projects owned by the cluster-api group outside of cluster-api will *not* have an OWNERS file? Should we delete the different provider owners files and merge them into cluster-api OWNERS?

**Comment by nikhita** [comment]
The repo needs `CONTRIBUTING.md` and `SECURITY_CONTACTS` files but I'm good with adding these post migration as well. :+1: 

And I ran a [FOSSA license scan](https://app.fossa.com/projects/git%2Bgithub.com%2Fnikhita-bot%2Fcluster-api-provider-docker/refs/branch/master/cbf3654b0b1d6ff513be844714d9e24c261bbe22) on the repo. There are a few false positives listed, but it's all good. :+1: 

GitHub doesn't allow transferring repos owned by a single person (only orgs), so this will need to be moved to a dummy org. @chuckha I'll follow up on this with you on slack.

**Comment by nikhita** [comment]
Migration done: https://github.com/kubernetes-sigs/cluster-api-provider-docker :tada: 

Created https://github.com/kubernetes/org/pull/939 to add teams to provide admins + write access to the repo. We'll also need to update sigs.yaml... let's reuse https://github.com/kubernetes/community/pull/3818? :)

**Comment by nikhita** [comment]
Granted access to relevant teams.

We can close this issue once https://github.com/kubernetes/community/pull/3822 merges, and the repo has `CONTRIBUTING.md` and `SECURITY_CONTACTS` files.

**Comment by justinsb** [comment]
Should this be cluster-api-provider-docker or cluster-api-provider-cri?

**Comment by chuckha** [comment]
I played with that idea! but it's strictly docker right now. As it progresses we may consider a rename in future.

**Comment by nikhita** [comment]
This is done.

/close
