### ISSUE TITLE
REQUEST: New membership for Liujingfang1

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes/org#940]
### GitHub Username
Liujingfang1

### Organization you are requesting membership in
kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @seans3
- @soltysh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/75005
https://github.com/kubernetes/kubernetes/pull/73033
https://github.com/kubernetes-sigs/kustomize/pull/633
https://github.com/kubernetes-sigs/kustomize/pull/632
https://github.com/kubernetes-sigs/kustomize/pull/621
- Issues responded to
https://github.com/kubernetes-sigs/kustomize/issues?q=is%3Aissue+assignee%3ALiujingfang1+is%3Aclosed

- SIG projects I am involved with
sig-cli kubectl
sig-cli kustomize

**Comment by seans3** [comment]
+1

**Comment by justaugustus** [comment]
+1

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #947 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
