### ISSUE TITLE
REQUEST: New membership for alexeldeib

### ISSUE THREAD

**Issue by alexeldeib** [kubernetes/org#943]
### GitHub Username
@alexeldeib

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @juan-lee
- @justaugustus 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=author%3Aalexeldeib+user%3Akubernetes+user%3Akubernetes-sigs+user%3Ahelm+user%3Acncf&type=Issues
- SIG projects I am involved with
  - Cluster API/cluster-api-provider-azure
  - Kubebuilder/controller-runtime/controller-tools

**Comment by justaugustus** [comment]
+1! Ace has been a big help on Cluster API Azure! :)

**Comment by juan-lee** [comment]
+1 - I vouch for @alexeldeib based on his involvement in Cluster API Azure and other projects we've collaborated on.

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #947 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
