### ISSUE TITLE
REQUEST: New membership for zulandar

### ISSUE THREAD

**Issue by zulandar** [kubernetes/org#944]
### GitHub Username
@zulandar

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @f0rmiga
- @carolynvs

### List of contributions to the Kubernetes project
- PRs reviewed / authored
[https://github.com/kubernetes-sigs/minibroker/pull/35](https://github.com/kubernetes-sigs/minibroker/pull/35)
[https://github.com/kubernetes-sigs/minibroker/pull/32](https://github.com/kubernetes-sigs/minibroker/pull/32)
- Issues responded to
[https://github.com/kubernetes-sigs/minibroker/issues/11](https://github.com/kubernetes-sigs/minibroker/issues/11)
[https://github.com/kubernetes-sigs/service-catalog/issues/2658](https://github.com/kubernetes-sigs/service-catalog/issues/2658)
[https://github.com/kubernetes-sigs/minibroker/issues/34](https://github.com/kubernetes-sigs/minibroker/issues/34)
[https://github.com/kubernetes-sigs/minibroker/issues/23](https://github.com/kubernetes-sigs/minibroker/issues/23)
- SIG projects I am involved with
[https://github.com/kubernetes-sigs/minibroker](https://github.com/kubernetes-sigs/minibroker)
[https://github.com/kubernetes-sigs/service-catalog](https://github.com/kubernetes-sigs/service-catalog)

**Comment by carolynvs** [comment]
+1

**Comment by f0rmiga** [comment]
+1

**Comment by justaugustus** [comment]
Hey @zulandar, @f0rmiga appears to only be a member of kubernetes-sigs.
You'll need to find one more non-Microsoft sponsor who is already a reviewer/approver in the kubernetes org.

Check out https://github.com/kubernetes/community/blob/master/community-membership.md#requirements for more details. :)

**Comment by carolynvs** [comment]
@zulandar  Did you mean to apply to the kuberentes org or to kubernetes-sigs? Just asking in case you intended to apply to kubernetes-sigs, because both minibroker and service-catalog are in the kubernetes-sigs organization.

**Comment by zulandar** [comment]
@carolynvs kubernetes-sigs was the org I was intending to apply for. I've adjusted the request. 

@justaugustus I've adjusted my request let me know if I need another sponsor.

**Comment by justaugustus** [comment]
Thanks for the clarification, @carolynvs! We'll get you processed, @zulandar! :)

**Comment by nzoueidi** [comment]
Hey there @zulandar , thank you for all your contributions so far :)

I've created PR #950  to add you to the @kubernetes-sigs Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes-sigs! 🎉

/assign
