### ISSUE TITLE
Add dependabot to the kubernetes-client organization.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/org#945]
### Organization or repository
kubernetes-client/javascript

### Name of integration
dependabot

### Link to integration website
https://github.com/marketplace/dependabot-preview

### Describe what is attempting to be accomplished
Dependabot automatically sends PRs for updates to dependencies due to security issues.

### Additional context for request
N/A

Thanks!

**Comment by cblecker** [comment]
Hey @brendandburns! I've been investigating this.. GitHub now integrates dependabot right into your repo settings, but there have been two issues in testing:
- It opens branches directly on your repo (not a fork), so these new branches get protected by prow
- The bot doesn't have a CLA signed, so it gets blocked on the CLA context

We're working on both of these, and I'll let you know when we make progress

/assign

**Comment by brendandburns** [comment]
@cblecker Thanks, I'm happy to guinea pig test anything you need, this will save us a bunch of time.

**Comment by cblecker** [comment]
One puzzle piece is in place: https://github.com/kubernetes/test-infra/pull/13016

This will allow is to exempt these branches from protection, so we can clean them up.

**Comment by yue9944882** [comment]
a polite bump, any updates in this thread?

**Comment by cblecker** [comment]
I opened a PR earlier today (https://github.com/kubernetes/test-infra/pull/13445) to get the regex in place. Still need to figure out the CLA stuff though.

**Comment by cblecker** [comment]
Poked CLA issue again: https://github.com/cncf/foundation/issues/3#issuecomment-511532076

**Comment by shu-mutou** [comment]
kubernetes/dashboard repo also uses dependabot and faces same problem.

**Comment by cblecker** [comment]
This is now enabled and is functional on https://github.com/kubernetes-client/javascript/network/alerts

/close
