### ISSUE TITLE
REQUEST: New membership for aojea

### ISSUE THREAD

**Issue by aojea** [kubernetes/org#952]
### GitHub Username

@aojea 

### Organization you are requesting membership in

@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @BenTheElder 
- @neolit123 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

[PRs authored in kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aaojea)
[PRs authored in kubernetes-sigs/kind](https://github.com/kubernetes-sigs/kind/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aaojea)

- Issues responded to

[Issues responded in kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=mentions%3Aaojea)
[Issues responded in kubernetes-sigs/kind](https://github.com/kubernetes-sigs/kind/issues?utf8=%E2%9C%93&q=mentions%3Aaojea)

- SIG projects I am involved with

https://github.com/kubernetes-sigs/kind

**Comment by nikhita** [comment]
+1

**Comment by neolit123** [comment]
+1. already a member of k/kuberentes-sigs so eligible for k/kubernetes too. :)

**Comment by BenTheElder** [comment]
+100000!

**Comment by justaugustus** [comment]
(As a point of clarification, membership to `kubernetes` implicitly makes you eligible for membership to our other non-hidden orgs, but not the other way around.)

**Comment by justaugustus** [comment]
@aojea -- Thanks so much for your contributions thus far!
I've created #960 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign

**Comment by BenTheElder** [comment]
> (As a point of clarification, membership to kubernetes implicitly makes you eligible for membership to our other non-hidden orgs, but not the other way around.)

I know this is not the place to discuss this but ... I think we really should not distinguish between kubernetes-sigs and kubernetes as we move things out of the main org to kubernetes-sigs pretty aggressively. It sends a bad / the wrong message that kubernetes-sigs has a different bar as we move projects from kubernetes to kubernetes-sigs...

In any case, @aojea has done a lot of wonderful and woefully understaffed work in both orgs in his spare time, thank you again!

**Comment by aojea** [comment]
Thanks folks

**Comment by justaugustus** [comment]
@BenTheElder -- I completely on all points and have opened https://github.com/kubernetes/org/issues/966 to discuss.

As an aside, I was surprised @aojea wasn't already in the org! :)

**Comment by BenTheElder** [comment]
thanks @justaugustus!! :-)
