### ISSUE TITLE
REQUEST: New membership for zhucan

### ISSUE THREAD

**Issue by zhucan** [kubernetes/org#953]
### GitHub Username
@zhucan

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@j-griffith
@humblec
@msau42 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pull/79015
  https://github.com/kubernetes-csi/external-snapshotter/pull/129

- Issues responded to
   https://github.com/kubernetes-csi/csi-driver-host-path/issues/46
   https://github.com/kubernetes-csi/external-snapshotter/issues/117
   https://github.com/kubernetes-csi/external-snapshotter/issues/115

- SIG projects I am involved with
   @kubernetes

**Comment by msau42** [comment]
+1 @zhucan is helping with snapshots

**Comment by nzoueidi** [comment]
Hey @j-griffith @humblec do you have a moment to approve zhucan's org membership?

Thanks.

**Comment by spiffxp** [comment]
Thanks for all of your contributions!

Once #969 gets merged, you should get a membership invite notification.

Welcome to the project! 🎉

/meowvie
