### ISSUE TITLE
REQUEST: New membership for @srampal

### ISSUE THREAD

**Issue by srampal** [kubernetes/org#956]
### GitHub Username
srampal

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @tashimi
- @nikhita 

### List of contributions to the Kubernetes project
- SIG projects I am involved with
Co-lead and contributor to K8s Multitenancy WG 
https://github.com/kubernetes-sigs/multi-tenancy

**Comment by tashimi** [comment]
Welcome! 

+1

![tenor-155941164](https://user-images.githubusercontent.com/719646/60140929-34d0c180-9768-11e9-9c4b-f7d24fa7d39a.gif)

**Comment by nikhita** [comment]
+1

**Comment by justaugustus** [comment]
@srampal -- Thanks so much for your contributions thus far!
I've created #960 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
