### ISSUE TITLE
Create new repository kubernetes-sigs/node-feature-discovery-operator

### ISSUE THREAD

**Issue by marquiz** [kubernetes/org#957]
### New Repo, Staging Repo, or migrate existing
new repository

### Requested name for new repository
node-feature-discovery-operator

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@marquiz, @zvonkok

### If not a staging repo, who should have write access
@marquiz, @zvonkok

### If not a staging repo, who should be listed as approvers in OWNERS
@marquiz, @zvonkok

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@marquiz, @zvonkok

### What should the repo description be
Operator for managing Node Feature Discovery deployment

### What SIG and subproject does this fall under in sigs.yaml
This is part of the node-feature-discovery subproject for sig-node

### Approvals
Was discussed in [SIG Node meeting](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg) on June 18th.

Related [SIG Node mailing list thread](https://groups.google.com/forum/#!topic/kubernetes-sig-node/ozLcB1H90vA)

Authoritative requirements are here: https://git.k8s.io/community/github-management/kubernetes-repositories.md

### Additional context for request
/cc @derekwaynecarr, @dchen1107

**Comment by nikhita** [comment]
Created https://github.com/kubernetes-sigs/node-feature-discovery-operator :tada: 

Also created:

- https://github.com/kubernetes/org/pull/959 - to add GitHub teams to grant access to the repo
- https://github.com/kubernetes/community/pull/3845 - to add the repo to sigs.yaml

Once both PRs merge, we can close the issue.

**Comment by nikhita** [comment]
This is done now.

/close
