### ISSUE TITLE
REQUEST: New membership for @hantaowang

### ISSUE THREAD

**Issue by hantaowang** [kubernetes/org#961]
### GitHub Username
@hantaowang

### Organization you are requesting membership in
https://github.com/kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@davidz627
@msau42 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
[All PRs by Me](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ahantaowang+)
- Issues responded to
[1](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/308) 
[2](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/307) 
[3](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/296) 
[4](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/298) 
[5](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/277)
- SIG projects I am involved with
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver

**Comment by msau42** [comment]
+1

Will is going to be working extensively with the gce pd csi driver.

**Comment by davidz627** [comment]
+1
Will has been doing great work so far and I believe has much more to contribute :)

**Comment by justaugustus** [comment]
@hantaowang -- you'll need to find one more non-Google sponsor, before I can add you to the org.

**Comment by davidz627** [comment]
@justaugustus, Will will be working primarily on the gcp-compute-persistent-disk-csi-driver which is mainly supported by Google folks so non-googlers have not had the chance to meet Will or review his code yet. I feel that since there are many Cloud Provider specific repo's in the "kubernetes-sigs" org that this may be a pattern that we see more of in the future. Are we able to get an exception for this case or is there a place where I can submit a request to rethink the org membership policy for these orgs that contain many more cloud provider specific repos?

**Comment by stevekuznetsov** [comment]
+1 from me as well
I looked at hantaowang’s linked PRs and it’s clear they’re actively contributing to the driver

**Comment by spiffxp** [comment]
Thanks for all of your contributions!

Once #969 gets merged, you should get a membership invite notification.

Welcome to the project! 🎉

/meowvie

**Comment by hantaowang** [comment]
Hi while this issue has been closed and the associated PR has been merged, I still have not received an invite to kubernetes-sigs. Does this normally take this long?

**Comment by cblecker** [comment]
@hantaowang A piece of our CI was broken. You should now have an invite.
