### ISSUE TITLE
REQUEST: New membership for @pswica

### ISSUE THREAD

**Issue by pswica** [kubernetes/org#962]
### GitHub Username
@pswica

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @seans3
- @justaugustus 

### List of contributions to the Kubernetes project:
Just a few:
- https://github.com/kubernetes/kubernetes/pull/79204
- https://github.com/kubernetes/kubernetes/pull/79000
- https://github.com/kubernetes/kubernetes/pull/78825
- https://github.com/kubernetes/release/pull/747
- https://github.com/kubernetes/release/pull/745

**Comment by seans3** [comment]
+1

**Comment by justaugustus** [comment]
+1. Peter has been diving in head-first on cleaning up some of the release engineering tooling and I'm looking forward to more contributions from him! :)

**Comment by justaugustus** [comment]
I've created #965 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign

**Comment by idealhack** [comment]
+1

@pswica welcome on board!
