### ISSUE TITLE
Investigate GitHub Subscriptions for our orgs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/org#963]
### Organization or repository
kuberentes
kubernetes-client
kubernetes-csi
kubernetes-incubator
kubernetes-security
kubernetes-sigs
kubernetes-retired

### Describe the issue
These orgs have different billing settings.  It's not clear that they should.  ~At a minimum we should probably be using the "GitHub Team for Open Source" subscription everywhere~ 

UPDATE: GitHub Team for Open Source got folded into GitHub Free. Are we OK with some orgs having GitHub Team, and some having GitHub Free?

- [kubernetes](https://github.com/organizations/kubernetes/settings/billing) - GitHub Team (w/ coupon, monthly)
- [kubernetes-client](https://github.com/organizations/kubernetes-client/settings/billing) - GitHub Free
- [kubernetes-csi](https://github.com/organizations/kubernetes-csi/settings/billing) - GitHub Free
- [kubernetes-incubator](https://github.com/organizations/kubernetes-incubator/settings/billing) - GitHub Free
- [kubernetes-security](https://github.com/organizations/kubernetes-security/settings/billing) - GitHub Team (w/ coupon, annual)
- [kubernetes-sigs](https://github.com/organizations/kubernetes-sigs/settings/billing) - GitHub Free
- [kubernetes-retired](https://github.com/organizations/kubernetes-retired/settings/billing) - GitHub Free

ref: https://github.com/pricing

**Comment by nikhita** [comment]
cc @idvoretskyi @dims

**Comment by idvoretskyi** [comment]
@spiffxp the proper way to handle the GitHub billing/plan questions - submit a request via the CNCF's ServiceDesk - https://github.com/cncf/servicedesk#how-do-i-file-a-ticket-with-the-service-desk.

**Comment by nikhita** [comment]
Update: the kubernetes-security coupon which provided us free access to GitHub Team recently expired (it was valid for 2 years). We now have a new coupon (thanks to GitHub!) which provides us 100% off forever.

**Comment by cblecker** [comment]
/unassign
/assign @idvoretskyi

So it looks like kubernetes and kubernetes-security now have the GitHub Team coupon that allows us private repos. There's still an odd discrepancy on our other orgs that some are GitHub Free and some are GitHub Teams for Open Source. Not sure what the difference is there.

I'm also curious if there is any chance of us upgrading to Enterprise plans, mostly because I would love to use https://github.com/maintainers/early-access-feedback/issues/269.. It couldn't hurt to ask GH about it.

Once we have answers to the above, I think we can close this one off. Thanks for taking the lead, Ihor!

**Comment by idvoretskyi** [comment]
> So it looks like kubernetes and kubernetes-security now have the GitHub Team coupon that allows us private repos. There's still an odd discrepancy on our other orgs that some are GitHub Free and some are GitHub Teams for Open Source. Not sure what the difference is there.

It seems that the last public org audit was performed by @spiffxp half a year ago. Can we do a new audit in the nearest future to understand our current state of the orgs?

> I'm also curious if there is any chance of us upgrading to Enterprise plans, mostly because I would love to use maintainers/early-access-feedback#269.. 

Any other desired features with the Enterprise plan besides this one? :)

**Comment by cblecker** [comment]
> Can we do a new audit in the nearest future to understand our current state of the orgs?

I've verified the current status in the body of this issue, as well as added links to the billing page so it's easier for any Owner to do :)

**Comment by idvoretskyi** [comment]
@cblecker awesome, thanks!

**Comment by spiffxp** [comment]
/milestone v1.19
@idvoretskyi I just audited the orgs' billing settings, nothing has changed since I originally opened this issue. I still think we should have the same setting for all of our orgs.  What are next steps on your end?

**Comment by idvoretskyi** [comment]
@spiffxp could you (or someone else from Steering) please raise the formal request with the proposed plans upgrade/change to the CNCF ServiceDesk  - http://servicedesk.cncf.io/; we'll take it from there.

Thanks!

**Comment by idvoretskyi** [comment]
FYI @spiffxp @cblecker - GitHub has announced some updates (https://help.github.com/en/github/getting-started-with-github/faq-about-changes-to-githubs-plans), can we investigate if some of these updates are valuable for us?

**Comment by spiffxp** [comment]
I've refreshed the description accordingly to handle where the plans are at.  I don't view this as an upgrade or beneficial for us, but I think I'm OK with where our plans stand now.

The two orgs that are on GitHub Team (kubernetes, kubernetes-security) will have their private-repo GitHub Action minutes reduced from 10k to 3k.  This doesn't impact us since we don't use GitHub Actions on private repos in kubernetes-security, and have no private repos in kubernetes.

Looking at the Compare features chart on https://github.com/pricing I would not want to downgrade our existing GitHub Team plans:
- GitHub Free lacks e-mail support (which we definitely want for at least kubernetes and kubernetes-security)
- GitHub Free lacks workflow features for private repos (which we definitely want for kubernetes-security)

I would like to hear from members of the team what we would like to pursue here

**Comment by spiffxp** [comment]
/close
Discussed during meeting, we're ok with the current state of affairs
