### ISSUE TITLE
REQUEST: New membership for <@verolop>

### ISSUE THREAD

**Issue by Verolop** [kubernetes/org#964]
### GitHub Username 
@verolop

### Organization you are requesting membership in 
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @alejandrox1
- @justaugustus 

### List of contributions to the Kubernetes project
- I'm part of the CI Signal team for the Kubernetes v1.16 release (shadowing)
- I'm part of sig-release and used to attend meetings for sig-testing as part of my former job

**Comment by justaugustus** [comment]
Enthusiastic +1 for Verónica! She's going to be a huge asset to the Release Team! :)

**Comment by alejandrox1** [comment]
SUPER MEGA +1

**Comment by justaugustus** [comment]
I've created #965 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
