### ISSUE TITLE
REQUEST: New membership for petr-muller

### ISSUE THREAD

**Issue by petr-muller** [kubernetes/org#968]
### GitHub Username
@petr-muller

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @stevekuznetsov
- @Katharine 
- @spiffxp 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/test-infra/pull/12301
https://github.com/kubernetes/test-infra/pull/12142
https://github.com/kubernetes/test-infra/pull/12024
https://github.com/kubernetes/test-infra/pull/11112
https://github.com/kubernetes/test-infra/pull/10119
https://github.com/kubernetes/test-infra/pull/10095
https://github.com/kubernetes/test-infra/pull/9386
https://github.com/kubernetes/test-infra/pull/9354
https://github.com/kubernetes/test-infra/pull/9137
https://github.com/kubernetes/test-infra/pull/9024
https://github.com/kubernetes/test-infra/pull/8558
- Issues responded to
- SIG projects I am involved with
sig-testing

**Comment by Katharine** [comment]
+1

**Comment by spiffxp** [comment]
+1 from sponsor

**Comment by stevekuznetsov** [comment]
+1 from this sponsor

**Comment by spiffxp** [comment]
Thanks for all of your contributions!

Once #969 that gets merged, you should get a membership invite notification.

Welcome to the project! 🎉

/meowvie
