### ISSUE TITLE
REQUEST: New membership for evillgenius75

### ISSUE THREAD

**Issue by evillgenius75** [kubernetes/org#971]
### GitHub Username
@evillgenius75

### Organization you are requesting membership in
@kubernetes
e.g. (at)kubernetes

### Requirements
- [ x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x ] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ c] I am actively contributing to 1 or more Kubernetes subprojects
- [x ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @kacole2 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with
SIG-Release

**Comment by justaugustus** [comment]
+1! Looking forward to working with you this cycle! :)

**Comment by nzoueidi** [comment]
Hey there @evillgenius75, thank you for all your contributions so far :)

I've created PR #973 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
