### ISSUE TITLE
REQUEST: New membership for odinuge

### ISSUE THREAD

**Issue by odinuge** [kubernetes/org#975]
### GitHub Username
@odinuge

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @BenTheElder 
- @oomichi 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pull/79493
- https://github.com/kubernetes/kubernetes/pull/78779
- https://github.com/kubernetes/kubernetes/pull/78611
- https://github.com/kubernetes/kubernetes/pull/78495
- https://github.com/kubernetes/kubernetes/pull/79560
- https://github.com/kubernetes/kubernetes/pull/79534
- https://github.com/kubernetes/kubernetes/pull/79531
- https://github.com/kubernetes/kubernetes/pull/79494
- https://github.com/kubernetes/kubernetes/pull/79241
- https://github.com/kubernetes/kubernetes/pull/79045
- https://github.com/kubernetes/kubernetes/pull/78769
- https://github.com/kubernetes/kubernetes/pull/78622
- https://github.com/containerd/cri/pull/1190
- https://github.com/kubernetes/kubernetes/pull/79075
- https://github.com/kubernetes/kubernetes/pull/79075
- https://github.com/kubernetes/kubernetes/pull/78884
- https://github.com/kubernetes/kubernetes/pull/78329
- https://github.com/kubernetes/kubernetes/pull/79502
- https://github.com/kubernetes/kubernetes/pull/79186
- https://github.com/kubernetes/kubernetes/pull/79287
- https://github.com/kubernetes/kubernetes/pull/78821
- https://github.com/kubernetes/kubernetes/issues/79454
- https://github.com/kubernetes/kubernetes/issues/79234
- https://github.com/kubernetes/kubernetes/issues/77169
- https://github.com/kubernetes/kubernetes/issues/79499
- https://github.com/kubernetes/kubernetes/issues/77103
- https://github.com/kubernetes/kubernetes/issues/78964

**Comment by BenTheElder** [comment]
+1, thank you!!

**Comment by oomichi** [comment]
+1 from me :-)

**Comment by mattjmcnaughton** [comment]
Thank you for your great work so far :)

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #985 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
