### ISSUE TITLE
REQUEST: New membership for @cpanato

### ISSUE THREAD

**Issue by cpanato** [kubernetes/org#979]
### GitHub Username
@cpanato

### Organization you are requesting membership in
kubernetes / release

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @idealhack 
- @justaugustus 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Acpanato+archived%3Afalse+org%3Akubernetes+
  - https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Acpanato+archived%3Afalse+org%3Akubernetes-sigs

- SIG projects I am involved with
 - sig-release

**Comment by idealhack** [comment]
+1

looking forward to working with you on release engineering :)

**Comment by pswica** [comment]
I don't think I'm qualified to give a +1, but @cpanato has already helped fix up k/release in a few ways. I really look forward to working with them

**Comment by nikhita** [comment]
+1

**Comment by justaugustus** [comment]
+1! Looking forward to working with you on Release Engineering! :)

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #985 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
