### ISSUE TITLE
REQUEST: New membership for josedonizetti

### ISSUE THREAD

**Issue by josedonizetti** [kubernetes/org#981]
### GitHub Username
@josedonizetti

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsor
- @tstromberg 
- @afbjorklund

### List of contributions to the Kubernetes project
- PRs reviewed / authored

   - https://github.com/kubernetes/minikube/pull/4308
   - https://github.com/kubernetes/minikube/pull/4323
   - https://github.com/kubernetes/minikube/pull/4328
   - https://github.com/kubernetes/minikube/pull/4331
   - https://github.com/kubernetes/minikube/pull/4334
   - https://github.com/kubernetes/minikube/pull/4343
   - https://github.com/kubernetes/minikube/pull/4344
   - https://github.com/kubernetes/minikube/pull/4355
   - https://github.com/kubernetes/minikube/pull/4379
   - https://github.com/kubernetes/minikube/pull/4380
   - https://github.com/kubernetes/minikube/pull/4381
   - https://github.com/kubernetes/minikube/pull/4385
   - https://github.com/kubernetes/minikube/pull/4398
   - https://github.com/kubernetes/minikube/pull/4399
   - https://github.com/kubernetes/minikube/pull/4401
   - https://github.com/kubernetes/minikube/pull/4591
   - https://github.com/kubernetes/minikube/pull/4593
   - https://github.com/kubernetes/minikube/pull/4611
   - https://github.com/kubernetes/minikube/pull/4612
   - https://github.com/kubernetes/minikube/pull/4630
   - https://github.com/kubernetes/minikube/pull/4631
   - https://github.com/kubernetes/minikube/pull/4632
   - https://github.com/kubernetes/minikube/pull/4641
   - https://github.com/kubernetes/minikube/pull/4642
   - https://github.com/kubernetes/minikube/pull/4644
   - https://github.com/kubernetes/minikube/pull/4645
  
- Issues responded to
  - https://github.com/kubernetes/minikube/issues/3771
  - https://github.com/kubernetes/minikube/issues/4249
  - https://github.com/kubernetes/minikube/issues/4069
  - https://github.com/kubernetes/minikube/issues/3581

- SIG projects I am involved with
  - sig-cluster-lifecycle/minikube

**Comment by medyagh** [comment]
+1 I sponsor  @josedonizetti  as well

**Comment by afbjorklund** [comment]
I sponsor @josedonizetti

**Comment by tstromberg** [comment]
I endorse @josedonizetti's membership request.

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #985 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
