### ISSUE TITLE
REQUEST: New membership for josephburnett

### ISSUE THREAD

**Issue by josephburnett** [kubernetes/org#983]
### GitHub Username
josephburnett

### Organization you are requesting membership in
kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @MaciekPytel
- @feiskyer 

### List of contributions to the Kubernetes project
- Contributed PR https://github.com/kubernetes/kubernetes/pull/79035 (Fix HPA feedback from writing status.replicas to spec.replicas)
- Contributed PR https://github.com/kubernetes/kubernetes/pull/79657 (Ignore unschedulable pods)
- Opened issue https://github.com/kubernetes/kubernetes/issues/79158 (Unscheduled Pods cause HPA to get stuck)
- Reviewed PR https://github.com/kubernetes/kubernetes/pull/78503 (Multiple metrics hpa)
- Reviewed KEP https://github.com/kubernetes/enhancements/pull/883 (Configurable scale velocity for HPA)
- Responded to issue https://github.com/kubernetes/kubernetes/issues/72775 (pod hpa would create extra pods during deployment rolling update)
- I am involved with the autoscaling SIG.

**Comment by MaciekPytel** [comment]
Big lgtm from me - Joe has been contributing to and relentlessly fixing bugs in HPA over the last few months. He's became the most active HPA contributor recently.

**Comment by nzoueidi** [comment]
Hey there @josephburnett, unfortunately @draveness cannot sponsor you for membership in the @kubernetes org as they are not an approver or/and reviewer. 

You should pick another eligible sponsor (that they are not goolger). Sponsors must be from multiple member companies.
Further details can be found here: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

Thanks.

**Comment by draveness** [comment]
+1

**Comment by feiskyer** [comment]
lgtm according to his excellent contributions of HPA.

**Comment by josephburnett** [comment]
@nzoueidi, @feiskyer has agreed to sponsor me.

**Comment by nzoueidi** [comment]
Hey there @josephburnett, thank you for all your contributions so far :)

I've created PR #990 to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
