### ISSUE TITLE
REQUEST: New membership for @amy

### ISSUE THREAD

**Issue by amy** [kubernetes/org#984]
### GitHub Username
@amy

### Organization you are requesting membership in
e.g. @kubernetes @kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @chuckha 
- @cblecker
- @dims 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/7
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/35
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/30
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/27
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/26
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/25
https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/16
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/798
https://github.com/kubernetes/k8s.io/pull/268
https://github.com/kubernetes-sigs/cluster-api/pull/854

- Issues responded to:
https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/15
https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/19
https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/29
https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/22
https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/9
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/795
https://github.com/kubernetes-sigs/cluster-api/issues/823

- SIG projects I am involved with: sig-cluster-lifecycle, sig-release

**Comment by chuckha** [comment]
Yes! Amy has helped significantly across various cluster-api owned projects (a subproject of sig-cluster-lifecycle)

+1!

**Comment by cblecker** [comment]
+1

Thanks for your help in wg-k8s-infra!

**Comment by dims** [comment]
+1 from me!

**Comment by nikhita** [comment]
+10000000000 :)

/pony party

**Comment by justaugustus** [comment]
+1! Looking forward to working with you on SIG Release! :)

**Comment by justaugustus** [comment]
Thanks so much for your contributions thus far!
I've created #985 to add you to the relevant org(s). Once that merges, you should receive an invite from our automation framework.

Welcome! :)
/assign
