### ISSUE TITLE
REQUEST: New membership for YoubingLi

### ISSUE THREAD

**Issue by YoubingLi** [kubernetes/org#987]
### GitHub Username
@YoubingLi

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @liggitt 
- @cblecker 

### List of contributions to the Kubernetes project
- PRs reviewed / authored

  kubernetes/kubernetes#72137
  kubernetes/kubernetes#73201
  kubernetes/kubernetes#75820
  kubernetes/kubernetes#76253
  kubernetes/kubernetes#77549
  kubernetes/kubernetes#77596
  kubernetes/kubernetes#77822
  kubernetes/kubernetes#78477

- Issues responded to

  kubernetes/kubernetes#74266
  kubernetes/kubernetes#75706
  kubernetes/kubernetes#76231
  kubernetes/kubernetes#76811
  kubernetes/kubernetes#76957
  kubernetes/kubernetes#77527
  kubernetes/kubernetes#77603
  kubernetes/kubernetes#78001
  kubernetes/kubernetes#78165

- SIG projects I am involved with

     cli
    scheduling
    testing

**Comment by liggitt** [comment]
+1

**Comment by nzoueidi** [comment]
Hey @cblecker do you have moment to sponsor @YoubingLi's org membership?

Thanks.

**Comment by cblecker** [comment]
+1 from me

**Comment by nzoueidi** [comment]
Hey there @YoubingLi, thank you for all your contributions so far :)

I've created PR #992  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
