### ISSUE TITLE
Creation of image-builder repository

### ISSUE THREAD

**Issue by timothysc** [kubernetes/org#988]
### New Repo, Staging Repo, or migrate existing
new repository

On July 2. 2019 sig-cluster-lifecycle approved the creation of an image-builder subproject.  The proposal can be found here: https://github.com/kubernetes/enhancements/pull/1102

### Requested name for new repository
image-builder

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@timothysc 
@justinsb 
@luxas 

### If not a staging repo, who should have write access
@timothysc 
@justinsb 
@luxas  
@moshloop 

### If not a staging repo, who should be listed as approvers in OWNERS
@timothysc 
@justinsb 
@luxas 
@moshloop 

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@timothysc 
@justinsb 
@luxas 

### What should the repo description be
Cross provider Kubernetes image building utility 

### What SIG and subproject does this fall under in sigs.yaml
sig-cluster-lifecycle

### Approvals
- [Proposal](https://github.com/kubernetes/enhancements/pull/1102)
- [Meeting Minutes](https://docs.google.com/document/d/1Gmc7LyCIL_148a9Tft7pdhdee0NBHdOfHS1SAF0duI4/edit#)

**Comment by akutz** [comment]
Hi @timothysc,

I was hoping to be involved in this. Nevertheless, I recommend using CAPV's augmentation of the CAPA process as the basis for the new repository. Please see https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/tree/master/build/images. Thanks!

**Comment by nikhita** [comment]
Created https://github.com/kubernetes-sigs/image-builder :tada: 

Also created:

- https://github.com/kubernetes/org/pull/989 - to add GitHub teams
- https://github.com/kubernetes/community/pull/3876 - to add the repo to sigs.yaml

Once both PRs merge, we can close this issue.

**Comment by nikhita** [comment]
This is done.
