### ISSUE TITLE
REQUEST: New membership for oke-py

### ISSUE THREAD

**Issue by oke-py** [kubernetes/org#991]
### GitHub Username
@oke-py

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nasa9084
- @MasayaAoyama

### List of contributions to the Kubernetes project
- PRs reviewed / authored
PRs of Kubernetes document modification
kubernetes/website#11529
kubernetes/website#11630
kubernetes/website#11694
kubernetes/website#12265
kubernetes/website#12557
kubernetes/website#13056
kubernetes/website#13421
kubernetes/website#14936
kubernetes/website#15159
kubernetes/website#15246
Translation PRs of Kubernetes document into Japanese
kubernetes/website#13153
kubernetes/website#13215
kubernetes/website#13228
kubernetes/website#13232
kubernetes/website#14116
kubernetes/website#14169
kubernetes/website#14488
kubernetes/website#14955
PRs of kubectl book modification
kubernetes/kubernetes#79845
- Issues responded to
- SIG projects I am involved with
kubernetes/sig-docs

**Comment by nasa9084** [comment]
+1
Thank you for your contribution :)

**Comment by MasayaAoyama** [comment]
+1
Thank you for your help!

**Comment by nzoueidi** [comment]
Hey there @oke-py, thank you for all your contributions so far :)

I've created PR #992  to add you to the Kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
