### ISSUE TITLE
REQUEST: New membership for ehashman

### ISSUE THREAD

**Issue by ehashman** [kubernetes/org#993]
### GitHub Username
@ehashman

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @brancz 
- @directxman12

### List of contributions to the Kubernetes project

- Metrics overhaul work
    - Coauthored a [sig-instrumentation KEP for improving k8s metrics usability](https://github.com/kubernetes/enhancements/blob/baca87088480254b26d0fdeb26303d7c51a20fbd/keps/sig-instrumentation/20181106-kubernetes-metrics-overhaul.md)
    - Updated cadvisor metric labels to meet instrumentation guidelines: https://github.com/kubernetes/kubernetes/pull/69099 (closed https://github.com/kubernetes/kubernetes/issues/66790)
    - Pending: deprecation of old cadvisor metric labels, to be coordinated with sig-node
- kube-state-metrics usability work
    - Tested kube-state-metrics release candidate performance improvements on large clusters https://github.com/kubernetes/kube-state-metrics/issues/257#issuecomment-408929692 https://github.com/kubernetes/kube-state-metrics/issues/257#issuecomment-449466592 https://github.com/kubernetes/kube-state-metrics/issues/498#issuecomment-443872447
    - Reported and added a workaround for broken in-cluster authentication for KSM 1.3+ https://github.com/kubernetes/kube-state-metrics/issues/543 https://github.com/kubernetes/kube-state-metrics/pull/549
- Other work in observability
    - Request for structured logging https://github.com/kubernetes/kubernetes/issues/69825
    - Gave an introductory talk on [how to monitor Kubernetes with CNCF components](https://hashman.ca/srecon-2019/)
- SIG projects I am involved with
    - [sig-instrumentation](https://groups.google.com/forum/#!forum/kubernetes-sig-instrumentation)
- Other
    - Program committee member for KubeCon/CloudNativeCon 2019 (Barcelona & San Diego)

**Comment by DirectXMan12** [comment]
:+1: from me!

**Comment by brancz** [comment]
:+1: from me as well!

**Comment by cblecker** [comment]
Thanks for your help with Kubernetes instrumentation and observability!

Invite will be sent out as soon as #994 merges. Welcome to @kubernetes! 🚀
