### ISSUE TITLE
Request admin permission for docs-l10n

### ISSUE THREAD

**Issue by nasa9084** [kubernetes/org#996]
### Organization or repository
kubernetes/website, docs-l10n

### Users affected
@nasa9084

### Describe the issue
I'm an owner of docs-ja project, to manage the project (rebase & force-push before PR to master), I need permission to the repository (I don't know why only I do not have the permission but other approvers for this project have...)

**Comment by nikhita** [comment]
@nasa9084 Please create a PR to add yourself to https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml#L167. That should give you the required permissions.

**Comment by nasa9084** [comment]
@nikhita Thank you for your direction. I have created.
