### ISSUE TITLE
REQUEST: New membership for @josiahbjorgaard

### ISSUE THREAD

**Issue by josiahbjorgaard** [kubernetes/org#999]
### GitHub Username
@josiahbjorgaard

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @xmudrii 
- @lachie83 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/79738, https://github.com/kubernetes/website/pull/15007, https://github.com/kubernetes/website/pull/14820
- Issues responded to
https://github.com/kubernetes/kubernetes/issues/50564, https://github.com/kubernetes/kubernetes/issues/77787
- SIG projects I am involved with
sig-release

**Comment by xmudrii** [comment]
+1

**Comment by nzoueidi** [comment]
Hey @josiahbjorgaard unfortunately @MikeSpreitzer can't sponsor your kubernetes org's membership. 
You need to find another eligible sponsor where they are approve and/or sponsor in the kubernetes org.

Thanks.

**Comment by josiahbjorgaard** [comment]
I edited to add @lachie83 for second sponsor

**Comment by lachie83** [comment]
+1

**Comment by lachie83** [comment]
cc @justaugustus

**Comment by justaugustus** [comment]
+1! Looking forward to working with you this cycle, @josiahbjorgaard!

**Comment by nzoueidi** [comment]
Hey there @josiahbjorgaard, thank you for all your contributions so far :)

I've created PR #1001 to add you to the kubernetes Org. Once that gets merged, you should get a membership invite notification.

Welcome to @kubernetes! 🎉

/assign
